### ISSUE TITLE
Cryptodredge Crypronightheavy not working

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#100]
Cryptodredge benchmark Crypronightheavy with good speed. but in real, it't not able to submit any shares.
So even if its showing good profit. but in real there are no shares submitted.

**Comment by RainbowMiner** [comment]
Hi, Cryptodredge has actually problems with submitting shares of both, CryptoNightV7 and CryptonightHeavy, to NiceHash. In the comeing release I will temporarily deactivate both, if NiceHash is at it's turn. Maybe the CryptoDredge developer supplies us with an updated version, as soon as it arrives, you will have it.
RBM

**Comment by RainbowMiner** [comment]
also #80 
New RainbowMiner v3.8.5.10 contains bugfixed CryptoDredge

**Comment by rinkal26783** [comment]
Thanks RM,
Cryptonightheavy is working fine with new version of CrytpoDredge.
But, CryptonightV7 is not saved to mining list even after sucessfull benchmark.
