### ISSUE TITLE
Cannot convert value to type "System.Int32"

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1003]
Hi @RainbowMiner , saw this on the console, what does it means? Running on the latest version.

![rbminer](https://user-images.githubusercontent.com/3217740/82736298-3e3d2200-9d5b-11ea-85bd-7989f3cc8792.png)
[debug_2020-05-24.zip](https://github.com/RainbowMiner/RainbowMiner/files/4672173/debug_2020-05-24.zip)

**Comment by RainbowMiner** [comment]
Thank you for reporting. This does no harm, but points to a change in the 6Block-API. I will check this.

**Comment by RainbowMiner** [comment]
Found and fixed.
