### ISSUE TITLE
Extra column in Activity page

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1005]
Please can you add the "for you" "for dev" column from the main Dashboard page into the Activity page? When looking at what my cards have been mining, I want to be able to filter out the devfee activity.

**Comment by RainbowMiner** [comment]
Sure, good point. I'll add this.

**Comment by samdave123** [comment]
Bump it's been 2 months and this would be really useful to me. I'm running a long stability test on Ethash so it's useful to know if it's stopped because of the devfee or because something else caused it to. The activity page and CSV is so useful, but it's confusing when there's devfee activity that isn't easily recognisable.

**Comment by RainbowMiner** [comment]
Ah, thank you. I forgot about this.

**Comment by samdave123** [comment]
Added and works well
