### ISSUE TITLE
New Servers on f2pool

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1008]
I can see that there are no eu f2pool servers that have been set up, but the earning estimates seem to be off. I'm getting £80 profit per day per rig. Maybe there's a mismatch somewhere...

![image](https://user-images.githubusercontent.com/42582444/82847552-ac622000-9ee6-11ea-9fe8-a90f12126d63.png)

**Comment by acos0874** [comment]
It looks like the grin31 servers are being matched to grin29

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I had a wrong assignment in this module.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/83047682-9b2d2680-a040-11ea-9e05-6ebc1637cf34.png)
I think there is still an issue, because when i enable f2pool the only pool that shows is the BTC one.

**Comment by acos0874** [comment]
Nevermind, it was an error in my pools config.

**Comment by RainbowMiner** [comment]
Good to hear. I really had a quick moment of shock :)
