### ISSUE TITLE
C32 Gminer in Windows

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1012]
It seems this works in Windows with the 6gb solver. I haven't tested the other algos.

**Comment by RainbowMiner** [comment]
Oh! Which miner did you test?

**Comment by acos0874** [comment]
Gminer. It automatically selected the 6gb solver. I tested c31 and it
didn't work.

>

**Comment by RainbowMiner** [comment]
That is interesting. I'll try.

**Comment by RainbowMiner** [comment]
Cool. Works. But it looks like, Gminer is oversensitive to memory overclocking on Cuckatoo32. I had many crashes with values greater than +200 and best results with -500 on GTX1070 8GB

**Comment by acos0874** [comment]
Yes my testing showed -1000 mem was best
null

**Comment by RainbowMiner** [comment]
Done, see commit 49f3eb355d6b2a80e9a7b36108d7b931f2cb3817
