### ISSUE TITLE
Pause mining and updates

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1014]
Hi, someone on Discord had a good suggestion to have the pause function also pause updates, to prevent the update running and interrupting gaming etc....

Please can this be implemented?

**Comment by samdave123** [comment]
Currently, the default behaviour is to update when paused and then start mining.

**Comment by RainbowMiner** [comment]
Yes, very good idea. I'll add this.

**Comment by RainbowMiner** [comment]
I have added parameter "EnableUpdateDuringPause" to config.txt: set to 1 if you want RainbowMiner to be updated automatically, even if it is paused [default=1] (issue #1014)

**Comment by RainbowMiner** [comment]
I have set it to "1" by default, because miners, that use server/client configuration often have a dedicated server running in pause mode. If you want to disable the updated during pause, set the value to "0"

**Comment by samdave123** [comment]
> 
> 
> I have set it to "1" by default, because miners, that use server/client configuration often have a dedicated server running in pause mode. If you want to disable the updates during pause, set the value to "0"

Perhaps you could set a different default on servers than on clients?

**Comment by RainbowMiner** [comment]
Ha. Good idea. That might eventually do the trick.
