### ISSUE TITLE
WARNING: Could not set process priority/affinity: Cannot find a process with the process identifier 17472.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1018]
PS>TerminatingError(Get-Process): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find a process with the process identifier 17472."
WARNING: Could not set process priority/affinity: Cannot find a process with the process identifier 17472.

[debug_2020-05-31.zip](https://github.com/RainbowMiner/RainbowMiner/files/4708180/debug_2020-05-31.zip)

**Comment by RainbowMiner** [comment]
This message will be displayed, in case a miner couldn't be started at all. Do you remember by any chance which miner caused the trouble?

**Comment by paulpoco** [comment]
No I only see it at the very begining of running RBM
