### ISSUE TITLE
[Q&A] Mrr auto rigs

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1019]
Nice update 👍

I have a question about mrr auto rig create when it goes live. Will the prices be set across algos or just set per algo? 

So for example if x16r is paying £2 for my rigs and grin is paying £10, I don't want to get on an x16r rental even if it is paying +50% at £3.

**Comment by RainbowMiner** [comment]
The automatic price will always be "Your rig's profitability per day" x "PriceFactor". It doesn't matter which algorithm, you will always sell your rig for exactly that number :)

**Comment by acos0874** [comment]
Thanks. Will algos need to be benchmarked on another active pool in order for them to appear in MRR?

**Comment by RainbowMiner** [comment]
> Thanks. Will algos need to be benchmarked on another active pool in order for them to appear in MRR?

Currently, yes. We need the numbers, first.
Since you ask, I will now make some crosschecks, which algorithms would be covered using the most popular autoexchange pools - and which are left out.

**Comment by acos0874** [comment]
This is live in the latest update?

**Comment by RainbowMiner** [comment]
> This is live in the latest update?

Actually, yes. I had it tested over the past 24h - release v4.5.7.7 has all MRR automation features active (you will have to set "EnableAutoCreate": "1", for auto creation and/or "EnableAutoUpdate": "1", for automatic price and hashrate updates in pools.config.txt)

**Comment by acos0874** [comment]
Should I set up separate keys for each of my rigs?

**Comment by RainbowMiner** [comment]
> Should I set up separate keys for each of my rigs?

This is recommended, because MRR uses incremental timestamps to check, if a request is valid.

**Comment by RainbowMiner** [comment]
Also, make sure to check "yes" on "Manage Rigs" for your API keys.

![image](https://user-images.githubusercontent.com/39437538/83646294-c02b1780-a5b3-11ea-8aa3-c88d27692bee.png)

**Comment by acos0874** [comment]
Should I give separate names for the rigs? At the moment I'm only getting 1 rig per algo and the hashrates keep changing. Sometimes it's combining all 3 rigs together.

**Comment by acos0874** [comment]
"MiningRigRentals": {
    "EnableMining": "0",
    "EnableAutoCreate": "1",
    "EnableAutoPrice": "1",
    "EnableMinimumPrice": "1",
    "PriceBTC": "0",
    "PriceFactor": "2.0",
    "PriceCurrencies": "BTC",
    "Title": "%algorithm% mining",
    "Description": "Autostart mining with RainbowMiner (https://rbminer.net) on Windows. This rig is idle and will activate itself, as soon, as you rent it. %workername%",
    "Worker": "$WorkerName",
    "Penalty": "0",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "0",
    "CoinSymbolPBM": "",
    "DataWindow": "",
    "StatAverage": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "",
    "User": "xx",
    "API_Key": "xx",
    "API_Secret": "xx",
    "AutoCreateMinProfitPercent": "50",
    "AutoCreateMinCPUProfitBTC": "0.00001",
    "AutoCreateMaxMinHours": "24",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "1",
    "AutoPriceModifierPercent": "0",
    "MinHours": "3",
    "MaxHours": "24"

**Comment by RainbowMiner** [comment]
I would recommend to design your titles a bit, so that you get more visibility - and of course different titles on different rigs. Or you add "%rigid%" to your title. It's a unique 4-letter id.

**Comment by acos0874** [comment]
Can I use $workername in the title?

"Title": "$workername %algorithm% mining",

**Comment by RainbowMiner** [comment]
A good starting point is 
`%algorithm% mining with RainbowMiner rig %rigid%`

Make sure it contains %algorithm% and either %rigid% or %workername%
Values will be substituted like that:
- %algorithm% with algorithm
- %rigid% with an unique 4-char rigid
- %workername% with the workername
- %type% with either CPU or GPU
- %typecpu% with CPU or empty
- %typegpu% with GPU or empty

**Comment by acos0874** [comment]
OK thanks. Also I'm getting some unusual hashrates that don't seem to match up with any of my rigs on x16rv2 and equihash144. I'll give it some type and report back

**Comment by acos0874** [comment]
Ah I realised I put the mrr key in the pools config insteadof the main config

**Comment by RainbowMiner** [comment]
> "User": "xx",
> "API_Key": "xx",
> "API_Secret": "xx",

should be set in pools.config.txt

**Comment by acos0874** [comment]
Oh wait sorry that is right. Can you remind me the correct string to exclude changes to the keys in the pools config?

**Comment by acos0874** [comment]
I think I found it..


There is a missing a "t" at the end of pools:MiningRigRentals:API_Secre in the server's config.txt:

pools:MiningRigRentals:API_Key,pools:MiningRigRentals:API_Secre,
.. also, there is a bug in the core. I will fix it now.

**Comment by acos0874** [comment]
Hmm the exclude variables seem to be working but the rigs aren't updating.

**Comment by acos0874** [comment]
Are you running your rigs successful in server-client mode or are you using standalone mode?

**Comment by acos0874** [comment]
OK another of my rigs seemed to come online. Is there a time limit on how long it takes for a rig to connect to the API to prevent too many tries?

**Comment by acos0874** [comment]
Ok all rigs seem to be online with the correct hashrates thank you. The only issue I can see is once the rigs have been created, the titles don't seem to update themselves with any changes I make. Will this happen after a time or do I need to delete and recreate the rigs?

**Comment by acos0874** [comment]
It seems like auto update isn't working on the price either.

**Comment by RainbowMiner** [comment]
> don't know if this is intentional, but the rigs only seem to autopopulate when I restart RBM.

There is indeed a timer - the MRR updates are started every hour. And for now, there are no updates of the titles (I think I will add another "EnableUpdateTitle" parameter asap). My initial thought has been to only send the title during initial creation, so that you can change them to your likes online, afterwards.

**Comment by acos0874** [comment]
Thanks. I would just prefer full automation so I can change the title string on my server rig and then it'll make any updates to all rigs on the website.

**Comment by RainbowMiner** [comment]
> Thanks. I would just prefer full automation so I can change the title string on my server rig and then it'll make any updates to all rigs on the website.

Ok, I am on the way adding that new parameter now.

**Comment by acos0874** [comment]
Also, is the price factor multiplying by the profit or the revenue?

**Comment by RainbowMiner** [comment]
> Also, is the price factor multiplying by the profit or the revenue?

It's the revenue

**Comment by acos0874** [comment]
Slight side note. I'm trying to enable more algos, but setting a penalty on f2pool doesn't seem to be applied to the price for some reason.

**Comment by RainbowMiner** [comment]
commit 0e5db3802a8af0bdb57deb817fe9887fdb3172a3
- add parameter "EnableUpdateTitle":  Enable automatic updating of rig titles (disable, if you prefer to edit your rig titles online at MRR) [default=1]

**Comment by acos0874** [comment]
Penalties also not working on hellominer pool

**Comment by acos0874** [comment]
Still can't get the penalties to show on the pools. Algorithm based penalties seem to be working fine. I have an 8% penalty on eth and 30% penalty on hellominer pool...

```
Algorithm: "Ethash"

Algorithm0: "Ethash"

CoinName: "Ethereum"

CoinSymbol: "ETH"

Currency: "ETH"

Price: 1.702e-12

StablePrice: 1.699991469074812e-12

MarginOfError: 0.0018534406551234915

Protocol: "stratum+tcp"

Host: "us1.hellominer.com"

Port: 1100

User: "0xF0810400343c6551A56B15xx.{workername:agnus}"

Pass: "x"

Region: "US"

SSL: false

Updated: "2020-06-03T18:56:09.2017483Z"

PoolFee: 0

DataWindow: "estimate_current"

Workers: 64

Hashrate: 26414649109.7088

EthMode: "ethproxy"

WTM: true

Name: "Hellominer"

Penalty: 8

PenaltyFactor: 0.92

Disabled: false

HasMinerExclusions: false

Price_Bias: 0

Price_Unbias: 0

Wallet: "0xF0810400343c6551A56B15487CfA1e453eE71Ae3"

Worker: "{workername:agnus}"

Email: null

tEnabled: true

tAlgorithm: "Ethash"

tCoin: "ETH"

tErrorRatio: "-"

```

**Comment by Yamanipanuchi** [comment]
The API key, Doesn't it sync across multiple devices in the server/client setup? How do we stop this from happening.. Right now I am only setting up one rig so it should not be an issue. But I am going to guess it will replicate to other rigs in the same group? Right?

**Comment by RainbowMiner** [comment]
> The API key, Doesn't it sync across multiple devices in the server/client setup? 

Yes, it does. But it can be avoided. Put API_Key and API_Secret on your client's "ExcludeServerConfigVars" list in config.txt
Just add `pools:MiningRigRentals:API_Key` and `pools:MiningRigRentals:API_Secret` to the list.

`"ExcludeServerConfigVars": "APIAuth,APIPassword,APIPort,APIUser,CPUMiningAffinity,CPUMiningThreads,DeviceName,EnableServerConfig,ExcludeDeviceName,ExcludeServerConfigVars,GPUMiningAffinity,GroupName,LinuxDisplay,LinuxXAuthority,MSIApath,NVSMIpath,Proxy,RunMode,ServerConfigName,ServerName,ServerPassword,ServerPort,ServerUser,StartPaused,WorkerName,pools:MiningRigRentals:API_Key,pools:MiningRigRentals:API_Secret",`

**Comment by acos0874** [comment]
Sent you a tip to your BTC wallet

**Comment by astronyu** [comment]
I've been asking for this feature previously and didn't even realized it was already implemented. Well done @RainbowMiner !
A question, for the title is it possible to add icons? Something like this >> 🚀⛏Avg 130 MH/s  💲💰

Also, is there a way to automatically extend the rental X hour for every 24 hours rented?

**Comment by RainbowMiner** [comment]
> A question, for the title is it possible to add icons? Something like this >> 🚀⛏Avg 130 MH/s 💲💰

Good question! Actually, it should be possible. I'll find out.

> Also, is there a way to automatically extend the rental X hour for every 24 hours rented?

Not yet, but I am working on it.
