### ISSUE TITLE
Issue: XMR-Stak runs multiple instances

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#102]
XMR-STAK is a hard one because it will run cpu and gpu bench at the same time causing mem alloc hoc error on gpu. If XMR-stak is going to bench cpu and gpu together, they should somehow open as one instance not 2 or it will fail. My only logical suggestion would be if cpu was going to be mined then just exclude xmr-stak and let xmrig do the job. Another point is as you can see the configurable dev fee for xmr-stak is still in there to.

![image](https://user-images.githubusercontent.com/42227809/45040108-0c7da800-b01a-11e8-9f54-8853f2e0c149.png)

**Comment by RainbowMiner** [comment]
Ya. I will think about a solution to exclude them against each other. And - disable the devfee.
RBM

**Comment by Byrd1083** [comment]
Yay!
