### ISSUE TITLE
Rig with AMD and Nvidia

### ISSUE THREAD

**Issue by Antoninich** [RainbowMiner/RainbowMiner#1020]
I have rig with 2 nvidia cards and 2 amd card.
![15](https://user-images.githubusercontent.com/57628432/83449383-2f8df380-a45c-11ea-9933-5eabf44524c6.PNG)
I found a couple of problems.
1) Wildrig miner sets the parameter "--opencl-platform 0", but for AMD --opencl-platform is 1
`Starting miner (WildRig-GPU#02-GPU#03): 'C:\RainbowMiner\Bin\AMD-WildRig\wildrig.exe --api-port $mport --algo kawpow -o stratum+tcp://kawpow.mine.zergpool.com:3638 -u  -p F4,c=XMR -r 4 -R 10 --send-stale --donate-level 1 --multiple-instance --opencl-devices 0,1 --opencl-platform 0 --opencl-threads auto --opencl-launch auto'`
2) New lolminer for both (lolminer-GPU#00-GPU#01) and (lolminer-GPU#02-GPU#03) sets the parameter --devices 0,1, but the correctly for (lolminer-GPU#00-GPU#01) is --devices 0,1 and for (lolminer-GPU#02-GPU#03) is --devices 2,3
`Benchmarking miner (lolminer-GPU#00-GPU#01): 'C:\RainbowMiner\Bin\Equihash-lolMiner\lolMiner.exe --pool grincuckatoo31.eu.nicehash.com --port 3372 --user .F4 --pass x --devices 0,1 --apiport $mport --tls 0 --digits 2 --longstats 60 --shortstats 5 --connectattempts 3 --coin GRIN-C31'`
`Benchmarking miner (lolminer-GPU#02-GPU#03): 'C:\RainbowMiner\Bin\Equihash-lolMiner\lolMiner.exe --pool grincuckatoo31.eu.nicehash.com --port 3372 --user .F4 --pass x --devices 0,1 --apiport $mport --tls 0 --digits 2 --longstats 60 --shortstats 5 --connectattempts 3 --coin GRIN-C31'`

**Comment by RainbowMiner** [comment]
Thank you for reporting this! I will take care of it asap.

**Comment by RainbowMiner** [comment]
Could you eventually start "GPUTest.bat" in RainbowMiner folder, once, and upload the resulting "gputestresult.txt" here?

**Comment by Antoninich** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/4715896/gputestresult.txt)

**Comment by RainbowMiner** [comment]
Ok, super. The Lolminer problem is solved. Leaves us the Wildrig platform problem.
Could you open http://localhost:4000/alldevices in your browser and upload the result?

**Comment by RainbowMiner** [comment]
.. also, if you look into the `.\Bin\AMD-Wildrig` folder, there is a `print-devices.bat` - please run it and show me the result.

**Comment by Antoninich** [comment]
![19](https://user-images.githubusercontent.com/57628432/83506807-538b1c80-a4d0-11ea-93ae-dd78d60e277d.PNG)
![18](https://user-images.githubusercontent.com/57628432/83506810-5423b300-a4d0-11ea-84da-80fc396109e3.PNG)

**Comment by RainbowMiner** [comment]
Sorry to bother you again, but I'ld need the JSON results of the exact url, not the .html version:  http://localhost:4000/alldevices

**Comment by Antoninich** [comment]
Ok.

[alldevices.txt](https://github.com/RainbowMiner/RainbowMiner/files/4716390/alldevices.txt)

**Comment by RainbowMiner** [comment]
Ah!! Thank you. I found the WildRig problem.

**Comment by RainbowMiner** [comment]
So, the Wildrig problem is eventually solved - but there remains one chance that I have missed out something. To be sure: could you eventually upload your `.\Config\miners.config.txt` config file?

**Comment by Antoninich** [comment]
Now Wildrig is worked. Thanks.
[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4717615/miners.config.txt)
