### ISSUE TITLE
Current power draw in Dashboard

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1023]
It's currently a bit awkward to know the current power draw. I have to add up each device group then add the base offset and the percentage offset to get a total figure. 

I infrequently check this to compare against my smart plug to ensure my offsets are reasonably accurate and it's a bit of a hassle doing the calculation manually.

I also like to check this figure to see how much heat output I'm getting which is important to maintain a comfortable ambient temperature in my flat.

I think this is such an important figure that it merits being on the main dashboard display, perhaps alongside earnings and uptime?

![image](https://user-images.githubusercontent.com/56473344/83515318-12ddd400-a4cd-11ea-8ffb-7ada2f2be9ae.png)

**Comment by RainbowMiner** [comment]
I'll get it there :)

**Comment by samdave123** [comment]
> 
> 
> I'll get it there :)

Thank you. I don't know whether you think it's best to have one figure for the total calculation, two figures with one just for the GPUs and then another for GPUs+offset?

**Comment by RainbowMiner** [comment]
Added.
![image](https://user-images.githubusercontent.com/39437538/83655150-57956800-a5be-11ea-86d1-e88715d3605a.png)

**Comment by samdave123** [comment]
So useful, thank you!

**Comment by samdave123** [comment]
This seems to be using benchmarked power consumption and not the current device power consumption. Current device power consumption would probably make more sense.

**Comment by samdave123** [comment]
It works well enough.
