### ISSUE TITLE
Cuckocycle on f2pool

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1025]
There seems to be a problem with AE on f2pool. 

 --server ae-eu.f2pool.com --port 7898 

It gives an error in the miner of 'no such host found'

**Comment by RainbowMiner** [comment]
Strange, it should work, since F2pool announces this host as valid.
![image](https://user-images.githubusercontent.com/39437538/83620085-1e90cf80-a58d-11ea-81f6-31ef969dabac.png)
.. I will temporarily deactivate the ae-eu host address on F2pool.

**Comment by acos0874** [comment]
Yea I checked and found the same thing. Really odd.

**Comment by RainbowMiner** [comment]
Since F2pool runs through the rbminer.net proxy, I could easily add ping checks - so from now on, all F2pool urls, that reach a RainbowMiner instance are live and active.
