### ISSUE TITLE
Pool Monitoring

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1027]
Just had a few crashes whilst I was running. 2 rigs, both on C29m on nicehash. It gave me an idea, not an urgent suggestion but just an idea for future development.

With the new notification emails, maybe there could be a page the monitoring website that keeps a track when there are common problems, and identifies a pool as problematic.

**Comment by RainbowMiner** [comment]
That's actually a smart idea. I'll think about it.
