### ISSUE TITLE
Localhost Balances

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1028]
I've noticed this for sometime now. Localhost on my server does not update the balances unless I stop the script and Re-start it. 

I've been showing the same balances for several weeks now, even after several payouts.
[debug_2020-06-03.zip](https://github.com/RainbowMiner/RainbowMiner/files/4725312/debug_2020-06-03.zip)

**Comment by RainbowMiner** [comment]
Interesting! I'll check it.
