### ISSUE TITLE
Pool Penalties

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1029]
Thought I'd start a new issue here. Can someone please confirm whether or not their pool penalties are working?

I don't know if it's related to the recent update, but I can't get penalties to apply to any pool. I have a 20% penalty set for zerg in the pools.config

![image](https://user-images.githubusercontent.com/42582444/83678978-84557980-a5d6-11ea-9ba5-f142431a202a.png)

**Comment by RainbowMiner** [comment]
I'll have a look.

**Comment by RainbowMiner** [comment]
Wow, nice finding! Actually, a bug. Don't know, how it got there. Thanks for reporting this to quickly.
