### ISSUE TITLE
Issue: Just updated now all excluded miners are benching.

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#103]
I have excluded excavator along with many others. Since latest update, all excluded miners are bench marking causing havoc.

**Comment by Byrd1083** [comment]
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2349185/config.txt)

**Comment by Byrd1083** [comment]
![image](https://user-images.githubusercontent.com/42227809/45040409-cc6af500-b01a-11e8-813c-e4bd23b34245.png)

**Comment by RainbowMiner** [comment]
8-| oh, this should not happen. Will check at once.
RBM

**Comment by RainbowMiner** [comment]
Would you send the latest Logs\Rainbowminer_2018_09_04.txt, as well, please?

**Comment by RainbowMiner** [comment]
Ah: found it. You are missing a "," in the config.txt, between Fireice and Excavator1.4.4

"Excavator,Firei**ceExc**avator1.4.4,Eminer,Cast,CpuminerJayddeeAvx2sha,CcminerTpruvotx64,CpuminerTpruvotCore2,CpuminerTpruvotCorei7"

**Comment by Byrd1083** [comment]
I see, my bad.
