### ISSUE TITLE
F2pool Connection Problems

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1030]
Still getting connection problems. This time with eth and hns.

**Comment by RainbowMiner** [comment]
Too bad. It seems they have some trouble with their non-asian proxies. I'll try to figure out, how to detect these.

**Comment by acos0874** [comment]
Thanks. I hope the eu pools can start working because hopefully I'll get less rejected shares.

**Comment by RainbowMiner** [comment]
I run the ping test script every 5 minutes. So, as soon as the servers are back up again, RainbowMiner will pick them up.
