### ISSUE TITLE
Weird error at startup

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1034]
I am getting this error when I start RBM

![image](https://user-images.githubusercontent.com/56473344/83938820-90585b80-a7cf-11ea-9d8b-37e6ddfcf307.png)

**Comment by RainbowMiner** [comment]
That's a strange one, you are right. Could you eventually create a Debug file and upload it here?

**Comment by RainbowMiner** [comment]
What would help a lot, is an overview over the current device objects. Just click http://localhost:4000/alldevices (or enter http://<your.machines.ip.address>:4000/alldevices in browser command line). Then post the result (should be in JSON format) here.

**Comment by samdave123** [comment]
[
    {
        "Name":  "GPU#00",
        "Index":  0,
        "PlatformId":  0,
        "PlatformId_Index":  0,
        "Type_PlatformId_Index":  0,
        "Vendor":  "NVIDIA",
        "Vendor_Name":  "NVIDIA Corporation",
        "Vendor_Index":  0,
        "Type_Vendor_Index":  0,
        "Type":  "Gpu",
        "Type_Index":  0,
        "Type_Mineable_Index":  0,
        "OpenCL":  {
                       "DeviceIndex":  0,
                       "Name":  "GeForce GTX 1660 Ti",
                       "Type":  "Gpu",
                       "Vendor":  "NVIDIA Corporation",
                       "GlobalMemSize":  6442450944,
                       "MaxComputeUnits":  24,
                       "PlatformVersion":  "OpenCL 1.2 CUDA 10.1.120",
                       "DriverVersion":  "432.00",
                       "PCIBusId":  "01:00",
                       "CardId":  -1
                   },
        "Model":  "GTX1660Ti",
        "Model_Base":  "GTX1660Ti",
        "Model_Name":  "GeForce GTX 1660 Ti",
        "InstanceId":  "PCI\\VEN_10DE\u0026DEV_2182\u0026SUBSYS_3FC41458\u0026REV_A1\\4\u002625438C51\u00260\u00260008",
        "CardId":  -1,
        "Bus":  1,
        "GpuGroup":  "",
        "Data":  {
                     "AdapterId":  0,
                     "Utilization":  100,
                     "UtilizationMem":  96,
                     "Clock":  975,
                     "ClockMem":  6351,
                     "FanSpeed":  35,
                     "Temperature":  54,
                     "PowerDraw":  67.43,
                     "PowerLimit":  160,
                     "PowerLimitPercent":  100,
                     "PowerMaxLimit":  200,
                     "PowerDefaultLimit":  160,
                     "Pstate":  "P2",
                     "Method":  "smi"
                 },
        "DataMax":  {
                        "Clock":  975,
                        "ClockMem":  6600,
                        "Temperature":  57,
                        "FanSpeed":  35,
                        "PowerDraw":  67.82
                    }
    },
    {
        "Name":  "GPU#01",
        "Index":  1,
        "PlatformId":  0,
        "PlatformId_Index":  1,
        "Type_PlatformId_Index":  1,
        "Vendor":  "NVIDIA",
        "Vendor_Name":  "NVIDIA Corporation",
        "Vendor_Index":  1,
        "Type_Vendor_Index":  1,
        "Type":  "Gpu",
        "Type_Index":  1,
        "Type_Mineable_Index":  1,
        "OpenCL":  {
                       "DeviceIndex":  1,
                       "Name":  "GeForce GTX 1660 Ti",
                       "Type":  "Gpu",
                       "Vendor":  "NVIDIA Corporation",
                       "GlobalMemSize":  6442450944,
                       "MaxComputeUnits":  24,
                       "PlatformVersion":  "OpenCL 1.2 CUDA 10.1.120",
                       "DriverVersion":  "432.00",
                       "PCIBusId":  "02:00",
                       "CardId":  -1
                   },
        "Model":  "GTX1660Ti",
        "Model_Base":  "GTX1660Ti",
        "Model_Name":  "GeForce GTX 1660 Ti",
        "InstanceId":  "PCI\\VEN_10DE\u0026DEV_2182\u0026SUBSYS_3FC51458\u0026REV_A1\\4\u002614EC8C8B\u00260\u002600E0",
        "CardId":  -1,
        "Bus":  2,
        "GpuGroup":  "",
        "Data":  {
                     "AdapterId":  0,
                     "Utilization":  100,
                     "UtilizationMem":  96,
                     "Clock":  990,
                     "ClockMem":  6351,
                     "FanSpeed":  34,
                     "Temperature":  54,
                     "PowerDraw":  64.69,
                     "PowerLimit":  140,
                     "PowerLimitPercent":  100,
                     "PowerMaxLimit":  200,
                     "PowerDefaultLimit":  140,
                     "Pstate":  "P2",
                     "Method":  "smi"
                 },
        "DataMax":  {
                        "Clock":  990,
                        "ClockMem":  6600,
                        "Temperature":  56,
                        "FanSpeed":  35,
                        "PowerDraw":  65.31
                    }
    },
    {
        "Name":  "GPU#02",
        "Index":  2,
        "PlatformId":  0,
        "PlatformId_Index":  2,
        "Type_PlatformId_Index":  2,
        "Vendor":  "NVIDIA",
        "Vendor_Name":  "NVIDIA Corporation",
        "Vendor_Index":  2,
        "Type_Vendor_Index":  2,
        "Type":  "Gpu",
        "Type_Index":  2,
        "Type_Mineable_Index":  2,
        "OpenCL":  {
                       "DeviceIndex":  2,
                       "Name":  "GeForce GTX 1660 Ti",
                       "Type":  "Gpu",
                       "Vendor":  "NVIDIA Corporation",
                       "GlobalMemSize":  6442450944,
                       "MaxComputeUnits":  24,
                       "PlatformVersion":  "OpenCL 1.2 CUDA 10.1.120",
                       "DriverVersion":  "432.00",
                       "PCIBusId":  "03:00",
                       "CardId":  -1
                   },
        "Model":  "GTX1660Ti",
        "Model_Base":  "GTX1660Ti",
        "Model_Name":  "GeForce GTX 1660 Ti",
        "InstanceId":  "PCI\\VEN_10DE\u0026DEV_2182\u0026SUBSYS_3FC51458\u0026REV_A1\\4\u00267D7BB99\u00260\u002600E5",
        "CardId":  -1,
        "Bus":  3,
        "GpuGroup":  "",
        "Data":  {
                     "AdapterId":  0,
                     "Utilization":  100,
                     "UtilizationMem":  97,
                     "Clock":  900,
                     "ClockMem":  6351,
                     "FanSpeed":  34,
                     "Temperature":  52,
                     "PowerDraw":  62.02,
                     "PowerLimit":  140,
                     "PowerLimitPercent":  100,
                     "PowerMaxLimit":  200,
                     "PowerDefaultLimit":  140,
                     "Pstate":  "P2",
                     "Method":  "smi"
                 },
        "DataMax":  {
                        "Clock":  900,
                        "ClockMem":  6600,
                        "Temperature":  56,
                        "FanSpeed":  37,
                        "PowerDraw":  62.08
                    }
    },
    {
        "Name":  "GPU#03",
        "Index":  3,
        "PlatformId":  0,
        "PlatformId_Index":  3,
        "Type_PlatformId_Index":  3,
        "Vendor":  "NVIDIA",
        "Vendor_Name":  "NVIDIA Corporation",
        "Vendor_Index":  3,
        "Type_Vendor_Index":  3,
        "Type":  "Gpu",
        "Type_Index":  3,
        "Type_Mineable_Index":  3,
        "OpenCL":  {
                       "DeviceIndex":  3,
                       "Name":  "GeForce GTX 1070 Ti",
                       "Type":  "Gpu",
                       "Vendor":  "NVIDIA Corporation",
                       "GlobalMemSize":  8589934592,
                       "MaxComputeUnits":  19,
                       "PlatformVersion":  "OpenCL 1.2 CUDA 10.1.120",
                       "DriverVersion":  "432.00",
                       "PCIBusId":  "04:00",
                       "CardId":  -1
                   },
        "Model":  "GTX1070Ti",
        "Model_Base":  "GTX1070Ti",
        "Model_Name":  "GeForce GTX 1070 Ti",
        "InstanceId":  "PCI\\VEN_10DE\u0026DEV_1B82\u0026SUBSYS_1B8210DE\u0026REV_A1\\4\u002615500B30\u00260\u002600E6",
        "CardId":  -1,
        "Bus":  4,
        "GpuGroup":  "",
        "Data":  {
                     "AdapterId":  0,
                     "Utilization":  100,
                     "UtilizationMem":  100,
                     "Clock":  1480,
                     "ClockMem":  4303,
                     "FanSpeed":  32,
                     "Temperature":  65,
                     "PowerDraw":  91.01,
                     "PowerLimit":  180,
                     "PowerLimitPercent":  100,
                     "PowerMaxLimit":  217,
                     "PowerDefaultLimit":  180,
                     "Pstate":  "P2",
                     "Method":  "smi"
                 },
        "DataMax":  {
                        "Clock":  1493,
                        "ClockMem":  4498,
                        "Temperature":  65,
                        "FanSpeed":  62,
                        "PowerDraw":  91.01
                    }
    },
    {
        "Name":  "GPU#04",
        "Index":  4,
        "PlatformId":  0,
        "PlatformId_Index":  4,
        "Type_PlatformId_Index":  4,
        "Vendor":  "NVIDIA",
        "Vendor_Name":  "NVIDIA Corporation",
        "Vendor_Index":  4,
        "Type_Vendor_Index":  4,
        "Type":  "Gpu",
        "Type_Index":  4,
        "Type_Mineable_Index":  4,
        "OpenCL":  {
                       "DeviceIndex":  4,
                       "Name":  "GeForce GTX 1070 Ti",
                       "Type":  "Gpu",
                       "Vendor":  "NVIDIA Corporation",
                       "GlobalMemSize":  8589934592,
                       "MaxComputeUnits":  19,
                       "PlatformVersion":  "OpenCL 1.2 CUDA 10.1.120",
                       "DriverVersion":  "432.00",
                       "PCIBusId":  "05:00",
                       "CardId":  -1
                   },
        "Model":  "GTX1070Ti",
        "Model_Base":  "GTX1070Ti",
        "Model_Name":  "GeForce GTX 1070 Ti",
        "InstanceId":  "PCI\\VEN_10DE\u0026DEV_1B82\u0026SUBSYS_1B8210DE\u0026REV_A1\\4\u002622C85AC7\u00260\u002600E7",
        "CardId":  -1,
        "Bus":  5,
        "GpuGroup":  "",
        "Data":  {
                     "AdapterId":  0,
                     "Utilization":  100,
                     "UtilizationMem":  100,
                     "Clock":  1430,
                     "ClockMem":  4303,
                     "FanSpeed":  33,
                     "Temperature":  65,
                     "PowerDraw":  93.23,
                     "PowerLimit":  180,
                     "PowerLimitPercent":  100,
                     "PowerMaxLimit":  217,
                     "PowerDefaultLimit":  180,
                     "Pstate":  "P2",
                     "Method":  "smi"
                 },
        "DataMax":  {
                        "Clock":  1468,
                        "ClockMem":  4498,
                        "Temperature":  65,
                        "FanSpeed":  39,
                        "PowerDraw":  93.23
                    }
    },
    {
        "Name":  "CPU#00",
        "Index":  5,
        "Vendor":  "INTEL",
        "Vendor_Name":  "GenuineIntel",
        "Type_PlatformId_Index":  0,
        "Type_Vendor_Index":  0,
        "Type":  "Cpu",
        "Type_Index":  0,
        "Type_Mineable_Index":  0,
        "Model":  "CPU",
        "Model_Base":  "CPU",
        "Model_Name":  "Intel(R) Pentium(R) CPU G4400 @ 3.30GHz",
        "Features":  [
                         "ssse3",
                         "sse2",
                         "sse42",
                         "sse41",
                         "sse3",
                         "x64",
                         "abm",
                         "aes",
                         "mmx",
                         "rdrand",
                         "sse"
                     ],
        "Data":  {
                     "Cores":  0,
                     "Threads":  0,
                     "CacheL3":  0,
                     "Clock":  0,
                     "Utilization":  0,
                     "PowerDraw":  0,
                     "Temperature":  0,
                     "Method":  ""
                 },
        "DataMax":  {
                        "Clock":  0,
                        "Utilization":  0,
                        "PowerDraw":  0
                    }
    }
]

**Comment by samdave123** [comment]
I'm also finding my OC profiles are not applying for GPU#01 #02 and #03 could this be a related problem?

[debug_2020-06-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/4739849/debug_2020-06-06.zip)

**Comment by samdave123** [comment]
{
  "Ethash-GPU#01": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "600",
    "CoreClockBoost": "-315",
    "LockVoltagePoint": "650000"
  },
  "Ethash-GPU#02": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "1100",
    "CoreClockBoost": "-310",
    "LockVoltagePoint": "650000"
  },
  "Ethash-GPU#04": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "1100",
    "CoreClockBoost": "-240",
    "LockVoltagePoint": "650000"
  },
    "Ethash-GTX1070Ti":  {
                             "PowerLimit":  100,
                             "ThermalLimit":  0,
                             "MemoryClockBoost":  "500",
                             "CoreClockBoost":  "200",
                             "LockVoltagePoint":  "700000"
                         },
    "MaxVoltsMinMemory-GTX1660Ti":  {
                                        "PowerLimit":  100,
                                        "ThermalLimit":  0,
                                        "MemoryClockBoost":  "-1000",
                                        "CoreClockBoost":  "120",
                                        "LockVoltagePoint":  "850000"
                                    },
    "MedVoltsMaxMemory-GTX1660Ti":  {
                                        "PowerLimit":  100,
                                        "ThermalLimit":  0,
                                        "MemoryClockBoost":  "600",
                                        "CoreClockBoost":  "140",
                                        "LockVoltagePoint":  "750000"
                                    },
    "MedVoltsMinMemory-GTX1660Ti":  {
                                        "PowerLimit":  100,
                                        "ThermalLimit":  0,
                                        "MemoryClockBoost":  "-1000",
                                        "CoreClockBoost":  "140",
                                        "LockVoltagePoint":  "750000"
                                    },
    "MinVoltsMaxMemory-GTX1070Ti":  {
                                        "PowerLimit":  100,
                                        "ThermalLimit":  0,
                                        "MemoryClockBoost":  "500",
                                        "CoreClockBoost":  "240",
                                        "LockVoltagePoint":  "650000"
                                    },
    "MinVoltsMaxMemory-GTX1660Ti":  {
                                        "PowerLimit":  100,
                                        "ThermalLimit":  0,
                                        "MemoryClockBoost":  "600",
                                        "CoreClockBoost":  "160",
                                        "LockVoltagePoint":  "650000"
                                    },
    "MinVoltsMinMemory-GTX1070Ti":  {
                                        "PowerLimit":  100,
                                        "ThermalLimit":  0,
                                        "MemoryClockBoost":  "-799",
                                        "CoreClockBoost":  "240",
                                        "LockVoltagePoint":  "650000"
                                    },
    "MinVoltsMinMemory-GTX1660Ti":  {
                                        "PowerLimit":  100,
                                        "ThermalLimit":  0,
                                        "MemoryClockBoost":  "-1000",
                                        "CoreClockBoost":  "160",
                                        "LockVoltagePoint":  "650000"
                                    },
    "Profile1-GTX1070Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "-799",
                               "CoreClockBoost":  "240",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile1-GTX1660Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "-1000",
                               "CoreClockBoost":  "160",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile2-GTX1070Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "500",
                               "CoreClockBoost":  "240",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile2-GTX1660Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "-1000",
                               "CoreClockBoost":  "160",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile3-GTX1070Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "500",
                               "CoreClockBoost":  "240",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile3-GTX1660Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "-1000",
                               "CoreClockBoost":  "160",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile4-GTX1070Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "-799",
                               "CoreClockBoost":  "240",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile4-GTX1660Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "-1000",
                               "CoreClockBoost":  "160",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile5-GTX1070Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "500",
                               "CoreClockBoost":  "240",
                               "LockVoltagePoint":  "650000"
                           },
    "Profile5-GTX1660Ti":  {
                               "PowerLimit":  100,
                               "ThermalLimit":  0,
                               "MemoryClockBoost":  "-1000",
                               "CoreClockBoost":  "160",
                               "LockVoltagePoint":  "650000"
                           }
}

**Comment by samdave123** [comment]
Additional context: Yesterday I transferred my RBM folder to a new SSD and motherboard. I rebuilt my mining rig and re-added all the GPUs as my board was struggling to run them all at the same time.

**Comment by RainbowMiner** [comment]
> Additional context: Yesterday I transferred my RBM folder to a new SSD and motherboard. I rebuilt my mining rig and re-added all the GPUs as my board was struggling to run them all at the same time.

This is useful, yes. It is most probably related.

**Comment by samdave123** [comment]
I seem to be able to set a Ethash OC profile for all 1660Tis, but when I try to set it per-card it doesn't seem to work. Is this related to the error message I'm seeing?

**Comment by samdave123** [comment]
The error does not show when I don't use per-card specific OC profiles

**Comment by samdave123** [comment]
Somehow I'm messing up setting custom OC profiles for Ethash on GPU#01 #02 and #03

**Comment by samdave123** [comment]
I've tried setting a per-card OC profile using GPU#00 and also 01:00 which is the PCI bus ID. Neither is working and are producing this error.

**Comment by samdave123** [comment]
I will try updating nvidia drivers. FYI I installed the wrong ones because the documentation is out of date here https://rbminer.net/documentation/

**Comment by samdave123** [comment]
I've tried a new installation of RBM and copied over my stats and config files, and the issue is still there.

**Comment by RainbowMiner** [comment]
> I will try updating nvidia drivers. FYI I installed the wrong ones because the documentation is out of date here https://rbminer.net/documentation/

Oh! I have cleared the cache. Now the current version is on the documentation page. Thank you for reporting.

**Comment by samdave123** [comment]
FIXED. Powershall 5.1 was installed instead of 6.0 I don't know if you can update the install script to use the correct version of Powershell, or create a warning of Powershell version is wrong?

**Comment by RainbowMiner** [comment]
> FIXED. Powershell 5.1 was installed instead of 6.0 I don't know if you can update the install script to use the correct version of Powershell, or create a warning if Powershell version is wrong?

Yes, I just came to the same conclusion 👍 I'll check the problem with the backwards compatiblitly.

**Comment by RainbowMiner** [comment]
Actually, updating the install script sounds like a very good idea. I'll think about that.

**Comment by RainbowMiner** [comment]
I have fixed the PS5 backwards compatibility for device specific overclocking profiles.
