### ISSUE TITLE
New Algo on Nicehash

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1035]
https://www.nicehash.com/algorithm/cuckaroo29bfc

**Comment by RainbowMiner** [comment]
Thank you for reporting this! I'll add it to our database asap.

**Comment by mo35** [comment]
Cuckaroo29bfc nbminer isnt compatible , gminer is fine

**Comment by RainbowMiner** [comment]
> Cuckaroo29bfc nbminer isnt compatible , gminer is fine

Ok, good to know. I'll disable NBminer for BFC, for the time being.
