### ISSUE TITLE
Price Factor or AutoCreateMinProfitPercent?

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1036]
I was mining swapcoin (low power algo) and I got some Kawpow rentals (high power algo), and the differences in power meant the margin for the MRR rental was not particularly high. Can the minprofitpercent be set to something so that it is based more on profit margins, than on revenue?

**Comment by RainbowMiner** [comment]
The AutoCreateMinProfitPercent is just a helper, to decide which rigs should be created at MRR. The announced price is calculated using the PriceFactor and/or PriceBTC values, based on revenue. 
So, what we would need is a way to increase (or decrease) the announced price according to profit margins on a rig. I am already thinking about a solution, but would be happy for suggestions :)

**Comment by RainbowMiner** [comment]
Ok, I think I found a smart way to include the powerdraw differences into the MRR prices. The following parameter has been added to pools.config.txt/MiningRigRentals and mrr.config.txt:

- **PowerDrawFactor**: Enter powerdraw multiplicator (only in use if UsePowerPrice is enabled): minimum price = minimum price + (miner's cost - rig's average cost) x this multiplicator [default=1.0] (issue #1036)

Also, I have added the price change level to the config (it has been unchangeable fixed 5% before):
- **AutoUpdateMinPriceChangePercent**: Enter minimum price change in percent, for a rig's price to be updated on MRR [default=3]
