### ISSUE TITLE
Algo's showing online when rented.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1037]
![image](https://user-images.githubusercontent.com/4724631/83960287-1611f080-a83c-11ea-9402-7ef4f64c6618.png)

I dont know if this is something I should report. Unfortunately I cannot get a De-Bug from the machine until Monday. I will get this to you if you state you need it?

**Comment by RainbowMiner** [comment]
This is perfectly right - RainbowMiner automatically creates separate MRR rigs for CPU and GPU. If you leave the WorkerName for CPU in device.config.txt empty, it will use an extra workername with your rig's workername plus "cpu" at the end.
In your case (workername = "t5600") it created an extra CPU worker with name "t5600cpu" and found RandomX to be worth for a listing.

**Comment by RainbowMiner** [comment]
A remark:
- if you use "%workername%" in the title, you do not need to use "%rigid%". Every rig-title needs to be unique, in your MiningRigRentals account, so only one of the two is necessary.
  Explanation: the "%rigid%" is simply an encrypted shortcut of your workername. So, in case you do not want to show your workername (when using "%workername%"), you can use "%rigid%" instead.

**Comment by Yamanipanuchi** [comment]
Ahh yes.. I didn't look at it close enough! Also forgot that rig had a low end GPU in it. All good!
