### ISSUE TITLE
Small glitch in MRR naming

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1041]
Maybe some dual mining conflict?

![image](https://user-images.githubusercontent.com/42582444/84124775-951d4980-aa33-11ea-9cba-921d32c9cc51.png)

![image](https://user-images.githubusercontent.com/42582444/84124729-85056a00-aa33-11ea-8f0f-8c421ec0b629.png)

**Comment by RainbowMiner** [comment]
Yes, that looks like a glitch. I'll check it.

**Comment by RainbowMiner** [comment]
Solved
