### ISSUE TITLE
Strange API values for HMQ1725

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1043]
I have zergpoolcoins enabled and I keep getting crazy estimates from the API, even though I have it set to an hour average....

![image](https://user-images.githubusercontent.com/42582444/84145631-256a8700-aa52-11ea-9103-47280d4c653f.png)
I've checked the zergpool page and the estimates seem fine, so could there be an issue with the API?

**Comment by acos0874** [comment]
I just realised my config files weren't on hour average as I expected, but were on minute_10. So I've switch over now to see if it's better. Is there a way to check on local host which average is in play?

**Comment by RainbowMiner** [comment]
Only possiblity to find the infos on localhost, is the "Running Config" page. Just search for "ZergPoolCoins" on that page. I have best results with "estimate_current" on ZergPoolCoins.

**Comment by acos0874** [comment]
Yea I use current estimates too but have been using a value other than 'live' for the stat average. I think I figured it out though. I was using hour as the stat average for anything other than nicehash in the expectation that this, along with the switch prevention, would keep my miners away from highly volatile shitcoins.

Unfortunately it seems this had an unintended consequence, because the HMQ1725 coins are crazy volatily it actually meant the hour average was pushed so high, that the estimate stayed high for a long time. This probably wouldn't have been so bad with minute_10.  I've switch back to live and the  estimates seem more reasonable again.

**Comment by acos0874** [comment]
Were you experiencing the same high estimates using 'hour' as your stat average?

**Comment by RainbowMiner** [comment]
Yes, there has been a high (but reasonable) value for the HMQ1725 BRAZ coin. I think, the major uplift has been with ESP coin - which I have on my ExcludeCoinSymbol list on ZergPoolCoins. So I expect I didn't see much of a shocking value.
But since the API's estimates for ESP are most of the times out of range, I think, I'll put this coin onto the auto-ignore-shitcoins-list.

**Comment by RainbowMiner** [comment]
Ok, I have listed "ESP" on ZergPoolCoins as unprofitable.

**Comment by acos0874** [comment]
Ok. I don't mind if you leave it in there if it's due to a legitimate difficulty drop. I'm mining BRAZ coin right now.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/84171926-455e7280-aa73-11ea-8e3d-4de15e5ae657.png)
Is there a way to force an update of the pool earnings tab? Mine doesn't seem to be picking up zergpool correctly.

**Comment by acos0874** [comment]
I discovered the error ratio for the HMQ coins had hit as high as 2, which seems a bit silly so I have disabled the error ratio setting. Is there a way to limit the error ratio number to have a maximum value?

**Comment by RainbowMiner** [comment]
I have added a "MaxErrorRatio" parameter to config.txt (which defaults to 1.5, currently)

**Comment by acos0874** [comment]
Nice thanks!
