### ISSUE TITLE
Earnings Tracking Bug

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1045]
![image](https://user-images.githubusercontent.com/42582444/84175596-18f92500-aa78-11ea-8cc2-1deeb991c270.png)

Earnings tracking seems to stop working on zerpgool. I think it may be due to me changing my BTC address recently.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/84175894-84db8d80-aa78-11ea-94d1-07a52b5ca973.png)
Might be a zergpool issue.

**Comment by RainbowMiner** [comment]
Yes, that looks like a ZergPool issue.
