### ISSUE TITLE
Suggestion: Dummy Pools

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1046]
Sorry for all the suggestions....

Sometimes I want to be able to monitor the profitability of a pool or algo, without it actually being selected by the profit switcher. Also this is useful for benchmarking algos for MMR which I'm not actually mining. Would it be possible to include an option that would allow the visibility of profitability but without it being mined?

Or otherwise, can you suggest a possible workaround that doesn't involve the use of penalties?

**Comment by samdave123** [comment]
The current workaround I'm using is to enable all pools with a 99% penalty, just to get stuff benched. It would be useful to be able to bench all MRR algos regardless of whethere there's a pool attached.

**Comment by RainbowMiner** [comment]
I am working on something already :)
