### ISSUE TITLE
"PoolSwitchingHysteresis" and "MinerSwitchingHysteresis" in localhost setup page

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1048]
I'm tweaking my switching settings at the moment and tweaking the "PoolSwitchingHysteresis" and "MinerSwitchingHysteresis" settings particularly. It would be nice to be able to tweak it in the localhost without having to RDP into my Windows machine.

**Comment by RainbowMiner** [comment]
Sure, no problem. I'll add those two.

**Comment by samdave123** [comment]
Thank you. Quick question about how these settings work. If I have Switching Prevention set to 5, does this have any effect on preventing switching between pools and between miners, or are the "PoolSwitchingHysteresis" and "MinerSwitchingHysteresis" required to do this? 

I don't care what RBM is switching (miner, algo, pool) I'd rather prevent them all equally.

**Comment by samdave123** [comment]
Does Switching Prevention only prevent the switch between algos?

**Comment by acos0874** [comment]
Why do you rdp in to change configs? Just set up a file share

**Comment by samdave123** [comment]
> 
> 
> Why do you rdp in to change configs? Just set up a file share

The config file is saved on my rig. Are you saying it would be simpler for me to buy a NAS and store the config file on that?

**Comment by acos0874** [comment]
Share the folder from your rig to the computer that you are remoting in from. Using windows file share

**Comment by samdave123** [comment]
This seems to be implemented.
