### ISSUE TITLE
Qitmeer + Zil

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1049]
https://minerstat.com/coin/PMEER

https://minerstat.com/coin/ETH+ZIL

Please can you add these algos?

**Comment by RainbowMiner** [comment]
All miners are already avail - we will need pools to handle it. I'll add some.

**Comment by acos0874** [comment]
MRR added Qitmeer. Please can this be set up?

**Comment by RainbowMiner** [comment]
Ok, that should do the job. They used "cuckaroo24" to address the Cuckaroom29 PMEER, so I had to extend the MRR translation function.
