### ISSUE TITLE
RBM orders GPUs differently when restarted

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1051]
Often restarting RBM will result in the GPUs being given different GPU numbers. For example, sometimes my first GPU is #01 and sometimes it is #00. This seems to be happening when IGP is enabled on my board but not when it's disabled. This then breaks all the stats and my rig has to rebench everything, and also breaks GPU-specific OC profiles. Disabling the IGP is more of a workaround than a real fix.

**Comment by RainbowMiner** [comment]
Wow, that's a strange thing! Normally, CUDA aligns the GPU's totally consistent, even over driver updates. It seems, that there is an IGP bug with the Nvidia drivers. What is your exact hardware configuration? Especially, which are the current motherboard model, the GPUs, the driver versions?

**Comment by RainbowMiner** [comment]
Could you eventually run http://localhost:4000/alldevices (yes, the url, without .html) and upload the resulting JSON data?

**Comment by samdave123** [comment]
I had to rename it to .txt so Github would accept it. smash/acos0874 has the same problem but he gets around it by disabling the IGP.

[alldevices.txt](https://github.com/RainbowMiner/RainbowMiner/files/4770974/alldevices.txt)

**Comment by samdave123** [comment]
Hardware:
ASRock Intel H110 Pro BTC+ 
2 X 1070Ti Palit
3X Gigabyte 1660Ti
G4400 CPU
IGP enabled

Driver version 432.00

**Comment by RainbowMiner** [comment]
Ok, some questions, to find the culprit:
- Do the Nvidia GPU change their sorting, too? 
- Does the sorting change completely?
- Or is it the IGP, that jumps to the beginning and at the end?

**Comment by samdave123** [comment]
The Nvidia GPUs remain the same sorting, they just change between starting at #00 and starting at #01

Right now the Intel GPU is #00 but sometimes my Nvidia GPU is #00

**Comment by RainbowMiner** [comment]
So I suspect, that the IGP jumps to beginning/end. Very strange, as CUDA should take care of such things. I never had that effect on any of my machines, so maybe it's releated to that specific H110 Pro board model. Next step (for me), will be to dig through the CUDA .net API interface.

**Comment by RainbowMiner** [comment]
> Right now the Intel GPU is #00 but sometimes my Nvidia GPU is #00

And does this happen, if you restart RainbowMiner, or if you reboot the machine?

**Comment by samdave123** [comment]
> 
> 
> > Right now the Intel GPU is #00 but sometimes my Nvidia GPU is #00
> 
> And does this happen, if you restart RainbowMiner, or if you reboot the machine?

I'm not 100% sure. I'll do a few restarts + closing and reopening + rebooting the rig to provide more information.

**Comment by RainbowMiner** [comment]
If you get a swap, please try to get the http://localhost:4000/alldevices for that machine.

**Comment by RainbowMiner** [comment]
I bet, we will now get an example of the demo effect and it will remain stable.

**Comment by samdave123** [comment]
Currently doing testing now. I'm wondering if it's being caused by the IGP not being activated at boot but instead becoming active after the first RDP session?

**Comment by samdave123** [comment]
Restarted RBM twice and Nvidia GPUs start at #01 both times.

**Comment by samdave123** [comment]
Rebooted and now first Nvidia GPU is 00

[alldevices.txt](https://github.com/RainbowMiner/RainbowMiner/files/4771759/alldevices.txt)

**Comment by samdave123** [comment]
Looks like the Intel GPU is swapping between first and last.

**Comment by samdave123** [comment]
Just killed RBM and started it again and it's back in its original order.

[alldevices.txt](https://github.com/RainbowMiner/RainbowMiner/files/4771769/alldevices.txt)

**Comment by samdave123** [comment]
I wonder if you could tweak the device order to make sure Nvidia GPUs always come first or always come last? I need them consistent as I'm applying OC profiles to GPU numbers and when the order changes it messes up my overclocks.

**Comment by RainbowMiner** [comment]
> I wonder if you could tweak the device order to make sure Nvidia GPUs always come first or always come last? I need them consistent as I'm applying OC profiles to GPU numbers and when the order changes it messes up my overclocks.

Yes, that is most important. Thank you for trying! I'll figure something out asap.

**Comment by RainbowMiner** [comment]
Something, that is really strange is, that it seems that OpenCL changes the platform ids *shock*

> Just killed RBM and started it again and it's back in its original order.

Was this after another reboot, or just a restart of RainbowMiner?

**Comment by samdave123** [comment]
> 
> 
> Something, that is really strange is, that it seems that OpenCL changes the platform ids _shock_
> 
> > Just killed RBM and started it again and it's back in its original order.
> 
> Was this after another reboot, or just a restart of RainbowMiner?

This was just a restart. The reboot placed my IGP last, and then the restart placed it first.

**Comment by RainbowMiner** [comment]
> This was just a restart. The reboot placed my IGP last, and then the restart placed it first.

Crazy!

**Comment by samdave123** [comment]
I can confirm disabling the IGP fixes this problem, but is something I would prefer to avoid doing.

**Comment by RainbowMiner** [comment]
It could be a timing problem with the OpenCL drivers - I startup RainbowMiner after a delay, after boot. So maybe that could help.
So or so - I am working on a solution.

**Comment by RainbowMiner** [comment]
> Rebooted and now first Nvidia GPU is 00

Question:
- did you start RainbowMiner automatically, after reboot? Or did you start it by-hand? 
- if automatically: did you start it immediately? Without any delay?

I still believe, this could be a timing issue.

**Comment by samdave123** [comment]
> 
> 
> > Rebooted and now first Nvidia GPU is 00
> 
> Question:
> 
>     * did you start RainbowMiner automatically, after reboot? Or did you start it by-hand?
> 
>     * if automatically: did you start it immediately? Without any delay?
> 
> 
> I still believe, this could be a timing issue.

Rainbowminer started automatically and immediately as per the recommended autostart settings. I did another restart and the order was back to Nvidia starting at 01. It seems to be random which way they get assigned.

**Comment by RainbowMiner** [comment]
I will push a new release, including some kind of auto-fix.

**Comment by RainbowMiner** [comment]
Ok, I have added some debugging code, now.
With the new release v4.5.8.7, could you eventually try to reboot again and see, if the mixup happens again? It might also happen, that you see a warning "OpenCL Platforms mixup! Applying automatic fix .. "

In any case: after reboot or restart, what is the result of http://localhost:4000/platforms ?

**Comment by samdave123** [comment]
{
  "DefaultDetect": [
    "NVIDIA Corporation",
    "Intel(R) Corporation"
  ],
  "XmrigDetect": [
    "NVIDIA Corporation",
    "Intel(R) Corporation"
  ]
}

**Comment by samdave123** [comment]
![image](https://user-images.githubusercontent.com/56473344/84591239-bcf61e00-ae34-11ea-9148-5c1e706a19eb.png)

**Comment by samdave123** [comment]
I then restarted RBM and got this 
![image](https://user-images.githubusercontent.com/56473344/84591259-edd65300-ae34-11ea-92fb-7c6aa760f2de.png)

**Comment by samdave123** [comment]
So now the IGP isn't showing up at all, which isn't an issue, but the GPU ordering is still changing, which is a significant issue. It also forces my rig to rebench everything.

**Comment by RainbowMiner** [comment]
Thank you for trying! So now it is clear, that it is a OpenCL driver problem, most probably due to initialization times during boot up of Windows.
The platforms JSON shows what RainbowMiner detects versus what the miner xmrig detects. Both use different approaches to access the OpenCL.dll

I will.now remove the debug code.

Good thing is, it seems you can easily reproduce the problem. I will think about another solution. 

The most simple solution would be to delay the startup of RainbowMiner for about 30 seconds after reboot (actually, that's what I have implemented on my rigs, maybe thats why I never happened to see this problem)

**Comment by RainbowMiner** [comment]
I would really like to find out, at which point during the Windows bootup, the OpenCL sorting changes. If we could pin it to a specific process or service, I could implement a wait loop into RainbowMiner.

**Comment by samdave123** [comment]
Is there any more information you would like from me to help you implement a wait loop?

**Comment by RainbowMiner** [comment]
There are actually two possible approaches. First, we could adapt with the software. Means, I could bind the GPU#xx sorting to the PCI-bus number sorting (which Nvidia uses anyway). That would then never break the sort order again, but it might cause problems with some miners. I cannot predict what this might break, yet (actually, regarding overclocking, you could pin the profiles to the PCI slots, by using "Profile-xx:00" format, instead of "Profile-GPU#yy". xx would be the Bus number).

The second approach is to find the systemprocess, that settles the GPU ordering. I'ld perhaps prefer this solution, if we can really figure it out. So, next step, I will implement a little debug code that will track the boot process versus the OpenCL platform sorting.

**Comment by samdave123** [comment]
I think the second approach is necessary because even if I pin the OC profiles to the PCI slots, RBM will still rebench the algos when the order changes.

**Comment by samdave123** [comment]
I added a 30s delay to the Windows autostart and updating the Nvidia driver version. It doesn't seem to be reoccuring, but I need to reboot more times to be sure.

**Comment by samdave123** [comment]
Nope, it happened again.

**Comment by samdave123** [comment]
I added a 1 minute delay to autostart RBM and it fixes this issue 90% of the time.

**Comment by samdave123** [comment]
I ended up just disabling the IGP to get around this problem.

**Comment by RainbowMiner** [comment]
That should now be solved, with the current release v4.6.8.7+
RainbowMiner now detects, if the OpenCL platforms have changed and resorts the GPUs according to the order at the time of first start of RainbowMiner.
