### ISSUE TITLE
Equihash20x9 = Equihash (200, 9)

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1052]
It looks like there are no miners enabled for this algo. Please can it be added? It's available on f2pool.

**Comment by Adiuk** [comment]
Do you know which miner you want to use? If so go to miners folder, find the miner ps file, open it and remove the # before the algo line. This will enable the algo on said miner.

**Comment by acos0874** [comment]
Oh it looks like it might actually be incorrect in the equihash conversion table. Documentation says 20x9 but I think it should be 21x9?

**Comment by RainbowMiner** [comment]
So it's solved :)

RainbowMiner uses the following nameing convention:
- Equihash16x5 = Equihash (96, 5)
- Equihash20x9 = Equihash (200, 9)
- Equihash21x9 = Equihash (210, 9)
- Equihash24x5 = Equihash (144,5), e.g. BTG
- Equihash24x7 = Equihash (192,7), e.g. ZEROcoin
- EquihashR25x4 = Equihash (125,4), e.g. ZelHash
- EquihashR25x5 = Equihash (150,5), e.g. GRIMM
- EquihashR25x5x3 = Equihash (150,5,3), e.g. BEAM

Those 200,9 and 210,9 are different algorithm. F2pool wants Equihash 210,9 - which is in fact Equihash21x9

Actually, you are allowed to enter different versions for these algorithms. You can always enter the (x,y) values, too. Like "Equihash2109" - that will do the job, as well. RainbowMiner sends every algorithm values, that it gets from the config files, through a remapping function.

**Comment by acos0874** [comment]
Oh yea. I think looking back I may have had a brain fart with the numbering. Also, my config files keep seem to reverting themselves. AION removed itself from my pool options.
