### ISSUE TITLE
RainbowMiner Not Capturing Hashrate from nheqminer

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1054]
Verus at Zergpool is the most profitable for a Ryzen cpu now and RainbowMiner correctly starts with this algo upon startup.  However RainbowMiner is not capturing the hashrate from nheqminer and thinks the hashrate is 0 so it closes that miner and moves onto the next most profitable miner.  
[debug_2020-06-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/4777254/debug_2020-06-14.zip)
nheqminer seems to be more intensive than other miners so maybe that has something to do with it.

**Comment by jch9678** [comment]
Actually may be happening on other algos too

**Comment by RainbowMiner** [comment]
Yes, nheqminer needed an update to miner version 0.8.1. Verushash has switched to v2.2 an June 14th.
Done with new release v4.5.8.9

**Comment by jch9678** [comment]
I think it was happening before then but I'll update and report back.
