### ISSUE TITLE
MRR Autoextend

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1057]
https://www.whattominingrigrentals.com/

This website uses an auto extend feature on the rentals

![image](https://user-images.githubusercontent.com/42582444/84778634-2adc4a00-afdb-11ea-96c4-07e2d35347e8.png)

Unfortunately there is no way to 'mass edit' all rigs. I was wondering if you could please implement something similar in RBM?

**Comment by RainbowMiner** [comment]
An auto extend feature is actually a very nice idea. I'll add something like that.
Regarding mass edit, which parameters would you like to mass edit manually?

**Comment by acos0874** [comment]
Thanks. It was only the autoextend option on that website. If I think of anything else I'll put it here. Does rbm already include a parameter for "relative to suggested"? How I used to implement my pricing to undercut the completion was use -20% relative to suggested but with a minimum price to make it more profitable than what I can make elsewhere (already implemented). This meant I could get rentals on less common algos like mtp whilst still maintaining a minimum on more common algos like ethash. 
null

**Comment by RainbowMiner** [comment]
I think, the parameter "AutoPriceModifierPercent" (-30 .. 30) does this job. But there are two buts, currently. First, it's used during the creation of the rigs, only. Second, it's the same for all created rigs.
The idea has been to provide the option to fine-tune that paramter for certain algorithm, online at the MRR website, after the rigs have been all created.

Eventually, I could add either an extra parameter to pools.config.txt (like, "EnableAutoUpdateModifier", that would force the modifier being updated during updates, too), or I could add another config file (mrr.config.txt), which would contain all algorithm specific parameters (like that modifier) per algorithm (or probably both).

**Comment by RainbowMiner** [comment]
> or I could add another config file (mrr.config.txt), which would contain all algorithm specific parameters (like that modifier) per algorithm (or probably both).

Oh! Much easier! I could simply add those mrr parameters to the algorithm.config.txt - which in fact already contains per-algorithm parameters.

**Comment by RainbowMiner** [comment]
- add parameter `"EnableUpdatePriceModifier": "0",` to pools.config.txt
  - set to "1", if the price modifier should be automatically updated
  - set to "0", if the price modifier will be set during creation of the rigs, only
- the value for the rig modifier is calculated either from global value (pools.config.txt, parameters `"AutoPriceModifierPercent"`) or specific value for each algorithm (algorithms.config.txt parameter `"MRRPriceModifierPercent"`, if empty string, global value will be used)

**Comment by acos0874** [comment]
Awesome, and just to check this will not override the minimum price which is also set by RBM?

**Comment by RainbowMiner** [comment]
The minimum price will always be respected.

**Comment by acos0874** [comment]
I just had another thought about this. Autoextend might develop a risk of rig owners being short changed by renters using incorrect settings. For example, if the renter sets a too high difficulty it would make the hashrate percentage seem low, even though it's not the fault of the rig owner. The auto extend would mean the renter would unfairly be getting extra time for free. 

So a potential alternative or additional feature would be to notify the rig owner when the hashrate appears to be low, some time before the end of the rental and before autoextend. This would give the rig owner the choice of either manually intervening to extend the rental or letting autoextend do its thing.

**Comment by RainbowMiner** [comment]
Yes, you are right. A malicious renter could cost us some nerves and money, here. It could be somehow limited by a value for "Max extend", but it could happen.

**Comment by acos0874** [comment]
True but in my experience it's more likely noob renters with incorrect settings. 
null

**Comment by RainbowMiner** [comment]
> True but in my experience it's more likely noob renters with incorrect settings. 

Oh dear, I totally agree with you.

**Comment by RainbowMiner** [comment]
Ok, auto extend on low average hashrate is added (commit c44395def73c2f886dee4f159692d872529d7357)

- add auto extend on low average feature. New params in pools.config.txt and mrr.config.txt:
  - **EnableAutoExtend**: Automatically extend MRR rentals, when low average hashrate [default=0]
  - **AutoExtendTargetPercent**: Extend rentals time, so that the total average hashrate is near this value in percent of advertised hashrate [default=100]
  - **AutoExtendMaximumPercent**: Extend rentals maximum to this value in percent of the rental time [default=100]

**Comment by astronyu** [comment]
I would also add a suggestion of adding extension option if possible. Adding an option to extend rental 1 hour for every 24 hour rented.

**Comment by RainbowMiner** [comment]
> I would also add a suggestion of adding extension option if possible. Adding an option to extend rental 1 hour for every 24 hour rented.

I have implemented that feature yesterday :)

- add automatic bonus extension feature to pools.config.txt:
  - **AutoBonusExtendForHours**: Enter amount of hours, that you want to be rewarded by an automatic bonus extension of AutoBonusExtendByHours (e.g. 24) [default=0]
  - **AutoBonusExtendByHours**: Enter bonus extension in hours per each fully rented AutoBonusExtendForHours (e.g. 1) [default=0]

**Comment by astronyu** [comment]
> 
> 
> > I would also add a suggestion of adding extension option if possible. Adding an option to extend rental 1 hour for every 24 hour rented.
> 
> I have implemented that feature yesterday :)
> 
>     * add automatic bonus extension feature to pools.config.txt:
>       
>       * **AutoBonusExtendForHours**: Enter amount of hours, that you want to be rewarded by an automatic bonus extension of AutoBonusExtendByHours (e.g. 24) [default=0]
>       * **AutoBonusExtendByHours**: Enter bonus extension in hours per each fully rented AutoBonusExtendForHours (e.g. 1) [default=0]

That is FAST! Thank you.
What does "AutoUpdatePriceModifier" means?

**Comment by acos0874** [comment]
He travelled back in time to implement it for you 😅

**Comment by RainbowMiner** [comment]
> What does "AutoUpdatePriceModifier" means?

This value sets the "modifier" value at MiningRigRentals. It's a percentage increase/decrease of the MiningRigRental's suggested price. Using this value, you can under-/overbid other rig owners. It is also available per algorithm (in algorithms.config.txt), in there, the name of the parameter is "MRRUpdatePriceModifier".
