### ISSUE TITLE
Trex miner error

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1059]
Not sure if this needs to be reported. To me at first glance looks as if there is an error with how it was compiled?

20200616 14:34:53 T-Rex NVIDIA GPU miner v0.15.7  -  [CUDA v10.0]
20200616 14:34:53 r.fde38bdcdcc1
20200616 14:34:53
20200616 14:34:53 NVIDIA Driver v440.82
20200616 14:34:53 CUDA devices available: 1
20200616 14:34:53
20200616 14:34:53 WARN: DevFee 1% (kawpow)
20200616 14:34:53
20200616 14:34:53 URL : stratum+tcp://us1.hellominer.com:6600
20200616 14:34:53 USER: RVPKz7oVmR3N1CWKJqcibaaUYrPfiUMLNt.Solar
20200616 14:34:53 PASS: x
20200616 14:34:53
20200616 14:34:53 WARN: NVML is disabled. You won't see GPUs stats.
20200616 14:34:53
20200616 14:34:53 WARN: Built-in watchdog has been disabled!
20200616 14:34:53 Starting on: us1.hellominer.com:6600
20200616 14:34:53 ApiServer: Telnet server started on 127.0.0.1:31600
20200616 14:34:53 WARN: GPU #0: EVGA GeForce GTX 1650 SUPER, intensity set to 20
20200616 14:34:54 Extranonce is set to: 00a4c2
20200616 14:34:54 Authorizing...
20200616 14:34:55 New target is set to: 0x00000007fff80000000000000000000000000000000000000000000000000000
20200616 14:34:55 Authorized successfully.
20200616 14:34:55 kawpow epoch: 170, block: 1278687, period: 426229, diff: 0.112 = 536.87 Mh
20200616 14:34:56 New target is set to: 0x00000007fff80000000000000000000000000000000000000000000000000000
20200616 14:34:57 Compile error: nvrtc: error: invalid value for --gpu-architecture (-arch)

20200616 14:34:57 Can't compile kernel, NVRTC error in func compile_kernel_from_source at line 69 calling compileResult failed with error

20200616 14:34:57 Generating DAG: 2.36 GB
20200616 14:34:57 New target is set to: 0x00000007fff80000000000000000000000000000000000000000000000000000

**Comment by Yamanipanuchi** [comment]
Correction, Trex is working for X16r but not KawPow. So might be something else.

**Comment by RainbowMiner** [comment]
KawPow uses a different kernel, than most of the other algorithms (ProgPow). So eventually Trex cannot handle the GTX 1650. I'll redirect that problem to the Trex developers.

**Comment by Yamanipanuchi** [comment]
No longer an active issue.
