### ISSUE TITLE
Kawpow Issue

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1060]
I've found my system several time locked up. Upon Digging it turns out it was having issues with KawPow miner, It was continually crashing. I added it to the exclude list and TTminer took over and no issues. This is a Linux System and it only started doing this recently. Unfortunately I cant tell you exactly when.

[debug_2020-06-16.zip](https://github.com/RainbowMiner/RainbowMiner/files/4787749/debug_2020-06-16.zip)

**Comment by RainbowMiner** [comment]
Thank you for reporting that. I'll probably disable the KawPowMiner by default, since TTminer is now developer fee free, too.

**Comment by Yamanipanuchi** [comment]
This issue no longer bothering my rig.. for some reason.
