### ISSUE TITLE
Different MRR rigs per device model.

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1061]
I have a mixture of 1070Tis and 1660Tis on the same rig. They are good at different algos, so they don't mine the same algos often. Since there aren't many algos they both excel at, I don't get many good rentals. It would probably be better if I could rent out the different device models individually.

**Comment by RainbowMiner** [comment]
That is actually (almost) possible. Every device group can be assigned another workername. Just edit devices.config.txt and enter individual workernames into paramter `"Worker":  ""`
.. here comes the but: currently, additional rigs will be created for each workername. The full GPU rigs will stay active, as well.
I will add another parameter to pools.config.txt, so that you can easily adjust this.

**Comment by RainbowMiner** [comment]
Ok, I have added two new parameters to pools.config.txt:
- add parameters to pools.config.txt, to be able to select workers for MRR rig operations
  - **AllowWorkerName**: Enter list of workernames that should be explicitly used for MRR (leave empty for all=default)
  -  **ExcludeWorkerName**: Enter list of workernames that should explicitly excluded from the use with MRR (leave empty for none=default)

Remark: 
- to (dis-)allow the CPU rigs: add `<yourrigworkername>cpu`, e.g. if your workername is "RainbowMiner", use "RainbowMinercpu"
- to (dis-)allow the all-GPU rig: add `<yourrigworkername>`, e.g. if your workername is "RainbowMiner", use it :)
- to (dis-)allow device groups: add the workername(s), that you have given your device groups in devices.config.txt (parameter `"Worker"`)

**Comment by RainbowMiner** [comment]
Uh, sorry. I had to rename "AllowWorkerName" to "UseWorkerName".

**Comment by samdave123** [comment]
Like this?

"UseWorkerName": "GTX1070Ti,GTX1660Ti",

**Comment by samdave123** [comment]
RBM seemed to turn off the combined GPU rigs, create some new rigs, then stop and not finish the job. After a few hours, it doesn't seem to be doing anything.

    "Devices": {
        "CPU": {
            "MinerName": [],
            "ExcludeMinerName": [],
            "DefaultOCprofile": "",
            "Algorithm": [],
            "ExcludeAlgorithm": [],
            "DisableDualMining": false,
            "PowerAdjust": 100,
            "Worker": "NvidiaRigcpu"
        },
        "GTX1070Ti": {
            "DefaultOCprofile": "Profile4",
            "MinerName": [],
            "ExcludeMinerName": [],
            "Worker": "GTX1070Ti",
            "Algorithm": [],
            "ExcludeAlgorithm": [],
            "DisableDualMining": false,
            "PowerAdjust": 100
        },
        "GTX1660Ti": {
            "DefaultOCprofile": "Profile2",
            "MinerName": [],
            "ExcludeMinerName": [],
            "Worker": "GTX1660Ti",
            "Algorithm": [],
            "ExcludeAlgorithm": [],
            "DisableDualMining": false,
            "PowerAdjust": 100

            "UseWorkerName": "GTX1070Ti,GTX1660Ti",
            "ExcludeWorkerName": "",

[debug_2020-06-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/4801304/debug_2020-06-18.zip)

**Comment by RainbowMiner** [comment]
Actually, there could be a clash - try not to use your device names as workernames. Use real unique names, instead. E.g. [NvidiaRig1070ti]

**Comment by RainbowMiner** [comment]
Could you please explain a bit more, what is happening?

**Comment by RainbowMiner** [comment]
> RBM seemed to turn off the combined GPU rigs, create some new rigs, then stop and not finish the job.

If you use "UseWorkerName" with your devices workernames - yes, the combined rigs will be shut off, completely. Even if they are currently rented.

**Comment by samdave123** [comment]
I added the device worker names to devices.config and then added those names to "UseWorkerName". All the old MRR rigs went offline and a few new ones popped up with the hashrates for each device model, however some algos had none created, some has 1 and some had 2, when they should all have 2. Nothing seemed to be happening and then I got an Ethash rental.

I tried changing the device names to "NvidiaRig1070ti" and "NvidiaRig1660ti" like you suggested but that broke my current 1070Ti rental so I had to revert that one.

**Comment by RainbowMiner** [comment]
> I tried changing the device names to "NvidiaRig1070ti" and "NvidiaRig1660ti" like you suggested but that broke my current 1070Ti rental so I had to revert that one.

Yes, if you have got a rental, leave it, like it is.

**Comment by samdave123** [comment]
> 
> 
> > I tried changing the device names to "NvidiaRig1070ti" and "NvidiaRig1660ti" like you suggested but that broke my current 1070Ti rental so I had to revert that one.
> 
> Yes, if you have got a rental, leave it, like it is.

I really shouldn't have touched it.... It's showing some algos as available for my 1070Tis right now even though they're on a job...

**Comment by RainbowMiner** [comment]
> I really shouldn't have touched it.... It's showing some algos as available for my 1070Tis right now even though they're on a job...   

just do a [R]estart to solve this.

**Comment by RainbowMiner** [comment]
> however some algos had none created, some has 1 and some had 2

There are two limiting factors, that could cause rental rigs not to be created:
- **AutoCreateMinProfitPercent**: if rig's profit is lower than device-combo's profit x this factor / 100
- **AutoCreateMaxMinHours**: if the calculated minimum time for a rig is above that value

**Comment by RainbowMiner** [comment]
Deleting rigs on MRR is a pain, online. You can use the RainbowMiner setup (start Setup.bat) for that - I have implemented some easy find and delete.

**Comment by samdave123** [comment]
Looks like my 1070Tis have gone offline again and continuing the rental as normal. I'll change the worker name at the end of the rental. I changed the 1660Ti worker names as you said and it all seems to be created now.

Seems to be working okay for now, so I'll leave it for tonight. Thanks for helping me resolve this.

**Comment by RainbowMiner** [comment]
I have a last remark (actually, I should put this into the readme, too):
- to avoid being blocked by MRR due to excessive API usage, the creation plus the update of descriptions of rigs is limited to a maximum of 20 per create/update run
- this restriction does not affect updates of rigs, if the description has not been changed
- the create/update run happens every hour
- if you want to rapidly let more rigs created/updated, click the "Run Rig-Updates" button on http://localhost:4000/mrrrigs.html page to induce another create/update run after the current RainbowMiner round.

**Comment by RainbowMiner** [comment]
> Seems to be working okay for now, so I'll leave it for tonight. Thanks for helping me resolve this.

So, maybe you do not have to change the workernames after all. If all runs smoothly, leave them.

**Comment by samdave123** [comment]
So I've got this all fixed, but now I have lots of obsolete rigs on MRR. Could RBM delete old rigs?

**Comment by RainbowMiner** [comment]
Not at the moment. I will add some easy code for that.

**Comment by RainbowMiner** [comment]
> So I've got this all fixed, but now I have lots of obsolete rigs on MRR. Could RBM delete old rigs?

Added to Setup.bat (choose "r" for MRR options, then "d" for delete and narrow down your selection)

**Comment by samdave123** [comment]
This is working well.
