### ISSUE TITLE
MRR Rig Description in MRR.config

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1062]
Hi, I added custom descriptions for the rigs in this file but it doesn't seem to update the website. Did I maybe make them too long?

**Comment by RainbowMiner** [comment]
Actually, the description is not being updated, currently. I'll fix this.

**Comment by RainbowMiner** [comment]
Ok, done.
- add enable update rig descriptions:
  - **EnableUpdateDescription**: Enable automatic updating of rig descriptions (disable, if you prefer to edit your rig descriptions online at MRR) [default=1]

**Comment by acos0874** [comment]
Tah very much
null

**Comment by acos0874** [comment]
The autoprice seems to be working but not the description updates. Is there a maximum length?

**Comment by RainbowMiner** [comment]
That last update should help. I am testing, currently.

**Comment by RainbowMiner** [comment]
Too bad - that doesn't work, currently. I have forwarded the request for changeable descriptions to merc at MRR and disabled the new code, for the time being (c8a64372cd3900c855888f85b94f109d9e8ce69c). There is a good chance, that merc will implement that feature.

**Comment by RainbowMiner** [comment]
Ha! Got it working, now. It's an undocumented API feature.

**Comment by acos0874** [comment]
Awesome :)

**Comment by acos0874** [comment]
Confirmed working. Thanks again!
