### ISSUE TITLE
Error I cant seem to find where.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1064]
Been getting this error for sometime now. I run this system headless normally so I didnt see the following. This is the second time i've got it.

This is the only system that is doing it, So when I have the time ill simple re-load it.

And actually now I cannot get the script to load at all. I keep getting the same error. Was thing to get it started to get the De-bug file.

![image](https://user-images.githubusercontent.com/4724631/85026820-047af380-b12e-11ea-803e-161702366699.png)

**Comment by Yamanipanuchi** [comment]
After starting several times it seems to come back up.. 
[debug_2020-06-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/4798964/debug_2020-06-18.zip)

**Comment by RainbowMiner** [comment]
Woa! Segmentation fault isn't too good, since it cannot be traced back. It's clearly related to either a hardware problem (possibly CPU or DRAM rates), or some damaged parts of powershell. My gut feeling tells me it's a DRAM timing problem, but I could be wrong.

**Comment by RainbowMiner** [comment]
How much DRAM are installed in that pc?

**Comment by Yamanipanuchi** [comment]
System is running 4gb. Usually not a problem with Linux. Maybe it is in this case?

**Comment by Yamanipanuchi** [comment]
Actually its running 8gb, Unless you are referring to the Video ram?

![image](https://user-images.githubusercontent.com/4724631/85035193-c4207300-b137-11ea-9513-53f3f9be800a.png)

**Comment by RainbowMiner** [comment]
8gb is perfect, 4gb should be enough, too. So it could be very probably a timing problem, with CPU or DRAM, or both (bus timings), that might happen, if the components getting hot.
You could check the BIOS setting, the connection of the heat sink to the CPU, the DRAMs (perhaps run some memtest tools).

**Comment by RainbowMiner** [comment]
Yes, the powershell script uses pretty much of the memory and has therefor a much larger possibility of being hit by timing problems. The mining applications are very specialized and mostly with a very small footprint. Anyway, these can be killed as well. It's a question of luck.

**Comment by Yamanipanuchi** [comment]
I suspect your right. This Rig is a weird setup. Ill just put a band aid script in plat that will simply reboot the system and call it there.
