### ISSUE TITLE
Nimiq Not Showing

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1065]
I've added a NIM wallet and set "EnableAutoPool": "1", in coins.config.txt  and "EnableAutoCoin": "1", in pools.config.txt for icemining.ca but no benchmark takes place.  Argon2d is the algo and NoncerPro is a gpu miner.  I think it can be mined with a cpu as well.

**Comment by RainbowMiner** [comment]
Did you try to directly add your wallet in pools.config.txt?
`"NIMQ": "$NIMQ",`
.. just to be sure.

**Comment by jch9678** [comment]
I did but I used NIM instead of NIMQ so that is probably the problem.

**Comment by RainbowMiner** [comment]
Ah, sorry, my bad. I had a typo. Of course, it is NIM - I'll check what is going on.

**Comment by RainbowMiner** [comment]
Yea, there was something wrong, with NIM. I have cleaned up the database and added the NoncerPro miner for CUDA and OpenCL. It should be possible to mine NIM on Icemining, now.

**Comment by jch9678** [comment]
Thank you very much.

**Comment by jch9678** [comment]
Just an fyi, Teamred Nimiq is not working with your implementation on .7.6.2    
.7.6.3 should be much simpler and does work with their example script.   With the new version the proxy is included so you can just use the pool's address.  Also it can't connect through ssl, only tcp so that has to be changed in your implementation
Thanks for getting it going.

**Comment by jch9678** [comment]
4.5.9.5 won't benchmark Nimiq for TeamRed.  Looks like the algo got erased for that miner.  It works for NoncerPro though.

**Comment by jch9678** [comment]
Actually NoncerPro is not working but for a different reason, it benchmarks just fine but RM doesn't record the hashrate and logs it as Failed.

Sorry this coin is such a pain.

**Comment by jch9678** [comment]
[debug_2020-06-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/4816203/debug_2020-06-22.zip)

**Comment by jch9678** [comment]
I think NoncerPro needs --api in addition to --apiport

**Comment by RainbowMiner** [comment]
Ok, I have fixed the Teamred/Nimiq - let's have a look into NoncerPro, now. "--api" should be enabled, by default.

**Comment by RainbowMiner** [comment]
> "--api" should be enabled, by default.

Oh! The OpenCL version for AMD is on an older number (v3.0.2). That version has the api disabled, by default. So enabling should solve that problem.

**Comment by RainbowMiner** [comment]
Eventually solved.
