### ISSUE TITLE
Smoother end to rentals

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1067]
At the end of a rental, RBM doesn't seem to shut down the miner until the pool stops responding. It then counts this as a crash.

**Comment by Adiuk** [comment]
I think its more dependant on how long your usual cycle time is, mine finishes ok every time and doesn’t crash but sometimes have to wait for the cycle to finish and start next run.

**Comment by RainbowMiner** [comment]
> At the end of a rental, RBM doesn't seem to shut down the miner until the pool stops responding. It then counts this as a crash.

That's actually not possible, at the moment we have to wait for the miner to crash, or that the current RainbowMiner round ends.
But I have another idea - MiningRigRentals automatically switches to the user's pool, if one has been setup. So, we could eventually add our own pools during create/update of the rigs. I'll try to figure something out.

**Comment by Adiuk** [comment]
I do wonder if this is the reason my windows os has been restarting due to an apparent crash, only started happening a week or so ago?

**Comment by samdave123** [comment]
> 
> 
> I do wonder if this is the reason my windows os has been restarting due to an apparent crash, only started happening a week or so ago?

I doubt it would cause Windows to restart as it wouldn't be a hardware error. It did trigger RBM's watchdog once for me, and also it makes maintenance more difficult as I usually check my logs once a month to see if there's been any instability, and there's so many false reports because of MRR.

**Comment by Adiuk** [comment]
I think it might be my power supply on the way out! All I can get from event viewer is kernel fault due to restart/crash/power loss, only program I run is RBM so it’s not like I have multiple things running to cause it. Just thinking out of the box because it has never happened before but literally 4 times in last few days.

**Comment by RainbowMiner** [comment]
> I think it might be my power supply on the way out! All I can get from event viewer is kernel fault due to restart/crash/power loss, only program I run is RBM so it’s not like I have multiple things running to cause it. Just thinking out of the box because it has never happened before but literally 4 times in last few days.

Yes, that very probably sounds like a hardware issue. Either with the riser cards, or, most probably with the power supply.

**Comment by samdave123** [comment]
I think this should be closed as it is now implemented.
