### ISSUE TITLE
One rig ignoring nicehash ethash

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1069]
It's fine on my other rigs, which are all in server-client mode, but for some reason this one rig constantly ignores nicehash ethash and selects zergpool ethash instead

[debug_2020-06-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/4812531/debug_2020-06-22.zip)

**Comment by acos0874** [comment]
I suspect it might be something to do with the price vs stable price, because I'm getting significantly different values depending on the rig.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/85278060-4ed8d900-b47c-11ea-935e-32fe5e74c769.png)
for some reason this whole rig is being glitchy. Nicehash is going right to the bottom for every algo.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/85278145-716af200-b47c-11ea-8dcb-4b5561b2d8b3.png)
Oh it looks like it might have suddenly corrected itself on a restart.

**Comment by RainbowMiner** [comment]
It could be the case, that it has fallen out-of-sync with the Nicehash API, for some reason.
