### ISSUE TITLE
Q&A: OCProfile config guide

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#107]
Just wondering what would happen if in miners.config I set the ocprofile to a clock and then set it different within AF under the same profile number. Would one trump the other? If so which one would override? Would it crash? I would like to begin to adjust clocks for different algos. Would it make more sense to just set custom clocks for algos only and not individual miners? Since there are multiple miner that can run the same algo, It makes more sense to just set one ocprofile for an algo and just exclude the miners you don't want to run. This would be less work and less confusing in the config. Plus prevent a miss on setting a specific miners ocprofile. Also, what is the difference between ocprofile and MSIprofile exactly? It seems redundant to allow both and I would think it may cause an issue with AF. I would be happy with just pushing clocks to MSI and let it handle the ocprofiles. You really should not need more then 5 profiles to cover all algos. At least I never have. Just food for thought.

**Comment by RainbowMiner** [comment]
> Just wondering what would happen if in miners.config I set the ocprofile to a clock and then set it different within AF under the same profile number. Would one trump the other? If so which one would override? 

Only one of the two OC options can be enabled:
- "EnableOCprofiles" = "1" enables ocprofiles.config.txt and disables AB profile switching
- "EnableOCprofiles" = "0" & "MSIAprofile" = "1"/"2".."5" enables AB profile switching, ocprofiles.config.txt will be disabled
- "EnableOCprofiles" = "MSIAprofile" = "0" disabled both

The differences:

|   |MSIAprofiles|ocprofiles| 
|---|:---:|:---:|
|Can handle parallel miners on different GPUs|no|yes|
|Depends on Afterburner|yes|no|
|Depends on nvidiaInspector|no|yes|
|Speed with more than 6 GPU|slow|fast|
|Works for Nvidia|yes|yes|
|Works for AMD|yes|no|
|max. number of profiles|5|unlimited|
|Individual profile names|no|yes|

t.b.c.

**Comment by RainbowMiner** [comment]
>  I would like to begin to adjust clocks for different algos. Would it make more sense to just set custom clocks for algos only and not individual miners?

Oh yes, this is something I had in mind for some time now. At the moment you will have to search for every occurence of the algorithm in miners.config.txt and set a profile. I will implement this asap.

**Comment by Byrd1083** [comment]
E few algos seem to run better at 80% power. Check my thread as I updated it.

**Comment by Byrd1083** [comment]
Excellent documentation. I might request this to be added to the readme file in master. 👍

**Comment by RainbowMiner** [comment]
Fine :) I will add it.
