### ISSUE TITLE
Question: API or calculators?

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1070]
Referring just to non-autoexchange pools, I know some pools use calculators and some pools have an API for their profitability. The problem is, if I wanted to mine for example Ethereum directly, how can I tell for myself what the source is? I don't trust using the calculator websites as their data is delayed.

**Comment by acos0874** [comment]
Specifically for ethereum, is f2pool on their own API and Sparkpool based on wtm data?

**Comment by RainbowMiner** [comment]
Click the "+" on one of the currently used pool on "Best Pools" page and look for 
![image](https://user-images.githubusercontent.com/39437538/85305063-d0485f80-b4ac-11ea-986a-0582addee988.png)

.. if "WTM: true" is there, then the calculators are being used.

**Comment by acos0874** [comment]
oh ace! Nice one!

**Comment by RainbowMiner** [comment]
> Specifically for ethereum, is f2pool on their own API and Sparkpool based on wtm data?

Both pools have their own profitability API

**Comment by acos0874** [comment]
Ok so do you have any idea why Sparkpool and wtm are showing a much higher estimate f2pool, nicehash and miningpoolhub right now?

**Comment by RainbowMiner** [comment]
Are SparkPool and WTM results very near?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/85305935-a8093280-b4a5-11ea-9983-32e2b58354b3.png)
wtm

![image](https://user-images.githubusercontent.com/42582444/85305979-be16f300-b4a5-11ea-965e-d3e67a6bab07.png)
sparkpool

![image](https://user-images.githubusercontent.com/42582444/85306022-cf5fff80-b4a5-11ea-8911-8850f3402279.png)
f2pool

![image](https://user-images.githubusercontent.com/42582444/85306096-e69eed00-b4a5-11ea-91e9-a15a56a58985.png)
nicehash

![image](https://user-images.githubusercontent.com/42582444/85306114-ef8fbe80-b4a5-11ea-9ffa-aafac7d43719.png)
minerstat

**Comment by acos0874** [comment]
Maybe I'm looking at the penalised prices when I should be looking at the stable price?

**Comment by RainbowMiner** [comment]
Oh, I just remember one thing: https://decrypt.co/32436/more-than-2-million-worth-ethereum-goes-unclaimed

.. if this is still happening, then the income in fact _is_ higher on SparkPool

**Comment by RainbowMiner** [comment]
.. but that would be on the long run, only. So if you are lucky enough to mine into a block, that gets that much gas, you are the happy one. If you do not rely on luck, I'ld rather put a small penalty on SparkPool

**Comment by acos0874** [comment]
Yes I assumed they would distribute it retrospectively to miners who were mining at the time of the block, but I guess you are saying they will distribute it over the coming days?

**Comment by acos0874** [comment]
It looks like the gap has closed now. Maybe there was just another high fee block that sparkpool was able to switch to mining first before the other pools. I've never fully understood how block selection on a pool works. So let me see if I can figure this out for myself...

step 1: Sparkpool, F2pool and MPH all run their own nodes +mempools

step 2: The nodes consolidate transactions based on on highest fees first and start working on creating a block.

step 3: a new transaction comes in with a high fee, but the pools don't restart the block, they wait until the current block is finish????

step 4: sparkpool was the first to solve their block so they can start work on a new block with the higher transaction fee first

If this is true, doesn't it mean that pools with the highest hashrate will always end up with better rewards? Since they are able to solve blocks faster and hence can capture the transactions with the highest fees faster?

**Comment by acos0874** [comment]
Haha sorry, I don't like not understanding why things behave unexpectedly!

**Comment by acos0874** [comment]
Another question: Do the f2pool and sparkpool APIs give a BTC/GH/DAY figure or do they give hashrate, difficulty etc,... and then RBM does a calculation?

**Comment by RainbowMiner** [comment]
Both pools return a complete BTC/GH/Day value

**Comment by RainbowMiner** [comment]
> If this is true, doesn't it mean that pools with the highest hashrate will always end up with better rewards? Since they are able to solve blocks faster and hence can capture the transactions with the highest fees faster?

Actually, it's always about luck. As long as the pool's hashrates do not differ by a magnitude, the effect of different hashrates should be neglectable, over time.
