### ISSUE TITLE
Equihash 210,9 with MRR

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1075]
Please can you check the personalisation options are compatible with MRR? I suspect there may be some new coins other than AION and at the moment I've picked up a rental with lots of issues. MiniZ doesn't even work at all.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/85553022-7ade9080-b61b-11ea-9c4c-6c3a0908b52b.png)

![image](https://user-images.githubusercontent.com/42582444/85553066-85992580-b61b-11ea-9722-d7b9f006ac8f.png)

**Comment by RainbowMiner** [comment]
Thank you for checking this with merc. Most of the times (like 99%) it's a renter issue, if such things happen. Anyway, RainbowMiner will use a fallback strategy - if a rental fails for some time, RainbowMiner will do some normal mining for 15 minutes before retry with MiningRigRentals. This helps to reduce the effect of inefficient rentals.

**Comment by acos0874** [comment]
Yes it's just unfortunately in this case, gminer seemed to be still submitting some shares for some reason which kept it alive.
