### ISSUE TITLE
MRR Logs

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1076]
I'm still having a few difficulties with some dodgy MRR rentals. Based on the past issue I had to be active in checking the rig after the fact and providing evidence that it wasn't my rig at fault. I'm finding it quite a lot of hassle to keep an eye on things and trouble shoot, but I just had an idea.

Would it be possible to keep a separate logs folder whenever a MRR rental starts? That way if there is a problem it'll be easy to find logs that can then be passed directly onto the MRR support team.

**Comment by RainbowMiner** [comment]
> Would it be possible to keep a separate logs folder whenever a MRR rental starts? That way if there is a problem it'll be easy to find logs that can then be passed directly onto the MRR support team.

Actually, separate logs for MRR is a really good idea. Ok, I'll try to add something.

**Comment by acos0874** [comment]
Awesome as always

**Comment by acos0874** [comment]
Did this get added? I seem to recall it showing up somewhere but I don't think my rigs are logging anything.
