### ISSUE TITLE
Idea about individual cards

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1078]
Just for fun (and perhaps a bit more profit), I was thinking about creating separate workers for each card a bit like how nicehash miner works, but also make the cards individually available on mrr, which I think would increase their chances of being rented. So I was thinking that it would be fairly automated if I just add some work names into the gpugroups.config file like follows...

{
  "GPU#00": "1660ti#0",
  "GPU#01": "1660ti#1",
  "GPU#02": "1660ti#2",
  "GPU#03": "1660ti#3",
  "GPU#04": "1660ti#4",
  "GPU#05": "1660ti#5"
}

I'm reluctant to just throw settings in, in case I break my existing rig set up. Do you see this working as I intended?

**Comment by acos0874** [comment]
Correction, I think I would need to do the above but then also given them each a worker name in devices.config??

**Comment by RainbowMiner** [comment]
To be able to totally separate the GPUs, you would need to
- set groups in gpugroups.config.txt
- then restart RainbowMiner (it should now create 6 new devices in device.config.txt)
- then give the 6 devices individual Worker names.

The gpugroups.config.txt parameters are strings, that will be concatenated to the orignal device name. E.g. you could just input
```
{
"GPU#00": "A",
"GPU#01": "B",
"GPU#02": "C",
"GPU#03": "D",
"GPU#04": "E",
"GPU#05": "F"
}
```

.. that would create 6 devices: GTX1660TiA .. GTX1660TiF

But make 100% sure to switch "MiningMode" to "Device" in config.txt. Combo mode would max out your machine, since it would have to calculate all possible combinations of 6 different devices.

**Comment by acos0874** [comment]
Thanks, and in regards to OC profiles, should I set up individual GPU OCs or can it just take them per card automatically?

**Comment by RainbowMiner** [comment]
You could also break the GPUs into groups of 2 or 3.
```
{
"GPU#00": "A",
"GPU#01": "A",
"GPU#02": "B",
"GPU#03": "B",
"GPU#04": "C",
"GPU#05": "C"
}
```

```
{
"GPU#00": "A",
"GPU#01": "A",
"GPU#02": "A",
"GPU#03": "B",
"GPU#04": "B",
"GPU#05": "B"
}
```

**Comment by RainbowMiner** [comment]
> Thanks, and in regards to OC profiles, should I set up individual GPU OCs or can it just take them per card automatically?

Duh, I am not sure :) I'll have to check this.

**Comment by acos0874** [comment]
> Be aware, that all specific miner setting in miners.config.txt will have to be updated for the new algorithm-device combinations.

I think based on this I may have to give it a miss, since I use different OC Profiles than the standard ones in the original config files.

**Comment by RainbowMiner** [comment]
So did you setup the OC Profiles in miners.config.txt?

**Comment by acos0874** [comment]
Generall I use 
Profile 2 +core and +mem
Profile 4 +core and -mem
Profile 5 specific to ethereum

Profile 1 and 3 are for higher core voltages.

but the optimal profile for the algo varies depending on the card model. So for example...

1660tis and 2070 supers on kawpow are optimal on profile4 (-mem) (set in the algorithms.config) whereas 1070tis on kawpow are optimal on profile2 (+mem) (set in the miners.config). So they behaved very differently. 

So yes my miners.config is a bit of a mess of different settings. A way round this would be for me to use a more general OC across all algos.

**Comment by RainbowMiner** [comment]
> > Be aware, that all specific miner setting in miners.config.txt will have to be updated for the new algorithm-device combinations.

> I think based on this I may have to give it a miss, since I use different OC Profiles than the standard ones in the original config files.

That would result in a very simple copy and paste task, aktually. Just take your current miners.config.txt, copy everything between `[` and `]`, then paste it into a notepad and find-and-replace GTX1660Ti with GTX1660TiA - now copy it back into your orignal miners.config.txt, don't forget to add a `,` after the last entry of the original block.

**Comment by acos0874** [comment]
Ok that makes sense.

**Comment by RainbowMiner** [comment]
It's a bit of a hazzle, and it might brake the JSON syntax, so always use JSONlint to verify the syntax.

**Comment by RainbowMiner** [comment]
.. oh, and - Backup first

**Comment by RainbowMiner** [comment]
> 1660tis and 2070 supers on kawpow are optimal on profile4 (-mem) (set in the algorithms.config) whereas 1070tis on kawpow are optimal on profile2 (+mem) (set in the miners.config). So they behaved very differently.

That's interesting. I didn't know the GTX1070tis prefer +mem.

**Comment by acos0874** [comment]
It appears so, but keep in mind I'm using locked voltages. It might behave differently when using a power limit. I get an average 14.8mh/s at 115W. I don't think the same is achievable using a power limit but I could be wrong.

**Comment by acos0874** [comment]
Ok this seems to be up and running fine. Would you say disabling "Show miner window" would have any effect on CPU usage?

**Comment by RainbowMiner** [comment]
> Would you say disabling "Show miner window" would have any effect on CPU usage?

Only, if you operate your rig from a very slow harddisk. If you are using a SSD, it should have near to no impact.

**Comment by acos0874** [comment]
Thanks. If I kept the listing for the whole rig as one, would it automatically disable the listings for the individual rigs?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/86241645-33b44a80-bb9b-11ea-8643-e10559260d8f.png)
I got a rental on the whole rig and the individual cards are still showing as available.

**Comment by RainbowMiner** [comment]
I'll better have a look into this. Could you send me a current Debug file?

**Comment by RainbowMiner** [comment]
Ok, this fix should do the job.

**Comment by acos0874** [comment]
Sorry I got distracted. Adding includeworkername to include only the full rig names worked.

**Comment by acos0874** [comment]
Gonna hijack this thread for something else though. I have one rig with 4gb RAM and 6 cards. RAM usage is pushing up again it's limit. Are there any settings you'd recommend to reduce RAM usage. Maybe hiding the miner windows, or a PWSH setting?

**Comment by acos0874** [comment]
Oh and would it be possible to change the default sorting option on running miners to devices? This way it'll coincide with the device status section. Please and thank you!

**Comment by RainbowMiner** [comment]
> Gonna hijack this thread for something else though. I have one rig with 4gb RAM and 6 cards. RAM usage is pushing up again it's limit. Are there any settings you'd recommend to reduce RAM usage. Maybe hiding the miner windows, or a PWSH setting?

Could you eventually upload a Debug file? Maybe I can find some hints in the log files.

**Comment by acos0874** [comment]
[debug_2020-07-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/4859887/debug_2020-07-01.zip)

Everything seems to be going well for the moment, although switching algos/opening new miners does appear a bit sluggish. 

Would you also help me understand how I could go about setting up the following combination of workers?

gpuA
gpuB
gpuC
gpuD
gpuE
gpuF
gpuA+gpuB+gpuC+gpuD+gpuE+gpuF

So I only have 7 sets of calculations to do renters could potentially rent either individual cards or the whole rig in one go?

**Comment by RainbowMiner** [comment]
That should already be the case, with your current setup. Did you start the whole rig-A..F with combo mode? If yes, you will now have tons of rigs at MRR. Just delete all combi-rigs at MRR, so that you get rid of them.

**Comment by acos0874** [comment]
> [debug_2020-07-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/4859887/debug_2020-07-01.zip)
> 
> Everything seems to be going well for the moment, although switching algos/opening new miners does appear a bit sluggish.
> 
> Would you also help me understand how I could go about setting up the following combination of workers?
> 
> gpuA
> gpuB
> gpuC
> gpuD
> gpuE
> gpuF
> gpuA+gpuB+gpuC+gpuD+gpuE+gpuF
> 
> So I only have 7 sets of calculations to do renters could potentially rent either individual cards or the whole rig in one go?

I've set up in combo mode and using the combos.config to disable all but the above combinations. It seems to be working as intended except that RBM is incredibly slow to load up (even though the CPU and RAM don't seem to be maxxed out).

**Comment by acos0874** [comment]
It was working fine for a time by switching back to device mode and deleting the miners.config file. However, I had to reboot and now it keeps creating the all the combinations again in the mienrs.config file, even though I'm in device mode. 😢

**Comment by RainbowMiner** [comment]
Oh! Really? I'll better have a look, then. It should not not create all combinations.

**Comment by RainbowMiner** [comment]
Ok. Fixed. It will now no longer create combo entries in miners.config.txt, if MiningMode is not set to "combo".

**Comment by acos0874** [comment]
Thanks. Now if I set mining mode to combo, will it only create entries in the miners.config file for 

gpuA
gpuB
gpuC
gpuD
gpuE
gpuF
gpuA+gpuB+gpuC+gpuD+gpuE+gpuF

This would be ideal for MRR setups.

**Comment by RainbowMiner** [comment]
No yet. I'll add this, too.

**Comment by acos0874** [comment]
That would be great thanks. In the interim, I can get round this by running without device groups to get a combined hashrate then letting the rig run with device groups.

**Comment by acos0874** [comment]
Is it possible that a renter could rent the individual cards and the whole rig if they placed the order simulataneously?

**Comment by RainbowMiner** [comment]
> Is it possible that a renter could rent the individual cards and the whole rig if they placed the order simulataneously?

Yes. That might happen, even though it didn't happen to me in two years, now. So I consider this pretty uncommon.
There is one new API feature at MRR, considering virtual groups. I am on the way to make use of this. It should avoid exactly that possibility of double renting, like you described.

**Comment by acos0874** [comment]
I just wanted to let you know that I've stopped using individual cards. I found that although it gave me more granular control over and more information about the cards, it also added extra work in terms of setting parameters for every card and making sure whole rig benchmarks are up to date.

**Comment by samdave123** [comment]
I'm testing this now and I'll provide more feedback later. The only suggestion I have so far is that there needs to be a way to set up MRR rigs in legacy mode so that all GPUs get rented together.

**Comment by samdave123** [comment]
This has been working really well for me for weeks now.

**Comment by RainbowMiner** [comment]
Super! Thank you for that feedback!
