### ISSUE TITLE
Enhancement: Reset AF profile before applying new profile

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#108]
I noticed that it helps to push the clock reset button in the middle of AF before applying a new clock rate when benching/testing clocks. This might help when a custom has been applied and the next miner/algo switch has not been tested yet causing that new miner to hold the last profile and crash. AF needs that reset push when a miner closes for switch to prevent this from happening. 

For example I set a custom clock for trex that was stable. Then an auto switch occurred changing to x16r and that algo could not run on that clock so it froze up system. If the AF was reset this would have prevented the crash and allow a new push of custom profile or me manually adjusting on the fly for testing clocks.

**Comment by Byrd1083** [comment]
Yes, that would work. Just FYI I know that will screw up AMD drivers though. They do not like to be manipulated through MSI yet if you open MSI, it will register it. I can see that being a future issue trying to reset the AMD to stock and tripping out AMD driver profiles. I use MSI only to monitor.

**Comment by Byrd1083** [comment]
Hope you can give a friend a little credit in the end of all this. ;-) 💯 🥇

**Comment by RainbowMiner** [comment]
> Hope you can give a friend a little credit in the end of all this. ;-) 💯 🥇

Ya, we can talk about this :)

**Comment by Byrd1083** [comment]
Awesome, a 24 hour donation will be coming your way when I get these rigs stable and benched 💯
