### ISSUE TITLE
MiniZ Beamhash3 won't work

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1081]
I recently installed the recommended drivers.

Error
Cannot read health status! (is libnvidia-ml.so installed?): No such file or directory

**Comment by RainbowMiner** [comment]
Are you using `--ocX` in the miners options?

**Comment by samdave123** [comment]
Using the default:

Arguments: "--telemetry $mport -cd 0 1 4 --server beamv3.eu.nicehash.com --port 3387 --user 3M73gP6x55C7nws3ie7UwCHpy5tDDVLwHN.GTX1660TIs --pass x --pers Beam-PoW --gpu-line --nonvml --extra --latency --nocolor --par=144,5s"

**Comment by acos0874** [comment]
Is the par 144,5s correct?

**Comment by samdave123** [comment]
There's nothing else in the log file other than the error I posted earlier.

**Comment by samdave123** [comment]
I used +0/+900/650mv on my 1660Tis. Should be very safe OC settings. It's affecting both my 1070Tis and 1660Tis so I don't think it's the OC settings.

**Comment by RainbowMiner** [comment]
> Is the par 144,5s correct?

Yes, Beamhash3 is a bit like Equihash 144,5 plus siphash.

I wonder, what is happening, since it works perfectly well on my rigs. Could you eventually re-run Install.bat (as admin), just to make sure nvidia-smi.exe and nvml.dll are in place?

**Comment by RainbowMiner** [comment]
What is the Nvidia driver version on your rig?

**Comment by samdave123** [comment]
441.34

**Comment by RainbowMiner** [comment]
Sounds perfectly ok. I am testing 441.41 since some time now, and that version seems to work out, too. I'll eventually update the recommendations.

Does this folder exist: `C:\Program Files\NVIDIA Corporation\NVSMI`
.. and does it contain `nvml.dll` and `nvidia-smi.exe` ?

**Comment by samdave123** [comment]
Yes, they are there. I am wondering if there's an issue with running Beamhash3 at too low of a voltage?

**Comment by RainbowMiner** [comment]
> Yes, they are there. I am wondering if there's an issue with running Beamhash3 at too low of a voltage?

I don't think so. The error message is indicating to some driver resources missing. You could try to upgrade your drivers to 441.41 - if you are lucky, it fixes the problem.

[Nvidia Driver Version v441.41 - Standard - Windows 10](https://www.guru3d.com/files-get/geforce-441-41-whql-driver-download,1.html)
[Nvidia Driver Version v441.41 - DCH - Windows 10](https://www.guru3d.com/files-get/geforce-441-41-whql-driver-download,2.html)
[Nvidia Driver Version v441.41 - Standard - Windows 7,8,8.1](https://www.guru3d.com/files-get/geforce-441-41-whql-driver-download,3.html)

**Comment by RainbowMiner** [comment]
I have found a workaround for BeamHash3 on MiniZ - everything should be fine, now.

**Comment by samdave123** [comment]
Seems to be working.
