### ISSUE TITLE
MRR Beamhash3 not working

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1082]
It looks like the algo pairings aren't correct. Maybe on the MRR API? I got a beamhash3 rental but rbm was selecting beamhash2.

**Comment by RainbowMiner** [comment]
This is fixed with release v4.5.9.9 - I have mapped the old MRR Equihash150 to new BeamHash3, temporarily.
The MiningRigRentals team will update their Beamhash sections within the next 24h, so expect another RainbowMiner release, then.
