### ISSUE TITLE
BeamHash3 benchmark reporting different values?

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1083]
It gave me these:
![image](https://user-images.githubusercontent.com/3217740/86008942-1e7cd600-ba4c-11ea-886b-b7db252bc9c9.png)

In dashboard, it shows Nicehash is mining at 154H/s BUT in nicehash the mining has 100% reject rate

**Comment by RainbowMiner** [comment]
These are two different miners. Lolminer is not yet optimized for Nvidia GPUs, whereas MiniZ is.

**Comment by astronyu** [comment]
In dashboard, it shows Nicehash is mining at 154H/s BUT in nicehash the mining has 100% reject rate

This is 6x 1060 6GB rig.

**Comment by astronyu** [comment]
![RBM MiniZ crash](https://user-images.githubusercontent.com/3217740/86011900-dbbcfd00-ba4f-11ea-9fa0-4c35595c605c.png)
[debug_2020-06-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/4845790/debug_2020-06-29.zip)

**Comment by astronyu** [comment]
I'm going to have to disable BEAM mining for now since I don't earned anything from it being 100% rejected and all. Will monitor this issue if there are any workaround.

**Comment by RainbowMiner** [comment]
I have just been discussing this issue on Discord - it seems like a MiniZ-on-Nicehash bug. It seems, that for some users the MiniZ simply switches to the old algorithm, even if we tell it to use the new one.

**Comment by RainbowMiner** [comment]
Yes, same thing with your rig. We start MiniZ with the correct command line:
`miniZ.exe --telemetry 30001 -cd 0 1 2 3 4 5 --server beamv3.hk.nicehash.com --port 3387 --user XXX.XXX --pass x --pers Beam-PoW --gpu-line --extra --latency --nocolor --par=144,5s`

.. but it selects the wrong algorithm "144,5" and not "144,5s", like we have instructed it.

**Comment by RainbowMiner** [comment]
I have forwarded this issue to the MiniZ developers.

**Comment by astronyu** [comment]
Noted, thanks for checking this one out. 
Will enable BEAM again once it is fixed.

**Comment by RainbowMiner** [comment]
@astronyu Could you eventually try the following?
- edit miners.config.txt
- find MiniZ-GTX10606G section
- find BeamHash3 in that section
- add `--par=beam3` to "Params", like that:
```
    {
      "MainAlgorithm": "BeamHash3",
      "SecondaryAlgorithm": "",
      "Params": "--par=beam3",
      "MSIAprofile": "",
      "OCprofile": "",
      "Difficulty": "",
      "Penalty": "",
      "Disable": "0"
    },
```

.. does this change anything?

**Comment by astronyu** [comment]
> 
> 
> @astronyu Could you eventually try the following?
> 
>     * edit miners.config.txt
> 
>     * find MiniZ-GTX10606G section
> 
>     * find BeamHash3 in that section
> 
>     * add `--par=beam3` to "Params", like that:
> 
> 
> ```
>     {
>       "MainAlgorithm": "BeamHash3",
>       "SecondaryAlgorithm": "",
>       "Params": "--par=beam3",
>       "MSIAprofile": "",
>       "OCprofile": "",
>       "Difficulty": "",
>       "Penalty": "",
>       "Disable": "0"
>     },
> ```
> 
> .. does this change anything?

I've made the changes and re-enable mining BeamHash3 again, we'll see what happen.

**Comment by astronyu** [comment]
@RainbowMiner , thanks that seems to be working. I was mining BEAM for almost an hour on nicehash and so far with 100% accepted hashes. NH reports my hashrate is around 54H/s although MiniZ benchmarked it at 70 H/s and lolminer at 49.9 H/s.

**Comment by RainbowMiner** [comment]
Thank you for reporting back :)

**Comment by RainbowMiner** [comment]
It looks like I could identify a problem with the PowerShell version 6.2.1, that you are using currently. I have already changed the core, so that it will return to full compatibility.

**Comment by astronyu** [comment]
Thanks for the fast action! Glad this one sorted out.
