### ISSUE TITLE
Donation fee goes haywire, takes control of my GPUs for too long and doesn't start my rental

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1084]
I think something went seriously wrong with the donations this morning. I got a great 1660Ti rental but RBM wouldn't start it because it got stuck on donations. Please can you take a look?

[debug_2020-06-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/4849368/debug_2020-06-30.zip)

**Comment by samdave123** [comment]
Looks like it got stuck in a weird loop of BeamHash3 on MRR and donation fees. Is RBM not disabling MRR rigs when I disable miners/algos on the Miners page?

![image](https://user-images.githubusercontent.com/56473344/86084345-8b1bc300-ba94-11ea-9323-dfabc29704e4.png)

**Comment by RainbowMiner** [comment]
Sounds strange! I will check asap.

**Comment by RainbowMiner** [comment]
I have checked the log files and there is no dev fee mining initiated, all miners mined for you. Can you provide some more information?
Sometimes it happens, that you get a bad renter (most of the times, they try to mine to pools, that are not compatible). If that happens, RainbowMiner will stop mining to MRR and retry every 15 minutes.

> Is RBM not disabling MRR rigs when I disable miners/algos on the Miners page?

Actually, no. The MRR rigs will be disabled for algorithms, only, if you have Algorithm/ExcludeAlgorithm setup in config.txt or pools.config.txt

**Comment by samdave123** [comment]
It was on Monero Ocean and Zpool and stuff which my rig will never mine because of 99% penalty, so I assumed it was devfee because those are the sort of pools that usually mine for you. I also got errors because of no wallet addresses and stuff. I guess someone RBM got confused and started mining for me but using donation settings? 

I'm struggling to explain it, but the profit-switching went absolutely wack doing all sorts of shitty algos on different multipools that it NEVER switches to with 99% penalty.

**Comment by RainbowMiner** [comment]
>  guess somehow RBM got confused and started mining for me but using donation settings?

No, these were all your 99% penalized pools. It looks like the pools went out of sync - if a pool's price nor hashrate doesn't update for one hour, the pool is basically dropped, until it comes back.
Could have been an internet outage, or a problem with a pool itself.

**Comment by samdave123** [comment]
Rig is stable, MRR benchmarking is added, I don't think this is an issue any more.
