### ISSUE TITLE
Pool Balance value no longer being calculated for XGM

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1086]
I'm using RB 4.6.0.0 and just notice in the last 24 hours that pool balance value is no longer being calculated for XGM?

![pwsh_2020-07-01_21-47-56](https://user-images.githubusercontent.com/17214552/86240585-d0e7a100-bbe4-11ea-90de-28d9ca6865eb.jpg)

**Comment by RainbowMiner** [comment]
I'll check the exchange API.

**Comment by RainbowMiner** [comment]
Ok, found it. Grimm has ditched symbol XGM for symbol GRIMM - I have just posted a commit to fix this.

**Comment by rizkyaulya** [comment]
I just upgraded to 4.6.0.0
I get worse only Coins that listed on MRR show pool balance
![image](https://user-images.githubusercontent.com/44210627/86273529-97219500-bbfa-11ea-84f2-74340fa1b5bc.png)

**Comment by RainbowMiner** [comment]
Oh! Sorry! I unintentionally stopped the currency proxy. It's back online, now. All currencies should be back, soon.

**Comment by RainbowMiner** [comment]
Pay attention: XGM is now being used by Defis, GRIMM stays Grimm. So I'll now remove the currency mapping in the proxy database.

**Comment by AnthonyBe** [comment]
I'm seeing this issue again for XGM on Sunpool
![cmd_2020-08-15_10-01-33](https://user-images.githubusercontent.com/17214552/90300560-5944ab80-dede-11ea-8bda-0a76945cc017.jpg)

**Comment by RainbowMiner** [comment]
Ah, I see. The internal exchange API's id has been changed for XGM. I'll fix it asap.

**Comment by RainbowMiner** [comment]
Ok. Solved. Your balance should be calculated correctly soon.

**Comment by AnthonyBe** [comment]
Thank you!
When you say 'soon', is that hours, or days?
Just clarifying so I know whether to report back that it is working or not (right now, still not).

**Comment by AnthonyBe** [comment]
Thank you! Working perfectly!
