### ISSUE TITLE
4.5.9.9 & 4.6.0.0 Not Mining Most Profitable

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1087]
[debug_2020-07-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/4858666/debug_2020-07-01.zip)

I can't see a reason for it not to.

**Comment by jch9678** [comment]
Somewhat same issue:  could you please add this miner  https://github.com/tomkha/nq-miner

**Comment by RainbowMiner** [comment]
Ok, Nqminer v0.99.7 added

**Comment by samdave123** [comment]
Do you have heat control enabled? I use this feature in the summer to mine more efficient algorithms to reduce heat rather than most profitable.

**Comment by jch9678** [comment]
I don't unless it was enabled by default.
