### ISSUE TITLE
DEFIS XGM mining on ravepool

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1088]
Is DEFIS XGM mining support on ravepool?
https://defis.ravepool.com

If not, could it be added?

**Comment by RainbowMiner** [comment]
Sure. I have enabled Defis/XGM on Ravepool and Sunpool. Be aware, that I have just re-updated the above commits with f8cae9e400e6320a58c1f55983e8270862253521, 147dc5d35c7d0a689436238154abfd8b27b5b6f2, dc82064f1136509da7902baadd8eec66ad2c8a7d, c21459d4f2bf13509ee14d083c4349cf3df1fe44
