### ISSUE TITLE
Issue: Miners force MSI AF profiles to stock

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#109]
Coolminer is not allowing custom profiles. As soon as it opens it will force stock clocks and power. You can manually push the profile through AF but it will immediately force stock.

**Comment by RainbowMiner** [comment]
Oh, too bad! Then this miner takes control over the GPU.

**Comment by Byrd1083** [comment]
Yes crypto-dredge -cryptonightV7 is doing this as well.

**Comment by Byrd1083** [comment]
Here it is in action.

![image](https://user-images.githubusercontent.com/42227809/45061501-9a2cb800-b059-11e8-99ce-0515fb69bdfb.png)

**Comment by Byrd1083** [comment]
I will report them here as I go.

**Comment by RainbowMiner** [comment]
Wow, that is how they produce the higher hashrates. They mess with the GPUs. Yes, a list will be very helpful.

**Comment by Byrd1083** [comment]
Would locking mV to say 760mV in custom ocprofile fix this you think if using inspector instead of MSI.

**Comment by RainbowMiner** [comment]
Eventually. Well, my gut feeling says no, but it would be worth a try, anyway.

**Comment by Byrd1083** [comment]
2018-09-04 19:44:23 INFO: Benchmarking miner (CcminerAlexis78-GPU#00): 'C:\Mining\RainbowMiner-master-working\Bin\NVIDIA-Alexis78\ccminer.exe -R 1 -b 10200 -d 0 -a x17 -q -o stratum+tcp://blockmasters.co:3737 -u 3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1 -p rig1,c=BTC -N 1' (Extend Interval 0)
2018-09-04 19:44:23 INFO:  miner CcminerAlexis78-GPU#00 closed gracefully
