### ISSUE TITLE
WARNING: Pool API (Ravepool) for XGM has failed

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1091]
I started getting this error on startup and each subsequent balance check in the last 24 hours:
`WARNING: Pool API (Ravepool) for XGM has failed`

error from asyncloader log file
`[2020-07-05 00:03:08] Error job 5C697BA59831DE08A9F4C9080BCA899F with https://defis-api.ravepool.com/v2/poolStats using REST: Problem fetching https://defis-api.ravepool.com/v2/poolStats using REST: The operation was canceled.`

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll check the balance API for XGM.
