### ISSUE TITLE
Benchmarks for MRR

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1092]
I'm aware that rbm will force the highest hashrate miner when an order is place, but please can you confirm that the hashrates set for being used for MRR rigs come from the highest miner? I just had some strange behaviour where my advertised grimm hashrate is 188 with gminer and 201 with miniz and the advertised hashrate comes out at 186.

**Comment by RainbowMiner** [comment]
Yes, it should always the highest possible hashrate, currently. I will check, to be sure.

**Comment by RainbowMiner** [comment]
Question: do you have setup penalties for miniz and grimm?

**Comment by acos0874** [comment]
Not that I'm aware of
