### ISSUE TITLE
MiningPoolHub Earning events 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#1093]
I'm not seeing any of the earning events for miningpoolhub. 

I'm really trying to hammer out my states so i can present RBM to someone but i have a lot of missing data right now. 

Having this issue with several pools.

**Comment by RainbowMiner** [comment]
I'll check the MiningPoolHub balance module. Which pools fail there, too? Some few pools have no balance module.

**Comment by ngiotta** [comment]
Just wanted to 2nd this.  I mine all the time on MiningPoolHub (apparently) and never see my pool balance listed.

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
