### ISSUE TITLE
Dev fee crashes rig

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1095]
My rig was all nice and stable until the devfee came along and crashed it.

Your worker "NvidiaRig" has gone offline.

Last seen: 2020/07/07 22:44:10 UTC

Miner(s):
- CcminerVerus mining VerusHash at ZergPoolCoins on GTX1660Ti
- NoncerProNvidia mining Argon2dNim at Icemining on GTX1070Ti

I checked the Reliability History and have no hardware errors. It was stable before the devfee and stable after I restarted RBM. What happened?
[debug_2020-07-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/4887572/debug_2020-07-08.zip)

**Comment by samdave123** [comment]
Found this in the log file, is it relevant?
"Error from pool: invalid share: invalid pow"

I've disabled these two algorithms for now in case they were issues.

**Comment by RainbowMiner** [comment]
Thank you for reporting this!

This is what gives us a hint at hand:
[2020-07-07 23:46:14] INFO: NiceHash loaded in 53.668s 
[2020-07-07 23:48:44] INFO: ZergPoolCoins loaded in 150.4s 
[2020-07-07 23:48:44] INFO: Updating pool balances. 
[2020-07-07 23:49:59] INFO: WhatToMine loaded in 40.059s

.. these super-long loading times of the pools indicate, that there has been either a very slow internet connection, or too much load on the CPU (I suspect the second). I cannot see, which of the two miners did cause such a load, but I suspect the CcminerVerus. I'll see, if it's CPU load can be reduced via some command line parameters.

**Comment by samdave123** [comment]
This might have been an issue with my hardware.

**Comment by acos0874** [comment]
CPU load could definitely be it. It's best to be selective with miners. I have everything enabled on my gaming PC to see if there's anything that makes the cut, but then have a shorter list on my rigs. This also helps with benchmarking time. Could this also be what is causing your crashes with your newest card? 

If the rig becomes unresponsive then this would suggest maxxed out CPU.

**Comment by RainbowMiner** [comment]
I agree. Another way is to check for the affinity values in the config.txt.

**Comment by Cryptominer937** [comment]
I have had RBM crash my rig in devfee as my AMD cards are very tweaked for KAWPOW and even though cryptonight variants are disabled the devfee still tries to use them and causes the rig to reboot.
My solution was to block monero ocean via a hosts file edit.

**Comment by RainbowMiner** [comment]
@Cryptominer937 Oh! That is good to know. Thank you for reporting this. I will think about a better handling. Actually, the donation round respects the two settings "Algorithm" and "ExcludeAlgorithm" in config.txt.

**Comment by Cryptominer937** [comment]
Right but I don't mine to Monero ocean. My thought would be to make the devfee respect the enabled pools.

**Comment by samdave123** [comment]
My rig has been stable for a few months now.
