### ISSUE TITLE
Custom Benchmark Lengths

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1096]
Please can you make it possible to make the benchmarks for algos like x16r longer, they are screwing me over a bit in my mrr rentals :D

**Comment by RainbowMiner** [comment]
Oh :) Actually, the benchmarks are already longer for all X16 algorithms. I'll add some extension, so that you can adjust it. There is one ways, already: just change "BenchmarkInterval" to "120" - and you have doubled the benchmarking time (it defaults to 60), value is in seconds.
