### ISSUE TITLE
Mining Rig Rental Earnings

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1098]
Please can you check if this is working on your rigs? It seems to have stopped working on mine.

**Comment by RainbowMiner** [comment]
You say, your balances aren't working anymore for MiningRigRentals? Or is it a different problem?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/87524451-180f7080-c680-11ea-8313-8a8167f9a06f.png)

Most of my revenue comes from MRR, but it doesn't seem to be picking up the daily earnings for the averages.

**Comment by samdave123** [comment]
I'm experiencing this issue now too. I got a big payout in LTC but this isn't showing in RBM.
