### ISSUE TITLE
Show wallet balances - GRIMM, NIM, XMR, etc.

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1099]
Hi!

I have wallet balances displaying for BTC, RVN, SAFE, and ZEC
I don't have them displaying for other wallets I have defined in coins.config.txt such as GRIMM, NIM, MWC, XMR, BEAM, XGM

Is there something I need to do to have these wallets displayed? Or do these wallets not have API support to retrieve wallet balances?

Thanks!

**Comment by RainbowMiner** [comment]
I add new coins to the wallet module, from time to time. It's always about finding a way to get the information from the respective blockchains. The coins you are asking for, aren't currently added. Also, these are mostly privacy coins, so the chances are, that I cannot get the data for some of them.

**Comment by AnthonyBe** [comment]
Got it! Thanks for clarifying!
