### ISSUE TITLE
WARNING: [Test-TimeSync] Time is out of sync by 430.515s! 22:45:46 - syncing now with time.windows.com

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#11]
Set-Service : Service 'Windows Time (W32Time)' cannot be configured due to the following error: Access is denied
At C:\Users\JP\Desktop\RainbowMinerV3.7.5.4\Include.psm1:1506 char:126
+ ... tus -ne "Running" } | Set-Service -StartupType Manual -Status Running
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (System.ServiceProcess.ServiceController:ServiceController) [Set-Service], ServiceCommandException
+ FullyQualifiedErrorId : CouldNotSetService,Microsoft.PowerShell.Commands.SetServiceCommand

WARNING: [Test-TimeSync] Time is out of sync by 430.515s! 22:45:46 - syncing now with time.windows.com
Transcript started, output file is .\Logs\RainbowMiner_2018-08-10_22-45-46.txt
Set-Service : Service 'Windows Time (W32Time)' cannot be configured due to the following error: Access is denied
At C:\Users\JP\Desktop\RainbowMinerV3.7.5.4\Include.psm1:1506 char:126
+ ... tus -ne "Running" } | Set-Service -StartupType Manual -Status Running
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (System.ServiceProcess.ServiceController:ServiceController) [Set-Service], ServiceCommandException
+ FullyQualifiedErrorId : CouldNotSetService,Microsoft.PowerShell.Commands.SetServiceCommand

WARNING: [Test-TimeSync] Time is out of sync by 430.520s! 22:45:53 - syncing now with time.windows.com

**Comment by RainbowMiner** [comment]
There is a timesync checker build in, to avoid getting "Pools out of sync" messages.
Did you start RainbowMiner as administrator? I will quickly provide you with an option for the timesync checker to be off by default. Later, you can then switch it on, if you like.

**Comment by RainbowMiner** [comment]
This is the promised update: d16d2057b28cc5ae784a87c02531994da1a0c0a6

you should:
1. download the new master.zip (https://github.com/RainbowMiner/RainbowMiner/archive/master.zip)
2. stop RainbowMiner
3. extract the master.zip into the RainbowMiner directory (make sure, you overwrite all files and do not extract it into a subdirectory of your directory unintentionally ;-) )
4. start RainbowMiner

**Comment by RainbowMiner** [comment]
Anyway: first you should make sure, that you have started RainbowMiner with administrator rights (use right mouse click over Start.bat and "Run as Administrator"). Maybe this solves this problem for you.

RBM
