### ISSUE TITLE
Cuckarooz Grin

### ISSUE THREAD

**Issue by Adiuk** [RainbowMiner/RainbowMiner#1100]
Gminer new release, fork tomorrow sometime to new algo. Will this be ready?

**Comment by RainbowMiner** [comment]
Yes, please use release v4.6.0.7 - it cointains Gminer v2.18 to mine Cuckarooz29

**Comment by Adiuk** [comment]
Thank you very much

**Comment by rizkyaulya** [comment]
Bittube fork to new algo Cuckaroo29B
Gminer supported it

**Comment by RainbowMiner** [comment]
Sorry, I had this in the master (pre-release), but forgot to publish a new release for this fork. I'll push this now.
