### ISSUE TITLE
Qitmeer and Nimiq

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1101]
Hi,

I have icemining and 666pool enabled for nimiq and qitmeer respectively. Then I have cryptodredge and gminer enabled.

Argon2dnim shows up under All Pools but not in the benchmark list. Cuckaroo24 doesn't show up at all. Am I missing something?

**Comment by acos0874** [comment]
Ah is qitmeer qkeccak?

**Comment by RainbowMiner** [comment]
No, it's Cuckaroom29 - mined with Gminer

**Comment by acos0874** [comment]
I still can't get either pool/coin to show up in profit switching. Please can you have a look at the debug file in case I'm missing something obvious?
[debug_2020-07-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/4937971/debug_2020-07-17.zip)

**Comment by RainbowMiner** [comment]
Sure, I will have a look. Did you already try to set "AllowZero" to "1" in pools.config.txt? Just in case?

**Comment by acos0874** [comment]
It crossed my mind. I'll try it when I get home

**Comment by acos0874** [comment]
I enabled allow zero. nim shows in 'all pools' for icemining. pmeer shows in uupool but not 666pool. Neither show in the list of benchmarks (although I understand pmeer probably doesn't need to)

**Comment by RainbowMiner** [comment]
I'll check why pmeer is not shown for 666pool.

**Comment by RainbowMiner** [comment]
Ah, found it. 666pool has a changed url path.

**Comment by acos0874** [comment]
Thanks. I still can't get argon2dnim to show up on the profit switcher.

**Comment by RainbowMiner** [comment]
Now that's weird. If you have put a NIM wallet into the Icemining section in pools.config.txt and added Icemining to PoolName in config.txt (your debug file shows you did).
Could you check the Benchmarks page on http://localhost:4000 for the miners Nimiq and NoncerProNvidia? Is it possible, that the miners did fail the benchmark?

**Comment by acos0874** [comment]
I don't have those miners enabled since I thought cryptodredge could do it. Should I try enabling those?

**Comment by RainbowMiner** [comment]
Oh yes, do it.

**Comment by RainbowMiner** [comment]
I have NoncerProNvidia running for some time, now. It runs pretty stable, even though I have the impression, that it sometimes reboots one of my rigs. But I am not sure, it could be a powerproblem, too. It's build pretty much on the powerlimits.

**Comment by acos0874** [comment]
Both are benchmarking now

**Comment by RainbowMiner** [comment]
Check the http://localhost:4000/rates.html page for NIM. Is it there? It should have a value around 0.00085 mBTC

**Comment by RainbowMiner** [comment]
> I don't have those miners enabled since I thought cryptodredge could do it.

Sorry, I missed that clue in your debug file.

**Comment by acos0874** [comment]
Thanks. All seems sorted now.
