### ISSUE TITLE
Excluded Pools and devfee

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1103]
Please can you tell me whether the devfee respects Excluded Pools? I just excluded Monero Ocean but I want to make sure my rig won't connect to it when the devfee starts.

**Comment by RainbowMiner** [comment]
Unfortunately, not yet. Does it still cause trouble?

**Comment by samdave123** [comment]
I've still got issues with my rig and I'm trying to stabilise it. It often goes stable for a couple of days, then switches over to devfee and NinjaRig/Monero Ocean crashes it. My rig has managed to benchmark all algos on NiceHash and ZergPool okay, and I'd rather not start whitelisting algorithms.

I've been troubleshooting my rig doing all sorts of things:
Disabling IGP
Disabling p2 state
Removing overclocks
Setting each GPU to profit-switch independently so I can try to pick out individual problem GPUs.

I'm still getting errors like this:
20200719 07:12:39 ERROR: Can't start miner, unable to get number of CUDA devices, is nvidia driver installed?
20200719 07:12:39 T-Rex finished

**Comment by RainbowMiner** [comment]
Oh dear, so NinjaRig could be a possible culprit.
So let us do the following: I'll temporarily remove MoneroOcean from the donation rounds and disable NinjaRig. No need to update your rigs, I'll edit the rbminer.net proxies. Then I'll find a better way to harmonize the donation rounds with an individual rig.

**Comment by RainbowMiner** [comment]
I updated the proxies shortly after my last note. So you should no longer get into trouble with this miner or pool.

**Comment by samdave123** [comment]
This may have also been related to some instability issues I had with my rig. I've managed to resolve them so maybe this miner wouldn't even be unstable any more.
