### ISSUE TITLE
MTP Degree of Accuracy on MRR

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1104]
Please can you increase this by one order of significance? At the moment it's being rounding down from 11.75 to 11, which is creating an error more significant than would be desireable.

**Comment by RainbowMiner** [comment]
You are right. I'll add something. The idea was to make rental hashrates look more attractive by have them look more "integer".

**Comment by acos0874** [comment]
Well I could just put a higher price factor on mtp to compensate

**Comment by RainbowMiner** [comment]
Added. We now have two decimals for hasrate values below 1 and one decimal for hashrate values below 100 (instead of below 10).

**Comment by acos0874** [comment]
Great thanks
