### ISSUE TITLE
Error: "Input string was not in a correct format."

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1105]
Finished waiting - starting next run
Cannot convert value "False" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\Users\yyyyy\Desktop\RainbowMiner\Include.psm1:110 char:13
+         if ([int]$ver1[$i] -lt [int]$ver2[$i]) {if ($Warning -ne "")  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastFromStringToInteger

Cannot convert value "False" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\Users\yyyyy\Desktop\RainbowMiner\Include.psm1:111 char:13
+         if ([int]$ver1[$i] -gt [int]$ver2[$i]) {return $true}
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastFromStringToInteger

WARNING: Failed to communicate with MSI Afterburner

This doesn't seem to be causing any problems though

**Comment by RainbowMiner** [comment]
That's part of the version checker function. When did this happen? Is it a one-timer, or permanently showing up?

**Comment by jch9678** [comment]
It permanently shows up.  Well, it's every other refresh really, definitely not a one time thing.

**Comment by RainbowMiner** [comment]
Would you mind to upload me a debug file?

**Comment by RainbowMiner** [comment]
What could help, too: which miners and pools were running, when this error showed up?

**Comment by jch9678** [comment]
Sorry for my delay.  I'll get them to you today.

**Comment by jch9678** [comment]
[debug_2020-07-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/4977209/debug_2020-07-26.zip)

NQMiner at icemining

**Comment by RainbowMiner** [comment]
Found and fixed. Thank you for reporting!
