### ISSUE TITLE
[REQUEST] algo k12

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#1106]
can you add in k12 miners here > https://github.com/enerc/VulkanXMRMiner

**Comment by RainbowMiner** [comment]
Unfortunately, this miner needs Vulkan. Since we rely heavily on OpenCL to control the GPUs, there is no easy way to get this miner to work for us. Anyway, I'll try to add it for all-the-GPUs (or legacy) mining.
