### ISSUE TITLE
xmrig with CryptoNightHeavyXhv Not Using All Available Threads

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1110]
This combo referenced above is only using 16 threads and 24 (or 22) are available.  
[debug_2020-07-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/4978372/debug_2020-07-26.zip)

**Comment by RainbowMiner** [comment]
Xmrig has a sophisticated auto-configuration. At first start, it will check you CPU (and features) and determine the optimum possible settings. RainbowMiner catches this initial config into a dedicated configuration file (in folder ANY-Xmrig). When there are more cores selected in config.txt, than the optimization did register at the beginning, the initial config will be used. 

The CryptonightHeavy variants are, as the name says, heavy on the CPU and big in memory, so the optimizer might have already chosen the best values.

But you can simply try out by changing the config file in "ANY-Xmrig". The name is build like this: `config_CryptoNightHeavyXhv_<yourCPUname>_<yourConfigAffinity>_<yourConfigCores>.json`

For example, `config_CryptoNightHeavyXhv_1xIntelPentiumG4560350GHz_0x0007_3.json` - it's a Pentium G4560 and affinity is set to 0x0007, cores are set to 3 in config.txt

Now edit this file and find `cn-heavy` - that is where the core/affinity config is located. You will find something like that:
```
    "cn-heavy": [
      [
        1,
        0
      ],
      [
        1,
        2
      ],
      [
        1,
        8
      ],
      [
        1,
        10
      ]
    ],
```

There are multiple `[x,y]` pairs. Where x = number of process-threads used on a specific core/thread, y = the number of the core/thread.
If you want more CPU core/threads assigned, simply add them (better use copy and paste and be sure not to forget the commas).
For example like that:
```
    "cn-heavy": [
      [
        1,
        0
      ],
      [
        1,
        2
      ],
      [
        1,
        4
      ],
      [
        1,
        6
      ],
      [
        1,
        8
      ],
      [
        1,
        10
      ],
      [
        1,
        12
      ],
      [
        1,
        14
      ]
    ],
```

now you are mining on four extra core/threads. The last `[x,y]` pair has no trailing comma, of course.

All the configuration changes will be copied over to future new versions of xmrig, automatically.

If you doubt the configuration (or if you mess up the json structure), simply delete it. It will be re-created upon next start of the algorithm on xmrig.

**Comment by jch9678** [comment]
Thanks for the in depth explanation.  I did some testing, I should not have doubted xmrig lol.
