### ISSUE TITLE
Devfee seems to have messed up my pools

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1112]
My rig was mining happily on Nicehash/Zerg/MRR and then devfee kicks in and then my rig is stuck on zergpoolcoins only. I had to manually go in and reset my pools. Not sure what happened exactly.

Debug file attached.

[debug_2020-07-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/4978926/debug_2020-07-27.zip)

**Comment by RainbowMiner** [comment]
Now that is a strange one! I'll check what has happened there.

**Comment by samdave123** [comment]
Rig is stable, MRR benchmarking is added, 50+ pools have been disabled, I don't think this is an issue any more.
