### ISSUE TITLE
NinjaRig won't start

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1113]
Error message:

C:\Users\Mining\Desktop\RainbowMinerV4.5.4.5\Bin\ANY-NinjaRig\ninjarig.exe: unsupported non-option argument 'NvidiaRig:x~argon2/chukwa'

**Comment by RainbowMiner** [comment]
I see - seems like NinjaRig needs special care for MoneroOcean passwords. I'll try to fix this.

**Comment by samdave123** [comment]
Ah that would make sense. I'm not really using MoneroOcean, I just enabled it to benchmark some algos so I can create some MRR rigs.

**Comment by RainbowMiner** [comment]
Ok, that should fix the problem.

**Comment by samdave123** [comment]
I'm also getting this issue with Gminer on Cuckaroo29s on MoneroOcean that looks related?

13:32:19 Connected to gulf.moneroocean.stream:10128
13:32:28 Authorization on Stratum Server Failed: Invalid payment address provided: --pass. Please use 95_char_long_monero_wallet_address format
13:32:28 Connection Error: End of file
13:32:33 Connected to gulf.moneroocean.stream:10128
13:32:42 Authorization on Stratum Server Failed: Invalid payment address provided: --pass. Please use 95_char_long_monero_wallet_address format
13:32:42 Connection Error: End of file
13:32:47 Connected to gulf.moneroocean.stream:10128
13:32:56 Authorization on Stratum Server Failed: Invalid payment address provided: --pass. Please use 95_char_long_monero_wallet_address format
13:32:56 Connection Error: End of file
13:32:56 All user mining pools are unavailable

**Comment by RainbowMiner** [comment]
Can you supply me with a Gminer/Cuckaroo29s/MoneroOcean command line?

**Comment by samdave123** [comment]
Path: "C:\\Users\\Mining\\Desktop\\RainbowMinerV4.5.4.5\\Bin\\GPU-Gminer\\miner.exe"
Arguments: "--api $mport --devices 0 --server gulf.moneroocean.stream --port 10128 --user --pass NvidiaRig:x~c29s --cuda 1 --opencl 0 --watchdog 0 --pec 0 --nvml 0 --algo swap"

**Comment by RainbowMiner** [comment]
Oh! It looks like, the value for "XMR" is missing.

**Comment by samdave123** [comment]
MRR benchmarking added, I no longer need Monero Ocean, it's no longer an issue.
