### ISSUE TITLE
Pool APIs getting out of sync

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1118]
I'm getting an issue that repeats itself occasionally where nicehash drops it's profitability and it shows has no profitable miners in the powershell window. You'll see my miner switched to zpool yescrypt even though I have a 99 profit factor. It only ever seems to happen on this rig.
[debug_2020-07-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/4999822/debug_2020-07-30.zip)
Please can you look into it?

**Comment by RainbowMiner** [comment]
Sure. I'll check it. It looks like API connection issue to Nicehash, on the first glance. But I'll dig a little deeper.

**Comment by acos0874** [comment]
Thanks. It's doing it again. This time caught it in the act and it's on all my rigs. Nicehash still seems to be active in the 'active miners' section.
[debug_2020-07-31.zip](https://github.com/RainbowMiner/RainbowMiner/files/5007996/debug_2020-07-31.zip)

**Comment by acos0874** [comment]
It looks like it could be related to the dev fee...

![image](https://user-images.githubusercontent.com/42582444/89056263-a9a30180-d353-11ea-9a3d-f59131bf1a02.png)

**Comment by acos0874** [comment]
Or it could be something to do with the BTC price isn't being put into the calculation? SO therefore the revenue is 0.

**Comment by RainbowMiner** [comment]
You got me thinking. I am already investigating and adding some extra switch, that should catch those things.

**Comment by RainbowMiner** [comment]
It looks like you are experiencing internet problems - the asyncloader logs contains so many "host is unknown". Is it possible, that the nameserver or cache in your router is corrupted?

**Comment by acos0874** [comment]
I powered down my router for 30 minutes, which normally gives me a brand new IP and would hopefully clear everything but the problem still occurred.

**Comment by acos0874** [comment]
I disabled zpool but i'm still switching to zergpool low power algos. I know you said it's a problem with the api but nicehash still shows in the profit switcher. Could it be something to do with using pool accuracy weight 100?

**Comment by acos0874** [comment]
Also something to note is whenever I just have nicehash enabled everything runs just fine. It's not like nicehash just disappears randomly.

**Comment by RainbowMiner** [comment]
Ok, it might have something to do with 
```
"HashrateWeight": Adjust weight of pool hashrates on the profit comparison in % (0..100, 0=disable) [default=20]
"HashrateWeightStrength": Adjust the strength of the weight (integer, 0=no weight, 100=linear, 200=square) [default=50]
"PoolAccuracyWeight": Adjust weight of pools accuracy on the profit comparison in % (0..100, 0=disable) [default=15]
```

Your settings are:
```
  "HashrateWeight": 20,
  "HashrateWeightStrength": 0,
  "PoolAccuracyWeight": 100,
```

.. especially the last one ("PoolAccuracyWeight": 100) could eventually cause havoc, if some pool prices cause swings at the accuracy. Try to (re)set it to the default of 15. In the meantime I will recheck the profit function regarding that setting.

**Comment by acos0874** [comment]
Thanks I'll give it a try. The reason I turned it to 100 was I was still occasionally mining some shitcoin algos even though their accuracy was 30% and my switch prevention was set to 5 or higher.

**Comment by acos0874** [comment]
Sorry still doing it. Local host still shows ethash on nicehash as most profitable but in powershell all nicehash algos have disappeared and I'm mining xcash on zergpool. for negative profit.

**Comment by RainbowMiner** [comment]
Ok, now it's getting strange. So let's dig a bit deeper. Could you please upload the following json files:

http://localhost:4000/stats
http://localhost:4000/watchdogtimers
http://localhost:4000/rates

**Comment by RainbowMiner** [comment]
Also, there might be some windows file locking problem. Try to delete all files in folder `.\Cache` and see, if you get any error message.

**Comment by RainbowMiner** [comment]
Third thing to check: is your system clock set correctly?

**Comment by acos0874** [comment]
Clock time seems correct as per my local time 22:13 GMT. I noticed that I was moved onto HNS algo briefly when only Nicehash was enabled which means the problem isn't isolated to pools like zergpool. I have deleted the cache folders on every rig and I'll send the json files if the problem occurs again.

**Comment by acos0874** [comment]
10 hours without an issue so it may have been fixed by clearing the cache folders.

**Comment by acos0874** [comment]
I've been wondering if this issue is related to the incorrect pricing I'm getting on MRR. Even with stable prices and PF 1.6 I'm still getting underpriced rentals.

Please can you instruct me on how to flush out all existing data (cache, etc...) in order to have a clean slate? Hopefully this will fix both problems.

**Comment by acos0874** [comment]
Hello, I'm still getting this issue. It's happened to me right now. Even after deleting the contents of the cache it has come back straight away. Please can you investigate for me?
[debug_2020-08-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/5125741/debug_2020-08-25.zip)

**Comment by RainbowMiner** [comment]
Thank you for reporting. Could you please zip the complete Stats\Pools folder into one zip file and upload the contents?

**Comment by acos0874** [comment]
Ah, unfortunately in my efforts to fix it, I deleted the entire contents of that folder. If the problem comes back I'll send it.

**Comment by acos0874** [comment]
[Pools.zip](https://github.com/RainbowMiner/RainbowMiner/files/5126479/Pools.zip)
It's still doing it, even with a clear cache and stats folder. Here is the pools.zip. Miner is selecting etc on f2pool even though nicehash shows as more profitable in the 'all poool ssection'

**Comment by acos0874** [comment]
Some additional info. when mining the dev fee the active miners list goes back to normal and i can see nicehash ethash.

**Comment by acos0874** [comment]
I just noticed these errors in the logs but don't know how to fix them...

[2020-08-25 19:49:46] WARNING: No more miners are profitable. 
[2020-08-25 19:49:42] INFO: Pool prices are out of sync (46 minutes).

**Comment by acos0874** [comment]
Hmm it seems to be back to normal now. I'm guessing its some API issue as it only seems to affect nicehash.

**Comment by acos0874** [comment]
Switching over to using my gaming PC as a server seems to have fixed this on all but 1 rig. Which is the 1 I was using for a server previously and is showing no update for 2 hours. So is there some way this rig has glitched and I can flush out the data that is clogging it up?

**Comment by acos0874** [comment]
I did a fresh install of RBM on this rig and it seems to have fixed the problem. Must have just been a random glitch.

**Comment by acos0874** [comment]
Unfortunately this is now happening on my other rigs. It seems to have happened after I enabled more pools but even after rolling back the changes the issue is still there. Is there someway I can flush the problem out without doing a fresh install? The rig I did the fresh install on seems to be fine.
[debug_2020-09-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/5187048/debug_2020-09-08.zip)

**Comment by RainbowMiner** [comment]
Which pools did you activate?
To get a clean run, try to remove all files from
.\Cache
.\Stats\Pools

.. that should do the job. To be sure, I would stop RainbowMiner before cleanup.

**Comment by acos0874** [comment]
Thanks. The pools are 

nicehash,zergpool,f2pool,hellominer,miningrigrentals,icemining,zpool,sunpool,uupool,666pool,luckpool,zergpoolcoins,sparkpool,herominers,moneroocean

I hadn't deleted the /stats/pools and I'll try shutting down rbm before performing the actions.

**Comment by RainbowMiner** [comment]
This is such a weird issue. I have enabled "Verbose" mode in the Asyncloader. So from the next release on, we should be able to get a better grip on this.

**Comment by RainbowMiner** [comment]
If this happens on one of your machines again, could you please do the following?
- on that machine open `http://localhost:4000/asyncloaderjobs` (or use it's IP or name http://<theclientsip>:4000),  and upload the result here.
- do the same for the server machine.

**Comment by acos0874** [comment]
Will do. I've reduced the pools to just mrr and nicehash but will monitor it.
