### ISSUE TITLE
Heating control vs rentals

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1119]
If I use heating control to minimise heat, what affect will this have on mrr prices please? 

Do mrr prices depend on 'most profitable' or 'current selection;?

Thanks in advance.

**Comment by samdave123** [comment]
Hey @acos0874 I use this feature extensively and it does not affect MRR pricing and advertised hashrate, but it does affect the miner chosen in the profit-switcher.

See https://github.com/RainbowMiner/RainbowMiner/issues/1114
