### ISSUE TITLE
Switching to rental is a little slow

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1120]
I measured the time for RBM to switch to a rental and it's taking over 3 minutes and upsetting some of my renters. Could this be looked at and perhaps shortened a bit? I'm not sure if it's just an issue with Ethash or in general.

**Comment by Adiuk** [comment]
I assumed it went by your own setting of time interval between runs? So if you have it set at 180 it would be 3 minutes

**Comment by samdave123** [comment]
My interval is 60.

**Comment by samdave123** [comment]
Maybe RBM is struggling with all the pools enabled and one miner per device? Maybe it's taking longer because of this?

**Comment by Adiuk** [comment]
Could be possible, how long does it take normally from start to start mining, if it is a similar amo
Unt of time that is probably the reason as like you said in theory it has to do all the calculations.

**Comment by RainbowMiner** [comment]
> Maybe RBM is struggling with all the pools enabled and one miner per device? Maybe it's taking longer because of this?

Very possible, in deed.

**Comment by samdave123** [comment]
Seems to be working better now I've stopped using 50 pools.
