### ISSUE TITLE
Gminer Cuckaroo29b MoneroOcean broken

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1121]
18:10:38 GPU1 GIGABYTE GeForce GTX 1660 Ti 6GB: Selected 5GB Solver
18:10:38 Connected to gulf.moneroocean.stream:10128
18:10:47 Authorization on Stratum Server Failed: Invalid payment address provided: --pass. Please use 95_char_long_monero_wallet_address format
18:10:47 Connection Error: End of file
18:10:52 Connected to gulf.moneroocean.stream:10128
18:11:01 Authorization on Stratum Server Failed: Invalid payment address provided: --pass. Please use 95_char_long_monero_wallet_address format
18:11:01 Connection Error: End of file
18:11:06 Connected to gulf.moneroocean.stream:10128
18:11:15 Authorization on Stratum Server Failed: Invalid payment address provided: --pass. Please use 95_char_long_monero_wallet_address format
18:11:15 Connection Error: End of file
18:11:15 All user mining pools are unavailable

**Comment by Adiuk** [comment]
I mined fine to moneroocean for a good time and was getting insane profits, something like 2 euro at one point and it was actually going in to my wallet poolside as I thought it may have been an error. Then suddenly it stopped.

**Comment by samdave123** [comment]
> 
> 
> I mined fine to moneroocean for a good time and was getting insane profits, something like 2 euro at one point and it was actually going in to my wallet poolside as I thought it may have been an error. Then suddenly it stopped.

I'm not sure what happened there, but I'm 99.9% sure my error is because I have no wallet address for this pool.

**Comment by RainbowMiner** [comment]
> I'm not sure what happened there, but I'm 99.9% sure my error is because I have no wallet address for this pool.

Yes, you do need a XMR wallet. Otherwise you cannot mine that pool. You may use TradeOgre for that, for example (or you simply use mine 8966CzKtSdaHvEUccMbWiUTrdCcuqHngrbZ8P2CsfjBTUCfTzoiY5RhBu8sK3RzYFGbyy45qL8utzadY4qNsKCAB7vNREYT)

**Comment by samdave123** [comment]
Thanks so much for adding benchmarking to MRR! I no longer need to keep this pool activated for more algos.
