### ISSUE TITLE
Is there a way to completely Re-start the MRR rigs client side?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1122]
I have this system that all the rigs are stuck disabled or offline. Only one algo will go online which is X21. I've tried deleting the rigs hoping it would eventually Re-created the them.

[debug_2020-08-02.zip](https://github.com/RainbowMiner/RainbowMiner/files/5012397/debug_2020-08-02.zip)

**Comment by Yamanipanuchi** [comment]
Is there a file or setting I can change to make RBM think MRR was just added?

**Comment by RainbowMiner** [comment]
Sorry, it took me some time to answer.
What is it, that you want to achieve exactly?

**Comment by Yamanipanuchi** [comment]
This PC for some reason stopped enabling all algo but X21r. COuldnt figure out why it would enable the rest of the algo's. Now I cant seem to get it to RE-create the rigs in MRR that I deleted. Not sure if there is a separate log showing what is happening for MRR specifically?

**Comment by Yamanipanuchi** [comment]
FOund the issue finally. For some reason the API keys I originally had in the pool.config are not there anymore.
