### ISSUE TITLE
XMRig CPU Mining?

### ISSUE THREAD

**Issue by Aphris-Karu** [RainbowMiner/RainbowMiner#1123]
I have been testing RainbowMiner and noticed that XMRig does not appear to be available for CPU mining. After standing it up on my test system I only see CpuminerRKZ and SrbMinerMulti in the list of avaliable miners. Is there a setting I need to do to make it show up?

Aslo, is there an easy way to add a pool to the list? I noticed that supportxmr.com is not in the pool list and would like to add it.

Thank you

**Comment by RainbowMiner** [comment]
Hi, actually, Xmrig should be available. Would you mind creating and uploading a Debug file here? Just open http://localhost:4000 in your browser. There is "Debug File" on the left. It will create a zip file, when clicked.

**Comment by Aphris-Karu** [comment]
[debug_2020-08-03.zip](https://github.com/RainbowMiner/RainbowMiner/files/5016428/debug_2020-08-03.zip)

**Comment by RainbowMiner** [comment]
Ok, so first thing, please reduce the number of pools in PoolName in config.txt
I'ld recommend you start with "ZergPoolCoins" only, to start testing. In the meantime, I'll fire up a CPU-only test instance, just to be sure that there is no bug in my miner modules.

**Comment by Aphris-Karu** [comment]
I cut it down to MiningPoolHub as I have an account there. Now it just tells me there are no miners available.

**Comment by RainbowMiner** [comment]
Which linux distro are you running? Did you start ./install.sh as root before starting start.sh or start-screen.sh? (it's important, that you do not run start.sh nor start-screen.sh as root. The install will add an ocdaemon, that will take care about all the miner starts).

Try `ocdaemon status` - is it up and running?

**Comment by Aphris-Karu** [comment]
It running on Ubuntu 20 TLS and yes, it is installed and running as root.

**Comment by Aphris-Karu** [comment]
Note: this is a test rig while I wait for the 6 GPU's I ordered to come in so I can wipe it and reinstall or do anything else to it if needed.

**Comment by RainbowMiner** [comment]
> Aslo, is there an easy way to add a pool to the list? I noticed that supportxmr.com is not in the pool list and would like to add it.

The easy way is telling me. If a pool makes sense, I'll add it asap. Supportxml.com does make sense, it will be added :)

**Comment by RainbowMiner** [comment]
Ok, I had my test rig started on Ubuntu 18 - it all worked perfectly. I'll fire up another on Ubuntu 20. Not that there is some problem with Ubuntu 20.

If you look into the folder `./Bin` inside the RainbowMiner folder. Which subfolders are there?

**Comment by Aphris-Karu** [comment]
The only directories in the RainbowMiner/Bin directory is 

ANY-SRBMinerMulti
CPU-rkz

**Comment by RainbowMiner** [comment]
That's really weird. There should be many more.

**Comment by RainbowMiner** [comment]
Another question: is there any CUDA (Nvidia) GPU installed in that system, currently?

**Comment by Aphris-Karu** [comment]
No, the only video card in the system is the Radeon that is built into the motherboard. Im 99% sure that is not going to mine. lol

00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Trinity [Radeon HD 7560D] (prog-if 00 [VGA controller])

**Comment by RainbowMiner** [comment]
Ok. My test rig runs perfect on CPU mining with Ubuntu 20. So my best guess is, that there might be some access right problems.
Try to download a complete new instance into an other folder - this time with your normal user account, into your current user directory. Do the `chmod +x *sh` and then either do `start.sh` + enter all data again or `mkdir Config && cd Config` then copy over all *.txt files out of the old rainbowminer folder `Config/*.txt` and then `start.sh`

**Comment by Aphris-Karu** [comment]
Figured I would do one better, the rig I was running it on is waiting on GPU's and will min with them. This one is being built to mine CPU

Fresh install of Ubuntu
Fresh install of RainbowMiner
Following the instructions posted in this repo.

WARNING: No miners available: check your configuration

There is no RainbowMiner/Bin directory even after starting it.

[debug_2020-08-04.zip](https://github.com/RainbowMiner/RainbowMiner/files/5019461/debug_2020-08-04.zip)

**Comment by RainbowMiner** [comment]
Ok, try to add your XMR wallet address.

##### Either (recommended):

Add XMR coin to coins.config.txt
```
   "XMR": {
...
      "Wallet": "putyourXMRwalletaddressinhere",
...
    },
```
.. then add `$XMR` as wallet address in pools.config.txt:
```
    "SupportXmr": {
...
      "XMR": "$XMR",
...
    },
```

##### .. or directly add the address in pools.config.txt:

```
    "SupportXmr": {
...
      "XMR": "putyourXMRwalletaddressinhere",
...
    },
```

**Comment by RainbowMiner** [comment]
Also, adjust your system clock. It seems to be off by 294 seconds. This may have an effect.
```
WARNING: This rig's system time is off by 294 seconds.
```

**Comment by Aphris-Karu** [comment]
I set the time yesterday evening. 

I tried putting my XMR address into the fields and starting it again. It still did not work and there is still no Bin directory.

This is the point where I am going to move on and look at other software options. Thank you for your time.

**Comment by RainbowMiner** [comment]
Sorry to hear that. So I'll close that thread.
One last question: could you give me a short description of your steps to install the system and RainbowMiner? It would help me a lot to eventually find out about the problem and fix it, for future users.
