### ISSUE TITLE
Cuckaroo29b not working at Miner.Rocks

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1127]
[debug_2020-08-10.zip](https://github.com/RainbowMiner/RainbowMiner/files/5052101/debug_2020-08-10.zip)

**Comment by jch9678** [comment]
I don't think it's solved,  I'm getting this with lolminer:

Connected to bittubecash.miner.rocks:30212 (TLS disabled)
Lost connection to stratum server bittubecash.miner.rocks:30212 or server not reachable.

**Comment by RainbowMiner** [comment]
I will better check lolminer.

**Comment by RainbowMiner** [comment]
I have checked with Lolminer - and everything worked fine. Please double-check, that you have entered the right wallet address for TUBE (have a look at localhost:4000 and click the '+' on lolminer to see, which wallet address it is using).

**Comment by jch9678** [comment]
I double checked that is the same address that I have always used.  The address format didn't change did it?

edit: I never knew I needed to change address when it switched algos.  I'll get a new one and see if that works.

By the way, the running config says my region is 'europe', while in the config I have 'us' set?

**Comment by RainbowMiner** [comment]
> By the way, the running config says my region is 'europe', while in the config I have 'us' set?

This should not be. I'll better check the region settings.
