### ISSUE TITLE
XLA on HeroMiners

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1128]
Trying to turn on XLA on Herominers. Had this all setup and used it about a month ago. Noticed the wallet address is different now, I changed that and enabled it. None of my miners go to it. Normaly I have XMR enabled, I disabled it so that XLA should be the next most profitable. But nothing. CPU mining just stops because it see's no other profitable CPU.

**Comment by RainbowMiner** [comment]
Are you using "Algorithm" in config.txt? If yes, please add "Panthera" to the list. I have forgotten to add it automatically. Also check, that miner "xlarig" isn't on your "ExcludeMinerName" list.
