### ISSUE TITLE
Bug: Miner switching interrupts keyboard typing

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#113]
I know this is so miner and little but as I test, it is so annoying when a new miner switches. It does not popup on the screen but a quick flash and it always interrupts my typing. As if when the switch happens it minimizes the miner window but takes keyboard priority with. I'll be typing along fast and look up to see a quarter of what I wrote is not there because the miner took the keyboard lol.

**Comment by RainbowMiner** [comment]
The miner windows are stealing focus, unfortunatly. Fortunatly we have the option to mine in the background (except for Excavator, it needs an own miner window). 
Set "ShowMinerWindow": "0" and the windows will be gone. To monitor the ongoings start "MinerLog.bat". This will open one single window where all miner output is being displayed.
