### ISSUE TITLE
Change CPU affinity in the config.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1130]
Instead of it saying...

WARNING: All threads selected for CPU mining! This will overload your system, auto-adjusting affinity to 0x000f
WARNING: RainbowMiner is out of date: lastest release version v4.6.1.3 is available.
Loading API modules ..

Each time, Actually modify the setting for the PC its being started on?

**Comment by RainbowMiner** [comment]
Actually, I decided to not change the user's config. I changed it, so that the warning message will be displayed once only, after the start of RainbowMiner.
