### ISSUE TITLE
MRR Prices

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1131]
Please can you help me to understand how MRR prices are set? I am using profit factor 1.4 but I seem to keep getting rentals at lower than nicehash is paying just on ethash and just on one of my rigs.

**Comment by acos0874** [comment]
Actually I just realised I can set a higher price modifier for ethash than other algos.

**Comment by samdave123** [comment]
I'm getting this issue too, I thought with PF at 1.3 I should be getting 30% more on MRR than on Nicehack?

**Comment by RainbowMiner** [comment]
Yes, that's right - the problem might be related to an averaging effect. The ETH prices paid on Nicehash have been rising very fast, the past days. So the rig's average income average might lag behind. That is especially true, if your rig is rented out most of the times.
You might want to delete all "Profit-GPU*.txt" files in `Stats` directory. It then takes three hours of normal mining, until a new average is reached.
Actually, this thing highlights one problem of the profit tracking (it only tracks during normal profit switching operation). I am thinking about a way to track the profitability, even when rented out.

**Comment by samdave123** [comment]
I'm just going to disable MRR until this is resolved. My rig has got into a cycle of permanent rental because RBM is underpricing it and never spending any time between rentals for the PF to be adjusted.

**Comment by acos0874** [comment]
I just realised a work around in these situations is to use +xx% auto price modifier for nicehash in particular. It might be worth using a -xx% for non-nicehash algos to capture more rentals.

**Comment by acos0874** [comment]
If a permanent fix is a while away, would it be possible to implement a pause between rentals? For example, when one rig completes, the rig can't be rented again for 3 hours? Maybe the average and pause time could be customised.

**Comment by RainbowMiner** [comment]
Yes, that's a very good idea. It turned out to be pretty complicated, to have kind of a background profitability monitor running. So, adding some pause (maybe for an hour) and interpolating a bit could solve the problem pretty easy. I'll try that one.

**Comment by samdave123** [comment]
Maybe it could be the highest of either current profitability and the current calculation?

**Comment by acos0874** [comment]
Is it also possible that the mrr data file can become corrupt? I have had a couple of rentals today at lower than nicehash-ethash and the prices have been pretty stable.

**Comment by RainbowMiner** [comment]
This commit f1f5db0733064a2d96c9fcf38c011c92e0ba7a45 eventually solves this problem.

**Comment by RainbowMiner** [comment]
I have updated the miningrigrentals code, so that there will be no more need to have all those pools activated _after_ they have been used for benchmarks. The hashrate and powerdraw will be stored in a cache. If this cache is disrupted, the new code uses the advertised hashrate on MiningRigRentals to recalculate the minimum price, thus following your rig's profitability.

**Comment by samdave123** [comment]
Do we still need to activate all the pools in the first place to get benchmarks? It's an awkward workaround.

**Comment by RainbowMiner** [comment]
Awkward as it is - yes, currently we need to activate all pools at first. I am working an a solution for that. It's a non-trivial task, though.

**Comment by samdave123** [comment]
> 
> 
> Awkward as it is - yes, currently we need to activate all pools at first. I am working an a solution for that. It's a non-trivial task, though.
> 
> Correction: not all, but some. You get the best results by activating MoneroOcean,Nicehash,Zergpool,Zpool
> 
> For MoneroOcean, you will have to set a XMR wallet in pools.config.txt, the others automatically use your BTC address (for Nicehash use the internal mining wallet address specific to your Nicehash account).
> If you do not want to have anything to do with XMR, please feel free to use my XMR wallet:
> 8966CzKtSdaHvEUccMbWiUTrdCcuqHngrbZ8P2CsfjBTUCfTzoiY5RhBu8sK3RzYFGbyy45qL8utzadY4qNsKCAB7vNREYT

I will use your XMR wallet, thanks.
