### ISSUE TITLE
Per device pools.config.txt

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1132]
If I add the following to pools.config.txt that resides in a folder in the server config/[MachineName]

  "MiningRigRentals": {
    "User": "yamanipanuchi",
    "API_Key": "a052f9cc6c315ec6d124d36b133aeaf74c01446ce0458d",
    "API_Secret": "c19f69d6343d469f92e8de422d5080023db646a1ec90cf7e4",

With no other tags added, Will the RBM script use the server config and amend/overwrite these values for that specific machine?

**Comment by Yamanipanuchi** [comment]
I that the answer is, It wont work. RBM replaces all the missing tags. Doh!

**Comment by RainbowMiner** [comment]
Yea, there is no merging of config files. It just copies the config files. But merging is a very good idea. I'll try to implement this.
