### ISSUE TITLE
How to get Sparkpool working?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1133]
It keeps trying to use a BTC address when I filled ETH address. 

I tried the sub account  name.

**Comment by RainbowMiner** [comment]
Would you please upload a Debug file? (click Debug file on http://localhost:4000)

**Comment by paulpoco** [comment]
I gave up on Sparkpool.

Here is a debug file but not trying to use Sparkpool.
[debug_2020-08-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/5078614/debug_2020-08-15.zip)
