### ISSUE TITLE
Nicehash pays higher for ETH but for over 6hrs it is only using Zergpool for GPU.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1135]
Nicehash pays higher for ETH but for over 6hrs it is only using Zergpool for GPU.

So manually set to only use Nicehash and it pays more than Zergpool was paying before.

So then changed to use Nicehash and Zergpool then it seemed to be working fine again.
[debug_2020-08-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/5078618/debug_2020-08-15.zip)

**Comment by paulpoco** [comment]
Here is the graph from Nicehash, you can see the right hand side it wasn't used while RBM thought Zergpool was more profitable. 
![Screenshot_20200815-052445_Chrome](https://user-images.githubusercontent.com/801414/90312263-d7418c00-deb7-11ea-81fe-eea335a43b4c.jpg)

**Comment by RainbowMiner** [comment]
I'll check the numbers, that came from ZergPool. Obviously they have been too high, then.

**Comment by paulpoco** [comment]
Is there a way to have GPU only do Nicehash but CPU do Nicehash/Zergpool?

**Comment by RainbowMiner** [comment]
> Is there a way to have GPU only do Nicehash but CPU do Nicehash/Zergpool?

Sorry, there is no way, currently.

**Comment by acos0874** [comment]
https://github.com/RainbowMiner/RainbowMiner/issues/1118

Could this be related to my bug? This happened again whilst I was away. I had to remote into each rig and delete the contents of the cache folder.

**Comment by paulpoco** [comment]
One solution was exclude Ethash on Zergpool

**Comment by paulpoco** [comment]
Not seeing this anymore
