### ISSUE TITLE
After 4.6.1.4 update Trex.exe get stuck running when RBM has started another miner

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1138]
After 4.6.1.4 update Trex.exe gets stuck running when RBM has started another miner
[debug_2020-08-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/5104755/debug_2020-08-20.zip)

**Comment by RainbowMiner** [comment]
Is this still happening on your rig?

**Comment by paulpoco** [comment]
Doesn't appear to do this anymore
