### ISSUE TITLE
Idea: MRR Decaying Profit Factor

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1139]
Been getting rentals at 4.0 profit factor and love it! But I am a little worried I may run sometime with that high with no rentals till I realize I may need to bring it back down.

Wondering if immediately after a rental it starts with your set Profit Factor, But can also be set to Decay over time down to lower set value say over the course of a few days? Maybe after say 4-5 days it can end at a user set lower value?

**Comment by RainbowMiner** [comment]
That is an interesting idea. I'll think this through.

**Comment by acos0874** [comment]
I think I may have mentinoed this before but Autominer had a similar feature whereby some algorithms were labelled as 'hot' so if more than 25% of rigs were rented it would bump the price or something. Also it would bump the price automatically for extensions.
