### ISSUE TITLE
1660 supers with trex

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1142]
I'm just setting up a new rig of 1660 supers and I noticed that trex doesn't show for kawpow and x16rv2. Please can you look into it?

**Comment by RainbowMiner** [comment]
Does trex show up for other algorithms? Or is it blind to all of them?

**Comment by acos0874** [comment]
Oh nevermind sorry it seems to be working now

**Comment by RainbowMiner** [comment]
Ah, super :)
