### ISSUE TITLE
 CryptoNightTurtle

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1144]
I'm getting rentals on 3 of my rigs, but I can't seem to get it to benchmark on my others. Was it once on zergpool and now it's not? If so, please can you suggest a coin and pool so I can establish a benchmark for 1070s and 1660supers.

**Comment by RainbowMiner** [comment]
Try moneroocean. It has IRD coin, which is mined, using cn-pico/trtl

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/91350530-babe2180-e7de-11ea-8c56-08735f5d395a.png)
Hmm I tried that. Used an IRD address I found in Discord but it appears to want to bench something else.

**Comment by acos0874** [comment]
Ah nevermind, benchmarks are there. I just specified IRD as the coin symbol.

**Comment by RainbowMiner** [comment]
I have updated the miningrigrentals code, so that there will be no more need to have all those pools activated ~after~ they have been used for benchmarks. The hashrate and powerdraw will be stored in a cache. If this cache is disrupted, the new code uses the advertised hashrate on MiningRigRentals to recalculate the minimum price, thus following your rig's profitability.

**Comment by acos0874** [comment]
Thanks. I've had some difficulty getting the rigs to benchmark though on IRD. So I've tried copying the stats file from another rig. The flag for 'failed benchmark' says 0 but it still says failed benchmark in localhost.

**Comment by RainbowMiner** [comment]
If you use moneroocean, use a XMR wallet, only. It then should benchmark IRD coin automatically.

**Comment by acos0874** [comment]
Ah I see 👍

**Comment by acos0874** [comment]
So does it have an API similar to zergpool etc for pricing?

**Comment by RainbowMiner** [comment]
Yes, it provides a pretty API for that purpose.
Feel free to use my XMR wallet:
8966CzKtSdaHvEUccMbWiUTrdCcuqHngrbZ8P2CsfjBTUCfTzoiY5RhBu8sK3RzYFGbyy45qL8utzadY4qNsKCAB7vNREYT

**Comment by RainbowMiner** [comment]
Starting with release v4.6.2.3, you may now enable automatic benchmarks for missing algorithms in pools.config.txt . Just set "EnableAutoBenchmark" to "1" in MiningRigRentals section - no more need to keep several pools enabled.
