### ISSUE TITLE
Issue with trex

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#1146]
https://i.imgur.com/Q6dtx6T.png
https://i.imgur.com/aaI0Aiv.png

**Comment by RainbowMiner** [comment]
I see. It could be, that the trex still isn't compatible with the Nvidia Turing architecture (those RTX GPUs). I have recently activated the miner for the RTX. Is this happening on all algorithms? Or does the error occur only for some of them?

**Comment by RainbowMiner** [comment]
I might have found a hint. Which Nvidia driver version are you using?

> CUDA 9.1/9.2 versions of the miner will no longer work with RTX (Compute Capability 7.5+) cards
This is done because RTX cards either hash slower or don't work correctly (depending on the algo) on these versions, producing result for ... does not validate on CPU errors.

**Comment by szentigrad3** [comment]
> I might have found a hint. Which Nvidia driver version are you using?
> 
> > CUDA 9.1/9.2 versions of the miner will no longer work with RTX (Compute Capability 7.5+) cards
> > This is done because RTX cards either hash slower or don't work correctly (depending on the algo) on these versions, producing result for ... does not validate on CPU errors.

i am using latest version 452.06, i;ve also never had a problem with trex on other miner software

**Comment by RainbowMiner** [comment]
Yes, I just saw the CUDA11 in your screenshots. Anyway, it could still be a problem with the RTX GPUs. Eventually, I will not only check for CUDA version, but have to block certain algorithms for RTX GPUs. So, if you gain information, which algorithm went through fine, and which didn't, please let me know.

**Comment by RainbowMiner** [comment]
Are you overclocking this GPU? The first error (nonce..) might indicate a problem with overclocking (see trex issues https://github.com/trexminer/T-Rex/issues/60)

**Comment by szentigrad3** [comment]
> Are you overclocking this GPU? The first error (nonce..) might indicate a problem with overclocking (see trex issues [trexminer/T-Rex#60](https://github.com/trexminer/T-Rex/issues/60))

i am i just turned it off and same error, i see the cuda11 version is new.. never had a problem with 10.0 version

**Comment by RainbowMiner** [comment]
Ah, that's interesting. Maybe trex for Cuda11 has a problem, somehow. I will redirect the problem to the trex developers.

**Comment by szentigrad3** [comment]
> Ah, that's interesting. Maybe trex for Cuda11 has a problem, somehow. I will redirect the problem to the trex developers.

it certainly does as i put the trex cuda10 version in the trex folder and let them run not one has failed

**Comment by RainbowMiner** [comment]
Ok, thank you for reporting back! I will disable CUDA11 for trex on RTX for the time being.

**Comment by RainbowMiner** [comment]
I have temporarily disabled the CUDA11 implementation of the miner.

**Comment by trexminer** [comment]
Thanks for letting me know, we'll fix this issue in the next release

**Comment by trexminer** [comment]
Should be fixed in T-Rex 0.17.2

**Comment by RainbowMiner** [comment]
I have already updated the miner module. So let's hope the best! Thank you for the fix.

**Comment by Tincho1286** [comment]
Hi!, im from Argentina and I´m having the same problem with version 0.19, I just see that I can switch to the cuda10 version and I am trying that, but I would like to know that it is something from my GPU

**Comment by trexminer** [comment]
@Tincho1286 Please post the log file / screenshot

**Comment by Tincho1286** [comment]
Hi again! I just switched to the cuda10 version and I haven't remembered to capture the error. If the error appears again I take a screenshot and upload it here. While I'm going to test if it works like this and I'm going to keep you updated.

**Comment by Tincho1286** [comment]
Again it didn't work
![Captura de pantalla 2021-03-28 174752](https://user-images.githubusercontent.com/81279801/112767589-f8419200-8fed-11eb-9852-c9124c612e74.png)

**Comment by RainbowMiner** [comment]
I could imagine, that this problem is related to a bug in Trex, which has been fixed with the new miner version v0.19.14. I have just pushed a commit with the new miner release.
