### ISSUE TITLE
Localhost main page information

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1147]
I've got quite a few rigs now and I was wondering if you could have an expand all button or otherwise change the columns on remote worker so it shows pool and algorithm. Just so I can keep an eye on the algorithms, pools, hashrates and power etc... at a glance without having to click into each rig please.

If you were going the whole hog, it would be great to have the highest temperature with all the above in one place.

**Comment by RainbowMiner** [comment]
Ok, I'll change the tables.

**Comment by acos0874** [comment]
Thanks. Would it also be possible please to have some gpu temperature information on the rbminer monitoring website so I can check the highest temp for each rig and also a total profit whilst I'm away from home?

**Comment by RainbowMiner** [comment]
Ok. Done :)

**Comment by acos0874** [comment]
Looks fantastic thank you. Please can you also add GBP to rbminer monitoring?

**Comment by jch9678** [comment]
Could you add temperatures for CPUs as well please?
