### ISSUE TITLE
Timesincelast block on etc zergpool

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1148]
Doesn't seem to match up on etc zergpool with the blocks actually being found.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/91506138-4c09c280-e8c9-11ea-93b8-5d7281a49a4f.png)
Actually might be due to this...

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/91506478-10232d00-e8ca-11ea-9a8e-2a0332c3312c.png)
I think this may be related to me other issue. Some thing is happening on nicehash and zergpoolcoins.

I've checked the logs and am getting this...

[2020-08-27 13:57:34] Exception calling ".ctor" with "1" argument(s): "The process cannot access the file 'C:\Users\acost\Desktop\RBM Singles\Cache\AA0F9832AF37CD171348B74CCD558DE3.asy' because it is being used by another process."

**Comment by acos0874** [comment]
Might this be related to the server-client set up? I understand this allows only the server to fetch the API data then shares it with other rigs. This would explain why it happens to all my rigs at the same time.

**Comment by RainbowMiner** [comment]
Is this access violation a regular error, does it happen a lot? Is it in the logs of the Server or one of the Clients? Client/Server shouldn't be an issue. 
What does happen (even though rarely) is, that Windows has locked a file. That then could hinder RainbowMiner from updating that file.

**Comment by acos0874** [comment]
[debug_2020-09-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/5159153/debug_2020-09-01.zip)
I seem to have some pools that haven't updated in 41 hours. It doesn't seem specific to any one pool as it's affecting hellominer, 666pool, nicehash and others.
