### ISSUE TITLE
Profit-switcher broken after RBM update

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1149]
My rig updated today, and now it keeps switching between lots of unprofitable algos doing a few mins of each. Ethash is by far the most profitable, but the rig isn't mining on it. Something has gone very wrong.
[debug_2020-08-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/5147254/debug_2020-08-30.zip)
![image](https://user-images.githubusercontent.com/56473344/91666513-4395cf80-eaf5-11ea-9de2-d9f94b476ca7.png)

**Comment by samdave123** [comment]
I fixed this by restarting RBM and waiting a few minutes until it finally worked again. I lost a few hours of very profitable Ethash mining in the meantime. If this issue doesn't get fixed, then I can't trust RBM to auto-update without breaking itself, so I'll have to disable auto-update. I'm sure this issue has happened before.

**Comment by RainbowMiner** [comment]
Ok, I will check in depth - at first glance It looks like it is going through benchmarks (the Xmrig and Cryptodrege got an update). That can take some time.

**Comment by samdave123** [comment]
Yeah it did benchmarks but then never switched back to Ethash Nicehash after benchmarks.

**Comment by acos0874** [comment]
This sounds similar to the issue I have in https://github.com/RainbowMiner/RainbowMiner/issues/1118

**Comment by acos0874** [comment]
I deleted the poolsdata file and it refreshed the profitability data.

**Comment by acos0874** [comment]
Not it's gone back to not updating. 14 minutes since last update.

**Comment by acos0874** [comment]
I've switched my rigs to standalone mode and deleted the cache and poolsdata. This seems to have temporarily fixed the problem. Could it be due to have too many pools enabled in combination with the server-client mode, making it get overloaded?

**Comment by RainbowMiner** [comment]
Actually, this could very well be the case. This would especially true, if you have some CPU mining running on the server machine.

**Comment by acos0874** [comment]
Actually I'm not mining CPU mining with any of my rigs and they don't seem to be maxing out the CPU. 

> I've switched my rigs to standalone mode and deleted the cache and poolsdata. This seems to have temporarily fixed the problem. Could it be due to have too many pools enabled in combination with the server-client mode, making it get overloaded?

Overnight this seems to have fixed the problem. Just deleting the cache and data file didn't work, so it seems to server having issues fetching the data. I might try using my gaming machine as the server since it has a more powerful CPU. Do you have any other suggestions?

**Comment by RainbowMiner** [comment]
Thank you for all that information. I hope to be able to narrow it down, now.

**Comment by RainbowMiner** [comment]
> I might try using my gaming machine as the server since it has a more powerful CPU. Do you have any other suggestions?

That sounds like a good idea. It all sounds pretty much like a lagging server API.

**Comment by samdave123** [comment]
I'm not using my mining rig CPU for mining, but I do have each of the 4 GPUs as their own worker and I have all pools enabled, so is the CPU being overworked and causing this problem?

**Comment by samdave123** [comment]
I think this happened at a time when my rig was having stability issues.
