### ISSUE TITLE
Bug: Flashing blue download bar

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#115]
Since last update, every interval the blue downloader bar will flash in main output window for a split second. Not effecting performance.

**Comment by RainbowMiner** [comment]
Yes, the download bar kills my nerves, sometimes. I am thinking of getting rid of it completely.

**Comment by Byrd1083** [comment]
My opinion, You should, I hate it. The progress bar with "oooooooooooooooooooooo" is not even accurate and it tends to hang even after downloads have completed. I nice little yellow strip similar to what is used for benchmarking progress would be easier on the eyes. Would be nice to get rid of all progress bars and just use an output x% completed format in text only as well because I hate the "o's".

**Comment by RainbowMiner** [comment]
Ok. Let's kick it :)

**Comment by Byrd1083** [comment]
See I let this machine bench all night to wake up to the blue download bar froze in output window. Rainbow has not crashed and is working correctly.

This has been up here for at least 4 hours now.

![image](https://user-images.githubusercontent.com/42227809/45168024-3916f880-b1af-11e8-8cf8-4fc21cc2eff3.png)

**Comment by RainbowMiner** [comment]
Yes. This is the main problem of the powershell implementation of the download bar. Sometimes, under conditions, it stays there. You will have to exit and restart to get rid of it. This is why we kill it :)

**Comment by Byrd1083** [comment]
👍🏼👍🏼👍🏼👍🏼🚀
