### ISSUE TITLE
MRR Cache

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1153]
In a recent update you added a feature that means there is no longer a need to keep lots of pools active. In the past if I did this the rig would stay available but the prices wouldn't be updated correctly.

My question is that now if I disable the pools will the disabled algorithms get their minimum prices updated appropriately?

**Comment by RainbowMiner** [comment]
> My question is that now if I disable the pools will the disabled algorithms get their minimum prices updated appropriately?

Yes - all ever created MininrigRental rigs will be taken into account, no matter if the algorithm is currently enabled on your miningrigs.

**Comment by acos0874** [comment]
Thanks. How would this work if an algo required benchmarking?

**Comment by samdave123** [comment]
I think this can be closed now with the new RBM release?

**Comment by RainbowMiner** [comment]
> I think this can be closed now with the new RBM release?

Yes, you are right. As soon as the new pools.config.txt setting "EnableAutoBenchmark" is set to "1", you are good.
