### ISSUE TITLE
Price factor using too long an average for MRR

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1154]
Sorry for all the issues. I've been monitoring my rig prices for a while and they don't seem to be behaving as expected. As an example, here is the profit and revenue on my 1660ti rig...

![image](https://user-images.githubusercontent.com/42582444/92026611-2feaa300-ed59-11ea-8428-1d49dacb813a.png)

I then have the pricefactor set as "2".

These are some example rig prices. 
Ethash
![image](https://user-images.githubusercontent.com/42582444/92026858-91ab0d00-ed59-11ea-9795-3b5352182f2f.png)

Kawpow 
![image](https://user-images.githubusercontent.com/42582444/92026834-87890e80-ed59-11ea-8dfa-d5ae22f12f12.png)

MTP
![image](https://user-images.githubusercontent.com/42582444/92026915-adaeae80-ed59-11ea-8d03-d6b1548a200c.png)

So they seem roughly correct but not exactly mulitplied by a factor of 2. Some others have mentioned this in discord. I can adjust the pricemodifier and this has the desired effect, but the minimum pricing doesn't seem to be working correctly for all algos. Ethash in particular.

**Comment by acos0874** [comment]
I deleted the mrr data file and it seemed to start working.

**Comment by acos0874** [comment]
Is the MRR base price for calculations based on a 3 hour average of earnings or 3 day average?

**Comment by RainbowMiner** [comment]
It indeed uses the one day average. I will add an extra parameter, so that the average base can be choosen.

**Comment by samdave123** [comment]
Could I set my rig pricing to be a multiple of the highest of either 10 mins average, 1 hour average, and 1 day average?

**Comment by acos0874** [comment]
That's awesome. Just saw in the recent release. Thanks as ever!
