### ISSUE TITLE
RBM just closed on its own

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1156]
RBM
[debug_2020-09-07.zip](https://github.com/RainbowMiner/RainbowMiner/files/5185742/debug_2020-09-07.zip)
 just quit on its own.

**Comment by RainbowMiner** [comment]
Wow. Weird thing. I'll scramble through the logs.

**Comment by paulpoco** [comment]
@RainbowMiner happened again early morning of Sept 20.
![image](https://user-images.githubusercontent.com/801414/93787364-414efe80-fbe5-11ea-8ccc-a057b9fca6bf.png)
[debug_2020-09-21.zip](https://github.com/RainbowMiner/RainbowMiner/files/5256448/debug_2020-09-21.zip)
