### ISSUE TITLE
Pause between rentals

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1159]
Would it be possible to please set a customisable timer that counts down at the end of a rental and prevents further rentals for a time period?

This would hopefully solve 2 problems 

#1 it would give a window for taking the rig down for maintenance
#2 allow the rig time to update it's profit calculations and rig prices

The main reason is I keep getting stuck in chains of rentals because profit tracking hasn't had time to update. I'm using a 1 hour window for profit stats, so ideally I would want something like a 2 hour pause between rentals.

**Comment by RainbowMiner** [comment]
Very good idea. I'll add this!

**Comment by acos0874** [comment]
Awesome thanks.

**Comment by acos0874** [comment]
Question: Does benchmarking and dev fee contribute towards the profit tracking? I'm conscious that using an hour interval for tracking might get distorted if I've benchmarking for more than a few minutes.

**Comment by RainbowMiner** [comment]
> Does benchmarking and dev fee contribute towards the profit tracking

.. no and no :)

**Comment by acos0874** [comment]
Thanks.

**Comment by acos0874** [comment]
I was just looking at prices of eth f2pool vs eth nicehash. 

![image](https://user-images.githubusercontent.com/42582444/92721015-51e9b400-f35d-11ea-873e-d710ce1892c2.png)

Currently my miners are preferring f2pool, even though the above rates seem to favour nicehash. So if I understand it correctly, rbm is picking based on 'stable price'.

The strange thing is this doesn't seem to be reflected in the profitability read out. So which one gets recorded in the profitstats?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/92721676-5d89aa80-f35e-11ea-8077-35cc60f92173.png)
This is f2pool
![image](https://user-images.githubusercontent.com/42582444/92721728-7003e400-f35e-11ea-8913-d998aabc6254.png)
This is nicehash.

**Comment by Yamanipanuchi** [comment]
I had to delete my ETH rig completely... Even after sitting a while unrented it never updated the price.

**Comment by RainbowMiner** [comment]
> I had to delete my ETH rig completely... Even after sitting a while unrented it never updated the price.

Really? Even with the past two or three releases? That re-price issue should be solved by now.

**Comment by RainbowMiner** [comment]
Parameter added to MiningRigRentals section in pools.config.txt:
- **PauseBetweenRentals**: Disable rigs on MRR after a rental for some time (in seconds, verbose allowed, e.g. 1.5h = 1.5 hours, 30m = 30 minutes) [default=10m]

**Comment by acos0874** [comment]
Fab, thank you!

**Comment by acos0874** [comment]
Please could you add something visual to localhost and/or powershell to indicate when this cooldown timer is in operation?

**Comment by RainbowMiner** [comment]
Sure :) I'll add something.

**Comment by RainbowMiner** [comment]
You can already check this: just open the current `.\Logs\RainbowMiner_YYYY-MM-DD.txt` file - after a rental, you will find an info string saying something like that:
`[2020-09-22 06:00:34] INFO: MiningRigRentals: Wait 506 seconds for worker1 rigs to be re-enabled.`

**Comment by acos0874** [comment]
Ok thats great thanks. I just didn't know where to look.
