### ISSUE TITLE
Bug: CcminerAlexis78 crashes

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#116]
![image](https://user-images.githubusercontent.com/42227809/45068350-e25cd200-b07b-11e8-976e-4f9fabf81860.png)

**Comment by hernandn01** [comment]
lower the intensity, start with -i 22, then keep trying half a point until stable

**Comment by RainbowMiner** [comment]
RainbowMiner's default miner parameter set contains the following intensity settings (which I found very stable running on overclocked GTX1070 and GTX1080Ti). Maybe this table can present some orientation:

|Miner|Algorithm|Params|
|---|---|:---:|
|CcminerAlexis78|c11|-i 21|
|CcminerAlexis78|keccak|-m 2 -i 29|
|CcminerAlexis78|veltor|-i 23|
|CcminerAlexis78|x11evo|-i 21|
|CcminerAlexis78|x13|-i 20|
|CcminerAlexis78|x17|-i 20.5|
|CcminerCool|lyra2z|-i 20|
|CcminerKlausT|neoscrypt|-i 17.6
|CcminerPolytimos|x17|-i 20.5|
|CcminerSkunk|skunk|-i 25|
|CcminerTpruvot|lyra2z|-i 21|
|CcminerTpruvot|x13|-i 20|
|CcminerTpruvotx64|allium|-i 22.125|
|CcminerTpruvotx64|keccak|-i 29|
|CcminerTpruvotx64|keccakc|-i 29|
|CcminerTpruvotx64|lyra2z|-i 21|
|CcminerTpruvotx64|sha256t|-i 29|
|CcminerTpruvotx64|x13|-i 20|
|CcminerXevan|c11|-i 21|
|CcminerXevan|xevan|-i 21|

**Comment by RetroShag** [comment]
CcminerTpruvot SHA256t -i 25 and CcminerTpruvotx64 HMQ1725 -i 21 are stable on 1080ti
