### ISSUE TITLE
BeamHash 3 Miniz Crashing

### ISSUE THREAD

**Issue by Adiuk** [RainbowMiner/RainbowMiner#1160]
Miniz keeps crashing when attempting to benchmark beamhash 3?

**Comment by Adiuk** [comment]
Not sure if this will hlp....

[2020-09-10 05:09:12] Error job 4EEF6C9A3BC36AECA9944B9DE218283D with https://beam.acepool.top/pool-info.php?miningpoolstats using REST: Problem fetching https://beam.acepool.top/pool-info.php?miningpoolstats using REST: The operation was canceled.
[2020-09-10 05:09:22] Error job AA0F9832AF37CD171348B74CCD558DE3 with https://www.miningrigrentals.com/api/v2/info/algos using REST: Problem fetching https://www.miningrigrentals.com/api/v2/info/algos using REST: The operation was canceled.

**Comment by RainbowMiner** [comment]
Are you overclocking? The Beamhash3 is a bit sensitive to overclocking.

**Comment by Adiuk** [comment]
+160 core -500 memory at 77%. Maybe turn core down a bit?

**Comment by RainbowMiner** [comment]
> There is also a new version of miniz I think.

I'll check that asap.

**Comment by Adiuk** [comment]
No worries I’ll wait for the new miniz then play with settings if need be and report back.

**Comment by RainbowMiner** [comment]
Updates with commit be0ccd96d18e0ddde666864105e18c86aa8bcf44

**Comment by Adiuk** [comment]
Tried all the different modes and oc settings still crashes immediately, dont even have chance to see the error line. However i think it may b related to Acepool because if i turn that off and run benchmark through Nicehack it works and benchmarks fine.

**Comment by Adiuk** [comment]
Also another new version out :) v1.6w

**Comment by RainbowMiner** [comment]
:) thank you for reporting! I will also have a closer look on acepool. It is very well possible, that this is the culprit.

**Comment by RainbowMiner** [comment]
Did you set your Acepool public user key as BEAM wallet in pools.config.txt?

**Comment by Adiuk** [comment]
I did yes, however I did notice that in the miner config the command line shows (acepoolkey) .Adiuk

Should the space be there between they key and .Adiuk

**Comment by Adiuk** [comment]
Thats what the problem was i had a space in my pools config after the key. What an idiot...

**Comment by RainbowMiner** [comment]
Ah, I am happy, that we found the problem.
