### ISSUE TITLE
new srb-multi 051 doesnt work

### ISSUE THREAD

**Issue by david0815** [RainbowMiner/RainbowMiner#1161]
srbminer multi has changed some commands since version 050
it seems that the hasrate is not reported back

**Comment by Adiuk** [comment]
Same problem here connects, hashes but comes up as failed in benchmarks, seems to hang a lot as well

**Comment by RainbowMiner** [comment]
Oh!! Thank you for reporting this. I'll check this asap.

**Comment by Adiuk** [comment]
Seems to be working now, thank you

**Comment by david0815** [comment]
great support, thanks.
