### ISSUE TITLE
Reading hashrates for individual cards on trex

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1163]
Hi, I'm just trying to check the hashrates on a 6 gpu rig but trex by default uses --quiet and I don't know how disable this. Is there some way I can get to see the individual hashrates, ideally in the localhost please? It would be great to have this feature in local host for every miner.

**Comment by RainbowMiner** [comment]
There is no way, currently. But I can just remove the --quiet from the miner module. It's just to reduce the logs a bit, on linux machines.

**Comment by RainbowMiner** [comment]
Done :)
