### ISSUE TITLE
Web interface stopped working on all rigs

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1164]
Happened over the weekend. The web interface on all my rigs stopped responding. AKA Localhost:4000.

Tried on several machines. Not sure if there is a way to get the debug off them.

Server system is still working, Maybe a config?

**Comment by Yamanipanuchi** [comment]
[debug_2020-09-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/5220727/debug_2020-09-14.zip)

Debug off server, doesn't include the sub configs I have though.

**Comment by RainbowMiner** [comment]
All of them? That really sounds like a config problem. I'll try to find some hints in your debug file. Actually, if you could upload a zip of a Logs folder of one of the clients, that would help a lot.

**Comment by Yamanipanuchi** [comment]
So I am confident it was something in the config, But I set the group to from "other" to no group at all, Let it sync the config and then placed it back into "other" and its working now. Had to do this for each right. Very weird, And very specific. So no need to look into it.
