### ISSUE TITLE
System keeps renting for lower price then price factor set to.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1165]
I have PriceFactor set to 4.5, Yet the system keeps getting rented for what seems to be 1.0 or less price factor.

Submitted for RBM and Also people on discord to look.

[debug_2020-09-16.zip](https://github.com/RainbowMiner/RainbowMiner/files/5234733/debug_2020-09-16.zip)

**Comment by acos0874** [comment]
Spoke in Discord. I think this is the problem.

WARNING: Stat file (Profit-GPU#00-GPU#01) was not updated because the value 0.000164962296798347 is at least 3 times above the hourly average.

Recommended to delete the profit file in the stats folder.

**Comment by RainbowMiner** [comment]
Oh yes, that is very well possible! Thank you for that! 
This feature is actually to avoid spikes, caused by pool APIs reporting moon prices. So best thing would be to use some sort of function and not a sharp cut-off.

**Comment by RainbowMiner** [comment]
I have increased the uplimit-protection from x3 to x8 - that should cover 99.9% of all cases.

**Comment by Yamanipanuchi** [comment]
So I deleted the profit file and it did show the a more accurate price for a few days, But it is now back down below the profit it would mine on a normal pool. it is on the new 4.6.2.2, I will be a new De-bug file posted when I get to the system.

**Comment by Yamanipanuchi** [comment]
![image](https://user-images.githubusercontent.com/4724631/93670742-7840db00-fa52-11ea-9a57-cda4d5e5d105.png)
 The 1660Ti's should be renting for well into the .2 mbtc and it was for a day or so.

**Comment by acos0874** [comment]
Could it be that because you are spending time mining rvn directly it's not tracking earning events correctly?

**Comment by acos0874** [comment]
> ![image](https://user-images.githubusercontent.com/4724631/93670742-7840db00-fa52-11ea-9a57-cda4d5e5d105.png)
> The 1660Ti's should be renting for well into the .2 mbtc and it was for a day or so.

Keep in mind eth revenue dropped in half the past day. It was at 0.003 BTC/GH/day this morning

**Comment by Yamanipanuchi** [comment]
True, but i still have my Profit factor set to 4.5. And if I cut MRR off it starts mining nicehash at .16. so.. Slight chance its math, But I dont know.

**Comment by Yamanipanuchi** [comment]
[debug_2020-09-19.zip](https://github.com/RainbowMiner/RainbowMiner/files/5250325/debug_2020-09-19.zip)

**Comment by Yamanipanuchi** [comment]
![image](https://user-images.githubusercontent.com/4724631/93724287-985bc180-fb5a-11ea-8fe4-44601766623a.png)
I am still getting really bad rental rates. I disabled ethash completely for now. It seems to only be that algo for some reason.

**Comment by acos0874** [comment]
Did you put +20% on auto pricing for eth only?

**Comment by RainbowMiner** [comment]
It looks like your special setup has again hit the limiter for the profit files. I think, I get an idea now, on what is going on.

**Comment by RainbowMiner** [comment]
Ok, I have made the spike protection optional, now. The default is "0". So if you get into trouble with weird upswings in prices on MRR, just set to a suitable value ("8" is a good one).

New parameter in config.txt:
- **ProfitSpikeProtection** = prevent profit files to be updated, if the actual value is greater than the avg. profit x this factor (0 to disable) [default=0]

**Comment by Yamanipanuchi** [comment]
@acos0874 Yes, I have 20% added to Ethash.

@RainbowMiner If I have special config, I dont see it. Should be fairly straight forward. It seems only be ethash that is the problem. It seems to pickup a back # someplace.

**Comment by Yamanipanuchi** [comment]
![image](https://user-images.githubusercontent.com/4724631/94171083-ab65de80-fe45-11ea-8487-e474a2eb65c8.png)
[debug_2020-09-24.zip](https://github.com/RainbowMiner/RainbowMiner/files/5277550/debug_2020-09-24.zip)

System still keeps getting rented for well below highest profit, I have the profit factor set to 2.0 but it almost seems as if it is completely ignoring the setting.

**Comment by acos0874** [comment]
Ah ha! I think because you aren't using power cost it seems to be distorting the calculations. You should try enabled 'power cost add only' and see if that helps.

**Comment by Yamanipanuchi** [comment]
![image](https://user-images.githubusercontent.com/4724631/94301172-fbfd3a80-ff1e-11ea-9726-69ef7584f29d.png)
Looking at this, You can see Ethash is considerably lower.
