### ISSUE TITLE
0w Power on all miners

### ISSUE THREAD

**Issue by kinebudking** [RainbowMiner/RainbowMiner#1168]
I ran gpu test. i see this:
Gpu 0 Errors=ADL2_OverdriveN_SettingsExt_Get is failed. Are drivers at least 18.12.1 or greater?
Gpu 0 Errors=ADL2_OverdriveN_Temperature_Get has failed
Gpu 0 Errors=ADL2_Overdrive6_CurrentPower_Get has failed
Gpu 0 Errors=ADL_Overdrive5_FanSpeed_Get has failed
Gpu 0 Errors=ADL_Overdrive5_FanSpeedInfo_Get has failed
Gpu 0 Model= AMD Radeon RX 5700 XT

**Comment by RainbowMiner** [comment]
Ok, looks like the Overdrive tool fails on the RX 5700 XT.
Is this a linux or a windows machine? Which driver version are you using?

**Comment by RainbowMiner** [comment]
I think, it's windows. Would you please try the following?
- download https://github.com/RainbowMiner/RainbowMiner/raw/master/Includes/odvii_x64.exe into RainbowMiner's `.\Includes` folder (right-click, save-as)
- download https://github.com/RainbowMiner/RainbowMiner/raw/master/GPUtest.ps1 into the RainbowMiner folder (right-click, save-as)
- now start GPUtest.bat again
- upload the resulting gputestresults.txt here

**Comment by kinebudking** [comment]
windows.  will try that now
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/5246617/gputestresult.txt)

**Comment by RainbowMiner** [comment]
Ok, that was helpful. Now try the new release. If we are lucky, you will now see wattage.

**Comment by kinebudking** [comment]
Yup nailed it! Thank you!
