### ISSUE TITLE
Times and dates (pools)

### ISSUE THREAD

**Issue by S0lin0x** [RainbowMiner/RainbowMiner#1169]
Under "all pools/best pools" last updated times are saying "NaN seconds ago"
under pool totals for "started" and "update" are saying "invalid date"

Is this normal?

**Comment by RainbowMiner** [comment]
No, that is not normal. Could you eventually create a Debug file (just click "Debug file") and upload it here? All sensitive data will be X-ed out automatically, inside that debug file.

**Comment by kinebudking** [comment]
[debug_2020-09-19.zip](https://github.com/RainbowMiner/RainbowMiner/files/5250801/debug_2020-09-19.zip)

**Comment by RainbowMiner** [comment]
The wrong values might be related to Powershell5 - you might want to update to [Powershell Core 6.2.7](https://github.com/PowerShell/PowerShell/releases/download/v6.2.7/PowerShell-6.2.7-win-x64.msi). Actually, you could also try to update to Powershell Core 7.0.3, but I have not tested RainbowMiner thoroughly on that version.

**Comment by kinebudking** [comment]
I will try the 7.0.3 and let you know. if all else fells i will go back go back to 6.2.7.

**Comment by kinebudking** [comment]
6.2.7 installed and working. thank you.
