### ISSUE TITLE
Issue: Miner.config.txt out of order

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#117]
Would be nice to see the organiztaion better. Ocprofiles are sometimes above and also below MSIprofiles.

Also, will any future updates over write this file since you are pushing a preset file? That means if I were to forget to backup my file and an update pushes, I would loose all my profile settings and be working on either your settings which would not match mine or completely erase my work with the customconfigreset.bat you created.

**Comment by Byrd1083** [comment]
Would be nice to see the organiztaion better. Ocprofiles are sometimes above and also below MSIprofiles.

![image](https://user-images.githubusercontent.com/42227809/45068893-a119f180-b07e-11e8-99d7-5bc1a3381e15.png)

**Comment by RainbowMiner** [comment]
> Would be nice to see the organiztaion better. Ocprofiles are sometimes above and also below MSIprofiles.

Ok, I will add a sort function to this. Looks really a bit messy :)

> Also, will any future updates over write this file since you are pushing a preset file? 

Never - only, if you decide to delete the miners.config.txt, it will be build up for new, out of the presets. 
RainbowMiner checks and includes new miners, thereby using the presets, but never changes existing settings.

>  Could we create 2 separate miner.config.txt? One for CPU only and one for GPU only.

Very good! I will add a cpu.miner.config.txt.

RBM
