### ISSUE TITLE
yescrypt16 and r32

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1170]
Any ideas why I could be getting this error on some of my rigs?

![image](https://user-images.githubusercontent.com/42582444/93753717-816bac80-fbf8-11ea-95c3-d9ed39c0fba9.png)

On one rig I get r16 fail and on the other I get r32 fail, but not on both. It's really odd.

**Comment by RainbowMiner** [comment]
Difficult to say. It might be an overclocking issue, but also a GPU memory or system memory problem.
Which GPUs are in these two systems, and how much system memory is avail? Did you setup the Windows swap file with constant size and large enough?

**Comment by acos0874** [comment]
r32 fails on the 1070tis and 1660supers
r16 fails on 2070supers

AFAIK I have enough of a swap file, but it could possibly be due to low RAM.  Both algos run fine on my 1660ti rig with 4gb and my 1070 rig. The 2070super rig has 256gb SSD so should be plenty of storage
