### ISSUE TITLE
Router Issues

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1171]
Hi, I keep having an issues with my Sky router. I think the issue is related to the number of rigs I'm running now.

Every few days the router seems to get to a point where it reboots itself every few minutes. I have isolated this to the rigs, since my fix is to disconnect the ethernet switch connecting the rigs, waiting a few minutes for the connection to recover and then reconnecting them. I'm using the server-client and my server PC is on a separate connection so doesn't get disconnected when I disable the switch.

The problem seems to occur when the server-client connection gets disrupted. I'm guessing this means the rigs will try to connect directly and overload the router. I'm reluctant to spend money on a new router-modem, so I was just wondering if there was a setting I can change, or otherwise prevent the client rigs from trying to access API values when the server is offline.

Thanks in advance.

**Comment by RainbowMiner** [comment]
This really looks like your router is overheating under load. So, first fix would be to find a way to position the router in a way, that the air stream through it is best. There is currently no way to block the fallback to network of the clients. 
I could imagine adding an option, that would prevent this fallback. Also, some kind of fallback strategy (with a fallback-master) could help, too. I'll figure something out.

**Comment by acos0874** [comment]
Thanks. I already did what you suggested and propped a pen underneath to improve airflow around the vents.

**Comment by samdave123** [comment]
@acos0874 ISP supplied routers are really bad. I recommend you go for a Ubiquiti Edgerouter. I've got one of these and it's so much better than what TalkTalk sent me.
