### ISSUE TITLE
linux and permissions

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#1172]
i am trying to run rainbowminer from a text line from ubuntu server and i get these errors

[RainbowMiner_2020-09-23_20-31-13.txt](https://github.com/RainbowMiner/RainbowMiner/files/5267427/RainbowMiner_2020-09-23_20-31-13.txt)

**Comment by RainbowMiner** [comment]
Did you run RainbowMiner as root, just before this run? 
It looks like your permissions are off.
Only run install.sh as root, but never run start.sh as root.

**Comment by szentigrad3** [comment]
i did i fixed this sorry my bad
