### ISSUE TITLE
RBM is updating itself mid-rental

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1173]
RBM is updating itself mid-rental

Surely updates should be scheduled after a rental ends?

**Comment by RainbowMiner** [comment]
Actually, that should not happen, you are right. I'll check the code.

**Comment by samdave123** [comment]
[debug_2020-09-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/5287354/debug_2020-09-26.zip)

Debug file attached. I think RBM is disconnecting from the MRR pool and then immediately updating. I think RBM should at least attempt to get back onto the rental before updating.
