### ISSUE TITLE
yescrypt on linux

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#1174]
is there a miner for linux that supports yescrypt for gpu seems to be most profitable algo atm

**Comment by RainbowMiner** [comment]
Currently, there is no linux GPU miner for YesCrypt. I'll try to find a suitable source and compile one.

**Comment by szentigrad3** [comment]
that would be great thanks!

**Comment by RainbowMiner** [comment]
I have added an experimental version of CcminerYescrypt for linux. Please report, if it runs or fails.

**Comment by szentigrad3** [comment]
[2020-09-26 06:04:33][36m Starting Stratum on stratum+tcp://yescrypt.sea.mine.zpool.ca:6233[0m
[2020-09-26 06:04:33] 1 miner thread started, using 'yescrypt' algorithm.[0m
[2020-09-26 06:04:34][33m Stratum difficulty set to 0.1[0m
[2020-09-26 06:04:36][33m Using intensity 13.312 (10752 threads)[0m
GPU #0: Cuda error in func 'yescrypt_setTarget' at line 1296 : invalid device symbol.
[2020-09-26 06:04:36] stopping 1 threads[0m
[2020-09-26 06:04:41] resetting GPUs[0m
ccminer 8.21-KlausT-yescrypt algo/s + lyra2v3 (64bit) for nVidia GPUs
Compiled with GCC 7.5 using Nvidia CUDA Toolkit 10.0

Based on pooler cpuminer 2.3.2 and the tpruvot@github fork
CUDA support by Christian Buchner, Christian H. and DJM34
Includes optimizations implemented by sp-hash, klaust, tpruvot and tsiv.

**Comment by RainbowMiner** [comment]
Which GPU is plugged into the system and which driver/CUDA version have you installed?

**Comment by szentigrad3** [comment]
1080ti 450.66

**Comment by szentigrad3** [comment]
https://i.imgur.com/dbaL9zj.png

**Comment by szentigrad3** [comment]
latest version works except now its done benchmarking its doing this > https://i.imgur.com/F17KGnE.png

**Comment by RainbowMiner** [comment]
Maybe it has too many rejected shares. Could you please upload the newest `.\Logs\CcminerYescrypt-GPU#00-*.txt` file?

**Comment by szentigrad3** [comment]
[Uploading CcminerYescrypt-GPU#00-12900_2020-09-26_22-07-14.txt…]()

**Comment by szentigrad3** [comment]
i also noticed that its only picking up zpool for yescrypt, not zergpool

**Comment by RainbowMiner** [comment]
I think your upload did not work. It's linking to the issue thread, only.

**Comment by szentigrad3** [comment]
[CcminerYescrypt-GPU#00-12900_2020-09-26_22-07-14.txt](https://github.com/RainbowMiner/RainbowMiner/files/5286764/CcminerYescrypt-GPU.00-12900_2020-09-26_22-07-14.txt)

**Comment by RainbowMiner** [comment]
As I suspected - there are nothing but rejected shares. Do still have access to the first CcminerYescrypt-GPU#00-*.txt log file, from the benchmark, that succeeded?

**Comment by szentigrad3** [comment]
[CcminerYescrypt-GPU#00-12920_2020-09-26_20-54-51.txt](https://github.com/RainbowMiner/RainbowMiner/files/5286770/CcminerYescrypt-GPU.00-12920_2020-09-26_20-54-51.txt)

**Comment by RainbowMiner** [comment]
Ok, now that looks better. In the newest log file, it looks like Zpool had directed the Yescrypt to a coin, that was not compatible. So better you try ZergPool with Yescrypt.

**Comment by szentigrad3** [comment]
how do i try zergpool with yescrypt?

**Comment by RainbowMiner** [comment]
I would recommend using ZergPoolCoins instead of ZergPool - then you will most probably mine BSTY with Yescrypt. Eventually disable Yescrypt on Zpool (put Yescrypt on the ExcludeAlgorithm list in pools.config.txt)

**Comment by szentigrad3** [comment]
[CcminerYescrypt-GPU#00-12900_2020-09-27_02-04-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/5286949/CcminerYescrypt-GPU.00-12900_2020-09-27_02-04-23.txt)
this miner seem to be not working at all with yescrypt

**Comment by RainbowMiner** [comment]
Are there any YescryptXXX algorithms, that this miner did benchmark? Ah, I wish, I had a linux machine at hand. Currently, all my instances run Windows.

**Comment by RainbowMiner** [comment]
Ok, let's try another thing: please download that file into your Miners folder [CcminerYescrypt.psm1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Miners/CcminerYescrypt.ps1) (overwrite the current file)

Either use
```
cd Miners
wget https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Miners/CcminerYescrypt.ps1
```

.. or do right-click save-as into the Miners folder.

It could be possible, that the CUDA11 version does not fully comply.

**Comment by szentigrad3** [comment]
> Are there any YescryptXXX algorithms, that this miner did benchmark? Ah, I wish, I had a linux machine at hand. Currently, all my instances run Windows.

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by szentigrad3** [comment]
> Ok, let's try another thing: please download that file into your Miners folder [CcminerYescrypt.psm1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Miners/CcminerYescrypt.ps1) (overwrite the current file)
> 
> Either use
> 
> ```
> cd Miners
> wget https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Miners/CcminerYescrypt.ps1
> ```
> 
> .. or do right-click save-as into the Miners folder.
> 
> It could be possible, that the CUDA11 version does not fully comply.

same problem

**Comment by RainbowMiner** [comment]
Ok, thank you for the feedback. Maybe it is an incompatibility with the GDDR memory. I'll give it another shot and compile a slightly adapted version today.

**Comment by szentigrad3** [comment]
always willing to help improve

**Comment by szentigrad3** [comment]
any news?

**Comment by RainbowMiner** [comment]
Yes, I have now merged yescrypt mining capabilities into the current ccminer KlausT v8.25 - and tested it on a 2xRTX2080Ti rig. For that rig, it worked perfect :) So maybe, your's will work now, too.
I plugged the new version into the CcminerYescrypt module. So let us hope.

**Comment by szentigrad3** [comment]
i hope so X

**Comment by RainbowMiner** [comment]
That is weird! Mine is doing it's job. Wait, I'll double-check, not that I have unintentionally uploaded the original klaust linux

**Comment by RainbowMiner** [comment]
Ahh :) I have disabled the R16/R32 - but the Yescrypt itself should work. I'll reenable the others asap.

**Comment by szentigrad3** [comment]
yescrypt works fine thanks for all this

**Comment by RainbowMiner** [comment]
Ok, I have re-compiled the ccminer. Now it includes the YescryptR16/32 algorithms, too.

**Comment by szentigrad3** [comment]
cool, hope it all works.. will wait for next update

**Comment by szentigrad3** [comment]
decided to test it out now getting this 

ccminer 8.25-KlausT-Yescrypt (64bit) for nVidia GPUs

Based on pooler cpuminer 2.3.2 and the tpruvot@github fork
CUDA support by Christian Buchner, Christian H. and DJM34
Includes optimizations and additions implemented by sp-hash, tpruvot, tsiv and others.

Compiled with GCC 7.5 using the Nvidia CUDA Toolkit 10.1

[2020-09-29 02:00:48][36m Starting Stratum on stratum+tcp://yescryptR32.mine.zergpool.com:6343[0m
[2020-09-29 02:00:48] 1 miner thread started, using 'yescryptr32' algorithm.[0m
[2020-09-29 02:00:50][33m Stratum difficulty set to 0.2[0m
[2020-09-29 02:00:51][33m Using intensity 13.312 (10752 threads)[0m
free(): invalid pointer

**Comment by szentigrad3** [comment]
it does not same error

**Comment by RainbowMiner** [comment]
Actually, that is pretty cool :) Because KlausT has been searching for a solution to this error for ages. If the former variant worked good, I think, I now know the problem. I'll compile another version.

**Comment by RainbowMiner** [comment]
.. and done. Does this new version now work?

**Comment by szentigrad3** [comment]
it does.. YAY!

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/95520850-1f64c280-09c0-11eb-83b9-4768da9f8123.png)
Which miner do I need to have enabled, because I'm getting this error...
