### ISSUE TITLE
Multiple Errors in newest version

### ISSUE THREAD

**Issue by ngiotta** [RainbowMiner/RainbowMiner#1178]
**Value was either too large or too small for a Decimal.**
Include.psm1:1516 
Include.psm1:1512

**Comment by RainbowMiner** [comment]
Oh! Could you eventually create und Upload a Debug file? Just click "Debug file" on http://localhost:4000

**Comment by ngiotta** [comment]
[debug_2020-09-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/5286247/debug_2020-09-25.zip)
Sure, here ya go!

**Comment by RainbowMiner** [comment]
Thank you! Found it. Fix follows asap.

**Comment by RainbowMiner** [comment]
This should be solved, with the new release.

**Comment by ngiotta** [comment]
Superb. I can verify it is fixed now. Thanks!
