### ISSUE TITLE
Found a way to boost profitability, can this be automated in RBM?

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1181]
As the title says, I have found a way to massively boost profitability.

When the rental is 3 hours from finishing, I check the profitability and if it's still well ahead of what I'd get if the rental wasn't extended, I message the renter and ask them to extend. It's a really simple trick but I'm finding massive success with it.

Could this be automated in RBM?

**Comment by RainbowMiner** [comment]
Nice! I have contacted merc from MiningRigRental. He tries to implement an API function for us within the next couple days :)

**Comment by samdave123** [comment]
Holy shit really? I didn't think this would get taken seriously...

It sounds stupid but it works.

**Comment by RainbowMiner** [comment]
> It sounds stupid but it works.

Not at all stupid. I just didn't think about it, yet. But it is a really smart idea.

**Comment by acos0874** [comment]
Something that might make profits even better, is if the extension price could be raised by a definable percentage, once the rig has been rented. I remember autominer had this feature.

**Comment by RainbowMiner** [comment]
Implemented. I have added two new parameters to pools.config.txt in the MiningRigRentals section:
- **ExtensionMessageTime**: Send the ExtensionMessage to the renter, when the remaining rental time drops below this value (in seconds, verbose allowed, e.g. 1.5h = 1.5 hours, 30m = 30 minutes, set to 0 or empty to disable) [default=2h]
- **ExtensionMessage**: Message, that will be sent to the renter, when remaining rental time drops below ExtensionMessageTime

**Comment by samdave123** [comment]
This needs to be disabled when "AllowExtensions" is set to "0", also if the rental is underpriced in current market conditions.

**Comment by RainbowMiner** [comment]
> if the rental is underpriced in current market conditions.

.. this is already implemented.

> his needs to be disabled when "AllowExtensions" is set to "0"

.. this is missing. I'll add that.
