### ISSUE TITLE
X11K Kyanite

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1184]
Please can you add this algo and coin? It's available on poolmine.xyz

**Comment by acos0874** [comment]
Actually you might want to hold on. It puts the CPU under heavy load.

**Comment by RainbowMiner** [comment]
Ok, I'll wait.

**Comment by RainbowMiner** [comment]
The new Wildrig claims to have lower CPU load. So we could try, now.
There are multiple possible pools, for Kyanite. I'll add one.

**Comment by acos0874** [comment]
Ok. I'll also ask MRR to add it

**Comment by RainbowMiner** [comment]
PoolmineXyz added (commit 62ca382a54d65d018266e56776b32f425a92ee66)

**Comment by acos0874** [comment]
Thanks
