### ISSUE TITLE
Allow Extensions MRR

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1186]
Please can you add a variable for adjusting allow extensions YES or NO?

**Comment by RainbowMiner** [comment]
It looks like, it is not controllable via the MRR API, currently. I'll contact merc to fix this.

**Comment by RainbowMiner** [comment]
Ok, I have added it.
- add allow extensions (issue #1186)
  - new parameter "AllowExtensions" in pools.config.txt (global 1=enable or 0=disable) [default=1]
  - new parameter "AllowExtensions" in mrr.config.txt (override global setting, leave empty for global value)
  - new parameter "MRRAllowExtensions" in algorithms.config.txt (override global and mrr.configtxt setting, leave empty for global value)

*this feature will currently not update your MRR rigs. There seems to be a bug in the MRR API and we have to wait for merc to fix it*

**Comment by acos0874** [comment]
Thank you!
