### ISSUE TITLE
API out of sync problem is back

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1192]
I switched my server back to one of my rigs instead of my gaming PC, and the nicehash API hasn't updated in 7 hours. Here is the debug.

[debug_2020-09-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/5303618/debug_2020-09-30.zip)

Changing the server back to my desktop seems to have fixed it.

**Comment by RainbowMiner** [comment]
Thank you for the report. Has the Nicehash data been out of sync on the client and the server? Or on the client, only?

**Comment by acos0874** [comment]
On all rigs.

**Comment by RainbowMiner** [comment]
Ok. That narrows it down a little.

**Comment by RainbowMiner** [comment]
Ahhhh!! I finally got to the bottom of this issue. How could I have been so blind.. ok, I will fix it now.

**Comment by acos0874** [comment]
Haha, please tell me! It's been bugging me for weeks.

**Comment by RainbowMiner** [comment]
It's so dumb. All asynchronous jobs (calls to APIs etc.) have one flag, called "Running" - this is set, as soon as we try a request to the API. This flag should be reset, at the end of the function - and is. Except if there is an access violation during the write to the cache. Unfortunately Powershell simply ignores the "-ErrorAction Ignore" flag on these write functions, in that case.
And here you go: the function stops execution at once and never resets the "Running" flag thus keeping that particular job from executing anymore.
