### ISSUE TITLE
Hardware information on Local Host

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1195]
Would it be possible please to add RAM usage, CPU usage and nvidia driver number to the local host dashboard? As well as anything else you think is suitable.

**Comment by samdave123** [comment]
Disk usage too, in case it's getting filled up by Windows temp files or error dump files or some other nonsense.

**Comment by acos0874** [comment]
Brilliant as always

**Comment by acos0874** [comment]
Would it also be OK to add some network information to local host? Specifically device name on network so I don't have to rely on IP addresses for remote access?

**Comment by RainbowMiner** [comment]
Sure. Added.
