### ISSUE TITLE
Miners Crashing

### ISSUE THREAD

**Issue by S0lin0x** [RainbowMiner/RainbowMiner#1196]
every miner is getting crashed 30sec to 5 min from starting.

[debug_2020-10-02.zip](https://github.com/RainbowMiner/RainbowMiner/files/5318809/debug_2020-10-02.zip)

**Comment by RainbowMiner** [comment]
Since when is this happening? Did you apply some overclocking to your GPUs?

**Comment by S0lin0x** [comment]
I noticed it when i woke up this morning. went to look at Remote desktop as i do every morning. couldn't log into it... restarted comp check event viewer to see what all happen. nothing odd that i seen. re-ran RBM kept a eye on it. noticed that it would run the miner 30sec's-5 mins then crash started with phxminer. went to look at the activity tab on localhost:4000. every miner it switched to was doing it.

Sorry nd all seems like im posting a lot with issues last few days LOL!

**Comment by RainbowMiner** [comment]
> Sorry nd all seems like im posting a lot with issues last few days LOL!

You are welcome :) I hope, I can help you.

**Comment by RainbowMiner** [comment]
That really looks strange. Try to switch off and restart the rig completely.

**Comment by S0lin0x** [comment]
HDD was bad. reinstalled nd things have been good. other then new post.
