### ISSUE TITLE
CPU Temps Displayed Like GPU Temps

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1197]
Is it possible to have cpu temps displayed everywhere that gpu temps are please?
Thanks.

**Comment by Adiuk** [comment]
Also to add to this is it possible to get the cpu temp to fluctuate the same as gpu as some algos use less power than others, therefore making them more profitable.

**Comment by RainbowMiner** [comment]
This is a bit harder, than the other numbers. Windows has no standard way for that. But I will find a solution ;-)

**Comment by jch9678** [comment]
@RainbowMiner Not sure if you meant my request or @Adiuk but you may be able to grab the cpu temps from Afterburner.  Of course that would mean the miner would have to use Afterburner.

**Comment by jch9678** [comment]
just bumping, can it be easily implemented with Afterburner?

**Comment by RainbowMiner** [comment]
No, Afterburner is no option here. But I have found another way.
It is implemented with commit 321c3b28c44dc8f32bae8331d1e94dd1b7badb7f - tomorrow I will push a new release.

**Comment by Adiuk** [comment]
Excellent, can’t wait to see how it works, thank you.

**Comment by RainbowMiner** [comment]
> Also to add to this is it possible to get the cpu temp to fluctuate the same as gpu as some algos use less power than others, therefore making them more profitable.

The real current CPU wattage is measured now, too. In the past, we had to use utilization and tdp from database.
Only drawback - for that new function to work, you will need to start RainbowMiner as Admin

**Comment by jch9678** [comment]
Looking good, is it possible to get the temperature displayed at Monitoring Central?

**Comment by jch9678** [comment]
It works great! Thank you very much.  

How would it work if I run 2 instances of RainbowMiner on the same machine, one for gpu and one for cpu?  Also how would it work if one instance of RainbowMiner is used for cpu and gpu?  Is another column needed, one that says Max GPU C?

**Comment by RainbowMiner** [comment]
Yes :) It should would fine.

**Comment by CryoRig** [comment]
Any Chance we can get the Temps under Linux too?
