### ISSUE TITLE
mining low profit algo

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#120]
![image](https://user-images.githubusercontent.com/30832110/45081336-9d38ae80-b114-11e8-8e19-7be095ea90b2.png)
crytpnightheavy is more profitable but rainbowminer is mining x17

**Comment by RainbowMiner** [comment]
In the meantime it should have switched to the more profitable currency. It is the switching prevention, which sometimes causes a delay, until changing. Anyway, I have been thinking about giving Nicehash a special role: because this is live paying, it could be efficient to switching to this pool more quickly.
RBM

**Comment by rinkal26783** [comment]
[RainbowMiner_2018-09-05.txt](https://github.com/RainbowMiner/RainbowMiner/files/2353359/RainbowMiner_2018-09-05.txt)
how about you keep 100% accuracy to all nicehash algos?

**Comment by RainbowMiner** [comment]
Let me think about that - this is an interesting idea. Nicehash is already a bit prefered over the other pools. It is the only pool that delivers live prices into RainbowMiner. All others use a one-hour-average to avoid spikes.

**Comment by RainbowMiner** [comment]
Another point: if you do not want to wait for the switching prevention, you may press [S] to skip it. The current best algo will then be mined, no matter what.

**Comment by RainbowMiner** [comment]
Do you have UsePowerPrice = 1 ? If yes, that explains it - the CryptoNight algorithm have very low power consumption.

**Comment by ebojali** [comment]
"UsePowerPrice": "0", in my config file.

**Comment by RainbowMiner** [comment]
So, is it still mining CryptoNight? Ok, then, maybe the StablePrice of the pools is the problem. 
Could you have a look into http://localhost:4000 at "Best Pool", click on the "+" of the pools and lookup variable "StablePrice". What are the values?

**Comment by RainbowMiner** [comment]
After huge price drops or rises, that my happen. In that case, it would be wise to either clear out all profit data (ResetProfit.bat), or delete the pool's algo related profit files by hand (in Stats\Pools, filename is like that: "<poolname>_<algorithm>_Profit.txt")

**Comment by ebojali** [comment]
I think you missunderstood, it is mining X17 as is the mos profitable in my benchmarks, but when I compare with @rinkal26783 it seems like Cryptonight is much more profitable..

**Comment by RainbowMiner** [comment]
Ahh! :D Ok, now I understand. Ok, I think rinkal26783 _is_ using "UsePowerPrice" = "1"

**Comment by RainbowMiner** [comment]
It is, at the moment.

**Comment by ebojali** [comment]
@RainbowMiner Thanks, look at my previous comment..

**Comment by RainbowMiner** [comment]
> how about you keep 100% accuracy to all nicehash algos?

This one? Yes, I am already trying to figure something out that works and avoids heavy switching.

**Comment by ebojali** [comment]
>  I ran the resetProfit bat file and now it is mining Neoscrypt...
This one, any comments on that?

**Comment by RainbowMiner** [comment]
Yes: just wait. RainbowMiner will collect data. After a "ResetProfit.bat" run it takes a current snapshot as new starting point. Over time, the StablePrice will stabilize and things will change. 

In general: when the market drops or rises heavily over a short period of time, it is a good idea, to reset the profits to speed up StablePrice calculation a bit.

**Comment by ebojali** [comment]
Alright, thanks for that explanation. I'm happy now! :smile:

**Comment by RainbowMiner** [comment]
👍 Good to hear 😄
