### ISSUE TITLE
Verushash with NHEQMiner

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1201]
I'm running a ryzen 3800X and have been CPU mining verus for a while using 14 threads on cores 0-12 and it's been fine for weeks. Recently I've been getting crashes and lock up and on close inspection it only appears to be running on cores 0-3.

Here is my original launch command

`Bin\CPU-Nheqminer\nheqminer.exe -a 53601 -v -l eu.luckpool.net:3956 -u RBjZUjsdeLk33rHUTx1qtvEJhZwBMtQfJt.studycpu -p x --cpu-affinity 0x3fff -t 14`

I then changed to let RBM automate the number of threads and core affinity

`Bin\CPU-Nheqminer\nheqminer.exe -a 53601 -v -l eu.luckpool.net:3956 -u RBjZUjsdeLk33rHUTx1qtvEJhZwBMtQfJt.studycpu -p x -t 8 --cpu-affinity 0x5555`

But the issue was still there

**Comment by RainbowMiner** [comment]
Oh, that looks like a CPU issue. Are you sure the Ryzen is ok? I'ld try to switch off and on the whole rig. What is the CPU's temperature?

**Comment by acos0874** [comment]
Yea it looks like rebooting fixed it. Although it's odd cos I tested running a game and all cores were fine.

I ran a virus scan and all cores were working. Temps topped 55°C.

Then I tried mining RandomSFX with automated affinity.

![image](https://user-images.githubusercontent.com/42582444/95019017-f6a89a00-065a-11eb-942a-b9f1c4a75dee.png)

System seems usable and fine. Started verus again and it seems fine. Although the only thing that doesn't seem to work is manually setting a CPU mining thread to 14 still results in only 8 threads being used.

**Comment by RainbowMiner** [comment]
Thank you for reporting back on this.

> I then changed to let RBM automate the number of threads and core affinity

Did you change it back to 0x3fff and 14 threads? Or is it maybe still running on the 0x5555?

**Comment by acos0874** [comment]
Actually I was previously just manually entering -t 14. I can go back to
doing that.

**Comment by RainbowMiner** [comment]
On my AMD zen machines, I have that setting in my config.txt:
`
  "CPUMiningThreads": 14,
  "CPUMiningAffinity": "0xfff5",
`
.. that turned out to be a good solution. It leaves 2 threads for the OS and RainbowMiner, but uses all full cores for mining on the CPU.

**Comment by acos0874** [comment]
Seems to be working ok now.
