### ISSUE TITLE
[localhost]PSSessionStateBroken

### ISSUE THREAD

**Issue by S0lin0x** [RainbowMiner/RainbowMiner#1203]
[localhost] The background process reported an error with the following message: .
+ CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
+ FullyQualifiedErrorId : 2100,PSSessionStateBroken

[debug_2020-10-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/5330971/debug_2020-10-05.zip)

**Comment by RainbowMiner** [comment]
Wow, that's a weirdo. Just to be sure: please start RainbowMiner as administrator (like right-click over `Start.bat`, then click run as admin)

**Comment by RainbowMiner** [comment]
Did you run `Install.bat` ? There might be a problem with the .net installation missing some dll
