### ISSUE TITLE
MRR Pause Conflicting with New Rental

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1204]
Hi, a rental ended but unfortunately the MRR pause didn't kick in correctly and someone else picked up a rental (which wasn't a problem in itself).

Anyway I decided to update the rig, but then the pause kicked in and it wouldn't pick up the new rental...

![image](https://user-images.githubusercontent.com/42582444/95215676-25547b00-07e9-11eb-8755-b4e9fc00c2f6.png)

[debug_2020-10-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/5334521/debug_2020-10-06.zip)

**Comment by RainbowMiner** [comment]
It really looks like, I will have to add some background job to monitor the rentals. This would decouple the rental management from the RainbowMiner loop time.

**Comment by acos0874** [comment]
How about, if when the rental is nearing it's end the price factor gets bumped up? After this the pause could probably be removed, because the main aim was to prevent getting locked into a low rental price cycle.

This would be a desirable feature anyway, whereby when a rig get's rented, any extensions could be charged at a premium. This would also help to prevent renters who do a short rental fishing for the market to increase and then putting in a large extension.

**Comment by acos0874** [comment]
Seems this problem is fixed
