### ISSUE TITLE
Free Script / AMD OC Profile Linux ¡!!!!!!!¡

### ISSUE THREAD

**Issue by ArSd-g** [RainbowMiner/RainbowMiner#1205]
#976  #1137 
Tired to beg for this....

**Comment by RainbowMiner** [comment]
Yea, you are right. It is about time. I'll add pre and post commands to ocprofiles today.

**Comment by RainbowMiner** [comment]
Ok, I have added pre and post commands to ocprofiles.config.txt - that should help a lot. The next step will be to integrate full overclocking features for AMD on Linux and Windows.

- "PreCmd"/"PreCmdArguments": define a command to be executed before the miner starts. PreCmd is the path to the binary, PreCmdArguments are optional arguments for that command.
- "PostCmd"/"PostCmdArguments": define a command to be executed after the miner has finished. PostCmd is the path to the binary, PostCmdArguments are optional arguments for that command.

Please be aware, that if you use backslashes in these config files, you will need to escape them with another backslash (don't `c:\a\b`, instead do `c:\\a\\b`). Otherwise the JSON parser will fail. This is especially important for paths to binaries, when using Windows.

Example for calling a Windows batch file
```
  "PreCmd": "cmd",
  "PreCmdArguments": "/c C:\\RainbowMiner\\sometest.bat",
```

Example for running some Linux tool
```
  "PreCmd": "/home/root/myownocshellcmd",
  "PreCmdArguments": "--gpu 0,1,2 --profile 2",
```

**Comment by ArSd-g** [comment]
oK GREAT! Thank you! i'll test that soon.
If you need any assistance to set amdgpu-oc-linux up, i'm on discord!
Kernels evolves, and i'm not at home for a while...i use to do it with github.com/sibradzic/amdgpu-clocks
but i'm checking for new tools to do this and there is new ones that i need to learn!
i'll be back home next week...easier to work without remote desktop/cmd tools

**Comment by ArSd-g** [comment]
I still not finding a way to run a f*** *.sh f file....and it drives me crazy!!!!!!!!!

**Comment by ArSd-g** [comment]
> Which GPUs is that .sh for?

Nvidia (of course) RTX 3060ti, memory OC still does not work !!!! provide a comprehensive way to make it works, or simply allow an *.sh script to be run as root. dont complicate things when it is simple

**Comment by RainbowMiner** [comment]
Could you please run the following command for me an report back the exact result?

`sudo nvidia-settings --query GPUPerfModes`

**Comment by ArSd-g** [comment]
Attribute 'GPUPerfModes' (ArScl:0.1): perf=0, nvclock=210, nvclockmin=210, nvclockmax=420, nvclockeditable=1, memclock=405, memclockmin=405, memclockmax=405,
  memclockeditable=1, memTransferRate=810, memTransferRatemin=810, memTransferRatemax=810, memTransferRateeditable=1 ; perf=1, nvclock=210, nvclockmin=210,
  nvclockmax=2100, nvclockeditable=149, memclock=810, memclockmin=810, memclockmax=810, memclockeditable=1, memTransferRate=1620, memTransferRatemin=1620,
  memTransferRatemax=1620, memTransferRateeditable=1 ; perf=2, nvclock=210, nvclockmin=210, nvclockmax=2100, nvclockeditable=42, memclock=5001, memclockmin=5001,
  memclockmax=5001, memclockeditable=1, memTransferRate=10002, memTransferRatemin=10002, memTransferRatemax=10002, memTransferRateeditable=1 ; perf=3, nvclock=210,
  nvclockmin=210, nvclockmax=2100, nvclockeditable=137, memclock=7901, memclockmin=7901, memclockmax=7901, memclockeditable=1, memTransferRate=15802,
  memTransferRatemin=15802, memTransferRatemax=15802, memTransferRateeditable=1 ; perf=4, nvclock=210, nvclockmin=210, nvclockmax=2100, nvclockeditable=221, memclock=8101,
  memclockmin=8101, memclockmax=8101, memclockeditable=1, memTransferRate=16202, memTransferRatemin=16202, memTransferRatemax=16202, memTransferRateeditable=1
  Attribute 'GPUPerfModes' (ArScl:0[gpu:0]): perf=0, nvclock=210, nvclockmin=210, nvclockmax=420, nvclockeditable=1, memclock=405, memclockmin=405, memclockmax=405,
  memclockeditable=1, memTransferRate=810, memTransferRatemin=810, memTransferRatemax=810, memTransferRateeditable=1 ; perf=1, nvclock=210, nvclockmin=210,
  nvclockmax=2100, nvclockeditable=149, memclock=810, memclockmin=810, memclockmax=810, memclockeditable=1, memTransferRate=1620, memTransferRatemin=1620,
  memTransferRatemax=1620, memTransferRateeditable=1 ; perf=2, nvclock=210, nvclockmin=210, nvclockmax=2100, nvclockeditable=42, memclock=5001, memclockmin=5001,
  memclockmax=5001, memclockeditable=1, memTransferRate=10002, memTransferRatemin=10002, memTransferRatemax=10002, memTransferRateeditable=1 ; perf=3, nvclock=210,
  nvclockmin=210, nvclockmax=2100, nvclockeditable=137, memclock=7901, memclockmin=7901, memclockmax=7901, memclockeditable=1, memTransferRate=15802,
  memTransferRatemin=15802, memTransferRatemax=15802, memTransferRateeditable=1 ; perf=4, nvclock=210, nvclockmin=210, nvclockmax=2100, nvclockeditable=221, memclock=8101,
  memclockmin=8101, memclockmax=8101, memclockeditable=1, memTransferRate=16202, memTransferRatemin=16202, memTransferRatemax=16202, memTransferRateeditable=1

**Comment by RainbowMiner** [comment]
Awesome, thank you! It'll make it easy to detect the number of performance mode on each GPU.

**Comment by ArSd-g** [comment]
NP, keep us in touch when you upload changes to your build

**Comment by ArSd-g** [comment]
no update still! your "chmod" fuck everything WE NEED TO RUN PRE CMD with "sudo" prefix:

`setPPT.sh` 0 /home/laarsn/Outils/Mining/Amd/Vega56/V56PPT965950850-Ethash                                    
cat /home/laarsn/Outils/Mining/Amd/Vega56/V56PPT965950850-Ethash > /sys/class/drm/card0/device/pp_table
/usr/bin/setPPT.sh: ligne 45: /sys/class/drm/card0/device/pp_table: Permission non `accordée`

with "sudo" in terminal adding "setPPT.sh" to sudoer WORKS!
but when RB start with PreCmd: "sudo .... setPPT.sh" your whmod fuck everything!!!!!

**Comment by ArSd-g** [comment]
"setPPT.sh" without "sudo" = "permission denied: /sys/class/drm/device...."
also running [https://github.com/flippette/nvml-tune]

**Comment by ArSd-g** [comment]
I ended up to make it work with approriates sudoers settings like this: 
```
"PreCmd": "/usr/bin/env",
"PreCmdArguments": "--chdir=/home/laarsn/Outils/Mining/OC ./nvml-tune -i 0 -t 135 -m 1200 -g -300",
```
But RBM still show me an error "/usr/bin/chmod: modification of the rights of '/usr/bin/env': Operation not permitted"

Please fix this error or make it dissapear!
