### ISSUE TITLE
C32 with Linux and 6gb cards

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1206]
C32 doesn't seem to be an option for 6gb cards running in windows, but my question is would my 6gb 1660tis be able to use the 6gb solver if i switched them over to linux?

**Comment by acos0874** [comment]
I tested it, but it said device was out of memory.

**Comment by RainbowMiner** [comment]
Hi, thank you for testing it. I'll doublecheck the memory requirements for that C32. Which miner did fail? All or only specific?

**Comment by acos0874** [comment]
Unfortunately I got a rental so had to abandon my testing. I'll check again in 24 hours

**Comment by acos0874** [comment]
I gave up on this and am back on Windows. Thanks for checking anyway
