### ISSUE TITLE
Params not working as intended

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#121]
Would you please review this? I got a failed Benchmark on x17 on the new EnemyZealot on 1050ti. This is what is trying to run, no intensity is set.
Bin\NVIDIA-Trex\t-rex.exe -b 127.0.0.1:31602 -d 0,2 -a x17 -o stratum+tcp://x17.mine.zergpool.com:3737 -u 3CnnvybE8YvhrZeqW3Rw6tD7XZ1Rk3dXye -p worker1,c=BTC

the screen flashes real fast and can't capture it, but I can see a red line and number 31 possibly trying to run with max intensity. If I run the same line on a separate window it default to intensity 20 and continues fine. 

I tried to set the intensity on the miners.config.txt and it did not pick it up from there. On 

"EnemyZealot-GTX1050Ti": [
    {
.....
 {
      "MainAlgorithm": "X17",
      "SecondaryAlgorithm": "",
      "Params": "-i 20",
      "Profile": ""
    },
I set -i 20 and it did not picked up the intensity from here. No intensity updated on the command line and same error that crashes the miner and closes the window.

on MinersConfigDefault.ps1 I set -19.5 and it did not picked it from here.
"EnemyZealot" = [PSCustomObject[]]@(
...
[PSCustomObject]@{MainAlgorithm = "x17"; SecondaryAlgorithm = ""; Params = "-i 19.5"; OCprofile = ""; MSIAprofile = ""}

I set -20.5 onEnemyZealot.ps1 and it did pick it up from here. The problem is when a new update to this file is done I will loose my preset.
[PSCustomObject]@{MainAlgorithm = "x17"; Params = "-N 1 -i 20.5"} #X17

![image](https://user-images.githubusercontent.com/41829368/45092711-87ef6000-b0d3-11e8-9fb4-857a62241554.png)

**Comment by RainbowMiner** [comment]
It may be a runtime issue: I have found a slight flaw, when a config has been edited by hand.
You should edit the miners.config.txt, only. The MinersConfigDefault.ps1 are the default values, which are written to a newly created miners.config.txt (only once).
I will publish a bugfix release.
Coins should work then, too.

**Comment by RainbowMiner** [comment]
Solved with release v3.8.5.15
