### ISSUE TITLE
Setting to schedule updates

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1210]
Please could you add a setting to pause updates for X amount of days after the last update or to set a desired day of the week/frequency?

I want my rig to update only on Sundays every 2 weeks. This is to reduce amount of benchmarking and also to ensure I'll be at home in case an update breaks something.

**Comment by RainbowMiner** [comment]
Hi, this is a very good idea. Sure, I'll add a switch.

**Comment by RainbowMiner** [comment]
- add parameter "EnableUpdateWhenScheduled" to config.txt and "EnableUpdate" to scheduler.config.txt:
  - if set to "1" automatic updates will happen during the specific timespan(s) defined in scheduler.config.txt, only

**Comment by samdave123** [comment]
I just set these settings, this should enable RBM to update ONLY between 12:00 and 20:00 on Saturdays and Sundays, right?     "DayOfWeek": "5",
    "From": "12:00",
    "To": "20:00",
    "PowerPrice": "",
    "Enable": "1",
    "Pause": "0",
    "Name": "Friday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "1"
  },
  {
    "DayOfWeek": "6",
    "From": "12:00",
    "To": "20:00",
    "PowerPrice": "",
    "Enable": "1",
    "Pause": "0",
    "Name": "Saturday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "1"

**Comment by samdave123** [comment]
Thanks for this, I've set my scheduler to only allow updates between 12:00 and 20:00 and only on Saturdays and Sundays. Can I still force a manual update during the weekdays by clicking the update button on the localhost?

**Comment by RainbowMiner** [comment]
> Can I still force a manual update during the weekdays by clicking the update button on the localhost?

Yes - that is always available.

**Comment by RainbowMiner** [comment]
Hint: the `"DayOfWeek"` starts on sunday

DayOfWeek
```
0 = Sunday
1 = Monday
2 = Tuesday
3 = Wednesday
4 = Thursday
5 = Friday
6 = Saturday
```

**Comment by samdave123** [comment]
I'm a little confused with setting this up. I just want to enable updates between 12:00 and 20:00 on Saturdays and Sundays.

Have I done this correctly, or what do I need to change?

[
  {
    "DayOfWeek": "*",
    "From": "",
    "To": "",
    "PowerPrice": "0.09975",
    "Enable": "0",
    "Pause": "0",
    "Name": "All",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "0"
  },
  {
    "DayOfWeek": "0",
    "From": "12:00",
    "To": "20:00",
    "PowerPrice": "",
    "Enable": "1",
    "Pause": "0",
    "Name": "Sunday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "1"
  },
  {
    "DayOfWeek": "1",
    "From": "00:00",
    "To": "23:59",
    "PowerPrice": "",
    "Enable": "0",
    "Pause": "0",
    "Name": "Monday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "0"
  },
  {
    "DayOfWeek": "2",
    "From": "00:00",
    "To": "23:59",
    "PowerPrice": "",
    "Enable": "0",
    "Pause": "0",
    "Name": "Tuesday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "0"
  },
  {
    "DayOfWeek": "3",
    "From": "00:00",
    "To": "23:59",
    "PowerPrice": "",
    "Enable": "0",
    "Pause": "0",
    "Name": "Wednesday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "0"
  },
  {
    "DayOfWeek": "4",
    "From": "00:00",
    "To": "23:59",
    "PowerPrice": "",
    "Enable": "0",
    "Pause": "0",
    "Name": "Thursday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "0"
  },
  {
    "DayOfWeek": "5",
    "From": "00:00",
    "To": "23:59",
    "PowerPrice": "",
    "Enable": "0",
    "Pause": "0",
    "Name": "Friday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "0"
  },
  {
    "DayOfWeek": "6",
    "From": "12:00",
    "To": "20:00",
    "PowerPrice": "",
    "Enable": "1",
    "Pause": "0",
    "Name": "Saturday",
    "EnableMiningHeatControl": "",
    "MiningHeatControl": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "EnableUpdate": "1"
  }
]

**Comment by RainbowMiner** [comment]
The setup is correct - you will have an update window between 12-22.00 on Saturdays and Sundays

**Comment by samdave123** [comment]
Do I need to disable auto-updates in the main config? Then, the schedular will enable updates on Saturdays and Sundays during my specified time period, and then disable updates again?

**Comment by RainbowMiner** [comment]
> Do I need to disable auto-updates in the main config?

No :) It needs to be "1" - it's something like a "masterswitch".
If you set `"EnableUpdateWhenScheduled": "1",`, then the automatic updates will happen during your scheduler setup.

**Comment by samdave123** [comment]
Right, so these two?

"EnableUpdateWhenScheduled": "1"
"EnableAutoupdate": "1",

**Comment by RainbowMiner** [comment]
Right 👍
