### ISSUE TITLE
webui not loading

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#1211]
when i try to access the webui on my linux server it doesn't load and get a blank page > https://i.imgur.com/HP4nKE0.png

**Comment by RainbowMiner** [comment]
Is this a new problem? Did you try to restart the server machine?

**Comment by RainbowMiner** [comment]
Another question: which CPU is this server machine running?

**Comment by szentigrad3** [comment]
yes and yes and 3600

**Comment by RainbowMiner** [comment]
> yes and yes and 3600

Ok, thank you! I have posted a potential fix to this, a new release will be out soon.

**Comment by szentigrad3** [comment]
this did not fix my problem

**Comment by RainbowMiner** [comment]
Ok, could you try, if that link shows anything?

http://localhost:4000/info

(Substitute localhost with your server's IP)

**Comment by szentigrad3** [comment]
https://i.imgur.com/zCGRKiB.png
i have it as a standalone

**Comment by RainbowMiner** [comment]
Very strange! Are subpages reachable? 
Try

http://localhost:4000/bestpools.html

(Substitute localhost with your server's IP)

**Comment by szentigrad3** [comment]
any news?

**Comment by RainbowMiner** [comment]
I have one more question: which browser are you using to access the ip? Is there any Anti-Malware or Anti-Virus installed, that might block the non-SSL connection for .html pages?

**Comment by szentigrad3** [comment]
microsoft edge and none

**Comment by RainbowMiner** [comment]
In your machines config.txt, you have 

```
  "APIauth": true,
```

.. please try to switch this off:

```
  "APIauth": false,
```

Does this help?

**Comment by RainbowMiner** [comment]
I might have an idea. 

1. we should check the folder `/home/noidea/web`:

Please enter the following commands into your command line and post the results:
```
ls -la /home/noidea | grep "^d"
```
```
ls -la /home/noidea/web
```

2. we try, if we can download one file with the web browser

http://localhost:4000/css/theme-nop.css

(Substitute localhost with your server's IP)

... it should result in `/* empty file */`

**Comment by szentigrad3** [comment]
> I might have an idea.
> 
> 1. we should check the folder `/home/noidea/web`:
> 
> Please enter the following commands into your command line and post the results:
> 
> ```
> ls -la /home/noidea | grep "^d"
> ```
> 
> ```
> ls -la /home/noidea/web
> ```
https://i.imgur.com/G2FrG7g.png
 
> 1. we try, if we can download one file with the web browser
> 
> http://localhost:4000/css/theme-nop.css
> 
> (Substitute localhost with your server's IP)
> 
> ... it should result in `/* empty file */`
it does

> 
> 1. we try, if we can download one file through CloudFlare
> 
> https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.15.5/extensions/filter-control/bootstrap-table-filter-control.css
> 
> ... it should result in
> 
> ```
> /**
>  * @author: Dennis Hernández
>  * @webSite: http://djhvscf.github.io/Blog
>  * @version: v2.1.1
>  */
> 
> .no-filter-control {
>   height: 34px;
> }
> 
> .filter-control {
>   margin: 0 2px 2px 2px;
> }
> ```
> 
> 1. final test, we try to provoke a not found:
> 
> http://localhost:4000/nop
> 
> (Substitute localhost with your server's IP)
> 
> ... it should result in `URI '/nop' is not a valid resource.`

it does

**Comment by szentigrad3** [comment]
> In your machines config.txt, you have
> 
> ```
>   "APIauth": true,
> ```
> 
> .. please try to switch this off:
> 
> ```
>   "APIauth": false,
> ```
> 
> Does this help?

it doesn't

**Comment by RainbowMiner** [comment]
Wow. So all is fine, but still no html pages.

We have a 5th test:
- go to the start page `http://localhost:4000`
- now right-click in the blank page and select `View source`

.. is there _anything_?

**Comment by RainbowMiner** [comment]
And a 6th - maybe we have some response header problems.

- open Edge browser
- press Ctrl + Shift + i simultaneously -> the inspector pane will show itself
- now enter `localhost:4000` (Substitute localhost with your server's IP)
- now click the `Network` tab on the inspector pane
- you should have some kind of list in the lower half of the pane, now. Scroll to the top -> eventually you should see your IP there -> click on it.
- now you should see `Headers` on the right. Could you please upload the result of all three headers (common, response, request)?

**Comment by szentigrad3** [comment]
> Wow. So all is fine, but still no html pages.
> 
> We have a 5th test:
> 
> * go to the start page `http://localhost:4000`
> * now right-click in the blank page and select `View source`
> 
> .. is there _anything_?

i can't even right click the page nothing shows up

**Comment by szentigrad3** [comment]
> And a 6th - maybe we have some response header problems.
> 
> * open Edge browser
> * press Ctrl + Shift + i simultaneously -> the inspector pane will show itself
> * now enter `localhost:4000` (Substitute localhost with your server's IP)
> * now click the `Network` tab on the inspector pane
> * you should have some kind of list in the lower half of the pane, now. Scroll to the top -> eventually you should see your IP there -> click on it.
> * now you should see `Headers` on the right. Could you please upload the result of all three headers (common, response, request)?

everything is just blank

**Comment by RainbowMiner** [comment]
Could you check, if you can load the page with another browser? Like Google Chrome, for example?

**Comment by szentigrad3** [comment]
> Could you check, if you can load the page with another browser? Like Google Chrome, for example?

exactly the same in google chrome

**Comment by RainbowMiner** [comment]
Did you check, if you can reach the IP from another computer or mobile phone?

**Comment by szentigrad3** [comment]
works on my phone... mmmm wierd

**Comment by RainbowMiner** [comment]
> works on my phone... mmmm wierd

Now that is good! So it's Windows that is blocking the requests at some level.
