### ISSUE TITLE
WARNING: CIM CPU detection has failed.

### ISSUE THREAD

**Issue by minergenon** [RainbowMiner/RainbowMiner#1212]
Stopped working (CPU) after automatic update from 4.6.3.4 to 4.6.3.6

**Comment by RainbowMiner** [comment]
Thank you for reporting! I will fix this asap.

Can you tell me which CPU and which Linux distro you are using?

**Comment by RainbowMiner** [comment]
Could you show me the output of the command `lscpu` ?
If it's too lengthy for the screen, just redirect it to a file and upload it here: `lscpu > testresult.txt`

**Comment by RainbowMiner** [comment]
This problem might be fixed, with the last release. Could you please send me the output of the command `lscpu`, anyway?
If you have updated to v4.6.3.7 release, then you could also create a Debug file and upload it here. I have included the result of lscpu, from v4.6.3.7 on.

**Comment by minergenon** [comment]
Mamjaro kernel 5.8.16-2
Архитектура:                     x86_64
CPU op-mode(s):                  32-bit, 64-bit
Порядок байт:                    Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Ядер на сокет:                   4
Сокетов:                         1
NUMA node(s):                    1
ID прроизводителя:               AuthenticAMD
Семейство ЦПУ:                   21
Модель:                          2
Имя модели:                      AMD FX(tm)-8350 Eight-Core Processor
Степпинг:                        0
Frequency boost:                 enabled
CPU MHz:                         4022.693
CPU max MHz:                     4000,0000
CPU min MHz:                     1400,0000
BogoMIPS:                        8030.31
Виртуализация:                   AMD-V
L1d cache:                       64 KiB
L1i cache:                       256 KiB
L2 cache:                        8 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and sec
                                 comp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitiz
                                 ation
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, STIBP disable
                                 d, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Флаги:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov p
                                 at pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_op
                                 t pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpui
                                 d extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 s
                                 se4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm e
                                 xtapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs 
                                 xop skinit wdt fma4 tce nodeid_msr tbm topoext perfctr_core per
                                 fctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_
                                 lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists p
                                 ausefilter pfthreshold

**Comment by RainbowMiner** [comment]
Ok, that explains it. Thank you!
Did the new release solve your issue?

**Comment by minergenon** [comment]
Updated to 4.6.3.7. So far so good, let's watch

**Comment by RainbowMiner** [comment]
That should work, if there is no warning message after detecting devices. Thank you for the feedback!
