### ISSUE TITLE
Instability when running 1 worker per device

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1213]
I'm finding that some miner/algo combinations don't work well with 1 worker per device. Sometimes the miners won't start up if they're already running X number of times.

Although I recognise the problem, I'm not sure what to suggest to fix it.

I really like running 1 miner per device because it gives me per-device data which is super useful.

**Comment by samdave123** [comment]
As an example, T-rex KawPOW gives this error when attempting to open a 4th mining window:
20201020 07:06:10 ERROR: Can't start miner, initialize error for nvrtc, failed to create temporary file
20201020 07:06:11 T-Rex finished.

**Comment by RainbowMiner** [comment]
Is this the actual Trex version v0.18.2 ? It claims to have fixed the multi-miner issue. If not, you might want to update to the current RainbowMiner release. If it is already the newest version, I'll forward this problem to the Trex developers.

**Comment by samdave123** [comment]
> 
> 
> Is this the actual Trex version v0.18.2 ? It claims to have fixed the multi-miner issue. If not, you might want to update to the current RainbowMiner release. If it is already the newest version, I'll forward this problem to the Trex developers.

I'm not sure, my rig has been in a rental for 53 hours and only updated a couple of hours ago. Good to hear it's been fixed in the newest version. I've had some similar problems with other miners, but it doesn't seem too frequent. I think this can be closed then.
