### ISSUE TITLE
Pause on activity

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1216]
Might be worth checking the Pause on Activity for Windows 10. Have three PC's I have this set on and this morning I had them running for 30-40 minutes and they never un-paused. I tried forcing the un-pause on one of them and it re-paused moments later.

**Comment by RainbowMiner** [comment]
Ok, I'll recheck.

**Comment by Yamanipanuchi** [comment]
I am going to close this issue. It seems it happens only once and a while. Im going to guess its Windows doing something in the background causing this.
