### ISSUE TITLE
TRTL not getting a value

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1217]
Low on the totem pole, But TRTL seems to be unable to get a price from anywhere. My systems benches it but does not see a value attached to it.

**Comment by Yamanipanuchi** [comment]
Might not be picking up the LTC pair?

**Comment by RainbowMiner** [comment]
I'll check the TRTL price in the API

**Comment by RainbowMiner** [comment]
I have checked this: TRTL get's in fact a price, but it's really super low (0.09 sat)
That leads to the fact, that it's rounded to 0 on all localhost display. But it is only a frontend display problem. Internally, all is fine. The miners will mine away, if it's profitable.
