### ISSUE TITLE
Exclude algorithm and exclude miner don't work after update to 4.6.3.9

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1219]
Hello,
After the update RBM ignore the exclude setting on device.config
I can see it was downloading and benchmarking for miners/algorithm that I set exclude before

**Comment by RainbowMiner** [comment]
Have you eventually enabled MiningRigRentals and the AutoBenchmark feature?

**Comment by RainbowMiner** [comment]
Oh, actually, if you are using AMD GPUs, then it might be, that a recent fix in the GPU ordering can have an effect on your devices. Could you please upload your current device.config.txt and a Debug file, here? I would love to have a look.
