### ISSUE TITLE
Bug: Setup won't go bachwards

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#122]
Tried to go back to fix a mistake. Won't go backwards in setup.

![image](https://user-images.githubusercontent.com/42227809/45101431-4ca75e00-b0e0-11e8-8de6-5b0dd00f23af.png)

**Comment by Byrd1083** [comment]
AMD GPU setup failed as well.


**"(3) Select the devices to mine on and miningmode

Mine on all available GPU (AMD&NVIDIA, choose no to select devices) (yes/no) [default=yes]: no
Do you want to mine on all NVIDIA GPUs (yes/no) [default=yes]: no
Enter the NVIDIA devices you want to use for mining (leave empty for none): AMD
The following entries are invalid (type "list" to show all valid):
AMD

Enter the NVIDIA devices you want to use for mining (leave empty for none):
Do you want to mine on your CPU (yes/no) [default=no]: no

Done! Do you want to save the changed values? (yes/no) [default=yes]:"**

**Comment by RainbowMiner** [comment]
Ok, looks like I have to redesign the questions.
These should have been your answers:

"(3) Select the devices to mine on and miningmode

Mine on all available GPU (AMD&NVIDIA, choose no to select devices) (yes/no) [default=yes]: no
Do you want to mine on all NVIDIA GPUs (yes/no) [default=yes]: no
Enter the NVIDIA devices you want to use for mining (leave empty for none): **<-- just press return here, leave empty**
Do you want to mine on all AMD GPUs (yes/no) [default=yes]: yes
Do you want to mine on your CPU (yes/no) [default=no]: no

Done! Do you want to save the changed values? (yes/no) [default=yes]:"

**Comment by RainbowMiner** [comment]
> Tried to go back to fix a mistake. Won't go backwards in setup.

Yes, I will check this. Should step back. I know, where it happens.
