### ISSUE TITLE
What does this do? [MRR config]

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1221]
"MaxMarginOfError": "100",
"AutoBonusExtendForHours": "0",
"AutoBonusExtendByHours": "0",
"ProfitAverageTime": "Hour",
"PauseBetweenRentals": "1h",

@RainbowMiner , may I know what does the above means?

**Comment by RainbowMiner** [comment]
- **AutoBonusExtendForHours**: Enter amount of hours, that you want to reward with an automatic bonus extension (e.g. 24). Explanation: this option (together with AutoBonusExtendByHours), gives you the option to reward a renter, if he rents an amount of hours. In the example, the renter will be given 1h per full 24h rental time as bonus. [default=0]
- **AutoBonusExtendByHours**: Enter bonus extension in hours per each fully rented AutoBonusExtendForHours (e.g. 1) [default=0]
- **ProfitAverageTime**: Enter the device profit moving average time period (Minute,Minute_5,Minute_10,Hour,Day,ThreeDay,Week). Explanation: when your rig is up and running, the normal-mining profit is recorded for each device, in the background. With this setting, you can decide the time base for the moving average [default=Day]
- **PauseBetweenRentals**: Disable rigs on MRR after a rental for some time (in seconds, verbose allowed, e.g. 1.5h = 1.5 hours, 30m = 30 minutes) [default=10m]

**Comment by astronyu** [comment]
Thank you for the explanation. I wasn't aware there is a new setting for this. I remember the function for extension was added after requesting it but don't think I've seen this before in 4.6.2.1.
