### ISSUE TITLE
Setup page ruined my RBM config

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1224]
I changed a setting in the setup page and now my pools are all messed up. I used to have 0 excluded, and have Nicehack+Zergpool+MRR enabled. Now it looks like this:
![image](https://user-images.githubusercontent.com/56473344/97904926-1c4bc080-1d39-11eb-923c-f608a59e5d66.png)

**Comment by samdave123** [comment]
And it messed up my excluded miners

**Comment by samdave123** [comment]
I am unsure if it has messed up anything else as I am unsure what else to look for.

**Comment by samdave123** [comment]
My pool earnings also dropped to 0

**Comment by samdave123** [comment]
[Uploading debug_2020-11-02.zip…]()

**Comment by samdave123** [comment]
[debug_2020-11-02.zip](https://github.com/RainbowMiner/RainbowMiner/files/5477253/debug_2020-11-02.zip)

**Comment by RainbowMiner** [comment]
I'll better check that - you find backups of everything in multiple version in `.\Config\Backup` - every time you start RainbowMiner, a backup will be created. The number, at the beginning of the filename, represents the date and time: `YYYYMMDDHHmmii` where YYYY=year, MM=month, DD=day, HH=hour, mm=minute, ii=seconds

**Comment by RainbowMiner** [comment]
Which setting have you tried to change?

**Comment by samdave123** [comment]
> 
> 
> Which setting have you tried to change?

I changed the heat factor to 3.0 because we've got some cold weather over the next few days. I think the problem is related to the devfee that was going on. I wonder if the settings could defer updating until after the devfee is done if that is an issue?
