### ISSUE TITLE
Add support for Hiveon pool

### ISSUE THREAD

**Issue by qinapps** [RainbowMiner/RainbowMiner#1225]
Hi is it possible to add the Hiveon poo for ETH or ETC?

**Comment by RainbowMiner** [comment]
Sure. I will add it.

**Comment by qinapps** [comment]
great thx a lot

**Comment by samdave123** [comment]
> 
> 
> Hi is it possible to add the Hiveon poo for ETH or ETC?

We need more faeces in RBM.
