### ISSUE TITLE
Event ID 7045 recorded in System Log every 30-60 sec since 27 Oct

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1226]
I've just noticed my System event Log (Windows 10 Pro x64) getting spammed by Event ID 7045 every 30-60 sec since 27 Oct with the following content:

```
A service was installed in the system.

Service Name:  WinRing0_1_2_0
Service File Name:  D:\Applications\RainbowMiner\Includes\OpenHardwareMonitor\OpenHardwareMonitorLib.sys
Service Type:  kernel mode driver
Service Start Type:  demand start
Service Account:  
```

Is this a result of the of the CPU monitoring introduced in v4.6.4.0 in commit [49f1fd8](https://github.com/RainbowMiner/RainbowMiner/commit/49f1fd84f146e2c303f1d630c56cfbd144d7fd50) ?

If so, something isn't happy.
I am launching RM as Administrator.
I'm not seeing anything in logs to provide more information but let me know if you'd like me to attach anything in particular

**Comment by RainbowMiner** [comment]
Oh dear! Yes, that pretty much looks like that. I will check, what can be done asap.

**Comment by RainbowMiner** [comment]
Ok, found and fixed.
