### ISSUE TITLE
Bug: AMD only selected in config.txt but benching all CPU,AMD, and NVIDIA

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#123]
I just pickedup with AMD testing with the latest version. Along with the setup AMD error, I let it ride. Config.txt is set to AMD only, yet it is benching CPU,AMD, and NVIDIA instead.

![image](https://user-images.githubusercontent.com/42227809/45102321-4a460380-b0e2-11e8-8c76-a6206e091d14.png)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2353319/config.txt)
[RainbowMiner_2018-09-05.txt](https://github.com/RainbowMiner/RainbowMiner/files/2353329/RainbowMiner_2018-09-05.txt)
[RainbowMiner_2018-09-05_08-01-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2353330/RainbowMiner_2018-09-05_08-01-23.txt)

**Comment by RainbowMiner** [comment]
Looking into your config.txt:
  "DeviceName": "",
.. no device name is selected.
Put   "DeviceName": "AMD", here and everything should work.

**Comment by Byrd1083** [comment]
Just downloaded fresh update. Went through setup again. It never asked for and AMD.

![image](https://user-images.githubusercontent.com/42227809/45110240-93a04e00-b0f6-11e8-8149-9a0b6dd14c61.png)

[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2353906/config.txt)

**Comment by RainbowMiner** [comment]
Oh! Now that is weird. Would you please start "ListGPUs.bat" and send me a picture?
In the meantime I will add the delay question and start to check why you have not been asked. RainbowMiner should detect the amd and if any is avail, ask for it.
RBM

**Comment by Byrd1083** [comment]
Sorry for late response. I would not necessarily do an automatic input of delay. Instead just ask additional question follwing the gpu type question.

Type of gpu to use? {user selection} 
If AMD, then ask
AMD cards can be sensitive to fast switching, would you like to set a delay in secs? {if yes, how many, if no set to default and move on.}

This way you can accommodate everyone 🍻
