### ISSUE TITLE
Mrr memory requirements

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1231]
Mrr made an announcement asking rig owners to list the memory of each GPU so etc or eth can be selected. Is it possible that this can be done automatically in rbm or will it need us to do it manually?

**Comment by RainbowMiner** [comment]
I will check with the MRR developers. Hopefully, that can be done automatically.

**Comment by RainbowMiner** [comment]
Ok, checked and added :)

**Comment by acos0874** [comment]
Fab thank you

**Comment by RainbowMiner** [comment]
This is the info, I've got from merc at MRR:
> It will be live (both device memory and messages) once we release the update to filter ethash

.. meaning, the memory size won't be written to all your rigs, before their ethash filter has gone live. But now we are well prepared and it should upload all sizes in a matter of minutes, then.
