### ISSUE TITLE
Decaying MRR Prices

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1233]
Not originally my idea, but it has been suggested that a decaying PF which give us more optimal rental prices. At the moment I'm doing this manually, So normally I can rely on ethash rentals with PF 1.2 or 1.25.

Occasionally when the market changes like it has recently, I increase my PD to 1.3 or higher because there is more interest in algos other than ethash.

A possible way to automate this would be to have the PF at a static value of say 1.4, then have it decay by 10% every 4 hours. Once a rental is picked up the PF gets reset back to 1.4 for the next rental. I'm not sure how this would work in actual practice, but please let me know if you think it's worth pursuing and could be implemented. Thanks as always!

**Comment by RainbowMiner** [comment]
This can be implemented, of course. The decay would need a lower limit, for example 1.1

**Comment by acos0874** [comment]
Thanks. If you like. Although if my PF is 1.2 I get ethash rentals without fail.

**Comment by RainbowMiner** [comment]
Ok. Got it. 
The following parameters in pools.config.txt do the job:
- **PriceFactorMin**: Minimum profit multiplicator (only of use, if PriceFactorDecayPercent is greater than 0) [default=1.2]
- **PriceFactorDecayPercent**: Enter percentage for decay of the profit multiplicator over time (e.g. 10 for 10%, 0 = disable) [default=0]
- **PriceFactorDecayHours**: Enter the profit multiplicator decay interval (in hours, integer) [default=4]

**Comment by samdave123** [comment]
PriceFactorDecayHours - can we set this in minutes?

**Comment by acos0874** [comment]
Brilliant! Just to clarify, is the decay percentage applied to the actual PF or the difference between the max and min PF?

**Comment by samdave123** [comment]
> 
> 
> Brilliant! Just to clarify, is the decay percentage applied to the actual PF or the difference between the max and min PF?

e.g. if the max PF is 1.4, the min PF is 1.2, and the decay percent is 10%, does the first decay interval drop the PF to 1.26 or 1.38?

**Comment by RainbowMiner** [comment]
It's really `PriceFactor x 0.9` per interval.
e.g. with minimum PF of 1.2 and if you start with 1.4 -> 1.26 -> 1.2 -> 1.2 -> 1.2

Do you think it would be better to decrease the difference?
e.g. with minimum PF of 1.2 and if you start with 1.4 -> 1.38 -> 1.362 -> 1.3458 ...

**Comment by acos0874** [comment]
No PF is fine! Thanks.

**Comment by RainbowMiner** [comment]
> PriceFactorDecayHours - can we set this in minutes?

Currently, not, because I have embedded it into the hourly mrr price update job.

**Comment by RainbowMiner** [comment]
Wow, this feature is super effective! For some time, I had only 30% of my rigs rented. Now I was able to rent out all of my rigs :) Thank you for that superb idea.

**Comment by samdave123** [comment]
> 
> 
> Wow, this feature is super effective! For some time, I had only 30% of my rigs rented. Now I was able to rent out all of my rigs :) Thank you for that superb idea.

It was my idea, I deserve the credit.

**Comment by acos0874** [comment]
> Wow, this feature is super effective! For some time, I had only 30% of my rigs rented. Now I was able to rent out all of my rigs :) Thank you for that superb idea.

Don't steal all my customers

**Comment by samdave123** [comment]
@acos0874 @RainbowMiner What values are you using?

**Comment by RainbowMiner** [comment]
> PriceFactorDecayHours - can we set this in minutes?

Now you can set it in minutes. I have renamed PriceFactorDecayHours to PriceFactorDecayTime (will be cleaned up automatically during update). Also, I have added new parameter UpdateInterval (which defaults to 1h). You can lower it, now. PriceFactorDecayTime will have a minimum at UpdateInterval, internally.

- Update pool MiningRigRentals
  - add automatic decay of PriceFactor (issue #1233)
    - **PriceFactorMin**: Minimum profit multiplicator (only of use, if PriceFactorDecayPercent is greater than 0) [default=1.2]
    - **PriceFactorDecayPercent**: Enter percentage for decay of the profit multiplicator over time (0 = disable) [default=0]
    - **PriceFactorDecayTime**: Enter the profit multiplicator decay interval (in seconds, verbose allowed, e.g. 1.5h = 1.5 hours, 30m = 30 minutes) [default=4h]
  - add parameter for update interval
    - **UpdateInterval**: Enter the interval time for create and update rigs on MRR (in seconds, verbose allowed, e.g. 1.5h = 1.5 hours, 30m = 30 minutes) [default=1h]

**Comment by samdave123** [comment]
There's a growing number of values to tweak with MRR now. Could an MRR settings page be added to the Localhost settings at some point?

**Comment by RainbowMiner** [comment]
Sure. I am working on a pool setup page. That will have all the inputs.

**Comment by samdave123** [comment]
Does the decay start during or at the end of the pause between rentals feature? #1159

**Comment by RainbowMiner** [comment]
The timer will start at the end of a rental. It would be better, if it would start after the pause time. Good that you asked that question.
But normally, it shouldn't have too much impact, since it's a discrete function with a periodtime of UpdateInterval. Therefor the first decay time may range +- one half of UpdateInterval.

Be careful with UpdateInterval. In case you decide to change it, do not choose it too short, it's a pretty costly calculation in means of time and CPU load.

**Comment by RainbowMiner** [comment]
Also, the decay is discrete, too.
It will drop the price not continuously, but after the elapse of the decay time.

**Comment by samdave123** [comment]
Is there a way to see what the PF value is at the time the rental is taken out? It would be really interesting to see what the value ends up being.

**Comment by RainbowMiner** [comment]
Yes, there is a file .\Data\mrrcontrol.json - it stores the current PF

**Comment by samdave123** [comment]
> 
> 
> Yes, there is a file .\Data\mrrcontrol.json - it stores the current PF

Oh this is sick. I just found out it's using PF 1.49985. I actually got a rental at 1.5 thanks to this feature. Even if there were no renters, it would decay to a more rentable value anyway. You have implemented this incredibly well.

**Comment by acos0874** [comment]
> Also, the decay is discrete, too.
> It will drop the price not continuously, but after the elapse of the decay time.

Just trying to understand this so I can play with the values. Is the decay factor applied linearly or is the decay compounded?

So for example if using 1% decay on PF1.5 is it:

1.5 -> 1.485 -> 1.47015 -> 1.4554485

OR

1.5 -> 1.485 -> 1.47 -> 1.455

**Comment by RainbowMiner** [comment]
That's the way:
> 1.5 -> 1.485 -> 1.47015 -> 1.4554485

**Comment by acos0874** [comment]
Another question, if the rig gets rented at PF 1.2, but they extend the rental, is the PF reset to 1.5 or will it be at the original pricing?

Also if the rental is extended, how does the price show in the RBM via the API? For example my initial rental was for 6 hours and it was extended for 6 hours. If the initial rental was at PF 1.2, will the profitability read out change once the initial rental has ended?

**Comment by Yamanipanuchi** [comment]
Is this decay automatically enabled? Or what settings need to be in place for it to start the price decay?

**Comment by Yamanipanuchi** [comment]
Nevermind, Found it.
