### ISSUE TITLE
WARNING: No pools available: check your configuration or WARNING: No miner available 

### ISSUE THREAD

**Issue by cocafruitos** [RainbowMiner/RainbowMiner#1238]
Hi I try to fix this problem since 4 days but I don't find any solutions. I went to rent my rig on MRR with RBM but all is setup for MMR and I get alway No pools available or No miner available I check my API key, i check all and never work but I try on other pool and on Nicehash work find is just on MMR I get this problem .

When I create my rig on MMR I put the name on my rig on description , RBM find it but No pools available or No miner  available error and when I setup automatic create rig with RBM the rig never create I try on windows and linux I et the same problem 

It's for rend Verushash

**Comment by RainbowMiner** [comment]
Could you please upload a Debug file here? Just go to http://localhost:4000 and click on Debug file.

**Comment by cocafruitos** [comment]
[Uploading debug_2020-11-11 (2).zip…]()

**Comment by cocafruitos** [comment]
[debug_2020-11-11 (2).zip](https://github.com/RainbowMiner/RainbowMiner/files/5527094/debug_2020-11-11.2.zip)
It's send you can downloads it ?

**Comment by RainbowMiner** [comment]
Yes, thank you. I'll look at it asap

**Comment by cocafruitos** [comment]
Ok thank
