### ISSUE TITLE
TeamRedMiner reported hashrate

### ISSUE THREAD

**Issue by jcabello7** [RainbowMiner/RainbowMiner#1242]
The TeamRedMiner reported hashrate is not OK, at least mining ETH.
I'm reading in the miner log that actual hashrate is 109MHs, while appears to be 90MHs in RainbowMiner.
Seems like is reading the average hashrate instead actual.
[Teamred-GPU#00-GPU#01-40900_2020-11-13_00-38-32.txt](https://github.com/RainbowMiner/RainbowMiner/files/5533868/Teamred-GPU.00-GPU.01-40900_2020-11-13_00-38-32.txt)
[RainbowMiner_2020-11-13_00-04-25.txt](https://github.com/RainbowMiner/RainbowMiner/files/5533869/RainbowMiner_2020-11-13_00-04-25.txt)

**Comment by RainbowMiner** [comment]
Ok, I have updated the miner API module. Please let me know, if it improved the reading.

**Comment by jcabello7** [comment]
I think that now is working worse than before
![TRM](https://user-images.githubusercontent.com/10871344/99113939-539b5680-25f0-11eb-8e1b-dcfa82c7eb35.JPG)

**Comment by jcabello7** [comment]
I tried and seems to be working worse than before.
![TRM](https://user-images.githubusercontent.com/10871344/99115849-5b102f00-25f3-11eb-90e0-38bbf96dd961.JPG)
