### ISSUE TITLE
GBP on Monitoring Page

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1244]
Please can you add the option of profit in GBP on the rbm monitoring page? Also ideally I would like to be able to see the revenue (not from the earnings tracker, just the projected revenue).

Thanks!

**Comment by Yamanipanuchi** [comment]
Cant this be done by changing   "Currency": "BTC,USD". I might be wrong, But if you Add GBP or Change USD to GBP it might do what you are looking for?

**Comment by acos0874** [comment]
I'm referring to rbminer.net not local host.

Either way whether it's rbminer.net or localhost, I just want to be able to see profit in GBP ( which is already on localhost) and revenue in GBP (projected not earnings tracker)

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/99527009-045c7980-2994-11eb-850a-c68c97db2dc2.png)
Ideally if there could be a choice between static/projected revenue vs tracked revenue (which isn't working properly for me anyway) either in the config file or a drop down then this would solve the issue for me.
