### ISSUE TITLE
Server system stopped working after recent update.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1249]
user@miningserver:~/RainbowMiner$ sudo ./start.sh
Transcript started, output file is .\Logs\RainbowMiner_2020-11-16_18-54-58.txt
__________        .__      ___.                   _____  .__
\______   \_____  |__| ____\_ |__   ______  _  __/     \ |__| ____   ___________
 |       _/\__  \ |  |/    \| __ \ /  _ \ \/ \/ /  \ /  \|  |/    \_/ __ \_  __ \
 |    |   \ / __ \|  |   |  \ \_\ (  <_> )     /    Y    \  |   |  \  ___/|  | \/
 |____|_  /(____  /__|___|  /___  /\____/ \/\_/\____|__  /__|___|  /\___  >__|
        \/      \/        \/    \/                     \/        \/     \/

Starting v4.6.4.9! Please wait..

Detecting devices ..
Initialize configuration ..
Write-Log : Please check your configuration: Conversion from JSON failed with error: Invalid character after parsing property name. Expected ':' but got: ". Path 'DisableMSIAmonitor', line 69, position 3.
At /home/user/RainbowMiner/Modules/Core.psm1:291 char:9
+         Write-Log -Level Error "Please check your configuration: $($_ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

Write-Log :  is invalid. Cannot continue.
At /home/user/RainbowMiner/Modules/Core.psm1:459 char:9
+         Write-Log -Level Error "$($Session.ConfigFiles["Config"].Path ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

Transcript stopped, output file is /home/user/RainbowMiner/Logs/RainbowMiner_2020-11-16_18-54-58.txt
user@miningserver:~/RainbowMiner$

**Comment by RainbowMiner** [comment]
It looks like your config.txt contains some syntax error. Would you please look into the config.txt and inspect the line with DisableMSIAmonitor?
The error message says, there is a ":" missing.

**Comment by RainbowMiner** [comment]
Could you please upload your config.txt (please remove the secret API keys) - do you have more than one config.txt, e.g. for clients in subfolders?

**Comment by RainbowMiner** [comment]
Was this a single version step update? 
v4.6.4.8 -> v4.6.4.9

And, which Powershell version are you using?

**Comment by RainbowMiner** [comment]
Could you also please upload the current `.\Logs\RainbowMiner_2020-11-16.txt` ? This is a pretty strange issue.

**Comment by Yamanipanuchi** [comment]
It was a single step. 

user@miningserver:~/RainbowMiner$ pwsh
PowerShell 6.2.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /home/user/RainbowMiner>


[RainbowMiner_2020-11-16.txt](https://github.com/RainbowMiner/RainbowMiner/files/5549820/RainbowMiner_2020-11-16.txt)

**Comment by Yamanipanuchi** [comment]
I do see some of my other rigs upgraded with no issue. So I may be an isolated issue. Just want to make sure you have the info quickly though.

**Comment by RainbowMiner** [comment]
How weird! It really seems to have a problem with the config.txt parsing, for whatever reason. I'll quickly setup a linux test system and give your config a shot.
What you could do, is to upgrade Powershell to v7.0.3. I'll add an upgrade script later. But these are the steps:
```
wget https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/powershell-7.0.3-linux-x64.tar.gz -O /tmp/powershell.tar.gz
sudo rm -f /usr/bin/pwsh
sudo mkdir -p /opt/microsoft/powershell/7
sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
sudo chmod +x /opt/microsoft/powershell/7/pwsh
sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh
sudo rm -rf /tmp/powershell.tar.gz
```

**Comment by Yamanipanuchi** [comment]
Cool, Ya I followed your steps there.. Upgraded. Of course I tried it just in case. Same outcome.

**Comment by RainbowMiner** [comment]
Ok, could you please now upload all other config.txt in _all_ subdirectories of `./Config` ?
Explanation: the parser reads through all subdirectories and looks, if it can find another config.txt.

**Comment by Yamanipanuchi** [comment]
Got it. I slowly removed each sub config until the script ran. That lead me to the config that was bad and sure enough there was a typo in one.

**Comment by RainbowMiner** [comment]
Very good :) I have updated the error checking for that parser at startup. Now you will see a warning message, but the system will still start.
