### ISSUE TITLE
Getting no value on a few coins on HeroMiners

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1251]
I have not tried any other pools. I am just playing around adding coins to see how well they mine on different systems. I keep getting 0's for the BTC/GH/Day value on several systems.

![image](https://user-images.githubusercontent.com/4724631/99410339-380da580-28a7-11eb-8975-4e5b3eeee52b.png)

At some points there's a value and other times's its 0's. I've noticed when I have it set to only mine herominers and these coins the system keep jumping from coin to coin. I assume it is because it keep getting those 0's from time to time.

Is there a value I need to change for it to hold only that projected value for a longer period of time?

**Comment by RainbowMiner** [comment]
I'll check this and report back.

**Comment by Yamanipanuchi** [comment]
Ya I am curios if its the pool, Or something else. Here is a screen shot now.

![image](https://user-images.githubusercontent.com/4724631/99418122-86bf3d80-28af-11eb-8f04-4756e493d705.png)

You can see the numbers have changed. Might be the pool blocking or not providing the #'s due to so many requests? Or what I am not sure yet.

**Comment by RainbowMiner** [comment]
It has something to do with the internal penalty calculations for that pool. I think, it will need a fix.

**Comment by RainbowMiner** [comment]
Found it. It's a problem with MaxAllowedLuck in combination with coins, that have a very fast blockrate. I'll add a fix.
In the meantime: just set the `"MaxAllowedLuck": "0",` in pools.config.txt for herominers.

**Comment by RainbowMiner** [comment]
Cool. That solves it.

**Comment by Yamanipanuchi** [comment]
So I should not need to change any settings after the update right?

**Comment by RainbowMiner** [comment]
Right.

**Comment by Yamanipanuchi** [comment]
Awesome! Thanks!
