### ISSUE TITLE
Error when running setup.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1254]
Ran setup to see suggested pools for coins and got the following error. Setup did not stop.

Re-installing libraries and binaries ..
./install.sh: line 22: syntax error near unexpected token `$'do\r''
'/install.sh: line 22: `do
Read configuration ..

**Comment by RainbowMiner** [comment]
Oh! Thank you very much for reporting. I'll check asap.

**Comment by RainbowMiner** [comment]
I fixed it.
