### ISSUE TITLE
Decay values are not working correctly?

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1255]
After 4h and 10m since my last rental:     "PriceFactor": 2.2415162829947879,

I am using    
"PriceFactor": "3",
"UpdateInterval": "2m",
"PriceFactorDecayTime": "2m"
"PriceFactorMin": "1.2",

By my calculations, my PF should be 1.2 by now.

**Comment by RainbowMiner** [comment]
There are minimum value in place:
- "UpdateInterval" -> min. 10 minutes
- "PriceFactorDecayTime" -> min. "UpdateInterval"

.. which value have you setup for "PriceFactorDecayPercent"?

**Comment by samdave123** [comment]
"PriceFactorDecayPercent" is 1

**Comment by samdave123** [comment]
I didn't realise UpdateInterval had a min of 10 minutes, that explains my problem. Is it not possible to reduce it further?

**Comment by RainbowMiner** [comment]
> I didn't realise UpdateInterval had a min of 10 minutes, that explains my problem. Is it not possible to reduce it further?

Currently, no. The update process is pretty resource consuming, because a lot of calculations and API calls have to be made.

**Comment by RainbowMiner** [comment]
I am thinking about moving this process to a parallel thread. If I manage to do this, the limit could be removed. But anyway, you will have a lot of API calls, then.

**Comment by samdave123** [comment]
> 
> 
> > I didn't realise UpdateInterval had a min of 10 minutes, that explains my problem. Is it not possible to reduce it further?
> 
> Currently, no. The update process is pretty resource consuming, because a lot of calculations and API calls have to be made.

Okay well 10 minutes isn't quite low enough to achieve what I'm going for, but knowing the limitations I'll adjust my values to get as close as possible.

**Comment by samdave123** [comment]
Thank you @RainbowMiner

**Comment by Yamanipanuchi** [comment]
What is the best place to see if you have Decay setup correctly?

**Comment by RainbowMiner** [comment]
There is a data file, where the current decayed profit factors are stored: `.\Data\mrrcontrol.json` (or for linux `./Data/mrrcontrol.json`). But I could add this information to the localhost, if you wish.

**Comment by samdave123** [comment]
> 
> 
> What is the best place to see if you have Decay setup correctly?

I enter the values into Excel to show the speed of decay.
