### ISSUE TITLE
Update Pools - MinerRocks and AionMine

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1257]
MinerRocks deleted several coins and I think AionMine changed ports

Thanks.

**Comment by RainbowMiner** [comment]
Thank you for reporting. I'll update them asap.

**Comment by jch9678** [comment]
Thanks.

**Comment by jch9678** [comment]
Still having this issue with Aionmine and now Ravenminer gave an error

WARNING: Pool API (Aionmine) for  has failed.
WARNING: Pool Balance API (Ravenminer) has failed.
