### ISSUE TITLE
Lots of crashing miners after latest update 4.6.5.5

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1258]
Lots of crashing miners after latest update.
[debug_2020-11-23.zip](https://github.com/RainbowMiner/RainbowMiner/files/5584852/debug_2020-11-23.zip)

![Screenshot_20201123-095905_Chrome](https://user-images.githubusercontent.com/801414/99997857-9b4d7b00-2d72-11eb-8482-0e05463323f8.jpg)

**Comment by RainbowMiner** [comment]
It looks like the SrbminerMulti has some kind of problem. I'll dig into it.
