### ISSUE TITLE
Issue: Profits do not reflect pools profitability calculations

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#126]
So I've finally got solid stable bench markes to begin further resting. I'm just curious about the pool prices. So I realize in rainbow it is a daily profitability calculation but it doesn't seem right.

For example, I have let them all run all night in blockmasters. Their site is showing since 4 hours ago that  Neoscrypt is there current most profitable coin with no quick spikes but yet other algos like balloon and x16, which are low on the profit scale according to blockmasters site, seem to get a higher profitability in rainbow. I have not touch the switching prevention just FYI. Currently I've been mining x16 all night which is like 5~7th but Neoscrypt would have been more profitable according to the pool all night long. Even miningpoolhub has had Neoscrypt most profitable all night. All rigs are doing this. I don't see how it is says x16 is more profitable then Neoscrypt right now. Power consumption is identical. It appears to be happening with the CPU algos choices to mine as well. Yescryptr16 has been most profitable for days now yet it is showing at the bottom of the list to mine in rainbow. Rainbow benchmarks are accurate without mistakes.

Screen shot of blockmasters pool list. Multiple algos are more profitable then what rainbow is choosing to mine.
![image](https://user-images.githubusercontent.com/42227809/45169542-b55f0b00-b1b2-11e8-878d-1a86d6755647.png)

Screen shot of rainbow 4 gpu rig profitability.
![image](https://user-images.githubusercontent.com/42227809/45168614-8fd10200-b1b0-11e8-8910-2ae95bac686a.png)

Screen shot of rainbow 1 gpu rig profitability.
![image](https://user-images.githubusercontent.com/42227809/45169084-b04d8c00-b1b1-11e8-8fc2-14d8c837b8ad.png)

Screen shot of rainbow 14 gpu rig profitability.
![image](https://user-images.githubusercontent.com/42227809/45169252-0a4e5180-b1b2-11e8-9702-bacb2d5a459b.png)

Screen shot of rainbow 13 gpu rig profitability.
![image](https://user-images.githubusercontent.com/42227809/45169452-821c7c00-b1b2-11e8-8d31-9eeeda201e25.png)

**Comment by RainbowMiner** [comment]
Polling a proper profitability is an averaging and luck problem.
It may happen, that a bunch of blocks are being found in a row for an algorithm at a pool. This would bring up the average (and mostly the estimate) profitability for this algo a lot and it will decrease slowly over time. If we would switch to this algo, after such a lucky time, we would not get this price payed, because we only get reward for the work until a block is found.

The only pool, which is different, is NiceHash. They pay exactly the price announced on their page.

Having this in mind, it is always a trade-off. Over the long run I made the experience that the RainbowMiner basic setup is quiet accurate.

But :) every pool handles the averages different, so I build a lot of fine-adjustment screws into RainbowMiner ("DataWindow" parameter). 

I will have a deeper look into BlockMasters and try to figure out, if we should trim the polling for this.

RBM

**Comment by Byrd1083** [comment]
Yes, I would just think that the logic does not make sense. For example if I wanted to mine the most average coin, I would most likely just solo mine that algo that would guarantee avoiding spikes and I would have to check pools on my own interval if desired. Not a big deal since I have to check them everyday regardless lol. However this is a long debate and a matter of perspective, I think 🤔. 

You must not get lost in the code and still ask yourself, "why is the user using this app?" I know it fda crazy but I've been part of lots of projects that can start out with one important intent and very lost. Ultimately, If the user wants to use a multipool/multialgo miner to profit switch to maximize profitability, why would I even care about average coins to begin with. To be clear, no miner is set it and forget it. Anyone that is expecting that is not realistic or educated enough in what they are doing. Personally, I would want to mine the highest reported algo from each pool, that is why I use a multiminer to begin with. Now, additionally about pools finding coins, rainbow is saying that x16 is most profitable and that is it's bias to mine x16 but even the pool shows that exponential amount of miners are mining neoscrypt compared to x16. So, with that being said regardless of what rainbow bias thinks, I'm not technically ever mining the most profitable coin nor am I following the largest pool that will most likely find a coin first. Logic just doesn't work for my intent, I want to mine either the highest payout/priced coin or here's a new thought, mine in pools with the highest number of workers to maximize potential of reward. 

The bias system almost seems over engineered like my range rover lol. I don't want to blame the pool because they're site is up to date and should be every hour. Would it not make it easier and make more sense plus reduce internet traffic with less requests to just request pool prices on a set interval like 30min or 60mins then switch at that point based on the pool report with out bias. Again, I realize there is a thin possibility that a spike occurred during the interval report but to only mine it for 30 mins so what? It would still be more profitable then relying on complex bias that really makes no sense to the front end user and may not even operate as intended for the back end user ultimately causing less profits with less understandably why. You will fight this forever I guarantee it. MPM has numerous users that non stop complaining about this issue including me.

Please note this has been on my mind for quite some time now. I mean no disrespect, I'm only just sharing my thoughts.

Update: Been about a 90 mins now and still mining x16. Neoscrypt was not spike. Neoscrypt also has the most workers. So bias 😝

**Comment by Byrd1083** [comment]
Instructions are limited here. How to configure this properly. I do not see these settings in any config files?

#### Change a pool's time frame (data window)

To override the default data window "average2e" of the YiiMP based pools (AHashPool,BlazePool,BlockMasters,Hashrefinery,ZergPool,Zpool) the parameter "DataWindow" can be added to the pool's configuration record. 
Possible values are:
- estimate_current (=default): the pool's current calculated profitability-estimation (more switching, relies on the honesty of the pool)
- estimate_last24h: the pool's calculated profitability-estimation for the past 24 hours (less switching, relies on the honesty of the pool)
- actual_last24h: the actual profitability over the past 24 hours (less switching)
- minimum2: the minimum value of estimate_current and actual_last24h will be used
- maximum2: the maximum value of estimate_current and actual_last24h will be used
- average2: the calculated average of estimate_current and actual_last24h will be used
- mininum2e: the minimum value of estimate_current and estimate_last24h will be used
- maximum2e: the maximum value of estimate_current and estimate_last24h will be used
- average2e: the calculated average of estimate_current and estimate_last24h will be used
- minimum2h: the minimum value of estimate_last24h and actual_last24h will be used
- maximum2h: the maximum value of estimate_last24h and actual_last24h will be used
- average2h: the calculated average of estimate_last24h and actual_last24h will be used
- mininum3: the minimum value of the above three values will be used
- maximum3: the maximum value of the above three values will be used
- average3: the calculated average of the above three values will be used

**Comment by Byrd1083** [comment]
Even Zergpool says it's HOT

![image](https://user-images.githubusercontent.com/42227809/45175201-adf32e00-b1c1-11e8-8bad-e30843a49c53.png)

**Comment by RainbowMiner** [comment]
> Instructions are limited here. How to configure this properly. I do not see these settings in any config files?

The easiest way would be to use [C]onfiguration->[P]ools. There is an extra input for the DataWindow. The second (less convenient way) would be to edit the pools.config.txt. There should be DataWindow entries, prepropagated with "average-2e" which I found a very good compromise.

> I also see in my config that I was calculating power. I turned this feature off and now getting much better calculations and results.

Ah! That explains it. I already was wondering, why it was still mining on X16r.  Now it makes sense, since the X16r is cheaper in power consumtion.

**Comment by RainbowMiner** [comment]
How about that:
We could provide users with three or four - easy to explain in one sentence or table - ready-to-go preset profiles, whereas each of them covers another characteristic. 
This could be part of the setup wizard then.

**Comment by Byrd1083** [comment]
Yes it might make the front end user more aware of just what they are setting vs what they are seeing.

**Comment by cromi81** [comment]
I was mining all day with 3 rigs. Calculated profit oscilated in 7-8 USD range. After 24h my rigs mined 3 USD in BTC. I think something is wrong with switching that cancels mining before blockis find and pool is not PPS.
