### ISSUE TITLE
Possible to specify the API port the miner uses?

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1262]
I'd like to be able to specify the port so that each miner uses the same port.  Is that possible?

**Comment by RainbowMiner** [comment]
That is currently not possible. This works only, if you have running one miner at a time.

**Comment by jch9678** [comment]
Yes sorry I could have said that in a clearer way.  I would only run one miner at a time, I don't have a mix of cards in my computers.  Yes that would be great if you could add that.  Thank you.

**Comment by RainbowMiner** [comment]
Ok, I'll add this 👍

**Comment by RainbowMiner** [comment]
Implemented:

- add possiblity to set the miner's API ports to a static value (issue #1262). The following new parameters have been added to config.txt:
  - **StaticCPUMinerPort** = enter a static API port number for all CPU miners (0=use default ports) [default=0]
  - **StaticGPUMinerPort** = enter a static API port number for all GPU miners (0=use default ports) [default=0]

Hint: do not use static GPU ports without setting `"EnableAutoMinerPorts": "1",`, if you have different GPUs and the "MiningMode" set to "combo" or "device".

**Comment by RainbowMiner** [comment]
The 127.0.01 is a standard, that should always be reachable. I'll double check the API settings for teamred.

**Comment by RainbowMiner** [comment]
What does happen, actually? Is the teamred miner running, but RainbowMiner fails to connect?

**Comment by jch9678** [comment]
The interaction between RM and the miner works just fine.  Also I can see the RM Dashboard at 127.0.0.1:xxxx just fine.  But I can't see 127.0.0.1:yyyy where yyyy is StaticGPUMinerPort

**Comment by jch9678** [comment]
From TeamRed usage.txt:

Enables the api. IP:PORT is optional. If present, the IP:PORT combo decides
                              the interface(s) and port to listen to. Default is 127.0.0.1:4028. For
                              external access, use e.g. 0.0.0.0:4028. It's also valid to only specify the
                              port, e.g. 4029.

Maybe it needs 0.0.0.0 before the port?

**Comment by jch9678** [comment]
[debug_2020-12-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/5649619/debug_2020-12-06.zip)

Also the static port doesn't seem to get passed to either Nimiq miner.
