### ISSUE TITLE
Powershell upgrade

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1268]
Tried to use the build in PowerShell upgrade and got the following error.

Ill check some of my other machines tomorrow to confirm if it was just this machine or not...

tar: ./pwsh: Cannot open: Text file busy
tar: Exiting with failure status due to previous errors

**Comment by RainbowMiner** [comment]
Did you stop RainbowMiner before upgrading the Powershell? What was version the formerly installed Powershell?

**Comment by RainbowMiner** [comment]
Hint: if the upgrade fails, you can do it manually.
- RainbowMiner installs the Powershell into `/opt/microsoft/powershell/7` - it will overwrite any existing prior Pwsh 7.
- it then puts a symbolic link to the `pwsh` executable into `/usr/bin`

These are the steps to (re-)install or upgrade Powershell:

1. remove current symbolic link to executable
```
sudo rm -f /usr/bin/pwsh
```

2. Donwload Powershell
```
wget https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/powershell-7.1.0-linux-x64.tar.gz -O /tmp/powershell.tar.gz
```

3. make the Powershell directory, extract the download. then remove the downloaded archive.
```
sudo mkdir -p /opt/microsoft/powershell/7
sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7 --overwrite
sudo rm -rf /tmp/powershell.tar.gz
```

4. make it executable and add new symbolic link in `/usr/bin`
```
sudo chmod +x /opt/microsoft/powershell/7/pwsh
sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh
```

Done!

**Comment by Yamanipanuchi** [comment]
I thought I stopped RBM, but now that I am thinking about it I may not have.

Everything still works. Ill try it again is a short while to make sure it applied correctly.

**Comment by RainbowMiner** [comment]
I will better add a check to the install.sh

**Comment by RainbowMiner** [comment]
I have added a check to the install.sh. The upgrade will fail with an error message, if there is still a pwsh running.
