### ISSUE TITLE
No Benchmarks since last update.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1269]
Since the last update two of my systems have no benchmarks for some device. Debug file submitted below is for a system that only mines CPU and has no benchmarks at all.

![image](https://user-images.githubusercontent.com/4724631/100630472-71023d00-32df-11eb-99b1-9869d91ac26c.png)
[debug_2020-11-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/5616916/debug_2020-11-30.zip)

The next debug file the CPU works but the GPU stopped mining after the update.

[debug_2020-11-30 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/5616922/debug_2020-11-30.1.zip)

I tried clearing all benchmark files, it didn't make a difference. I assume it will clear up as miners get updated. Both miners are VERY small earners so I am not sweating it.

**Comment by RainbowMiner** [comment]
Oh! My bad. The Nanominer module has a problem. I'll post an update asap.

**Comment by RainbowMiner** [comment]
Solved. The v4.6.5.9 should run fine, now.

**Comment by Yamanipanuchi** [comment]
It is! Thanks!
