### ISSUE TITLE
Enhancement: set MPM address, and key in config.txt instead of start

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#127]
This would probably prevent most noobs from breaking start.bat on accident.

**Comment by RainbowMiner** [comment]
Yeah, very good idea. Thank you :)

**Comment by Byrd1083** [comment]
It is broken, when multiple rigs log with the same key it will not show multiple rigs in log. This is probably why MPM sets workers names in the start.bat and not the config.txt.

**Comment by RainbowMiner** [comment]
Yes, with the comeing release the correct worker name will be transmitted.
