### ISSUE TITLE
ETH pool on Binance

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1270]
Binance Pool officially launched an Ethereum mining pool at 12:00 AM on November 12, 2020 (UTC) as published on https://www.binance.com/en/support/articles/97cbbd87bb204d0fbf382544e8073fca

can we add https://pool.binance.com/en ?

The pool have no minimum threshold.
We also can gain from the Binance saving option.

**Comment by RainbowMiner** [comment]
Of course. It will be added today.

**Comment by gurkburk76** [comment]
I'm currently trying this pool as well and there is one thing that strikes me as odd.
I've created a worker name in their pool as per instructions and added it to pools.config.txt
When i check the binance stats page both workers seem to hash away but under a differens workername (__default__) this is probably not a problem but it would make it hard to differentiate bwtween workers if i want to have several.
Is this something wrong on my side? Here is an example:

 "Binance": {
    "Worker": "myworkername",
    "Penalty": "0",
    "DataWindow": "",
    "StatAverage": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "",
    "MaxAllowedLuck": "",
    "MaxTimeSinceLastBlock": "",
    "ETH": "0xmy_eth_wallet",
    "ETH-Params": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "CoinSymbolPBM": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "0",
    "FocusWallet": "",
    "AllowZero": "0"
  },
