### ISSUE TITLE
ZergPool - Curve is broken

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1271]
The profitability is way off.  It might be a pool issue though.  Some machines are mining it and others stopped.
[debug_2020-12-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/5623554/debug_2020-12-01.zip)

**Comment by RainbowMiner** [comment]
Yes, I just discovered that, too. It's CpuminerRplant which gives us exorbitant hashrate. It's API seems to be broken for curvehash. I have just updated that miner module. New release follows asap.

**Comment by jch9678** [comment]
Thank you
