### ISSUE TITLE
MRR Rigs offline

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1272]
RBM has created 119 rigs for me automatically on MRR, And I realize rentals are very slow right now. But I looked further into it and out of all 119 rigs only 5 of them show online. This is across 5 different rigs that I have available for rental.

It would seem I need to reset something, Or something is out of sync. I dont know if simply deleting the rig on MRR and letting RBM eventually replace it is the approach I should take?

What option do I have or should I take?

**Comment by RainbowMiner** [comment]
Is it possible, that these rigs in question are very low profit rigs?
If yes, it could be, that `MaxHours` in pools.config.txt limits the activation of the rig. The default is 168h

**Comment by RainbowMiner** [comment]
Another factor: if a rig is benchmarking, all it's rigs will be disabled in MRR for that time.

**Comment by Yamanipanuchi** [comment]
I assumed some of these same things. Changing the time doesn't seem to make a difference. Yes, some of them are low profit, and those I am not worried about.

![image](https://user-images.githubusercontent.com/4724631/100774142-9f9f1700-33b6-11eb-9e90-e144a5dca1ab.png)

In the image above, T5610 has two 1660Ti's in it.. And those are the only 3 algo's online.
In Solar it has a 1650 Super.. I would expect to see a little less.. But still a few more algo then those 2.

I had my Max time set to 24 hrs, I just changed it to 96hrs, I may push it all the way out to 168 and see what changes. I know it takes about an hour for RBM to update the rigs.

**Comment by Yamanipanuchi** [comment]
I did just notice this....

![image](https://user-images.githubusercontent.com/4724631/100774856-67e49f00-33b7-11eb-9ebe-d88a7ddea97d.png)

**Comment by Yamanipanuchi** [comment]
At a glance, it would almost seem like RBM no longer is updating the rigs that show offline. Almost like either it forgot about them, Or is not processing them for some reason.

I change the Max hours to 96 almost 2 hours ago and to 168 about an hour ago, The rigs that show online have still not updated.

I think you explain it before, but there is a way to completely reset MRR data for a rig right? Removing specific files?

**Comment by RainbowMiner** [comment]
That's strange! I will check, what else could be happening, there. It should not forget, since it loads the actual mrr rig list every round for new.
Could you check, if the rignames are definitely in the rig description?

**Comment by RainbowMiner** [comment]
Another question, are these rigs in master/slave configuration, or do they run standalone?

**Comment by Yamanipanuchi** [comment]
I did check, And yes they are there.

As for master/slave, if you mean pulling there config from an RBM server. Then yes. I don't have any systems that run stand alone.

**Comment by Yamanipanuchi** [comment]
I just check 4 of the 6 API keys, And there all correctly set to the appropriate rigs (No duplicates). Ill check the other two later today when I can get to that location.

**Comment by RainbowMiner** [comment]
If you call the `http://localhost:4000/minersneedingbenchmark` on a rig, where rigs are offline, is it `[]` or does it contain some miners? If it does contain some info, could you please upload it here?

**Comment by RainbowMiner** [comment]
If you call the `http://localhost:4000/asyncloaderjobs` on a rig, where rigs are offline, search for "MiningRigRentals" and find endpoint "/rig/mine", you find something like that:

```
    "447FA263F2EBEDB050C465343777C4C2": {
      "endpoint": "/rig/mine",
      "key": "xxx",
      "secret": "xxx",
      "params": null,
      "method": "GET",
      "base": "https://www.miningrigrentals.com/api/v2",
      "cache": 0,
      "forcelocal": {
        "IsPresent": false
      },
      "raw": {
        "IsPresent": false
      },
      "Error": null,
      "Running": false,
      "Paused": false,
      "Success": 974,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2020-12-01T19:12:19.3799728Z",
      "LastCacheWrite": "2020-12-01T19:12:19.3796591Z",
      "LastFailRetry": null,
      "CycleTime": 90,
      "Retry": 0,
      "RetryWait": 0,
      "Tag": "MiningRigRentals",
      "Timeout": 15,
      "Index": 11
},
```

Could you tell me, if the LastRequest and LastCacheWrite are in sync to your local time? Also do you have "Fail" other than 0?

**Comment by RainbowMiner** [comment]
Could you please upload a Debug file of one of those rigs?
Btw: are the rigs all there on the "MRR Rigs" page on localhost?

**Comment by Yamanipanuchi** [comment]
[debug_2020-12-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/5625252/debug_2020-12-01.zip)

**Comment by Yamanipanuchi** [comment]
Just Refreshed a few minutes ago and more are available. a few from different rigs.

![image](https://user-images.githubusercontent.com/4724631/100793716-6b851f80-33d1-11eb-9d05-1caa481d3212.png)

**Comment by Yamanipanuchi** [comment]
T5610 is current paused, Which probably explains the disabled.

**Comment by Yamanipanuchi** [comment]
So, I found the issue. As you probably saw. I was missing MiningRigRentals in the pools selection.

Dont know how I missed that, Or removed it?

Devices are slowly updating now.

**Comment by RainbowMiner** [comment]
Oh dear! That was so obvious, that I totally oversaw it.

**Comment by Yamanipanuchi** [comment]
Some devices are coming online, But several still show offline or disabled.

**Comment by Yamanipanuchi** [comment]
Yet, those same rigs that show disbaled show online.. Maybe need sometime for everything to catch up?

**Comment by Yamanipanuchi** [comment]
Ohhh.. Its Benchmarking, Like you said earlier... Ya its going to take sometime then...

**Comment by Yamanipanuchi** [comment]
Ya its looking like its all working now... THank for the attention.. :)
