### ISSUE TITLE
Really BAD MRR rental

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1274]
So this rental should never have happened. I am not near the machine to post a Bug Report. I just excluded the RandomX algo all together for now.

This seems to happen often on multiple of my rigs.

![image](https://user-images.githubusercontent.com/4724631/100967296-c149ec80-34e3-11eb-8946-d9d4d466ca14.png)

**Comment by RainbowMiner** [comment]
What is the average profit of that machine?
It would be very interesting, to see the contents of the Profit* files in folder `/Stats`
And of course a Debug file would be super.

**Comment by RainbowMiner** [comment]
Could you please either show a screenshot of the settings at MiningRigRentals.com, or tell me the rig id or rental id? I'ld really like to get to the bottom of this.

**Comment by Yamanipanuchi** [comment]
https://www.miningrigrentals.com/rigs/168274

I will get you the rest of the requested info in about an hour.

**Comment by Yamanipanuchi** [comment]
[debug_2020-12-03.zip](https://github.com/RainbowMiner/RainbowMiner/files/5637002/debug_2020-12-03.zip)

Still working on the profit files.

**Comment by Yamanipanuchi** [comment]
[Stats.zip](https://github.com/RainbowMiner/RainbowMiner/files/5637056/Stats.zip)

**Comment by RainbowMiner** [comment]
Super, thank you. I'll check that now.

**Comment by RainbowMiner** [comment]
Ok, it all comes down to PostBlockMining. You have enabled it for XMR with a time of 300 seconds
```
"XMR": {
      "Penalty": "",
      "MinHashrate": "0",
      "MinWorkers": "0",
      "MaxTimeToFind": "0",
      "Wallet": "XXX",
      "EnableAutoPool": "1",
      "PostBlockMining": "300",
      "Comment": "",
      "MinProfitPercent": "0",
      "MinBLKRate": "0"
    },
```

Since most of the time Hellominer, some of the time HeroMiners find a block in faster than 300 seconds, your rig will mine XMR RandomX most of the time. With CPU and GPU. That kills your average profit for both.

So, currently, I would recommend the following:

#### 1st solution: disable PostBlockMining for XMR in coins.config.txt
```
"XMR": {
...
      "PostBlockMining": "0",
...
    },
```

#### 2nd solution: disable PostBlockMining for Hellominer and HeroMiners in pools.config.txt
```
  "Hellominer": {
...
    "EnablePostBlockMining": "0",
...
  },
```

#### 3rd solution: if you want to keep PostBlockMining for XMR on CPU

1. disable RandomX for GPU mining in devices.config.txt
```
  "GTX1660Ti": {
...
    "ExcludeAlgorithm": "RandomX",
...
  }
```

2. to be sure, set a minimum profit percentage in coins.config.txt:
```
"XMR": {
...
      "MinProfitPercent": "85",
...
    },
```

**Comment by RainbowMiner** [comment]
#### in any case, do this now (or after you have applied one of the above solutions):

- delete files `./Stats/Profit-GPU#00-GPU#01.txt` and `./Stats/Profit-CPU#00.txt`

**Comment by RainbowMiner** [comment]
The prices for MRR will always depend on you rig's current profitability. If you want to add same fail-safe minimum profitability, you could enter a value for  `AutoCreateMinProfitBTC` in mrr.config.txt. That value is in BTC per day. So, if you want to limit the profit to a minimum of 0.2mBTC per day, you would enter this:
```
  "T5610": {
...
    "AutoCreateMinProfitBTC": "0.0002",
...
  },
```

.. but be aware, that this is a static value. So no matter the current profitability of your rig, this will be your lower limit.

**Comment by Yamanipanuchi** [comment]
All make sense! I opted for option 3. I removed the Profit files and set the minprofit. Thanks for the response. I have seen this issue with other Algo in the past and Disabled them because of it.. Now I know what to look for.
