### ISSUE TITLE
Can I tweak the Watchdog settings?

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1275]
I have a rental where MiniZ is incompatible, but RBM keeps trying to get MiniZ running instead of Gminer every 20 minutes which just makes things worse.

I tried to look for Watchdog variables to tweak, but couldn't find any.

Are there any variables I can change to stop RBM from enabling MiniZ so frequently?

**Comment by RainbowMiner** [comment]
There is only on and off, currently. But you could temporarily disable the MiniZ's algorithm in miners.config.txt.
Important: can you tell me the rental id (or for which algorithm the miniZ fails)? I would like to avoid that problem in future release.

**Comment by samdave123** [comment]
https://www.miningrigrentals.com/rental/3060300

I think something needs to be changed for rentals. Either a miner needs to be disabled if it's failing and not keep trying and stick to the backup miner, or RBM needs to abandon the rental.

What is currently happening is that RBM tries MiniZ and it fails, mines for Gminer for 20 mins, tries MiniZ again, and repeats.

**Comment by RainbowMiner** [comment]
> What is currently happening is that RBM tries MiniZ and it fails, mines for Gminer for 20 mins, tries MiniZ again, and repeats.

Yes, that is the intended behavior, currently. I'll think about an alternative approach.

**Comment by RainbowMiner** [comment]
What GPU models are mining inside this rig?

**Comment by samdave123** [comment]
> 
> 
> What GPU models are mining inside this rig?

4X 1660Ti

**Comment by RainbowMiner** [comment]
It was a bug with MiniZ 1.6w4, I have just updated the miner module to v1.6x
