### ISSUE TITLE
Add Argument to miner command for all Algos

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1276]
I would like to add  --bus_reorder  to teamred's miner.  I can do it in the miner configs but that means I have to do it for every algorithm.  Is there a place to do this or can you put this in the ps1 (if that's where you generate the cmd).  

--bus_reorder is supposed to be the default behavior for team red but it doesn't work on my machines.

**Comment by RainbowMiner** [comment]
That's easy, you can use '*' as wildcard for all algorithms in miners.config.txt: just add a new block to the beginning of `Teamred-DEVICENAME`

After
```
  "Teamred-DEVICENAME": [
```

.. add..
```
    {
      "MainAlgorithm": "*",
      "SecondaryAlgorithm": "",
      "Params": "",
      "MSIAprofile": "",
      "OCprofile": "",
      "Difficulty": "",
      "Penalty": "",
      "Disable": "0",
      "ShareCheck": ""
    },
```

Now you can manipulate all algorithms for that miner on devices DEVICENAME.
Be careful not to mess up the JSON structure, use https://jsonlint.com to doublecheck the grammar.

**Comment by RainbowMiner** [comment]
I will better add that `--bus_reorder` to the miner module as well.

**Comment by jch9678** [comment]
In the past I've found that --bus_reorder helps with troubleshooting.  For example if Card 3 in teamredminer fails, which is the corresponding card in OverdriveNTool?  Maybe I'm doing it wrong?

Also there seems to be a problem with gputest.bat  I get:

```
---------------------------
OverdriveNTool
---------------------------
Wrong command: -console-only

"o" cannot be used as [gpu_id]
---------------------------
OK   
---------------------------
```
Does RainbowMiner use OverdriveNTool?

**Comment by RainbowMiner** [comment]
Yes, it does. But the gputestresult.txt should be created, anyway.

The problem will be, that --bus_reorder and --opencl_order contradict each other. So adding that --bus_reorder might fail. If you want to know the PCIe bus, you can easily use the "Selected Devices" tab in the http://localhost:4000 - just click the '+'. The PCI bus will be at two places: either at parameter "OpenCL" ("PCIBusId":"01:00") or directly at parameter "Bus" (1)

**Comment by jch9678** [comment]
It doesn't get created unless it's in a different location.  It tells me it was placed on the desktop but it's not there.

I'll just troubleshoot with RM and --opencl_order, seems like that is a good solution.

**Comment by RainbowMiner** [comment]
> It doesn't get created unless it's in a different location.

It should be created in your Rainbowminer folder.

**Comment by jch9678** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/5644899/gputestresult.txt)

Here it is.
