### ISSUE TITLE
When restarting RBM it doesn't release the 1st GPU.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1277]
The red line is GPU 1 and the blue line is GPU 2, when blue goes down to almost 0 I have just restarted RBM.
![Screenshot_1](https://user-images.githubusercontent.com/801414/101264148-5114b400-36f9-11eb-8e02-f06fd263d9a9.png)

[debug_2020-12-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/5647863/debug_2020-12-05.zip)

**Comment by paulpoco** [comment]
@RainbowMiner did you figure this out?  Or is just my system?

**Comment by paulpoco** [comment]
Uninstalled Nvidia Driver.
Used DDU to remove all traces.
Install Nvidia driver

Works proper now.  @RainbowMiner

**Comment by RainbowMiner** [comment]
Thank you for reporting back :) I am happy, that it all works proper now.
