### ISSUE TITLE
Client Rig Mining on Nicehash only

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1278]
I have some issue after uprade to  PowerShell 7:

1. Warning Message:
WARNING: Get-ServerConfig failed The request was canceled due to the configured HttpClient.Timeout of 20 seconds elapsing.
2. The Rainbow won't start and get error warning 
vcruntime140_1.dll was not found 
3.  It somehow stuck mining to nicehash onely after mining for dev

Solution so far: 
Install C++ 2015-2019 Redistribution
I afraid it would stuck on mining on nicehash again.
When I restart the rainbow miner it always show vcruntime error again so I need to restart the windows.

Please take a look at my debug as well

![image](https://user-images.githubusercontent.com/44210627/101270002-28e38e80-37a7-11eb-98e5-9df6bf938d00.png)
![image](https://user-images.githubusercontent.com/44210627/101270019-4f092e80-37a7-11eb-97b0-d1b8de062796.png)
[debug_2020-12-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/5648198/debug_2020-12-06.zip)

**Comment by RainbowMiner** [comment]
Could you please upload the server's Debug file, too?

**Comment by RainbowMiner** [comment]
It looks like that rig has some issues with a firewall or networking, in general. Looking through the logfiles, it looks like it is not able to connect. Could you please try to switch the client to `"MiningMode": "Standalone",` to see, if it cannot connect to the server, or if it's a general networking problem.

**Comment by rizkyaulya** [comment]
> It looks like that rig has some issues with a firewall or networking, in general. Looking through the logfiles, it looks like it is not able to connect. Could you please try to switch the client to `"RunMode": "Standalone",` to see, if it cannot connect to the server, or if it's a general networking problem.

Yes I switched some of my RIGs to standalone mode now.



> Could you please upload the server's Debug file, too?

[debug_2020-12-06 server.zip](https://github.com/RainbowMiner/RainbowMiner/files/5649105/debug_2020-12-06.server.zip)

**Comment by RainbowMiner** [comment]
This is a strange issue. Could you check, if you can reach to your server http://RIG2:4000 from one of those clients, using a browser?

**Comment by rizkyaulya** [comment]
> This is a strange issue. Could you check, if you can reach to your server http://RIG2:4000 from one of those clients, using a browser?

Yes. I can reach the server from dashboard any client browser

**Comment by Yamanipanuchi** [comment]
So, I just noticed this same issue with one of my Windows machines I upgraded to PowerShell 7, This is the only machines ive done this on so far. And it was showing the same thing thing. it was only Nicehash. I closed the script and Re-opened it and then it had the correct info.

**Comment by Yamanipanuchi** [comment]
[debug_2020-12-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/5680045/debug_2020-12-11.zip)

The I restarted the script less then an hour ago, So whatever was not working would be less than an hour into the logs.

**Comment by rizkyaulya** [comment]
I just realize there is an error message like this:
![image](https://user-images.githubusercontent.com/44210627/103357478-dbc4b500-4ae5-11eb-9fe1-7ae0c605f424.png)

**Comment by RainbowMiner** [comment]
Looks like some stat file is either corrupted or missing. I'll dig a bit to find out.
