### ISSUE TITLE
Phoenixminer on windows wrong benchmark

### ISSUE THREAD

**Issue by qinapps** [RainbowMiner/RainbowMiner#1279]
On windows shows by Phoenix miner wrong results. its says xxx khs instead of MHs

**Comment by RainbowMiner** [comment]
Oh! I didn't see this. I'll check the miner.

**Comment by RainbowMiner** [comment]
My rigs all show MHs - question: which GPUs are you using?

**Comment by qinapps** [comment]
RTX 3090 on windows10

**Comment by jch9678** [comment]
Mine show kh/s

Phoenix 0.65% EtcHash   160.82 kH/s    - 1463W 0.00000024    0.005      88% MiningPoolHubCoins-Ethereum   1.10%

I just created a duplicate issue, I'll close mine.

**Comment by RainbowMiner** [comment]
Ah sorry. Found & fixed it.

**Comment by jch9678** [comment]
I'm still seeing this in RM's console

Phoenix 0.65% EtcHash   163.00 kH/s    - 1495W 0.00000018    0.003      97% Ethermine-EtherClassic   1.00%

**Comment by jch9678** [comment]
Actually it was fixed but we have to re-benchmark because the speed value was outside the tolerance

**Comment by RainbowMiner** [comment]
Yes, sorry. I should have added an automatic reset for Phoenix Etchash to the cleanup. I'll add it now, just to be sure.

**Comment by jch9678** [comment]
No problem, thanks for the fix.
