### ISSUE TITLE
Zergpoolcoins Equihash144

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1280]
Getting an end of file error on this, possible personalisation issue?

**Comment by RainbowMiner** [comment]
Which miner throws that error?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/101481018-67ff1480-394c-11eb-998e-37706d33c9f0.png)
Seems to be gminer.

**Comment by RainbowMiner** [comment]
There was one coin missing in the pers database (ZCH / 0cash) - maybe that was the problem.
