### ISSUE TITLE
2miners Seems Broken on Beam

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1283]
This is in the miner console

Connected to us-beam.2miners.com:5252  (TLS disabled)
Lost connection to stratum server us-beam.2miners.com:5252 or server not reachable.
Trying to connect in 1 second

**Comment by RainbowMiner** [comment]
Thank you, I'll check it.

**Comment by RainbowMiner** [comment]
Fixed. BEAM needs ssl connection.

**Comment by jch9678** [comment]
Thank you very much.  Any luck with PhoenixMiner and RM mh/s vs kh/s problem and also the api port issue?
