### ISSUE TITLE
Enhancement: Stat folder separations

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#129]
Since, I've been benching and testing, I find myself in the stat folder a lot deleting bad benches to trigger a rebench. It would be an improvement to have these following 

stat sub folders:
- pools
- benchpass
    - cpu
    - nvidia
    - amd
- benchfail
    - cpu
    - nvidia 
    - amd

It would be great to have this folder structure for all pass/fail benchmarks so I do not delete a good bench on accident with them all crammed into one or get it confused with naming conventions. Plus would give a better understanding as to which miners need to be excluded or parameters adjusted.

**Comment by RainbowMiner** [comment]
Very nice. You could use http://localhost:4000 -> click on Benchmarks until I will update this. There is a complete, filterable list and a button to clear out all failed.

**Comment by Byrd1083** [comment]
I see, I have not been using localhost. Just rummaging through folders and files up to this point.
