### ISSUE TITLE
odvii_x64.exe - System Error

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1299]
I started getting this error on RainbowMiner start after updating PowerShell to 7.1 and release 4.6.7.0  Do you think there's any correlation?  I've noticed on 2 machines.

---------------------------
odvii_x64.exe - System Error
---------------------------
The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

**Comment by RainbowMiner** [comment]
Please run the Install.bat - it looks like, the Microsoft Visual C++ Redistributable is either missing or too old.
If that doesn't work, [download the VC redist installer](https://aka.ms/vs/16/release/vc_redist.x64.exe) from Microsoft and reinstall it.

**Comment by jch9678** [comment]
Re-installing the redistributables fixed it.  Updating to powershell 7.1 somehow deleted or changed or made the installed ones obsolete.  This happened on a few machines.   Thanks.
