### ISSUE TITLE
Add power consumption details and show net profit

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#13]
It is really good if you can add power consumption details per algo. and deduct it from the profit and show net profit.

**Comment by RainbowMiner** [comment]
I am already working an this. I could already supply power consumption details for nVidia GPUs. Do you own AMD or nVidia or both?

**Comment by rinkal26783** [comment]
I have nVidia

**Comment by RainbowMiner** [comment]
Ok, I am on it.

**Comment by RainbowMiner** [comment]
Done! See commit 48c1c2fc78ffd9dcb251c5f7b9de61629c237ca9
To install, use new release of v3.8.0.0: https://github.com/RainbowMiner/RainbowMiner/releases/download/v3.8.0.0/RainbowMinerV3.8.0.0.zip

For usage, read the Readme.md, section "config.txt": https://github.com/RainbowMiner/RainbowMiner

RBM

**Comment by RainbowMiner** [comment]
Update: for convenience, I have pushed anonther mini release.
From now on, missing fields in config.txt will be added automatically at startup of RainbowMiner.

To install "Electricity Cost" plus this mini release, use release v3.8.0.1:
https://github.com/RainbowMiner/RainbowMiner/releases/download/v3.8.0.1/RainbowMinerV3.8.0.1.zip

**Comment by rinkal26783** [comment]
There are 48 miners left for benchmarks. But its only mining x16r for last 30 min
![image](https://user-images.githubusercontent.com/30832110/44076872-625ae32a-9fbf-11e8-96d7-b221ccc3b26c.png)

**Comment by RainbowMiner** [comment]
Please try bugfix release https://github.com/RainbowMiner/RainbowMiner/releases/download/v3.8.0.3/RainbowMinerV3.8.0.3.zip

I think, this should solve the problem.
