### ISSUE TITLE
Trex Octopus

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1304]
For some reason TrexOctopus isn't available on some of my rigs. They are all using the same driver version 441.34 and have 6 or 8gb of memory. I can't see a reason why it won't even show up in benchmarking. Here are the debug files for one that is working and one that isn't.

[debug_2021-01-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/5809522/debug_2021-01-13.zip)

[debug_2021-01-13 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/5809524/debug_2021-01-13.1.zip)

**Comment by wizkah** [comment]
I had the same problem. When investigating I stumbled over `    $UriCuda = @(
        [PSCustomObject]@{
            Uri    = "https://github.com/RainbowMiner/miner-binaries/releases/download/v0.19.12-trex/t-rex-0.19.12-win-cuda10.0.zip"
            Cuda   = "11.1"
        }`
I replaced the executable with the Cuda11-Version: et voila, T-Rex Octopus was there again.
