### ISSUE TITLE
Rejected shares

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1308]
I've noticed nicehash ethash has been giving me more rejected shares than it used to. I don't know why but nicehash customer service sucks so it's hard to investigate. Would it be possible to add 'rejected shares' to the main local host page please so I can keep an eye on it?

![image](https://user-images.githubusercontent.com/42582444/104590295-058fe700-5663-11eb-87ac-41737b11470f.png)

Thanks in advance.

**Comment by RainbowMiner** [comment]
Sure. I'll add the number.

**Comment by acos0874** [comment]
OK will do if the problem continues. I did find I was getting hardware rejected shares with all miners but this was due to too high OC I think.

**Comment by samdave123** [comment]
> add a Penalty matching the Rejected/Accepted shares ratio

Is this something RBM could do automatically? Manually checking rejected shared ratios and adding penalties sounds like a PITA and something that could be automated.

**Comment by RainbowMiner** [comment]
> Is this something RBM could do automatically?

That's kind of tricky, since it might induce a lot of switching. I will make some tests.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/104633473-19554080-5697-11eb-847b-32bdd5959166.png)

It looks like Sparkpool has some EU pools which don't seem to get selected by rbm. Would it be possible to add these please? Might be a good alternative to nicehash.

**Comment by acos0874** [comment]
I just read that connecting to the USA nicehash server reduces the rejected shares. Going to test this.

**Comment by acos0874** [comment]
Thanks!

**Comment by RainbowMiner** [comment]
> It looks like Sparkpool has some EU pools which don't seem to get selected by rbm. Would it be possible to add these please? Might be a good alternative to nicehash.

I am updating Sparkpool now.

**Comment by acos0874** [comment]
Thanks
