### ISSUE TITLE
MinerMore pool back

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1309]
I seem to recall MinerMore pool being removed from RM sometime last year? Anyway, I can't see it in my current pools.config.txt

Just stumbled on this article saying MinerMore pool is back up: https://www.reddit.com/r/Ravencoin/comments/ka1i79/minermore_mining_pool_is_back_under_new_ownership/

https://minermore.com/

**Comment by RainbowMiner** [comment]
Yes, it's removed. I'll check.
