### ISSUE TITLE
New miners in latest release benchmark issue

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#131]
Latest release minor update fails to benchmark. I guess it is because of msi profiles? 
![screenshot_20180909-202146_teamviewer](https://user-images.githubusercontent.com/35561346/45267510-5e855a00-b46e-11e8-83a2-835c6609759c.jpg)

**Comment by RainbowMiner** [comment]
Yes, looks like they are more sensitive to overclocking. Which profile is setup for ethminer and fireice?
I have the impression, that the new ethminer version isn't that stable (it is 0.1.6rc1 release candidate 1), so I think I will downgrade this miner until it will be released a final version. Also, try profile 5 (then 3, then 4).
For FireIce: the default profile is being used for this one. You could try a more relaxed profile for that (it is cryptonight, so maybe it is not worth the effort).

**Comment by ebojali** [comment]
Actually the new release overrides my nvidia. config file in the bin/cryptonight-Fireice folder.. That is the main reason for the benchmarks to fail. Ethminer worked fine after a rebench, cryptonightV7 worked out by changing hte config in nvidia file, Still figuring out what to do with the cryptonightHeavy. Perhaps just remove that algo completly instead.

**Comment by RainbowMiner** [comment]
Oh! Now I understand. Yes, during miner update, the whole directory is being deleted and then recreated with the new version. I will figure out a solution for this.

**Comment by Byrd1083** [comment]
Scrap AF and use nvidiainspector. You will not have any more issues after that. If you need help let me know. You will need a custom batch file. Tell me your gpu and I can put a batch file together for you. You will be able to lock voltage as well and run low stable watts no lag. You will need to Uninstall msi af completely.

**Comment by Byrd1083** [comment]
Exclude cryptonightheavy. It isn't profitable and uses way more watts. It lags my system bad. No money to make there.

**Comment by Byrd1083** [comment]
You should exclude fireice. It has issues with loading its own config files as well that can screw with over clocking. If you head to the bin file and find it you will see separate files for amd, cpu, nvidia. You can optimize each one through the api and it will apply them even when rainbow launches. It is by program design and has a high dev fee that can not be removed. There is xmr-stak benchmark sites you can find online to show best optimizations of those configs. Personally xmrig for cpu and srbminer for amd are better choices for cryptonightv7. Frankly it is not worth running nvidia on cryptonightv7 anyway. You can plan on it only running amd and cpu. Currently x16r and hmq1725 is what is top profitable on nvidia right now.💲💲💲

**Comment by Byrd1083** [comment]
Here is my exclusing list:

"ExcludeMinerName": "ClaymoreEquihashAmd,ClaymoreCryptonightAmd,SgminerKl,XmrigAmd,Sgminer,ClaymoreNeoscryptAmd,Cast,CpuminerJayddeeAvx2sha,CpuminerTpruvotAvx2,CcminerTpruvotx64,CpuminerTpruvotCore2,CpuminerTpruvotCorei7",

**Comment by Byrd1083** [comment]
Here I took the liberty of creating you a custom batch file for nvidiainspector. just place this file in the same directory as NVI enforce admin rights and run the batch file. You will need to completely remove MSI AF or it could BSOD on you. You can close NVI after applying but you will need to run the bat every time you reboot. ethpill can run with this no problem. You should see stable 130~170watts stable depending on algo you are mining. You picture shows way to high power consumption.

Tested and stable on 1080 ti 11gb
[ApplyNVI - 6x1080ti.txt](https://github.com/RainbowMiner/RainbowMiner/files/2377642/ApplyNVI.-.6x1080ti.txt)

**Comment by RainbowMiner** [comment]
Thanks a lot for the details!
One remark: I forked the fireice miner and compiled a RainbowMiner version, with developer fee set to 0%. It is already part of the current release :)
