### ISSUE TITLE
RPlant-combode showing oddly high value

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1310]
![cmd_2021-01-14_23-36-30](https://user-images.githubusercontent.com/17214552/104591821-5b937780-56c1-11eb-8814-b83c75689299.jpg)

USD$1,346/day seems a bit high? It was showing 100x higher up until 1-2 hours ago so I'm not sure what's going on there?

**Comment by AnthonyBe** [comment]
Seems to be settling down. I'm now seeing USD$87/day

**Comment by RainbowMiner** [comment]
Oh. Yes, that seems a bit high. I'll have a look.

**Comment by AnthonyBe** [comment]
Seems to have settled right down back to 'normal' expected value.

**Comment by RainbowMiner** [comment]
Odd. Yes, I have checked the API readings multiple time, yesterday. Looked good. So I'll close this issue for now.
