### ISSUE TITLE
PYRK-yespower does not resolve to PYRK

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1311]
As in the title, it appears that PYRK-yespower does not resolve to PYRK.
This means that mining for PYRK coins when switching, it is selecting payouts in BTC rather than PYRK.

**Comment by RainbowMiner** [comment]
For which pool?

**Comment by talentoscope** [comment]
I *think* it's ZergPoolCoins

**Comment by RainbowMiner** [comment]
Ok, I'll check it.

**Comment by RainbowMiner** [comment]
Ah! I've got it. It's a multi algorithm coin. And it's not in our coins database, yet. I'll add it now.

**Comment by talentoscope** [comment]
Woohoo!
Thanks again mate :)

**Comment by RainbowMiner** [comment]
There is more - did you specify `"PYRK": "yourpyrkwalletaddress",` in your pools.config.txt, or different?

**Comment by talentoscope** [comment]
PYRK is specified in my coins.config.txt, all pools are set to autoenable
for all coin wallets

**Comment by RainbowMiner** [comment]
Ah, ok. Super. Thanks for the quick reply.

**Comment by talentoscope** [comment]
Closing my issue as this has been fixed in the above commit.
Thanks again mate.
