### ISSUE TITLE
Feature Suggestion: Pay Rate Tracking Graph

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1312]
Not essential but something I thought that would be cool to see, would be a line graph tracking the payrates for various pools of the same algos. 

![image](https://user-images.githubusercontent.com/42582444/104713214-785c9900-571b-11eb-8982-4cab13792d9d.png)

The idea is inspired by the difference in pay rates from various ethash pools (zergpool could be included here) and I'm just curious how that vary over time. There could also be an average daily pay rate.

On a side note, I have observed that the 'whattomine' data being pulled for ethermine uses a block reward for the past 24 hours, rather than the current one, which is why it's higher than the rest because the blockreward had a spike yesterday. I was wondering if there is a way of selecting current estimates. I have current estimates set in the pools config.

**Comment by shocker1185** [comment]
2nd.
