### ISSUE TITLE
RBM goes offline in middle of night

### ISSUE THREAD

**Issue by LarryJ88** [RainbowMiner/RainbowMiner#1317]
I am new to RMB, but I have been having the same issue the last couple of nights. My machine runs well until about 2:00am EST when it goes offline. I am only mining using GPUs, and have no other programs running that could effect CPU performance. 
Also, is there to reboot when miner goes offline?

Thanks,
Larry

**Comment by RainbowMiner** [comment]
Is this a Windows machine?
Please create a Debug file (go to http://localhost:4000 and then click "Debug file" on the left hand side) and upload it here. I'll look into it.

**Comment by LarryJ88** [comment]
Yes, it is a Windows machine. I am in the process of building a Linus machine with 8-10 cards for stability purposes though. Attached is the debug file. 

[debug_2021-01-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/5821199/debug_2021-01-15.zip)

**Comment by RainbowMiner** [comment]
Thank you.
At first glance, it looks like a Windows process is shutting down RainbowMiner and/or the machine. Is the machine in standby in the morning?
Also, I have noticed some misconfiguration. Look into config.txt, find `"Currency": "abort",` - change it to something like `"Currency": "BTC,USD,EUR",`, best practice is to have at least "BTC" plus your home country currency here.
And maybe consider to reduce the number of selected pools. Just use those, that you really want to your mining power to be directed. If it's BTC only, that you are after, only the autoexchange pools (like ZergPool or ZergPoolCoins for example) make sense.

**Comment by LarryJ88** [comment]
I have the machine set to never got into standby mode. So it is just open and RBM shows a black screen. 

I will make the adjustment to the config doc.

I am only mining BTC, ETH, and RVN now - although I am considering expanding that.
