### ISSUE TITLE
Two rentals for the same rig

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1318]
My rig was just rented twice within about a minute of each other. @merc in MRR's Discord said this is because I am not using the "riggroup functionality". Can this be implemented to fix this issue and prevent reoccurance? 

https://www.miningrigrentals.com/rental/3113673
https://www.miningrigrentals.com/rental/3113674

**Comment by RainbowMiner** [comment]
Yes, @merc is right. We have this functionality since some time, now. I will add this as soon as possible.

**Comment by RainbowMiner** [comment]
Ok, I have implemented the MRR rig groups and will do some tests. If everything runs fine, I'll push a new release.
