### ISSUE TITLE
PowerShell version detection

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1319]
I just updated to PowerShell v7.1.1 and on restarting RM got the following:

![image](https://user-images.githubusercontent.com/17214552/104784416-524afd80-57dc-11eb-96ae-c7fb2719f571.png)

```
Starting v4.6.7.1! Please wait..

RainbowMiner recommends Powershell Core Version 7.1.0 (vs. v7.1.1)
Everything will run fine with the current version, but consider updating your Powershell

Link for Powershell: https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0
```

Not sure if your intent is to:

1. Specify a _specific_ version, or 
2. Just recommend a _minimum_ version.

If the latter, the version check code will need tweaks to allow for the fact there may be versions newer than what is known at time of code check-in.

Oh, and just a minor aesthetic thing; it is Power**S**hell and not Power**s**hell :)

**Comment by RainbowMiner** [comment]
> 2. Just recommend a minimum version.

It's that. I'll fix it. Thank you!
