### ISSUE TITLE
New pool balances all wallets available

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#132]
Very nice the new feature on 3.8.6.6. for all pool balances. Would if be possible to show all wallets in config?

In my case, I have BTC and STAK on BlockMasters and is only showing STAK and ZergPoolCoins is not showing under ZergPool. Although all current available on MiningPoolHub are showing.

![image](https://user-images.githubusercontent.com/41829368/45270264-b022ea00-b458-11e8-9edd-e8cec0205a5c.png)

**Comment by RainbowMiner** [comment]
Sure, I will check :)
