### ISSUE TITLE
Baikalmine does not support coins

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1320]
Baikalmine does not support RYO or ZCL, but RBM attempts to poll the API for these coins.

Relevant log part:

``[2021-01-15 00:00:57] Error job 99A1D57337C112F50C0E46290F2A19D7 with https:///api/stats using REST: Problem fetching https:///api/stats using REST: Cannot convert argument "address", with value: "https:///api/stats", for "FindServicePoint" to type "System.Uri": "Cannot convert value "https:///api/stats" to type "System.Uri". Error: "Invalid URI: The hostname could not be parsed.""``
``[2021-01-15 00:01:07] Error job C1F91B0300FBA82280ADA43A2D5C250E with https://ryo.baikalmine.com/api/stats using REST: Problem fetching https://ryo.baikalmine.com/api/stats using REST: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.``
``[2021-01-15 00:01:17] Error job 53752D850EC4B711C18C15EFBAA2788C with https://zcl.baikalmine.com/api/stats using REST: Problem fetching https://zcl.baikalmine.com/api/stats using REST: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.``

**Comment by RainbowMiner** [comment]
Thank you! I'll update the pool module.

**Comment by talentoscope** [comment]
Thank youuuu! :)
