### ISSUE TITLE
RainbowMiner not Benchmarking Ethash and Etchash

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1326]
[debug_2021-01-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/5826870/debug_2021-01-17.zip)

I'm having this problem on more than one machine.
Thanks.

**Comment by RainbowMiner** [comment]
Is it a GPU memory problem? Do they all have more than 4GB memory?

**Comment by jch9678** [comment]
Yes they all have 8gb of memory.  It's a 390

**Comment by jch9678** [comment]
I found a clue.  noncerpro wasn't benchmarking at all but it shows up in RM.  I went to the noncerpro directory in bin and started it's default batch file.  This is what I got.

```
C:\Users\xx\Desktop\RainbowMiner GPU\Bin\AMD-NoncerPro>noncerpro.exe --address="xx" --threads=2 --server=eu.nimpool.io --port=8444 --mode=dumb
[I 13:54:44] NoncerPro: NoncerPro OpenCL Miner 3.0.2 starting
[I 13:54:44] NoncerPro: Address                xx
[I 13:54:44] NoncerPro: Mining mode            dumb
[I 13:54:44] NoncerPro: Device Name            xx
[I 13:54:44] NoncerPro: Number of Pools        1
[I 13:54:44] NoncerPro: Active Pool            eu.nimpool.io
[I 13:54:44] NoncerPro: Active port            8444
[I 13:54:44] NoncerPro: Active gpu ids         0
[I 13:54:44] NoncerPro: threads                2
[I 13:54:44] NoncerPro: API status             Disabled
[I 13:54:44] NoncerPro: Initializing active GPUs. This might take a while.
Selected platform: Advanced Micro Devices
Detected 1 total devices
Active devices:
    GPU#0, Name: Hawaii, Detected total memory: 512 MB, Allocated memory: 384 MB with 2 threads
Building kernels...
Could not allocate 201326592 of memory. Try a lower --batchsize

C:\Users\xx\Desktop\RainbowMiner GPU\Bin\AMD-NoncerPro>pause
Press any key to continue . . .
```

For some reason only 512mb of video memory is being detected.  Is this a hardware problem?  Can memory go bad on a card and it still mine, because nqminer still works albeit at a lower speed than normal?

**Comment by jch9678** [comment]
![Capture](https://user-images.githubusercontent.com/12422346/105086656-f04dfa80-5a5e-11eb-9d52-c9a7064d013f.PNG)
Windows detects the correct amount of memory?

**Comment by RainbowMiner** [comment]
What does RainbowMiner say? Are the 8GB visible in localhost?

**Comment by jch9678** [comment]
![Capture](https://user-images.githubusercontent.com/12422346/105087896-c72e6980-5a60-11eb-8827-59fc621532df.PNG)
It only shows 512mb also

**Comment by RainbowMiner** [comment]
Oh, that is strange. Why would OpenCL report back that weirdo number. Something must be very off. So either, the hardware is defective, or there is a driver problem. It almost looks like the R9 390 is handled as on-chip with the CPU with shared memory.

**Comment by jch9678** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/5843848/gputestresult.txt)

**Comment by jch9678** [comment]
I was testing a couple identical 390s in this same machine.  They were both bad.  One didn't POST at all and the other is able to load BIOS but not windows.  Could this machine, somehow think it still has one of the bad cards in it?  I can DDU the driver and see if that changes anything.

**Comment by jch9678** [comment]
DDU and re-install 20.4.2 drivers still shows 512MB

**Comment by jch9678** [comment]
Found the culprit.  I had enabled Resizable BAR in the new bios and was using an incompatible driver.  I updated to 20.12.1 and 8gb was detected correctly.  https://forums.guru3d.com/threads/resizeable-bar-support-issues.435389/

**Comment by RainbowMiner** [comment]
Super! Thank you for the feedback. So I'll close this issue for now.
