### ISSUE TITLE
error loading rainbowminer

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#1327]
https://i.imgur.com/Au9kclk.png

**Comment by RainbowMiner** [comment]
Is this still an issue? When does this happen?
Do you have a larger image, I can barely read it.
A zip of the Logs folder would be of great help, too.

**Comment by szentigrad3** [comment]
![Au9kclk](https://user-images.githubusercontent.com/5462780/105049874-42276c80-5ac1-11eb-91f2-ce673bf54ecf.png)

yes it is still happening

[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/5836558/Logs.zip)

**Comment by RainbowMiner** [comment]
Ok, found it. It's a problem with the version checker function. You can easily work around it by installing the new release of [Powershell Core 7.1.1](https://github.com/PowerShell/PowerShell/releases/download/v7.1.1/PowerShell-7.1.1-win-x64.msi)

**Comment by RainbowMiner** [comment]
The problem with Powershell "rc"/"preview" versions is solved in the current release v4.6.7.3

**Comment by RainbowMiner** [comment]
That should be solved by now
