### ISSUE TITLE
RPlant-combode showing oddly high value (again)

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1328]
Same as #1310 again.

![image](https://user-images.githubusercontent.com/17214552/104965698-65a3d600-5a33-11eb-8452-002ee38ae919.png)

I've watched it for last 10 mins and it's I've watched it go up and down, i.e. it's not going in one single direction currently.

I could only wish that it was netting me USD$223m/day :)

**Comment by RainbowMiner** [comment]
What is this, with Combode ?! I'll try to find out.
