### ISSUE TITLE
Pool Balances not showing up.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1333]
Since the last few updates Balances for HelloMiner and HeroMiners not showing up. Not sure if its just me or a bug. Posting here just in case.
[debug_2021-01-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/5843885/debug_2021-01-20.zip)

**Comment by RainbowMiner** [comment]
It looks like a firewall and/or nameserver problem (maybe restart your router, just in case):
> Problem fetching https://ethereum.herominers.com/api/stats using REST: No route to host (ethereum.herominers.com:443)

**Comment by shocker1185** [comment]
i have a balance issue with herominers as well...it shows a total for usd and btc values but no determination of which coin it is....
it would be nice to always show in the profit/day category the coin that is currently being mined or auto exchanged to.

**Comment by Yamanipanuchi** [comment]
I cant get to HeroMiners no issue, I would guess its probably the API URL? No sure why it suddenly is being blocked.
