### ISSUE TITLE
Problem selecting correct port for difficulty, Conflux, Herominers

### ISSUE THREAD

**Issue by shocker1185** [RainbowMiner/RainbowMiner#1334]
Herominers CFX mining automatically sets the port to xxx22, which is too high of a difficulty for me to mine. I can't say for sure if this is with all miners or not. Can there please be an easier way to change the port, or benchmark for profits between them?

**Comment by RainbowMiner** [comment]
You are right - Herominers have changed their port config descriptors in the API. I'll supply you with a patch asap.

**Comment by RainbowMiner** [comment]
> Can there please be an easier way to change the port, or benchmark for profits between them?

That is quiet complicated. I'll try to find a way to supply you with the possibility to set ports directly.
