### ISSUE TITLE
What does GetCPU do, is it necessary?

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1337]
The Event Viewers for my machines are filled with Errors related to GetCPU.  Are these errors having any effect on stability?

```
Faulting application name: GetCPU.exe, version: 1.0.0.0, time stamp: 0xb000021b
Faulting module name: KERNELBASE.dll, version: 10.0.18362.997, time stamp: 0xd5511be4
Exception code: 0xe0434352
Fault offset: 0x001140b2
Faulting process id: 0x19dc
Faulting application start time: 0x01d6ef279f1ed430
Faulting application path: C:\Users\xx\Desktop\RainbowMiner GPU\Includes\getcpu\GetCPU.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ec9814f0-cd09-4803-97c2-c771a61701ce
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Application: GetCPU.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)
   at GetCPU.Program.GetSystemInfo()
   at GetCPU.Program.Main(System.String[])
```

**Comment by RainbowMiner** [comment]
I'll have a look - it's a proxy for the OpenHardwareMonitor. It should not have an effect on the stability, but it could be, that RainbowMiner doesn't get the CPU temperature.

**Comment by jch9678** [comment]
I just got this on a machine

---------------------------
GetCPU.exe - Application Error
---------------------------
The exception unknown software exception (0xe0434352) occurred in the application at location 0x00007FFC28B63E49.


---------------------------
OK   
---------------------------

Monitoring Central shows the machine as having crashed 28 times in the last hour but it looks fine.  Could these be correlated?
