### ISSUE TITLE
Dashboard all MPH coins shows up in the Balances

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#134]
Dashboard MPH balance shows a box for each coin, perhaps it is a good idea to actually combine them on thw webpage but keep the separate prinout in the console.

![image](https://user-images.githubusercontent.com/35561346/45284783-a7c2c180-b4e1-11e8-8d80-729e6fa16f5b.png)

![image](https://user-images.githubusercontent.com/35561346/45284814-bb6e2800-b4e1-11e8-882d-80a175660206.png)

**Comment by RainbowMiner** [comment]
You are right. It should be added together.
