### ISSUE TITLE
[Issue] Default Wallet

### ISSUE THREAD

**Issue by shocker1185** [RainbowMiner/RainbowMiner#1346]
Let's say I'm mining zpool, all algorithms selected, XVG,TTN,XSH wallets enabled. By default, BTC is the "default" wallet that will be used when RB-miner doesn't have a wallet address for the current coin its mining.
If "focus wallet" is set, RB-miner will set the focus wallet to the mining wallet regardless of the coin being mined. WIth "focus wallet" not set, it will pick the relative wallet to use, and switch to the "default" for auto-exchange if RB-miner doesn't have a known wallet.
I want to set XVG as the "default".

**Comment by RainbowMiner** [comment]
We have `"AECurrency": "XMR",` for that case. At least, I think. I will doublecheck this.

**Comment by shocker1185** [comment]
> We have `"AECurrency": "XMR",` in pools.config.txt for that case. At least, I think. I will doublecheck this.
> 
> EDIT: This parameter is avail in the `*Coins` pools only, currently.

Ah, yes. Thank you. I was wondering what that was. It was causing me errors when both AECurrency and FocusWallet were set.

**Comment by RainbowMiner** [comment]
Yes, that may contradict each other. Thanks to your input, I am just wondering, if the Zpool.ps1 and ZergPool.ps1 need a rework, so that AECurrency can be used, as well. FocusWallet has another intention: it's for force mining to a certain coin in non-autoexchange pools.

**Comment by RainbowMiner** [comment]
Done. Thank you!
From now on, you can simply set "AECurrency" for Zpool, ZergPool, ZergPoolParty and ZergPoolSolo to select your default wallet, too.

**Comment by shocker1185** [comment]
> Done. Thank you!
> From now on, you can simply set "AECurrency" for Zpool, ZergPool, ZergPoolParty and ZergPoolSolo to select your default wallet, too.

Thank you for all your amazing work!
