### ISSUE TITLE
Can we have the ability to point to our own server?

### ISSUE THREAD

**Issue by Puxta** [RainbowMiner/RainbowMiner#1348]
I would like to use this software to point to my own pool (bitcoin core).  Is that possible?

**Comment by RainbowMiner** [comment]
Currently not - I'll add custom pools asap.

**Comment by paulpoco** [comment]
Flexpool for ETH?

**Comment by RainbowMiner** [comment]
- add userpools (issue #1348)

Userpools:
Integrate your own pool or other pools of choice via `.\Config\userpools.config.txt`. Each Currency/Coin/Algorithm combination needs an own entry. Every pool name will get an own config entry in pools.config.txt

Example for flexpool.io:
```
  {
    "Enable": "1",
    "Name": "Flexpool",
    "PoolFee": "0",
    "Algorithm": "",
    "CoinName": "",
    "CoinSymbol": "ETH",
    "Currency": "ETH",
    "Protocol": "stratum+tcp",
    "Host": "eu.flexpool.io",
    "Port": "4444",
    "User": "$Wallet.$WorkerName",
    "Pass": "x",
    "Region": "EU",
    "SSL": "0",
    "Worker": "$WorkerName",
    "EthMode": ""
  },
```

Mandatory parameters:
- "Name": name of the pool, every unique name will automatically get an own entry in pools.config.txt
- "CoinSymbol": coin, that will be mined
- "Currency": coin, that will be payed
- "Host": stratum server address
- "Port": stratum server port
- "User": exact syntax for user
  - `$Wallet` will be automatically replaced with your wallet (as defined in pools.config.txt)
  - `$WorkerName` will be automatically replaced with your rig's workername (or the value in pools.config.txt)

Optional:
- `"PoolFee"`: pool fee in percent (e.g. 1 for one percent), [default=0]
- `"SSL"`: set to "1" if the stratum wants SSL [default=0]
- `"Algorithm"`: if your coin is not in our database, explicitly setup the algorithm here.
- `"CoinName"`: if your coin is not in our database, explicitly setup the coin's name here.

If CoinSymbol equals Currency for the pool, only one of the two needs to be set.

**Comment by RainbowMiner** [comment]
### Config\userpools.config.txt

Integrate your own pool or other pools of choice via `.\Config\userpools.config.txt`.

Notes:
- Each Currency/Coin/Algorithm combination needs an own entry
- Every unique pool name will automatically get an config entry in pools.config.txt
- Price and profit calculations will be done via WhatToMine
- Hashrate/Workers/Blocktimes are currently not supported
- Don't forget to add your custom pool's name to `"PoolName"` in config.txt!

#### Example for flexpool.io:

add in pools.config.txt

```
  {
    "Enable": "1",
    "Name": "Flexpool",
    "PoolFee": "0",
    "Algorithm": "",
    "CoinName": "",
    "CoinSymbol": "ETH",
    "Currency": "ETH",
    "Protocol": "stratum+tcp",
    "Host": "eu.flexpool.io",
    "Port": "4444",
    "User": "$Wallet.$WorkerName",
    "Pass": "x",
    "Region": "EU",
    "SSL": "0",
    "EthMode": ""
  },
```

in config.txt, add the Flexpool to the "PoolName" list:
```
  "PoolName": "Nicehash,ZergPoolCoins,Flexpool",
```

#### Mandatory parameters:
- **Enable** = set to "1", to enable your new entry [default=0]
- **Name** = name of the pool, every unique name will automatically get an own entry in pools.config.txt
- **CoinSymbol** = coin, that will be mined
- **Currency** = coin, that will be payed, determines the wallet address. Each currency will have an entry in pools.config.txt
- **Host** = stratum server address, without `stratum+tcp://`, just my.server.name
- **Port** = stratum server port

Remark: if CoinSymbol equals Currency, only one of the two needs to be set. 

#### Optional parameters:
- **User** = exact syntax for the user parameter for the miners, variables possible, see remarks below [default=$Wallet.$WorkerName]
- **Pass** = specific pool password, variables possible, see remarks below [default=x]
- **Protocol** = setup your own protocol, if it differs from the default [default=stratum+tcp / stratum+ssl]
- **PoolFee** = pool fee in percent (e.g. 1 for one percent) [default=0]
- **SSL** = set to "1" if the stratum wants SSL [default=0]
- **Algorithm** = if your coin is not in our database, explicitly setup the algorithm here.
- **CoinName** = if your coin is not in our database, explicitly setup the coin's name here.
- **EthMode** = setup the stratum/proxy mining mode for Ethash, Kawpow, Progpow pools [default=ethproxy for Ethash, stratum for KawPow]
  - "ethproxy"
  - "ethstratumnh"
  - "qtminer"
  - "minerproxy"
  - "stratum"

Remark: the following variables will be automatically replaced in parameters **User** and **Pass**:
- `$Wallet` will be replaced with your currency's wallet (as defined in pools.config.txt)
- `$WorkerName` will be replaced with your rig's workername (or the value in pools.config.txt)
- `$CoinSymbol` will be replaced with the CoinSymbol
- `$Currency` will be replaced with the Currency

**Comment by paulpoco** [comment]
Thanks excellent work.

**Comment by rizkyaulya** [comment]
Would this work for https://unmineable.com/coins/trx as well?

**Comment by rizkyaulya** [comment]
> ### Config\userpools.config.txt
> Integrate your own pool or other pools of choice via `.\Config\userpools.config.txt`.
> 
> Notes:
> 
> * Each Currency/Coin/Algorithm/Region combination needs an own entry
> * Every unique pool name will automatically get an config entry in pools.config.txt
> * Price and profit calculations will be done via WhatToMine
> * Hashrate/Workers/Blocktimes are currently not supported
> * Don't forget to add your custom pool's name to `"PoolName"` in config.txt!
> 
> #### Example for flexpool.io:
> add in userpools.config.txt
> 
> ```
>   {
>     "Enable": "1",
>     "Name": "Flexpool",
>     "PoolFee": "0",
>     "Algorithm": "",
>     "CoinName": "",
>     "CoinSymbol": "ETH",
>     "Currency": "ETH",
>     "Protocol": "stratum+tcp",
>     "Host": "eu.flexpool.io",
>     "Port": "4444",
>     "User": "$Wallet.$WorkerName",
>     "Pass": "x",
>     "Region": "EU",
>     "SSL": "0",
>     "EthMode": ""
>   },
> ```
> 
> in config.txt, add the Flexpool to the "PoolName" list:
> 
> ```
>   "PoolName": "Nicehash,ZergPoolCoins,Flexpool",
> ```
> 
> #### Mandatory parameters:
> * **Enable** = set to "1", to enable your new entry [default=0]
> * **Name** = name of the pool, every unique name will automatically get an own entry in pools.config.txt
> * **CoinSymbol** = coin, that will be mined
> * **Currency** = coin, that will be payed, determines the wallet address. Each currency will have an entry in pools.config.txt
> * **Host** = stratum server address, without `stratum+tcp://`, just my.server.name
> * **Port** = stratum server port
> 
> Remark: if CoinSymbol equals Currency, only one of the two needs to be set.
> 
> #### Optional parameters:
> * **User** = exact syntax for the user parameter for the miners, variables possible, see remarks below [default=$Wallet.$WorkerName]
> * **Pass** = specific pool password, variables possible, see remarks below [default=x]
> * **Protocol** = setup your own protocol, if it differs from the default [default=stratum+tcp / stratum+ssl]
> * **PoolFee** = pool fee in percent (e.g. 1 for one percent) [default=0]
> * **SSL** = set to "1" if the stratum wants SSL [default=0]
> * **Algorithm** = if your coin is not in our database, explicitly setup the algorithm here.
> * **CoinName** = if your coin is not in our database, explicitly setup the coin's name here.
> * * **Region** = setup the stratum server's home region [default=US]
> * **EthMode** = setup the stratum/proxy mining mode for Ethash, Kawpow, Progpow pools [default=ethproxy for Ethash, stratum for KawPow]
>   
>   * "ethproxy"
>   * "ethstratumnh"
>   * "qtminer"
>   * "minerproxy"
>   * "stratum"
> 
> Remark: the following variables will be automatically replaced in parameters **User** and **Pass**:
> 
> * `$Wallet` will be replaced with your currency's wallet (as defined in pools.config.txt)
> * `$WorkerName` will be replaced with your rig's workername (or the value in pools.config.txt)
> * `$CoinSymbol` will be replaced with the CoinSymbol
> * `$Currency` will be replaced with the Currency

Would this work for https://unmineable.com/coins/trx as well?

**Comment by RainbowMiner** [comment]
Sure. That would work. But looking at the pool, it looks pretty interesting - let me integrate it into our default repertoire.

**Comment by RainbowMiner** [comment]
Ok, I have added that unMineable pool. We mine with 0,75% fee for all currencies.
