### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by minergenon** [RainbowMiner/RainbowMiner#1352]
After the last updates of the RM, it was noticed that several miners began to run either for cpu or for gpu (xmrig cpu 10%, cpuminer 35%, cpu-ccminer 40%). As if the new miner is launched and the old one is not killed. When you press (x) PM, red text is displayed in the console and, like, a stop, but everything in the console stops and the system continues to work.
![Screenshot_20210124_172230](https://user-images.githubusercontent.com/17958425/105629233-f92e3a00-5e6b-11eb-8624-ab0ecb77ebd8.png)

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I have a vague idea what could be the culprit. I'll make a slight code adjustment ready, for the coming release.

**Comment by RainbowMiner** [comment]
Could you please create a Debug file and upload it here?

**Comment by minergenon** [comment]
Here is some of the code.

PS>TerminatingError(Stop-Process): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (cpuminer-avx)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (cpuminer-avx)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (cpuminer-avx)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (cpuminer-avx)" value of type "System.Diagnostics.Process" to type "System.Int32"."

ForEach-Object: /home/sergey/RainbowMiner/Modules/Include.psm1:2318
Line |
2318 |  …   $ToKill | Foreach-Object {Stop-Process -id $_ -Force -ErrorAction I …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (cpuminer-avx)" value of type "System.Diagnostics.Process" to type "System.Int32".

[91mForEach-Object: [0m/home/sergey/RainbowMiner/Modules/Include.psm1:2318
[96mLine |
[96m2318 | [0m …   $ToKill | [96mForeach-Object {Stop-Process -id $_ -Force -ErrorAction I[0m …
[96m     | [91m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (cpuminer-avx)"
[96m     | [91mvalue of type "System.Diagnostics.Process" to type "System.Int32".
[0m
PS>TerminatingError(Stop-Process): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32"."

ForEach-Object: /home/sergey/RainbowMiner/Modules/Include.psm1:2318
Line |
2318 |  …   $ToKill | Foreach-Object {Stop-Process -id $_ -Force -ErrorAction I …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32".

[91mForEach-Object: [0m/home/sergey/RainbowMiner/Modules/Include.psm1:2318
[96mLine |
[96m2318 | [0m …   $ToKill | [96mForeach-Object {Stop-Process -id $_ -Force -ErrorAction I[0m …
[96m     | [91m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)"
[96m     | [91mvalue of type "System.Diagnostics.Process" to type "System.Int32".
[0m
PS>TerminatingError(Stop-Process): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32"."

ForEach-Object: /home/sergey/RainbowMiner/Modules/Include.psm1:2318
Line |
2318 |  …   $ToKill | Foreach-Object {Stop-Process -id $_ -Force -ErrorAction I …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)" value of type "System.Diagnostics.Process" to type "System.Int32".

[91mForEach-Object: [0m/home/sergey/RainbowMiner/Modules/Include.psm1:2318
[96mLine |
[96m2318 | [0m …   $ToKill | [96mForeach-Object {Stop-Process -id $_ -Force -ErrorAction I[0m …
[96m     | [91m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (SRBMiner-MULTI)"
[96m     | [91mvalue of type "System.Diagnostics.Process" to type "System.Int32".
[0m
PS>TerminatingError(Stop-Process): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (wildrig-multi)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (wildrig-multi)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (wildrig-multi)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (wildrig-multi)" value of type "System.Diagnostics.Process" to type "System.Int32"."

ForEach-Object: /home/sergey/RainbowMiner/Modules/Include.psm1:2318
Line |
2318 |  …   $ToKill | Foreach-Object {Stop-Process -id $_ -Force -ErrorAction I …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (wildrig-multi)" value of type "System.Diagnostics.Process" to type "System.Int32".

[91mForEach-Object: [0m/home/sergey/RainbowMiner/Modules/Include.psm1:2318
[96mLine |
[96m2318 | [0m …   $ToKill | [96mForeach-Object {Stop-Process -id $_ -Force -ErrorAction I[0m …
[96m     | [91m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (wildrig-multi)"
[96m     | [91mvalue of type "System.Diagnostics.Process" to type "System.Int32".
[0m
PS>TerminatingError(Stop-Process): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32"."

ForEach-Object: /home/sergey/RainbowMiner/Modules/Include.psm1:2318
Line |
2318 |  …   $ToKill | Foreach-Object {Stop-Process -id $_ -Force -ErrorAction I …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32".

[91mForEach-Object: [0m/home/sergey/RainbowMiner/Modules/Include.psm1:2318
[96mLine |
[96m2318 | [0m …   $ToKill | [96mForeach-Object {Stop-Process -id $_ -Force -ErrorAction I[0m …
[96m     | [91m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of
[96m     | [91mtype "System.Diagnostics.Process" to type "System.Int32".
[0m
PS>TerminatingError(Stop-Process): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32"."
>> TerminatingError(ForEach-Object): "Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32"."

ForEach-Object: /home/sergey/RainbowMiner/Modules/Include.psm1:2318
Line |
2318 |  …   $ToKill | Foreach-Object {Stop-Process -id $_ -Force -ErrorAction I …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of type "System.Diagnostics.Process" to type "System.Int32".

[91mForEach-Object: [0m/home/sergey/RainbowMiner/Modules/Include.psm1:2318
[96mLine |
[96m2318 | [0m …   $ToKill | [96mForeach-Object {Stop-Process -id $_ -Force -ErrorAction I[0m …
[96m     | [91m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot bind parameter 'Id'. Cannot convert the "System.Diagnostics.Process (xmrig)" value of
[96m     | [91mtype "System.Diagnostics.Process" to type "System.Int32".
[0m

**Comment by RainbowMiner** [comment]
Now, that is interesting. I'll dig down to it.

**Comment by RainbowMiner** [comment]
Two questions:
- is the OCDaemon running? Try `ocdaemon status`
- do you have "screen" installed on your Linux? If not try to install it `apt install screen`

**Comment by minergenon** [comment]
ocdaemon status - running
screen - works

**Comment by RainbowMiner** [comment]
I see - so these error messages happen, if you press [x] to exit, only?

**Comment by minergenon** [comment]
Not really. When benchmarks or mining, a new miner is launched and the old one does not end the process or loops (ie the same miner is launched "as two for example: cpu-xmrig 50%, cpu-xmrig 50%"). When you click on (x), a red text with an error is displayed in the console and everything stops there, but it continues to work in the system

**Comment by RainbowMiner** [comment]
Could you please upload a current Debug file? Just click "Debug file" on http://localhost:4000 - alternatively upload the current log files in folder `./Logs`? These look like `RainbowMiner_yyyy-mm-dd.txt` and `RainbowMiner_yyyy-mm-dd_hh-mm.txt`

**Comment by minergenon** [comment]
Ok.
[Logs.tar.gz](https://github.com/RainbowMiner/RainbowMiner/files/5867793/Logs.tar.gz)

**Comment by RainbowMiner** [comment]
Weird. It looks like, it is not using `screen` to start the miners, but the default method (and here we had a bug with stop-process!)

**Comment by RainbowMiner** [comment]
I have updated the stop-process function, so that it should now kill all miners, even if they aren't running in a `screen`

**Comment by minergenon** [comment]
Running ./start.sh in the console:
v-RM 4.6.7.7
The red text with an error has ceased to appear and everything else is the same. When you click on (x) in the same way, everything stops in the console in the system, it continues to work
[testresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/5881470/testresult.txt)
[Logs.tar.gz](https://github.com/RainbowMiner/RainbowMiner/files/5881514/Logs.tar.gz)

**Comment by RainbowMiner** [comment]
I have now reworked the whole start/stop process for Linux machines, that do run RainbowMiner within a non-root account (commit 752d6ae352fad390c560b88676effddebcefead1) . The problem relates also to issues #1396, #1389 and #1371

Please try git clone or download the current master.zip and try again. Make sure "EnableMinersAsRoot" is set to "1" in config.txt and the ocdaemon is up and running (enter `ocdaemon status`).

If you still run into trouble, please let RainbowMiner run and open http://localhost:4000 in your browser, then click "Debug file" and upload the zip file here.

Thank you for your help!
