### ISSUE TITLE
EnableServerPools Question

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1356]
This will only apply if the server actually mines correct? If you server never mines then there will be no information to make decisions on. Right?

**Comment by RainbowMiner** [comment]
No, it is enough to enable the pools and coins. The server doesn't need to mine. It's the pool and balance data that will be sent to the clients - the miners will be calculated in locally.

**Comment by Yamanipanuchi** [comment]
Answered
