### ISSUE TITLE
Infinite value on Yiimp pool

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#136]
Please account for infinite value on Yiimp pool. 

Also what does it mean that pool prices are out of sync? is there something that we need to do on our end?

![image](https://user-images.githubusercontent.com/41829368/45301045-485ab680-b4cd-11e8-9ccf-9cef796f0060.png)

**Comment by RainbowMiner** [comment]
Ok, I will fix this.
Pool prices out of sync shows up, if the pool's last price reporttimes differ by a large value. It can be ignored. Normally that means, that a pool is not responding timely.
