### ISSUE TITLE
[Question] Is there any way to force a miner to redownload?

### ISSUE THREAD

**Issue by VoltaVX** [RainbowMiner/RainbowMiner#1365]
I want to try using CCMinerMTP, which was in the "exclusions" list in the web dashboard, so I don't believe it was ultimately downloaded. Is there any way to force missing miners to download?

**Comment by RainbowMiner** [comment]
Normally, it should do that automatically, as soon as you remove the miner from the exclusions list. If it doesn't, there is a reason, why it is not used. For CcminerMTP, you need a RTX30xx GPU with Cuda 11.1+ - for all GTX10xx, RTX20xx and other GPU, with Cuda version 10.2+, the sister module CcminerMTP10 should kick in.

**Comment by VoltaVX** [comment]
As always, thank you so much for your swift response :)
