### ISSUE TITLE
Few Error's

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1367]
Getting the errors below when running on a Windows Machine.

[debug_2021-01-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/5885349/debug_2021-01-27.zip)

Finished waiting - starting next run
Test-Path: C:\RainbowMiner\Modules\Include.psm1:5491
Line |
5491 |  … _].Path;"$($_)ZZZ$(if ($Force -or -not (Test-Path $PathToFile) -or -n …
     |                                            ~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')

Test-Path: C:\RainbowMiner\Modules\Include.psm1:5491
Line |
5491 |  … _].Path;"$($_)ZZZ$(if ($Force -or -not (Test-Path $PathToFile) -or -n …
     |                                            ~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')

Test-Path: C:\RainbowMiner\Modules\Include.psm1:5491
Line |
5491 |  … _].Path;"$($_)ZZZ$(if ($Force -or -not (Test-Path $PathToFile) -or -n …
     |                                            ~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')

Test-Path: C:\RainbowMiner\Modules\Include.psm1:5491
Line |
5491 |  … _].Path;"$($_)ZZZ$(if ($Force -or -not (Test-Path $PathToFile) -or -n …
     |                                            ~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')

Test-Path: C:\RainbowMiner\Modules\Include.psm1:5491
Line |
5491 |  … _].Path;"$($_)ZZZ$(if ($Force -or -not (Test-Path $PathToFile) -or -n …
     |                                            ~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')

Set-ContentJson: C:\RainbowMiner\Modules\Include.psm1:5520
Line |
5520 |                  Set-ContentJson -PathToFile $PathToFile -Data $Data > …
     |                                              ~~~~~~~~~~~
     | Cannot bind argument to parameter 'PathToFile' because it is an empty string.

Set-ContentJson: C:\RainbowMiner\Modules\Include.psm1:5520
Line |
5520 |                  Set-ContentJson -PathToFile $PathToFile -Data $Data > …
     |                                              ~~~~~~~~~~~
     | Cannot bind argument to parameter 'PathToFile' because it is an empty string.

Set-ContentJson: C:\RainbowMiner\Modules\Include.psm1:5520
Line |
5520 |                  Set-ContentJson -PathToFile $PathToFile -Data $Data > …
     |                                              ~~~~~~~~~~~
     | Cannot bind argument to parameter 'PathToFile' because it is an empty string.

Set-ContentJson: C:\RainbowMiner\Modules\Include.psm1:5520
Line |
5520 |                  Set-ContentJson -PathToFile $PathToFile -Data $Data > …
     |                                              ~~~~~~~~~~~
     | Cannot bind argument to parameter 'PathToFile' because it is an empty string.

WARNING: You are running RainbowMiner prerelease v4.6.7.8. Use at your own risk.

**Comment by Yamanipanuchi** [comment]
Sorry, Forgot to include that I've seen it on multiple Machines.

**Comment by RainbowMiner** [comment]
Oh! I'll check that.

**Comment by RainbowMiner** [comment]
Since when is this happening?

**Comment by Yamanipanuchi** [comment]
Started after one of the most recent updates. I believe .6 because I it was trying to upgrade some of the machines to .8 and wouldn't. I had to stop the script and use the update script.

**Comment by RainbowMiner** [comment]
Yes, that's what I have expected. It's since .6 - I imported a bug when implementing the userpools. It is solved with the new .9
