### ISSUE TITLE
What does this means? [Failed to listen on prefix 'http://+:4000/']

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1369]
> MethodInvocationException: D:\Miner Selection\RainbowMiner\Modules\API.psm1:37
Line |
  37 |      $Global:APIHttpListener.Start()
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Start" with "0" argument(s): "Failed to listen on prefix 'http://+:4000/' because it conflicts with an existing registration on the machine."

I know port 4000 is for live monitoring. The dashboard works fine while monitoring central shows my rig as offline.
Nothing was changed, not even router side.

**Comment by RainbowMiner** [comment]
Is it possible, that there is/was another RainbowMiner instance running on that machine?
If it doen't go away, I would reboot the machine, because in that case, most probably there is a crashed Microsoft Http Listener.

**Comment by astronyu** [comment]
> Is it possible, that there is/was another RainbowMiner instance running on that machine?
> If it doen't go away, I would reboot the machine, because in that case, most probably there is a crashed Microsoft Http Listener.

There was no other instances running and tried rebooting the machine few times but the error persists.
[debug_2021-01-29_2.zip](https://github.com/RainbowMiner/RainbowMiner/files/5894553/debug_2021-01-29_2.zip)
