### ISSUE TITLE
Issue: Late night crashs

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#137]
Rack1 Crash

[errors_2018-09-09.main.txt](https://github.com/RainbowMiner/RainbowMiner/files/2367044/errors_2018-09-09.main.txt)
[RainbowMiner_2018-09-09.txt](https://github.com/RainbowMiner/RainbowMiner/files/2367045/RainbowMiner_2018-09-09.txt)
[errors_2018-09-09.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2367048/errors_2018-09-09.asyncloader.txt)
[errors_2018-09-10.main.txt](https://github.com/RainbowMiner/RainbowMiner/files/2367050/errors_2018-09-10.main.txt)

**Comment by RainbowMiner** [comment]
What is the error symptom?

**Comment by Byrd1083** [comment]
Rig2 crash

Looks like it died during benchmark. 

[RainbowMiner_2018-09-10.txt](https://github.com/RainbowMiner/RainbowMiner/files/2367300/RainbowMiner_2018-09-10.txt)
[errors_2018-09-10.main.txt](https://github.com/RainbowMiner/RainbowMiner/files/2367301/errors_2018-09-10.main.txt)
[errors_2018-09-10.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2367302/errors_2018-09-10.asyncloader.txt)

**Comment by RainbowMiner** [comment]
Oh dear! Yes, it looks like some benchmark issue with a miner.
Please update to the newest release, since I have build-in a lot of new security measures that could avoid such crashes.

**Comment by Byrd1083** [comment]
I think I am having an issue with nvidia drivers crashing and restarting. To aggressive of a clock. I will tune back and retest.

Windows log is full of:
Display driver nvlddmkm stopped responding and has successfully recovered.

**Comment by RainbowMiner** [comment]
> Display driver nvlddmkm stopped responding and has successfully recovered.

Oh yes. Looks pretty much like that.

**Comment by RainbowMiner** [comment]
> Pool prices are not adding up with latest update.

Are you refering to the "Balance" column, *Total* being emtpy? If yes, that's because there are different currencies in this column. Only the BTC/USD columns add up.

**Comment by RainbowMiner** [comment]
Ok, I added a new parameter in the upcomeing release: ShowPoolBalancesDetails - set this to "0" and you will get back a consolidated view of the balances. Added up as BTC.
