### ISSUE TITLE
 WARNING: No miners available: disabled by Watchdog

### ISSUE THREAD

**Issue by minergenon** [RainbowMiner/RainbowMiner#1371]
What is it
![Screenshot_20210130_203927](https://user-images.githubusercontent.com/17958425/106359356-8249e300-633c-11eb-96b4-db2c9d0c489a.png)
[Logs.tar.gz](https://github.com/RainbowMiner/RainbowMiner/files/5898133/Logs.tar.gz)

**Comment by RainbowMiner** [comment]
All the miners are crashing - that's why the watchdog has disabled them.
Now we need to figure out, why this is happening. Could you please run `./gputest.sh` and upload the gputestresult.txt? Something seems very much off, with the OpenCL values.

**Comment by minergenon** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/5903999/gputestresult.txt)
[lscpu.txt](https://github.com/RainbowMiner/RainbowMiner/files/5904023/lscpu.txt)

**Comment by minergenon** [comment]
What needs to be done to make it work normally through ./start.sh

**Comment by ParfectShot** [comment]
These are my GPU test results, getting the same error :/ -

GPU-TEST 02/11/2021 18:48:11
================================================================================
 
 
1. nvidia-smi
--------------------------------------------------------------------------------
 
GeForce RTX 2060 with Max-Q Design, 99 %, 18 %, 72, 64.15 W, [N/A], [N/A], P0, 1470 MHz, 5500 MHz, [N/A], [N/A]
 
2. OpenCL
--------------------------------------------------------------------------------
 

Profile    : FULL_PROFILE
Version    : OpenCL 1.2 CUDA 11.2.109
Name       : NVIDIA CUDA
Vendor     : NVIDIA Corporation
Extensions : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, cl_khr_local_int32_extended_atomics…}



AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel
Extensions                 : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, cl_khr_local_int32_extended_atomics…}
GlobalMemCacheSize         : 983040
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 128
GlobalMemSize              : 6222839808
ImageSupport               : True
LocalMemSize               : 49152
LocalMemType               : Local
MaxClockFrequency          : 1185
MaxComputeUnits            : 30
MaxConstantArgs            : 9
MaxConstantBufferSize      : 
MaxMemAllocSize            : 1555709952
MaxParameterSize           : 4352
MaxReadImageArgs           : 256
MaxSamplers                : 32
MaxWorkGroupSize           : 1024
MaxWorkItemDimensions      : 3
MaxWorkItemSizes           : {1024, 1024, 64}
MaxWriteImageArgs          : 32
MemBaseAddrAlign           : 4096
MinDataTypeAlignSize       : 128
DeviceCapability           : 7.5
Architecture               : GeForce RTX 2060 with Max-Q Design
Name                       : GeForce RTX 2060 with Max-Q Design
ClVersion                  : OpenCL C 1.2 
Platform                   : OpenCl.Platform
PreferredVectorWidthChar   : 1
PreferredVectorWidthShort  : 1
PreferredVectorWidthInt    : 1
PreferredVectorWidthLong   : 1
PreferredVectorWidthFloat  : 1
PreferredVectorWidthDouble : 1
Profile                    : FULL_PROFILE
QueueProperties            : OutOfOrderExecModeEnable, ProfilingEnable
SingleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt
Type                       : Gpu
Vendor                     : NVIDIA Corporation
VendorId                   : 4318
Version                    : OpenCL 1.2 CUDA
DriverVersion              : 460.32.03
PCIBusId                   : 01:00


................................................................................

**Comment by RainbowMiner** [comment]
Could you please create a Debug file and upload it here? Just open http://localhost:4000 in your browser and then click "Debug file".

**Comment by RainbowMiner** [comment]
I have now reworked the whole start/stop process for Linux machines, that do run RainbowMiner within a non-root account (commit 752d6ae352fad390c560b88676effddebcefead1) . The problem relates also to issues #1396, #1389 and #1371

Please try git clone or download the current master.zip and try again. Make sure "EnableMinersAsRoot" is set to "1" in config.txt and the ocdaemon is up and running (enter `ocdaemon status`).

If you still run into trouble, please let RainbowMiner run and open http://localhost:4000 in your browser, then click "Debug file" and upload the zip file here.

Thank you for your help!

**Comment by RainbowMiner** [comment]
This should be solved, by now.
