### ISSUE TITLE
RBM altering memory speed when OC in config set to 0, RBM setting memory to standard rate and overriding GPU Tweak settings.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1372]
RBM altering memory speed when OC in config set to 0, RBM setting memory to standard rate and overriding GPU Tweak settings.

Here is the memory speed set for 2 x 1070 running Heaven benchmark, memory clock 8468.
![Screenshot_8](https://user-images.githubusercontent.com/801414/106378526-82f17200-635a-11eb-86cb-ec0fed36347e.png)

And here is RBM going back to 8064.
![Screenshot_9](https://user-images.githubusercontent.com/801414/106378539-97356f00-635a-11eb-83a5-8e7cddb67137.png)
[debug_2021-01-31 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/5899374/debug_2021-01-31.1.zip)

**Comment by RainbowMiner** [comment]
Oh. It shouldn't do that. I'll check. Is it happening at miner shut-down, or at miner-start?

**Comment by RainbowMiner** [comment]
Ok, found it. I have fixed that problem. Actually, the OC setting has been reset, after the miner shutdown. Thus leaving it in that condition for the next miner(s).

**Comment by paulpoco** [comment]
Can I just download the latest Master and copy Overton or do you need to do more before next release?

**Comment by paulpoco** [comment]
@RainbowMiner ok @smash had me try the OCprofiles5 and OCVoltage lock setting.

Found a bug where RBM does not release the "CoreClockBoost" after you quit RBM.

Found another bug where RBM does not release the "LockVoltagePoint" after you quit RBM.
