### ISSUE TITLE
Warning: No miners available: check your configuration / Montoring Central Problem

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1374]
[debug_2021-01-31.zip](https://github.com/RainbowMiner/RainbowMiner/files/5900729/debug_2021-01-31.zip)
This happens to some of my machines from time to time.  And when this happens Monitoring Central still shows the computer in green.  There are other times Monitoring Central shows green when the computer is not mining but that does happen when this problem happens.

**Comment by RainbowMiner** [comment]
Ok, I'll add a red flag, in case.

**Comment by jch9678** [comment]
Is it possible to know why there were no miners available at that time?

**Comment by RainbowMiner** [comment]
Yes - in 99% of the cases it's the Watchdog that holds miners and/or pools back. It can be a pool API failure, an issue with the local network.

**Comment by jch9678** [comment]
Would you mind taking a look at that debug file to see what happened please?  Or I can if you can give me a hint of where to look.

**Comment by RainbowMiner** [comment]
I have checked it. It's simply the donation round. I had added checks for miner exclusion / pool exclusion to avoid overloading systems (have it use it's allowed miners, only) during the donation round. So it's pretty harmless for you - bad for me. I am currently adding extra wallets for PHI5 and ETC, so that it doesn't sit there, doing nothing during the round.

**Comment by jch9678** [comment]
Oh I see.  Do you ever use a multipool like nlpool for wallets, might be easier for something like phi5.  Looks like combode came back down so my machines went back to etc.  
This machine with this new debug lost connection to Monitoring Central but is still mining....would you  mind checking please.
[debug_2021-02-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/5905101/debug_2021-02-01.zip)

**Comment by RainbowMiner** [comment]
I have just added Ethermine on ETC to the donation pools.

I'll check the second machine's debug file.
