### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1375]
![Untitled2](https://user-images.githubusercontent.com/4724631/106635960-48dcc780-6536-11eb-9594-1e669f336def.png)

Is it possible to toggle the display of the m on BTC?
Also, Is it possible to change the currency displayed for Average Earned? Maybe to Satoshi's? Or anything?

Just question, Not a request.

**Comment by RainbowMiner** [comment]
Regarding the milli, it's an automatic scaling, currently. Regarding the average earned currency - I'll see into it. Most probably it shouldn't be a problem to change it.

**Comment by Yamanipanuchi** [comment]
Answered.
