### ISSUE TITLE
Add VerthashMiner

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1376]
Could you please add VerthashMiner
https://github.com/CryptoGraphics/VerthashMiner/releases
Vertcoin seems to be pretty profitable right now especially for my old gpu's

**Comment by jch9678** [comment]
https://github.com/CryptoGraphics/VerthashMiner
Might be a little tougher to implement

```
Note: Verthash algorithm requires a special file verthash.dat, which can be obtained from external sources or generated by the miner using the following command(available in v0.6.2 or later):
./VerthashMiner --gen-verthash-data verthash.dat
```
It's taking a while to download this file and it's already at 1.2gb

**Comment by RainbowMiner** [comment]
Yes, I know :) I have a beta version running. It will be part of the next release.

**Comment by jch9678** [comment]
cool.  That's great.

**Comment by paulpoco** [comment]
@RainbowMiner I am not mining verthash but I keep seeing a message downloading verthash.dat every now and then.  On the Server machine window.

On one of the clients I am getting something about verthash error on the main window pointing some line of code.
