### ISSUE TITLE
Can't find claymore anywhere

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#1377]
Hi!

I'm looking for Calymore miner but can't find it. It's not on Miners, Active, or Benchmarks. It's not disabled and it's already downloaded.
I have a VEGA56.
[debug_2021-02-03.zip](https://github.com/RainbowMiner/RainbowMiner/files/5915962/debug_2021-02-03.zip)

Regards

**Comment by paulpoco** [comment]
Thought it was abandoned

**Comment by RainbowMiner** [comment]
Hi, yes, I have retired Claymore, because the developer has abandoned the project and it cannot handle the current Ethash DAG epoch anymore. Plus, we have multiple stable and fast alternatives (Phoenix, Trex, Gminer and more).

**Comment by Djago** [comment]
As always, a big THANKS!
So, it is OK to delete:
![image](https://user-images.githubusercontent.com/34612740/106794211-444c0800-6637-11eb-8875-c002b34a7ad4.png)
?

**Comment by RainbowMiner** [comment]
Sure. Delete it.
