### ISSUE TITLE
Coin Value stats

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1378]
Any chance other sources of coin values? I only throw it out there because I found What To Mine to be fairly inaccurate on a few of my coins.

Maybe CoinGecko?

**Comment by RainbowMiner** [comment]
Which coins turn out to be inaccurate? 
I'll have a look into CoinGecko. If it has an API, I can build a proxy around it.

**Comment by Yamanipanuchi** [comment]
Ya, I checked. CoinGecko does have an API. How good it is I dont know. TRTL was fairly screwed, And upon looking on WhatToMine I notice it only uses Trade Ogre for its numbers. Which made me think about other coins that might end up in the same boat. It would be best to have more point of data to get a better average. I checked a few others and most of them were fairly accurate.

CoinGecko was just a suggestion because that is where I ended up looking for more information on pricing. I think there are other's.

**Comment by RainbowMiner** [comment]
We are currently using Coinbase + Coinpaprika for our coins. Maybe I can push these values into the WhatToMine coin calculators. I'll look into it.

**Comment by Yamanipanuchi** [comment]
I checked Coinpaprika, The price there looks to match the exchange. What my RBM system shows in rates does not match. For TRTL I had to add a -11 for penalty and then it was close. I havent dug into any other coins. The root of my inquiry was that maybe more sources might give a more rounded number?

**Comment by RainbowMiner** [comment]
> more sources might give a more rounded number

Excactly. The WhatToMine calculators are pretty convenient, so that I'll now try to inject our coin rates.

**Comment by RainbowMiner** [comment]
I forgot the essential question: on which pool did you mine TRTL? It may be, that the pool has supplied us with wrong numbers.

**Comment by Yamanipanuchi** [comment]
HeroMiners.

**Comment by RainbowMiner** [comment]
Ok, thanks.

**Comment by cleanerspam** [comment]
Please add more sources for checking a coin profitability and add an option to select which source or gtoup of sources (median) you want to use .
