### ISSUE TITLE
"All miners crashed Immediately"

### ISSUE THREAD

**Issue by TuRDMaN** [RainbowMiner/RainbowMiner#1379]
So I first installed RainbowMiner on a linux rig and it was working great.

Then I installed it on a Windows 10 machine, and I can't get it to run any miners at all.

Running Start.bat as admin, it opens a powershell window, then begins operating as it should... but whenever it tries to launch a miner, it just flashes "All miners crashed immediately" and then loops.

At the bottom of the status screen, it shows:
`OperationStopped: Incorrect function.
OperationStopped: Incorrect function.
Finished waiting - starting next run`

If I try running the displayed Command (in the Command column on the status screen), the miners will launch and run just fine. But for some reason, when they are called by RainbowMiner, they just crash. I am at a loss!

**Comment by RainbowMiner** [comment]
Hi, I will try to help you out - it should run perfect on Windows 10. Could you please either create a Debug file or zip the Logs folder and upload it here?

**Comment by TuRDMaN** [comment]
Thanks for the assistance! Not sure how to create a debug file, but I wiped all my logs, then let it run for a few minutes, then zipped the Logs folder and attached it here.
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/5919562/Logs.zip)

**Comment by RainbowMiner** [comment]
Ok, it seems to be a problem with Powershell Core v7.1.0 and some kind of file system. The Microsoft devs claim, it has been fixed with [Powershell Core v7.1.1](https://github.com/PowerShell/PowerShell/releases/download/v7.1.1/PowerShell-7.1.1-win-x64.msi) - please update the powershell and try again. [Download the installer](https://github.com/PowerShell/PowerShell/releases/download/v7.1.1/PowerShell-7.1.1-win-x64.msi)

**Comment by TuRDMaN** [comment]
That did the trick! All working now.

For clarity, I am running RainbowMiner from a pooled drive created with DriveBender. I guess Powershell 7.1.0 had a problem with it. All is well with Powershell 7.1.1

Thanks again!

**Comment by RainbowMiner** [comment]
Nice :) 
I am happy, it could be resolved. Yes, the pooled drive will be most probably formatted with FAT32 or exFAT. And this is what clashes with Powershell 7.1.0.
