### ISSUE TITLE
problem with XVG blockmasters

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#138]
WARNING: Pool Balance API (BlockMasters) for XVG returned nothing.
Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
At C:\Users\JP\Desktop\RainbowMiner-3.8.6.9\RainbowMiner-3.8.6.9\Include.psm1:115 char:5
+     $Balances += $Totals
+     ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
+ FullyQualifiedErrorId : MethodNotFound

WARNING: No pools available.

**Comment by RainbowMiner** [comment]
It looks like blockmasters is down. I check.

**Comment by RainbowMiner** [comment]
Is it your only pool? If not, could you please send me your config.txt and your current Logs as zip?

**Comment by RainbowMiner** [comment]
I included an extra check into v3.8.6.10, so that there will no error show up, when no pool's balance is available.

**Comment by rinkal26783** [comment]
Now i have also added zergpool. but its only showing zergpool. no sign of blockmasters
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2367629/config.txt)

**Comment by RainbowMiner** [comment]
For the time being: download this file, and copy the BlockMasters.ps1 inside into your Pools directory

[BlockMasters.zip](https://github.com/RainbowMiner/RainbowMiner/files/2367718/BlockMasters.zip)

**Comment by rinkal26783** [comment]
Blockmasters is paying XVG very frequently. I get payment every 5 hours even if it is 1 XVG.

**Comment by RainbowMiner** [comment]
> Another option could be: I could generally remove the currencies API check from any auto exchange pool and blindly accept any wallet that is configured in pools.config.txt.

I will integrate this solution. Then there will be no more waiting for a currencies API, anymore.

**Comment by RainbowMiner** [comment]
Done. Will be published with the next release :)

**Comment by rinkal26783** [comment]
Please add xvg support for zpool,zergpoolcoins and blockmasterscoins as well
