### ISSUE TITLE
Does GTX 1660 Super need the profile inspector P0 done?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1381]
I setup a new PC with a 1660 Super and I notice after the miner quits or changes then the clock frequency goes up temporarily before it goes down. 

I'd upload a debug file but the debug download doesn't strip out the passwords in config.json.  I didn't check any other files for not stripping out private info.

**Comment by RainbowMiner** [comment]
Yes, the 1660 Super need that "Force P2 State" set to "Off", too.

**Comment by paulpoco** [comment]
Ok will do that later and lower my core/mem clock beforehand. 

Thanks.

**Comment by paulpoco** [comment]
Questions if set to P0 mode how would that affect playing games while RBM is paused?

**Comment by rizkyaulya** [comment]
@RainbowMiner New miner for Autolykosv2 
https://www.ergoforum.org/t/nvminer-1-1-0-with-improved-hashrate-by-mhs-sam/614/2
Please add up, So our GTX 1660 can join the vibe.. :))
