### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by david0815** [RainbowMiner/RainbowMiner#1382]
Power calculation is wrong on "Pool Calculated Totals"-Page. testet it : 300min * 480W = 2,4 kWh but it shows 0.077 kwh.
The cost seems legit.
please check

**Comment by RainbowMiner** [comment]
Oh. Thank you for bringing this up. I'll have a look.

**Comment by RainbowMiner** [comment]
Found the problem. The miner's power is cumulated with as kWd (day). It needs to be multiplicated by 24 to get to kWh (hour).
It's fixed. 
Release will be out soon.
