### ISSUE TITLE
Debug file does block out some passwords and addresses like it does for 90%?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1383]
I think this issue was only in config.json.

Here is some screenshots.
![Screenshot_20210204-165341_Solid Explorer](https://user-images.githubusercontent.com/801414/106975682-cd347380-670b-11eb-9667-ac8cd8cc02ca.jpg)
![Screenshot_20210204-165716_Solid Explorer](https://user-images.githubusercontent.com/801414/106975690-d1609100-670b-11eb-8685-964a74c13f56.jpg)
![Screenshot_20210204-165742_Solid Explorer](https://user-images.githubusercontent.com/801414/106975695-d45b8180-670b-11eb-99a3-38256970b78f.jpg)

**Comment by RainbowMiner** [comment]
Ok, I'll check the parser. Thank you for bringing this up!
