### ISSUE TITLE
BitSend (BSD) Bad Price

### ISSUE THREAD

**Issue by shocker1185** [RainbowMiner/RainbowMiner#1384]
RB Miner sees 1 BSD as 1 USD...wildly incorrect. 
Thanks!

**Comment by RainbowMiner** [comment]
Wow! Yes, that's off. I will check the coins API

**Comment by RainbowMiner** [comment]
That's crazy: it is the Coinbase API that reports a value of 37609sat for 1BSD - our own API reports around 10sat for 1BSD.
I don't know, why the Coinbase value is so far off, but I will investigate.

**Comment by RainbowMiner** [comment]
Even more different. The Coinbase's BSD is the Bahamian Dollar. I will implement a filter, so that all world currencies will be handled separately.

**Comment by RainbowMiner** [comment]
Ok, I have reworked the coin rates functions, so that world currency vs. coin symbol clashes shouldn't happen any more.
