### ISSUE TITLE
Client/Server Question - Can server actively mine as well?

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1386]
I just wanted to clarify something about client/server network config.

I have a stand-alone PC (PC1) currently running RM and mining.
I have a 2nd PC (PC2) that I'd also like to have mine for me overnight when not in use.

So on PC1, can I simply run the InitServer.bat,
and then on PC2 run InitClient.bat

Then I can run PC1 as my main miner, but also acting as a server when I fire up PC2 in the evenings?

That is, PC1 is Server _and_ actively mining?

**Comment by RainbowMiner** [comment]
Yes. The server can mine along, as well.
