### ISSUE TITLE
MiningPoolHub VTC pool : wrong port number - TEMP FIX included

### ISSUE THREAD

**Issue by 5ymph0en1x** [RainbowMiner/RainbowMiner#1387]
Hi there !

Congrats for this very nice piece of software ! Your 40min/day are well-earned...

I think I have found an issue relating to a wrong port number being assigned to MPH VTC pool adress.

I had to modify the line 89 of MiningPoolHubCoins.ps1 to this in order for RBM to work properly:

`Host          = $Pool_Hosts | Select-Object -First 1 #Sort-Object -Descending {$_ -ilike "$Pool_Region*"} |`

Hope this will help others...

Best regards

**Comment by RainbowMiner** [comment]
Thank you very much! I'll check the MPH ports.

**Comment by RainbowMiner** [comment]
Ok, solved. Thanks again for bringing this up.
