### ISSUE TITLE
RainbowMiner is between x% and x% more profitable

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#139]
Question, what does this indicate? isn't Rainbowminer a profit switch manager as oppose to an actual miner. Or is there an actual miner that it is more profitable than T-rex and/or EnemyZealot?

![image](https://user-images.githubusercontent.com/41829368/45310168-d0978680-b4e2-11e8-921a-6e31f56cabe4.png)

**Comment by RainbowMiner** [comment]
This compares the past profitability against the actual best miners. If rainbowminer has been better, this line shows up.
