### ISSUE TITLE
Verthash doesn't show up in Profitability List

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1390]
To test this, I set RM to only mine Verthash, it works (the miner is hidden because of no API) but it doesn't show up in the profitability list.  I think this also prevents it from switching to it.

**Comment by jch9678** [comment]
[debug_2021-02-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/5945740/debug_2021-02-08.zip)

**Comment by acos0874** [comment]
Have you tested using f2pool? They should have their own API for vertcoin.

**Comment by jch9678** [comment]
Thanks @acos0874.  I'm not sure I understand.  Most miners have a built in API so stats can be reported to 3rd party apps.  Verthash doesn't have one yet so RM has to act as a wrapper to capture the stats.  When it does that, the Show Miner Window setting is ignored.  Also I unfortunately can't use f2pool for vertcoin, the hashrate is too low and I'm using MiningPoolHub's auto exchange feature.

**Comment by jch9678** [comment]
@RainbowMiner just wondering if you've had a chance to look at this.  RM doesn't switch to Verthash

**Comment by jch9678** [comment]
The new update seems to have fixed Verthash showing in the profitability list but only for zergpool and zergpoolcoins not MiningPoolHub.  If I exclude Verthash from zergpoolcoins, RM still won't mine Verthash at MiningPoolHub. After looking at my Best Pools on the Dashboard, it looks like the BTC/GH/Day is off for this algo at this pool.
[debug_2021-02-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/5973095/debug_2021-02-12.zip)
