### ISSUE TITLE
Odd behavior, I think?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1391]
This is what I got on one of my machines.

![image](https://user-images.githubusercontent.com/4724631/107318892-9be0de00-6a52-11eb-83e1-cf24ce10e2a3.png)

This system only has one 1650 Super in it....

Ill post a debug tomorrow when I am at the machine.

**Comment by Yamanipanuchi** [comment]
[debug_2021-02-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/5949188/debug_2021-02-08.zip)

**Comment by RainbowMiner** [comment]
This IS weird.  Thank you for pointing to this. It seems some rare condition killed the miner-stop command. I will check asap and post a fix.

**Comment by RainbowMiner** [comment]
The commit  b829e54 doesn't solve this issue completely, since the underlying error is still there, but it will now stop the miners. I will continue to find out, what causes the trouble.

**Comment by RainbowMiner** [comment]
One request: could you please open `http://localhost:4000/runningminers` for that machine and post the resulting JSON here?

**Comment by jch9678** [comment]
Off topic, but @Yamanipanuchi how did you change the colors of Monitoring Central?

**Comment by Yamanipanuchi** [comment]
@RainbowMiner When I am back at the system I will get the requested info.

@jch9678 Down in the lower left hand corner there is a darkmode.

**Comment by jch9678** [comment]
ah, I see that now on the local dashboard, was thinking it was on Monitoring Central.  Thanks.
