### ISSUE TITLE
[BUG] Invalid argument 'NotePropertyName' in Core.psm1

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1392]
![image](https://user-images.githubusercontent.com/22162766/107433898-e8471f00-6b21-11eb-899c-a04a1a528732.png)

Only just caught this. Haven't run RBM for about 4-5 versions so it's happened in that time.
Tried a fresh install with the Config and Stats moved back into the app folder.

Probably something to do with a config change, but not sure what it is?

**Comment by RainbowMiner** [comment]
Strange! That should not happen. Does the program run normally, after that warning? Did you try a restart of RainbowMiner?

**Comment by talentoscope** [comment]
Yeah, works perfectly fine.
Still there on restart and during each round

**Comment by mrunyon** [comment]
Also experiencing this on v4.6.8.5, message appears after each update (initial start and also after each round).

**Comment by RainbowMiner** [comment]
Could you please upload a Debug file? Just click "Debug file" at http://localhost:4000

**Comment by RainbowMiner** [comment]
Another question: which pools do you happen to have activated, currently?

**Comment by talentoscope** [comment]
2miners,572133club,666pool,6block,acepool,ahashpool,aionmine,baikalmine,beepool,binance,blazepool,blockmasterscoins,bsod,btcprivate,cortexmint,cpupool,ethashpool,ethermine,f2pool,fairpool,flypool,goscx,grinmint,hashcity,hashcryptos,hashpool,hashvault,hellominer,herominers,hiveon,icemining,leafpool,luckpool,luckypool,luxor,minerrocks,minexmr,miningdutchcoins,MiningPoolHub,miningpoolhubcoins,miningpoolovh,mintpond,moneroocean,nanopool,nicehash,nlpool,poolin,poolium,poolminexyz,poolsexy,ravenminer,ravepool,rplant,sparkpool,sunpool,supportxmr,tecracoin,uupool,woolypooly,zellabs,zergpoolcoins,zpoolcoins

That's from my config lol
Sorry, I know it doesn't help narrow it down

**Comment by RainbowMiner** [comment]
Oh. In that case, could you eventually open http://localhost:4000 in the browser and click "Debug file"? It's important for me to know all the coin symbols, that you have setup.

**Comment by RainbowMiner** [comment]
There is a good chance, that I have fixed that error message with my last couple commits. Especially the new coinsdb.json should do wonders

**Comment by talentoscope** [comment]
Awesome!
Look forward to the next official release 🙂

Thanks again as always bud
