### ISSUE TITLE
[POOL] Rplant CBE stats incorrect

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1393]
As above

![image](https://user-images.githubusercontent.com/22162766/107439266-b0dc7080-6b29-11eb-8799-74afe9cf8f7e.png)

Now, how do I cash that in? lol

**Comment by RainbowMiner** [comment]
Oh wow! We are rich!
I check the pool API.

**Comment by talentoscope** [comment]
Thanks mate :)
I've got my debit card on standby haha

**Comment by RainbowMiner** [comment]
Could you please also tell me, which pools you happen to have activated, currently? It's regarding that strange Noteproperty Error in issue #1392 )

**Comment by talentoscope** [comment]
Replied in other issue.

Re CBE, it looks like it's all pools that support it, so not sure what's going on there.

**Comment by RainbowMiner** [comment]
Sure, it's a problem with the CBE price on Coingecko. I have now restricted all coins to a minimum 24h trading volume. All coins below that limit will get 0 value.
