### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by minergenon** [RainbowMiner/RainbowMiner#1396]
Thank you for trying - look into your Config/config.txt. Is "EnableMinersAsRoot" set to "1" ?

_Originally posted by @RainbowMiner in https://github.com/RainbowMiner/RainbowMiner/issues/1389#issuecomment-776060915_

After changing Config / config.txt. Is "EnableMinersAsRoot" set to "1" from 1 to 0 Benchmark started, but after a while RM got an error /home/sergey/RainbowMiner/start.sh: line 23: 2381 Killed pwsh -ExecutionPolicy bypass -Command $ {command} and stopped in the shell window and miners continued to work in the system

[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/5965405/Logs.zip)

**Comment by RainbowMiner** [comment]
Is it possible, that bash is not installed on your system? Could check, please?

**Comment by RainbowMiner** [comment]
Ok, I think I have got a lead. Your Linux user is not root, right?

**Comment by RainbowMiner** [comment]
I have now reworked the whole start/stop process for Linux machines, that do run RainbowMiner within a non-root account (commit 752d6ae352fad390c560b88676effddebcefead1) . The problem relates also to issues #1396, #1389 and #1371

Please try git clone or download the current master.zip and try again. Make sure "EnableMinersAsRoot" is set to "1" in config.txt and the ocdaemon is up and running (enter `ocdaemon status`).

If you still run into trouble, please let RainbowMiner run and open http://localhost:4000 in your browser, then click "Debug file" and upload the zip file here.

Thank you for your help!
