### ISSUE TITLE
Issue with RBM stuck in a crashing loop with Nicehack Ethash today

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1397]
Today RBM was stuck in a devfee/Ethash/Nicehack loop. I have Sparkpool enabled, but RBM wouldn't switch over to it. I had to resort to manually disabling Nicehack to get my rig mining again. Fortunately, I was at my PC when this happened. Can you look into this?

**Comment by RainbowMiner** [comment]
Of course! What had happend? Could you please create a Debug file and upload it here?

**Comment by samdave123** [comment]
My MRR rental ended, and then my rig started mining on Nicehack and was having issues, and then the devfee was having issues and RBM said no pools available and idled. Nicehack is doing some maintenance currently but I'm not sure if it's related.
[debug_2021-02-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/5967163/debug_2021-02-11.zip)

**Comment by RainbowMiner** [comment]
Ah, ok. I'll have a look.

**Comment by RainbowMiner** [comment]
Surely a nicehash problem, today. The crashes happend during the donation round. There is one thing: if you restart RainbowMiner during the donation round, it will try to finish it, after the restart. That is what might have felt like a loop.

**Comment by jch9678** [comment]
Happened to me too
