### ISSUE TITLE
"Mining for Dev" now happening constantly all of a sudden.

### ISSUE THREAD

**Issue by VoltaVX** [RainbowMiner/RainbowMiner#1398]
When I first started mining, I barely got any "Mining for Dev" in my activity monitor. But all of a sudden, may around last week, "Mining for Dev" is starting to appear and continue for well over 30 minutes. While I don't mind helping out the people who developed these miners, my GPU/CPU doesn't earn that much, to begin with. I only mine during online classes, so constant 30 minutes of dev mining every hour or 2 throughout my mining schedule really cuts down on the small number of profits I could even make. Is this a result of some miner update by any chance?

**Comment by RainbowMiner** [comment]
Thanks for reporting this. The dev mining should happen once every 24h. Could you please zip your Logs folder and upload it here? I will have a look.

**Comment by VoltaVX** [comment]
Hi, so for my schedule, I often start mining from 7:30 to around 5 when I finish all my homework. I follow this schedule on weekdays, but on weekends sometimes I just mine for 3-4 hours depending on whether I wake up late or have too much homework. 

Here's the link to my logs: https://drive.google.com/file/d/1YN6c7WS907JHHXpd3lBIc95_AWUuSjEf/view?usp=sharing

**Comment by RainbowMiner** [comment]
The past 2 days, it's just 12 minutes per your mining day. I'll check the activity monitor.

**Comment by RainbowMiner** [comment]
Should be better now.
