### ISSUE TITLE
Constant crashing since update or something 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#1399]
Not sure. I’m out of town with auto updates. All of my Linux rigs are crashing 60-80times per hour. I’ve went from making $50 a day to 5 from a Windows rig. Would appreciate some help. 

Issue start roughly 2-3 days ago. Maybe 4

**Comment by RainbowMiner** [comment]
Pretty hard to say, what is happening. Do you have remote access? I'll contact you via Discord.

**Comment by RainbowMiner** [comment]
The new v4.6.8.7 release seem to have cured your boxes. They are up and running. Please upload a Debug file of one of those machines, anyway. I still need to find out, what has happened exactly.
