### ISSUE TITLE
Allow Benchmark Below 1 H/s for Cuckatoo31

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1400]
[debug_2021-02-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/5974310/debug_2021-02-12.zip)
This test machine only hashes at ~0.5 g/s but it looks like RM won't go below 1 for this algo.

**Comment by RainbowMiner** [comment]
Oh! Sorry, we had a rounding bug. It's fixed now.

**Comment by jch9678** [comment]
Thanks!
