### ISSUE TITLE
Struggling to get MRR working

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1401]
I have to create this issue because I've tried everything and I've got stuck getting MRR working. I just added 2 new GPUs to my rig and enabled Legacy mode, and somehow broken it.

I've tried changing all the settings, but I can't figure out why my rigs are all disabled and offline on the MRR website.

I've attached the debug file, can someone help me get this working?

[debug_2021-02-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/5975891/debug_2021-02-13.zip)

**Comment by samdave123** [comment]
From pools.config.txt

  "MiningRigRentals": {
    "EnableMining": "0",
    "EnableAutoCreate": "1",
    "EnableAutoPrice": "1",
    "EnableMinimumPrice": "1",
    "PriceBTC": "0",
    "PriceFactor": "2.5",
    "PriceCurrencies": "BTC,ETH",
    "Title": "David Brown | %algorithm% | %workername%",
    "Description": "Please allow up to 3 minutes for the rental to begin.",
    "Worker": "NvidiaRig",
    "Penalty": 0,
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "FocusWallet": "",
    "AllowZero": "1",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "0",
    "CoinSymbolPBM": "",
    "DataWindow": "",
    "StatAverage": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "",
    "User": "samdave",
    "API_Key": "9b8f475b4340f4fc229a78f98a4fe478fc79376d7fbf85381c042e3f8da26ba9",
    "API_Secret": "2511289586821900afa3b6af52f386a9145bf2d6bb1e52e39ed5eb1e4ff39539",
    "AutoCreateMinProfitPercent": "0",
    "AutoCreateMinCPUProfitBTC": "0.00001",
    "AutoCreateMaxMinHours": "24",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "1",
    "AutoPriceModifierPercent": "0",
    "MinHours": "8",
    "MaxHours": "168",
    "EnableUpdateTitle": "1",
    "AutoUpdateMinPriceChangePercent": "0",
    "EnablePowerDrawAddOnly": "0",
    "PowerDrawFactor": "0.5",
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableUpdateDescription": "1",
    "EnableUpdatePriceModifier": "0",
    "EnableAutoExtend": "0",
    "AutoExtendTargetPercent": "95",
    "AutoExtendMaximumPercent": "5",
    "AutoBonusExtendForHours": "0",
    "AutoBonusExtendByHours": "0",
    "ProfitAverageTime": "Hour",
    "PauseBetweenRentals": "1h",
    "EnableAutoBenchmark": "1",
    "MaxAllowedLuck": "",
    "MaxTimeSinceLastBlock": "",
    "AllowExtensions": "0",
    "UseHost": "",
    "ExtensionMessageTime": "2h",
    "ExtensionMessage": "Dear renter, your rental will end soon. Now would be a good time to extend the rental, if you are happy with the result.",
    "UpdateInterval": "10m",
    "PriceFactorMin": "1.2",
    "PriceFactorDecayPercent": "6",
    "PriceFactorDecayTime": "10m",
    "Region": ""

**Comment by samdave123** [comment]
From mrr.config.txt:

{
  "GTX1070Ti": {
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableAutoCreate": "",
    "AutoCreateMinProfitPercent": "",
    "AutoCreateMinProfitBTC": "",
    "AutoCreateMaxMinHours": "",
    "AutoUpdateMinPriceChangePercent": "",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "",
    "EnableAutoPrice": "",
    "EnableMinimumPrice": "",
    "EnableUpdateTitle": "",
    "EnableUpdateDescription": "",
    "EnableUpdatePriceModifier": "",
    "EnablePowerDrawAddOnly": "",
    "AutoPriceModifierPercent": "",
    "PriceBTC": "",
    "PriceFactor": "",
    "PowerDrawFactor": "",
    "MinHours": "",
    "MaxHours": "",
    "PriceCurrencies": "",
    "Title": "",
    "Description": "",
    "EnableAutoExtend": "",
    "AutoExtendTargetPercent": "",
    "AutoExtendMaximumPercent": "",
    "AutoBonusExtendForHours": "",
    "AutoBonusExtendByHours": "",
    "ProfitAverageTime": "",
    "AllowExtensions": "",
    "PriceFactorMin": "",
    "PriceFactorDecayPercent": "",
    "PriceFactorDecayTime": ""
  },
  "GTX1070TIs": {
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableAutoCreate": "",
    "AutoCreateMinProfitPercent": "",
    "AutoCreateMinProfitBTC": "",
    "AutoCreateMaxMinHours": "",
    "AutoUpdateMinPriceChangePercent": "",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "",
    "EnableAutoExtend": "",
    "AutoExtendTargetPercent": "",
    "AutoExtendMaximumPercent": "",
    "EnableAutoPrice": "",
    "EnableMinimumPrice": "",
    "EnableUpdateTitle": "",
    "EnableUpdateDescription": "",
    "EnableUpdatePriceModifier": "",
    "EnablePowerDrawAddOnly": "",
    "AutoPriceModifierPercent": "",
    "PriceBTC": "",
    "PriceFactor": "",
    "PowerDrawFactor": "",
    "MinHours": "",
    "MaxHours": "",
    "PriceCurrencies": "",
    "Title": "",
    "Description": "",
    "AutoBonusExtendForHours": "",
    "AutoBonusExtendByHours": "",
    "ProfitAverageTime": "",
    "AllowExtensions": "",
    "PriceFactorMin": "",
    "PriceFactorDecayPercent": "",
    "PriceFactorDecayTime": ""
  },
  "GTX1660SUPER-GTX1660Ti": {
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableAutoCreate": "",
    "AutoCreateMinProfitPercent": "",
    "AutoCreateMinProfitBTC": "",
    "AutoCreateMaxMinHours": "",
    "AutoUpdateMinPriceChangePercent": "",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "",
    "EnableAutoExtend": "",
    "AutoExtendTargetPercent": "",
    "AutoExtendMaximumPercent": "",
    "AutoBonusExtendForHours": "",
    "AutoBonusExtendByHours": "",
    "EnableAutoPrice": "",
    "EnableMinimumPrice": "",
    "EnableUpdateTitle": "",
    "EnableUpdateDescription": "",
    "EnableUpdatePriceModifier": "",
    "EnablePowerDrawAddOnly": "",
    "AutoPriceModifierPercent": "",
    "PriceBTC": "",
    "PriceFactor": "",
    "PriceFactorMin": "",
    "PriceFactorDecayPercent": "",
    "PriceFactorDecayTime": "",
    "PowerDrawFactor": "",
    "MinHours": "",
    "MaxHours": "",
    "AllowExtensions": "",
    "PriceCurrencies": "",
    "Title": "",
    "Description": "",
    "ProfitAverageTime": ""
  },
  "GTX1660TIs": {
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableAutoCreate": "",
    "AutoCreateMinProfitPercent": "",
    "AutoCreateMinProfitBTC": "",
    "AutoCreateMaxMinHours": "",
    "AutoUpdateMinPriceChangePercent": "",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "",
    "EnableAutoExtend": "",
    "AutoExtendTargetPercent": "",
    "AutoExtendMaximumPercent": "",
    "EnableAutoPrice": "",
    "EnableMinimumPrice": "",
    "EnableUpdateTitle": "",
    "EnableUpdateDescription": "",
    "EnableUpdatePriceModifier": "",
    "EnablePowerDrawAddOnly": "",
    "AutoPriceModifierPercent": "",
    "PriceBTC": "",
    "PriceFactor": "",
    "PowerDrawFactor": "",
    "MinHours": "",
    "MaxHours": "",
    "PriceCurrencies": "",
    "Title": "",
    "Description": "",
    "AutoBonusExtendForHours": "",
    "AutoBonusExtendByHours": "",
    "ProfitAverageTime": "",
    "AllowExtensions": "",
    "PriceFactorMin": "",
    "PriceFactorDecayPercent": "",
    "PriceFactorDecayTime": ""
  },
  "GTX1660Tis,GTX1660SUPERs": {
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableAutoCreate": "",
    "AutoCreateMinProfitPercent": "",
    "AutoCreateMinProfitBTC": "",
    "AutoCreateMaxMinHours": "",
    "AutoUpdateMinPriceChangePercent": "",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "",
    "EnableAutoExtend": "",
    "AutoExtendTargetPercent": "",
    "AutoExtendMaximumPercent": "",
    "AutoBonusExtendForHours": "",
    "AutoBonusExtendByHours": "",
    "EnableAutoPrice": "",
    "EnableMinimumPrice": "",
    "EnableUpdateTitle": "",
    "EnableUpdateDescription": "",
    "EnableUpdatePriceModifier": "",
    "EnablePowerDrawAddOnly": "",
    "AutoPriceModifierPercent": "",
    "PriceBTC": "",
    "PriceFactor": "",
    "PriceFactorMin": "",
    "PriceFactorDecayPercent": "",
    "PriceFactorDecayTime": "",
    "PowerDrawFactor": "",
    "MinHours": "",
    "MaxHours": "",
    "AllowExtensions": "",
    "PriceCurrencies": "",
    "Title": "",
    "Description": "",
    "ProfitAverageTime": ""
  },
  "NvidiaRig": {
    "EnableAutoCreate": "",
    "AutoCreateMinProfitPercent": "",
    "AutoCreateMinProfitBTC": "",
    "AutoCreateMaxMinHours": "",
    "AutoUpdateMinPriceChangePercent": "",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "",
    "EnableAutoPrice": "",
    "EnableMinimumPrice": "",
    "EnableUpdateTitle": "",
    "EnablePowerDrawAddOnly": "",
    "AutoPriceModifierPercent": "",
    "PriceBTC": "",
    "PriceFactor": "",
    "PowerDrawFactor": "",
    "MinHours": "",
    "MaxHours": "",
    "PriceCurrencies": "",
    "Title": "",
    "Description": "",
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableUpdateDescription": "",
    "EnableUpdatePriceModifier": "",
    "EnableAutoExtend": "",
    "AutoExtendTargetPercent": "",
    "AutoExtendMaximumPercent": "",
    "AutoBonusExtendForHours": "",
    "AutoBonusExtendByHours": "",
    "ProfitAverageTime": "",
    "AllowExtensions": "",
    "PriceFactorMin": "",
    "PriceFactorDecayPercent": "",
    "PriceFactorDecayTime": ""
  },
  "NvidiaRig1070ti": {
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableAutoCreate": "",
    "AutoCreateMinProfitPercent": "",
    "AutoCreateMinProfitBTC": "",
    "AutoCreateMaxMinHours": "",
    "AutoUpdateMinPriceChangePercent": "",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "",
    "EnableAutoExtend": "",
    "AutoExtendTargetPercent": "",
    "AutoExtendMaximumPercent": "",
    "EnableAutoPrice": "",
    "EnableMinimumPrice": "",
    "EnableUpdateTitle": "",
    "EnableUpdateDescription": "",
    "EnableUpdatePriceModifier": "",
    "EnablePowerDrawAddOnly": "",
    "AutoPriceModifierPercent": "",
    "PriceBTC": "",
    "PriceFactor": "",
    "PowerDrawFactor": "",
    "MinHours": "",
    "MaxHours": "",
    "PriceCurrencies": "",
    "Title": "",
    "Description": "",
    "AutoBonusExtendForHours": "",
    "AutoBonusExtendByHours": "",
    "ProfitAverageTime": "",
    "AllowExtensions": "",
    "PriceFactorMin": "",
    "PriceFactorDecayPercent": "",
    "PriceFactorDecayTime": ""
  },
  "NvidiaRig1660ti": {
    "UseWorkerName": "",
    "ExcludeWorkerName": "",
    "EnableAutoCreate": "",
    "AutoCreateMinProfitPercent": "",
    "AutoCreateMinProfitBTC": "",
    "AutoCreateMaxMinHours": "",
    "AutoUpdateMinPriceChangePercent": "",
    "AutoCreateAlgorithm": "",
    "EnableAutoUpdate": "",
    "EnableAutoPrice": "",
    "EnableMinimumPrice": "",
    "EnableUpdateTitle": "",
    "EnableUpdateDescription": "",
    "EnableUpdatePriceModifier": "",
    "EnablePowerDrawAddOnly": "",
    "AutoPriceModifierPercent": "",
    "PriceBTC": "",
    "PriceFactor": "",
    "PowerDrawFactor": "",
    "MinHours": "",
    "MaxHours": "",
    "PriceCurrencies": "",
    "Title": "",
    "Description": "",
    "EnableAutoExtend": "",
    "AutoExtendTargetPercent": "",
    "AutoExtendMaximumPercent": "",
    "AutoBonusExtendForHours": "",
    "AutoBonusExtendByHours": "",
    "ProfitAverageTime": "",
    "AllowExtensions": "",
    "PriceFactorMin": "",
    "PriceFactorDecayPercent": "",
    "PriceFactorDecayTime": ""
  }
}

**Comment by samdave123** [comment]
devices.config.txt:

{
  "CPU": {
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "DefaultOCprofile": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1070Ti": {
    "DefaultOCprofile": "Profile4",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1070TiD": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1070TiE": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660SUPER": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660SUPERE": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660SUPERF": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660SUPER-GTX1660Ti": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660Ti": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660TiA": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660TiB": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660TiC": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660TiD": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660TiE": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
  "GTX1660TiF": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": ""
  }
}

**Comment by samdave123** [comment]
combos.config.txt:

{
  "AMD": {},
  "NVIDIA": {
    "GTX1660SUPER-GTX1660Ti": "1"
  }
}

**Comment by samdave123** [comment]
gpugroups.config.txt:

{
  "GPU#00": "",
  "GPU#01": "",
  "GPU#02": "",
  "GPU#03": "",
  "GPU#04": "",
  "GPU#05": ""
}

**Comment by RainbowMiner** [comment]
I have the gut feeling, it could have something todo with the Legacy mode. Let me check the code.

**Comment by samdave123** [comment]
Thanks @RainbowMiner

**Comment by samdave123** [comment]
I think this issue may have come back.

**Comment by samdave123** [comment]
@RainbowMiner All my rigs are offline again, could this have been broken in the latest RBM release?

**Comment by samdave123** [comment]
Nevermind, I'm sure it's being caused by whatever is causing https://github.com/RainbowMiner/RainbowMiner/issues/1450
