### ISSUE TITLE
CryptoDredge doesn't work with Virtual Machine Rig

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1402]
CryptoDredge doesn't work with Virtual Machine Rig.

Found this out during benchmarking.

What  what does RBM do if I am not there to close the popups that say, "CryptoDredge doesn't work with Virtual Machine"?  The popup message was wording different, just cannot remember the exact words.   In this case I had the RBM VM up on a browser VNC VM window and could click OK each time.

This could also apply to machine you currently don't have physical access to at the moment, I guess I better put Teamviewer on that Rig.

[debug_2021-02-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/5976155/debug_2021-02-13.zip)

**Comment by RainbowMiner** [comment]
Oh, this is not good. First, I would recommend to put all three `CryptoDredge16,CryptoDredge25,CryptoDredge` on the "ExcludeMiner" list in config.txt I cannot say, if killing the process get's rid of such a popup, too. Second, I will try to find a way to find out, if we are running within a VM and exclude it automatically.

Which VM are you using?

**Comment by RainbowMiner** [comment]
Woud you please open a cmd on that machine and enter

`wmic computersystem get model,name,manufacturer,systemtype`

.. and report back the result?

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/107861202-229e0e00-6df9-11eb-9d94-8887126e22aa.png)

**Comment by paulpoco** [comment]
> Oh, this is not good. First, I would recommend to put all three `CryptoDredge16,CryptoDredge25,CryptoDredge` on the "ExcludeMiner" list in config.txt . I cannot say, if killing the process get's rid of such a popup, too. Second, I will try to find a way to find out, if we are running within a VM and exclude it automatically.
> 
> Which VM are you using?

If I change "ExcludeMiner" on the client VM's config.txt will the server just overwrite the config?  i.e. earlier today added CPU back to Server's config.txt and one of the client machines also added CPU back but the VM client didn't add CPU back.

**Comment by RainbowMiner** [comment]
Ok, I have found a smart way to detect a VM. In Linux and Windows. Thank you for that hint!

**Comment by RainbowMiner** [comment]
> If I change "ExcludeMiner" on the client VM's config.txt will the server just overwrite the config? i.e. earlier today added CPU back to Server's config.txt and one of the client machines also added CPU back but the VM client didn't add CPU back.

Yes. It will change the ExcludeMiner back to the server's value. The only way to avoid this, would be to add ExcludeMiner to the "ExcludeServerConfigVars" list in config.txt of the client.
