### ISSUE TITLE
Pagefile initial size is not equal maximum size

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1405]
Noticed this info when starting the script today.

![RBMINER Pagefile initial size is not equal maximum size](https://user-images.githubusercontent.com/3217740/107871623-38393380-6ede-11eb-81c5-203f9daf2fde.png)

Any idea what should I do? Does this affect the mining operation?

**Comment by RainbowMiner** [comment]
Ignore it. It is for sure a bug, due to dual swap files. I will fix the message.
