### ISSUE TITLE
Autolykos2 / ERGO mining

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1407]
I checked Estimate Mining Profits on hermoniers website.
Mining Autolykos2 could the most profitable algo for some of my GPUs.

I just noticed Autolykos2 / ERGO  is disappeared from the mining list.
I have tried using all pool in RBMiner; 666pool.cn, nanopool.org, woolypooly.com and herominers.com but it still not appeared.
It just happened today.

**Comment by RainbowMiner** [comment]
There are multiple possibilities:
- the 24h trade volume for ERGO on the exchanges dropped below a minimum of 500$ for longer than 24 hours
- the last block has been found over one hour ago
- the mining hashrate on the pools is zero

In case of ERGO, I would suspect the trading volume, because all pools dropped out. I will check our rates API connectors.

**Comment by rizkyaulya** [comment]
![image](https://user-images.githubusercontent.com/44210627/107946913-3ea1db00-6fc4-11eb-8fa9-35c5f9518122.png)

The network split yesterday, that could be the reason all pools dropped out.
But, after that unfortunate event. All pool back online before.

**Comment by RainbowMiner** [comment]
Ok, that's a good reason for the pools to drop support temporarily.
Anyway, I have reworked our rates API, so that we always grab data from the aggregator, that is more accurate.

**Comment by rizkyaulya** [comment]
It happening again. The price of ERGO is increasing.
Nanopool & Herominer calculator said it should me more profitable for some of my GPUs
but it dissappeared again from @RainbowMiner 

> There are multiple possibilities:
> 
> * the 24h trade volume for ERGO on the exchanges dropped below a minimum of 500$ for longer than 24 hours

![image](https://user-images.githubusercontent.com/44210627/109375376-dec60100-78ee-11eb-8115-b1d7bc7f57de.png)


> * the last block has been found over one hour ago

> * the mining hashrate on the pools is zero

![image](https://user-images.githubusercontent.com/44210627/109375392-f8674880-78ee-11eb-86d0-e66ebef23a9d.png)

**Comment by RainbowMiner** [comment]
Thank you! I will check, what is going on.

**Comment by RainbowMiner** [comment]
I have seen, that you have set `"MinProfitPercent": 80.0,` for ERG - is it possible, that the profitability of ERG is below 80% of your rig's profitability?

**Comment by rizkyaulya** [comment]
I set it to deafult "MinProfitPercent": 0,
it didn't appear.

Then I tried to set "CheckProfitability": "0", in main config. VOILA!
It running Autolykos2 Ergo, sadly with this status:
![image](https://user-images.githubusercontent.com/44210627/109394598-6b59d900-795a-11eb-8b65-ffc07e22a69f.png)

while in whattomine calculator:
![image](https://user-images.githubusercontent.com/44210627/109394630-90e6e280-795a-11eb-8acb-74c331484a9c.png)

Official ERGO website:
![image](https://user-images.githubusercontent.com/44210627/109394646-9f34fe80-795a-11eb-9a7b-8dff086b4c76.png)

Hero Miner :
![image](https://user-images.githubusercontent.com/44210627/109394972-7f9ed580-795c-11eb-9852-e5e634cc96ef.png)

Meanwhile on RBminer window:
![image](https://user-images.githubusercontent.com/44210627/109394671-bffd5400-795a-11eb-9eef-b788330d5f5b.png)

Conclution
Autolykos2 / ERGO probably the most profitable for this RIG. 
But sometimes the profitability into minus in rbminer,
So I need to set set "CheckProfitability": "0" for a while now
