### ISSUE TITLE
lolminer won't start

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1408]
I spoke to you in Discord about this issue and we both thought it sounded like a driver issue. However, I did DDU and then installed the latest driver and it's still a problem. Something funny is going on...

[debug_2021-02-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/5984004/debug_2021-02-15.zip)

[lolminer-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-31700_2021-02-15_20-38-00.txt](https://github.com/RainbowMiner/RainbowMiner/files/5984003/lolminer-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-31700_2021-02-15_20-38-00.txt)

**Comment by samdave123** [comment]
The miner seems to think I have 11 devices?

**Comment by samdave123** [comment]
I'm also getting similar errors in Wildrig, some ccminers, etc.

**Comment by RainbowMiner** [comment]
Weird. It looks like there is some driver duplication. Could you please start `GPUTest.bat` and upload the gputestresult.txt?
I want to check, if OpenCL reports the correct number of platforms and devices. I have a lot of error checks and self-healing build into RainbowMiner, so that the command line parameters are perfectly allright.

Oh, and just to be double sure: for test purposes, set `"ShowMinerWindow": "1",` in config.txt and restart RainbowMiner. Now check, if Lolminer and Wildrig still fail.

**Comment by samdave123** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/5984135/gputestresult.txt)

**Comment by samdave123** [comment]
> Oh, and just to be double sure: for test purposes, set `"ShowMinerWindow": "1",` in config.txt and restart RainbowMiner. Now check, if Lolminer and Wildrig still fail.

This made no difference.

**Comment by RainbowMiner** [comment]
Ok, something is really wrong with your drivers. They report two Nvidia platforms. Both with 6 GPUs. Normally, there should be one Nvidia Platform and one Intel Platform (if the Onboard Intel GPU is active). 
Did you remove aLL Gpu drivers with DDU, or the Nvidia drivers, only? The second choice would have been the correct one.
So, I would do the following:
- DDU again, do the reboot dance
- Install actual Intel drivers, reboot again
- Install Nvidia drivers, reboot
- run GPUTest.bat and send the gputestresult.txt

**Comment by samdave123** [comment]
I removed just the Nvidia drivers with DDU.

The onboard Intel GPU is disabled.

Should I still follow these steps?

**Comment by RainbowMiner** [comment]
I would give it a second shot.

But before, make sure, that Windows doesn't install drivers automatically. Here is an instruction of how to disable that automation: https://www.laptopmag.com/articles/disable-automatic-driver-downloads-on-windows-10

And after that and before you DDU, install the driver once again. Maybe the driver installer fixes it. Just a shot.

**Comment by samdave123** [comment]
I've got Windows updates fully disabled, so I shouldn't have that problem. I'll follow these steps in the next few days when I have some time.

**Comment by RainbowMiner** [comment]
Ok. Keep me informed. I have a list for things, that can go wrong during Windows installations. I'ld like to add this issue.

**Comment by samdave123** [comment]
[Uploading gputestresult.txt…]()

**Comment by samdave123** [comment]
I mostly followed your steps, I did DDU to the Intel, Nvidia and even AMD just in case. I didn't install the Intel driver because the GPU was disabled and the Intel website says there is no available supported driver. The issue persists.

**Comment by samdave123** [comment]
[lolminer-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-31700_2021-02-16_18-42-04.txt](https://github.com/RainbowMiner/RainbowMiner/files/5990959/lolminer-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-31700_2021-02-16_18-42-04.txt)

**Comment by samdave123** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/5990961/gputestresult.txt)

**Comment by RainbowMiner** [comment]
So, this is really, really strange.
Most important: did you disable the hardware driver automatic download? (https://www.laptopmag.com/articles/disable-automatic-driver-downloads-on-windows-10)

Did you already try to install the Nvidia driver a second time, without DDU? Just on top of the currently installed driver?

If this doesn't help, maybe try to install an older driver, like the 441.34 hotfix. I'ld first try to install it directly on top of the 460 driver. If that doesn't work, DDU and install.
[Nvidia 441.34 hotfix Standard Win 10](https://international.download.nvidia.com/Windows/441.34hf/441.34-desktop-notebook-win10-64bit-international.hf.exe)
[Nvidia 441.34 hotfix DCH Win 10)[https://international.download.nvidia.com/Windows/441.34hf/441.34-desktop-notebook-win10-64bit-international-dch.hf.exe]

**Comment by samdave123** [comment]
I ran a script which disables all Windows auto-updates, so it should have disabled the HW driver auto-download too. I'm pretty sure that's not an issue.

I did DDU and then installed the Nvidia driver. I was on 441.34 when I first reported this problem.

**Comment by RainbowMiner** [comment]
Ok. Just make sure to double check that hardware driver update is really disabled. I had super strange effects on a rig, where I had forgotten to switch it off.

So the problem already happened on 441.34. That's good on the one hand, but bad on the other.
I will ask the Nvidia developers, what could cause such a duplication.

**Comment by RainbowMiner** [comment]
Did you install Vulcan, by accident? Check if it is on the installed programs list on the control panel.
When installing the drivers, install the drivers, only. Not the gameready part.

**Comment by samdave123** [comment]
> 
> 
> Did you install Vulcan, by accident? Check if it is on the installed programs list on the control panel.
> When installing the drivers, install the drivers, only. Not the gameready part.

Vulcan is not installed, and I did not install Geforce Experience (I assume that's what you mean by "gameready part").

**Comment by RainbowMiner** [comment]
> Geforce Experience (I assume that's what you mean by "gameready part").

Yes. 

I just did a Google search on duplicate GPUs and OpenCL and found, that there are some users, who have that exact same problem.

One last resort: enable that onboard Intel GPU and install drivers for it. Maybe the Intel drivers come along with an own OpenCL implementation, that fixes that problem.

**Comment by samdave123** [comment]
> One last resort: enable that onboard Intel GPU and install drivers for it. Maybe the Intel drivers come along with an own OpenCL implementation, that fixes that problem.

I don't think that's not going to solve my problem, because when the rig reboots the on-board Intel GPU does not activate unless I have a monitor plugged in. The board disables it by default. This was causing an issue before when my GPUs were getting reordered depending on whether I had a monitor plugged in.

**Comment by samdave123** [comment]
I use this rig headless.

**Comment by RainbowMiner** [comment]
> This was causing an issue before when my GPUs were getting reordered depending on whether I had a monitor plugged in.

This reordering should (hopefully) be solved by now, btw.

I will google on a bit. Maybe I find some more input to your problem with Nvidia OpenCL Platform duplicates.

**Comment by samdave123** [comment]
As we're currently out of ideas, I'm going to re-enable MRR. If you come up with any ideas to fix it, there will be a delay before I can test as I don't want to interrupt any ongoing rentals.

**Comment by samdave123** [comment]
Would device mode possibly fix this? If I'm not running 1660Tis and 1660 Supers on the same miner?

**Comment by RainbowMiner** [comment]
No. That wouldn't do the job, unfortunately. It's really a hardware driver issue, that some mining programs manage to solve. I would recommend, you disable all miners, that fail with that OpenCl duplication.
I have contacted a dev. at Nvidia. Now waiting for a response. Can take some time, in my experience.

**Comment by samdave123** [comment]
I'm running Windows 10 Pro 1809. Would it help if I updated Windows or reinstalled it?

**Comment by RainbowMiner** [comment]
It is worth a try.

**Comment by samdave123** [comment]
Might updating my BIOS or changing my BIOS settings help?

**Comment by samdave123** [comment]
I managed to fix/workaround this by adding "--devices 0,2,4,6,8,10" to the params in miner.config.txt. Please could you find a way to automate/self-heal this for the benefit of other users and also if I change my device setup in the future, or if lolminer adds additional algos? The log files still look a little weird, but it's working.

I'm wondering if I can fix other miners this way, as I have disabled a dozen of them for similar issues.

[lolminer-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-31700_2021-03-04_14-04-29.txt](https://github.com/RainbowMiner/RainbowMiner/files/6084191/lolminer-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-31700_2021-03-04_14-04-29.txt)
[lolminer-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-31700_2021-03-04_14-02-39.txt](https://github.com/RainbowMiner/RainbowMiner/files/6084194/lolminer-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-31700_2021-03-04_14-02-39.txt)
[lolminer-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-31700_2021-03-04_13-59-18.txt](https://github.com/RainbowMiner/RainbowMiner/files/6084195/lolminer-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-31700_2021-03-04_13-59-18.txt)

**Comment by samdave123** [comment]
@RainbowMiner Since I am able to work around this with just a parameter changes in the config file, could you automate some self-healing inside RBM to resolve this issue?

**Comment by RainbowMiner** [comment]
Ok, that should be possible.
To be able, would you please open `http://localhost:4000/devices` in your browser and upload the resulting JSON data?

**Comment by samdave123** [comment]
Weird, Github won't let me upload a .json so I named it .zip but it's a .json

[devices.zip](https://github.com/RainbowMiner/RainbowMiner/files/6084479/devices.zip)
