### ISSUE TITLE
DLL error on start on windows with Nvidia GPUs

### ISSUE THREAD

**Issue by OdinsTaint** [RainbowMiner/RainbowMiner#1409]
Starting v4.6.8.9! Please wait..

Checking for VM .. ok, not in a VM
Detecting devices ..
**WARNING: WDDM device detection has failed.**
Checking Windows pagefile/virtual memory .. ok
**WARNING: C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll has wrong version 441.41 vs. 461.40**
Initialize configuration ..
Cleanup legacy data ..
Cleaned 5 elements

Miner appears to be working, but wondering if this is an issue, and if it could be causing me loss of profits.  Nothing urgent, just wondering.

**Comment by AnthonyBe** [comment]
Already reported #1287

**Comment by RainbowMiner** [comment]
> WARNING: C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll has wrong version 441.41 vs. 461.40

Yes, that warning is just a warning of a nvml.dll version mismatch. Nvidia installs the dll in C:\Windows\System32 and (most of the times) in folder C:\Program Files\NVIDIA Corporation\NVSMI - RainbowMiner comes with an emergency fallback nvml.dll in folder .\Includes. If there are different program versions, RainbowMiner will warn.
The mismatch has no implications in 99% of the cases. If something odd is happening, you might consider to let RainbowMiner repair it. If you run RainbowMiner's Start.bat as administrator, it will try to repair the mismatch automatically.

The failing WDDM call is interesting. It should run through, without a problem. Anyway - it's a fallback for systems, where the OpenCL fails get the PCIe bus addresses of the devices. So if the miners run problem free, you are good.

Would you please be so kind and run GPUTest.bat and upload the resulting gputestresult.txt here?

**Comment by OdinsTaint** [comment]
Results, this only happens on my Nvidia 1030 GPU systems running windows:

GPU-TEST 02/16/2021 14:03:48
================================================================================
 
1. Afterburner NVIDIA
--------------------------------------------------------------------------------
 
 
2. Afterburner AMD
--------------------------------------------------------------------------------
 
 
3. OverdriveN
--------------------------------------------------------------------------------
 
Failed to load ADL library
 
4. nvidia-smi
--------------------------------------------------------------------------------
 
GeForce GT 1030, [Not Supported], [Not Supported], 38, [Not Supported], [Not Supported], 26 %, P5, [Not Supported], [Not Supported], [Not Supported], [Not Supported]
 
5. OpenCL
--------------------------------------------------------------------------------
 

Profile    : FULL_PROFILE
Version    : OpenCL 1.2 CUDA 11.2.135
Name       : NVIDIA CUDA
Vendor     : NVIDIA Corporation
Extensions : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, cl_khr_local_int32_extended_atomics…}



AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel
Extensions                 : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics, cl_khr_local_int32_extended_atomics…}
GlobalMemCacheSize         : 147456
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 128
GlobalMemSize              : 2147483648
ImageSupport               : True
LocalMemSize               : 49152
LocalMemType               : Local
MaxClockFrequency          : 1468
MaxComputeUnits            : 3
MaxConstantArgs            : 9
MaxConstantBufferSize      : 
MaxMemAllocSize            : 536870912
MaxParameterSize           : 4352
MaxReadImageArgs           : 256
MaxSamplers                : 32
MaxWorkGroupSize           : 1024
MaxWorkItemDimensions      : 3
MaxWorkItemSizes           : {1024, 1024, 64}
MaxWriteImageArgs          : 16
MemBaseAddrAlign           : 4096
MinDataTypeAlignSize       : 128
DeviceCapability           : 6.1
Architecture               : GeForce GT 1030
Name                       : GeForce GT 1030
ClVersion                  : OpenCL C 1.2 
Platform                   : OpenCl.Platform
PreferredVectorWidthChar   : 1
PreferredVectorWidthShort  : 1
PreferredVectorWidthInt    : 1
PreferredVectorWidthLong   : 1
PreferredVectorWidthFloat  : 1
PreferredVectorWidthDouble : 1
Profile                    : FULL_PROFILE
QueueProperties            : OutOfOrderExecModeEnable, ProfilingEnable
SingleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt
Type                       : Gpu
Vendor                     : NVIDIA Corporation
VendorId                   : 4318
Version                    : OpenCL 1.2 CUDA
DriverVersion              : 461.40
PCIBusId                   : 01:00


................................................................................
6. OverdriveNTool
--------------------------------------------------------------------------------
 
7. OdVII
--------------------------------------------------------------------------------
 
Failed to load ADL library
8. OdVII 8
--------------------------------------------------------------------------------
 
Failed to load ADL library

**Comment by RainbowMiner** [comment]
Ok, I see there is a PCIBusId in the OpenCL record. So you can safely ignore that warning.
