### ISSUE TITLE
666pool pool API errors

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1410]
Started today 16 Feb at 00:38 GMT+11
`[2021-02-16 00:38:36] WARNING: Pool API (666Pool) has failed. `

asyncloader log
`[2021-02-16 00:29:27] Error job CC64FBF61E1261532D08D3BEE15CB849 with https://www.666pool.cn/pool2/ using REST: Problem fetching https://www.666pool.cn/pool2/ using REST: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.`

**Comment by RainbowMiner** [comment]
Thank you! I will check, what is going on with 666pool.
