### ISSUE TITLE
Show remote miners in selected currency

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#1412]
![image](https://user-images.githubusercontent.com/1572453/108151382-28674e00-709c-11eb-9dd8-59b92e345b72.png)

**Comment by jch9678** [comment]
I like this idea as well.

**Comment by RainbowMiner** [comment]
Here you go - implemented.

**Comment by Nickfost** [comment]
It's still a mess
the remote table doesnt show the dollars only mbtc

**Comment by Nickfost** [comment]
![image](https://user-images.githubusercontent.com/1572453/109240674-892e0f00-779d-11eb-9a45-0771dcaa1785.png)
