### ISSUE TITLE
Show remote mining rigs qty of GPU

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#1413]
I would like to be able to see the quantity of graphics cards per mining program or mining rig in this view this way I can understand the benchmarks on a per card basis as well as how many online cards are in a given rig 
![image](https://user-images.githubusercontent.com/1572453/108151511-7b410580-709c-11eb-9840-f6cc28209ab4.png)

**Comment by RainbowMiner** [comment]
Added. Good idea, thanks!

**Comment by Nickfost** [comment]
It's still a mess
the remote workers table doesnt show the qty only model
![image](https://user-images.githubusercontent.com/1572453/109240569-4bc98180-779d-11eb-9fe2-b38b96eb2fe4.png)
