### ISSUE TITLE
MoneroOcean on Ethash broken

### ISSUE THREAD

**Issue by ArSd-g** [RainbowMiner/RainbowMiner#1415]
==> Gminer-GPU#00-32900_2021-02-17_21-14-16.txt <==
21:12:54 Connection Error: Write timed out
21:12:54 All user mining pools are unavailable

Teamred Miner - >Error -> reconnect >works!
Pool gulf.moneroocean.stream rpc method "eth_submitLogin" timed out after 69 seconds.  Reconnecting.

**Comment by RainbowMiner** [comment]
Thank you! I'll check Ethash on this pool.

**Comment by RainbowMiner** [comment]
Good finding. MoneroOcean needs special stratum for Ethash. Fixed it.
