### ISSUE TITLE
Question: rbminer.net

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1416]
The setting,

MinerStatusURL = url to central monitoring server [default=https://rbminer.net]

Is there another place we can point this? I only ask, Cause. Well. I only know of the one place.

I also ask because if I can point it to my own system and use it to collect the benchmarks on all my rigs so I can have a central point to see what I could potentially mine. But really its just the first question.

**Comment by RainbowMiner** [comment]
Sure. Where ever you point it to, the data will be sent to. You will have to put url + path to script. It sends a JSON formatted POST with loads of data. I can write the specification down for you, if you like.

**Comment by Yamanipanuchi** [comment]
Yes.

**Comment by gurkburk76** [comment]
seems like rbminer.net was down a day or two ago witch in turn triggered pushover messages about my rigs being down, witch in this case was now true so i'm thinking if there could be any way of preventing this by having some redundant server in case site X does not respons in Y tried. Or you setup a redundant solution on your backend via cloudflare or similar ;)

**Comment by RainbowMiner** [comment]
@gurkburk76 it's already behind Cloudflare. I will add some backup servers in the future, just in case.

**Comment by RainbowMiner** [comment]
### Report API documentation

Example:
```
{
    "cpu":  "AMD FX(tm)-8350 Eight-Core Processor",
    "cpuload":  "",
    "cpupower":  "0",
    "cputemp":  "",
    "crashalert":  "0",
    "crashdata":  "[]",
    "devices":  "",
    "earnings_1d":  "1.14E-06",
    "earnings_avg":  "1.03569394360143E-05",
    "email":  "",
    "interval":  "180",
    "machineip":  "192.168.1.17",
    "machinename":  "RAINBOWMINTER",
    "maxcrashes":  "5",
    "maxtemp":  "90",
    "minerdata":  "",
    "pool_totals":  "[]",
    "poolsdata":  "",
    "powerdraw":  "369.0",
    "profit":  "0.0001589",
    "pushoverkey":  "",
    "rates":  {
                  "BTC":  1.0,
                  "USD":  52673.115
              },
    "status":  "Running",
    "sysuptime":  "411812",
    "tempalert":  "0",
    "uptime":  "104073.7670121",
    "user":  "012345678-abcd-abcd-abcd-0123456789ab",
    "version":  "RainbowMiner 4.6.9.0",
    "worker":  "rainbowminer1",
    "data":  [
                 {
                     "Name":  "Xmrig",
                     "Version":  "6.8.2",
                     "Path":  "./Bin/ANY-Xmrig/xmrig",
                     "Type":  [
                                  "CPU"
                              ],
                     "Active":  "00 Days 00 Hours 45 Minutes",
                     "Algorithm":  [
                                       "CryptoNightHeavyXhv"
                                   ],
                     "Currency":  [
                                      "BTC"
                                  ],
                     "CoinName":  [
                                      "BLOC.money"
                                  ],
                     "CoinSymbol":  [
                                        "BLOC"
                                    ],
                     "Pool":  [
                                  "ZergPool"
                              ],
                     "CurrentSpeed":  [
                                          91.46775510204081
                                      ],
                     "EstimatedSpeed":  [
                                            111.09577838566442
                                        ],
                     "Accepted":  [
                                      239.0
                                  ],
                     "Rejected":  [
                                      0.0
                                  ],
                     "PowerDraw":  50,
                     "BTC/day":  1.886601391778084E-06,
                     "Profit":  1.886601391778084E-06,
                     "Donator":  false,
                     "Benchmarking":  false,
                     "Devices":  [
                                     {
                                         "Id":  0,
                                         "Name":  "AMD FX(tm)-8350 Eight-Core Processor",
                                         "Watt":  50,
                                         "Temp":  0
                                     }
                                 ]
                 },
                 {
                     "Name":  "Trex",
                     "Version":  "0.19.11",
                     "Path":  "./Bin/NVIDIA-Trex/t-rex",
                     "Type":  [
                                  "RTX2060"
                              ],
                     "Active":  "00 Days 00 Hours 23 Minutes",
                     "Algorithm":  [
                                       "Ethash"
                                   ],
                     "Currency":  [
                                      "BTC"
                                  ],
                     "CoinName":  [

                                  ],
                     "CoinSymbol":  [

                                    ],
                     "Pool":  [
                                  "NiceHash"
                              ],
                     "CurrentSpeed":  [
                                          27075395.666666668
                                      ],
                     "EstimatedSpeed":  [
                                            27061677.14432317
                                        ],
                     "Accepted":  [
                                      57.0
                                  ],
                     "Rejected":  [
                                      0.0
                                  ],
                     "PowerDraw":  146,
                     "BTC/day":  6.3674161164300046E-05,
                     "Profit":  6.3674161164300046E-05,
                     "Donator":  false,
                     "Benchmarking":  false,
                     "Devices":  [
                                     {
                                         "Id":  0,
                                         "Name":  "RTX2060",
                                         "Mem":  6,
                                         "Temp":  73,
                                         "Fan":  86,
                                         "Watt":  146.38,
                                         "Core":  1920,
                                         "MemC":  6801,
                                         "MaxTemp":  79
                                     }
                                 ]
                 },
                 {
                     "Name":  "Trex",
                     "Version":  "0.19.11",
                     "Path":  "./Bin/NVIDIA-Trex/t-rex",
                     "Type":  [
                                  "RTX2070"
                              ],
                     "Active":  "00 Days 00 Hours 28 Minutes",
                     "Algorithm":  [
                                       "Ethash"
                                   ],
                     "Currency":  [
                                      "BTC"
                                  ],
                     "CoinName":  [

                                  ],
                     "CoinSymbol":  [

                                    ],
                     "Pool":  [
                                  "NiceHash"
                              ],
                     "CurrentSpeed":  [
                                          37335604.02666666
                                      ],
                     "EstimatedSpeed":  [
                                            37344134.51658664
                                        ],
                     "Accepted":  [
                                      83.0
                                  ],
                     "Rejected":  [
                                      3.0
                                  ],
                     "PowerDraw":  173,
                     "BTC/day":  8.7868036673006042E-05,
                     "Profit":  8.7868036673006042E-05,
                     "Donator":  false,
                     "Benchmarking":  false,
                     "Devices":  [
                                     {
                                         "Id":  1,
                                         "Name":  "RTX2070",
                                         "Mem":  8,
                                         "Temp":  67,
                                         "Fan":  76,
                                         "Watt":  177.47,
                                         "Core":  1830,
                                         "MemC":  6801,
                                         "MaxTemp":  68
                                     }
                                 ]
                 },
                 {
                     "Name":  "Trex",
                     "Version":  "0.19.11",
                     "Path":  "./Bin/NVIDIA-Trex/t-rex",
                     "Type":  [
                                  "GT1030"
                              ],
                     "Active":  "00 Days 02 Hours 33 Minutes",
                     "Algorithm":  [
                                       "MegaBTX"
                                   ],
                     "Currency":  [
                                      "BTC"
                                  ],
                     "CoinName":  [
                                      "BitCore"
                                  ],
                     "CoinSymbol":  [
                                        "BTX"
                                    ],
                     "Pool":  [
                                  "Zpool"
                              ],
                     "CurrentSpeed":  [
                                          2345252.5
                                      ],
                     "EstimatedSpeed":  [
                                            2342479.708096538
                                        ],
                     "Accepted":  [
                                      751.0
                                  ],
                     "Rejected":  [
                                      8.0
                                  ],
                     "PowerDraw":  0,
                     "BTC/day":  1.09454290981124051E-05,
                     "Profit":  1.09454290981124051E-05,
                     "Donator":  false,
                     "Benchmarking":  false,
                     "Devices":  [
                                     {
                                         "Id":  2,
                                         "Name":  "GT1030",
                                         "Mem":  2,
                                         "Temp":  61,
                                         "Fan":  56,
                                         "Watt":  null,
                                         "Core":  1607,
                                         "MemC":  3003,
                                         "MaxTemp":  61
                                     },
                                     {
                                         "Id":  3,
                                         "Name":  "GT1030",
                                         "Mem":  2,
                                         "Temp":  61,
                                         "Fan":  56,
                                         "Watt":  null,
                                         "Core":  1607,
                                         "MemC":  3003,
                                         "MaxTemp":  61
                                     }
                                 ]
                 }
             ]
}
```

The JSON encoded object contains multiple machine global values, plus an array `"data"`, that contains all data of the currently running miners, including the used devices.

#### General values

- "cpu":  name of the machine's CPU
- "cpuload":  current CPU load (in percent, 0..100)
- "cpupower":  current CPU power consumption
- "cputemp":  current CPU temperature
- "crashalert":  number of crash alerts in the past hour
- "crashdata":  array, that contains all data of the crashed miners
- "devices":  this will contain all device's data (sent during startup, only)
- "earnings_1d":  one day moving average earnings per day
- "earnings_avg":  live moving average earnings per day
- "email":  your email address, if set
- "interval":  current RainbowMiner script interval in seconds
- "machineip":  machine's local IP address
- "machinename":  machine's system name
- "maxcrashes":  number of allowed crashes within one hour
- "maxtemp":  maximum allowed GPU temperature, before a notification will be initiated
 - "minerdata":  this will contain all active miner's data (sent every three hours, only)
 - "pool_totals":  this will contain all pool's totals (sent every three hours, only)
 - "poolsdata":  this will contain all pool's data (sent every three hours, only)
- "powerdraw":  machine's current power consumption
- "profit":  current profit in BTC
- "pushoverkey":  your Pushover key, if set
- "rates":  object, with conversion rates for your currencies, set in config.txt
- "status":  status of rig "Paused", "Waiting" (for profitability) or "Running"
- "sysuptime":  uptime of your system in seconds
- "tempalert":  number of temperature alerts during the past hour
- "uptime":  uptime of RainbowMiner
- "user":  your rbminer.net API key
- "version":  version of RainbowMiner instance
- "worker":  name of the RainbowMiner worker
- "data": array of all running miners

#### device "data" records
- "Name":  miner's name
- "Version":  miner's version
- "Path":  local file path to the miner
- "Type":  array with device model names*
- "Active":  runtime of miner,
- "Algorithm":  array with algorithms*
- "Currency":  array with autoexchange currencies (or coinsymbol, if no autoexchange)*
- "CoinName": array with minted coin's names*
- "CoinSymbol":  array with minted coin's symbols*
- "Pool":  array of pools*
- "CurrentSpeed":  array with current hashrate in H/s or G/s *
- "EstimatedSpeed":  array with benchmarked hashrates in H/s or G/s *
- "Accepted":  array with number of accepted shares*
- "Rejected":  array with number of rejected shares*
- "PowerDraw":  current powerdraw in Watt
- "BTC/day": current profit per day in BTC
- "Profit":  current profit per day in "Currency"
- "Donator":  true if miner is mining for developer
- "Benchmarking":  true if miner is benchmarking
- "Devices":  array of used devices

* two entries if dual mining, otherwise only one entry

#### Devices records
-  "Id":  internal id number (starts with 0)
- "Name":  model name
- "Mem":  amount of memory in GB (board memory, in case of CPU)
- "Temp":  current temperature in °C
- "Fan":  current fan speed in percent (GPUs only)
- "Watt":  current power consumption in Watt
- "Core":  current core clock (GPUs only)
- "MemC":  current memory clock (GPUs only)
- "MaxTemp":  maximum temperature during runtime in °C

**Comment by RainbowMiner** [comment]
@gurkburk76 I have switched rbminer.net to a bigger machine. That should help to reduce downtimes. Also, the way I handle notifications on the server side has been changed, so that false positives should be avoided.
Step three, I am currently adding a load balancer for the report API to compensate during downtimes.

**Comment by TheeeX** [comment]
> Sure. Where ever you point it to, the data will be sent to. You will have to put url + path to script. It sends a JSON formatted POST with loads of data. I can write the specification down for you, if you like.

Can you open-source the code for RainbowMiner monitoring central (rbminer.net).

**Comment by bwstandard** [comment]
> ### Report API documentation
> Example:
> 
> ```
> {
>     "cpu":  "AMD FX(tm)-8350 Eight-Core Processor",
>     "cpuload":  "",
>     "cpupower":  "0",
>     "cputemp":  "",
>     "crashalert":  "0",
>     "crashdata":  "[]",
>     "devices":  "",
>     "earnings_1d":  "1.14E-06",
>     "earnings_avg":  "1.03569394360143E-05",
>     "email":  "",
>     "interval":  "180",
>     "machineip":  "192.168.1.17",
>     "machinename":  "RAINBOWMINTER",
>     "maxcrashes":  "5",
>     "maxtemp":  "90",
>     "minerdata":  "",
>     "pool_totals":  "[]",
>     "poolsdata":  "",
>     "powerdraw":  "369.0",
>     "profit":  "0.0001589",
>     "pushoverkey":  "",
>     "rates":  {
>                   "BTC":  1.0,
>                   "USD":  52673.115
>               },
>     "status":  "Running",
>     "sysuptime":  "411812",
>     "tempalert":  "0",
>     "uptime":  "104073.7670121",
>     "user":  "012345678-abcd-abcd-abcd-0123456789ab",
>     "version":  "RainbowMiner 4.6.9.0",
>     "worker":  "rainbowminer1",
>     "data":  [
>                  {
>                      "Name":  "Xmrig",
>                      "Version":  "6.8.2",
>                      "Path":  "./Bin/ANY-Xmrig/xmrig",
>                      "Type":  [
>                                   "CPU"
>                               ],
>                      "Active":  "00 Days 00 Hours 45 Minutes",
>                      "Algorithm":  [
>                                        "CryptoNightHeavyXhv"
>                                    ],
>                      "Currency":  [
>                                       "BTC"
>                                   ],
>                      "CoinName":  [
>                                       "BLOC.money"
>                                   ],
>                      "CoinSymbol":  [
>                                         "BLOC"
>                                     ],
>                      "Pool":  [
>                                   "ZergPool"
>                               ],
>                      "CurrentSpeed":  [
>                                           91.46775510204081
>                                       ],
>                      "EstimatedSpeed":  [
>                                             111.09577838566442
>                                         ],
>                      "Accepted":  [
>                                       239.0
>                                   ],
>                      "Rejected":  [
>                                       0.0
>                                   ],
>                      "PowerDraw":  50,
>                      "BTC/day":  1.886601391778084E-06,
>                      "Profit":  1.886601391778084E-06,
>                      "Donator":  false,
>                      "Benchmarking":  false,
>                      "Devices":  [
>                                      {
>                                          "Id":  0,
>                                          "Name":  "AMD FX(tm)-8350 Eight-Core Processor",
>                                          "Watt":  50,
>                                          "Temp":  0
>                                      }
>                                  ]
>                  },
>                  {
>                      "Name":  "Trex",
>                      "Version":  "0.19.11",
>                      "Path":  "./Bin/NVIDIA-Trex/t-rex",
>                      "Type":  [
>                                   "RTX2060"
>                               ],
>                      "Active":  "00 Days 00 Hours 23 Minutes",
>                      "Algorithm":  [
>                                        "Ethash"
>                                    ],
>                      "Currency":  [
>                                       "BTC"
>                                   ],
>                      "CoinName":  [
> 
>                                   ],
>                      "CoinSymbol":  [
> 
>                                     ],
>                      "Pool":  [
>                                   "NiceHash"
>                               ],
>                      "CurrentSpeed":  [
>                                           27075395.666666668
>                                       ],
>                      "EstimatedSpeed":  [
>                                             27061677.14432317
>                                         ],
>                      "Accepted":  [
>                                       57.0
>                                   ],
>                      "Rejected":  [
>                                       0.0
>                                   ],
>                      "PowerDraw":  146,
>                      "BTC/day":  6.3674161164300046E-05,
>                      "Profit":  6.3674161164300046E-05,
>                      "Donator":  false,
>                      "Benchmarking":  false,
>                      "Devices":  [
>                                      {
>                                          "Id":  0,
>                                          "Name":  "RTX2060",
>                                          "Mem":  6,
>                                          "Temp":  73,
>                                          "Fan":  86,
>                                          "Watt":  146.38,
>                                          "Core":  1920,
>                                          "MemC":  6801,
>                                          "MaxTemp":  79
>                                      }
>                                  ]
>                  },
>                  {
>                      "Name":  "Trex",
>                      "Version":  "0.19.11",
>                      "Path":  "./Bin/NVIDIA-Trex/t-rex",
>                      "Type":  [
>                                   "RTX2070"
>                               ],
>                      "Active":  "00 Days 00 Hours 28 Minutes",
>                      "Algorithm":  [
>                                        "Ethash"
>                                    ],
>                      "Currency":  [
>                                       "BTC"
>                                   ],
>                      "CoinName":  [
> 
>                                   ],
>                      "CoinSymbol":  [
> 
>                                     ],
>                      "Pool":  [
>                                   "NiceHash"
>                               ],
>                      "CurrentSpeed":  [
>                                           37335604.02666666
>                                       ],
>                      "EstimatedSpeed":  [
>                                             37344134.51658664
>                                         ],
>                      "Accepted":  [
>                                       83.0
>                                   ],
>                      "Rejected":  [
>                                       3.0
>                                   ],
>                      "PowerDraw":  173,
>                      "BTC/day":  8.7868036673006042E-05,
>                      "Profit":  8.7868036673006042E-05,
>                      "Donator":  false,
>                      "Benchmarking":  false,
>                      "Devices":  [
>                                      {
>                                          "Id":  1,
>                                          "Name":  "RTX2070",
>                                          "Mem":  8,
>                                          "Temp":  67,
>                                          "Fan":  76,
>                                          "Watt":  177.47,
>                                          "Core":  1830,
>                                          "MemC":  6801,
>                                          "MaxTemp":  68
>                                      }
>                                  ]
>                  },
>                  {
>                      "Name":  "Trex",
>                      "Version":  "0.19.11",
>                      "Path":  "./Bin/NVIDIA-Trex/t-rex",
>                      "Type":  [
>                                   "GT1030"
>                               ],
>                      "Active":  "00 Days 02 Hours 33 Minutes",
>                      "Algorithm":  [
>                                        "MegaBTX"
>                                    ],
>                      "Currency":  [
>                                       "BTC"
>                                   ],
>                      "CoinName":  [
>                                       "BitCore"
>                                   ],
>                      "CoinSymbol":  [
>                                         "BTX"
>                                     ],
>                      "Pool":  [
>                                   "Zpool"
>                               ],
>                      "CurrentSpeed":  [
>                                           2345252.5
>                                       ],
>                      "EstimatedSpeed":  [
>                                             2342479.708096538
>                                         ],
>                      "Accepted":  [
>                                       751.0
>                                   ],
>                      "Rejected":  [
>                                       8.0
>                                   ],
>                      "PowerDraw":  0,
>                      "BTC/day":  1.09454290981124051E-05,
>                      "Profit":  1.09454290981124051E-05,
>                      "Donator":  false,
>                      "Benchmarking":  false,
>                      "Devices":  [
>                                      {
>                                          "Id":  2,
>                                          "Name":  "GT1030",
>                                          "Mem":  2,
>                                          "Temp":  61,
>                                          "Fan":  56,
>                                          "Watt":  null,
>                                          "Core":  1607,
>                                          "MemC":  3003,
>                                          "MaxTemp":  61
>                                      },
>                                      {
>                                          "Id":  3,
>                                          "Name":  "GT1030",
>                                          "Mem":  2,
>                                          "Temp":  61,
>                                          "Fan":  56,
>                                          "Watt":  null,
>                                          "Core":  1607,
>                                          "MemC":  3003,
>                                          "MaxTemp":  61
>                                      }
>                                  ]
>                  }
>              ]
> }
> ```
> 
> The JSON encoded object contains multiple machine global values, plus an array `"data"`, that contains all data of the currently running miners, including the used devices.
> 
> #### General values
> * "cpu":  name of the machine's CPU
> * "cpuload":  current CPU load (in percent, 0..100)
> * "cpupower":  current CPU power consumption
> * "cputemp":  current CPU temperature
> * "crashalert":  number of crash alerts in the past hour
> * "crashdata":  array, that contains all data of the crashed miners
> * "devices":  this will contain all device's data (sent during startup, only)
> * "earnings_1d":  one day moving average earnings per day
> * "earnings_avg":  live moving average earnings per day
> * "email":  your email address, if set
> * "interval":  current RainbowMiner script interval in seconds
> * "machineip":  machine's local IP address
> * "machinename":  machine's system name
> * "maxcrashes":  number of allowed crashes within one hour
> * "maxtemp":  maximum allowed GPU temperature, before a notification will be initiated
> * "minerdata":  this will contain all active miner's data (sent every three hours, only)
> * "pool_totals":  this will contain all pool's totals (sent every three hours, only)
> * "poolsdata":  this will contain all pool's data (sent every three hours, only)
> * "powerdraw":  machine's current power consumption
> * "profit":  current profit in BTC
> * "pushoverkey":  your Pushover key, if set
> * "rates":  object, with conversion rates for your currencies, set in config.txt
> * "status":  status of rig "Paused", "Waiting" (for profitability) or "Running"
> * "sysuptime":  uptime of your system in seconds
> * "tempalert":  number of temperature alerts during the past hour
> * "uptime":  uptime of RainbowMiner
> * "user":  your rbminer.net API key
> * "version":  version of RainbowMiner instance
> * "worker":  name of the RainbowMiner worker
> * "data": array of all running miners
> 
> #### device "data" records
> * "Name":  miner's name
> * "Version":  miner's version
> * "Path":  local file path to the miner
> * "Type":  array with device model names*
> * "Active":  runtime of miner,
> * "Algorithm":  array with algorithms*
> * "Currency":  array with autoexchange currencies (or coinsymbol, if no autoexchange)*
> * "CoinName": array with minted coin's names*
> * "CoinSymbol":  array with minted coin's symbols*
> * "Pool":  array of pools*
> * "CurrentSpeed":  array with current hashrate in H/s or G/s *
> * "EstimatedSpeed":  array with benchmarked hashrates in H/s or G/s *
> * "Accepted":  array with number of accepted shares*
> * "Rejected":  array with number of rejected shares*
> * "PowerDraw":  current powerdraw in Watt
> * "BTC/day": current profit per day in BTC
> * "Profit":  current profit per day in "Currency"
> * "Donator":  true if miner is mining for developer
> * "Benchmarking":  true if miner is benchmarking
> * "Devices":  array of used devices
> 
> * two entries if dual mining, otherwise only one entry
> 
> #### Devices records
> * "Id":  internal id number (starts with 0)
> * "Name":  model name
> * "Mem":  amount of memory in GB (board memory, in case of CPU)
> * "Temp":  current temperature in °C
> * "Fan":  current fan speed in percent (GPUs only)
> * "Watt":  current power consumption in Watt
> * "Core":  current core clock (GPUs only)
> * "MemC":  current memory clock (GPUs only)
> * "MaxTemp":  maximum temperature during runtime in °C

So I'm a little nooby here. I do know web but not necessarily all the Dev stuff.

I have a vps and could get domains etc. 

Is there a certain system you post this json into? I would like to use something like this in the case my ip gets blocked again.
