### ISSUE TITLE
No Pools Available

### ISSUE THREAD

**Issue by VoltaVX** [RainbowMiner/RainbowMiner#1419]
All of a sudden, I started getting this problem in the middle of mining. During startup, it claims to be loading pools that I don't have selected. From what I could guess, this might have something to do with devfees? Maybe one of the pools it uses is down? I'm don't really know

![image](https://user-images.githubusercontent.com/51927819/108375089-a710d800-71cf-11eb-86d6-f13d34d9614a.png)

Also getting this error:

![image](https://user-images.githubusercontent.com/51927819/108375310-d45d8600-71cf-11eb-94c6-79dff8a0514d.png)

**Comment by VoltaVX** [comment]
Here are my logs:
PS: I zipped the 7zip file inside zip so Github would let me upload it.
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/6003691/Logs.zip)

**Comment by VoltaVX** [comment]
Update: After updating to the latest version, and restarting Windows Terminal, the error got fixed. Anyways, I'll leave the thread up just in case there's some glitch with the dev fee mechanism that caused the initial error in the first place.

**Comment by RainbowMiner** [comment]
The warning points to the problem. I'll check your logs.

**Comment by RainbowMiner** [comment]
Would you please open http://localhost:4000 in your browser and then click "Debug file" and finally upload the resulting zip file here?

**Comment by VoltaVX** [comment]
[debug_2021-02-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/6004599/debug_2021-02-18.zip)

**Comment by RainbowMiner** [comment]
This should be solved. You had the right idea to update.
