### ISSUE TITLE
Add XVG for blockmasterscoins and zergpoolcoins

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#142]
Add XVG payout for blockmasterscoins and zergpoolcoins

**Comment by rinkal26783** [comment]
#138

**Comment by RainbowMiner** [comment]
Ok: I changed the pool management in the upcomeing release: from this release on, every currency that is added to a pool in the pools.config.txt will be used as autoexchange currency. You have to check, if the used currency is being payed regularly by a pool.

**Comment by rinkal26783** [comment]
still not being able to use xvg wallet for zergpoolcoins and blockmasterscoins
Starting up v3.8.6.12! Please wait..

Transcript started, output file is .\Logs\RainbowMiner_2018-09-12_09-14-37.txt
Detecting devices ..
Initialize configuration ..
Write-Log : Could not create C:\Users\JP\Desktop\RainbowMiner-master\RainbowMiner-master\Config\pools.config.txt
At C:\Users\JP\Desktop\RainbowMiner-master\RainbowMiner-master\Include.psm1:2477 char:13
+             Write-Log -Level Error "Could not create $($PathToFile) "
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

Start afterburner library ..
Read configuration ..
WARNING: No pools available.

**Comment by rinkal26783** [comment]
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2373501/config.txt)
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2373502/pools.config.txt)

**Comment by RainbowMiner** [comment]
> Write-Log : Could not create C:\Users\JP\Desktop\RainbowMiner-master\RainbowMiner-master\Config\pools.config.txt

This has it's cause in a write lock: you may have opened the pools.config.txt in an editor. I think I will implement a check for that, since multiple users stumbled over this problem.

**Comment by RainbowMiner** [comment]
For the XVG - I will start one of my rigs with your config to check. It should work.

**Comment by RainbowMiner** [comment]
Checked: you corrupted the json format:

`"XVG: "DLUr2gaJbSks5JgyZDi1psrrSzhKtyq5YA",
-----^ 

the closing " is missing
`

This is how it would be correct:
`"XVG": "DLUr2gaJbSks5JgyZDi1psrrSzhKtyq5YA",`

**Comment by RainbowMiner** [comment]
All checked and working, with the correct json format. I just mined for you for some minutes.
