### ISSUE TITLE
Update BTC Wallet RegEx Statement

### ISSUE THREAD

**Issue by jeremyhammon** [RainbowMiner/RainbowMiner#1420]
Line 15 in wallet.ps1 should be updated as follows in order to capture segwit BTC addresses.  This is for the wallet balance update so it should not affect if you ware wanting to restrict the use of segwit addresses elsewhere in the application, but i have not had any issues with using a segwit address so far except for the balance updates.

This line:
```powershell
$Wallets = @($Config.Wallet) + @($Config.Pools.PSObject.Properties.Value | Where-Object {$_.Wallets.BTC} | Foreach-Object {$_.Wallets.BTC}) | Where-Object {$_ -match "^[13]"} | Select-Object -Unique | Sort-Object
```

Changed to this for a full address match/validation:
```powershell
$Wallets = @($Config.Wallet) + @($Config.Pools.PSObject.Properties.Value | Where-Object {$_.Wallets.BTC} | Foreach-Object {$_.Wallets.BTC}) | Where-Object {$_ -match '^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}$'} | Select-Object -Unique | Sort-Object
```

Or this to simply match the starting characters as you are doing now:
```powershell
$Wallets = @($Config.Wallet) + @($Config.Pools.PSObject.Properties.Value | Where-Object {$_.Wallets.BTC} | Foreach-Object {$_.Wallets.BTC}) | Where-Object {$_ -match '^(bc1|[13])'} | Select-Object -Unique | Sort-Object
```

There could be other places in the code where this same RegEx is being used and may need to be updated.  I have not performed a complete search to check it yet.

[More information about BTC address formats.](https://allprivatekeys.com/bitcoin-address-format)

**Comment by RainbowMiner** [comment]
Hi, thank you! I will change the wallets code accordingly.
