### ISSUE TITLE
Rainbow miner hang / stuck

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1423]
Hello, All of my rig perform similar behavior.
Monitoring Central show the RIGs was offline, but in fact the miner still running.
here are some details:

1. Miner still working in the background but the RainbowMiner CMD window stuck/hang
2. Can't press anything X for Exit R for restart
3. localhost still working fine
4. Mostly Happen when Hashing for MRR renters
5. Detected as offline at rbminer.net/monitoring/?user=

**Comment by RainbowMiner** [comment]
There are not many conditions, that could cause a hang. So here are some questions:
- is this Linux or Windows?
- which algorithm/miner are mostly active, when such a hang happens?
- could you please upload a Debug file for one of the machines, where it happened most recently?

**Comment by rizkyaulya** [comment]
"is this Linux or Windows?"
Windows, I just did sfc scannow and restore health. hopefully fix some issues.

which algorithm/miner are mostly active, when such a hang happens?
I didn't check it. But it just happen in Kawpow & Equishash 24x7

could you please upload a Debug file for one of the machines, where it happened most recently?
here is it:
[debug_2021-02-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/6011793/debug_2021-02-20.zip)

**Comment by RainbowMiner** [comment]
This is connected to #1425 - will be solved with the tomorrow release.

**Comment by rizkyaulya** [comment]
The problem still occurs.
with Error warning:

"WARNING: MiningRigRental error: Not Authenticated - Invalid Key - Bad Nonce. - rig/81"

2 of my RIG was hashing for MRR
one server & one client.

Server:
[debug_2021-02-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/6019061/debug_2021-02-22.zip)
Client:
[debug_2021-02-22 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/6019068/debug_2021-02-22.1.zip)

**Comment by RainbowMiner** [comment]
Thank you for uploading the debug files. I will analyse the ongoings.

**Comment by rizkyaulya** [comment]
Now with Asyncloader crashed warning

![image](https://user-images.githubusercontent.com/44210627/109771715-bbbd8900-7c2f-11eb-8c13-b8d9c9bf4c50.png)

**Comment by RainbowMiner** [comment]
Please try the new pre-release. I have included lots of fixes, which address that annoying Powershell bug.
