### ISSUE TITLE
Rainbowminer restarts system NVIDIA

### ISSUE THREAD

**Issue by mcangeli** [RainbowMiner/RainbowMiner#1424]
I have two systems I am trying to run rainbow miner on. The first one has two GPUS, a GTX 1060 and an AMD RX560.

I can run rainbow miner on this machine with mining on the AMD and the CPU, but as soon as I enable the NVIDIA card in the settings it crashes the computer.

I am able to mine with Phoenix Miner on the NVIDIA and the AMD card with out an issue (outside of RBMiner) its only when I run rainbow miner.

On the second system, I only have a GTX 1080 card. Again, I am able to mine without an issue in Phoenix outside of RBM, but when I start RBM and try to mine with it, the system restarts. On this machine, i did remove the updated driver I had and installed the 442.01 version that was tested good a year ago and I am able to mine with Phoenix but not RBM.

Where should I be looking to see what the cause of the restarts are??

**Comment by RainbowMiner** [comment]
A restart is normally a sign either for too much overclocking or too much powerdraw of the GPUs, causing PSU failure.
Question: do you happen to notice, which miner has been called, just before that reboot? Could you please zip the Logs folders of both machines and upload them here? I will then have a look, what causes the trouble. Maybe I then can tell you more.

**Comment by mcangeli** [comment]
Thanks!
I disabled the oc on both machines and it still happened. I thought it was Trex (or whatever that one is but I am not certain.
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/6011597/Logs.zip)
Here are the logs for the machine with just the GTX 1080 in it.

**Comment by mcangeli** [comment]
And here are the ones with the Dual GPu
[Logs-2.zip](https://github.com/RainbowMiner/RainbowMiner/files/6011628/Logs-2.zip)

**Comment by mcangeli** [comment]
These are both Windows 10 Pro machines.

**Comment by RainbowMiner** [comment]
Ok, it looks like one of the both above.
The miners run power intense algorithms. No problem with Ethash, though, because it hasn't that much power consumption.

Important: did you set "Force P2 State" to "Off" ? Here is a documentation --> https://github.com/RainbowMiner/RainbowMiner/issues/36

With the above flag set, you might want to retry with EnableOCProfiles set to "1"

**Comment by mcangeli** [comment]
Ok, so that let it run for a bit, but I think it really does not like the trex miner.

**Comment by mcangeli** [comment]
I "excluded" trex. It still runs for a bit and then crashes the whole system on the box with one card. Same on the dual GPU.

I'll play with it, maybe I just need to limit what I am mining to Eth,

**Comment by RainbowMiner** [comment]
Yes, probably too much power draw on your PSUs. How big are those?

**Comment by mcangeli** [comment]
I don't know, whatever came in the computers to begin with.
Its on my list to build a dedicated rig for the two nvidia cards.

**Comment by RainbowMiner** [comment]
> I don't know, whatever came in the computers to begin with.

Oh. So most probably, those PSUs aren't suitable for maximum power draw of the GPUs. Especially those 1080 are beasts, regarding that. Try to cut down maximum power of the GPUs, using the powerlimit in ocprofiles. Try to go lower by some Watt and try again, then repeat.

**Comment by mcangeli** [comment]
Thanks! I'll play with it a bit when I have time. 
These two are mining eth so its all good and then Rainbow is working ok with the rx560 and the cpu on the one machine.

Any plans of being able to monitor external miners (like asics?)
