### ISSUE TITLE
Running too many miner in Multi GPUs RIG

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1425]
I just build a mix GPU RIG from my old RIGs consist of:
2x RX VEGA
1x RTX 1660
2x RX 580 4GB
it was running too many miner that cause the RIG freezing.
Looks like it failed to close previous miner before start a new one.

Here is my debug:
[debug_2021-02-20 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/6011988/debug_2021-02-20.1.zip)

My mining mode is device or combo before.

**Comment by RainbowMiner** [comment]
Ok, this is a special case. I think, I have found a possible culprit. Could you please try to set `  "EnableMinerStatus": "0",` in config.txt for test purposes? Does this solve the problem? If yes, please let me know.

**Comment by rizkyaulya** [comment]
I set "EnableMinerStatus": "0", in the server RIG. 
All Worker/IP status in monitoring central was offline.

Then, I re-benchmark the "ok status" miner.
The benchmark is successful smoothly .

So, Do I need to set "EnableMinerStatus": "0" for this RIG to prevent the issue in the future?

**Comment by RainbowMiner** [comment]
> All Worker/IP status in monitoring central was offline.

Yes, that's what you disable with that setting. Actually, leave it at "0" until the next release, tomorrow. I will solve the problem with a tweak to the core code.
