### ISSUE TITLE
2 Miners Pending Balance

### ISSUE THREAD

**Issue by jeremyhammon** [RainbowMiner/RainbowMiner#1426]
2 Miners Pending Balance is currently reading the "pending" value from the API which i believe is actually for a pending payment.  Earnings from mining which are pending are in the API as a value of "immature"

The Pending value for 2 miners in Balances\2Miners.ps1 starting at line 53 should be updated with something like the following

```powershell
                Pending     = [Decimal]$Request.stats.immature / $Divisor
                Total       = ([Decimal]$Request.stats.balance + [Decimal]$Request.stats.immature) / $Divisor
```

in order to capture all current "earnings" including the blocks that are still pending.

**Comment by RainbowMiner** [comment]
Thank you! I will fix it.
