### ISSUE TITLE
Asynchloader dies (was: Question on RM AutoUpdate - how often does it check for new releases?)

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1429]
Hi,

A couple of times recently I've seen GitHub notifications letting me know about new releases of RM, but when I check my PC, I'm still running a previous version even up to 24 hours later. If I Restart RM, it detects the new version and AutoUpdates.

My goal is to have RM auto-update faster when a new release is pushed.

In my config.txt I have
```
  "EnableAutoupdate": "1",
  "EnableUpdateDuringPause": "1",
  "EnableUpdateWhenScheduled": "$EnableUpdateWhenScheduled",
```

EnableUpdateWhenScheduled I've never set, so that is how it was added when that feature was pushed.

Based on the above, how often _should_ RM be checking for an update to trigger the auto-update?
Is there anything I should be changing to speed up detection of new releases to trigger autoupdate?

Thanks!

**Comment by RainbowMiner** [comment]
That's interesting. The automatic update should detect a new version every 1-2 hours.

**Comment by AnthonyBe** [comment]
I'm still running 4.6.8.9 despite 4.6.9.0 being release 2 days ago.

Does the check for newer version operation, and autoupdate operation, get logged anywhere?

**Comment by RainbowMiner** [comment]
Do you get a warning message, that a new release is available?

**Comment by AnthonyBe** [comment]
Nope.

That's why I asked how often it was checking because I see no evidence that is actually checking for updates.

**Comment by RainbowMiner** [comment]
That's odd.

Could you please upload the following:
- file `.\Logs\autoupdate.txt`
- open `http://localhost:4000/asyncloaderjobs` in your browser, then search for record `34D1FC8F1EB5271842739D69997C6B54` and upload the JSON of that record.

**Comment by RainbowMiner** [comment]
Ok. These four files should help me to narrow down, what is going on.

**Comment by AnthonyBe** [comment]
1. [autoupdate.txt](https://github.com/RainbowMiner/RainbowMiner/files/6014939/autoupdate.txt)
2. The asyncloader JSON for `34D1FC8F1EB5271842739D69997C6B54` record
```
"34D1FC8F1EB5271842739D69997C6B54": {
      "Url": "https://api.github.com/repos/rainbowminer/RainbowMiner/releases/latest",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Body": null,
      "Headers": null,
      "Success": 69,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2021-02-18T14:28:01.9438701Z",
      "LastCacheWrite": "2021-02-18T14:28:01.9473142Z",
      "LastFailRetry": null,
      "CycleTime": 3600,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10,
      "Index": 1
    },
```
3. `.\Cache\34D1FC8F1EB5271842739D69997C6B54.asy` attached
[34D1FC8F1EB5271842739D69997C6B54.asy.txt](https://github.com/RainbowMiner/RainbowMiner/files/6014943/34D1FC8F1EB5271842739D69997C6B54.asy.txt)
4. `.\Logs\errors_2021-02-20.asyncloader.txt` I don't have for 20th Feb. Most recent for me is this 19 Feb
[errors_2021-02-19.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/6014944/errors_2021-02-19.asyncloader.txt)
 attached.

**Comment by RainbowMiner** [comment]
It seems like the build-in asynchronous loader is crashed. That should never happen, actually. Which file date has the youngest file in your `./Cache` folder?

**Comment by AnthonyBe** [comment]
Newest files (25 of them) have the following timestamp (I'm GMT+11): 19 Feb 2021 1:46 AM

**Comment by AnthonyBe** [comment]
I'll hold off Restarting RM to keep it in the 'broken state' and avoid over-writing logs, etc. until you give me the green light :)

**Comment by RainbowMiner** [comment]
Ok, the time of the newest file is identically to the last error entry in errors_2021-02-19.asyncloader.txt. Which doesn't explain, why the loader is crashed. That's really strange. Give me 10 minutes to think this over.

**Comment by RainbowMiner** [comment]
Please try the following:
- press `Y` in the RainbowMiner console window, when "Waiting XXs until next run" is shown.

Now the console should display "[Y] pressed - Asyncloader yanked.".
- If it doesn't and/or the console hangs, please let me know. In that case, just close the console by clicking onto "x" and restart RainbowMiner.
- If it does show up, have a look into the `.\Cache` folder and look, if the files are updating.

**Comment by RainbowMiner** [comment]
Would you mind to create and upload a Debug file please? I want to check the logs and config for possible clues.

**Comment by AnthonyBe** [comment]
> Would you mind to create and upload a Debug file please? I want to check the logs and config for possible clues.

Is that done by doing this?
`DisableAsyncLoader = set to 1, if all net access should happen synchronous (used for debugging)`

**Comment by RainbowMiner** [comment]
For a Debug file, open http://localhost:4000 and then click "Debug file" on the left hand side.

**Comment by AnthonyBe** [comment]
> For a Debug file, open http://localhost:4000 and then click "Debug file" on the left hand side.

Ah, OK.

So, since I hung it earlier by pressing Y in the console, I've manually killed it and restarted. It detected 4.6.9.1 and updated successfully.

I assume there isn't much value in sending you the debug zip file now while everything is working, but just in case, please find attached.

I'll keep an eye out for when you push a new release and RM doesn't autoupdate, and then grab a fresh debug log dump when it is in a 'broken' state.

**Comment by RainbowMiner** [comment]
The debug file compacts historic data, so it is very helpful. I have identified a problem with the Microsoft webrequests and timeouts on calls. It looks pretty much like a Powershell bug, so I will try to build a work around to avoid these hangs.

**Comment by AnthonyBe** [comment]
It's failed again.
Currently still running RM 4.6.9.1
4.6.9.2 GitHub email notification in my Inbox at 5:19am 22 Feb 2021 (GMT+11)
./cache files - most recent timestamps are 7:36pm 21 Feb 2021 (GMT+11)

Fresh debug attached in case it is useful
[debug_2021-02-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/6019394/debug_2021-02-22.zip)

**Comment by RainbowMiner** [comment]
Yes, let's hope, it helps. It looks pretty much like a Powershell bug.

**Comment by RainbowMiner** [comment]
It all comes down to the Powershell web request commands. I have now switched all calls to exactly one specific command. If we are lucky, there shouldn't be anymore blockings.

If you are running v4.6.9.2 update immediatly.

**Comment by AnthonyBe** [comment]
Found that my setup had successfully auto-updated to 4.6.9.3 overnight, so that's a plus!

Will continue to monitor and provide feedback.

**Comment by RainbowMiner** [comment]
Nice! So let's now hope the best, since I have changed another bit from v4.6.9.2 to v4.6.9.3

**Comment by AnthonyBe** [comment]
![image](https://user-images.githubusercontent.com/17214552/108918348-5133a880-7685-11eb-9973-487eda451c65.png)

I tried hitting Y to restart asyncloader but it hung RM.
I was still able to get a Debug log out of it.

[debug_2021-02-24.zip](https://github.com/RainbowMiner/RainbowMiner/files/6032210/debug_2021-02-24.zip)

**Comment by RainbowMiner** [comment]
Ah, I hate this Powershell bug. It comes down to the point, where I will need to program my own web access module.

**Comment by RainbowMiner** [comment]
Ok, I have one recommendation: cut down your pools. It's not a good idea to select so many. So, pick those, that you really want to mine and setup all wallets for them. Think about setting AutoCoin/AutoPool to "0".

That might cut down the total web request load by a lot. There are especially lot's of 404 not found errors for pools.

**Comment by AnthonyBe** [comment]
> Ok, I have one recommendation: cut down your pools. It's not a good idea to select so many. So, pick those, that you really want to mine and setup all wallets for them. Think about setting AutoCoin/AutoPool to "0".
> 
> That might cut down the total web request load by a lot. There are especially lot's of 404 not found errors for pools.

Got it. I've trimmed about 1/3 of them first cut and will see what happens.

**Comment by AnthonyBe** [comment]
[debug_2021-03-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/6215328/debug_2021-03-27.zip)

Even with a single pool (Ezil) I've just noticed that asynchloader died again

**Comment by RainbowMiner** [comment]
Ok, please activate cURL on that machine. Just create an empty text file `curl.txt` in your RainbowMiner folder and restart.

**Comment by RainbowMiner** [comment]
Oh! Wait! I think I have just found a problem with the WoolyPooly balance module (thanks to your Debug file)

**Comment by AnthonyBe** [comment]
I've been focus mining a single pool for the last few weeks (unmineable). I've just re-enabled my normal multi-pool config and am seeing the Asyncloader crashing most days (i.e. every ~24 hours).

[debug_2021-04-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/6395176/debug_2021-04-29.zip)

**Comment by AnthonyBe** [comment]
I got the 4.7.16 update when I restarted RM this morning, and I'm finding that the Asyncloader is crashing within a few hours.

Fresh debug logs:

[debug_2021-04-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/6396552/debug_2021-04-29.zip)

**Comment by RainbowMiner** [comment]
I think, you are exhausting the Windows dynamic IP stack by using the "EnableAutoPool" (coins.config.txt) / "EnableAutoCoin" (pools.config.txt), since every coin will be applied to every possible pool thus causing a load of http fails. Each failed http call will block a dynamic IP address from the Windows IP stack (there is a maximum of about 60000 addresses avial) for some time. At some point, this stack is used up, obviously crashing the Windows stack handler.

I would strongly recommend the following:
- set all `"EnableAutoPool": "0",` in coins.config.txt and all `"EnableAutoCoin": "0",` in pools config.txt.
- don't use all pools. It's very much more efficient, if you focus on a handful (e.g. 2Miners, ProHashing, unMineable, Nicehash, ZergPoolCoins). 
- decide, which coins you want to mine on pools, that don't do autoexchange and setup the wallet addresses.
- if there are more pool modules for a certain pool available (like ZergPool, ZergPoolCoins, ZergPoolSolo, ... for ZergPool), use one of them, only.

If all those hints don't help (or if you want to stick to the AutoCoin/AutoPool mechanics), you could also try to enable CURL. That's kind of a workaround to avoid that Windows stack handler crash. To enable it, just create a text file with the name `curl.txt` in your RainbowMiner folder. It doesn't matter, if that file is empty or contains text, RainbowMiner checks for it's existance, only, during startup.
