### ISSUE TITLE
Wallet Question

### ISSUE THREAD

**Issue by jeremyhammon** [RainbowMiner/RainbowMiner#1432]
What is the best way, without be developing my own - which is an option if i need to, to add an additional BTC wallet to be tracked?  Code looks like it gets BTC addresses from $wallet and the ones in use in the pools, but adding it to a pool which is not in use doesn't seem to work.  Is there another method to add one to track that I am missing?  or is that just a functionality that isn't/wasn't expected?

Example use case:
NiceHash allows you to transfer from your wallet there to any other wallet.  Sometimes that transfer may be to your default BTC wallet, but you may also transfer to coinbase as there is a lower fee to do so.  In this situation you may wish to track the balance of both BTC wallets, but one of them may never be directly mined into.

**Comment by RainbowMiner** [comment]
Hi, good idea. Currently, that is not possible, without abusing pools, that are not in use. I will add an enhancement to the coins.config.txt, so that multiple wallets of one currency can be added.

**Comment by jeremyhammon** [comment]
I could probably find a way to work around it with other coins, but BTC is handled different than everything else.  It may be possible if i added a BTC in the coins config it may pick it up as long as i add an additional handler in there for it, but i don't really want to duplicate the code for BTC.  

Quick (kinda off topic) question.  What is your interest level in adding support for additional currencies for the wallets?  I know I have added support for DOGE and DASH already just so i could track some balances, but i wasn't sure if you would want to integrate those into the codebase.  I guess you could add as many as possible as long as they weren't too hard to maintain since you already have the config option to restrict which ones are shown if you want to.

**Comment by RainbowMiner** [comment]
Sure, DOGE should be easy. For DASH, I can't tell. I will try to add both.

Regarding the coins, some words in general. I have designed the coins.config.txt as the wallet container. You can use easy variables in pools.config.txt to reference to the coins in coins.config.txt. E.g. "$DOGE" in pools.config.txt will be automatically substituted with the "DOGE" wallet address, that you have defined in coins.config.txt

The coins for the wallets in localhost and the console are all unique wallet addresses, found in coins.config.txt and pools.config.txt.

**Comment by jeremyhammon** [comment]
here is code for DOGE, DASH, and AE

```powershell
    [PSCustomObject]@{symbol = "DASH"; match = "^Xn";   rpc = "https://api.blockcypher.com/v1/dash/main/addrs/{w}";                   address = "address";                          balance = "balance";                         received = "total_received";                   divisor = 1e8}
    [PSCustomObject]@{symbol = "DOGE"; match = "^D";    rpc = "https://api.blockcypher.com/v1/doge/main/addrs/{w}";                   address = "address";                          balance = "balance";                         received = "total_received";                   divisor = 1e8}
    [PSCustomObject]@{symbol = "AE";   match = "^AK";   rpc = "http://www.aeknow.org/api/account/{w}";                                address = "id";                               balance = "balance";                         received = "";                                 divisor = 1e18}
```

**Comment by jeremyhammon** [comment]
well, the match may not be exactly right on them, i would have to research their addresses to see if there are any other options

**Comment by RainbowMiner** [comment]
Thanks a lot! I will add them asap

**Comment by RainbowMiner** [comment]
Cool. I just discovered some AE.

I have implemented the following, as well (commit dd202c1906974e4016753318a3e8b5a873f84136)
- allow multiple wallet addresses for a currency in coins.config.txt: simply add them with underscore and a unique number. e.g. "BTC_1", "DOGE_23", etc. The new coinnames can be used as variables in pools ("$BTC_1","$DOGE_23").

**Comment by jeremyhammon** [comment]
There is an issue i am seeing.  Specifically with AE.

When it pulls the Json data, it seems to read it, convert it to an object, Convert it back to Json and then write it out and/or use it.

The issue I am seeing in particular is that the Json  balance for AE seems to be converted to a biginteger datatype when being converted to an object.  Then when it converts it back to Json you end up with {IsPowerOfTwo=False; IsZero=False; IsOne=False; IsEven=True; Sign=1} as your balance value instead of the number and the end result is this error:

Cannot convert the "@{IsPowerOfTwo=False; IsZero=False; IsOne=False; IsEven=True; Sign=1}" value of type
"System.Management.Automation.PSCustomObject" to type "System.Decimal".
At C:\Crypto\RainbowMiner\Balances\Wallet.ps1:102 char:50
+             $Wallet_Balance = [Decimal]$(Switch ($Wallet_Symbol) {
+                                                  ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException


This is a fundamental flaw in the way powershell handles Json, but there isn't a good fix for it.  It affects core worse than windows, but it can be encountered in both.

Best way i can see to handle it would be to pass the data through a function to change the datatype of anything that is a biginteger before writing it back out.  for a simple object it would just be something like

$Data | Get-Member -MemberType NoteProperty | ?{$Data.($_.Name).GetType().Name -eq "BigInteger"} | %{$Data.($_.Name) = [Decimal]$Data.($_.Name)}

but if it is multi-dimensional it gets more complex.  Another option would be to exceptionalize that one wallet and do a more direct call of the API, but it may not be the only time this issues is encountered either.

**Comment by RainbowMiner** [comment]
Thank you! Oh dear, a bigint, again. Yes, I had my encounters with the bigints, too. I will convert the values for AE accordingly.

**Comment by RainbowMiner** [comment]
What a nasty bug! I think, I have found an elegant way to work around it.
For future reference: https://github.com/PowerShell/PowerShell/issues/9207 is where the bug is best described.
