### ISSUE TITLE
GTX860M

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1434]
I have an old laptop I just wanted to see if its at all profitable. RBM seems to detect it fine and creates all the OC and miner config files. However, it just doesn't show up in the profit switching. Is there a reason why it wouldn't?

**Comment by RainbowMiner** [comment]
Is it mining away? So, is it a display issue, only?

**Comment by acos0874** [comment]
No it doesn't appear to be mining as no miner window has opened except for
the CPU mining.

**Comment by RainbowMiner** [comment]
Could you please run GPUTest.bat and upload the gputestresult.txt ?

**Comment by acos0874** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/6023777/gputestresult.txt)

**Comment by RainbowMiner** [comment]
Ok, that should work. Which pools did you setup? I have quickly run a test on my old notebook with a GT 630M - worked.
Could you create a Debug file?

**Comment by acos0874** [comment]
[debug_2021-02-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/6023816/debug_2021-02-22.zip)

**Comment by acos0874** [comment]
Also, don't worry about it too much. I suspect it's not going to be profitable enough for you to spend time on.

**Comment by RainbowMiner** [comment]
Sure, no problem :)

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/108745014-8380c100-7532-11eb-8569-69e82d0226e4.png)
 I just noticed this. I'll try updating the drivers

**Comment by RainbowMiner** [comment]
Ah! Found it. Your selection of miners doesn't contain any CUDA 9.1 miner. That GPU has reached it's max. with CUDA 9.1

```
    "MinerName":  [
                      "gminer",
                      "trex",
                      "trexgtx",
                      "nbminer",
                      "claymoredual",
                      "enemyzealot",
                      "miniz",
                      "nheqminer",
                      "cryptodredge",
                      "cryptodredge16",
                      "CcminerYescryptR8",
                      "CcminerYescrypt",
                      "trexoctopus",
                      "ccminermtp",
                      "ccminermtp10",
                      "verthash"
                  ],
```

.. so, I recommend enabling all miners (empty that "MinerName" in config.txt) and see, which download.

**Comment by acos0874** [comment]
OK thanks will try it.

>

**Comment by RainbowMiner** [comment]
> I just noticed this. I'll try updating the drivers

IF there is a newer driver, then do it. For my old GT 630M, the current driver with CUDA9.1 is as high as it can go.
