### ISSUE TITLE
Profit Display Keep Changing

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1435]
![image](https://user-images.githubusercontent.com/42582444/108746869-c774c580-7534-11eb-8b73-8ad09dbe0781.png)
Sometimes the profit on remote rigs shows in GBP but sometimes in mBTC. I don't know how it is that I change it, but I quite enjoy seeing it in GBP. Please can you explain if I'm looking in the wrong place?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/108747027-e83d1b00-7534-11eb-9197-95184ede9687.png)
Now it's just changed

**Comment by RainbowMiner** [comment]
Do all rigs have the exact same "Currency" string in config.txt? I mean, like "GBP,BTC" and not vice versa?

**Comment by astronyu** [comment]
Same here, it shows as mBTC and a few moments later changed to USD.
In config, I have default "Currency": "BTC,USD"

**Comment by RainbowMiner** [comment]
Oh! My bad! I have found the problem - I have been using hashtable keys for the rate's sorting. That's bad, because it changes from call to call. Fix is on the way. Good, that you have pointed to that.

**Comment by acos0874** [comment]
Thanks for fixing!

>

**Comment by RainbowMiner** [comment]
Now, here we go. With the next release, the sorting will be constant.
