### ISSUE TITLE
HeroMiners - RVN price at USD$4.36B/day :)

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1436]
![image](https://user-images.githubusercontent.com/17214552/108796429-ddd65c00-75dc-11eb-80ec-7736c00c86bb.png)

Seems a tad high :)

**Comment by AnthonyBe** [comment]
Seems to have returned to normal now.

**Comment by RainbowMiner** [comment]
Woa! That was high. You must be rich, by now.

**Comment by AnthonyBe** [comment]
I wish. You'd be seeing a big donation if that were the case! :)
