### ISSUE TITLE
Separate oc profile for each or group of GPU.

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1437]
@RainbowMiner, I have 6x 1060s where 4 of them can accept higher mem oc and 2 of them only can accept low mem oc.
Is there a way to use ocprofile to oc 4 in 1 group and 2 in another group?

**Comment by RainbowMiner** [comment]
Yes - use their PCIe address (or GPU-id) in ocprofiles.config.txt
This is the priority:  GPU-id > PCIe > Devicemodel

e.g.
- `"Profile2-GPU#03"` or `"Profile2-3"` will address GPU#03
- `"Profile2-03:00"` will address GPU at PCIe address 03:00
- `"Profile2-GTX1060"` will address all, except those that are addressed by PCIe or GPU-id

**Comment by astronyu** [comment]
Great! Thanks for the explanation.
