### ISSUE TITLE
 Creating miner config files failed

### ISSUE THREAD

**Issue by mcangeli** [RainbowMiner/RainbowMiner#1442]
WARNING: Creating miner config files failed (Xmrig KawPOW@ZergPool}) [Error: 'Invalid JSON primitive: .'].

Is there something I can do to correct this??

Also, I am seeing a message about not being able to connect to MSIAfterburner (even when I have it running).

Is there a correction for that as well?

**Comment by RainbowMiner** [comment]
> WARNING: Creating miner config files failed (Xmrig KawPOW@ZergPool}) [Error: 'Invalid JSON primitive: .'].

That's a strange error message.
- please look into the folder `.\Bin\ANY-Xmrig` and upload all `threads_*.json`, and all `config_KawPOW*.json` files here.
- please create a Debug file (click "Debug file" on http://localhost:4000) and upload it as well

> Also, I am seeing a message about not being able to connect to MSIAfterburner (even when I have it running).

Try to start the Afterburner first, then start RainbowMiner. Maybe that fixes the problem.

**Comment by mcangeli** [comment]
Starting Afterburner first seems to have resolved the issue with it.

I restarted the whole machine and it seems to be working now.

Thanks!
