### ISSUE TITLE
MRR Autoextend hours...

### ISSUE THREAD

**Issue by mcangeli** [RainbowMiner/RainbowMiner#1443]
I have the autoextendhours set.

"AutoBonusExtendForHours":  "12",
                   "AutoBonusExtendByHours":  "2",

And it worked, but it added it for every set of 12 hours. So for a 48 hour rental it added 8 hours when I only meant for it to add 2 hours total.

Is there a way for it to only add it once?

**Comment by astronyu** [comment]
Looks fine to me?
For every 12 hours, add 2 hours. So, for 48 hours means 2x4=8.

If you need hours added to be 2 hoursfor 48 hours rental, then maybe this helps.
"AutoBonusExtendForHours": "24",
"AutoBonusExtendByHours": "1",

This will add 1 hours for every 24 hours rental.

**Comment by RainbowMiner** [comment]
> And it worked, but it added it for every set of 12 hours. So for a 48 hour rental it added 8 hours when I only meant for it to add 2 hours total.

This is exactly the correct behavior.
But I can add an extra option `"AutoBonusExtendTimes"` for you, that would restrict the bonus extension to an exact number of times. Setting it to "1" would just add that bonus once, if the 12 hours minimum rental time has been met.

**Comment by RainbowMiner** [comment]
Ok, here you go:
- **AutoBonusExtendTimes**: Limit the maximum extensions by AutoBonusExtendByHours to a specific number of times (e.g. 1), 0=unlimited [default=0]

**Comment by mcangeli** [comment]
Thank you!
