### ISSUE TITLE
RVN on Herominers

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1446]
I keep getting RVN popping up on HeroMiners for some 1.4T$. Look like either HeroMiner's is tossing a bad number or there a decimal in the wrong place?

**Comment by RainbowMiner** [comment]
I will investigate that - it's most probably a bigint problem.

**Comment by RainbowMiner** [comment]
If that 1.4T$ pops up next time, would you please open `http://localhost:4000/rates` and upload the result here? I want to make sure, the problem isn't a currency rates API problem.

**Comment by Yamanipanuchi** [comment]
{
  "BTC": 1.0,
  "CFX": 101729.3997965412,
  "XMR": 237.44744217898383,
  "TRTL": 1711427625.9067452,
  "USD": 47192.385,
  "ETH": 31.730921783277804,
  "RVN": 288006.27078549867
}

**Comment by Yamanipanuchi** [comment]
Miner    Fee Algorithm        Speed    Diff Power         BTC/Day           USD/Day  Accuracy Pool                 PoolFee
-----    --- ---------        -----    ---- -----         --------          -------- -------- ----                 -------
Trex   1.00% KawPOW      15.20 MH/s 243.06M  206W 200,110.01761822 9,380,314,162.218      87% HeroMiners-Ravencoin   0.90%

**Comment by RainbowMiner** [comment]
Ok, so the problem is with the Herominers API. Now it's easier for me to find out. Thank you!

**Comment by Yamanipanuchi** [comment]
Thank, Fixed now.
