### ISSUE TITLE
Zpool does not pick up Lux wallet

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#145]
Running from Master. Zpool did not picked up Lux Wallet
![image](https://user-images.githubusercontent.com/41829368/45388350-f5205b00-b5d5-11e8-9493-1e081f2b751f.png)
![image](https://user-images.githubusercontent.com/41829368/45388399-0f5a3900-b5d6-11e8-8ac7-680d17dbd226.png)

**Comment by RainbowMiner** [comment]
Maybe, the currencies API was down. I will check.

**Comment by RainbowMiner** [comment]
Ok, it's a little different with Zpool: put one single wallet into the pools.config.txt, only (means, remove the line "BTC": "$Wallet"), since Zpool accepts only one autoexchange wallet.

**Comment by hernandn01** [comment]
I see, well my main purpose is to mine and get paid on the same currency for a few of the currencies. Everything else convert into BTC

**Comment by hernandn01** [comment]
Basically only autoexchange BTC and nothing else.
