### ISSUE TITLE
Problems with Verthash Miner on 4.6.9.6

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1452]
I'm running into a couple problems with Verthash Miner.  
It's still choosing the wrong devices:
`VerthashMiner.exe --cl-devices 1,5,6,2,4,3` 
One of my 6 gpu's is not activated, I assume because the onboard graphics is chosen instead of the gpu.

It doesn't show up in the profitability list so it is not chosen even though it should be the most profitable.
[debug_2021-02-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/6055121/debug_2021-02-27.zip)

**Comment by RainbowMiner** [comment]
Could you please run GPUtest.bat/gputest.sh and upload the gputestresult.txt?

**Comment by jch9678** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/6059435/gputestresult.txt)

**Comment by RainbowMiner** [comment]
Ah! I see. Thank you, that will help. Now one last thing: open http://localhost:4000/alldevices
.. please upload the result here.

**Comment by jch9678** [comment]
Sorry was out of town.  Is this what you want?

`Name
Vendor
Model
Memory
Cores/Stream Processors
Clock Speed
Driver Version
GPU#00	AMD	R9200	4 GB	40	300	2841.19
GPU#01	AMD	R9200	4 GB	40	300	2841.19
GPU#02	AMD	R9200	4 GB	40	300	2841.19
GPU#03	AMD	R9200	4 GB	44	300	2841.19
GPU#04	AMD	R9200	4 GB	44	300	2841.19
GPU#05	AMD	R9200	4 GB	44	300	2841.19
GPU#06	INTEL	HDGraphics	1.39 GB	6	N/A	10.18.10.4252
CPU#00	INTEL	CPU	2 GB	2/2	N/A	N/A`

**Comment by RainbowMiner** [comment]
Almost. I would love to get the JSON data from `http://localhost:4000/alldevices`

**Comment by jch9678** [comment]
[
  {
    "Name": "GPU#00",
    "Index": 0,
    "PlatformId": 0,
    "PlatformId_Index": 0,
    "Type_PlatformId_Index": 0,
    "Platform_Vendor": "AMD",
    "Vendor": "AMD",
    "Vendor_Name": "Advanced Micro Devices, Inc.",
    "Vendor_Index": 0,
    "Type_Vendor_Index": 0,
    "Type": "Gpu",
    "Type_Index": 0,
    "Type_Mineable_Index": 0,
    "OpenCL": {
      "DeviceIndex": 0,
      "Name": "AMD Radeon R9 200 Series",
      "Architecture": "Hawaii",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "GlobalMemSize": 4294967296,
      "GlobalMemSizeGB": 4,
      "MaxComputeUnits": 40,
      "PlatformVersion": "OpenCL 2.1 AMD-APP (2841.19)",
      "DriverVersion": "2841.19",
      "PCIBusId": "01:00",
      "DeviceCapability": null,
      "CardId": -1
    },
    "Model": "R9200",
    "Model_Base": "R9200",
    "Model_Name": "Radeon R9 200",
    "InstanceId": "PCI\\VEN_1002&DEV_67B1&SUBSYS_93951682&REV_00\\4&A2E6DA5&0&0008",
    "CardId": -1,
    "BusId": "01:00",
    "BusId_Index": 1,
    "BusId_Mineable_Index": 0,
    "GpuGroup": "",
    "Data": {
      "AdapterId": 0,
      "Utilization": 0,
      "UtilizationMem": 0,
      "Clock": 300,
      "ClockMem": 150,
      "FanSpeed": 43,
      "Temperature": 37,
      "PowerDraw": 0.0,
      "PowerLimit": 0,
      "PowerLimitPercent": 0,
      "PowerMaxLimit": 0,
      "PowerDefaultLimit": 0,
      "Pstate": "",
      "Method": "ab"
    },
    "DataMax": {
      "Clock": 300,
      "ClockMem": 150,
      "Temperature": 37,
      "FanSpeed": 43,
      "PowerDraw": 0.0
    }
  },
  {
    "Name": "GPU#01",
    "Index": 1,
    "PlatformId": 0,
    "PlatformId_Index": 1,
    "Type_PlatformId_Index": 1,
    "Platform_Vendor": "AMD",
    "Vendor": "AMD",
    "Vendor_Name": "Advanced Micro Devices, Inc.",
    "Vendor_Index": 1,
    "Type_Vendor_Index": 1,
    "Type": "Gpu",
    "Type_Index": 1,
    "Type_Mineable_Index": 1,
    "OpenCL": {
      "DeviceIndex": 1,
      "Name": "AMD Radeon R9 200 Series",
      "Architecture": "Hawaii",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "GlobalMemSize": 4294967296,
      "GlobalMemSizeGB": 4,
      "MaxComputeUnits": 40,
      "PlatformVersion": "OpenCL 2.1 AMD-APP (2841.19)",
      "DriverVersion": "2841.19",
      "PCIBusId": "06:00",
      "DeviceCapability": null,
      "CardId": -1
    },
    "Model": "R9200",
    "Model_Base": "R9200",
    "Model_Name": "Radeon R9 200",
    "InstanceId": "PCI\\VEN_1002&DEV_67B0&SUBSYS_93951682&REV_00\\4&246A276&0&0009",
    "CardId": -1,
    "BusId": "06:00",
    "BusId_Index": 5,
    "BusId_Mineable_Index": 4,
    "GpuGroup": "",
    "Data": {
      "AdapterId": 1,
      "Utilization": 0,
      "UtilizationMem": 0,
      "Clock": 300,
      "ClockMem": 150,
      "FanSpeed": 45,
      "Temperature": 40,
      "PowerDraw": 0.0,
      "PowerLimit": 0,
      "PowerLimitPercent": 0,
      "PowerMaxLimit": 0,
      "PowerDefaultLimit": 0,
      "Pstate": "",
      "Method": "ab"
    },
    "DataMax": {
      "Clock": 300,
      "ClockMem": 150,
      "Temperature": 40,
      "FanSpeed": 45,
      "PowerDraw": 0.0
    }
  },
  {
    "Name": "GPU#02",
    "Index": 2,
    "PlatformId": 0,
    "PlatformId_Index": 2,
    "Type_PlatformId_Index": 2,
    "Platform_Vendor": "AMD",
    "Vendor": "AMD",
    "Vendor_Name": "Advanced Micro Devices, Inc.",
    "Vendor_Index": 2,
    "Type_Vendor_Index": 2,
    "Type": "Gpu",
    "Type_Index": 2,
    "Type_Mineable_Index": 2,
    "OpenCL": {
      "DeviceIndex": 2,
      "Name": "AMD Radeon R9 200 Series",
      "Architecture": "Hawaii",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "GlobalMemSize": 4294967296,
      "GlobalMemSizeGB": 4,
      "MaxComputeUnits": 40,
      "PlatformVersion": "OpenCL 2.1 AMD-APP (2841.19)",
      "DriverVersion": "2841.19",
      "PCIBusId": "07:00",
      "DeviceCapability": null,
      "CardId": -1
    },
    "Model": "R9200",
    "Model_Base": "R9200",
    "Model_Name": "Radeon R9 200",
    "InstanceId": "PCI\\VEN_1002&DEV_67B0&SUBSYS_93951682&REV_00\\4&223A9A17&0&00E0",
    "CardId": -1,
    "BusId": "07:00",
    "BusId_Index": 6,
    "BusId_Mineable_Index": 5,
    "GpuGroup": "",
    "Data": {
      "AdapterId": 2,
      "Utilization": 0,
      "UtilizationMem": 0,
      "Clock": 300,
      "ClockMem": 150,
      "FanSpeed": 44,
      "Temperature": 38,
      "PowerDraw": 0.0,
      "PowerLimit": 0,
      "PowerLimitPercent": 0,
      "PowerMaxLimit": 0,
      "PowerDefaultLimit": 0,
      "Pstate": "",
      "Method": "ab"
    },
    "DataMax": {
      "Clock": 300,
      "ClockMem": 150,
      "Temperature": 38,
      "FanSpeed": 44,
      "PowerDraw": 0.0
    }
  },
  {
    "Name": "GPU#03",
    "Index": 3,
    "PlatformId": 0,
    "PlatformId_Index": 3,
    "Type_PlatformId_Index": 3,
    "Platform_Vendor": "AMD",
    "Vendor": "AMD",
    "Vendor_Name": "Advanced Micro Devices, Inc.",
    "Vendor_Index": 3,
    "Type_Vendor_Index": 3,
    "Type": "Gpu",
    "Type_Index": 3,
    "Type_Mineable_Index": 3,
    "OpenCL": {
      "DeviceIndex": 3,
      "Name": "AMD Radeon R9 200 Series",
      "Architecture": "Hawaii",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "GlobalMemSize": 4294967296,
      "GlobalMemSizeGB": 4,
      "MaxComputeUnits": 44,
      "PlatformVersion": "OpenCL 2.1 AMD-APP (2841.19)",
      "DriverVersion": "2841.19",
      "PCIBusId": "02:00",
      "DeviceCapability": null,
      "CardId": -1
    },
    "Model": "R9200",
    "Model_Base": "R9200",
    "Model_Name": "Radeon R9 200",
    "InstanceId": "PCI\\VEN_1002&DEV_67B0&SUBSYS_93951682&REV_00\\4&BC64714&0&00E2",
    "CardId": -1,
    "BusId": "02:00",
    "BusId_Index": 2,
    "BusId_Mineable_Index": 1,
    "GpuGroup": "",
    "Data": {
      "AdapterId": 3,
      "Utilization": 0,
      "UtilizationMem": 0,
      "Clock": 300,
      "ClockMem": 150,
      "FanSpeed": 43,
      "Temperature": 37,
      "PowerDraw": 0.0,
      "PowerLimit": 0,
      "PowerLimitPercent": 0,
      "PowerMaxLimit": 0,
      "PowerDefaultLimit": 0,
      "Pstate": "",
      "Method": "ab"
    },
    "DataMax": {
      "Clock": 300,
      "ClockMem": 150,
      "Temperature": 37,
      "FanSpeed": 43,
      "PowerDraw": 0.0
    }
  },
  {
    "Name": "GPU#04",
    "Index": 4,
    "PlatformId": 0,
    "PlatformId_Index": 4,
    "Type_PlatformId_Index": 4,
    "Platform_Vendor": "AMD",
    "Vendor": "AMD",
    "Vendor_Name": "Advanced Micro Devices, Inc.",
    "Vendor_Index": 4,
    "Type_Vendor_Index": 4,
    "Type": "Gpu",
    "Type_Index": 4,
    "Type_Mineable_Index": 4,
    "OpenCL": {
      "DeviceIndex": 4,
      "Name": "AMD Radeon R9 200 Series",
      "Architecture": "Hawaii",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "GlobalMemSize": 4294967296,
      "GlobalMemSizeGB": 4,
      "MaxComputeUnits": 44,
      "PlatformVersion": "OpenCL 2.1 AMD-APP (2841.19)",
      "DriverVersion": "2841.19",
      "PCIBusId": "05:00",
      "DeviceCapability": null,
      "CardId": -1
    },
    "Model": "R9200",
    "Model_Base": "R9200",
    "Model_Name": "Radeon R9 200",
    "InstanceId": "PCI\\VEN_1002&DEV_67B1&SUBSYS_93951682&REV_00\\4&3D1194C&0&00E3",
    "CardId": -1,
    "BusId": "05:00",
    "BusId_Index": 4,
    "BusId_Mineable_Index": 3,
    "GpuGroup": "",
    "Data": {
      "AdapterId": 4,
      "Utilization": 0,
      "UtilizationMem": 0,
      "Clock": 300,
      "ClockMem": 150,
      "FanSpeed": 44,
      "Temperature": 37,
      "PowerDraw": 0.0,
      "PowerLimit": 0,
      "PowerLimitPercent": 0,
      "PowerMaxLimit": 0,
      "PowerDefaultLimit": 0,
      "Pstate": "",
      "Method": "ab"
    },
    "DataMax": {
      "Clock": 300,
      "ClockMem": 150,
      "Temperature": 37,
      "FanSpeed": 44,
      "PowerDraw": 0.0
    }
  },
  {
    "Name": "GPU#05",
    "Index": 5,
    "PlatformId": 0,
    "PlatformId_Index": 5,
    "Type_PlatformId_Index": 5,
    "Platform_Vendor": "AMD",
    "Vendor": "AMD",
    "Vendor_Name": "Advanced Micro Devices, Inc.",
    "Vendor_Index": 5,
    "Type_Vendor_Index": 5,
    "Type": "Gpu",
    "Type_Index": 5,
    "Type_Mineable_Index": 5,
    "OpenCL": {
      "DeviceIndex": 5,
      "Name": "AMD Radeon R9 200 Series",
      "Architecture": "Hawaii",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "GlobalMemSize": 4294967296,
      "GlobalMemSizeGB": 4,
      "MaxComputeUnits": 44,
      "PlatformVersion": "OpenCL 2.1 AMD-APP (2841.19)",
      "DriverVersion": "2841.19",
      "PCIBusId": "03:00",
      "DeviceCapability": null,
      "CardId": -1
    },
    "Model": "R9200",
    "Model_Base": "R9200",
    "Model_Name": "Radeon R9 200",
    "InstanceId": "PCI\\VEN_1002&DEV_67B1&SUBSYS_93951682&REV_00\\4&39C7283F&0&00E4",
    "CardId": -1,
    "BusId": "03:00",
    "BusId_Index": 3,
    "BusId_Mineable_Index": 2,
    "GpuGroup": "",
    "Data": {
      "AdapterId": 5,
      "Utilization": 0,
      "UtilizationMem": 0,
      "Clock": 300,
      "ClockMem": 150,
      "FanSpeed": 42,
      "Temperature": 35,
      "PowerDraw": 0.0,
      "PowerLimit": 0,
      "PowerLimitPercent": 0,
      "PowerMaxLimit": 0,
      "PowerDefaultLimit": 0,
      "Pstate": "",
      "Method": "ab"
    },
    "DataMax": {
      "Clock": 300,
      "ClockMem": 150,
      "Temperature": 35,
      "FanSpeed": 42,
      "PowerDraw": 0.0
    }
  },
  {
    "Name": "GPU#06",
    "Index": 6,
    "PlatformId": 1,
    "PlatformId_Index": 1,
    "Type_PlatformId_Index": 0,
    "Platform_Vendor": "INTEL",
    "Vendor": "INTEL",
    "Vendor_Name": "Intel(R) Corporation",
    "Vendor_Index": 1,
    "Type_Vendor_Index": 0,
    "Type": "Gpu",
    "Type_Index": 6,
    "Type_Mineable_Index": 6,
    "OpenCL": {
      "DeviceIndex": 1,
      "Name": "Intel(R) HD Graphics",
      "Architecture": "Intel(R) HD Graphics",
      "Type": "Gpu",
      "Vendor": "Intel(R) Corporation",
      "GlobalMemSize": 1494849946,
      "GlobalMemSizeGB": 1,
      "MaxComputeUnits": 6,
      "PlatformVersion": "OpenCL 1.2 ",
      "DriverVersion": "10.18.10.4252",
      "PCIBusId": null,
      "DeviceCapability": null,
      "CardId": -1
    },
    "Model": "HDGraphics",
    "Model_Base": "HDGraphics",
    "Model_Name": "Intel HD Graphics",
    "InstanceId": "PCI\\VEN_8086&DEV_0152&SUBSYS_21111462&REV_09\\3&11583659&0&10",
    "CardId": -1,
    "BusId": "00:02",
    "BusId_Index": 0,
    "BusId_Mineable_Index": 0,
    "GpuGroup": "",
    "Data": {
      "AdapterId": 0,
      "Utilization": 0,
      "UtilizationMem": 0,
      "Clock": 0,
      "ClockMem": 0,
      "FanSpeed": 0,
      "Temperature": 0,
      "PowerDraw": 0,
      "PowerLimit": 0,
      "PowerLimitPercent": 0,
      "PowerMaxLimit": 0,
      "PowerDefaultLimit": 0,
      "Pstate": "",
      "Method": ""
    },
    "DataMax": {
      "Clock": 0,
      "ClockMem": 0,
      "Temperature": 0,
      "FanSpeed": 0,
      "PowerDraw": 0
    }
  },
  {
    "Name": "CPU#00",
    "Index": 7,
    "Vendor": "INTEL",
    "Vendor_Name": "GenuineIntel",
    "Type_PlatformId_Index": 0,
    "Type_Vendor_Index": 0,
    "Type": "Cpu",
    "Type_Index": 0,
    "Type_Mineable_Index": 0,
    "Model": "CPU",
    "Model_Base": "CPU",
    "Model_Name": "Intel(R) Celeron(R) CPU G1620 @ 2.70GHz",
    "Features": [
      "sse",
      "sse3",
      "sse41",
      "mmx",
      "sse2",
      "sse42",
      "x64",
      "ssse3"
    ],
    "Data": {
      "Cores": 2,
      "Threads": 2,
      "CacheL3": 2048,
      "Clock": 0,
      "Utilization": 0,
      "PowerDraw": 0,
      "Temperature": 0,
      "Method": ""
    },
    "DataMax": {
      "Clock": 0,
      "Utilization": 0,
      "PowerDraw": 0,
      "Temperature": 0
    }
  }
]

**Comment by jch9678** [comment]
It looks like 4.6.9.8 has fixed one of the problems, all the cards now mine and benchmark.  I'm still having the other problem, Verthash doesn't show up in the profitability list and so is never chosen.  Take a look at this line from BestPools.html

![Capture](https://user-images.githubusercontent.com/12422346/110066833-fca0c500-7d37-11eb-95e9-200752d7b828.PNG)

The pool is not updating.  It was last updated 32 days ago.

**Comment by jch9678** [comment]
@RainbowMiner just wondering if you've had a chance to take a look at this issue

**Comment by RainbowMiner** [comment]
Not yet, sorry. I will.look into what is going on with MPH today.

**Comment by jch9678** [comment]
Thank you.  I know you're busy.  I think it's been happening since vertcoin changed algos.  I have this issue on several machines.
