### ISSUE TITLE
Question - Server Communication per docs

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1453]
In the documentation, it mentions this:

"_All pool API communication will then be managed by the server: no more being blocked by the pools due to excessive use of their API_"

Does this mean the server will handle all traffic (in server mode) to and from the mining pool, and the clients never directly talk to the pool?  If so, is there a way to submit it to the pool as one large worker instead of multiple via the server?

**Comment by RainbowMiner** [comment]
It is not a miner proxy, currently. The Server concentrates all API calls (price, currencies, balances, etc.), only.
