### ISSUE TITLE
Question - RBM Mining Fee

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1454]
There are pool fees, miner fees, but... are there any RBM miner fees for using RBM?  I've been using RBM for months, just curious if our miners are redirecting for a period of time.

If not, I wouldn't mind checking a box to offset some of my miners to pay for your work (if possible).

**Comment by RainbowMiner** [comment]
My donation fee can be defined with parameter "Donate" in config.txt. It is minutes per day.
