### ISSUE TITLE
Zergpoolcoins not working correctly

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1456]
Please can you look at my attempt to use zerg support on discord? I'm not sure it's correct but either way something is not working....

![image](https://user-images.githubusercontent.com/42582444/109410524-433a9c00-7993-11eb-933f-5aead9cac9c7.png)

**Comment by RainbowMiner** [comment]
Could you upload a Debug file, please? The command line looks normal.

**Comment by acos0874** [comment]
[debug_2021-02-28.zip](https://github.com/RainbowMiner/RainbowMiner/files/6056618/debug_2021-02-28.zip)

It's mining something else now, but localhost did say it was mining LTZ, however when I went to zergpool it was mining 0cash, so I think it's a zergpool issue.

**Comment by RainbowMiner** [comment]
Yes, most probably, but I better have a look. If it's a ZergPool issue, I will temp. disable that one coin there.

**Comment by RainbowMiner** [comment]
Actually, I have found a possible glitch - miniZ has changed the way, it handles passwords with it's recent miner update. I'll try out on Zergpool, if I can provoke that problem.

**Comment by RainbowMiner** [comment]
It looks pretty much like a ZergPool issue. My tests showed, that it works now. So maybe they have solved the issue.
