### ISSUE TITLE
Ethminer binary

### ISSUE THREAD

**Issue by Sweepi** [RainbowMiner/RainbowMiner#1457]
Hi,

I was looking for  a Cuda 11 version of ethminer and found your binary, which works flawlessly. Did you build it yourself?
The ReadMe of https://github.com/RainbowMiner/miner-binaries/ says:

> Releases of miners. All releases are the unmodified zip files from their original source, hosted here to allow for automated downloading.

Unfortunately, I am unable to find the original source for ethminer v0.19.0-18 + Cuda 11.2 (and Visual Studio 2019)
- https://github.com/ethereum-mining/ethminer/ builds include only up to Cuda 10.0.
- The latest experimental build was for Cuda 11.1,  ethminer v0.19.0-17 (https://ci.appveyor.com/project/ethereum-mining/ethminer/builds/37485839/job/6m6ubwvqv03cs12i/artifacts)

Can you help me out?

**Comment by RainbowMiner** [comment]
Yes, I have build it myself with the most current upstream (the one, CUDA 10 has been build of).

**Comment by Sweepi** [comment]
Thanks!
