### ISSUE TITLE
What to mine values

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1459]
Is there a way to force the profitability figures drawn from what to mine to use current difficulty values instead of 24 hour values?

Estimate in RBM for octopus
![image](https://user-images.githubusercontent.com/42582444/109476453-da285680-7a6e-11eb-99a9-a368ea8662cf.png)

Estimate for 1gh on wtm using 24 hour difficulty
![image](https://user-images.githubusercontent.com/42582444/109476504-e8767280-7a6e-11eb-9808-9c8e36bbd50d.png)

Estimate for 1gh on wtm using current difficulty which has risen significantly
![image](https://user-images.githubusercontent.com/42582444/109476642-0ba12200-7a6f-11eb-827e-0003512d1d5b.png)

**Comment by RainbowMiner** [comment]
Wow, that is extreme. I will add a setting for that asap.

**Comment by acos0874** [comment]
Rbm can calculate 24 hour averages anyway. So wouldn't it be better to just use current difficulty and let rbm do the rest?

**Comment by RainbowMiner** [comment]
That is a bit more complicated, because different algorithms need different calculations. We just had that problem with RVN on HeroMiners. It turned out, it has a non-standard diff calculation forumla. What we could do, actually, we could react on d/dt of the difficulty and switch the moving averages.

**Comment by acos0874** [comment]
Hi did this get implemented? I intend to start using ethermine but just wanted to check it's using live prices and not 24 hour average.

**Comment by acos0874** [comment]
Actually I just saw the commit

`  "WhatToMine": {
    "Worker": "$WorkerName",
    "Penalty": "0",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "0",
    "CoinSymbolPBM": "",
    "DataWindow": "",
    "StatAverage": "live",
    "StatAverageStable": "live",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "",
    "MaxAllowedLuck": "",
    "MaxTimeSinceLastBlock": "",
    "Region": ""`

I don't have whattomine set as a pool but will this affect ethermine correctly?

**Comment by acos0874** [comment]
I've just tested this. As far as I can see it is using current difficulty but I suspect it might still be using 24 hour block rewards
![image](https://user-images.githubusercontent.com/42582444/111771098-2a8f1900-88a3-11eb-87bc-d1cb1fa4ac1f.png)

vs

![image](https://user-images.githubusercontent.com/42582444/111771139-38449e80-88a3-11eb-94cf-98b27a2b0b93.png)

**Comment by RainbowMiner** [comment]
RainbowMiner uses the WTM home page calculator over the coin calculators. So if the coin is found on the frontpage, it uses the values for "Current Difficulty" on this page. For all other coins it uses the coin calculators (I have fixed the difficulty)
