### ISSUE TITLE
XVG wallet not working again

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#146]
Starting up v3.8.6.12! Please wait..

Transcript started, output file is .\Logs\RainbowMiner_2018-09-12_15-52-06.txt
Detecting devices ..
Initialize configuration ..
Write-Log : Could not create C:\Users\JP\Desktop\RainbowMiner-master\RainbowMiner-master\Config\pools.config.txt
At C:\Users\JP\Desktop\RainbowMiner-master\RainbowMiner-master\Include.psm1:2477 char:13
+             Write-Log -Level Error "Could not create $($PathToFile) "
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

Start afterburner library ..
Read configuration ..
WARNING: Pool Balance API (BlockMasters) for Count returned nothing.
WARNING: Pool Balance API (BlockMasters) for IsFixedSize returned nothing.
WARNING: Pool Balance API (BlockMasters) for IsReadOnly returned nothing.
WARNING: Pool Balance API (BlockMasters) for IsSynchronized returned nothing.
WARNING: Pool Balance API (BlockMasters) for Length returned nothing.
WARNING: Pool Balance API (BlockMasters) for LongLength returned nothing.
WARNING: Pool Balance API (BlockMasters) for Rank returned nothing.
WARNING: Pool Balance API (BlockMasters) for SyncRoot returned nothing.
WARNING: No pools available.
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2374697/config.txt)
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2374698/pools.config.txt)

**Comment by RainbowMiner** [comment]
Edit your pools.config.txt:
`   "XVG: "DLUr2gaJbSks5JgyZDi1psrrSzhKtyq5YA",`

You are missing the closing " after XVG

like that:
`   "XVG": "DLUr2gaJbSks5JgyZDi1psrrSzhKtyq5YA",`

**Comment by RainbowMiner** [comment]
In the comeing release, I integrated additional warnings, so that you can easily find out, what's happening.

**Comment by rinkal26783** [comment]
It is not working even after writing this 
"XVG": "DLUr2gaJbSks5JgyZDi1psrrSzhKtyq5YA",
![image](https://user-images.githubusercontent.com/30832110/45424214-739efa80-b6b3-11e8-99d8-e6745170bf36.png)

**Comment by RainbowMiner** [comment]
There is still another json error in your file. I will check the whole file for you. Just a second.

**Comment by RainbowMiner** [comment]
Try this pools.config.txt:
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2375264/pools.config.txt)

**Comment by hernandn01** [comment]
Copy and paste you json file here, it will point out where is the error if any
http://json.parser.online.fr/

**Comment by rinkal26783** [comment]
error is gone after updating new pools.config.txt provided by you. but now its only mining 1 currency from zergpoolcoins only.
I want to mine all algos from zergpoolcoins and blockmasterscoins and received payout in XVG wallet.

**Comment by rinkal26783** [comment]
![image](https://user-images.githubusercontent.com/30832110/45428081-13fa1c80-b6be-11e8-8f56-fb0c7191f615.png)

[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2375300/config.txt)
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2375301/pools.config.txt)
[RainbowMiner_2018-09-12_18-41-29.txt](https://github.com/RainbowMiner/RainbowMiner/files/2375305/RainbowMiner_2018-09-12_18-41-29.txt)
[RainbowMiner_2018-09-12_18-44-20.txt](https://github.com/RainbowMiner/RainbowMiner/files/2375306/RainbowMiner_2018-09-12_18-44-20.txt)
[RainbowMiner_2018-09-12_18-46-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/2375308/RainbowMiner_2018-09-12_18-46-26.txt)

**Comment by RainbowMiner** [comment]
> I want to mine all algos from zergpoolcoins and blockmasterscoins and received payout in XVG wallet.

I understand. Looks like, I have forgotten to add the pools.config.txt wallets to both of them, I just updated the pool files:
Download and save them into your Pools directory
https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/BlockMastersCoins.ps1
https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/ZergPoolCoins.ps1

(right-click, save as..)

**Comment by RainbowMiner** [comment]
And: blockmaster's currency API is down since some days now. Therefor, BlockMastersCoins will not work, at the moment.

**Comment by RainbowMiner** [comment]
Also, you might consider using BlockMasters & ZergPool (not the *Coins variants) by removing BTC wallet from pools.config.txt and leaving XVG, only. 
Like that:
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2375763/pools.config.txt)

**Comment by rinkal26783** [comment]
Thanks for the help. Its working now.

**Comment by RainbowMiner** [comment]
Duh! Very good 😄
