### ISSUE TITLE
Error with WoolyPooly and NBMiner

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1460]
I'm getting this with NBMiner

![image](https://user-images.githubusercontent.com/42582444/109655160-dc67df00-7b5a-11eb-8964-2fb2c7d63dc1.png)

Address and everything else works fine with trexgtx though.

**Comment by RainbowMiner** [comment]
Most likely due to the "cfx:" in the wallet address. Is this something, the NBminer fiddled into, or is this your wallet setup? I thought, the CFX wallets start with "0x"

**Comment by acos0874** [comment]
I checked in the CFX discord and they said put the cfx bit at the start. It's working fine with my mining rigs...

-N 10 -r 5 --api-bind-http 127.0.0.1:$mport -d 0,1,2 -a octopus -o stratum+tcp://cfx.woolypooly.com:3094 -u cfx:aapxfnn9c4vkt9cehurfhyhk9xws3ez22a77mv8n10.cynthia -w cynthia -p x --no-watchdog -b 0"

I just had trexgtx disabled on my gaming PC so it defaulted to nbminer instead.

**Comment by RainbowMiner** [comment]
NBminer cannot handle the ":" - it thinks, everything to the left is the wallet, everything to the right of it is the password. I'll write an issue at NBminer's github. I have disabled NBminer for wallets, that include a ":"

**Comment by acos0874** [comment]
Thanks. I'm just using trexgtx now cos its faster anyway.
