### ISSUE TITLE
ExcludeFromWatchdog not work

### ISSUE THREAD

**Issue by Antoninich** [RainbowMiner/RainbowMiner#1462]
Hi. "ExcludeFromWatchdog" in config.txt not work and not found in the code RainbowMiner.

**Comment by RainbowMiner** [comment]
Oh. It looks like you have found a started-but-not-finished mummy.
I'll add some functionality.

**Comment by Antoninich** [comment]
Please. I really need this functionality.

**Comment by RainbowMiner** [comment]
There. That should do the job.
- add parameter "ExcludeFromWatchdog" to config.txt: add miners, pools or algorithms that should be excluded from the Watchdog (beware: algorithms will not be parsed, so use the correct RainbowMiner names)
