### ISSUE TITLE
How to configure Sparkpool with RBM?

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1463]
Hi, anyone knows how to mine with Sparkpool with RBM? I enabled it in settings but not sure where to put the details.
Appreciate if someone can help me with this.

**Comment by RainbowMiner** [comment]
Open `.\Config\pools.config.txt` with a text editor, find section `"SparkPool"`. You will find some coin symbols. Most probably
```
  "ETH": "",
  "GRIN": "",
  "BEAM": "",
  "XMR": "",
```

.. these were the available coins some months ago. Nowadays Sparkpool has coins ETH, CKB and BEAM (no more GRIN nor XMR).

So, if you want to mine ETH or BEAM, you are good. Just put your SparkPool subaccount name (something like sp_xyz) into the coin's parameter. If you want to mine CKB, just rename one of the other two (e.g. GRIN -> CKB) and enter your subaccount name. You can safely remove the unused currency's GRIN/XMR lines.

Your pools.config.txt could now look like that, for example:
```
  "ETH": "sp_xyz",
  "CKB": "sp_xyz",
  "BEAM": "",
```

**Comment by astronyu** [comment]
`  "SparkPool": {
    "ETH": "",
    "ETH-Params": "",
    "GRIN": "",
    "GRIN-Params": "",
    "BEAM": "",
    "BEAM-Params": "",
    "XMR": "",
    "XMR-Params": "",`
So, I should put my subaccount name into "ETH": "", and not the "ETH-Params": "", if based on your example above?

**Comment by RainbowMiner** [comment]
Exactly. Whatever you put into the `"ETH-Params": "",` parameter will be comma appended to your password. It's most of the time to set some static difficulty, like `"d=100",` for some pools.

**Comment by astronyu** [comment]
@RainbowMiner , thank you for the explanation.

Also while we're at it, may I ask if it is the same for WoolyPooly? I created an account with them so able to use 1 email for any coins listed there. Should I just put an email in the config? or use the address as shown on the site in "how to connect" popup?
