### ISSUE TITLE
Benchmarking keeps on crashing

### ISSUE THREAD

**Issue by 33Fraise33** [RainbowMiner/RainbowMiner#1464]
Hello,

I'm seeing an issue with the initial run of Rainbowminer. I installed al the required software but I am getting errors at the end of each benchmark run.

This is what I'm seeing:
![image](https://user-images.githubusercontent.com/6802744/110006160-99079f00-7d19-11eb-9fd6-f88a98994ab7.png)

Uploaded are my gpu test and devices.json
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/6085648/gputestresult.txt)
[devices.txt](https://github.com/RainbowMiner/RainbowMiner/files/6085650/devices.txt)

**Comment by 33Fraise33** [comment]
The download issue is related to pihole blocking the domain apparently, I whitelisted it. 

The Powerdraw error is still there though

**Comment by 33Fraise33** [comment]
The monitoring website reports that I'm experiencing crashing, where do I check the logs or reason behind this?
`Crashing (16 cph)`

**Comment by RainbowMiner** [comment]
Hi, look into the Logs folder - you will find your miner's logs and RainbowMiner*.txt log files, as well. Which miner is crashing?

**Comment by jeremyhammon** [comment]
I have been seeing that power draw issue as well lately.  I was waiting to see if it had anything to do with AMD card stats that I was working with

**Comment by 33Fraise33** [comment]
I will close this issue as I am no longer using this software.
