### ISSUE TITLE
Question (Documentation) - Watchdog

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1465]
There's not much information on what the Watchdog does, and am curious how it works.  Does it watch hashrate?  hashrate over time? heat? uptime? failed miners?  Just various settings that we've set through the config?

From our perspective, we just see... enable/disable, and a Watchdog menu item but not much more info.

**Comment by RainbowMiner** [comment]
Sorry, missed your question due to heavy workload. Could you find an answer?

**Comment by RainbowMiner** [comment]
> Does it watch hashrate? hashrate over time? heat? uptime? failed miners? Just various settings that we've set through the config?

It checks for hashrate plus the ratio of accepted to rejected shares and detects crashes of the miners.

**Comment by saki2fifty** [comment]
I know you're busy, and didn't want to clog the issues with petty questions... hence why I closed these out.

Thanks for the answers!
