### ISSUE TITLE
Question (Documentation) - MinerHeatControl

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1466]
I'm in Texas, and summer heat is brutal.  As I started using RBM a few months ago, I didn't care much about heat because our temps were good.  But now, it's going to get much warmer / hotter.

I'm trying to understand the logic behind the heat control (profit vs. heat), trying to use the calculation in the docs but still not getting it.

- If all I care about is my temps never exceeding 70c, would HeatControl play into this? (This is my only care: never exceed a certain temp)
- Throughout the configs, I can set MaxTemp to some number, but is this more to alert us of the temp, or does it actually control the temp?  (stop using the gpu until so many degrees below the target temp, and start mining again)

**Comment by RainbowMiner** [comment]
Sorry, missed your question due to heavy workload. Could you find an answer?

**Comment by RainbowMiner** [comment]
> If all I care about is my temps never exceeding 70c, would HeatControl play into this? (This is my only care: never exceed a certain temp)

Actually, no. The HeatMyFlat option changes how the  Hash per Watt values will sort the miners. With that you can change the efficiency of your rig to your needs: from max. profit with max. Watt to max. profit with min. Watt

> Throughout the configs, I can set MaxTemp to some number, but is this more to alert us of the temp, or does it actually control the temp? (stop using the gpu until so many degrees below the target temp, and start mining again)

If you choose to monitor your rig, using https://rbminer.de/monitoring - rbminer.net will send you an eMail and/or a Pushover message to your mobile phone, if a GPU reaches that temperature. We currently have no automatic on/off in case the GPUs reach a critical temperature. If on Windows, try MSI Afterburner for that - you can set a max. temperature. It will adjust you GPU clocks, if the temperature gets too high. That's pretty convenient.

**Comment by saki2fifty** [comment]
I know you're busy, and didn't want to clog the issues with petty questions... hence why I closed these out.

Thanks for the answers!
