### ISSUE TITLE
Excluded device still being included.....

### ISSUE THREAD

**Issue by mcangeli** [RainbowMiner/RainbowMiner#1468]
I've combined a GTX1060 and a GTX1080 card in to one machine. The 1060 is working well, the 1080 works ok however there is an odd occurance.

the devices are being displayed a total of 4 times. 
![image](https://user-images.githubusercontent.com/6456272/110212959-daa85f00-7e6b-11eb-9f3a-080073c87237.png)
I can exclude the GPU02 and it works, but if I have the GPU03 also selected to get rid of the second instance of the 1080, it does not seem to exclude it.

It is listed in the exclude config file as well.
But it still shows up in my Selected devices list.
![image](https://user-images.githubusercontent.com/6456272/110212985-09263a00-7e6c-11eb-8c13-2411126c1ad4.png)

**Comment by RainbowMiner** [comment]
This is odd. It's most probably an OpenCL/Nvidia driver issue. Could you please do the following:
- run `GPUTest.bat` (linux: `gputest.sh`) and upload the resulting `gputestresult.txt` file here. 
- open a `cmd` (linux: command shell), now change directory to your RainbowMiner folder
- enter `cd Bin\GPU-Gminer` (linux: `cd Bin/GPU-Gminer`)
- enter `miner --list_devices` (linux: `./miner --list_devices`)
- now upload the device list

Question: is this a Linux or Windows machine?

**Comment by mcangeli** [comment]
Its a windows machine. I'll run those when I get back home in a bit.

Thanks!

**Comment by mcangeli** [comment]
c:\RainbowMiner\Bin\GPU-Gminer>miner.exe --list_devices
GPU0: PNY GeForce GTX 1060 6GB  PCI: 0000:01:00.0
GPU1: ASUS GeForce GTX 1080 8GB PCI: 0000:03:00.0

[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/6095835/gputestresult.txt)
[devices.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/6095837/devices.config.txt)

**Comment by mcangeli** [comment]
When I start it: Detecting devices .. 1 CPU, 4 Nvidia, 1 Intel found

And I even removed the original directory and downloaded a clean install.

**Comment by mcangeli** [comment]
It seems to be an issue if I select the name (GTX1080, GTX1060). If I select the individual GPU (GPU00, GPU00) it works ok and is stable at that point.

I did think it was odd though that it only seemed to pick up on one of the two excluded devices.

**Comment by RainbowMiner** [comment]
It still is odd - it seems to be a rare condition with some Nvidia driver installs, that cause two Nvidia OpenCL platforms (but with only one valid set of GPUs).

**Comment by mcangeli** [comment]
I think this affecting some of the miners and being able to bench mark them as well. In several log files I am seeing:
invalid device index: 2
(and its on miners that I know work with the GPU or show ok on the 1060 but not the 1080, which is odd).

**Comment by RainbowMiner** [comment]
I still cannot put my finger onto that. Could you please create a Debug file on that one rig with the 1060 + 1080? I hope to find some hint there.

**Comment by mcangeli** [comment]
Hope this is right... 
[debug_2021-03-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/6130489/debug_2021-03-12.zip)

And yes, this box *had* an amd device in it, I've currently moved it to a different box so I could run the two nvidia cards together. I may be adding it back once I get a pcie splitter so I can have another riser in there.

**Comment by mcangeli** [comment]
Ok, I updated my install and I also used DDU to remove the amd drivers from this system and rebooted it and now I only have the correct number of Devices!!

Thank you!!

I have to say, this is an amazing bit of software....

**Comment by RainbowMiner** [comment]
Thank you!
