### ISSUE TITLE
Phoenix need remove!

### ISSUE THREAD

**Issue by toshkov02** [RainbowMiner/RainbowMiner#1469]
https://www.nicehash.com/blog/post/stop-using-phoenix-miner-immediately

> It has come to our attention that Phoenix miner is no longer available for download from its original download location. Control shasum from new download locations does not match the value published by the developer on his channel! This brings the possibility that the Phoenix miner's author wants to cover its tracks and disappear or even do something malicious.

> We have immediately disabled Phoenix miner from NiceHash Miner, and we advise everyone to stop using Phoenix miner immediately!

> Phoenix miner is a mining software from an anonymous author. It is not digitally signed, and no one knows who the creator is. This brings serious risk to anyone who will continue to use this software! Do not try to download Phoenix miner from any 3rd party source since it could be fake and malicious! 

> If you have used PhoenixMiner on your PC, which contains any sensitive information or information of any value such as logins to various services (accesses to bank accounts, PayPal, Gmail, Facebook, Instagram, Dropbox, Google Drive, etc. ) and especially if your PC contains any private keys for any cryptocurrency wallet, directly or indirectly (through online wallet provider) consider them compromised.

**Comment by RainbowMiner** [comment]
Thank you! I will temporarily disable the miner, until this is clarified.

**Comment by RainbowMiner** [comment]
Here is some more discussion about that Nicehash press release. Since they base their assumption on the one fact, that the Mega account of the developer has been disabled, it might concern downloads from random other sources, only (there have been multiple tries of newbies on bitcointalk.de, to trick miners into an obvious malicious fake 5.5d version of Phoenix miner).
I'll hack into Phoenix and do some analysis.

**Comment by RainbowMiner** [comment]
[PhoenixMiner has been banned from MEGA and is now on Github](https://bitcointalk.org/index.php?topic=2647654.msg56514824#msg56514824)
