### ISSUE TITLE
Gminer had an issue where the hash rate reduced 33% to 20 or so MH

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1470]
Gminer had an issue where the hash rate reduced 33% to 20 or so MH

This happened about 11 hours ago.  Re-benchmarked Trex 11hr ago to get it to use something else, why didn't RBM switch to the better miner when hashrate was reduced on Gminer? 

Just now I re-benchmarked Gminer and it is back up to the 31.xx MH for a 1660Super.

Thanks.
[debug_2021-03-07.zip](https://github.com/RainbowMiner/RainbowMiner/files/6097772/debug_2021-03-07.zip)

**Comment by RainbowMiner** [comment]
I will check this.

**Comment by paulpoco** [comment]
@RainbowMiner ignore my Daughter was using her PC with the 1660Super and didn't Pause.

**Comment by RainbowMiner** [comment]
Ok :)
