### ISSUE TITLE
Linux: AMD GPU stats missing

### ISSUE THREAD

**Issue by mgbowe1** [RainbowMiner/RainbowMiner#1477]
Current setup:
NVIDIA RTX 2070 Super (all hardware stats available: Temperature, power usage, etc.)
AMD Radeon Pro WX7100 (no hardware stats available)

![RBMiner_NoAMDGPU_Stats](https://user-images.githubusercontent.com/14890220/110529407-3d595f00-80e7-11eb-867e-468715b50d90.png)

*Note:* I can get power usage and temperature info from the `sensors` command, the relevant output is below:
```
amdgpu-pci-0b00
Adapter: PCI adapter
vddgfx:      993.00 mV
fan1:        3593 RPM  (min =  700 RPM, max = 4500 RPM)
edge:         +87.0°C  (crit = +99.0°C, hyst = -273.1°C)
power1:       81.00 W  (cap =  95.00 W)
```
The sensors command does not seem to have NVIDIA GPU stats, so I can totally understand why they aren't both working. I'm a bit curious how the NVIDIA stats are reported, but seeing as they're the ones that are working, I'm worried about it at all.

**Comment by RainbowMiner** [comment]
The Nvidia stats are read from nvidia-smi - the AMD stats are available only, if rocm-smi is installed. Using the sensors command is actually a very good idea. I will try to integrate it.

**Comment by mgbowe1** [comment]
Thanks, I'll update the documentation with a list of dependencies and submit a pull request. Installing rocm-smi fixed my issue
