### ISSUE TITLE
Excluded GPU - Missing stats (Selected Devices)

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1478]
I have a failing GPU, so I have excluded it.

If I exclude the device, then all stats after the failing gpu is blank:
![Excluded](https://user-images.githubusercontent.com/2228638/110539876-67ad1b80-80eb-11eb-8bf5-9c48b83cd189.PNG)

If I include the gpu, then all stats for all devices are displayed:
![Included](https://user-images.githubusercontent.com/2228638/110540031-9925e700-80eb-11eb-94ee-6d433c43dc9e.PNG)

**Comment by saki2fifty** [comment]
Ubuntu 18.04.

[gputestresult (2).txt](https://github.com/RainbowMiner/RainbowMiner/files/6111521/gputestresult.2.txt)

**Comment by RainbowMiner** [comment]
Could you please:
- open a new command shell and enter `nvidia-smi` and report the result?
- create a Debug file and upload it here

**Comment by RainbowMiner** [comment]
Oh man. That was a dud. Solved.

**Comment by saki2fifty** [comment]
Was typing it all out... deleted when I saw your comment.

I'll check.

**Comment by saki2fifty** [comment]
Tested, this now works.  Thx.
