### ISSUE TITLE
Problem with port during setup

### ISSUE THREAD

**Issue by roguetr** [RainbowMiner/RainbowMiner#1479]
During the setup, choosing Australia and then only choosing FlexPool, the port instead of being 5555 is set to "us-east" and all tests fail.
![Screenshot 2021-03-10 165423](https://user-images.githubusercontent.com/52813338/110583409-c349d880-81c1-11eb-9969-6366e6708ec7.png)

**Comment by RainbowMiner** [comment]
Ok, done. Now the ports should be fine. Sorry!
