### ISSUE TITLE
Exclude particular coin from pool blockmasters

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#148]
I want to mine x17 but want to exclude xvg coin from blockmasters. because of high orphan rate.
Is this correct?
    "ExcludeCoin": "XVGx17",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "XVGx17"

Another thing, If i exclude xvg from x17. how it will effect on profit calculation? 
It would be good if rainbowminer show profit for rest of 3 coins (excluding xvg) from x17 algo. is it possible?

**Comment by RainbowMiner** [comment]
I will have a look. Only one Exclude should be sufficient. Either add "XVG" to ExcludeCoinSymbol (this takes the real currency and would effectively disable all XVG no matter which algorithm) or "XVGx17" to ExcludeCoin (this takes the coin name, like it is used at the pool and would disable XVG for x17 mining, only)

**Comment by RainbowMiner** [comment]
Ok, it took some time. Sorry!

I had to fix the pool files for BlockMastersCoins, Bsod and ZergPoolCoins, first.

To make this exclude to work, you need to use "ExcludeCoinSymbol": "XVGx17", only. Of course it only works for pool "BlockMastersCoins".

There is a difference between CoinSymbol/ExcludeCoinSymbol (working on the pool's coin symbols) and CoinName/ExcludeCoin (working on the pool's coin names).

Example for Blockmasterscoins:

|CoinName|CoinSymbol|Currency|Algo|
|---|---|---|---|
|Verge|XVG|XVG|scrypt|
|Verge|XVGlyra|XVG|lyra2v2|
|Verge|XVGx17|XVG|x17|
