### ISSUE TITLE
Balances other currencies on Nicehash

### ISSUE THREAD

**Issue by toshkov02** [RainbowMiner/RainbowMiner#1482]
Please, add balances other currencies on Nicehash, example XMR (API request "GET https://api2.nicehash.com/main/api/v2/accounting/account2/XMR").

**Comment by RainbowMiner** [comment]
Ok. I'll add it. Since there are a lot of wallets at NH, you will have to specify for which coins to load the values.

**Comment by RainbowMiner** [comment]
Ok, done.
- add all Nicehash wallets. Set `"EnableShowWallets": "1",` in pools.config.txt to enable

**Comment by paulpoco** [comment]
> Ok, done.
> 
> * add all Nicehash wallets. Set `"EnableShowWallets": "1",` in pools.config.txt to enable

So this will show the paid Nicehash wallet?  Right now it only shows the unpaid wallet.

**Comment by paulpoco** [comment]
@RainbowMiner updated and now Nicehash wallet doesn't show.

**Comment by RainbowMiner** [comment]
It shows all Nicehash wallets (other than the default BTC), that contain coins.

**Comment by RainbowMiner** [comment]
@paulpoco Have you supplied your Nicehash API_Key, API_Secret and OrganizationId?

Also, what kind of wallet are you using for mining? The Nicehash mining wallet address, or an external wallet address?
- if it's the first - API credentials will be needed for balance to show up
- if it's the second - the Nicehash external API is reduced. It doesn't show a lot.

**Comment by paulpoco** [comment]
> @paulpoco Have you supplied your Nicehash API_Key, API_Secret and OrganizationId?
> 
> Also, what kind of wallet are you using for mining? The Nicehash mining wallet address, or an external wallet address?
> 
> * if it's the first - API credentials will be needed for balance to show up
> * if it's the second - the Nicehash external API is reduced. It doesn't show a lot.

The internal Nicehash wallet
"API_Secret and OrganizationId"  is that supposed to be in pools.config.txt?

![Screenshot_17](https://user-images.githubusercontent.com/801414/110975599-cbfef380-8314-11eb-9e8f-52f3220d6586.png)

**Comment by RainbowMiner** [comment]
> "API_Secret and OrganizationId" is that supposed to be in pools.config.txt?

Exactly. All three credentials are provided by Nicehash. The Organization Id is the same for all API keys/secrets and can be found on page "My Settings" -> "API Keys".

pools.config.txt, section "Nicehash"
```
  "API_Key": "your-nicehash-api-key",
  "API_Secret": "your-nicehash-api-secret",
  "OrganizationID": "your-nicehash-organizationid",
```

**Comment by paulpoco** [comment]
Ok I added all 3 with new key,secret,org before I left for work and still do not see any Nicehash wallets.   Even the unpaid amount is gone for Nicehash. 

I will have to look at it again after work.

[debug_2021-03-12 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/6132752/debug_2021-03-12.1.zip)

**Comment by RainbowMiner** [comment]
> Nicehash API call: 500 Internal Server Error (Server Error)

Looks like, the Nicehash API was down. So chances are good, that the balances will show up later.

**Comment by paulpoco** [comment]
Ok when I enabled the OrganizationID my account gave me a new mining address at Nicehash, I don't want 2 accounts.

My api key & secret are to do with my personal account.

How do I get it back to showing Nicehash like it used to?  Now it shows nothing.

**Comment by RainbowMiner** [comment]
> How do I get it back to showing Nicehash like it used to? Now it shows nothing.

I will add a fix asap.

**Comment by paulpoco** [comment]
> > How do I get it back to showing Nicehash like it used to? Now it shows nothing.
> 
> I will add a fix asap.

No rush
