### ISSUE TITLE
WARNING: Stat file

### ISSUE THREAD

**Issue by minergenon** [RainbowMiner/RainbowMiner#1483]
WARNING: Stat file (SrbMinerMulti-CPU#00_RX2_HashRate) was not updated because the value 0  H is outside fault tolerance 691.64  H to 2.54 kH. 

 WARNING: Miner SrbMinerMulti-CPU#00 mining RX2 on pool ZergPool temporarily disabled.

How to deal with it.

[RainbowMiner_2021-03-12.txt](https://github.com/RainbowMiner/RainbowMiner/files/6130467/RainbowMiner_2021-03-12.txt)
[RainbowMiner_2021-03-12_17-47-54.txt](https://github.com/RainbowMiner/RainbowMiner/files/6130468/RainbowMiner_2021-03-12_17-47-54.txt)

**Comment by paulpoco** [comment]
I would just ignore as it will self correct.

**Comment by RainbowMiner** [comment]
Yes, just ignore it. It's most likely a temporary pool problem.
