### ISSUE TITLE
Ezil ZIL/ETH

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1484]
Wanted to atleast try the dual mining. Though I enabled what I need to. But its not mining it or showing up in the miner list.

What am I missing?

[debug_2021-03-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/6132123/debug_2021-03-12.zip)

**Comment by Yamanipanuchi** [comment]
I think maybe something with ZIL being enabled, Because I dont see that as a minable coin anywhere yet...

**Comment by Yamanipanuchi** [comment]
Its in my list, But has no Benchmark.

**Comment by Yamanipanuchi** [comment]
Okey, I show a Zill Balance.. So it must be working. It just doesnt show that its working... Cheers.

**Comment by RainbowMiner** [comment]
Zilliqa is quiet different from other coins. It hasn't an own algorithm, but uses Ethash. The following is taken from the FAQ on [https://ezil.me](https://ezil.me/?p=dcf9)

## What coins can I mine with the Ezil.me pool? How does mining happen?

Our pool mines ETH or ETC and ZIL simultaneously. We have the following mining scheme: most of the time, the pool is mining ETH or ETC. However, just before a ZIL mining round starts (every 1.5 hours) the pool automatically switches to ZIL. At the end of the ZIL mining round, the pool instantly switches back to ETH or ETC. From the individual miner’s perspective, no action is required. Everything happens automatically in the background, and the reward is credited and paid the same way for both coins.
