### ISSUE TITLE
Miners are crashing since latest update

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1485]
Miners are crashing since latest update.  only on one client machine.
[debug_2021-03-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/6132467/debug_2021-03-12.zip)

**Comment by RainbowMiner** [comment]
It looks like the Windows port stack is messed up. Please reboot that one machine. It should be resolved, after that.

**Comment by paulpoco** [comment]
I rebooted by turning off at the HS110 energy monitor then wait a bit and turn it back on.   I have it set to always turn on when power comes back and auto login and autostart RBM.   Seems ok now.

**Comment by paulpoco** [comment]
@RainbowMiner is this normal, after I added the org, my mining address changed
