### ISSUE TITLE
RM 4.7.0.3 | Cannot add a member with the name "Ezil" because a member with that name already exists.

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1486]
Seeing this with RM 4.7.0.3
Could be because I just updated PowerShell from 7.1.2 to 7.1.3, or could be result of RM 4.7.0.2 -> 4.7.0.3 update, or both, or neither :)

![cmd_2021-03-13_11-03-52](https://user-images.githubusercontent.com/17214552/111011113-8d3c6c80-83ec-11eb-9c51-320e36fc6f4c.jpg)
```
NVSMI installed successfully!
Initialize configuration ..

Add-Member: D:\Applications\RainbowMiner\Modules\Include.psm1:5301
Line |
5301 |                      $Done | Add-Member $Pool_Name $Setup_Content
     |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot add a member with the name "Ezil" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.

[91mAdd-Member: [0mD:\Applications\RainbowMiner\Modules\Include.psm1:5301
[96mLine |
[96m5301 | [0m                     $Done | [96mAdd-Member $Pool_Name $Setup_Content[0m
[96m     | [91m                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot add a member with the name "Ezil" because a member with that name already exists. To overwrite the member anyway,
[96m     | [91madd the Force parameter to your command.
[0m
Read configuration ..
Loading pool modules ..
```

[debug_2021-03-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/6133731/debug_2021-03-13.zip)

**Comment by RainbowMiner** [comment]
Ah! I see. I have added Ezil pool with the last release. Since you already have that pool as Userpool, the above error happens. I will add some extra checks. I would recommend, you remove Ezil from the userpools.config.txt and add $ETH and $ZIL to the Ezil pool section in pools.config.txt.

**Comment by AnthonyBe** [comment]
/facepalm

Sorry. I had completely forgotten!
I've removed it from Userpool and all good now :)
