### ISSUE TITLE
MRR pricing option

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1490]
@RainbowMiner, just want to confirm if "PriceCurrencies": "BTC", in pool config is where I can set the currency for rental? So if I want to enable all, it will be "PriceCurrencies": "BTC,LTC,BCH,DASH,ETH",?

Sorry for asking such a simple question, tried changing to those but still not showing as enabled on MRR.

**Comment by RainbowMiner** [comment]
Yes. That's right, `"BTC,BCH,ETH,LTC,DASH"` should enable all accepted currencies. They should appear at your rigs.
