### ISSUE TITLE
Mining stops - screen session hung

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1491]
This happens quite a bit, and a simple reboot fixes it.  But...

- On this rig, running in device legacy mode
- In the RBM console, its just locked.  My key commands do not work, cannot restart, update, etc.  Screen never changes, and does not loop like it typically does.  The server itself responds and is functional.
- Web console does work
- Miner "commiting suicide", but screen never closes

In the RBM console, i'm getting:
![1](https://user-images.githubusercontent.com/2228638/111073157-a6f0b900-84ab-11eb-8454-132914124b6f.PNG)

List of screens:
![2](https://user-images.githubusercontent.com/2228638/111073175-b7089880-84ab-11eb-8155-3061ee564bbe.PNG)

Miner:
![3](https://user-images.githubusercontent.com/2228638/111073186-c2f45a80-84ab-11eb-804f-48fb41f7ed44.PNG)

Nvidia-smi:
![4](https://user-images.githubusercontent.com/2228638/111073225-f20acc00-84ab-11eb-9726-5682088700a1.PNG)

[debug_2021-03-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/6136900/debug_2021-03-14.zip)

**Comment by RainbowMiner** [comment]
Thanks for reporting this!
