### ISSUE TITLE
uninstallation?

### ISSUE THREAD

**Issue by void-witch** [RainbowMiner/RainbowMiner#1492]
rainbowminer never worked for me, and i'd like to remove the systemd service it installed that continues to run every boot. unfortunately, the service isn't actually named rainbowminer. what's it named so i can remove it?

**Comment by RainbowMiner** [comment]
Oh, that is sad. The systemd service is `ocdaemon`

**Comment by void-witch** [comment]
yeah, i think my drivers are weird. great software though, thanks for the work and the answer!
