### ISSUE TITLE
Hiveon pool not working

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1493]
I'm having problem with mining on Hiveon pool. I setup the config and it seems RBM not picking it up.
Even after turning off other pools RBM started idle showing meesage "WARNING: No pools available: check your configuration"

@RainbowMiner can you help?

**Comment by astronyu** [comment]
@RainbowMiner , I tried connecting it manually using phoenix miner with config below and it works. (default was port 4444 but that port isn't working)

`@ECHO Off

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

SET POOL_URL=eu-eth.hiveon.net:14444
SET POOL_URL=aspac1-eth.hiveon.net:14444
SET POOL_URL=naw-eth.hiveon.net:14444
SET POOL_URL=ru-eth.hiveon.net:14444

SET WALLET=0x3d1d0ac316AC98Ed7aD031F6D7a48D002Afec4D7
SET WORKER_NAME=rig0

PhoenixMiner.exe -epool %POOL_URL% -ewal %WALLET%.%WORKER_NAME% -epsw x`

It seems port 4444 having issues but connected fine on port 14444. 
Which file should I change to replace the port?

**Comment by RainbowMiner** [comment]
I'll change it in the the pool module asap. Just a sec.

**Comment by astronyu** [comment]
> I'll change it in the the pool module asap. Just a sec.

Noted, thank you.

**Comment by RainbowMiner** [comment]
Done :) Just download the new [Hiveon.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/Hiveon.ps1) into your Pools folder.

**Comment by astronyu** [comment]
> Done :) Just download the new [Hiveon.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/Hiveon.ps1) into your Pools folder.

Thank you for fixing this., By the way, may I know what influence the port "Accuracy" as shown in the console and what it does? Currently showing 17%.

**Comment by RainbowMiner** [comment]
Accuracy reflects the price up and downs of the pool's API. The lower, the higher the variation. It corrects itself over time. If you have got the feeling that it is badly off, just delete the pool's stats file. For Hiveon it's `.\Stats\Pools\Hiveon_ETH_Profit.txt` (Linux: `./Stats/Pools/Hiveon_ETH_Profit.txt`)
