### ISSUE TITLE
BeePool not showing in Console anymore.  RVN.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1494]
BeePool not showing in Console anymore.  RVN.
![Screenshot_19](https://user-images.githubusercontent.com/801414/111226703-bbfa4480-859e-11eb-883b-250ffe8b49d0.png)
[debug_2021-03-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/6144747/debug_2021-03-15.zip)

**Comment by RainbowMiner** [comment]
> Error job 5AFD22DCD8979E6842600D147DE9C176 with https://www.beepool.org/detail/get_blocks using REST: Problem fetching https://www.beepool.org/detail/get_blocks using REST: 500 Internal Server Error (Server Error)

Looks like a server problem at BeePool. I will check.

**Comment by RainbowMiner** [comment]
Ok, got it. BeePool seems to newly forbid posting to their get_blocks ajax endpoint.
