### ISSUE TITLE
Just stupid problem, Discord invite doesn't work.

### ISSUE THREAD

**Issue by eskimos2000** [RainbowMiner/RainbowMiner#1495]
As in the subject. Thanks for consideration.

**Comment by RainbowMiner** [comment]
Oh dear! Thank you for reporting. I will create a new invite.

**Comment by RainbowMiner** [comment]
Here is our new, non-expiring invite:

###### **Discord: [https://discord.gg/znzQpJWWQH](https://discord.gg/znzQpJWWQH)**
[![online](https://img.shields.io/discord/513274071010508800)](https://discord.gg/znzQpJWWQH)
