### ISSUE TITLE
Adding Antpool??

### ISSUE THREAD

**Issue by mcangeli** [RainbowMiner/RainbowMiner#1497]
I've setup antpool in the userpools.txt file (I have .05 ether there that I need to get to .5 for a payout at some point) and it is enabled and setup in the pools.config file as well, but it does not appear in the "ALL POOLS" page with the other enabled pools and I cannot seem to start mining on it.

Is there a trick to getting userpools to work correctly?

**Comment by RainbowMiner** [comment]
Make sure you put "AntPool" on the "PoolName" list in config.txt (in fact, use the name, that you have given in userpools.config.txt)
If you like me to check, just upload a Debug file.

**Comment by mcangeli** [comment]
I have done that. (Well, AntpoolETH).

I've also disabled the ethermine pool. I have three pools active right now, ZERG, Miningrigrental and then AntpoolETH. 

Should I disable ZERG (its mostly the CPU that mines on ZERG).

**Comment by mcangeli** [comment]
[debug_2021-03-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/6156983/debug_2021-03-17.zip)

I removed ZERG and the only pool are my antpooleth and the miningrigrental...

**Comment by RainbowMiner** [comment]
It looks like your userpools.config.txt is either empty or contains a JSON error. Could you please upload it?

**Comment by mcangeli** [comment]
[userpools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/6157169/userpools.config.txt)

**Comment by mcangeli** [comment]
I set it on my server and set my clients to pull the userpools config file (which they do).

**Comment by mcangeli** [comment]
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/6157353/pools.config.txt)

And because you may ask for it next... here is my pools.config file.

**Comment by RainbowMiner** [comment]
Actually, it may sound weird, but could you please upload the scheduler.config.txt file, too?

**Comment by mcangeli** [comment]
[scheduler.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/6157409/scheduler.config.txt)

**Comment by RainbowMiner** [comment]
Thank you. Yes, just, what I thought. Those file formats are old style JSON arrays. Strange. Maybe it is a backwards compat issue with the old PowerShell 5 version (that's your current version). I'll try on my test machine.
Normally, those two files should look (and autocorrect to) like that:

[scheduler.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/6157491/scheduler.config.txt)
[userpools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/6157492/userpools.config.txt)

Could you please try the following?
- stop RainbowMiner
- replace your config files with the files above
- start RainbowMiner
- check, if the files have been altered to the wrong format again

**Comment by mcangeli** [comment]
it looks like they are still the new format (I compared the file you sent to the file in the config folder after 10 minutes)
but the pool is still not showing in my ALL POOLS page

**Comment by mcangeli** [comment]
it looks like the userpool one is ok. The Scheduler one is not.

**Comment by RainbowMiner** [comment]
I have added some backwards compatibility tweaks to the core. These should avoid the invalid config files in the future. I will push a new release tomorrow.

**Comment by RainbowMiner** [comment]
Could you please create another Debug file?

**Comment by RainbowMiner** [comment]
Sidenote: you might consider to install the new Powershell v7.1.3. These strange problems are due to a bug in Powershell version up to 6.0

**Comment by mcangeli** [comment]
Yep, its working now. I'll close this issue.

**Comment by RainbowMiner** [comment]
Perfect!
