### ISSUE TITLE
WARNING: OpenCL platform detection failed

### ISSUE THREAD

**Issue by ArSd-g** [RainbowMiner/RainbowMiner#1498]
WARNING: OpenCL platform detection failed: Cannot bind argument to parameter 'ReferenceObject' because it is null

Both on Ubuntu LTS server (no GPU) and Archlinux (with GPU)

**Comment by RainbowMiner** [comment]
Do you have Debug files avail?

**Comment by ArSd-g** [comment]
no debugging files....where? logs you mean?, ctrl+F in your git"readme" give me something about "asynchronous loader"

**Comment by RainbowMiner** [comment]
Would you please zip the Logs folder and upload it here? I see, if I can found out, what is going on. Also, please start `gputest.sh` in the RainbowMiner folder. It will create a gputestresult.txt file.

**Comment by RainbowMiner** [comment]
> OpenCL platform 

normally indicates missing or failed OpenCL drivers. Which GPU have you been running?

**Comment by ArSd-g** [comment]
This is for my 1st machine (M1): OS=Archlinux-zen-kernel GPU=RX580+opencl-amd-20.45.1164792-4 CPU=i3-9100
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/6162875/gputestresult.txt)
[Logs.tar.gz](https://github.com/RainbowMiner/RainbowMiner/files/6162880/Logs.tar.gz)
Things to understand; after several bugs to get my GPU detected back (after update of 'RBM+system'->clean opencl-amdgpu reinstall) this message appears!! On this system AMD+CPU are detected correctly and this is not a fail over issue, it starts to mine...
BUT: On my rig (2nd machine=M2) with right now no GPU's: CPU's: 2xXeon-E5-2658-V3 OS: Ubuntu 20.04 LTS server and usually Vega56 with 19.50-'30' drivers it's a mess....
I did same thing; reboot then update RBM+System and the same error message appears with 'opencl warning' but lol there is no GPU attached to the MB...and this task end with a "no devices" detected (even cpu) then starts to mine then hardly crash...mining seems running on M1:Dashboard connection (to see M2 working so as remote) but i can't access it anymore with M2:Dashboard ip and even ssh and ipmi show no response but it STILL MINING! i'm suspecting an heavy bug with new kernel to detect i don't know what CPU values or acpi... logs for M2 will come after .....HARD REBOOT!

**Comment by RainbowMiner** [comment]
Did you get some logs for the M2 machine, yet? 
Also, the CPU affinity and threads for the M1 seems a bit harsh. It's an Intel Core i3 and all four cores are selected for CPU mining. I recommend you set the "CPUMiningAffinity" to "0xe" and the "CPUMiningThreads" to "3" for that particular machine. Give it some air to breathe.

**Comment by ArSd-g** [comment]
air?! naaan for this great i3 lol... i'm joking i'll consider it! i'm still on M2 lol...logs will come soon checking with old version of RBM with "turbostats, sensors, lscpu...." what is going wrong the crash is hard...

**Comment by ArSd-g** [comment]
this is M2 logs
@ "no devices" then start mining then hard crash on fresh RBM install directly updated to new one you will see that in update log!
switching quickly to archlinux-lts, thing i wanted to do since 19.50 is on aur as "Polaris special" but ok with my sleeping vega's
[Uploading M2.logs.tar.gz…]()

**Comment by ArSd-g** [comment]
M1 show no errors anymore after your update...did you make "in-rely" mods?

**Comment by ArSd-g** [comment]
After switching to windows 10 (after Ubuntu, after Archlinux) for testing in a GUI env = same error still "no devices" detected at RBM boot, hashrates and mining seems to be ok...but i don't like to see "errors" even if it might not affects performance...
Can you try to understand what's is going on? CPU= 2xXeon-E5-2658V3 i know it's old Cpus but so great for what i'm doing with!
Here is the logs: 
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/6177235/Logs.zip)

**Comment by RainbowMiner** [comment]
Ah! Now I see. It's the [INFO] notice in the logs file. I'll fix it.

**Comment by ArSd-g** [comment]
great thank you dude? i was dealing with heavy "try fix" numactl and more lol
I have also read that RBM uses rocm-smi for reading GPU power and others infos.

What about amdgpu OC underlinux ?(should be easy to bind?!) i'll check your "init script after/before miner"

Another question; are you aware about OpenCL versionning that breaks the driver for Vega's card and force users to use 
<= v19.50 and do you know where i can fallow this issue to get rid of instability, low hashrates and crashs on newest drivers (linux of course) 

last thing you always say that RBM should NOT be run as Root (sudo ./start.sh), and i found another issue; i always use it as root because i manage the rig via SSH+Tmux (just threw this "screen" app away lol tmux is the one) and it doesn't even connect to the internet when running RBM as user in Tmux (waiting for internet connection... (no tmux + RBM as user via ssh WORKS)
