### ISSUE TITLE
MRR Rentals

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1499]
Replaced some hardware, and my rigs have been mining perfectly.

Started to rent out my miners on MRR, and was hitting 100+% until towards the end of the rental when my rigs switched to Nicehash.

Question, how does RBM pick up where it left off when there is a current pending Rental?

**Comment by saki2fifty** [comment]
Tried disabling the NiceHash pool and leaving only MRR, but just says that there is no configured pool.  Reenabled NiceHash.

**Comment by RainbowMiner** [comment]
If the renter's pool fails for a period of time, RainbowMiner will briefly switch to standard operation (for 10-15 minutes) and then try again.

**Comment by RainbowMiner** [comment]
Question: 
- is this a standalone rig or a client/server machine?
- which algorithm has been rented?
- go to `http://magicminer:4000/watchdog.html` and see, if the Watchdog has disabled the miner.
- to immediate try a reconnect, restart RainbowMiner.
- if you are unsure, what is going on, create a Debug file and upload it. I will most likely find a clue

**Comment by RainbowMiner** [comment]
To get to the bottom of MRR interruptions, it often helps to watch the miners closely. So, if you have `"ShowMinerWindows": "0",` in config.txt - look into the Logs folder and find the most recent miner log files and check them. If ShowMinerWindows is enabled ("1"), I recommend restarting RainbowMiner. It will try to mine on MRR starting with the first or second round. Now you can watch, what is going on.

**Comment by saki2fifty** [comment]
- It was originally client, but switch to standalone when trying to find my bad gpu, so standalone
- Eth
- Screenshot below.  I'm forcing Trex only, and it is currently mining NiceHash.
- I restarted RBM, but it created another rig on MRR for rental.  :), I disabled that in the config and deleted the rig.
- Attached.

(Both rentals are being rented by the same guy, and his pool is not connecting.  However, in the screenshot below, my Connectoin Status is offline as well, per the below screenshot)

[Rig01_debug_2021-03-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/6160299/Rig01_debug_2021-03-17.zip)
[Rig02_debug_2021-03-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/6160300/Rig02_debug_2021-03-17.zip)



![image](https://user-images.githubusercontent.com/2228638/111550603-71b6c600-874c-11eb-8143-921c96a5742c.png)


![image](https://user-images.githubusercontent.com/2228638/111550465-2997a380-874c-11eb-984a-0dfee6107028.png)

**Comment by saki2fifty** [comment]
> To get to the bottom of MRR interruptions, it often helps to watch the miners closely. So, if you have `"ShowMinerWindow": "0",` in config.txt - look into the Logs folder and find the most recent miner log files and check them. If ShowMinerWindow is enabled ("1"), I recommend restarting RainbowMiner. It will try to mine on MRR starting with the first or second round. Now you can watch, what is going on.

Got it.  But, what exactly does "ShowMinerWindow"... show?

**Comment by saki2fifty** [comment]
Ok, I think I found the problem.  Per the docs, it says: 

_edit your rig's description and add your RainbowMiner workername, enclosed with square brackets, somewhere into the text, e.g. [rbm]. This is important, otherwise Rainbowminer will not find your rig, later._

While sitting there watching it, I think I somehow overwrote this.  I guess.  I'm starting from scratch.

Sorry for wasting your time, I'll stay quiet for a bit.  It's not much, but I'll increase my dev fees for a while.
