### ISSUE TITLE
WARNING: Download in progress

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#150]
![image](https://user-images.githubusercontent.com/41829368/45501364-2fa50780-b73e-11e8-88d3-310be6e18fa7.png)

Download is not kicking in neither when calling the (D) ownloader

**Comment by RainbowMiner** [comment]
Oh! Would you please send me your Logs folder zipped? It seems, some miner URL might be down.

**Comment by hernandn01** [comment]
I have already exited Rainbowminer and got back in again and it did download ccminersupr this time. This might not be reproducible again but the condition was that I had already updated  Trex.ps1 before the release to be able to download the new version of the binary. So it did detect there was only one left to be downloaded but it never did until I exit and got back again.

**Comment by RainbowMiner** [comment]
Ok. Would you be so kind and send the Logs zipped, anyway? (Only if it does not cause you too much trouble). I would like to find out about what has happened :)

**Comment by hernandn01** [comment]
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/2381147/Logs.zip)
Certailny, here they are
