### ISSUE TITLE
Other miners permanently disabled

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1502]
I used the miners tab in local host to disable everything except trex, but now I looked to turn some back on and there doesn't seem to be an option. Am I missing something please?

![image](https://user-images.githubusercontent.com/42582444/111696493-460b0d00-882c-11eb-84f6-e5168f97b9e7.png)

[debug_2021-03-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/6167159/debug_2021-03-18.zip)

**Comment by RainbowMiner** [comment]
Oh. I will check the localhost. These miners should show up as disabled. To enable them manually, look into folder `.\Stats\Disabled` - just delete the matching files there.
