### ISSUE TITLE
Trex issues

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1503]
0210318 21:53:11 Start working in get-work mode...
20210318 21:53:11 WARN: Connection with pool timed out. Trying to reconnect...
20210318 21:53:11 Using protocol: stratum1.
20210318 21:53:11 Start working in get-work mode...
20210318 21:53:11 WARN: Connection with pool timed out. Trying to reconnect...
20210318 21:53:11 Using protocol: stratum1.
20210318 21:53:11 Start working in get-work mode...
20210318 21:53:12 WARN: Connection with pool timed out. Trying to reconnect...
20210318 21:53:12 Using protocol: stratum1.
20210318 21:53:12 Start working in get-work mode...
20210318 21:53:12 WARN: Connection with pool timed out. Trying to reconnect...
20210318 21:53:12 Using protocol: stratum1.
20210318 21:53:12 Start working in get-work mode...
20210318 21:53:12 WARN: Connection with pool timed out. Trying to reconnect...
20210318 21:53:12 Using protocol: stratum1.
20210318 21:53:12 Start working in get-work mode...
20210318 21:53:12 WARN: Connection with pool timed out. Trying to reconnect...
20210318 21:53:12 Using protocol: stratum1.
20210318 21:53:12 Start working in get-work mode...

**Comment by acos0874** [comment]
20210318 22:01:43 GPU #1: generating DAG 4.14 GB for epoch 402 ...
20210318 22:01:43 GPU #2: generating DAG 4.14 GB for epoch 402 ...
20210318 22:01:43 GPU #0: generating DAG 4.14 GB for epoch 402 ...
20210318 22:01:44 GPU #3: generating DAG 4.14 GB for epoch 402 ...
20210318 22:01:53 GPU #0: DAG generated [crc: 0b018709, time: 9817 ms], memory left: 2.90 GB
20210318 22:01:53 GPU #3: DAG generated [crc: 0b018709, time: 9812 ms], memory left: 2.90 GB
20210318 22:01:53 GPU #2: DAG generated [crc: 0b018709, time: 9848 ms], memory left: 2.90 GB
20210318 22:01:53 GPU #1: DAG generated [crc: 0b018709, time: 10096 ms], memory left: 2.90 GB
20210318 22:02:10 GPU #3: using kernel #2
20210318 22:02:10 GPU #2: using kernel #4
20210318 22:02:10 GPU #0: using kernel #4
20210318 22:02:10 GPU #1: using kernel #4
20210318 22:02:23 [ OK ] 1/1 - 125.05 MH/s, 47ms ... GPU #3
20210318 22:02:25 [ OK ] 2/2 - 125.01 MH/s, 47ms ... GPU #2
            
Nicehash is fine

**Comment by RainbowMiner** [comment]
Which pool did fail? I think it's Trex's new erhproxy mode.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/111753878-44266580-888f-11eb-8ff7-a8ecfbfdf51d.png)

**Comment by RainbowMiner** [comment]
Yes. That's what I fixed with the commit https://github.com/RainbowMiner/RainbowMiner/commit/7ca1994cae57813374968e409e0cdef26be1d06e above. I'll push a new release asap.

**Comment by acos0874** [comment]
THanks
