### ISSUE TITLE
NBminer

### ISSUE THREAD

**Issue by bing281** [RainbowMiner/RainbowMiner#1506]
Benchmarking NBminer on KawPOW BeamHash3 Cuckatoo32 CuckooCycle Octopus

While the miner works RBM does not receieve any power gpu share stats and fails the benchmark.

**Comment by RainbowMiner** [comment]
Which pool did NBminer try to mine to?

**Comment by RainbowMiner** [comment]
Ok, solved. I will push a new release asap.

**Comment by bing281** [comment]
Solved Please Close
