### ISSUE TITLE
MRR Warning Message 3 hours

### ISSUE THREAD

**Issue by bing281** [RainbowMiner/RainbowMiner#1507]
How do I fix this warning message so that it creates the rigs?  

WARNING: MiningRigRentals: Unable to create rigs for EST_RB_1070TI: your rig must run for at least 3 hours be accurate

Also you have a grammar error on this message it should be "3 hours to be accurate"

**Comment by RainbowMiner** [comment]
Hi, thank you for reporting this. I'll fix the grammar error. Just wait the three hours (it starts after the benchmarks).
RainbowMiner needs an idea of your rig's profit performance before it can create new rigs on MiningRigRentals.

**Comment by bing281** [comment]
Thank you the information was correct.
