### ISSUE TITLE
Following up Issue #1461

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1508]
Following up issue #1461 

Hope it is fine to open a new issue since the previous was closed.

@RainbowMiner , is it possible to also have this feature enabled for remote miners? Instead of having to open a separate dashboard for other miner, can we instead reboot that particular rig from server/main rig? Don't know where the best place to put this additional button but maybe an extra button in console tab would do?

**Comment by RainbowMiner** [comment]
Sure. That is very well possible. I'll add buttons.

**Comment by astronyu** [comment]
Thank you.
