### ISSUE TITLE
Crash on flexpool

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1510]
@RainbowMiner, for some reason I experienced a lot of crashes when trying to mine at Flexpool.
No crashes when mining on other pools such as Hiveon or Nicehash though.

Can you help me by taking a look on the debug
[debug_2021-03-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/6178103/debug_2021-03-22.zip)
?

**Comment by RainbowMiner** [comment]
It looks like the Flexpool's Singapore stratum has a problem or cannot be reached at your location.
Try to force another stratum in pools.config.txt: set `"Region": "",` to another region, try "India", for example.

```
+----------------------------------------------------------------+
|                          GMiner v2.47                          |
+----------------------------------------------------------------+
02:42:35 Connect to eth-sg.flexpool.io:4444 Failed: Connection timed out
02:42:50 Connect to eth-sg.flexpool.io:4444 Failed: Connection timed out
02:43:05 Connect to eth-sg.flexpool.io:4444 Failed: Connection timed out
```

**Comment by astronyu** [comment]
Ah, I missed that. Thank you.
Just wondering, is there a way to have the miner to automatically try the next closest server after X times timout?

**Comment by RainbowMiner** [comment]
I can add this to the Flexpool, too, yes.

**Comment by astronyu** [comment]
That would be nice. Thank you.

**Comment by astronyu** [comment]
For some reason it didn't work. So, I remove sg server from the pool and try again.
This time I noticed it shows:

20210323 06:24:27 WARN: ApiServer: request took long, 21049.4ms for /summary
20210323 06:24:27 WARN: ApiServer: An established connection was aborted by the software in your host machine

What could be wrong?

**Comment by astronyu** [comment]
@RainbowMiner,. I tested running the miner directly and it failed on port 4444 but works fine on SSL 5555.
How to get the miner to connect to SSL port 5555 instead?

**Comment by astronyu** [comment]
Anyone knows how to connect to pool via SSL?
