### ISSUE TITLE
Feature Request?:  Expose powerprice via API

### ISSUE THREAD

**Issue by rawhide-kobayashi** [RainbowMiner/RainbowMiner#1511]
My power has hourly pricing, and they provide an API to get live cost info.  It would be nice if the powerprice setting was exposed and changeable via api, so I could update it with that info to get true-to-life granular profit measurements.

Am I a big dumb and missing that it's already possible?

**Comment by RainbowMiner** [comment]
No, you are not missing a thing. We have a saveconfig API endpoint, but it's not yet usable. I will add a working endpoint asap.

**Comment by rawhide-kobayashi** [comment]
The functionality in 4.7.0.7 is... functional!  Whipped up a quick script to do it ezpz, works perfectly.

**Comment by RainbowMiner** [comment]
Nice. Thank you for the feedback!
