### ISSUE TITLE
Could not write to file "devices.config"

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1513]
I just got a new laptop with a 3070, I'm trying to set up RBM but I can't get past this stage. I've tried several fresh installs, but keep getting this error.

![image](https://user-images.githubusercontent.com/42582444/112125230-1c027380-8bbb-11eb-8f15-98bc2e21e102.png)

**Comment by acos0874** [comment]
Ah it finally progressed past that page but has still failed to create the devices config.

**Comment by RainbowMiner** [comment]
That's interesting. Could you please upload a Debug file?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/112154276-03568580-8bdc-11eb-9575-568fdaa3368a.png)

So I tried updating the graphics driver, but the installer wouldn't allow because "no nvidia gpu detected". So then I realised that the laptop has an integrated GPU and appears to fully disable the dedicated GPU to save power. I disable this feature and was able to install the drivers, however, I'm still getting the error in RBM. I can't see to get localhost to load to get a debug file but I'll keep trying.

**Comment by acos0874** [comment]
[debug_2021-03-23.zip](https://github.com/RainbowMiner/RainbowMiner/files/6190043/debug_2021-03-23.zip)

I rebooted and removed AMD from the config and now it is mining but i still get the error...

I also got this when I downloaded the debug.

![image](https://user-images.githubusercontent.com/42582444/112155566-54b34480-8bdd-11eb-97df-57ec35b49278.png)

**Comment by RainbowMiner** [comment]
Ok, we are approaching - could you upload the `.\Config\devices.config.txt` please?

**Comment by acos0874** [comment]
I'm afraid it doesn't exist.

**Comment by RainbowMiner** [comment]
Ok.
That actually helped - I have found the culprit. What is the model of the AMD GPU?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/112196296-cb166d80-8c02-11eb-8a82-bc6887616521.png)

**Comment by RainbowMiner** [comment]
I'll post a workaround asap.

**Comment by RainbowMiner** [comment]
Ok - added.
