### ISSUE TITLE
Proxy server

### ISSUE THREAD

**Issue by saki2fifty** [RainbowMiner/RainbowMiner#1514]
Referencing #1348 and the docs, I cannot figure out how to use a custom pool, which would point to a local proxy server.

The docs say `Proxy = set your proxy address here, if you are using one` .  Is this a web proxy to get out?  Or is it for a stratum proxy server?

Reading through the **Config\userpools.config.txt** section, I've updated it to include my pool:

    "Enable": "1",
    "Name": "TestPool",
    "PoolFee": "0",
    "Algorithm": "Ethash",
    "CoinName": "ETH",
    "CoinSymbol": "ETH",
    "Currency": "ETH",
    "Protocol": "stratum+http",
    "Host": "192.168.1.200",
    "Port": "8080",
    "User": "",
    "Pass": "",
    "Region": "US",
    "SSL": "0",
    "EthMode": "ethproxy"
  },

I've updated my config.txt:

  "Region": "USSouth",
  "Currency": "BTC,USD,ETH",
  "PoolName": "TestPool",
  "ExcludePoolName": "",
  "MinerName": "Trex",

Restarting RBM, I can see the new custom Pool, and selected... "WARNING: No pools available: check your configuration"

If I copy T-rex from your /bin dir, and run it with minimal parameters, the miner see's it:
![image](https://user-images.githubusercontent.com/2228638/112231120-14b38800-8c04-11eb-9e6e-411a593bbeb6.png)

stratum+http://, however your docs don't show this as an option.

Sorry... just testing all your features, but would like to use this.

**Comment by RainbowMiner** [comment]
That's interesting. Could you please try to add one of the pools that come with RainbowMiner?

Regarding the stratum+http:// - yes, I have it disabled, currently. I will re-add it for `"EthMode": "ethlocalproxy",`

**Comment by saki2fifty** [comment]
I created another test Nicehash pool: WARNING: No pools available: check your configuration

config.txt : "PoolName": "NicehashTest",

  {
    "Enable": "1",
    "Name": "TestPool",
    "PoolFee": "0",
    "Algorithm": "Ethash",
    "CoinName": "ETH",
    "CoinSymbol": "ETH",
    "Currency": "ETH",
    "Protocol": "stratum+http",
    "Host": "192.168.1.200",
    "Port": "8080",
    "User": "test",
    "Pass": "x",
    "Region": "US",
    "SSL": "0",
    "EthMode": "ethproxy"
  },
  {
    "Enable": "1",
    "Name": "NicehashTest",
    "PoolFee": "0",
    "Algorithm": "Ethash",
    "CoinName": "ETH",
    "CoinSymbol": "ETH",
    "Currency": "ETH",
    "Protocol": "stratum+tcp",
    "Host": "daggerhashimoto.usa-west.nicehash.com",
    "Port": "3353",
    "User": "$Wallet.$WorkerName",
    "Pass": "x",
    "Region": "US",
    "SSL": "0",
    "EthMode": ""
  },

**Comment by RainbowMiner** [comment]
Please try to add "Nicehash" to the PoolName parameter. It will activate the build-in Nicehash pool module. Intention is to see, if it's an issue, that you have userpools activated, only.

**Comment by saki2fifty** [comment]
Left custom pool enabled, added "NiceHash" to Poolname, restarted, and it started to mine.

Left custom pool enabled, changed Poolname back to "TestPool", restarted, and: WARNING: No pools available: check your configuration.

Left custom pool enabled, change Poolname back to "Nicehash", restarted, and it started to mine again.

**Comment by saki2fifty** [comment]
![image](https://user-images.githubusercontent.com/2228638/112363199-3c0d6200-8ca3-11eb-9a93-8772fd8f9d04.png)

**Comment by saki2fifty** [comment]
Duplicated my config on my laptop...

With PoolName set to NiceHash and EthProxy user pool set to disabled:

When this if statement ends, $NewPools is populated:
![1](https://user-images.githubusercontent.com/2228638/112403265-1a7c9c80-8cdc-11eb-905d-2a71cc547c49.PNG)

Pools are found:
![2](https://user-images.githubusercontent.com/2228638/112403387-50ba1c00-8cdc-11eb-9379-fdb08e220daf.PNG)

With PoolName set to EthProxy and EthProxy user pool set to enabled, $NewPools is not populated:
![3](https://user-images.githubusercontent.com/2228638/112403554-9d055c00-8cdc-11eb-821f-23aff6a94ac0.PNG)

User pool appears to be found:
![5](https://user-images.githubusercontent.com/2228638/112403620-c1f9cf00-8cdc-11eb-9423-5965057b993a.PNG)

No pools available as $NewPools is empty:
![6](https://user-images.githubusercontent.com/2228638/112403670-d6d66280-8cdc-11eb-9708-7a3d1bd260dd.PNG)

**Comment by RainbowMiner** [comment]
Super! Thank you for the analysis. I think, now I can solve the problem.

**Comment by saki2fifty** [comment]
I'm old, slow, wife and I in bed for a month now with Covid...  looking for stuff to do.  haha :)

**Comment by RainbowMiner** [comment]
Oh dear! Covid is no fun. Get well soon!

**Comment by RainbowMiner** [comment]
Oh man! How could I have been so blind:
- Please add a ETH wallet address in pools.config.txt for your TestPool

If RainbowMiner detects a new poolname in userpools, it creates a new entry in pools.config.txt for that poolname. User created pools need a wallet address in pools.config.txt, like all other pools. There is a check in place against "Enable" and the currencies wallet address in pools.config.txt not empty.

**Comment by saki2fifty** [comment]
Literally the largest PS project on Earth...  you may pass GO.

It now works!  Thx!

![image](https://user-images.githubusercontent.com/2228638/112469281-4b3def80-8d37-11eb-8dcf-2491228eee0b.png)

**Comment by RainbowMiner** [comment]
Perfect!
