### ISSUE TITLE
RBM on a laptop: GPU not detected

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1517]
I'm trying to install RBM on my laptop as I'm planning to let it run for a few hours when idle. Unfortunately each time I tried it gave me "GPU not detected" message. What could be the problem?

Laptop is Intel(R) Core(TM) i7-8750H, 16GB RAM with GTX 1060 6GB
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/6216174/gputestresult.txt)

**Comment by RainbowMiner** [comment]
Could you please upload either a Debug file or a zip of the Logs folder?

**Comment by astronyu** [comment]
Sorted out. It turns out the message only showed when I run the install.bat but no issue running start.bat afterward.
