### ISSUE TITLE
Enabling SSL on supported pools

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1518]
@RainbowMiner, is there a quick way to enable or prioritize SSL connection to supported pool by default?
Maybe a toggle switch in dashboard somewhere to enable/disable SSL on a pool?
Tried adding "SSL":"1" in pool config but that doesn't seems to work.

**Comment by RainbowMiner** [comment]
No, there isn't a pool specific way, currently. It's only possible to change it globally.
I will add a pool SSL switch.

**Comment by RainbowMiner** [comment]
- added pool specific SSL selection (parameter "SSL" in pools.config.txt)
  - set to "1" to prefer SSL connection
  - set to "0" to prefer non-SSL connectino
  - leave empty "" to use config.txt SSL parameter value

**Comment by AnthonyBe** [comment]
Am I right in understanding that the global (config.txt) SSL setting _forces_ only SSL connections?
If so, is there a way to have a global _prefer_ SSL connections, but fall-back to non-SSL if not available?

**Comment by RainbowMiner** [comment]
In fact, that is already the case. Setting SSL to "1" uses SSL wherever it is possible and falls back to non-ssl, if a pool doesn't have an encrypted stratum.

**Comment by AnthonyBe** [comment]
> In fact, that is already the case. Setting SSL to "1" uses SSL wherever it is possible and falls back to non-ssl, if a pool doesn't have an encrypted stratum.

Thanks for confirming!

The docs say "SSL = set to 1, _if only ssl connections wanted_" which didn't sound like there was a fallback option to non-SSL. Well, to me, anyway :)

**Comment by AnthonyBe** [comment]
Just out of curiosity, is there any reason _not_ to have SSL=1 in config.txt?
Is there a significant performance overhead or some other negative?
