### ISSUE TITLE
Hiveon balance not showing

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1519]
I just tried Hiveon these past 2 weeks and kind of liking it. However for some reason I didn't see Hivepool balance shown on the dashboard, is there an option to enable this in config? Other pools showing are showing balance though (Flexpool,Nicehash,MPH, MRR)
[debug_2021-03-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/6217728/debug_2021-03-22.zip)

**Comment by RainbowMiner** [comment]
Could you supply me with your ETH or ETC address, so that I have a test case?

**Comment by astronyu** [comment]
Sorry for the late reply. 
This is Eth address. 0x3d1d0ac316AC98Ed7aD031F6D7a48D002Afec4D7
