### ISSUE TITLE
Mintpond.ps1 estimated profit incorrect FIRO

### ISSUE THREAD

**Issue by bing281** [RainbowMiner/RainbowMiner#1520]
Mintpond returns wrong estimated profit at least for FIRO because of the following: 

\Pools\Mintpond.ps1

Line 73       $reward         = 14 #if ($lastBlock.reward) {$lastBlock.reward} else {14}

This should not be static 14 I believe FIRO reward is currently ~6.25

**Comment by RainbowMiner** [comment]
Thank you for reporting this. Mintpond had issues with the lastblock reward value back then. I'll rework the pool module.

**Comment by bing281** [comment]
looks solved to me thank you.
