### ISSUE TITLE
Feature Request : Preferred Miner if within %

### ISSUE THREAD

**Issue by bing281** [RainbowMiner/RainbowMiner#1522]
Preferred Miner if within X % of other best miners benchmarked hash rate.  

Preferred Miner Settings
  percent=5%
  1 TREX 
  2 SBMINER
  3 GMINER
  4 PHOENIX

Example 1
  TREX benchmarks @ 10 MH on algorithm whatever1
  GMINER benchmarks @ 10.2 MH on algorithm whatever1
  PHOENIX doesn't work on algorithm whatever1
  SBMINER doesn't work on algorithm whatever1

  TREX will be chosen

Example 2
  TREX benchmarks @ 10 MH on algorithm whatever2
  GMINER benchmarks @ 10.2 MH on algorithm whatever2
  PHOENIX benchmarks @ 11 MH on algorithm whatever2
  SBMINER benchmarks @ 10.3 MH on algorithm whatever2

  PHOENIX will be chosen

Example 3
  TREX benchmarks @ 9.8 MH on algorithm whatever3
  GMINER benchmarks @ 10.1 MH on algorithm whatever3
  PHOENIX benchmarks @ 10.1 MH on algorithm whatever3
  SBMINER benchmarks @ 10.2 MH on algorithm whatever3

  TREX will be chosen

--------------

Just a thought I personally like TREX better than other miners most of the time but find that RBM will switch off it because a small amount of hash

**Comment by RainbowMiner** [comment]
It's an interesting idea. I will add something.
