### ISSUE TITLE
Linux dependencies for SgminerFancyIX

### ISSUE THREAD

**Issue by sashizu** [RainbowMiner/RainbowMiner#1527]
Please add libncurses5 and libncurses5-dev to list of dependencies for install/update on Linux.

> /root/RainbowMiner/Bin/AMD-FancyIX/sgminer: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory

Thanks,

Robert

**Comment by RainbowMiner** [comment]
Added. Thank you for reporting!
