### ISSUE TITLE
Add support to memo in unMineable wallet config

### ISSUE THREAD

**Issue by appsettings** [RainbowMiner/RainbowMiner#1531]
Hi,

I've found out that RBM checks the validity of the wallet of unMineable config using the regex provided by unMineable API.
It does work for normal wallet config, but it doesn't if mining to exchange and using memo, for example unMineable says for BNB:

`If you are mining to an exchange or need to set a MEMO or TAG you must add it after your address:
BNB:YourAddress:YourMemo.YourWorkerName`
https://unmineable.com/coins/BNB

I saw that unMineable API provides separate regex for memo.

Can you add memo/tag support?

Thanks a lot

**Comment by RainbowMiner** [comment]
Did you already try "wallet:memo" in pools.config.txt, "unMineable" section, yet?

Like
```
"BNB": "yourwalletaddress:thememo",
```

because RainbowMiner should then create "BNB:yourwalletaddress:thememo.workername" automatically.

**Comment by appsettings** [comment]
Yes, I've tried like you said, but it doesn't work because of the regex check. It checks the length of the wallet, and the pool is not picked up. Manually "removing" the regex check from the pool file it starts to mine.

**Comment by RainbowMiner** [comment]
Ah! I see. Ok, I'll fix it asap.

**Comment by RainbowMiner** [comment]
I have removed the regex. It's pretty from programmer's perspective, but to be honest, not needed.
