### ISSUE TITLE
IsVM check - false positive on Windows.

### ISSUE THREAD

**Issue by theGunner295** [RainbowMiner/RainbowMiner#1532]
The $Session.IsVM check appears to be returning 'True' on Microsoft devices.

A way to manually bypass the VM check for devices you know are not virtual would be great.

![image](https://user-images.githubusercontent.com/82002977/114274863-4015df80-9a18-11eb-998c-3f7bf89411df.png)
![image](https://user-images.githubusercontent.com/82002977/114274875-4b690b00-9a18-11eb-90cd-6181ec9875f6.png)

**Comment by RainbowMiner** [comment]
Oh. Yes, I see. Let's remove the regex for microsoft.
