### ISSUE TITLE
Adding new coin to a pool

### ISSUE THREAD

**Issue by packetspyke** [RainbowMiner/RainbowMiner#1533]
Perhaps I am blind but I can't for the life of me figure out how to add a new coin to an existing pool. I don't want to edit files just to have them overwritten with an autoupdate, so I figured I would ask here.

SuprNova has a new coin called Optical Bitcoin (OBTC) and it uses the algo HeavyHash. How do I go about adding this to my existing rainbowminer server so my clients pick it up and benchmark and start mining it?

Also, MiningRigRentals has added this algo as well and I wish  to have rainbowminer offer it to rent as well.

**Comment by RainbowMiner** [comment]
This is the way. 
If you find out about a pool adding or removing coins, please just open an issue. I will adapt the pool modules asap.

**Comment by sgeneralov13** [comment]
How to add OBTC wallet to balances list?

**Comment by RainbowMiner** [comment]
Ok, OBTC has been added. 
If you don't want to wait until the next release, either download the file [walletsdata.json](https://github.com/RainbowMiner/RainbowMiner/raw/master/Data/walletsdata.json) into your `./Data` (windows: `.\Data`) folder, or edit the file `./Data/walletsdata.json` (windows: `.\Data\walletsdata.json`) and add the following record:
```
    {
        "symbol":  "OBTC",
        "match":  "^bc1",
        "rpc":  "https://txrat.com/ext/getaddress/{w}",
        "address":  "address",
        "balance":  "balance",
        "received":  "",
        "divisor":  1
    },
```
