### ISSUE TITLE
Feature Request / Issue : Some wallet balances not showing

### ISSUE THREAD

**Issue by bing281** [RainbowMiner/RainbowMiner#1537]
For example my YEC wallet gets payouts from F2Pool and doesn't show up in the wallet balances.   

feature request is docuement which wallets / coins support wallet balances

issue is show YEC wallet balance and F2Pool balances as neither show up.

**Comment by RainbowMiner** [comment]
The f2pool balance module needs an update. Will be there asap.
Please report, if pools or pool's balances are missing some coins. I'll add them.

**Comment by RainbowMiner** [comment]
Ok, updated.

**Comment by RainbowMiner** [comment]
YEC added to Wallets

**Comment by bing281** [comment]
Fixed for YEC yet to mine F2Pool yet to see if it is updating.
