### ISSUE TITLE
Miner windows do no longer steal focus

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#154]
If you select to let rainbowminer show the actual miner window (setting "ShowMinerWIndow" to "1" in config.txt), the miner windows would steal your windows focus at the time they are started. To avoid this focus problem, I have implemented a new start process function.
Since this is a new system function, I would appreciate help in testing this out, before I publish a release.

If you are already using the "ShowMinerWindow" or am interested in it, have the time and like to help testing, please download the current [master.zip](https://github.com/RainbowMiner/RainbowMiner/archive/master.zip) and give it a try :)

Thank you very much!

RBM

**Comment by hernandn01** [comment]
Tested correctly, new start function do not steal focus. from main window

**Comment by RainbowMiner** [comment]
Thank you! :)
