### ISSUE TITLE
stop disabling miner when hashrate is too high

### ISSUE THREAD

**Issue by wakamex** [RainbowMiner/RainbowMiner#1540]
i'm getting randomx disabled because i restarted and my hashrate doubled. this is also in the middle of an MRR rental.

> WARNING: Stat file (Xmrig-CPU#00_RandomX_HashRate) was not updated because the value 16.23 kH is outside fault tolerance 1.50 kH to 14.28 kH.

**Comment by wakamex** [comment]
doubled the miner fault tolerance for CPU

>   "MinerFaultToleranceCPU": 100,

**Comment by wakamex** [comment]
setting it to 200 did the trick, though that's out of spec according to https://rbminer.net/documentation/

**Comment by RainbowMiner** [comment]
> it's still happening

If such a hashrate recovery happens happens, the easiest way to deal with it, is to remove the stat file of the miner. All stat files can be found in `.\Stats\Miners` (linux: `./Stats/Miners`) folder.
