### ISSUE TITLE
Please for the love of god add a confirmation on the "benchmark all miners". Or a backup for miner stats

### ISSUE THREAD

**Issue by VoltaVX** [RainbowMiner/RainbowMiner#1545]
I spent all day benchmarking on 180 second intervals, and without thinking, I pressed "Benchmark all miners" for some reason thinking it'll only delete the miners from the pools selected. Please add a confirmation or a backup of the stats file. 

Needless to say, imma go log off right now for a bit, it's not your fault, and I appreciate all the work you've put into this amazing software, but adding that feature would be EXTREMELY appreciated by a lot of people as well

**Comment by RainbowMiner** [comment]
Oh dear! I feel with you. I'll add a confirmation.

**Comment by RainbowMiner** [comment]
Too late for you - but now there is a confirmation modal on that red button.

**Comment by VoltaVX** [comment]
Thank you so much for the addition, you don't know how much I appreciate it. I'm sorry if I came off a bit hostile when I created this issue, but deleting the benchmark files that took the whole day to compile so foolishly was extremely frustrating.

Thank you so much for your work!

**Comment by RainbowMiner** [comment]
Also working on an Auto-Backup.
