### ISSUE TITLE
Rebench specific OC profiles

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1546]
Currently there doesn't seem an easy way to trigger a rebench of a specific OC profile e.g. Profile2. If I want to do this, I either have to rebench all miners and waste money rebenching stuff that doesn't need to be done, or go through the list of each miner/device and select them one by one.

**Comment by RainbowMiner** [comment]
I have never thought about that possibility. Very good idea.

**Comment by RainbowMiner** [comment]
Now you can go to "Benchmarks" page, choose an oc profile with the dropdown of the miner's list, then click the upper left checkbox to select all visible miners. Finally click "Benchmark Selected" and off you go.

**Comment by samdave123** [comment]
Sounds like a super simple and elegant solution. Does this also work if I want to filter to a specific device or specific algo or specific miner?
