### ISSUE TITLE
(bug) Dashboard sorts numbers incorrectly, as if it was an alphabet 

### ISSUE THREAD

**Issue by tvanroo** [RainbowMiner/RainbowMiner#1548]
On the web ui dashboard, when sorting by a column with numbers as values (profit, power, last seen, etc...) the sort is effectively alphabetical, only using the first digit to order the column.  No consideration is made for the size of the number nor the units (e.g. days vs. minutes)

As an illustration sorting the power column results in:
- 0W
- 1500W
- 20W
- 220W

As opposed to what it should be:
- 0W
- 20W
- 220W
- 1500W

Another example, from "Last Seen"
- 10 Hours
- 22 Seconds
- 3 days
- 31 minutes

As opposed to what is should be:
- 22 seconds
- 31 minutes
- 10 hours
- 3 days

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll fix it.

**Comment by RainbowMiner** [comment]
I hope, I have found all. If you happen to find another sort problem, please let me know.
