### ISSUE TITLE
Error On Benchmarking

### ISSUE THREAD

**Issue by syedadeel2** [RainbowMiner/RainbowMiner#1549]
In a previous version of RBminer, there was no such error but, today I downloaded the latest RBminer, and I'm getting below errors

InvalidOperation: /home/miner/RainbowMiner/Modules/Include.psm1:1649
Line |
1649 |  … al:StatsCache."$($c.Name)_$($c.BaseAlgorithm -replace '\-.*$')_HashRa …
     |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'PowerDraw' cannot be found on this object. Verify that the property exists and can be set.

**Comment by RainbowMiner** [comment]
That's interesting. It looks like a corrupted stat file. Could you please upload a Debug file (on localhost:4000 click "Debug file")? I'ld like to find out more about that error.

**Comment by syedadeel2** [comment]
There are a lot of files, which one you need? I can upload file zip, but I want to share any of my wallet or server info in it if any.

**Comment by RainbowMiner** [comment]
It's the Debug file, the Web UI creates. 
open http://localhost:4000 in your webbrowser, then find "Debug file" on the left hand side and click it. It will create a zip file, that you can upload here. All sensible information will be removed, so your wallets stay anonymous.
![image](https://user-images.githubusercontent.com/39437538/115144592-c43a1980-a04d-11eb-87ee-92f3777939eb.png)

**Comment by syedadeel2** [comment]
Below is the screenshot. Whenever I click on debug file, I get this error. 
![image](https://user-images.githubusercontent.com/2682457/115161554-c0f06d80-a0e1-11eb-8e3c-0d4251611616.png)

Also, I m attached the debug zip file; this new release is not stable; in mid of benchmarking, it automatically closes the PowerShell. Same thing on Linux and Windows.

The first time I downloaded rbminer was 3 weeks ago, and that version was so stable, no issues at all.. let me find where what version I used.
[debug_2021-04-18 (2).zip](https://github.com/RainbowMiner/RainbowMiner/files/6332255/debug_2021-04-18.2.zip)

**Comment by RainbowMiner** [comment]
Thanks. This looks like a compatibility issue with the old Powershell 5.
There are some things you can do:
- first of all, update your PowerShell to v7.1.3. Here is the link to the Windows installer: https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x86.msi
- second, increase your Windows pagefile to 61600 MB (from 16000 MB)

**Comment by syedadeel2** [comment]
Hello, I downloaded Powershell from the link you have given, and increase the size to 80 GB but there are new error in your new release see below

![image](https://user-images.githubusercontent.com/2682457/115383997-d8327680-a219-11eb-88dc-547c46566846.png)

**Comment by RainbowMiner** [comment]
Yes, it looks like, MiningPoolHub pool is currently changing SIA coin (it has no algorithm assigned). You can safely ignore this message. I'll add a workaround for that asap.
