### ISSUE TITLE
MiningPoolHub script Error

### ISSUE THREAD

**Issue by mborisagar** [RainbowMiner/RainbowMiner#1555]
i get this error till today
![Desktop_Screenshot_2021 04 20_-_17 10 28 77](https://user-images.githubusercontent.com/9131487/115411730-5b9b9a00-a211-11eb-874e-faa5db453375.png)

**Comment by mborisagar** [comment]
same error in other sytem

![image](https://user-images.githubusercontent.com/9131487/115416524-7bcd5800-a215-11eb-99bc-18ecc2b2fca2.png)

**Comment by RainbowMiner** [comment]
Yes, MiningPoolHub seems to phase out SIA coin. I have addressed that issue with commit 08e904704319d7fe78c55cf0201a7d55649dc243 earlier this day.
