### ISSUE TITLE
Power offset

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#156]
Suggested feature or config item. The ability to add a power offset to allow consideration for overhead power. This would be useful for people that take readings off there rig and know there pulling more power than just the video card itself.

Ex. The power usage reported on my rig is 900w, But I know by the meter I have on my rig that it is actually pulling 1100w.

**Comment by RainbowMiner** [comment]
Very good idea, thank you! I will add this

**Comment by hernandn01** [comment]
Will you integrate this power offset into checkprofitability? to stop mining if the overall powerdraw is not profitable

**Comment by RainbowMiner** [comment]
Yes :) It's done.
