### ISSUE TITLE
ProHashing needs "-k 'api-key'" parameter

### ISSUE THREAD

**Issue by ArSd-g** [RainbowMiner/RainbowMiner#1560]
Of course "api-key" is "on" on Prohashing.com and in RBM pool config....

Pool eu.prohashing.com authorization failed. Error code: -2 - Authorization failed because API key requirement is enabled for username ***** and the k= argument is missing or mismatched. (1454 ms)

**Comment by RainbowMiner** [comment]
I see - you have enabled "Require API key for miners" at the ProHashing account settings. You can safely disable the option.

If you want to rather keep it enabled, try the following settings in pools.config.txt (ProHashing section)
```
    "AECurrency": "LTC",
    "LTC-Params": "k=put_your_API_key_here",
```

If you have another currency setup for autoexchange at ProHashing, just interchange LTC with the coin's symbol.
e.g.
```
    "AECurrency": "BTC",
    "BTC-Params": "k=put_your_API_key_here",
```

**Comment by RainbowMiner** [comment]
There is now a new configuration parameter in pools.config.txt:
- `EnableAPIKeyForMiners` - set to "1", if you have enabled "Require API key for miners" at the ProHashing account settings. RainbowMiner will then add "k=your_api_key" to the miner's options.
