### ISSUE TITLE
Incorrect syntax on line 131 of TeamRed.ps1 miner in RainbowMiner\Miners\TeamRed.ps1

### ISSUE THREAD

**Issue by theGunner295** [RainbowMiner/RainbowMiner#1561]
When executing TeamRed.ps1, Rainbow miner throws a large series of errors relating to line 131.

Line reads as 
} elsif ($IsVerthash) {

Correct syntax is
} elseif ($IsVerthash) {

**Comment by RainbowMiner** [comment]
Oh crap! You are right. I'll push a new release asap.

**Comment by RainbowMiner** [comment]
Done.
