### ISSUE TITLE
RM 4.7.1.5 - Pool API (ZelLabs) for ZEL has failed.

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1563]
I re-enabled this pool yesterday and noticed this error popping up each time:

`WARNING: Pool API (ZelLabs) for ZEL has failed. `

[debug_2021-04-23.zip](https://github.com/RainbowMiner/RainbowMiner/files/6362174/debug_2021-04-23.zip)

**Comment by AnthonyBe** [comment]
Seeing additional error for FIRO as of 30 April:

`[2021-04-30 00:49:53] WARNING: Pool API (ZelLabs) for FIRO has failed. `

**Comment by RainbowMiner** [comment]
Oh! They have renamed their pool to fluxpools.net - I'll push an update.

**Comment by AnthonyBe** [comment]
I've updated to RM 4.7.1.7 and am seeing following error on FluxPools

`WARNING: Pool API (FluxPools) for FIRO has failed.`

Fresh debug logs if needed.
[debug_2021-05-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/6408575/debug_2021-05-01.zip)

**Comment by RainbowMiner** [comment]
Oh dear :) They really have some quirks left over, after their rename. I have fixed it.

**Comment by AnthonyBe** [comment]
Sorry, I just noticed another issue.
I grabbed the updated fluxpools.ps1 from commit dfb0790 to clear the API errors.

I'm now seeing the Gminer crashing when trying to mine FIRO every time.
```
10:36:13 Connect to us-flux.fluxpools.net:7111 Failed: sslv3 alert handshake failure
10:36:13 All user mining pools are unavailable
```

Now, this may actually be a Gminer v2.54 issue (or my system) as I'm also seeing it fail on Nicehash pool with

```
10:44:11 Connect to kawpow.usa.nicehash.com:3385 Failed: stream truncated
10:44:11 All user mining pools are unavailable
```

**Comment by AnthonyBe** [comment]
Actually, let's close this off and I'll raise new Issue for these as they vary from the original Issue
