### ISSUE TITLE
TTF Discrepancy

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1568]
I was just looking at my rigs mining on zergpoolcoins, and I wondered why I hadn't found a DYN block in a while, since my max luck is 1.25, the ttf on the pool was 3 min and the last block was 14 min ago. So digging a little deeper I noticed that RBM disagrees with the website.

![image](https://user-images.githubusercontent.com/42582444/116159335-f1d73080-a6e7-11eb-9c0e-948204d9783e.png)

vs  
![image](https://user-images.githubusercontent.com/42582444/116159402-129f8600-a6e8-11eb-8a55-426af88dedc0.png)

So I'm not sure where rbm is getting it's ttf values from for this coin.

**Comment by acos0874** [comment]
The website agrees with the API 

mic","height":696848,"difficulty":"1.16149443","workers":276,"workers_shared":263,"workers_solo":13,"shares":0,"hashrate":31666436,"hashrate_shared":26954052,"hashrate_solo":4712384,"network_hashrate":25847568,"reward":1,"estimate":"0.41512237","estimate_current":"0.00041512","estimate_last24":"0.00023745","actual_last24h":"0.21480","actual_last24h_shared":"0.21593","actual_last24h_solo":"0.21196","mbtc_mh_factor":1,"24h_blocks":83,"24h_blocks_shared":60,"24h_blocks_solo":23,"24h_btc":"0.001878","24h_btc_shared":"0.001351","24h_btc_solo":"0.000527","lastblock":"696847","timesincelast":230,"timesincelast_shared":230,"timesincelast_solo":1327,"noautotrade":0,"pool_ttf":157,"real_ttf":158,"minpay":2.99754,"minpay_sunday":0.59951,"blocktime":"133","symbol":"DYN"}

**Comment by RainbowMiner** [comment]
It's a problem of blocks over time. RainbowMiner uses the `24h_blocks_shared` number to calculate the average ttf over the past 24h. The number is fed through a 1 hour moving avergage function and then the ttf is calculated:
```
24 * 60 / MovingAvg1h(24h_blocks_shared) = 24min. (with 24h_blocks_shared is 60 in the API example.)
```
The calculated ttf will differ from the current ttf, if the hashrate peaks.

**Comment by acos0874** [comment]
Can RBM not just take the TTF from the API?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/116829097-e7f77680-ab9a-11eb-8f84-3774b929c9fd.png)
Something seems to be not working quite right since the TTF for FIRO is way too huge.
