### ISSUE TITLE
Balance issue using ZergPoolCoins

### ISSUE THREAD

**Issue by thebeerbaron2018** [RainbowMiner/RainbowMiner#157]
When using just ZergPoolCoins - zergpool does not get listed in the balances output section.

**Comment by thebeerbaron2018** [comment]
OK - so this is because I remove all the unneeded files from the pools folder.... if I only leave zergpoolcoins.ps1 in there - no balance output, but if I put zergpool.ps1 in there as well (although unused by the mining selection algorithm) then I get the balance correctly displayed.

**Comment by RainbowMiner** [comment]
Yes, same applies to MiningPoolHubCoins and BlockmastersCoins.

**Comment by thebeerbaron2018** [comment]
Maybe a lookup table like below, read the active pools and make an array of the balances needed and then filter the duplicates to make the list unique and then pass that to the code that gets the balances.

```
 	AHashPool > AHashPool
	BlazePool > BlazePool
	BlockMasters > BlockMasters
	BlockMastersCoins > BlockMasters
	Blockcruncher > Blockcruncher
	Bsod > Bsod
	Hashrefinery > Hashrefinery
	MiningPoolHub > MiningPoolHub
	MiningPoolHubCoins > MiningPoolHub
	NiceHash > Nicehash
	PhiPhiPoo > PhiPhiPoo
	Ravenminer > Ravenminer
	YiiMP > Yiimp
	ZergPool > Zergpool
	ZergPoolCoins > Zerpool
	Zpool > zpool
```
