### ISSUE TITLE
Feature request: per day cost manual config

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#1574]
In some situations, where power is either a fixed price per day or there may be a monthly or yearly lease for access to hardware plus power it may make sense to calculate profits from revenue minus fixed expense instead of revenue minus power consumption multiplied by power rate. 

for example if I were to rent a VPS to mine monero and I had a fixed cost of a dollar per day regardless of power usage my profit calculation would be revenue minus 1 dollar per day. 

or if you had entered into an arrangement with a power provider where your electricity cost was exactly $50 per month regardless of wattage you would want to employ similar logic. 

Also you would prioritize making max revenue instead of max profit

**Comment by Nickfost** [comment]
Bump

**Comment by RainbowMiner** [comment]
Thanks for the bump - added.

**Comment by DCreason** [comment]
is this the correct configuration to account for fixed datacenter costs and keep mining even if it becomes unprofitable? 
![image](https://user-images.githubusercontent.com/11247559/139505266-2cfb9cd6-1b88-4e9d-980b-4a3428636b78.png)
