### ISSUE TITLE
Add Pool Request wowne.ro & cryptonote.social

### ISSUE THREAD

**Issue by chavesfop** [RainbowMiner/RainbowMiner#1575]
I'm mining a lot of Wownero Coins lately how can I help to add this Pools in RainbowMiner:

https://wowne.ro  
https://cryptonote.social/

**Comment by RainbowMiner** [comment]
You can add these pools, using the RainbowMiner's userpools. These are the steps:

1. edit `.\Config\userpools.config.txt` and add the following record (or edit one of the presets). Do not change the `$Wallet` or `$WorkerName`. These act as variables for your settings in pools.config.txt (see step 2)

```
    {
        "Enable":  "1",
        "Name":  "Wownero",
        "PoolFee":  "0.5",
        "Algorithm":  "RandomWow",
        "CoinName":  "Wownero",
        "CoinSymbol":  "WOW",
        "Currency":  "WOW",
        "Protocol":  "stratum+tcp",
        "Host":  "pool.wowne.ro",
        "Port":  "3333",
        "User":  "$Wallet",
        "Pass":  "$WorkerName",
        "Region":  "US",
        "SSL":  "0",
        "Worker":  "$WorkerName",
        "EthMode":  ""
    },
```

2. now let RainbowMiner run for 1-2 rounds. It will inject your new userpool with name "Wownero" into it's configuration. Then edit `.\Config\pools.config.txt` and find the newly added pool-entry "Wownero". Add your Wow super address to parameter "WOW":

```
  "Wownero": {
    "WOW": "YOUR_WOWNERO_SUPER_ADDRESS",
    "WOW-Params": "",
...
  },
```

... of course, you might as well add your WOW address to `.\Config\coins.config.txt` and then input `$WOW` into the pools.config.txt "WOW" parameter.

3. edit `.\Config\config.txt` and add your newly created userpool "Wownero" to the "PoolName" parameter.

Now you should be able to see the new Wownero pool on http://localhost:4000 and eventually start mining there.

**Comment by RainbowMiner** [comment]
Now for the https://cryptonote.social/ pool. 

1. edit `.\Config\userpools.config.txt` and add the following record (or edit one of the presets). Do not change the `$Wallet` or `$WorkerName`. These act as variables for your settings in pools.config.txt (see step 2)

```
    {
        "Enable":  "1",
        "Name":  "CryptonoteSocial",
        "PoolFee":  "0",
        "Algorithm":  "RandomWow",
        "CoinName":  "Wownero",
        "CoinSymbol":  "WOW",
        "Currency":  "WOW",
        "Protocol":  "stratum+tcp",
        "Host":  "cryptonote.social",
        "Port":  "2222",
        "User":  "$Wallet.$WorkerName",
        "Pass":  "x",
        "Region":  "US",
        "SSL":  "0",
        "Worker":  "$WorkerName",
        "EthMode":  ""
    },
```

2. now let RainbowMiner run for 1-2 rounds. It will inject your new userpool with name "CryptonoteSocial" into it's configuration. Then edit `.\Config\pools.config.txt` and find the newly added pool-entry "CryptonoteSocial". Add your Wow super address to parameter "WOW":

```
  "CryptonoteSocial": {
    "WOW": "YOUR_WOWNERO_SUPER_ADDRESS",
    "WOW-Params": "",
...
  },
```

... of course, you might as well add your WOW address to `.\Config\coins.config.txt` and then input `$WOW` into the pools.config.txt "WOW" parameter.

3. edit `.\Config\config.txt` and add your newly created userpool "CryptonoteSocial" to the "PoolName" parameter.

**Comment by chavesfop** [comment]
In both cases I got a warning, but the pools are listed in All Pools (in web interface)

```
Add-Member: /home/rodrigo/RainbowMiner/Modules/Include.psm1:5345
Line |
5345 |                      $Done | Add-Member $Pool_Name $Setup_Content
     |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot add a member with the name "WowneRo" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.

[91mAdd-Member: [0m/home/rodrigo/RainbowMiner/Modules/Include.psm1:5345
[96mLine |
[96m5345 | [0m                     $Done | [96mAdd-Member $Pool_Name $Setup_Content[0m
[96m     | [91m                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot add a member with the name "WowneRo" because a member with that name already exists. To overwrite the
[96m     | [91mmember anyway, add the Force parameter to your command.
[0m
```
[RainbowMiner_2021-05-03_10-58-44.txt](https://github.com/RainbowMiner/RainbowMiner/files/6418357/RainbowMiner_2021-05-03_10-58-44.txt)

**Comment by RainbowMiner** [comment]
Seems like you have a pool module with the name "WowneRo.ps1" in the `./Pools` folder. Also, it looks like we have stumbled over a PowerShell bug (or inconsistency) with case sensitivity where it should use case insensitivity. I have pushed a fix.
