### ISSUE TITLE
New crashing issues on Ethereum 

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1576]
New crashing issues on Ethereum .

Both clients have 1660Super but here is the debug file for one of them
[debug_2021-05-02.zip](https://github.com/RainbowMiner/RainbowMiner/files/6412391/debug_2021-05-02.zip)

**Comment by RainbowMiner** [comment]
Seems like Gminer has problems running SSL encrypted Ethash on Nicehash. I'll doublecheck and eventually disable SSL for this combination.

**Comment by RainbowMiner** [comment]
Solved. Thank you for reporting this!
