### ISSUE TITLE
RM 4.7.1.7 - TecraCoin (TCR) value not being displayed in Pool Balance

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1577]
TecraCoin (TCR) value not being displayed in Pool Balance

![image](https://user-images.githubusercontent.com/17214552/116842395-c7bdcb00-ac1f-11eb-99d2-6d0c85f70684.png)

[debug_2021-05-03.zip](https://github.com/RainbowMiner/RainbowMiner/files/6412924/debug_2021-05-03.zip)

**Comment by AnthonyBe** [comment]
Just noticed after re-enabling Fluxpools recently that this has now evolved to the following error:

`WARNING: Pool API (FluxPools) for TCR has failed.`

Checking [Fluxpools.net, ](https://fluxpools.net/)I _think_ they may have dropped TCR pool and are only doing Firo and Flux?

**Comment by RainbowMiner** [comment]
They really have dropped it. That's sad. I have updated our pool and balance modules.
