### ISSUE TITLE
benchmark per algo/coin?

### ISSUE THREAD

**Issue by gurkburk76** [RainbowMiner/RainbowMiner#1584]
So it would seem the ETC (ethereum classic) has overtaken Ravencoin(RVN) / KawPow according to whattomine on my old shitty 570 4gb cards but i don't think RBM gets that so i though i'de re-bench that by removing files from /Stats/Miners/
and AMD*Ethash_HashRate.txt and hope it would re-bench those. 
It didn't.
Waht the best way going about doing this WITHOUT re-benching everything? 👯‍♂️ 

(I did look into pools that i have and (ETC) is listed there on zergpool as a coin so that's all good.)

worth noting is that it looks like the ETC was recently added to zergpool, like in the last 24h or something.
That might throw things off.

**Comment by RainbowMiner** [comment]
You did right, but with the wrong files:
ETC has it's own algorithm. It is "Etchash". So you will have to delete all files `AMD*Etchash_HashRate.txt`
