### ISSUE TITLE
Disk Space Warning

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1586]
Would it be ok to add to rbminer.net a warning when disk space gets low? I just had a rig max itself out and get all the files corrupt.

**Comment by RainbowMiner** [comment]
Sure, very good idea.

**Comment by Yamanipanuchi** [comment]
I would second this.. I've had this happen more times than I would like to admit... Especially on my windows machines.

**Comment by RainbowMiner** [comment]
Implemented and tested :)
