### ISSUE TITLE
Possible math problem, although I hope it isn't.

### ISSUE THREAD

**Issue by OdinsTaint** [RainbowMiner/RainbowMiner#1591]
I hope this is real, but since the other 2 miners in the pic are both NOT mining this algo, I think the profitability calculator might be a bit off.  How do I correct this?  I deleted the nvidia benchmarks yesterday and re-ran the benchmarks for my 1070s, and I need to know how to get past this math error and mine real profitability.  Unless this is real, then WOOT [WOOT!

![math](https://user-images.githubusercontent.com/79120281/118120116-5f0fe480-b3bd-11eb-9c2b-716cac040bcc.png)

**Comment by OdinsTaint** [comment]
Zpool shows 600KH/s vs. the reported 7.21 GH/s.

![zpool](https://user-images.githubusercontent.com/79120281/118120760-62f03680-b3be-11eb-87f0-06d32d1cce0f.png)

**Comment by OdinsTaint** [comment]
And apparently zero hashrates on this one rig that is way out of balance.
![zerohash](https://user-images.githubusercontent.com/79120281/118120897-a185f100-b3be-11eb-9c67-1e426952260c.png)

**Comment by RainbowMiner** [comment]
Could be a Zpool API issue, as well. Maybe, please try to delete the `.\Stats\Pools\Zpool... .txt` file with Allium in the filename.

**Comment by OdinsTaint** [comment]
I deleted all benchmarks and rebenchmarked, same issue.  I did manage to go into config.txt and exclude allium algo and it got right.  I will definitely look to use the delete the stats file.  Thank you, and I will close this if I can.  Again, love your product, and the support is solid as well.

**Comment by RainbowMiner** [comment]
Thank you!
