### ISSUE TITLE
Issues when change devices in web configuration

### ISSUE THREAD

**Issue by chavesfop** [RainbowMiner/RainbowMiner#1596]
Hi RainbowMiner :) 

Every time I switch my configs in http://localhost:4000/setup.html some miners just re-benchmark.

I mine with CPU and GPU
Have checked: 
[x] CPU, [x] NVIDIA, [ ] GPU0, [ ] CPU0

Then, disabled the NVIDIA, and:

```
WARNING: Benchmarking in progress: 16 miners left, interval is set to 177 seconds.
 
Please be patient!
RainbowMiner will benchmark the following 16 miners with extended intervals!
These algorithms need a longer time to reach an accurate average hashrate.
After that, benchmarking will be much faster (3-6 minutes per miner).
If you do not want that accuracy, set DisableExtendInterval to 0 in your config.txt.
```

Ok, after this benchmark, I just turned on the NVIDIA in setup.html. Aaaaand...

```
WARNING: Benchmarking in progress: 16 miners left, interval is set to 177 seconds.
 
Please be patient!
RainbowMiner will benchmark the following 16 miners with extended intervals!
These algorithms need a longer time to reach an accurate average hashrate.
After that, benchmarking will be much faster (3-6 minutes per miner).
If you do not want that accuracy, set DisableExtendInterval to 0 in your config.txt.
```

Any glue why this happens?

**Comment by RainbowMiner** [comment]
Hi, thank you for reporting this - I have a vague idea. Do you remember, which miners have been re-benched?

**Comment by RainbowMiner** [comment]
I see. It's most probably, because these two miners are CPU + GPU miners. Let me check.

**Comment by chavesfop** [comment]
Yeah, just these 2 miners follow this flow:
download miner again, install, and rebench for CPU and GPU.

I'll do some tests in exclude devices option to try a workaround.
