### ISSUE TITLE
Incorrect wallet format for ZergPool --wallet is NOT valid only -u or --user

### ISSUE THREAD

**Issue by dlprentice** [RainbowMiner/RainbowMiner#1598]
ZergPool does **_not_** accept --wallet only -u or --user

However some miners use --wallet which doesn't work. The workers never show up.
![image](https://user-images.githubusercontent.com/34632073/118814589-4f414600-b87e-11eb-90d4-4414ea6d4c81.png)
Directly from ZergPool FAQ:
![image](https://user-images.githubusercontent.com/34632073/118815776-8e23cb80-b87f-11eb-9ec4-5186fa794b41.png)
The only way around this (at least to my knowledge) is to exclude miners that don't follow the right format.

**Comment by RainbowMiner** [comment]
Normally, the wallet goes into the appropriate miner parameters. For some, it's --user, -u for others it's --wallet. Which miner causes the trouble for which algorithm, actually?

**Comment by dlprentice** [comment]
At the moment, these miners are the ones that seem to be an issue:
SrbMiner,SrbMinerMulti

I don't recall a specific algorithm being an issue, the miners would just never show up for the address I wanted them to mine on ZergPool. I did not try another pool.

I brought this up on the ZergPool discord, and someone mentioned they had a similar issue.
![image](https://user-images.githubusercontent.com/34632073/118827068-07c0b700-b88a-11eb-8711-0f8d1f7dc57b.png)
