### ISSUE TITLE
New release: CPU mining threads

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#160]
The upcoming release v3.8.7.0 will contain an all new CPU thread configuration. Before I release this, I would ask some question to all those of you who mine on their CPU, so that I may fine tune.

The new config.txt parameters are:
- CPUMiningThreads
   you may enter any integer. It will add "-t [threads]" to cpu miner commandlines, if greater than 0
- CPUMiningAffinity
  this is by default fitting to your CPU. Leave this empty, If you do not want the --cpu-affinity parameter automatically added to cpu miner commandlines.

This works for all cpuminer-opt forks, it will not work for ClaymoreCpu, FireIce and Jceminer: 
Parameters added to the command line will be "-t [threads]" and "--cpu-affinity [affinity]" (if enabled)
The latter will be a hexadecimal bitmask.

The setup for affinity looks like that, now:
![image](https://user-images.githubusercontent.com/39437538/45625510-50969100-ba8d-11e8-9aed-922e8616fc9d.png)

If you want to override those values, add "-t" or/and "--cpu-affinity" to the miner's Params field in miners.config.txt.

- Will this help? Do you have suggestions?
- Would it make sense, to only use --cpu-affinity and leave -t?

**Comment by hernandn01** [comment]
I have a Celeron, two threads available. If I set threads=1 and affinity=0 for for the CPU miner, will everything else run affinity=1 (all or Ranbowminer and GPU miner windows)?

**Comment by RainbowMiner** [comment]
I think, windows will execute the remaining jobs on the free cpu.

**Comment by RetroShag** [comment]
I think what you are referring to is cpu priority = 0 (lowest priority) everything else will have higher priority than mining.  cpu affinity just spread the mining load.  Instead of 1 core at 100%, you wil have 2 cores at 50% each.

**Comment by hernandn01** [comment]
No I meant cpu affinity, to separate completely the cpuminer process in one core and everything else on the other core. I do not change cpu priority as it get unresponsive.

**Comment by RetroShag** [comment]
My bad, I misunderstood the question.  In your case, disabling affinity will load core 0 to 100%, but in my experience I found the system is more responsive with affinity enabled.

**Comment by hernandn01** [comment]
that is right, that is why I was asking, if now we can direct cpumininig to core 0, will Rainbowminer directly everything else to core 1?

**Comment by hernandn01** [comment]
https://stackoverflow.com/questions/19187241/change-affinity-of-process-with-windows-script

I think the same can be applied to all process that you start under powershell

**Comment by RainbowMiner** [comment]
very nice. Thanks for the link. I will try this out.
