### ISSUE TITLE
EnableAutoCoin keeps resetting to 0 when I set it to 1

### ISSUE THREAD

**Issue by dlprentice** [RainbowMiner/RainbowMiner#1600]
EnableAutoCoin keeps resetting on my server from 1 to 0. I don't have any wallets defined in my pool.

I'm using ZergPool, I have EnableAutoCoin set to 1, I have coins defined for use with "EnableAutoCoin": "1", I have one coin defined in FocusWallet that I eventually change with another coin symbol.

All seems to work as expected, but then eventually for no apparent reason "EnableAutoCoin": "1" turns into "EnableAutoCoin": "0"... stopping me from mining with this config. I suppose I could just define the wallet which I'll do, but still. I think this is a unintended behavior.

![image](https://user-images.githubusercontent.com/34632073/118975164-b2e07780-b941-11eb-8086-7119a3c443da.png)

**Comment by RainbowMiner** [comment]
This would be unintended, for sure. There is not much, that could change that value, when the rig is running in server mode. I'll have a look. Could you upload a Debug file?

**Comment by dlprentice** [comment]
Sorry for the late follow-up. Do you want debug logs from just the server or the clients or both? It's happened several more times since I posted this.
________________________________

**Comment by dlprentice** [comment]
To elaborate on this issue, I still find that the following option continues to reset itself to no 🙁

Enable forced mining a currency for a timespan after a block has been found (activate in coins.config.txt with PostBlockMining > 0) (yes/no) [default=no]:
________________________________
