### ISSUE TITLE
Add nsfminer (no-devfee open source Ethash miner).

### ISSUE THREAD

**Issue by fjvva** [RainbowMiner/RainbowMiner#1602]
Been using it for quite a while, better than ethminer and zero devfees. 

Website: https://github.com/no-fee-ethereum-mining/nsfminer

**Comment by RainbowMiner** [comment]
That miner works ok in principle, but causes a lot of trouble under certain conditions.
- doesn't work for >6 GPUs
- doesn't work with CUDA11.3 on Linux
- low hashrate on Windows, if API is enabled (we need this)
- caused severe hangs on some of my rigs (reboot needed)
... so I had sorted it out, currently.

**Comment by RainbowMiner** [comment]
I could actually add it to our repo, but disabled by default. Then you could try to switch it on.

**Comment by fjvva** [comment]
That would be awesome. I had stability problems with older versions but the current one has been pretty stable so far on a 4 GPU rig on ubuntu 20.04 with cuda 11.3.

**Comment by RainbowMiner** [comment]
Ok, added. I have just re-tested the new version on three of my rigs (those, that had problems with v1.3.7) and they benched the miner fine.

**Comment by fjvva** [comment]
I just tested it and it is working great. Thanks!
