### ISSUE TITLE
GrinMinerPro not starting (2xRX580)

### ISSUE THREAD

**Issue by fjvva** [RainbowMiner/RainbowMiner#1604]
I am not sure if it is an error on my side, so please check.

Log:
` HTML Dashboard at http://localhost:33500
JSON API listening on http://localhost:33500/api
         (Both also available over network)
         (API docs: https://grinpro.io/api.html)
*******************************************************
Init started for gpu 0 - Radeon RX 580
Using OpenCL device: Ellesmere (Advanced Micro Devices, Inc.)

Init completed for gpu 0 - Radeon RX 580 with SUCCESS
Init started for gpu 1 - Radeon RX 580
Using OpenCL device: Ellesmere (Advanced Micro Devices, Inc.)

Init completed for gpu 1 - Radeon RX 580 with SUCCESS
ERROR   Exception in: StratumConnect.cs # 197 # Connect Message: No such device or address
ERROR   Exception in: StratumConnect.cs # 197 # Connect Message: No such device or address
ERROR   GrinPro.io collects 1% as fee for the Grin Development Fund and 1% for further miner development.
ERROR   Please allow these connections:
ERROR   eu.stratum.cuckoomine.org, port 5555
ERROR   grinpro.mimwim.eu, port 5555
ERROR   Mining halted. Press any key.`

**Comment by RainbowMiner** [comment]
You have detected a miner at it's end-of-life. Ignore it, I'll remove it.

**Comment by fjvva** [comment]
Thanks! I'll close the issue as the change has been commited.
