### ISSUE TITLE
4.7.1.8 -> 4.7.2.0 - active curl.exe did not update

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#1608]
Just a small thing I noticed after the 4.7.1.8 -> 4.7.2.0 auto-update.
The curl.exe in my \Includes\curl\x64 folder was still the previous version (7.75). All the other curl x32 and x64 binaries updated.

I have curl enabled (due to ongoing asyncloader dying issues) on my Win10 x64 PC.

Did it fail to update the x64 curl.exe because it was in-use?

[debug_2021-05-24.zip](https://github.com/RainbowMiner/RainbowMiner/files/6532158/debug_2021-05-24.zip)

**Comment by RainbowMiner** [comment]
> Did it fail to update the x64 curl.exe because it was in-use?

Yes. 100%. I'll think about an alternative way. In the meantime - please update by hand.
