### ISSUE TITLE
Issue: Zergpool

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#161]
Any idea why I updated this morning and now zergpool is all out of wack? Mining HMQ1725 with all 4 rigs showing crazy accuracy. All rigs have switched to this since latest update.

![image](https://user-images.githubusercontent.com/42227809/45723708-84de8000-bb67-11e8-816c-2123be6334f0.png)

**Comment by Byrd1083** [comment]
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2394940/config.txt)
[RainbowMiner_2018-09-18.txt](https://github.com/RainbowMiner/RainbowMiner/files/2394941/RainbowMiner_2018-09-18.txt)
[errors_2018-09-18.main.txt](https://github.com/RainbowMiner/RainbowMiner/files/2394942/errors_2018-09-18.main.txt)
[RainbowMiner_2018-09-18_17-23-53.txt](https://github.com/RainbowMiner/RainbowMiner/files/2394943/RainbowMiner_2018-09-18_17-23-53.txt)
[ZergPool_HMQ1725_Profit.txt](https://github.com/RainbowMiner/RainbowMiner/files/2394944/ZergPool_HMQ1725_Profit.txt)

**Comment by RainbowMiner** [comment]
I will have a look to ZergPool. Whatever there is!

**Comment by RainbowMiner** [comment]
They deliver a crazy number! Ohmygod. 

![image](https://user-images.githubusercontent.com/39437538/45724074-c0ec0200-bbb4-11e8-9f55-bb5ed771b869.png)

Ok, to solve this for short, edit the pools.config.txt, search for DataWindow in ZergPool section and change it to "DataWindow": "estimate_current",

I will implement an additional check for the averaging algorithm, so that such faulty numbers will never make it into RainbowMiner again.

**Comment by RainbowMiner** [comment]
After that change, you need to delete all ZergPool profits in Stats\Pools\Zergpool*

**Comment by Byrd1083** [comment]
I can add it but mine does not have as described.
![image](https://user-images.githubusercontent.com/42227809/45724730-5d3de680-bb6c-11e8-84ef-0a03193a2548.png)
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2394995/pools.config.txt)

I have just been updating. I have not compiled new.

**Comment by Byrd1083** [comment]
I did as instructed and same results.

![image](https://user-images.githubusercontent.com/42227809/45724943-4946b480-bb6d-11e8-89a0-a86fedbde95d.png)
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2395008/pools.config.txt)

**Comment by RainbowMiner** [comment]
Oh dear! I just forgot: this will solve the problem only over some time. Everytime, there is no stat file for an algo, the erstimate_24h value (which is the cracy one). So the stat will always start with this bad number.
Zergpool really has a problem, here. I remeber, that they had this glitch some weeks ago, too. It has been x16r, then. I will change the basic pool setting, so that it will take the actual_24h number for start.

**Comment by RainbowMiner** [comment]
Ok, that solved the problem for my rigs. They just started to switch to hmq1725 at ZergPool, too.
- change DataWindow for ZergPool to "estimate_current"
- download new [ZergPool.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/ZergPool.ps1) file into your Pools directory. Use right-click / save as.. (the next release will have this change, too)

**Comment by RainbowMiner** [comment]
In the next release, I will include an extra number checker, so that those totally out of range numbers will be ignored.

**Comment by Byrd1083** [comment]
Should this line of code be put on all pools in pools.config as well?

change DataWindow for ZergPool to "estimate_current"

**Comment by RainbowMiner** [comment]
No, I would not do that. The default is an average, calculated of the two estimates: (estimate_current+estimate_last24h)/2 
It has been quiet accurate, in the past. It is only ZergPool, who had this maxed out numbers (now for the second time within 4 weeks).

**Comment by Byrd1083** [comment]
Understood.

**Comment by Byrd1083** [comment]
Okay that is fixed. However I have 1 rig that will not update. I always have to manually compile new. It also throws this error 203 real quick after reading configuration. It seems to load and run properly following this.

![image](https://user-images.githubusercontent.com/42227809/45727818-2a025400-bb7a-11e8-9228-fc4e9005d2a0.png)

**Comment by RainbowMiner** [comment]
Yes, this is looking like an admin right problem. Just try to switch ShowMinerWindows to "0", on this machine. The error 203 is a windows system error related to opening mining windows without stealing focus.

Q: did you edit the Start.bat on that system? It is very important to not edit that file. If you want to have an own Start.bat, make a copy of it and edit the copy, only.

**Comment by RainbowMiner** [comment]
I just changed the updater from external to internal, so that it no longer depends on the Start.bat. With the next release, you may edit the Start.bat to your needs :)

**Comment by Byrd1083** [comment]
No, I have not touched the start.bat but I do like to show miner window to ensure all cards clocks are locked in properly. Doesn't seem to effect performance.
