### ISSUE TITLE
Add `us` region to HeroMiners Pool

### ISSUE THREAD

**Issue by chavesfop** [RainbowMiner/RainbowMiner#1610]
According recent news in HeroMiners website, I check this urls in every "start" section in all coins, the coins above have a new `us` region :)

## Uplexa:  
Region | Country | Server
-- | -- | --
Europe | Germany | uplexa.herominers.com
Europe | Finland | fi.uplexa.herominers.com
America | Canada | ca.uplexa.herominers.com
America | USA | us.uplexa.herominers.com
Asia | HongKong | hk.uplexa.herominers.com
Asia | Singapore | sg.uplexa.herominers.com

## Swap:  
Region | Country | Server
-- | -- | --
Europe | Germany | swap.herominers.com
Europe | Finland | fi.swap.herominers.com
America | Canada | ca.swap.herominers.com
America | USA | us.swap.herominers.com
Asia | HongKong | hk.swap.herominers.com
Asia | Singapore | sg.swap.herominers.com

## Ravencoin:
Region | Country | Server
-- | -- | --
Europe | Germany | ravencoin.herominers.com
Europe | Finland | fi.ravencoin.herominers.com
America | Canada | ca.ravencoin.herominers.com
America | USA | us.ravencoin.herominers.com
Asia | HongKong | hk.ravencoin.herominers.com
Asia | Singapore | sg.ravencoin.herominers.com

## Mimblewimble:  
Region | Country | Server
-- | -- | --
Europe | Germany | mwc.herominers.com
Europe | Finland | fi.mwc.herominers.com
America | Canada | ca.mwc.herominers.com
America | USA | us.mwc.herominers.com
Asia | HongKong | hk.mwc.herominers.com
Asia | Singapore | sg.mwc.herominers.com

## MoneroV:  
Region | Country | Server
-- | -- | --
Europe | Germany | monerov.herominers.com
Europe | Finland | fi.monerov.herominers.com
America | Canada | ca.monerov.herominers.com
America | USA | us.monerov.herominers.com
Asia | HongKong | hk.monerov.herominers.com
Asia | Singapore | sg.monerov.herominers.com

## Grin:
Region | Country | Server
-- | -- | --
Europe | Germany | grin.herominers.com
Europe | Finland | fi.grin.herominers.com
America | Canada | ca.grin.herominers.com
America | USA | us.grin.herominers.com
Asia | HongKong | hk.grin.herominers.com
Asia | Singapore | sg.grin.herominers.com

## Ergo:
Region | Country | Server
-- | -- | --
Europe | Germany | ergo.herominers.com
Europe | Finland | fi.ergo.herominers.com
America | Canada | ca.ergo.herominers.com
America | USA | us.ergo.herominers.com
Asia | HongKong | hk.ergo.herominers.com
Asia | Singapore | sg.ergo.herominers.com

## Equilibra:
Region | Country | Server
-- | -- | --
Europe | Germany | equilibria.herominers.com
Europe | Finland | fi.equilibria.herominers.com
America | Canada | ca.equilibria.herominers.com
America | USA | us.equilibria.herominers.com
Asia | HongKong | hk.equilibria.herominers.com
Asia | Singapore | sg.equilibria.herominers.com

## Conflux:
Region | Country | Server
-- | -- | --
Europe | Germany | conflux.herominers.com
Europe | Finland | fi.conflux.herominers.com
America | Canada | ca.conflux.herominers.com
America | USA | us.conflux.herominers.com
Asia | HongKong | hk.conflux.herominers.com
Asia | Singapore | sg.conflux.herominers.com

## Conceal: 
Region | Country | Server
-- | -- | --
Europe | Germany | conceal.herominers.com
Europe | Finland | fi.conceal.herominers.com
America | Canada | ca.conceal.herominers.com
America | USA | us.conceal.herominers.com
Asia | HongKong | hk.conceal.herominers.com
Asia | Singapore | sg.conceal.herominers.com

## Bittube:
Region | Country | Server
-- | -- | --
Europe | Germany | bittube.herominers.com
Europe | Finland | fi.bittube.herominers.com
America | Canada | ca.bittube.herominers.com
America | USA | us.bittube.herominers.com
Asia | HongKong | hk.bittube.herominers.com
Asia | Singapore | sg.bittube.herominers.com

## Beam:
Region | Country | Server
-- | -- | --
Europe | Germany | beam.herominers.com
Europe | Finland | fi.beam.herominers.com
America | Canada | ca.beam.herominers.com
America | USA | us.beam.herominers.com
Asia | HongKong | hk.beam.herominers.com
Asia | Singapore | sg.beam.herominers.com

## Haven:
Region | Country | Server
-- | -- | --
Europe | Germany | haven.herominers.com
Europe | Finland | fi.haven.herominers.com
America | Canada | ca.haven.herominers.com
America | USA | us.haven.herominers.com
Asia | HongKong | hk.haven.herominers.com
Asia | Singapore | sg.haven.herominers.com

## Monero:
Region | Country | Server
-- | -- | --
Europe | Germany | monero.herominers.com
Europe | Finland | fi.monero.herominers.com
America | Canada | ca.monero.herominers.com
America | USA | us.monero.herominers.com
Asia | HongKong | hk.monero.herominers.com
Asia | Singapore | sg.monero.herominers.com

## Turtle:
Region | Country | Server
-- | -- | --
Europe | Germany | turtlecoin.herominers.com
Europe | Finland | fi.turtlecoin.herominers.com
America | Canada | ca.turtlecoin.herominers.com
America | USA | us.turtlecoin.herominers.com
Asia | HongKong | hk.turtlecoin.herominers.com
Asia | Singapore | sg.turtlecoin.herominers.com

## Quantum:
Region | Country | Server
-- | -- | --
Europe | Germany | qrl.herominers.com
Europe | Finland | fi.qrl.herominers.com
America | Canada | ca.qrl.herominers.com
America | USA | us.qrl.herominers.com
Asia | HongKong | hk.qrl.herominers.com
Asia | Singapore | sg.qrl.herominers.com

## ArQmA:
Region | Country | Server
-- | -- | --
Europe | Germany | arqma.herominers.com
Europe | Finland | fi.arqma.herominers.com
America | Canada | ca.arqma.herominers.com
America | USA | us.arqma.herominers.com
Asia | HongKong | hk.arqma.herominers.com
Asia | Singapore | sg.arqma.herominers.com

## Scala:
Region | Country | Server
-- | -- | --
Europe | Germany | scala.herominers.com
Europe | Finland | fi.scala.herominers.com
America | Canada | ca.scala.herominers.com
America | USA | us.scala.herominers.com
Asia | HongKong | hk.scala.herominers.com
Asia | Singapore | sg.scala.herominers.com

## Wownero <3 :
Region | Country | Server
-- | -- | --
Europe | Germany | wownero.herominers.com
Europe | Finland | fi.wownero.herominers.com
America | Canada | ca.wownero.herominers.com
America | USA | us.wownero.herominers.com
Asia | HongKong | hk.wownero.herominers.com
Asia | Singapore | sg.wownero.herominers.com

## Dero:
Region | Country | Server
-- | -- | --
Europe | Germany | dero.herominers.com
Europe | Finland | fi.dero.herominers.com
America | Canada | ca.dero.herominers.com
America | USA | us.dero.herominers.com
Asia | HongKong | hk.dero.herominers.com
Asia | Singapore | sg.dero.herominers.com

**Comment by sashizu** [comment]
PR #1611
