### ISSUE TITLE
Add Moscow pool

### ISSUE THREAD

**Issue by seoseo29** [RainbowMiner/RainbowMiner#1612]
Add the Moscow pool, thanks!
https://monero.pool-moscow.ru pps, pplns, solo
https://ethereum.pool-moscow.ru pplns
https://etc.pool-moscow.ru pplns
https://soloetc.pool-moscow.ru solo
https://haven.pool-moscow.ru pps, pplns, solo

**Comment by chavesfop** [comment]
Hello @seoseo29 

Take a look in this comment:
https://github.com/RainbowMiner/RainbowMiner/issues/1575#issuecomment-831382984

**Comment by seoseo29** [comment]
> Hello @seoseo29
> 
> Take a look in this comment:
> [#1575 (comment)](https://github.com/RainbowMiner/RainbowMiner/issues/1575#issuecomment-831382984)

Hello, I am the owner of these pools
