### ISSUE TITLE
VerthashMiner

### ISSUE THREAD

**Issue by spc789** [RainbowMiner/RainbowMiner#1613]
Is it possible to add support for verthashminer for vertcoin ?
Many ppl seem to have problems with it, but if I compile it from source it runs flawlessly over here (ubuntu 20.04)
(atleast the last 4 days)

Verthashminer is 0% dev free. (

In the end, if ppl should have issues with it, it's quite easy to block it in the miner setup isn't it ?

**Comment by RainbowMiner** [comment]
Isn't it already part of our miner library? We have this miner up and running: https://github.com/CryptoGraphics/VerthashMiner/releases

**Comment by spc789** [comment]
Indeed, my excuses. It seems that it benchmarked with 0 stats.
Is there any way to (parameter, option) to benchmark one specific algo with one specific miner instead of auto benching all of them to overcome issues like this ?
