### ISSUE TITLE
In some cases Rainbowminer doesn't detect GPU's

### ISSUE THREAD

**Issue by spc789** [RainbowMiner/RainbowMiner#1614]
In some cases rainbowminer doesn't detect a gpu at all, more details in the screenshots below
- lspci recognizes GPU's 
- amdgpu module is loaded.
- cards show up in /sys/classes/drm  
- rocm-smi works -> Edit : _seems_ to work

I intendendly left out the nvidia modules for testing, but neither nvidia nor amd gpu's show up 

- https://i.imgur.com/VIT6Jae.png 
- https://i.imgur.com/rIMjDiH.png

**Comment by ArSd-g** [comment]
Same as #1565 still not fixed...but i have some news;
- After last RBM update; one of my rig suddently get GPU (Vega56) detected by RBM (Rig1)
- I immediately tried on the other rig with exactly the same GPU/Brand (Vega56 Pulse) and it's not working
Funny thing is; there are both under Ubuntu Server LTS 18.04.5 + Amdgpu-20.40 as clone install and ...euh... i always learn that computering stuff works or not!!!! not sometime if i am lucky....
- Rig1: Asus z10pa-d8/2xXeon 26580V3
- Rig2: Asrock H110 Pro BTC/I5-7600
tired of this bug!

**Comment by spc789** [comment]
I tested a little bit further ... could it be there was an (automatically system upgrade on your side ?
Here I discovered the remnants of an dist upgrade, which couldn't work as my kernel and initrd are served from a tftpserver and the root file system is mounted over nfs. (I PXE boot my rigs).
What happened over here is that amdgpu thinks I run the 5.7.0 kernel because the release upgrade did upgrade the root file system (together with /lib/modules), but the kernel is not upgraded. 
When I install amdgpu with or without the -no-dkms option, it compiles against the 5.7.0 headers (due to the dist upgrade)
In the end of the install it can't remove the amdgpu module (rmmod amdgpu can't work because it's in use, forcing it to rmmod works neither, it segfaults the whole system). 
In the end of the amdgpu installer it doesn't pick up this error, *but installs the new libraries anyway*
What happens then, the kernel module is an older amdgpu version, but the opencli libraries are all compiled against the dist upgrade kernel source and the newer amdgpu version. 

The strange thing about this thing is, internally some amdgpu calls are working, and some ain't, throwing some errors for clinfo.
The even more strange thing is rocm-smi recognizes the cards (I suspect it doesn't use clinfo).

RBM uses clinfo to recognize the cards but due to the clinfo errors it doesn't find any.

I suspect it's a shared amdgpu installer and RBM detecting GPU bug. 

For RBM it could be wise to detect cards via the /sys/classes way and only rely on clinfo to make sure if there is an opencl platform installed ... or ... the RBM GPU detection could be made more error safe to incorporate some sanity checks. 
The amdgpu installer could use some major extra sanity checks too, but that's beyond the RBM scope. 

Can you check if this is a similar case in your rigs ? and check your kernel version, even if it's under LTS 18.04.5 ?

For RBM GPU check with clinfo, why it fail's I don't have a clue, probably some minor thing with big consequences, maybe I give it a look when those amdgpu version conflicts are resolved over here.

**Comment by ArSd-g** [comment]
Hello, thanks for your time (i'll give you every information i have with my noob/average level in sys admin, maybe some are usless!)
Also i did today's update (Both kernel 5.4.0-73 to *.*.*-74 and RBM libs) = same! Rig1=ok, Rig2=soon thrown from the 5th floor :D
So:
Rig1(detected): 5.4.0-74-generic 
[Rig1-update-5.4.0.73-74.txt](https://github.com/RainbowMiner/RainbowMiner/files/6592736/Rig1-update-5.4.0.73-74.txt)

Rig2(not detected): 5.4.0-74-generic
[Rig2-update-5.4.0.73-74.txt](https://github.com/RainbowMiner/RainbowMiner/files/6592738/Rig2-update-5.4.0.73-74.txt)

1-I'm suspecting also both of a mess between amdgpu-module/opencl libs on opencl > 1.2 (RX580 under latest driver/Archlinux zen-kernel= never had problems, you ll find how the *.pkg install this on Arch from aur)
[PKGBUILD.txt](https://github.com/RainbowMiner/RainbowMiner/files/6592378/PKGBUILD.txt)

2- _could it be there was an (automatically system upgrade on your side ?_ = exept canonical live patch; no!
But before testing on Rig2 (which got a messy Mesa drivers/amdgpu/opencl-amdgpu-pro mix)  
I did a full uninstall before fresh install (Drivers only)
Rig1(r)-Rig2(l) via ssh: 
![apt list --installed | grep amdgpu](https://user-images.githubusercontent.com/42816950/120671589-d3581800-c491-11eb-8e31-e5afd6ec08bc.png)
 
3- "amdgpu-install" works with "no-dkms" argument "amdgpu-pro-install" doesn't - So no choice = DKMS install...
Rig1: clinfo as user: 
[clinfo-rig1.txt](https://github.com/RainbowMiner/RainbowMiner/files/6592763/clinfo-rig1.txt)
Rig2: clinfo as user: 
[clinfo-rig2.txt](https://github.com/RainbowMiner/RainbowMiner/files/6592765/clinfo-rig2.txt)
 
4- another weird thing is with "amdgpu-pro-install -y  --opencl=pal,legacy,rocm --headless" doesn't install opencl-amdgpu-pro version but opencl-amdgpu, i need to manually get it after install with "apt install opencl-amdgpu-pro + opencl-amdgpu-pro-dev"

**Comment by spc789** [comment]
If you want to throw your rig from the fifth floor, give me a call first .... I'll be happely rescueing it from a near death experience and give it a second life ;) 

Just kidding ... 

It seems a lot has changed in the inner workings of amdgpu. I found out that : 

"There have been a number of 20.45 installs that have failed with a variety of kernels. 

So back to basics.  5.4.0-54 and earlier do have the pci_platform_rom kernel symbol.  This can be checked with grep "pci_platform_rom" /boot/System.map-your-kernel-name.  If it is there, then install amdgpu 20.30 or 20.40.  If it is not there, then install amdgpu 20.45 as this version no longer uses the "pci_platform_rom" call and should be kernel independent.  I expect 20.45 should work with 5.8.0 kernels but the results have been mixed.

The same missing kernel call issue exists for 18.04.5 LTS.  Kernels 4.15.0-115/117 and amdgpu 20.30 (for 18.04 hwe) installed correctly.  As the kernel number migrated upward, the 20.30 driver install broke, while the kernel build got errors but still produced a bootable kernel.  Kernels 4.15.0-128/129/130/132 are all missing the "pci_platform_rom" call.  I suspect all was well up to about 4.15.0-122 before the poo started hitting the fan.  I did get my 18.04 LTS system functioning again by upgrading the kernel from 4.15.0-130 to kernel 5.4.0-52 and re-installing amdgpu-pro 20.30. " 

So basically what is said is if you've use a recent kernel use amdgpu-pro > 20.45. 

Some things i tried was installing a amdgpu pro 20.50 on an 5.4.0-73-generic kernel, which didn't throw errors, and installed with dkms (amdgpu --opencl=legacy,rocr --no-32), but  no help, the same thing stayed : no platform found, which is quite strange because some clinfo calls DO work, others don't. 
The rocm-smi behavior stayed the same (it shows detected cards, but a simple command like rocm-smi --setfan 100% didn't do anything, did an amdgpu uninstall and then the following (notice on recent amdgpu versions the --opencl=pal option is depreciated)

So I did an for amdgpu 20.50 (for a freshly installed system)
amdgpu-pro --opencl=legacy,rocr --no-32 

It compiled ok with dkms and results are found here -> https://www.dropbox.com/sh/ofmi3i44br606f6/AAD0tXd_7mha3R95zUs5TiRWa?dl=0
This is for standalone mining system running on 20.04 

If one has a bit experience in linux one could overwrite the /boot ; /var/opt and /lib/modules directories 
on a non live system which are found in the link

Do an depmod afterwards, it will check if the dependencies for the modules is ok. (Should normally not be done, but hey what is normal those days)

Libraries must be installed for amdgpu20.50 must be installed afterwards manually

For amdgpu 20.50 mining user (mostly root) must be in render and, or video group.
Don't forget to update grub settings to incorporate amdgpu.ppfeaturemask=0xffffffff (else overclockking or fiddling with the timings will fail)
 
 That's it for the kernel part, for the library part, it could be that some calls don't work anymore because of the missing "pci_platform_rom" call... 
 That's work for later on the day

**Comment by ArSd-g** [comment]
Thanks for all these precious work and informations...testing futher as 20.50...one thing; user space or pro cmd to install aka ./amdgpu-pro-install or amdgpu-install "--opencl=legacy,rocr -....

**Comment by ArSd-g** [comment]
UPDATE ! and #enhancement 
I found the tricks:
1- add rocm repo for ubuntu as mentionned here: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu
2- instead of a full install of rocm components just install: rocm-smi-lib4.2.0
3- install amdgpu-pro drivers; like ./amdgpu-pro-install -y --opencl=pal,legacy,rocm --headless 
4- Both of system, miners, RBM detect f*** amdgpu f**** vega f**** 10

@RainbowMiner maybe you should consider to add this dep (rocm-smi-lib4.2.0) to your install script for amd

**Comment by RainbowMiner** [comment]
That's perfect! Thank you, for reporting back. I'll consider that rocm-smi-lib4.2.0 for installation.

**Comment by spc789** [comment]
@ArSd-g glad it resolved ... hi from Belgium btw

**Comment by itsdarklikehell** [comment]
> @ArSd-g glad it resolved ... hi from Belgium btw

hallo buurman, greetings from the netherlands!

**Comment by ArSd-g** [comment]
UPDATE @RainbowMiner 
After a clean reinstall under LTS Server 18.04.5 it appears that "rocm-smi-libs" is not the problem to allow RBM to detect AMD gpus; 
"ocl-icd-opencl-dev" and/or "ocl-icd-opencl" are! just make an "apt install ..." after amdgpu 20.40 driver installation (with a failed dkms build dgf) and your gpus will be detected.

I think it will be easier to add this as dependency during RBM install, also i still have rocm repo with rocm-smi-libs installed but i'm pretty sure it's useless...i typed a lot of apt install/remove/clean/purge before finding the solution so if someone can try this on a clean fresh install of ubuntu and confirm it would be great!

**Comment by acidpandas** [comment]
Not sure if this is relevant to the issue but, I was having the exact GPU detection issue with the RX 580. I've done a fresh install of Ubuntu 20.04 and followed the findings provided by @ArSd-g to install rocm and amdgpu-pro drivers and still GPU is not detected by clinfo or RBM.

However, if running clinfo or RBM as root, then GPU is detected. Is it expected that elevated privileges are needed to detect the GPU?

**Comment by vannevar-morgan** [comment]
Also have this problem.  The install.sh correctly detects the gpu but start.sh only detects the cpu, not gpu.
