### ISSUE TITLE
Latest update made my system think it had 0 gpus until reboot

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#1615]
Latest update made my system think it had 0 gpus until reboot

this happened on multiple machines, happens to be the day i went out of town lol

**Comment by ArSd-g** [comment]
lol look just right before your issue, #1614

**Comment by RainbowMiner** [comment]
> happens to be the day i went out of town lol

That's Murphy's Law. Sorry for that! So, the machines are back to work with all GPUs found, now?

**Comment by Nickfost** [comment]
All back online after reboot.


all Nvidia.



Nick Foster
-----------------
***@***.***
