### ISSUE TITLE
CPU mining server consistently forgets which devices it should be mining to 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#1616]
CPU mining server consistently forgets which devices it should be mining to. 

Dm me on discord

**Comment by RainbowMiner** [comment]
Using the web Setup page on a CPU-only rig did erase the "DeviceName" parameter in config.txt. It's fixed, now.

**Comment by chavesfop** [comment]
Thanks Rainbow, this issue break my nuts since I start to use RbMiner
![image](https://user-images.githubusercontent.com/1554252/121023036-46ef7300-c779-11eb-8e14-e24cd900764a.png)

<3
