### ISSUE TITLE
Custom Price Stats Average

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#163]
Suggestion, the option to use internal averages instead of what the pool posts.

Start off with current earnings when the miner is started, But start averaging the values as the pool get polled. This would give the option to change the average length to something other than 24hrs.

**Comment by RainbowMiner** [comment]
Thank you for the suggestion. RainbowMiner already does averaging, in the background. Our current averaging window is one week.
