### ISSUE TITLE
GMiner crashed & GetCPU Error

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1632]
Hi @RainbowMiner , I have Gminer crashed while the other miners were fine. Could you take a look of this debug file and dissect what was the issue? Thank you.

Is this error related to GMiner crashing?

> Faulting application name: GetCPU.exe, version: 1.0.0.0, time stamp: 0x93aefc93
> Faulting module name: KERNELBASE.dll, version: 10.0.22000.51, time stamp: 0xbfe98718
> Exception code: 0xe0434352
> Fault offset: 0x000000000004467c
> Faulting process id: 0x7fc0
> Faulting application start time: 0x01d76cd7e5620a84
> Faulting application path: X:\RBM\Includes\getcpu\GetCPU.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 69b702d0-cb6b-4e35-bea0-3f5bc360dbea
> Faulting package full name: 
> Faulting package-relative application ID: 

[debug_2021-06-29_2.zip](https://github.com/RainbowMiner/RainbowMiner/files/6732915/debug_2021-06-29_2.zip)

**Comment by RainbowMiner** [comment]
It says
> 19:12:01 Anti-hacking system detected modification of the miner memory. If you using an antivirus, add miner to antivirus exceptions

First of all, I would try to reboot the machine. Most of the times, there is some crashed Windows background process. If that doesn't help, double-check, if the RainbowMiner folder is on the exceptions list of your anti virus (if there is any). If that doesn't solve your problem, I'ld rather open an issue at the Gminer repository.

**Comment by RainbowMiner** [comment]
Ok, looks like you are not alone: https://github.com/develsoftware/GMinerRelease/issues/300
I have already added your issue there.

**Comment by astronyu** [comment]
Thank you. Looks like I'm not along having this issue.

**Comment by itsdarklikehell** [comment]
https://github.com/develsoftware/GMinerRelease/issues/300#issuecomment-872407706
