### ISSUE TITLE
Error about transcribing.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1636]
Getting the following error, I dont know if it is related to the previous error I posted.

`Stop-Transcript: /home/user/RainbowMiner/Modules/Core.psm1:3911
Line |
3911 |          Stop-Transcript > $null
     |          ~~~~~~~~~~~~~~~~~~~~~~~
     | An error occurred stopping transcription: The host is not currently transcribing.

[X] pressed - stopping script.                                                                                          
Stop-Transcript: /home/user/RainbowMiner/RainbowMiner.ps1:435
Line |
 435 |      Stop-Transcript
     |      ~~~~~~~~~~~~~~~
     | An error occurred stopping transcription: The host is not currently transcribing.
`

**Comment by RainbowMiner** [comment]
Related to issue #1635
