### ISSUE TITLE
BCD working on Zergpool now, please update to T-Rex 0.6.8

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#164]
T-Rex 0.6.8 (TEST)
NOTE: Changelog includes items from unsuccessful 0.6.7. The list below is based on 0.6.6 as previous version

Speed improvements: x16r/s, x17, c11, bitcore, bcd, sonoa - 1-2%
Add functionality for setting failover pools in cmd line by specifying -o, -u and -p arguments multiple times.
New cmd line arguments:
    --gpu-report-interval: controls how often GPU report stats are displayed (by default every 5th share).
    --no-color: disable coloured output
    --time-limit: maximum time [s] to mine before exiting the program.
    --quiet: disable GPU stats output
Add ability to change averaging hashrate window and GPU report interval via API or web browser on the fly (without stopping the miner) - see the help file.
Fix for the hung issue
Fix for the long log path issue on Linux

Cosmetic changes:
Showing configured pools upon start up
Displaying colour representation of hashorders for x16r/s
Miner uptime is displayed as part of GPU stats report

Windows (x64)
CUDA 9.1/9.2:
https://mega.nz/#!DdE3kIwC!uQ7NMnnwQwjnzMZ2igvPA8fI9bUhleu0ocATPGqWGDA

**Comment by RainbowMiner** [comment]
Thank you! Done :)
