### ISSUE TITLE
xmrig, doesn't support json files

### ISSUE THREAD

**Issue by mderoo75** [RainbowMiner/RainbowMiner#1642]
xmrig and xmrig based program's is giving an error that, the first character, should be a {

and it's using it's default config instead and mining on the cpu and not on the gpu.

I Tested, with the latest second release of today, buth the same problem

[xmrigmr.txt](https://github.com/RainbowMiner/RainbowMiner/files/6760154/xmrigmr.txt)

**Comment by RainbowMiner** [comment]
Oh dear! Is this a Windows or a Linux machine?

**Comment by RainbowMiner** [comment]
Ok, my bets are on Windows with pre installed Powershell 5 - this would eventually create BOM at the beginning of these files. Please update to Powershell Core 7.1.3 until I fix this backwards incompatibility.

**Comment by RainbowMiner** [comment]
I have updated the file `.\Modules\Include.psm1` for backwards compatibility to Powershell5. Either install Powershell Core 7.1.3 or download the updated file (https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Modules/Include.psm1 - right-click and Save as) into your `.\Modules` folder to solve this issue.

**Comment by mderoo75** [comment]
Wow you are great and have a solution for it, so soon, and without knowing, what version of Powershell and that I am using on Windows 10/ 11. (maybe the .txt, gives a clue)

I am now going to test it!

And what do you need to-do to reset al xmrig ans xmrig based programs, only, so it does a Re-Benchmark?

**Comment by RainbowMiner** [comment]
> And what do you need to-do to reset al xmrig and xmrig based programs, only, so it does a Re-Benchmark?

Open http://localhost:4000, go to Benchmarks page. There you can select Xmrig at the Miner column. Check all or selected rows and clock Benchmark selected

**Comment by RainbowMiner** [comment]
> On Windows 11, the developers/ preview build, it doesn't work!

Did you try to install Powershell Core 7.1.3?

**Comment by mderoo75** [comment]
no not yet, installed the newer powershell

Buth both fails, with kawpow, with win10 and win11

**Comment by RainbowMiner** [comment]
It would help me a lot, if you could upload a RainbowMiner "Debug file" from that Windows11 system. Just open `http://localhost:4000` and find "Debug file" on the left-hand side. Click on it and RainbowMiner will generate a zip file, that is ready to be uploaded here (all private information will be x-ed out).

**Comment by RainbowMiner** [comment]
Another note: if you still got problems with that error + Xmrig, it might be the case, that you have old "run_*.json" files in use. So look into folder `.\Bin\ANY-Xmrig` and delete all files, that match `run_*.json` (all files, that start with `run_`).

**Comment by mderoo75** [comment]
[debug_2021-07-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/6765163/debug_2021-07-05.zip)

**Comment by RainbowMiner** [comment]
>  is there an reason that ms is not upgrading automaticly or doesn't it mather?

Powershell Core is a somehow standalone product. It's the much improved Powershell5

**Comment by mderoo75** [comment]
Yeah, you where right again, deleting de run*.json files helped

If you change the Windows priority of the powershell program to abovenormal even on slow computers, the script works much better, it is now at belownormal! And it kills better locked or hogging programs of the cpu!
