### ISSUE TITLE
Method Invocation failed Error

### ISSUE THREAD

**Issue by da1712** [RainbowMiner/RainbowMiner#1646]
i am attaching the error i am getting can you help me to fix it.
![Screenshot_3](https://user-images.githubusercontent.com/87229704/125161120-26627080-e19e-11eb-816e-1551566dc759.png)

**Comment by RainbowMiner** [comment]
Could you please upload a Debug file? Just open `http://localhost:4000` and click "Debug file" on the left-hand side. RainbowMiner will create a zip file with your current config (all privacy relevant information, wallets, etc. will be xxx-ed out).

**Comment by da1712** [comment]
[debug_2021-07-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/6796888/debug_2021-07-11.zip)
the image i sent previously of method invocation that error is gone now but when i start the rainbow miner in the consloe while loading balance modules it give some errors, but it starts working though without any trouble. Just it shows some error in console.

**Comment by RainbowMiner** [comment]
I see. It's mostly failing API calls on some pools, so nothing to worry about. Most of them will be back online, after some time.

_BUT_

I would strongly recommend to reduce your number of enabled pools. It takes a lot of time to grab all data from all pools and format them into machine readable format. Also, your earnings will be distributed too much. That will have a negative impact on the efficiency of your system. A good selection would be

```
    "PoolName":  [
                     "Ethermine",
                     "MoneroOcean",
                     "Nicehash",
                     "ProHashing",
                     "ZergPoolCoins"
                 ],
```

Ethermine -> mining ETH directly
Nicehash -> mine many algorithms and get them converted directly to BTC (but sign up with them and use their mining wallet address!)
ProHashing -> mining some algorithms and get them converted to LTC (or different)
ZergPoolCoins -> mining many algorithms and coins and get them converted directly to BTC

**Comment by da1712** [comment]
i am even having trouble with OC, i set up oc to to 
powerlimit 80
memclock +1500
Coreclock -200 on profile 9 whcih i added manually and assigned it to ethash. But its not working
i have 6x3080ti even after profile 9 is assiged to ethash the hashrate is stagnant to 58, it should mine at around 65 with these settings.

**Comment by da1712** [comment]
and while benchmarking ctxc and xwp earnings was showing $1100 per day. can you check that too why was it showin that number

**Comment by da1712** [comment]
I even own gampool.com can you add my pool  in rainbowminer, we are adding more 15 coins in few days. So it will be great help if you can add our mining pool in rainbow miner.

**Comment by itsdarklikehell** [comment]
I have this same issue btw..

**Comment by itsdarklikehell** [comment]
[debug_2021-07-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/6820456/debug_2021-07-15.zip)
