### ISSUE TITLE
Rig stuck in non-existant rentals for a week

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1647]
I just checked my rig after getting back from holiday and found that they have been mining non-existant rentals???
[debug_2021-07-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/6826110/debug_2021-07-15.zip)

**Comment by samdave123** [comment]
https://www.miningrigrentals.com/rigs/184521
https://www.miningrigrentals.com/rigs/184457

**Comment by samdave123** [comment]
I think this may have been caused by failure to resolve the MRR DNS? My pihole was blocking www.miningrigrentals.com for some reason. RBM needs to be able to figure out when to end a rental even when this happens, otherwise it'll get stuck.

**Comment by RainbowMiner** [comment]
Yes, that is most probably the main cause - since a renter can extend a rental, RainbowMiner checks the current rental-end time online, each round.

**Comment by samdave123** [comment]
I've fixed my Pihole so this isn't being blocked, but could RBM perhaps not do this check if rental extensions are disabled, or just assume there's no extensions if unable to contact MRR?

**Comment by samdave123** [comment]
Otherwise RBM will continue the rental forever.

**Comment by RainbowMiner** [comment]
Yes, that would be better. I will change the code accordingly.

**Comment by RainbowMiner** [comment]
Ok, that should be solved.

**Comment by samdave123** [comment]
Awesome, thank you! That's one less thing to worry about! Thank you for all your hard work making RBM the best mining automation software ever <3
