### ISSUE TITLE
Trex 0.6.8 Color disabled

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#165]
Can option --no-color be left as an individual option in Params and not be color disabled by default? Also miner can now be controlled by HTTP Api call but miners are sharing the same HTTP port. Can this be enabled with --api-bind-http 0.0.0.0:x ?

![image](https://user-images.githubusercontent.com/41829368/45830707-eebb6e80-bcba-11e8-859d-72ee18f4fba3.png)

**Comment by RainbowMiner** [comment]
Yes, I can, of course remove the --no-color option. I did not explore the --api-bind-http command, yet. At the moment, only the telnet ports are relevant for RainbowMiner. Maybe, we switch to http for Trex. I will have a look.
