### ISSUE TITLE
Skip Benchmark and just run selected Miners

### ISSUE THREAD

**Issue by oyi77** [RainbowMiner/RainbowMiner#1651]
Hi, i would like to know if there are something i can do, to skip benchmarking. since i am running this on a cloud pc. so everytime i run this it takes too much time to benchmarking. I know there were a solution like, direct use the original miners. But i like the feature of this mining that can auto choose between GPU and CPU, if it exist. and also a central monitoring system.

Regards!

**Comment by itsdarklikehell** [comment]
There is an central monitor system it's [rbminer.net](rbminer.net)  
There is also an option in the config to shorten or speed up the benchmarking process in exchange for some less accurate benchmark values offcourse, but I forgot what it was.

**Comment by RainbowMiner** [comment]
Actually, a Speed-Start feature might prove as pretty useful. We could start with all user's average for a distinct GPU or CPU (if available in the central monitoring database) - I will think about that.

A second approach would be to backup all miner stats of a similar rig and copy them into the Stats folder of the new rig.

**Comment by oyi77** [comment]
> Actually, a Speed-Start feature might prove as pretty useful. We could start with all user's average for a distinct GPU or CPU (if available in the central monitoring database) - I will think about that.
> 
> A second approach would be to backup all miner stats of a similar rig and copy them into the Stats folder of the new rig.

Okey i will try it, but i think, the first solution would be great. So we could use the best setting available from the central monitoring database. Its a slightly great feature, to copy and use best available setting for same device. I would wait for it.

The second solution was good though but it doesn't solve a problem if the cloud machine was resetted before the benchmark even done. Thankyou!

**Comment by RainbowMiner** [comment]
@oyi77 I have added a new "Fastlane for Benchmark" feature. If enabled, RainbowMiner will try to download average, minimum or maximum values from rbminer.net, instead of running all benchmarks locally.

**Comment by oyi77** [comment]
@RainbowMiner thank you for your hardwork dude. RainbowMiner is a perfect tools to mining with a lot of great features

**Comment by RainbowMiner** [comment]
Please wait with testing, until I give you the final ok. During testing, I found out some smaller issues with that new feature. Will be solved soon.

**Comment by oyi77** [comment]
Okay i got it, i still experimenting and tweaking to make it suitable for cloud based too. Thanks dude, i am waiting for your good news
