### ISSUE TITLE
Linux: RainbowMiner script exiting after a couple days uptime consistently

### ISSUE THREAD

**Issue by mgbowe1** [RainbowMiner/RainbowMiner#1655]
Every couple of days the RainbowMiner script exits with an error at line 23 of start.sh which seems to be the end of the loop.

Note: I'm using zsh on Arch linux, and this issue started a few weeks ago. 

I've attached my most recent log, it just happened again this AM. 
[RainbowMiner_2021-07-29_09-13-51.txt](https://github.com/RainbowMiner/RainbowMiner/files/6900812/RainbowMiner_2021-07-29_09-13-51.txt)

**Comment by RainbowMiner** [comment]
Could you please create a Debug file? Just click "Debug File" at http://localhost:4000 (it's down on the left hand side)

**Comment by mgbowe1** [comment]
It didn't think to get the exact error message before restarting the miner this time. The next time it happens I'll update the ticket. I can create a debug file now, but I'm not sure how helpful it will be. In the instances where this has happened, the whole process gets killed and I can't access the web interface because the webserver isn't running.

**Comment by mgbowe1** [comment]
[debug_2021-07-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/6902387/debug_2021-07-29.zip)

**Comment by mgbowe1** [comment]
This issue seems to have been resolved.
