### ISSUE TITLE
and what the heck is that ?

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#1656]
$ContestWallet = if ($Session.Config.Coins.ETH.Wallet -match "^0x[0-9a-f]{40}$") {$Session.Config.Coins.ETH.Wallet} else {"0xaaD1d2972f99A99248464cdb075B28697d4d8EEd"}

i wont even comment , you know what im talking about

**Comment by RainbowMiner** [comment]
Gminer is currently having a contest running (in case you have missed it: https://github.com/RainbowMiner/miner-binaries/releases/tag/v2.61-gminer and https://bitcointalk.org/index.php?topic=5034735.msg57497206#msg57497206, it's on their Telegram channel, too). I automatically enabled the contest for every RainbowMiner user, who has an ETH wallet in the coins.config.txt, hoping some of us could catch the lottery. In case there is no ETH wallet, I have put in mine.

**Comment by mo35** [comment]
some announce woulda been nice , because i manually added param --contest_wallet  , and after update i noticed its getting overwriten by diff eth address , bit sneaky

**Comment by RainbowMiner** [comment]
> some announce woulda been nice , because i manually added param --contest_wallet , and after update i noticed its getting overwriten by diff eth address , bit sneaky

Did you put the "--contest_wallet 0x.." into the miners.config.txt (parameter "Params")? This input should always override the default values. In case it didn't, that's a bug.

**Comment by mo35** [comment]
for some reason it got overwritten , anyways no probs , but please mention such things next time in change notes , so prolly other people can add their eth wallets also.
