### ISSUE TITLE
Is PauseBetweenRentals still required to give time for RBM to calculate rental prices?

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1662]
Is PauseBetweenRentals still required to give time for RBM to calculate rental prices?

I remember a while back this was added so that RBM can start calculating profitability for rentals. Ideally, I want the rig ready to go with accurate pricing as soon as the previous rental ends. Is a pause still required?

**Comment by RainbowMiner** [comment]
Yes, it's still a good idea to insert a short pause in between two rentals. Especially, during times of huge BTC price swings. It doesn't need to be long - I have set it to 15 minutes on my rigs, currently.
