### ISSUE TITLE
Warning message needing cuda 9.2

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#167]
Version 3.8.7.3 does not account for Cuda 10 where all miners where working with new driver version 411.63 on 3.8.7.2. Only the following are available to mine

![image](https://user-images.githubusercontent.com/41829368/45878539-9ccc2480-bd5e-11e8-866f-31f21ffd7298.png)

**Comment by hernandn01** [comment]
![image](https://user-images.githubusercontent.com/41829368/45879767-ed458100-bd62-11e8-92d2-cca438d597ff.png)

**Comment by hernandn01** [comment]
in addition could there be a way to notice the warning / error on a fix place instead of trying to catch it while its scrolling away, maybe after the run.

**Comment by RainbowMiner** [comment]
Ohh! I see. I will update at once.

**Comment by RainbowMiner** [comment]
Done. Sorry for that. With the new release, it should account for CUDA 10
