### ISSUE TITLE
Autoupdate stuck in loop

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#168]
The autoupdate charesh RBM every time. It is stuck in a restart loop. The workaround is to manually exit and restart the application.

![image](https://user-images.githubusercontent.com/35561346/45883217-b5652a80-bdb0-11e8-846e-be6a960bcdf4.png)

**Comment by RainbowMiner** [comment]
Now that is weird! For me, it is working perfecly. Ok, let's see what is going on. Which version of powershell have you installed?

**Comment by RainbowMiner** [comment]
Normal behavior would be, that RainbowMiner starts a new instance of itself, waits for it to come up, then, terminates itself.

**Comment by RainbowMiner** [comment]
Would you please send me the Logs\errors_2018-09-21.main.txt file, if it exists?

**Comment by RainbowMiner** [comment]
Have you run Start.bat with Admin rights?

**Comment by ebojali** [comment]
No, why would that be necessary since I've not done that before? Additionally how would I make sure that it is started with admin rights when put in startup folder so it is started with windows reboot?

**Comment by hernandn01** [comment]
I had created a bat file with admin rights and stuck that on the startup folder. That stopped working and neither creating a scheduled task that runs at startup works now. So I would appreciate too a way to start Rainbowminer at windows startup.

**Comment by RainbowMiner** [comment]
Ah! Ok :) That explains a lot. 
I will add a fallback-update feature for those, who did not start as admin. It is not possible for RainbowMiner to recreate itself, if it hasn't admin rights, so the update fails.

**Comment by RainbowMiner** [comment]
For the admin rights at startup, I created a scheduled task with the following parameters:

`Create a basic task`
Tab "General":
- check `Run only when user is logged in`
- check `Run with highest privileges`
- Configure for: `Windows Vista, Windows Server 2008`
Tab "Trigger":
- check `When I log in`
Tab "Actions": 
- Action=`Start a program`
- Program/Script=`cmd`
- Add Arguments=`/c "C:\Users\RainbowMiner\Desktop\current-version\Start.bat"`
- Start In=C`:\Users\RainbowMiner\Desktop\current-version\`

At least, that is how it is working for me :)

**Comment by RainbowMiner** [comment]
Another question: does a new Rainbowminer pop up? Or will it be simply stuck in the old window?

**Comment by ebojali** [comment]
For me it is stuck in the old window, no new miner pop up.

**Comment by RainbowMiner** [comment]
Would you be so kind and try the following?
Extract this file into your RainbowMiner directory and click Test.bat
[Test.zip](https://github.com/RainbowMiner/RainbowMiner/files/2405717/Test.zip)

And show me the result?

**Comment by RainbowMiner** [comment]
Ok, I added a fallback to legacy update to the core. 
@ebojali: please tell me, if you are ready for the update, because the autoupdate will run into this issue, for a last time. If you are ready, I will create a new release. After the update the problem should be gone.

Anyway, I am very interested in the result of the Test.bat :)

**Comment by ebojali** [comment]
Sorry, birthday party... Will update you tomorrow. 😀

**Comment by RainbowMiner** [comment]
No need to hurry! Have a nice party! 🎂

**Comment by ebojali** [comment]
Ok, I ran the test.bat, this is how it looks like :)
![snip20180922_23](https://user-images.githubusercontent.com/35561346/45919142-79ee5d00-be91-11e8-8d5b-91de06f964c4.png)

**Comment by ebojali** [comment]
I noticed that the problem appears when pressing U as well even though there is nothing to update. Perhaps a check could be implemented?
![snip20180922_25](https://user-images.githubusercontent.com/35561346/45919174-ea957980-be91-11e8-97fc-9e913de52818.png)

**Comment by RainbowMiner** [comment]
Thank you very much for the checks. Yes, I already have implement an administrator check. The update will fallback to the legacy updater, if not in admin mode.

**Comment by RainbowMiner** [comment]
Super, I could replicate this on a second pc, using powershell 6.0.2. It looks like it is not an administrative problem, but a problem with powershell 6.0.2. I would recommend, that you update to the new powershell core 6.1.0. It comes with vastly improved performance, and, the creation of childs work properly. I will now implement a check for the powershell version, so that this error will not happen to anybody else, using the powershell 6.0.2

**Comment by RainbowMiner** [comment]
Ok, I released new version v3.8.7.5 - all users who are still using v3.8.7.4 (or below), together with PowerShell 6.0.2 (or below) should exit RainbowMiner and start "Updater.bat" by hand. After that, all automatic updates will work again :)
