### ISSUE TITLE
Monitoring Site down? 

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1696]
@RainbowMiner 
![Screenshot_20210809-080223_Chrome](https://user-images.githubusercontent.com/801414/128728447-b1375e2e-40ec-464b-8893-10cb81412d36.jpg)

**Comment by RainbowMiner** [comment]
Thank you for reporting this! I'll check asap.

**Comment by RainbowMiner** [comment]
It seems to have a server issue and will take a short time, until it's back.

**Comment by RainbowMiner** [comment]
Ok, server is back. Sorry for the inconvenience.
