### ISSUE TITLE
Remote Workers not Displaying

### ISSUE THREAD

**Issue by mcangeli** [RainbowMiner/RainbowMiner#1697]
After the 4.7.3.6 update last night/this morning, the remote workers are no longer being displayed even though their consoles say they are connected to the 'server'
![image](https://user-images.githubusercontent.com/6456272/128856719-2d95ff24-74a9-4f93-b495-23e45a989d3b.png)

**Comment by RainbowMiner** [comment]
Oh. I see - I'll fix it asap.

**Comment by RainbowMiner** [comment]
Ok. Fixed.

**Comment by mcangeli** [comment]
Yep. Is working now.

**Comment by TheeeX** [comment]
Hi, I am not able to see Remote workers, 
Clients show that it's connected to the server, but the Remote Workers tab is not visible on the server dashboard.
Also If I open http://localhost:4000/clients on the server machine, it shows all the clients.
Also, I can see the worker and server at https://rbminer.net

What could be the issue?
