### ISSUE TITLE
1 Rig = 2 MRR instances

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1699]
I have a rig with 2070 supers and 3060s and I'm trying to set it up so they can be rented independently on MRR. I've entered separate worker names in the devices config

```
  "RTX2070SUPER": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": "cynthia"
  },
  "RTX3060": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "100",
    "Worker": "cynthia2"
  }
```

However, I don't seem to be able to get 2 separate entries in the MRR config file. Please can you point of what I'm missing?

**Comment by RainbowMiner** [comment]
Two things to check in config.txt:
- 1st make sure, your "WorkerName" in config.txt is different from the two workernames in devices.config.txt. I tend to simply add a "0" to "WorkerName". E.g. in your case `"WorkerName": "cynthia0",`
- 2nd make sure you are not using "legacy" for "MiningMode". E.g. use `"MiningMode": "device",`

**Comment by RainbowMiner** [comment]
In case, no extra entry in mrr.config.txt is created, even if you have considered the above hints: make a backup of that file and then delete it. RainbowMiner should recreate it, with all workernames included. But normally, the hints should help.

**Comment by acos0874** [comment]
I've tried the above except waiting for 3 hours so I'll leave it a while.

**Comment by acos0874** [comment]
[debug_2021-08-12 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/6977568/debug_2021-08-12.1.zip)

Sorry it's still not working

**Comment by acos0874** [comment]
"UseWorkerName": "agnus,bertha,cynthia,darcy,emily",

I think this variable might be the problem. I'll wait till my current rental ends and then change it.

**Comment by RainbowMiner** [comment]
> "UseWorkerName": "agnus,bertha,cynthia,darcy,emily",
> I think this variable might be the problem. I'll wait till my current rental ends and then change it.

100% that's the problem - I have totally forgotten about that setting. It's for selection of specific workers on a rig.
