### ISSUE TITLE
Benchmark Issue

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#17]
benchmarks are not working. 
![image](https://user-images.githubusercontent.com/30832110/44080143-cadc9642-9fc8-11e8-80ec-81f9c89bd924.png)

**Comment by RainbowMiner** [comment]
Sorry for that! It could be a problem with the config files. 
Please stop RainbowMiner and update to new bugfix release. This should cleanup.

https://github.com/RainbowMiner/RainbowMiner/releases/download/v3.8.0.2/RainbowMinerV3.8.0.2.zip

RBM

**Comment by RainbowMiner** [comment]
If the problem persists, even with v3.8.0.3 (https://github.com/RainbowMiner/RainbowMiner/releases/download/v3.8.0.3/RainbowMinerV3.8.0.3.zip), please let me know.

**Comment by RainbowMiner** [comment]
Ok, I got it. Sorry for the inconvenience. There has been a problem with benchmarks, when the usePowerPrice has been set to "1". This problem should now be solved:

Please download and install bugfix release v3.8.0.4
https://github.com/RainbowMiner/RainbowMiner/releases/download/v3.8.0.4/RainbowMinerV3.8.0.4.zip

RBM

**Comment by RainbowMiner** [comment]
@hernandn01 : would you please zip your Logs folder and paste it here? Also, please provide your current config.txt

**Comment by hernandn01** [comment]
I am using v3.8.0.4 and using usePowerPrice = 1 and benchmarks on all cards are working now. I assumed usePowerPrice was the actual cost in decimals of KWH

**Comment by RainbowMiner** [comment]
Super :) Phew! I am happy, if this issue is resolved.

- **PowerPrice** = actual cost for 1 kWh as decimal. E.g. 0.23
- **PowerPriceCurrency** = currency of PowerPrice. E.g. USD
- **UsePowerPrice** = if set to 1, the electricity cost will be substracted from the actual miner's profit
- **CheckProfitability** = if set to 1, RainbowMiner will stop mining, if no more miners are profitable. If profitability returns, mining operation will be resumed automatically.

**Comment by hernandn01** [comment]
How about a mix solution for the cards that do not report power consumption. I have 1050 ti that do not. Maybe a setting in miners.config.txt for those cards? Consumption should be observed at the wall for those cards and set the watt number static per algo.

**Comment by RainbowMiner** [comment]
@hernandn01 : Good idea, even though it implies a lot of hand work. I will think about it.

**Comment by RainbowMiner** [comment]
@hernandn01 : regarding the problem with the GTX 1050ti, I found it is a known problem with the NVIDIA drivers. It seems, Nvidia disabled the watt reading for this card model.
https://devtalk.nvidia.com/default/topic/1024744/linux/nvidia-387-12-breaks-power-reading-in-nvidia-smi-/1
So, adding a static power value to the miners.config.txt looks like the only safe solution, at the moment.

**Comment by RainbowMiner** [comment]
@hernandn01 : could you open the web-interface at http://localhost:4000 , click "Selected Devices". You will see a table with all your mining devices. Now click on the little "+", in the row of your GTX1050Ti.
Would you please copy-and-paste the full data window here? (it is the opened, with the grey background). Maybe we can aproximate the powerconsumption.

**Comment by hernandn01** [comment]
I have two 1050 ti, copied both, powerdraw is NaN as mentioned in your previous link from Nvidia 

Index: 2
PlatformId: 1
PlatformId_Index: 0
Type_PlatformId_Index: 0
Vendor: "NVIDIA"
Vendor_Name: "NVIDIA Corporation"
Vendor_Index: 0
Type_Vendor_Index: 0
Type: "Gpu"
Type_Index: 1
OpenCL: {"AddressBits":64,"Available":true,"CompilerAvailable":true,"DoubleFpConfig":"FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma","EndianLittle":true,"ErrorCorrectionSupport":false,"ExecCapabilities":"ExecKernel","Extensions":"cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer","GlobalMemCacheSize":98304,"GlobalMemCacheType":2,"GlobalMemCachelineSize":128,"GlobalMemSize":4294967296,"ImageSupport":true,"LocalMemSize":49152,"LocalMemType":1,"MaxClockFrequency":1493,"MaxComputeUnits":6,"MaxConstantArgs":9,"MaxConstantBufferSize":null,"MaxMemAllocSize":1073741824,"MaxParameterSize":4352,"MaxReadImageArgs":256,"MaxSamplers":32,"MaxWorkGroupSize":1024,"MaxWorkItemDimensions":3,"MaxWorkItemSizes":"1024 1024 64","MaxWriteImageArgs":16,"MemBaseAddrAlign":4096,"MinDataTypeAlignSize":128,"Name":"GeForce GTX 1050 Ti","ClVersion":"OpenCL C 1.2 ","Platform":"@{Profile=FULL_PROFILE; Version=OpenCL 1.2 CUDA 9.2.156; Name=NVIDIA CUDA; Vendor=NVIDIA Corporation; Extensions=System.Object[]}","PreferredVectorWidthChar":1,"PreferredVectorWidthShort":1,"PreferredVectorWidthInt":1,"PreferredVectorWidthLong":1,"PreferredVectorWidthFloat":1,"PreferredVectorWidthDouble":1,"Profile":"FULL_PROFILE","QueueProperties":"OutOfOrderExecModeEnable, ProfilingEnable","SingleFpConfig":"FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt","Type":"Gpu","Vendor":"NVIDIA Corporation","VendorId":4318,"Version":"OpenCL 1.2 CUDA","DriverVersion":"398.36"}
Model: "GTX1050Ti"
Model_Name: "GeForce GTX 1050 Ti"
Name: "GPU#01"
Data: {"Utilization":100,"UtilizationMem":16,"Temperature":61,"PowerDraw":null,"PowerLimit":106,"FanSpeed":62,"Pstate":" P0","Clock":1911,"ClockMem":4503,"PowerMaxLimit":130,"PowerDefaultLimit":120,"PowerLimitPercent":88}
tMemory: "4 GB"
tDriverVersion: "398.36"
tClockSpeed: 1493
tCores: 6
tPowerDraw: "NaN W"
tFanSpeed: "62 rpm"
tClock: "1911 MHz"
tClockMem: "4503 MHz"
tPowerLimitPercent: "88 %"
tTemperature: "61 °C"
tUtilization: "100 %"

Second 1050 ti

Index: 4
PlatformId: 1
PlatformId_Index: 2
Type_PlatformId_Index: 2
Vendor: "NVIDIA"
Vendor_Name: "NVIDIA Corporation"
Vendor_Index: 2
Type_Vendor_Index: 2
Type: "Gpu"
Type_Index: 3
OpenCL: {"AddressBits":64,"Available":true,"CompilerAvailable":true,"DoubleFpConfig":"FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma","EndianLittle":true,"ErrorCorrectionSupport":false,"ExecCapabilities":"ExecKernel","Extensions":"cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer","GlobalMemCacheSize":98304,"GlobalMemCacheType":2,"GlobalMemCachelineSize":128,"GlobalMemSize":4294967296,"ImageSupport":true,"LocalMemSize":49152,"LocalMemType":1,"MaxClockFrequency":1493,"MaxComputeUnits":6,"MaxConstantArgs":9,"MaxConstantBufferSize":null,"MaxMemAllocSize":1073741824,"MaxParameterSize":4352,"MaxReadImageArgs":256,"MaxSamplers":32,"MaxWorkGroupSize":1024,"MaxWorkItemDimensions":3,"MaxWorkItemSizes":"1024 1024 64","MaxWriteImageArgs":16,"MemBaseAddrAlign":4096,"MinDataTypeAlignSize":128,"Name":"GeForce GTX 1050 Ti","ClVersion":"OpenCL C 1.2 ","Platform":"@{Profile=FULL_PROFILE; Version=OpenCL 1.2 CUDA 9.2.156; Name=NVIDIA CUDA; Vendor=NVIDIA Corporation; Extensions=System.Object[]}","PreferredVectorWidthChar":1,"PreferredVectorWidthShort":1,"PreferredVectorWidthInt":1,"PreferredVectorWidthLong":1,"PreferredVectorWidthFloat":1,"PreferredVectorWidthDouble":1,"Profile":"FULL_PROFILE","QueueProperties":"OutOfOrderExecModeEnable, ProfilingEnable","SingleFpConfig":"FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt","Type":"Gpu","Vendor":"NVIDIA Corporation","VendorId":4318,"Version":"OpenCL 1.2 CUDA","DriverVersion":"398.36"}
Model: "GTX1050Ti"
Model_Name: "GeForce GTX 1050 Ti"
Name: "GPU#03"
Data: {"Utilization":100,"UtilizationMem":16,"Temperature":51,"PowerDraw":null,"PowerLimit":60,"FanSpeed":51,"Pstate":" P0","Clock":1607,"ClockMem":4503,"PowerMaxLimit":130,"PowerDefaultLimit":120,"PowerLimitPercent":50}
tMemory: "4 GB"
tDriverVersion: "398.36"
tClockSpeed: 1493
tCores: 6
tPowerDraw: "NaN W"
tFanSpeed: "51 rpm"
tClock: "1607 MHz"
tClockMem: "4503 MHz"
tPowerLimitPercent: "50 %"
tTemperature: "51 °C"
tUtilization: "100 %"

**Comment by RainbowMiner** [comment]
Ok, I added TDP aproximation for Nvidia cards, also.
Please try the master.zip
https://github.com/RainbowMiner/RainbowMiner/archive/master.zip
- stop RainbowMiner
- unzip master.zip and overwrite all files
- start RainbowMiner

.. if we are lucky, the GTX1050Ti will now present it's powerdraw.

RBM

**Comment by hernandn01** [comment]
I get tPowerDraw: "0 W", I applied all commits including update watt calculation

**Comment by hernandn01** [comment]
GeForce GTX 1050 Ti (GPU#01,GPU#03)
===================================

Miner              Algorithm                Speed Power   BTC/Day  USD/Day  Accuracy   Fee Pool
-----              ---------                ----- -----   -------- -------- --------   --- ----
CryptoDredge       Lyra2z               2.67 MH/s    0W 0.00013455   0.8228      98% 1.00% BlockMasters
Excavator1.4.4     NeoScrypt            1.04 MH/s    0W 0.00012984   0.7940      96%     - BlockMasters
CryptoDredge       Lyra2RE2            33.05 MH/s    0W 0.00010915   0.6675      94% 1.00% BlockMasters
CryptoDredge       PHI2                 5.26 MH/s    0W 0.00010770   0.6586      94% 1.00% BlockMasters-Luxcoin
EnemyZealot        Hex                  9.52 MH/s    0W 0.00009779   0.5980      98% 1.00% BlazePool
Trex               X16S                 9.45 MH/s    0W 0.00009390   0.5742      98% 1.00% BlockMasters
Ewbf               Equihash24x5        32.00  H/s    0W 0.00009123   0.5579      98%     - ZergPool
EnemyZealot        X16R                12.30 MH/s    0W 0.00009649   0.5900      90% 1.00% ZergPool
Ewbf               Equihash24x7        17.00  H/s    0W 0.00008492   0.5193      98%     - ZergPool-Zero
CryptoDredge       Allium               5.19 MH/s    0W 0.00008421   0.5150      97% 1.00% ZergPool-Garlic
Trex               X17                  9.35 MH/s    0W 0.00008076   0.4939      96% 1.00% BlockMasters
CryptoDredge       Tribus              65.91 MH/s    0W 0.00007887   0.4823      95% 1.00% BlockMasters
EnemyZealot        PHI                 18.43 MH/s    0W 0.00006913   0.4227      95% 1.00% BlockMasters
XmrigNvidia        CryptoNightHeavy   637.00  H/s    0W 0.00006564   0.4014      94% 1.00% NiceHash
CcminerKlaust      Yescrypt             8.00 KH/s    0W 0.00006213   0.3799      99%     - BlazePool
Bminer             Equihash           426.00  H/s    0W 0.00006358   0.3888      93% 2.00% NiceHash
CcminerXevan       Skein              415.50 MH/s    0W 0.00006123   0.3744      94%     - BlockMasters
CcminerAlexis78    C11                 12.55 MH/s    0W 0.00005820   0.3559      94%     - BlockMasters
CcminerX16s        HMQ1725              3.66 MH/s    0W 0.00005687   0.3478      94%     - ZergPool
CcminerXevan       Xevan                2.31 MH/s    0W 0.00005413   0.3310      97%     - ZergPool
Excavator          CryptoNightV7-NHMP 622.00  H/s    0W 0.00004914   0.3005      97%     - NiceHash
EnemyZealot        Timetravel          25.93 MH/s    0W 0.00005033   0.3078      91% 1.00% BlockMasters-Machinecoin
CcminerAlexis78x64 KeccakC            576.99 MH/s    0W 0.00004493   0.2747      65%     - ZergPoolCoins-Creativecoin
CcminerKlaust      YescryptR16          1.44 KH/s    0W 0.00003312   0.2025      96%     - BlockMasters
CcminerSkunk       Skunk               16.89 MH/s    0W 0.00002907   0.1778      96%     - BlazePool
CcminerPolytimos   Keccak             549.33 MH/s    0W 0.00001573   0.0962      93%     - ZergPool-Maxcoin

**Comment by hernandn01** [comment]
followed instructions as I should on the first placed, and replace all files from Master. It is working now
![image](https://user-images.githubusercontent.com/41829368/44121610-e4cc8e80-9fdd-11e8-9562-7edda8ffb9d2.png)

**Comment by RainbowMiner** [comment]
Super :)

**Comment by RainbowMiner** [comment]
@rinkal26783 : has your benchmark problem being resolved with the bugfix release, too?
