### ISSUE TITLE
Error in Powershell

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1700]
Hi I keep getting this error in a 6x1070 rig...

PS>TerminatingError(ConvertFrom-Json): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'InputObject' because it is null."
WARNING: All miners crashed. Immediately restarting loop.

MiniZ opens and then closes immediately. I can't see a problem with any hardware settings.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/129326516-be97f18a-07ce-43c2-9b92-d927caed019c.png)
And this

**Comment by acos0874** [comment]
[debug_2021-08-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/6980969/debug_2021-08-13.zip)

**Comment by RainbowMiner** [comment]
- for some reason miniZ seems to have start problems with algorithm KawPow on your rig, but only sometimes. Easiest way would be to disable miniZ->KawPow in miners.config.txt (section "miniZ-GTX1070", find "KawPow", set `"Disable": "1",`) for the time being. For KawPow, Trex or Gminer do a decent job.
- the other error seems to indicate, that WildRig is not compatible with the Windows build 19041 - very weird, it could be, that the exe is damaged. I have checked the executable on Windows 19043 build and it executes just perfect. First, try to remove the  `.\Bin\GPU-Wildrig` directory and let RainbowMiner download and re-install the miner. If it doesn't help, you could try to update Windows to build 19043.

**Comment by acos0874** [comment]
The error with miniz seems to have recreated itself on another of my rigs, which is a shame as it is strong on some algos. I'll see if I can contact the devs as I'd prefer to keep it enabled.
