### ISSUE TITLE
Feature request - Click on the failed bechmark label to open the corresponding logfile for easy debugging.

### ISSUE THREAD

**Issue by itsdarklikehell** [RainbowMiner/RainbowMiner#1701]
It would be nice to be able to click on the Failed bechmark label in the bechmarks tab to open up the corresponding logfile. (either sanitzed for privacy reasons like you can do now with the debug file, or not, like you can do now with the currently running config.) it would make much easier debugging why it has failed the benchmark.

**Comment by RainbowMiner** [comment]
That's a very good idea! I'll add this. Thank you!

**Comment by itsdarklikehell** [comment]
:+1:  you are a godsend!
