### ISSUE TITLE
Plan to be available for HiveOs?

### ISSUE THREAD

**Issue by oyi77** [RainbowMiner/RainbowMiner#1703]
Do you have plan, to make it, can be integrated to hive os?

**Comment by RainbowMiner** [comment]
That should be possible.

**Comment by bro-ee** [comment]
Running on HiveOS, using HiveOS as an OS and repository for compiled miners, overclocking settings, remote reboot and so and so forth, just have no flightsheet attached.
While Rainbow Miner being started by cron, and is mining.
Quite sad that there are no module to connect with HiveOS API and report on current mining activities (i.e. miner, hashrate, profit, pool, etc...)
So Upvote +100500

**Comment by acos0874** [comment]
I think @oyi77 is suggesting a ready to run flash image of hiveOS with rbm installed. Would be really great to just plug and go with RBM.

**Comment by oyi77** [comment]
i think it would be easy to manage many rigs on hive os, when using auto profit switch with RBM. So it will be fun, and easy to manage. Managing the os from hive os website, while managing the miner itself with RBM. since as far as i know with RBM there is a benchmark and a profile to make it auto switch between miner, coin, and pool. Also there is a fun feature that auto rentalling the rig when its more profitable. 

Maybe if you as the owner send an email or message to hiveos to officially add your RBM there it would be very useful.

I am sorry for make such a issue here :D

**Comment by RainbowMiner** [comment]
No issue at all. In fact, I am already investigating the HiveOS API and integration possibilities now, thanks to your issue.

**Comment by morti000** [comment]
any news ?
it will be very interesting in hiveos like this one https://github.com/MaynardMiner/SWARM
