### ISSUE TITLE
No benchmarking for Herominers pool (auotlykos2)

### ISSUE THREAD

**Issue by doomnie7** [RainbowMiner/RainbowMiner#1704]
Hi there,

I have added Herominers pool specifically to mine Ergo (autolykos2). But for some reason, RainbowMiner picks up the pool when starting, but does no benchmarks.
I have tried to specify the autolykos algo, as well as the specific coin (in device config as well as pools), but still no luck. What am I doing wrong?
I have attached a screengrab of my pools config file.
![screeshot](https://user-images.githubusercontent.com/88477107/130419395-56766867-8b67-4eba-bb9c-46210dc0e8c9.jpg)

**Comment by RainbowMiner** [comment]
This is what you should do:
- first, please check, if the pool is listed in the "Pools" list on http://localhost:4000
- check if you have, by any chance, any other pool activated, that offers Autolycos2 mining? Look at "Best Pool" on http://localhost:4000 - which pool (if any) is being chosen for Autolycos2?

**Comment by doomnie7** [comment]
Herominers is not listed under All Pools. (It is ticked under "Pools, Miners and Algorithms" on the setup page)
Autolykos2 in not listed under Best Pools.

**Comment by RainbowMiner** [comment]
Ok - found it. Please just leave `"Region": "",` empty for now. There is a little flaw with sub-regions. In you case, Herominer's Europe server is located in germany. So selecting "eu" currently fails.

**Comment by RainbowMiner** [comment]
Important, it's the pools.config.txt's `"Region": "",` in section "Herominers" - not the config.txt's Region parameter. The latter is mandatory.

**Comment by RainbowMiner** [comment]
In your case, you might set Herominer's region to `"Region": "Germany",` in pools.config.txt, that does the job as well.

**Comment by doomnie7** [comment]
We have a saying in South Africa in my native tongue (Afrikaans) which roughly translates as "It's a shame that such a brain one day must rot!" :-)  You are brilliant! Thank you for your time and trouble.

Which brings me to my next hiccup.

RainbowMiner did not benchmark Teamred for autolykos2. Since I only get a hashrate of 115 with SRBMinerMulti compared to 165 with Teamred, I tried to manually configure Rainbowminers by editing the Teamred.ps file.  I also added it to the miners config file. Success!

But for some reason the autolykos currency totals are nowhere shown or included. It is not a major problem, but it would be nice if there were
![fullscreen](https://user-images.githubusercontent.com/88477107/130651430-cc0d58fa-414a-4a1b-ad33-c61c517e0dfd.jpg)
 a fix.

I have attached my screenshot.

Thanks again!

**Comment by RainbowMiner** [comment]
Uh! Good finding. Thank you! I have added Autolycos2 to the Teamred module.
Regarding the visibility in the list: there is a minimum profitability requirement in place, currently. It's useful, if you have a lot of algorithms. In your case, with only one algorithm selected, it results in the empty list. I'll add a quick fix to the core, so that it takes into account the number of currently selected algorithms.

**Comment by doomnie7** [comment]
Is there anything I have to do from my side to see the profitability of the autolykos2 algo?
Intermittendly I do see the amounts, but then next time I look they are gone

**Comment by RainbowMiner** [comment]
Normally, there is no need for action. Does it disappear from the list in the console window?

**Comment by RainbowMiner** [comment]
Oh, most important question: are there other pool/miners on that list? If it's the "lite" display mode, there will be the best 3, only. If you want to see all, use http://localhost:4000/bestpools.html and http://localhost:4000/activeminers.html

**Comment by doomnie7** [comment]
Here is my current console display.
![autolykos](https://user-images.githubusercontent.com/88477107/131332667-db118312-47c3-46b7-9917-925e191bf863.jpg)

**Comment by RainbowMiner** [comment]
So the UI style is set to "lite" - effectively reducing the miner counts within the lists to the top 3 available miners. If you want to see them all, set `"UIstyle": "full",` in config.txt.

**Comment by doomnie7** [comment]
UIstyle is set to full, but the profit estimates is still show as "unknown".
![autolykos](https://user-images.githubusercontent.com/88477107/131349876-06cdecd4-df69-495d-911c-a5befeeaa3b7.jpg)

**Comment by RainbowMiner** [comment]
Ah! Now I see the problem. Sorry, didn't notice that Unknown before. Could you please go to http://localhost:4000/bestpools.html, find the HeroMiners Autolycos2 entry and click onto the "+" on the left hand side of that row? It will open up a list of parameters - please copy-n-paste them here.

**Comment by doomnie7** [comment]
Here they are:

Algorithm: "Autolykos2"

Algorithm0: "Autolykos2"

CoinName: "Ergo"

CoinSymbol: "ERG"

Currency: "ERG"

Price: 0

StablePrice: 0

MarginOfError: 0.002081488614906264

Protocol: "stratum+tcp"

Host: "ergo.herominers.com"

Port: 1180

Ports: {"CPU":1180,"GPU":1180,"RIG":1180}

User: "9gsY94kYZgAGPPd9nWRfnedVXPuMEknPg1n7LQH6KTwdQBxshxy{diff:=$difficulty}"

Pass: "{workername:KINDERPC1070}"

Region: "Germany"

SSL: false

Updated: "2021-08-30T15:29:47.1977435Z"

PoolFee: 0.9

Workers: 17952

Hashrate: 6124770446783

TSL: 1530

BLK: 130.87537953264462

WTM: true

EthMode: null

Name: "HeroMiners"

Penalty: 1

PenaltyFactor: 0

Disabled: false

HasMinerExclusions: false

Price_Bias: 0

Price_Unbias: 0

Wallet: "9gsY94kYZgAGPPd9nWRfnedVXPuMEknPg1n7LQH6KTwdQBxshxy"

Worker: "{workername:KINDERPC1070}"

Email: null

tAlgorithm: "Autolykos2"

tCoin: "ERG"

tErrorRatio: "-"

tWTM: "✓"

**Comment by doomnie7** [comment]
Very weird, I just checked and the profit amounts were there, and then on the next run, they were again replaced by "unknown"".

**Comment by RainbowMiner** [comment]
The interesting part of that list are Penalty and PenaltyFactor. The profitprice will be multiplicated by the PenaltyFactor - so that basically explains the unknown profitability since it's zero, in your case.

Try to set `"MaxAllowedLuck": "",` in pools.config.txt (is there a specific reason, why you have set it to "-0.01"?). If that doesn't help, please create another Debug file. There are multiple possibilities, why the Penalty is 1 (1 means PenaltyFactor of 0 -> no profit)

**Comment by doomnie7** [comment]
It worked! Thanks! Now you probably won't believe me, but I did not change "MaxAllowedLuck" parameter....

**Comment by RainbowMiner** [comment]
> It worked! Thanks! Now you probably won't believe me, but I did not change "MaxAllowedLuck" parameter....

Sure, I believe you. I'll better look into that. There is always the chance, that I have a left-over debugging value.

**Comment by RainbowMiner** [comment]
Question: is this the only pool, that has that weird -0.01 value set in pools.config.txt or is it set for all pools?

**Comment by doomnie7** [comment]
It is set only for the one pool.
