### ISSUE TITLE
No miners available

### ISSUE THREAD

**Issue by doomnie7** [RainbowMiner/RainbowMiner#1707]
So the last day or two, this happens. (See screenshot)

When I go to benchmarks in the local dashboards, it is all blank. I have to restart a few times before both GPU are hashing again.
![no miners](https://user-images.githubusercontent.com/88477107/131329289-889c3cf8-755f-4b96-9791-dede907652ea.jpg)

**Comment by RainbowMiner** [comment]
Could you please upload a Debug file (http://localhost:4000, click "Debug file" on the left hand side)?
It is most probably a hardware problem with the GPUs - if one or both of the GPUs fail or fall off the bus, the miners start to crash and cause the Watchdog to disable one after the other. Reboot often brings the GPUs back to life. 
Do you overclock?

**Comment by doomnie7** [comment]
I do overclock, but not excessively. When a GPU crashes, it resets my overclocking settings, but in this case, there were no crashes (which I am aware of ie overclocking settings are still active
[debug_2021-08-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/7076306/debug_2021-08-30.zip)
).

**Comment by RainbowMiner** [comment]
Ok, so that is what the log files tell:

1. Pagefile

`[2021-08-30 07:10:59] WARNING: Pagefile is set to manage automatically. This is NOT recommended!`
You should set a fixed pagefile size.

```
To adjust your pagefile settings:
1. goto Computer Properties -> Advanced System Settings -> Performance -> Advanced -> Virtual Memory
2. uncheck "Automatically manage paging file size for all drives"
3. select "Custom size"
4. enter 30800 into the fields "Initial Size (MB)" and "Maximum Size (MB)"
5. click onto "Set" and then "OK"
```

2. The GPUs seem to have crashed at around 7:08 - seems like a hardware-crash and restart of RainbowMiner.

Gminer:
```
07:11:19 AMD Driver: 21.3.1
07:11:20 Connected to europe.ethash-hub.miningpoolhub.com:17020 [35.156.160.57]
07:11:21 Subscribed to Stratum Server
07:11:21 Set Extra Nonce: 0220
07:11:21 Authorized on Stratum Server
07:11:22 New Job: 8d76 Epoch: #437 Diff: 12.88G
07:11:22 Started Mining on GPU0: GIGABYTE AMD Radeon RX 6800 16GB [0000:07:00.0]
07:11:22 Started Mining on GPU1: AMD Radeon RX 6700 XT 12GB [0000:0e:00.0]
07:11:24 GPU1: Generating DAG for epoch #437 [Single Buffer 4520 MB]
07:11:24 GPU0: Generating DAG for epoch #437 [Single Buffer 4520 MB]
07:11:25 New Job: 8d77 Epoch: #437 Diff: 12.88G
07:11:27 GPU1: DAG generated in 2.70s [1672 MB/s]
07:11:27 GPU1: DAG verification passed
07:11:29 New Job: 8d78 Epoch: #437 Diff: 12.88G
07:11:29 New Job: 8d79 Epoch: #437 Diff: 12.88G
07:11:29 New Job: 8d7a Epoch: #437 Diff: 12.88G
07:11:29 New Job: 8d7b Epoch: #437 Diff: 12.88G
07:11:33 New Job: 8d7c Epoch: #437 Diff: 12.88G
07:11:33 New Job: 8d7d Epoch: #437 Diff: 12.88G
07:11:33 New Job: 8d7e Epoch: #437 Diff: 12.88G
07:11:34 Error on GPU0: Device not responding, check overclocking settings
```

LolMiner:
```
Setup Miner... 
[38;2;178;034;034mGPU detection thread timed out on card 0 of OpenCL platform 0.
Likely the card is dead, a rig reboot is recommended. 
[0mOpenCL driver detected.
Number of OpenCL supported GPUs: 1 
No Cuda driver or GPUs detected. 
```

... so one of your GPUs really did die, causing havoc. All miner starts after that did fail then, causing all pools and miners being disabled by the Watchdog one by one.

Actually, there is a feature, that you could enable, if you don't mind, that your PC will be rebooted automatically, in case of GPU failure. Some miners rise a red-flag, in case a GPU dies. RainbowMiner is able to react on those red flags. Just set `"EnableRestartComputer": "1",` and `"RebootOnGPUFailure": "1",` in config.txt. The first allows RainbowMiner to reboot the machine, the second enables the red-flag checking.

**Comment by doomnie7** [comment]
Thanks! The reboot function will be a great help! Now I just have to figure out how to implement my overclock settings on reboot...

**Comment by doomnie7** [comment]
I notice there is an EnableResetVega option. Since I have a Vega 64 card, just wondered if it was relevant and what it is for?

**Comment by RainbowMiner** [comment]
If enabled, RainbowMiner tries to disable, then re-enable each Vega GPU manually, before starting any miner software on them. It uses the tool switch-radeon-gpu.exe to do so. Actually, you might give this a try. If it turns out to worsen things, just disable that option again.

**Comment by doomnie7** [comment]
I had a few unexplainable crashes  today. I then did a clean install of the Radeon Crimson drivers.
But now I have two problems:
1. The teamredminer fails its benchmarks and can't mine autolykos2. (The miner runs fine if started on its own. The other miners are not an option - their hashrate is way lower)
2.  I get the following message on the console: WARNING: Could not read power data from AMD.
Any help or suggestions will be appreciated!
[debug_2021-09-03 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/7108225/debug_2021-09-03.1.zip)
