### ISSUE TITLE
Nicehash not showing Rig??

### ISSUE THREAD

**Issue by mcangeli** [RainbowMiner/RainbowMiner#1708]
I have nicehash pool setup (figured I'd add it to the mix) and I have my NH Wallet, API Key and Secret added to the config for it. The system shows that it has been mining for 2.5 hour and has a good amount found, however my miner does not show up on my NH Dashboard??

![image](https://user-images.githubusercontent.com/6456272/131330224-f85246d9-04ab-48af-9337-b9838e98967c.png)

Am I missing a setup somewhere??

**Comment by RainbowMiner** [comment]
Actually, it should appear as "yourworkername - UNMANAGED". Have you been using the "Mining Address" (it's a button on the https://www.nicehash.com/my/mining/rigs?path= page)?

**Comment by mcangeli** [comment]
Yea, never mind (and thank you for the quick reply) of the bazillion addresses in nicehash, I was using the wrong one.
