### ISSUE TITLE
Miners are still mining but Rainbowminer is showing the following error

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#171]
![image](https://user-images.githubusercontent.com/41829368/46035098-74765a00-c0bf-11e8-8e19-d5837548110c.png)

**Comment by hernandn01** [comment]
it appears the problem is at Bsod pool 

![image](https://user-images.githubusercontent.com/41829368/46035508-696ff980-c0c0-11e8-96bb-43e9e82cbe07.png)

error at log:

[2018-09-25 11:37:21] Problem fetching http://api.bsod.pw/api/currencies using REST: A task was canceled.
At C:\miner\RainbowMiner\Include.psm1:3209 char:47
+ ... yncLoader.Jobs.$Jobkey.Error) {throw $AsyncLoader.Jobs.$Jobkey.Error}
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: ([2018-09-25 11:...k was canceled.:String) [], RuntimeException
+ FullyQualifiedErrorId : [2018-09-25 11:37:21] Problem fetching http://api.bsod.pw/api/currencies using REST: A task was canceled.
 
Cannot convert null to type "System.TimeSpan".
At C:\miner\RainbowMiner\Include.psm1:360 char:9
+         $Stat = [PSCustomObject]@{
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : nullToObjectInvalidCast

**Comment by RainbowMiner** [comment]
Oh, I will have a look!

**Comment by RainbowMiner** [comment]
Ok, this seems to be a very uncommon Microsoft Powershell problem not directly related to RainbowMiner. You should stop and restart RainbowMiner. I am already in contact with the Microsoft support to find and wipe this bug off the table.

**Comment by hernandn01** [comment]
I figure that much, yes, I had to hard close Rainbowminer

**Comment by RainbowMiner** [comment]
I worked out a solution, together with Microsoft. Let's hope this will avoid this issue in the future.

**Comment by hernandn01** [comment]
Same issue

Invoke-RestMethod : A task was canceled.
At C:\miner\RainbowMiner\ReportStatus.ps1:32 char:17
+ ... $Response = Invoke-RestMethod -Uri $MinerStatusURL -Method Post -Body ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], TaskCanceledException
+ FullyQualifiedErrorId : System.Threading.Tasks.TaskCanceledException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Measure-Object : Cannot process argument because the value of argument "Property" is not valid. Change the value of the "Property" argument and run the operation again.
At line:211 char:98
+ ... ers | ConvertFrom-Json | Measure-Object -Sum -Property Profit).Sum;Ra ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Measure-Object], PSArgumentException
+ FullyQualifiedErrorId : GenericMeasurePropertyNotFound,Microsoft.PowerShell.Commands.MeasureObjectCommand


![image](https://user-images.githubusercontent.com/41829368/46110324-8976ea00-c1a0-11e8-9565-65e5a9b0f783.png)

**Comment by hernandn01** [comment]
[2018-09-26 15:41:10] Cycle problem with https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,LUX,ORE,SONO,XDNA&tsyms=BTC,USD&extraParams=https://github.com/rainbowminer/RainbowMiner using REST: You cannot call a method on a null-valued expression.

**Comment by RainbowMiner** [comment]
Oh dear! Which version of powershell are you using?

**Comment by hernandn01** [comment]
![image](https://user-images.githubusercontent.com/41829368/46142424-24f57280-c214-11e8-9446-fa0c32ba5d80.png)

is the second time that happen

**Comment by hernandn01** [comment]
upgrading now to 6.1.0
