### ISSUE TITLE
SSL Connection Ethermine

### ISSUE THREAD

**Issue by nevermind19** [RainbowMiner/RainbowMiner#1713]
Hi, i tried to configure SSL connection into pool config for Ethermine, but is not working , and still doing normal connection to the pool. I tried in "manual"  with the Gminer miner and all is ok, i think something not work.

**Comment by RainbowMiner** [comment]
You are right - I didn't have the SSL ports defined inside the pool module. It's fixed, now. Thank you for bringing this up.
