### ISSUE TITLE
No miners available - ZClassic to MPH

### ISSUE THREAD

**Issue by doomnie7** [RainbowMiner/RainbowMiner#1715]
I tried to force Rainbowminer to mine ZClassic to MiningPoolHub by defining the algorithm in the pools config.
Also tried specifying the coin in the pools config.
I keep getting the message: No miners available.

Can it maybe have something to do with the following message at ZClassic pool at MPH?:
  - Zclassic hardforked at block height 585318 and changed its algo to Equihash 192, 7
    Previous port(20575) mining hashpower is routed to mine Zencash instead.
    Please download new miner and mine at new port 20574 to mine Zclassic.

**Comment by RainbowMiner** [comment]
That's actually possible. I'll check the pool module. Which algorithm did you put into the pools.config.txt?
