### ISSUE TITLE
PWR vs TEMP Prioritisation

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1716]
Hi, I've been having problems with hot cards in this heat and I was investigating why the thermal throttling doesn't work as intended. I noticed that Afterburner has the option to prioritise either PWR or TEMP and by default it's set to PWR which means that cards are allowed to run hotter than the limit if power allows it. Switching this over manually to prioritise temp on the affected cards solved my problem, but I was hoping there might be a way to set it system wide using RBM in some way please?

**Comment by acos0874** [comment]
I just noticed the prioritisation seems to revert to PWR when switching algos.

**Comment by acos0874** [comment]
Hi, has there been any progress on this? I'm temporarily running on reduced power limits, but would be great if I could raise them again and allow the temp limits to manage overheating cards.

**Comment by acos0874** [comment]
Hi, I've just been thinking about the heating control function in RBM. Please can you tell me if this can be used to penalise hot algos to prevent them from being selected? I list my rigs on MRR and it tends to be that my rigs get hot when someone rents a hot algo.

**Comment by acos0874** [comment]
Yea it seems to be working. Does it apply an additional price to MRR listings?

**Comment by acos0874** [comment]
Hi, I think I found the setting. Assuming RBM using nvidiasmi it should be just a case of changing this setting...

![image](https://user-images.githubusercontent.com/42582444/134809552-7b506dc6-d4aa-4be8-b41d-3cde334633cb.png)

**Comment by RainbowMiner** [comment]
How could I have been so blind! Very good finding! I'll add some switch.

**Comment by acos0874** [comment]
Thank you

**Comment by RainbowMiner** [comment]
Added:
- add parameter "PriorizeThermalLimit" to ocprofiles.config.txt. Set this to "1" to priorize thermal limit over power limit (issue #1716). Hint: this only works on Windows and Nvidia GPUs.
