### ISSUE TITLE
New miner on the block to assess

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#1717]
https://bitcointalk.org/index.php?topic=5358334.0
https://github.com/sp-hash/TeamBlackMiner/releases/

by known dev (mostly doing optimization stuff) SP_

maybe worth checking out

Thx!

**Comment by RainbowMiner** [comment]
It's already added to our miner library :) In fact, it's a pretty fast miner. I have named the new module "Teamblack".

**Comment by RainbowMiner** [comment]
Note: this miners doesn't have any build-in API, so I need to have it mine behind a wrapper to catch and parse it's output. So even if you have set `"ShowMinerWindow": "1",` in config.txt, this miner will run in the background. If you want see the result, look for files `Teamred-GPU#...txt` inside the `.\Logs` (linux `./Logs`) folder.

**Comment by paulpoco** [comment]
I though something was broken when I didn't see a miner window

**Comment by UselessGuru** [comment]
I just hate miner devs that don't implement an API.
Parsing logs is a pain :-(

**Comment by mo35** [comment]
SP kinda mentioned that basic API is on to do list , as soon as some mining perf. improvements and optimisations are done

**Comment by RainbowMiner** [comment]
Yes. But no problem, in the meantime, our RainbowMiner wrapper does take good care of it. Only drawback is, that the miner has to run in the background.
