### ISSUE TITLE
CryptoDredge v0.9.2

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#172]
https://github.com/technobyl/CryptoDredge/releases/download/v0.9.2/CryptoDredge_0.9.2_cuda_10.0_windows.zip

New CryptoNightSaber (BitTube) algorithm
Improve Allium and Phi2 for 1070, 1070 Ti, 1080, 1080 Ti
Allow to set intensity per GPU
Fix failover mechanism
Disable miner to auto-start after system restart
Add crash reporting mechanism. Check Readme for more information

**Comment by RainbowMiner** [comment]
Thank you! I add it at once.
