### ISSUE TITLE
404 Not Found (Client Error)

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1726]
@RainbowMiner, suddenly there was no mining activities from my rig and when I looked into the dashboard it shows no miners. What could be the issue?

`Checking for VM ..
ok (not in a VM)
Checking for cURL ..
ok (disabled)
Detecting devices ..
1 CPU, 6 Nvidia, 1 AMD found
Checking Windows pagefile/virtual memory ..
ok
Initialize configuration ..
Read configuration ..
Loading pool modules ..
.. loading FlexPool
PS>TerminatingError(): "404 Not Found (Client Error)"
PS>TerminatingError(): "404 Not Found (Client Error)"
PS>TerminatingError(): "404 Not Found (Client Error)"
PS>TerminatingError(): "404 Not Found (Client Error)"
PS>TerminatingError(): "404 Not Found (Client Error)"
PS>TerminatingError(): "404 Not Found (Client Error)"
done (4.463s)
.. loading MiningRigRentals
done (2.121s)
Loading balance modules ..
PS>TerminatingError(): "404 Not Found (Client Error)"
PS>TerminatingError(): "404 Not Found (Client Error)"
PS>TerminatingError(): "404 Not Found (Client Error)"
Selecting best pools ..
Loading miner modules ..
Selecting best miners ..
Starting mining operation ..

WARNING: No pools available: check your configuration`

**Comment by astronyu** [comment]
[debug_2021-09-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/7161927/debug_2021-09-14.zip)

**Comment by RainbowMiner** [comment]
Looks like flexpool.io has it's API updated. I'll fix the pool/balance modules asap.

**Comment by RainbowMiner** [comment]
Duh! They really did evolve the API. Our pool modules are now up to date with their API v2

**Comment by astronyu** [comment]
Thanks for the quick response @RainbowMiner. It's back mining now.
