### ISSUE TITLE
Just wanted some more info

### ISSUE THREAD

**Issue by Joe23232** [RainbowMiner/RainbowMiner#1729]
Hey guys, I wanted to know is an operating system of its own that gets installed on individual PCs? Does this contain all the algorithims? Little confused how it works?

**Comment by RainbowMiner** [comment]
No, this is a script, that runs on either Windows 7, Windows 10 or Linux. The script interpreter is called PowerShell, which needs to be installed on Linux machines and should be updated to the newest Core 7.1.4 on Windows machines.

- first, you tell RainbowMiner, which pools you plan to use (Nicehash, Zergpool, Prohashing, ...)
- then RainbowMiner will download all miner binaries for all algorithms, that those pools support
- lastly, RainbowMiner will start to mine to the most profitable pools, with the most profitable algorithm. Automatically.

**Comment by Joe23232** [comment]
@RainbowMiner I see thanks for clearing that up for me,

So one last question, does all of the computers have to be on the same network as the device that controls the computers for mining?

**Comment by RainbowMiner** [comment]
> So one last question, does all of the computers have to be on the same network as the device that controls the computers for mining?

No :)

**Comment by Joe23232** [comment]
@RainbowMiner 

that sounds awesome mate =D

So like is my PC going to be a webserver or is it that all the PCs connect to your web server?

If it is the later, then do you guys have access to my data?

**Comment by RainbowMiner** [comment]
> So like is my PC going to be a webserver or is it that all the PCs connect to your web server?

It's the first - your data stays with you.

**Comment by Joe23232** [comment]
@RainbowMiner I see mate, thanks mate :)
