### ISSUE TITLE
New blocks on zpool

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#173]
![image](https://user-images.githubusercontent.com/30832110/46089057-5564ee80-c1cb-11e8-81a5-873959e192bf.png)
what is the meaning of new blocks? do we get payment for submitting shares after this new block status?

**Comment by ebojali** [comment]
@rinkal26783 perhpaps that is a quiestion to ask zpool admins? You can ask your question in their discoord channel 
https://discordapp.com/channels/376790817811202050/402913604057300995

**Comment by RainbowMiner** [comment]
I think, they declare a found block as new, if it is younger than 10 minutes. And yes, if we were mining during this time, we will get a share of the block. But first, if must be cleared (they mark it as green).

**Comment by rinkal26783** [comment]
@RainbowMiner Is it possible to switch miner whenever new block is found? If miner is switched whenever block is new, it would be more profitable. That way we can be sure that we are going to get quick and more payment.

**Comment by RainbowMiner** [comment]
@rinkal26783 it would be possible to read the web interface and check for new blocks - but only for dedicated currencies, say, the currency being currently mined by RainbowMiner. What would be the best method, then? Mine until a block is being found and then switch?

**Comment by ebojali** [comment]
@RainbowMiner what if the second most profitable coins finds alot of new blocks. Will that be picket up by the miner then and switch?
