### ISSUE TITLE
Rainbowminer Lock ups

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1731]
Hi, I've been having this persistent problem that occasionally hits a different rig each time. The rig appears to be offline, even though I think it is still mining. The powershell window is not updating, but the system is still responsive. There are no errors in the main window but I suspect it may be something to do with my network. To fix it I have to log into the rig to close and reopen rbm. Please can you investigate what the issue is?

![image](https://user-images.githubusercontent.com/42582444/134062342-811a0aee-3218-4da5-80a7-e991a2a752d8.png)
[debug_2021-09-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/7198225/debug_2021-09-20.zip)

**Comment by RainbowMiner** [comment]
That most probably looks like a network problem. I'll have a look tomorrow.

**Comment by acos0874** [comment]
Thanks.

**Comment by mgbowe1** [comment]
I've been having the same issue. 
My ISP is notorious for minor hiccups (down for less than 30s approx 1-2x/day) 
Since the update to 4.7.4.7, I get a notice that the miner has gone offline, but based on my fan noise and my Nicehash account info, I'm still mining, however RainbowMiner has locked up and requires a restart.

**Comment by acos0874** [comment]
@mgbowe1 are you using the ISP standard router?

**Comment by mgbowe1** [comment]
No, I have a Netgear Modem and separate router (rig is hardwired directly to the router) Also, not so sure the issue is network related, has happened after approx 30mins all morning today and the network hasn't dropped at all.

**Comment by mgbowe1** [comment]
I managed to get a debug file while the RainbowMiner script was hung:
[debug_2021-09-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/7251810/debug_2021-09-29.zip)

Note, this issue does not prevent mining, only stops the automated switching for profitability an thus hurting the profitability of the rig. Based on my email notification, the hang started about 2:54:29 EDT, 2021/09/29 06:54:29 UTC.

**Comment by mgbowe1** [comment]
Any updates on this? It's a major usability issue. It stopped sending offline notifications, so I now need to monitor my system 24/7 so I can restart the process when it inevitably hangs. Issue is still present in version 4.7.5.0

**Comment by RainbowMiner** [comment]
Please try to enable curl:
Set `"EnableCurl": "1",` in config.txt

**Comment by DCreason** [comment]
@Nickfost and I have 6 machines at two separate sites with this same issue. 
I have set `"EnableCurl": "1",` in config.txt on multiple machines, this issue persists. 
The machines are all running Ubuntu, one Ubuntu 20.04, the others 18.04.
I haven't observed any network issues, my workstation is on the same switch as one machine with this issue.

[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/7295730/RBminer.Logs.zip)

**Comment by itsdarklikehell** [comment]
I have seen this behaviour too, ill switch on the `"EnableCurl": "1",` in config.txt and wait if/till it happens again and make a debug for you to peek at.

**Comment by itsdarklikehell** [comment]
Actually two debug files. one is my own rig the other is my dads one. both lock up on diffrent pools and miners.


[debug_2021-10-07.zip](https://github.com/RainbowMiner/RainbowMiner/files/7298980/debug_2021-10-07.zip)
[debug_2021-10-07 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/7298981/debug_2021-10-07.1.zip)

**Comment by acos0874** [comment]
I've not sure the issues are related, but I am suddenly having 2 rigs that won't fetch API values or config files from the server. The two affected rigs are on wifi and the server is on ethernet.

The error given on the client rigs is similar to the one above

PS>TerminatingError(): "cURL 28 / HTTP 200"
WARNING: Get-ServerConfig failed cURL 28 / HTTP 200
PS>TerminatingError(): "cURL 28 / HTTP 200"
PS>TerminatingError(): "cURL 28 / HTTP 200"

**Comment by acos0874** [comment]
Seems to be solved for me.

**Comment by acos0874** [comment]
Hi I'm sorry to report the issue has come back. It has happened twice on two separate rigs today.

**Comment by RainbowMiner** [comment]
Ah, too bad. Could you create debug files for these two machines? When did it happen aprox? Was there any special event, like power outage, internet outage or similar?

**Comment by RainbowMiner** [comment]
One extra question: could you please describe again, what is exactly happening? Is the console output simply stuck? What happens, if you open that console and just hit the `Enter` key?

**Comment by acos0874** [comment]
Just to note the issue occurred on 2 rigs in the night. They were still mining, which I can be sure of because they were in rentals.

**Comment by RainbowMiner** [comment]
> Would it be possible to please have a time stamp on the main powershell window, so I can more easily establish that the window has in fact locked up without having to look at the logs?

Sure. I'll add it.

**Comment by RainbowMiner** [comment]
> Just to note the issue occurred on 2 rigs in the night. They were still mining, which I can be sure of because they were in rentals.

I will push a new release today - that may very well fix things for you. But note: please set `"EnableCurl": "0",` for all updated rigs, then. Otherwise the new update will only partly reduce the port depletion problem.

**Comment by acos0874** [comment]
This seems to be fully fixed now.
