### ISSUE TITLE
latest update broke pools.config.txt

### ISSUE THREAD

**Issue by mcangeli** [RainbowMiner/RainbowMiner#1732]
Something in the way the latest update updated pools.config.txt broke my config. It overwrote two of the pools I had setup (ethermine and nicehash) and for some reason left Zergpool untouched....

**Comment by mcangeli** [comment]
It also broke the MRR setup I had in the pools.config.txt file. Luckily I had a back up copy of it to put in place.

**Comment by RainbowMiner** [comment]
RainbowMiner keeps backups of all config files in folder `.\Config\Backup` - at each start or restart a new backup set is created.

How exactly did the last update break your pools.config.txt? All data missing, wrong data or chaos?

**Comment by mcangeli** [comment]
It got rid of the data in the ethermine and nicehash sections (possibly the
zergpool too but I have to check)
