### ISSUE TITLE
Not reporting hash to Ethermine and saw a 404 error during start

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1734]
Not reporting hash to Ethermine and saw a 404 error during start

[debug_2021-09-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/7215082/debug_2021-09-22.zip)
![Screenshot_20210922-220725_Chrome](https://user-images.githubusercontent.com/801414/134457194-f082ba16-f0ac-4df1-80ea-85a280aaa9b3.jpg)

**Comment by RainbowMiner** [comment]
Yes, that's a known issue with the Teamblack miner. The developer has identified the problem, it will be fixed in the next release of the miner (v1.07)

**Comment by paulpoco** [comment]
Funny the server PC is showing TeamBlack and a client PC is not showing TeamBlack.

TeamBlack on 2 x 1070 is 2MH higher than others on Ethash.

**Comment by RainbowMiner** [comment]
The Teamblack miner is a pretty fast miner - but it produces a good hand full of stale shares. These in fact are rewarded by real Ethash pools like Ethermine, but cause harm on Nicehash and Flexpool. Therefor RainbowMiner uses two extra Ethash algorithms, that add more conservative intensity settings to Teamblack on those two pools (it's EthashNH for Nicehash and EthashFP for Flexpool). So maybe that client rig is currently on Nicehash.

**Comment by RainbowMiner** [comment]
The newest version of the miner should report the hashrate to Ethermine, now.
