### ISSUE TITLE
Flux on Minerpool

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1739]
@RainbowMiner, I added userpools for Minerpool and also tried out Fluxpools. It loaded the pool when the script started up but both gave me "No miners available warning".

Below screenshot is what is showing in RBM when Fluxpool was checked. Mind you I went into Fluxpools.ps1 file and change the password to 5 (a number as required by the pool)
![Screenshot 2021-09-25 010056](https://user-images.githubusercontent.com/3217740/134713431-54efa337-7e03-472f-ac5d-7fdcbc276e59.png)

Can I request to add minerpool for flux mining?

**Comment by RainbowMiner** [comment]
Is it minerpool.org? Yes, that should be a good addition to our Pools library. I'll add it.
Also, I'ld like to investigate that "No miners available warning" - it should, if the pools are shown in the Pools section on localhost:4000.

**Comment by astronyu** [comment]
> Is it minerpool.org? Yes, that should be a good addition to our Pools library. I'll add it.
> Also, I'ld like to investigate that "No miners available warning" - it should, if the pools are shown in the Pools section on localhost:4000.

Yes, minerpool.org, seems like it is a little bit more profitable than other FLUX pool, mainly because of parallel assets rewards distribution to miners. I was not sure what happened. It showed Flexpool in best pool tab but console showing no miners available.
Appreciate your help.

**Comment by RainbowMiner** [comment]
Ok, added.
- add new FLUX mining pool (issue #1739) https://minerpool.org
- Minerpool is pool mining
- MinerpoolSolo is solo mining

**Comment by astronyu** [comment]
> Ok, added.
> 
> * add new FLUX mining pool (issue [Flux on Minerpool #1739](https://github.com/RainbowMiner/RainbowMiner/issues/1739)) https://minerpool.org
> * Minerpool is pool mining
> * MinerpoolSolo is solo mining

Thank you for this. Ran the updater bat but doesn't seems to received any new updates so just went ahead and copy the changes manually.

As for the Fluxpools, can you look into changing the password from default "x" to user definable? As what I understand, they require miners to set miner password to a NUMBER:
'minpayout=<NUMBER>' to set the amount needed to trigger a payment

**Comment by astronyu** [comment]
@RainbowMiner, for tweaking OC for Flux, is Equihash24x5 is the same as Equihash 125_4?
I'm trying to set it to use certain OC profile instead of using the same settings for Eth.

**Comment by RainbowMiner** [comment]
> Thank you for this. Ran the updater bat but doesn't seems to received any new updates so just went ahead and copy the changes manually.

It will be in the tomorrow release. Then the updater will catch it.

> As for the Fluxpools, can you look into changing the password from default "x" to user definable? As what I understand, they require miners to set miner password to a NUMBER: 'minpayout=' to set the amount needed to trigger a payment

Of course, I can make it user definable, but that will be on a per-pool basis. There is already a simple way to add parameters to the password on a per-coin basis, just edit pools.config.txt and add your extra parameters to `"FLUX-Params"`.
e.g.
```
  "FLUX-Params": "minpayout=5",
```

This will then be automatically comma concatenated to the "x". I think most pools interpret this correctly. If you want to try this on Flexpools, please report back, if that worked for you.
