### ISSUE TITLE
When trying to change Common setting in Configuration

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#174]
When I tried to change common settings I got the following error after hitting enter on the first question.

"WARNING: "You cannot call a method on a null-valued expression.". You should never reach here. Please open issue on github.com"

I've tried this multiple times, and each time same result.

**Comment by RainbowMiner** [comment]
Thank you! At which point did it stop you?

**Comment by Yamanipanuchi** [comment]
This error appeared right after I hit enter on the selection for Combo, Which is the first question. The error repeated itself for what seemed to be a continuous loop. Each time I simply closed the window and Re-opened start with start.bat.

**Comment by RainbowMiner** [comment]
Yes, I see. Which powershell version do you use? I suspect a problem with the new PS6.1.0 since I can reproduce it on my PS6.1.0 test system.

**Comment by RainbowMiner** [comment]
Ok, found the problem. I will add the fix to the next release.
