### ISSUE TITLE
Rates page theme resets.

### ISSUE THREAD

**Issue by Wornie** [RainbowMiner/RainbowMiner#1740]
RainbowMiner v4.7.4.6
Firefox 92.0

When navigating to /rates.html, the rbm-theme cookie is reset to light.

This is all that is found in the logs.

I can't find any other page with this issue.

![image](https://user-images.githubusercontent.com/39562590/134777404-cdae6782-a1d9-462e-9fd5-c71335725d2b.png)

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll fix it asap.
