### ISSUE TITLE
HiveOn Balance not showing

### ISSUE THREAD

**Issue by tdrechsl** [RainbowMiner/RainbowMiner#1743]
Error message:
Pool Balance API (Hiveon) for Cannot bind parameter 'Date'. Cannot convert value "08/27/2021 07:04:44" to type "System.DateTime". Error: "String '08/27/2021 07:04:44' was not recognized as a valid DateTime." has failed.

ETH adress is 0xfee29e6ae0c448b093b596cfcdc5b35d6d5f8a07

**Comment by tdrechsl** [comment]
Error still present in v4.7.4.9

**Comment by RainbowMiner** [comment]
Thank you for reporting it back. I'll double-check.

**Comment by tdrechsl** [comment]
I can confirm the issue being fixed in v4.7.5.0

Thank you very much.
