### ISSUE TITLE
Arch linux: package names are not correct

### ISSUE THREAD

**Issue by mgbowe1** [RainbowMiner/RainbowMiner#1746]
The install.sh script fails to install some rainbowminer dependencies due to a package name mismatch on arch. After researching the correct package names, I have found that I have all the dependencies, but the install script does not recognize that I do.
They should be as follows:
libc-ares2 -> c-ares
libuv1 -> libuv
libcurl4 -> libcurl
libcurl4-openssl-dev -> libcurl-openssl-dev
ocl-icd-libopencl1 -> ocl-icd
libjansson4 -> libjansson
libltdl7 -> libltdl
libncurses5 -> ncurses (may need ncurses5-compat-libs from the AUR if it's required to be version 5)
p7zip-full -> p7zip

**Comment by RainbowMiner** [comment]
Thank you very much! I have merged your pull request.
