### ISSUE TITLE
MMR Hashrate unit, auto or need manual editing?

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#1749]
Just curious, is there a config that I need to set in RBM to make sure the rig advertise correct hashrate unit? For some reason my rig was advertised for MH instead of H.

**Comment by RainbowMiner** [comment]
This is done automatically. Which algorithm got the wrong hashrate unit? What hashrate have you got on that algorithm on your rig and what value has been advertised on MRR?

**Comment by astronyu** [comment]
> This is done automatically. Which algorithm got the wrong hashrate unit? What hashrate have you got on that algorithm on your rig and what value has been advertised on MRR?

It was algo Equihash 125,4, showing MH/s instead of KH/s. The value advertised was the same as on my rig apart from the unit.

**Comment by RainbowMiner** [comment]
Ok, thank you. I'll check the MRR API for a potential bug.
