### ISSUE TITLE
CryptoDredge to v0.9.2 requires cuda 10

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#175]
Hi cuda 10 is needed for CryptoDredge to v0.9.2 but I cannot install it since visual studio is not installed on my rig and unfortunate fails to launch the installer when I try installing the latest visual studio.

Do you have a clue? I've tried all, but nothing seems to work.

**Comment by hernandn01** [comment]
you don't need to install CUDA 10 unless you are developing, Nvidia drivers 411.63 are cuda 10 enabled.

**Comment by ebojali** [comment]
cryptodredge 0.9.2 gives the following warning, that does not mean I need to update the cuda installed?
2018-09-26 22:11:58 WARNING: CryptoDredge requires CUDA version 10.0 or above (installed version is 9.2.189). Please update your Nvidia drivers.

**Comment by ebojali** [comment]
So far so good, everything benched and running smoothly... We can close the ticket..
