### ISSUE TITLE
Odd hashrate on RandomArq rental

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1750]
![image](https://user-images.githubusercontent.com/42582444/135503051-daaebb8e-b600-4e86-ab60-7e82d93cd118.png)

![image](https://user-images.githubusercontent.com/42582444/135503023-18836abd-cbbf-418f-bd36-883b2b4af593.png)

Any ideas?

**Comment by acos0874** [comment]
It's happening no more than one rig.

**Comment by acos0874** [comment]
MRR devs reported it is a problem their end.

**Comment by RainbowMiner** [comment]
Ah, ok. That's good. It's as if they account for exactly twice your hashrate.

**Comment by acos0874** [comment]
Shame I wasn't getting paid twice as much.
