### ISSUE TITLE
[Feature Request] Disable Mining when on Battery Mode

### ISSUE THREAD

**Issue by cleanerspam** [RainbowMiner/RainbowMiner#1754]
Option to automatically pause mining when a laptop is not connected to power and automatically resume miners when power is back .
Some miners like xmrig support it by default

**Comment by RainbowMiner** [comment]
Very interesting proposal! I will try to add a Batterie-Stop feature.

**Comment by cleanerspam** [comment]
Thanks for adding this feature in v4.7.5.3
