### ISSUE TITLE
[Feature Request] Payout Fees and Monitoring Central

### ISSUE THREAD

**Issue by OGizzle** [RainbowMiner/RainbowMiner#1757]
I just noticed, that Mining Pool Hub has a 0% fee on mining ETH but 0.0006 BTC TX fee on payouts. I could set a higher penalty value in Pools.Config but it would be very helpful if the payout fees would be handled like the Pool Fees now.

My second request is to add the RBMiner Version in the monitoring central.

Thank you.

**Comment by RainbowMiner** [comment]
> My second request is to add the RBMiner Version in the monitoring central.

I have added the RainbowMiner version number to the Monitoring Central (it fitted well into the Worker/IP column)

**Comment by OGizzle** [comment]
Great! Thank you for your answers and the implementation of RBM version number.
