### ISSUE TITLE
Profit switch based on timing

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#176]
I wonder if its possible to profit switch based on time to find new block. 
Today I am mining verge x17 on yiimp. It's been 2 hours to and yet we haven't found any block yet. usually they find 3-4 block per hour. 
What if we could setup switch based on timing. Where i can set 40 minutes to find block in xvg. If any block not found in 40 minutes, It will switch to secondary coin.

**Comment by Yamanipanuchi** [comment]
I like this idea, Always thought it would be nice to have a "Mine till block found option" also.

**Comment by RainbowMiner** [comment]
Good idea. I will try to figure something out.

**Comment by rinkal26783** [comment]
same case happens with ravencoin. sometime there are no ravencoins for days, but once a new block is found they find 2-3 blocks per hour. Denarius too. and there are many other coins which has tendency to be found in a row.

**Comment by RainbowMiner** [comment]
Continued with issue #200
