### ISSUE TITLE
AMD card not detected

### ISSUE THREAD

**Issue by mdrobb** [RainbowMiner/RainbowMiner#1763]
I've been using RM in Linux mint with an Nvidia card. I wanted to add an AMD to the system but after following the guide I'm still not seeing it. It's detected by the system but not RM.

**Comment by mdrobb** [comment]
Rx 580 8GB

**Comment by DeeDeeRanged** [comment]
Did you install the amdgpu-pro-21.20 or 21.20 drivers with the following command?
./amdgpu-install --opencl=legacy --headless --no-dkms
do note this is based on debian/ubuntu with xserver-xorg-video-amdgpu installed.
