### ISSUE TITLE
Idea: What has been mined next to Balances

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#177]
I have my system set to only mine when profitable. Sometimes I am not sure if I even mined anything though the night or when I am at work. Yes I could go to each pool as see what is pending. But I was wondering if there would be a way to for Rainbow miner to actually keep track of how much of what was mined. Maybe in BTC value from what was offered by the pool? This would put this information in one place summarized.

**Comment by RainbowMiner** [comment]
Oh, yes. Very good. I have been missing this feature. Noted :)

**Comment by RainbowMiner** [comment]
Release v3.8.8.5 starts to write an activity log. The contents of this log can be viewed at "Activity" in the miners section:
![image](https://user-images.githubusercontent.com/39437538/46290157-56ab6800-c58b-11e8-82fa-fcc785e10881.png)
