### ISSUE TITLE
Error Loop in PowerShell

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1770]
![image](https://user-images.githubusercontent.com/42582444/136781612-adf23dbf-b63d-48f4-ada1-6c7f302c2d46.png)
Happened occasionally before but has happened twice today. Works fine after restarting RBM. I replaced the core module with a healthy one but the problem persisted.

**Comment by RainbowMiner** [comment]
> I switched my server to another rig and now the new server rig is having the same problem.

This looks like a very strange Powershell bug, since it creates this error for Powershell default cmdlets (and not only for cmdlets, that I have programmed).  Try to update the powershell to Powershell Core 7.1.4.

**Comment by acos0874** [comment]
I updated the new server to 7.1.4. The same thing just happened.
[debug_2021-10-12 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/7330392/debug_2021-10-12.1.zip)

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/136976057-369480b1-92d2-4400-b309-0d5bfe0109cf.png)
Antivirus is manual scan and windows all up to date. I just managed to catch this error which didn't cause the loop and it continued running after...

![image](https://user-images.githubusercontent.com/42582444/136976125-7572d3c4-abd0-49c5-82b5-76c57ad0e632.png)

**Comment by acos0874** [comment]
I found some relevant articles. I have updated powershell but the issue persists. 

https://social.technet.microsoft.com/Forums/en-US/edc4ae2d-b804-4361-94de-7482533a8084/intermittent-the-term-getdate-is-not-recognized-as-the-name-of-a-cmdlet-function-script-file?forum=winserverpowershell

https://stackoverflow.com/questions/28810631/powershell-commands-not-working-in-build-events-in-visual-studio

**Comment by RainbowMiner** [comment]
I always keep RBM is backwards compatible, down to Powershell 5.
But yes, I'ld rather try to re-install PS Core 7.1.4 and see, if it changes a thing. In the meantime, I'll change something in the RainbowMiner core. I have a gut feeling about the pause classes, I have introduced recently. Not that passing custom classes via synchronized hashtables (our session variable is of that kind) triggers a Powershell bug.

**Comment by acos0874** [comment]
Do I want x86 or x64? Runing on a celeron

**Comment by acos0874** [comment]
I haven't had a single error email in the past 2 days. Thanks for all your hard work on this.
