### ISSUE TITLE
Remote Workers tab is not visible

### ISSUE THREAD

**Issue by kostek001** [RainbowMiner/RainbowMiner#1776]
Client shows that its connected to the server, but the Remote Workers tab is not visible on the server dashboard
![1](https://user-images.githubusercontent.com/69671514/137167509-09f2546e-383b-4817-8421-8df06374c1be.png)
![2](https://user-images.githubusercontent.com/69671514/137167512-10cbf5f8-c1b3-4f47-80c7-4a168f1a9d40.png)
![3](https://user-images.githubusercontent.com/69671514/137167796-f124909b-e535-41fa-8faf-34e6f94ae358.png)

.

**Comment by TheeeX** [comment]
Hi, I am not able to see Remote workers, 
Clients show that it's connected to the server, but the Remote Workers tab is not visible on the server dashboard.
Also If I open http://localhost:4000/clients on the server machine, it shows all the clients.
Also, I can see the worker and server at https://rbminer.net

What could be the issue?

**Comment by RainbowMiner** [comment]
Could you please create Debug files, for server and client, and upload it here? Click "Debug file" on http://localhost:4000 - a zip file will be created, that has all sensitive data x-ed out.

**Comment by TheeeX** [comment]
After using the same worker id I'm able to use it, is it the right way?

Also can we remotely change client configuration?

**Comment by RainbowMiner** [comment]
> After using the same worker id I'm able to use it, is it the right way?

Every machine should have it's own unique WorkerName, but all should share the same MinerStatusKey.

> Also can we remotely change client configuration?

Yes, that is possible: if you want to provide the individual rigs with specific config files, put these files into a subdirectory `.\Config\<workername>` (linux: `./Config/<workername>`) on your server. Use lowercase letters for the subdirectoy `<workername>`.
