### ISSUE TITLE
Plug and Play RBM on Linux

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1778]
I remember seeing it mentioned on a separate issue (but can't find it) that there were plans to implement a ready made linux/hiveOS version of RBM that could be flashed to USB. Given all the problems I've been having recently in windows and the introduction of locked core clocks in trex, I've been thinking of moving all my rigs across to linux. 

Is this something that is likely to help in the near future or should I go ahead and set them up myself?

Thanks as always.

**Comment by acos0874** [comment]
I'm planning on building so more rigs soon. Please can you let me know is this something that is still being worked on?

**Comment by RainbowMiner** [comment]
It's in the works - but has to go a long road, still.

**Comment by acos0874** [comment]
Will locked core clock through OC Profiles still work in linux?

**Comment by samdave123** [comment]
What's the best/easiest way to set up a Linux RBM rig? HiveOS, Ubuntu, or something else is recommended?
