### ISSUE TITLE
Idea: Web Interface Running Miners

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#178]
Running miners in the web interface populated from the information obtainable via the pool API. Giving one location to see all active miners, Even the ones that are not on the immediate PC.

I looked into programming a script to do this for me, And realized how complicated this might be. So as a side note thank you for all the time you put into this overall script.

**Comment by RainbowMiner** [comment]
Thank you :) I will see, what I can do.

**Comment by RainbowMiner** [comment]
Good :) First step is done:
- update to new release v3.8.8.1
- find central monitoring at https://rbminer.net
- enter "https://rbminer.net" as MinerStatusURL (config.txt or [C]onfiguration->[C]ommon)
- create a new miner status key (either at https://rbminer.net or in [C]onfiguration -> [C]ommon) and enter it as MinerStatusKey
- set "EnableMinerStatus" to "1" in config.txt (or enable it in [C]onfiguration->[C]ommon)

**Comment by Yamanipanuchi** [comment]
I love where its going! Looks nice so far!

**Comment by ebojali** [comment]
This is a very good functionality, thanks alot m8! :) @RainbowMiner

**Comment by RainbowMiner** [comment]
Important side note:
you may use the same miner status key for all of your rigs. All rigs will then show up together in a list at https://rbminer.net, using this one key.
