### ISSUE TITLE
One Rig Not Selecting Ethash

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1781]
Sorry for all the issues, but I can't for the life of me figure out why this rig isn't selecting ethash, but instead selecting the next thing down. I have tried configuring it with a custom pool and with the new poolin adjustments. All other rigs are mining fine now on poolin, but just this one is being stubborn. Poolin shows in the active miners but not in the console.
[debug_2021-10-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/7352936/debug_2021-10-15.zip)

**Comment by samdave123** [comment]
Similar issue here
[debug_2021-10-16.zip](https://github.com/RainbowMiner/RainbowMiner/files/7357246/debug_2021-10-16.zip)
