### ISSUE TITLE
AECurrency not always used in ZergPoolCoins

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1782]
It seems for ZergPoolCoins that RB prioritizes mining to the defined wallet over the AECurrency wallet.

For example, I have $LTC as AECurrency. I have a $VRSC wallet defined in pools.config.txt.
When mining VRSC it mines into the VRSC wallet, otherwise it mines into LTC.

Is this expected?
Does ZergPoolCoinsSolo behave the same way?

**Comment by RainbowMiner** [comment]
> ZergPool/Zpool should always mine to the AECurrency though, correct?

Exactly. ZergPool & Zpool always mine to one wallet. It's always the currency's wallet, which is setup in pools.config.txt. If you setup multiple currencies, the first of BTC->DASH->LTC->any other currency is being used. With AECurrency, you can select the currency.

E.g. 
```
"ZergPool": {
  "BTC": "yourBTCwalletaddress",
  "LTC": "yourLTCwalletaddress",
  "XMR": "yourXMRwalletaddress",
  "AECurrency": "",
...
},
```

--> this will mine to your BTC wallet

```
"ZergPool": {
  "BTC": "",
  "LTC": "yourLTCwalletaddress",
  "XMR": "yourXMRwalletaddress",
  "AECurrency": "",
...
},
```

--> this will mine to your LTC wallet

```
"ZergPool": {
  "BTC": "",
  "LTC": "",
  "XMR": "yourXMRwalletaddress",
  "AECurrency": "",
...
},
```

--> this will mine to your XMR wallet

```
"ZergPool": {
  "BTC": ""yourBTCwalletaddress,
  "LTC": "yourLTCwalletaddress",
  "XMR": "yourXMRwalletaddress",
  "AECurrency": "LTC",
...
},
```

--> this will mine to your LTC wallet
