### ISSUE TITLE
Timed out errors

### ISSUE THREAD

**Issue by Gamerios** [RainbowMiner/RainbowMiner#1784]
Hello

I tryed with Proxy and VPN and OpenVPN   with 2 different ISPs  but in LOgs always

`
Starting v4.7.6.0! Please wait..

Checking for VM ..
ok (not in a VM)
Checking for cURL ..
ok
Detecting devices ..
1 CPU, 6 Nvidia found
Checking Windows pagefile/virtual memory ..
ok
Initialize configuration ..
PS>TerminatingError(): "Call to https://api.coinbase.com/v2/currencies timed out after 15 secs"
>> TerminatingError(): "Call to https://api.coinbase.com/v2/currencies timed out after 15 secs"
WARNING: Worldcurrencies API failed.
Read configuration ..
Loading pool modules ..
.. loading Ezil
PS>TerminatingError(): "Call to https://calculator.ezil.me/api/ezil_calculator?hashrate=100 timed out after 15 secs"`

Also different poools and so on bit as you see coinbase and ezil and also same at other ppols Timed out

But if i try this URL in Chrome at the Rig they work 

Also searched google and here but not find anything how i can fix    sry if i already fixed but i not found here a resolution :(

Regards

**Comment by RainbowMiner** [comment]
Question: which proxy are you using?

**Comment by RainbowMiner** [comment]
Just to be sure: try to set `"EnableCurl": "1",` in config.txt. it switches from the Powershell build-in web request functions to an external tool curl.exe (a tool, that comes with RainbowMiner)
