### ISSUE TITLE
New Pool Suggestion nlpool.nl

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#179]
I found new auto exchange pool nlpool.nl
It looks good. How about we give it a try in Rainbowminer?

**Comment by Yamanipanuchi** [comment]
You can add it yourself. I just took ZPool.ps1 made a copy and edited the URL's... The script is very smart at figuring out all the Algo's and what not.

**Comment by RainbowMiner** [comment]
Ok, I will add it :)
