### ISSUE TITLE
(Feature Request ) Show IP address and country flag on top pf Rainbow Miner dashboard 

### ISSUE THREAD

**Issue by cleanerspam** [RainbowMiner/RainbowMiner#1794]
Useful for people to know at glance that through which ip (country) there data is moving and to check /prevent data leakage in hostile regions

**Comment by cleanerspam** [comment]
Any Updates ?

**Comment by RainbowMiner** [comment]
Not yet. 
Question: do you refer to the IP address of the rig or the IP addresses of the running miners?

**Comment by cleanerspam** [comment]
I meant the external IP address that the ISP provides  , I want the Dashboard at top to show the IP address which the pool sees for my miners along with country flag , so as i can easily check if all data is being sent through proxy/vpn or not

**Comment by cleanerspam** [comment]
Hey , any update ?

**Comment by RainbowMiner** [comment]
Thanks for the reminder. I have just added all functionality for that to rbminer.net, plus a new endpoint "/remoteip" for the localhost API. Next, I will add an output and flag to the Dashboard.

**Comment by cleanerspam** [comment]
Hey ,
Thabks for pushing update that aimed to bring this feature , unfortunately it is not working , I cant see flag or country name in either Dashboard or Console Page 

Do i have to install any additional dependency to get it too work ?

**Comment by RainbowMiner** [comment]
Hi, in fact, there is something:
- either enable the status page at https://rbminer.net/monitoring (create yourself a MinerStatusKey and add it to config.txt:  https://rbminer.net/monitoring/?action=createkey)
- or add a dummy coin to coins.config.txt, that is not supported by Coinbase (e.g. TON)

Reason is, that new service accesses a local database at rbminer.net. I think, I should add an extra call at the start of Rainbowminer.
