### ISSUE TITLE
OpenCL device detection has failed.

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#18]
The Miner doesn't detect my gtx1080ti, also using ListGPU batch gives me the result below.. 
![image](https://user-images.githubusercontent.com/35561346/44142025-2c5c29e4-a07f-11e8-9c82-bb21c1abc892.png)

In addition to that there is an error as below before it contiunes with benchmarking but only algos for the CPU. Need help with resolving the issue before I can go ahead and use your miner..

![image](https://user-images.githubusercontent.com/35561346/44142073-5f8bcfb8-a07f-11e8-97c1-f71b360db452.png)

![image](https://user-images.githubusercontent.com/35561346/44142101-75c545de-a07f-11e8-99bf-9bf7d5e320e0.png)

**Comment by RainbowMiner** [comment]
Hi, it looks like you are running an old powershell version (please have a look at Issue #1 )
These are the steps, that might help:
- (re-)install Powershell v6.0.4, download actual release here: https://github.com/PowerShell/PowerShell/releases/download/v6.0.4/PowerShell-6.0.4-win-x64.msi
- check, if you are using uptodate Nvidia drivers version 398.82, download actual drivers here: https://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/Windows/398.82/398.82-desktop-win10-64bit-international-whql.exe&lang=us&type=TITAN
- check, if Powershell is in your PATH: I had to manually add C:\Program Files\PowerShell\6.0.4 to my PATH after installing the Powershell 6.0.4. Here is a nice tutorial, how to add to PATH environment variable https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/amp/

Now everything should be fine.

RBM

**Comment by ebojali** [comment]
Thanks for helping me out,

1st bullet: I think the powershell is correctly installed since it started the benchmark etc I use 6.0.2 as seen in the pic below:
![image](https://user-images.githubusercontent.com/35561346/44148250-dc229238-a097-11e8-8f55-06003ac0f3e2.png)


2nd bullet: The drivers used are quite up to date and I would not believe it is up to the drivers. The version I use is 398.36

3rd bullet: I think the path is added correctly as ListGPUs now runs but openCL still failes to find the GPUs
![image](https://user-images.githubusercontent.com/35561346/44148460-ce1c16fe-a098-11e8-87a3-822ee539882e.png)

**Comment by RainbowMiner** [comment]
Ok, there is something wrong.
Would you please download the updates ListGPUs.ps1 to your miner's folder and try ListGPUs.bat again? What is the error message, you get?

Download from this link (use right-click "Save link as..") https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/ListGPUs.ps1

**Comment by RainbowMiner** [comment]
A fourth bullet to be checked:
- for OpenCL to function correctly, Microsoft .NET Framework 4.5.1 (or later) is mandatory. The current version can be downloaded from here: https://www.microsoft.com/net/download/dotnet-framework-runtime

RBM

**Comment by RainbowMiner** [comment]
Ok, now it is clear: Window 10 has messed up your Nvidia drivers, possibly during one of it's past updates. Please install the newest drivers from here: https://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/Windows/398.82/398.82-desktop-win10-64bit-international-whql.exe&lang=us&type=TITAN
.. and reboot afterwards. Then, everything should be fine.

RBM

**Comment by ebojali** [comment]
Not really sure that that is the case here, I will reinstall the drivers but could you tell me what dll file it is looking for and in what folder? I see i have openCl dll files see screen below:
![image](https://user-images.githubusercontent.com/35561346/44170297-33aa1f00-a0d7-11e8-9d72-aefdf744b3f0.png)

**Comment by RainbowMiner** [comment]
I had this problem some time ago: Windows had replaced the Nvidia OpenCL dll with it's own version and the Miner-API stopped working.
So - thumbs pressed - let's hope, that after a fresh driver install, everything is ok.

RBM

**Comment by ebojali** [comment]
I can now confirm that it works fine with the new drivers, algoht some other problems occur with miners crashing at benchmark but I will open a new ticket for those..

**Comment by RainbowMiner** [comment]
Perfect :)
