### ISSUE TITLE
Missing Flux Coin in 2miners pool

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1800]
Hi, I just found out there is no Flux option in 2 miners
![image](https://user-images.githubusercontent.com/44210627/139674680-7ab59077-4ca1-4f4a-8b1e-f9af485ed31e.png)
Zelcash was rebrading to FLux on March ago

**Comment by RainbowMiner** [comment]
Thank you! I'll update the pool asap.

**Comment by RainbowMiner** [comment]
Ok, done.
