### ISSUE TITLE
--lock-cclock on trex

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1801]
This is a really strong feature but unfortunately I had to disable it since the locked clock appear to persist when switching to other algos. Is there a way to make sure it resets when switching algorithms?

**Comment by acos0874** [comment]
https://forum.hiveos.farm/t/locked-core-clock-speed-is-much-better-than-power-limit-why-is-not-included-by-default/29803

According to this article, locking core clock might actually be possible through nvidia-smi. Is it possible it could be added to ocprofiles?

**Comment by acos0874** [comment]
It looks like this was already raised in issue #503

**Comment by acos0874** [comment]
https://github.com/trexminer/T-Rex/issues/503

It was raised as an issue and solved on the trex github. It requires trex to be shut down in a way that allows it to perform a clean up operation.

**Comment by RainbowMiner** [comment]
> https://forum.hiveos.farm/t/locked-core-clock-speed-is-much-better-than-power-limit-why-is-not-included-by-default/29803
> 
> According to this article, locking core clock might actually be possible through nvidia-smi. Is it possible it could be added to ocprofiles?

In fact, that should be pretty straightforward to implement. I will dig into this tomorrow.

**Comment by acos0874** [comment]
Thanks. Keep in mind I don't think it works on all cards. I tested using
lock clock in trex with 1070tis and it didn't work. Might be different for
nvidiasmi.

**Comment by acos0874** [comment]
This is working really well on the core clock thanks. The locked memory clocks seem a bit off. I tested this on 1660tis and 3090s and setting a locked mem clock had no effect. On the 3090 when I tried to use locked at 0 (which I assumed meant it would reset the value), the mem clock was getting stuck at 800mhz and I had to reset the drivers to get it unlocked again.

**Comment by RainbowMiner** [comment]
> On the 3090 when I tried to use locked at 0 (which I assumed meant it would reset the value), the mem clock was getting stuck at 800mhz and I had to reset the drivers to get it unlocked again.

That's weird - I'll check it. On my 3070s the reset works.

**Comment by RainbowMiner** [comment]
Ok, I have found and fixed the problem. It worked for me, because I always reset both, LockMemoryClock and LockCoreClock.
There was a bug in the overclocking function, that did set the memory clock to 0, in case only the LockMemoryClock would have been reset.

**Comment by acos0874** [comment]
Hi, the lock memory clocks still don't seem to be working on 1660tis. Please can you look into it cos this new card I just got is strangely different to the others?
