### ISSUE TITLE
Linux version incorrectly detects Zen2 processor as AVX2 only 

### ISSUE THREAD

**Issue by PapaChealio** [RainbowMiner/RainbowMiner#1803]
Ubuntu 21.10
RBM 4.7.7.1
AMD Ryzen 3900x CPU

When GlobalCPUInfo.Features table is built in Modules/Include.psm1, the "sha_ni" CPU features flag is sanitized to become "shani". Regardless, neither flag is caught by miners, such as CpuminerJayddee, which look strictly for a "sha" flag as part of determining which binary version to use. In that example, "cpuminer-avx2" is used instead of the proper "cpuminer-zen".

`..elseif($f.avx2 -and $f.sha -and $f.aes){'zen'}...`

I suggest modifying the logic to be:

`..elseif($f.avx2 -and ($f.sha -or $f.shani) -and $f.aes){'zen'}...`

There may be a larger and/or more elegant fix required here to amalgamate all the "sha" flag variants into a single one to keep miner logic simple, but thought I'd point this out.

**Comment by RainbowMiner** [comment]
Thank you very much for letting me know! The problem is solved.

**Comment by PapaChealio** [comment]
Perfect, thanks!
