### ISSUE TITLE
FIRO not mined on ZergPool

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1804]
For some reason RainbowMiner won't mine FIRO on ZergPool since the algorithm change.
[debug_2021-11-04.zip](https://github.com/RainbowMiner/RainbowMiner/files/7475624/debug_2021-11-04.zip)

**Comment by RainbowMiner** [comment]
RainbowMiner sorts ZergPool out, most probably, because the pool gets so low hashrate on FiroPow, thus the resulting TTF is greater than 17 hours, currently.
