### ISSUE TITLE
MaxTTF doesnt seem to work correctly

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1805]
I set ZergPoolCoinsSolo pool MaxTTF to 3h and not choosing any CPU coins. Increased it up to 4h, 6h, 8h, 16h, 48h.
At some point it started mining GravityCoin, not sure when.
At 48h most of my CPU miners started mining BELL with Yespower.
I did the calculation on one rig. My calculation is based on 64.5kh pool rate with pool TTF of 61s. My hash rate on this rig is 487h.s.
That is approximately 135 min TTF, right?

Zergpool shows my TTF is about ~30 minutes for all rigs combined that are mining this coin, 2.7kh/s.
Can you check that this is calculated correctly? It should have been mining this solo at 3h.
[solo ttf debug_2021-11-04.zip](https://github.com/RainbowMiner/RainbowMiner/files/7477328/solo.ttf.debug_2021-11-04.zip)

**Comment by RainbowMiner** [comment]
Yes, you are totally right. I had a factor wrong.
