### ISSUE TITLE
How to use duplicate coins per client?

### ISSUE THREAD

**Issue by Gibby** [RainbowMiner/RainbowMiner#1806]
Here is my use case:

1 - Server
3 - Clients

Server and Client 1, are setup to mine the same.
Client 2, I want to mine on Ethermine with Coin ETH-1
Client 3, I want to mine on Ethermine with Coin ETH-2

Right now I just set Client 2 and Client 3 to only get scheduler from the server, so almost like a standalone.

Would like to be able to have client 2 and client 3 get configs from server, but allow a single over ride for the ETH wallet address.

Also, would like the server to report on all 3 Ethermine ETH balances.

Reason. 
Client 2 and Client 3 are my kids gaming PC's. I would like the server to manage them, but payout go to their own ETH wallets.

**Comment by RainbowMiner** [comment]
If you want to provide the individual rigs with specific config files, put these files into a subdirectory `.\Config\<workername>` (linux: `./Config/<workername>`) . Use lowercase letters for the subdirectoy `<workername>`.

In your case, you could simply copy your server's coins.config.txt into the subdirs and change the ETH coin. If you have setup the pool wallets in pools.config.txt in the way `  "ETH": "$ETH",`, the clients would mine to different wallets.

**Comment by Gibby** [comment]
@RainbowMiner I did that, however, the balances only shows the balance for Ethermine from the server.
