### ISSUE TITLE
Configure Failed Benchmark Reattempt Count

### ISSUE THREAD

**Issue by rpringst** [RainbowMiner/RainbowMiner#1808]
Whenever redoing all benchmarks, some miner+algo combinations naturally will crash. It seems that the default number of Total attempts Rainbow is using is 5. Is this configurable in any of the config files? I could not find anything specifically mentioned in the manual. Thanks in advance!

**Comment by RainbowMiner** [comment]
Surprisingly, there is no parameter for that, currently.
It is fixed to 3 for most GPU, 4 for most CPU miners/algorithms and 5 for miners/algorithms, that need more time to deliver accurate results. The main problem with the benchmarking is, that we do not distinguish between a miner, that is running but fails to deliver hashrate and a crashing miner, at the moment. 
I will add an enhancement for that: a parameter for maximum crashes during benchmark, that will be compared against the miner's crash counter. That should help shorten the benchmarks.

**Comment by RainbowMiner** [comment]
Done:
- add parameter "MaxCrashesDuringBenchmark" [default=2] to config.txt. Let's benchmark fail, if a miner crashes more often, than that number (issue #1808)

**Comment by rpringst** [comment]
> Done:
> 
> * add parameter "MaxCrashesDuringBenchmark" [default=2] to config.txt. Let's benchmark fail, if a miner crashes more often, than that number

Thank you!
