### ISSUE TITLE
How to disable MRR gracefully?

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1809]
I want to disable MRR to do some overclocking and benching, but it's hard to actually take my rig down when none of the GPUs are being rented. Is there a way to prevent further rentals without cancelling current ones?

**Comment by RainbowMiner** [comment]
I would do the following in pools.config.txt:
- add all currently not rented workers to the "ExcludeWorkerName" list (comma separated)
- set "PauseBetweenRentals" to a long enough time

Now wait until the last rental is done and then add the last worker name to that "ExcludeWorkerName" list. Now you are free to work with the rig.

**Comment by samdave123** [comment]
Thanks, Ash also suggested setting a really high PF value.

**Comment by RainbowMiner** [comment]
> Thanks, Ash also suggested setting a really high PF value.

There is a small goodtoknow with that solution: MiningRigRentals limits the maximum price and will set it automatically to that value, in case the rental prices are too high. So don't be alarmed, if your prices on MRR are smaller than Profit x PriceFactor
