### ISSUE TITLE
 Add pool SeroPool 

### ISSUE THREAD

**Issue by kriswebdev** [RainbowMiner/RainbowMiner#1810]
Hi, I've added [SeroPool](https://pool.sero.cash/) support here https://github.com/kriswebdev/RainbowMiner/commit/40d5b72b057acfd5807da79936185d54d7445e21 This pool is listed as the main SERO pool in [miningpoolstats](https://miningpoolstats.stream/superzero).

Mining is working if it's the only option, however profitability is not implemented yet.

I don't fully understand what you expect in the pool `Set-Stat` function call especially the `Value` parameter. It's taking too much time retro-engineering this part so I'm asking.

**→ Can you develop what should be in this field, the unit, how it is generally calculated, how it is used, etc?**

Also, this coin/pool has issues in WhatToMine: 
- Negative SERO coin profitability (see [here](https://whattomine.com/gpus/61-nvidia-geforce-rtx-3080-ti?cost=0.1) at the bottom for example). Minerstat does a better job at calculating the profitability (see [here](https://minerstat.com/hardware/nvidia-rtx-3080-ti) for comparison)
- SeroPool not present in WhatToMine 

**→ Does it affect the profitability and coin/pool priority in Rainbowminer?**

**Comment by RainbowMiner** [comment]
Thank you very much! I'll add this pool.

> Also, this coin/pool has issues in WhatToMine:

No problem, we are already using Minerstat instead of WhatToMine. I know, it's a little confusing, but I haven't changed the nomenclature, yet. I'll change it in the future.

**Comment by kriswebdev** [comment]
I've added a fix to the pool balance : https://github.com/kriswebdev/RainbowMiner/commit/a8330f17e6ec8829aa7c3da8a55cdd470a847fa4

However the balance is still unusable:
1. The API reports 0 on the specific the unpaid values ("balance" and "immature") when called form script instead of browser. We probably need to spoof some header, to test.
2. As ZERO chain is a "privacy" blockchain with a strong focus on anonymous transactions, we can't get the wallet balance from the blockchain just from a public key.

The "Paid" info is reliable (as long as the miner doesn't change its IP address I guess), however it not used in the console as far as I can see. It is anyway not a good idea to try to guess a wallet balance from a pool info.

I don't think there is any easy way out of this second issue.
