### ISSUE TITLE
Equihash 125 Rental

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1811]
I think there is a problem with Gminer when getting Equihash 125 rentals. MiniZ seems to work fine. Please can you check?

**Comment by RainbowMiner** [comment]
Yes, it looks like Gminer has a principle problem with Equihash 125, currently. I am checking.

**Comment by RainbowMiner** [comment]
This seems to be fixed with the new Gminer v2.72.
