### ISSUE TITLE
Invalid Config in some miners

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1812]
Hi, I am setting up a new RX 6600 non XT RIG and found some interesting Issues.

1. Nanominer invalid config
![image](https://user-images.githubusercontent.com/44210627/140826702-be2c0155-5696-419f-9be1-d8a94e07d762.png)

I removed the [ethlowmemory] and start the miner alone. It can work normally.
So probabaly that algorithm line cause the issue.

2. Auto tuning miner (Teamred, Phoenix, Nanominer etc )
Auto tuning miner sometimes causing "openCL call error -4(263)" for the next miner/algo.

I found out we need to do the diable/able trick like in RX VEGA .
Can we escalate the current feature Reset "EnableResetVega": "0" 
to any GPU that need to be reset?

3. SRBminer haven't support this card
![image](https://user-images.githubusercontent.com/44210627/140829425-89e006a4-d962-4d15-a1e9-1e0433d2642d.png)
no wonder all the benchmark are failed and the miner always force closed
![image](https://user-images.githubusercontent.com/44210627/140829546-60275e8a-bd58-4665-b642-1b4414651fc0.png)
but it this also happen in RX VEGA GPUs RIG

here is some debug for referenc
[debug_2021-11-09 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/7500643/debug_2021-11-09.1.zip)
[debug_2021-11-09.zip](https://github.com/RainbowMiner/RainbowMiner/files/7500644/debug_2021-11-09.zip)
[debug_2021-11-09 (2).zip](https://github.com/RainbowMiner/RainbowMiner/files/7500645/debug_2021-11-09.2.zip)
e

**Comment by RainbowMiner** [comment]
Ok, I have fixed the Nanominer and added a potential reset fix for the RX6x00 and RX5x00 GPUs. Please let me know, if the `switch-radeon-gpu.exe` really is able to disable/enable these GPUs.

**Comment by rizkyaulya** [comment]
how to use switch-radeon-gpu.exe in rbminer? config file or only work via autoexc?

**Comment by RainbowMiner** [comment]
Config file. Set `"EnableResetVega": "1",` in config.txt.
