### ISSUE TITLE
Raptoreum Profitability Seems to be Off

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1814]
According to this https://mineraptoreum.com/ a hashrate of 2038 h/s should yield about $2.27 per day.  RM shows profitability for the same speed at $0.002

Also could you add this miner for Raptoreum please

https://github.com/WyvernTKC/cpuminer-gr-avx2/releases

**Comment by RainbowMiner** [comment]
Which pool causes that trouble? Is it RPlant?

**Comment by jch9678** [comment]
It's zpoolcoins

**Comment by RainbowMiner** [comment]
It's fixed - the profit calculation for ZpoolCoins has been wrong.

**Comment by jch9678** [comment]
Thanks

**Comment by jch9678** [comment]
What do you think about that miner?  It may be tough to implement because there are different binaries depending on your cpu.

**Comment by PapaChealio** [comment]
jch9678: "It may be tough to implement..."
RainbowMiner: "Hold my beer."

=)

**Comment by jch9678** [comment]
Hahaha. 
A quick and dirty way would be to treat each binary as a different miner and benchmark them all.  A little more complicated would be too benchmark the miner with the most instructions set, then if it fails, fall back to the next miner with less instructions set, and so on.

**Comment by RainbowMiner** [comment]
> jch9678: "It may be tough to implement..."
> RainbowMiner: "Hold my beer."

That nails it pretty accurate =)
