### ISSUE TITLE
Raptoreum Zergpool/Benchamrk?active Miner

### ISSUE THREAD

**Issue by Adiuk** [RainbowMiner/RainbowMiner#1817]
Seems to be a problem with Zergpool and raptoruem, its shows as benchmarked in my benchmark tab, but does not show under active miners although it always used to be the best coin to mine. It is now double the price but still not showing on console. Something wrong somewhere.

**Comment by RainbowMiner** [comment]
It's due to the very long time to find a block of 8 hours for RTM. The real profitability for mining decreases, if that timespan increases. Therefor this coin gets sorted out, currently.

**Comment by Adiuk** [comment]
It seems to be more than that I set cpu to mine take2 only and all of the miners available work for about 2 minutes then just close down. Eventually disregarding the miners and mines nothing from cpu unless I delete the take 2 algo setting from device config

**Comment by paulpoco** [comment]
My GPU fails benchmark for take2.

My CPU passes 3 benchmarks but fails to be in the CPU list in the console.
1.06kh/s  right now that shows as negative profit so maybe that is why I don't see it. 
[debug_2021-11-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/7529031/debug_2021-11-12.zip)

**Comment by paulpoco** [comment]
My estimate 
![Screenshot_20211112-084316_Chrome](https://user-images.githubusercontent.com/801414/141503158-e86d19ee-8dd7-4b16-8bf8-d4c13176f575.jpg)

**Comment by paulpoco** [comment]
If you had a 5900x
![Screenshot_20211112-084613_Chrome](https://user-images.githubusercontent.com/801414/141503507-e1c1f0e4-73b3-4155-adc1-4270f9fae5ac.jpg)

**Comment by acos0874** [comment]
> It's due to the very long time to find a block of 8 hours for RTM on ZergPool. The real profitability for mining decreases, if that timespan increases. Therefor this coin gets sorted out, currently.

I increased the TTF limits in rbm and still nothing showed. Is it possibly a name mismatch between take2 and ghostrider algos?

**Comment by paulpoco** [comment]
> > It's due to the very long time to find a block of 8 hours for RTM on ZergPool. The real profitability for mining decreases, if that timespan increases. Therefor this coin gets sorted out, currently.
> 
> I increased the TTF limits in rbm and still nothing showed. Is it possibly a name mismatch between take2 and ghostrider algos?

Zergpool calls it "ghostrider" on the main part of website.

Then if you click "ghostrider" each won block has Raptoreum(ghostrider) listed  and nothing about take2 Algorithm.

**Comment by paulpoco** [comment]
> It's due to the very long time to find a block of 8 hours for RTM on ZergPool. The real profitability for mining decreases, if that timespan increases. Therefor this coin gets sorted out, currently.

Could RBM look at a number of past won blocks to get a better estimate?   I do guess RBM is helping pick something that earns a lot sooner.

**Comment by RainbowMiner** [comment]
Here is the explanation from the Raptoreum developers:
> CPU miner that supports Raptoreums Ghostrider algorithm (Take2). Take2 is smoother and faster then the original GhostRider.
RainbowMiner internally translates "ghostrider" to "Take2".

I'll try to add that WyvernTKC CPU miner

>It seems to be more than that I set cpu to mine take2 only and all of the miners available work for about 2 minutes then just close down. Eventually disregarding the miners and mines nothing from cpu unless I delete the take 2 algo setting from device config

There is still a good possibility, that the miner get's sorted out for some reason. It might be needed, that I increase the hashrate tolerance, since that algorithm really, really changes the hashrate by a huge margin.

> I do guess RBM is helping pick something that earns a lot sooner.

Yes, the profit switcher will always try to optimize the rig's profit.

**Comment by paulpoco** [comment]
Today it picked up and is using Take2
![image](https://user-images.githubusercontent.com/801414/141661743-3eb3fd65-f34b-4624-8c59-f1f624a85d6d.png)

**Comment by paulpoco** [comment]
> Here is the explanation from the Raptoreum developers:
> 
> > CPU miner that supports Raptoreums Ghostrider algorithm (Take2). Take2 is smoother and faster then the original GhostRider.
> 
> RainbowMiner internally translates "ghostrider" to "Take2".
> 
> I'll try to add that WyvernTKC CPU miner
> 
> > It seems to be more than that I set cpu to mine take2 only and all of the miners available work for about 2 minutes then just close down. Eventually disregarding the miners and mines nothing from cpu unless I delete the take 2 algo setting from device config
> 
> There is still a good possibility, that the miner get's sorted out for some reason. It might be needed, that I increase the hashrate tolerance, since that algorithm really, really changes the hashrate by a huge margin.
> 
> > I do guess RBM is helping pick something that earns a lot sooner.
> 
> Yes, the profit switcher will always try to optimize the rig's profit.

What about this miner?  https://github.com/WyvernTKC/cpuminer-gr-avx2/releases

**Comment by paulpoco** [comment]
@RainbowMiner trying this Flockpool and miner directly, from screenshot it say 222 minutes or 3hrs 42min.
And the miner needs to be run as admin.
![image](https://user-images.githubusercontent.com/801414/141685918-ba9d2e32-512c-4764-9317-faf09339a4fe.png)

**Comment by RainbowMiner** [comment]
I'll try to figure out a way to integrate that miner a smart way. This tuning process is a bit difficult to handle.

**Comment by RainbowMiner** [comment]
Ok, I have added that miner with commit b88c6a312f757098e8951429fee9dc04a556b571 :
- mine RTM with Take2/Ghostrider algorithm
- if you already have a "tune_config" file (see https://github.com/WyvernTKC/cpuminer-gr-avx2), just wait until the miner is being installed in path `.\Bin\CPU-Wyvern` and then copy that file there. It will be picked up automatically. If you are lucky and there is already a preset available for your cpu (all presets are in subfolder `.\Bin\CPU_Wyvern\tune_presets`), this preset will be copied to "tune_config" upon first start of the miner.

**Comment by paulpoco** [comment]
Thanks.

I have been running the "tuning" for 3hrs and 45 minutes left directly on Flockpool.
Ryzen 7 1700  I probably will be nowhere close to a Ryzen 3900x or 5900(x)

Did you add [https://flockpool.com/](https://flockpool.com/) ?

**Comment by RainbowMiner** [comment]
> Did you add https://flockpool.com/ ?

Not yet - I have it setup as userpool, currently.

userspools.config.txt, inserted at the end of the record:
```
{
...
    },
    {
        "Enable":  "1",
        "Name":  "FlockPool",
        "PoolFee":  "1",
        "Algorithm":  "Take2",
        "CoinName":  "Raptoreum",
        "CoinSymbol":  "RTM",
        "Currency":  "RTM",
        "Protocol":  "stratum+tcp",
        "Host":  "eu.flockpool.com",
        "Port":  "4444",
        "User":  "$Wallet.$WorkerName",
        "Pass":  "x",
        "Region":  "EU",
        "SSL":  "0",
        "Worker":  "$WorkerName",
        "EthMode":  ""
    }
}
```

**Comment by RainbowMiner** [comment]
> I have been running the "tuning" for 3hrs and 45 minutes left directly on Flockpool.
Ryzen 7 1700 I probably will be nowhere close to a Ryzen 3900x or 5900(x)

Wow. Would you be so kind and upload the `tune_config` file here? It was a Ryzen 7 1700 on Windows, right?

**Comment by paulpoco** [comment]
> > I have been running the "tuning" for 3hrs and 45 minutes left directly on Flockpool.
> > Ryzen 7 1700 I probably will be nowhere close to a Ryzen 3900x or 5900(x)
> 
> Wow. Would you be so kind and upload the `tune_config` file here? It was a Ryzen 7 1700 on Windows, right?

I didn't read the setting said threads and not cores,  I only set to 8 and not 16.
Do I do it again with 16.  And later if I have problems using PC keep tune_config but change threads to 14 in the config.json file?
![image](https://user-images.githubusercontent.com/801414/141694522-b7b32bb2-a72b-4327-a5eb-c2fe17b714eb.png)

**Comment by paulpoco** [comment]
@RainbowMiner started again with 16 threads.  See screenshot, it is not pegging 100%.
![image](https://user-images.githubusercontent.com/801414/141695418-ef0a3225-7657-411e-a303-0626a3d17c1b.png)

**Comment by paulpoco** [comment]
And if you set 
"benchmark": true,
After it was done the tuning, it would just benchmark over and over again.
![image](https://user-images.githubusercontent.com/801414/141695924-0d2e7210-cc7c-4075-8250-bd35bba22d1e.png)

**Comment by RainbowMiner** [comment]
> I keep the tune_config for 8 threads just in case.

It would be wonderful, if you'ld upload that tune_config. And later the file for the 16 threads. I'ld like to compare the files, just to confirm (or not confirm), that the thread number doesn't matter for these files.

**Comment by paulpoco** [comment]
[Ryzen_7_1700_8_threads.zip](https://github.com/RainbowMiner/RainbowMiner/files/7534607/Ryzen_7_1700_8_threads.zip)
The 8 thread tune_config and benchmark files for 
![image](https://user-images.githubusercontent.com/801414/141697602-3d39cead-bc89-41f4-ada2-2d63396f33ea.png)
![image](https://user-images.githubusercontent.com/801414/141697638-dfe87a29-cb22-4a37-b8a7-a8d39b027358.png)

**Comment by paulpoco** [comment]
@RainbowMiner coming up to 4hrs running the tune for the tune_config with 29 minutes left

**Comment by paulpoco** [comment]
@RainbowMiner Ok here is the finished Ryzen 7 1700 16 thread tun_config and benchmark files.
[Ryzen_7_1700_16_threads.zip](https://github.com/RainbowMiner/RainbowMiner/files/7534974/Ryzen_7_1700_16_threads.zip)

**Comment by paulpoco** [comment]
Ok with 16 threads of course it says CPU 100% but 16 logical threads show like it drawing lower values, see below.
![image](https://user-images.githubusercontent.com/801414/141704951-7b9fdadc-923d-4a1d-9dd7-6bd8fc1a1b5e.png)

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/141707965-9c5f8181-a216-4005-a7d1-834a38a4af68.png)

**Comment by paulpoco** [comment]
15hrs so far.  Ryzen 7 1700 @ 16 threads
![image](https://user-images.githubusercontent.com/801414/141802738-7cb3cfb0-05bb-48ec-8080-dc6ebd7608ae.png)

**Comment by paulpoco** [comment]
27hrs so far. Ryzen 7 1700 @ 16 threads
![image](https://user-images.githubusercontent.com/801414/141888397-4f0230eb-a221-40ea-bcdb-0576977918d6.png)

**Comment by paulpoco** [comment]
@RainbowMiner 

Protocol = setup your own protocol, if it differs from the default [default=stratum+tcp / stratum+ssl]

But Flockpool uses "url": "stratum+tcps://us-west.flockpool.com:5555",

I have RTM defined in coins.config or what ever it is called.

  {
    "Enable":  "1",
    "Name":  "Flockpool",
    "PoolFee":  "1",
    "Algorithm":  "Take2",
    "CoinName":  "Raptoreum",
    "CoinSymbol":  "RTM",
    "Currency":  "RTM",
    "Protocol":  "stratum+ssl",
    "Host":  "us-west.flockpool.com",
    "Port":  "5555",
    "User":  "$Wallet.$WorkerName",
    "Pass":  "somepasword",
    "Region":  "US",
    "SSL":  "1",
    "Worker":  "$WorkerNamer",
    "EthMode":  ""
  }

It isn't selecting Flockpool

I even in pools.conf filled in under zergpool exclude take2 as it it was only doing zergpool and it want flockpol, so now no CPU gets picked.  It isn't really acknowledging flockpool.

For now will just use autoexec line to start the miner I already have working just fine from an outside folder.

[debug_2021-11-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/7543530/debug_2021-11-15.zip)

**Comment by RainbowMiner** [comment]
To enable a userpool, three steps are mandatory:
- 1st define your pool in userpools.config.txt and make sure to set `"Enable": "1",`
- 2nd let RainbowMiner run for at least one round, until your new pools shines up in pools.config.txt. It will have the name defined in `"Name": "FlockPool",` in userpools.config.txt. Now add a wallet address to the new record in pools.config.txt.
- 3rd add your pool to the `"PoolName": "...,FlockPool",` list in config.txt

Now it should be on the localhost's Pool list.

**Comment by RainbowMiner** [comment]
Ok, added :) I even managed to extract TTF and TSL from the official Raptoreum block explorer.

**Comment by paulpoco** [comment]
OK will try it on the later this week

**Comment by paulpoco** [comment]
@RainbowMiner ok I got the new addition of Flockpool working in RBM.  I did set in devices under CPU to only do Take2 and CpuminerWyvern.
![image](https://user-images.githubusercontent.com/801414/142563696-8b3e07fc-33ed-465e-bd15-a7e13aa0d1ca.png)

My question is about CPU affinity.  When I was running the CpuminerWyvern not part of RBM, it never mentioned anything about CPU affinity at the begining like is happening in RBM.  Isn't that is what the tune_config file is for?
![image](https://user-images.githubusercontent.com/801414/142563888-b17eed7b-5c68-4eec-81ce-e8f11929e3e1.png)

Here is what it look like when it starts without using RBM.
![image](https://user-images.githubusercontent.com/801414/142564014-0d5a8678-bdbe-4601-b925-8c84fdee049a.png)

**Comment by paulpoco** [comment]
@RainbowMiner 2nd question will RBM show the actual RTM wallet balance at the bottom like below:
Ok right now below there is nothing to show because past payments went to an Exchange and eventually they disapear from the blockchain.
![image](https://user-images.githubusercontent.com/801414/142564378-5be15446-0137-49d6-9385-f54940e0fb66.png)

**Comment by paulpoco** [comment]
The right side of this graph is the start of using RBM for Flockpool and RTM, will see if RBM setting a CPU affinity will raise or lower my rate.  I did stop for 15 minutes to get it all working.
![image](https://user-images.githubusercontent.com/801414/142565049-4107d8c2-ce20-4679-85ef-40f1a796aa88.png)

**Comment by paulpoco** [comment]
Ok here is the graph after switching to letting RBM handle Raptoreum starting at the 20:00 hour.  So everything just fine.
![image](https://user-images.githubusercontent.com/801414/142666251-979b9656-ca14-4338-8cc8-38f2e7417fdd.png)
