### ISSUE TITLE
Phoenix miner had an issue awhile back,  is it ok to use now?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1818]
Phoenix miner had an issue awhile back,  is it ok to use now?

**Comment by RainbowMiner** [comment]
There have been no issues for us, I always take care that we use clean software.
It was Nicehash, that had accidently distributed a Phoenix miner version, which didn't exist and contained a trojan.

**Comment by paulpoco** [comment]
Ok thanks
