### ISSUE TITLE
[Enhancement] Console and Dashboard : Display SOLO TTF for Solopools

### ISSUE THREAD

**Issue by sxb1n9** [RainbowMiner/RainbowMiner#1820]
pretty much the title but display the SOLO TTF on solopools kind of like the timer on miningrigrentals or another column whatever works best

bonus : also under the console make a column for pool on running miners it sucks to parse the command each time to figure out.

**Comment by RainbowMiner** [comment]
Thank you for the input! It's implemented now.

**Comment by sxb1n9** [comment]
> Thank you for the input! It's implemented now.

I just did a short peer review and looks good.   
Looks like you also fixed some old naming on the Miner.Pool  

One note from peer review that doesn't affect this issue but you should probably fix the Miner.Hashrate variable naming at the same time as doing this one as it should be similar.  However it is only naming scheme and nothing to do with the working of the code. 

Thank you for getting this done.
