### ISSUE TITLE
Number of Rigs in Rentals

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1821]
Just a small cosmetic request please, would you be able to add a 'Number of Rigs in Rentals' on the rminer.net monitoring page.

**Comment by RainbowMiner** [comment]
Ok, done :)

**Comment by sxb1n9** [comment]
No peer review needed as this was only on the rbminer.net site side and does not have the code in this repository

**Comment by acos0874** [comment]
Ace thank you.
