### ISSUE TITLE
TeamBlack always mines with all available GPUs

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1823]
Teamblack ignores the GPU setting and uses all GPUs.
If all GPUs try to mine with TeamBlack, they are all generating DAGs across all GPUs.
Total Scheisse.

**Comment by ZZCoder1** [comment]
Oh, and with Remote Desktop, TeamBlack is also not smart enough to realize that one GPU is virtual, so mines to it 2x, causing low hashrate. So it wouldn't even work for all GPUs in this configuration.

**Comment by RainbowMiner** [comment]
Oh wow! That really sounds like a bad experience. 

> Teamblack ignores the GPU setting and uses all GPUs.

Is this happening on an Nvidia or an AMD or a mixed rig? Windows or Linux? If you have the time - would you please create a Debug file on this system? I'ld like to see, what is happening.
 
> Oh, and with Remote Desktop, TeamBlack is also not smart enough to realize that one GPU is virtual

I'll open an issue on sp_'s Github repos on that. That is really bad.

**Comment by ZZCoder1** [comment]
All AMD. Here is a debug file. I have one GPU device selected, and you can see that Teamblack is using them all.
There are two workarounds. Only select one device in Rainbowminer, and do not use the other cards for anything else! Or, disable Teamblack.
[teamblack debug_2021-11-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/7534300/teamblack.debug_2021-11-14.zip)
