### ISSUE TITLE
list_cpu_features.exe does not detect SSE42 on Xeon X5650

### ISSUE THREAD

**Issue by PapaChealio** [RainbowMiner/RainbowMiner#1825]
I have Ubuntu and Windows servers with identical hardware configuration: the Linux variant picks up the SSE42 feature set and uses it whereas the Windows one does not (defaults to SSE2).

https://ark.intel.com/content/www/us/en/ark/products/47922/intel-xeon-processor-x5650-12m-cache-2-66-ghz-6-40-gts-intel-qpi.html

I've tried both the 4.7.7.3 variant of the list_cpu_features.exe and the previous one from 4.7.7.1 and neither detects the SSE42.

Windows (list_cpu_features.exe from 4.7.7.3):
`arch            : x86
brand           : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
family          :   6 (0x06)
model           :  44 (0x2C)
stepping        :   2 (0x02)
uarch           : INTEL_WSM
flags           : aes,clfsh,cx16,cx8,dca,fpu,mmx,pclmulqdq,popcnt,smx,ss,sse,sse2,sse3,tsc
cache_info      : {"level":1,"cache_type":"data","cache_size":32768,"ways":8,"line_size":64,"tlb_entries":64,"partitioning":1},{"level":1,"cache_type":"instruction","cache_size":32768,"ways":4,"line_size":64,"tlb_entries":128,"partitioning":1},{"level":2,"cache_type":"unified","cache_size":262144,"ways":8,"line_size":64,"tlb_entries":512,"partitioning":1},{"level":3,"cache_type":"unified","cache_size":12582912,"ways":16,"line_size":64,"tlb_entries":12288,"partitioning":1}`

Linux (partial output from cat /proc/cpuinfo):
`processor       : 23
vendor_id       : GenuineIntel
cpu family      : 6
model           : 44
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
stepping        : 2
microcode       : 0x1f
cpu MHz         : 2925.936
cache size      : 12288 KB
physical id     : 0
siblings        : 12
core id         : 10
cpu cores       : 6
apicid          : 21
initial apicid  : 21
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 5319.94
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:`

**Comment by PapaChealio** [comment]
I've attached the output from the latest CoreInfo64 app from Microsoft (https://docs.microsoft.com/en-us/sysinternals/downloads/coreinfo) for reference.

[coreinfo64-x5650.txt](https://github.com/RainbowMiner/RainbowMiner/files/7533518/coreinfo64-x5650.txt)

**Comment by RainbowMiner** [comment]
Ok, thank you for reporting this. I'll add a fix asap.

**Comment by RainbowMiner** [comment]
Would you please try the following command (the CHKCPU32.exe is found in the Rainbowminer Includes folder) and post the result here?

`.\Includes\CHKCPU32.exe /x`

**Comment by RainbowMiner** [comment]
My last commit most probably fixes this problem.

**Comment by PapaChealio** [comment]
`<?xml version="1.0" encoding="utf-8" ?>

<chkcpu32>
  <ident>CPU Identification utility</ident>
  <version>v2.14 final</version>
  <copyright>(c) 1997-2017 Jan Steunebrink</copyright>
  <cpu_vendor>Intel </cpu_vendor>
  <cpu_model>Xeon Quad/Six-Core W3670-L5640-E5649-X5690 B1-step</cpu_model>
  <cpu_speed>2660</cpu_speed><speed_unit>MHz</speed_unit>
  <cpu_name>Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz</cpu_name>
  <cpuid_sign>0x0206C2</cpuid_sign>
  <physical_cpus>2</physical_cpus>
  <cores>6</cores>
  <threads>24</threads>
  <htt>1</htt><xd>1</xd><_64bit>1</_64bit><vt>1</vt>
  <mmx>1</mmx><_3dnow>0</_3dnow><sse>1</sse><sse2>1</sse2><sse3>1</sse3>
  <ssse3>1</ssse3><sse41>1</sse41><sse42>1</sse42><sse4a>0</sse4a>
  <aes>1</aes><avx>0</avx><avx2>0</avx2><f16c>0</f16c><fma3>0</fma3>
  <fma4>0</fma4><xop>0</xop><sha>0</sha>
  <l1>6 x 64 KB</l1>
  <l2>6 x 256 KB</l2>
  <l3>12288 KB</l3>
</chkcpu32>`

**Comment by PapaChealio** [comment]
I've tried the new Include.psm1 and it appears to correctly detect the SSE42 now. Thanks!
