### ISSUE TITLE
Server not Mining to selected pools

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1826]
I only have ZergPoolCoinsSolo selected. This rig (server) was only mining to ZergPoolCoinsSolo, then for some reason it started mining to other pools. Looks like the other pools were the ones i was previously mining to. However, the clients are all still mining only to ZergPoolCoinsSolo.
This debug file is taken on the server after it was mining to other pools.
Why did the server start mining to other pools?
[wrong pools debug_2021-11-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/7536277/wrong.pools.debug_2021-11-14.zip)

**Comment by RainbowMiner** [comment]
The rig is working on the daily donation round.

From the logs:
> Donation run started for the next 9 minutes.
