### ISSUE TITLE
DERO Mining

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1827]
Hi, I'm trying to mine DERO on herominers, but I can't get it to show up in active miners. Please can you have a look at what I'm missing?
[debug_2021-11-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/7538929/debug_2021-11-15.zip)

**Comment by RainbowMiner** [comment]
I'ld say it's your `"MaxAllowedLuck": "0.4",` - pool needs to be very lucky (<40%). Just increase that value to something plausible, like "1.5" (=150% luck is just ok, then)

**Comment by acos0874** [comment]
Sorted thanks.
