### ISSUE TITLE
First Run of RainbowMiner on Windows Dropping into Paused by Error Mode

### ISSUE THREAD

**Issue by rpringst** [RainbowMiner/RainbowMiner#1828]
Using a fresh download of the most recent release for windows (version 4.7.7.3)

After running install.bat as administrator, I proceed to run start.bat. Typically on first run, I expect to drop into the initial configuration wizard. However, it seems to drop into mining mode without prompting for any sort of input. CPU and GPUs are correctly detected during Rainbow's initialization.

![image](https://user-images.githubusercontent.com/20052754/141788909-5b47ab13-2d22-49c1-8ed7-ffd9259b849b.png)

Should I be using another procedure to complete the initial configuration wizard, or is this a bug?

**Comment by RainbowMiner** [comment]
This is most probably a bug. I'll check this. In the meantime, just exit RainbowMiner and run `Setup.bat` to run the setup.

**Comment by RainbowMiner** [comment]
Thank you very much for reporting this! I have imported this bug aprox. a week ago.
