### ISSUE TITLE
Idea: NLpool LTC wallet

### ISSUE THREAD

**Issue by fbradaric** [RainbowMiner/RainbowMiner#183]
Is there maybe a possibility of adding a LTC wallet option for the new NLpool?

All in all, you are doing a great job with RainbowMiner :)

**Comment by RainbowMiner** [comment]
Of course: just add "LTC": "<yourwallet>", to NLpool's section in pools.config.txt and you are done :)
Alternative:
- got to [C]onfiguration -> [P]ools
- select NLpool
- add LTC wallet
- save & exit

**Comment by fbradaric** [comment]
![image](https://user-images.githubusercontent.com/38699632/46258128-90b23680-c4c5-11e8-95fb-7c6aaa1a1f91.png)

I tried to do it but it seems that LTC is missing from the list

**Comment by RainbowMiner** [comment]
Oh! Looks like it is not reported back from NLpool. I will add LTC to the defaults.

**Comment by RainbowMiner** [comment]
Ok, I added it to the pool. If you want a quick update, just download [NLpool.zip](https://github.com/RainbowMiner/RainbowMiner/files/2431709/NLpool.zip) and extract the one file NLpool.ps1 into your "Pools" directory, overwriting the existing one.

**Comment by fbradaric** [comment]
Thank you for the fast fix. I extracted the new file and now I can add a LTC wallet.
