### ISSUE TITLE
Info: Error after Update to 4.7.7.6

### ISSUE THREAD

**Issue by OGizzle** [RainbowMiner/RainbowMiner#1830]
Since the last update I get several times the following error:

TerminatingError(): "Exception calling "FromSeconds" with "1" argument(s): "TimeSpan overflowed because the duration is too long.""
>> TerminatingError(ForEach-Object): "Exception calling "FromSeconds" with "1" argument(s): "TimeSpan overflowed because the duration is too long.""

I don't know if this affects mining in some way. For now it seems to work properly. Can I just ignore it?

**Comment by RainbowMiner** [comment]
Yes, just ignore these message for now.

**Comment by RainbowMiner** [comment]
Ok, don't mind. I think, I have found and fixed the culprit. I'll quickly push another release that includes that fix.

**Comment by OGizzle** [comment]
You were faster to fix it than me trying to get a debug file :-)
Your fix works perfectly, thank you!
