### ISSUE TITLE
Spelling/grammar errors in setup

### ISSUE THREAD

**Issue by PapaChealio** [RainbowMiner/RainbowMiner#1831]
Definitely low priority on this one (except for maybe the error at the bottom), but I noticed a few spelling/grammar errors from 4.7.7.3 that need correcting and would love to see this amazing tool "cleaned up". This list is not complete, but worth an initial pass if you're bored.

Common Setup:
- In default pool datawindow, the 4th option reads "mininum" instead of "minimum".
- "a notification is being triggered" (multiple options) should be "a notification will be triggered"

Other items found in Setup.psm1:
- "Wallet: setup wallet addresses, worker- and username" (remove "-" from "worker-")
-  "Enter the miners your want to use..." (multiple instances, "your" should be "you")
-  "Disable the build-in list of..." (multiple instances, "build-in" should be "built-in")
- "Don't do it, unless you know exactly, what you are doing." (remove commas, or at least the one after "exactly")
- "Maxium error ratio for yiimp pool..." (should be "Maximum", not "Maxium")
- "Priorize heat over profit to heat my flat." (should be "Prioritize" not "Priorize")
- "Use cURL instead of the build in web requests" (should be "built-in" not "build in")
- "After this, in the next minutes, RainbowMiner will download all miner programs. So please be patient and let it run. There will pop up some windows, from time to time." (should be "After this, in the next few minutes, RainbowMiner will download all miner programs. Please be patient and let it run. There will be some popup windows, from time to time.")
- "Enable forced mining a currency for a timespan" (should be "Enable forced mining of a currency for a timespan")
-  "and make sure, that you enter your API-Key" (no comma, should be "and make sure that you enter your API-Key")

Also spotted this error during configuration:
- Enter configuration mode and choose Common config
- Accept defaults on all items until you hit option below

`Enable custom overclocking profiles (MSI Afterburner profiles will be disabled) (yes/no) [default=no]: [Pressed ENTER here]
Write-Log: Unknown setup command "enableocfullreset"enablelinuxheadless". You should never reach here. Please open an issue on github.com`

**Comment by RainbowMiner** [comment]
That was very helpful. Thanks again!
