### ISSUE TITLE
Unable to detect AMD Radeon Pro WX2100 GPU in Linux

### ISSUE THREAD

**Issue by PapaChealio** [RainbowMiner/RainbowMiner#1833]
I'm not sure if this is chronic across all of the workstation-focused AMD cards (i.e. Radeon Pro WX x100), but I've exhausted my options and RBM doesn't seem to pick up the 2 x Radeon Pro WX2100 GPUs I have installed in a test Linux rig (yet the install.sh determines there are 2 AMD GPUs present).

Here's what I've done:
- Installed Ubuntu 20.04.02 LTS
- Updated all system packages with "sudo apt update && sudo apt upgrade -y"
- Downloaded latest amdgpu-pro-21.20-1292797-ubuntu-20.04 driver package and installed as per RBM instructions (./amdgpu-pro-install -y --opencl=pal,legacy,rocm --headless)
- Added /opt/amdgpu-pro/bin to PATH in .profile
- Edit default grub params to use GRUB_CMDLINE_LINUX_DEFAULT="amdgpu.ppfeaturemask=0xfffd7fff"
- Downloaded, built and installed latest rocm-smi tool/library via https://github.com/RadeonOpenCompute/rocm_smi_lib
- Added /opt/rocm/bin to PATH in .profile
- Rebooted
- Installed RBM 4.7.7.7 and run ./install.sh to successfully install PowerShell and initialize system (reports 2 AMD GPUs at the end)
- Run ./setup.sh and complete info (no devices detected)
- Run ./start.sh (no devices detected)

I've tried running multiple miners directly from the shell which all seem to pick up the cards fine and happily mine away.

Output from "rocm-smi --showhw":

======================= ROCm System Management Interface =======================
============================ Concise Hardware Info =============================
GPU  DID   GFX RAS  SDMA RAS  UMC RAS  VBIOS             BUS
0    6995  N/A      N/A       N/A      113-D0910800-101  0000:03:00.0
1    6995  N/A      N/A       N/A      113-D0910800-101  0000:04:00.0
WARNING:                 One or more commands failed
============================= End of ROCm SMI Log ==============================

Output from "SRBMiner-Multi --list-devices":

GPU0  [0][0] [03:00.0] : amd_radeon_pro_wx2100 [gfx804] [2030 MB] [CU: 8] [MaxB: 1725 MB] [MID: 7][CID: 7]
GPU1  [0][1] [04:00.0] : amd_radeon_pro_wx2100 [gfx804] [2038 MB] [CU: 8] [MaxB: 1732 MB] [MID: 7][CID: 7]

Partial output from "/opt/amdgpu-pro/bin/clinfo" for each GPU:

Platform ID:                                   0x7fb214130e70
Name:                                          gfx804
Vendor:                                        Advanced Micro Devices, Inc.
Device OpenCL C version:                       OpenCL C 1.2
Driver version:                                3224.4
Profile:                                       FULL_PROFILE
Version:                                       OpenCL 1.2 AMD-APP (3224.4)

I'm wondering if there is something special about the "name" of these devices that is throwing off RBM's device detection.

**Comment by PapaChealio** [comment]
I should also mention that I have an identical machine running Windows 10 with the appropriate AMD drivers and RBM does pick up and mine with the GPUs there. So this issue is specifically around Linux support for these cards.

**Comment by PapaChealio** [comment]
Log file entry that points out the lack of device detection:

[2021-11-17 01:08:21] INFO: Starting RainbowMiner v4.7.7.7
[2021-11-17 01:08:23] INFO: Curl : /usr/bin/curl
[2021-11-17 01:08:23] INFO: OpenCL device detection has failed: Exception calling "GetPlatformIDs" with "0" argument(s): "Value cannot be null. (Parameter 'path1')"

**Comment by PapaChealio** [comment]
I'm continuing to dig on this and it appears it might be an issue with the older C# wrapper you are using for OpenCL detection (https://github.com/uhrm/opencl-sharp). I'm suspecting that the wrapper may not be synced parameter-wise with newer OpenCL library function exports, though it's a guess.

I've tried overwriting the libOpenCL.so.1.2 in /opt/rainbowminer/lib with the one that came with the amdgpu-pro driver install (/opt/amdgpu-pro/lib/x86_64-linux-gnu/) but it made no difference.

**Comment by PapaChealio** [comment]
Progress!

By adding the following line to .profile, I was able to force RBM to use its own supplied libraries first, which likely match with the C# library mentioned above.

export LD_LIBRARY_PATH=/opt/rainbowminer/lib:$LD_LIBRARY_PATH

With this set, the CS library correctly detects the two AMD cards. I'm actually surprised that the install script doesn't set this or that the main scripts (setup.sh, install.sh, start*.sh etc) don't explicitly set this variable...perhaps you can add that logic for a future release?

**Comment by PapaChealio** [comment]
OK, it's clear that for OpenCL related tasks in RBM the system has to use the RBM-supplied OpenCL libraries specifically. In order to force their usage (but not affect other system libraries), I had to make a copy (links) of those libraries in an isolated folder. I did the following:

sudo mkdir -p /opt/rainbowminer/lib/OpenCL
sudo ln -s /opt/rainbowminer/lib/libOpenCL.so.1.2 /opt/rainbowminer/lib/OpenCL/libOpenCL.so
sudo ln -s /opt/rainbowminer/lib/libOpenCL.so.1.2 /opt/rainbowminer/lib/OpenCL/libOpenCL.so.1 
sudo ln -s /opt/rainbowminer/lib/libOpenCL.so.1.2 /opt/rainbowminer/lib/OpenCL/libOpenCL.so.1.2
 
I then created a new 09-rainbowminer.conf file in /etc/ld.so.conf.d/ that contains the text:

/opt/rainbowminer/lib/OpenCL

The "09-" prefix on the file puts it in front of the amdgpu .conf files, to make sure the RBM folder above is used first.

Then:

sudo ldconfig

This updates the shared library cache, which can be displayed with "sudo ldconfig -p" to show that the OpenCL library for RBM takes priority (first in the list of OpenCL libraries).

This solved my issues (I think) while not causing any issues I can see on the system itself. I use the system headless (i.e. no GUI), so I'm not sure what impact this would have on a GUI-based Ubuntu distribution. I'd be interested on your thoughts on the best way to get around this otherwise.

**Comment by PapaChealio** [comment]
Just realized I went at this the wrong way. The problem is not the version of library involved, it's that the CS files RBM uses are looking for a libOpenCL.so library (without any version suffix on it). You have that link created in your supplied libraries, but the AMD GPU Pro  install doesn't create that .so link, just an .so.1 version. Therefore, the CS code can't find the library (since there is no LD path to it) and fails to detect anything.

So on a whim, I undid all the things I did above and just added a new symlink in the amdgpu-pro folder to its own libOpenCL.so.1.2 library and rebuilt the ldconfig cache:

cd /opt/amdgpu-pro/lib/x86_64-linux-gnu/
sudo ln -s libOpenCL.so.1.2 libOpenCL.so
sudo ldconfig

This fixed the device detection and the miners are happily benchmarking now. I'm not sure if this is a bug in the amdgpu-pro installer, missing the creation of that symlink, or if they don't create it because modern code doesn't link to just the .so library anymore. Anyway, much simpler fix...not sure if you want to add logic into the installer to verify the presence of all the required libOpenCL files and perhaps create the missing symlink for them?

**Comment by RainbowMiner** [comment]
> This fixed the device detection and the miners are happily benchmarking now. I'm not sure if this is a bug in the amdgpu-pro installer, missing the creation of that symlink, or if they don't create it because modern code doesn't link to just the .so library anymore. Anyway, much simpler fix...not sure if you want to add logic into the installer to verify the presence of all the required libOpenCL files and perhaps create the missing symlink for them?

So many thanks for going all that way! This in fact is a perfect solution of the problem. I think this is a bug in the ampgpu-pro installer. That link should have been created. I think, the smartest way would be to check for that library during install.sh (and start.sh) and create it (warn that install.sh should be started again). I'll add code for that.

**Comment by RainbowMiner** [comment]
Ok, I have added a little extra code to the install.ps1, that will do exactly what you have found out. Only if the libOpenCL.so.s.1.2 exists at that exact path. I think, this is a temporary solution to fix that situation.

I am thinking about a more permanent solution by using ldconfig to add libOpenCL.so manually, in case it's not already in the ldconfig cache.

**Comment by RainbowMiner** [comment]
I have added a tweak to the core code, that might solve the detection problem. Could you please try this out on your Linux system? Just remove the .so link and try a restart. Did this help?

**Comment by RainbowMiner** [comment]
Please wait with the test - I have imported a bug. Needs fix, but will be ready in the next minutes

**Comment by RainbowMiner** [comment]
All solved :) It's pretty neat now, actually. I am confident, that this will let us detect the GPUs, even if the libOpenCL.so is nowhere to be found.

**Comment by PapaChealio** [comment]
So, I've downloaded the 4.7.7.9 dist to see how it works. I see that you've left in the missing symlink creation logic in install.sh, which fixes the setup.sh/start.sh process GPU detection. But you also added in logic to the Includes.psm1 to dynamically add the RBM library path to LD_LIBRARY_PATH for what appears to be just the detection portion of the code. You then revert back to the old LD_LIBRARY_PATH after that code section. However, this logic doesn't appear to help with the original device detection issue, so I'm not sure if you had done this to fix something else?

If I remove the symlink, then immediately run setup.sh or start.sh (without running install.sh to restore the link), it doesn't detect the GPUs.

Also related to the LD_LIBRARY_PATH code, I haven't read too much into it but one thing I know is that when I exported the LD_LIBRARY_PATH with the RBM path included originally to fix the missing library issue, this worked for the OpenCL device detection BUT it also messed up other system tools (like wget) due to conflicting libssl libraries you package in that /opt/rainbowminer/lib folder. If you're only altering that LD_LIBRARY_PATH temporarily it should be fine but you may want to double check that. Also, does the code correctly handle the situation where LD_LIBRARY_PATH is empty to begin with (which it normally is)?

**Comment by RainbowMiner** [comment]
> If I remove the symlink, then immediately run setup.sh or start.sh (without running install.sh to restore the link), it doesn't detect the GPUs.

Ah, I think, I know what happened on your system. I'll tell you below. The important sentence will be bold.

I have played around with one RTX3090 rig, installed Ubuntu 20.04, newest Nvidia drivers 495, then removed the symbolic link to the systems libOpenCL.so.1. **Rebuild the ld cache with a call to `sudo ldconfig`** With that, I could reproduce exactly the detection error. Using the new device detection mode, RainbowMiner now detects the GPUs.

This is how I am doing it, currently:
- check, if `ldconfig -p` has no `libOpenCL.so` entry, only if yes:
  - save LD_LIBRARY_PATH  to a temporary variable
  - set LD_LIBRARY_PATH to `/opt/rainbowminer/lib` (or `./IncludesLinux/lib` in case that other folder doesn't exist).
- start separate powershell job to detect GPUs via the DotNet/OpenCL library. The job inherits all currently set env vars thus should find a libOpenCL.so somewhere
- check, if there is a saved LD_LIBRARY_PATH, if yes:
  - restore the env variable to the original state

I think (hope) you didn't use `ldconfig` to rebuild the ld cache after the removal of the `libOpenCL.so` symbolic link. That would lead to a `libOpenCL.so` entry in the result of `ldconfig -p` thus instructing RainbowMiner to do no LD_LIBRARY_PATH magic.

**Comment by PapaChealio** [comment]
> I think (hope) you didn't use `ldconfig` to rebuild the ld cache after the removal of the `libOpenCL.so` symbolic link. That would lead to a `libOpenCL.so` entry in the result of `ldconfig -p` thus instructing RainbowMiner to do no LD_LIBRARY_PATH magic.

You're absolutely right...I had forgotten to re-run `sudo ldconfig` to rebuild the cache (and remove the link from it) after I deleted the symlink to the amdgpu-pro supplied library. Your new LD_LIBRARY_PATH "switcheroo" works as designed and both setup.sh and start*.sh delect the GPUs.

So, now that I've done that I am used the RBM supplied version of the OpenCL libraries for the card. I noticed at least one difference that leads me to believe it is better to use the amdgpu-pro supplied versions (i.e. not manually delete the symlink).

e.g. Running without the symlink in place, RBM constantly reports "WARNING: Could not read power data from AMD" on the console.

**Comment by RainbowMiner** [comment]
> e.g. Running without the symlink in place, RBM constantly reports "WARNING: Could not read power data from AMD" on the console.

Yes, it is always better to use system supplied libs. 
Anyway - maybe the warnings can be solved, if I again temporarily set LD_LIBRARY_PATH when calling rocm .

**Comment by RainbowMiner** [comment]
What happens, if you call `rocm-smi -f -t -P --json` from the command-line on the system with the missing libOpenCL.so? Could you upload the result?

**Comment by PapaChealio** [comment]
This is actually happening with either library (amdgpu-pro or RBM supplied). I had forgotten to add the path to rocm-smi back into system PATH as I had cleaned out all my changes as part of the above testing. Once I added the path, RBM obviously picked up on it and was able to execute it, so it shows that error all the time now.

This is from rocm-smi 1.4.1 I built from latest github source and prefixed to system PATH so it is usable:

`{"card0": {"Temperature (Sensor edge) (C)": "57.0", "Temperature (Sensor junction) (C)": "N/A", "Temperature (Sensor memory) (C)": "N/A", "Temperature (Sensor HBM 0) (C)": "N/A", "Temperature (Sensor HBM 1) (C)": "N/A", "Temperature (Sensor HBM 2) (C)": "N/A", "Temperature (Sensor HBM 3) (C)": "N/A", "Fan speed (level)": "204", "Fan speed (%)": "80", "Fan RPM": "5443", "Average Graphics Package Power (W)": "19.093"}, "card1": {"Temperature (Sensor edge) (C)": "57.0", "Temperature (Sensor junction) (C)": "N/A", "Temperature (Sensor memory) (C)": "N/A", "Temperature (Sensor HBM 0) (C)": "N/A", "Temperature (Sensor HBM 1) (C)": "N/A", "Temperature (Sensor HBM 2) (C)": "N/A", "Temperature (Sensor HBM 3) (C)": "N/A", "Fan speed (level)": "204", "Fan speed (%)": "80", "Fan RPM": "5659", "Average Graphics Package Power (W)": "24.085"}}`

It may be that these are older GPUs (GCN vs. Polaris or newer) and some of the sensors aren't exposed via rocm-smi.

**Comment by PapaChealio** [comment]
![image](https://user-images.githubusercontent.com/35071545/142552631-687d4f6f-c2bc-4ecf-a582-317e9fa10191.png)

**Comment by PapaChealio** [comment]
Looks like this code in Modules/Include.psm1 is throwing the error, as it isn't handling non-numerical values of temperature from the rocm-smi JSON data very well (e.g. "N/A"):

`$_.Data.Temperature       = [decimal]($Data.PSObject.Properties | Where-Object {$_.Name -match "Temperature" -and $_.Name -notmatch "junction"} | Foreach-Object {[decimal]$_.Value} | Measure-Object -Average).Average`

I changed this line to:

`$_.Data.Temperature       = [decimal]($Data.PSObject.Properties | Where-Object {$_.Name -match "Temperature" -and $_.Name -notmatch "junction" -and $_.Value -notmatch "N/A"} | Foreach-Object {[decimal]$_.Value} | Measure-Object -Average).Average`

This solved the problem and power usage is now being reported properly in the interface. You likely have a more graceful way of dealing with this, but at least you know what to fix now.

**Comment by RainbowMiner** [comment]
Ok, done. Thank you very much!
I went the other way round by checking for valid chars `-match "[\d\.]+"`. You never know, if that "N/A" changes to something else in the future. But numbers will be numbers.
