### ISSUE TITLE
TTF calculation on Moneroocean

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1837]
How is this calculated? My console is showing ttf > 1 yr for Ethash on Moneroocean. Their website shows a hash rate of 40Gh/s, which should be 3-4 days according to this calculator:
https://2cryptocalc.com/eth-mining-calculator?hashrate=40000

**Comment by RainbowMiner** [comment]
Yes, that seems a bit off. It's actually around 3-4 days with 41GH/s. I will check the API.

**Comment by RainbowMiner** [comment]
This is fixed, now. The calculation has been based on blocks found within 24h. I have now added a real pool ttf to the API.

**Comment by ZZCoder1** [comment]
Thanks for fixing this. Question, though. I updated to this version, and I have seen TTF at 1.1d earlier, when pool hash rate was 41Ghs/s or so, and now TTF is 3.4d with pool hash rate of 43.7Gh/s. Are you factoring in luck somehow, or is TTF changing so much because ETH difficulty is changing?

**Comment by RainbowMiner** [comment]
> is TTF changing so much because ETH difficulty is changing?

That exactly. It's directly related.
