### ISSUE TITLE
Feature Request. Per Algorithm OC

### ISSUE THREAD

**Issue by MasterDoge1** [RainbowMiner/RainbowMiner#1838]
Some coins like high memory oc while other do not. I would like to be able to set per algorithm OC in the web api. 
Ex) 
When rainbow begins mining eth -> use eth oc profile. 
When rainbow switches to another algorithm -> switch oc profile to different profile
Currently I have msi set my oc but I would like rainbow to choose the optimised oc profile that I find

Edit: This may possibly be added by adding another tab in the web api for a specific coin posibly

**Comment by sxb1n9** [comment]
you can do this in the algorithm config file under OCProfile.

**Comment by RainbowMiner** [comment]
Here is an example of how I have inserted the profile "Ethash" to all Ethash algorithms in `.\Config\algorithms.config.txt`:
```
...
  "EtcHash": {
    "Penalty": "0",
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "MSIAprofile": 0,
    "OCprofile": "Ethash",
    "MRRPriceModifierPercent": "",
    "MRREnable": "1",
    "MRRAllowExtensions": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "MinHashrateSolo": "0"
  },
  "Ethash": {
    "Penalty": "0",
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "MSIAprofile": 0,
    "OCprofile": "Ethash",
    "MRRPriceModifierPercent": "",
    "MRREnable": "1",
    "MRRAllowExtensions": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "MinHashrateSolo": "0"
  },
  "EthashFP": {
    "Penalty": "0",
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "MSIAprofile": 0,
    "OCprofile": "Ethash",
    "MRRPriceModifierPercent": "",
    "MRREnable": "1",
    "MRRAllowExtensions": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "MinHashrateSolo": "0"
  },
  "EthashLowMemory": {
    "Penalty": "0",
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "MSIAprofile": 0,
    "OCprofile": "Ethash",
    "MRRPriceModifierPercent": "",
    "MRREnable": "1",
    "MRRAllowExtensions": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "MinHashrateSolo": "0"
  },
  "EthashNH": {
    "Penalty": "0",
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "MSIAprofile": 0,
    "OCprofile": "Ethash",
    "MRRPriceModifierPercent": "",
    "MRREnable": "1",
    "MRRAllowExtensions": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "MinHashrateSolo": "0"
  },
...
```

Be aware, that there are currently multiple Ethash algorithms, that serve different purposes. You could decide to define different OC profiles for those macro variants:
- **EtcHash** mines ETC Ethereum classic
- **Ethash** the classic Ethereum algorithm
- **EthashFP** currently only used for Teamblack miner, in case that miner mines to a pool, that doesn't pay for stale shares (e.g. FlexPool)
- **EthashNH** currently only used for Teamblack miner, in case that miner mines to Nicehash
- **EthashLowMemory** used, when mining coins on pool ProHashing, that have a very small DAG
