### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#184]
Getting the following error or information while script is refreshing...

Finished waiting - starting next run
WARNING: Miner Status (https://rbminer.net):
<!DOCTYPE html>
<html lang="en-US">

<head>
                <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta name="format-detection" content="telephone=no">
        <meta name="theme-color" content="#ff8c00">
        <link rel="profile" href="http://gmpg.org/xfn/11">
        <link rel="pingback" href="https://rbminer.net/xmlrpc.php">

        <title>RainbowMiner &#8211; most versatile crypto mining and monitoring</title>
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="RainbowMiner &raquo; Feed" href="https://rbminer.net/feed/" />
<link rel="alternate" type="application/rss+xml" title="RainbowMiner &raquo; Comments Feed" href="https://rbminer.net/comments/feed/" />
                <script type="text/javascript">
                        window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/11\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/11\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/rbminer.net\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.9.8"}};
                        !function(a,b,c){function d(a,b){var c=String.fromCharCode;l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,a),0,0);var d=k.toDataURL();l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,b),0,0);var e=k.toDataURL();return d===e}function e(a){var b;if(!l||!l.fillText)return!1;switch(l.textBaseline="top",l.font="600 32px Arial",a){case"flag":return!(b=d([55356,56826,55356,56819],[55356,56826,8203,55356,56819]))&&(b=d([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]),!b);case"emoji":return b=d([55358,56760,9792,65039],[55358,56760,8203,9792,65039]),!b}return!1}function f(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var g,h,i,j,k=b.createElement("canvas"),l=k.getContext&&k.getContext("2d");for(j=Array("flag","emoji"),c.supports={everything:!0,everythingExceptFlag:!0},i=0;i<j.length;i++)c.supports[j[i]]=e(j[i]),c.supports.everything=c.supports.everything&&c.supports[j[i]],"flag"!==j[i]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[j[i]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(h=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",h,!1),a.addEventListener("load",h,!1)):(a.attachEvent("onload",h),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),g=c.source||{},g.concatemoji?f(g.concatemoji):g.wpemoji&&g.twemoji&&(f(g.twemoji),f(g.wpemoji)))}(window,document,window._wpemojiSettings);
                </script>
                <style type="text/css">
img.wp-smiley,
img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
}

**Comment by Yamanipanuchi** [comment]
Got this on two different machines, On two different networks.. Don't know if that helps.

**Comment by RainbowMiner** [comment]
Helps :)

**Comment by RainbowMiner** [comment]
I am not so sure, what caused this misbehaviour, since I do not have this problem, here. I suspect a SSL problem with the powershell invoke function. Please keep me updated, if everything works fine now.

**Comment by RainbowMiner** [comment]
Ok. Found it. I forgot to update the Core.psm1. It called the old report status ps1. Now everything will work.
Sorry for this!
