### ISSUE TITLE
CPU setting seem to not work?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1840]
I've tweeked with my setting on several machines, Unless I mess with the CPU affinity and add a bunch of cores no other setting will use much more than 25% of my CPU. What am I missing? I thought Auto Affinity was supposed to take care of what cores to use.

[debug_2021-11-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/7567801/debug_2021-11-18.zip)

**Comment by PapaChealio** [comment]
I'm not the author, but here are my thoughts. From what I can see, there are a few issues based on your logs.

1. `WARNING: Parameter CPUMiningAffinity (config.txt) is empty or contains errors. Falling back to 0x555555`
For a 12c/24t Ryzen in Windows, you should be using 0x555555 by default. You can override this per miner/algo combo, if required. Its not clear what you actually have set for your affinity, but update it to 0x555555 for now.

2. You aren't running RBM in an admin command prompt. This is recommended to allow RBM and miners to do low-level tweaks (such as MSR changes). XMRig is complaining about this specifically in its logs, which will affect your hashrate.

3. You haven't set the recommended memory pagefile settings in Windows; see the readme notes on how to do this. For CPU-only mining this isn't a huge deal, but still recommended to stop Windows thrashing around with paged memory under high load.

4. As noted in the readme, XMRig may require some custom configuration to maximize performance as it has a ton of tweakable settings in its JSON config file. You may want to try running it standalone outside of RBM to debug what are optimal settings for you, then retrofit RBM to work with that config.

**Comment by PapaChealio** [comment]
If you actually want to use ALL the threads on the CPU by default for all CPU mining, you can change your CPUMiningThreads setting to 24, your CPUMiningAffinity to 0xffffff and optionally change EnableAutoAdjustAffinity to 1 (which will automatically adjust your affinity setting to reduce overall thread count by 1 or 2).

As most modern CPU algorithms are more cache-limited than thread-limited, my advice is to stick to a default of using half the available threads (i.e. physical cores only) via the 0x555555 affinity mask. If you know an algorithm works better with more threads, you can override its thread count and affinity parameters using the "#" trick mentioned in the readme.

**Comment by RainbowMiner** [comment]
That's pretty much it. 

In short:

There are three parameters to adjust the global CPU affinity.
- **CPUMiningAffinity** hex representation of affinity
- **CPUMiningThreads** number of threads (should match the number of 1-bits in CPUMiningAffinity)
- **EnableAutoAdjustAffinity** if this is set to "1", RainbowMiner will automatically reduce the mining affinity/threads, if the system would be overloaded, otherwise.

For an AMD Ryzen, I have best results when mining on all cores+(threads minus 2). For your application, that would lead to:
```
  "CPUMiningThreads": 22,
  "CPUMiningAffinity": "0xFFFFF5",
  "EnableAutoAdjustAffinity": "1",
```

For an Intel processor, I have best results when mining on cores, only. e.g.
```
  "CPUMiningThreads": 12,
  "CPUMiningAffinity": "0x555555",
  "EnableAutoAdjustAffinity": "1",
```

To remove --cpu-affinity & -t  from a miner's command line, use the '#'-method:
- find out, which parameters are being used (e.g. --cpu-affinity for affinity and -t for threads) by looking at the command line, RainbowMiner is using
- edit miners.config.txt and find the miner
- now add the paramters, that you want to have removed to "Params", each followed by a blank and #

e.g.
```
  "Params": "--cpu-affinity # -t #",
```

**Comment by Yamanipanuchi** [comment]
I did not have the 0x on my CPUMiningAffinity. I added it, didn't make a difference. This these setting I do get 50-60% CPU usage which is fine for this machine.

If I left it with the old setting with EnableAutoAdjustAffinity enabled it would only user max 4 cores. I've tried it on multiple machines also.

Eitherway, I call this complete. just thought it was odd.

**Comment by whitindllc** [comment]
how do you figure out the conversion
i put 22 and 0xFFFFFF and it still sets the thread count to 12
is it because of the enable auto adust?

**Comment by imrecsoka** [comment]
I cant understand the 0xFFFFFF  i dont know what it means? and how do u learn the other values

**Comment by imrecsoka** [comment]
what the heck is 0xFFF or 555 whatever it is, and how does this go hand in hand with Threads = value
or do they

**Comment by RainbowMiner** [comment]
It is a hexadecimal notation, where every digit ranges from 0 to F (like 0123456789ABCDEF). Each digit can be converted to 4 binary digits. A binary digit is either 0 or 1. The cores/threads can be addressed via a binary notation. So simply use a converter like https://www.rapidtables.com/convert/number/hex-to-binary.html to translate the hexadecimal number (FFF, 555, FF5 ...) to the binary number, consisting of 0 and 1 only, where 0 means "off" and 1 means "on".
Note: "0x" in front of the hex numbers simply tells the machine that the following number is in deed a hexadecimal number. So you can differentiate between decimal 555 and hexadecimal 0x555.

No go ahead: enter FFF into the hex-to-binary converter and look at the result:
You will get `111111111111` - from right to left it addresses the cores/threads in the form core0-thread0-core1-thread1- ... 
Result: all cores and threads will be "on" for mining

Now enter FF5 into the hex-to-binary converter and look at the result:
You will get `111111110101` - as you can see (again from right to left), core0 = on, thread0 = off, core1 = on, thread1 = off, core2 = on, thread2 = on ...
Result: all cores and threads will be "on" for mining, except thread0 and thread1. So with 0xFF5 you manage to disable two threads for mining. Those threads can now be used by RainbowMiner or the System processes.

**Comment by RainbowMiner** [comment]
> is it because of the enable auto adust?

Yes. It will keep some threads/cores disabled for mining. It is very important, that you reserve some core/thread for your System and for RainbowMiner. Don't ever use all-Fs. It will bring the machine almost to a hold.

**Comment by RainbowMiner** [comment]
Thank you for reporting. Would you please create a new Debug File and upload it?
