### ISSUE TITLE
Failed Benchmark with miner, but it works ok

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#1842]
Hi
Last couple of days my VEGA56 was successfully mining Optical with SrbMinerMulti. But yesterday it decided to mine ETH again as most profitable. I've checked the benchmarks and now SrbMinerMulti says Failed Benchmark. I've tried again, to no avail.
But if I try to manually use the miner with the actual command line used by Rainbow Miner, it mines OK.
I've checked the Log but it's unfinished:
[2021-11-19 17:17:14] GPU0[t0] result accepted [  226ms] [heavyhash][0]
[2021-11-19 17:17:14] GPU0[t0] result accepted [  229ms] [heavyhash][0]
[2021-11-19 17:17:14] GPU0[t0] result accepted [  235ms] [heavyhash][0]
[2021-11-19 17:17:15] GPU0[t0] result

And the RainbowMiner log...
[2021-11-19 17:19:17] INFO: Stopping miner SrbMinerMulti-GPU#00 on pool Zpool. 
[2021-11-19 17:19:17] INFO: Attempting to kill Miner SrbMinerMulti-GPU#00 PID 25636
[2021-11-19 17:19:17] INFO: Miner SrbMinerMulti-GPU#00 closed gracefully

The timestamp does not looks good. And the timestamp of the SrbMinerMilti log is... 17:19:17
So... what's wrong?

**Comment by RainbowMiner** [comment]
This is a duplicate #1849 - and solved. SrbminerMulti has changed the miner's API, silently.

**Comment by Djago** [comment]
Now I have the benchmark OK:
![image](https://user-images.githubusercontent.com/34612740/142864285-786b61c2-37ac-404d-a79c-2183b854b6b4.png)
but HeavyHash is not on my list:
![image](https://user-images.githubusercontent.com/34612740/142864380-10170b42-0cb2-44d8-8afa-581c0f8c6ebd.png)
What can I do to make it back to the list?

**Comment by RainbowMiner** [comment]
It's zpool, right?
The last found OBTC-block is now 18h ago on that pool - therefor RainbowMiner reduces the profitability of Heavyhash on Zpool to zero. It looks like, the difficulty is far too high, currently. So if you don't care and want to mine it on that pool anyway, you will have to adjust "MaxTimeToFind" and "MaxTimeSinceLastBlock" (also maybe "MaxAllowedLuck") in pools.config.txt. But I strongly advise against this. Your earnings will be low.
Other possibility: choose a pool with more hashrate for that algo (https://miningpoolstats.stream/opticalbitcoin)

**Comment by Djago** [comment]
Yes, it's zpool-optical.
But if you advice against it, I'll leave it at that.
Thanks as always!

**Comment by Djago** [comment]
One last question. Why HeavyHash is not on the list of miners?
