### ISSUE TITLE
Bug with server client API?

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1846]
I just enabled 2minerssolo on my server rig. It immediately got picked up by the profits switcher, but when I checked my client rigs they aren't picking it up. However, in 'All Pools' it is showing the hardware that is on my server PC.

![image](https://user-images.githubusercontent.com/42582444/142780223-f07c0c6b-42f7-4f2f-9b29-53e98c16b8e8.png)

This is the debug from my client rig.

[debug_2021-11-21.zip](https://github.com/RainbowMiner/RainbowMiner/files/7577203/debug_2021-11-21.zip)

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll check, what is going on.

**Comment by RainbowMiner** [comment]
Question: this AllPools screenshot, is this a screenshot on the client? Or is this the screenshot on the server?

**Comment by acos0874** [comment]
I believe this was an issue related to my network hardware. I recently changed all my network hardware and all the problems I was having seem to be solved.
