### ISSUE TITLE
2 SIN Coins : Blockmasters

### ISSUE THREAD

**Issue by sxb1n9** [RainbowMiner/RainbowMiner#1848]
Blockmasters has SIN (Sinovate) and the exchange rate for SIN (Sinovate) is being pulled up as Sin City Metaverse

https://www.coingecko.com/en/coins/sin-city
https://www.coingecko.com/en/coins/sinovate

i don't really know how to fix this issue however Sinovate is a few orders of magnitude less than Sin City causing the algorithm to mine Sinovate when it should not.  

Thanks,

**Comment by RainbowMiner** [comment]
Since this pool has x25x mining for three different coins, the only chance is to disable x25x for BlockMasters and switch to WTM prices for BlockMastersCoins. I'll add a fix.

**Comment by RainbowMiner** [comment]
Done.
