### ISSUE TITLE
SRBMinerMulti doesn't report hashrate properly

### ISSUE THREAD

**Issue by PapaChealio** [RainbowMiner/RainbowMiner#1849]
It appears that something has changed in the SRBMinerMulti miner configuration (API? hashrate reporting mechanism?).

If I clear all my existing SRBMinerMulti benchmarks (CPU only, for example) and re-bench them, the hashrate is constantly reported as 0, as do all the resulting benchmark stat files. The miner, however, appears to run fine and is hashing away at the pool; RBM just isn't reporting it.

I've tried this with 4.7.7.9 on both Windows and Linux and same issue.

**Comment by RainbowMiner** [comment]
Oh dear! It really looks like, they have changed their API. I'll adapt the miner module asap.

**Comment by RainbowMiner** [comment]
Ok, fixed.

**Comment by RainbowMiner** [comment]
Oh, this needed some more work here. But now it's working.

**Comment by PapaChealio** [comment]
Works now!
