### ISSUE TITLE
[Enhancement] Display Benchmarks that are 1 minute 

### ISSUE THREAD

**Issue by sxb1n9** [RainbowMiner/RainbowMiner#1852]
Display the 1 minute long benchmarks just like the ones that are over 1 minute.    

Also add column for miner version

Finally add column for OCprofile

I think this one should be rather easy hopefully thank you.

**Comment by RainbowMiner** [comment]
Ok, I have added an extra parameter "UIFullBenchmarkList" to config.txt:
- **UIFullBenchmarkList** set to "1" to show non-extended benchmarks in minerlist

**Comment by sxb1n9** [comment]
it is defaultly set to a variable should that variable be removed and it set to 1 or is that variable supposed to connect to a setting on the web site?

**Comment by RainbowMiner** [comment]
> it is defaultly set to a variable should that variable be removed and it set to 1

Exactly. That variable represents the default, which is 0.
```
  "UIFullBenchmarkList": "1",
```

**Comment by sxb1n9** [comment]
thank you i will close this issue now.
