### ISSUE TITLE
miners.config.txt is blanked upon server upgrade for server/client configuration

### ISSUE THREAD

**Issue by PapaChealio** [RainbowMiner/RainbowMiner#1853]
This has happened to me every time I try to upgrade the server computer (Linux) in both of my farm of CPU mining servers:

1. Stop RBM process.
2. Run `./updater.sh` which completes the upgrade to the new version successfully.
3. Run `sudo ./install.sh` which completes successfully.
4. Run `./start-screen.sh`

After RBM launches, it does a "cleanup" step post-upgrade, which appears to be where the previous `Config/miners.config.txt` file is replaced with a 3-byte file. I am then forced to exit RBM, manually restore the file with the most recent backup in the `Config/Backups` folder, then restart it. If I don't do this, the 3-byte file remains there and propagates to all the clients, messing up their mining config.

Let me know if you need any more info to debug this. I've had to disable auto-update because of this issue which makes upgrade very painful on a large farm of clients. This has happened since I started using RBM, so not something that started as part of a recent update.

**Comment by RainbowMiner** [comment]
It would be great, if you could upload a Debug file from that server. Is there anything special happening in the log files?

**Comment by RainbowMiner** [comment]
Thank you very much for reporting this! I could fix an ancient bug in the Cleanup script.

**Comment by PapaChealio** [comment]
Nice! I'll try it once you release the next official version; hopefully I can then re-enable auto updates.
