### ISSUE TITLE
Wallet Format Definition - Port to JSON?

### ISSUE THREAD

**Issue by rpringst** [RainbowMiner/RainbowMiner#1854]
https://github.com/RainbowMiner/RainbowMiner/blob/master/Balances/Wallet.ps1

Would it be possible to put on the 'nice to have list' the following?

- Define Wallet definitions, namely the Wallets_Data PSCustomObject, in a portable data structure, such as JSON.

**Comment by RainbowMiner** [comment]
Sure. No problem. Done!

**Comment by rpringst** [comment]
You are the best! Expect a couple pull requests for some fun altcoins in the coming days and weeks.
