### ISSUE TITLE
Is there a way to list all the miner 127.0.0.1 ports that are used?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1859]
Is there a way to list all the miner 127.0.0.1 ports that are used?

I am running a hard driver miner Scanvenger and Foxy-proxy and it uses 127.0.0.1:5000 and having issues.  I could just try a different port.

**Comment by RainbowMiner** [comment]
Here is a list: https://github.com/RainbowMiner/RainbowMiner/blob/master/Data/miner-ports.txt
Be aware, that this list contains all miners, that have been deprecated, too.

If you find a value of 123 then the corresponding miner will get the port 12300 + number of first GPU (or plus 0 in case of a CPU miner) assigned.
All ports are 5-digit. So you should be clear with port 5000

You can set `"EnableAutoMinerPorts": "1",` in config.txt - then RainbowMiner will check, if a port is already in use. If its blocked, it will automatically choose another free port: it will add +10 to the port number, until it finds a free port.

**Comment by paulpoco** [comment]
@RainbowMiner what about the ones that 127.0.0.1:port for web interface? 

Like Trex uses 31600.

**Comment by RainbowMiner** [comment]
I tried to make sure, that all miners use only one port - either API only, or webinterface including API. The Trex miners belongs to the second group (port 31600 is set by RainbowMiner).
If you stumble accross one rogue miner, please let me know.

**Comment by paulpoco** [comment]
I haven't found a rogue miner.
