### ISSUE TITLE
Add possiblity to benchmark updated miners via rbminer monitoring central

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#186]
Would it be possible to add rebench updated miners on the https://rbminer.net ? Or any other commands that are currently supported by the page genereted on localhost?

**Comment by RainbowMiner** [comment]
In principle - yes. A feedback path could be installed. At the moment I reduced all traffic to ensure total privacy and isolation of the mining rig. I will think about it :)

**Comment by Byrd1083** [comment]
Any ideas why I can't get rbminer to work? Says site can't be reached. I have rainbow running. I've made exception through firewall and unblocked all AVG tcp/udp ports. Should not be any other blocks. I've also disabled windows real time protection as well.

**Comment by hernandn01** [comment]
it appears that the monitoring site is down

**Comment by Byrd1083** [comment]
I also since last update, I now have a blank black window open with miner that shows no output. However, when I close Rainbow that blank window will say terminate batch job y/n?

**Comment by RainbowMiner** [comment]
Yes, that sounds pretty much like a very weird issue, related to powershell version mix.

**Comment by RainbowMiner** [comment]
> Would it be possible to add rebench updated miners on the https://rbminer.net ? Or any other commands that are currently supported by the page genereted on localhost?

Starting with v3.8.8.15 there are be feedback actions implemented. First action at rbminer.net is "Benchmark Updated Miners". This button will do nothing for older releases.

**Comment by hernandn01** [comment]
refreshed rbminer.net page after updating 3.8.8.15, clicked on new button Benchmark updated miners and Rainbowminer responded updating benchmark for Ethminer v0.16.1 
![image](https://user-images.githubusercontent.com/41829368/46573783-44e50e80-c957-11e8-9c00-b6de905d89ef.png)
