### ISSUE TITLE
Xmrig fails to Benchmark on Take2 Raptoreum

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1860]
@RainbowMiner  Xmrig fails to Benchmark on Take2 Raptoreum.

Here is the debug 
[debug_2021-11-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/7612179/debug_2021-11-27.zip)

And screenshots of start of Xmrig.
![Screenshot_20211127-093557_TeamViewer](https://user-images.githubusercontent.com/801414/143691605-186ddb99-d349-486c-a532-97ba27a0b942.jpg)
![Screenshot_20211127-093510_TeamViewer](https://user-images.githubusercontent.com/801414/143691612-b24dca4d-e688-4c8d-ac00-120da01686d0.jpg)

**Comment by RainbowMiner** [comment]
Yes, they have a bug in their code. I have already compiled a new code version with fixes. The next RainbowMiner release will be out soon.

**Comment by paulpoco** [comment]
I have the Take2 on a Ryzen 5 2600(6c/12t), working as free heat(if 40W extra counts per the Kasa/TPlink).  With CpuminerWyvern miner working fine.
