### ISSUE TITLE
Nvidia Profile Inspector Not Working

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1867]
![image](https://user-images.githubusercontent.com/42582444/144444499-bb7cdf66-2e41-43c1-a8e0-05483f11e75a.png)

I'm getting this error when trying to launch npi to enable p0state on a rig where I just installed a new card. I have tried to repair .net framework and have run a system file scan. Do you have any suggestions of how I can fix it?

**Comment by acos0874** [comment]
https://forums.guru3d.com/threads/problem-with-nvidia-inspector-2-3-0-2-only.428452/

I found a fix that worked.

**Comment by RainbowMiner** [comment]
Nice! Good finding!

For the books, that's the fix:
> Delete file AppData\Local\NVIDIA Profile Inspector\settings.xml
