### ISSUE TITLE
Xmrig worker name in wrong field

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1868]
Using [https://pool.minafacil.com/](https://pool.minafacil.com/) with Userpools.  I don't think it was always wrong

![image](https://user-images.githubusercontent.com/801414/144724324-20a794ec-effa-4591-aac6-05382561f4a6.png)

**Comment by RainbowMiner** [comment]
Could you please upload your userpools.config.txt? Maybe there is problem.

**Comment by paulpoco** [comment]
[userpools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/7654719/userpools.config.txt)

**Comment by RainbowMiner** [comment]
Try the following for "Pass". Maybe that helps. I'll double check the Xmrig config, just in case.
```
    "Pass":  "ID=$WorkerName,c=RTM",
```

**Comment by paulpoco** [comment]
They are an ok pool but have a really small limit for payout so sometimes you can get a 1.5 RTM payout every hour

**Comment by paulpoco** [comment]
That made it worse.
![image](https://user-images.githubusercontent.com/801414/144725466-65346d8a-5796-494d-ad4f-9d27c6c6735c.png)

**Comment by RainbowMiner** [comment]
Ok, that's even worse. I have checked the Xmrig miner module. In fact, there is currently no WorkerName set in the config files. I'll try to add it asap and check for the implications on other pools. For the password to this pool, I'ld rather stick to your original solution with `"Pass": "$WorkerName",` for now.

**Comment by paulpoco** [comment]
> Ok, that's even worse. I have checked the Xmrig miner module. In fact, there is currently no WorkerName set in the config files. I'll try to add it asap and check for the implications on other pools. For the password to this pool, I'ld rather stick to your original solution with `"Pass": "$WorkerName",` for now.

I put it back already

**Comment by RainbowMiner** [comment]
Now, that's unexpected: there is no workername parameter available for the Xmrig. So it seems, you will have to stick to the workername in the password field for now. I'll discuss that with the Xmrig developers. Maybe they see an easy way to add a workername parameter.

**Comment by paulpoco** [comment]
This  Minafacil pool has no fee, I get more here than Flockpool.

I have been trading my RTM(same with BHD) almost every 1 to 2 days for BTFGCake token that puts SIGNA to WSIGNA on Binance Smart Chain then sells that for BNB on PancakeSwap then half of that to Cake then add to Liquidity Pool then to a farm.  Then BTFGCake token holders get paid dividends in SIGNA.

RTM has been going down since the spike.

**Comment by paulpoco** [comment]
@RainbowMiner should you just add [https://pool.minafacil.com/](https://pool.minafacil.com/) ?

As you can see not healthy for 1 pool to have 77% of hash.
![image](https://user-images.githubusercontent.com/801414/144725758-6ee461ea-dde7-4a20-9f64-213952203d7f.png)

**Comment by RainbowMiner** [comment]
I am currently mining to the rplant.xyz. But Minafacil.com looks pretty promising.

> I have been trading my RTM(same with BHD) almost every 1 to 2 days for BTFGCake token that puts SIGNA to WSIGNA on Binance Smart Chain then sells that for BNB on PancakeSwap then half of that to Cake then add to Liquidity Pool then to a farm. Then BTFGCake token holders get paid dividends in SIGNA.

Nice move!

**Comment by RainbowMiner** [comment]
> Now, that's unexpected: there is no workername parameter available for the Xmrig.

Ah! Found it. Xmrig has the `--rig-id` parameter. I'll experiment with it to be sure, that there are not compatibility problems with some pools.

**Comment by paulpoco** [comment]
> I am currently mining to the rplant.xyz. But Minafacil.com looks pretty promising.
> 
> > I have been trading my RTM(same with BHD) almost every 1 to 2 days for BTFGCake token that puts SIGNA to WSIGNA on Binance Smart Chain then sells that for BNB on PancakeSwap then half of that to Cake then add to Liquidity Pool then to a farm. Then BTFGCake token holders get paid dividends in SIGNA.
> 
> Nice move!

I switched when YouTube Rabid Mining mentioned it.

At 1st I was getting 3.5 or so RTM per pool block find then Hash doubled but blocks more often now.
Oh not 5Mhs/s now 6/8Mh/s, that is why now every pool block my share is now 1.18 RTM.
![image](https://user-images.githubusercontent.com/801414/144725922-b5e06dff-6276-432d-84ab-dac793407be7.png)

**Comment by paulpoco** [comment]
It is a no nonsense no features pool.  The Telegram group are all Spanish.

**Comment by RainbowMiner** [comment]
Ok, that last commit should do the job.

**Comment by RainbowMiner** [comment]
Oh! I have been blind. It's even more simple: just add the `$WorkerName` (with a dot) to the User parameter inside your userpools.config.txt:
```
    "User":  "$Wallet.$WorkerName",
    "Pass":  "$WorkerName",
```

**Comment by RainbowMiner** [comment]
I will check the pool module, just to be sure.

**Comment by RainbowMiner** [comment]
Oh dear! Sorry for the inconvenience, I had some copy-and-paste error in the pool modules. It's fixed now, new release upcomeing.

**Comment by RainbowMiner** [comment]
Done :) It should work now. Sorry again.

**Comment by paulpoco** [comment]
Appears all good now.


![Screenshot_20211206-115312_Chrome](https://user-images.githubusercontent.com/801414/144913076-96cd62fe-0b4a-4205-920a-d6f342ad25ca.jpg)

**Comment by RainbowMiner** [comment]
That's good to hear!
