### ISSUE TITLE
Information Requested Unavailable on Current Platform

### ISSUE THREAD

**Issue by rpringst** [RainbowMiner/RainbowMiner#1869]
WARNING: Auto-Port failed for Xmrig-CPU#00: Exception calling "GetActiveTcpListeners" with "0" argument(s): "The information requested is unavailable on the current platform."

This error (warning) is being thrown on a new RBM deployment I am testing. Not sure if it is that big of any issue or not, any insights?

**Comment by RainbowMiner** [comment]
It might be relevant. Which is the operating system (and version) of that rig?
