### ISSUE TITLE
TeamBlack Miner

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#1870]
it instantly crashes on my system

https://i.imgur.com/FxjMiqo.png

**Comment by RainbowMiner** [comment]
That's maybe related to your GPU (or drivers). Which GPU are you using? And which Nvidia driver version is currently installed?

**Comment by szentigrad3** [comment]
RTX 3090 and 497.09

**Comment by RainbowMiner** [comment]
Try to clock down the GPU memory clock. It's often an overclocking issue with that specific miner
