### ISSUE TITLE
Encountered condition which should never be reached during OC configuration

### ISSUE THREAD

**Issue by Vivraan** [RainbowMiner/RainbowMiner#1877]
Encountered `Write-Log: Unknown setup command "enableocfullreset"enablelinuxheadless". You should never reach here. Please open an issue on github.com` while performing setup.

**Comment by RainbowMiner** [comment]
Oh! Thank you very much for reporting this. I will fix it asap.

**Comment by RainbowMiner** [comment]
I think, this has been already solved with commit 9eaa2ef86ff44095806fa7fbfb04dd5d762f0431 - try to update your RainbowMiner instance to the newest version.
