### ISSUE TITLE
Error while setting up schedule

### ISSUE THREAD

**Issue by Vivraan** [RainbowMiner/RainbowMiner#1878]
Version 4.7.7.7 and 4.7.8.9.

```autohotkey
Enable automatic updates? (if EnableUpdateWhenScheduled is set to 1 in config.txt) (yes/no) [default=no]: yes
Write-Log: Unknown goto command "Exception setting "EnableUpdate": "The property 'EnableUpdate' cannot be found on this object. Verify that the property exists and can be set."". You should never reach here. Please open
an issue on github.com
```
Keeps failing and loops back to `Enable automatic updates? (if EnableUpdateWhenScheduled is set to 1 in config.txt) (yes/no) [default=no]:`

**Comment by Vivraan** [comment]
When will this fix be available?

**Comment by RainbowMiner** [comment]
Perfect! Anyway, there is always an easy way to update in between releases: just download the current [developer master.zip](https://github.com/RainbowMiner/RainbowMiner/archive/master.zip) and unzip the contents into your RainbowMiner folder.
The link to the master.zip can be found on the main page https://github.com/RainbowMiner/RainbowMiner very much at the beginning of the Readme area.

**Comment by Vivraan** [comment]
> Perfect! Anyway, there is always an easy way to update in between releases: just download the current [developer master.zip](https://github.com/RainbowMiner/RainbowMiner/archive/master.zip) and unzip the contents into your RainbowMiner folder. The link to the master.zip can be found on the main page https://github.com/RainbowMiner/RainbowMiner very much at the beginning of the Readme area.

Nah I'd rather not do that. Better rely on the stable releases as much as I can.

Unless of course nothing breaks? 😉
