### ISSUE TITLE
All 6 miner downloads fail after RBMiner opens notepad with `7z.ps1` loaded 6 times.

### ISSUE THREAD

**Issue by Vivraan** [RainbowMiner/RainbowMiner#1879]
Even having them installed in the location doesn't stop the errors.

**Comment by RainbowMiner** [comment]
That's super weird, never had this happening before. It seems like Windows prefers ps1 over exe on your machine. I have posted a fix to avoid this rare condition.

**Comment by Vivraan** [comment]
> That's super weird, never had this happening before. It seems like Windows prefers ps1 over exe on your machine. I have posted a fix to avoid this rare condition.

Where can I get it – the releases page?
