### ISSUE TITLE
add Ethereum mining in Ethermine

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#188]
Is it possible to add mining Ethereum to Ethermine pool? For those days when profits go way down instead of mining Ethereum in Nicehash or Mining Pool Hub, I think it could be an alternative to mine direct to Ethereum and not autoexchange

**Comment by RainbowMiner** [comment]
Of course. I will add this.

**Comment by hernandn01** [comment]
thanks

**Comment by RainbowMiner** [comment]
Since Ethermine has a sub than optimal API, I started by adding NanoPool. Would this pool be ok for your purpose? Or should I add Ethermine, too?

**Comment by hernandn01** [comment]
that is great news about nanopool, I haven't use that though but I will try it. I have used Ethermine and yes, I have seen't a good way to put that pool in the mix. I you could do it, I would appreciated. Thanks again.

**Comment by RainbowMiner** [comment]
Pool & balance Ethermine has been added to release v3.8.8.9

**Comment by RainbowMiner** [comment]
PS: thank you for that issue. I was pretty much surprised as a lost-and-found balance showed up for me at Ethermine.org 💯

**Comment by hernandn01** [comment]
you are welcome, I am so glad that Rainbowminer is becoming like no other
