### ISSUE TITLE
[SUGGESTION] MRR SCHEDULES

### ISSUE THREAD

**Issue by sxb1n9** [RainbowMiner/RainbowMiner#1884]
Allow schedule of when MRR can be rented and it can be rented as long as the rental allows but no extensions if out of schedule.   No rentals when out of schedule.

**Comment by RainbowMiner** [comment]
Very good idea. Not easy to implement, but very useful. I'll give it a shot.

**Comment by acos0874** [comment]
Just a suggestion, but I often manually increase the profit factor to something very high when I don't want rigs to be rented. If they do get rented, it's worth the inconvenience for the extra pay. Maybe this could be added to the scheduler?

**Comment by RainbowMiner** [comment]
Ok, added with commit 53b45bed2f2c5b528a95313c26bf073a9bf21e90
- added two parameters to scheduler.config.txt:
  - "PauseRentals": if set to "1", all unrented rigs will be paused during this timespan
  - "MRRPriceFactor": set specific price factor for MiningRigRentals, during that timespan

**Comment by sxb1n9** [comment]
thank you kind sir.
