### ISSUE TITLE
Zergpool Change

### ISSUE THREAD

**Issue by gorgarp** [RainbowMiner/RainbowMiner#1887]
!pinpin [zergpool.com] — Yesterday at 4:09 AM
Ever wanted to get paid in low fee non-minable assets when mining at zergpool.com? Now it is possible, with new assets as part of guaranteed payouts, welcome Tron $TRX and $USDT TRC20 token.

Please add AE payout coins TRX and USDT for Zergpool per above announcement.

**Comment by RainbowMiner** [comment]
Nice! I will add them asap

**Comment by RainbowMiner** [comment]
Ok, done. Release will follow soon.

**Comment by gorgarp** [comment]
Oops, found an error. Coin for usdt  (c=) needs to be USDT-TRC20 not usdt (usdt will convert to eth)

**Comment by gorgarp** [comment]
or rather the usdt erc20 token

**Comment by RainbowMiner** [comment]
Thanks for reporting this! So ZergPool now allows for transfers on the Tron network, too. I will add a check on the wallet address and then switch to the correct token. 
It's luckily pretty easy to distinguish: 0x... for ERC and T... for TRC

**Comment by RainbowMiner** [comment]
Now all ZergPools check for the correct wallet address and switch the token accordingly (USDT for ERC20/0x... and USDT-TRC20 for TRC20/T...). If the address is wrong, you will get a warning.
