### ISSUE TITLE
Setting up custom miners 

### ISSUE THREAD

**Issue by Vivraan** [RainbowMiner/RainbowMiner#1890]
I'm really interested in installing Rainbow on one of my rigs which uses CPU to mine SUGAR using the YesPowerSugar algorithm. Can this be added to the mix?

**Comment by Vivraan** [comment]
Where can I find the answer?

**Comment by RainbowMiner** [comment]
The algorithm YespowerSUGAR is already in-the-mix. Four miners do support it: CpuminerRplant, CpuminerPower, CpuminerJayddee and SrbminerMulti. The following pools support it: BlockMasters, BlockMastersCoins, CpuPool, NLpool, RPlant, Zpool, ZpoolCoins

**Comment by RainbowMiner** [comment]
> Where can I find the answer?

Sorry, you read faster than I was typing :)

**Comment by Vivraan** [comment]
> The algorithm YespowerSUGAR is already in-the-mix. Four miners do support it: CpuminerRplant, CpuminerPower, CpuminerJayddee and SrbminerMulti. The following pools support it: BlockMasters, BlockMastersCoins, CpuPool, NLpool, RPlant, Zpool, ZpoolCoins
> 
> Here is a pool size comparison. Actually, I would recommend against using BlockMasters currently. My choice would be either CpuPool or RPlant https://miningpoolstats.stream/sugarchain

I plan to solo mine.

**Comment by RainbowMiner** [comment]
Ok, for that you will have to add a userpool pointing to your localhost qt-sugarwallet (set it up according https://forum.sugarchain.org/d/20-solo-mining-on-linux or https://forum.sugarchain.org/d/9-solo-mining-on-windows and choose some rpcuser and rpcpassword) and add some extra parameters to the miner's command-line. Do it in a six-step way.

1. start wallet and let it sync completely. That's important, otherwise, the mining will fail
2. edit userpools.config.txt and add your localhost (just edit one of the empty default records):
```
  {
    "Enable": "1",
    "Name": "QtSugarchain",
    "PoolFee": "0.0",
    "Algorithm": "YespowerSUGAR",
    "CoinName": "SUGAR",
    "CoinSymbol": "SUGAR",
    "Currency": "SUGAR",
    "Protocol": "stratum+tcp",
    "Host": "127.0.0.1",
    "Port": "34229",
    "User": "$Wallet",
    "Pass": "$Password",
    "Region": "EU",
    "SSL": "0",
    "Worker": "$WorkerName",
    "EthMode": ""
  },
```
3. add "QtSugarchain" to PoolName and "CpuminerJayddee" to MinerName in config.txt
4. let RainbowMiner run for one or two rounds until a record "QtSugarchain" has been created in pools.config.txt
5. now edit pools.config.txt and add your values for rpcuser and rpcpassword to the record:
```
  "QtSugarchain": {
    "SUGAR": "(your value for rpcuser)",
    "Password": "(your value for rpcpassword)",
...
```
6. add your SUGAR wallet address to miners.config.txt:
```
  "CpuminerJayddee-CPU": [
...
    {
      "MainAlgorithm": "YespowerSUGAR",
      "SecondaryAlgorithm": "",
      "Params": "--no-longpoll --coinbase-addr=(Your sugarchain address)",
      "MSIAprofile": "",
      "OCprofile": "",
      "Difficulty": "",
      "Penalty": "",
      "Disable": "0",
      "Affinity": "",
      "Threads": "",
      "ShareCheck": "",
      "Tuning": "0"
    },
...
  ],
```

You can later add more miners or pools, of course.

**Comment by RainbowMiner** [comment]
Is the sugar-maker miner faster than the cpuminer jayddee?

**Comment by Vivraan** [comment]
> Ok, for that you will have to add a userpool pointing to your localhost qt-sugarwallet (set it up according https://forum.sugarchain.org/d/20-solo-mining-on-linux or https://forum.sugarchain.org/d/9-solo-mining-on-windows and choose some rpcuser and rpcpassword) and add some extra parameters to the miner's command-line. Do it in a six-step way.
> 
> 1. start wallet and let it sync completely. That's important, otherwise, the mining will fail
> 2. edit userpools.config.txt and add your localhost (just edit one of the empty default records):
> 
> ```
>   {
>     "Enable": "1",
>     "Name": "QtSugarchain",
>     "PoolFee": "0.0",
>     "Algorithm": "YespowerSUGAR",
>     "CoinName": "SUGAR",
>     "CoinSymbol": "SUGAR",
>     "Currency": "SUGAR",
>     "Protocol": "stratum+tcp",
>     "Host": "127.0.0.1",
>     "Port": "34229",
>     "User": "$Wallet",
>     "Pass": "$Password",
>     "Region": "EU",
>     "SSL": "0",
>     "Worker": "$WorkerName",
>     "EthMode": ""
>   },
> ```
> 
> 3. add "QtSugarchain" to PoolName and "CpuminerJayddee" to MinerName in config.txt
> 4. let RainbowMiner run for one or two rounds until a record "QtSugarchain" has been created in pools.config.txt
> 5. now edit pools.config.txt and add your values for rpcuser and rpcpassword to the record:
> 
> ```
>   "QtSugarchain": {
>     "SUGAR": "(your value for rpcuser)",
>     "Password": "(your value for rpcpassword)",
> ...
> ```
> 
> 6. add your SUGAR wallet address to miners.config.txt:
> 
> ```
>   "CpuminerJayddee-CPU": [
> ...
>     {
>       "MainAlgorithm": "YespowerSUGAR",
>       "SecondaryAlgorithm": "",
>       "Params": "--no-longpoll --coinbase-addr=(Your sugarchain address)",
>       "MSIAprofile": "",
>       "OCprofile": "",
>       "Difficulty": "",
>       "Penalty": "",
>       "Disable": "0",
>       "Affinity": "",
>       "Threads": "",
>       "ShareCheck": "",
>       "Tuning": "0"
>     },
> ...
>   ],
> ```
> 
> You can later add more miners or pools, of course. I don't know, if the "--no-longpoll" parameter is really needed. If you run into trouble, just leave it out and try again.

I already use Sugarmaker (with `--no-longpoll`), so I'll start from the userpool setup.
Can the region param be something other than `EU`?

**Comment by Vivraan** [comment]
> Is the sugar-maker miner faster than the cpuminer jayddee?

That will be put to the test! JayDDee's miner is more recent and is actively developed so I am banking on this new contender.

**Comment by RainbowMiner** [comment]
> Can the region param be something other than EU?

Sure. Since there will be only one pool region for this userpool, it doesn't really matter.

**Comment by RainbowMiner** [comment]
In my experience, the CpuminerRplant and CpuminerPower are pretty fast, too. Both can be configured just like the CpuminerJayddee. So you can have more competitors.

**Comment by Vivraan** [comment]
CpuminerPower seems to be old and not actively maintained, and CpuminerRplant is closed source with 0 documentation. I'm really happy with open source miners and okay with closed source miners with well documented features and support.

**Comment by Vivraan** [comment]
Is it normal that I'm getting JSON decode errors? I imagine it could be because the wallet endpoint isn't connected.

**Comment by RainbowMiner** [comment]
> Is it normal that I'm getting JSON decode errors

No. Please check all edited config files using Https://jsonlint.com
... if you need help, please upload the changed config files here, and I will have a look.

**Comment by Vivraan** [comment]
[userpools.config.json](https://www.toptal.com/developers/hastebin/woxefibibu.json)
[pools.config.txt](https://www.toptal.com/developers/hastebin/akicezohot.json)
[miner.config.txt](https://www.toptal.com/developers/hastebin/zaqipepaxo.json)
[config.txt](https://www.toptal.com/developers/hastebin/upedosupek.json)

I still don't get why you're saving JSON files as .txt – isn't it just better to save them as .json? That way I won't need third party tools to lint JSON and just use VSCode or something.

**Comment by RainbowMiner** [comment]
> I still don't get why you're saving JSON files as .txt 

You are totally right - it's a relict from the past. That really needs a change. The reason was, that Windows users could open and edit the files more easy by a simple double-click. Notepad would open. In case of .json users would have to choose how to open the file.

**Comment by RainbowMiner** [comment]
Ok, the only thing I have found is this extra record in miners.config.txt:

```
  "CpuminerJayddee": [
    {
      "MainAlgorithm": "YespowerSUGAR",
      "SecondaryAlgorithm": "",
      "Params": "--no-longpoll --coinbase-addr=sugar1q62fmhvngj8m8fn9vu73h4dq45s85maseshuzlu",
      "MSIAprofile": "",
      "OCprofile": "",
      "ExtendInterval": 0,
      "FaultTolerance": 0.0,
      "Penalty": "",
      "Difficulty": "0",
      "Disable": "0",
      "Tuning": "0",
      "ShareCheck": ""
    }
  ],
```

This is the miners.config.txt file which has that block removed:
[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/7710030/miners.config.txt)

The root level indexes in miners.config.txt are always `"<Minername>-<Device>": [...`

**Comment by RainbowMiner** [comment]
> Is it normal that I'm getting JSON decode errors?

What is the exact error message?

**Comment by RainbowMiner** [comment]
There is a pretty simple way to edit those config files, in case RainbowMiner is running. Just use the http://localhost:4000 (or `http://<yourmachineip>:4000`) and choose the "JSON Editor" on the left hand side. It comes with a tree view and a simple syntax checker.

**Comment by Vivraan** [comment]
> There is a pretty simple way to edit those config files, in case RainbowMiner is running. Just use the http://localhost:4000 (or `http://<yourmachineip>:4000`) and choose the "JSON Editor" on the left hand side. It comes with a tree view and a simple syntax checker.

Cool!



> > Is it normal that I'm getting JSON decode errors?
> 
> What is the exact error message?

I can't replicate it anymore because the Watchdog has blocked it.

**Comment by RainbowMiner** [comment]
No problem - I will quickly setup a SUGAR node and try myself.

**Comment by RainbowMiner** [comment]
Ok, so my node is up and running and I have found the culprits:
- first, there has been a problem with the substitution of `$Password` - that simply wasn't implemented. So better put the password in cleartext into `userpools.config.txt` or download the updated `./Pools/Userpools.ps1` into your `./Pools` folder.
- second, the protocol has been wrong. For solo mining to a daemon, we need `http` instead of `stratum+tcp` in `userpools.config.txt`

```
  {
    "Enable": "1",
    "Name": "QtSugarchain",
    "PoolFee": "0.0",
    "Algorithm": "YespowerSUGAR",
    "CoinName": "SUGAR",
    "CoinSymbol": "SUGAR",
    "Currency": "SUGAR",
    "Protocol": "http",
    "Host": "127.0.0.1",
    "Port": "34229",
    "User": "$Wallet",
    "Pass": "(your rpcpassword here)",
    "Region": "EU",
    "SSL": "0",
    "Worker": "$WorkerName",
    "EthMode": ""
  },
```
- third, CpuminerRplant and CpuminerPower do not support solo mining via `http`. Only CpuminerJayddee is working.

**Comment by rpringst** [comment]
> No problem - I will quickly setup a SUGAR node and try myself.

You're awesome lol

**Comment by Vivraan** [comment]
> Ok, so my node is up and running and I have found the culprits:
> 
> * first, there has been a problem with the substitution of `$Password` - that simply wasn't implemented. So better put the password in cleartext into `userpools.config.txt` or download the updated `./Pools/Userpools.ps1` into your `./Pools` folder.
> * second, the protocol has been wrong. For solo mining to a daemon, we need `http` instead of `stratum+tcp` in `userpools.config.txt`
> 
> ```
>   {
>     "Enable": "1",
>     "Name": "QtSugarchain",
>     "PoolFee": "0.0",
>     "Algorithm": "YespowerSUGAR",
>     "CoinName": "SUGAR",
>     "CoinSymbol": "SUGAR",
>     "Currency": "SUGAR",
>     "Protocol": "http",
>     "Host": "127.0.0.1",
>     "Port": "34229",
>     "User": "$Wallet",
>     "Pass": "(your rpcpassword here)",
>     "Region": "EU",
>     "SSL": "0",
>     "Worker": "$WorkerName",
>     "EthMode": ""
>   },
> ```
> 
> * third, CpuminerRplant and CpuminerPower do not support solo mining via `http`. Only CpuminerJayddee is working.

Yep, the protocol makes perfect sense. Noob me. 😅
