### ISSUE TITLE
RainbowMiner 2.7.9.0 says "No GPUs found" for device with Nvidia GeForce 940M when running Install.bat

### ISSUE THREAD

**Issue by Vivraan** [RainbowMiner/RainbowMiner#1891]
Is the GPU too old for it to run anything, because of which the error is thrown?

EDIT: it does get detected in `Start.bat`.

**Comment by RainbowMiner** [comment]
I have fixed the Install.ps1

**Comment by Vivraan** [comment]
Will this GPU be enough for ETH mining?

**Comment by RainbowMiner** [comment]
As far as I remember, that GPU runs on 4GB memory. Try to enable zombie mode, then there is a chance, that the GPU mines Ethash for ETH.

**Comment by Vivraan** [comment]
Its architecture is older than Pascal, hence I asked.
