### ISSUE TITLE
Combo Mining Mode Not Working

### ISSUE THREAD

**Issue by rpringst** [RainbowMiner/RainbowMiner#1894]
I'm not sure when Combo mode stopped working, but on a most recent deployment of RainbowMiner, after setting mining mode to 'Combo', I would expect each 'permutation' of devices, in a 'group', to show on benchmarks/main console overview. This used to automatically work, but now it does not. Oddly, within miners.config.txt, each miner has a child data structure for the correct combo groupings, yet they are not being utilized. Let me know what logs/configs you need, if any. Thanks in advance, this is one of my favorite features.

**Comment by RainbowMiner** [comment]
Please have a look into file `.\Config\combos.config.txt` - there should be a list of combos for each vendor. Now check, which combos are activated (set to 1). The activated combos should appear after a restart of RainbowMiner. If it doesn't, please upload a Debug file for further investigation.

**Comment by rpringst** [comment]
[debug_2021-12-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/7721114/debug_2021-12-15.zip)

Activated combos are not appearing. The combo was even set as active before I restarted Rainbow, very odd.

**Comment by RainbowMiner** [comment]
I see - it's a miner, that cannot be downloaded hence RainbowMiner stays in a "benchmarking" state.
Please open `http://localhost:4000/downloadlist` and upload the result here.

**Comment by rpringst** [comment]
`[
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.04-teamblack/TeamBlackMiner_1_04_Ubuntu_18_04_Cuda_11_4.7z",
    "Path": "/RainbowMiner/Bin/GPU-VerthashSP/SPMiner",
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.0-verthash/verthash.dat",
    "Path": "/RainbowMiner/Bin/Common/verthash.dat",
    "IsMiner": false
  }
]`


I've noticed verhash.dat failing to download for a lot of rigs, SP is a new one though. Interesting. So, the downloads being stuck is hanging up a subsequent 'step' of the config generation procedure?

**Comment by RainbowMiner** [comment]
> So, the downloads being stuck is hanging up a subsequent 'step' of the config generation procedure?

Exactly. It seems, you are running a pretty old RainbowMiner release. Consider an update, please. I think to remember, that the Teamblack v1.04 had some severe bug, so that I have removed it from the repo.

**Comment by rpringst** [comment]
That is incorrect. I literally git cloned this repository last night, for the rig in question. I follow your install instructions verbatim - https://github.com/RainbowMiner/RainbowMiner#installation

**Comment by RainbowMiner** [comment]
> That is incorrect. I literally git cloned this repository last night, for the rig in question. I follow your install instructions verbatim -

That's interesting! Yes, I can see that in the log files, too. So why on earth would it download Teamblack v1.04?
- Could you please look into the folder `./MinersOldVersions` ? It should contain only one file, the `Ethminer17.ps1`
- Also, please open the `.\Miners\Teamblack.ps1` and check the $Version: 
```
using module ..\Modules\Include.psm1

param(
    [PSCustomObject]$Pools,
    [Bool]$InfoOnly
)

if (-not $IsWindows -and -not $IsLinux) {return}

$ManualURI = "https://github.com/sp-hash/TeamBlackMiner"
$Port = "365{0:d2}"
$Version = "1.32"
```

**Comment by RainbowMiner** [comment]
Oh! I think I have a vague idea of what is going on. Could you please reboot the machine and restart RainbowMiner after that? Then check the `http://localhost:4000/downloadlist`

**Comment by rpringst** [comment]
> > That is incorrect. I literally git cloned this repository last night, for the rig in question. I follow your install instructions verbatim -
> 
> That's interesting! Yes, I can see that in the log files, too. So why on earth would it download Teamblack v1.04?
> 
> * Could you please look into the folder `./MinersOldVersions` ? It should contain only one file, the `Ethminer17.ps1`
> * Also, please open the `.\Miners\Teamblack.ps1` and check the $Version:
> 
> ```
> using module ..\Modules\Include.psm1
> 
> param(
>     [PSCustomObject]$Pools,
>     [Bool]$InfoOnly
> )
> 
> if (-not $IsWindows -and -not $IsLinux) {return}
> 
> $ManualURI = "https://github.com/sp-hash/TeamBlackMiner"
> $Port = "365{0:d2}"
> $Version = "1.32"
> ```

Both of these looked fine, I'll reboot and restart Rainbow now.

**Comment by rpringst** [comment]
Still doing the same thing, and I checked network traffic to see if it was actually downloading - it is not.

**Comment by RainbowMiner** [comment]
Is it still trying to download TB v1.04?

**Comment by RainbowMiner** [comment]
Ohhh!! Found it. Sorry for that inconvenience! This is a bit embarrassing. I'll fix it asap.

**Comment by RainbowMiner** [comment]
Please download the new `.\Miners\VerthashSP.ps1` or just git clone it again. It should be fine, now.

**Comment by rpringst** [comment]
Yep, all good now! Thanks!
