### ISSUE TITLE
XMRIG CPU RTM miner error

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1897]
XMRIG CPU RTM miner error at begining when miner starts but it seems to be mining fine.
![Screenshot_5](https://user-images.githubusercontent.com/801414/146483747-4bb04c68-55b4-4ae0-82f9-cab8fcbbea25.png)
[debug_2021-12-16.zip](https://github.com/RainbowMiner/RainbowMiner/files/7731880/debug_2021-12-16.zip)

**Comment by RainbowMiner** [comment]
This warning can be ignored. It just warns, that this WinRing0_1_2_0 service lib is already in memory. But the outcome is the same: xmrig is able to set the register values for the CPU.
