### ISSUE TITLE
Allow DOGE payout for zpool

### ISSUE THREAD

**Issue by crackfoo** [RainbowMiner/RainbowMiner#1899]
Hi, 

While not seen on the pool, we do allow DOGE payouts however, RBM errors when trying to set it currently.

Can you allow DOGE to be set?

Thanks

**Comment by RainbowMiner** [comment]
Sure, thanks for reporting this.

**Comment by crackfoo** [comment]
Thanks. Actually, I'm not sure if this is possible. But we actually allow payouts in ALL our currencies aside from one that are not enabled for conversion. I've added a field in our currencies API that will indicate if the coin is able to be paid out:

`currencies API:
    "AXE": {
        "algo": "x11",
        "port": 3533,
        "name": "Axe",
        "height": 751170,
        "workers": 24,
        "shares": 0,
        "hashrate": 0,
        "estimate": "0.00012475",
        "mbtc_mh_factor": 1000000,
        "24h_blocks": 336,
        "24h_btc": 0.00020279,
        "lastblock": 751170,
        "timesincelast": 1183,
        "bitcointalk": "https:\/\/bitcointalk.org\/index.php?topic=2569112.0",
        "site": "https:\/\/axerunners.github.io\/",
        "twitter": "https:\/\/twitter.com\/axerunners",
        "discord": "https:\/\/discordapp.com\/invite\/BqhteaU",
        "source": "https:\/\/github.com\/AXErunners\/axe",
        "explorer": "",
        "image": "\/images\/coin-4979.png",
        "conversion_disabled": "1",
        "error": ""
    },
`

Note the conversion_disabled field. IN this case, AXE can not be paid to miners.

A bit more info is that we have a few guaranteed payout currencies BTC, LTC. DASH, DGB, KMD and RVN which we will always allow payouts with...

Thanks!

**Comment by RainbowMiner** [comment]
Ok, I'll use this field. Nice one!
