### ISSUE TITLE
Adding MPH balance (APIkey)

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#19]
Where do I add the MPH API key, I am missing the balance etc from that pool in the console printout

**Comment by RainbowMiner** [comment]
You will find the fields for API_ID and API_Key in your Config\config.txt

RBM

**Comment by ebojali** [comment]
It is currently reading in some variable:
  "API_ID": "$API_ID",
  "API_Key": "$API_Key",

Or do I missunderstand the functionality?

**Comment by RainbowMiner** [comment]
Simply replace the variables with your values, like that:

  "API_ID": "12345",
  "API_Key": "abcdef0123456789abcdef4abcdef0123456789abcdeffdc",

**Comment by RainbowMiner** [comment]
The API_ID is your USER ID at Miningpoolhub

**Comment by ebojali** [comment]
OK User ID, thanks now I get it! :) Perhaps a more suitable variable name is in place.
