### ISSUE TITLE
Activity Page Yiimp Pool shows infinity earns

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#190]
also Current Profit shows: NaN BTC/day in all pages and this was before the new activity page
![image](https://user-images.githubusercontent.com/41829368/46322606-18bc3d00-c5a7-11e8-91a4-986cd5efd85b.png)

Dashboard shows algo as one letter starting from new activity page was introduced. Decimals have not been fixed in Balances. Tested on Chrome, Explorer and Edge. On Explorer Dashboard shows as empty
![image](https://user-images.githubusercontent.com/41829368/46322658-6b95f480-c5a7-11e8-9c2b-0e9afb8f91f4.png)

**Comment by RainbowMiner** [comment]
Thank you. I will check this.

**Comment by RainbowMiner** [comment]
Ok, the missing decimals on Dashboard are fixed. Now I will go for the strange Infinity.

**Comment by RainbowMiner** [comment]
Would you be so kind and send me yesterdays activity log?
Logs\Activity_2018-10-01.txt
Thank you!

**Comment by hernandn01** [comment]
[Activity_2018-10-01.txt](https://github.com/RainbowMiner/RainbowMiner/files/2438586/Activity_2018-10-01.txt)

**Comment by hernandn01** [comment]
excellent, yes it was behaving weird the Yiimp pool. First it gave a message of corrupted stats, started to mine but only for one cycle at least before moving somewhere else.

**Comment by RainbowMiner** [comment]
It is a very weak pool. I consider disabling it. For now, I added more checks to avoid mining for zero results.
