### ISSUE TITLE
Hangs using newest version immediately after finishing downloads - cmdlet Remove-Job at command pipeline position 1

### ISSUE THREAD

**Issue by rpringst** [RainbowMiner/RainbowMiner#1902]
![image](https://user-images.githubusercontent.com/20052754/146971896-a00851b2-9e58-4f30-b95d-8b8e456ebd7e.png)

Just did a fresh git clone of the repo approximately 15 minutes ago, and this is the result. Probably a simple typo in a recent commit?

**Comment by rpringst** [comment]
I believe this contains the issue, but not quite sure... - https://github.com/RainbowMiner/RainbowMiner/commit/251c635c390aad32710136f963d106cc3050bd66#diff-84686b359a4422fcb4f90e876b819a55820071cf56b0d7df2730cf3bd76e6bb9

**Comment by RainbowMiner** [comment]
Woa! That's a bad one. Yes, I forgot on `$_`.
