### ISSUE TITLE
ScryptN2 / XBTX crashing on all CPU miners (with fix: it was the RBM recommended virtual memory settings)

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1905]
I installed RBM on a rig with an i9-9900K, 16 GB of RAM and a single 8GB 2080 card.  I followed the RBM recommendation to set a fixed virtual memory size of total GPU memory x 1.1 = 8800 MB, rather than allowing Windows to manage virtual memory.  The virtual memory is on an Intel 660P M.2 SSD.

I found that all three available ScryptN2 CPU miners would promptly crash, even after attempting to rebenchmark them following a fresh reboot.  This was particularly annoying because it is one of the most profitable CPU algos (Bitcoin Subsidium, XBTX) for this CPU right now.

I suspected it might be related to virtual memory size (my Windows-managed size had been around 13000 MB), so I doubled the fixed size to 17600 MB.  Sure enough, all three CPU miners now ran smoothly on ScryptN2 and the rig frequently mines XBTX on the CPU as the most profitable coin.  I noted that RBM doesn’t issue a warning on startup about the doubled fixed size, as it does with Windows-managed virtual memory.   I guess it cares more that the virtual memory size is fixed, rather than what fixed size it is.

So, I think this issue is fixed for me, but I am posting this here with hopefully appropriate keywords in case it can help someone else with the same issue.  Or in case RBM thinks it should reconsider its virtual memory recommendations.  Or in case I inadvertently caused other issues by doubling my fixed virtual memory size from the RBM recommendation, in which case, please let me know.

If this is the wrong place to post this, please move it and/or let me know.

**Comment by RainbowMiner** [comment]
Super! Thanks a lot. I'll improve the startup test.

**Comment by coolbreeze21** [comment]
Wow!  Two posts without a stupid newbie mistake yet.  My luck can't hold out too much longer...

I hope you get your money's worth mining dev fee on my other rig, which is a 3090 / 5950X!
