### ISSUE TITLE
Avian (AVN) price is wrong?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1907]
Avian (AVN) price is wrong?  I think the BTC value is wrong.  I think TradeOgre is showing 3 to 4 Sats.
![image](https://user-images.githubusercontent.com/801414/147391897-4e357d0b-d6df-4b68-ad67-1d59fd5ed324.png)

Here is a screenshot of a price chart.
![image](https://user-images.githubusercontent.com/801414/147391924-45a32f88-c672-4978-94ee-be872042dd9c.png)

**Comment by paulpoco** [comment]
I think AVNRich token price is being used in error.
![image](https://user-images.githubusercontent.com/801414/147391975-ac92c0d9-1f90-4821-95a0-69e22a7c00bd.png)

**Comment by RainbowMiner** [comment]
That is very likely. I will check the online currency engine.

**Comment by RainbowMiner** [comment]
Ok, I have added the TradeOgre to the online currency engine and manually excluded all non-Avian AVN tokens and coins. The new price should arrive on your rigs in some minutes.

**Comment by paulpoco** [comment]
It is correct now
