### ISSUE TITLE
XMR Miner gives the below error in the latest release not just when it loads but every time it starts to mine (PSv7.2.1)

### ISSUE THREAD

**Issue by KovZoli** [RainbowMiner/RainbowMiner#1908]
.. loading Minexmr RuntimeException: C:\Users\%username%\Desktop\RainbowMiner\Pools\Minexmr.ps1:76
Line |
  76 |      $profitLive   = 86400/$diffLive * $reward/$coinUnits
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Attempted to divide by zero.

done (0.225s)

**Comment by RainbowMiner** [comment]
I'll check the pool module.

**Comment by RainbowMiner** [comment]
Thank you for reporting this: since the pool has updated it's API, our pool module needed some work. It's done.
