### ISSUE TITLE
Missing Current Profit in Dashboard

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#191]
Fixed decimals in Balances. Current Profit is showing as NaN BTC/Day. Algo in Dashboard is showing only the first letter and another letter is showing as second algo although there should be none at the time that is mining Lyra2z.

![image](https://user-images.githubusercontent.com/41829368/46384651-7a96a880-c674-11e8-9b28-3883374a3a35.png)

**Comment by RainbowMiner** [comment]
Oh! I have got an idea. I think, I asked the wrong question. I should have asked: which Browser are you using? Chrome, Firefox, Edge or Internet Explorer?

**Comment by hernandn01** [comment]
I do not have Firefox, Chrome and Edge shows one letter in algo, Explorer does not show records on the table, current profit is showing as null on API

Chrome
![image](https://user-images.githubusercontent.com/41829368/46394542-b0ed1b80-c6a6-11e8-8f48-e10ada2486e3.png)

Explorer (no records ...!)
![image](https://user-images.githubusercontent.com/41829368/46394610-d843e880-c6a6-11e8-8178-f3f9349a827c.png)

Edge
![image](https://user-images.githubusercontent.com/41829368/46394654-f6a9e400-c6a6-11e8-80fc-afb2cc4aa97b.png)

Current Profit
![image](https://user-images.githubusercontent.com/41829368/46394749-47214180-c6a7-11e8-8dca-cd5beb5f6cc0.png)

**Comment by RainbowMiner** [comment]
Yes, I found this. Needed brackets around some json decoding in API.psm1 - what is left, ist the strange thing, with the letters.

**Comment by RainbowMiner** [comment]
Second one is fixed, too :)
