### ISSUE TITLE
WARNING: No miners available: Downloading miners, please be patient

### ISSUE THREAD

**Issue by henres** [RainbowMiner/RainbowMiner#1912]
Hello everyone,

I just install: `v4.7.9.7`

I'm stuck at 
```
WARNING: No miners available: Downloading miners, please be patient
 
 
WARNING: Download in progress: 1 miner left. Command windows might popup during extraction.
WARNING: Download in progress: 1 mining pre-requisite left.
```

The process send a lot of run.

Can you help me please.

Thanks in advance

**Comment by RainbowMiner** [comment]
Could you please open `http://localhost:4000/downloadlist` in your web browser and upload the result?

**Comment by henres** [comment]
Here the result :
```json
[
    {
        URI: "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.35-teamblack/TeamBlackMiner_1_35_Ubuntu_18_04_Cuda_11_5.tar.gz",
        Path: "/home/henres/project/mining/RainbowMiner/Bin/GPU-Teamblack/TBMiner",
        IsMiner: true
    },
    {
        URI: "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.0-verthash/verthash.dat",
        Path: "/home/henres/project/mining/RainbowMiner/Bin/Common/verthash.dat",
        IsMiner: false
    }
]
```

**Comment by RainbowMiner** [comment]
The Teamblack miner people have unintentionally zipped a whole path into their archives. I have just repacked everything and uploaded a new Teamblack.ps1 miner module.
Please download the [Teamblack.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Miners/Teamblack.ps1) directly into your `./Miners` folder to fix this problem (or git clone again).

**Comment by RainbowMiner** [comment]
.. you might have to restart RainbowMiner, after you have updated that Teamblack.ps1 module.
