### ISSUE TITLE
CcminerKlausT wild results

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1917]
RBM has launched CcminerKlausT a few times here in the last week.  It has never lasted for more than a few minutes and the results always seemed pretty improbable.  But this was a new record:

![CcminerKlausT](https://user-images.githubusercontent.com/96564929/147696491-9866cdcc-7aba-4859-9b94-a0122db102bc.jpg)

KlausT announced he was abandoning development of CcminerKlausT on 7/8/2021.   Perhaps it is time to move it to RBM’s miner graveyard.   It doesn’t seem worth trying to figure out what is going on with the RBM integration with an abandoned miner.  But at least one can dream about making $44 million a day in BTC…

**Comment by RainbowMiner** [comment]
Man, you must be like super-rich now! The CcminerKlausT works fine, it's most likely a problem with the MiningPoolHubCoins API and SHA256. I'll fix this asap.

**Comment by DCreason** [comment]
Having the same issue 
![image](https://user-images.githubusercontent.com/11247559/147779596-038b0ae8-e087-4afb-89dc-a2f54cb2f1bf.png)

Let me know if you'd like a debug log dump

**Comment by Nickfost** [comment]
I have three gripes

1. im offended that you'd call BCH bitcoin, this is a crime. 
2. where's my money? lol
3. MPH says "bad, stop it" and gives me 0 rev from this operation

**Comment by Nickfost** [comment]
Supporting info 
![image](https://user-images.githubusercontent.com/1572453/147789096-aa103577-f89b-4219-a166-3c059138124a.png)

**Comment by Nickfost** [comment]
Supporting info: 
![image](https://user-images.githubusercontent.com/1572453/147789133-2cbe7016-da6d-463e-ad7b-a5cc46c3bea9.png)

**Comment by Nickfost** [comment]
Supporting info: 
![image](https://user-images.githubusercontent.com/1572453/147789235-1abf6360-cb6a-4bca-bfa6-deab9f6a314b.png)

**Comment by Nickfost** [comment]
today's solution @DCreason "ExcludeAlgorithm": "sha256",

**Comment by RainbowMiner** [comment]
Yes, MPH seems to have added the sha256 algorithm to their API, for whatever reason. Never showed up there, in the past. I have put the SHA256 algorithm on the global unprofitable-things list. Every Rainbowminer instance will pick this up pretty soon, then that problem is fixed.
