### ISSUE TITLE
Raptoreum RTM on MoneroOcean doesn’t seem to be working, including for dev fee

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1918]
Raptoreum (RTM) works fine here on a couple of rigs with Flockpool.  But I noticed that the dev was trying to mine devfee with RTM on MoneroOcean and it appeared to fail with both CpuminerWyvern and XMRig.

I tried it myself by forcing MO as the only available RTM pool and it failed to mine anything, returning errors like “Stratum answer ID is not correct” and “Unauthenticated, code: -1”.

It seems a shame to see the wasted dev fee and I might like to use MO for RTM myself at some point. So, I hope you can address this.

**Comment by RainbowMiner** [comment]
It looks like ghostrider uses stratum over rpc2 at Moneroocean. That's pretty uncommon and in fact none of our miners support this. I'll disable ghostrider on Moneroocean for now.

**Comment by coolbreeze21** [comment]
One would think that Moneroocean's customized version of XMRig supports it, if you want to try to get it working, rather than disabling it.  It is at https://github.com/MoneroOcean/xmrig/releases

**Comment by RainbowMiner** [comment]
In fact there are fixes in their cloned xmrig repos, regarding the RTM. I'll add this miner for RTM.

**Comment by RainbowMiner** [comment]
Our version of Xmrig now comes with two binaries - first the classic, second the MoneroOcean fork. The Xmrig module automatically uses the correct one, while sharing the hashrate stats.
