### ISSUE TITLE
ZpoolCoins HashTap takes over mining with $1000/Day returns

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1919]
Enabling ZpoolCoins in RBM appears to also enable their on-demand mining rig rental service called HashTap™.  Now I like the idea of making my rigs available for rental on demand, and HashTap requires no setup, unlike the elaborate setup for MRR.  But HashTap periodically blows every other algo out of the water in RBM with RBM profitability numbers in the $800-3000/Day range.  It usually mines successfully for 5-10 minutes and then drops the profitability, thus releasing control to the baseline algo that the rig wanted to do otherwise.

Also, switching back from HashTap always seems to result in the following RBM warning: “WARNING: Stat file (Profit-CPU#00) is corrupt and will be reset.”

Is this expected behavior, or is something off in the RBM profitability calculations with ZpoolCoins and HashTap?  My ZpoolCoins balance does grow appreciably when this happens, but there is considerably more switching when it is enabled.

**Comment by RainbowMiner** [comment]
I suspect the zpool API supplies us with over-the-top numbers in some cases. I'll try to find it out and eventually adapt the peak filters.

**Comment by RainbowMiner** [comment]
It turns out, that Zpool sends HashTap data over it's coins API every 5 minutes. I have now disabled the HashTap data, so that ZpoolCoins works as intended.
