### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#192]
I keep getting this once and a while on the script screen "WARNING: Miner Status httpsrbminernet has failed."
I unfortunately still do not see my devices in the monitor site.. :(

**Comment by RainbowMiner** [comment]
Still! Now that is strange. Please send me the current Logs\Rainbowminer_2018-10-03.txt, the newest Logs\Rainbowminer_2018-10-dd_hh-mm-ss.txt and the Conifg\config.txt and I will recheck, what is wrong and see, what data is arriving at the rbminer server. Have you entered the MinerStatus values, using the Configuration, or did you directly edit the config.txt?

We will get this right :)

**Comment by RainbowMiner** [comment]
Ok, you do not need to sand data. I found the problem, since you gave the clou, already with the WARNING. There is a not intended removal of non letters and numbers at the input of the Configuration. I will fix this asap. Thank you for your patience!

**Comment by RainbowMiner** [comment]
Good. It is fixed. I also added a check and correct function to the cleanup. That means, if you update to v3.8.8.8 both values, MinerStatusUrl and MinerStatusKey will be corrected automatically.

**Comment by Yamanipanuchi** [comment]
Ok, Yes. One of my remote PC's started reporting. Awesome! Thanks!
