### ISSUE TITLE
All Pools - "On/Off" switch not working

### ISSUE THREAD

**Issue by bgianninoto** [RainbowMiner/RainbowMiner#1920]
Hello! Under "All Pools", there is an On/Off switch for each pool. I would assume this is to enable or disable the active status of the pool for each algorithm. It does not appear to be working. After switching a few pools to "Off", they revert back to On after the next screen refresh.

**Comment by RainbowMiner** [comment]
Ok, I'll have a look.

**Comment by bgianninoto** [comment]
> Ok, I'll have a look.

Thanks! Let me know if you need any more info. New user here, so I'm still feeling my way around.

**Comment by bgianninoto** [comment]
I think I figured this out. I was trying to switch off other regions (Asia, EU), and by doing so, I believe it was double posting to the server which was causing the abnormal behavior I observed. If I toggle a single switch for a single pool/algorithm combo, it works as expected.

**Comment by RainbowMiner** [comment]
Ah, yes, you are pretty right about that. It's a pool/algorithm combo toggle switch.
