### ISSUE TITLE
memory leakage? get pushover notices ever so often

### ISSUE THREAD

**Issue by gurkburk76** [RainbowMiner/RainbowMiner#1923]
So a while ago after updating versions (i think this was about 1,5 months age) i started to notice that after some uptime (2-3 days i think) i started to get about 10-15 pushover notices per day about the rig being offline, upon further investigation this turned out not to be true but turned out that the rigg was using like 99,99999% of the memory, i had then 4gigs of memory.
I decided to upgrade to 12gigs just to rule out that some of the miners might have become a little more memory hungry, no big deal cost-wise.

So i installed the memory and upgraded to the latest version about 2 weeks ago.
I've noticed the same behavior and it seems to take about 5-6 days after a restart before it hogs all of the mem and does this.
Now, afaik i haven't touched anything else besides updating RMB like stated above, this looks like some kind of memory leakage somewhere, would you like to see my logs?
I hope this issue can be tracked down with the help of those.

**Comment by RainbowMiner** [comment]
Which version of RainbowMiner are you running, currently?

**Comment by gurkburk76** [comment]
Well since i'm at 4.7.8.6 i'll upgrade to the latest and let it run, if i'm still experiencing problems after ~1 week like i stated above i'll pull out the logs and post.
