### ISSUE TITLE
add ability to force mine a coin regardless of profitability

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#193]
Could be like the penalty setting for a pool but to a coin to force mine it, more like a handicap. It could be combine to a specific pool. When you need to complete the balance require for Sunday payout for a given coin/pool.

**Comment by RainbowMiner** [comment]
Very well. I will include this.

**Comment by RainbowMiner** [comment]
Done with release v3.8.8.10 - very nice feature :) To force mining to a pool's wallet, just enter the wallet's coin symbols into pools.config.txt, field FocusWallet, or use the Configuration->Pools. The forced running miner will be marked with an exclamation mark.
![image](https://user-images.githubusercontent.com/39437538/46469559-13900580-c7d4-11e8-881f-d1d3de2e9847.png)

**Comment by hernandn01** [comment]
I think there is an error on reading the fields for pool configuration.

this is the starting config
![image](https://user-images.githubusercontent.com/41829368/46472249-d444c300-c799-11e8-8e9b-85f6628eb1f0.png)

the coins to mine are read as coins to exclude instead, loops into list not valid
![image](https://user-images.githubusercontent.com/41829368/46472524-b592fc00-c79a-11e8-81d8-03d70588995d.png)

**Comment by RainbowMiner** [comment]
Now, that's surprising! Ok, I will have a look.

**Comment by RainbowMiner** [comment]
I think, you selected the wrong pool name "ZergPool". Try to select "ZergPoolCoins" - then your configuration should be reflected correctly.

**Comment by hernandn01** [comment]
working after adding coin in FocusWindow and disabling check profitability. Very nice, still pending to check the pools setup on config
![image](https://user-images.githubusercontent.com/41829368/46474115-48359a00-c79f-11e8-91b3-0665eda01b4d.png)

**Comment by RainbowMiner** [comment]
Eventually I could add a config.txt flag, something like "CheckProfitabilityFocusWallet", that would override the "CheckProfitability", if a "FocusWallet" has been set. What do you think? Or does this make things to complicated?

**Comment by hernandn01** [comment]
would you please check that profitability is not check regardless of setting while FocusWindow is set. I am only mining on two card and not all 4, Although check profitability is off still miners are not profitable and not being used.

![image](https://user-images.githubusercontent.com/41829368/46474548-6b147e00-c7a0-11e8-8b9a-e397d877e869.png)

also Excavator was selected but Cryptodreged has better benchmark
![image](https://user-images.githubusercontent.com/41829368/46474653-a9aa3880-c7a0-11e8-9958-8506a1b18f07.png)

**Comment by RainbowMiner** [comment]
Which currency have you set as FocusWindow?

**Comment by hernandn01** [comment]
I think a third variable like CheckProfitabilityFocusWallet is unnecessary, if you are going for a certain coin I think a warning that that coin is not profitably should be enough. TRAID coin was set on FocusWindow. I tried to edit in config first ZergPool but I got the message of No wallets configured. Is it because only BTC wallet is configured?

"ZergPoolCoins": {
    "Worker": "$WorkerName",
    "Penalty": 0.0,
    "User": "$UserName",
    "API_ID": "$API_ID",
    "API_Key": "$API_Key",
    "SONO": "SbKvEnb2Hkx9RPLXvfydkmQpfugpHn5MrX",
    "LUX": "LckJRPcXkod3sXWU9yj18RCGCZppkZZmhf",
    "STAK": "SeJXLDQmEuneCuQLSBuhnuFwxvsMmqEctC",
    "REDN": "R9ezpAPYzECcrMXoBWdUHUP91mY5DY4ifB",
    "ORE": "GcXyq9SrWrE7KrJMyy6R6FZAihc5XbNhGG",
    "KREDS": "K8NjM7Hj1uhi8kdf5uUdAwCbavnZi1EEVD",
    "XDNA": "XCj8tZ1DenhR34xiudHKNHzsA5wfaqCCWY",
    "TRAID": "Tav8RdyWrA4uQ1cD545bNgbH5HGvt24CpJ",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "TRAID,XDNA,KREDS,ORE,REDN,STAK,LUX,SONO",
    "ExcludeCoinSymbol": "BCD",
    "FocusWallet": "TRAID"
  },

**Comment by RainbowMiner** [comment]
> ZergPool but I got the message of No wallets configured. Is it because only BTC wallet is configured?

.. you will have to edit pool name "ZergPoolCoins". It differs from "ZergPool"

**Comment by hernandn01** [comment]
yes, I did select first ZergPool but then ZergPoolCoins, have a close look at the first paste

**Comment by RainbowMiner** [comment]
I think you edited the right thing in conig.txt, but selected the wrong pool in [C]onfiguration->[P]ools. Your screenshot says "ZergPool".

**Comment by RainbowMiner** [comment]
> ZergPool but I got the message of No wallets configured.

This is a bug. I will check this. It should display BTC

**Comment by hernandn01** [comment]
here is the paste again, I selected first ZergPool, no wallets configured, and yes I only have BTC there, so at least BTC should display. then I select ZergPoolCoins but got into the ExcludedCoins showing my actual included coins, and then a loop that I had to ctrl + c to get out of there, never got to FocusWindow on setup config.

I just checked my miner window and I am back to regular mining but FocusWallet is still set.

![image](https://user-images.githubusercontent.com/41829368/46475792-bbd9a600-c7a3-11e8-924f-684b2e16ab0b.png)

**Comment by RainbowMiner** [comment]
Ah, now I see. You entered ZergPoolCoins into field "Enter the worker name..", so you ended up editing ZergPool, with changing "Worker" to ZergPoolCoins. The "No wallets" bug is fixed. I will push a new release soon.

**Comment by hernandn01** [comment]
got it too, yes, that is my correct excluded coin on ZergPool. once I realized I did not want to edit ZergPool, I read "leave empty to end wallet configuration" which I did but was expecting to leave pool edit for ZergPool. I guess I had to enter Exit to leave?

Still would you check, I still have FocusWallet set but it is regular mining right now. Thanks

**Comment by hernandn01** [comment]
checked back again, only CPU mining at the moment, and also check to use the miner with the better benchmark

**Comment by RainbowMiner** [comment]
> Still would you check, I still have FocusWallet set but it is regular mining right now. Thanks

Ok - I will check.

**Comment by RainbowMiner** [comment]
Could you send me your Logs\Rainbowminer_2018-10-04.txt, please? That would help.

**Comment by hernandn01** [comment]
so is this a precondition, I guess the API's failing so no mining on that pool?
![image](https://user-images.githubusercontent.com/41829368/46477237-76b77300-c7a7-11e8-9a7d-591b01db3506.png)

**Comment by RainbowMiner** [comment]
Yes, very probably, the API must have been active at least for one time after a new start of RainbowMiner.

**Comment by hernandn01** [comment]
all API coins have been not very reliable, could the check be against the main pool then?

**Comment by RainbowMiner** [comment]
Unfortunatly not - I need the currencies data from the API.
I will implement a fallback - if a pool has FocusWindow set and is failing, the FocusWindow will be ignored.

**Comment by hernandn01** [comment]
yes, that would be great and if API is available again than continue if FocusWallet is still set

**Comment by RainbowMiner** [comment]
Implemented. The problem is not only the API, but the hashrate reported by the pool: actually it reports "hashrate":0 for TRAID and is thus ignored by RainbowMiner.

**Comment by hernandn01** [comment]
oh yes, that too. At times I am the only one mining TRAID or REDEN for example.

**Comment by RainbowMiner** [comment]
Ok, I pushed a new release, including that fallback. Eventually, it would make sense to allow 0 hashrate, if the FocusWallet is set for a pool. What do you think?

**Comment by hernandn01** [comment]
I am testing now, yes that could make sense but there are times like yesterday that Sonoa wallet was not updated on ZergPool and all hashes were rejected so they decided to take it out, so that effectively means 0 hashrate and if we force we would be wasting hashpower. That is the extreme case but also possible.

**Comment by hernandn01** [comment]
under 3.8.8.11 it is not mining on the 1050tis, I have no other indication as to why not
![image](https://user-images.githubusercontent.com/41829368/46480158-e4669d80-c7ad-11e8-8c10-760e16d90ce9.png)

**Comment by RainbowMiner** [comment]
Strange. I will find out. Are they still active in the localhost:4000 Devices section?

**Comment by hernandn01** [comment]
yes devices stayed the same with or without FocusWallet. I could not setup FocusWallet on Setup I suppose ZergPoolCoins still is failing, although I do not see a message in the warnings. But once I setup FocusWallet in config,txt it stops mining on the 1050tis

![image](https://user-images.githubusercontent.com/41829368/46481457-acad2500-c7b0-11e8-9e78-77751f169176.png)

**Comment by RainbowMiner** [comment]
Ok, I might have found a reason.

**Comment by hernandn01** [comment]
also is it really failing ZergPoolCoins? I am able to query in browser http://api.zergpool.com:8080/api/currencies

**Comment by RainbowMiner** [comment]
No. I found another problem with the setup query - Zergpool has changed some cross references in currencies. I am investigating.

**Comment by RainbowMiner** [comment]
Now the 1050ti s should work.

**Comment by hernandn01** [comment]
Fixed Setup
![image](https://user-images.githubusercontent.com/41829368/46485220-7ecbde80-c7b8-11e8-9cd8-31f4e52d42f3.png)

Fix used better miner
![image](https://user-images.githubusercontent.com/41829368/46485279-999e5300-c7b8-11e8-9806-21a9d2845e97.png)

not fix used all devices, it is using only one, now the 1060 3GB
![image](https://user-images.githubusercontent.com/41829368/46485306-aae75f80-c7b8-11e8-97dc-c9ab19b18926.png)

**Comment by RainbowMiner** [comment]
:9 ok. Looks like a difficult one. I will get it.

**Comment by RainbowMiner** [comment]
It is a hard one. Please do not be surprised, if you find same TRAIDS in your wallet. I am testing your configuration with one of my rigs (unfortunatly I have only unique GPU rigs)

**Comment by RainbowMiner** [comment]
Ok, I think I found the problem. It was deeply buried in the main function. Since I do not have a multi GPU rig - would you be daring and try the new version? That would be superb! I am interested, if it works seemless with and without a FocusWallet, or if any problems pop up.
Just exit Rainbowminer and unzip the contents of this file into your RainbowMiner directory:
[Updatepatch3.8.8.13.zip](https://github.com/RainbowMiner/RainbowMiner/files/2448558/Updatepatch3.8.8.13.zip)

If anything goes wrong, I prepared a reverse patch, just in case :)
[ReversePatch3.8.8.13to3.8.8.12.zip](https://github.com/RainbowMiner/RainbowMiner/files/2448562/ReversePatch3.8.8.13to3.8.8.12.zip)

**Comment by hernandn01** [comment]
Setup tested - ok
![image](https://user-images.githubusercontent.com/41829368/46511675-2410a200-c80d-11e8-8601-416d1cce11fd.png)

All 3 devices tested - ok
![image](https://user-images.githubusercontent.com/41829368/46511697-4f938c80-c80d-11e8-8c14-dda9f8b907e1.png)

I am getting some rejects, I suppose is difficulty. Is there any where were a vardiff could be accounted?

![image](https://user-images.githubusercontent.com/41829368/46511766-b5801400-c80d-11e8-89de-801539dec285.png)

**Comment by hernandn01** [comment]
Very well. It is working as intended. Thanks. One question before closing this, maybe opening this question in a new issue.

Right now it is favoring excavator for the 1050 tis and the 1060 6b in one instance plus an instance of cryptodregde for the 1060 3gb (althought the last one comes as a negative profit it overalls the sum total, which is fine) 

![image](https://user-images.githubusercontent.com/41829368/46512180-ca5da700-c80f-11e8-9e16-8ffb6fe2b262.png)

In the miners section filtered by Neoscrypt , in all 3 devices it shows as a higher profit Cryptodredge but is only being used on the 1060 3gb. here is the question: is the profit column the last value to considered to select miners or after that number the cost of the power is factored in? Profit column should indicate the last calculated value, than the CD should be favor instead of the excavator. 

![image](https://user-images.githubusercontent.com/41829368/46512136-98e4db80-c80f-11e8-890b-d3564382b34b.png)

**Comment by hernandn01** [comment]
I am getting a different value on the profit in the script than the Dashboard and the Monitoring page. The last two are the same
![image](https://user-images.githubusercontent.com/41829368/46512963-9e442500-c813-11e8-97ae-25990d4d977d.png)

![image](https://user-images.githubusercontent.com/41829368/46512979-adc36e00-c813-11e8-88c3-19e38b9b69c4.png)

![image](https://user-images.githubusercontent.com/41829368/46512999-c0d63e00-c813-11e8-878b-413551f500cc.png)

**Comment by hernandn01** [comment]
changed to Sono directly in the config.txt. It started 3 instances of Trex mining Sono but the next cycle it went back to regular mining. Enabled Full view and Sono is visible so the fallback shouldn't kicked in

![image](https://user-images.githubusercontent.com/41829368/46513445-b026c780-c815-11e8-895f-4281e63e7315.png)

**Comment by hernandn01** [comment]
went back in to Sono by itself, and got me out of Full view and into Lite view,like if I was doing a Benchmark, but as you can see on the previous paste nothing was being benchmarking

![image](https://user-images.githubusercontent.com/41829368/46513693-14965680-c817-11e8-9af8-51eab98e49eb.png)

**Comment by RainbowMiner** [comment]
Thank you very much for testing! I will trim some little remains and then publish the new release.

**Comment by RainbowMiner** [comment]
> I am getting a different value on the profit in the script than the Dashboard and the Monitoring page. The last two are the same

fixed :) Nice finding. Thank you.

**Comment by RainbowMiner** [comment]
> Right now it is favoring excavator for the 1050 tis and the 1060 6b in one instance plus an instance of cryptodregde for the 1060 3gb (althought the last one comes as a negative profit it overalls the sum total, which is fine)

This is hard to say - would you send me your actual Logs\RainbowMiner_2018-mm-dd_hh-mm-ss.txt and the Logs\RainbowMiner_2018-10-05.txt ?

**Comment by RainbowMiner** [comment]
> is the profit column the last value to considered to select miners or after that number the cost of the power is factored in?

Yes.

**Comment by hernandn01** [comment]
I have been testing with different coins and everything is working as expected. I even tested Eth on Ethermine and the 1060 3GB I have disable ETH at the device.config.txt and the fallback worked for that card, thank you very much
