### ISSUE TITLE
Certain Algorithms Using Incorrect OCProfile in Out-Of-The-Box Experience

### ISSUE THREAD

**Issue by Sheeepthief** [RainbowMiner/RainbowMiner#1931]
This issue occurred with a new installation of RainbowMiner on Ubuntu 20.04.3 LTS.

RainbowMiner was configured to use two GPUs, a GTX10606GB and a P106090. Both had their respective "Profile1-..." from the ocprofiles.config.txt, set as the DefaultOCprofile in devices.config.txt. I then expected when I started benchmarking that all the algos would be using OCprofile1. What I found was that a handful of algos would consistently use a nondefault OCprofile. A noncomprehensive list includes:

NeoScrypt defaults to Profile3
PHI2 defaults to Profile4
X17 defaults to Profile 4
EquihashR25x5x3 defaults to Profile5
KawPOW defaults to Profile7

Looking at the algorithms.config.txt I find many algos that have their OCprofile set to a specific profile that matches what they are using in the benchmark. Most algos have no OCprofile specified and therefore properly use the default given by devices.config.txt.

Although I manually fixed the issue for my personal installation, I wanted to make aware that the out-of-the-box experience had the issue of not having all algos use the default OCProfile.

**Comment by RainbowMiner** [comment]
This is the default behavior, actually. Some algorithms don't need memory overclocking, some don't need core overclocking and some cause miners to crash in general, if the memory overclocking is at the upper limit. Therefor I have a default pre-defined set of profiles 0 to 7 (for MSI Afterburner, only Profiles 1..5):
- Profile 0: no core oc, reduced memory oc (e.g. 0/-500)
- Profile1 (MSI 1): no oc (e.g. +0/+0)
- Profile2 (MSI 2): max. core / max. memory oc (e.g. +100/+400), good for most miners
- Profile3 (MSI 3): max. core / half memory oc (e.g. +100/+200)
- Profile4 (MSI 4): max. core / low memory oc (e.g. +100/-500)
- Profile5 (MSI 5): max. core / reduced memory oc (e.g. +100/+350)
- Profile6: reduced core / max. memory oc (e.g. -100/+400)
- Profile7: small core / max. memory oc (e.g. +50/+400)

> Most algos have no OCprofile specified and therefore properly use the default given by devices.config.txt.

The setting in algorithms.config.txt has priority over the setting in devices.config.txt - so the default given in devices.config.txt is used only, if there is no other profile set for a specific algorithm in algorithms.config.txt.

The complete list of pre-assigned algorithms can be found in `./Data/AlgorithmsConfigDefault.ps1`
