### ISSUE TITLE
How to add WETH Wallet Balance (payout from Ethermine)?

### ISSUE THREAD

**Issue by sgeneralov13** [RainbowMiner/RainbowMiner#1935]
https://ethpool.freshdesk.com/support/solutions/articles/8000093699-polygon-guide

**Comment by RainbowMiner** [comment]
For that to show up, you need to create yourself a Covalent API key at https://www.covalenthq.com/ and add it to config.txt:
```
  "CovalentAPIKey": "<put your key here>",
```

.. then you add "WETH" as own coin in coins.config.txt
```
  "WETH": {
    "Wallet": "0x.....",
    "Penalty": "0",
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "2h",
    "PostBlockMining": "0",
    "MinProfitPercent": "0",
    "EnableAutoPool": "0",
    "Comment": "",
    "MinHashrateSolo": "0"
  },
```

**Comment by sgeneralov13** [comment]
> 

It work! Thank you!

![image](https://user-images.githubusercontent.com/35292309/149298612-0feeaaa9-ecf7-43a5-a4f7-ba21596f6fc3.png)

Not a very important comment: it doesn't work for some reason if I write like this:
_..."WETH": {
     "Wallet": "$ETH",..._

**Comment by RainbowMiner** [comment]
That's good to hear :)

```...
"WETH": {
  "Wallet": "$ETH",...
```

... yes, that's to be expected. There is no variable substitution inside the coins.config.txt file. But I think, it would be pretty neat. I'll add it to the enhancements list.

**Comment by coolbreeze21** [comment]
That is pretty cool.  Is there a way to do this for some of the smaller blockchains that Covalent doesn't support, like CFX, CTXC, SERO and TON?

**Comment by RainbowMiner** [comment]
For most of the blockchains, that's possible. What we do need is a public explorer, which offers an API.

**Comment by RainbowMiner** [comment]
I have just added TON. It's pretty easy.
