### ISSUE TITLE
Someone's Random Miner Showed up in my Monitoring Central

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1936]
![Capture](https://user-images.githubusercontent.com/12422346/149388795-f4fefbda-f98b-400e-8aa2-60ebf54794ef.JPG)

No idea who or what it is.  I've also never seen an ip address included at Monitoring Central.

**Comment by itsdarklikehell** [comment]
This is odd (or bad opsec).
Too bad its offline tho.
Is this even possible without having login creds? I suggest at least changing your servers password for the sake of security.

**Comment by RainbowMiner** [comment]
It's only possible, if this user had the same status key, which is a one-in-a-trillion chance.
Can you give me a machine name of one of your valid rigs?

**Comment by jch9678** [comment]
You mean expand the screenshot to include my computers that are online?  Would that help?  Just a little confused what you want.

**Comment by RainbowMiner** [comment]
Yes, expand the screenshot, so that at least one of your other machines is visible. But it be enough, if you just copy the contents of the first column (there is the machinename).

**Comment by jch9678** [comment]
Fletch_CPU

I'm curious how this helps. All my machines are named after movies

**Comment by jch9678** [comment]
So strange. Do you have any thoughts? Could someone have obtained my config? It would be quite a coincidence if someone was able to remote in, steal a config, then know what to do with a config. Are you able to see what device they mined with?

**Comment by jch9678** [comment]
@RainbowMiner do you have any thoughts on this.  I've done some investigating and found something very strange but I'm hesitant to talk about it here.  I think knowing how an ip address shows up in Monitoring Central would help.

**Comment by RainbowMiner** [comment]
Since it has been a singular incident, only, the respective record is already deleted from the database. I will have a look into a backup today.
If you like, you can contact me over at Discord, then you can share your findings and maybe we find the culprit

**Comment by RainbowMiner** [comment]
The rig's CPU: Intel(R) Core(TM) i5 CPU 760  @ 2.80GHz, GPU: GeForce GT 430

**Comment by jch9678** [comment]
Thanks, I DM'd you back.

**Comment by RainbowMiner** [comment]
I have added a new parameter to config.txt:
- add parameter "APIallowIPs" to config.txt: comma separated list of IPs, restrict API access to specific IP addresses. *-wildcard is allowed (e.g. 192.168.0.*)

You can now add one extra level of security by restricting the API access to a list if IP addresses.

**Comment by jch9678** [comment]
Thank you.
