### ISSUE TITLE
rbminet.net price bug

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1937]
![image](https://user-images.githubusercontent.com/42582444/149517556-7071b816-32c5-40f9-a679-bf3d13fca62b.png)
It looks like this has stopped updating.

**Comment by RainbowMiner** [comment]
Oh. Thank you for reporting this. I'll check the services.

**Comment by acos0874** [comment]
Was working but seems to be stuck again

**Comment by acos0874** [comment]
![Screenshot_20220123-151635](https://user-images.githubusercontent.com/42582444/150685432-275c106b-df3a-4a83-8635-694c3bced15b.png)

As much as I'd love for this to still be true, unfortunately it's still not solved

**Comment by acos0874** [comment]
Seems ok now.
