### ISSUE TITLE
Fast switch

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#194]
I would like fast switching mode. other miners like mindminer and nemosminer, they have fast switch mode.
but with RBM, it keeps mining same algo even after 10 minutes even after estimated profit is dropped.

**Comment by RainbowMiner** [comment]
Try to set "SwitchingPrevention" to 0. That should do the job.

**Comment by hernandn01** [comment]
how does that work? changing "SwitchingPrevention" to 0 from 2.0 or some other value

**Comment by RainbowMiner** [comment]
Yes. Set it to 0.

**Comment by rinkal26783** [comment]
I have already switched "SwitchingPrevention" to 0 since last week.

**Comment by RainbowMiner** [comment]
Ahh! Oh dear, you are right. The switching prevention speeds the switching between algorithm on a pool. The switching between pools is always with threshold. I will add a switch, so that you may disable that threshold, too.

**Comment by RainbowMiner** [comment]
The next release will contain parameter EnableFastSwitching - this will decrease the switching time.

**Comment by rinkal26783** [comment]
is it implemented in new version?

**Comment by RainbowMiner** [comment]
It will be in release v3.8.8.13 - the current master.zip already contains the implementation.
