### ISSUE TITLE
Nimiq Port number is missing in NoncerPro

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1940]
The port number is missing for NoncerPro at icemining.ca pool mining nimiq.  The port is 2053.

This is what the cmd line is with RM
noncerpro.exe --devices=0 --address=walletaddress --name=XXX --server=nimiq.icemining.ca --port= --api  --apiport=#### --mode=dumb

Adding "--port=2053" to the "Params": "",  of NoncerPro section of miners.config fixes the issue and mining is able to commence.

This may be a problem with nqminer as well as mining immediately closes too.

Edit: Port seems to be missing for Nqminer as well:

nq-miner.exe -t opencl -d 0 -a walletaddress -n XXX -p nimiq.icemining.ca: --api #### --mode dumb

**Comment by RainbowMiner** [comment]
In fact, this pool module needed a do-over. The pool doesn't send the stratum ports via their API any more.

**Comment by jch9678** [comment]
Thank you.
