### ISSUE TITLE
Why are some pools not in selection list?

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1942]
Specifically why are FIRO and ETC from Zergpool not showing up in the pool selection list?
I suspect it has to do with "24 hours actual" being 0. But I think the longer the pool goes without finding a block, the higher the probability it will find one.
Is there something I can configure to make these show up
[no_firo_etc_debug_2022-01-16.zip](https://github.com/RainbowMiner/RainbowMiner/files/7877597/no_firo_etc_debug_2022-01-16.zip)
?

**Comment by RainbowMiner** [comment]
> But I think the longer the pool goes without finding a block, the higher the probability it will find one.

That's not correct. In game theory, there is no increase in good luck over times of bad luck. The luck is dependent on hashrate and difficulty, only. So looking at FIRO at ZergPool, the current pool hashrate (+network difficulty) come down to a time to find of 45 hours. If you have only little hashrate to add, the work-to-revenue value will be pretty low.
Therefor RainbowMiner calculates the real profit, that you can expect when mining to a pool, factoring in the TTF (and some more).

I have described the profit switcher here: https://github.com/RainbowMiner/RainbowMiner#how-does-the-profit-switcher-work-and-how-can-i-change-its-behavior

**Comment by ZZCoder1** [comment]
Correct about the luck, but if two people roll dice 1000000 times each their results will be quite similar.
