### ISSUE TITLE
TON Coin Rates Missing

### ISSUE THREAD

**Issue by packetspyke** [RainbowMiner/RainbowMiner#1945]
I have TON coin added thanks to a recent release. The coin has no price so its never profitable and will never be mined. How do I get a price listed?

**Comment by RainbowMiner** [comment]
Thank you for reporting this, I'll doublecheck the rates service. The price will be back asap.

**Comment by RainbowMiner** [comment]
Question: did you use "TON" or "TONCOIN" as symbol in coins.config.txt/pools.config.txt?

**Comment by RainbowMiner** [comment]
> Thank you for reporting this, I'll doublecheck the rates service. The price will be back asap.

The rates service returns a value. In fact, I am mining TON on TONWhales for some time, now. Very important: do not forget to register your TON wallet address via Telegram. I recommend, that you add "TON" to coins.config.txt and then make use of the variable substitution in pools.config.txt:

coins.config.txt
```
  "TON": {
    "Wallet": "E....",
    "Penalty": "0",
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "PostBlockMining": "0",
    "MinProfitPercent": "0",
    "EnableAutoPool": "0",
    "Comment": "",
    "MinHashrateSolo": "0"
  },
```

pools.config.txt
```
  "TONWhales": {
    "TON": "$TON",
    "TON-Params": "",
    "Worker": "$WorkerName",
    "Penalty": "0",
...
```

**Comment by packetspyke** [comment]
I think my issue was that I added the coin as TON instead of TONCOIN. It would seem now that my rates tab reports both as the same amount so its mining this morning.

I suppose did you make a change?

I have used the pool before and I am already set up for telegram for the pool. Thanks for the heads up anyways 👍

**Comment by packetspyke** [comment]
It would seem that the rates page is displaying values for the coin now.
