### ISSUE TITLE
BTT on Unmineable profitability

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#1947]
Hi, BTT just did a redenomination and really affected in RBM profitability calculator

My current balance:
![image](https://user-images.githubusercontent.com/44210627/150723107-55551a91-acae-43e2-9d9f-5a7649f7933b.png)

meanwhile in coin gecko:
![image](https://user-images.githubusercontent.com/44210627/150723162-1c710066-f2b5-43dd-b225-280396f27a36.png)

So, I disable BTT for awhile due to extreme profitability issue.

**Comment by RainbowMiner** [comment]
Is this on pool unMineable, or globally?

**Comment by rizkyaulya** [comment]
mining BTT only at unmineable right?

the redenomintaion ratio is 1:1000
So the current profitability calculation is 1000 more than its should be

https://medium.com/@BitTorrent/launch-of-bttc-mainnet-and-btt-redenomination-plan-2eacfe26d22

**Comment by RainbowMiner** [comment]
Ok, should be fine, now.
