### ISSUE TITLE
RBM ignoring Extended Benchmark Setting?

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1948]
[extbm_debug_2022-01-24.zip](https://github.com/RainbowMiner/RainbowMiner/files/7928412/extbm_debug_2022-01-24.zip)

I have ExtendedBenchmark disabled:
"DisableExtendInterval": "1",

But RBM is still using extended benchmarks according to the below text.
Also, it says to disable extended benchmarks by setting DisableExtendedInterval to 0. That is backwards.
I did try setting it to "0" just to check, and no change in behavior.

Please be patient!
RainbowMiner will benchmark 200 out of 356 miners with extended intervals!
These algorithms need a longer time to reach an accurate average hashrate.
After that, benchmarking will be much faster (1-2 minutes per miner).
If you do not want that accuracy, set DisableExtendInterval to 0 in your config.txt.

**Comment by RainbowMiner** [comment]
I'll check this. Thank you for reporting it.

**Comment by RainbowMiner** [comment]
This function was broken - I have fixed it now.
