### ISSUE TITLE
Not starting after update to v4.8.0.1

### ISSUE THREAD

**Issue by sgeneralov13** [RainbowMiner/RainbowMiner#1949]
_Starting v4.8.0.1! Please wait..

Checking for VM .. ok (not in a VM)
Checking for cURL .. not found
Detecting devices .. 1 CPU, 1 Nvidia found
Starting sysinfo .. ok
Checking Windows pagefile/virtual memory .. ok
Initialize configuration ..
ERROR: Please check your configuration: The term '' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
InvalidOperation: Index operation failed; the array index evaluated to null.

Add-Member: Cannot validate argument on parameter 'NotePropertyMembers'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

ERROR:  is invalid. Cannot continue._

**Comment by RainbowMiner** [comment]
Oh! Could you please upload the current log file ./Logs/RainbowMiner_2022-01-25.txt ?

**Comment by sgeneralov13** [comment]
Log sended directly. Windows 10. I have full access to all files.

**Comment by sgeneralov13** [comment]
Solved by manual upgrade to v4.8.0.2! Thank you!
