### ISSUE TITLE
solution for ravencoin

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#195]
there is a pattern for raven coin. it could be very profitable coin if we mine on right time.
pools like zpool and blockmasters find ravencoin in sequence. 

for example. no ravencoin block found for 14-18 hours but once first block is found. they start finding ravencoin block everyhour.

I want to ravencoin on the right time. but with current miner. It shows same profit all the time, even if ravencoin blocks found or not.

**Comment by RainbowMiner** [comment]
That is interesting! I would never have thougt, that there could be a pattern. I will have a look, how to account for that.

**Comment by RainbowMiner** [comment]
We could integrate something like a "trigger", like "if N blocks found, increase profitability"

**Comment by hernandn01** [comment]
that can be confused by pool luck. sometimes it seems that pool is finding more blocks but those are awarded to miners that participated earlier with shares. it does not guarantee that the pool will continue to find blocks unless your miner(s) is it actually bringing a substantial hashrate to the pool

**Comment by rinkal26783** [comment]
this solution is good for ravencoin. and it can be applied to any other coins and it is totally up to the user. how they want to set it.
in my opinion is best chance to find ravencoin block after first block is found. and best time to leave mining ravencoin after 2 hours from last found block. this works best with zpool and blockmasters.

**Comment by rinkal26783** [comment]
![image](https://user-images.githubusercontent.com/30832110/46492748-1b7b9400-c82c-11e8-9e50-d3b3b8a7b1fa.png)
![image](https://user-images.githubusercontent.com/30832110/46492761-259d9280-c82c-11e8-899e-dee81427ca64.png)
![image](https://user-images.githubusercontent.com/30832110/46492796-3ea64380-c82c-11e8-962d-a4e5fa4ea2dc.png)

**Comment by RainbowMiner** [comment]
Well spotted. I will include an user defined trigger function. It will be very interesting, if this really improves the revenue. First of all, I need the information about the blocks.

**Comment by rinkal26783** [comment]
hashrate might affect the block found ratio. but, I am not sure how much variation.

**Comment by RainbowMiner** [comment]
Continued with issue #200
