### ISSUE TITLE
Unclean shutdowns

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1952]
Would it be possible to add an email notification please whereby when RBM starts up, it can detect that it wasn't closed down properly and will send an email notification through rbminer.net?

This would ultimately be useful for detecting when a rig has crashed and restarted itself.

**Comment by RainbowMiner** [comment]
Sure, no problem.
--> added.

**Comment by acos0874** [comment]
Ace thanks. Is there any useful information you think could be logged? I have a 3090 eGPU plugged into a laptop, and the whole system keeps rebooting after being fine for months. I'm trying to figure out what's causing the problem.

**Comment by acos0874** [comment]
Works fantastic. I sold the eGPU. Thank you.
