### ISSUE TITLE
LHR and 470.05 driver

### ISSUE THREAD

**Issue by OGizzle** [RainbowMiner/RainbowMiner#1953]
Is there a possibility to disable the LHR detection? Because my cards are unlocked using the 470.05 nvidia driver, but the mining software still detects my GPU as LHR and don't use the full hashrate.
An exeption if using the 470.05 driver would be helpful.

**Comment by RainbowMiner** [comment]
No problem. I'll add a check.

**Comment by RainbowMiner** [comment]
Question: I assume, you are using Windows and a single RTX3060 GPU, right? As far as I know, that driver doesn't unlock the full hashrate on a multi-GPU setup. Please correct me, if I am wrong.

**Comment by OGizzle** [comment]
I'm using 2x RTX3060 GPU. But you need "HDMI-Dummys" in addition to the 470.05 driver to unlock them. Another limitation is the pci slot. I had to use the onboard pci slots x16. I couldn't avoid the limitation with riser cars. 
I don't think you can use more than 2 GPU in the same rig anyway, because the LHR will be active again if you try to use a third GPU...
Quite a tricky thing :-)

**Comment by RainbowMiner** [comment]
Ok. That's bad :) 
It is not possible to detect this specific configuration automatically. I'll therefor add a parameter to either devices.config.txt and/or config.txt, so that you can disable the LHR detection manually.

**Comment by RainbowMiner** [comment]
I have added the new parameter "EnableLHR" to devices.config.txt:
- set to "1": if you want to force Trex and Teamblack into using LHR magic for a device
- set to "0": if you want to explicitly forbid Trex and Teamblack to use their LHR magic for a device
- leave empty "": if you want to let RainbowMiner automatically select, if Trex and Teamblack should use LHR magic for a device

I will push a release within some hours.
