### ISSUE TITLE
Gaming Mode

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1955]
I have a situation where I don't want to use pause on activity, but will occasionally pause mining to play some graphics intensive games. The problem is I often forget to resume mining after I'm finished and wake the next morning to find I missed a night of mining. I also have a 2nd GPU on a riser on this machine just for mining. 

My ideal would be a hotkey in the main window that will disable mining just on GPU#01 (for some reason the GPU on the riser takes the GPU#00 slot), then resumes on an activity time out.

Do you think this would be possible please?

**Comment by RainbowMiner** [comment]
An interesting idea. I'll think about it, should be possible.

**Comment by astronyu** [comment]
Good suggestion. Maybe adding an idle detector to start mining when PC is idle and pause or stop when game launcher e.g. steam is running?

**Comment by backamblock** [comment]
> Good suggestion. Maybe adding an idle detector to start mining when PC is idle and pause or stop when game launcher e.g. steam is running?

for the "steam" part, you should be able to do that with windows task scheduler. 
you can define multiple versions of triggers, so you could kill rbminer when steam starts and restart when steam closes.

to make it working effectively, you should set rbminer to autostart on boot, but i guess you already got that one :)

still, this would kill the whole rbminer, not just 1 GPU. but solves your problem about forgetting it 👍🏻

**Comment by samdave123** [comment]
The official Nicehash client automatically pauses mining when it detects a Steam game has started. That could be one of the auto-detection features in the gaming mode.

**Comment by backamblock** [comment]
@samdave123 
you can just build the "gaming mode" yourself in 2-3 minutes as mentioned above :)
