### ISSUE TITLE
Out of Memory Problems

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1957]
![image](https://user-images.githubusercontent.com/42582444/152237462-4f761743-5693-4f98-8f21-f96e779b92eb.png)

Any idea what might be causing this? I don't need to restart the rig to fix it, just restart RBM. Cards seems fine.

**Comment by RainbowMiner** [comment]
This message addresses the Windows paging file. How large is it, currently? Does Rainbowminer warn during the start, regarding it's size?
If yes, set it to the proposed size, if not, try to increase it by 30%

My gut feeling points to a small memory leak in the trex miner. I will forward this question to the trex developers, just to be sure.

**Comment by acos0874** [comment]
At the moment it is the correct size and does not show a warning. I will
try increasing it if the error persists.

Thanks

**Comment by acos0874** [comment]
Thanks for the fix. Has been fine for a few days.
