### ISSUE TITLE
miningpoolhub coins difficulty

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1958]
MPB does not appear to have difficulty set (d=xxx) with Phoenix miner and EtcHash.
It is set to 1 in my config.

**Comment by RainbowMiner** [comment]
You have added it to the following parameter, right? `"ETC-Params": "d=1",`,
If yes, does the `d=1` appear at the command line of Phoenix miner

For this pool (MPH), there are two things, that may change the difficulty afterwards:
- Difficulty value can go up and down again. It's not a bug.
  d=XXX just gives us hint at start and it doesn't enforce diff value to be fixed.
- Far wrong diff value may corrected automatically, but you'd better write optimized value.

(this info is copied from here: https://bitcointalk.org/index.php?topic=472510.msg10596890#msg10596890)

**Comment by talentoscope** [comment]
D'oh!
The one place I didn't think of putting it is where it should be haha
Thanks man, I'll do this now!
