### ISSUE TITLE
add worker name per device/combo

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#196]
is there currently the ability to identify the worker name per device? or can this option be added at the devices.config,txt for example. If there is a worker name in devices.config,txt use this instead

**Comment by RainbowMiner** [comment]
This is not possible, at the moment. But it is makeable, of course. I will have a look.

**Comment by hernandn01** [comment]
not sure if all the pools support this, but this can be achieve by adding the device/group name to the address: address.workername

**Comment by hernandn01** [comment]
I added a name into devices.config.txt into each device in the MinerName key hoping that will solve this question (coincidentally I use the device name as the MinerName in each case) and all devices became non profitably, I remove the name and they started mining again.   

![image](https://user-images.githubusercontent.com/41829368/48575754-046e9e00-e8d0-11e8-9624-720f4f041c06.png)

**Comment by RainbowMiner** [comment]
Ah yes :) This is the MinerName, e.g. Trex, Cryptodredge, not the Worker. So if you put in your workername, Rainbowminer will no longer find miners that match this. I have not yet added this feature, but will do this.

**Comment by RainbowMiner** [comment]
There is one restriction with this feature: if a device has a different Worker name than the global default, it will not be used in a combo with the others. This is because the worker can only be set per running miner.

**Comment by hernandn01** [comment]
you are right, I guess the name of the worker should be of the name of the combo. That will work for me. Even better that will tell me at a glance how many cards and which are giving that hashrate at the pool level

**Comment by RainbowMiner** [comment]
How about that idea: if worker names are assigned to devices, the combo-workername will be automatic like "worker1-worker2"

**Comment by hernandn01** [comment]
yes, I think that will work

**Comment by RainbowMiner** [comment]
Implemented with commits b5d71592db0e8629101d9a996f04c79a7f2b1610 and c3b9dab5b39d8b87b84219d0fc792ecf16dafd8a

- each device my get it's own worker name (devices.config.txt, field "Worker")
- the total workername of a combo will be a "_" - concatenation of all device worker names
- if no device worker name defined, the default worker name from config.txt will be used
- no duplicate device worker names, e.g. "rbmabc","rbm","rbm" will be "rbmabc_rbm" (and not "rbmabc_rbm_rbm")
