### ISSUE TITLE
ETH + TON report and issues

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1960]
The recent release of lolMiner 1.43 says that it “Added support for real dual mine Ethash / Etchash / Ubiqhash + Ton.”  That certainly sounds interesting.  Below is my experience in trying to get this working with RBM on two Win 10 rigs, a 2080 and a 3090.

1.	It is widely reported on the lolMiner Github that lolMiner will crash if TonWhales is the TON pool, and that switching to another pool like TonPool fixes the issue.  My experience tends to confirm this.  Since TonWhales was the only TON pool I initially had configured in RBM, all initial benchmark tests promptly failed with a crash.  This caused RBM to think that ETH + TON didn’t work at all, when it actually appears to be a pool issue with TonWhales.

Note to those new to TON:  with either TonPool or TonWhales you have to do a one-time anonymous signup using their respective Telegram bots before you can start mining.

2.	I then disabled TonWhales and enabled TonPool.  The crashes on the 3090 had been “silent”, that is not accompanied by a popup Windows crash report, but the ones on the 2080 generated the popup.  On the 2080, it appears that this eventually led RBM to suppress lolMiner ETH + TON entirely from the Miners and Benchmarks sections, even after resetting the Watchdog.   Since I could no longer select ETH + TON, this prevented me from continuing any testing with the 2080.  On the 3090, ETH + TON also initially disappeared as an option, but resetting the Watchdog and the benchmark caused it to reappear and rebenchmark using TonPool without crashing.

How does one reenable a miner that RBM has suppressed in this manner?  I have had the same experience with TeamBlack and certain algos like Ethash and could never get it back as an option to even test.

3.	The lolminer release notes say “On Nvidia GPUs we recommend a very high power limit (or none set at all) plus locked core clock for ideal mining experiences. Variable clocks or low power limits might give inconsistent or non ideal results”.  By default, RBM uses the same OC settings for ETH + TON (MSIA3/Profile 3 - max memory, low core, limited power) as for ETH.  I strongly question whether this is appropriate for ETH + TON.  I increased the MSIA3 power limit on the 3090 from 87% to 100% and noticed a definite improvement.  I think it is likely that the ideal OC settings are max memory, max locked core, max power, high cooling.  How does one override the OC selection associated with an algo in RBM?

For those who aren't going to tune their overclocks, I would recommend that RBM change its default OC setting for ETH + TON to what it uses for TON (the “standard” OC, typically # 2), as a better approximation of the ideal OC setting than what it uses for ETH (typically # 3).

4.	The 3090 continued stable with ETH + TON for hours.  It was the most profitable algo by a modest percentage, beating plain ETH, which had usually been most profitable previously.  However, much later RBM was still generating an error similar to the following every cycle “Warning: Stat file (lolminer-Ethash-GPU#00_SHA256ton_HashRate) was not updated because the value 1.95 GH is outside fault tolerance 284.53 MH to 711.32 MH.”.  It appears that RBM is never recording the actual TON performance of ETH + TON because it far outside the range it expects.  At a minimum, I would expect this is causing RBM to improperly estimate ETH + TON profitability.  Potentially worse, at one point I thought I saw RBM discard ETH + TON entirely because it thought it wasn’t mining any TON, since it was ignoring all the actual results.

I think RBM needs to recognize that the stats resulting from ETH + TON dual mining will be significantly different than those from mining ETH and TON individually and track them separately.

As a distinct but related issue I think RBM’s stat fault tolerance is too tight in general.  ETH + TON is not an isolated incident of RBM ignoring real results.  In my opinion, it would be better to loosen the stat fault tolerance significantly and accept the occasional outlier (for example, from startup) as one data point among many, rather than the current situation in which RBM sometimes systematically ignores long periods of valid data because they are outside the overly restrictive fault tolerance.

I would be interested in hearing others experiences with the new ETH + TON option, particularly under Windows (reports are that it currently works better on other OSs).

**Comment by RainbowMiner** [comment]
I have mostly the same experience.

> For those who aren't going to tune their overclocks, I would recommend that RBM change its default OC setting for ETH + TON to what it uses for TON (the “standard” OC, typically # 2), as a better approximation of the ideal OC setting than what it uses for ETH (typically # 3).

Fixed with commit 6eecda02a690b50e88022d6bba5d814dddfc299a

> I think RBM needs to recognize that the stats resulting from ETH + TON dual mining will be significantly different than those from mining ETH and TON individually and track them separately.

The dual mining results are being tracked separately already. This happened to you, because you have changed the overclocking settings. In that case, you should let RainbowMiner re-benchmark the algorithm. 
Nonetheless it's maybe a good idea to at least loosen the upper limit of the hashrate bandwidth a bit. I'll think about it.

**Comment by coolbreeze21** [comment]
After the 4.8.0.5 update, I got ETH + TON working on both rigs on TonPool.  However, TonPool has a steep 5% pool fee vs. TonWhales 0%.  The comments on the lolMiner Github confirm that TonWhales isn’t working at present because of Cloudflare issues.  They also say “there have been issues with TonWhales so everyone jumped to TonCoinPool.io”.  TonCoinPool.io has a 0% pool fee.  MiningPoolStats confirms it has gained 3000 miners in the last day to become the number two TON pool.

Would you please add TonCoinPool.io to RBM?  The setup of ETH + TON is too complex for me to want to try adding it as a custom pool.  Thanks.  I will post here if there are reports that TonWhales is fixed and would appreciate it if you would do the same.

ETH + TON now appears to be the most profitable mining option on both rigs by a substantial margin.  I really appreciate RBM keeping so up to date with the latest developments in mining, even though it means more work for you.

**Comment by RainbowMiner** [comment]
> Would you please add TonCoinPool.io to RBM? The setup of ETH + TON is too complex for me to want to try adding it as a custom pool. Thanks. 

No problem. I have added the ToncoinPool. Be aware, that the ToincoinPool pays PPLNS while the TonPool pays PPS.

**Comment by paulpoco** [comment]
I cannot get the ETH and TON dual mining to work.

[debug_2022-02-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/8024983/debug_2022-02-08.zip)

**Comment by paulpoco** [comment]
Ok not a pool issue as I tried TONpool and got 0GH on dual but TON only is fine

**Comment by paulpoco** [comment]
ToncoinPool dual doesn't work either.

**Comment by paulpoco** [comment]
Ok tried to do it manually(Outside of RBM) and dual doesn't work either.
https://2miners.com/blog/eth-ton-dual-mining-definitive-guide-overclocking-profitability-setup-for-windows-and-linux/

**Comment by coolbreeze21** [comment]
For what it's worth, ETH + TON is working here on my 3090 rig on 2MinersAE and either ToncoinPool or TonPool.  It worked "out of the box" with RBM once I dumped TonWhales as the TON pool.  ETH + TON was working on my 2080 rig on 2MinersAE and TonPool until RBM apparently suppressed ETH + TON entirely as an algo option.  Sorry I can't be of more help.

Just for fun, there are reports on the lolMiner Github that people have gotten ETH + TON + ZIL triple mining working using both Shardpool and Ezil as the ZIL pool.  I prefer Rustpool for ZIL, but I am waiting to get ETH + TON stable before giving that a try.

**Comment by coolbreeze21** [comment]
One additional thought for paulpoco:  what are you using for overclock settings?  All reports, and my experience, are that you have to feed it pretty much as much power and cooling as you have got to start, stabilize and avoid throttling.  Previous ETH settings don't cut it; ETH +TON is more demanding and heat producing than any other algo.

**Comment by coolbreeze21** [comment]
Paulpaco, I should have paid closer attention to your screenshots.  It looks like you are trying to get ETH +TON this working on 1070 (Pascal) GPUs.  I don't think anyone was able to do that using lolMiner 1.43.  LolMiner 1.44 describes its support for Pascal GPUs as "experimental".  From the release notes: "Added experimental Ethash + Ton dual mining kernels for Nvidia Pascal generation GPUs".  I'm surprised the lolMiner devs thought it might work at all on Pascal GPUs, considering DAG sizes and how taxing the algo is, but perhaps they just said "WTF, users asked us to give it a shot.  Maybe it works on a 1090 Ti"

**Comment by RainbowMiner** [comment]
> ... but perhaps they just said "WTF, users asked us to give it a shot. Maybe it works on a 1090 Ti"

I am pretty sure, they said that :)
The dual mining ETH+TON actually works so-so on my GTX1070 rigs with v1.44.

**Comment by coolbreeze21** [comment]
So, how do I get back the ETH + TON option that RBM has suppressed on my 2080 rig?

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/153125306-15f14e26-f51d-430b-81a8-6f906427f9fa.png)
Not showing hash on TON for GPU 1

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/153126406-95aa4090-17fc-4482-8b05-b4017c3f3866.png)
Tried a different pool now no hash for TON on GPU 0

Not worth it, uses more power and make the same as just Ethash alone

**Comment by coolbreeze21** [comment]
Overnight, lolMiner ETH + TON has now disappeared as an algo option and from the Miners and Benchmarks sections on my 3090 rig.  It had been working fine for days.  The activity log shows its most recent launch ran 10+ hours with no crashes, but now it is as if it doesn’t exist at all.

What is going on???  And how do I fix this?

**Comment by RainbowMiner** [comment]
- which release version of RainbowMiner are you on currently?
- go to http://localhost:4000 and click "Watchdog": it is possible, that the algorithms or pools are currently disabled by the watchdog
- have a look into the stat files: `.\Stats\Miners\Lolminer-Ethash-*.txt` - please upload them here.

**Comment by coolbreeze21** [comment]
I am currently using 4.8.0.6 but the issue also occurred on earlier versions.  I tried resetting the Watchdog many times without success.  The stat files for two rigs are attached.  Because they have the same file names, I appended "(3090)" to the 3090 ones.

I was using ToncoinPool when the ETH + TON disappeared on the 3090 around 4 AM this morning, but I was using TonPool on the 2080 when it disappeared (under 4.8.0.5, I think) on 4/7.  I will try your pools.config.txt suggestion next.

[NVIDIA-lolminer-Ethash-GPU#00_SHA256ton_HashRate (3090).txt](https://github.com/RainbowMiner/RainbowMiner/files/8034160/NVIDIA-lolminer-Ethash-GPU.00_SHA256ton_HashRate.3090.txt)
[NVIDIA-lolminer-Ethash-GPU#00_SHA256ton_HashRate.txt](https://github.com/RainbowMiner/RainbowMiner/files/8034161/NVIDIA-lolminer-Ethash-GPU.00_SHA256ton_HashRate.txt)
[NVIDIA-lolminer-Ethash-GPU#00_Ethash_HashRate (3090).txt](https://github.com/RainbowMiner/RainbowMiner/files/8034162/NVIDIA-lolminer-Ethash-GPU.00_Ethash_HashRate.3090.txt)
[NVIDIA-lolminer-Ethash-GPU#00_Ethash_HashRate.txt](https://github.com/RainbowMiner/RainbowMiner/files/8034163/NVIDIA-lolminer-Ethash-GPU.00_Ethash_HashRate.txt)

**Comment by coolbreeze21** [comment]
I made the change to pools.config.txt and gave it some time.  No luck.  Lolminer ETH + TON is still deleted from Miners and Benchmarks, where it was present before.  I do still have entries visible in Activity showing that it was working with no crashes, but those will scroll off in time.  Should I save those or send those?

I then did a cold reboot, restarted RBM on both rigs, enabled TonPool, ToncoinPool and Icemining for TON and gave it some time.  Still no luck.  I can't use ETH + TON at all, as if RBM had banished it :(

**Comment by coolbreeze21** [comment]
Looking at the code in your commits today, I thought I should mention, in case it is relevant, that months ago I changed the default setting in RBM from "StatAverageStable": "Week" to "StatAverageStable": "Day".   StatAverage is unchanged from the default at "StatAverage": "Minute_10".

My reasoning was that, with recent volatility, week-old data sometimes might as well have been ancient history, considering weekly price swings of up to 50% in many coins, including large ones.

**Comment by RainbowMiner** [comment]
Could you please create another Debug file.and upload it here? Click on Debug file on page http://localhost:4000

**Comment by coolbreeze21** [comment]
Here you go:

[debug_2022-02-09.zip](https://github.com/RainbowMiner/RainbowMiner/files/8035869/debug_2022-02-09.zip)

**Comment by coolbreeze21** [comment]
The lolMiner Ethash and ETH + TON algos spontaneously reappeared here at around 17:55 EST (-5 UTC) and started benchmarking on TonPool on the 2080 rig.  I am thinking that had to be something you did, so I wanted to give you the timestamp for what worked.

So far, there is no improvement on the on the 3090 rig despite resetting the watchdog and hitting him on the nose with a rolled up newspaper.  But I think you must be on the right track.

**Comment by RainbowMiner** [comment]
Ok, could you please check
- if the TonPool is on `http://localhost:4000/bestpools.html`
- at which position the Lolminer Ethash + SHA256ton is on page `http://localhost:4000/activeminers.html`

**Comment by coolbreeze21** [comment]
ETH + TON spontaneously reappeared (I was asleep) on both rigs as of 01:47 (3090) and 02:11 EST (2080) and has been running continuously since then without any crashes.  TonPool is listed as the best TON pool on Best Pools on both rigs.  TonPool is listed as number 1 on Active Miners and Miners on both rigs, beating the second-place miner by 35-37%.

I am pretty sure ETH + TON had been missing entirely from Active Miners during those periods when it was “disappeared”, but it could conceivably have been far down the list, since I was looking much more frequently at the Miners tab.  I am 100% certain it was missing entirely, not far down the list, on Miners and Benchmarks.  I had the console visible, but wasn’t relying on it; I knew its top-3 didn’t show the whole picture.  So, I don’t think the explanation is “total profitability just slipped”.  But it is back now on both rigs, which is the most important thing.  Thanks!

FWIW, since encountering this issue, I had given both rigs a choice of 3 TON pools: TonCoin, ToncoinPool and Icemining.  In the Pools section, Ton Pool is currently showing that it is 75% more profitable than ToncoinPool and 84% more profitable than Icemining.  That certainly outweighs it's 5% pool fee, if true.  I will probably run some tests comparing the balance/wallet results of the pools once I am comfortable that ETH + TON is reasonably stable.  I had noticed that ToncoinPool didn’t seem to be accumulating TON in my balance as fast as TonPool, but it was just a gut sense.

**Comment by RainbowMiner** [comment]
I think, I have found out, what causes the problem with your config:
For the time when ETH+TON disappeared, your userpool Rustpool was more profitable than the 2MinersAE pool. That wouldn't have caused any trouble, if you hadn't restricted the Rustpool to Phoenix miner in your pools.config.txt (parameter MinerName). With this restriction in tact, RainbowMiner chose Rustpool as best ETH pool, but didn't allow Lolminer to start to mine ETH.

```
    "Rustpool": {
      "BTC": "XXX",
      "BTC-Params": "",
...
      "MinerName": "Phoenix",
...
    },
```

So, I would recommend, you either drop the restriction to Phoenix all together, or you add Lolminer to the list. 

Like that, for example:
```
    "Rustpool": {
      "BTC": "XXX",
      "BTC-Params": "",
...
      "MinerName": "Lolminer,Phoenix",
...
    },
```
