### ISSUE TITLE
Failed Benchmarking with NBminer (--coin etc)

### ISSUE THREAD

**Issue by Sheeepthief** [RainbowMiner/RainbowMiner#1965]
The NBminer.ps1 PowerShell script contains conditions to add a "--coin etc" parameter to the miner upon benchmarking with Etchash algorithm on ZergPool. However, it appears that "--coin" is not an valid/accepted parameter according to NBminer's [CMD option documentation](https://github.com/NebuTech/NBMiner). Therefore, RBM fails to bench or mine Etchash on Zergpool.

The log output is:
`NBMiner: Unknown option 'coin'.`

I don't know enough about PowerShell script to fix this problem myself, unfortunately. :(

**Comment by RainbowMiner** [comment]
No problem, I will fix it asap. Thank you for reporting this.
