### ISSUE TITLE
TTF is wrong for RTM on Zergpool

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1966]
TTF in RBM shows 1.7h for Take2. The pool is profit switching between two coins. The coin it is mining on is RTM, which has 41h TTF according to Zergpool. So I think RBM is calculating TTF based on the other coin in the Raptoreum pool which has TTF of 2-3 hours.
Not sure if this can even be addressed, but it it causing the maxTTF parameter to not work correctly in this case.
[rtm 41h debug_2022-02-09.zip](https://github.com/RainbowMiner/RainbowMiner/files/8036380/rtm.41h.debug_2022-02-09.zip)

**Comment by RainbowMiner** [comment]
That's in fact a bit of a problem, because ZergPool doesn't send us the info, to which the profitswitcher points, currently. Our pool module currently uses the minimum TTF of all the coins for an algorithm.

**Comment by ZZCoder1** [comment]
So maybe it is not a good idea to use a low TTF when the pool has a profitswitcher, or if possible use the max TTF of the coins being mined. But I think maybe that is too much effort.
