### ISSUE TITLE
Ravenminer is not the same as Ravenminer EU

### ISSUE THREAD

**Issue by giannibonfanti** [RainbowMiner/RainbowMiner#197]
RavenMiner.com and eu.RavenMiner.com return different results from their api (like estimates, stats).
Wallet balance is different, hashrate, luck.. depending if you use EU or US pool.

Also, in RBM US pool api are the fallback of EU pool, and in this way US apis are never called (although "us" region is set in config).

Instead of having a single pool file with 2 regions, I think that RavenMiner pool should be treated as two different pools with one region, like:

RavenMiner.ps1 -> ravenminer.com -> US
RavenMinerEu.ps1 -> eu.ravenminer.com -> EU

I suppose that the same thoughts can be applied to balances.

**Comment by RainbowMiner** [comment]
Yes, good point. Ravenminer in it's current form has it's roots in the beginning of eu.ravenminer.com, when hashrate has been too low from time to time. I will separate the Miner.

**Comment by RainbowMiner** [comment]
Done with v3.8.8.15
