### ISSUE TITLE
RBM does not allow decimal points in difficulty

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1973]
For Yespower, I noticed the stratum put me down to 0.25 difficulty, so I added this 0.25 to miners.config
I restarted the miner and it's set sd=25, omitting the "0." bit.

Is this an international keyboard issue with decimal numbers between ',' and '.' ?

![image](https://user-images.githubusercontent.com/22162766/154824795-7c8f60e4-b149-4b3c-99e4-a542169ad1bb.png)

**Comment by RainbowMiner** [comment]
It's more a "no dots allowed" issue. I will adapt the check. Did you add the difficulty via the password parameter?

**Comment by talentoscope** [comment]
Nope. Added it in miners.config as suggested in that other issue :)

**Comment by talentoscope** [comment]
Oh wow, thank you buddy, amazing!!!!
