### ISSUE TITLE
[Question] MRR display

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1978]
Just a question really.

The MRR Rigs page shows Rig Price, but I'm not sure where that data comes from or what it's supposed to represent?

If it's cost or something, can that be changed to be more reflective of what it is please?

**Comment by RainbowMiner** [comment]
The Rig Price column is the value, that MRR proposes for a rental. It's a number for orientation to find out, why some rigs never get rented.

**Comment by talentoscope** [comment]
So the suggested times the number of hours basically?
Gotcha, thanks!
