### ISSUE TITLE
TONWhales pool issue

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1980]
Keeps dropping the connection for some reason
![image](https://user-images.githubusercontent.com/22162766/156135522-750089f0-e2f3-465b-9a3a-ae1aae80a228.png)

**Comment by RainbowMiner** [comment]
I see - Lolminer doesn't detect the correct ton mode for the tcp.whalestonpool.com stratum. I have just updated all TON pools and miners, so that the pool module effectively controls the miner's ton mode setting. That should fix this issue.

**Comment by talentoscope** [comment]
Nice one, as always :)
