### ISSUE TITLE
nlpool payout coin bug

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1981]
I've added GRIN and others to my coin options, but nlpool is getting c=GRIN which they do not support (it's choosing others too).

**Comment by RainbowMiner** [comment]
In fact, I have found a bug in the module. Happens, if `"EnableAutoCoin": "1",` is being used or a coin wallet has been added to the pool in pools.config.txt, that isn't supported by the pool.

**Comment by talentoscope** [comment]
Cool, thanks bro! :)
