### ISSUE TITLE
Ton-Pool not earning anything even though all looks OK in RBM

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1982]
Ton-Pool had been working fine before for me until around the 4.8.1.6 update yesterday (which may be a coincidence, since Ton-Pool also made some changes).  Since yesterday, everything still looked good in RBM but their Telegram Ton-Pool bot, which reports the balances and hashrates, wasn’t showing any earnings or hashrate despite hours of mining on two rigs.  I contacted Ton-Pool on Telegram and their first response was to direct me to this link:

https://telegra.ph/How-to-launch-a-new-ton-pool-server-with-lolminer-145-and-wsseu1stratumton-poolcomstratum-in-HiveOS-02-18

When I pointed out that I was not using HiveOS but rather Rainbow Miner they replied with this:

![image](https://user-images.githubusercontent.com/96564929/156421598-778c582c-f301-4f25-8aaa-4a262ec47ec4.png)

TonWhales still works fine, but their reported $/GH is usually lower than Ton-Pool.  So, this is mainly an alert to other RBM users that they may want to check their actual earnings and disable Ton-Pool if they are not getting any, like me.  If the RBM dev is willing to investigate, that would be nice, but I can understand if he has other priorities, since other pools are working and the Ton-Pool people weren’t particularly helpful (they also hit me with a temporary ban for innocently mentioning that the same RBM configuration worked with Whales).

**Comment by coolbreeze21** [comment]
UPDATE: TonPool has the same issue with Gminer 2.83.  Everything looks good on the RBM side, but no hashrate or earnings are being reported on the pool side.   Switching the region from the US to the EU made no difference.  Gminer 2.83 works fine with TonWhales, in fact it slightly beat lolMiner 1.46a on benchmarking.

**Comment by RainbowMiner** [comment]
I thought I had seen some hashrate results at Ton-Pool with the Gminer while testing, yesterday. How long have you been testing?
Anyway, I will let it test-run a couple of hours, starting now.

**Comment by RainbowMiner** [comment]
Note: You might be able to increase the income of Gminer a little; set the "Intensity" parameter in miners.config.txt (search Gminer-YourGPU, then scroll down until you find Ethash+SHA256ton). Then enter a comma separated list of intensities. All intensities will get benchmarked separately. E.g.
```
  "Intensity": "8,12,16,20",
```

**Comment by RainbowMiner** [comment]
Oh! Did you already update to the new RainbowMiner release v4.8.1.7? That's rather important, since it switches the TonPool to "Icemining" type of stratum. And of course contains the changes for the use of multiple Intensities.

**Comment by coolbreeze21** [comment]
Yes, I updated to 4.8.1.7 minutes after it came out.  The issue was present both before and after the update.

I first noticed the problem two days ago when lolMiner had been running for at least 2 hours on both rigs without generating any results in the Ton-pool bot.  Since then, I have limited my testing to 10-15 minute intervals, since the bot has a 10 minute hashrate report.  If I see 0 hash on the 10-minute report after 15 minutes I consider the test a failure.

Thanks for the tip on how to use Intensity setting.  I noticed it in the release notes, but didn't understand how to use it.  I am going to test "Intensity": "8,12,16,20,24", since the 3090 appears to have defaulted to 24

**Comment by RainbowMiner** [comment]
If it defaulted to 24, maybe add another 28 and 32 on the upper side, too. It's just to see where the profit(intensity) curve has it's maximum.

**Comment by RainbowMiner** [comment]
Update: my tests return the same - zero hashrate at the ton pool bot. That is bad. I bet they have a problem with the stratum to ton pool bot bridge, since the miners definitely find shares and it also seems that the stratums are accepting them. I'll better switch to TONWhales for the time being, too.

**Comment by coolbreeze21** [comment]
OK, testing 8,12,16,20 on the 2080 and 8,12,16,20,24,28,32 on the 3090.  I suggest you add the more detailed instructions on how to use it to the release notes.

For what it's worth, multiple users are reporting the issue with the Ton-pool bot reporting zero or low hashrate/earnings on the Ton-Pool Telegram chat.  I doubt they are all using RBM.  It seems to be a wider problem.  I mainly wanted to warn people to check the bot, because all looks good on the RBM side but you are not getting any credit on the pool side

**Comment by RainbowMiner** [comment]
> It seems to be a wider problem. I mainly wanted to warn people to check the bot, because all looks good on the RBM side but you are not getting any credit on the pool side

Agreed.

**Comment by coolbreeze21** [comment]
The 3090 profitability climbed steadily to 22, peaked at 25 and dropped off sharply after 26.  The 2080 profitability climbed steadily to 40, peaked at 45 and declined at 50.  This was with electricity cost set to $0.18/kWh.  The top of the “curve” on the 2080 was erratic, maybe because it finds fewer shares in the roughly 15-minute benchmarking interval.

I question whether the release notes should say that “only 5-20 make sense”.  22-26 was the sweet spot on the 3090 and 40-50 was the sweet spot on the 2080.

Also, Ton-Pool admin Make Maks appears to have started to take the “0 hash in the bot“ complaints seriously within the last hour (they were ignoring them or blowing them off with robotic responses before).  He posted:

Dear miners! Whoever has problems with displaying the hashrate in the pool bot, please enable the miner log and send me a private message:
1. Screenshot from the bot showing the drop in hashrate;
2. Miner log file *.log where the time interval during which the crash occurs is fixed;
3. The number of your wallet registered in the bot;
Only if these points are met, I can help you with something and contact the developers of the miners to eliminate the identified problems.

So if you want to send him something, maybe they’ll respond now.

**Comment by RainbowMiner** [comment]
Wow, thank you for sharing the results! I'll change the "make sense" values in the final documentation of the Intensity feature. And I am happy, that the ton-pool devs now acknowledge that there is a problem. Let's hope they fix this soon.

**Comment by coolbreeze21** [comment]
It looks to me like Gminer 2.84 fixed the "0 results in bot" issue.  The Gminer devs acknowledged that this was a miner issue in 2.83 that they fixed in 2.84.  

As far as I know (I haven't retested), it is still an issue with lolMiner 1.46a, so RBM users should exclude lolMiner from Ton-pool unless they have tested that it is posting results in the bot.  If anyone has retested lolMiner on Ton-pool and seen that it is posting results in the bot, please post here.
