### ISSUE TITLE
MRR not respecting paused state

### ISSUE THREAD

**Issue by callym** [RainbowMiner/RainbowMiner#1983]
I've had a few times where I've paused and then MRR has rented my rig, which then gets refunded because there's no hashrate (because RM is paused) - I'd expect pausing to not let people rent the rig until it's unpaused? I know there's the system maintenance option but it's not as convenient as the big pause button on the dashboard

**Comment by RainbowMiner** [comment]
That sounds like a bug to me, I will check what is going on.

**Comment by RainbowMiner** [comment]
Ok, that was a nice one. Thank you for bringing this up.
I have added parameter "AllowRentalDuringPause" to pools.config.txt and mrr.config.txt
-  set to "1", if you want to allow renters to rent your rig's worker(s), even if the rig is currently in Pause mode [default=0]
- the rig reacts differently on pause, now: do not pause mining, if a worker is currently in exclusive mode (rented by MiningRigRentals). This affects the currently rented worker(s), only. So if you have CPU and/or multiple GPU models, only the currently rented out models (or your CPU) keep on running, all others stay paused.
