### ISSUE TITLE
ocprofiles.config.txt vs miners.config.txt

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#1985]
If my ocprofil is named Profile1-RTX3070 do I need to use "OCprofile": "Profile1-RTX3070" to make it work in miners.config.txt or it will detect the json parent name "CcminerMtp10-RTX3070" and "OCprofile": "Profile1" would be enough to make it work ?

Is there a way to add an overclock column to the command line output so we know which overclock is active for the active miner gpu ?

Thanks for you excellent work ;)

**Comment by RainbowMiner** [comment]
The keys on ocprofiles.config.txt are `Profilename-GPUMODEL` - in miners.config.txt you use the `Profilename`, only. (E.g. "Profiile1-RTX3070" in ocprofiles.config.txt will be selected by `"OCprofile": "Profile1",` in miners.config.txt)

**Comment by RainbowMiner** [comment]
> Is there a way to add an overclock column to the command line output so we know which overclock is active for the active miner gpu ?

Yes, that should be possible. I will add the info.

**Comment by astitsa** [comment]
Thank you very much !

**Comment by astitsa** [comment]
Is there a list of the todo priority we can check to know what will be release next ?

Thanks
