### ISSUE TITLE
MPH SHA256

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1986]
RBM, when can I expect this payout? 🤣 
Bug in calculation :)
![image](https://user-images.githubusercontent.com/22162766/156787286-976839f9-72a5-4a6e-aafc-adc2e914403a.png)

**Comment by RainbowMiner** [comment]
What a wonderful GPU that old GTX1050Ti can be! I'll deactivate SHA256 completely. It just doesn't make sense.

**Comment by RainbowMiner** [comment]
Done. That was the last of the miners, that had SHA256d enabled.

**Comment by talentoscope** [comment]
Thanks dude :)

Power to the 1050Ti haha!
