### ISSUE TITLE
Add TTF & Pool Hash in order to find more frequent blocks

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#200]
if you could display ttf and pool hash on mining screen and user can set filter to mine most profitable coin/algo with highest profit + shortest ttf (manual set max wait time 10,20,etc..)
It will help to avoid mining hard diff coins (ravencoin,bitcore,bcd,verge,lux) at the time of low pool hash rate. but when pool hash rate increase they would be able to mine those coins.
I think this is good idea and it may give more profit. we should try this.

**Comment by RainbowMiner** [comment]
Ok, I added Hashrate and block count (to calculate TTF) to the statistics database of the pools (if applicable). Those values are visible in the http://localhost:4000. So, what to do with this info now. At which setting would it make sense to define a maximum wait time? For each currency? Globally? For each pool?

Open for discussion :)

**Comment by RainbowMiner** [comment]
This issue is main discussion for the following issues: #176 and #195

**Comment by hernandn01** [comment]
I would add in the mix, if possible, the actual global hashrate per pool. Right now BlockMasters publish a higher price for x16r but what it matters is RVN so the actual return is much lower. So collect the actual hashrate per coin and prefer the pool that has a high hashrate regardless of price. Also prune the list of algo/coins of less than x miners are actually mining that combination on a given pool.
