### ISSUE TITLE
Rentals sometimes stop early

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#2000]
I've noticed this a few times in the past couple of weeks. The rig will start a rental but then at some random time in the rental my rig will just switch back to nicehash. If I restart rbm through the console, it will then pick up the rental again. Please can you investigate?
[debug_2022-03-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/8230619/debug_2022-03-11.zip)
![image](https://user-images.githubusercontent.com/42582444/157837937-49e1ef05-aaae-4484-b492-7782ee919020.png)

**Comment by RainbowMiner** [comment]
Strange, yes of course, I will have a look.

**Comment by RainbowMiner** [comment]
I have identified and (hopefully) fixed the problem. Thank you for that report! I noticed this problem myself one or two times, but was too late for a debug file and therefor couldn't put my finger on it.

**Comment by RainbowMiner** [comment]
I have found another worst-case condition, that needs to be solved. I'll push a commit asap.
