### ISSUE TITLE
Rental Extension Premium

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#2008]
Working under the assumption that once a rental starts, RBM no longer updates MRR prices based on mining data, would it please be possible to add a feature that increases the extension price by a certain premium after the rental starts? The aim would be to prevent the types of rentals where a renter books for 6 hours then extends when the market moves in their favour.

**Comment by samdave123** [comment]
Thanks @acos0874 for raising this. This is exactly why I have extensions disabled. Usually I only get an extension if the market moves in their favour. I wouldn't mind extensions if the pricing was recalculated.

**Comment by RainbowMiner** [comment]
That is not possible, unfortunately. MiningRigRentals does not allow to update the pricing of a rental, as soon as it has started. Meaning, if a renter buys an extension, he will always get the pricing from the start of the rental. I will discuss this matter with merc at MiningRigRentals. Maybe they can unlock this for us.

**Comment by acos0874** [comment]
Ok thanks for looking into it. I suspect they may want to protect their renters since I'm fairly certain this may be the only reason they make rentals in the first place. 

The only other relevant thing I can think of is if I made some adjustments to the automatic pricing. If I understand correcly the MRR automatically changes the price based on market conditions that way but I'll need to check that.

**Comment by RainbowMiner** [comment]
Ok, I have an answer - an extension already uses the current price of the rig and not the price from the start. The only thing, that is not changeable is the hashrate.
So I can implement that rental extension premium feature.

**Comment by samdave123** [comment]
@RainbowMiner It does? I'm sure it didn't last time I checked this. My rentals were often underpriced compared to current market conditions.

**Comment by RainbowMiner** [comment]
This is the official answer of merc from MiningRigRentals:
> Rental extensions occur at the rigs current price, it does not use the rentals original price

**Comment by RainbowMiner** [comment]
I'll have a close look on the current rentals and their extensions to verify this.

**Comment by acos0874** [comment]
On the topic of underpriced rentals, I keep getting one rig that seems to be suffering from bad pricing. Would you mind having a look please?
[debug_2022-03-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/8322272/debug_2022-03-22.zip)

**Comment by RainbowMiner** [comment]
- add parameter "PriceRiseExtensionPercent" to pools.config.txt and mrr.config.txt: enter price rise for extensions of a rental (in percent, e.g. 10 means 10% price rise) [default=0]

**Comment by acos0874** [comment]
Thanks. Please can you confirm the pricing is correct for my rig here. It's actually the same on more than one rig.

![image](https://user-images.githubusercontent.com/42582444/159649138-ab40602a-4ac4-4bcb-baf8-78f8e7d97859.png)

When I check the logs it appears only one algorithm is being updated.

![image](https://user-images.githubusercontent.com/42582444/159649255-027809b0-02a0-4e22-9683-e2edd7f7df5f.png)

**Comment by RainbowMiner** [comment]
> Thanks. Please can you confirm the pricing is correct for my rig here. It's actually the same on more than one rig. Nicehash is normally around 0.00091 btc/gh/day so the minimum here strikes me as odd.

Could you please upload the `.\Stats\MRR\emily.txt` file and all `.\Stats\Profit-*.txt` files found on that machine?

> When I check the logs it appears only one algorithm is being updated.

RainbowMiner updates rigs, that have changed price and/or hashrate, only.

**Comment by acos0874** [comment]
Shouldn't the minimum price be updating itself if I know the current rate
is around 20% higher than the one shown in the screenshot? My understanding
is that mrr controls the suggested pricing but mrr controls the minimum. It
looks to me that the minimum price isn't being updated from the
0.00077btc/gh/day to the higher value. I'll upload the log files when I
get home tonight. With energy prices going up I had to get a job 😆

**Comment by acos0874** [comment]
I was about to upload the debug file but I realised it occurs on the rig where I have different device groups listed as a single rental. My hypothesis is that this is causing incorrect pricing, so I'm switching to separate MRR listings to see if it fixes it.
