### ISSUE TITLE
Simplify the Changelog on Release Page 

### ISSUE THREAD

**Issue by cleanerspam** [RainbowMiner/RainbowMiner#2009]
Changelog contains too much content 
I feel everything from Hints for Networking is redundant and that information should be either jn Readme or any other wiki or guide not in Release page

**Comment by RainbowMiner** [comment]
I totally agree. The info will be moved and linked.

**Comment by cleanerspam** [comment]
It could be more simplified by making columns like
Miner.                      |       Core.               | Pools

Extra = Documentation ,Guides etc
