### ISSUE TITLE
"ZpoolCoins.ps1" loading error + simple fix --version-- RainbowMinerV4.8.2.2_win

### ISSUE THREAD

**Issue by Haarlow1372** [RainbowMiner/RainbowMiner#2010]
---ERROR---

.. loading ZpoolCoins ZpoolCoins.ps1: Cannot bind parameter because parameter 'DataWindow' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".

---FIX---

   (Remove) "[String]$DataWindow = "estimate_current"," from "ZpoolCoins.ps1"

**Comment by RainbowMiner** [comment]
Actually, there might something wrong with your pools.config.txt - would you please upload a Debug file, so that I can check this? Just click "Debug file" on http://localhost:4000 (left-hand side).

**Comment by Haarlow1372** [comment]
[debug_2022-03-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/8324839/debug_2022-03-22.zip)
