### ISSUE TITLE
PriceFactor by algo

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2013]
Could it be possible to implement a PriceFactor by algorithm for MRR. There is MRRPriceModifierPercent in algorithms.config.json but it is limited to max 30%.

Thanks for your work ;)

**Comment by RainbowMiner** [comment]
This enhancement is tempting. Not easy to implement, though. I will add this.

**Comment by astitsa** [comment]
Thank you very much once again ! There are people that want to pay way more for renting some algo ;)

**Comment by RainbowMiner** [comment]
Ok, done. It's part of the release v4.8.2.5

**Comment by RainbowMiner** [comment]
A note: I have moved all "MRRxxx" parameters from the algorithms.config.txt to the new config file mrralgorithms.config.txt (also, I have removed the leading MRR from the names). If you do an update, the cleanup-script should automatically copy over all your "MRRxxx" parameters to the corresponding "xxx" during the first start of the new version.

**Comment by astitsa** [comment]
Amazing work once again sir !
