### ISSUE TITLE
MiniZ Etchash benchmarking pool broken?

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#2016]
I was unable to bench MiniZ Etchash until setting a different pool. Can you check this please?

**Comment by samdave123** [comment]
Perhaps you could add failover non-donation pools for benchmarking if your pools don't work?

**Comment by RainbowMiner** [comment]
I'll check this.

**Comment by RainbowMiner** [comment]
In fact, there has been a bug in the MiniZ miner module. It should be fixed with the last commit

**Comment by RainbowMiner** [comment]
Even more - it seems, that the ethermine etc stratums do in fact fail to accept shares from time to time. I have switched to 2Miners for ETC from now on.

**Comment by samdave123** [comment]
Would you be able to add failover/multiple pools for benchmarking to improve benchmarking reliability going forwards?

**Comment by samdave123** [comment]
Or would this just make benchmarking take too long?
