### ISSUE TITLE
Wrong wallet address

### ISSUE THREAD

**Issue by Nc2meu2** [RainbowMiner/RainbowMiner#2017]
Some how RBM is paying to wrong Firo Wallet. Can you help. Should I remove the address?

**Comment by RainbowMiner** [comment]
Could you please explain a bit more what is happening? Also, please upload a Debug file (open http://localhost:4000 and click "Debug file" on the left hand side).

**Comment by Nc2meu2** [comment]
It's all good. I'm new to this and didn't realize that if you download an entire block chain (firo QT wallet) of any wallet, it may give you different addresses for transactions. That's what I did and I was confused for a while.
