### ISSUE TITLE
Disable cryptodredge25 for a4000

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2018]
It’s my understanding that cd25 doesn’t support 30 series cards. 

My a4000 on a crashing loop.

**Comment by RainbowMiner** [comment]
In fact, it doesn't. It's most probably, because A4000 isn't detected as 30 series. I'll handle this.

**Comment by RainbowMiner** [comment]
Ok, that should be solved with the last two commits.
