### ISSUE TITLE
Enhancement: Show rainbow miner version at all times

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#202]
I know it is a small request. However, when I use the auto update feature, I honestly have no idea what version it is running. There has been several times were the app will not auto update and I have to manually do it. I can tell that it is auto updating properly when I notice the minimized window is now maximized. Would just be nice at the very top above CPU mining stat to just state what version is running at all times. Even when I update, using an older config file does not update the new version being used in the first line. Ultimately I'm left to guess or have to shut down and restart rainbow to see.

![image](https://user-images.githubusercontent.com/42227809/46589224-65e35780-ca5c-11e8-9fbe-313e52bf1af9.png)

**Comment by RainbowMiner** [comment]
Good idea. I will add a headline.

**Comment by RainbowMiner** [comment]
I changed the powershell console title directly. This should do the job:
![image](https://user-images.githubusercontent.com/39437538/46601654-0c2b6d80-caee-11e8-85b6-f6acb673112b.png)

Will be part of the next release (or use master.zip)
