### ISSUE TITLE
Nanopool password parameter not being passed?

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#2020]
Nanopool requires a password or email address in the password field of the miner launch string in order to change minimum payout settings for CFX.  A valid email is only required if you want notifications, otherwise it can be any password with a minimum length of 6 characters.

It looks to me like RBM isn't passing the password to Nanopool in either Trex, NBMiner or Nanominer.  The launch string for either Trex or NBminer passes the parameter "-p x" regardless of what is set in the "Email" or "CFX-Params" fields in the Setup Pools settings for Nanopool.  The Nanominer configuration .txt file has a warning from RBM not to edit it.  I edited it anyway as a workaround and it worked to change the minimum payout after I had built up the required 10 rating at Nanopool while mining under the edited Nanominer config.

Would you please take a look at this when you have a chance?  Thanks.

**Comment by RainbowMiner** [comment]
Ok, thank you for pointing this out. I have just updated the Nanopool module, so that the value of "xxx-Params" (if it's not empty, of course) will be sent instead of the "x".
