### ISSUE TITLE
Zergpool added TLS/SSL support today

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#2021]
The Zergpool admin wrote today on Discord:

"Happy to announce that we are adding TLS/SSL support also for all mining ports. All regular mining ports have its sibling now, which starts with 1. As example for sha256, TLS/SSL mining port is 13333. Happy mining, and please report if some of ports does not work for you in TLS mode."

It looks to me like RBM thinks Zergpool doesn't support SSL (apparently accurate until today) and acts accordingly, even if RBM's "SSL - Enable use SSL stratum connection, if available" field for Zergpool is set to "enabled".  It would be great if RBM could update the Zergpool settings accordingly and it sounds like it would be fairly simple to do because of the way Zergpool implemented this by simply prepending "1" to the old port number for the new SSL port.  Man-in-the-middle hacks may or may not be uncommon, but nearly every other crypto hack seems to have been done with some regularity, so I think it is worth using SSL when possible.  Thanks!

**Comment by coolbreeze21** [comment]
Zpool also announced SSL/TLS support a few days ago: 

"! zpool.ca | crackers: In an effort to fight back the oppression some miners are experiencing from their governments and ISP's we've enabled SSL/TLS mining on ALL algorithms. To utilize SSL, simply prepend the standard port with a 5. Please ensure your miner supports SSL/TLS prior to making changes. Example with curve using SRBminer:

SRBMiner-MULTI --disable-gpu --algorithm curvehash --pool mine.zpool.ca:54633 --tls true --wallet donate"

Zpool may also have a self signed SSL certificate, but it looks like you have already done the hard work to figure out how to deal with that.  Please add support for SSL/TLS on Zpool.  Thank you for the work on Zergpool, MoneroOcean and C3Pool.  Clearly it was more work to deal with the self signed SSL certificates than simply prepending a digit to the port number.

**Comment by RainbowMiner** [comment]
Nice! Thank you for the information. Our ZPool modules now support SSL.
