### ISSUE TITLE
Nanominer/MoneroOcean benchmark SSL error

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#2025]
The 4.8.2.7 update generates a flood of the following errors when trying to benchmark Nanominer 3.6.0 on MoneroOcean:

"Failed to verify SSL certificate against the host gulf.moneroocean.stream. Trying to use unsecure connection."

As a result, the NanoMiner benchmarks for VerusHash and Autolykos fail and I think the one for RandomX is questionable.

**Comment by RainbowMiner** [comment]
Oh dear! Thank you for the report. I'll see, if we can disable the Nanominer SSL checks.

**Comment by coolbreeze21** [comment]
It looks to me like Nanominer isn't connecting to MoneroOcean at all when it tries to use SSL.  Possibly a mismatch when trying to verify the certificate?  If nothing else, Nanominer could be told not to use SSL when connecting to MO.  The old non-SSL MO ports are still available.  Plus, I don't think I ever saw Nanominer be the best miner on anything, but maybe 3.6.0 is an improvement.

**Comment by RainbowMiner** [comment]
In fact the MoneroOcean SSL certificate is foul. I have disabled SSL for Nanominer, in case of pool is MoneroOcean

**Comment by coolbreeze21** [comment]
If the MoneroOcean SSL certificate is bad, should you be disabling SSL for MO for all miners?  There is a user named Oleg reporting XMrig also isn't working on the Discord MO support channel.  Admin !pinpin said "will check soon" two hours ago, but nothing since then.  If you have a contact with !pinipin, you might want to alert him to what you found out about the issue.  I would have thought Zergpool would have checked their certificate before rolling this out :(

**Comment by coolbreeze21** [comment]
Nanominer generates the same error on Zergpool and C3Pool.  I would guess that they use self signed SSL certificates like MoneroOcean.  Nanominer apparently doesn't like that.

**Comment by RainbowMiner** [comment]
Thanks for reporting this back. I'll try to find a way to handle those SSL certificates.

**Comment by RainbowMiner** [comment]
Yes, I agree. Maybe I add another SSL option to explicitly allow self signed certificates.
