### ISSUE TITLE
Crazypool: WARNING: No pools available: check your configuration

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#2026]
@RainbowMiner, is there something changed for Crazypool? I set config to the pool and script says "WARNING: No pools available: check your configuration"

**Comment by RainbowMiner** [comment]
Crazypool is working just normal. Which currency did you enable on that pool? ETH, ETC or UBQ?

**Comment by astronyu** [comment]
In pools.config.txt 

`"Crazypool": {
    "ETH": "",
    "ETH-Params": "",
    "ETC": "",
    "ETC-Params": "",
    "UBQ": "",
    "UBQ-Params": "",
    "Worker": "$WorkerName",
    "Penalty": "0",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "0",
    "CoinSymbolPBM": "",
    "DataWindow": "",
    "StatAverage": "",
    "StatAverageStable": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "",
    "MaxAllowedLuck": "",
    "MaxTimeSinceLastBlock": "",
    "Region": "",
    "SSL": "",
    "BalancesKeepAlive": "",
    "MaxTimeToFind": ""`

**Comment by RainbowMiner** [comment]
Yes, add your ETH, ETC or UBQ wallet to the params. If you have defined the wallet addresses in coins.config.txt, you can use variables.
Example for ETH

Without variables:

**Comment by astronyu** [comment]
Thanks. 

Now its giving me access denied, RBM was run as admin.

> WARNING: Could not execute .\Includes\getcpu\GetCPU.exe : Exception calling "Start" with "0" argument(s): "Access is denied."
> Finished waiting - starting next run                                                                                                              
> WARNING: Failed to apply OC for Trex-GPU#00)!
> WARNING: Failed to apply OC for Trex-GPU#00)!
