### ISSUE TITLE
Unprofitable list blocking profitable PulsarCoin (PLSR, curvehash)

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#2027]
The unprofitable list(s) are blocking Pulsarcoin (PLSR).  It appears to me that this is due to a blanket block of its algo, curvehash.  Another curvehash coin, CURVE, may or may not be problematic, but PLSR does not appear to be.  It is one of the most profitable CPU-mineable coins currently and has been for the past month.

Please take a look at whether it is possible to remove PLSR/curvehash from the unprofitable list(s).  It is a pain to have to disable the lists and tolerate the benchmarking of a bunch of truly unprofitable algos/coins in order to get PLSR back.  There are lamentably few profitable CPU coins as it is without excluding PLSR. 

A somewhat related matter is that disabling the unprofitable lists generates many errors of the form "wrong url stratum+ssl://neoscrypt.mine.zergpool.com:14233" when trying to benchmark on Zergpool using SSL, which requires disabling SSL on Zergpool to work around. 

Thanks to user Papadrams on the RainbowMiner Discord for the tip about PLSR.

**Comment by RainbowMiner** [comment]
Thank you! I have removed Curvehash from the unprofitable list. Your RainbowMiner instance should pick this up. 
Regarding the SSL problems - I am already on the way to find how to deal with self signed certificates. Some miners do fail with those.
