### ISSUE TITLE
Remove miner CcminerXaya

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2029]
CcminerXaya is faster than your self compiled CcminerKlausT on my GTX1660Super

CcminerXaya: 834.58 kH/s, intensity 21
CcminerKlausT: 816.38 kH/s, intensity 15.5

Same Driver & OC settings

**Comment by RainbowMiner** [comment]
Did you try higher intensity with the CcminerKlausT? Or is the 15.5 the highest possible value for stable operation already?

**Comment by RainbowMiner** [comment]
I have re-added the miner - as long as there are GPU / driver combinations that run faster with this module, we keep it.

**Comment by UselessGuru** [comment]
> Or is the 15.5 the highest possible value for stable operation already?

Yes, this is the highest possible intensity in my case.

**Comment by RainbowMiner** [comment]
Thank you for the feedback. Better we keep the CcminerXaya, then.
