### ISSUE TITLE
RainbowMiner v3.8.8.17 and WildRig Multi

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#203]
Benchmarking didn't work for me out of the box because I'm using a Hawaii card and you must download that bin separately.  I can't remember from the initial setup, is there a way to benchmark a miner only?

**Comment by jch9678** [comment]
I just deleted the stats for WildRig.  I'll see if the additional bins work.

**Comment by RainbowMiner** [comment]
Yes, you did the right thing. Deleting the stats of one miner, starts the benchmark. Did it work with the additional bin? Since I do not have AMD cards, I am very interested in your results.

**Comment by jch9678** [comment]
No they didn't work but I think it's because they are missing the --opencl-threads  --opencl-launch parameters.  I should have some time to play around with it tonight ( in a few hours ).  I'll let you know my benchmarks for all the algos though they will not be optimized.

**Comment by RainbowMiner** [comment]
Super! Thanks a lot. These are the possible defaults (MainAlgorithm contains the name of the algo, Params coin default values). If those would work, I would include them directly into the miners file.
```
        "WildRig" = [PSCustomObject[]]@(
            [PSCustomObject]@{MainAlgorithm = "bcd"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 512x128"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "c11"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 128x128"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "geek"; SecondaryAlgorithm = ""; Params = "--opencl-threads 2 --opencl-launch 1024x128"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "hmq1725"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 1024x128"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "phi"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 256x128"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "renesis"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 2048x128"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "sonoa"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 512x0"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "timetravel"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 512x128"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "tribus"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 2048x0"; OCprofile = ""; MSIAprofile = ""}
            [PSCustomObject]@{MainAlgorithm = "x16r"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 512x128"; OCprofile = ""; MSIAprofile = "4"}
            [PSCustomObject]@{MainAlgorithm = "x16s"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 512x128"; OCprofile = ""; MSIAprofile = "4"}
            [PSCustomObject]@{MainAlgorithm = "x17"; SecondaryAlgorithm = ""; Params = "--opencl-threads 3 --opencl-launch 1024x0"; OCprofile = ""; MSIAprofile = ""}
        )
```

**Comment by RainbowMiner** [comment]
Would you also please send me your Config\devices.config.txt ? I then can easily build in an automatic download of the alternative binaries.

**Comment by RainbowMiner** [comment]
I have updated the miner file Miners\Wildrig.ps1 to include those defaults. If you like, you can give this a try to start with the parameters. To override, simply add your parameters to Config\miners.config.txt.
Here it is: [WildRig.zip](https://github.com/RainbowMiner/RainbowMiner/files/2460045/WildRig.zip) downlaod and extract into folder Miners, overwriting the old file.

**Comment by jch9678** [comment]
I didn't have time to mess around with it last night so I was about to throw your defaults in there and see what happens.  However I noticed that your --opencl-launch are significantly different than what's on the first page:
First set is for a 460 and the second set is for a 570/580

bcd | --opencl-threads 3 --opencl-launch 19x128 | --opencl-threads 3 --opencl-launch 19x128
c11 | --opencl-threads 3 --opencl-launch 17x128 | --opencl-threads 3 --opencl-launch 17x128
geek | --opencl-threads 2 --opencl-launch 18x128 | --opencl-threads 2 --opencl-launch 20x128
hmq1725 | --opencl-threads 3 --opencl-launch 18x128 | --opencl-threads 3 --opencl-launch 20x128
phi | --opencl-threads 3 --opencl-launch 18x128 | --opencl-threads 3 --opencl-launch 18x128
renesis | --opencl-threads 3 --opencl-launch 21x128 | --opencl-threads 3 --opencl-launch 21x128
sonoa | --opencl-threads 3 --opencl-launch 19x128 | --opencl-threads 3 --opencl-launch 19x0
timetravel | --opencl-threads 3 --opencl-launch 18x128 | --opencl-threads 3 --opencl-launch 19x128
tribus | --opencl-threads 3 --opencl-launch 20x0 | --opencl-threads 3 --opencl-launch 21x0
x16s, x16r | --opencl-threads 3 --opencl-launch 18x128 | --opencl-threads 3 --opencl-launch 19x128
x17 | --opencl-threads 3 --opencl-launch 20x0 | --opencl-threads 3 --opencl-launch 20x0

I'm going to put the 570/580 parameters in the miners.config.txt and see what happens.

**Comment by jch9678** [comment]
Whoops just saw your post above mine.  Am I not editing configs correctly by editing the miners.config.txt ?

**Comment by RainbowMiner** [comment]
You are totally correct by editing miners.config.txt. The parameters in there count (and override any defaults)

**Comment by jch9678** [comment]
Miner                    Fee Algorithm           
-----                    --- ---------           ----- 
ClaymoreCryptonight CryptoNightV7 683.01  H/s   (SRBMiner is faster 840h/s but benchmarking failed)
Phoenix                0.65% Ethash         20.96 MH/s    (Slow, probably need blockchain drivers ~27.5mh/s)
WildRig                1.00% X16R            6.22 MH/s
WildRig                1.00% HMQ1725         2.56 MH/s
WildRig                1.00% X17             4.41 MH/s
SgminerBitcore         1.00% Bitcore         7.50 MH/s
WildRig                1.00% SonoA         700.18 KH/s
WildRig                1.00% C11             6.46 MH/s
WildRig                1.00% X16S            4.43 MH/s
ClaymoreEquihashAmd    2.00% Equihash      314.00  H/s
Sgminer                1.00% Lyra2RE2       11.60 MH/s
WildRig                1.00% Timetravel     12.58 MH/s
WildRig                1.00% PHI             5.41 MH/s
SgminerXevan           1.00% Xevan         702.63 KH/s
SgminerLyra2z          1.00% Lyra2z        395.05 KH/s
WildRig                1.00% Tribus         23.64 MH/s
Sgminer                1.00% Yescrypt      300.00  H/s

Here are my benchmarking scores for a non-reference 290x that has a failing water block on it.  My reference 290x are usually better clock for clock.
Keep in mind these are using default parameters by RainbowMiner and the parameters for a 570/580 for WildRig.  I'm confident it can perform much better.

**Comment by RainbowMiner** [comment]
Thank you very much, for your results. So, adding the fixed defaults make the miner benchmark. I will add them for the future.

**Comment by RainbowMiner** [comment]
What I am still very interested in, is your devices.config.txt - would you be so kind and drop them here?

**Comment by jch9678** [comment]
[devices.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2469329/devices.config.txt)

Here you go, though it appears to be empty.

**Comment by RainbowMiner** [comment]
Super :) Thank you very much. I have been interested in the nametag of your GPU (Hawaii).
