### ISSUE TITLE
DEV FEE not as advertised

### ISSUE THREAD

**Issue by CadenceMTk** [RainbowMiner/RainbowMiner#2030]
new user here, i may be wrong but  dev fee supposed ot be 10 minutes a day i have been getting 17-20 minutes a day in mining for dev. is there something im doing wrong.. its been 3 days and most of it was benchmarking and sorting out unstable miner/algo pairs.

**Comment by RainbowMiner** [comment]
Please have a look into the config.txt and check if parameter Donate is set to 10. I suspect it's at 20 (it's the value in minutes the donation round will take per day).
```
  "Donate": 10,
```

> its been 3 days and most of it was benchmarking and sorting out unstable miner/algo pairs.

In fact the benchmark can take a long time, depending on your rig. We would have had a shortcut here: next time, just set parameter `"EnableFastlaneBenchmark": "1",` in config.txt. Rainbowminer will then try to download a set of benchmark results that comes close to your rig's performance. It's not really accurate, but will give you a quick start. In fact, the hashrates will then adjust themselves overtime.

**Comment by RainbowMiner** [comment]
Also a hint: if your benchmarks are ready, always keep a fresh backup of your benchmarks. Just add the contents of folder `.\Stats\Miners` to a zip archive and store it away.

**Comment by CadenceMTk** [comment]
thank you so much! i have 2.5gh farm will be deploying this on more rigs. ill set to 15mins for now. if my profit goes up vs steady mining ill donate more still too early to tell.

side question, does your 2minersae pool settings do etc yet? they just added ae to btc on that coin recently..

**Comment by RainbowMiner** [comment]
> side question, does your 2minersae pool settings do etc yet? they just added ae to btc on that coin recently..

Thank you for the information! I'll add it at once.

**Comment by Nc2meu2** [comment]
> Also a hint: if your benchmarks are ready, always keep a fresh backup of your benchmarks. Just add the contents of folder `.\Stats\Miners` to a zip archive and store it away.

Could you post this info on the main instructions?
I didn't find them while reading. Or please point me to this part on the installation instructions. Thank you.
