### ISSUE TITLE
profit calculation

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2031]
It looks like there is an profit calculation error for cuckaroo30 algo using gminer with herominers pool. It says 100+ usd a day for a single 3090 but more a 4 usd on pool

**Comment by RainbowMiner** [comment]
Uh! That's a lot. I'll check it. Please disable it for now, just to be sure.

**Comment by astitsa** [comment]
Poolmining with heorominers pool and the hashrate is 4.85 h/s to 6.62 h/s on 3080 & 3090

**Comment by RainbowMiner** [comment]
Ok, got it. I have fixed the reward calculation. Please remove the pool's stat file now: `.\Stats\Pools\HeroMiners_CTXC_Profit.txt`

**Comment by astitsa** [comment]
Thanks !
