### ISSUE TITLE
SgminerFancyIX.ps1 issues

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2035]
Hallo,
i own 2xRX480 and sgminerfancy was always failing the benchmarks. After a little digging, i ended up reconfiguring the whole .ps1 file and finally got it working. I can't pinpoint exactly to what was the issue, but it now works. I am attaching my new .ps1 file that works.

Also another problem on that miner is that you have a typo on the .ps1 file. 
 [PSCustomObject]@{MainAlgorithm = "neoscrypt-xa**j**a"; Params = "--gpu-threads 1 --worksize 256 -I 17"}
(In the attached file i have already corrected it)
This issue was brought to my attention by ondalf on zpool discord server.
[1.txt](https://github.com/RainbowMiner/RainbowMiner/files/8426559/1.txt)

*(couldnt upload the .ps1 file so i made it into .txt.)

**Comment by RainbowMiner** [comment]
Ha, that's interesting. Basically, you did only remove the ExcludePoolName="Nicehash" (and fixed that typo).
Is it, that you are using this miner on Nicehash?

**Comment by RainbowMiner** [comment]
Could you please create a Debug file and upload it here?

**Comment by papadrams** [comment]
I removed nicehash cause i couldnt pinpoint the issue. So i did multiple things and tried after and it worked. i dont know what exactly made it work. I also deleted the linux quotes. But when i edited that .ps1 it was different. 
It had that line as well: 
$Miner_Device = $Device | Where-Object {($_.Model -notmatch "^RX[56]\d\d\d" -and $MainAlgorithm -eq $_.MainAlgorithm) -or ($_.Model -match "^RX[56]\d\d\d" -and $MainAlgorithm -ne $_.MainAlgorithm)}
