### ISSUE TITLE
please add solo mining functionality to prohashing

### ISSUE THREAD

**Issue by CadenceMTk** [RainbowMiner/RainbowMiner#2038]
cant find a way to get prohashing to mine solo in the local dashboard interface.

**Comment by RainbowMiner** [comment]
I will have a look into it.

**Comment by RainbowMiner** [comment]
Found it: it is already implemented into pool module "ProHashingCoins" - to enable solo mining, add "@solo" to the end of you username in pools.config.txt.
```
  "User": "itsme@solo",
```

Hint: with this "@" parameter, you are able to control the payout scheme at ProHashing.
- "@pps" : use pay-per-share payout scheme
- "@pplns" : use pay-per-last-N-shares payout scheme
- "@solo" : use solo mining

**Comment by CadenceMTk** [comment]
does this mean it will only solo mine? or will it benchmark and switch depending on whats better?

**Comment by RainbowMiner** [comment]
> does this mean it will only solo mine?

Yes

> should i create a custom "prohashing solo" pool like you did for zerg?

I'll add it for you :)
