### ISSUE TITLE
please add VIABTC pool with AE to RBMiner pool list

### ISSUE THREAD

**Issue by CadenceMTk** [RainbowMiner/RainbowMiner#2039]
this pool is ranking top 5 in minerstat and has many coins to min and all can be auto exchanged to BTC ..
love the platform

**Comment by RainbowMiner** [comment]
Sure, I will add it asap.

**Comment by RainbowMiner** [comment]
Ok, added.

**Comment by CadenceMTk** [comment]
thank you sir, one side ask... i have 7 rigs: on unmineable, how can i disable rbminer default referral code, i would like to add my own please.

**Comment by RainbowMiner** [comment]
I will add a parameter substitution to the unMineable pool module, so that it can be changed.

**Comment by RainbowMiner** [comment]
Ok, I have updated the unMineable pool module for you:
- add possiblity to add own referals to the command line. Just use the "COINSYMBOL-Params" parameter in pools.config.txt. 
  e.g. if you want to add your referal code to MATIC (is _must_ be of the correct 4-letter/numbers + minus + 4-letter/numbers)
```
    "MATIC": "$MATIC",
    "MATIC-Params": "a2bc-efg8",
```
