### ISSUE TITLE
Zergpool warning

### ISSUE THREAD

**Issue by Nc2meu2** [RainbowMiner/RainbowMiner#2044]
Hello, I was wondering why I wasn't getting paid from zergpool if the threshold had been reached and so I went to the website and got this ![image](https://user-images.githubusercontent.com/101607809/163657838-340bb503-423c-4783-92a1-868202ccb808.jpeg)

Could someone help me please

**Comment by papadrams** [comment]
This has nothing to do with Rainbowminer.
You should go to zergpool discord and ask for support
Here is the zergpool discord server: https://discord.gg/FxFZgXBF

**Comment by papadrams** [comment]
The easiest way to sort it out is on their discord server. Thats why i sent you the link.
Or if you dont want to click the link i sent you, go to zergpool.com and at the top right corner there is a discord icon. Press it to join their discord and get support.

**Comment by UselessGuru** [comment]
> You should go to zergpool discord

Exactly.
Unless ZergPool somehow makes this information available in their API (which currently is not the case) Rainbow miners (and all similar software that relies on the pools API) can do anything about this.

**Comment by Nc2meu2** [comment]
I saw your link and I used it. Thank you. I'll be reading and posting there until I get a response..or directions to resolve this issue.

**Comment by Nc2meu2** [comment]
Thank you everyone. Zergpool resolved my issue.

**Comment by RainbowMiner** [comment]
Perfect! I am happy to hear that.
