### ISSUE TITLE
MRR balance missing 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2046]
My MRR balance is missing and my rigs believe my earnings to be far less than they are

**Comment by astitsa** [comment]
I have the same problem on a server clien setup where one of my rig is not showing MRR balance

**Comment by astitsa** [comment]
Is it just me and Nickfrost having this issue ?

**Comment by RainbowMiner** [comment]
Hi, I cannot replicate that problem on my machines. So it's only one client of many that doesn't display the balance? Could you please create and upload a Debug file of this one specific machine? Just open http://localhost:4000 (or http://<machineip>:4000) and click "Debug file".

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
