### ISSUE TITLE
Allow me to turn off each Notification type

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2047]
Allow me to turn off each notification type

I just want offline alerts, i know they are hot, i know the crash, i dont care, i just need to know went they need physically rebooted. 

each additional notification type is clogging my emails inbox

**Comment by acos0874** [comment]
Both are possible in the config files....
  "MinerStatusMaxTemp": "82",
  "MinerStatusMaxCrashesPerHour": "1",
Change both to a larger artbitrary number.

**Comment by RainbowMiner** [comment]
No problem! It is on the list, now.

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
