### ISSUE TITLE
Make config wizard standalone for editing server configs

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2048]
Make config wizard standalone for editing server configs

Yo 

So our config editor wizard is the best way to edit configs, but i am using a server config and have like 4 groups/configs all doing different things if i could run a standalone config editor that understood all my config folders that'd be great. 

TY

**Comment by RainbowMiner** [comment]
Yes, very good idea. I will find a way to implement it.

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
