### ISSUE TITLE
No Method Named 'op_Addition'

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#205]
On my one nvidia machine I get this error:

Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
At C:\Users\yyyy\Desktop\RainbowMiner\Include.psm1:178 char:5
+     $Balances += $Totals
+     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
At C:\Users\yyyy\Desktop\RainbowMiner\Include.psm1:178 char:5
+     $Balances += $Totals
+     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

INFO: Loading saved statistics.

**Comment by RainbowMiner** [comment]
Oh! Which version are you running? The actual master or the latest release? I will check this.

**Comment by RainbowMiner** [comment]
Also, would you be so kind and send me your current config.txt and latest logs?
When did this error occur?

**Comment by jch9678** [comment]
I believe it started on the first install and setup with 3.8.8.6 and has stuck around.  
How would you like me to send the logs?

**Comment by RainbowMiner** [comment]
Just drag and drop the config.txt to here. I believe it may be a problem with a pools balance. So I am interested in which pools you are using. The logs are best as zipped folder.

**Comment by RainbowMiner** [comment]
Good, I found and fixed the problem. Next release will contain this fix.

**Comment by jch9678** [comment]
Great, let me know if you still need my config.txt

**Comment by RainbowMiner** [comment]
> Great, let me know if you still need my config.txt

I don't need it anymore, since the problem is solved :)
