### ISSUE TITLE
need to run CPU miners in administrator mode to enable MSR

### ISSUE THREAD

**Issue by CadenceMTk** [RainbowMiner/RainbowMiner#2055]
please let me know how to enable to run the CPU miners in admin mode to enable MSR .. I'm getting low hash rates also not all the threads are being used even when i put in threads in config file.

i have a few multi-CPU servers to CPU/chia mine, and have upgraded all the GPU rigs with higher performance CPU's and RAM to take advantage of CPU mining. 

2 issues:

1. I have no control over how many threads are being used or CPU affinity that I can see. (config file does no difference)

2. The cpu miners need to be run in admin mode in order to enable MSR which gives much more hash rates. ( I have all notifications off so everything can run in admin mode with no stopping to ask)

please help sir.

**Comment by RainbowMiner** [comment]
Just start Rainbowminer as Administrator (in Admin mode), then all miners will be started elevated.

Regarding the affinity: you will have to set affinity and threads to make it work. For example:

```
    "CPUMiningThreads": 14,
    "CPUMiningAffinity": "0xFFFC",
```

**Comment by CadenceMTk** [comment]
i manually run the rbminer in admin mode.. but upon a reset , i have it set to run on startup folder.. and it wont execute if i set the shortcut to run in admin mode. the only way it will execute on start up is if i turn off the run as admin setting.. any advise on how to fix this would be great.

furthermore the threads in the main config file have no bearing on the cpu miners they all run with 2 threads only and im not sure they are picking up the affinity either.. i dont see the threads or affinity arguments in the command line in the shell window.. i would very much like to set the threads and affinity in the main config and have it apply to all cpu miners on the next round, im going through a bunch of benchmarking trying to find out the best settings. 

i also get "end of file" errors and the hash seems to drop from 1500h/s to 125h/s i cant seem to get a consistent hash rate ...  im working on my i7 cpu's they are 4 core 8 thread just want to get a consistent hash from them as they seem to be able to profit .15-.30 cents a day on BTM coin. that adds up with 12 rigs.  please look at the module that spits out those config files for xmrig specifically for take2 algo seems to use ghostrider settings.

**Comment by RainbowMiner** [comment]
- Here is an instruction on how to add RainbowMiner to Window's system start using task manager. This way, RainbowMiner will start with elevated privileges (as Admin): https://github.com/RainbowMiner/RainbowMiner#how-do-i-add-rainbowminers-startbat-to-the-windows-task-sheduler-for-autostart
- so we are talking about the Take2/Ghostrider algorithm, right? In fact, this is a different beast.
  - first, Take2 and Ghostrider are the same algorithm. It consists of a collection of different other sub-algorithms, which will be executed in random order. This explains the different hashrates and CPU loads over time. The hashrate be very low at one moment and very much higher on the other moment. RainbowMiner uses a moving average algorithm to smoothen the graph.
  - second, Xmrig has a build-in optimization for Take2/Ghostrider algorithm, that will adapt automatically to each sub-algorithm combination thus totally ignoring the thread/affinity setting. The only parameter xmrig respects is the `max-threads-hint`. It defaults to 50 (=50%) and can be changed manually in `.\Bin\ANY-Xmrig\config_Take2_1xYourCPUsName_0xFE_7.json`. The value can range between 1 and 100 (=100% load allowed)

    The name of the config file is a "_"-concatenation of the following values: "config_algorithm_1xYourCPUsName_affinity_threads.json"
    - "config" to mark this file as config file
    - "algorithm" (e.g. Take2)
    - "1xYourCPUsName" for CPU it's always "1x", even if there are multiple CPUs. "YourCPUsName" will be something like "IntelCorei7..."
    - "affinity" the affinity defined in "config.txt" (e.g. 0xFE)
    - "threads" the number of threads defined in "config.txt" (e.g 7)
