### ISSUE TITLE
New MiniZ Freezing 3070 Heavy Machines

### ISSUE THREAD

**Issue by bwstandard** [RainbowMiner/RainbowMiner#2058]
I have two machines with 5+ 3070 and when MiniZ goes through to run FLUX it will freeze those machines, I have had to turn off the miner. 

After doing many tests including dropping power, etc it still freezes. 

On my other machines, with 4 and less, there is no issue. 

Anyone else having issues on these? Pretty sure I'm just pulling too much power on these and killing the system.

**Comment by RainbowMiner** [comment]
I am unsure - can you confirm, that there weren't such problems with the old miniZ version? Currently, I am evaluation the new miniZ regarding speed and for now it looks like, the old version is a little bit faster on most algorithms. At least on my rigs. I'll wait for more feedback, before I decide if it would be better to fallback to the prior miniZ.

**Comment by bwstandard** [comment]
I have had no issues up until the switch a few days ago, I'm not necessarily sure that I was running it regularly, but I did get through benches and what not without an issue. Currently I have had to turn if off on my machines as mentioned that are running more than 4 3070, which is only 2. The rest of my machines that do not have that many are having no issues with the client. 

I did not change my OC between the timeframes either. After the freezing I did, trying to remedy going from 80PL to 65PL and still having issues. I just turned off the miners on those rigs for now.

**Comment by RainbowMiner** [comment]
Ok, thank you for the feedback. I have just decided to revert back to the old version, after I could in fact provoke a hang on one of my larger rigs.

**Comment by bwstandard** [comment]
Ok, so in that case, being that I'm mildly new to your system, which is pretty nice btw, are you pushing that and it will automagically set up and I should re-enable the miner at some point? 

Thanks for being on it.

**Comment by RainbowMiner** [comment]
Yes, I will push a new release within the next hour. Your system should update automatically to v4.8.3.7 - after that, try to re-enable the miniZ.

**Comment by bwstandard** [comment]
10-4. I'll give a test or two later today and if it continues will mention again. 

Thanks.

**Comment by bwstandard** [comment]
Same issue. Multiple algos and oc defaulted and detuned. RIP

**Comment by RainbowMiner** [comment]
> Same issue. Multiple algos and oc defaulted and detuned. RIP

Is it happening on the 125,4 algo, only? I could not reproduce the problem on my rigs with the MiniZ v1.8y4rc1.

**Comment by bwstandard** [comment]
It's happening on multiple algo. 

Etc eth etc. 

Just looked at other rigs benching and it's just a 3070 issue. Just had another spew crashes. 

I took equihash to 0 on my big rig. Made no difference.

**Comment by bwstandard** [comment]
Another update. My smaller rigs with just 3060ti doing it too.

**Comment by bwstandard** [comment]
Looks like I got the freeze to subside with different settings. Still having crashes though.
