### ISSUE TITLE
Zergpool CPU mining - wrong port issue

### ISSUE THREAD

**Issue by CadenceMTk** [RainbowMiner/RainbowMiner#2060]
Hi once again thanks for the stellar support. ive deployed this software on my entire farm and keep growing it!

for some reason when CPU mining on zergpool I'm noticing a lot of incorrect ports being assigned creating "connection refused" errors

for example if the port is supposed to be 6333 the arguments command will use port 16333 it does that on just about all the algos in zergpool CPU mining, not sure if its doing that on gpu.. 

this seems to be a problem on only some of my rigs.. some seem work fine, im concerned im not getting proper benchmarks because of this issue.

**Comment by RainbowMiner** [comment]
I will check this asap. Try to set "SSL": "0" for ZergPool in pools.config.txt too in the meantime.

**Comment by jch9678** [comment]
I've noticed this issue as well.

**Comment by RainbowMiner** [comment]
Have you been able to solve this issue with setting "SSL":"0" for ZergPoolCoins in pools.config.txt?
Anyway - please have a look at the "Running config" page on http://localhost:4000. Search for ZergPoolCoins until you find the pool's config section, then scroll down a bit and verify, that there is `"SSL": false,`.

**Comment by CadenceMTk** [comment]
i have has the config.txt ssl set to "0"
i just went in the poolsconfig and set all the zergpools to 0 i think that may be it ill check on all the rigs shortly

**Comment by CadenceMTk** [comment]
looks like its solved.. i still se other pools trying to connect in ssl even though i have set to "0" but luckilly they detect and then connect in regular.
