### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by bpvarsity** [RainbowMiner/RainbowMiner#2062]
Is there a way to schedule the miner to turn on and off at certain parts of the day?

**Comment by RainbowMiner** [comment]
Yes - in fact we have a build-in scheduler. To configure it use scheduler.config.txt . Here is a link to the documentation of how to setup the scheduler: https://github.com/RainbowMiner/RainbowMiner#configschedulerconfigtxt

**Comment by bpvarsity** [comment]
> Yes - in fact we have a build-in scheduler. To configure it use scheduler.config.txt . Here is a link to the documentation of how to setup the scheduler: https://github.com/RainbowMiner/RainbowMiner#configschedulerconfigtxt

I totally missed that. Thank you for this and your hard work
