### ISSUE TITLE
Wallet Column in PowerShell Window

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#2068]
I was hoping you could implement this if you think it would be worthwhile.  Just a column with the Wallet Address that each miner mines to in the Profitability Table.  Sometimes it's possible to look at the command below the Profitability Table but it would be nice to see the wallet address even if the miner is not running.  Also many miners i.e. xmrig are using config files where the wallet address is not shown.  Thanks.

**Comment by RainbowMiner** [comment]
I have added that column to the end of the rows, now.

If you feel the miner profit table is overcrowded or doesn't match your sense of order, just remove or resort the columns with the following, newly added parameter "UIProfitColumns" in config.txt:
- configure columns of miner profit tables in UI [default=Miner,Fee,Algorithm,Speed,Diff,Power,Profit,TTF,Accuracy,Pool,PoolFee,Wallet]

**Comment by jch9678** [comment]
Thank you! I'll give it a shot.

**Comment by jch9678** [comment]
It's perfect.  And thank you for the extra options.
