### ISSUE TITLE
Setting up Dual mining ETH+TON in Teamredminer

### ISSUE THREAD

**Issue by Celldfusion** [RainbowMiner/RainbowMiner#2069]
### Discussed in https://github.com/RainbowMiner/RainbowMiner/discussions/2067

<div type='discussions-op-text'>

<sup>Originally posted by **Celldfusion** May 10, 2022</sup>
Hello, I am trying to setup dual mining in eth+ton on teamredminer but it still just use ethash. I already setup a ton wallet, ton pool (icemining) and i already configured the miners.config file to include sha256ton as secondary algorithm, but it still doesnt work. I dont know what i am missing or what to do.
</div>

**Comment by RainbowMiner** [comment]
I have found the bug in the miner module - Teamred should now dual mine ethash and sha256ton

**Comment by Celldfusion** [comment]
Now it runs the benchmark for dual mining in teamredminer as required. But now there are 2 other issues .
1: The dual mining benchmark crashes at startup, but i found that is because a command line option is wrong
![problem1](https://user-images.githubusercontent.com/105326702/168496527-c89c2401-6491-4b97-ac9e-6738484d4d73.png)
2: I managed tu edit the teamred.ps1 to correct the first issue and it ran "correctly", but after the benchmark finished, it dropped a stat file with 0 values into it and it just keep mining ethash only.

**Comment by RainbowMiner** [comment]
Thank you so much for trying and reporting back, what was the fix to the command line? The zero in the stat file is most probably due to the API values are interpreted wrongly. I will check it asap.

**Comment by RainbowMiner** [comment]
This should be solved now. I had to change the miner API plus the way the Icemining pool interacted with Teamred (added protocol).

**Comment by Celldfusion** [comment]
> This should be solved now. I had to change the miner API plus the way the Icemining pool interacted with Teamred (added protocol). Again, thank you very much for your support!

Now the benchmark works!, it register the power consumption and hashrate respectively, and now i am dual mining as intended. Only minor issue i found is that if a set a custom region for icemining (in my case i tried adding ca because i have lower ping in that) it causes to just mine  ethash again, i bruteforce edited the teamred.ps1 file again for my case in the meantime but for the rest, its working as intended. Thank you for the solution
![image](https://user-images.githubusercontent.com/105326702/168640351-bc65eb8b-568f-43a5-8565-3e74f86b4bd5.png)

**Comment by RainbowMiner** [comment]
Ok, found and fixed it. With the next release you will not need to brute-force the Teamred.ps1 module any more. Setting the `"Region": "ca",` in pools.config.txt will work as intended, then. You can simply update the `.\Pools\Icemining.ps1` file by downloading the bugfixed version from here https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/Icemining.ps1 . Just right-click + save-as it into the `.\Pools` folder.

**Comment by Celldfusion** [comment]
> Ok, found and fixed it. With the next release you will not need to brute-force edit the Teamred.ps1 module any more. Setting the `"Region": "ca",` in pools.config.txt will work as intended, then.
> 
> You can simply update the `.\Pools\Icemining.ps1` file by downloading the bugfixed version from here https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/Icemining.ps1 . Just right-click + save-as it into the `.\Pools` folder.

Problem solved, now i can mine in ca region without needing bruteforce, thanks again
