### ISSUE TITLE
Issue: Cryptodredge Crashs

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#207]
Just reporting that Cryptodredge keeps crashing when it has never before on all rigs now.

**Comment by RainbowMiner** [comment]
Oh dear, for all or for specific algorithm? Also, which Nvidia driver version is installed?
If you want, you may post your Logs folder, so that I can have a look into it.

**Comment by RainbowMiner** [comment]
@Byrd1083 I added fallback versions to CUDA9.1 and CUDA9.2 to CryptoDredge, as I suspect the problem might be the Nvidia drivers still running on cuda9.1/9.2. Eventually the crashes might be resolved, after that.
