### ISSUE TITLE
NEOSCRYPT not working on some Nvidia GPU's

### ISSUE THREAD

**Issue by CadenceMTk** [RainbowMiner/RainbowMiner#2073]
when i set zergpool to run neoscrypt with cryptodredge, my rig only utilizes the 1080ti,1660,2060 gpu's none of the 3000 series or a4000 series gpus mine.. they mine on other algos just not that one..
how do i force cryptodredge to activate the other nvidia gpus in the arguments..?

**Comment by RainbowMiner** [comment]
You can't - the old Cryptodredge has no kernel for the newer GPUs. But - I have adapted and compiled a version of Ccminer for exactly that purpose. 
Just use our CcminerKlausT module. This should handle the newer Nvidias.
