### ISSUE TITLE
ZergPool is closing down!

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#208]
From their website:

> We have taken decision to close down the pool. Stratum servers are stopped, regular payment schedule too, we wait for all coins to mature/exchange and final payment within next 24h.

Please remove ZergPool from your config.txt. With the next release I will remove the pool files.

**Comment by ebojali** [comment]
I used zerg... Is there any recommendation on what pools to use perhaps?
