### ISSUE TITLE
Currency calculations off

### ISSUE THREAD

**Issue by bwstandard** [RainbowMiner/RainbowMiner#2083]
Showing I'm making a very large amount of money. Like 600k a day

**Comment by bwstandard** [comment]
![5B6719F8-5F9D-4281-BA0E-923A2B8657B4](https://user-images.githubusercontent.com/92652253/170825636-e3b157c3-3764-4b1b-9649-b4b8e259ef70.jpeg)

**Comment by RainbowMiner** [comment]
Oh man! That's a number. So which pool and which coin is the current miner doing?

**Comment by RainbowMiner** [comment]
Don't mind - I have found the culprit and fixed it.

**Comment by bwstandard** [comment]
Thanks. I'll look for the push

**Comment by RainbowMiner** [comment]
It should heal itself, now. There was a bug inside the rates API.
