### ISSUE TITLE
Setting up 'mc' parameter on miner launch options

### ISSUE THREAD

**Issue by tryiou** [RainbowMiner/RainbowMiner#2084]
Hello,
I'm trying to setup rainbowminer pool to use 'mc=coinA/coinB/...' param for zergpool,
this param is /per algo /per pool specific, we choose what coin to mine on a multicoin stratum, by default mine all of them,
I can't find a proper way to set this with rainbowminer setup/dashboard,
goal would be to turn launch option from

> Bin/NVIDIA-MiniZ/miniZ --telemetry=33000 -cd 0
                                                                                   --url=myaddresspayout@equihash144.mine.zergpool.com:2146 -p
                                                                                   ID=worker1,c=mycoinpayout,refcode=myrefcode --worker=worker1 --pers=auto --gpu-line --extra --latency --nocolor
                                                                                   --nohttpheaders --par=144,5

to custom mc:

> Bin/NVIDIA-MiniZ/miniZ --telemetry=33000 -cd 0
                                                                                   --url=myaddresspayout@equihash144.mine.zergpool.com:2146 -p
                                                                                   ID=worker1,c=mycoinpayout,refcode=myrefcode,mc=GLINK/LTZ --worker=worker1 --pers=auto --gpu-line --extra --latency --nocolor
                                                                                   --nohttpheaders --par=144,5     
                                                                                   
Any help welcome, thanks

**Comment by RainbowMiner** [comment]
Ok, understood. There is currently no specific option to handle the mc parameter for multi-coin in module ZergPool. There are two possibilities available, currently:
- add the `mc=...` in pools.config.txt in parameter `"BTC-Params": "mc=...` (if you are using a payout coin that is not BTC, simply add the coin specific Params line, e.g. `"RTM-Params": "mc=...",`)
- use the ZergPoolCoins module and setup the coins in parameter `"CoinSymbol": "GLINK,LTZ",` and let Rainbowminer do the profit switching for you. This pool module (ZergPoolCoins) makes use of the mc parameter, but for one coin only and switches automatically to the most profitable coin.

**Comment by tryiou** [comment]
Second solution working perfectly,
thanks for your help!
