### ISSUE TITLE
RainbowMiner is excluding some coins from a given algo on ZergPoolCoins

### ISSUE THREAD

**Issue by tryiou** [RainbowMiner/RainbowMiner#2088]
Hello!
I'm trying to understand why RainbowMiner is excluding some coins from a given algo,
using **ZergPoolCoins** on algo **Equihash (144,5)** ,
all those coins are under my max time to find and a block was found in recent times ( under the default 12h filter ),
but can't get them to display on active miners list, only GLINK display,

![1](https://user-images.githubusercontent.com/73646876/172373234-26fef3ad-52b3-40cc-a5c5-ebcdb5246401.png)
![2](https://user-images.githubusercontent.com/73646876/172373245-64a17e20-b577-4c01-92da-5e45139e81c8.png)

I tested a fresh setup of RainbowMiner to see if it was my config conflicting in any way,
this time it would select only BTCZ and would not see other coins from same algo in active list,
i can't understand why it's pruning out the others from profitability list.
Using v4.8.4.6 and tested latest github master with same result.

Behavior changed as i was seeing all those coins in my active list sorted by profitability,
but today only one of them will display, maybe it just select the most profitable and prune the others, is that intended change ?
![3](https://user-images.githubusercontent.com/73646876/172375710-0a2ee302-48f7-4949-9802-b64ff34668c5.png)
now switched to BTCZ and no trace of others.

**Comment by RainbowMiner** [comment]
You got it right already: the BestPool list contains exactly one selection for each algorithm. This is intended.

It's a 4-step selection process:
- Pools: all coins/algorithms that fit your current definitions in the config
- BestPools: only the most profitable coin/algorithm/pool
- Miners: all possible miners combined with the BestPools
- Active Miners: only the fastest miner on the BestPool

**Comment by tryiou** [comment]
Ok got it, thanks for those clarifications :)
