### ISSUE TITLE
Sgminer-kl crashes on launch 

### ISSUE THREAD

**Issue by mattdistro** [RainbowMiner/RainbowMiner#209]
Something changed on my system, perhaps due to Windows 10 build 1809 or a driver update, as I didn't have an issue before.

Sgminer-kl crashes immediately after launch unless GPU_FORCE_64BIT_PTR is set to 0.

**Comment by RainbowMiner** [comment]
Do you know, with which error message and for which algorithm it crashes? Maybe it is some kind of out of memory.

**Comment by RainbowMiner** [comment]
So, just edit your Start.bat and change line 3 to:

@if not "%GPU_FORCE_64BIT_PTR%"=="0" (setx GPU_FORCE_64BIT_PTR 0) > nul

**Comment by mattdistro** [comment]
Would that potentially affect any other miners? Also will the auto-update still work if I change the start.bat

It's not a particular algorithm. It's sgminer-kl as a whole. Found this bug that's related: https://github.com/KL0nLutiy/sgminer-kl/issues/5

I'm going to try a fresh install of Windows and the drivers, see if changes anything. If not I'll go ahead and change the start.bat on that machine (only one with an AMD card).

**Comment by RainbowMiner** [comment]
I think, the setting should not affect other miners, as long as there are no GPU with small memory (2GB) running. 
You can safely change the Start.bat, it will not break the auto update. I changed the whole procedure some releases ago.

**Comment by mattdistro** [comment]
I have 3 4GB cards in that rig. No issues noticed when using

@if not "%GPU_FORCE_64BIT_PTR%"=="0" (setx GPU_FORCE_64BIT_PTR 0) > nul

in the start.bat

I think we're good

**Comment by RainbowMiner** [comment]
Perfect :)
