### ISSUE TITLE
Pool configuration

### ISSUE THREAD

**Issue by dakingwow** [RainbowMiner/RainbowMiner#2093]
I want mine SFX on fastpool.xyz, i'm following the documentation, but it only shows this error:

WARNING: No pools available: check your configuration

I used it as it is in the documentation. Is possible add Fastpool on RBMiner?

**Comment by RainbowMiner** [comment]
Sure, that's possible. I will add it.
To solve it for now, could you please upload a Debug file? Start Rainbowminer, then open http://localhost:4000, then click Debug file on the left hand side

**Comment by dakingwow** [comment]
[debug_2022-06-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/8884798/debug_2022-06-11.zip)
Attached

**Comment by RainbowMiner** [comment]
Ok, two things:
- first, just don't use the parameter "CoinName" in pools.config.txt for Userpools (in your case the Fastpool section). Reason is, the Userpools use normalized coin names, if RainbowMiner finds the CoinSymbol in its coins database. The normalized coinname used inside Rainbowminer for SFX is "Safexcash". So your setting of "safex" is the reason, the pool is not being shown. Also, there is no need to set parameters "Algorithm" or "CoinSymbol", since the Fastpool userpool only has that one position.
- second, the "User" for Fastpool is `    "User": "$Wallet@$WorkerName",`, according to the pools webseite. You have put a "." (dot) instead of a "@" (ampersand).

**Comment by dakingwow** [comment]
Same error, i upload debug.

WARNING: No pools available: check your configuration

[debug_2022-06-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/8891706/debug_2022-06-13.zip)

**Comment by RainbowMiner** [comment]
Ok, add CPU to the DeviceName parameter in config.txt
```
  "DeviceName": "CPU",
```

**Comment by RainbowMiner** [comment]
In principle, yes. That works for most parameters. Only, the DeviceName parameter is exclusive, by default. This one parameter you will have to set for each client.  If you are using setup.json to create rigs, make sure, the "DeviceName" is set in setup.json.

**Comment by dakingwow** [comment]
The server worked for me, Benchmarking. But the client no, i download the rbminer (client), i need change userpool and pool.config in client?

**Comment by dakingwow** [comment]
I tested with same userpool in client, and work. If i want add pool in my server, i will change userpool in each client?

**Comment by RainbowMiner** [comment]
No, just add "userpools" to the "ServerConfigName" list in config.txt on every client. Every client will then check, if the userpools.config.txt has been changed on the server and update its own, accordingly.

**Comment by RainbowMiner** [comment]
> Edit: in fact, I think, I will add this userpools to the ServerConfigName list by default. That just makes sense

Done. "userpools" is now by default on the "ServerConfigName" list.

**Comment by dakingwow** [comment]
You can put a count of Remote Workers, and External IP in a row.

**Comment by CadenceMTk** [comment]
im trying to add a user pool miner-control.de and cant get it to work same errors
[debug_2022-06-15 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/8913564/debug_2022-06-15.1.zip)

**Comment by RainbowMiner** [comment]
Yes, out of town is correct. But now I am back. Sorry for the delay.

**Comment by dakingwow** [comment]
Rainbow, please verify the API port Icemining, is offline.

**Comment by dakingwow** [comment]
WARNING: Pool API (Icemining) has failed.

**Comment by dakingwow** [comment]
Same error with this fix

**Comment by dakingwow** [comment]
Rainbow, how to mine XDAG?
Algo: Xdag ??
Coin: Xdag ??

stratum.xdag.org:13656

**Comment by dakingwow** [comment]
What coin name i put for XDAG?
I try Xdag and not work.

**Comment by RainbowMiner** [comment]
XDAG is the correct symbol. So there must be some setup problem. Please show me your userpools.config.txt record, so that I can help you out.

**Comment by dakingwow** [comment]
[
  {
    "Enable": "1",
    "Name": "XDAG",
    "PoolFee": "0",
    "Algorithm": "randomxdag",
    "CoinName": "",
    "CoinSymbol": "",
    "Currency": "",
    "Protocol": "stratum+tcp",
    "Host": "equal.xdag.org",
    "Port": "13656",
    "User": "$Wallet",
    "Pass": "x",
    "Region": "US",
    "SSL": "0",
    "EthMode": ""

**Comment by dakingwow** [comment]
[
{
"Enable": "1",
"Name": "XDAG",
"PoolFee": "0",
"Algorithm": "randomxdag",
"CoinName": "XDAG",
"CoinSymbol": "",
"Currency": "",
"Protocol": "stratum+tcp",
"Host": "equal.xdag.org",
"Port": "13656",
"User": "$Wallet",
"Pass": "x",
"Region": "US",
"SSL": "0",
"EthMode": ""

**Comment by dakingwow** [comment]
I try stratum.xdag.org too, but not work.

**Comment by RainbowMiner** [comment]
Two things to check:
- 1st did you add the pool "XDAG" to the parameter PoolName in config.txt?
- 2nd did you add your XDAG wallet address to pools.config.txt, either directly or indirectly via coins.config.txt and `$XDAG` variable.

Could you show me the pools.config.txt "XDAG" section, too please?

**Comment by dakingwow** [comment]
"XDAG": {
    "XDAG": "MY WALLET DIRECT",
    "XDAG-Params": "",
    "Worker": "$WorkerName",
    "Penalty": "0",
    "Algorithm": "randomxdag",
    "ExcludeAlgorithm": "",
    "CoinName": "XDAG",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "MinerName": "Xmrig",
    "ExcludeMinerName": "",
    "FocusWallet": "MY WALLET DIRECT",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "0",
    "CoinSymbolPBM": "",
    "DataWindow": "",
    "StatAverage": "",
    "StatAverageStable": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "",
    "MaxAllowedLuck": "",
    "MaxTimeSinceLastBlock": "",
    "MaxTimeToFind": "",
    "Region": "",
    "SSL": "",
    "BalancesKeepAlive": ""

**Comment by RainbowMiner** [comment]
In pools.config.txt, 
```
"FocusWallet": "MY WALLET DIRECT",
```
... FocusWallet is a boolean (0 or 1). Set it to "1", if you want to focus mine XDAG with your new userpool.

**Comment by RainbowMiner** [comment]
In pools.config.txt
```
"Algorithm": "randomxdag",
...
"CoinName": "XDAG",
```

... these two don't need to be set, since your userpool "XDAG" covers XDAG and randomxdag, only.

**Comment by dakingwow** [comment]
I need use stratum.xdag.org or equal.xdag.org?

**Comment by RainbowMiner** [comment]
Use `equal.xdag.org`

**Comment by RainbowMiner** [comment]
Yes, `stratum+tcp` is perfect. Be aware, that the pool on equal.xdag.org seems to be on maintenance, currently.
