### ISSUE TITLE
Variety of offline miners 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2094]
Hello sir. 

Wouldn’t you please reach out to me via discord. 

I have a lot of offline cards and a headache. 

Dont forget I’m in cst 

if you use the discord group I added you to not too long ago you’ll have access to other help as well. 

always appreciated

**Comment by Nickfost** [comment]
Sigh

**Comment by RainbowMiner** [comment]
Sorry, I have/had all hands full with work and -sigh- Corona. Will come back to you as soon as possible. Just to let you know, you are not forgotten.
