### ISSUE TITLE
Enhancement: monitor profit display in USD

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#210]
Is there any way through the monitor to be able to get just a USD profit display. It maybe multiple columns to auto convert and display. It is very primal and unclear the way profits are displayed through remote monitoring. Would suggest a column for btc, usd, eu, ect...

**Comment by RainbowMiner** [comment]
Yes, of course. This is a good idea. I will add a column for each selected currency.

**Comment by RainbowMiner** [comment]
Ok, implemented :) With the next release there will be the following features, in addition:
- transfer selected currencies to rbminer.net
- display all other workers on localhost:4000 dashboard (if using rbminer.net for reporting)
- display power usage on rbminer.net
- display profit for usd, eur in rbminer.net/monitoring headlines
- display profit for all selected currencies in rbminer.net/monitoring details (click +)

**Comment by Byrd1083** [comment]
Just curious. I currently have rainbow config to calculate power cost and show actual profit in the output. If I look on the online monitor it shows a calculation of profit. Is this showing before or after power cost?
