### ISSUE TITLE
Incorrect ERG DAG size

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2101]
DAG size '"ERG": 1283453312,' for FIRO seems wrong. See https://minerstat.com/coin/ERG

**Comment by RainbowMiner** [comment]
Oh yes, that seems a bit off. I'll check the calculation.

**Comment by UselessGuru** [comment]
If you comaacross the REAL formula pls. let me know.
I just tried to get close to that values from minerstat.
Check function Get-DAGdata in https://github.com/Minerx117/NemosMiner/blob/master/Includes/Include.psm1

**Comment by RainbowMiner** [comment]
In fact, ERG isn't a DAG but a table, that has some very specific growth. It's now easy to calculate the table size in memory, given the current block height.
