### ISSUE TITLE
ERG Data size (again)

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2102]
```
  $tablesize = pow(2,26);
  $blockheight = min($blockheight,4198400);
  if ($blockheight >= 614400) {
    $p = floor(($blockheight - 614400)/51200) +1;
    while($p-- > 0) {
      $tablesize = floor($tablesize/100)*105;
    }
  }
  $tablesize *= 31;
```

This is the powershell code I use:

```
$Dataset_Bytes_Init = [Math]::Pow(2, 26)
$Blockheight = [Math]::Min($Blockheight, 4198400)
If ($Blockheight -ge 614400) { 
    $P = [Math]::Floor(($Blockheight - 614400) / 51200) + 1
    While ($P-- -gt 0) {
        $Size = [Math]::Floor($Dataset_Bytes_Init / 100) * 105
    }
}
$Size *= 31
```

I cant get the same values as you. Can you assist?

With blockheight 776391 I get 2184391440?

BTW: Your current value 2528702085 (2.35503733623773) does not correspond with what minerstat shows 2.409GB

**Comment by RainbowMiner** [comment]
> BTW: Your current value 2528702085 (2.35503733623773) does not correspond with what minerstat shows 2.409GB

The minerstat value is slightly off. They do not use discrete flooring in between, so it's a bit higher. But the original Autolycos2/ERG source code uses exactly the above function.

**Comment by UselessGuru** [comment]
thank you - I spotted my mistake (after having looked 10x).
