### ISSUE TITLE
Connection to API getting rejected.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#2106]
I am in the process of adding a machine for mining and I checked the credentials multiple times but I am still getting the following error. Please let me know what to look at as to the issue?

`Download server configuration now? This will end the setup. (yes/no) [default=yes]:

WARNING: Get-ServerConfig failed 401 Unauthorized (Client Error)
Error downloading configfiles!

Download server configuration now? This will end the setup. (yes/no) [default=yes]:
`

**Comment by RainbowMiner** [comment]
Do you have another client connected, already? Does your password contain `$`, `` ` `` or `"` ?

**Comment by Yamanipanuchi** [comment]
Yes, I have another client connected. Checked the server config and it matches.

**Comment by whitindllc** [comment]
im getting this error as well after changing the user name and password on the server side... i shut down the client... pushed a new config to it with the new user and password but am seeing that error in the miner
