### ISSUE TITLE
All of a sudden can't get to rbminer.net 

### ISSUE THREAD

**Issue by bwstandard** [RainbowMiner/RainbowMiner#2107]
This issue is within my network and none of my machines will report to it and I can't monitor from my phone. Did I get blocked somehow?

**Comment by bwstandard** [comment]
I believe this is my  isp as vpn gets me there

**Comment by bwstandard** [comment]
Although if that's the only site I'd think I got blacklisted somehow on the site.

**Comment by bwstandard** [comment]
Would this have to do with an outage I had maybe resetting my IP? I'm not 100% sure it did but relatively positive I got a new IP. Thanks in advance

**Comment by bwstandard** [comment]
I did some looking and more testing. It looks as though my IP has been banned by the website somehow overnight. I remember checking my stats before going to bed and now everything in my network will not get to your final IP, it's blocked at your VPS gate before it gets to your 193 address. Could you let me know why it got blocked so I can fix that on my end? I really need to make sure the monitoring doesn't go down again. It's pretty nice and I don't like being without it.

**Comment by Mushroomvendor** [comment]
I think you got hit by cloud flare. I've been stuck in this too for a couple of days. Hopefully we hear back from the Dev. 

Have you tried the server / client setup?  Going to see if that makes a difference otherwise I'll have to setup proxies on my entire farm which may take a while. 

Im still.able to mine for the Dev however even though I cannot connect otherwise.

**Comment by RainbowMiner** [comment]
Oh dear! In fact the side sits behind CloudFlare. I'll see what I can do.

**Comment by bwstandard** [comment]
Thank you, and if you could let me know preventative measures, I was just about to get my own monitor setup rather than ping the crap out of your site. Maybe I push the button too much? Let me know, not trying to be malicious

**Comment by RainbowMiner** [comment]
Ok, I have lowered the bar for CloudFlare. Can you access the website now? What does it say? Do you get a "403 Forbidden" or something else!

**Comment by RainbowMiner** [comment]
Can you access the following URL?
https://rbminer.net/api/gmdate.php

**Comment by Mushroomvendor** [comment]
No I cannot. I get a server not responding. 

Of i do a tracert I get all the way to the hostinger servers 153.**** and then I'm shut down.

**Comment by Mushroomvendor** [comment]
Is there an ip blacklist? Could you whitelist mine?

**Comment by bwstandard** [comment]
No I cannot. I get a server not responding.

Of i do a tracert I get all the way to the hostinger servers 153.**** and then I'm shut down.

Also cannot get to the link

**Comment by bwstandard** [comment]
Is there an ip blacklist? Could you whitelist mine?

**Comment by RainbowMiner** [comment]
Just send me an eMail to info@rbminer.net with your IP address and I'll try. I can contact the hostinger support as well, then.

**Comment by bwstandard** [comment]
sent. just checked on my mobile network. Works.

**Comment by RainbowMiner** [comment]
Ok, there is a IP-Whitelist, I have added your IP address. Please check again now. If it's still blocked, I'll hand it over to the hostinger support.

**Comment by bwstandard** [comment]
![image](https://user-images.githubusercontent.com/92652253/177000045-a13ab0cd-4b8e-444d-986a-9f556eb8c3c6.png)

**Comment by bwstandard** [comment]
I'm looking into just building one here, I just need to figure out how to interface with WP. I have a few VPS, Ive just never sent a json to a wordpress with rest API

**Comment by RainbowMiner** [comment]
Did you try the url https://rbminer.net/api/gmdate.php ? It's a simple php script, that returns the current datetime in UTC. All of the API is completely independent of WordPress.

**Comment by bwstandard** [comment]
![image](https://user-images.githubusercontent.com/92652253/177000229-efa445cf-591e-4bca-b5b3-7e81dd7de6a2.png)
If you're using wordpress, maybe do you use a plugin for the json? I have a site up, as mentioned I've never sent a json to WP to make it work

**Comment by bwstandard** [comment]
I'm thinking authorization and a webhook plugin should do the trick however I'm new to this fact. Zapier would require premium. 

Battery ran out on my one pc so I'll check further soon, just need to find the correct reporting file to modify for sending to the right place. I think I found it however I'm not 100% sure since I didn't see any sort of authorization stuff in it.

**Comment by bwstandard** [comment]
I've started working on getting this going but I'm too new to REST I'm getting a no route when I got to test my POST. Once I get that figured out I'm hoping just a point of the config file will take are of the rest.

**Comment by RainbowMiner** [comment]
Your calls did never reach the server, so it's Cloudflare, that blocks your IP for some reason. I have now changed the Cloudflare plan, so that I have more control. Your IP will be whitelisted soon. After that, you should be able to get around Cloudflare's L3/L4 firewall.

**Comment by bwstandard** [comment]
I used to use it but it caused too many issues for me. I switched to a premium plugin pack to stop spam etc although I'd bet your at a ginormous capacity in comparison to my two servers. 

I wonder what cloud flare labeled me as. Other than my 8 machines I only accessed via phone / tablet

**Comment by RainbowMiner** [comment]
I have added your IP to the "Allow" list at Cloudflare. Could you please try again both urls?
https://rbminer.net/monitoring
https://rbminer.net/api/gmdate.php

**Comment by bwstandard** [comment]
![034CC71B-45D9-43DD-B42C-FCDCA1B5450B](https://user-images.githubusercontent.com/92652253/177041739-8a809362-9dfb-46ae-9057-cc8a4cd2e999.png)

Same result on both. 

Permissions error now

**Comment by RainbowMiner** [comment]
Aha! But that's one step ahead. I'll investigate your 403

**Comment by bwstandard** [comment]
Absolutely. Cf is touchy. Thank you. Let me know if I need to tweak something. Am running server client mode now. Not sure if that makes a difference

**Comment by RainbowMiner** [comment]
I have checked the server accesslog and the Cloudflare access log for your IP address (the one you sent by email). It's no where to be found. Please check, if the IP is still the same. Also, try a traceroute to rbminer.net and send me the result by email.

**Comment by RainbowMiner** [comment]
Is the API url now reachable for you?
https://rbminer.net/api/gmdate.php

**Comment by bwstandard** [comment]
Still forbidden

**Comment by RainbowMiner** [comment]
Ok. It was worth a try - could you please go to https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending and upload the resulting header fields here? Especially the useragent will be of major interest.

**Comment by bwstandard** [comment]
![878D1592-0D78-49D1-A863-9C579068480F](https://user-images.githubusercontent.com/92652253/177051869-b69721b8-1c65-45b4-85c6-309befe4204a.png)

From my phone. Where I usually look from. My rigs can't ping either but probably because of browser. I will check on pc from time to time but not a ton.

**Comment by RainbowMiner** [comment]
I have adapted the Cloudflare DDOS rules. Are you now able to access the website?

**Comment by bwstandard** [comment]
No. Same 403. 

Checked on a miner too. 

Is your htaccess blocking me? 403 is usually a file permissions thing shutdown by a defender or such

**Comment by bwstandard** [comment]
![E45D468D-C7D4-477F-AA03-A93405B04CB2](https://user-images.githubusercontent.com/92652253/177129266-2c9eac74-ca7c-4b67-b9cd-47d906f85b18.png)

![2A1E1796-3F06-4929-9574-35F7C614403F](https://user-images.githubusercontent.com/92652253/177129325-7ec53da3-5ec3-4671-a5ef-e04d05dfefdd.png)

**Comment by bwstandard** [comment]
Hey what file.are you using for.the POST request?

I'm trying to figure out hosting this and i literally just stepped into REST API

**Comment by bwstandard** [comment]
![image](https://user-images.githubusercontent.com/92652253/177386933-6f81bc9e-c4f1-4073-8be3-310729591939.png)
PC browser

**Comment by bwstandard** [comment]
No. don't use any. 403 isn't my end blocking, it's still your end. 

Is openresty something you use? Your Server? seems like that's making the block at this point

**Comment by RainbowMiner** [comment]
This is so weird - so it's def. not Cloudflare. No entries in the logs there, also, Cloudflare would block you with a four digit error code (1xxx). Has your access IP changed? If yes, please send it to me by email, so that I can check the server logs, these 403 should be logged in the access_log. If there aren't any, it's Hostinger that blocks your accesses. We could try another (sub-)domain, just to be sure.

**Comment by RainbowMiner** [comment]
Can you reach http://api.rbminer.net/gmdate.php ? That's a non-ssl subdomain which should directly access the server, without any in-betweens.

**Comment by bwstandard** [comment]
When accessing NORMALLY, which I must do because of a very unique situation I CANNOT access your site. I get a 403, which is an improvement from where we normally were behind Cloudflare. 403 is a server based error, not CDN. 

WHEN I DO use a VPN everything is great. I can report, see the monitoring central which is the main reason we're doing this etc. BUT I CANNOT USE A VPN for extended periods or across my 8 soon to be 9 unit farm.

Sorry for the caps, I'm lazy and don't like Bold formatting keyboards are superior to mouse work. to recap, 
VPN =Good but cannot use
NO VPN = 403 forbidden openresty server error. 

I think we're almost there, and most importantly I'd like to know how to avoid this in the future because this sucks, probably as much for you as me. Going to try and figure out REST so I can just have it on my VPS so I don't have to bother you but time is not available to sit with it right now.

**Comment by RainbowMiner** [comment]
Good, that makes it clearer, now.
Could you check, if your IP is on some blacklist?
You can use this website: https://whatismyipaddress.com/blacklist-check

**Comment by bwstandard** [comment]
dnsbl.spfbl.net

Is the only that I find

**Comment by bwstandard** [comment]
![image](https://user-images.githubusercontent.com/92652253/177523355-1c4908eb-cb13-4eee-bd62-e1d268f0977a.png)

**Comment by bwstandard** [comment]
https://www.hostinger.com/tutorials/what-is-403-forbidden-error-and-how-to-fix-it

**Comment by bwstandard** [comment]
Nothing new on this of late?

**Comment by bwstandard** [comment]
Looks like it's working for now. I did order a new modem to flip my ip. 

If you can shed light in the cause that'd be great.
