### ISSUE TITLE
Add Autolykos To Unmineable pool

### ISSUE THREAD

**Issue by gorgarp** [RainbowMiner/RainbowMiner#2108]
Unmineable now supports Autolykos as a mining option via autolykos.unmineable.com:3333

"Supported algorithms: Ethash, Autolykos, Etchash, RandomX and KawPow."

**Comment by RainbowMiner** [comment]
Thank you for the hint! I have added Autolycos2 to the pool module.

**Comment by gorgarp** [comment]
Thank you!

**Comment by gorgarp** [comment]
Actually, just tested. You can now mine to earn the coin ERGO but still not able to mine the algo to earn other coins. (Not showing as an option)

**Comment by gorgarp** [comment]
![image](https://user-images.githubusercontent.com/7957736/177015100-39a88c87-2e66-4f66-8dc4-97a22b1bdd77.png)

**Comment by gorgarp** [comment]
I cloned master to obtain current upstream
