### ISSUE TITLE
FYI: new miners XmrigAmd/Cpu/Nvidia and Fireice with 0% dev fee (no dev fee)

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#211]
I compiled special RainbowMiner versions of the miners XmrigAmd, XmrigCpu, XmrigNvidia and Fireice (Xmr-Stak), with developer fee set to 0%. All versions are part of the current RainbowMiner release.

**Comment by Byrd1083** [comment]
Is this automatic or do I need to change anything. I was set to auto update fyi.

**Comment by Byrd1083** [comment]
I also noticed the other day that all rigs went down. I had all pools loaded into config. Phiphipool would report its profits but would never allow a connection to establish in any rigs. So essentially it reported highest profits and then crashed all rigs. I simply removed phiphipool. Additionally I am just going to mine on 2 pools for now anyway. Just reporting the biz ;~)

**Comment by RainbowMiner** [comment]
Yes, it seems, that phiphipool has big problems with it's stratum servers. It is always a good idea, to find a selection of suitable pools. Running on all pools might result in too much switching.

> Is this automatic or do I need to change anything. I was set to auto update fyi.

This is automatic.
The only thing: you will need to have a look if you had edited FireIce's cpu.txt/amd.txt/nvidia.txt config files. The config files for FireIce v2.4.7 are no longer compatible with those for v2.5.0. The new FireIce v2.5.0 is being installed in path "Bin\Cryptonight-FireIce250", the old version will be conserved in path "Bin\Cryptonight-FireIce", so that nothing will be lost.
You will have to edit the newly created files in "Bin\Cryptonight-FireIce250" to suit your needs. Do not copy over the old config files.
