### ISSUE TITLE
Issue: update triggers output window to popup

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#212]
Is there any way to prevent the output window from popping up when an auto update happens?

**Comment by RainbowMiner** [comment]
I think so, yes. I will have a look.

**Comment by RainbowMiner** [comment]
It is not that easy :) 
We are doing it like that, for now:

|Status before update|Status after update|
|:-:|:-:|
|opened maximized|opened maximized|
|opened normal|opened normal|
|minimized (from maximized)|minimized (from maximized)|
|minimized (from normal)|minimized (from maximized)|

So, basicly, the new window will be minimized, if the old one has been minimized.
What cannot be avoided is, that the new window will get the focus, if the old window has been opened as normal or maximized and is running behind other applications. Maybe I find a solution for this, too.
