### ISSUE TITLE
Rainbowminer Linux is showing activity times as 4 hours ahead of actual time

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#2122]
Rainbowminer Linux is showing activity times as 4 hours ahead of actual time. Is this just a timezone misconfiguration in Linux/RBM? I'm hoping this is an easy fix?

**Comment by RainbowMiner** [comment]
Interesting. The system clock shows the correct date/time? If yes, it's most probably an logging issue with timezones.

**Comment by samdave123** [comment]
Sorry, I had my rig shut down for a few days because of the mental weather here in the UK.

HiveOS set an incorrect timezone, I've correct this and all is good now.
