### ISSUE TITLE
BzMiner is not getting a pool from RM

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#2123]
[debug_2022-07-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/9106711/debug_2022-07-13.zip)

It tries to connect to the placeholder pool called   yourpool.org or something like that instead of the pools I have set up.

Thanks.

**Comment by RainbowMiner** [comment]
I'll check the miner. Thank you for the Debug file.

**Comment by RainbowMiner** [comment]
Could you please send me all config_nnn.log and config_nnn.txt files in folder `Bin\GPU-BzMiner` ? Be aware, that these will contain your wallets, so better send it by email to rbminer2018@gmail.com

**Comment by RainbowMiner** [comment]
Ah, ok. Don't bother. I have found and fixed the problem.
