### ISSUE TITLE
Not Ignoring Neoscrypt

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#213]
RainbowMiner does not seem to be ignoring neoscrypt as written in the config.  Claymore's neoscrypt miner is visible in the idle miner section.
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2479423/config.txt)

**Comment by RainbowMiner** [comment]
It should :) I will have a look.

**Comment by jch9678** [comment]
Any progress with this.  I just caught rainbowminer using neoscrypt.  I hate neoscrypt, they are the worst for Hawaii cards.  My temp is 94C!

**Comment by hernandn01** [comment]
try disabling at the device level, in my case I disabled ethash for the 1060 3gb card. Setting is on devices.config.txt
![image](https://user-images.githubusercontent.com/41829368/47032655-212c8000-d130-11e8-967b-ccdd5137209c.png)

**Comment by jch9678** [comment]
Thanks.  I'll try that.  But I also just deleted claymore's neoscrypt miner.  I can't take a chance with 94C.

**Comment by RainbowMiner** [comment]
Ok, I found a possible glitch, which could fire up an in config.txt disabled algo. I will fix this.
Disabling it at device level or deleting the miner's ps1-file are both 100% save solutions.

**Comment by RainbowMiner** [comment]
Fixed. This fix will be part of the next release.
