### ISSUE TITLE
Please add multiminer-kudaraidee for Argon2d16000

### ISSUE THREAD

**Issue by xiaolin1579** [RainbowMiner/RainbowMiner#2131]
Please add multiminer-kudaraidee for Argon2d16000
https://github.com/Kudaraidee/multiminer

**Comment by RainbowMiner** [comment]
Ok, I'll have a look.

**Comment by xiaolin1579** [comment]
thank

**Comment by UselessGuru** [comment]
In my test multiminer-kudaraidee for Argon2d16000 did not work well for me:
AMD: I could not get it work at all uding OPENCL
NVIDIA: Very low hash rate (approx. 60H/s on GTX760 / GT 1030 or GTX1660 Super).

**Comment by xiaolin1579** [comment]
> In my test multiminer-kudaraidee for Argon2d16000 did not work well for me: AMD: I could not get it work at all uding OPENCL NVIDIA: Very low hash rate (approx. 60H/s on GTX760 / GT 1030 or GTX1660 Super).

Maybe set --gpu-batchsize too small
Because I'm using a 1050Ti and getting about 1-2 Kh/s hashrate per card (using --gpu-batchsize 172).

**Comment by UselessGuru** [comment]
> Maybe set --gpu-batchsize too small

Might be. I did not set it at all.
Problem: How do I automatically detect the best value for each GPU? In a SW like RM such parameters should be automatically set to optimal values by the miner (like intensity in other miners).

**Comment by RainbowMiner** [comment]
First, I have to update the source code, so that it accepts multiple GPU IDs, then we can try. At the moment, this fork of the multiminer accepts "all" or one specific GPU, only. I am on it, after that we can test. Actually, I will add a specific batch-size as default. After that, you can change it to any value you like in your miners.config.txt.

**Comment by RainbowMiner** [comment]
Ok, I have reworked the multiminer code (commit 9ff9a222c28e2b9234538f5c27d89d554817ef19)
- added Argon2dURX and Argon2d16000
- the value for parameter `--gpu-batchsize` is pre-calculated by RainbowMiner, so that it fits into your GPU
- multiple GPUs can be selected
- hashrate optimizations

**Comment by UselessGuru** [comment]
I cannot get it work on my 2 AMD cards (RX 5700 & RX580). AMD Driver version is 30.0.21017.1000 (on Win 11).

`Multiminer.exe --algo argon2d4096 --use-gpu OpenCL --url stratum+tcp://argon2d4096.eu.mine.zergpool.com:4240 --user ######################--pass #############,c=BTC,pl=0 --gpu-batchsize 422 -t 1 --retry-pause 1 --api-bind 127.0.0.1:4003 --gpu-id 5`

Bot give me 

```
         **********  multiminer-rbm 1.2.0  ***********
     A CPU/GPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.

     RainbowMiner Edition https://rbminer.net

[Device #1] OpenCL Device 'NVIDIA GeForce GTX 1660 SUPER' (NVIDIA Corporation)
[Device #2] OpenCL Device 'NVIDIA GeForce GT 1030' (NVIDIA Corporation)
[Device #3] OpenCL Device 'NVIDIA GeForce GTX 750 Ti' (NVIDIA Corporation)
[Device #4] OpenCL Device 'Ellesmere' (Advanced Micro Devices, Inc.)
[Device #5] OpenCL Device 'gfx1010:xnack-' (Advanced Micro Devices, Inc.)
Start mining on device #5.

[2022-08-23 18:16:49] 6 CPU cores available, 1 miner threads selected.
[2022-08-23 18:16:49] Starting Stratum on stratum+tcp://argon2d4096.eu.mine.zergpool.com:4240
: OpenCL ERROR: -30: clCreateProgramWithSource
[2022-08-23 18:16:49] FAIL: thread 0 failed to initialize
```

Nvidia cards work fine.

**Comment by UselessGuru** [comment]
> I cannot get it work on my 2 AMD cards (RX 5700 & RX580). AMD Driver version is 30.0.21017.1000 (on Win 11).

Any ideas?

**Comment by RainbowMiner** [comment]
You could try this new libmm_gpu_gate.dll - maybe it solves the AMD issue (I have compiled it with AMD APP SDK OpenCL 1.2)
[libmm_gpu_gate.zip](https://github.com/RainbowMiner/RainbowMiner/files/9521927/libmm_gpu_gate.zip)

Make sure to bakup the current libmm_gpu_gate.dll, then unzip the new dll out of the above archive into the `.\Bin\GPU-Multiminer` folder.

**Comment by UselessGuru** [comment]
Nope, does not work...  same error:

`Multiminer.exe --algo argon2d16000 --use-gpu OpenCL --url stratum+tcp://argon2d16000.eu.mine.zpool.ca:4241 --user #######################--pass ##############,c=BTC --gpu-batchsize 432 --threads 1 --retry-pause 1 --api-bind 127.0.0.1:4004 --gpu-id 4`

```
         **********  multiminer-rbm 1.2.0  ***********
     A CPU/GPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.

     RainbowMiner Edition https://rbminer.net

[Device #1] OpenCL Device 'NVIDIA GeForce GTX 1660 SUPER' (NVIDIA Corporation)
[Device #2] OpenCL Device 'NVIDIA GeForce GT 1030' (NVIDIA Corporation)
[Device #3] OpenCL Device 'NVIDIA GeForce GTX 750 Ti' (NVIDIA Corporation)
[Device #4] OpenCL Device 'Ellesmere' (Advanced Micro Devices, Inc.)
[Device #5] OpenCL Device 'gfx1010:xnack-' (Advanced Micro Devices, Inc.)
Start mining on device #4.

[2022-09-08 13:16:48] 6 CPU cores available, 1 miner threads selected.
: OpenCL ERROR: -30: clCreateProgramWithSource
[2022-09-08 13:16:48] Starting Stratum on stratum+tcp://argon2d16000.eu.mine.zpool.ca:4241
[2022-09-08 13:16:48] FAIL: thread 0 failed to initialize
```

`Multiminer.exe --algo argon2d16000 --use-gpu OpenCL --url stratum+tcp://argon2d16000.eu.mine.zpool.ca:4241 --user #######################--pass ##############,c=BTC --gpu-batchsize 432 --threads 1 --retry-pause 1 --api-bind 127.0.0.1:4004 --gpu-id 5`
``
```

         **********  multiminer-rbm 1.2.0  ***********
     A CPU/GPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.

     RainbowMiner Edition https://rbminer.net

[Device #1] OpenCL Device 'NVIDIA GeForce GTX 1660 SUPER' (NVIDIA Corporation)
[Device #2] OpenCL Device 'NVIDIA GeForce GT 1030' (NVIDIA Corporation)
[Device #3] OpenCL Device 'NVIDIA GeForce GTX 750 Ti' (NVIDIA Corporation)
[Device #4] OpenCL Device 'Ellesmere' (Advanced Micro Devices, Inc.)
[Device #5] OpenCL Device 'gfx1010:xnack-' (Advanced Micro Devices, Inc.)
Start mining on device #5.

[2022-09-08 13:16:57] 6 CPU cores available, 1 miner threads selected.
: OpenCL ERROR: -30: clCreateProgramWithSource
[2022-09-08 13:16:57] Starting Stratum on stratum+tcp://argon2d16000.eu.mine.zpool.ca:4241
[2022-09-08 13:16:57] FAIL: thread 0 failed to initialize
```
