### ISSUE TITLE
MRR pool share difficulty message

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2133]
Is this possible to send a message to the renter when his pool share difficulty is out of suggested bound ?

Like so : hello your share difficulty is 4.295m and it should be between 138m - 828m to get the advertised hashrate.

the message should be customisable with variable for bound and current share difficulty

Like so : hello your share difficulty is %c and it should be between %b to get the advertised hashrate.

**Comment by RainbowMiner** [comment]
Yes, that would be nice. I will add this.

**Comment by astitsa** [comment]
thanks once again for your excellent work

**Comment by RainbowMiner** [comment]
It's now in beta test. The message will be sent only, if the current miner supplies the difficulty via it's API. Most of the miners do, but for example, the Gminer doesn't.

**Comment by astitsa** [comment]
that will help us all in the long way ;) 

thanks for your work !

**Comment by astitsa** [comment]
FYI 

PS>TerminatingError(Set-MiningRigRentalStatus): "The property 'diffmessagesent' cannot be found on this object. Verify that the property exists and can be set."
PS>TerminatingError(Set-MiningRigRentalStatus): "The property 'diffmessagesent' cannot be found on this object. Verify that the property exists and can be set."
PS>TerminatingError(Set-MiningRigRentalStatus): "The property 'diffmessagesent' cannot be found on this object. Verify that the property exists and can be set."
PS>TerminatingError(Set-MiningRigRentalStatus): "The property 'diffmessagesent' cannot be found on this object. Verify that the property exists and can be set."
PS>TerminatingError(Set-MiningRigRentalStatus): "The property 'diffmessagesent' cannot be found on this object. Verify that the property exists and can be set."
PS>TerminatingError(Set-MiningRigRentalStatus): "The property 'diffmessagesent' cannot be found on this object. Verify that the property exists and can be set."
PS>TerminatingError(Set-MiningRigRentalStatus): "The property 'diffmessagesent' cannot be found on this object. Verify that the property exists and can be set."

**Comment by RainbowMiner** [comment]
Ok, it's either because you have updated the "Pools/MiningRigRentals.psm1" module, only, or it's because of that error I have just fixed with the last commit. I'll push a new release within the next 10 minutes.

**Comment by RainbowMiner** [comment]
The release v4.8.5.5 is online. Please update your rigs - the error message should go away then (I hope)

**Comment by astitsa** [comment]
thanks i will give you a feedback later on
