### ISSUE TITLE
herominers xeq

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2134]
can i understand how could this happen ? what's the part of algo that let the pool manipulate our profit this way ?

![xeq-herominers-what](https://user-images.githubusercontent.com/97480060/185807880-8b71c6d9-8e0a-4e08-98e9-266daf7672b9.PNG)
![herominers-xeq](https://user-images.githubusercontent.com/97480060/185807881-2d2be9f1-bf56-4d48-8535-c2c2fca55424.PNG)
![Xeq-herominers-strange](https://user-images.githubusercontent.com/97480060/185807882-52f77518-bf5f-4f98-818c-c241b83b92b9.PNG)

**Comment by RainbowMiner** [comment]
The profit seems pretty far off. I'll check the herominer's API data.

**Comment by astitsa** [comment]
yeah and it's worst today ... what's funny is everything was fine 2 days ago. it means it clearly is a variable from the pool api that is very wrong

**Comment by RainbowMiner** [comment]
It should be resolved, by now. I have disabled XEQ in the minerstat API, since they deliver overly inflated reward values.

**Comment by astitsa** [comment]
ok thanks
