### ISSUE TITLE
Add Support for neoxa (NEOX)

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#2136]
Hi, Could we add support for this new coin?
It available to mine at Hero Miners and minerpool.org too.
https://neoxa.herominers.com/ | https://neox.minerpool.org/

It being recognized cause Trade Ogre listing.
https://tradeogre.com/exchange/USDT-NEOX

and support from Red Panda Mining
https://www.youtube.com/watch?v=A6r9O11MkEk

Regards.

**Comment by RainbowMiner** [comment]
The coin is already in our database, HeroMiners is configured for it. I will now update Minerpool, too.

**Comment by RainbowMiner** [comment]
I have pushed a new release. This contains all changes to Herominers and Minerpool, so that NEOX can be mined there.
