### ISSUE TITLE
Autolykos not working on lolMiner 1.55

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2139]
https://github.com/Lolliedieb/lolMiner-releases/issues/1692

**Comment by jgonzis** [comment]
New Release 1.55a has solved that problem!!

**Comment by RainbowMiner** [comment]
Nice! I'll push an update as soon as there is a Windows v1.55a, too.

**Comment by RainbowMiner** [comment]
> New Release 1.55a has solved that problem!!

@jgonzis will there be a Windows v1.55a as well?

**Comment by jgonzis** [comment]
> > New Release 1.55a has solved that problem!!
> 
> @jgonzis will there be a Windows v1.55a as well?

Yes it should be, that was express launch in Linux... if no ERGO is used then 1.55 is fine, in case is used it crashes in some rigs.

**Comment by RainbowMiner** [comment]
I have temporarily added an extra Lolminer module for v1.54 + Autolycos2 since this version runs good.
