### ISSUE TITLE
Question: Uknown's for specific Algorithims

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#214]
I keep getting the following...

GeForce GTX 1080 Ti (GPU#01,GPU#02)
===================================

Miner          Fee Algorithm      Speed Power*   BTC/Day  USD/Day  Accuracy Pool         PoolFee
-----          --- ---------      ----- ------   -------- -------- -------- ----         -------
Trex         1.00% X17       51.96 MH/s   389W 0.00030612   1.9610      81% BlockMasters   0.25%
Trex         1.00% C11           0  H/s     0W    Unknown  Unknown      74% Zpool          1.25%
CryptoDredge 1.00% Lyra2z    11.21 MH/s   357W 0.00000901   0.0577      90% NLpool         0.10%

For C11, It shows unknown. I've tried doing the benchmarks. It seems to not clear up. Not sure why its there also if it does not know the hashrate?

**Comment by RainbowMiner** [comment]
Very strange! Would you zip and drop your current Logs directory here? Then I will find out, where this unknown comes from.

**Comment by Yamanipanuchi** [comment]
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/2479721/Logs.zip)

**Comment by RainbowMiner** [comment]
I found it: please remove ZergPool from your config.txt, the pool has shut down, and update to the current RainbowMiner release. Then rebenchmark all failed miners (use button at http://localhost:4000/minerstats.html).

**Comment by RainbowMiner** [comment]
Also, I tweaked the lite ui display, so that "unknown" (=failed miners) will no longer be displayed in the lite UI

**Comment by RainbowMiner** [comment]
Another thing: "NVIDIA Driver v411.63", you should update to the newest display drivers, if you find some time.
