### ISSUE TITLE
Help wanted: How to calculate Octopus (CFX) DAG size

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2140]

**Comment by RainbowMiner** [comment]
I'll look it up for you. CFX is totally different from the "standard" DAG size calculations.

**Comment by UselessGuru** [comment]
> I'll look it up for you.

TIA
I could not find any documentation on it

**Comment by UselessGuru** [comment]
Any news?

**Comment by RainbowMiner** [comment]
Sorry, I forgot about that. Actually, I mixed it up with ERG (ERG is the coin that's special regarding calculation). CFX is calculated just like all the other DAG coins.

Here are the base values for CFX:

    blocks per epoch = 524288
    dataset bytes init = 4294967296
    dataset bytes growth = 16777216
    dataset mix bytes = 256

**Comment by UselessGuru** [comment]
Thank you. Where did you find this information? 

curiosity killed the cat :-)

**Comment by RainbowMiner** [comment]
> Thank you. Where did you find this information?

In fact, that was one of the harder ones. I read through their reference miner's source code. There is a function in one of the files that does the calculation, hence all constants are set at this location.
