### ISSUE TITLE
Shiny new AMD equipment offline / ineffective for 60+ days  #2118 #2126

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2141]
# Shiny new AMD equipment offline / ineffective for 60+ days  #2118 #2126

I've moved all 8 cards back to 1 rig, I’ve got all of the details available in our chat. please help me out man. 

all these cards are available to mine in hiveos, I can use hiveos to mine today, I’m just not incredibly interested in doing so.

![image](https://user-images.githubusercontent.com/1572453/188364851-d40d846f-0342-4682-b64f-272845c7b956.png)

**Comment by RainbowMiner** [comment]
Ok, let's do it now: 
- please run `./gputest.sh` in the RainbowMiner folder and upload the `gputestresult.txt` here
- please run `clinfo` and post the result

**Comment by Nickfost** [comment]
GPU-TEST 05/08/2023 04:41:51
================================================================================
 
 
1. nvidia-smi
--------------------------------------------------------------------------------
 
 
2. OpenCL
--------------------------------------------------------------------------------
 

Profile    : FULL_PROFILE
Version    : OpenCL 2.1 AMD-APP (3558.0)
Name       : AMD Accelerated Parallel Processing
Vendor     : Advanced Micro Devices, Inc.
Extensions : {cl_khr_icd, cl_amd_event_callback, }


................................................................................

**Comment by Nickfost** [comment]
user@RDRIG20:~/RainbowMiner$ clinfo
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3558.0)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               0
user@RDRIG20:~/RainbowMiner$

**Comment by Nickfost** [comment]
======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp (DieEdge)  AvgPwr  SCLK    MCLK   Fan     Perf  PwrCap  VRAM%  GPU%
0    40.0c           11.0W   500Mhz  96Mhz  40.78%  auto  138.0W    0%   4%
1    40.0c           9.0W    500Mhz  96Mhz  40.0%   auto  138.0W    0%   3%
2    39.0c           13.0W   500Mhz  96Mhz  40.78%  auto  138.0W    0%   3%
3    40.0c           13.0W   500Mhz  96Mhz  40.78%  auto  138.0W    0%   3%
4    40.0c           12.0W   500Mhz  96Mhz  40.78%  auto  138.0W    0%   1%
5    40.0c           12.0W   500Mhz  96Mhz  40.78%  auto  138.0W    0%   3%
6    41.0c           14.0W   500Mhz  96Mhz  40.0%   auto  138.0W    0%   4%
7    41.0c           12.0W   500Mhz  96Mhz  40.78%  auto  138.0W    0%   4%
================================================================================
============================= End of ROCm SMI Log ==============================
user@RDRIG20:~/RainbowMiner$

**Comment by Nickfost** [comment]
Install script:

![image](https://user-images.githubusercontent.com/1572453/236735866-85f5f20c-077f-40d1-9c2a-ffd60fb026cb.png)

**Comment by Nickfost** [comment]
[2023-05-07 23:47:47] INFO: Gracefully halting RainbowMiner
[2023-05-07 23:47:50] INFO: Starting RainbowMiner v4.8.9.2
[2023-05-07 23:47:51] INFO: Curl : /usr/bin/curl
[2023-05-07 23:47:53] INFO: OpenCL detection failed: Exception calling "GetDeviceIDs" with "2" argument(s): "OpenCl error -1: DeviceNotFound."
[2023-05-07 23:48:02] INFO: cURL disabled
[2023-05-07 23:48:02] INFO: Internet is ok
[2023-05-07 23:48:02] INFO: Started 2 API threads on port 4000

**Comment by Nickfost** [comment]
I legit never solved this. Yikes

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
