### ISSUE TITLE
MRR rigs and config suddenly lost

### ISSUE THREAD

**Issue by appsettings** [RainbowMiner/RainbowMiner#2142]
Hi, I use MRR pool since a long time, but tonight something weird happened.
I take one rig has an example, but the same thing happened in the same moment on every rig I have.
RBM was mining for a rental, but at some point stopped and moved to another pool. I clearly see this in the logfile, do not see any errors or reboots.

What is strange is that from that moment it is like MRR is not available anymore, all rigs on MRR are offline.
From that moment, every 30mins, according to UpdateInterval settings, RBM tries to re-create all the rigs like this:
```
INFO: MiningRigRentals: Updating algorithms config data (forced)
INFO: MiningRigRentals: Start create rigs on rig1
WARNING: MiningRigRental error: Error: Rig name already exists. 
```

I tried to run ResetProfit.bat, and I see after some hourse that MRR files are not recreated in folder Stats\Pools.

On MRR Rigs page of RBM web ui, I do not see the rigs anymore (apart of 1-2 spare rigs, do not know why).
On All Pools page, MRR pool is listed, but all algo have 0 value on BTC/GH/Day column.

In the Data folder I see this files:
- mrrcontrol.json (content seems legit, algorithm field is empty)
- mrrinfo.json (I see all the ids of my rigs on MRR)
- mrrpools.json (content seems legit)
- mrrpoolsall.json (content seems legit)
- mrrservers.json (content seems legit)

In the Config folder I see this files:
- mrr.config.json (a rig object with many fields and empty values)
- mrralgorithm.config.json (many algos with enabled=1)

Summarizing, despite MRR pools seems configured (and I didn't change anything), MRR is not working anymore on all rigs.
I wonder if something happened on latest releases (i run it with autoupdate, v4.8.5.5 now), or if something happened only to me (but on all rigs simultaneously).
Thanks

**Comment by RainbowMiner** [comment]
How very strange! My rigs all run just fine (all on MRR) with the v4.8.5.5 so I suspect there is something else going on. Are all rigs standalone, or do they run as clients + one master? Has there been a daylight saving time switch on your time zone?
Could you please upload a Debug file? Also try to clear all Cache folders, just in case.

**Comment by RainbowMiner** [comment]
Please try the following:
Create a new API key/secret pair on MiningRigRentals and change the API_Key and API_Secret settings in your pools.config.txt accordingly.

**Comment by appsettings** [comment]
All rigs are standalone. No daylight saving switch. I've tried already to clear the asy files on Cache folder. 
As an info, I add also that I see MRR balance on RBM, as well as MRR stats page.

**Comment by RainbowMiner** [comment]
Ok, please just create a Debug file on one of these machines and upload it here. Maybe I can see in there, what is going on.

**Comment by RainbowMiner** [comment]
I am especially interested in the "Title" setting in pools.config.txt in MiningRigRentals section. The above warning/error indicates, that RainbowMiner tries to create a rig with a name, that already exists.

**Comment by RainbowMiner** [comment]
Could you please check, if the now disabled rigs on MRR in fact still do contain the tag `[yourrigname]`? Have you some exceptionally long Description? Not that MRR has suddenly reduced their maximum number of characters.

**Comment by appsettings** [comment]
Thanks, I've found out that on MRR all the descriptions of the rigs are now empty!
I think it might be the link I have (https://rbminer.net). If I try to enter the description via web, I see it's get censored with ***********
I do not know if via api it might be now ignored, causing all of my rigs to get "disassociated".

The description is also quite long, 480 chars, with some <br> in it, but from web I see it doesn't get truncated (i tried to copy paste it).
I didn't change it since years, so it might be some recent MRR changes. Now all 384 rigs on MRR are orphaned, with empty description.

**Comment by RainbowMiner** [comment]
With some effort I could help you out and build some repair script, so that the descriptions can be refilled. It should be possible to re-identify the MRR rigs via their title.

**Comment by RainbowMiner** [comment]
Question: could you please check your "EnableUpdateDescription" setting in pools.config.txt? Is it "0" or "1"?

**Comment by RainbowMiner** [comment]
> I think it might be the link I have (https://rbminer.net/). If I try to enter the description via web, I see it's get censored with ***********
 I do not know if via api it might be now ignored, causing all of my rigs to get "disassociated".

Luckily this is not the case - I have just checked by letting the descriptions of some rigs being updated, including a link. The link get's censored, but the descriptions is updated correctly. So it must be something else. I could imagine, that there could have been a problem with the API on MRR side. Either way, I'll add some logic to recover your rigs, but I'ld really like to see your Description and Title settings. If you don't want to share this publicly, please send me an eMail.

**Comment by RainbowMiner** [comment]
Ok - I have added the promised recovery mode to the MiningRigRentals in pools.config.txt:
- **EnableRecoveryMode**: if you have orphaned rigs due to empty description or if you have unintentionally removed the [%workername%]  tag, set this to "1" and RainbowMiner will try to match all orphaned rigs to the unique rig titles and eventually recover the description. Since the recovery mode adds another pretty lengthy API call, make sure to disable (set "EnableRecoverMode" to "0"), after all rigs have been recovered.

**Comment by RainbowMiner** [comment]
Now try to set EnableRecoveryMode on one of your rigs and check, if the rigs' descriptions return on MRR.

**Comment by appsettings** [comment]
Sorry for the delay.
I can confirm that using EnableRecoveryMode I restored all my rigs!
I confirm also that I had EnableUpdateDescription enabled, now I've disabled it.
Don't really know what caused the issue, but thanks again for your prompt solution.

**Comment by RainbowMiner** [comment]
Ah, that's good to hear!
