### ISSUE TITLE
RX 470 Mining Edition 8gb not detected

### ISSUE THREAD

**Issue by BTKiDfr** [RainbowMiner/RainbowMiner#2143]
Hello,

I have a rig with mix AMD gpu : 
3x RX5600XT
2x RX5700XT
1x RX5700
2x RX470 Mining Edition 8gb

Rbminer detect all cards except the 2 RX 470

Can you help me, please ?

Best regards
BTKiDfr

**Comment by RainbowMiner** [comment]
Could you please generate and upload a Debug file (run RainbowMiner, then open http://localhost:4000 in your browser and click "Debug file" on the left hand side).

**Comment by BTKiDfr** [comment]
> Could you please generate and upload a Debug file (run RainbowMiner, then open http://localhost:4000 in your browser and click "Debug file" on the left hand side).

**Comment by BTKiDfr** [comment]
> > Could you please generate and upload a Debug file (run RainbowMiner, then open http://localhost:4000 in your browser and click "Debug file" on the left hand side).

I can't use localhost, the rig is not in my home.
i can access the rig via SSH, the degub file is it in a directory ?

**Comment by RainbowMiner** [comment]
It's not a single file in one directory, but a zip file, that will contain many files. If you know the IP address of your rig, try 'your.ip.add.ress:4000', e.g. if your rig is 166.230.2.123, then you should be able to contact `http://166.230.2.123:4000` via your internet browser. If you have setup username and password (you should!), a simple login window should ask you for the credentials.

**Comment by BTKiDfr** [comment]
Hello
My debug file in attachment
[debug_2022-09-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/9543074/debug_2022-09-11.zip)

**Comment by RainbowMiner** [comment]
Thank you, that helps. I think, I have got an idea now.

**Comment by RainbowMiner** [comment]
Could you please run `./gputest.sh` in the RainbowMiner folder and upload the resulting `gputestresult.txt` here?

**Comment by RainbowMiner** [comment]
Ok, gotcha. It's two AMD platforms. I have tried to fix this today already.

**Comment by BTKiDfr** [comment]
Hello
Very good job, thank you so much
