### ISSUE TITLE
2miners added Ergo to autoexchange to BTC and ETC autoexchanges to BTC

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#2144]
2miners added some coins to autoexchange:
         Ergo to autoexchange to BTC
         ETC autoexchanges to BTC

Do I just add to poolconfig coin name?

https://twitter.com/pool2miners/status/1567584361624571911?t=hA_PK2Cr6_5NehfMpuq55Q&s=19

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/189509279-f86cb834-1187-45a7-84fa-38ff5935869b.png)
Is this what I add, the 3rd line

**Comment by paulpoco** [comment]
Nope, the lolminer154 is trying to use port 2020 instead of 8888

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/189509409-53570740-eaf2-418b-93fc-7cc2ef1a6d02.png)

**Comment by paulpoco** [comment]
I forgot to change the 3rd line rpc to erg
![image](https://user-images.githubusercontent.com/801414/189509441-80f6ac3e-27ed-4952-96a5-a242df59af8c.png)

**Comment by paulpoco** [comment]
Hmmm maybe ERGO is for a different type of card because this is not profitable on a 1070.
![image](https://user-images.githubusercontent.com/801414/189509918-12daefd6-b3da-4589-ac85-a4bd04d88468.png)

**Comment by paulpoco** [comment]
Not profitable for 1070 or 1660super.

Like the Benchmark isn't long enough, only found 1 share.

**Comment by RainbowMiner** [comment]
Thank you! I'll add ERG->BTC autoexchange asap. We will have to double-check the divisor. I think it's 1e9 for ERG.

**Comment by paulpoco** [comment]
So using 1e8 for ERG will make it look unprofitable?

**Comment by RainbowMiner** [comment]
It's 1e18 vs. 1e9 - yes, using the latter makes it much more profitable.

**Comment by paulpoco** [comment]
@RainbowMiner are you going to do a new release with these changes implemented? 

I too many machines to individually change files.

**Comment by paulpoco** [comment]
2 x 1070 not profitable
