### ISSUE TITLE
2Miners added RVN to get paid in BTC

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#2147]
https://2miners.com/blog/get-paid-in-bitcoin-for-altcoin-mining-btc-payouts-for-gpu-mined-etc-ergo-rvn/

**Comment by RainbowMiner** [comment]
Nice! I'll add it asap.

**Comment by paulpoco** [comment]
Yes my alternate to ETH.  I don't like trading the alts myself.
