### ISSUE TITLE
Add ETHW and some of working pools https://miningpoolstats.stream/ethereumpow

### ISSUE THREAD

**Issue by sgeneralov13** [RainbowMiner/RainbowMiner#2149]
Please!

**Comment by RainbowMiner** [comment]
Molepool is in the works - WoolyPooly is already adapted. I'll push a new commit soon.

**Comment by RainbowMiner** [comment]
Molepool will follow

**Comment by jul-ienfr** [comment]
Hello with the new version 4.8.5.9 I have this message
WARNING: Pool API (Nanopool) for ETHW has failed.

**Comment by RainbowMiner** [comment]
Thanks for reporting this - I'll double check it.

**Comment by RainbowMiner** [comment]
Is this message still persisting? I have just checked the Nanopool API for ETHW and everything runs fine.

**Comment by sgeneralov13** [comment]
@RainbowMinerI i don't understand. Do I need to add an "ETHW" address == ETH in coins.config.txt?
