### ISSUE TITLE
Dual mining with srbminermulti doesnt work

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2159]
While srbminermulti tries to benchmark a dual algo, the second algo isnt connecting to the pool. This is not specific to 1 pool. I tried 3 of them. Also, bzminer works on dual algo mining. 
![Screenshot_60](https://user-images.githubusercontent.com/36564393/191122655-19cb3c83-9b3d-4a1b-9095-c29d4806b899.jpg)

**Comment by RainbowMiner** [comment]
Ah, that's bad. Could you please send me the commandline of the miner? You can find it in the log files (or just create a Debug file and upload it here).

**Comment by papadrams** [comment]
Can i send it to you in discord? Last time i posted a debug file, someone was playing with my wallets.

**Comment by RainbowMiner** [comment]
Yes, please send it by eMail to rbminer2018@gmail.com

**Comment by papadrams** [comment]
Thanks!
