### ISSUE TITLE
Review setting "ShowPoolBalancesExcludedPools": "1",

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#216]
it does not appear to be showing balances from excluded pools "ShowPoolBalancesExcludedPools": "1",

**Comment by RainbowMiner** [comment]
Oh! You are right. I will check.

**Comment by RainbowMiner** [comment]
Fixed. Will be included in the next release (you may download [Include.psm1](https://github.com/RainbowMiner/RainbowMiner/raw/master/Include.psm1) with right-click link save as.. into your RainbowMiner directory to fix it until the next release)
