### ISSUE TITLE
MiniZ stuck downloading on AMD rigs

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2160]
Since 2 updates ago, miniz gets stuck and does not download in amd gpu rigs.
![Screenshot_61](https://user-images.githubusercontent.com/36564393/191204599-98317262-fbd0-4157-a290-39540901d187.jpg)

After the interval i get this error

![Screenshot_62](https://user-images.githubusercontent.com/36564393/191204667-9dc23fe9-3682-4821-8bc6-a4d87f59b640.jpg)

**Comment by papadrams** [comment]
The debug file i sent you by mail is an AMD rig as well and has this same issue. 2 birds 1 stone

**Comment by RainbowMiner** [comment]
Oh! Thank you so much for reporting that!

**Comment by RainbowMiner** [comment]
> The debug file i sent you by mail is an AMD rig as well and has this same issue. 2 birds 1 stone

I have not yet recieved your eMail. Is the address correct? rbminer2018@gmail.com
Maybe, just to be sure, send it via discord, too.

**Comment by papadrams** [comment]
Thanks!
