### ISSUE TITLE
TeamBlackMiner v1.67 fix2 contains corrupt verthash.dat

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2161]
https://github.com/sp-hash/TeamBlackMiner/issues/307

**Comment by RainbowMiner** [comment]
That shouldn't be a problem for us, since we download our file separately.

**Comment by UselessGuru** [comment]
v1.68 has been relased
https://github.com/sp-hash/TeamBlackMiner/releases/tag/v1.68
