### ISSUE TITLE
Zpool balance not appearing

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2164]
I am a pain in the ass!!!
When using zpoolcoins, balance is nowhere to be seen in console!

**Comment by RainbowMiner** [comment]
I have just updated all the multi-instance pool's balance modules. Maybe the commit f98193fe10b96f172587bdc6638cd02ec4526fe0 solves your issue.

**Comment by papadrams** [comment]
Thanks again!
