### ISSUE TITLE
bzminer + runmode combo prob

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2168]
i have 3060ti, 3080, 3090 and with combo mode it cause bzminer to disable all card and throw me an error : lhr unlock init failed: driver may not be supported. so i tried to go device mode and everything was fine.

**Comment by RainbowMiner** [comment]
Ok, so your issues #2170 and #2169 are directly related to this switch to device mode. It looks like, there have been very old stat files for multiple rare algorithms, that haven't been updated for some time, now. I think, I have spotted a bug at the automatic detection of this condition that could cause benchmarks, that do not look like benchmarks.
I'll try to figure this out now.
Could you please look in the `.\Stats\Miners\` folder and find and upload all `*_Allium_HashRate.txt` files?

**Comment by RainbowMiner** [comment]
Regarding Bzminer - I will disallow combo mode on this miner. It looks like it can't handle mixed GPUs.

**Comment by astitsa** [comment]
yeah i feel like you are spot on with bzminer
thanks for your time
