### ISSUE TITLE
Kaspa

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#2171]
I'm trying to mine Kaspa (KAS) via woolypooly, but it won't work. I think it's maybe because the algo kheavyhash isn't yet added to RBM?

**Comment by RainbowMiner** [comment]
It's already been added some time ago. I had called it "Kaspa" - but just some hours ago I decided to rename it to "kHeavyHash", since that's the algorithm name on the official kaspa website. But don't mind, if you are using the current release 4.8.6.3, then simply enable "Kaspa". The updater will automatically change it to "kHeavyHash" with the next release.

**Comment by acos0874** [comment]
Well actually I just can't even get woolypooly to work. please can you check my debug?
[debug_2022-09-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/9647663/debug_2022-09-26.zip)

**Comment by RainbowMiner** [comment]
If you did try to mine for some VEIL, then you should empty the following parameters in pools.config.txt:

Yours are focused on KAS which isn't in the current pool module, yet:
```
  "CoinSymbol": "KAS",
  "FocusWallet": "KAS",
```

.. just remove the KAS:
```
  "CoinSymbol": "",
  "FocusWallet": "",
```

**Comment by acos0874** [comment]
Thanks for the update. It's now showing in all pools but won't benchmark or show in active miners. Is there a memory restriction on it??

**Comment by acos0874** [comment]
Sorry my bad, I had the only available miners in exclusions

**Comment by bwstandard** [comment]
I'm trying to get my miners to bench mark as well. but for some reason it doesn't want to take. I have Woolypooly enabled, The coin KAS setup, kHeavyHash in the algos. What would I be missing further? 

Thanks for the help.

**Comment by acos0874** [comment]
I also couldn't get it to working recently but I believe the pool currently has it in maintenance anyway so didn't push the issue
