### ISSUE TITLE
MRR error?

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2172]
Good afternoon,
I have enebled miningrigrentals in 3 of my rigs and i am trying to install it at 1 more but i get this error after each interval:
![Screenshot_20220927-012940_TeamViewer](https://user-images.githubusercontent.com/36564393/192393892-712d9278-54f4-4d63-8cf0-35c86144eba6.jpg)
I really hope i am not doin something wrong and waste your time. i've checked the config about 10 times.
I have already sent you a debug file in your mail.
Thanks in advance

**Comment by papadrams** [comment]
yeah i just rtied it on another rig, but same error

**Comment by RainbowMiner** [comment]
That's a bug for sure. I will look into it asap

**Comment by RainbowMiner** [comment]
Ok, that last commit should solve the problem. You can simply download the new `.\Pools\MiningRigRentals.ps1` pool module into your RainbowMiner's `.\Pools` folder to fix it: https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/MiningRigRentals.ps1
(right-click -> save link as ...)

**Comment by papadrams** [comment]
the error is gone. But it doesnt create any rigs in mrr.
I have created 2 by hand. one for cpu [par2cpu] and one for gpu as [par2]
The cpu one is online although it hasnt changed the name of the rig. Also it doesnt creates any more by itself.
The gpu one seems to be offline, not renamed and not created any more algos by itself

**Comment by RainbowMiner** [comment]
Are all benchmarks done? It will start to create rigs 3h after the last benchmark is done.

**Comment by papadrams** [comment]
Yeah, all benchmark is done for 10 hours at least now

**Comment by RainbowMiner** [comment]
Maybe it's a profitability issue - I'll look into your debug file.

**Comment by papadrams** [comment]
Ok, thanks!

**Comment by RainbowMiner** [comment]
Could you please send a new Debug file, one where all benchmarks are finished 10h+ ?

**Comment by papadrams** [comment]
Ofcourse!! Its in your mail

**Comment by RainbowMiner** [comment]
Good, I'll look into it asap.

In the meantime try to change these parameters in pools.config.txt:
```
    "AutoCreateMinProfitPercent": "0",
    "AutoCreateAlgorithm": "",
    "AutoCreateMaxMinHours": "48",
```

**Comment by papadrams** [comment]
i did. No change so far

**Comment by papadrams** [comment]
w8, now i see it has created many rigs for cpu. 
"AutoCreateMinCPUProfitBTC":  "0.0000010"
i have changed that as you can see, but it still created rigs only with minimum daily profit of 0.00001
I have done that cause many have done as well and are still getting paid

**Comment by RainbowMiner** [comment]
> i have changed that as you can see, but it still created rigs only with minimum daily profit of 0.00001

There is in fact a hard-limit set by MiningRigRentals.com: the total profit (profit per day x minimum hours/24) must be above that 0.00001 figure. Therefor you need to increase your "AutoCreateMaxMinHours" value.

**Comment by papadrams** [comment]
Its not applied in practise though. You can see many rigs in mrr that dont use it and get rented and get paid as regular.

**Comment by RainbowMiner** [comment]
> Its not applied in practise though. You can see many rigs in mrr that dont use it and get rented and get paid as regular.

That's interesting! Maybe they have lowered the limit. I'll ask them.

**Comment by RainbowMiner** [comment]
I have tried to change one rig by hand:

![image](https://user-images.githubusercontent.com/39437538/192485827-a53610ed-26ef-428f-a3cf-11b6694310b1.png)

It looks like, they still check for that limit.

**Comment by papadrams** [comment]
Press update. it updates and anyone can rent it. I can send you screenshots of my transactions.
I guess that you couldnt press update earlier? or could you and you havent tried?

**Comment by RainbowMiner** [comment]
Yes, that error showed up after I had pressed Update. I'll try, if the API accepts lower values (in the past, they simply rejected the calls).

**Comment by papadrams** [comment]
i have sent you a picture of my recent payments in mail. one is as low as 0.00000131
Do you know any way of changing this by hand, without affecting any of the other users using rbminer?

**Comment by RainbowMiner** [comment]
Yes, open the pool module `.\Pools\MiningRigRentals.ps1` with notepad, go to line 732 and change the number 0.00001 to something lower, e.g. 0.000001. Then save it. Done.
![image](https://user-images.githubusercontent.com/39437538/192493774-f0d9ec7a-ac6f-411d-b89b-617103e66638.png)

**Comment by papadrams** [comment]
Will this update all of my existing rigs on mrr if i configure maxminrentalhours as well?? Or it will apply those only on new rigs?

**Comment by RainbowMiner** [comment]
I think it should update all rigs.

**Comment by papadrams** [comment]
Thanks a lot! I will let you know!

**Comment by papadrams** [comment]
You have closed the issue so i dont know if you will get notified about this.
Anyway
In 2 new pc's, i changed the value rigminprofit from .ps1 file to 0.000001. set maxminhours to 12 as well as minimumhours to 12
rbm created rigs for all the algos as i stated. perfect!!! those rigs got listed and have been rented already at prices less that 0.00001btc per day. (i believe someone who is reading this post rent them and thank you for that)

BUT once the rigs are created, rbm makes no changes. Meaning: i changed the maxminhours to all my pcs along with all the others i mentioned. New pc's worked great. Pc's that rbm had already created rigs for in mrr with the old settings, never change. 

Is there a way to create a .bat for example that resets all those settings in mrr according to values in pools.config?

**Comment by RainbowMiner** [comment]
Got it. Thank you for reporting back! I'll lower that number in the source code, then.
Normally, those rigs should be updated, so there are only two chances: MRR blocks us from doing so or there is problem with the code. I'll double-check the code, if it looks as if there isn't a problem there, I'll forward the issue to MRR.

> Is there a way to create a .bat for example that resets all those settings in mrr according to values in pools.config?
This could be of help in one more way as well. In some algos, the profit margin is huge. And i put prices by hand to get the most profit. Once this market drops prices, i am expensive. it would be nice to have a file like that to restore all values or even make it more specific per algo.

Currently no - but it would be possible. The only way is to trigger a manual run of the mrr updater via localhost:4000 (on the MRR Rigs page).

**Comment by papadrams** [comment]
I did the manual run but it didnt work. No "hand written" prices were corrected, nor minimum hours changed.
There is 1 more issue i pinpointed. For some reason only 2 of my 7 cpus have rigs on algo minotaurx. I even tried putting 1 more by hand, but it keeps getting disabled and not renamed. it is not excluded in rbm and it is benched normally and exists in my console when mining in my pool.

**Comment by RainbowMiner** [comment]
From the last release on, the rigs should update automatically. In fact, there was no check for changed min. / max. hours in place.
Regarding the minimum rig rental prices: I have added two new parameters to pools.config.txt.
-  "MaxMinHours" (=defaults to 12) this offers you the possibility to limit the automatic min. hours adjustment. Just set it to "3" and all rigs will get 3 min. hours set, even if the minimum rig rental price is below 0.00001 BTC then. If you choose to set to a higher number, say "12" for example, all rig's min. hours will be between "MinHours" (=defaults to 3) and "MaxMinHours". 
- "EnableAutoAdjustMinHours" (=defaults to 1) if set to "1", the automatic adjustment according to minimum rig rental price will take place, but the resulting min. hours will always remain between "MinHours" and "MaxMinHours"
