### ISSUE TITLE
MRR mass delete rigs

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2175]
Is there an option to mass delete the rigs created in mrr?
Example: I have a pc that has created rigs for cpu with a rigid and rigs for gpu with another rigid.
I would love to have the option to mass delete all the rigs with 1 rigid or another or both of them.
And then create the all over with different settings.
(I would like it cause rbm doesnt update already created rigs with different settings (rigminprofit, maxminhours, hand drawnprices etc)}

Also it would be awesome to see the minimum rig prices that rbm creates even if i have it disabled (helps greatly with hand drawn prices)

**Comment by RainbowMiner** [comment]
Start `Setup.bat` / `setup.sh`, then select Mrr (enter r + Return). You will get a list of all created rigs with the specified API credentials. Now select delete some (enter d + Return) and you will have the possiblity to enter search criteria.

**Comment by papadrams** [comment]
You are awesome!
