### ISSUE TITLE
MRR rent using 3344 when it should use 3333

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2178]
the miner was gminer and the algo kawpow

here is the debug file

[debug_2022-09-29 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/9679252/debug_2022-09-29.1.zip)

**Update**
i tested it with 2 mrr account and it looks like the last time i used xmrig with 3344 port it was working fine

Are we using the port MRR provide with their API when the rig is rented ?

**Comment by RainbowMiner** [comment]
> Are we using the port MRR provide with their API when the rig is rented ?

Yes - we use /rig/[ID]/port API request to get the real port.

**Comment by RainbowMiner** [comment]
Ok, so most probably MRR did switch from 3344 to another port number for KawPow. I have now changed the cachetime to 2 x RainbowMiner Interval for rented rigs. That should avoid this problem in the future.

**Comment by astitsa** [comment]
Ok thanks for your support

i  will keep an eye open for the feedback

**Comment by astitsa** [comment]
i think you commited a fix for this it happened again with 3315 vs 3344

![image](https://user-images.githubusercontent.com/97480060/193633282-2141af87-d61d-45fc-9e67-f03f0585b7fc.png)
![image](https://user-images.githubusercontent.com/97480060/193633364-cfd2b005-7de6-42a4-90f3-5da88a2818ac.png)
