### ISSUE TITLE
BSODsolo not mining when hashrate_solo = 0

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#218]
Please review:

I can see ORE in the Best Pools but is not mining solo on BSOD. is it because there is no other solo miner on ORE? I was able to solo mine fine with HEX and REDN.

![image](https://user-images.githubusercontent.com/41829368/47038587-10cfd180-d13f-11e8-8435-61bd3fdc819f.png)

**Comment by hernandn01** [comment]
yes that is the case, I went back to solo mine REDN but this time there is no solo hashrate and solo mine is not kicking. maybe we do not need to check that and solo mine regardless

**Comment by hernandn01** [comment]
not entirely sure that was the case, it is mining now hashrate_solo is still 0 but there are 3 worker_solo, just want it to make sure that there is no restrictions in place to allow solo mining. I haave focuswallet set and to not check profit
![image](https://user-images.githubusercontent.com/41829368/47043716-8b9ee980-d14b-11e8-833c-6469d672276d.png)

**Comment by RainbowMiner** [comment]
Yes. It is because of the 0 hashrate.
It might be better, if I remove this limitation for solo mining.

**Comment by hernandn01** [comment]
I think so too, thanks

**Comment by RainbowMiner** [comment]
What just came to my mind: would it make sense, to add a switch to each entry of the pools.config.txt, so that 0-hashrates might be enabled for any other pool, too? I am not sure, but it might be useful.

**Comment by RainbowMiner** [comment]
Download the new pool file directly into your Pools directory, from here: [BsodSolo.ps1](https://github.com/RainbowMiner/RainbowMiner/raw/master/Pools/Bsod.ps1) with right-click link save as ..

**Comment by hernandn01** [comment]
if is not too much trouble to add that setting to the poo config to allow 0-hashrates that would be great. We have discussed this previously and the could be a solution as to that as well.

**Comment by RainbowMiner** [comment]
Good. I will add a switch.

**Comment by RainbowMiner** [comment]
Added. It is names "AllowZero" in pools.config.txt. Set to "1", if you want to allow mining alogrithms with pool's hashrate equal to 0. I will push a release.

**Comment by RainbowMiner** [comment]
Release is out. Make sure you set BsodSolo's "AllowZero" to "1" in pools.config.txt, now. I put back the hashrate check into the BsodSolo.ps1 to be consistent.
