### ISSUE TITLE
AutoPriceModifierPercent not working with a negative value like it says in RBM docs

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2183]
![image](https://user-images.githubusercontent.com/97480060/193420261-0ef2b3de-2ae0-4361-80ff-ac13968f765a.png)
![image](https://user-images.githubusercontent.com/97480060/193420336-1fa67c2e-2e31-4d5c-95c9-658cdbfc6ac0.png)
![image](https://user-images.githubusercontent.com/97480060/193420315-1a1ca793-7590-42a5-9359-a4e1f6aea4c3.png)

**Comment by RainbowMiner** [comment]
Please check in `.\Config\mrralgorithms.config.txt` for that specific rig's algorithm, if the "AutoPriceModifierPercent" is empty and not set to "5"

**Comment by astitsa** [comment]
They are all empty cause I did not set any in this file.

Don't worry I already got this logic order in mind.

My feeling is there is a -(-1) somewhere in the code or MRR just doesn't allow negative modifier

**Comment by RainbowMiner** [comment]
Ahh!! It's easier. RainbowMiner does everything allright. MRR separates the -/+ information into a radiofield selection:
![image](https://user-images.githubusercontent.com/39437538/193428104-22187fb5-f99f-4f43-8051-3c84989354bc.png)

**Comment by astitsa** [comment]
omg I was blind ... so counter intuitive 

sorry for the waste of time

**Comment by RainbowMiner** [comment]
> omg I was blind ... so counter intuitive
> 
> sorry for the waste of time

No problem :) Now we know forever.

**Comment by astitsa** [comment]
Sounds like a true statement ;)
