### ISSUE TITLE
Issues Batch no1

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2185]
Hallo again,
Here are some issues or suggestions i have.

1) If rigs have been created with a PriceFactor of 1.8 and i change it after the creation to 2.0, prices are not affected in mrr.

2) Renaming rigs. it would be awesome if i had the opportunity to mass rename the rigs after their creation. I tried changing the "title" from default to  "Title": "%algorithmex% mining with RainbowMiner rig P4 %rigid%", but it didnt update the rigs. Instead i deleted them all and let it create them again.

3) I made some changes to my 6 core 12 thread cpu to only mine yespower with 6 cores instead of all 12 threads. This resulted in higher hashrates. These higher hashrates were never changed automatically in mrr.

4) In one of my pcs, i have 1 nvidia and 1 amd card. Bzminer buged in on benchmark resulting in "profits" of 11800 euros a day and changed all prices in mrr to accomodate that. I put ot in excluded miners and deleted the hashrates. I tried deleting all rigs and creating them again with no luck. I resetprofit.bat with no result again. More that 24 hours has passed and no change in prices. It would be nice to have a failsafe not only to mrr, but rbm itself to protect and ban miners that appear to have so high profits.

5) I have 8 pcs that have rigs on mrr. Only 1 or 2 of them managed to create rigs on algo MinotaurX. I created them by myself, rbm detected them, renamed them, but they alwayes appear to be offline. No rentals or benchamrks in progress and still offline.

6) Miners verthash and verthashsp are running only in background. No matter if ShowMinerWindows --> 1

7) Miner SRBminer2 or Cryptonightsrbminer whatever its name is. It is reporting wrong hashrates on my 480, 570 and 550. i've tested it in different pools and the result was the same. 1.8kh in srbminer but 400h in pools. I have it in excluded miners now, but i thought you wouldlike to know it.

8) Benchmark only changes in miners. Meaning: Srbminermulti new release especially with mrr enabled. 80 benchmarks. For no reason, maybe an algo was added. It would be great to only benchmark that one algo instead of all the supported algorithms in that miner. No idea how it could be done. Just Wishfull thinking!! 

Thanks in advance!

**Comment by papadrams** [comment]
About no5) I dont know how or why but: In a pc that minotaurx is avaliable to be rented in mrr, there is a file in stats-pools miningrigrentals_minotaurx_profit.
In pcs that minotaurx isnt being created or if i create them by hand it is always offline, that file does not exist at all.
I hope this helps.

**Comment by RainbowMiner** [comment]
> 1. If rigs have been created with a PriceFactor of 1.8 and i change it after the creation to 2.0, prices are not affected in mrr.

That should change your prices. For this to ceck, I'll need another debug file. Maybe check parameter "AutoUpdateMinPriceChangePercent", too. Set it something low, like "3"

> 2. Renaming rigs. it would be awesome if i had the opportunity to mass rename the rigs after their creation. I tried changing the "title" from default to  "Title": "%algorithmex% mining with RainbowMiner rig P4 %rigid%", but it didnt update the rigs. Instead i deleted them all and let it create them again.

That's already implemented: just set the parameter "EnableUpdateTitle" to "1" in pools.config.txt (for description mass updates the parameter is "EnableUpdateDescription")

> 3. I made some changes to my 6 core 12 thread cpu to only mine yespower with 6 cores instead of all 12 threads. This resulted in higher hashrates. These higher hashrates were never changed automatically in mrr.

They should have been updated. If not, then there is some problem.

> 4. n one of my pcs, i have 1 nvidia and 1 amd card. Bzminer buged in on benchmark resulting in "profits" of 11800 euros a day and changed all prices in mrr to accomodate that. I put ot in excluded miners and deleted the hashrates. I tried deleting all rigs and creating them again with no luck. I resetprofit.bat with no result again. More that 24 hours has passed and no change in prices. It would be nice to have a failsafe not only to mrr, but rbm itself to protect and ban miners that appear to have so high profits.

Oh man! That's a lot. Which algorithm did the 11800 magic? Was it mining on AMD or NVIDIA?

> 5. I have 8 pcs that have rigs on mrr. Only 1 or 2 of them managed to create rigs on algo MinotaurX. I created them by myself, rbm detected them, renamed them, but they alwayes appear to be offline. No rentals or benchamrks in progress and still offline.

What I could imagine is, that it's below the CPU profitability threshold on these machines.

> 6. Miners verthash and verthashsp are running only in background. No matter if ShowMinerWindows --> 1

Yes, that is intended. Both miners do not have a build-in API, so that we need to grab and parse their screen output. This can only be done in the form of a background job. But you find their output in the `.\Logs` folder.

> 7. Miner SRBminer2 or Cryptonightsrbminer whatever its name is. It is reporting wrong hashrates on my 480, 570 and 550. i've tested it in different pools and the result was the same. 1.8kh in srbminer but 400h in pools. I have it in excluded miners now, but i thought you wouldlike to know it.

That's a pretty old miner. Thank you for reminding me, I'll double-check and probably retire it.

> 8. Benchmark only changes in miners. Meaning: Srbminermulti new release especially with mrr enabled. 80 benchmarks. For no reason, maybe an algo was added. It would be great to only benchmark that one algo instead of all the supported algorithms in that miner. No idea how it could be done. Just Wishfull thinking!!

In fact a wonderful wish! I have implemented the redux-benchmarks now. Unfortunately, it now needs some time: it will kick in for the next resp. over-next miner updates, automatically.

**Comment by papadrams** [comment]
>1) If rigs have been created with a PriceFactor of 1.8 and i change it after the creation to 2.0, prices are not affected in mrr.
That should change your prices. For this to ceck, I'll need another debug file. Maybe check parameter "AutoUpdateMinPriceChangePercent", too. Set it something low, like "3"

I will check again. "AutoUpdateMinPriceChangePercent" is default at 3 on all of my rigs

>2) Renaming rigs. it would be awesome if i had the opportunity to mass rename the rigs after their creation. I tried changing the "title" from default to "Title": "%algorithmex% mining with RainbowMiner rig P4 %rigid%", but it didnt update the rigs. Instead i deleted them all and let it create them again.
That's already implemented: just set the parameter "EnableUpdateTitle" to "1" in pools.config.txt (for description mass updates the parameter is "EnableUpdateDescription")

These are enabled. Maybe it needed more time. I;ll come back with an answer in 24 hours.

>3) I made some changes to my 6 core 12 thread cpu to only mine yespower with 6 cores instead of all 12 threads. This resulted in higher hashrates. These higher hashrates were never changed automatically in mrr.
They should have been updated. If not, then there is some problem.

Indeed they updated after i posted this. It needed more time propably. **BUT** there is an issue here. Ghostrider and Mike hashrates. They change all the time and along with that the "ranking" in profitability. That causes a lot of issues especially in mrr. I have a rented rig with advertised hashrate of 1.4kh while my real speed is closer to 1kh. I know exactly my 24 hour hashrates in those algos for all of my machines. Is there a way to lock that hashrate in both mrr and rbm itself? And to have the ability to unlock it if and when an improvement is made by a miner in those algorithms?

> 4) In one of my pcs, i have 1 nvidia and 1 amd card. Bzminer buged in on benchmark resulting in "profits" of 11800 euros a day and changed all prices in mrr to accomodate that. I put ot in excluded miners and deleted the hashrates. I tried deleting all rigs and creating them again with no luck. I resetprofit.bat with no result again. More that 24 hours has passed and no change in prices. It would be nice to have a failsafe not only to mrr, but rbm itself to protect and ban miners that appear to have so high profits.
Oh man! That's a lot. Which algorithm did the 11800 magic? Was it mining on AMD or NVIDIA?

It was Bzminer on amd. I cant remember the algorithm. I am sending a debug file to your mail in case you can figure out what it was. I think 4 days have passed and my rig prices are still through the roof. I changed some prices in mrr by hand in some regurarly rented algos in mrr. But most of them have still a rig price of 74. I hope you can find a way to bring it back to normal.

> 5) I have 8 pcs that have rigs on mrr. Only 1 or 2 of them managed to create rigs on algo MinotaurX. I created them by myself, rbm detected them, renamed them, but they alwayes appear to be offline. No rentals or benchamrks in progress and still offline.
What I could imagine is, that it's below the CPU profitability threshold on these machines.

It is not below the cpu profitability on any of those machines. I have changed the miningrigrentals.ps1 for $AutoCreateMinCPUProfitBTC = "0.000001" and
$RigMinProfit = 0.000001
Also in pools.config.txt
"AutoCreateMinCPUProfitBTC": "0.000001"
On a rig i created this algo by hand in mrr, it has been detected by rbm and changed the title, description, price and minimum hours. It is in minimum hours 4 and minimum rented price of 0.00000146. I am sending a debug file for this as well. (Currently this cpu is rented, but even if its not rented, it appears offline and disabled.

8) **AWESOME**

**Comment by papadrams** [comment]
I did and i got this
![Screenshot_99](https://user-images.githubusercontent.com/36564393/194307286-224bff45-c67a-4962-82a3-e04ac6937741.jpg)

**Comment by RainbowMiner** [comment]
Ok, so delete the `.\Stats\MRR\<workername>.txt` files, too. Important: do NOT delete files, that end with `*_rental.txt`

**Comment by RainbowMiner** [comment]
.. and just to be sure, since the Bzminer is disabled, remove the according stats `.\Stats\Miners\AMD-Bzminer*_hashrate.txt`, too. Just to be sure.

**Comment by papadrams** [comment]
Done
I still get the same message. I suppose i am waiting now?

**Comment by RainbowMiner** [comment]
Yes - in fact, RainbowMiner waits 3 hours, so that the averages in the `Profit_*.txt` files are accurate.

**Comment by papadrams** [comment]
i am still getting the same error message
![Uploading Screenshot_102.jpg…]()
