### ISSUE TITLE
mrr port cache problem

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2187]
just so you don't forget this one cause it's flagged solved ;)

https://github.com/RainbowMiner/RainbowMiner/issues/2178

**Comment by RainbowMiner** [comment]
It should cache ports for 2 intervals, only. I'll check the logic.

**Comment by astitsa** [comment]
what about if the rent cannot connect successfully it clears the cache for that algo to get the new port ?

**Comment by astitsa** [comment]
![image](https://user-images.githubusercontent.com/97480060/193740554-978ac9a8-895d-48b2-8f59-a9bb6c89578f.png)

**Comment by RainbowMiner** [comment]
That is really odd. There is one last thing I could imagine - if a port isn't sent via API, Rainbowminer uses default ports 3333 and 3344. So maybe there are some algos, that fail to supply a port via API. I will check this.

**Comment by RainbowMiner** [comment]
> I will check this.

The API returns the correct port for my rigs. I have checked multiple, especially Octopus.
BUT - I might have found the reason for the problems you are experiencing. It's the use of "UseHost" - if this is set, RainbowMiner uses deprecated port information. For most algorithms, that's no problem, but for some in fact it is. I'll fix this now.

**Comment by RainbowMiner** [comment]
Yes! That did solve the problem. Thank you for reporting this again!

**Comment by astitsa** [comment]
Nice thanks for your work !

I will keep you posted there is still a prob
