### ISSUE TITLE
review BSODsolo mining mode

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#219]
when using BSODSolo as a regular pool it makes sense to mine with all devices possible and not split power to other pools. Maybe changing temporarily to Legacy mining mode while solo pool is in effect.

When AllowZero = 1 and FocusWallet is set it does not react as quick as it use to when just setting FocusWallet. It took a few cycles to start mining the coin of the FocusWallet and only on one device group, the odds are decreased splitting the max available power.
![image](https://user-images.githubusercontent.com/41829368/47058635-19e29200-d183-11e8-8d83-2ae11a232498.png)

![image](https://user-images.githubusercontent.com/41829368/47058608-f6b7e280-d182-11e8-8ea9-48f616c62ffb.png)

**Comment by hernandn01** [comment]
BSOD Api has been spotty (maybe query less often). The same is true for all other APIs several times a failed warning message is shown for this and other pools. How are the intervals. maybe increase the main interval? I had "Interval": 120, but now I have increase it to 180. I think 2 minutes is too often.

Anyway, the comment for this, I think the Api call failed for Solo mine and the fallback quick in. But, the miners ( or miner if change to Legacy) was mining and a check should be in place to disregard api failure if hashrate continues .

**Comment by RainbowMiner** [comment]
It is in deed an API fail on the pool. I have an idea of how to solve it. I plan to implement a skip over fail function, that will gracefully react to failing pool APIs.

**Comment by RainbowMiner** [comment]
I integrated graceful failover to the API calls. Meaning: it accepts upto five fails in a row, until an error is propagated.
