### ISSUE TITLE
TRM kaspa not benchmarking

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2193]
Hallo,
as the title suggests, trm does not benchmark on my amd rx570. It doesnt even bother. It is not failing. It just acts like kaspa doesnt exist. According to their github it is supported in polaris gpus.
Also devfee is 1% not 2.5%

**Comment by RainbowMiner** [comment]
Thank you for reporting this! It's fixed.

**Comment by papadrams** [comment]
Anytime!! When you have the time check the batch issue once more please.

**Comment by appsettings** [comment]
Hi, I have the same issue. I manually applied the updated Teamred.ps1 file, but now teamred fails continuosly during benchmark.
I believe it is passing wrong algo argument (kHeavyHash instead of kas).
Thanks @RainbowMiner

**Comment by papadrams** [comment]
Yeah, mine too..

**Comment by RainbowMiner** [comment]
Oh! Sorry for that. I misused a parameter. With the last change, Kaspa should benchmark.
