### ISSUE TITLE
Bittube (cuckaroo29b) 0 profit on Herominers

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2197]
While using rbm with herominers, tube profit is 0 and doesnt even appear on rbm. I deleted the herominers.tube profit and ita been recreated again with 0 profit.

**Comment by papadrams** [comment]
Actually its not just Tube, but pretty much everycoin in herominers. At different times, at different rigs, some coins dissappear, or some are saying uknown profit. Scala, Keva, Tube, haven etc

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll check what is going on with the Herominers.
