### ISSUE TITLE
Configuration stuck at msi profile selection

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#22]
Seems to be a bug in the configuration selection of MSI profiles. 
![image](https://user-images.githubusercontent.com/35561346/44206709-f1c2bc80-a15a-11e8-850d-e5181b58b2c5.png)

**Comment by RainbowMiner** [comment]
Oh dear :) Yes. This is a bug, I put into the last release. I will change it at once.

**Comment by RainbowMiner** [comment]
There is a path available at https://github.com/RainbowMiner/RainbowMiner/issues/21#issuecomment-413603714
