### ISSUE TITLE
FireIce 2.5.0 benchmark failure

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#220]
Benchmark of Cryptonight algos fails with newest fireIce release on my rig. The older one worked fine after configuring bfactor,threds etc in ncivida config file. When I copy that into this directory the miner crashes when benchmark starts. Any ideas?

![image](https://user-images.githubusercontent.com/35561346/47073417-8d72b680-d1f8-11e8-9b1f-0e9fdae08224.png)

Configuration looks like:
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9308/11264 MiB
  //      smx: 28
  { "index" : 4,
    "threads" : 26, "blocks" : 84,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,

**Comment by ebojali** [comment]
Please close, I found the issue. The config files are not compatible like you have already stated in a realease note of the version where you updated the miner! :)

**Comment by RainbowMiner** [comment]
Ok, I am happy, if all runs fine.
