### ISSUE TITLE
Unable to autocreate rigs on MrR

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2200]
Hallo again!
I had recently added an nvidia gpu to an instalation of rbm. Unfortunately it wasnt able to create rigs. Autocreate was (1). I thought that i need to do a clean install. So i did. I created a new instance of rbm. Nothing copied from the previous one.
Its 2 nvidia cards, 1 1060 6gb and 1 1660 super 6gb. and a ryzen cpu.
everything benchmarked as they shouls with the msi profiles i had per algorithm.
I created a new api key on mrr just to be sure.
I left it all night and when i woke up only cpu rigs were automatically made. No gpu rigs at all.
I have the same settings on pools.config on all my other machines and they were created fine.
The only difference i have is that in this rig i have MiningMode in legacy cause i had issues running 2 instances of miniz.
What i have observed is that there is no profit.gpu in stats folder and file workername.txt on stats --> mrr folder is empty while workernamecpu.txt has values in it.
Thanks in advance

[debug_2022-10-28.zip](https://github.com/RainbowMiner/RainbowMiner/files/9891033/debug_2022-10-28.zip)

**Comment by RainbowMiner** [comment]
Hi, I am currently at a seminar, maybe I might be able to look into it in the evening. If not - I hope it's not too big of an annoyance until I can check on Wednesday.

**Comment by papadrams** [comment]
No worries man!

**Comment by papadrams** [comment]
Have you got the chance to check on this?

**Comment by papadrams** [comment]
@RainbowMiner

**Comment by RainbowMiner** [comment]
> Have you got the chance to check on this?

Ah, sorry. I have had pretty much on my plate the past days. I will get to it this weekend.

**Comment by papadrams** [comment]
@RainbowMiner Hallo!!!!
I guess you had no time to check it. 
Please when you have the time help me.
Also you disabled icemining pool. Propably because the stopped their epic pool. But their nimiq pool is still online and works great. No plans to stop it as well. Please consider reenabling it.

**Comment by RainbowMiner** [comment]
In fact, I have been deep down under work, the past couple weeks. I'll try to get to it the next days. 
Thank you for hinting to the Icemining pool. I will re-enable it.
