### ISSUE TITLE
4.8.7.2 - Cannot convert argument "microsecond", with value: "Utc", for ".ctor" to type "System.Int32":

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#2208]
I just updated from PowerShell 7.2.7 to 7.3.0 and RM 4.8.7.1 to 4.8.7.2 and have started to get the following error:

```
.. loading WhatToMine MethodException: Cannot convert argument "microsecond", with value: "Utc", for ".ctor" to type "System.Int32": "Cannot convert value "Utc" to type
"System.Int32". Error: "The input string 'Utc' was not in a correct format.""
MethodException: Cannot convert argument "microsecond", with value: "Utc", for ".ctor" to type "System.Int32": "Cannot convert value "Utc" to type
"System.Int32". Error: "The input string 'Utc' was not in a correct format.""
done (0s)
Loading miner modules ..
```

I'm running RM on Windows 10 Pro 22H2 (OS Build 19045.2251).

I'm not sure if something has gone funky with my setup, or if this is an issue triggered by PowerShell 7.3.0?
[debug_2022-11-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/9993830/debug_2022-11-12.zip)

**Comment by RainbowMiner** [comment]
That is most probably an incompatibility with PowerShell 7.3.0 - for the time being, please downgrade to PowerShell 7.2.7. I will make the upgrade check and updates soon.

**Comment by RainbowMiner** [comment]
Ok, that last commit should solve that datetime incompatibility for Powershell 7.3.0 while maintaining backwards compatibility down to Powershell 5

**Comment by AnthonyBe** [comment]
Just gave it a quick run - all errors gone.
Looks good!
Thank-you!

**Comment by RainbowMiner** [comment]
Very good! I have just finished my compatibility runs against the new Powershell Core 7.3.0 too and all looks fine, now.

**Comment by RainbowMiner** [comment]
Please have a look into the #2211 headsup announcement. It seems like the Powershell Core 7.3.0 has some really bad memory leak. Check the memory usage in the current `Logs\RainbowMiner_2022-MM-DD.txt` file. Just open it with some text editor and search "Memory usage". The value to be expected should be around or below 300MB.
