### ISSUE TITLE
Low difficulty share

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#221]
can this be prevented? The miner is reporting hashrate but all are rejected

![image](https://user-images.githubusercontent.com/41829368/47084696-87b5aa80-d1d1-11e8-95eb-40f91997780b.png)

**Comment by RainbowMiner** [comment]
Hm, that is a difficult one. I will have a look.

**Comment by RainbowMiner** [comment]
Which currency have you been mining, at which pool?

**Comment by hernandn01** [comment]
allium at ahashpool

**Comment by hernandn01** [comment]
I think the pool set the difficulty incorrectly for allium at least at that time. That just appear in the mix. I did not force it especially on Ahashpool. An overriding setting  of "d=xxx" per algo/miner would be a good solution

**Comment by RainbowMiner** [comment]
Solved with #247
