### ISSUE TITLE
AMD Radeon Pro WX2100

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#2212]
Hey, I have an older AMD Radeon Pro WX2100, OpenCL recognizes the device but RBM doesn't. Its an ubuntu 22.04 system.

Is there something I am over looking that may be blocking it from being seen? I've been messing with the drivers for sometime thinking that was it. Thought I would ask if I am missing something obvious
[debug_2022-11-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/10126358/debug_2022-11-30.zip)
?

**Comment by Yamanipanuchi** [comment]
Meh, As I dig further it looks like its just drivers. The Ubuntu/Linux default drivers give me the basics but nothing further and because there odd ball cards from AMD they need specific drivers. The drivers that do work are for 18.04... 

Unless you see something obvios?

**Comment by RainbowMiner** [comment]
I have had a look into your debug file, neither RainbowMiner nor the single miners can find the GPU. So it's most probably a driver issue.

**Comment by Yamanipanuchi** [comment]
Okay, I found it... There was a part of the drivers that were not installing correctly. Thank again for looking!
