### ISSUE TITLE
BzMiner fails to mine

### ISSUE THREAD

**Issue by smyers63** [RainbowMiner/RainbowMiner#2213]
I see this on all the benchmark logs:

*************************

**                     **

**   BzMiner v12.1.1   **

**                     **

*************************

 Language: English

 Working Directory: C:\Users\Scott-miner\Downloads\RainbowMinerV4.8.7.2_win\Bin\GPU-BzMiner

 Logging to: bzminer_33200.log

 Cuda: 11.8

 Nvidia Driver: 522.25

 ----------------------------------------------- devices ---------------------------------------------

 | # | name                                           | free | total | core | mem | fan | pwr | temp | 

 |   |                                                |      |       |      |     |     | 0w  |      |

 12-03 05:15:07:231 -------------------------------------------------------------------------- v12.1.1

 <Warn> GPU 3:0: disabled. Set start_mining to true to enable.

 <Warn> GPU 4:0: disabled. Set start_mining to true to enable.

 <Warn> GPU 5:0: disabled. Set start_mining to true to enable.

 <Warn> No devices mining. Check config

 HTTP API Listening on 0.0.0.0:33200

 ----------------------------------------------- devices ---------------------------------------------

 | # | name                                           | free | total | core | mem | fan | pwr | temp | 

 |   |                                                |      |       |      |     |     | 0w  |      |

 12-03 05:15:23:329 -------------------------------------------------------------------------- v12.1.1

 ----------------------------------------------- devices ---------------------------------------------

 | # | name                                           | free | total | core | mem | fan | pwr | temp | 

 |   |                                                |      |       |      |     |     | 0w  |      |

 12-03 05:15:38:812 -------------------------------------------------------------------------- v12.1.1

**Comment by RainbowMiner** [comment]
This looks like a GPU detection/alignment problem. Could you please create a Debug file on localhost:4000 and upload it here?

**Comment by smyers63** [comment]
[debug_2022-12-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/10155369/debug_2022-12-05.zip)

**Comment by smyers63** [comment]
Any news?

**Comment by RainbowMiner** [comment]
I have totally forgotten about your problem. Sorry! Will look into it now.

**Comment by RainbowMiner** [comment]
Ok. Solved.

**Comment by smyers63** [comment]
I've exited and started RBM again but no change.  What do I need to do to obtain that update?

**Comment by smyers63** [comment]
BzMiner is still not running with the new BzMiner.ps1.

Error parsing command line arguments
The following arguments were not expected: 0 --blockchain_fee
Run with --help for more information.

Error parsing command line arguments
The following arguments were not expected: 0 --community_fund
Run with --help for more information.

**Comment by smyers63** [comment]
I went ahead today and did a copy\paste for the BzMiner fix.  All the benchmarks have worked.  Thanks.
