### ISSUE TITLE
Balances for MiningPoolHubCoins missing for the past several days

### ISSUE THREAD

**Issue by smyers63** [RainbowMiner/RainbowMiner#2217]
The user and API information are still correct.  I don't know what else to look at.

Are there settings that can enable/disable balance display by pool or is that only a global setting?

**Comment by smyers63** [comment]
I've just sent some manual API queries and I get the correct data back, such as {"getuserbalance":{"version":"1.0.0","runtime":6.637096405029297,"data":{"confirmed":29.06541195,"unconfirmed":0}}} .  No data for the coins in this pool shows up in RBM.

**Comment by UselessGuru** [comment]
Issue is caused by missing information in the pool API:

https://bitcointalk.org/index.php?topic=472510.7660

**Comment by RainbowMiner** [comment]
Oh! Super and thanks a lot for the link. So there is currently nothing we can do but wait for MPH to fix this.

**Comment by smyers63** [comment]
Using "getuserbalance" (not "getuserallbalances") means you know which coin you're querying but the query goes to the coin's subdomain instead of just "miningpoolhub.com."  That's how I got the data in my first example earlier.

**Comment by UselessGuru** [comment]
>> and we already know that's Ravencoin because that's the coin we queried

Yes. But:
The list of coin names is dynamic. So we need to get this from the pools API. This is why we first try to get the list of all coin names with 'getuserallbalances'.

To keep API requests to a minimum we then iterate through all coins with balance and query 'getuserbalance' for each coin.

-> No coin name list -> no balances :-(

**Comment by smyers63** [comment]
I understand.  But:

What I'm talking about will work even if MPH never fixes the current problem and they are not quick with making fixes.  It took 6 months to get a fix for a problem I reported to them.  The list of coins is right there at https://miningpoolhub.com/.

[Auroracoin (Qubit)](https://auroracoin-qubit.miningpoolhub.com/)
    [Bitcoin](https://bitcoin.miningpoolhub.com/)
    [Bitcoin-Cash](https://bitcoin-cash.miningpoolhub.com/)
    [Bitcoin-Gold](https://bitcoin-gold.miningpoolhub.com/)
    [Dash](https://dash.miningpoolhub.com/)
    [Digibyte (Qubit)](https://digibyte-qubit.miningpoolhub.com/)
    [Digibyte (Skein)](https://digibyte-skein.miningpoolhub.com/)
    [Ethereum](https://ethereum.miningpoolhub.com/)
    [Ethereum-Classic](https://ethereum-classic.miningpoolhub.com/)
    [Ethersocial](https://ethersocial.miningpoolhub.com/)
    [Expanse](https://expanse.miningpoolhub.com/)
    [Feathercoin](https://feathercoin.miningpoolhub.com/)
    [Globalboosty](https://globalboosty.miningpoolhub.com/)
    [Groestlcoin](https://groestlcoin.miningpoolhub.com/)
    [Litecoin](https://litecoin.miningpoolhub.com/)
    [Maxcoin](https://maxcoin.miningpoolhub.com/)
    [Monacoin](https://monacoin.miningpoolhub.com/)
    [Monero](https://monero.miningpoolhub.com/)
    [Myriadcoin (Groestl)](https://myriadcoin-groestl.miningpoolhub.com/)
    [Myriadcoin (Yescrypt)](https://myriadcoin-yescrypt.miningpoolhub.com/)
    [Ravencoin](https://ravencoin.miningpoolhub.com/)
    [Startcoin](https://startcoin.miningpoolhub.com/)
    [Vertcoin](https://vertcoin.miningpoolhub.com/)
    [Zcash](https://zcash.miningpoolhub.com/)
    [Zclassic](https://zclassic.miningpoolhub.com/)
    [Zcoin](https://zcoin.miningpoolhub.com/)
    [Zencash](https://zencash.miningpoolhub.com/)

**Comment by UselessGuru** [comment]
> The list of coins is right there

Not quite. 
a) This list is not available through the API
b) It is not always possible to derive the the coin's subdomain from the above list.

> If getuserallbalances was working, wouldn't you already have everything?

No, because this gives you only 'confirmed' value, but not the other values like 'ae_confirmed' etc.

**Comment by RainbowMiner** [comment]
> I have little to no faith they will correct this one anytime soon.

In fact, we could add a manual list of the coins. That involves some work and we cannot use the ae_* values. But - at least we would have some balance. I'll try this as a quick-fix until the MPH devs fix their API. Secondly I'll directly contact the MPH devs.

**Comment by UselessGuru** [comment]
> Secondly I'll directly contact the MPH devs

How dou you contact them directly?

**Comment by RainbowMiner** [comment]
> How dou you contact them directly?

I have some ancient email address, that worked a decade ago. Maybe that still works.

**Comment by RainbowMiner** [comment]
> In fact, we could add a manual list of the coins. That involves some work and we cannot use the ae_* values. But - at least we would have some balance. I'll try this as a quick-fix until the MPH devs fix their API. Secondly I'll directly contact the MPH devs.

That workaround will need you to set all coin symbols in parameter CoinSymbol in pools.config.txt. Otherwise we do not know which singular API endpoints to call.

**Comment by RainbowMiner** [comment]
Ok, I have added a workaround. As already explained, you will now have to explicitly set all coin symbols, that you wish to show the pool balance, in parameter "CoinSymbol" in pools.config.txt.

**Comment by smyers63** [comment]
Answering a question back a few posts: MPH has a few contact methods listed on the site at https://miningpoolhub.com/.

"Forum
Discuss, ask general questions about pool minig and miningpoolhub usage. Read Quick start guide and [FAQ](https://miningpoolhub.com/?page=gettingstarted) before you ask.

    [Twitter @MiningPoolHub](https://twitter.com/MiningPoolHub)
    [Bitcointalk](https://bitcointalk.org/index.php?topic=472510.0)
    [Reddit](https://www.reddit.com/r/MiningPoolHub)

Contact
Please send email if you want to receive official reply from us. We reply to all your emails.

    Email: contact@miningpoolhub.com"

I'll check out the fix you've worked up.  Thanks.

**Comment by smyers63** [comment]
I thought the file would be updated automatically but since it hadn't yet, I copied and pasted the new script into a new file here.  There's a typo, I think, in it.  In the localhost console, I got:

PS>TerminatingError(): "Exception setting "RequestUri": "Cannot convert value "http://myriadcoin-yescrypt myriadcoin-groestl.miningpoolhub.com/index.php ...

Looks like this should be "myriadcoin-yescrypt.miningpoolhub.com."  The balance for Myriadcoin-Yescrypt (XMY) doesn't appear.  The rest of my balances are there now.

Thanks.

**Comment by smyers63** [comment]
I thought the file would be updated automatically but since it hadn't yet, I copied and pasted the new script into a new file here.  There's a typo somewhere I haven't found yet - looks like it's in a file referenced by this one.  In the localhost console, I got:

PS>TerminatingError(): "Exception setting "RequestUri": "Cannot convert value "http://myriadcoin-yescrypt myriadcoin-groestl.miningpoolhub.com/index.php ...

Looks like this should be "myriadcoin-yescrypt.miningpoolhub.com."  The balance for Myriadcoin-Yescrypt (XMY) doesn't appear.  The rest of my balances are there now.

Thanks.

**Comment by UselessGuru** [comment]
Any luck contacting MPH? Please also see my PM in discord.

**Comment by smyers63** [comment]
> I thought the file would be updated automatically but since it hadn't yet, I copied and pasted the new script into a new file here (on my system). There's a typo somewhere I haven't found yet - looks like it's in a file referenced by this one. In the localhost console, I got:
> 
> PS>TerminatingError(): "Exception setting "RequestUri": "Cannot convert value "http://myriadcoin-yescrypt myriadcoin-groestl.miningpoolhub.com/index.php ...
> 
> Looks like this should be "myriadcoin-yescrypt.miningpoolhub.com." The balance for Myriadcoin-Yescrypt (XMY) doesn't appear. The rest of my balances are there now.
> 
> Thanks.
