### ISSUE TITLE
Add some CryptoNight pools

### ISSUE THREAD

**Issue by giannibonfanti** [RainbowMiner/RainbowMiner#222]
It can be possible? CryptoNight pools apis are quite different from the yiimp based.
For example: https://miner.rocks/ or https://cryptoknight.cc

I think profit estimate can be taken from
https://bittube.miner.rocks/api/stats
or 
https://cryptoknight.cc/rpc/stellite/live_stats

and use the charts -> profit values

And maybe this schema can be expanded to many other cryptonight pools!

**Comment by RainbowMiner** [comment]
Yea, why not :) Are these two pools good and save pools?

**Comment by hernandn01** [comment]
I have used this without a problem
https://www.supportxmr.com/#/home

**Comment by giannibonfanti** [comment]
I did not use them directly so I cannot tell, and each coin has it best pool.
I listed that two pools taking the one with best hashrate for bittube and stellite, based on https://miningpoolstats.stream , and they are also multicoin pool.
Supportxmr is for monero, good hashrate

**Comment by jch9678** [comment]
I use both those pools, miner.rocks and cryptoknight.cc, and they work fine.

**Comment by RainbowMiner** [comment]
Ok. Working on cryptoknight.cc - not really an easy task, but faisable.

**Comment by RainbowMiner** [comment]
CryptoKnight.cc added 🍰 - happy mining!

**Comment by jch9678** [comment]
Thanks this is going to be great.  I manually added it to the config, is that the right way?

**Comment by RainbowMiner** [comment]
Miner.rocks added 🍥 - happy mining! (with next release)

> Thanks this is going to be great. I manually added it to the config, is that the right way?

Yes, this is the way. Just add `CryptoKnight` and/or `MinerRocks`  to "PoolName" list in config.txt or use the [C]onfiguration->[S]elections to add (enter `+Cryptoknight,MinerRocks` and they both will be added

**Comment by giannibonfanti** [comment]
Awesome 🏆
