### ISSUE TITLE
bzMiner 12.2.0 is out

### ISSUE THREAD

**Issue by MattF42** [RainbowMiner/RainbowMiner#2229]
https://github.com/bzminer/bzminer/releases

**Comment by RainbowMiner** [comment]
Thanks! An update will follow asap

**Comment by MattF42** [comment]
In fact one of the parameters got broken, so just bumping the version breaks it :(

I've submitted a PR to fix it

**Comment by MattF42** [comment]
Clean PR at `https://github.com/RainbowMiner/RainbowMiner/pull/2237`
