### ISSUE TITLE
Review Combo mining mode

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#223]
Would you please review the mining modes? I usually use Combo mining mode but for a while now that looks like Device Mining mode. Tried Legacy mining mode and that did not used only one miner for all cards, it behave also like Device.

![image](https://user-images.githubusercontent.com/41829368/47090809-db7bc000-d1e0-11e8-9cef-4760df4d3c05.png)

![image](https://user-images.githubusercontent.com/41829368/47090890-0c5bf500-d1e1-11e8-9295-aca81c2a5fd8.png)

**Comment by RainbowMiner** [comment]
Ok,  I will have a look.

**Comment by RainbowMiner** [comment]
Did you restart RainbowMiner after changing this setting? I ask, because this is the only setting, which needs a complete restart.

**Comment by hernandn01** [comment]
no, I did not. I thought I have changed that without restarting before. In any case, I always started with Combo, and I think I saw 8 different combos before but it always start with 3 like Device

**Comment by RainbowMiner** [comment]
Ok, so either, the relevant combos are less profitable than the single miners, or something is wrong. It would be interesting, what the stats say. Would you zip-drop the Stats\Miners folder here? Then I can look into it.

**Comment by hernandn01** [comment]
[Miners.zip](https://github.com/RainbowMiner/RainbowMiner/files/2491778/Miners.zip)

**Comment by hernandn01** [comment]
just when I was loading the stat-> miners.zip file, I saw a warning on the saying stat\miners folder is corrupt and will be delete it, I couldn't capture but I am seeing the folder fine, only the last 3 files were updated
![image](https://user-images.githubusercontent.com/41829368/47153512-1a6f4b80-d29d-11e8-8257-5a97413025d2.png)

**Comment by RainbowMiner** [comment]
Would you provide me with your miners.config.txt, also?

**Comment by hernandn01** [comment]
[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2493462/miners.config.txt)

**Comment by RainbowMiner** [comment]
Very weird! Your stats indicate, that no combos have been build. What is the browser output of http://localhost:4000/devicecombos ?

**Comment by hernandn01** [comment]
is it by any chance COMBOS and not COMBO?

"MiningMode": "COMBO",

![image](https://user-images.githubusercontent.com/41829368/47183662-d3597880-d2e5-11e8-903a-a999962e5c52.png)

**Comment by RainbowMiner** [comment]
The config value "combo" is correct ("MiningMode": "combo",)
.. would you also send me your config.txt, please?

**Comment by hernandn01** [comment]
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2493910/config.txt)

**Comment by RainbowMiner** [comment]
I found it and will fix this asap. Thank you very much for bringing this up!

**Comment by RainbowMiner** [comment]
Fixed. I will push a new release, which includes the changes.
