### ISSUE TITLE
Radiant / SHA512256d not getting selected unless forced with FocusWallet

### ISSUE THREAD

**Issue by MattF42** [RainbowMiner/RainbowMiner#2230]
Following on from

[https://github.com/RainbowMiner/RainbowMiner/issues/2190](url)

If I set FocusWallet to RXD on Rplant, then fine it picks Radiant - but I suspect it's going to do that regardless of the profitability.  
If FocusWallet isn't set then Radiant gets ignored, despite me having an RX6700XT in the rig which I'm pretty sure should be picking Radiant by some distance.

SHA512256d doesn't appear in the console - what am I doing wrong?

Radeon RX 6700 XT (GPU#00)
==========================

Miner            Fee Algorithm                  Speed    Diff Power    BTC/Day GBP/Day RVN/Day XMR/Day    TTF Accuracy Pool             PoolFee Wallet
-----            --- ---------                  -----    ---- -----    ------- ------- ------- -------    --- -------- ----             ------- ------
SgminerFancyIX     - Allium                11.87 MH/s  225.15  134W 0.00001191   0.165    9.93 0.00135 53.2 s      86% ZergPool           0.30% RDM..Bed
SgminerFancyIX     - Allium                11.87 MH/s  225.15  134W 0.00001191   0.165    9.93 0.00135 53.2 s      86% ZergPool           0.30% RDM..Bed
NBminer        2.00% Autolykos2            96.47 MH/s   6.56G  139W 0.00000785   0.109    6.54 0.00089      -      89% NiceHash           2.00% NHb..ATt
Nanominer      2.50% Autolykos2          Benchmarking       -    0W    Unknown Unknown Unknown Unknown      -      89% NiceHash           2.00% NHb..ATt
lolminer       1.00% BeamHash3             21.34  H/s       -  119W 0.00000773   0.107    6.44 0.00088      -      90% NiceHash-BEAM      2.00% NHb..ATt
WildRig        1.00% BMW512              Benchmarking       -    0W    Unknown Unknown Unknown Unknown 11.4 m      65% ZergPool           0.30% RDM..Bed
Xmrig              - CryptoNightFast2       2.18 kH/s  91.16k  136W 0.00000359   0.050    2.99 0.00041  7.5 m      77% MoneroOcean-MSR    0.68% 45D..zQ9
Teamred        2.50% CryptoNightFast2    Benchmarking       -    0W    Unknown Unknown Unknown Unknown  7.5 m      77% MoneroOcean-MSR    0.68% 45D..zQ9
SrbMinerMulti  0.85% CryptoNightGPU         2.07 kH/s  24.96k  161W 0.00001225   0.170   10.21 0.00139  3.8 m      87% MoneroOcean-XEQ    0.68% 45D..zQ9
Xmrig              - CryptoNightHeavyXhv    1.42 kH/s  37.65k  130W 0.00000674   0.093    5.62 0.00076 37.5 m      85% MoneroOcean-XHV    0.68% 45D..zQ9
Teamred        2.50% CryptoNightHeavyXhv Benchmarking       -    0W    Unknown Unknown Unknown Unknown 37.5 m      85% MoneroOcean-XHV    0.68% 45D..zQ9
Xmrig              - CryptoNightLiteUpx2   36.93 kH/s 859.14k  132W 0.00000347   0.048    2.89 0.00039  9.2 m      82% ZergPool           0.30% RDM..Bed
Teamred        2.50% CryptoNightLiteUpx2 Benchmarking       -    0W    Unknown Unknown Unknown Unknown  9.2 m      82% ZergPool           0.30% RDM..Bed
Xmrig              - CryptoNightR           1.12 kH/s  41.00k   85W 0.00000601   0.083    5.01 0.00068 21.9 m      86% MoneroOcean-SUMO   0.68% 45D..zQ9
Teamred        2.50% CryptoNightR        Benchmarking       -    0W    Unknown Unknown Unknown Unknown 21.9 m      86% MoneroOcean-SUMO   0.68% 45D..zQ9
Xmrig              - CryptoNightTurtle     10.15 kH/s   1.24M  134W 0.00000177   0.025    1.47 0.00020 30.3 m      88% MoneroOcean-IRD    0.68% 45D..zQ9
Teamred        2.50% CryptoNightTurtle   Benchmarking       -    0W    Unknown Unknown Unknown Unknown 30.3 m      88% MoneroOcean-IRD    0.68% 45D..zQ9
lolminer       1.00% Cuckaroo29b            4.85  H/s       -   91W 0.00000708   0.098    5.90 0.00080  2.1 m      88% MoneroOcean-TUBE   0.68% 45D..zQ9
lolminer       2.00% Cuckatoo32           567.92 mH/s       -  163W 0.00001328   0.184   11.07 0.00150      -      83% NiceHash           2.00% NHb..ATt
lolminer       2.00% CuckooCycle            4.88  H/s       -  110W 0.00000685   0.095    5.71 0.00078      -      92% NiceHash-AE        2.00% NHb..ATt
WildRig        1.00% CurveHash              9.29 MH/s  87.83M  177W 0.00001494   0.207   12.45 0.00169 19.8 m      82% ZergPool           0.30% RDM..Bed
SrbMinerMulti  0.85% CurveHash           Benchmarking       -    0W    Unknown Unknown Unknown Unknown 19.8 m      82% ZergPool           0.30% RDM..Bed
Gminer         2.00% Equihash (144,5)      65.39  H/s       -  173W 0.00000924   0.128    7.70 0.00105      -      87% NiceHash           2.00% NHb..ATt
lolminer       1.00% Equihash (192,7)      32.02  H/s       -   96W 0.00000732   0.101    6.10 0.00083  3.3 m      85% ZergPool           0.30% RDM..Bed
lolminer       1.00% EquihashR (125,4)     45.23  H/s       -  131W 0.00000922   0.128    7.69 0.00104      -      84% NiceHash           2.00% NHb..ATt
Gminer         1.00% EtcHash               47.35 MH/s       -  155W 0.00000835   0.116    6.96 0.00095      -      40% NiceHash           2.00% NHb..ATt
Phoenix        0.65% Ethash                46.84 MH/s       -  160W 0.00000868   0.120    7.23 0.00098      -      39% NiceHash           2.00% NHb..ATt
Teamred        …5%,- {Ethash, kHeavyHas… …77.86 MH/s} …,47.16  153W 0.00001527   0.212   12.72 0.00173 {-, -} …%, 88%} {NiceHash, Nice… …2.00%} {NHb..A…
WildRig        1.00% HMQ1725             Benchmarking       -    0W    Unknown Unknown Unknown Unknown 55.2 m      61% ZergPool           0.30% RDM..Bed
Gminer         1.00% KawPOW                22.63 MH/s       -  173W 0.00001026   0.142    8.55 0.00116      -      92% NiceHash           2.00% NHb..ATt
Xmrig              - KawPOW              Benchmarking       -    0W    Unknown Unknown Unknown Unknown      -      92% NiceHash           2.00% NHb..ATt
Teamred        1.00% kHeavyHash           545.64 MH/s    7.01  159W 0.00001099   0.152    9.16 0.00125      -      88% NiceHash           2.00% NHb..ATt
Nsgminer           - NeoScrypt           Benchmarking       -    0W    Unknown Unknown Unknown Unknown      -      81% NiceHash           2.00% NHb..ATt
SgminerFancyIX     - NeoScryptXaya        589.30 kH/s   1.44k  109W 0.00000417   0.058    3.48 0.00047  1.6 m      83% ZergPool           0.30% RDM..Bed
SgminerFancyIX     - NeoScryptXaya        589.30 kH/s   1.44k  109W 0.00000417   0.058    3.48 0.00047  1.6 m      83% ZergPool           0.30% RDM..Bed
Nanominer      2.00% Octopus               13.18 MH/s       -  131W 0.00000301   0.042    2.51 0.00034      -      92% NiceHash-CFX       2.00% NHb..ATt
Xmrig              - RandomArq              1.59 kH/s   1.25M   78W 0.00000027   0.004    0.22 0.00003  8.4 m      91% MoneroOcean-ARQ    0.68% 45D..zQ9
Xmrig              - RandomX              394.60  H/s 190.73k   90W 0.00000059   0.008    0.49 0.00007      -      93% NiceHash-XMR       2.00% NHb..ATt
SrbMinerMulti  0.85% VerusHash             12.07 MH/s  20.00m  186W 0.00000359   0.050    2.99 0.00041      -      79% NiceHash           2.00% NHb..ATt
WildRig        1.00% X17                 Benchmarking       -    0W    Unknown Unknown Unknown Unknown  >10 y      34% ZergPool           0.30% RDM..Bed
WildRig        1.00% X21s                Benchmarking       -    0W    Unknown Unknown Unknown Unknown  1.7 m      75% ZergPool           0.30% RDM..Bed
WildRig        1.00% X25x                   2.04 MH/s 171.80M   84W 0.00000130   0.018    1.09 0.00015  6.4 m      74% ZergPool           0.30% RDM..Bed
WildRig        1.00% Xevan               Benchmarking       -    0W    Unknown Unknown Unknown Unknown  1.6 h      49% ZergPool           0.30% RDM..Bed
SrbMinerMulti  0.85% Yescrypt              21.87 kH/s 800.00m  140W 0.00001327   0.184   11.06 0.00150 38.8 m      70% ZergPool           0.30% RDM..Bed
SrbMinerMulti  0.85% YescryptR16            5.58 kH/s    1.11  141W 0.00001609   0.223   13.41 0.00182  4.1 m      84% ZergPool           0.30% RDM..Bed

**Comment by RainbowMiner** [comment]
If it can be mined via FocusWallet, I suspect there is no rate avail for RDX. Try to set `"AllowZero": "1",` for Rplant in pools.config.txt

**Comment by MattF42** [comment]
Interesting, that's helped somewhat. Somewhat unhelpfully I've just updated the AMDGPU drivers to ROCM 5.4.1 which finally feels like a clean install on Ubuntu 22.04.01, so going through a full re-benchmark loop.  Anyway....
Under the CPU we get

`

AMD Ryzen 9 3900X 12-Core Processor (CPU#00)
============================================
SrbMinerMulti   0.85% SHA512256d          Benchmarking       -    0W    Unknown Unknown Unknown Unknown 19.7 m     100% RPlant-RXD         1.00% 1Mh..DN7`

Under the GPUs (only one shown, they all do the same) we get

`
Radeon RX 6700 XT (GPU#00)
==========================
BzMiner        0.50%,- {Autolykos2, SHA512256d} {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {89%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}
SrbMinerMulti  1.50%,- {Autolykos2, SHA512256d} {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {89%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}
SrbMinerMulti  1.50%,- {Autolykos2, SHA512256d} {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {89%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}
SrbMinerMulti  0.65%,- {EtcHash, SHA512256d}    {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {40%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}
SrbMinerMulti  0.65%,- {EtcHash, SHA512256d}    {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {40%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}
SrbMinerMulti  0.65%,- {EtcHash, SHA512256d}    {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {40%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}
SrbMinerMulti  0.65%,- {Ethash, SHA512256d}     {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {39%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}
SrbMinerMulti  0.65%,- {Ethash, SHA512256d}     {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {39%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}
SrbMinerMulti  0.65%,- {Ethash, SHA512256d}     {Benchmarking, Benchmarking}     -,-    0W    Unknown Unknown Unknown Unknown {-, 19.7 m} {39%, 100%} {NiceHash, RPlant-RXD}    {2.00%, 1.00%} {NHb..ATt, 1Mh..DN7}`

Maybe it will sort itself out by tomorrow when hopefully the re-benchmark run has finished.  From what I can see though RBM is happy to consider dual mining RXD, but not normal mining it on the GPUs......

**Comment by MattF42** [comment]
I've a sneaking feeling this is config related, and I've something dumb included.  I've done a fresh install on my Nvidia rig, and will let it run through a benchmark cycle and report back.

**Comment by MattF42** [comment]
This was indeed config.  Thanks for all the pointers
