### ISSUE TITLE
Sugestion: Change 'localhost' to '127.0.0.1' for better performance

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2232]
https://github.com/RainbowMiner/RainbowMiner/blob/a95cb69515146727f8d7e690db82e8c837c37496/Modules/MinerAPIs.psm1#L908

This will dramatically speed up the API request.

https://github.com/dotnet/runtime/issues/31085#issuecomment-540011105

**Comment by RainbowMiner** [comment]
Interesting! Thank you for the hint. I will try this out.
