### ISSUE TITLE
lolMiner 1.65 is out

### ISSUE THREAD

**Issue by MattF42** [RainbowMiner/RainbowMiner#2234]
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.65

**Comment by MattF42** [comment]
Looks like it was slightly buggy, probably best to go straight to 
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.65a

**Comment by RainbowMiner** [comment]
Yes, for sure. I have been waiting for the windows version auf the 1.65a - the update will be integrated asap.
