### ISSUE TITLE
Issue: Pool balance missing

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#224]
I am mining on blockmasters but it is not showing up under balances.

![image](https://user-images.githubusercontent.com/42227809/47093521-37911500-d1de-11e8-8ade-6bf9ff73811f.png)

**Comment by jch9678** [comment]
I'm having this problem with MiningPoolHub balances not showing up

**Comment by hernandn01** [comment]
Blockmasters API is out for the moment

BlockMasters.co hoy a las 9:53
@everyone Wallet API's have been disabled for a bit.  Will be back up later today.

**Comment by RainbowMiner** [comment]
The balances APIs are not really stable, for any of the pools. They may fail from time to time.

@jch9678 for the MiningPoolHub balances showing up, you need to supply API credentials in the pools.config.txt. Eventually these are missing. If you have already put them into your config: did the balance show up, ever?

**Comment by jch9678** [comment]
I've had them in there since the beginning but the balance has never shown up.  I use miningpoolhubstats.com to monitor my other miners that are pointed at mph and it uses the api just fine.  I use miningpoolhubcoins instead of miningpoolhub, could that make a difference?

**Comment by RainbowMiner** [comment]
>  I use miningpoolhubcoins instead of miningpoolhub, could that make a difference?

Yes, it does :) I will add a fix for that.

**Comment by RainbowMiner** [comment]
Ok, fixed. Will be part of next release.
