### ISSUE TITLE
AMD GPU issues

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#2249]
************ miniZ v1.9z5b ************
LoadLibrary "nvcuda.dll" failed!

https://i.imgur.com/lhJPchc.png
https://i.imgur.com/Mh2VUle.png

progminer 1.1.2-9+commit.f0197778
Build: windows/release/msvc

Error: The following arguments were not expected: 0 --opencl-platform

firominer 1.2.4+commit.fec56135.dirty
Build: windows/release/msvc

Error: The following arguments were not expected: 0 --opencl-platform

**Comment by RainbowMiner** [comment]
Same as #2246
