### ISSUE TITLE
Not Benchmarking All Algos for SRBMiner

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#225]
I just erased my stats for SRBMiner and WildRig in order to re-benchmark.  It's benchmarking 8 algos for WildRig but benchmarking cryptonightv7 twice...  

I'm not sure why it's doing that one twice (maybe for 1 thread and 2 threads?) and not even trying heavy alloy etc.

**Comment by RainbowMiner** [comment]
Yes, it is because of 1 thread, 2 threads.
Regarding the missing algorithm: that may have different reasons. Eventually no pool with hashrate has been avail. If you want, I can have a look (just drop the Logs folder zipped, here).

**Comment by jch9678** [comment]
I ended up just editing config file inside the bin folder.  

You're right about the pools, I just looked at all of them and none offer the cryptonight variants with the only exception being nicehash and the heavy algo.  

If you could support  https://cryptoknight.cc/ that would be huge.

**Comment by RainbowMiner** [comment]
> If you could support https://cryptoknight.cc/ that would be huge.

Ok :)
