### ISSUE TITLE
InvalidArgument: Cannot convert value "8.25yescryp.19" to type "System.Version". Error: "Input string was not in a correct format."

### ISSUE THREAD

**Issue by MattF42** [RainbowMiner/RainbowMiner#2255]
Weirdly only the NVDIA Ubuntu 22.04.1 rig reports this at the start of each loop.
Doesn't happen on the AMD Ubuntu 22.0.4.1 rig, which has very similar, if not identical config.

They are both standalone deployments, so it's possible there is some config difference.

Powershell 7.2.7

**Comment by RainbowMiner** [comment]
Yes, that's a bug in the version parsing function. Thank you for reporting this!
