### ISSUE TITLE
API port timeouts

### ISSUE THREAD

**Issue by smyers63** [RainbowMiner/RainbowMiner#2260]
Bin\GPU-lolMiner\lolMiner.exe --pool us-beam.2miners.com:5252 --user [removed].MINER --pass x --tls on --worker MINER --devices 0,2 --apiport 31700 --digits 2 --longstats 60 --shortstats 5 --connectattempts 3 --lhrtune off,off --watchdog exit --algo BEAM-III

PS>TerminatingError(): "Call to http://localhost:31700/summary timed out after 10 secs"

Bin\GPU-Gminer\miner.exe --api 32901 --devices 1 --server us-beam.2miners.com:5252 --user [removed].MINER --pass x --worker MINER --ssl 1 --ssl_verification 0 --cuda 1 --opencl 0 --watchdog

PS>TerminatingError(): "Call to http://localhost:32901/stat timed out after 10 secs"

I think there are others I haven't been able to catch sometimes before they disappear when another round starts.  I'll keep watching.

**Comment by smyers63** [comment]
Bin\GPU-lolMiner\lolMiner.exe --pool us-beam.2miners.com:5252 --user [removed].MINER --pass x --tls on --worker MINER --devices 1 --apiport 31701 --digits 2 --longstats 60 --shortstats 5 --connectattempts 3 --lhrtune off --watchdog exit --algo BEAM-III

PS>TerminatingError(): "Call to http://localhost:31701/summary timed out after 10 secs"

**Comment by RainbowMiner** [comment]
That normally indicates, that you CPU load is too high. But try the new release v4.8.7.8 - I have changed the localhost API urls to speed up these calls a lot.

**Comment by smyers63** [comment]
I think that has fixed the issue.  I've seen one instance of a miner still using "localhost" and during the benchmark showing zero hashrate for quite a while..  It was Miniz/Kawpow and used localhost:33001.  It ended up showing over 10% rejected (slightly different reject rates for RTX3080 and RTX3090).
