### ISSUE TITLE
Request: Add MiniZ miner for Equihash, progpow and octopus support

### ISSUE THREAD

**Issue by gorgarp** [RainbowMiner/RainbowMiner#2261]
https://miniz.ch/

This miner tends to have the best hashrate for Equihash varients.

**Comment by gorgarp** [comment]
Hmm, now that I see you have it, I guess it's just not built into to the definitions for ZelHash (Equihash 125,4)

I currently only see LOLminer and Gminer for that algo

**Comment by smyers63** [comment]
For what it's worth, I have MiniZ showing that algo (as well as lolminer and Gminer).
![Screenshot 2023-01-13 at 03-26-51 RainbowMiner Local Dashboard](https://user-images.githubusercontent.com/95280323/212285847-302be7a3-107f-4912-a968-8d7cb816f493.png)
