### ISSUE TITLE
API connection refused

### ISSUE THREAD

**Issue by smyers63** [RainbowMiner/RainbowMiner#2263]
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34900))" --> One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34900))"
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34900))" --> One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34900))"
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34900))" --> One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34900))"
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34900))" --> One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34900))"

Bin\ANY-SRBMinerMulti\SRBMiner-MULTI.exe --algorithm heavyhash --api-enable --api-port 34900 --api-rig-name MINER --gpu-id 0!1!2 --gpu-intensity  0!0!0 --disable-cpu --disable-gpu-amd --pool stratum-na.rplant.xyz:7064 --wallet [removed].MINER --worker MINER  --password x --tls false --nicehash false --keepalive --retry-time 10 --disable-startup-monitor

**Comment by RainbowMiner** [comment]
Does the miner benchmark, despite those warnings? If yes, it looks like it takes some time after the timer-start, until the API returns results. If no, it's a problem and needs further investigation.

**Comment by smyers63** [comment]
Yes, I see today that the benchmarks worked and that miner does mine that algo.
