### ISSUE TITLE
RBM suddenly stopped mining - claims no pools selected

### ISSUE THREAD

**Issue by smyers63** [RainbowMiner/RainbowMiner#2268]
*** RainbowMiner Configuration ***

Please choose, what to configure:

- Wallet: setup wallet addresses, worker and username, API-keys
- Common: setup the most common RainbowMiner settings and flags
- Energycosts: setup energy consumption values
- Selection: select which pools, miners, algorithms to use
- All: step through the full setup, configuring all
- Miners: finetune miners, add command-line arguments, penalty values and more (only for the technical savvy user)
- Pools: finetune pools, add different coin wallets, penalty values and more
- Devices: finetune devices, select algorithms, coins and more
- Algorithms: finetune global settings for algorithms, penalty, minimum hashrate and more
- Coins: finetune global settings for dedicated coins, wallets, penalty, minimum hashrate and more
- OC-Profiles: create or edit overclocking profiles
- Network: API and client/server setup for multiple rigs within one network
- Scheduler: different power prices and selective pause for timespans

 WARNING: without the following data, RainbowMiner is not able to start mining.
- No pool selected! Please go to [S]elections and add some pools!

[W]allets, [C]ommon, [E]nergycosts, [S]elections, [A]ll, [M]iners, [P]ools, [D]evices, A[l]gorithms, Co[i]ns, [O]C-Profiles, [N]etwork, Sc[h]eduler, E[x]it configuration and start mining [default=X]*:

I hit Enter to exit and RBM put up the same thing again.  The localhost was still connected, so I went to Setup.  The pools are missing.
![Screenshot 2023-01-13 at 16-46-43 RainbowMiner Local Dashboard](https://user-images.githubusercontent.com/95280323/212433024-4378f180-7101-427b-ae31-2ae72c4144a5.png)

In Setup Pools, none are in the upper section anymore (to show selected pools).

I quit RBM/PS and restarted it.  I still got the same screen wanting me to select pools.  There were errors on the system drive which have now been repaired.  I added one pool back using [S]elections and RBM is mining on that pool.  Can I get my previous pool selections back from the backup files or in some other way without doing any setup again??

**Comment by RainbowMiner** [comment]
Your configuration files have been damaged due to your hardrive failure. Luckily RBM keeps many backups of the config files in Config\Backups.
Just copy an old set of config files into the Config folder and remove the datetimestamp from the filenames.

**Comment by smyers63** [comment]
OK, thanks.
