### ISSUE TITLE
v3.8.9.11 CryptonightV8 benchmark failure with ccMinerTpruvotx64

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#227]
See pictures below, fails to benchmark cryptonightV8 algo with v3.8.9.11...

![image](https://user-images.githubusercontent.com/35561346/47206455-f9842480-d388-11e8-85af-6fb259a1cf48.png)

![image](https://user-images.githubusercontent.com/35561346/47206602-57187100-d389-11e8-83c8-6c1cd73eb4ef.png)

![image](https://user-images.githubusercontent.com/35561346/47206591-4ec03600-d389-11e8-84ee-115384694511.png)

**Comment by RainbowMiner** [comment]
Thank you! I will fix tpruvot.

**Comment by RainbowMiner** [comment]
It will be included in the next release.
