### ISSUE TITLE
Add RigelMiner

### ISSUE THREAD

**Issue by MattF42** [RainbowMiner/RainbowMiner#2276]
https://github.com/rigelminer/rigel/releases

Seems quite good on Nexa on Nvidia

**Comment by RainbowMiner** [comment]
Sure thing. This sounds like an interesting addition. I'll give it  shot.

**Comment by RainbowMiner** [comment]
Ok, I have added the Rigel miner: 364fcbb0f508e22e4259a3c782ea208fb9972e4d - if you want to enable ZIL dual/tripple mining, you will have to update FlexPool, too: f52e82101f1e6456b64fcee682d9daced1dbe491

I will push a new release within the next 24 hours, so no need to hurry.

**Comment by MattF42** [comment]
Can you bump to 1.3.1 please - big hashrate improvement :)

**Comment by MattF42** [comment]
1.3.4 is out now, with ZIL mining working with it, so another worthwhile update please :)

**Comment by RainbowMiner** [comment]
Thank you! Updated.

**Comment by MattF42** [comment]
💯
