### ISSUE TITLE
Release v3.8.9.12: update stuck in update loop -> Please read!

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#228]
As title say. Looping the upgrade, miners are not started resulting in idle rig. I can't get past this loop, unless setting auotupdate parameters to 0 in the config file?  Need any logs?

Edit by RainbowMiner: [how to solve](https://github.com/RainbowMiner/RainbowMiner/issues/228#issuecomment-431528350)

**Comment by ebojali** [comment]
Update to the case. When disabling auto update and do a manual upgrade by pressing U upgrade worked and is now mining again

**Comment by RainbowMiner** [comment]
What ever happened! It should never get stuck in auto update loop. Would you please send me the logs, so I can analyse the cause?

**Comment by NPittinger** [comment]
This actually happened to me as well. The program kept saying this:
`Automatic update to v3.8.9.13 will begin in some seconds

Waiting 50s until next run: [U]pdate RainbowMiner, E[x]it, [R]estart, [S]kip switching prevention, [C]onfiguration, [V]erbose off, [P]ause
Finished waiting - starting next run

WARNING: RainbowMiner is out of date: lastest release version v is available.`
I'm looking for anything relevant in the logs, but haven't seen anything yet.

**Comment by RainbowMiner** [comment]
Ok, I found the reason. I am very sorry! I unintentionally blocked the automatic update.
#### To solve this, please do the following:
- close the RainbowMiner window (really, press ![image](https://user-images.githubusercontent.com/39437538/47248250-56272400-d409-11e8-95d1-33b78d0a8ffd.png))
- now start "Updater.bat" (in RainbowMiner directory)
- now restart RainbowMiner and everything should be solved.

Again - I am very sorry for the inconvenience.

**Comment by RainbowMiner** [comment]
@NPittinger read my solution comment above.

**Comment by RainbowMiner** [comment]
[how to solve](https://github.com/RainbowMiner/RainbowMiner/issues/228#issuecomment-431528350)

**Comment by ebojali** [comment]
@RainbowMiner bugs do happen now a then, but you are as usual very fast on fixing them. Keep up the fantastic job!
