### ISSUE TITLE
Prohashing stratums wrong.

### ISSUE THREAD

**Issue by ngiotta** [RainbowMiner/RainbowMiner#2282]
I had to manually edit the ps files for prohashing/prohashing coins to include **_us.mining._** as that was missing from the stratum.  Might want to fix on next release.

**Comment by smyers63** [comment]
Adding just "mining." works for me (I'm in the US).  When I added "us.mining." the All Pools list also showed eu.us.mining.prohashing.com" as well as "us.mining.prohashing.com." The miner connected anyway but I'll guess that having "us." also in there would cause trouble reaching the EU servers.

**Comment by ngiotta** [comment]
Interesting.  Mine was just trying to connect to prohashing.com.  No region.mining (even though I had a region set).  In any event, it's working fine now for me with us.mining in there.

**Comment by smyers63** [comment]
Yes, also for me originally it was just prohashing.com and didn't work.  I tried setting the region to US in the pool's setup but it didn't work.  The "eu" part is/was already there from somewhere - not needed for you and me but needed for others.

**Comment by RainbowMiner** [comment]
Thank you! Problem solved.
