### ISSUE TITLE
Rainbowminer is not responding to changes in heat control, and not showing pool balance

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#2285]
I think something has gone wrong with my Rainbowminer? It was working fine for ages and I never really touched it except for changing heat control based on whether it's a cold or warm day.

**Comment by samdave123** [comment]
[debug_2023-01-31.zip](https://github.com/RainbowMiner/RainbowMiner/files/10546120/debug_2023-01-31.zip)

**Comment by RainbowMiner** [comment]
Did you try to reboot that machine? Maybe there is something off.

**Comment by samdave123** [comment]
I'll try rebooting now. I've also had weird stuff happen like an error message come up when I tried to change a setting on localhost, and RBM not starting automatically until I select pools again.

**Comment by samdave123** [comment]
Yeah this happened 
![image](https://user-images.githubusercontent.com/56473344/215862818-43a396fa-5f50-4a58-9656-7b0b0d879194.png)

**Comment by samdave123** [comment]
I also had a message to do sudo ./install.sh -pu so I am doing that now.

**Comment by RainbowMiner** [comment]
That indicates, that your config files are damaged. Most probably your hdd (or sdd) has problems. RainbowMiner creates backups of it's config files in `./Config/Backup`

**Comment by samdave123** [comment]
I'm a noob, what's the terminal command to copy and replace all my config files from 4 weeks ago? 
![image](https://user-images.githubusercontent.com/56473344/215863954-3c3fa0bf-a307-47c7-addb-75983198333d.png)

**Comment by samdave123** [comment]
Okay nvm I managed to replace my config files with my oldest backups.

**Comment by samdave123** [comment]
I'll do a reboot and then monitor this over the coming days to confirm my rig is all working again. Thanks for the help.

**Comment by samdave123** [comment]
I wonder actually, could some simple backup features be added to the localhost? Just give us a one click button to replace the config files with backups?

**Comment by DezHo1** [comment]
> I wonder actually, could some simple backup features be added to the localhost? Just give us a one click button to replace the config files with backups?

you use purse often right?

**Comment by samdave123** [comment]
desmond_ho86?

**Comment by DezHo1** [comment]
Right, u use tg?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by samdave123** [comment]
Yes

**Comment by DezHo1** [comment]
WhaleDoneBro  , give me a shout on tg
