### ISSUE TITLE
Miniz mining on amd

### ISSUE THREAD

**Issue by szentigrad3** [RainbowMiner/RainbowMiner#2287]
the miner crashes on my system unless i add --amd into the command line argument
Bin\NVIDIA-MiniZ\miniZ.exe --amd --telemetry=33000 -cd 0 --url=<hidden>@ethash.mine.zergpool.com:9999 -p ID=<hidden>,c=LTC,mc=EGEM --worker=<hidden> --gpu-line --extra --latency --nohttpheaders --par=ethash

**Comment by sfalas01** [comment]
I have the same issue

**Comment by RainbowMiner** [comment]
Ok, so we better add --amd . Will be done.
