### ISSUE TITLE
GPU Model_Name Detected as Ellesmere instead of RX 470

### ISSUE THREAD

**Issue by malorx** [RainbowMiner/RainbowMiner#229]
Hi,

My GPU is not detected as Model_Name: RX 470 so the power data is read as 0 W. I extract below info from http://localhost:4000/alldevices.html and selected the AMD GPU. I have read other samples in internet and found the board name property of OpenCL seems to be as expected. My other card using Nvidia is detected as Model_Name: GTX1070

Index: 1

PlatformId: 1

PlatformId_Index: 0

Type_PlatformId_Index: 0

Vendor: "AMD"

Vendor_Name: "Advanced Micro Devices, Inc."

Vendor_Index: 0

Type_Vendor_Index: 0

Type: "Gpu"

Type_Index: 1

Type_Mineable_Index: 1

OpenCL: {"AddressBits":64,"Available":true,"CompilerAvailable":true,"DoubleFpConfig":"FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma","EndianLittle":true,"ErrorCorrectionSupport":false,"ExecCapabilities":"ExecKernel","Extensions":"cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash cl_amd_planar_yuv","GlobalMemCacheSize":16384,"GlobalMemCacheType":2,"GlobalMemCachelineSize":64,"GlobalMemSize":4294967296,"ImageSupport":true,"LocalMemSize":32768,"LocalMemType":1,"MaxClockFrequency":1077,"MaxComputeUnits":32,"MaxConstantArgs":8,"MaxConstantBufferSize":null,"MaxMemAllocSize":4026531840,"MaxParameterSize":1024,"MaxReadImageArgs":128,"MaxSamplers":16,"MaxWorkGroupSize":256,"MaxWorkItemDimensions":3,"MaxWorkItemSizes":"1024 1024 1024","MaxWriteImageArgs":64,"MemBaseAddrAlign":2048,"MinDataTypeAlignSize":128,"Name":"Ellesmere","ClVersion":"OpenCL C 2.0 ","Platform":"@{Profile=FULL_PROFILE; Version=OpenCL 2.1 AMD-APP (2671.3); Name=AMD Accelerated Parallel Processing; Vendor=Advanced Micro Devices, Inc.; Extensions=cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices }","PreferredVectorWidthChar":4,"PreferredVectorWidthShort":2,"PreferredVectorWidthInt":1,"PreferredVectorWidthLong":1,"PreferredVectorWidthFloat":1,"PreferredVectorWidthDouble":1,"Profile":"FULL_PROFILE","QueueProperties":"ProfilingEnable","SingleFpConfig":"FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt","Type":"Gpu","Vendor":"Advanced Micro Devices, Inc.","VendorId":4098,"Version":"OpenCL 2.0 AMD-APP (2671.3)","DriverVersion":"2671.3"}

Model: "Ellesmere"

Model_Name: "Ellesmere"

Name: "GPU#01"

tMemory: "4 GB"

tClockSpeed: 1077

tDriverVersion: "2671.3"

tCores: 32

**Comment by RainbowMiner** [comment]
Thank you for bringing this up. I will have a look

**Comment by RainbowMiner** [comment]
One question: did you install MSI afterburner? It is no problem, if not, but I need to know to analyse the problem.

**Comment by malorx** [comment]
yes, today I installed to the latest version. thanks for your support.

**Comment by RainbowMiner** [comment]
I need your help :)

First do update to release v3.8.9.16 and afterwards download and unzip the following test utility into your RainbowMiner folder: [GPUtest.zip](https://github.com/RainbowMiner/RainbowMiner/files/2498032/GPUtest.zip)

It does contain two files (GPUtest.bat and GPUtest.ps1) - please click-start the GPUtest.bat. A file "gputestresult.txt" will be written. Drop this file here, please.

![image](https://user-images.githubusercontent.com/39437538/47254489-9fa45d00-d463-11e8-8e5f-e30d2456e18d.png)

**Comment by malorx** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504844/gputestresult.txt)

please find the result in link above

**Comment by RainbowMiner** [comment]
Thank you very much! I am now able to fix the power reading.

**Comment by RainbowMiner** [comment]
I updated the beta test download zip: [Include_v3.8.10.0b.zip](https://github.com/RainbowMiner/RainbowMiner/files/2508463/Include_v3.8.10.0b.zip) in the above post.

**Comment by malorx** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2509968/gputestresult.txt)

Hi,

Please see above for latest gputestresult.txt. I see the device name for AMD GPU has changed to "Radeon RX 470". However currently the mining status is "Waiting for profitability" so i cannot see the power reading for now.

cheers

**Comment by RainbowMiner** [comment]
Very nice! Thanks for the feedback. Now I am finally able to release v3.8.10.1
