### ISSUE TITLE
Access to the path RainbowMiner/Bin/ANY-SRBMinerMulti/Cache/verthash.dat is denied.

### ISSUE THREAD

**Issue by ToasterUwU** [RainbowMiner/RainbowMiner#2292]
Hello there, i get a error message every single time the run ends and the next one starts.

Im on a Ubuntu Based Distro. I followed the setup, including Huge Pages and Drivers.

Error message is below.

```
Finished waiting - starting next run                                                                                                                         
Test-Path: /home/aki/RainbowMiner/Miners/SrbMinerMulti.ps1:199
Line |
 199 |  if (-not (Test-Path "$(Join-Path $Session.MainPath "Bin\ANY-SRBMinerM …
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the path '/home/aki/RainbowMiner/Bin/ANY-SRBMinerMulti/Cache/verthash.dat' is denied.
```

**Comment by RainbowMiner** [comment]
Looks like SrbMiner messes up the access rights of that verthash.dat - could you check the rights via `ls -la` in the path `./Bin/ANY-SRBMinerMulti/Cache` as well, as that of the folder `./Bin/ANY-SRBMinerMulti/Cache`? Maybe you will have to use the following two commands:
```
su chmod 0666 ./Bin/ANY-SRBMinerMulti/Cache
su chmod -R 0666 ./Bin/ANY-SRBMinerMulti/Cache/*
```

**Comment by ToasterUwU** [comment]
I will attach my outputs below (note that the way the permissions are, are how RainbowMiner made them, i didnt touch anything so far)

```
aki@Barbara:~/RainbowMiner/Bin/ANY-SRBMinerMulti$ ls -la
total 13108
drwxrwxr-x 1 aki  aki      2718 Feb  4 10:34 .
drwxrwxr-x 1 aki  aki      1126 Feb  4 08:44 ..
drwxr--r-- 1 root root        0 Feb  4 04:57 Cache
aki@Barbara:~/RainbowMiner/Bin/ANY-SRBMinerMulti$ sudo cd Cache/
sudo: cd: command not found
sudo: "cd" is a shell built-in command, it cannot be run directly.
sudo: the -s option may be used to run a privileged shell.
sudo: the -D option may be used to run a command in a specific directory.
aki@Barbara:~/RainbowMiner/Bin/ANY-SRBMinerMulti$ sudo -i
NVIDIA GPU detected. Checking for NVIDIA Driver.
NVIDIA Driver detected. setting env-v vars for va-api.
root@Barbara:~# cd /home/aki/RainbowMiner/Bin/ANY-SRBMinerMulti/Cache/
root@Barbara:/home/aki/RainbowMiner/Bin/ANY-SRBMinerMulti/Cache# ls -la
total 0
drwxr--r-- 1 root root    0 Feb  4 04:57 .
drwxrwxr-x 1 aki  aki  2718 Feb  4 10:34 ..
```

@RainbowMiner I assume it made the Cache directory and than was not able to save verthash.dat because the Cache dir is read only

**Comment by RainbowMiner** [comment]
Exactly. It is a SrbMinerMulti bug - this miner creates itself a Cache directory. I will report the problem to the miner developer. 

You should be able to change the attributes of the Cache directory: cd to your Rainbowminer main folder, then

```
su chmod 0777 ./Bin/ANY-SRBMinerMulti/Cache
```

**Comment by ToasterUwU** [comment]
Sounds good. I did that yesterday and it seemed to work.

Thanks for your response.
