### ISSUE TITLE
Dynex DNX

### ISSUE THREAD

**Issue by jul-ienfr** [RainbowMiner/RainbowMiner#2293]
Hello please add Dynex

**Comment by RainbowMiner** [comment]
Is there already a miner available, that could be integrated?

**Comment by jul-ienfr** [comment]
There is currently
https://github.com/dynexcoin/Dynex/releases/tag/DynexSolve
is soon available on srbminer
exchange on txbit.io & tradeogre.com

**Comment by papadrams** [comment]
Also avaliable for mining on zergpool! @RainbowMiner

**Comment by RainbowMiner** [comment]
Ok, we give it a shot.

**Comment by papadrams** [comment]
@RainbowMiner I tested it and it works for gpu. It is a cpu miner as well though. Also, there is something wrong with the -multi-gpu function. I have 2 nvidia gpus on my system, but it never got the -multi-gpu parameter. However i edited the .ps1 file by myself and it is working.

**Comment by RainbowMiner** [comment]
> It is a cpu miner as well though.

As far as I can see, this miner is not valid for standalone CPU mining. There is a warning on the miner's help page: `-no-gpu   run no Dynex chips on GPU (WARNING: MINING NOT POSSIBLE)`. If I ignore this warning and start mining on CPU only, I get this message during mining: `[INFO] OPTION no-gpu ACTIVATED - WARNING: ONLY FOR TESTING - MINING WILL NOT BE PERFORMED`

> I have 2 nvidia gpus on my system, but it never got the -multi-gpu parameter.

Are this two identical GPUs or different ones? Either way, could you please provide me with a Debug file?
