### ISSUE TITLE
SrbMinerMulti 2.1.0 (AMD)

### ISSUE THREAD

**Issue by sfalas01** [RainbowMiner/RainbowMiner#2294]
Using this miner on RX580 (4GB) fails to detect any devices and by extension fails to benchmark any algorithm. Running list-gpu-devices.bat from the "bin" file successfully detects the GPU and running any algo .bat file directly from the ANY-SRBMinerMulti folder starts mining just fine.
[debug_2023-02-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/10684550/debug_2023-02-08.zip)

**Comment by sfalas01** [comment]
@RainbowMiner 
It seems that the problem is --gpu-id. It is probably pointing to the wrong ID or the CPU-integraded GPU. If I remove the --gpu-id parameter from SrbMinerMulti.ps1 then the miner works correctly.

**Comment by sfalas01** [comment]
There also seems to be a problem with providing data to RBM during benchmarks:
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34901))" --> One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:34901))"

It is very slow to start mining (adding extended benchmark intervals for Srb would probably solve this) but the SrbMiner window console does not show up on the Web-Gui, probably due to this error

**Comment by RainbowMiner** [comment]
Found and solved! Thank you for reporting this.

**Comment by sfalas01** [comment]
It seems that now SrbMinerMulti appears multiple times during benchmarking
![image](https://user-images.githubusercontent.com/22576563/218474347-d3f3a72c-c0d9-4a26-8f84-95e9de8e02d6.png)

**Comment by sfalas01** [comment]
> Yes, that is intended. SrbminerMulti has a parameter `--gpu-dual-max-loss` to adjust the intensity of the dual mining. It's in percent and RainbowMiner runs 1(%), 5(%) and 10(%) by default. You can change these values in miners.config.txt, it's parameter "Intensity". Put a comma separated list of numbers in there.

Ok got it, thanks! I think I found another bug. When dual mining on Nvidia, SrbMinerMulti crashes if config file has ShowMinerWindow="1"

**Comment by sfalas01** [comment]
@RainbowMiner 
Scrap that. I have found the real reason. A lot of those dual mining algorithms for some reason are taking too much time to load GPU libraries and start mining the script things that they crashed. I have extended the benchmark and interval durations to massive numbers to let it benchmark more and it seems to be working after 3-5 minutes, which is very slow. Can you take a look at that? It was tested on an AMD GPU. Also, SrbMinerMulti dual mining with Ethash variants (2g-5g) crashes.

On Nvidia, dual mining seems to be crashing immediately every time it is run with ShowMinerWindow="1" but it seems to be mining just fine when set to zero. No delays like AMD and every Ethash variant works.

**Comment by sfalas01** [comment]
> @RainbowMiner ~Scrap that. I have found the real reason. A lot of those dual mining algorithms for some reason are taking too much time to load GPU libraries and start mining the script things that they crashed. I have extended the benchmark and interval durations to massive numbers to let it benchmark more and it seems to be working after 3-5 minutes, which is very slow. Can you take a look at that? It was tested on an AMD GPU.~ Also, SrbMinerMulti dual mining with Ethash variants (2g-5g) crashes.
> 
> On Nvidia, dual mining seems to be crashing immediately every time it is run with ShowMinerWindow="1" but it seems to be mining just fine when set to zero. No delays like AMD. Ethash variants are shown as crashed as well even though they work just fine.
> 
> ![image](https://user-images.githubusercontent.com/22576563/220796215-a2acd933-4d8b-40cb-a12f-72fe9ae9a4e4.png) ![image](https://user-images.githubusercontent.com/22576563/220796234-d643ed61-3332-406f-b917-03e3421a0259.png) ![image](https://user-images.githubusercontent.com/22576563/220796259-eb04f09e-50ee-4017-8f43-8023e8b2c7fe.png)
> 
> Edit: It seems that the delayed start of mining on AMD GPUs is an SRBminerMulti problem and not something introduced by the RBM script.

Any ideas about this @RainbowMiner ? It still has not been solved. Dual-mining with SRBMinerMulti with ShowMinerWindow="0" crashes immediately

**Comment by sfalas01** [comment]
Bump
``Any ideas about this @RainbowMiner ? It still has not been solved. Dual-mining with SRBMinerMulti with ShowMinerWindow="0" crashes the miner immediately.``

**Comment by sfalas01** [comment]
[debug_2023-07-04.zip](https://github.com/RainbowMiner/RainbowMiner/files/11949517/debug_2023-07-04.zip)
A debug file that might be useful, showing this behavior in the last benchmarks
