### ISSUE TITLE
Phoenixminer difficulty too high for zergpool ethash and upqhash

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2296]
Using phoenixminer on zergpool, i discovered that pool was sending me huge difficulties. 
On ethash and ubqhash.
I runned ubqhash by hand and changed the -proto value from 2 to 4.
And i am getting regular difficulty jobs from pool now. 
Should you change eth and ubq on zergpool to take proto 4?

**Comment by papadrams** [comment]
I changed the value from zergpool.ps1 in line 150 to: 
EthMode       = $Pool_ethstratum    instead of EthMode       = $Pool_stratum
But then miner chose proto 1. No connection to pool

I manually changed the default value from phoenix.ps1 line 123 to:
default            {"-proto 4"}        instead of              default            {"-proto 1"}
and it worked

Its a temp solution cause this way other pools will not work.

**Comment by UselessGuru** [comment]
Chatted with ZergPool yesterday.
They recommend to use Ethstratum 2.0.0 protocol

**Comment by papadrams** [comment]
> Chatted with ZergPool yesterday. They recommend to use Ethstratum 2.0.0 protocol

That should be -proto 5 in phoenixminer

**Comment by RainbowMiner** [comment]
Interesting - thank you for reporting this. I'll check all Ethash/Ubqhash miners, if it's easy to switch to Ethstratum 2.0.0 via the pool module.

**Comment by RainbowMiner** [comment]
I am running final tests now. If all turns out to be good, I will push a new release.

**Comment by UselessGuru** [comment]
EtcHash is still buggy. Pls test well.
