### ISSUE TITLE
Feature request: add payouts from pools (total earnings)

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#23]
Hi,

A feature request on the website, an earnings page where we can get a summarized graph of all payouts from the pool, filtering option to just see TX's from a pool or all together. That info can be gathered from the API call below. This is for zergpool, I guess the other pools got the same possibility? 

I just checked at Ahashpool and Zpool, they don't seem to return the payouts in the API call. Perhpas we can start with zergpool support and then chase the other pools to implement it :)

http://api.zergpool.com:8080/api/walletEx?address=WALLET_ADDRESS

result:
{
	"unsold": 0.00050362,
	"balance": 0.00000000,
	"unpaid": 0.00050362,
	"paid24h": 0.00000000,
	"paidtotal" : 0.00000000,
	"total": 0.00050362,
	"miners":[{
		"version": "ccminer\/1.8.2",
		"password": "d=96",
		"ID": "",
		"algo": "decred",
		"difficulty": 96,
		"subscribe": 1,
		"accepted": 82463372.083,
		"rejected": 0
	}],
	"payouts": [{
		"time": "1529749163", 
		"amount": 0.01714574, 
		"tx": "8a727e1b591034ad6bdea8be2d82849e8eeaeaf3427414c92327a77c9c56b667"
	}, {
		"time": "1529705825", 
		"amount": 0.02249281, 
		"tx": "491ed3628e7bc3349c7c8bae92baabdcd5edafd49e650c1d811e505a2afe5d93"
	}]
}

**Comment by RainbowMiner** [comment]
Good idea. I will have a look into the divers APIs and see, what I can do.

RBM

**Comment by ebojali** [comment]
Blazepool now added the payouts to their API call:

http://api.blazepool.com/wallet/<WALLET_ADDRESS>

**Comment by RainbowMiner** [comment]
Ah, super! Then we already have two. I think, now we could start showing the transactions.

**Comment by ebojali** [comment]
Yeah. A plog of the payout would be great. P
Individual pools as well as accumulated 👍😁

**Comment by Byrd1083** [comment]
Very nice enhancement! Keep up the great work!

**Comment by RainbowMiner** [comment]
Oh! I did miss the last statement. Yes, that would be real cool. It looks like, that more and more pools show transactions to their API, so it would be good to start with this enhancement, now.
My plan is to add a database to collect those transactions, because most pools only show the last X transactions and not the full history. I give it a go, now.
RBM

**Comment by RainbowMiner** [comment]
This is now implemented - we need to wait for the pool owners to implement this feature to their APIs. I will contact them one be one and ask for implementation.
