### ISSUE TITLE
Activity page Pool filter not working

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#230]
all the other filters and sorters are working except the pool filter, when selecting one pool to filter it says no matching records found

![image](https://user-images.githubusercontent.com/41829368/47257526-4da40d00-d44c-11e8-9f52-27302d440918.png)

![image](https://user-images.githubusercontent.com/41829368/47257534-5dbbec80-d44c-11e8-93db-08efe5e5287b.png)

**Comment by RainbowMiner** [comment]
Ok, I will fix it.

**Comment by RainbowMiner** [comment]
Found and fixed.
