### ISSUE TITLE
Tribus numbers

### ISSUE THREAD

**Issue by bwstandard** [RainbowMiner/RainbowMiner#2306]
I have been watching Tribus and it seems like the profitability numbers may be off somewhere on that one. Hopefully I'm wrong somewhere. 

On my two rigs I'm running I show that I should be somewhere in the $200/day range, which is pretty big and probably wrong. When I watch zpool and notice that I've been on tribus for near a day I show that I have nowhere near that much in earnings. 

Can you look into? 
![image](https://user-images.githubusercontent.com/92652253/219865271-b99f3bd6-cd31-465d-b471-a0228182ab94.png)
![image](https://user-images.githubusercontent.com/92652253/219865279-3ea3b3ea-aa19-4ce8-8ed2-407bccf401a1.png)
![image](https://user-images.githubusercontent.com/92652253/219865300-c41f190a-f115-48e2-9d85-0f4da9e0e874.png)

**Comment by RainbowMiner** [comment]
Hi, sure, I'll check the Zpool API. Obviously it's off.

**Comment by jul-ienfr** [comment]
there seems to be a bug
![2023-03-02_18-08-29](https://user-images.githubusercontent.com/105233896/222501455-75ab64ff-5989-4b2f-9a50-fb281557242b.png)

**Comment by RainbowMiner** [comment]
I have added the Tribus on Zpool/ZpoolCoins onto the unprofitable list for GPU miners. It should finally vanish from your machines.

**Comment by whitindllc** [comment]
> I have added the Tribus on Zpool/ZpoolCoins onto the unprofitable list for GPU miners. It should finally vanish from your machines.

is it possible to add it back manually.... how could or could i go about doing it?
