### ISSUE TITLE
SRBminermulti on Dynexsolve 

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2314]
Good Morning!
There is an issue with the new srbminermulti on dynexsolve algo.
Srb uses the --gpu-intensity parameter to define how many chips will be used to mine.
I rbminer, it uses --gpu-intensity 0. This has those results in 2 of my rigs that i tested.
In a 2x480 rig it uses the command --gpu-id 0!1 --gpu-intensity 0!0
This results to srb using 4 intensity (dynex chips) per gpu.
In a 3x550 rig it uses the command --gpu-id 0!1!2 --gpu-intensity 0!0!0
This results to srb using 8 intensity (dynex chips) per gpu.

For the 2x480 it should be using --gpu-intensity  512!512      (vram devided by 16) 8gb cards
For the 3x550 it should be using --gpu-intensity 256!256!256     (vram devided by 16) 4gb cards

BUT --gpu-intensity is being used this way only in dynexsolve. This parameter is being used differently in other algos.

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I already wondered about the very low dynexsolve hashrates. Fix is coming up asap.
