### ISSUE TITLE
SRBminermulti on Nvidia gpus

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2315]
I have a rig with 1 1060 6gb and 1 1660 6gb.
I run them in legacy mode.
Since the releases of srbminer with nvidia support, my rbm client does not benchmark the nvidia cards.
I believe it has something to do with running in legacy mode and being different architecture cards.

**Comment by RainbowMiner** [comment]
Yes, in fact it needs at least a Pascal GPU to run. BUT they have added a new (experimental) parameter recently, that may allow SrbminerMulti to handle those older architectures: they state "for older try using parameter --disable-ptx-check". I'll upload a miner module, that will add this parameter automatically. Maybe that helps.

**Comment by papadrams** [comment]
1060 is Pascal. So it meets rewuirements. 
I was just now playing with the .ps1 file of srb and got it to work.
[SrbMinerMulti - NVIDIA.zip](https://github.com/RainbowMiner/RainbowMiner/files/10940743/SrbMinerMulti.-.NVIDIA.zip)

**Comment by RainbowMiner** [comment]
> 1060 is Pascal.

You are right. I'll double-check the Architecture detection. Could you please upload a Debug file from that machine? Maybe your GPU is a speciality.

**Comment by papadrams** [comment]
Its the same rig that i have created an issue 2 months ago about not autocreating mrr rigs on the gpus.
You havent looked at it since then.
Maybe its the same reason srb doesnt bench them!
[debug_2023-03-10.zip](https://github.com/RainbowMiner/RainbowMiner/files/10940834/debug_2023-03-10.zip)

**Comment by RainbowMiner** [comment]
> You havent looked at it since then.

Oh dear. Too much trees in the wood... I am sorry!

**Comment by papadrams** [comment]
No worries, i have made them by hand in about 20 algos

**Comment by RainbowMiner** [comment]
Oh! Now I see it. Your GPU driver's CUDA version is 11.7.101, but I have set the minimum requirements to CUDA 11.8.

**Comment by RainbowMiner** [comment]
Ok, I have updated that module to check for CUDA 11.7. It should work now out of the box.

**Comment by papadrams** [comment]
It will take a while to check. Rig is rented right now. Please let me know if you find anything about the autocreation in mrr on this rig.
