### ISSUE TITLE
Expected benchmark lengths vs. actual

### ISSUE THREAD

**Issue by smyers63** [RainbowMiner/RainbowMiner#2317]
I've seen this probably with every benchmark RBM has run since I started using it in November 2022.  The expected duration might show 3-6 minutes but it actually takes much longer and the durations on the Console and Dashboard views don't match.

0  H/s 00d/00h/22m Once    WildRig ProgPoWZ  ZANO RTX 3090,RTX 3080 ZergPoolSolo 0W 

WildRig          0.36.5b   ProgPoWZ            RTX3080-RTX3090 Profile2/Profile2 3-6 minutes

WildRig | ZergPoolSolo | ZANO | BTC | RTX3080-RTX3090 | RTX3080=Profile2 RTX3090=Profile2 | - | 0 			W | ProgPoWZ-RTX3080-RTX3090 | 122.79 MH/s | 0 H/s | 172/0/0 | - | 00:12:02 | for you

Those 3 sets of data were copied within a few seconds of each other.  Console says it was running for 22 minutes.  Dashboard says it was running for 12 minutes.  Expected duration was 3-6 minutes.

Why is that?

**Comment by smyers63** [comment]
More data:

Trex | ZergPoolSolo | FIRO | DASH | RTX3080-RTX3090 | RTX3080=Profile2RTX3090=Profile2 | - | 0 W | FiroPoW-RTX3080-RTX3090 | 128.83 MH/s | 0 H/s | 390/2/0 | - | 00:15:06 | for you

 0  H/s 00d/00h/28m Once    Trex  FiroPoW   FIRO RTX 3090,RTX 3080 ZergPoolSolo 0W 

--------------------------20230312 04:16:22 ---------------------------
Mining at firopow.mine.zergpool.com:3001 [103.249.70.7], diff: 942.05 M
GPU #0: Zotac RTX 3090    - 38.64 MH/s, [T:66/98C, P:280W, F:59%, E:138kH/W], 118/118 R:0%
GPU #1: Zotac RTX 3080    - 47.68 MH/s, [T:56/104C, P:271W, F:98%, E:177kH/W], 171/173 R:1.16%
GPU #2: Gigabyte RTX 3090 - 42.82 MH/s, [T:62/100C, P:295W, F:72%, E:145kH/W], 129/129 R:0%
Hashrate: 129.14 MH/s, Shares/min: 9.147 (Avg. 12.975), Avg.P: 844W, Avg.E: 153kH/W
Uptime: 33 mins 6 secs | Algo: firopow | Driver: 522.25 | T-Rex 0.26.8

Trex             0.26.8    FiroPoW             RTX3080-RTX3090 Profile2/Profile2 3-6 minutes

Multiple choice:
A. 3-6 minutes
B. 15 minutes
C. 28 minutes
D. 33 minutes
E. All the above

?

**Comment by smyers63** [comment]
I've been checking these at random times.  The first one didn't have an uptime in the miner stats from the API, so I don't know what the real duration was at the time I checked it.  Of the 2 so far which did have uptime in the miner stats from the API, both ran over 30 minutes but were expected to finish much sooner.

WildRig          0.36.5b   FiroPoW             RTX3080-RTX3090 Profile2/Profile2 3-6 minutes

 0  H/s 00d/00h/23m Once    WildRig FiroPoW   FIRO RTX 3090,RTX 3080 ZergPoolSolo 0W 

WildRig | ZergPoolSolo | FIRO | DASH | RTX3080-RTX3090 | RTX3080=Profile2RTX3090=Profile2 | - | 0 W | FiroPoW-RTX3080-RTX3090 | 123.67 MH/s | 0 H/s | 171/1/0 | - | 00:12:01 | for you

RTX3080-RTX3090 WildRig
                 60s:                         123.52 MH/s                     Rejected:        1
 15m:                         122.08 MH/s                     Ignored:         1
 0 days 00:33:01 ---------------------------------------------------------------
[05:32:10] new job from firopow.mine.zergpool.com:3001 diff 1.70G/27.91T
[05:32:10] block: 640,654       epoch: 492       job target: 0x000000028659cec1
[05:32:31] new job from firopow.mine.zergpool.com:3001 diff 1.70G/27.91T
[05:32:31] block: 640,654       epoch: 492       job target: 0x000000028659cec1
[05:32:45] new job from firopow.mine.zergpool.com:3001 diff 1.70G/27.91T
[05:32:45] block: 640,655       epoch: 492       job target: 0x000000028659cec1
---------------------------------- Statistics ----------------------------------
 ID Name                         Hashrate Temp  Fan  Pwr CClk MClk     A   R   I
--------------------------------------------------------------------------------
 #0 GeForce RTX 3090           27.15 MH/s  66C  55% 279W  722   10    73   -   1 
 #1 GeForce RTX 3080           34.58 MH/s  57C  77% 271W 1325   10    79   1   - 
 #2 GeForce RTX 3090           31.61 MH/s  62C  72% 293W  861   10    60   -   - 
--------------------------------------------------------------------------------
 10s:                          93.34 MH/s Power:    843W      Accepted:      212
 60s:                         117.97 MH/s                     Rejected:        1
 15m:                         122.13 MH/s                     Ignored:         1
 0 days 00:34:01 ---------------------------------------------------------------

The two I posted data for earlier weren't finished when I got the data so I don't know how much longer those ran but the previous one I posted ran at least 33 minutes.  This one finished just a few seconds after I got this data so it definitely ran over 34 minutes.

Is there any reason for any benchmark to run that long?  If so, why is the estimated duration so far off?  In the other miner control software I've used for a long time, I've mostly run benchmarks for 5 minutes.  Occasionally, I've run them for only 1 minute (while checking whether the mining would even start and the API would return any data) and sometimes as long as 20 minutes.  None have ever really needed more than about 5 minutes to be really close to the right data.  At 10 minutes, sometimes the averages would go up a little more but not significantly - not worth spending the extra time.  There was no gain beyond 10 minutes so I really don't want any benchmarks longer than 10 minutes.  I'd prefer 5 minutes as a default and would like the ability to change the duration for only the ones that might need it.  Your estimate of 3-6 minutes would be great if RBM actually stuck to that.

I've seen times when a benchmark crashes but RBM doesn't move on to the next one for around that 30-minute time.  I have the max benchmark crashes set to 1.  If one crashes, I don't want RBM trying it again until some other time when I want to try it again.  Earlier tonight, there was a benchmark crash, the console said it was started twice and the next benchmark didn't start for at least 20 minutes.  RBM shouldn't be doing nothing for 20-30 minutes.  Another benchmark should be running in that time and really about 5 should have run in that time.

Those are my observations and thoughts for now.  I'll keep testing and thinking about all this.  Hopefully, we can come up with a solution together.

**Comment by RainbowMiner** [comment]
Thank you very much for the in depth data. The benchmarks rely on several factors (numbers of cycles, accuracy of the result, miner crashes). Normally, the estimated times are quiet accurate, so answer A. should be the correct one. If they aren't, then there is most probably something off. I have noticed, that you have running all GPUs together in one group. Which `MiningMode` did you set in config.txt? Is it legacy? Did you notice hashrate swings during the benchmarking time? Or was it just constant from the beginning on.

Could you please create a Debug file on that rig? I'ld really love to see, what is going on there.

**Comment by smyers63** [comment]
I've been running Combo mode for a long, long time.  With benchmarks taking so long to run, I haven't watched the hashrate to see if it varies during any of them.  I'm trying to do other things while that's going on.  RBM does sometimes run all GPUs together but also runs 3080 and 3090 separately sometimes.  The benchmarks are in 3 sets - 3080, 3090 and 3080/3090 together.  I understand getting separate benchmarks would take extra time but it should take about 18 minutes to do the 3 instead of over 30 minutes to do just one.

I've just done some more data captures.  At 5:42PM today, I checked on the rig.  All the GPUs were cold.  Rigel was running Etchash/kHeavyhash.  The last run time in the console was 5:34PM so there's already at least 8 minutes on it.  At 6:07PM, Rigel was still going with no connection/no hashrate.  That makes at least 33 minutes that one was running and most, if not all, was without making a working connection to the pool.  The console now shows that it started Phoenix at 6:08.  All my benchmarks have always (since my first installation of RBM in late Oct or early Nov) taken way longer than the estimates.  That's on my main GPU rig as well as my 3 CPU rigs.

While Rigel was running so long with no connection, I decided to disable extended intervals to see if anything would be different.  I'll check up on that over the next few hours.

While I've been finishing up this post and waiting for the debug file, RBM has switched Extended Intervals off.  Phoenix has been running for 18 minutes according to its API stats:

 *** 0:18 *** 3/12 18:27 **************************************
Eth: Mining ETC on etchash.mine.zergpool.com:9997 for 0:18

  0  H/s 00d/00h/18m Once    Phoenix EtcHash   ETC  RTX 3090,RTX 3080 ZergPoolSolo 0W 

Here's a fresh debug file:
[debug_2023-03-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/10952391/debug_2023-03-12.zip)

**Comment by smyers63** [comment]
Now that the extended interval is off, there's a Bzminer benchmark running for 14 minutes so far with no connection.  It's trying different stratum settings over and over.  The entire benchmark should be over in less than half that time.  If there's no connection after a resonable time, RBM should shut that benchmark down and move on to the next one.


RTX3080-RTX3090 BzMiner

                 | 3:0 | Zotac RTX 3090 Trinity             | 23.78gb | 24.00gb | 8mhz | 14mhz | 0%  | 19w | 25C/34C |
 | 4:0 | Zotac RTX 3080 AMP Holo            | 9.84gb  | 10.00gb | 8mhz | 14mhz | 0%  | 11w | 25C/32C |
 | 5:0 | Gigabyte RTX 3090 Gaming OC        | 23.78gb | 24.00gb | 8mhz | 14mhz | 0%  | 17w | 28C/34C |
 |     |                                    |         |         |      |       |     | 47w |         |
 03-12 19:00:18:0248 ------------------------------------------------------------------------- v13.3.0

 -------------------------- etchash - etchash.mine.zergpool.com:9997 - MINER -------------------------
 | #    | uptime | a/r/i | cfg | tbs | eff  | pool hr | miner hr | status                            | 
 | 3:0  |        | -/-/- |     | --  | 0h/w | --      | --       | Not Mining                        |
 | 4:0  |        | -/-/- |     | --  | 0h/w | --      | --       | Not Mining                        |
 | 5:0  |        | -/-/- |     | --  | 0h/w | --      | --       | Not Mining                        |
 |      |        |       |     |     |      |         |          |                                   |
 | smry | 0:0:13 | -/-/- |     | --  | 0h/w | --      | --       | Connecting...14m                  |
 03-12 19:00:18:0249 ------------------------------------------------------------------------- v13.3.0

 Connecting with stratum failed. Trying ethproxy.
 Reconnecting to ethstratum2+tcp://etchash.mine.zergpool.com:9997 in 15s seconds...
 Connecting to ethstratum2+tcp://etchash.mine.zergpool.com:9997 as MINER with wallet:
 XdnFogHDTofBfByvxDGzqvsLuxrAogK9VP
 Connecting with ethproxy failed. Trying ethstratum.

**Comment by smyers63** [comment]
Still running with 80 benchmarks left and extended intervals off.  Nbminer going 27 minutes with no connection.  My default benchmark interval has always been 60s.

                [19:43:18] INFO - | 0|  3090|  0.000 |     0|     0|  0|  18|  25|  34|  0| 210|  405|Mi|   0|  0.000 |
System.Management.Automation.RemoteException
[19:43:18] INFO - | 1|  3080|  0.000 |     0|     0|  0|  10|  25|  32|  0| 210|  405|Mi|   0|  0.000 |
System.Management.Automation.RemoteException
[19:43:18] INFO - | 2|  3090|  0.000 |     0|     0|  0|  17|  27|  32|  0| 210|  405|Mi|   0|  0.000 |
System.Management.Automation.RemoteException
[19:43:18] INFO - |------------------+------+------+---+----+------------------+-------------+--------|
System.Management.Automation.RemoteException
[19:43:18] INFO - |    Total:  0.000 |     0|     0|  0|  45| Uptime: 0D 00:27  NvDrv: 522.25  CPU: 0%|
System.Management.Automation.RemoteException
[19:43:18] INFO - =====================================================================================
System.Management.Automation.RemoteException
[19:43:18] INFO - etchash - On Pool   10m:  0.000    4h:  0.000    24h:  0.000 
System.Management.Automation.RemoteException
[19:43:18] INFO - etchash - Logging in to etchash.mine.zergpool.com(103.249.70.7):9997 ...
System.Management.Automation.RemoteException
[19:43:18] ERROR - etchash - Login failed: Pool disconnected, protocol may be wrong!
System.Management.Automation.RemoteException
[19:43:18] INFO - Logout.
System.Management.Automation.RemoteException

I think you'll want another debug file when the rest of these 80 benchmarks finish.  I think some have finished in maybe 10 minutes but that's still too long even if extended intervals was still on, I think.  With extended intervals off, it's not reasonable at all to take 10 and sometimes over 20 minutes, especially when the miner isn't even connecting.

**Comment by smyers63** [comment]
I see at the top of this thread, I first posted about this 17 hours ago.  I don't remember exactly how many benchmarks were to be done when this started but it was either 114 or 140.  Out of the total, 80 are left right now.  Here's the math:

140-80=60
17hrs/60 benchmarks = 0.28 hrs avg for each
0.28hrs*60mins/hr = 17 minutes avg per benchmark   - too long at the best case of starting with 140

114-80=34
17hrs/34 benchmarks = 0.5 hrs avg for each (30 mins) - even longer avg

I'm fairly sure the number to start with was 114.  We know that many of the benchmarks are taking over 20 minutes and up to over 30 minutes so it's unlikely that many, if any, were only 17 minutes.  There would have to be quite a few at much less than 17 minutes to bring the average down to 17.

Keep in mind that all these benchmarks that took 20-30+ minutes without ever connecting were not only too long but were actually a complete waste of time and gave no benchmark data.  They'll have to be run again and might not be worthwhile the next time even if they only take a minute each.  That would still be a waste so the reason for them taking so long is one thing.  **The reason they're not connecting is just as important.**

So, I will absolutely be much happier when this is resolved.  I'm deliberately giving up my income for the past 17 hours and the next unknown number of hours so that these benchmarks will finish and we'll have all the data to work with.

I'll post another debug file whenever these are finished so you'll also have info on the last 80+ benchmarks after turning off extended intervals.

**Comment by RainbowMiner** [comment]
Ok! Thank you so much for the in-depth reports. I do think, I know what is going on: the prolonged benchmarks are because of connection issues to ZergPool / Ethash and Progpow variants. This artificially extends the benchmark times, because of a bunch of retries. Thanks to your feedback, I can now double-tripple check the miner/pool protocols easily.

**Comment by RainbowMiner** [comment]
Second thing - you have enabled much too many multi-currency autoexchange pools (I'll give you some hints below). Therefor the RainbowMiner cycle will be automatically extended, because it needs to handle the load of all pool/miner profit calculations on the Celeron CPU.

Notes for multi-currency autoexchange pools: make a choice, do you want to have profit-switching by algorithm (ZergPool and ZergPoolSolo) or do you want to have profit-switching by coin (ZergPoolCoins and ZergPoolCoinsSolo). Same for Zpool.
I strongly advice against using all together. So best choice (in my opinion) is ZergPoolCoins,ZergPoolCoinsSolo,Zpool

**Comment by RainbowMiner** [comment]
Third - you might have stumbled over a combo mode bug in case of 1-0-1 alignment of combos. It would explain why your benchmarks get erased now and then. I'll fix this asap.

**Comment by smyers63** [comment]
> Ok! Thank you so much for the in-depth reports. I do think, I know what is going on: the prolonged benchmarks are because of connection issues to ZergPool / Ethash and Progpow variants. This artificially extends the benchmark times, because of a bunch of retries. Thanks to your feedback, I can now double-tripple check the miner/pool protocols easily.

There are cases where there aren't retires and the benchmark runs far too long.  Even with extended intervals off, no retires, and my benchmark interval set to 60s, there were only 4 benchmarks in the last hour (15 minutes avg).  That is unacceptable for me.  I can decide how long the benchmarks need to be.  I've purposely left the interval at 60s just to see if RBM will do what I tell it to do.  It won't.

**Comment by smyers63** [comment]
> Second thing - you have enabled much too many multi-currency autoexchange pools (I'll give you some hints below). Therefor the RainbowMiner cycle will be automatically extended, because it needs to handle the load of all pool/miner profit calculations on the Celeron CPU.
> 
> Notes for multi-currency autoexchange pools: make a choice, do you want to have profit-switching by algorithm (ZergPool and ZergPoolSolo) or do you want to have profit-switching by coin (ZergPoolCoins and ZergPoolCoinsSolo). Same for Zpool. I strongly advice against using all together. So best choice (in my opinion) is ZergPoolCoins,ZergPoolCoinsSolo,Zpool

I do understand what you said.  I don't see any other way to find out what will be profitable and what will not unless I run the benchmarks for all possibilities first.  After I see the results, I can make a decision.  But since it's taking way too long to get the results, I'm losing interest in continuing to use RBM.

You've brought up another one of my concerns with RBM - that PowerShell usually takes up more than 50% of my CPU cycles.  There are many times when the miner software can hardly get any cycles.  I don't have that problem with the software I used before.  It also runs benchmarks for the duration I want.  You can see where I'm heading.

**Comment by smyers63** [comment]
> Third - you might have stumbled over a combo mode bug in case of 1-0-1 alignment of combos. It would explain why your benchmarks get erased now and then. I'll fix this asap.

Good to know.  When I first started using RBM a few months ago, I only used the default setup.  I don't remember offhand what mining mode that used but that's what I stayed with for a long time.  I had Nicehash, Prohashing, Zergpool and Zpool enabled and that was all for the beginning.  I added 2Miners and a few others a little later.  Benchmarks took way too long then, too.  They were never only 6 minutes or less.  Later, I experimented with the other settings and settled on Combo.  Before using RBM, I always had all GPUs doing the same thing other than a few short times when I experimented with setting different miners/algos/pools on different GPUs.  I never ran like that for long.  I always wanted all to mine the currently most profitable thing.  If I continue using RBM, I might change the mining mode to do that again.  With benchmarks taking so long - even with extended intervals off and the interval set at 60s - I can't really afford to keep using RBM.  I need to know that whatever software I use will do what I expect it to do and that I can walk away from it and not have to think about whether it's actually doing that or not.

**Comment by papadrams** [comment]
Sorry to jump in here. I'll share with you what i have observed.
Most extended benchmarks are supposed to take 3-6 minutes. In stock settings, benchmarkinterval is set to 60.
So it will do 5 to 10 intervals in extended benchmarks. If i set benchmark interval to 90, then it will also do 5 to 10 intervals. it will appear the same 3-6 minutes but it will not be. It will be 5-10 benchmarks with 90secongs of benchmark intervals. So it will actually be 8 to 15 minutes. It looks like extended benchmarks means 5-10 intervals of the benchmarkinterval. But no calculations are done for the approximate time to end. I hope i made myself understood.

**Comment by RainbowMiner** [comment]
I have been able to locate various bugs, that did cause exactly that described behavior. There will be a new release as soon as I am ready with testing out the final version.

**Comment by smyers63** [comment]
> Sorry to jump in here. I'll share with you what i have observed. Most extended benchmarks are supposed to take 3-6 minutes. In stock settings, benchmarkinterval is set to 60. So it will do 5 to 10 intervals in extended benchmarks. If i set benchmark interval to 90, then it will also do 5 to 10 intervals. it will appear the same 3-6 minutes but it will not be. It will be 5-10 benchmarks with 90secongs of benchmark intervals. So it will actually be 8 to 15 minutes. It looks like extended benchmarks means 5-10 intervals of the benchmarkinterval. But no calculations are done for the approximate time to end. I hope i made myself understood.

Are you saying that if the benchmark interval is 60s and there are 5-10 intervals, the 3-6 minute estimates should really be 5-10 minute estimates?  I appreciate any extra data, so no need to apologize.

What do you mean about no calculations being done?  For what time?

Even after turning off extended intervals, benchmarks are still taking 15-30 minutes with the interval set to 60s.  I find that completely unacceptable.

**Comment by smyers63** [comment]
> I have been able to locate various bugs, that did cause exactly that described behavior. There will be a new release as soon as I am ready with testing out the final version.

Could you say which specific behavior(s)?

Thanks.

**Comment by RainbowMiner** [comment]
> Could you say which specific behavior(s)?

- most common causes for crashing miners resolved
- protocol errors of some Ethash/Etchash miners with Zergpool/ZergpoolCoins
- no more benchmarking of GPU combos, only GPU groups will be benchmarked

All of the three have artificially prolonged the benchmarks. The overall benchmark time should be decreased big time.
What is not yet solved: estimated times for individual benchmarks are not adapted to extended cycle times due to longer than expected miner profit calculations. Next, I will try to optimize the miner profit calculations. It's a bit inefficient on a very weak CPU currently. For now I would strongly recommend to use `"MiningMode": "device",` over "combo" on weak CPUs.

**Comment by smyers63** [comment]
I'll go back to device mode, then, in the meantime.
