### ISSUE TITLE
Remove CPU KWH cost from profit

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#232]
Consider removing the KWH usage from CPU mining, the powerdraw from CPU reads closely the same with  or without CPU mining. The actual KWH usage read from the wall can be adjusted on the PowerOffset setting
![image](https://user-images.githubusercontent.com/41829368/47260375-c53b6180-d477-11e8-83c9-5a78870a6e10.png)

**Comment by RainbowMiner** [comment]
We do it now like this: if the rig's PowerOffset value is greater than zero, we will not substract power costs from the CPU mining profit. If there is no PowerOffset in the config.txt, the power costs will be substracted.
