### ISSUE TITLE
WARNING: CIM CPU detection has failed.

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2322]
not exactly a newer machine... not having he issues on older xeon's
[cputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/10997325/cputestresult.txt)

**Comment by RainbowMiner** [comment]
That's interesting. Is this a Windows 10 machine? Did you install the Powershell Core 7.2.x?

**Comment by whitindllc** [comment]
okay did that an here are the results
[cputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/11009794/cputestresult.txt)
[console.txt](https://github.com/RainbowMiner/RainbowMiner/files/11009796/console.txt)


in the config its set as CPU,NVIDIA  under this 
 "DeviceName":  "CPU,NVIDIA",
it just ignores the cpu like it isnt there

**Comment by RainbowMiner** [comment]
Sorry for not having had a look - I'll check this now. So you are still having the same odd warning message?

**Comment by RainbowMiner** [comment]
Ok, I have updated the device detection - please download the following module into your RainbowMiner's `.\Modules` folder [.\Modules\Include.psm1](https://github.com/RainbowMiner/RainbowMiner/raw/master/Modules/Include.psm1) - use right-click + save-as ...

Then restart RainbowMiner and hope for the best :)

**Comment by whitindllc** [comment]
same error on startup
Get-CimInstance: Invalid class
