### ISSUE TITLE
Mining-Pool.ovh

### ISSUE THREAD

**Issue by ericb2233** [RainbowMiner/RainbowMiner#2327]
The instructions for this pool state that a username and password is necessary, however, the website https://www.mining-pool.ovh/ isn't working. Where do we go to obtain a username and password?

**Comment by smyers63** [comment]
Looks like that one's gone:

https://www.whois.com/whois/mining-pool.ovh

**Comment by ericb2233** [comment]
Ok, got it. Thanks.

**Comment by RainbowMiner** [comment]
Yes, this pool is gone. I'll remove it
