### ISSUE TITLE
Poolium

### ISSUE THREAD

**Issue by ericb2233** [RainbowMiner/RainbowMiner#2328]
I think their website has vanished:

https://www.poolium.com/

**Comment by RainbowMiner** [comment]
Too bad - bad yes. That doesn't look good. Better we remove this one as well.

**Comment by smyers63** [comment]
That one isn't gone, at least not for sure yet.  The domain is still registered and the countdown at the site makes it look like it will be back in about 39 days.  If it's removed from RBM for now, it would be a good idea to check on it again later.
