### ISSUE TITLE
SRBMiner gone from benchmarks

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#233]
After updating to I think to 3.8.9.11 SRBminer stats disappeared.  I just updated to .17 and erased srbminer stats but it won't benchmark.

Also what's the procedure to add cryptoknight pool to my config.  I just added it manually because it wasn't in the exclude list.

**Comment by RainbowMiner** [comment]
> After updating to I think to 3.8.9.11 SRBminer stats disappeared. I just updated to .17 and erased srbminer stats but it won't benchmark.

Would you please send me your config.txt and your Logs-folder zipped? I am interested in your selected algorithms. And, maybe I see in the logs what is going on.

**Comment by jch9678** [comment]
Here you go.

[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2501824/config.txt)
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/2501825/Logs.zip)

**Comment by jch9678** [comment]
I uploaded them but they seem to have disappeared....

**Comment by RainbowMiner** [comment]
Yes, github has had a major outage. Now everything should be fine, again.

**Comment by jch9678** [comment]
RainbowMiner should be fine again or my config file and zips should be fine?

**Comment by RainbowMiner** [comment]
Your files. Regarding the SrbMiner: try to add "CryptonightV8" to the list of Algorithms in config.txt

**Comment by RainbowMiner** [comment]
Would you also be so kind and extract the following zip into your Rainbowminer folder, start the "GPUtest.bat" and then drop the newly created file "gputestresult.txt" here? That would help a lot.

[GPUtest.zip](https://github.com/RainbowMiner/RainbowMiner/files/2503657/GPUtest.zip)

**Comment by jch9678** [comment]
Sure, would you like me to add CryptonightV8 to the config.txt first?  Or just try the zip?

**Comment by jch9678** [comment]
It didn't work.

& : File C:\Users\Turbo\Desktop\RainbowMiner\GPUtest.ps1 cannot be loaded. The file C:\Users\Turbo\Desktop\RainbowMiner\GPUtest.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.

At line:1 char:3
+ & .\GPUtest.ps1
+   ~~~~~~~~~~~~~
+ CategoryInfo          : SecurityError: (:) [], PSSecurityException
+ FullyQualifiedErrorId : UnauthorizedAccess

**Comment by RainbowMiner** [comment]
Thanks for trying! Please try again, with this GPUtest. I changed the execution policy, so that it will run on your machine:

[GPUtest.zip](https://github.com/RainbowMiner/RainbowMiner/files/2503705/GPUtest.zip)

**Comment by RainbowMiner** [comment]
Regarding the SrbMiner:
- try to add "CryptonightV8" to the list of "Algorithm" in config.txt
- try to readd "Nicehash" to the list of "PoolName" in config.txt (just to try, because this pool supports CryptonightHeavy and CryptonightV8)

**Comment by jch9678** [comment]
Here are the results

[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2506615/gputestresult.txt)

**Comment by jch9678** [comment]
Adding CryptonightV8 prompted the appropriate miners to benchmark v8 (bad results for my card, or rather non-optimized).  I then added Nicehash but it didn't benchmark heavy so I'm going to delete my stats for the relevant miners.

**Comment by jch9678** [comment]
Oh one other thing.  My card is not compatible with cast-xmr but it tried to benchmark.  Maybe that's what's expected though.

**Comment by RainbowMiner** [comment]
> By the way, when I right click start.bat and choose run as administrator, RainbowMiner doesn't run in powershell, just a cmd window. When I cd into the RainbowMiner directory and .\start.bat it runs in powershell but upon pressing exit, RainbowMiner stops but the window does not close. Is this expected behavior?

Basicly, if you right-click start.bat, yes, it starts a cmd window, but with pwsh running inside. This is intended behaviour. If you press [R]estart or [U]pdate, during runtime, a pure powershell window opens up, and the old cmd will be closed. If you press E[X]it, the cmd should be closed, also. 

Did RainbowMiner run and started to mine, if you right-click started? If not, which powershell version have you installed?

> Oh one other thing. My card is not compatible with cast-xmr but it tried to benchmark. Maybe that's what's expected though.

Yes, this is intended. The miners check for AMD / NVIDIA / CPU, only. They do not know about compatibility of the vendor's card models.

**Comment by jch9678** [comment]
Yeah it runs and starts mining when I right-click start.

I now have v7 v8 and heavy benchmarks for miningpoolhubcoins and nicehash.  Great!
Just need to optimize now and get addresses for the other coins listed on cryptoknight and miner rocks pools.

**Comment by RainbowMiner** [comment]
Perfekt :)
