### ISSUE TITLE
Loading Miner errors.

### ISSUE THREAD

**Issue by bwstandard** [RainbowMiner/RainbowMiner#2339]
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
PS>TerminatingError(): "Job F291679FB76AF999586B78912E0E4465 contains clutter."
>> TerminatingError(): "Job F291679FB76AF999586B78912E0E4465 contains clutter."

I've been getting a lot of these when my miner starts up. 

What do they mean and how can I fix them?

**Comment by RainbowMiner** [comment]
Which pools are you using?

**Comment by bwstandard** [comment]
There were various errors like this. I do recall one specifically was zpools. 

I mainly run Zpool Vipor Zerg Woolypooly HeroMiners AccPool and 2Miners. 

I want to say that I saw something like this down at least 3

**Comment by RainbowMiner** [comment]
Please try the following. Open the url `http://localhost:4000/asyncloaderjobs` , now search the page for one of those job names (these hex codes), e.g. `F291679FB76AF999586B78912E0E4465` - now please upload the resulting record to that job. E.g.

`    "51F1201402993C2120296500D28EF66A": {
      "Url": "https://api.unminable.com/v3/calculate/reward",
      "Host": "api.unminable.com",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Body": {
        "coin": "LTC",
        "mh": 1000000000.0,
        "algo": "kheavyhash"
      },
      "Headers": null,
      "Success": 1305,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2023-04-04T12:38:23.9792297Z",
      "LastCacheWrite": "2023-04-04T12:38:23.980542Z",
      "LastFailRetry": null,
      "LastFailCount": 0,
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Delay": 100,
      "Tag": "unMineable",
      "Timeout": 15,
      "FixBigInt": false,
      "Index": 93
    },
`

**Comment by bwstandard** [comment]
"F291679FB76AF999586B78912E0E4465":  {
                                                 "Url":  "https://www.zpool.ca/api/status",
                                                 "Host":  "www.zpool.ca",
                                                 "Error":  null,
                                                 "Running":  false,
                                                 "Paused":  false,
                                                 "Method":  "REST",
                                                 "Body":  null,
                                                 "Headers":  null,
                                                 "Success":  17,
                                                 "Fail":  0,
                                                 "Prefail":  0,
                                                 "LastRequest":  "\/Date(1680612325196)\/",
                                                 "LastCacheWrite":  "\/Date(1680612325198)\/",
                                                 "LastFailRetry":  null,
                                                 "LastFailCount":  0,
                                                 "CycleTime":  120,
                                                 "Retry":  0,
                                                 "RetryWait":  250,
                                                 "Delay":  750,
                                                 "Tag":  "Zpool",
                                                 "Timeout":  30,
                                                 "FixBigInt":  false,
                                                 "Index":  26

**Comment by bwstandard** [comment]
seems to have fixed the issue so far thanks
