### ISSUE TITLE
Failed to get nicehash balance !

### ISSUE THREAD

**Issue by ArSd-g** [RainbowMiner/RainbowMiner#2349]
Hi there 'til Nicehash adresses for deposit(wallet)/mining are not the same anymore, i can't get my balance to show.
I'm getting mad... i tried everything to get it back to my RB miner screen, but nothing works except if i enter deposit adress for Nicehash but it doesn't product any share (of course it does not !! this is a wallet/deposit adress!)...

I tried to add deposit (wallet) as default adress in default BTC adress in config.txt and mining adress for Nicehash in pool.config.txt= not working, i also tried to enable every "show" Wallet/Pool/Balance options 1b1 = nothing work.
Also what are the correct settings for Nicehash api on nicehash.com?!

Another question when i enable my protonvpn wirguard on my router, nicehash connection doesn't work (connection reset by peer/Gminer) is there a way to bypass this, allow specific port? split tunnelling on my router using PBR but not for 1 port but for RainbowMiner "service" which is (pid)?! ocddeamon?

Fix this please!

**Comment by whitindllc** [comment]
my nicehash balance disappeared as well

**Comment by ArSd-g** [comment]
Also ZergPool mining just disappear also from miners/algo dashboard, i still have the balance but even when i press "V" (verbose) no ZergPool at all on algos, but it is enabled in "pool selection", think it is a time to an upadate about nicehash mining and ZergPool

**Comment by RainbowMiner** [comment]
I will have a look
 Zergpool should be still avail, though

**Comment by ArSd-g** [comment]
Yep NVM, corrupted pool options for zergpool it's working now...but still nicehash doesn't!

**Comment by ArSd-g** [comment]
@RainbowMiner 2 mounths issue is here...still nothing in the last update....

              
Thank you, I will look into it today.
_Originally posted by @RainbowMiner in https://github.com/RainbowMiner/RainbowMiner/issues/2303#issuecomment-1432675259_

**Comment by RainbowMiner** [comment]
Ok, that's a long day, I admit. So could you please give some more information? The thing is, I have my Nicehash mining balance visible in the console, fetched via API.
- Do you want to see your mining balance, or your general Nicehash wallets balance(s)?
- Is the wallet permission enabled for the used API key/secret?
![image](https://user-images.githubusercontent.com/39437538/233834096-deb41a59-309c-4d58-bc19-eafb1cf1672e.png)
- is the wallet invisible on a Linux or on a Windows rig?
- is the rig running as client to a server?

**Comment by ArSd-g** [comment]
Hi, all BTC adress shown are my mining wallet adress on nicehash exept the one in coins.config wich is my regular nicehash wallet....still nothing in rb dashboard, zergpool and others pools are ok!
![api](https://user-images.githubusercontent.com/42816950/233964069-300fd55e-8a67-4e59-ad91-ad8e581e30d3.png)
![coins](https://user-images.githubusercontent.com/42816950/233964083-62a370d4-3581-43a9-9b79-cf5af56af7f6.png)
![config](https://user-images.githubusercontent.com/42816950/233964089-1b256d7d-147e-4c0f-8f3e-8224bd11c9ea.png)
![pool](https://user-images.githubusercontent.com/42816950/233964100-e2c6fa9e-e232-481c-9efa-f2d9871a40a9.png)

**Comment by RainbowMiner** [comment]
Ok, and did you set all three API values, complete with all "-" between the numbers? OrganizationID, API_Key and API_Secret
Since this is a simple balance API key, would you send me the three values by email at rbminer2018@gmail.com, so that I can try to directly access the API with your credentials?

**Comment by ArSd-g** [comment]
@whitindllc check/renew your api keys
@RainbowMiner working now...i don't understand why but my api keys was corrupted without any changes...that's weird i'm investigating...maybe i upload an old pools.config.txt. renew the api keys fixed the problem!
Sorry for disturbing you for a self fixed problem!

**Comment by RainbowMiner** [comment]
No problem! I am happy, if it finally works out for you.

**Comment by ArSd-g** [comment]
Also see #1205 plz
