### ISSUE TITLE
Teamredminer crashes when trying to mine ironfish

### ISSUE THREAD

**Issue by Celldfusion** [RainbowMiner/RainbowMiner#2359]
I noticed that changing the "blake3ironfish" to "ironfish" solves the isue, thats because teamredminer uses -a ironfish instead of -a blake3ironfish to mine, so now is working fine but it can be better if the script come with the issue resolved by default. Another question is if you can upgrade trm to 0.10.12. Thanks in advance

**Comment by RainbowMiner** [comment]
Thank you for reporting this! I will fix it asap, so that it comes clean with the next release tomorrow.
