### ISSUE TITLE
New to RainbowMiner, question about Power Column

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#236]
New to RainbowMiner, question about Power Column.

Are the 0W entries ones that the Miner couldn't report the power usage?
![image](https://user-images.githubusercontent.com/801414/47263280-790e1280-d4b3-11e8-8703-7103f94d6a93.png)

**Comment by RainbowMiner** [comment]
The readout is independant of the GPU/CPU. It should get values greater than zero, over time. If not, it may be the case, that a miner has failed, for some reason. Which GPU are you running?
