### ISSUE TITLE
Missing pool in Server config causes all Clients to enter reconfig loop

### ISSUE THREAD

**Issue by PapaChealio** [RainbowMiner/RainbowMiner#2362]
I ran into this issue today using 4.8.9.0 on both my Server and large Client farm.

When a Server is left with no enabled pool configured (accidental on my part), the next time the clients check in with it and sync enabled pool settings they throw an error and enter the Configuration prompt. Even after correcting the pool definition on the server, trying to eXit the loop on the clients simply returns them back to the Configuration menu (they don't re-poll the Server for updated pool config).

My only method of resolving my locked up Client machines was to abort RBM (CTRL-C) and restart it, after which they picked up the updated Server config.

Ideally, if a Client retrieves a pool list from a Server that is empty, it would simply enter an idle loop for the defined Interval time then re-check with the Server.

**Comment by RainbowMiner** [comment]
Thank you for the report. 

> Ideally, if a Client retrieves a pool list from a Server that is empty, it would simply enter an idle loop for the defined Interval time then re-check with the Server.

... this is very good point. I will add some extra logic to avoid that kind of lock up.

**Comment by RainbowMiner** [comment]
That was much simpler, than I thought. Done.

**Comment by PapaChealio** [comment]
Thanks!
