### ISSUE TITLE
Feature Request: Yellow Highlight the MiningPoolHub Auto Exchange

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#237]
Feature Request: Yellow Highlight the MiningPoolHub Auto Exchange.

Under Pool Balances it would be nice to have the entire line of the Auto Exchange coin balance in Yellow to make it easier to see.

Would have to have a setting in config.txt to set the MPH Autoexchange coin.

**Comment by RainbowMiner** [comment]
Yes, good idea. I will add this.
