### ISSUE TITLE
Client has server not found 

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2372]
I am able to access the localhost:4000 panel when my server is running using user and password, but on my client rig when I attempt to connect to server using appropriate ip address and port shown and same user and password - client returns error "

I noticed that the client was also trying to create its own default username and password, should that be happening if its client?

Any ideas for a solution to connect my clients?

**Comment by whitindllc** [comment]
i have the server setup on port 8000 and let the local clients default to port 4000

**Comment by realsetvin** [comment]
> i have the server setup on port 8000 and let the local clients default to port 4000
> 
> i should specify... i force the clients to connect to the server on port 8000 but then i also allow the local api to run so i can get into each one separately if i need be.... otherwise i wouldnt have been able to tun off srbminer for just 1 algo

Thanks for the reply. Do you think there is some documentation somewhere? Do you think you would be willing to join the rainbow miner discord to discuss this and assist?

**Comment by whitindllc** [comment]
I'm on the rainbow discord... things get answered faster here....

**Comment by realsetvin** [comment]
I resolved this issue. The server was on my windows machine, which for some reason - even with port forwarding and DMZ would not allow any pings in or out on any port with any IP address. 

I switched server to one of the linux miners and now it works perfectly. I think there is something on my windows machine which is causing conflicts as a server. 

Its a pc I have downloaded a lot of video games and random wallets and miner software, so anything is possible. At one time I used this pc for work and had to download a client to work at home, wonder if thats related. I noticed the other day its always phoning home. 

Sticking to linux everything seems to work fine! I will probably have some feedback or suggestions on the webUI - hope it wont be too annoying!

**Comment by realsetvin** [comment]
Closing this issue. 

Basically you can either have clients and servers that are windows based, or you can have clients and servers that are linux based - but having a windows client/server and linux server/client does not work for whatever reason. Even after extensive testing, including but not limited to port forwarding, dmz, disabling and open ports on linux and windows, disabling windows built in protects, ext.
