### ISSUE TITLE
Memehash won't mine or bench with Nvidia

### ISSUE THREAD

**Issue by Robbylikes** [RainbowMiner/RainbowMiner#2373]
For some reason SrbMinerMulti.ps1 will not benchmark. It does say Nvidia, I even tested the miner and it works. How do I fix? Can't mine memehash on Zpool also I assume the issue is present in all algos that say nvida. Could you post a quick copy and paste of the fix? 
Thank you.

**Comment by whitindllc** [comment]
you ran the updater right?

**Comment by Robbylikes** [comment]
Yes. Current ver 4.8.9.4. Zpool just added it not too long ago thought it was gonna auto bench when pool found. Might have something to do with 'when' to benchmark in config maybe?

**Comment by Robbylikes** [comment]
Sorry didn't mean to close

**Comment by Robbylikes** [comment]
I can confirm that SrbminerMulti not the one that says 094 or Srbminer. It seems to show up if I add an AMD GPU but not for Nvidia alone. I checked my conif file all seems good.

**Comment by whitindllc** [comment]
> 

yeah the 2.2.8 version is the one that works with it

**Comment by whitindllc** [comment]
> 

yes.... check the config.txt and see what you have for this chunk
  "EnableAutoUpdate": "1",
  "EnableUpdateDuringPause": "1",
  "EnableUpdateWhenScheduled": "0",
  "EnableAutoAlgorithmAdd": "1",
  "EnableAutoBenchmark": "1",
  "AutoBenchmarkMode": "updated",

**Comment by whitindllc** [comment]
also what is the card?? i have a 1660 that it ignores

**Comment by Robbylikes** [comment]
"EnableAutoUpdate":  "0",
    "EnableUpdateDuringPause":  "0",
    "EnableUpdateWhenScheduled":  "0",
    "EnableAutoAlgorithmAdd":  "1",
    "EnableAutoBenchmark":  "1",
    "AutoBenchmarkMode":  "updated",

**Comment by Robbylikes** [comment]
The GPUs 3x1080, 3x3070, 1x3070ti

**Comment by Robbylikes** [comment]
I think it's the coding for SrbMinerMulti.ps1 in the miners folder could be set for AMD & INTEL GPUs only.

**Comment by whitindllc** [comment]
i cant find much online on what cards are supported... the 3060ti and a4000s i have seem to work

**Comment by whitindllc** [comment]
there is 1 of 2 things you can do to test....
go to the rbm folder and bin.... open any-srbminermulti..... find the file called start-mining-pepepow... run it... right click run as administrator.... see what it does... if it errors out to quick to see then open that file ...go the very bottom and type pause and then save the file and run it again....

it fails on my laptop with AMD video and 5GB of GPU mem

**Comment by Robbylikes** [comment]
Works fine on my Nvidia cards. Just don't start with rainbow miner.

**Comment by Robbylikes** [comment]
I found out what it was. I had checked the logs and found I was using old drivers. After I up dated it began benchmarking.
