### ISSUE TITLE
"zergpool"

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2374]

**Comment by realsetvin** [comment]
"zergpool" not a listed pool option for BCH as payout currency. Miner will not start says no pools found when adding BCH through "co[i]ns" in config

Just shows solo and zergpoolcoins. 

Gives me error of no pools found check config.

**Comment by Robbylikes** [comment]
Copy & replace this is how I got mine to work. I've changed it to BCH if you look at the bottom.

"ZergPoolCoins": {
    "AECurrency": "",
    "Penalty": 12,
    "BTC": "$Wallet",
    "BTC-Params": "",
    "Worker": "$WorkerName",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "0",
    "CoinSymbolPBM": "",
    "DataWindow": "",
    "StatAverage": "",
    "StatAverageStable": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "",
    "MaxAllowedLuck": "",
    "MaxTimeSinceLastBlock": "",
    "MaxTimeToFind": "",
    "Region": "",
    "SSL": "",
    "BalancesKeepAlive": "",
    "BCH": "$BCH",
    "BCH-Params": ""

**Comment by realsetvin** [comment]
Thank you for this solution, Robbylikes. I was able to get it working by adjusting the configs, however shouldn't it work through the options within the miner itself? 

Zergpool has amended their minimum payout of BCH down to 0.0015 so it will be good if it works without adjusting in config.
