### ISSUE TITLE
Fee?

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2376]
Someone told me this miner raises $1 in fees every $2.5 you earn? Is that true? 

I could not see anywhere on the documentation what your fee is. Thank you!

**Comment by RainbowMiner** [comment]
That information is most definitely wrong.

Setting in config.txt
Donate = set the minutes within 24 hours, you want RainbowMiner to work for the developer (min. is 10 minutes, equals to 0.7%) [default=24]

**Comment by realsetvin** [comment]
Thank you for the quick response and detailed information! 

I have been showing other people how you use your tool as I help moderate from Zergpool, this information will be useful. 

Thanks for all you do, my mining experience has changed forever due to this program!
