### ISSUE TITLE
[HEADSUP] I am on conference tour

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#2377]
Hi, since some days I am on crypto conference tour. I had hoped to have more time for programming, but the socializing events keep me pretty busy.
- some more complicated updates, like the new xmrig have to wait until end of next week.
- my response time will be a bit slower than usual

**Comment by realsetvin** [comment]
Thank you for letting us know. A crypto conference sounds fun, best wishes to you! If you have social media we would gladly follow you. 

One thing which I I believe requires some attention, maybe you can look into if you still have some time. 

There was some critical update on verushash recently, and some miners are broken on the current version. They hash but dont report hashrate to pool due to mismatch. I believe some miners are no longer supported by verushash until they update

**Comment by RainbowMiner** [comment]
In fact, this can be easily solved - do you happen to know which of the miners are failing at the moment?

**Comment by sfalas01** [comment]
> In fact, this can be easily solved - do you happen to know which of the miners are failing at the moment?

I believe the only ones working right now are the ones based on ccminer, like CpuminerVerus and CcminerVerus for Nvidia GPUs

**Comment by whitindllc** [comment]
> Thank you for letting us know. A crypto conference sounds fun, best wishes to you! If you have social media we would gladly follow you.
> 
> One thing which I I believe requires some attention, maybe you can look into if you still have some time.
> 
> There was some critical update on verushash recently, and some miners are broken on the current version. They hash but dont report hashrate to pool due to mismatch. I believe some miners are no longer supported by verushash until they update

update to the latest version and then go into the config and find the excludeminers section and add Nheqminer,nqminer to it

**Comment by realsetvin** [comment]
> > Thank you for letting us know. A crypto conference sounds fun, best wishes to you! If you have social media we would gladly follow you.
> > One thing which I I believe requires some attention, maybe you can look into if you still have some time.
> > There was some critical update on verushash recently, and some miners are broken on the current version. They hash but dont report hashrate to pool due to mismatch. I believe some miners are no longer supported by verushash until they update
> 
> update to the latest version and then go into the config and find the excludeminers section and add Nheqminer,nqminer to it

SRBminer is also affect. I have personally just disabled verushash altogether for now until issue is resolved. I was mining for long time before I noticed they were just wasting power.

**Comment by whitindllc** [comment]
> > > Thank you for letting us know. A crypto conference sounds fun, best wishes to you! If you have social media we would gladly follow you.
> > > One thing which I I believe requires some attention, maybe you can look into if you still have some time.
> > > There was some critical update on verushash recently, and some miners are broken on the current version. They hash but dont report hashrate to pool due to mismatch. I believe some miners are no longer supported by verushash until they update
> > 
> > 
> > update to the latest version and then go into the config and find the excludeminers section and add Nheqminer,nqminer to it
> 
> SRBminer is also affect. I have personally just disabled verushash altogether for now until issue is resolved. I was mining for long time before I noticed they were just wasting power.

srb didnt work with luckpool... it was still working with zerg and zpool.... luckpool issue was known a few weeks ago...he disabled nano and srb with the last updates....
https://github.com/RainbowMiner/RainbowMiner/issues/2370

**Comment by realsetvin** [comment]
> > > > Thank you for letting us know. A crypto conference sounds fun, best wishes to you! If you have social media we would gladly follow you.
> > > > One thing which I I believe requires some attention, maybe you can look into if you still have some time.
> > > > There was some critical update on verushash recently, and some miners are broken on the current version. They hash but dont report hashrate to pool due to mismatch. I believe some miners are no longer supported by verushash until they update
> > > 
> > > 
> > > update to the latest version and then go into the config and find the excludeminers section and add Nheqminer,nqminer to it
> > 
> > 
> > SRBminer is also affect. I have personally just disabled verushash altogether for now until issue is resolved. I was mining for long time before I noticed they were just wasting power.
> 
> srb didnt work with luckpool... it was still working with zerg and zpool.... luckpool issue was known a few weeks ago...he disabled nano and srb with the last updates.... #2370

I am using zergpool and srbminer does not appear to work
