### ISSUE TITLE
how do you use an algo that isnt benchmarked

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2379]
on zpool or zergpool there are a few algo's that sometimes pop up with new coins or the coin values pop up... but the algos are not benchmarked or in the main list... like for example skein2 woodcoin.... lets say that coin suddenly starts becoming autotraded/AE again....

if i go to the config and choose skein2 for algorithm nothing happens... all the miners go offline with a watchdog nothing to mine error... is there a way to mine things that arent already listed or in a do not mine list....

tribus over on zpool is another...

**Comment by realsetvin** [comment]
Do you think this occurs when you have low income coins disabled? Or the built in list enabled? Basically one of the settings causing this to happen?

**Comment by IwasthefirstNerrdAlerrt** [comment]
Let’s say it is for an example,  if that became profitable will RM automatically benchmark that coin?  Just curious as I’m new.  Thanks!

**Comment by RainbowMiner** [comment]
Yes, for most of the cases: 1st there needs to be some hashrate on the pool already, 2nd the value for time to find a block needs to be low enough.
