### ISSUE TITLE
SRBMiner not mining BitTube

### ISSUE THREAD

**Issue by giannibonfanti** [RainbowMiner/RainbowMiner#238]
Using CryptoKnight pool, returned algo for BitTube is CryptoNightLiteIpbc.
SRBMiner ps1 file shows cryptonightbittubev2 algo.
In Algorithms.json file, cryptonightbittubev2 is mapped to CryptoNightHeavyTube and not to cryptonightbittubev2.

If I manually change the mapping to "cryptonightbittubev2": "CryptoNightLiteIpbc", it works correctly.

**Comment by RainbowMiner** [comment]
Thank you! I will change it in the algorithm.json.
