### ISSUE TITLE
"Solo" mode

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2383]
I use cpu and gpu to mainly mine on zergpool - it works great so far. I wonder if it would be possible to add a "solo" mode where the autoswitching logic of rainbowminer would be able to pick coins that have lower network hashrate to ensure solo blocks are found, but also be able to switch to most profitable solo coins and leave when the network hashrate is too high and solo is not likely anymore.

**Comment by RainbowMiner** [comment]
Easy: just use ZergPoolCoinsSolo as pool. It is important, that you set some coins in `CoinSymbol` in pools.config.txt (section ZergPoolCoinsSolo), because each coin needs some time to calculate.

**Comment by realsetvin** [comment]
Thank you! Using this so far, I like it! May I also ask what the difference between "zergpool" and "zergpoolcoins" is?

**Comment by RainbowMiner** [comment]
> May I also ask what the difference between "zergpool" and "zergpoolcoins" is?

ZergPool selects per algorithm (ZergPool will automatically preselect the highest paying coin)
ZergPoolCoins selects per highest paying coin using the RainbowMiner algorithm.

Personally, I prefer using ZergPoolCoins and ZergPoolCoinsSolo over using ZergPool. My strategy is to add solo mining coins to "CoinSymbol" (ZergPoolCoinsSolo) while excluding these coins from ZergPoolCoins using "ExcludeCoinSymbol" (ZergPoolCoins).

**Comment by realsetvin** [comment]
Thank you for the comment! Do you prefer to close issues or leave them open and mark them answered?

**Comment by RainbowMiner** [comment]
Actually, if you are satisfied with the answer, just close the issue.
