### ISSUE TITLE
Option to mine a single coin

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2388]
I was trying to mine one of the ghostrider coins specifically - without autoswitching but it does not appear I have the option to do so.
I can only set which algorithm to mine in config on the localhost gui - but that is not enough information to specificy which coin. 
I tried to add "mc=" option to the individual pool configs however this did not work as there are now two mc= options in the miner. 
Is it possible to add a section in the config gui to "mine by specific coin"? Thanks!

![Screenshot from 2023-07-02 13-31-36](https://github.com/RainbowMiner/RainbowMiner/assets/117243445/a2b5dacd-7b2e-4d70-9d16-3fbc3bed90c3)

**Comment by RainbowMiner** [comment]
This is an option, that has to be set at pool-level. As it seems you are using ZergPool, try the following:
- use `ZergPoolCoins` (config.txt / "PoolName" list) instead of `ZergPool`
- if you want to mine other coins/algorithms besides ghostrider:
  put all non-wanted coins into parameter `"ExcludeCoinSymbol": "RTM,ARGY,TAFT,BBC,YERB,GSPC,FSC,BTSC,LTRM,GEC,TCC",` as comma separated list (pools.config.txt, section "ZergPoolCoins")
- if you want to mine ghostrider exclusively:
  put BTRM into parameter `"CoinSymbol": "BTRM",` (pools.config.txt, section "ZergPoolCoins")

**Comment by realsetvin** [comment]
Just tried "coinsymbol" and need to report small problem, I am attempting to mine ARQ as a test (on zergpool) and get paid in another coin, such as XMR. This means I have no ARQ wallet configured on the pool config or coin config. but still attempting to only mine arq with "coinsymbol". The miner stalls and nothing mines, I am guessing its because its waiting for me to include my ARQ wallet since ive written the option to force coinsymbol. But im not quite wanting to get paid in ARQ, only force mine it. 

I was thinking (maybe hoping) it would be possible to add the "mine by coin symbol (or name)" in the config section so that it applies across pools as an over ride. If enable all party solo and shared pools, plus your algo switching variant it can get quite tedious to insert the specific coin to mine in each config file, and then remove them when im done - especially if I was just hoping to quickly mine a coin for a few moments at any given time. 

Thanks for taking time to review my feedback and ideas.

**Comment by realsetvin** [comment]
The option to "mine by algorithm" in the config is almost perfect for my needs - except in the event of multiple coins being on a single algo, then it becomes difficult to specify exactly which coin to mine. In my example of randomarq above I could have just used mine by algorithm randomARQ in the config and that would work the way I was expecting - but only because arqma is the only coin in randomarq. 

In the case of ghostrider if I want to only mine by yerbas, using mine by algo ghostrider wont be useful due to the amount of ghostrider altcoins in zergpool.

**Comment by whitindllc** [comment]
> This is an option, that has to be set at pool-level. As it seems you are using ZergPool, try the following:
> 
>     * use `ZergPoolCoins` (config.txt / "PoolName" list) instead of `ZergPool`
> 
>     * if you want to mine other coins/algorithms besides ghostrider:
>       put all non-wanted coins into parameter `"ExcludeCoinSymbol": "RTM,ARGY,TAFT,BBC,YERB,GSPC,FSC,BTSC,LTRM,GEC,TCC",` as comma separated list (pools.config.txt, section "ZergPoolCoins")
> 
>     * if you want to mine ghostrider exclusively:
>       put BTRM into parameter `"CoinSymbol": "BTRM",` (pools.config.txt, section "ZergPoolCoins")

so i tried that with zpoolcoins and i got this
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/db99636d-08ed-4528-bfaf-0fb3d8f65d3f)

this is the correct setting?
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/4c8fbfd8-9622-4d08-a284-a988ada066dc)
