### ISSUE TITLE
Option to disable coins

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2389]
Had a lot of time on my weekend and spent most of it messing around with rainbow miner trying different coins. 
An option to "temporarily disable" coins would be nice, under each specific coin.
Right now I have the coin I want to mine with a min workers set higher than my total workers - but sometimes they still jump around to other coins on the list. A temporarily disable option or something like that would be useful

**Comment by whitindllc** [comment]
go into the config and look for these two lines... those are 3 that i exclude

  "ExcludeCoin": "Flux,ROD,TNET",
  "ExcludeCoinSymbol": "Flux,ROD,TNET",

**Comment by RainbowMiner** [comment]
Yes, exactly. The important parameter is `"ExcludeCoinSymbol": "",` - this addresses the coin's symbol. The other one ("ExcludeCoin") addresses the coin's name, which isn't always consistent, so use the "ExcludeCoinSymbol"
