### ISSUE TITLE
edit Efficiency column on Activity page

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#239]
Please take into account the minutes column to normalize the reading
![image](https://user-images.githubusercontent.com/41829368/47276916-1c286000-d578-11e8-937e-acd5aba7d8f3.png)

**Comment by RainbowMiner** [comment]
Wow. It looks like github.com is back online, again. They had a bad outage, the past hours.
And yes, you are right. kWh imports the time into the equation. so it is an absolute number. I will multiplicate with the minutes to remove the time from the number.

**Comment by RainbowMiner** [comment]
Sorry, I must revise my last post. The original calculation should give the correct number. The lower efficiency for very short runtimes looks more like a result of rounding. I will review the rounding cascade and see, if it can be sanitized.

**Comment by RainbowMiner** [comment]
Ok, I revised the roundings on the activity page plus I will -.--- all efficiency values, that base on times lower than 1 minute.
