### ISSUE TITLE
Issue with $SKYDOGE

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2390]
Was attempting to mine skydoge directly as I am writing a guide for it and wanted a screenshot of what it looked like to have a worker connected on pool. 

I added skydoge as a coin and also added it to the appropriate pool configs. 

Because "SKYDOGE" is actually 7 characters I think its causing an issue. When forcing all miners to mine skydoge algo, with min 1000 workers (far less than my total) and appropriate pool config set - nothing happens. They idle and my estimated profit per day goes to 0. 

When I examine the pools config section I notice that there is no $SKYDOGE displasy as you would expect - although it is listed in the actual text file. I think this is causing issues because the currency ticker is over 4 digits 

![image](https://github.com/RainbowMiner/RainbowMiner/assets/117243445/08987415-7761-4b5d-a171-774f10629d9d)
normally I would expect $SKYDOGE to display, just like it is with $XMR and other coins ive used

![image](https://github.com/RainbowMiner/RainbowMiner/assets/117243445/d7d13352-7e41-42de-bca8-1acc864422eb)
you can see it was actually written to the file. 

I can fenaggle it to get it working where im only mining skydoge, but I think this could probably be an easy fix just increasing the decimal limit (maybe 9 would be good future proofing just in case)

I did not even know it was possible to have a 7 digit ticker but on xeggex its shown as this so appears correct

**Comment by RainbowMiner** [comment]
If you want to mine that coin directly, you could also use RPlant pool. Only thing is, RPlant uses "SKY" as coin symbol, not "SKYDOGE", so in your pools.config.txt, "RPlant" section you would add
```
  "SKY": "$SKYDOGE",
  "SKY-Params": "",
```

If you want to use ZergPool and wish to mine SKYDOGE and get SKYDOGE, you will have to use "ZergPoolCoins" and set `"SKYDOGE": "$SKYDOGE",` alongside your other autoexchange currency (like `  "BTC": "$Wallet",`).
If you with to mine SKYDOGE exclusively and avoid the profit switching for that pool module, set `"CoinSymbol": "SKYDOGE",`.

**Comment by RainbowMiner** [comment]
Remark on ZergPool: that pool is pretty slow in finding blocks. Currently, it is around 9 blocks per day, which translate in a TTF (time to find) of around 2.67 hours. So make sure, that the following two parameters aren't too restrictive. Otherwise you won't find the SKYDOGE on the All Pools list. In the example, I have set them to 3h (3 hours), which should be ok.
```
    "MaxTimeSinceLastBlock": "3h",
    "MaxTimeToFind": "3h",
```

For comparison: the RPlant pool currently finds around 266 blocks per day, which translate in a TTF of 5.4 minutes.
