### ISSUE TITLE
Worldcurrencies API Failed

### ISSUE THREAD

**Issue by IwasthefirstNerrdAlerrt** [RainbowMiner/RainbowMiner#2392]
I am successfully CPU mining on another computer and today I just received my GPU computer, but I am having difficulties getting RM to run on the new computer.  I completed all the pre-requisites for Windows.  For some reason when starting the start.bat file, I get worldcurrencies API failed when initialize configuration.  All subsequent pool API's fail after I finish configuration.  Any idea why this may be?  Would love to get the GPU up soon!  Thanks!

**Comment by IwasthefirstNerrdAlerrt** [comment]
Well I solved it myself after pulling my hair out!  It was simple.  Make sure your network is on ipv4!  Mine had both ipv6 and ipv4.  Disabled ipv6 and BINGO!

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll try to enhance the networking to IPv6 in the future.
