### ISSUE TITLE
sha256csm (wildrig)

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2395]
I thought at one time this was in rainbow miner but I just attempted to mine this coin and do not see it on the list of available miners. sha256csm (wildrig) is available on zergpool and zpool.

**Comment by whitindllc** [comment]
its gale coin.... its pretty much garbage.... it mines it

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/215829de-b6fe-4a9f-8c7b-e30f446452f6)

**Comment by realsetvin** [comment]
It appears the issue is that it is listed for Zpool, but not Zergpool. When having only zergpool as pool option, its impossible to mine sha256csm even though its an option.

**Comment by realsetvin** [comment]
Ah I see, so certain coins are below a threshold you have set to disallow mining, if I understand correctly? Basically if its "zero" profitability the rainbow miner will refuse to mine it unless that variable is set to 1. 

If for example GALE became profitable would it automatically leave the "do not mine" status? Thanks for input and feedback!

**Comment by whitindllc** [comment]
> @whitindllc just a random remark, it seems, that your machine is running PowerShell 5 (the default, that comes with Windows). I would recommend, you install PowerShell Core 7.2.12 (download the installer from here: https://github.com/PowerShell/PowerShell/releases/download/v7.2.12/PowerShell-7.2.12-win-x64.msi). Do NOT install PS Core 7.3.x nor PS Core 7.4.x. These versions come with a serious memory leak. The version PS Core 7.2.12 is stable.
> 
> GALE is listed on ZergPool and on Zpool. But the profitability swings pretty hefty on ZergPool. Plus, there are times where nobody is mining that sha256csm on ZergPool. If you want to allow RainbowMiner to mine it no matter what, set `"AllowZero": "1",` in pools.config.txt for ZergPool/ZergPoolCoins.

thats version 7.2.12 ...
