### ISSUE TITLE
Hiveon pool API

### ISSUE THREAD

**Issue by IwasthefirstNerrdAlerrt** [RainbowMiner/RainbowMiner#2398]
Any chance to get RM to integrate hiveon API for pool balances?  Thanks for all your hard work!

**Comment by RainbowMiner** [comment]
As far as I remember, Hiveon didn't have a balance-API. I'll have a look in case the pool has added some balance functionality.

**Comment by IwasthefirstNerrdAlerrt** [comment]
There is an option for requesting an api, but not 100% if that is associated with balance. I just noticed the option and assumed as some others pool require api for balance. Thanks for
Checking

**Comment by RainbowMiner** [comment]
I think I might have found some API call that might do the trick. If you have already some balance on that pool, could you please send me your wallet address by email at info@rbminer.net ? With that I can check the API and setup the balance module.

**Comment by UselessGuru** [comment]
Your existing balances module
https://github.com/RainbowMiner/RainbowMiner/blob/master/Balances/Hiveon.ps1

is pretty similar to the NemosMiner one (which does collect the balances from the pool):
https://github.com/Minerx117/NemosMiner/blob/master/Balances/HiveON.ps1

**Comment by RainbowMiner** [comment]
Oh! I already had one in the library :) Thank you for the hint.

**Comment by RainbowMiner** [comment]
Ok, I have added BTC and RVN to the API. It should work now.
