### ISSUE TITLE
algo-min-time bug on monero ocean

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2399]
someone in the monero ocean discord discovered a bug when it came to algo-min-time

![image](https://github.com/RainbowMiner/RainbowMiner/assets/117243445/9017f80a-c418-4070-a258-b6da2e2ec40e)

I am just wondering if its possible the default zergpool logic or your zergpoolcoins logic either would be affected by this potential bug?

**Comment by RainbowMiner** [comment]
Interesting. Yes, that would hurt every other RandomX pool, too.
I think, it will not hurt to increase Xmrig's algo-min-time.
