### ISSUE TITLE
Bug: Fees for Zpool not correct in the console printouts

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#24]
First of all I'm so sorry for spamming issues :) Please forgive me for being such a pain in the a**... Keep u the great work, your miner is much appreciated.

Just to let you know that the fees for Zpool needs to be updated according to the API call, they are 1.75 and not 1%. 

Cheers!

![snip20180816_11](https://user-images.githubusercontent.com/35561346/44231118-50a92580-a19d-11e8-8c3f-1fa8602ab726.png)

{"aergo":{"name":"aergo","port":3691,"coins":1,"fees":1.75,"hashrate":28675263,"workers":6,"estimate_current":"0.00002292","estimate_last24h":"0.00002014","actual_last24h":"0.01594","mbtc_mh_factor":1,"hashrate_last24h":94714451.3229},"allium":{"name":"allium","port":6433,"coins":1,"fees":1.75,"hashrate":479461323,"workers":27,"estimate_current":"0.00002030","estimate_last24h":"0.00001930","actual_last24h":"0.01867","mbtc_mh_factor":1,"hashrate_last24h":284149199.2708},"bitcore":{"name":"bitcore","port":3556,"coins":1,"fees":1.75,"hashrate":1439709512,"workers":37,"estimate_current":"0.00000520","estimate_last24h":"0.00000431","actual_last24h":"0.00562","mbtc_mh_factor":1,"hashrate_last24h":1042046614.7708},"blake2s":{"name":"blake2s","port":5766,"coins":5,"fees":1.75,"hashrate":12711146065463,"workers":2157,"estimate_current":"0.00000371","estimate_last24h":"0.00000461","actual_last24h":"0.00412","mbtc_mh_factor":1000,"hashrate_last24h":11260144087619},"blakecoin":{"name":"blakecoin","port":5743,"coins":2,"fees":1.75,"hashrate":2697468527,"workers":5,"estimate_current":"0.00000034","estimate_last24h":"0.00000038","actual_last24h":"0.00000","mbtc_mh_factor":1000,"hashrate_last24h":10511636581.479},"c11":{"name":"c11","port":3573,"coins":8,"fees":1.75,"hashrate":1057642225,"workers":92,"estimate_current":"0.00000769","estimate_last24h":"0.00000566","actual_last24h":"0.00613","mbtc_mh_factor":1,"hashrate_last24h":1229844376.5729},"decred":{"name":"decred","port":5744,"coins":1,"fees":1,"hashrate":4515327751,"workers":7,"estimate_current":"0.00000034","estimate_last24h":"0.00000032","actual_last24h":"0.00000","mbtc_mh_factor":1000,"hashrate_last24h":255886286933.32},"equihash":{"name":"equihash","port":2142,"coins":6,"fees":1.75,"hashrate":792279.756,"workers":554,"estimate_current":"0.00022529","estimate_last24h":"0.00023842","actual_last24h":"0.20611","mbtc_mh_factor":0.5,"hashrate_last24h":790082.75725},"hex":{"name":"hex","port":5135,"coins":1,"fees":1.75,"hashrate":946152728,"workers":34,"estimate_current":"0.00925022","estimate_last24h":"0.01147483","actual_last24h":"8.23136","mbtc_mh_factor":1000,"hashrate_last24h":823048920.7813},"hmq1725":{"name":"hmq1725","port":3747,"coins":4,"fees":1.75,"hashrate":329717662,"workers":44,"estimate_current":"0.00002107","estimate_last24h":"0.00002191","actual_last24h":"0.02399","mbtc_mh_factor":1,"hashrate_last24h":320293454.0729},"keccak":{"name":"keccak","port":5133,"coins":1,"fees":1.75,"hashrate":33489546060,"workers":72,"estimate_current":"0.00005781","estimate_last24h":"0.00005328","actual_last24h":"0.07690","mbtc_mh_factor":1000,"hashrate_last24h":30802779008.802},"keccakc":{"name":"keccakc","port":5134,"coins":1,"fees":1.75,"hashrate":6925777916,"workers":7,"estimate_current":"0.00006254","estimate_last24h":"0.00006222","actual_last24h":"0.04979","mbtc_mh_factor":1000,"hashrate_last24h":14651109240.542},"lbry":{"name":"lbry","port":3334,"coins":1,"fees":1,"hashrate":341655371179,"workers":52,"estimate_current":"0.00000490","estimate_last24h":"0.00000718","actual_last24h":"0.00000","mbtc_mh_factor":1000,"hashrate_last24h":354079754845.26},"lyra2v2":{"name":"lyra2v2","port":4533,"coins":13,"fees":1.75,"hashrate":47300646739,"workers":308,"estimate_current":"0.00000140","estimate_last24h":"0.00000230","actual_last24h":"0.00236","mbtc_mh_factor":1,"hashrate_last24h":40380827046.158},"lyra2z":{"name":"lyra2z","port":4553,"coins":9,"fees":1.75,"hashrate":2330755421,"workers":280,"estimate_current":"0.00003132","estimate_last24h":"0.00004312","actual_last24h":"0.05173","mbtc_mh_factor":1,"hashrate_last24h":1628389928.1458},"m7m":{"name":"m7m","port":6033,"coins":1,"fees":1.75,"hashrate":24401579,"workers":776,"estimate_current":"0.00006570","estimate_last24h":"0.00018957","actual_last24h":"0.12941","mbtc_mh_factor":1,"hashrate_last24h":23791744.8229},"myr-gr":{"name":"myr-gr","port":5433,"coins":4,"fees":1.75,"hashrate":407097845223,"workers":56,"estimate_current":"0.00005449","estimate_last24h":"0.00004761","actual_last24h":"0.04317","mbtc_mh_factor":1000,"hashrate_last24h":219222460865.31},"neoscrypt":{"name":"neoscrypt","port":4233,"coins":32,"fees":1.75,"hashrate":914701550,"workers":491,"estimate_current":"0.00009001","estimate_last24h":"0.00010327","actual_last24h":"0.02887","mbtc_mh_factor":1,"hashrate_last24h":2622929386.0729},"nist5":{"name":"nist5","port":3833,"coins":5,"fees":1.75,"hashrate":9211972300,"workers":17,"estimate_current":"0.00000718","estimate_last24h":"0.00002541","actual_last24h":"0.02441","mbtc_mh_factor":1000,"hashrate_last24h":34905132785.74},"phi":{"name":"phi","port":8333,"coins":3,"fees":1.75,"hashrate":1557025746,"workers":24,"estimate_current":"0.00000335","estimate_last24h":"0.00000385","actual_last24h":"0.00367","mbtc_mh_factor":1,"hashrate_last24h":1701071542.8646},"phi2":{"name":"phi2","port":8332,"coins":1,"fees":1,"hashrate":166931081,"workers":10,"estimate_current":"0.00000748","estimate_last24h":"0.00002098","actual_last24h":"0.00988","mbtc_mh_factor":1,"hashrate_last24h":312835963.3854},"quark":{"name":"quark","port":4033,"coins":5,"fees":1.75,"hashrate":84081486695,"workers":78,"estimate_current":"0.00005970","estimate_last24h":"0.00004931","actual_last24h":"0.05008","mbtc_mh_factor":1000,"hashrate_last24h":94253530558.865},"qubit":{"name":"qubit","port":4733,"coins":2,"fees":1.75,"hashrate":92833672553,"workers":68,"estimate_current":"0.00006670","estimate_last24h":"0.00006603","actual_last24h":"0.05586","mbtc_mh_factor":1000,"hashrate_last24h":96901473722.344},"scrypt":{"name":"scrypt","port":3433,"coins":41,"fees":1.5,"hashrate":684540939271,"workers":1606,"estimate_current":"0.00069945","estimate_last24h":"0.00058593","actual_last24h":"0.38864","mbtc_mh_factor":1000,"hashrate_last24h":722743119070.69},"scrypt-ld":{"name":"scrypt-ld","port":3434,"coins":31,"fees":1.75,"hashrate":33431714329,"workers":71,"estimate_current":"0.00054472","estimate_last24h":"0.00061013","actual_last24h":"0.48190","mbtc_mh_factor":1000,"hashrate_last24h":29206040102.75},"sha256":{"name":"sha256","port":3333,"coins":34,"fees":1.5,"hashrate":1.3756768927783e+16,"workers":1188,"estimate_current":"0.06521815","estimate_last24h":"0.04489910","actual_last24h":"47.84149","mbtc_mh_factor":1000000000,"hashrate_last24h":1.2636162415944e+16},"sha256t":{"name":"sha256t","port":3339,"coins":1,"fees":1.75,"hashrate":2873390387,"workers":3,"estimate_current":"0.00003589","estimate_last24h":"0.00005063","actual_last24h":"0.04374","mbtc_mh_factor":1000,"hashrate_last24h":2834452404.6563},"sib":{"name":"sib","port":5033,"coins":1,"fees":1.75,"hashrate":38635695108,"workers":31,"estimate_current":"0.00000048","estimate_last24h":"0.00000044","actual_last24h":"0.00044","mbtc_mh_factor":1,"hashrate_last24h":126011651547.91},"skein":{"name":"skein","port":4933,"coins":7,"fees":1.75,"hashrate":799897113472,"workers":267,"estimate_current":"0.00014267","estimate_last24h":"0.00014890","actual_last24h":"0.19092","mbtc_mh_factor":1000,"hashrate_last24h":612098960919.21},"skunk":{"name":"skunk","port":8433,"coins":1,"fees":1.75,"hashrate":339382589,"workers":2,"estimate_current":"0.00000122","estimate_last24h":"0.00000084","actual_last24h":"0.00039","mbtc_mh_factor":1,"hashrate_last24h":361285929.7083},"timetravel":{"name":"timetravel","port":3555,"coins":1,"fees":1.75,"hashrate":1559359379,"workers":20,"estimate_current":"0.00000168","estimate_last24h":"0.00000289","actual_last24h":"0.00275","mbtc_mh_factor":1,"hashrate_last24h":1410259686.6875},"tribus":{"name":"tribus","port":8533,"coins":4,"fees":1.75,"hashrate":2667898994,"workers":22,"estimate_current":"0.00000045","estimate_last24h":"0.00000072","actual_last24h":"0.00075","mbtc_mh_factor":1,"hashrate_last24h":4269290187.1354},"x11":{"name":"x11","port":3533,"coins":45,"fees":1.5,"hashrate":27294863054113,"workers":1562,"estimate_current":"0.00001586","estimate_last24h":"0.00003296","actual_last24h":"0.01737","mbtc_mh_factor":1000,"hashrate_last24h":29571264440470},"x11evo":{"name":"x11evo","port":3553,"coins":1,"fees":1.75,"hashrate":277575375,"workers":17,"estimate_current":"0.00000469","estimate_last24h":"0.00000584","actual_last24h":"0.00581","mbtc_mh_factor":1,"hashrate_last24h":223793680.4271},"x13":{"name":"x13","port":3633,"coins":3,"fees":1.75,"hashrate":133109780369,"workers":136,"estimate_current":"0.00010101","estimate_last24h":"0.00009486","actual_last24h":"0.09310","mbtc_mh_factor":1000,"hashrate_last24h":122547096211.7},"x16r":{"name":"x16r","port":3636,"coins":5,"fees":1.75,"hashrate":6423804883,"workers":364,"estimate_current":"0.00000711","estimate_last24h":"0.00001360","actual_last24h":"0.01529","mbtc_mh_factor":1,"hashrate_last24h":8463814727.1042},"x16s":{"name":"x16s","port":3663,"coins":5,"fees":1.75,"hashrate":1753148127,"workers":62,"estimate_current":"0.00000987","estimate_last24h":"0.00001036","actual_last24h":"0.01101","mbtc_mh_factor":1,"hashrate_last24h":1446980510.7083},"x17":{"name":"x17","port":3737,"coins":4,"fees":1.75,"hashrate":12352587994,"workers":292,"estimate_current":"0.00000853","estimate_last24h":"0.00000978","actual_last24h":"0.00681","mbtc_mh_factor":1,"hashrate_last24h":22367034274.073},"xevan":{"name":"xevan","port":3739,"coins":4,"fees":1.75,"hashrate":1752527856,"workers":280,"estimate_current":"0.00001890","estimate_last24h":"0.00001968","actual_last24h":"0.02051","mbtc_mh_factor":1,"hashrate_last24h":856594560.8021},"yescrypt":{"name":"yescrypt","port":6233,"coins":5,"fees":1.75,"hashrate":4484703,"workers":3017,"estimate_current":"0.00000653","estimate_last24h":"0.00000589","actual_last24h":"0.00605","mbtc_mh_factor":0.001,"hashrate_last24h":5110010.4167},"yescryptR16":{"name":"yescryptR16","port":6333,"coins":1,"fees":1.75,"hashrate":29995,"workers":39,"estimate_current":"0.00002133","estimate_last24h":"0.00002155","actual_last24h":"0.01776","mbtc_mh_factor":0.001,"hashrate_last24h":29481.8542}}

**Comment by RainbowMiner** [comment]
:D Definitly not a pain in the a**, I appreciate your questions and issues very much.
Regarding this issue:
the display is a bit misleading. The Fee column is the miner's fee, not the pool's fee (the latter is not being displayed, yet). Which brings me to the point, that I should reorganize the columns a bit, so that the fee(s) will clear to read.

RBM

**Comment by ebojali** [comment]
Ah ok. So the miner fee, I understand

**Comment by RainbowMiner** [comment]
I changed the RainbowMiners.ps1 to clarify this.
Now it looks like that:
![image](https://user-images.githubusercontent.com/39437538/44235517-172ae700-a1aa-11e8-83eb-f16da877b268.png)

RBM
