### ISSUE TITLE
How to set penalty on any algo?

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#240]
I want to set 10% penalty on x17 algo because of orphan blocks in verge.
Is there any way i can reduce 10% from x17 algo?

**Comment by RainbowMiner** [comment]
No. But it's a good point. I will implement a solution for that.

**Comment by RainbowMiner** [comment]
Done. 🍪  I will publish a release soon.

**Comment by RainbowMiner** [comment]
From v3.8.10.0 on, you may edit file Config\algorithms.config.txt - this files will always contain all possible algorithms. At this time, the only valid parameter is "Penalty" in percent. If you set "Penalty" for X17 to "10", all X17 pool prices will be reduced by 10%. The total penalty factor of a pool price is:

`shown price = api price * (1 - (pool fee + pool penalty + algorithm penalty)/100)`
