### ISSUE TITLE
PMPmining (pool)

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2406]
Requesting what the requirements are to have a new pool added, making my first suggestion of "PMPmining"
They are active and update often, and support various altcoins. 
https://pmpmining.com/

**Comment by PMPMining** [comment]
2nd this!

**Comment by whitindllc** [comment]
> 2nd this!

is it auto exchange?

**Comment by RainbowMiner** [comment]
No, it is not an autoexchange pool. Only pooled coin mining and solo coin mining.

**Comment by realsetvin** [comment]
> No, it is not an autoexchange pool. Only pooled coin mining and solo coin mining.

Is that acceptable? I dont know if you have a list of qualifications you would prefer.

**Comment by realsetvin** [comment]
> 2nd this!

Would you ever consider adding the ability to be paid out in a guarantee payout coin, like BTC or XMR?

**Comment by PMPMining** [comment]
> > 2nd this!
> 
> Would you ever consider adding the ability to be paid out in a guarantee payout coin, like BTC or XMR?

at this time we are not developing that but as we grow we will look into developing that feature.
