### ISSUE TITLE
Email Notification

### ISSUE THREAD

**Issue by ericb2233** [RainbowMiner/RainbowMiner#2408]
I don't think the email notification when a rig is down feature is working. I have my email address loaded and one of my rigs was down for 2 hours and I never received an email.

**Comment by RainbowMiner** [comment]
Are you using the monitoring central on https://rbminer.net/monitoring ? If not, that would explain the email problem. You need to use that. Powershell can't send eMails.

**Comment by RainbowMiner** [comment]
Ok, I have found the problem. It sill be solved asap.

**Comment by ericb2233** [comment]
Thanks. Seems to be working now. I just had a power outage and received a bunch of emails.
