### ISSUE TITLE
Update to 3.8.10 not working even with the solution shown before

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#241]
@RainbowMiner 
Update to 3.8.10 not working even with the solution shown before.

Not sure what log you would like? 

Edit: downloaded the new version copied into my RainbowMiner folder, all seems fine.

[Activity_2018-10-20.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504022/Activity_2018-10-20.txt)
[Activity_2018-10-21.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504023/Activity_2018-10-21.txt)
[Activity_2018-10-22.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504024/Activity_2018-10-22.txt)
[Bminer-GPU#00-GPU#01-30700_2018-10-20_21-59-24.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504025/Bminer-GPU.00-GPU.01-30700_2018-10-20_21-59-24.txt)
[Bminer-GPU#00-GPU#01-30700_2018-10-20_22-01-29.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504026/Bminer-GPU.00-GPU.01-30700_2018-10-20_22-01-29.txt)
[CcminerAlexis78-GPU#00-GPU#01-10200_2018-10-20_22-21-31.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504027/CcminerAlexis78-GPU.00-GPU.01-10200_2018-10-20_22-21-31.txt)
[CcminerAlexis78-GPU#00-GPU#01-10200_2018-10-20_22-22-35.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504028/CcminerAlexis78-GPU.00-GPU.01-10200_2018-10-20_22-22-35.txt)
[CcminerAlexis78-GPU#00-GPU#01-10200_2018-10-20_22-23-36.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504029/CcminerAlexis78-GPU.00-GPU.01-10200_2018-10-20_22-23-36.txt)
[CcminerAlexis78x64-GPU#00-GPU#01-12300_2018-10-20_22-10-55.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504030/CcminerAlexis78x64-GPU.00-GPU.01-12300_2018-10-20_22-10-55.txt)
[CcminerCool-GPU#00-GPU#01-10400_2018-10-20_22-32-43.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504031/CcminerCool-GPU.00-GPU.01-10400_2018-10-20_22-32-43.txt)
[CcminerDumax-GPU#00-GPU#01-12000_2018-10-20_22-03-32.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504032/CcminerDumax-GPU.00-GPU.01-12000_2018-10-20_22-03-32.txt)
[CcminerKlaust-GPU#00-GPU#01-10600_2018-10-20_22-06-43.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504033/CcminerKlaust-GPU.00-GPU.01-10600_2018-10-20_22-06-43.txt)
[CcminerKlaust-GPU#00-GPU#01-10600_2018-10-20_22-08-51.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504034/CcminerKlaust-GPU.00-GPU.01-10600_2018-10-20_22-08-51.txt)
[CcminerSpModPhi-GPU#00-GPU#01-11100_2018-10-20_21-51-03.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504035/CcminerSpModPhi-GPU.00-GPU.01-11100_2018-10-20_21-51-03.txt)
[CcminerSupr-GPU#00-GPU#01-11600_2018-10-20_22-14-17.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504036/CcminerSupr-GPU.00-GPU.01-11600_2018-10-20_22-14-17.txt)
[CpuminerJayddeeAessse42-CPU#00-50102_2018-10-20_21-28-30.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504037/CpuminerJayddeeAessse42-CPU.00-50102_2018-10-20_21-28-30.txt)
[CpuminerJayddeeAessse42-CPU#00-50102_2018-10-20_21-48-58.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504038/CpuminerJayddeeAessse42-CPU.00-50102_2018-10-20_21-48-58.txt)
[CpuminerJayddeeAessse42-CPU#00-50102_2018-10-20_22-11-58.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504039/CpuminerJayddeeAessse42-CPU.00-50102_2018-10-20_22-11-58.txt)
[CpuminerJayddeeAessse42-CPU#00-50102_2018-10-20_22-32-42.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504040/CpuminerJayddeeAessse42-CPU.00-50102_2018-10-20_22-32-42.txt)
[CpuminerJayddeeAvx2-CPU#00-50202_2018-10-20_21-34-40.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504041/CpuminerJayddeeAvx2-CPU.00-50202_2018-10-20_21-34-40.txt)
[CpuminerJayddeeAvx2-CPU#00-50202_2018-10-20_21-55-11.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504042/CpuminerJayddeeAvx2-CPU.00-50202_2018-10-20_21-55-11.txt)
[CpuminerJayddeeAvx2-CPU#00-50202_2018-10-20_22-14-16.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504043/CpuminerJayddeeAvx2-CPU.00-50202_2018-10-20_22-14-16.txt)
[CpuminerJayddeeAvx2sha-CPU#00-50302_2018-10-20_21-40-47.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504044/CpuminerJayddeeAvx2sha-CPU.00-50302_2018-10-20_21-40-47.txt)
[CpuminerJayddeeAvx2sha-CPU#00-50302_2018-10-20_21-59-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504045/CpuminerJayddeeAvx2sha-CPU.00-50302_2018-10-20_21-59-23.txt)
[CpuminerJayddeeAvx2sha-CPU#00-50302_2018-10-20_22-19-25.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504046/CpuminerJayddeeAvx2sha-CPU.00-50302_2018-10-20_22-19-25.txt)
[CpuminerJayddeeSse2-CPU#00-50002_2018-10-20_21-46-53.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504047/CpuminerJayddeeSse2-CPU.00-50002_2018-10-20_21-46-53.txt)
[CpuminerJayddeeSse2-CPU#00-50002_2018-10-20_22-02-33.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504048/CpuminerJayddeeSse2-CPU.00-50002_2018-10-20_22-02-33.txt)
[CpuminerJayddeeSse2-CPU#00-50002_2018-10-20_22-22-34.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504049/CpuminerJayddeeSse2-CPU.00-50002_2018-10-20_22-22-34.txt)
[CpuminerTpruvotAvx2-CPU#00-51002_2018-10-20_22-04-36.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504050/CpuminerTpruvotAvx2-CPU.00-51002_2018-10-20_22-04-36.txt)
[CpuminerTpruvotCore2-CPU#00-51102_2018-10-20_22-06-42.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504051/CpuminerTpruvotCore2-CPU.00-51102_2018-10-20_22-06-42.txt)
[CpuminerTpruvotCorei7-CPU#00-51202_2018-10-20_22-09-56.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504052/CpuminerTpruvotCorei7-CPU.00-51202_2018-10-20_22-09-56.txt)
[CryptoDredge-GPU#00-GPU#01-31300_2018-10-20_22-18-20.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504053/CryptoDredge-GPU.00-GPU.01-31300_2018-10-20_22-18-20.txt)
[CryptoDredge-GPU#00-GPU#01-31300_2018-10-20_22-19-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504054/CryptoDredge-GPU.00-GPU.01-31300_2018-10-20_22-19-26.txt)
[EnemyZealot-GPU#00-GPU#01-30200_2018-10-20_21-28-31.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504055/EnemyZealot-GPU.00-GPU.01-30200_2018-10-20_21-28-31.txt)
[EnemyZealot-GPU#00-GPU#01-30200_2018-10-20_21-46-54.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504056/EnemyZealot-GPU.00-GPU.01-30200_2018-10-20_21-46-54.txt)
[errors_2018-10-21.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504057/errors_2018-10-21.asyncloader.txt)
[errors_2018-10-22.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504058/errors_2018-10-22.asyncloader.txt)
[Ethminer-GPU#00-GPU#01-30100_2018-10-20_21-55-12.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504059/Ethminer-GPU.00-GPU.01-30100_2018-10-20_21-55-12.txt)
[Excavator-31000_2018-10-20_22-02-34.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504060/Excavator-31000_2018-10-20_22-02-34.txt)
[Excavator-31000_2018-10-21_14-05-48.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504061/Excavator-31000_2018-10-21_14-05-48.txt)
[Excavator-31100_2018-10-21_02-27-14.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504062/Excavator-31100_2018-10-21_02-27-14.txt)
[Excavator-31100_2018-10-21_16-17-29.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504063/Excavator-31100_2018-10-21_16-17-29.txt)
[Excavator-31100_2018-10-21_16-26-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504064/Excavator-31100_2018-10-21_16-26-23.txt)
[RainbowMiner_2018-10-20.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504065/RainbowMiner_2018-10-20.txt)
[RainbowMiner_2018-10-20_21-16-31.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504066/RainbowMiner_2018-10-20_21-16-31.txt)
[RainbowMiner_2018-10-20_22-32-17.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504067/RainbowMiner_2018-10-20_22-32-17.txt)
[RainbowMiner_2018-10-21.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504068/RainbowMiner_2018-10-21.txt)
[RainbowMiner_2018-10-21_13-30-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504069/RainbowMiner_2018-10-21_13-30-26.txt)
[RainbowMiner_2018-10-21_13-40-59.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504070/RainbowMiner_2018-10-21_13-40-59.txt)
[RainbowMiner_2018-10-21_13-42-41.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504071/RainbowMiner_2018-10-21_13-42-41.txt)
[RainbowMiner_2018-10-21_13-45-11.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504072/RainbowMiner_2018-10-21_13-45-11.txt)
[RainbowMiner_2018-10-21_13-50-39.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504073/RainbowMiner_2018-10-21_13-50-39.txt)
[RainbowMiner_2018-10-21_14-05-22.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504074/RainbowMiner_2018-10-21_14-05-22.txt)
[RainbowMiner_2018-10-21_14-30-49.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504075/RainbowMiner_2018-10-21_14-30-49.txt)
[RainbowMiner_2018-10-21_14-41-40.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504076/RainbowMiner_2018-10-21_14-41-40.txt)
[RainbowMiner_2018-10-21_19-33-21.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504077/RainbowMiner_2018-10-21_19-33-21.txt)
[RainbowMiner_2018-10-21_19-42-07.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504078/RainbowMiner_2018-10-21_19-42-07.txt)
[RainbowMiner_2018-10-21_19-48-21.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504079/RainbowMiner_2018-10-21_19-48-21.txt)

[RainbowMiner_2018-10-22_07-58-00.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504081/RainbowMiner_2018-10-22_07-58-00.txt)
[RainbowMiner_2018-10-22_07-59-20.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504082/RainbowMiner_2018-10-22_07-59-20.txt)
[RainbowMiner_2018-10-22_08-06-52.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504083/RainbowMiner_2018-10-22_08-06-52.txt)
[RainbowMiner_2018-10-22_08-08-21.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504084/RainbowMiner_2018-10-22_08-08-21.txt)
[RainbowMiner_2018-10-22_13-36-08.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504085/RainbowMiner_2018-10-22_13-36-08.txt)
[RainbowMiner_2018-10-22_13-39-36.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504086/RainbowMiner_2018-10-22_13-39-36.txt)
[RainbowMiner_2018-10-22_18-31-45.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504087/RainbowMiner_2018-10-22_18-31-45.txt)
[RainbowMiner_2018-10-22_18-33-03.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504088/RainbowMiner_2018-10-22_18-33-03.txt)
[RainbowMiner_2018-10-22_18-34-15.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504089/RainbowMiner_2018-10-22_18-34-15.txt)
[RainbowMiner_2018-10-22_18-36-46.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504090/RainbowMiner_2018-10-22_18-36-46.txt)
[RainbowMiner_2018-10-22_18-37-48.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504091/RainbowMiner_2018-10-22_18-37-48.txt)

[Trex-GPU#00-GPU#01-31600_2018-10-20_21-37-45.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504093/Trex-GPU.00-GPU.01-31600_2018-10-20_21-37-45.txt)
[Trex-GPU#00-GPU#01-31600_2018-10-20_22-09-56.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504094/Trex-GPU.00-GPU.01-31600_2018-10-20_22-09-56.txt)
[Trex-GPU#00-GPU#01-31600_2018-10-20_22-24-40.txt](https://github.com/RainbowMiner/RainbowMiner/files/2504095/Trex-GPU.00-GPU.01-31600_2018-10-20_22-24-40.txt)

**Comment by RainbowMiner** [comment]
I would like to find out, what has happened, anyway. When you started the Updater.bat manually, what was the Output? Were there any error messages?

**Comment by RainbowMiner** [comment]
Some error must have been occured, running the Updater.ps1 script. Could you send me your Config\config.txt, please? Eventually there is a special condition. Were you editing text files in some miner binaries folder? I could imagine, that there has been a some access denied during the update.
So or so - I will add more error checks to the update process, that will shift automatic update into the future (or pause it at all) in case of error.

**Comment by paulpoco** [comment]
I only edited the config.txt and pool config.

[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2507170/config.txt)

**Comment by RainbowMiner** [comment]
If you now exit RainbowMiner and click on "Updater.bat" (right-click, run as administrator), does the error message still flash up? You may safely start the updater, it will not overwrite a thing, if it does not find a newer version at github.

**Comment by paulpoco** [comment]
I already just copied the new version over top the old version, replace old with new.

**Comment by RainbowMiner** [comment]
I finally found the reason: if connection to github failed for any reason, the automatic update would enter this loop. So I added multiple improvements, including a limiting the automatic update attempts to 3.
