### ISSUE TITLE
GPU # 0 - Low Hashrate 

### ISSUE THREAD

**Issue by ericb2233** [RainbowMiner/RainbowMiner#2410]
On all 3 of my rigs, whatever GPU is listed as zero, is pulling in much less hashrate than the other GPUs.

**Comment by whitindllc** [comment]
is that the one you have you monitor connected to? im assuming all 3 are the same card

**Comment by ericb2233** [comment]
Yes. One rig is all 1660 Supers. The other two rigs are 3070tis.

**Comment by whitindllc** [comment]
what are the values
for instance i have a machine with 6 a4000's in it.... and 0 is attached to the monitor.... on most et based hashes i get 62mh on all of them but 0 which i have connected to the monitor and im running like 5 broswers and remote monitoring/connection apps... it runs about 40 to 48mh

IF i disconnect the monitor and shut down all of the browsers and come in remotely and look it bumps back up to 61/62 mh

**Comment by ericb2233** [comment]
I have one rig attached to a monitor on its own and the other two rigs share a monitor via a KVM switch. 

Are you saying maybe using the onboard GPU for mining is causing issues?

**Comment by ericb2233** [comment]
I turned off onboard GPU mining for all rigs and things have stabilized. We can close this issue out. Thanks.
