### ISSUE TITLE
nimiq (icemining) api is broke.... 

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2411]
this pool stopped working a bit ago.... I just never got around into look as to why....

WARNING: Pool API (Icemining) returned nothing.

So i did some digging and looked at the icemining powershell file... it makes a call to a site https://api.icemining.ca/api that has an invalid SSL cert...
I talked to the pool admin in discord and he said that the API was decommissioned awhile back and they use https://api.hashrate.to/api/ now... so I edited the powershell script to point to that and it still didnt work... I notice when you go to the website in a browser it loads if you ignore the ssl cert issues and has values.. I let them know all of the RBM miners were being affected by this and he said he would update the cert eventually..

**Comment by RainbowMiner** [comment]
I have removed the certificate checks from the web requests, so that the icemining API should work again.

**Comment by whitindllc** [comment]
i thought that would have worked.... but RBM is still saying icemining api returns nothing
