### ISSUE TITLE
Not able to directly mine a coin on zergpool

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2413]
The coin is "YERBAS" on zergpool. using "mine by algo" wont be sufficient since their are multiple coins on this algo and I only want to mine a single one.

The pool zergpool needs mc=YERB and putting in the "CoinSymbol" YERB option by pool also does not work to produce the desired effect. The miners still are auto mining and getting paid out in YERB, which is not what I want. I want all my gpus and cpus using ghostrider and only mining YERB.

After setting "CoinSymbol" to YERB on Zergpool and Zergpool coins (and ensuring those are the only two pools enabled in the config) the miners just continue to mine autoswitching getting paid out in YERB, not necessarily respecting the "CoinSymbol" flag 

From what I can see its actually not possible to directly mine YERB or any other coin that has multiple coins per algo on zergpool. Maybe I am missing something?

**Comment by whitindllc** [comment]
no i have the same issue

**Comment by RainbowMiner** [comment]
Let's see if I get it right: 
- do you want to mine YERB and being paid in YERB
- or do you want to mine YERB and being paid in BTC
?

In general - mining one single coin can be done with ZergPoolCoins, only. The ZergPool module uses algorithm to select.

**Comment by realsetvin** [comment]
> Let's see if I get it right:
> 
>     * do you want to mine YERB and being paid in YERB
> 
>     * or do you want to mine YERB and being paid in BTC
> 
> 
> In general - mining one single coin can be done with ZergPoolCoins, only. The ZergPool module uses algorithm to select.

I usually select low cap altcoins to get paid out in, for example YERB. In most cases I will have a few pools active, for example zpool zpoolcoins zergpool and zergpoolcoins. I find I get the maximum profits doing autoswitching this was.

There are times, for my own reasons, where I want to participate in a single network more heavily for a short period of time. In this case I want all my CPUs and GPUs to be mining on the YERBAS network in this specific scenerio. This can be for many reasons. When mining low market cap coins zpool and zergpool will run out of coins. The way to "pay yourself" those coins can be to directly mine that coin - which from what In testing I was not able to do in the zergpool module. 

Previously I would have to carry my rigs to my living room tv to program them each individually that way - since I started using client and server mode and the local panel I have found it more useful to change the options in the settings

I did not attempt to directly mine YERB through the zergpoolcoins module - yet. I can try that and report back. I didnt realize it would make a difference between zergpool and zergpoolcoins - actually I figured zergpool module would be best being the "basic" module.

**Comment by whitindllc** [comment]
so i am going to mess with this today.....
so you turn on zergpoolcoins... then you go to pools.config.com and put the coin you want to mine in the coinsymbol or focus wallet?


> Let's see if I get it right:
> 
>     * do you want to mine YERB and being paid in YERB
> 
>     * or do you want to mine YERB and being paid in BTC
> 
> 
> In general - mining one single coin can be done with ZergPoolCoins, only. The ZergPool module uses algorithm to select.

**Comment by realsetvin** [comment]
I have been using the work around of only using zergpoolcoins module because it does work there. I can confirm thats good enough for me that I have been doing that. Attempting to do so on zergpool module (without "coins") does not work. Certainly not a high priority bug since it does work on zergpoolcoins

**Comment by whitindllc** [comment]
well zergpool is autoswitching at the algorithm level at the pool itself... rbm does make that decision... however in the pool config you can control what algorithm to mine

coins was put there with the intent on controlling what coin you want to go after i guess

**Comment by realsetvin** [comment]
> well zergpool is autoswitching at the algorithm level at the pool itself... rbm does make that decision... however in the pool config you can control what algorithm to mine
> 
> coins was put there with the intent on controlling what coin you want to go after i guess

I think I understand what this means now, I can close this issue since I found out how to do it.
