### ISSUE TITLE
 CryptoNight-FireIce250 - "Switch to assembler version for 'amd_avx' cpu's" ?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#242]
CryptoNight-FireIce250 - "Switch to assembler version for 'amd_avx' cpu's" ?

![image](https://user-images.githubusercontent.com/801414/47335378-cdde9400-d63f-11e8-8fdd-d6f411edc2b9.png)

**Comment by RainbowMiner** [comment]
This is a normal information of Xmrig. It switches to a faster assembler kernel automatically, if a avx CPU is detected.
