### ISSUE TITLE
Gminer255 segmentation violation 

### ISSUE THREAD

**Issue by username-rand** [RainbowMiner/RainbowMiner#2429]
Gminer255 gets a segmentation violation on my system trying to mine Cuckatoo32 on Nicehash.  Nothing I can tell from gdb (no symbols).
Ubuntu 22.04.3 LTS

root@miner3:/home/rainbow/RainbowMiner/Bin/GPU-Gminer255# ./temp.sh
./temp.sh: line 7: 319019 Segmentation fault      (core dumped) /home/rainbow/RainbowMiner/Bin/GPU-Gminer255/miner --api 34700 --devices 0 --server grincuckatoo32.auto.nicehash.com --port 9200 --user xxxxxxxxxxxxxxxxxxxxx.miner3 --pass x --worker miner3 --cuda 1 --opencl 0 --watchdog 0 --pec 0 --nvml 1 --algo grin32

**Comment by whitindllc** [comment]
i have issues with 258 as well and bsod's with my nvidia cards...

**Comment by username-rand** [comment]
> i have issues with 258 as well and bsod's with my nvidia cards...

Guess it’s past it’s prime 😊

**Comment by whitindllc** [comment]
i have 3060ti's.... the a4000/5000/6000 dont have any issues at all

**Comment by username-rand** [comment]
Thanks for getting back with me.  I guess my problem is that 3 of my 4 rigs are mixed 30 series and 40 series.  I've discovered that for the 40 series I need to use Nvidia driver 535.  Now I'm trying to figure out why some benchmarks fail.  For all ccminers, they will not run on 535 at all.  Team black requires a library version that that isn't there.  In some cases the miner doesn't support the 4090 and or 4060ti.    In some cases I get errors in the miner about the pool, e.g.,
Bzminer on a 3090 (4090 and 4060ti in same worker) on nicehash mining Blake3Ironfish "Warn> Ironfish pool provided invalid workload: Invalid Body".  BzMiner mines other algorithms on a combination of all three GPU's fine.  I'm trying to go through the failing benchmarks to see if I can figure out what the issue is and whether or not I can fix it or if I need your help or the miner's dev help.

Right now I'm dealing with the one worker that has 4 3080's.  The hash rate is set via the algorithm based on hashrate.no.  RainbowMiner crashes eventually and then Ubuntu.  Appears to be related to the driver causing the crash and that may be related to the overclock.  Started with Nvidia 510 and moved all the way up to 535.  Same thing.  So I need to reduce the memory overclock.  I think I can overclock the miner for each card for each algorithm I'm just not sure which GPU is causing the issue.

Really appreciate your prompt replies, really.  I'm going to try to leave you alone and continue to try to get RainbowMiner stable on each worker for each algorithm.

Thanks

Rand

**Comment by whitindllc** [comment]
if the overclock is killing it.... try 200 on the gpu and 1000 on the memory.... but those are windows numbers... they translate to something different in linux maybe double

so i have trouble with the different kinds of nvidia cards as well.. i dont know about linux but for windows only the studio drivers work when mixing two series of cards... for me i have the a4000's and the 3060ti's... the game drivers crash and burn
