### ISSUE TITLE
Trex 0.7.1

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#243]

**Comment by petrovsky34** [comment]
T-Rex 0.7.1 (TEST)

Added algos: sha256t, timetravel
Replace "--exit-on-fail-shares" parameter with "--reconnect-on-fail-shares"
New/changed arguments:
    --temperature-start: When a GPU cools down to this temperature the miner starts using it again
    --reconnect-on-high-diff: Forces miner to immediately reconnect if the pool difficulty is above this value
    --exit-on-fail-shares: Now replaced with --reconnect-on-fail-shares
    -r (--retries): if set to 0, miner exits immediately upon the first network failure

A few cosmetic changes.

API:
Multiple http://localhost:4067/trex page enhancements, it now displays all the info you see in the console.
New API handler "config".
Some miner parameters can now be changed and saved on the fly.
Please see the help file for additional details.

Bug fixes:
"bad weak ptr" error
Share rejects were not displayed (Suprnova, Aikapool, possibly some others)


Linux
CUDA 9.1:
https://mega.nz/#!CB8VXKbQ!vSttRJ1uFeJpguwJ4QBmzYNaeAP0oJO9hY-HrJ8Ls5w

CUDA 9.2:
https://mega.nz/#!6ElXwaKC!VORd_7kFfFibRqu6vptbWuZDVzKI2d0Um6T2O4CDMzk

CUDA 10.0:
https://mega.nz/#!nBkhQQIR!LPgOOfVAbL9yHymTvvLSo-B9dZzwfRDX_bR-nigka6s


Windows (x64)
CUDA 9.1:
https://mega.nz/#!2ElTzYZK!oPQtKgdMc6mzJftmCPRcdTCI_yxRBmfMbz7GSxxIsUE

CUDA 9.2:
https://mega.nz/#!nI0BEIoJ!rWZMb42bSbuiF6GsKU7cp1s2Q2cdT55oP9KMqOWZd6M

CUDA 10.0:
https://mega.nz/#!SFkxRC6B!yDhIBEHDDIjRAJgJSPY4Qv5vNBpkqVBkGLITgILtvrw

**Comment by RainbowMiner** [comment]
Super! The long awaited update has hit the bench 👍 I will add it at once.
