### ISSUE TITLE
Overclocking Scripts don't appear correct for some miners

### ISSUE THREAD

**Issue by username-rand** [RainbowMiner/RainbowMiner#2430]
1.  RainbowMiner is a copy of "master" not "release" and appears up to date.
2. Worker is all 3080's (although different brands so different max PL's) and I've defined one algorithm profile with overclocks (but I just noticed that there are a few OCprofiles in miners.config.txt which I've now removed).
3. When I look at oc scripts in Bin for different miners they don't all appear correct.  Sometimes some PL's are missing, sometimes they are correct.

For kHeavyHash for example.  Defined in Algorithms at Profile4.
  "kHeavyHash": {
    "Penalty": "0",
    "MinHashrate": "0",
    "MinHashrateSolo": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "MSIAprofile": 0,
    "OCprofile": "Profile4",
    "MinerName": "",
    "ExcludeMinerName": ""
  },

The ocprofiles Profile4 for the 3080s,
  "Profile4-RTX3080": {
    "PowerLimit": 35,
    "ThermalLimit": 65,
    "PriorizeThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "255",
    "LockVoltagePoint": "*",
    "LockMemoryClock": "810",
    "LockCoreClock": "1470",
    "PreCmd": "",
    "PreCmdArguments": "",
    "PostCmd": "",
    "PostCmdArguments": ""
  },

Here are some of the oc scripts for different miners,

Here is Gminer for instance for KHeavyHash.  Note that there is only one PL define for GPU 3 but not for 0, 1, and 2.

#!/usr/bin/env bash
export CUDA_DEVICE_ORDER=PCI_BUS_ID
nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1' -a '[gpu:0]/GPUGraphicsClockOffset[4]=0' -a '[gpu:0]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:1]/GPUPowerMiz
erMode=1' -a '[gpu:1]/GPUGraphicsClockOffset[4]=0' -a '[gpu:1]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockO
ffset[4]=0' -a '[gpu:2]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:3]/GPUPowerMizerMode=1' -a '[gpu:3]/GPUGraphicsClockOffset[4]=0' -a '[gpu:3]/GPUMemoryTransf
erRateOffset[4]=0'
nvidia-smi -i 0 -rgc
nvidia-smi -i 0 -rmc
nvidia-smi -i 1 -rgc
nvidia-smi -i 1 -rmc
nvidia-smi -i 2 -rgc
nvidia-smi -i 2 -rmc
nvidia-smi -i 3 -rgc
nvidia-smi -i 3 -rmc
nvidia-smi -i 3 -pl 120.75
nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1' -a '[gpu:0]/GPUGraphicsClockOffset[4]=255' -a '[gpu:1]/GPUPowerMizerMode=1' -a '[gpu:1]/GPUGraphicsClockOffset
[4]=255' -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockOffset[4]=255' -a '[gpu:3]/GPUPowerMizerMode=1' -a '[gpu:3]/GPUGraphicsClockOffset[4]=255
'
nvidia-smi -i 0 -lgc 1470
nvidia-smi -i 0 -lmc 810
nvidia-smi -i 1 -lgc 1470
nvidia-smi -i 1 -lmc 810
nvidia-smi -i 2 -lgc 1470
nvidia-smi -i 2 -lmc 810
nvidia-smi -i 3 -lgc 1470
nvidia-smi -i 3 -lmc 810

SrbMinerMulti is the same, one one PL set for GPU 3

#!/usr/bin/env bash
export CUDA_DEVICE_ORDER=PCI_BUS_ID
nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1' -a '[gpu:0]/GPUGraphicsClockOffset[4]=0' -a '[gpu:0]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:1]/GPUPowerMiz
erMode=1' -a '[gpu:1]/GPUGraphicsClockOffset[4]=0' -a '[gpu:1]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockO
ffset[4]=0' -a '[gpu:2]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:3]/GPUPowerMizerMode=1' -a '[gpu:3]/GPUGraphicsClockOffset[4]=0' -a '[gpu:3]/GPUMemoryTransf
erRateOffset[4]=0'
nvidia-smi -i 0 -rgc
nvidia-smi -i 0 -rmc
nvidia-smi -i 1 -rgc
nvidia-smi -i 1 -rmc
nvidia-smi -i 2 -rgc
nvidia-smi -i 2 -rmc
nvidia-smi -i 3 -rgc
nvidia-smi -i 3 -rmc
nvidia-smi -i 3 -pl 120.75
nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1' -a '[gpu:0]/GPUGraphicsClockOffset[4]=255' -a '[gpu:1]/GPUPowerMizerMode=1' -a '[gpu:1]/GPUGraphicsClockOffset
[4]=255' -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockOffset[4]=255' -a '[gpu:3]/GPUPowerMizerMode=1' -a '[gpu:3]/GPUGraphicsClockOffset[4]=255
'
nvidia-smi -i 0 -lgc 1470
nvidia-smi -i 0 -lmc 810
nvidia-smi -i 1 -lgc 1470
nvidia-smi -i 1 -lmc 810
nvidia-smi -i 2 -lgc 1470
nvidia-smi -i 2 -lmc 810
nvidia-smi -i 3 -lgc 1470
nvidia-smi -i 3 -lmc 810

However, lolMiner is correct.  There are 4 PL's set.

#!/usr/bin/env bash
export CUDA_DEVICE_ORDER=PCI_BUS_ID
nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1' -a '[gpu:0]/GPUGraphicsClockOffset[4]=0' -a '[gpu:0]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:1]/GPUPowerMiz
erMode=1' -a '[gpu:1]/GPUGraphicsClockOffset[4]=0' -a '[gpu:1]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockO
ffset[4]=0' -a '[gpu:2]/GPUMemoryTransferRateOffset[4]=0' -a '[gpu:3]/GPUPowerMizerMode=1' -a '[gpu:3]/GPUGraphicsClockOffset[4]=0' -a '[gpu:3]/GPUMemoryTransf
erRateOffset[4]=0'
nvidia-smi -i 0 -rgc
nvidia-smi -i 0 -rmc
nvidia-smi -i 1 -rgc
nvidia-smi -i 1 -rmc
nvidia-smi -i 2 -rgc
nvidia-smi -i 2 -rmc
nvidia-smi -i 3 -rgc
nvidia-smi -i 3 -rmc
nvidia-smi -i 0 -pl 119.00
nvidia-smi -i 1 -pl 112.00
nvidia-smi -i 2 -pl 133.00
nvidia-smi -i 3 -pl 120.75
nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1' -a '[gpu:0]/GPUGraphicsClockOffset[4]=255' -a '[gpu:1]/GPUPowerMizerMode=1' -a '[gpu:1]/GPUGraphicsClockOffset
[4]=255' -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockOffset[4]=255' -a '[gpu:3]/GPUPowerMizerMode=1' -a '[gpu:3]/GPUGraphicsClockOffset[4]=255
'
nvidia-smi -i 0 -lgc 1470
nvidia-smi -i 0 -lmc 810
nvidia-smi -i 1 -lgc 1470
nvidia-smi -i 1 -lmc 810
nvidia-smi -i 2 -lgc 1470
nvidia-smi -i 2 -lmc 810
nvidia-smi -i 3 -lgc 1470
nvidia-smi -i 3 -lmc 810

So I would like to get RainbowMiner to re-create the oc scripts in the Bin directory for the existing miners to make sure i've not done something stupid.  Is there a way to do that without starting over?

Thanks

Rand

**Comment by username-rand** [comment]
On another system with three different GPU's, a 4090, 3090, and 4060ti.  Each GPU therefore has an OC script for each algorithm.  I've found an OC script for one GPU that also references another GPU.  This is a BzMiner oc script for sha512256d for GPU 01,

rainbow@miner3:~/RainbowMiner/Bin/GPU-BzMiner$ more startoc_gpu01_sha512256d.sh
#!/usr/bin/env bash
export CUDA_DEVICE_ORDER=PCI_BUS_ID
nvidia-settings -a '[gpu:1]/GPUPowerMizerMode=1' -a '[gpu:1]/GPUGraphicsClockOffset[4]=0' -a '[gpu:1]/GPUMemoryTransferRateOffset[4]=0'
nvidia-smi -i 1 -rgc
nvidia-smi -i 1 -rmc
nvidia-settings -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockOffset[4]=0' -a '[gpu:2]/GPUMemoryTransferRateOffset[4]=0'
nvidia-smi -i 2 -rgc
nvidia-smi -i 2 -rmc
nvidia-smi -i 1 -pl 124.80
nvidia-settings -a '[gpu:1]/GPUPowerMizerMode=1'
nvidia-smi -i 1 -lgc 1305
nvidia-smi -i 1 -lmc 810

This worker also had OC profiles defined in miners that I didn't know about.  I've since cleaned out all the miners OC scripts but I'll have to start over if there is no way to regenerate the OC scripts.

Thanks 

Rand

**Comment by RainbowMiner** [comment]
The OC scripts are being written every time a miner starts. RainbowMiner checks the pl of the GPUs beforehand and if the pl of a GPU already has the correct value, the pl command for that GPU isn't written into the script.

**Comment by RainbowMiner** [comment]
> On another system with three different GPU's, a 4090, 3090, and 4060ti. Each GPU therefore has an OC script for each algorithm. I've found an OC script for one GPU that also references another GPU. This is a BzMiner oc script for sha512256d for GPU 01,
> 
> rainbow@miner3:~/RainbowMiner/Bin/GPU-BzMiner$ more startoc_gpu01_sha512256d.sh #!/usr/bin/env bash export CUDA_DEVICE_ORDER=PCI_BUS_ID nvidia-settings -a '[gpu:1]/GPUPowerMizerMode=1' -a '[gpu:1]/GPUGraphicsClockOffset[4]=0' -a '[gpu:1]/GPUMemoryTransferRateOffset[4]=0' nvidia-smi -i 1 -rgc nvidia-smi -i 1 -rmc nvidia-settings -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockOffset[4]=0' -a '[gpu:2]/GPUMemoryTransferRateOffset[4]=0' nvidia-smi -i 2 -rgc nvidia-smi -i 2 -rmc nvidia-smi -i 1 -pl 124.80 nvidia-settings -a '[gpu:1]/GPUPowerMizerMode=1' nvidia-smi -i 1 -lgc 1305 nvidia-smi -i 1 -lmc 810
> 
> This worker also had OC profiles defined in miners that I didn't know about. I've since cleaned out all the miners OC scripts but I'll have to start over if there is no way to regenerate the OC scripts.
> 
> Thanks
> 
> Rand

That one is pretty weird. Is it possible, that the script is already out of date? You should try to run the miner with that specific algorithm and check, if the script still contains two GPUs.

**Comment by username-rand** [comment]
> The OC scripts are being written every time a miner starts. RainbowMiner checks the pl of the GPUs beforehand and if the pl of a GPU already has the correct value, the pl command for that GPU isn't written into the script.
> 
> If that irritates you, I can easily remove the pl check. Then all pl levels will written to the script.

That explains the reason.  I just didn’t understand why there were not the same number of PL’s as GPU’s.  Guess you don’t reset the PL’s when the miner finishes like you do the overclocks.  Still trying to figure why my 3080 system hangs during benchmarking yet if I run the miner that appears to cause the hang manually with the existing oc script it runs fine.  Thanks

**Comment by username-rand** [comment]
> > On another system with three different GPU's, a 4090, 3090, and 4060ti. Each GPU therefore has an OC script for each algorithm. I've found an OC script for one GPU that also references another GPU. This is a BzMiner oc script for sha512256d for GPU 01,
> > rainbow@miner3:~/RainbowMiner/Bin/GPU-BzMiner$ more startoc_gpu01_sha512256d.sh #!/usr/bin/env bash export CUDA_DEVICE_ORDER=PCI_BUS_ID nvidia-settings -a '[gpu:1]/GPUPowerMizerMode=1' -a '[gpu:1]/GPUGraphicsClockOffset[4]=0' -a '[gpu:1]/GPUMemoryTransferRateOffset[4]=0' nvidia-smi -i 1 -rgc nvidia-smi -i 1 -rmc nvidia-settings -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockOffset[4]=0' -a '[gpu:2]/GPUMemoryTransferRateOffset[4]=0' nvidia-smi -i 2 -rgc nvidia-smi -i 2 -rmc nvidia-smi -i 1 -pl 124.80 nvidia-settings -a '[gpu:1]/GPUPowerMizerMode=1' nvidia-smi -i 1 -lgc 1305 nvidia-smi -i 1 -lmc 810
> > This worker also had OC profiles defined in miners that I didn't know about. I've since cleaned out all the miners OC scripts but I'll have to start over if there is no way to regenerate the OC scripts.
> > Thanks
> > Rand
> 
> That one is pretty weird. Is it possible, that the script is already out of date? You should try to run the miner with that specific algorithm and check, if the script still contains two GPUs.

This machine has always had these 3 GPU’s so it should never had referenced a second gpu in that script unless it was somehow caused by a profile being defined both in algorithms and miners.  I’ll change config.txt to try to run just that miner and algorithm and let you know.  This worker is actually running without intervention.

**Comment by username-rand** [comment]
> > On another system with three different GPU's, a 4090, 3090, and 4060ti. Each GPU therefore has an OC script for each algorithm. I've found an OC script for one GPU that also references another GPU. This is a BzMiner oc script for sha512256d for GPU 01,
> > rainbow@miner3:~/RainbowMiner/Bin/GPU-BzMiner$ more startoc_gpu01_sha512256d.sh #!/usr/bin/env bash export CUDA_DEVICE_ORDER=PCI_BUS_ID nvidia-settings -a '[gpu:1]/GPUPowerMizerMode=1' -a '[gpu:1]/GPUGraphicsClockOffset[4]=0' -a '[gpu:1]/GPUMemoryTransferRateOffset[4]=0' nvidia-smi -i 1 -rgc nvidia-smi -i 1 -rmc nvidia-settings -a '[gpu:2]/GPUPowerMizerMode=1' -a '[gpu:2]/GPUGraphicsClockOffset[4]=0' -a '[gpu:2]/GPUMemoryTransferRateOffset[4]=0' nvidia-smi -i 2 -rgc nvidia-smi -i 2 -rmc nvidia-smi -i 1 -pl 124.80 nvidia-settings -a '[gpu:1]/GPUPowerMizerMode=1' nvidia-smi -i 1 -lgc 1305 nvidia-smi -i 1 -lmc 810
> > This worker also had OC profiles defined in miners that I didn't know about. I've since cleaned out all the miners OC scripts but I'll have to start over if there is no way to regenerate the OC scripts.
> > Thanks
> > Rand
> 
> That one is pretty weird. Is it possible, that the script is already out of date? You should try to run the miner with that specific algorithm and check, if the script still contains two GPUs.

Nothing is wrong.  BzMiner was mining sha512256 on all three GPU, thus it was using a different oc profile.  When I forced it to use only GPU 1, the oc profile was recreated and was correct.  Must have been created when I was trying to get the worker to work without issues.  Thanks.  

Rand
