### ISSUE TITLE
Feature request: Add GPU monitoring statistics on rbminer.net and actions

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#244]
An Idea would be to add GPU monitoring statistics from nvidia-smi prinout like GPU load, GPU mem load and temperature. Additionally would be to add alarms when x % GPU load is lost and perhaps even actions to take like restart rig, restart RBM etc.. I am today using application called Rig monitoring on my phone, as the picture below. I get push notifications when something happens with the GPUs but I can't take actions unless I login to my rig. Just an idea, let me know what you think. (I'm happy to pay for such a service) since I already pay a monthly subscription of 1.5$ for this application. 

![image](https://user-images.githubusercontent.com/35561346/47356329-03c55c00-d6c4-11e8-8464-48669f3ed84e.png)
![image](https://user-images.githubusercontent.com/35561346/47356360-1f306700-d6c4-11e8-9aef-a0d10ebc769e.png)
![image](https://user-images.githubusercontent.com/35561346/47356380-2ce5ec80-d6c4-11e8-9a4d-84c3a2e8771f.png)

**Comment by giannibonfanti** [comment]
@RainbowMiner I would be happy to give my help on this, integrating data to our www.brucomining.com monitoring service!
