### ISSUE TITLE
Failed Benchmarks (Rethereum)

### ISSUE THREAD

**Issue by sfalas01** [RainbowMiner/RainbowMiner#2440]
Rigel and SrbMinerMulti mining on ethashb3 are both marked as failed benchmarks even though they definitely work. SrbMinerMulti even has a submitted share.

![image](https://github.com/RainbowMiner/RainbowMiner/assets/22576563/db676099-5fb1-4551-a0ca-f8db44435ede)
![image](https://github.com/RainbowMiner/RainbowMiner/assets/22576563/d4aee1c2-a966-4bb5-ad9d-642d91f03bc5)
![image](https://github.com/RainbowMiner/RainbowMiner/assets/22576563/520fae44-35a1-4445-b5cb-c80688ed0d37)

**Comment by RainbowMiner** [comment]
Oh! Thank you for that report. I will check their API modules asap.

**Comment by whitindllc** [comment]
its zergpool.... most of the ETHASH algos havent worked for months now
