### ISSUE TITLE
Substitute whattomine api for api.minerstat.com

### ISSUE THREAD

**Issue by Robbylikes** [RainbowMiner/RainbowMiner#2443]
Whattomine api has not worked for some time it might be my V¶N. Not sure, I think using https://api.minerstat.com is better.

**Comment by RainbowMiner** [comment]
We already make use of the minerstat API - the WhatToMine pool module first tries to find a quote on minerstat. If it doen't find one, it moves on to whattomine.

**Comment by Robbylikes** [comment]
Understood, thanks.
