### ISSUE TITLE
Hashcryptos.com API dead does dev know?

### ISSUE THREAD

**Issue by Robbylikes** [RainbowMiner/RainbowMiner#2444]
Could someone alert the dev for hashcryptos.com that the API is down.

**Comment by RainbowMiner** [comment]
Yes, I can. I'll get into contact.

**Comment by Robbylikes** [comment]
Nice...

**Comment by sfalas01** [comment]
```.. loading Hashcryptos
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (The SSL connection could not be established, see inner exception.)" --> One or more errors occurred. (The SSL connection could not be established, see inner exception.)"
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (The SSL connection could not be established, see inner exception.)" --> One or more errors occurred. (The SSL connection could not be established, see inner exception.)"
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (The SSL connection could not be established, see inner exception.)" --> One or more errors occurred. (The SSL connection could not be established, see inner exception.)"
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (The SSL connection could not be established, see inner exception.)" --> One or more errors occurred. (The SSL connection could not be established, see inner exception.)"
WARNING: Pool API (Hashcryptos) returned nothing.
```
Seems like nothing changed so far

**Comment by RainbowMiner** [comment]
Could you please upload a Debug file? The per-session logs contain many more error informations.

**Comment by sfalas01** [comment]
> Could you please upload a Debug file? The per-session logs contain many more error informations.

Might be a little all over the place because I was testing a lot of stuff today

[debug_2023-09-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/12672751/debug_2023-09-20.zip)

**Comment by 05sonicblue** [comment]
I have submitted a PR with the fix. The root cause is that hashcrypto's SSL Cert isn't a wildcard and the API endpoint needed to be updated to drop the subdomain prefix. Once it's merged in, all should be well again with hashcrypto's being used on RainbowMiner calculations.

https://github.com/RainbowMiner/RainbowMiner/pull/2507

**Comment by sfalas01** [comment]
@RainbowMiner
![image](https://github.com/RainbowMiner/RainbowMiner/assets/22576563/9b678f32-32a1-4336-80d2-fcb145d36893)
![image](https://github.com/RainbowMiner/RainbowMiner/assets/22576563/0bb33924-cb99-4729-b657-746242e04976)
It seems there's some mismatch in profitability calculation that makes all CPU algos except RandomX show zero profitability

**Comment by RainbowMiner** [comment]
Yes, looks a bit off. I'll check it.
