### ISSUE TITLE
Disabled MRR algos

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2445]
Hallo!
RBM keeps disabling some algos per rig with no obvious reason.
I have a rig with a 3060ti 8gb, no excluded algos in config, nor in pools.config. But for some reason some algos always stay disabled in mrr.
About the ethash one i guess its because there is a huge dag size for etf according to ethdagsizes in data folder.
Is that correct?

**Comment by papadrams** [comment]
![Screenshot_171](https://github.com/RainbowMiner/RainbowMiner/assets/36564393/0713a44f-a9ba-4710-adac-ccc4f9bdd119)
![Screenshot_172](https://github.com/RainbowMiner/RainbowMiner/assets/36564393/8a5e642a-7f4d-4385-a7a8-73f6c86fa9ba)

**Comment by RainbowMiner** [comment]
Yikes! That ETF Dag size is way off. I'll check what's going on.
