### ISSUE TITLE
Mining Algo on a pool where there is a better hashrate

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#245]
Example BCD, currently RBM sends me to BCD on Blazepool
![image](https://user-images.githubusercontent.com/41829368/47358207-5b44d700-d686-11e8-9126-1145984c8a21.png)

I already run it overnight and the accuracy has gone from 100% to 96% but that still will not give me any rewards for days if any. 

GeForce GTX 1060 6GB (GPU#02)
=============================

Miner         Fee Algorithm      Speed Power*   BTC/Day  USD/Day  Accuracy Pool                     PoolFee
-----         --- ---------      ----- ------   -------- -------- -------- ----                     -------
Trex        1.00% Bcd       11.25 MH/s    79W 0.00005138   0.3276      **96%** BlazePool-BitcoinDiamond   1.00%

where on Icemining I definitely receive rewards 
![image](https://user-images.githubusercontent.com/41829368/47358549-39981f80-d687-11e8-879c-b3f02ce5fc50.png)

If I use the new algo penalty feature that will penalize the algo across pools.

Please add more weight to the algo pool hashrate.

**Comment by hernandn01** [comment]
I did that, I remember you were working on something like that. I see the global hashrate already, so you are on your way
![image](https://user-images.githubusercontent.com/41829368/47364539-d1513a00-d696-11e8-9a42-440b7fac8f50.png)

**Comment by paulpoco** [comment]
Yes I wish there was a way to get more accurate rate for these pools.

Sad when you are safer on Nicehash.

**Comment by RainbowMiner** [comment]
Ok, I added experimental hashrate weight. Testing is on the way.

The following new parameters will be added automatically to the config.txt upon restart:
- `"HashrateWeight": 10,`
    Adjust weight of pool hashrates on the profit comparison in % (0..100, 0=disable)
- `"HashrateWeightStrength": 50,`
    Adjust the strength of the weight (integer, 0=no weight, 100=linear, 200=square)

Formula: 
**`compare price = price * (1-(hashrate weight/100)*(1-(rel. hashrate)^(hashrate weight strength/100))"`**

**Comment by hernandn01** [comment]
Working fine. X17 on Zpool over BCD on Blazepool

![image](https://user-images.githubusercontent.com/41829368/47440771-15fad500-d76c-11e8-8747-5ab231ef39eb.png)

**Comment by RainbowMiner** [comment]
Ha! Wonderful 🍻

**Comment by hernandn01** [comment]
Should Nicehash accuracy be 100% ?
![image](https://user-images.githubusercontent.com/41829368/47454102-89f8a580-d78b-11e8-8fe1-27bd68aa71da.png)

**Comment by hernandn01** [comment]
tried to force skunk on Nicehash using focuswallet but did not worked
![image](https://user-images.githubusercontent.com/41829368/47464081-65112c00-d7a5-11e8-9a1a-54b69415ff91.png)

**Comment by hernandn01** [comment]
I just realized there is no skunk wallet on Nicehash so it worked correctly. Perhaps that should be the behavior for strict autoexchange to BTC pools, to force mine the algo selected on focus wallet

**Comment by RainbowMiner** [comment]
Ok, I change the following for pool NiceHash (and other's which pay using PPS):
- the SwitchingPrevention is switched off
- FastSwitchingMode is switched on

This will always use the live price, ignoring the accuracy. Also, on pool algorithm switching will be fast.

**Comment by hernandn01** [comment]
applied latest commit. Nicehash is in the mix now. Thanks, Price is a little bit low as reported by NLPool but the payment is constant which I prefer 
![image](https://user-images.githubusercontent.com/41829368/47499337-f7a0e200-d81c-11e8-9c41-bb253e1f33a1.png)

**Comment by hernandn01** [comment]
Please review BCD on Blockmasters, it has less hashrate but it is getting a higher profit. if new formula still stands I will apply penalty to Blockmasters. Any suggested number? I have seen 30% penalty commented on discord for Blockmasters
![image](https://user-images.githubusercontent.com/41829368/47508806-0219a680-d832-11e8-8e16-1a7fb3de339c.png)

**Comment by RainbowMiner** [comment]
I would try to change the new parameters, first:
- set `HashrateWeight` to 25
- if it does not help, additionally set `HashrateWeightStrength` to 100, then 150, then 200

**Comment by hernandn01** [comment]
will continue monitoring, it adjust itself after a cycle. Currently mining x22i on Blockmasters (just added) it consumes a lot less kwh, will see 

![image](https://user-images.githubusercontent.com/41829368/47509930-56258a80-d834-11e8-9ed8-baab80cb19ce.png)

**Comment by RainbowMiner** [comment]
So, maybe you should change `HashrateWeight` to 30, anyway. Then those hickups are avoided.

**Comment by hernandn01** [comment]
changed hashrateweight to 30, continue monitoring
