### ISSUE TITLE
New KawPow coins on MoneroOcean

### ISSUE THREAD

**Issue by Kin39** [RainbowMiner/RainbowMiner#2454]
Hello, 
I was looking at Rainbowminer -> All Pools and saw that 2 new KawPow coins where missing from the list (CLORE, XNA). Is there a way to tell RainbowMiner to benchmark/mine these new coins?

Thanks

**Comment by whitindllc** [comment]
so if you get rid of all the pools and just leave MO they dont benchmark?

On MO are you trying to get paid out in them or in xmr?

**Comment by Kin39** [comment]
Sorry, I didn't explain myself very well. It was bedtime where I live ^^

What I mean is: the two coinlists (the one on the MO website and the one inside RainbowMiner) do not match.

**Comment by RainbowMiner** [comment]
I doesn't need to mine these coins, since they share the KawPow algorithm. That's probably already benchmarked with RVN. You won't see those coins in the Active Pools list unless they are more profitable than RVN on KawPow.

**Comment by Kin39** [comment]
"You won't see those coins in the Active Pools list unless they are more profitable than RVN on KawPow."

Thanks, I missunderstood hot the Active Pools Tab works ^^
