### ISSUE TITLE
allow setting difficulty on the password field

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#247]
add a setting in miners.config.txt for difficulty, if set include the difficulty on the password field:
setting for example for icemining
 -p c=BCD,d=0.05

**Comment by RainbowMiner** [comment]
Very good idea. I will add it.

**Comment by RainbowMiner** [comment]
Will be part of the next release:
- add parameter "Difficulty" to miners.config.txt
  - each miner/algo/device combination may have their own static difficulty recm. for any pool
  - e.g. add `"Difficulty": "1000",` for a difficulty of 1000
  - [C]onfiguration->[M]iners may be used to change the diff, too

**Comment by hernandn01** [comment]
please review, difficulty was set on the whole miner and not just limited to an algo
![image](https://user-images.githubusercontent.com/41829368/47441834-4c395400-d76e-11e8-8a3b-bc18693e8877.png)
...
![image](https://user-images.githubusercontent.com/41829368/47441756-12684d80-d76e-11e8-8a90-07e60d04509c.png)

![image](https://user-images.githubusercontent.com/41829368/47441783-257b1d80-d76e-11e8-8b24-31c2ee4f629a.png)

**Comment by RainbowMiner** [comment]
Oh dear! Yes, I will have a look

**Comment by RainbowMiner** [comment]
Ok, found and fixed it.
