### ISSUE TITLE
New Device Name in 3.8.10.1 and Lost MiningPoolHubCoins

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#248]
I'm not sure if they are related but I seem to have lost miningpoolhubcoins for monero.  I have ethash benchmarks for that pool though.

My device name changed from Hawaii to R9200 and so it created all new configs, at least for srbminer.  I now have power readings because of this but it is not accurate.  250W on v8 is too much.

**Comment by RainbowMiner** [comment]
Thank you for the feedback. Yes, for the R9 200 Series I have to add some special handling. Unfortunatly the card Bios does not report the exact model. 
Regarding your configs: I could quickly create some AmdCleanup tool, so that the old settings will be recovered (in fact, RainbowMiner always creates a backup of all config files upon restart). Plus, the old settings should still be inside the miners.config.txt.

**Comment by jch9678** [comment]
It's in there.  It's currently mining cryptonightv8 on nicehash.

[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2512000/config.txt)

**Comment by jch9678** [comment]
None of my optimizations ever get stored in miners.config.txt 
I make my changes in the config files located here.  \Bin\CryptoNight-SRBMiner  I could've sworn that's where you told me previously to make changes.

**Comment by RainbowMiner** [comment]
I just tested with a rig, for me, the MiningPoolHubCoins / cnv8 is available. Would you please click http://localhost:4000/runningconfig.html and copy me your running config?

**Comment by RainbowMiner** [comment]
> None of my optimizations ever get stored in miners.config.txt. I make my changes in the config files located here. \Bin\CryptoNight-SRBMiner I could've sworn that's where you told me previously to make changes.

Yes :) You are right. The Srbminer config files are written to:
"config_SrbMiner-[Algorithm]-[DeviceName].txt"
.. you simply have to rename them to ...-R9200.txt

**Comment by RainbowMiner** [comment]
Actually, I think I have to add the chipset name to the device name of the R9 200 model series for propper power readout. Will do this now and upload another release.

**Comment by jch9678** [comment]
[running config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2512080/running.config.txt)

Here's the running config.  

Which miner's setting get stored in miners.config.txt?  Would wildrig's, for example?

**Comment by RainbowMiner** [comment]
> Which miner's setting get stored in miners.config.txt? Would wildrig's, for example?

Only if you had added extra command line options.

**Comment by RainbowMiner** [comment]
> Here's the running config.

Thank you. Would you send me your Config\miners.config.txt, too, please? Something looks strange.

**Comment by jch9678** [comment]
[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2512116/miners.config.txt)

**Comment by jch9678** [comment]
By the way where would I make changes to WildRig's configs?  The ps1 file?

Also I'm not sure if this matters, but in the RainbowMiner window, where it shows the Command for the miner.  It doesn't show what is actually on the miner for me.  For example the rb window for srbminer double threads is set to false but I have changed it to true in the "config_SrbMiner-[Algorithm]-[DeviceName].txt"  Also I changed the kernel there to 2 and that doesn't show up in the rb window.  Not sure if this is expected just wanted to let you know in case it helps.

**Comment by RainbowMiner** [comment]
> By the way where would I make changes to WildRig's configs? The ps1 file?

You do this in the miners.config.txt - find the miner/algorithm/device combination and put them into the fiels "Params": "[put them in here]"

> Also I'm not sure if this matters, but in the RainbowMiner window, where it shows the Command for the miner. It doesn't show what is actually on the miner for me. For example the rb window for srbminer double threads is set to false but I have changed it to true in the "config_SrbMiner-[Algorithm]-[DeviceName].txt" Also I changed the kernel there to 2 and that doesn't show up in the rb window. Not sure if this is expected just wanted to let you know in case it helps.

What you see in the RainbowMiner console is the default, only. Your config files in the Bin folder of SrbMiner override those.

**Comment by RainbowMiner** [comment]
"WildRig-R9200": [
      {
        "MainAlgorithm": "Bcd",
        "SecondaryAlgorithm": "",
        "Params": "[in here you put command line parameters for Wildrig BCD, for example]",
        "MSIAprofile": "",
        "OCprofile": "",
        "Difficulty": ""
      },
      {
        "MainAlgorithm": "Bitcore",
        "SecondaryAlgorithm": "",
        "Params": "",
        "MSIAprofile": "",
        "OCprofile": "",
        "Difficulty": ""
      },

**Comment by RainbowMiner** [comment]
But wait some minutes, before you start entering your parameters. I will quickly rework the model detection for R9 200 series, so the devicemodel names will change again.

**Comment by jch9678** [comment]
No problem I won't start doing that.  I'm so used to working with config and not command line parameters that I had been looking in Bin\AMD-WildRig to modify config files without realizing most of the other miners will just need command line parameters.

**Comment by RainbowMiner** [comment]
Ok, I did it. Now it should detect your card as Radeon R9 290X
Would you try it out? This is the zip containing the updated files: 
[Include_v3.8.10.2.zip](https://github.com/RainbowMiner/RainbowMiner/files/2512533/Include_v3.8.10.2.zip)

**Comment by jch9678** [comment]
Sure.  Give me about 1-2 hours

**Comment by RainbowMiner** [comment]
No hurry! I am happy, if you can help.

I updated the include again:
[Include_v3.8.10.2b.zip](https://github.com/RainbowMiner/RainbowMiner/files/2512803/Include_v3.8.10.2b.zip)

**Comment by RainbowMiner** [comment]
Super :) The power is derived from AMD's TDP value. Do you have a measurement at the wall? I am may adjust the tdp value of 250W.

Regarding MiningPoolHubCoins: let's go in depth for that. If you click http://localhost:4000/allpools.html , then look into the "Pool" select list, is MiningPoolHubCoins there? If yes, is CryptoNightV8 availabe? If yes, please click on the "+" in the first column of the MPH/Cnv8 row and send me the details.

If you click on http://miningpoolhub.com/index.php?page=api&action=getminingandprofitsstatistics - does it work? Or do you get an error 503 or something like that?

**Comment by jch9678** [comment]
I have a kill-a-watt on 2 reference 290x cards mining monero, unfortunately I'm not at that location right now but I think it's reading 325 watts for both.  At least it was measuring that for v7, I think v8 uses a little more power.  I may be able to see it this weekend.  

Yes MiningPoolHubCoins is there and it does appear to be available. However I think I see a problem.  Instead of 3 entries, 1 for each europe, asia, and us-east, I have 6 entries, 2 for each location.  In fact it looks like some of the other coins are doubled up. Once exception is the ethash algos, and those do show up in the rainbowminer window, at least ethereum does.
[v8 Pools Column - 1st entry.txt](https://github.com/RainbowMiner/RainbowMiner/files/2515479/v8.Pools.Column.-.1st.entry.txt)
[v8 Pools Column - 2nd Entry.txt](https://github.com/RainbowMiner/RainbowMiner/files/2515480/v8.Pools.Column.-.2nd.Entry.txt)

On second thought, the only difference is the protocol so maybe that's not a problem.  The api link works.

**Comment by RainbowMiner** [comment]
> I have a kill-a-watt on 2 reference 290x cards mining monero, unfortunately I'm not at that location right now but I think it's reading 325 watts for both. At least it was measuring that for v7, I think v8 uses a little more power. I may be able to see it this weekend.

I will add a power correction factor to devices.config.txt, so that you may adjust the results. AMD cards do not power measurment circuits on board, so the value needs to be aproximated (currently, RainbowMiner uses AMD's reference values for that). For your card, the TDP would be 250W at 100% load.
The new factor will be in percent: for your case, you will place a value of around 175W/250W x 100 = 87.5

**Comment by jch9678** [comment]
Ok, cool.  It might need to be a power correction factor per algo.  It can be vary quite a bit otherwise it will always show up as 175W.  Any luck with my MiningPoolHubCoins problem?

**Comment by RainbowMiner** [comment]
The relative uilization is being drawn from the AMD and multiplicated by AMD's TDP, so the different algorithm should already deliver different power reading, automatically.

**Comment by jch9678** [comment]
Oh that's great.  Very cool.

**Comment by jch9678** [comment]
Hmmm, when CryptoNightV8 is selected I get 2 pools, both nicehash:

Algorithm: CryptoNightV8  Name:  NiceHash  Host: cryptonightv8.usa.nicehash.com
&
Algorithm: CryptoNightV8-NHMP  Name:  NiceHash  Host: nhmp.usa.nicehash.com

When I choose CryptoNightV8 I only get this 1 pool (the second one above):

Algorithm: CryptoNightV8-NHMP  Name:  NiceHash  Host: nhmp.usa.nicehash.com

**Comment by jch9678** [comment]
Looks like that may be expected behavior.  Not sure what to do.  Should I exclude MiningPoolHubCoins, restart, let it run for a minute, exit, then re-add MiningPoolHubCoins...could something like that work?

**Comment by RainbowMiner** [comment]
I think, I found the problem: it is electroneum mining at miningpoolhub. There is a price of 0 with a very high hashrate, thus artificially decreasing the monero stable price when comparing to nicehash (or other pools).
The release v3.8.10.5 contains a fix for that.

**Comment by jch9678** [comment]
Thank you.  I did notice that high hashrate for electroneum but would never have put that together.  Updating now.

**Comment by RainbowMiner** [comment]
Of course, the MiningPoolHubCoins StablePrice * (1-MarginError)  must be higher than the Nicehash Price to be selected.

**Comment by jch9678** [comment]
I'll let it run some more but I'm not seeing MiningPoolHubCoins in the powershell window at all now except for digibyte skein.  Before ethash is always lurking towards the top.

**Comment by RainbowMiner** [comment]
Nicehash might dominate the list at the moment, because it's live price is used to campare against the other pools (see details of All Pools  list at localhost; Nicehash uses "Price", all other pools use "StablePrice*(1 - MarginError)")

**Comment by jch9678** [comment]
Ok. Some of the MPHCoins came back.  I'm going to take a screenshot and post it so you can tell me if it's working right.

**Comment by jch9678** [comment]
![rainbowminer](https://user-images.githubusercontent.com/12422346/47591336-d9c6a080-d934-11e8-8a78-0c54a335e81d.jpg)

**Comment by RainbowMiner** [comment]
Perfect :)

**Comment by jch9678** [comment]
Phew, thanks for all that.  Because this computer has such a small screen, I constantly have to scroll up as the window refreshes.  Can something be done about that?  I know I should just turn verbose off but I like seeing it all for some reason.  Just wondering, this should be the lowest priority if it's even possible.  Thanks again for all your help.

**Comment by RainbowMiner** [comment]
> I'll just change the font size :)

I will have a look, if this could be done automatically, respecting the window's width.
