### ISSUE TITLE
Monitoring Central knows BTC to my currency but other part shows as USD & EU

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#249]
Monitoring Central knows BTC to my currency but other part shows as USD & EU.
![screenshot_20181024-154414_chrome](https://user-images.githubusercontent.com/801414/47466020-321a6880-d7a4-11e8-99e2-a7c0625f03bf.jpg)

**Comment by RainbowMiner** [comment]
Yes, that is by design, to keep the green line readable and on screen. The inner, grey line can be scrolled.

**Comment by paulpoco** [comment]
It not about the green line being readable, it is the wrong Currency being USD & EU.

**Comment by RainbowMiner** [comment]
Solved :) please reload page.
