### ISSUE TITLE
BZMiner v17.0.0 is available

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2496]
https://www.bzminer.com/releases/v17.0.0/

Note: I cannot get it to work under windows (miner just closes without message - I am still investigating).
Does it work for you?

**Comment by RainbowMiner** [comment]
I will try today.

**Comment by RainbowMiner** [comment]
It seems to run with no problem. Do you have a mixed Nvidia/AMD/Intel rig?

**Comment by UselessGuru** [comment]
>  Do you have a mixed Nvidia/AMD
Yep (No Intel).
I got it to work on my 'normal' computer, but not on my Notebook.

**Comment by RainbowMiner** [comment]
Is the miner crash happening when starting on Nvidia or AMD or on both?
Because there is an option for bzminer (--disable-opencl) to help with driver problems when mining on Nvidia but not on Amd
