### ISSUE TITLE
Mining with cpu and SRBminermulti with full threads issue

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2498]
Hallo,
When srbminermulti is using full threads of the cpu, rainbowminer cannot do its runs
I'll go ahead and set an example.
I have a ryzen 5600g. when its mining verushash, its using all 12 threads. Rainbowminer will stay stuck forever in "Finished waiting - starting next run".
They way i found to solve this is to go to miners.comfig, under srbminermulti in all algos set "--cpu-threads-priority 1" in params
For a general fix and let noone have this issue again i thought of this, i just dont have the knowledge to right in in .ps1 file:

In srbminermulti.ps1 there shouyld be a command where
if mining with cpu and cpumining threads = max cpu mining threads then set params --cpu-threads-priority 1

**Comment by RainbowMiner** [comment]
I always leave two threads for RainbowMiner, but the thread priority option sounds really useful. I will add it.
