### ISSUE TITLE
Configuration keeps restarting

### ISSUE THREAD

**Issue by RetroShag** [RainbowMiner/RainbowMiner#25]
I'm running start.bat as per readme file.  However, the configuration keeps restarting even after filling out all the information.  Unable to proceed to miners download.
![image](https://user-images.githubusercontent.com/39284708/44295602-57599a80-a27a-11e8-878c-81c4b1aedaea.png)

**Comment by RainbowMiner** [comment]
Thank you for this issue. Up to which point do you get?
Did you see this line "[W]allets, [C]ommon, [E]nergycosts, [S]election, [A]ll, [M]iner, [P]ools, E[x]it configuration and start mining" ?

RBM

**Comment by RainbowMiner** [comment]
Oh dear! I found, that I introduced a bug in the yesterday's release. I will immediately correct this and push a new release. Totally sorry for that.

RBM
