### ISSUE TITLE
SRBminer-Multi 2.3.7 available now

### ISSUE THREAD

**Issue by tcj2001** [RainbowMiner/RainbowMiner#2500]
https://github.com/doktor83/SRBMiner-Multi/releases/tag/2.3.7
Can you add this one, this has huge hashrate improment on Dynex with AMD and NVIDIA cards

**Comment by UselessGuru** [comment]
Implemented in https://github.com/RainbowMiner/RainbowMiner/commit/bcee311d00b8b77e85e61a4cf9bc6b0de558e3f5
