### ISSUE TITLE
SrbMinerMulti multi coin script error

### ISSUE THREAD

**Issue by username-rand** [RainbowMiner/RainbowMiner#2506]
SrbMinerMulti fails running multiple coins.  Tried this script generated by RainbowMiner manually and reporting the result:

root@Miner3:~/RainbowMiner/Bin/ANY-SRBMinerMulti# more ./temp.sh
#!/usr/bin/env bash
export DISPLAY=:0
cd /
cd '/home/user/RainbowMiner/Bin/ANY-SRBMinerMulti'
export CUDA_DEVICE_ORDER=PCI_BUS_ID
/home/user/RainbowMiner/Bin/ANY-SRBMinerMulti/SRBMiner-MULTI --api-enable --api-
port 34900 --api-rig-name miner3 --esm 2 --gpu-id 0 --disable-cpu --disable-gpu-
amd --disable-gpu-intel --gpu-dual-max-loss 0 --algorithm ethash;blake3_alephium
 --pool daggerhashimoto.auto.nicehash.com:9200 --pool blake3-us.unmineable.com:3
333 --wallet 35FyeBfhL27PG6MVpwwTGQhocvpxFdP5Uh.miner3 --wallet BTC:35FyeBfhL27P
G6MVpwwTGQhocvpxFdP5Uh.miner3#9fh9-4fa8 --password x --password x --tls false --
tls false --nicehash true --nicehash false --keepalive --retry-time 10 --disable
-startup-monitor

The result running this as root manually displays:

root@Miner3:~/RainbowMiner/Bin/ANY-SRBMinerMulti# ./temp.sh
You must first set --pool parameter
./temp.sh: line 6: blake3_alephium: command not found

**Comment by RainbowMiner** [comment]
It seems like we have to escape the ";" on Linux machines. Please try the above fix. Does it work for you?

**Comment by username-rand** [comment]
Sorry I've been busy and this is the first chance I've had to answer your question.  Yes ";" works.  ';' also works.  The difference I believe is that "" allows expression evaluation between the "".  '' does not allow expression evaluation, it's take it as it is.

Thanks for this.  

Rand

**Comment by username-rand** [comment]
Thanks again.  I'll close the issue.
