### ISSUE TITLE
Block Masters added European servers

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#251]
We have added European servers! Please access these by using stratum+tcp://eu.blockmasters.co[:port] and share your feedback on our D

**Comment by RainbowMiner** [comment]
Ah, wow! Good. I will add them.

**Comment by petrovsky34** [comment]
We have added European servers! Please access these by using stratum+tcp://eu.blockmasters.co[:port] and share your feedback on our Discord.

**Comment by petrovsky34** [comment]
SPASIBO)))
THANKS)))
