### ISSUE TITLE
Question to all CPU miner regarding CpuminerJayddee

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#252]
I plan to replace the four individual miner files CpuminerJayddeeXXX with one universal miner file CpuminerJayddee - this will autodetect the best exe to be used.

My question:
Do you have individual miner settings in use for the old CpuminerJayddeeXXX (miners.config.txt / Params)?

**Comment by RetroShag** [comment]
Not I.

**Comment by RainbowMiner** [comment]
Ok, I will change this in v3.8.10.3, then:
- CpuminerJayddeeXXX will be moved to MinersOldVersions
- CpuminerJayddee replaces all four CpuminerJayddeeXXX

**Comment by RetroShag** [comment]
I think the upgrade works, and the correct cpu miner is selected for the processor.  However, it doesn't collect the power used by the cpu miner.  Can that be added back in?

**Comment by RainbowMiner** [comment]
Perfect :) 

> Can that be added back in?

Yes, I fixed it. I will have a look onto another issue, after that I upload an update.

**Comment by RainbowMiner** [comment]
Fixed with v3.8.10.6
