### ISSUE TITLE
Grammar errors in README.md inside section "FEATURES SUMMARY"

### ISSUE THREAD

**Issue by ayushrakesh** [RainbowMiner/RainbowMiner#2520]
I have noticed two grammatical mistakes in specified section .

" from specific algorithm and miners" should be " from specific algorithms and miners"

" core, power limit and voltage"  should be " core, power limit, and voltage"

screenshot-

![Screenshot (167)](https://github.com/RainbowMiner/RainbowMiner/assets/115995339/ed0c3ca1-be76-455d-b9c4-d7e6704549c5)

**Comment by RainbowMiner** [comment]
Thank you! I will fix it.
