### ISSUE TITLE
Probably wrong string construction for miners when using HashCryptos pool

### ISSUE THREAD

**Issue by sfalas01** [RainbowMiner/RainbowMiner#2524]
Miners crash when trying to mine in Yes-x (crypt or power variants) algorithms on HashCryptos. Probably due to bad miner string command construction. This happens to both CPU and GPU

Here's a debug log:
[debug_2023-11-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/13267262/debug_2023-11-06.zip)

**Comment by whitindllc** [comment]
should that be --pass

**Comment by RainbowMiner** [comment]
Either -p or --pass are ok - but the problem was that the password was empty for Hashcryptos thus leading to a parameter error. That should be fixed now.
