### ISSUE TITLE
Issue with radeon rx 6600 mining spaceexpanse

### ISSUE THREAD

**Issue by Faty100** [RainbowMiner/RainbowMiner#2525]
Hello I am using rainbow miner to mine spaceexpanse and one of my video cards doesnt seem to work mining this coin. All my other video cards are fine. Its just the radeon rx 6600.

I believe the algo is Neoscryptxaya.

Unless its a setting I dont have correct?

**Comment by Faty100** [comment]
Like, nvidia 3060, 4070 and I have another radeon rx 5700 xt

**Comment by Faty100** [comment]
Is there a quick fix for this or maybe the rx 6600 is not supported?
Reason I am asking I am currently mining but I have 1 video card sittin lol

**Comment by RainbowMiner** [comment]
I am currently looking into it. Expect an answer within 24 hours.

**Comment by RainbowMiner** [comment]
Oh wait, are all cards plugged into one rig? Or are these separate rigs?

**Comment by Faty100** [comment]
All into one rig

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Faty100** [comment]
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RainbowMiner** [comment]
Ok, I have checked all miners, your's should be the SgminerFancyIX for the AMD GPUs. The parameters should all be correct, so I suspect some different problem like for example different OpenCL platforms. Could you please create a Debug file and upload it here? Just click "Debug file" on http://localhost:4000

**Comment by Faty100** [comment]
I got it to work. So sorry it looks like I had to log in directly localhost and benchmark again. I am using 1 machine as a server so i never remote into each machine individually. with the info you provided i figured it out. I must of missed when it failed but either way i benchmarked again and not its working.

Thanks man.

**Comment by RainbowMiner** [comment]
Nice! Thank you for your feedback.
On https://rbminer.net/monitoring I have added an action button "Re-run Failed Benchmarks". Click there  and all failed benchmarks will be retried for all connected rigs.

**Comment by Faty100** [comment]
Very cool thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
