### ISSUE TITLE
DeepMinerZSolo Error

### ISSUE THREAD

**Issue by ericb2233** [RainbowMiner/RainbowMiner#2528]
Getting this error message when attempting to mine DeepMinerZSolo (DeepMinerZ seems to be fine):

SetValueInvocationException: Exception setting "BLK": "The property 'BLK' cannot be found on this object. Verify that the property exists and can be set."

**Comment by RainbowMiner** [comment]
Which coin are you trying to mine solo with that module? It might be some division by zero problem.

**Comment by ericb2233** [comment]
DNX

**Comment by RainbowMiner** [comment]
Bug found and fixed. Thank you for the report!
