### ISSUE TITLE
nimiq - fixing it?

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2534]
any chance we will ever fix nimiq?? it actually pays out to usdc

**Comment by whitindllc** [comment]
icemining still is showing it to be active and the correct block
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/0cefaf43-6085-48ae-8a1e-894286db82a0)
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/9f71ca14-812b-43fc-9956-532410abe1f6)

**Comment by whitindllc** [comment]
this is maybe the problem?
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/5daf8cc0-dacd-4e09-ac7e-c2a3249f4f5d)

**Comment by RainbowMiner** [comment]
You seem to run on PowerShell 5 - maybe the SSL checking is too strict with this version. Please update to PowerShell Core 7.2.17 https://github.com/PowerShell/PowerShell/releases/download/v7.2.17/PowerShell-7.2.17-win-x64.msi (important: do not touch 7.3.x nor 7.4.x, both versions import a huge memory leak)

**Comment by whitindllc** [comment]
its not powershell 5... i just changed the colors of the dos prompt because its annoying to read from across the house 
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/77112aad-c4fa-4137-9e2c-5e2f437317e5)

**Comment by RainbowMiner** [comment]
Ah ok. Then the "ignore SSL check" function has a bug. I'll check this.

**Comment by whitindllc** [comment]
i dont think it does because you checked that awhile back

**Comment by whitindllc** [comment]
this is more in depth from a startup console log i was troubleshooting something on 

.. loading Icemining
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (The SSL connection could not be established, see inner exception.)" --> One or more errors occurred. (The SSL connection could not be established, see inner exception.)"
WARNING: Pool API (Icemining) returned nothing.
done (2.318s)

**Comment by RainbowMiner** [comment]
Fixed

**Comment by whitindllc** [comment]
it worked.... what did you do?

**Comment by RainbowMiner** [comment]
> it worked.... what did you do?

Since Icemining is using an invalid/expired SSL certificate on their API, I allowed these invalid/expired certs for Icemining.
