### ISSUE TITLE
Cant seem to get most pools to work specifically solopool all the zergpools work fine

### ISSUE THREAD

**Issue by Faty100** [RainbowMiner/RainbowMiner#2537]
I am trying to mine in solopool and I cant seem to get it to work?

Should it work automatically like zergpool does or are their some configurations I need to do?

for example in zergpoolcoinssolo I can mine spaceexpanse and just type in ROD in the symbol section and away it goes.

But for solopool nothing works if I leave it empty or if I type in a symbol. I am currently trying to mine alph.

Are there some configurations I need to do that I am not aware of or are you suppose to update stuff on your end to get them working again. Maybe they updated their url or api....

I am using my server with 3 computers connecting to the server. All the computers say no pools available.

Again all Zerg pools work fine with no configurations they just start working automatically and also MoneroOcean works fine as well with no configurations.

**Comment by RainbowMiner** [comment]
You are right - the current SoloPool module needs an update, the pool's API has changed. I'll do this asap.

**Comment by Faty100** [comment]
Thats amazing thank you. Let me know when its done so i can start using it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RainbowMiner** [comment]
Done. Please be aware, that you have to setup wallets for each coin you want to mine on SoloPool, because the pool isn't an autoexchange-pool like ZergPool.

Example:
```
  "SoloPool": {
    "ETC": "$ETC",
    "ETC-Params": "",
    "KAS": "$KAS",
    "KAS-Params": "",
    "RVN": "$RVN",
    "RVN-Params": "",
    "XMR": "$XMR",
    "XMR-Params": "",
...
},
```

- Setup the coins in coins.config.txt first, so that you can use the variables ( `$xxx`). Otherwise you have to input your wallet addresses directly.
- be aware, that the TTF might be long (>1mo, >1year) for many coins, so that Rainbowminer will automatically reduce the profit

**Comment by Faty100** [comment]
Sorry not sure what you mean by that last part? TTF?

So rainbow will reduce my profits. I dont get it?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Faty100** [comment]
Fyi... solopool works for me now. Thank you so much.

Before you close the ticket if you can just answer the question I asked that would be great.

: )

**Comment by RainbowMiner** [comment]
> Sorry not sure what you mean by that last part? TTF?
> So rainbow will reduce my profits. I dont get it?

TTF = time to find a block

Depending on your setting `MaxTimeToFind` in pools.config.txt (and config.txt for the defaults), RainbowMiner will calculate a lower profit, in case the TTF is greater than the `MaxTimeToFind`. With this measure, it avoids to mine to some coin that you will not be able to mine in time.
