### ISSUE TITLE
It does not show "power" on amd FX processors

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2538]
Hello. The AMD FX series I have does not show "power" on all processors. but it does mining. It's not a big deal. However, I would appreciate it if there is something that can be fixed. (but there is no problem with my other "ryzen and xeon" processors. This problem only exists in FX processors)

![resim_2023-11-22_211753984](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/49faff7e-02b3-45ba-aeb5-a46596788c0e)

**Comment by RainbowMiner** [comment]
Ok, it looks like I need to update the Hardware library.

**Comment by MTCHANNELL** [comment]
Do you have a chance to fix this problem in your new update?

**Comment by RainbowMiner** [comment]
I'll for sure will try.

**Comment by Robbylikes** [comment]
Same here but with older cards and R9 290s.

**Comment by MTCHANNELL** [comment]
I installed the new version from scratch and waited for it to benchmark. but still "power:0"

**Comment by RainbowMiner** [comment]
Would you please be so kind and create and upload a Debug file? Just click "Debug file" on http://localhost:4000

**Comment by MTCHANNELL** [comment]
[debug_2023-11-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/13468360/debug_2023-11-27.zip)

**Comment by RainbowMiner** [comment]
Ok, perfect. That helped!

**Comment by MTCHANNELL** [comment]
Yes, sir. I expect good news from you.

**Comment by MTCHANNELL** [comment]
Installed from scratch. benchmark was made. tested again. but "power:0" didn't work. Also "cpu-load:0" gets stuck at zero.
![Adsız](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/915dd0ac-929c-4930-a7de-132acd2dfc7a)
[debug_2023-11-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/13476965/debug_2023-11-27.zip)

**Comment by RainbowMiner** [comment]
You do not need to install from scatch. Just:
1) stop RainbowMiner
2) download the most actual [master.zip](https://github.com/RainbowMiner/RainbowMiner/archive/refs/heads/master.zip)
3) extract into RainbowMiner folder, make sure to allow overwrite
4) start RainbowMiner

**Comment by RainbowMiner** [comment]
What is going on with these FX CPUs :)
I have added some more info to CPUtest.bat - please do the following:
- follow the above steps to update RainbowMiner
- after that, run "CPUtest.bat" in RainbowMiner folder with elevated rights (right-click -> run as Admin)
- upload the new file "cputestresult.txt" from RainbowMiner folder

**Comment by MTCHANNELL** [comment]
The problem is fixed. Thank you very much.

**Comment by MTCHANNELL** [comment]
[cputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/13479651/cputestresult.txt)

**Comment by RainbowMiner** [comment]
Ah sorry, you need to update RainbowMiner with the actual master.zip before hitting the CPUtest.bat as Admin. Your instance is missing the last update from today. I have added more information to the cputestresult.txt with the last commit.

**Comment by MTCHANNELL** [comment]
[cputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/13481513/cputestresult.txt)
I downloaded the "Master.zip" file again. I just ran "cputest.bat" as administrator. I uploaded the results sir.

**Comment by MTCHANNELL** [comment]
I just downloaded the latest "master.zip" update. I'm waiting for the benchmark to finish. It was as if it had happened. But when it's done, I will give a clear answer.

**Comment by MTCHANNELL** [comment]
![Adsız](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/9ecf9b51-9ce7-402c-b5c7-38ceca8c4331)
I just barely found the time to check it out. This time it defined everything as 125watts. Could this be true? because there is no fixed number in other CPUs.

**Comment by RainbowMiner** [comment]
Yes, that is very well possible. If mining, you really load the CPU up to max.

**Comment by MTCHANNELL** [comment]
![1220v2](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/97136cf8-babf-4ee4-9e4a-3e77145fae2f)
![2670v3](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/caceeb73-985b-4d69-96d7-9abdd652c0fd)
![FX8350](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/c934ee0b-e6b8-4b2f-a360-a625f28a8ff2)
When comparing 1220v2 and 2670v3 the power ratings are always different. Each algo has different wattage values. Of course, they are all actively mining. However, fx8350 gives a constant value of 125watts. If it showed the same constant wattage on other processors, I would say it was normal, but FX8350 works a little weird. It seemed a little strange to me that it showed a constant 125 watts.
