### ISSUE TITLE
MinerRocks API Error 

### ISSUE THREAD

**Issue by ericb2233** [RainbowMiner/RainbowMiner#2545]
Getting the following errors when mining via MinerRocks:

WARNING: Pool API (MinerRocks) for AEON has failed.
WARNING: Pool API (MinerRocks) for QWC has failed.
WARNING: Pool API (MinerRocks) for TUBE has failed.
WARNING: Pool API (MinerRocks) for MSR has failed.
WARNING: Pool API (MinerRocks) for SUMO has failed.

**Comment by RainbowMiner** [comment]
Looks like it needs an update.
