### ISSUE TITLE
2 errors I see in webgui / +2 bonus requests

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2546]
1-) The web gui console page should be kept wide. Since the texts and numbers do not fit, they move to the bottom line and become a little difficult to read.
example;
![01](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/5c3eaa15-c85f-47f7-be41-9c8996a3a298)

2-) Miner versions appear incorrectly in webgui console. No errors except srbminer. I am using srbminer 2.4.1. but it sees 2.3.9 . Just a textual error. miner is working properly.
example;
![02](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/c329332c-5aa0-4908-b4e5-bfb8055d63de)
- - - - - - -
- bonus -
- - - - - - - 
3-) code to start as administrator; (This code should be added to all ".bat". my personal opinion.)
:: BatchGotAdmin (Run as Admin code starts)
REM --> Check for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
echo Requesting administrative privileges...
goto UACPrompt
) else ( goto gotAdmin )
:UACPrompt
echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
echo UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
"%temp%\getadmin.vbs"
exit /B
:gotAdmin
if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
pushd "%CD%"
CD /D "%~dp0"
:: BatchGotAdmin (Run as Admin code ends)
:: Your codes should start from the following line

4-) Since "setup.bat", that is, all the vowels used in the initial installation phase, are invalid, the code I mentioned below must be added to the "setup.bat" file. In this case, for example; accepts vowels when adding our wallet address. I spent a long time until I figured this out. It can be set manually in the "coins.config.txt" file, but it would be better to do this during the initial installation.
code;
chcp 65001

I think the admin rights and chcp code I mentioned should be added to all ".bat" files. This is my personal opinion. This is how I organize and use it.

**Comment by RainbowMiner** [comment]
Super, thank you for your information and code!
