### ISSUE TITLE
Mining4People Errors

### ISSUE THREAD

**Issue by ericb2233** [RainbowMiner/RainbowMiner#2551]
Getting these errors when attempting to mine via Mining4People:

InvalidArgument: C:\Users\ericb\Downloads\RainbowMiner\Pools\Mining4people.ps1:84
Line |
  84 |          $Pool_TSL      = ((Get-Date) - ([datetime]$Pool_CoinRequest.l …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert null to type "System.DateTime".

RuntimeException: C:\Users\ericb\Downloads\RainbowMiner\Pools\Mining4people.ps1:89
Line |
  89 |  … .hashrate -gt 0) {$btcPrice * $reward * $Pool_BLK / $hashrate} else { …
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

this object. Verify that the property exists and can be set."

SetValueInvocationException: Exception setting "BLK": "The property 'BLK' cannot be found on this object. Verify that the property exists and can be set."

SetValueInvocationException: Exception setting "BLK": "The property 'BLK' cannot be found on this object. Verify that the property exists and can be set."

SetValueInvocationException: Exception setting "BLK": "The property 'BLK' cannot be found on this object. Verify that the property exists and can be set."

SetValueInvocationException: Exception setting "BLK": "The property 'BLK' cannot be found on this object. Verify that the property exists and can be set."

SetValueInvocationException: Exception setting "BLK": "The property 'BLK' cannot be found on this object. Verify that the property exists and can be set."

**Comment by gordoisgone** [comment]
Getting the samer error.
