### ISSUE TITLE
Recommendation for miners to automatically download the latest version

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2553]
Hello. If I understand correctly, you are constantly releasing updates to update the miners. While searching the internet I found a code to download the latest miners published in github repositories. If you can integrate this code into your system, I think you will not need to constantly update it. Don't get me wrong, my goal is to reduce your workload even a little bit. I do not have a bad purpose.

sample codes;
cpuminer-opt-jayDDee.bat
set repo=owner/name
  for /f "tokens=1,* delims=:" %%A in ('curl -ks https://api.github.com/repos/JayDDee/cpuminer-opt/releases/latest ^| find "windows.zip"') do ( curl -kOL %%B )
pause

cpuminer-opt-rplant.bat
set repo=owner/name
  for /f "tokens=1,* delims=:" %%A in ('curl -ks https://api.github.com/repos/rplant8/cpuminer-opt-rplant/releases/latest ^| find "win.zip"') do ( curl -kOL %%B )
pause

srbminer.bat
set repo=owner/name
  for /f "tokens=1,* delims=:" %%A in ('curl -ks https://api.github.com/repos/doktor83/SRBMiner-Multi/releases/latest ^| find "-win64.zip"') do ( curl -kOL %%B )
pause

teamredminer.bat
set repo=owner/name
  for /f "tokens=1,* delims=:" %%A in ('curl -ks https://api.github.com/repos/todxx/teamredminer/releases/latest ^| find "win.zip"') do ( curl -kOL %%B )
pause

wildrig.bat
set repo=owner/name
  for /f "tokens=1,* delims=:" %%A in ('curl -ks https://api.github.com/repos/andru-kun/wildrig-multi/releases/latest ^| find "wildrig-multi-windows"') do ( curl -kOL %%B )
pause

By the way, I completely translated "Rainbowminer" into Turkish. There are a few places where I made mistakes. I couldn't find time to sit in front of the computer because I had hospital work. Before presenting it to you, I will first test it from scratch and see if there are any problems, and then I will share the completely finished version with you. If you find it appropriate, you can share it on your page.
Your interest is great. Thank you to the whole team.

**Comment by RainbowMiner** [comment]
Thank you :) 
The miner updates are a bit difficult regarding automization, because we maintain a hand-curated "what has been updated" database. This database avoids unnecassary benchmarks. Most of the time, only one or two algorithms get an upgrade by the miner's developers.
But we could include automatic miner module updates, so that you don't have to wait for a new RainbowMiner release.
