### ISSUE TITLE
mrr Dogecoin Pricing don't enabled!

### ISSUE THREAD

**Issue by ciumete** [RainbowMiner/RainbowMiner#2557]
On MRR rigs only Dogecoin Pricing don't enabled!

mrr.config.txt
"PriceCurrencies": "BTC,ETH,LTC,BCH,DOGE",

pools.config.txt
"PriceCurrencies": "BTC,ETH,LTC,BCH,DOGE",

**Comment by RainbowMiner** [comment]
I will take care of it. Thank you for reporting this!

**Comment by RainbowMiner** [comment]
Fixed.
