### ISSUE TITLE
Linux - Nvidia 1080 - p0 state

### ISSUE THREAD

**Issue by plittlefield** [RainbowMiner/RainbowMiner#2559]
Does RM in LINUX set the correct p state for nvidia 1080 by default?

If not, does the Nvidia Profile Inspector run in Linux?

Thanks!

**Comment by RainbowMiner** [comment]
> Does RM in LINUX set the correct p state for nvidia 1080 by default?
> 
> If not, does the Nvidia Profile Inspector run in Linux?
> 
> Thanks!

There is no way to set the P-State on Linux, so I have programmed "forcePstate", that tool loop-accesses all Nvidia GPUs in a manner, that it doesn't consume any resources but keeps the GPUs in the correct P state. When starting RainbowMiner, it should run in the background all the time.

**Comment by plittlefield** [comment]
Great :)  and no, I haven't touched any other settings - fans are at about 50% and all seems good.

Thanks very much for writing the software, keep up the good work and have a Happy Christmas :christmas_tree:
