### ISSUE TITLE
add parameter minimum hash rate or miners for any algo

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#256]
can you add minimum hash or miners para to algorithms.config.txt?
some high diff algos need should be mined only when there is enough hashrate
algos like phi2,bitcore,bcd,x16r

**Comment by RainbowMiner** [comment]
Of course. Good idea, I will do that.

**Comment by RainbowMiner** [comment]
The new parameters are "MinHashrate" (in H/s) and "MinWorkers" - upon restart, these two will be added to algorithms.config.txt automatically. The values are positive integers or 0. 
Values can be changed, using the [C]onfiguration -> A[L]gorithms or directy, via editing the Config\algorithms.config.txt

**Comment by rinkal26783** [comment]
If i want to add "MinHashrate" 50 GH 
What value i should enter?

**Comment by RainbowMiner** [comment]
Add 50000000000 (it is a 5 with 9+1 = 10 zeros)

|Hashrate|Number|Zeros to add|
|:---:|:---:|:---:|
|1 kH|1000|3|
|1 MH|1000000|6|
|1 GH|1000000000|9|
|1 TH|1000000000000|12|

Ok, I see :D It is better, we support units.

**Comment by RainbowMiner** [comment]
OH! I just realized, that large numbers will fail for MinHashrate in v3.8.10.3. **Please update to v3.8.10.4**
From this release on, you may use units. E.g. enter "50GH" or "12.5 MH" and it will be interpreted correctly.

**Comment by rinkal26783** [comment]
"50GH" or "12.5 MH" is there space between numbers and GH?

**Comment by RainbowMiner** [comment]
> "50GH" or "12.5 MH" is there space between numbers and GH?

It doesn't matter :) I designed the converter very relaxed.

**Comment by hernandn01** [comment]
Please review, it does not appear to be working for me.

Current hash is 328622035, tried 428622035 and 500 MH, changed that on the fly and also restarted but it does not stop mining on x22i

"X22i": {
    "Penalty": 0,
    "MinHashrate": "428622035",
    "MinWorkers": 0
  },

![image](https://user-images.githubusercontent.com/41829368/47594735-ec8fa400-d939-11e8-9748-e7f3ac6e5426.png)

**Comment by RainbowMiner** [comment]
Thanks for pointing towards this. I will have a look.

**Comment by hernandn01** [comment]
applied fix from core.psm1, please check for multiple miners, (used "500 MH") exit and start again. worked on one but no the other combo

![image](https://user-images.githubusercontent.com/41829368/47596745-a5a7ab80-d945-11e8-9df9-fc3004b51fed.png)

**Comment by hernandn01** [comment]
on second thought I think we are ok. I saw that the hashrate has gone up to 600, so I changed it to 650 MH and it took me right out both combos. Thanks for looking

**Comment by RainbowMiner** [comment]
Yes, it looks like Blockmasters X22i hashrate rises quickly. Anyway, I am using 10GH hashrate limit for X22i already.
