### ISSUE TITLE
KLS support

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2562]
Any chance for KLS support? it looks like a kheavyhash fork of kaspa....3 miners already support it.... gminer and lolminer have some kind of support... 2miners, herominers and woolypooly all have active pools

**Comment by RainbowMiner** [comment]
KLS is already supported. Just use Herominers pool, for example.

**Comment by whitindllc** [comment]
Yes i see it working with herominers... thank you
