### ISSUE TITLE
"mining-dutch" mines ghostrider algorithm on wrong port

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2569]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/dc62bd1e-afc0-4160-b86b-80e15fc78a90)

"mining-dutch" mines ghostrider algorithm on wrong port

**Comment by RainbowMiner** [comment]
I see - it should be 9997 instead of 9991. Their API delivers us the wrong value. I'll add a temporary quick fix.
