### ISSUE TITLE
Power limit in OC profile vs power adjust in devices.config

### ISSUE THREAD

**Issue by RetroShag** [RainbowMiner/RainbowMiner#257]
Might be a stupid question. what is the difference between power limit value in OC profiles and power adjustment in devices.config.  I run my cards at 80% power limit and limits the power draw to 80%.  Am I missing something?

**Comment by RainbowMiner** [comment]
There is no such thing like a stupid question :) The new power adjustment factor is used to correct TDP/power consumption calculations, only. It has nothing to do with overclocking.
It is of use with AMD gpus, since those do not have power measurement circuitry on-board.
