### ISSUE TITLE
issue: When i do the benchmark it constantly freezes.

### ISSUE THREAD

**Issue by neve360** [RainbowMiner/RainbowMiner#2570]
I set up 2 hours ago RainbowMiner but its constantly freezing when benckmarking so i try to hardly shutdown and after reboot the pc a lot of times but same result. from console RainbowMiner kinda knew about the crash but he try again (failing) can someone help me fix this problem there are some photos about my last frames of pc ![image](https://github.com/RainbowMiner/RainbowMiner/assets/46618433/c5f0950b-4d28-40ca-a69b-bbc534385e8d)

![image](https://github.com/RainbowMiner/RainbowMiner/assets/46618433/e5776e07-49e1-41c0-a8e0-4995d06cc89d)

**Comment by RainbowMiner** [comment]
Please try to adjust CPUMiningThreads and CPUMiningCores. The Srbminer most probably eats up all resources, so that there is no CPU processing power left for Rainbowminer.
Look here: https://github.com/RainbowMiner/RainbowMiner/issues/1109

**Comment by whitindllc** [comment]
honestly if i were you i would go into the config.txt and where it says devicename it probably says, cpu,gpu or cpu,nvidia

I would remove the CPU and the , and just leave nvidia in there.... run your bench marks.... the 1650 is probably only going to make 5 or 6 cents a day.... 

i would then open the config again and remove nvidia and change it to cpu and let it pick up the config and start benching the CPU... the cpu will probably make more... 

The developer is probably right... you might need to move the cputhreads to 2

**Comment by neve360** [comment]
what i should put affinity for quadcore processor

**Comment by RainbowMiner** [comment]
Is it AMD or Intel?

**Comment by RainbowMiner** [comment]
If it is QuadCore / Dual Threads I would guess
```
"EnableAutoAdjustAffinity": "0",
"CPUMiningThreads": 6,
"CPUMiningAffinity": "0xF5",
```
will do the job.

**Comment by neve360** [comment]
hi i have an amd processor now i try this settings thank you so much, btw on discord fix the auth bot its says some error when he typed in dms ![image](https://github.com/RainbowMiner/RainbowMiner/assets/46618433/4a094706-81c0-4257-bf80-c9c8c1af9fae)

**Comment by neve360** [comment]
> If it is QuadCore / Dual Threads I would guess
> 
> ```
> "EnableAutoAdjustAffinity": "0",
> "CPUMiningThreads": 6,
> "CPUMiningAffinity": "0xF5",
> ```
> 
> will do the job.

is single threads it still freezing all

**Comment by RainbowMiner** [comment]
Ok, if it is single thread, leave on thread for RainbowMiner:
```
"EnableAutoAdjustAffinity": "0",
"CPUMiningThreads": 3,
"CPUMiningAffinity": "0xE",
```
