### ISSUE TITLE
question regarding wallets that have 2 sets of numbers

### ISSUE THREAD

**Issue by Faty100** [RainbowMiner/RainbowMiner#2572]
Hello I dont see a seciton for adding a second wallet code in the setup coins section for the website gui.

For example DNX has a payment ID. Where should I put this?

**Comment by RainbowMiner** [comment]
The Payment ID belongs to the wallet, therefor it should be appended to the wallet using a `+`
Like `abcdef0123456789abcdef0123456789+fedcba9876543210`

**Comment by Faty100** [comment]
ok this is good to know thank you.
