### ISSUE TITLE
issue with rplant

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2573]
im not sure if its just me only but rplant disappeared....i cant mine to it at all... i thought it might have something to do with the WTM api i experienced late last night but i dont think it does that was resolved.. i set it to just mine by itself and here are the logs... 

[debug_2023-12-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/13668574/debug_2023-12-13.zip)

**Comment by RainbowMiner** [comment]
Yes, you are right. Rplant has changed it's API. I will push a fix asap.

**Comment by whitindllc** [comment]
weird... wtm and rplant... back to back...

**Comment by RainbowMiner** [comment]
Ok, so my last commit fad3738788d443f947969f30cc7fdf73a665612a fixes RPlant.

**Comment by whitindllc** [comment]
testing now

**Comment by whitindllc** [comment]
same result 
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/705ec63f-f9ca-4e5a-9c2b-c569d0006af2)

**Comment by whitindllc** [comment]
i still dont see rplant anywhere in my list of profitable mining pools

**Comment by whitindllc** [comment]
testing now after new release

**Comment by whitindllc** [comment]
new release fixed it
