### ISSUE TITLE
PYI mining

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2576]
is there a miner for it we use yet? i was playing with it a bit but its very much in its infancy

**Comment by slappy6212** [comment]
+1 Lolminer is supporting it. Herominers and K1pool supporting it.

lolMiner.exe --algo PYRIN --pool ca.pyrin.herominers.com:1177 --user YOUR_PYRIN_WALLET_ADDRESS.YOUR_WORKER_NAME
pause

**Comment by whitindllc** [comment]
looks like smash added it... now its time to find a wallet

**Comment by slappy6212** [comment]
TradeOgre.

**Comment by whitindllc** [comment]
i hate mining to exchange wallets.... at the same time the only thing i hate more is having to compile a wallet

**Comment by whitindllc** [comment]
can you add kryptex and baikelmine for this please?

**Comment by RainbowMiner** [comment]
PYI on Kryptex should already be available. Just add PYI to your coins.config.txt and `"PYI": "$PYI"` in pools.config.txt and off you go

**Comment by RainbowMiner** [comment]
PYI is now available on BaikalMine too.

**Comment by whitindllc** [comment]
can you add kryptex and baikelmine for this please?
