### ISSUE TITLE
Hashcryptos. Wrong profitability.

### ISSUE THREAD

**Issue by YastrebX** [RainbowMiner/RainbowMiner#2578]
Hello. It's looks like profitability on hashcryptos pool is wrong. For rainbow miner it 1000 times more than real profit. Because of that profit switching does not work.

**Comment by YastrebX** [comment]
For example, ryzen 9 3900 profit shown in rainbow miner 1300$, really on pool around 1.3$

**Comment by RainbowMiner** [comment]
Yes, they updated their API and removed a calculation bug (which we did account for in our module). The following commit should solve the problem: 51cc78269b899103eb96b462b82f7b20dcd58e83

**Comment by UselessGuru** [comment]
<img width="358" alt="image" src="https://github.com/RainbowMiner/RainbowMiner/assets/30080938/342eb62f-527e-4207-8500-cd23ad728f6d">

**Comment by MTCHANNELL** [comment]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/1cac216b-3e3f-4fbc-a524-306506fdcaf2)
Monero cannot benchmark. There is a problem with pricing
