### ISSUE TITLE
Trex 0.7.2 Release x22i support

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#258]

**Comment by hernandn01** [comment]
T-Rex 0.7.2

Added algos: x22i
Note: if the miner crashes on x22i, decrease your overclock, the algorithm is quite "unstable"


Linux
CUDA 9.1:
https://mega.nz/#!PNUQ1KLB!xusnqHpNa5L2QmX5UN_deBF5HhRarPZypSy6iBW_oDQ

CUDA 9.2:
https://mega.nz/#!LAE2RSqQ!pnBWXW8keay3MGn85v7hUk8TuLvJZCekl_FTePoPlbo

CUDA 10.0:
https://mega.nz/#!PdUQTIyK!0EX4nel2zwVHSL8L4OaILK2Azn8pmj96x71nlkfcI7s


Windows (x64)
CUDA 9.1:
https://mega.nz/#!aBUB1azQ!hqsBylvgFtjhPHAFGsIL53RYF2SN2_eCJUKBuPDI3Jc

CUDA 9.2:
https://mega.nz/#!jAMEwA5B!CLYkWFv6R7D93nSaJw2a4q3oreH10ARUxKr6G6K6aks

CUDA 10.0:
https://mega.nz/#!qB0SkQzY!jHmWBZYe5KWr1Jz4Ose_2rTg__Sfsws8KAldr09lAMo

**Comment by RainbowMiner** [comment]
added. x22i mining is +40% compared to Zjazz 🐎
