### ISSUE TITLE
1 miner crashed (wildrig)

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2582]
warning : 1 miner crashed. The loop restarts as soon as possible
Today this has just begun. It only does it in the "wildrig" miner program. It crashes constantly.
There is no problem with the graphics card or wildrig. because if I run it manually outside "rainbowminer" there is no problem. The problem only occurs in rainbowminer.

manuel miner screen shot
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/0906b7d5-9c95-4428-a888-8aad07ae911a)

**Comment by whitindllc** [comment]
its the switch dude... i had this problem before... it crashes because it cant shutdown fast enough before opening the next miner
there is something you can change in the config for a wait parameter until opening the next miner... i had to do it...

are you using any kind of overclocks?

**Comment by MTCHANNELL** [comment]
I don't use any overclocking. But there was no such problem until yesterday. It suddenly happened like this. I only select "gpu" from "rainbowminer" settings. I use "take2" as an algorithm. for testing purposes. Wildrig gives an error as soon as it is opened.only "wildrig" does it in miner. There is no problem with other miner program.

**Comment by whitindllc** [comment]
what version of the manually run wildrig?

**Comment by whitindllc** [comment]
what pool is rbm running against vs what you are doing manually?

**Comment by MTCHANNELL** [comment]
what version of the manually run wildrig?
latest version

what pool is rbm running against vs what you are doing manually?
zpool

**Comment by MTCHANNELL** [comment]
I solved the issue. I stopped using amd radeon software. I was making all my settings with "msi after burner". I edited config.txt and set the msi setting to 1 and it worked
