### ISSUE TITLE
way to delete old miners...

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2584]
is there is a way to delete these without having to do it manually ? i just did this recently and its already up to 3GB again

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/510d3284-b1d3-4adf-a6fe-7f58f34742a8)

**Comment by MTCHANNELL** [comment]
config.txt edit;
MaxLogfileDays = max. days to keep logfiles in Logs folder [default=5]
MaxDownloadfileDays = max. days to keep downloaded files in Downloads folder [default=14]
MaxCachefileDays = max. days to keep cache files in Cache folder [default=14]
EnableMinerBackups = keep backups of updated miners in Bin folder, set to 0, if you have limited space [default=1]
EnableKeepDownloads = keep downloaded miners in Downloads folder, set to 0, if you have limited space [default=1]

**Comment by whitindllc** [comment]
i shall test this and push it out

**Comment by RainbowMiner** [comment]
Those backup folders are limited to a number of 3, so it cleans up after itself automatically,

**Comment by whitindllc** [comment]
it worked setting a few to 1
