### ISSUE TITLE
hashcryptos problem?

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2585]
Hello. I think we are having some issues with the "hashcryptos" pool caused by "Rainbowminer".
1-) Randomx always gives zero prices even though we make comparisons. Can it be fixed?
2-) While benchmarking on the Randomx algorithm, it tries to mine on the GPU with xmrig, but apparently it cannot. This is a technical problem. It shouldn't. I have to check manually. It would be nice if it could be fixed. Because sometimes I leave the job to the criteria and leave the house, and when I come back, it tries to do it again and gets stuck.
3-) the most important problem. While searching the hashcryptos pool it suddenly gives an API issue. Even though I restarted "Rainbowminer" many times, it gives the "no pool" error. I install from scratch and still get the same error. I can't figure out if the problem is with the pool or the "rainbow miner". For now I'm mining this pool with a manual bat file.

**Comment by UselessGuru** [comment]
> While searching the hashcryptos pool it suddenly gives an API issue. 
Do you have more than one RainbowMiner instance running in you network?
HashCryptos only allows 1 API request from the same IP adress every 10 seconds.

**Comment by MTCHANNELL** [comment]
3 different hardware is running on the same ip. While 2 of them are working normally, 1 of them shows "no pool" at any time during the day. but the other 2 are working normally. I'm currently mining with a normal manual bat file. There is nothing wrong. It only happens when mining with "rainbowminer".

**Comment by RainbowMiner** [comment]
If you have multiple instances of RainbowMiner running, the 10 seconds limit of hashcryptos will cause trouble. First solution would be to use a client/server setup. Then the server will manage the 10 seconds limit. Second solution, I can move the hashcryptos API to the rbminer.net API. There is no 10 seconds limit on my server. I'll look into it.

**Comment by MTCHANNELL** [comment]
It would be great if you can solve this problem. I keep my low gear in that pool. For now I am not using "rainbowminer" in the "hashcyrptos" pool. However, I use "rainbowminer" in the "zpool" pool for my other high capacity hardware and I am very satisfied. I'm waiting for your review. Happy new year in advance.

**Comment by RainbowMiner** [comment]
Already done :) I have moved the Hashcrypto API to rbminer.net with the above commit (155ea6d9a289b071cca826d7be957930daa740fd)

**Comment by MTCHANNELL** [comment]
I'm sorry I didn't see it. ok thank you.
