### ISSUE TITLE
Warning: Could not set process priority/affinity

### ISSUE THREAD

**Issue by NasoLiteratus** [RainbowMiner/RainbowMiner#2588]
Hi, I keep getting this error and my miner keeps crashing, any ideas?
![error](https://github.com/RainbowMiner/RainbowMiner/assets/50769264/978fcf89-369d-411a-a71f-2cf3ebb6d035)

**Comment by NasoLiteratus** [comment]
Also, sometimes RBM crashes, but the the mining window keeps mining.

**Comment by NasoLiteratus** [comment]
I have disabled Rigel and Miniz miners and no longer have this error or miner crash.
It has been mining for 24 hour without issue.
Would like to resolve this issue so I can use Rigel again.

**Comment by RainbowMiner** [comment]
Check your overclocking settings. Maybe it's too harsh for Rigel to dual mine.

**Comment by RainbowMiner** [comment]
Oh! I have just noted, that the workername is "New 40 Series" - since it contains spaces it will cause trouble. Please set the workername, so that it contains letters and numbers, only.

**Comment by NasoLiteratus** [comment]
Cheers Mate, well spotted, spaces removed, and mining as it should.
Case Closed.
Regards
Lee
