### ISSUE TITLE
It could be very important!

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2589]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/72cef1b2-7dd2-4b82-a87c-9e7496b1228b)

Just now, while I was checking my workers in the "zpool" pool, I suddenly noticed that they all disappeared.
Suddenly the account turned into "btc" payment.
When I immediately checked the console from the webgui, I noticed that she was mining to a different wallet account.
There are no viruses etc. in my system.
I checked all my "rainbowminer" settings, but I couldn't find anything with my wallet address other than just "raven". I shut it down completely and even unplugged it :) and restarted it. Everything is working normally now. I don't know why something like this happened.
I even put only the "zpool" pool files in the "balances" and "pools" folders. so that it does not switch to a different pool.I'm a bit of a guarantee person. :)
This is the first time I encounter something like this. all "config etc." I edited the files and looked inside them. But I could not reach the wallet address in the picture.

**Comment by RainbowMiner** [comment]
This happens, when RainbowMiner switches to the daily donation round. It is my donation wallet.
