### ISSUE TITLE
CryptoNight Claymore CPU Port error

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#259]
CryptoNight Claymore CPU Port error.   Sorry for the number of lig files.

![screenshot_20181027-073001_teamviewer](https://user-images.githubusercontent.com/801414/47605372-5b144680-d9ba-11e8-89d8-1288caefe209.jpg)
![screenshot_20181027-072820_teamviewer](https://user-images.githubusercontent.com/801414/47605374-60719100-d9ba-11e8-930a-e659cc3f45f1.jpg)
[Activity_2018-10-24.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521843/Activity_2018-10-24.txt)
[Activity_2018-10-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521844/Activity_2018-10-23.txt)
[errors_2018-10-27.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521845/errors_2018-10-27.asyncloader.txt)
[errors_2018-10-26.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521846/errors_2018-10-26.asyncloader.txt)
[errors_2018-10-25.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521847/errors_2018-10-25.asyncloader.txt)
[errors_2018-10-24.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521848/errors_2018-10-24.asyncloader.txt)
[errors_2018-10-23.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521849/errors_2018-10-23.asyncloader.txt)
[Activity_2018-10-27.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521850/Activity_2018-10-27.txt)
[Activity_2018-10-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521851/Activity_2018-10-26.txt)
[Activity_2018-10-25.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521852/Activity_2018-10-25.txt)
[RainbowMiner_2018-10-22_21-20-38.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521853/RainbowMiner_2018-10-22_21-20-38.txt)
[RainbowMiner_2018-10-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521854/RainbowMiner_2018-10-23.txt)
[RainbowMiner_2018-10-23_07-45-35.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521855/RainbowMiner_2018-10-23_07-45-35.txt)
[RainbowMiner_2018-10-23_15-44-17.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521856/RainbowMiner_2018-10-23_15-44-17.txt)
[RainbowMiner_2018-10-23_12-44-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521857/RainbowMiner_2018-10-23_12-44-23.txt)
[RainbowMiner_2018-10-23_22-42-31.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521858/RainbowMiner_2018-10-23_22-42-31.txt)
[RainbowMiner_2018-10-23_22-36-06.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521859/RainbowMiner_2018-10-23_22-36-06.txt)
[RainbowMiner_2018-10-23_22-30-02.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521860/RainbowMiner_2018-10-23_22-30-02.txt)
[RainbowMiner_2018-10-23_16-11-47.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521861/RainbowMiner_2018-10-23_16-11-47.txt)
[RainbowMiner_2018-10-23_22-45-56.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521862/RainbowMiner_2018-10-23_22-45-56.txt)
[RainbowMiner_2018-10-23_22-48-25.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521863/RainbowMiner_2018-10-23_22-48-25.txt)
[RainbowMiner_2018-10-24_06-20-36.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521864/RainbowMiner_2018-10-24_06-20-36.txt)
[RainbowMiner_2018-10-24_06-18-22.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521865/RainbowMiner_2018-10-24_06-18-22.txt)
[RainbowMiner_2018-10-24.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521866/RainbowMiner_2018-10-24.txt)
[RainbowMiner_2018-10-24_06-23-11.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521867/RainbowMiner_2018-10-24_06-23-11.txt)
[RainbowMiner_2018-10-24_20-37-31.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521868/RainbowMiner_2018-10-24_20-37-31.txt)
[RainbowMiner_2018-10-24_18-50-33.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521869/RainbowMiner_2018-10-24_18-50-33.txt)
[RainbowMiner_2018-10-24_18-47-06.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521870/RainbowMiner_2018-10-24_18-47-06.txt)
[RainbowMiner_2018-10-24_18-37-13.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521871/RainbowMiner_2018-10-24_18-37-13.txt)
[RainbowMiner_2018-10-24_18-36-11.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521872/RainbowMiner_2018-10-24_18-36-11.txt)
[RainbowMiner_2018-10-24_16-05-19.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521873/RainbowMiner_2018-10-24_16-05-19.txt)
[RainbowMiner_2018-10-24_20-39-53.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521874/RainbowMiner_2018-10-24_20-39-53.txt)
[RainbowMiner_2018-10-24_21-39-37.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521875/RainbowMiner_2018-10-24_21-39-37.txt)
[RainbowMiner_2018-10-25.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521876/RainbowMiner_2018-10-25.txt)
[RainbowMiner_2018-10-25_14-33-43.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521877/RainbowMiner_2018-10-25_14-33-43.txt)
[RainbowMiner_2018-10-25_13-16-19.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521878/RainbowMiner_2018-10-25_13-16-19.txt)
[RainbowMiner_2018-10-25_15-51-18.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521879/RainbowMiner_2018-10-25_15-51-18.txt)
[RainbowMiner_2018-10-26_05-30-04.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521880/RainbowMiner_2018-10-26_05-30-04.txt)
[RainbowMiner_2018-10-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521881/RainbowMiner_2018-10-26.txt)
[RainbowMiner_2018-10-26_06-17-11.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521882/RainbowMiner_2018-10-26_06-17-11.txt)
[RainbowMiner_2018-10-26_11-11-04.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521883/RainbowMiner_2018-10-26_11-11-04.txt)
[RainbowMiner_2018-10-26_17-49-35.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521884/RainbowMiner_2018-10-26_17-49-35.txt)
[RainbowMiner_2018-10-26_15-31-30.txt](https://github.com/RainbowMiner/RainbowMiner/files/2521885/RainbowMiner_2018-10-26_15-31-30.txt)

**Comment by RainbowMiner** [comment]
Very weird! It should communicate over port 52002 and not 10048. Is this miner faster than the XmrigCPU (0%fee)?

**Comment by paulpoco** [comment]
I don't know if one is faster than the other.

**Comment by RainbowMiner** [comment]
Ok, I will try them out on different CPU. Anyway, there is an experimental feature build into the  RainbowMiner to detect used ports. I will drop you a substitute Miner to test, if using another port helps, or if it is a basic problem with this Miner on your Cpu. Which CPU are you using?

**Comment by paulpoco** [comment]
Don't see this anymore or the Miner just dropped off
