### ISSUE TITLE
OC based on Algo, not on miner

### ISSUE THREAD

**Issue by derhier** [RainbowMiner/RainbowMiner#2594]
as the title said.

As far as i understand OC is made on per miner basis. Would be smart to set it based on algorithm, so its easier to set up and more controllable.

Also Hive API would be very nice to integrate. Then you would be able to outsource the OC, etc to hive and just use Rainbow as a control server.

**Comment by slappy6212** [comment]
You can do it via algorithms.congig.txt. both way supported MSI afterburner or direct profile. You must setup ocprofiles.config.txt before. :-)
EX:

**ocprofiles.config.txt**

"Profile7-VII": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "PriorizeThermalLimit": 0,
    "MemoryClockBoost": "1150",
    "CoreClockBoost": "1750",
    "LockVoltagePoint": "980",
    "PreCmd": "",
    "PreCmdArguments": "",
    "PostCmd": "",
    "PostCmdArguments": "",
    "LockMemoryClock": "*",
    "LockCoreClock": "*"
  }

**algorithms.congig.txt**

"KawPOW": {
    "Penalty": "0",
    "MinHashrate": "0",
    "MinHashrateSolo": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "MSIAprofile": "",
    "OCprofile": "Profile7",
    "MinerName": "",
    "ExcludeMinerName": ""
  },

**Comment by derhier** [comment]
ok. Seems like the discord was wrong then. 

What about scalability with hive? i dont see us flashing rigs with windows. And as far as i can tell OC on linux is not working great with rainbow
