### ISSUE TITLE
Ubuntu: Incorrect path form exported to LD_LIBRARY_PATH ?

### ISSUE THREAD

**Issue by timvis** [RainbowMiner/RainbowMiner#2596]
Some miners fail in the benchmark. For example Rplant. If manually launched it stops with a segfault immediately.

Looking into the start script I found that the non-working path '**./:**/opt/rainbowminer/lib' is exported as LD_LIBRARY_PATH

Maybe it also affects other miners. For example I noticed some fail in the benchmark by not finding the old libssl.

![image](https://github.com/RainbowMiner/RainbowMiner/assets/16374634/0aa68c8a-1b85-4609-848a-b4d4c4fbdfe9)

**Comment by timvis** [comment]
I found this in '/modules/Include.psm1'

![image](https://github.com/RainbowMiner/RainbowMiner/assets/16374634/8fe299e9-e714-4c45-a192-40ac6bfb3ce9)

**Comment by timvis** [comment]
got it, a colon seperates paths... sorry my wrong.

**Comment by RainbowMiner** [comment]
Yes, and the dot represents the current directory.
