### ISSUE TITLE
rplant problem !

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2599]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/83370e9a-a620-4a93-a56e-22614374f3c4)

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/ed2379c9-d864-4ad0-9355-e70320d3be72)

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/cbe23dc6-8025-4d49-9cbb-b11f0755637e)

Hello. Happy new year in advance. I wanted to mine in the "rplant" pool. but it gives the error you see in the pictures. I couldn't solve it no matter what I did. The only thing that works is balance :)

[debug_2023-12-31.zip](https://github.com/RainbowMiner/RainbowMiner/files/13801471/debug_2023-12-31.zip)

**Comment by RainbowMiner** [comment]
I have changed the profit calculation for RPlant in a way that it uses it's own API values. It no longer makes use of the WhatToMine module. This should solve the problem with mining TDC (and possibly other coins)

**Comment by MTCHANNELL** [comment]
Thank you. I'm testing it right away.

**Comment by MTCHANNELL** [comment]
Unfortunately, it gives exactly the same error.

**Comment by RainbowMiner** [comment]
Please also download the current `./Pools/WhatToMine.ps1` into your pools folder. It looks like you are running on an older version. Restart RainbowMiner after that, just to be sure.

**Comment by MTCHANNELL** [comment]
I'm testing it right away.

**Comment by MTCHANNELL** [comment]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/868cb258-111e-4c32-aebe-1cfe64a6c0cc)

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/05465e3d-3fa6-47cc-b502-f85c2cbbca86)

Now all errors have disappeared. but the message "There is no pool. Check your configuration" appears. I'm sure I've made all the settings. Because I applied the same process for the zpool pool from scratch and it worked.

**Comment by MTCHANNELL** [comment]
I noticed this. As soon as I enter the TDC wallet address, the message "no pool" begins to appear. "vkax" does not cause any problems. I don't understand what it's about :(

**Comment by MTCHANNELL** [comment]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/177962e7-320d-46c4-8b41-6f75127c0468)

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/5c19887c-bc87-4f20-a37c-0dbc259fa09a)

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/4fd90e72-a8be-48cc-a245-49e11d443b4a)

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/4eacb30a-bd9b-42a7-a505-699e4b951ca3)

Now I deleted everything and made it from scratch. Let me show you pictures of all the settings I made. I don't think I made a mistake anywhere. Because when I make the exact same settings in different pools, it works directly. I am facing this problem only in the "rplant" repository.

**Comment by MTCHANNELL** [comment]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/f1cc3ff8-986f-471a-8dff-c900c8eb1329)

Unfortunately, it doesn't work even though I tested it many times. Now I leave the rest to you.
my purpose;
Mining only "tidecoin" in the "rplant" pool.
I would be happy to take care of you whenever you are available. see you later.

**Comment by RainbowMiner** [comment]
There are multiple possibilities that could in fact  hinder the RPlant pool from being used. Profitability is zero, MaxTimeToFind is too low and more. I will add TDC myself and check in depth.

**Comment by RainbowMiner** [comment]
Ok, I have fixed some problems with the read-pools loop in case of only one pool, one coin. For me it worked perfectly now.

**Comment by whitindllc** [comment]
this is actually an interesting one since there are 3 TDC coins... tidecoin is the one most of us know... but mps lists tdcoin and tdccoin...

ive had tons of issues with rplant coins so this should be interesting...

**Comment by MTCHANNELL** [comment]
Yes, my problem is now completely solved. by running a single "rbm". I can mine tidecoin with cpu in rplant pool. I can mine with gpu in zpool pool. thank you for everything.
