### ISSUE TITLE
Configuration doesn't save NiceHash wallet ID

### ISSUE THREAD

**Issue by RetroShag** [RainbowMiner/RainbowMiner#26]
Configuration doesn't save NiceHash wallet ID and defaults to main BTC wallet ID

**Comment by RainbowMiner** [comment]
Hi, thank you for the issue. If you use v3.8.1.5, please use Configuration->Pools to set the nicehash wallet, in the meantime. I will have a look.

RBM

**Comment by RainbowMiner** [comment]
Of course you can also click "Updater.bat" to start the automatic update :)

RBM

**Comment by RetroShag** [comment]
Thank you for quick response.
