### ISSUE TITLE
minimum time to find config, similar to minimum hashrate/workers

### ISSUE THREAD

**Issue by RetroShag** [RainbowMiner/RainbowMiner#260]
Just an idea, is it possible to add/replace minimum hashrate/workers with minimum TTF.  Like setting a mimimum TTF of 3 hours for an algo.  I think it will be more universally useful and make sure you are not working on inactive pools.

**Comment by RainbowMiner** [comment]
Implemented. I added parameter "MaxTimeToFind" to configuration algorithms.config.txt and [C]onfiguration->A[l]gorithms. Put the allowed maximum average time to find an algorithm's block (in seconds), if you want to avoid slow pools.

**Comment by RetroShag** [comment]
Awesome.  Thank you for quick implementation.

**Comment by daimaah** [comment]
I think there's a mistake in the implementation, the code is looking for "MinTimeToFind" but the config files are using "MaxTimeToFind".

**Comment by rinkal26783** [comment]
is it possible to specify coin for TTF and MTTF? because most of the algos have multiple coins.

**Comment by RainbowMiner** [comment]
> is it possible to specify coin for TTF and MTTF? because most of the algos have multiple coins.

Not yet, this is a bit more complex. But I have an idea, already. I will add an extra parameter to algorithm.config.txt (an hashtable, into which coin:mttf values can be added). This should do the job.

**Comment by RainbowMiner** [comment]
Done. I added an extra .\Config\coins.config.txt
- same parameters as algorithms.config.txt
- add coins by editing coins.config.txt carefully
- use [C]onfiguration->Co[i]ns

**Comment by rinkal26783** [comment]
that's great. I have another idea, if you can add something in config.txt about mining priority either based on coin mttf or based on profit estimation.
config.txt
miningpriority:"1"- Miner will give preference on profit calculation. 
miningpriority:"2"- first miner will work as per mttf values. if there aren't any coins within mttf values,miner will switch back to mine based on profit calculation. Again if any coin is within mttf, it will switch back to mttf mining.

**Comment by RainbowMiner** [comment]
Good idea. I will think about this :)
