### ISSUE TITLE
lthn coin (lethean)

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2605]
is this correct?? its what shows up in the all pools tab

<html><body>

HashVault | CryptoNightR | LTHN | 0.0000000000 | - | 167.07 KH/s | 2.9 m | 1.7 |   | pool.hashvault.pro
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

</body>
</html>

isnt LTHN a argon2/chukwav2 algo? is this why it wont benchmark it or acknowledge it?

**Comment by RainbowMiner** [comment]
Maybe no blocks found. That would automatically reduce the profitability.

**Comment by whitindllc** [comment]
how do the commits work.... they get pushed out in the next update of 4.9.1.2?

**Comment by RainbowMiner** [comment]
Yes, either you wait for Release v4.9.1.2 or you download the current master.zip and extract it into your RainbowMiner folder.

**Comment by whitindllc** [comment]
if i push this to the server will it then update all the clients or does that only happen with a release update

**Comment by RainbowMiner** [comment]
You will have to wait for the next release update (happening within 12h)
