### ISSUE TITLE
All Benchmark marked as failed since couples of days

### ISSUE THREAD

**Issue by slappy6212** [RainbowMiner/RainbowMiner#2606]
Hi,
On one of my rig, i have all benchmark marked as failed even if the miner is working fine. I Tried a fresh install and same things.
Any ideas ?

**Comment by whitindllc** [comment]
whats the failed algo? mostly ethash?

what pools do you have checked to mine in?

**Comment by slappy3** [comment]
All algos are marked as failed. Only on one rig having this issue.

**Comment by slappy6212** [comment]
I played around with the anti-virus and the windows folder security tabs...I am not sure if it was this but the problem is solved.
