### ISSUE TITLE
Need old version Wildrig 0.35.2 for Nexa

### ISSUE THREAD

**Issue by slappy3** [RainbowMiner/RainbowMiner#2609]
Hi, Can you add Wildrig old version (0.35.2). it is needed for Nexapow and CurveHash and other algos on hiveos using Raseon VII.
Or point me how to create a custom miner if possible.

Thanks :-)

**Comment by slappy3** [comment]
Look like i did it myself. Download WildRig 0.35.2 / reame to WildRig0352 put in Bin folder.
Copy/rename WildRig.ps1 to WildRig0352.ps1 et voilà...now I am benchmarking with the old wildrig version to see if everything will pass.

**Comment by RainbowMiner** [comment]
Did you try all versions, downto 0.35.2? Or how did you find out, which version is still working on your Radeon VII?

**Comment by slappy3** [comment]
It is advised by the software when start mining that the current version is no longer supporting NEXA and refer to 0.35.2. 
I dont know what they change after this but there is a couple of algo losted.

**Comment by slappy3** [comment]
Update: Now with version 0.35.2 i have another problem. Wildrig stop and said Radeon VII not supported with Drivers newe than september 2020...LOL....For now i have no option to mine NEXA with my Radeon VII.

**Comment by whitindllc** [comment]
> Update: Now with version 0.35.2 i have another problem. Wildrig stop and said Radeon VII not supported with Drivers newe than september 2020...LOL....For now i have no option to mine NEXA with my Radeon VII.

you lose almost 90 cents a day mining that.... that card is more profitable mining kawpow... you would probably make more money at nicehash just letting it spec mine kawpow
