### ISSUE TITLE
Feature request: add the Blago.exe Miner for Burstcoin

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#261]
Feature request: add the Blago.exe Miner for Burstcoin.

I know that Burstcoin is a hard drive Miner.  Right now I start the Qbunble then the Miner, then close down the Qbundle and leave the Blago Miner running.

**Comment by RainbowMiner** [comment]
Since I am not used to this miner, would you do me favor and explain it in simple words to me? Do you have already some proven to be fine parameters?

**Comment by paulpoco** [comment]
So if I am looking at this correct one would only need one Variable of say BurstCPUtype = (avx or avx2 or sse) to form the command line with the proper exe file.

Not sure what happens when Rainbow Miner tries to run an exe outside of its' own directory?

I know under the Qbundle launch of the BlagoMiner_xxxx.exe the Windows systems pops up an UAC yes/no.  Would I assume as Rainbow Miner is run as Administrator it would do the UAC popup?

**Comment by paulpoco** [comment]
@RainbowMiner I found a BlagoMiner on Github with the downloadable Miners https://github.com/JohnnyFFM/blagominer/releases 

I tried it, didn't work right away as it complained about missing miner.conf file.

I tried it again after copying my miner.conf from the C:\Qbundle\BlagoMiner folder to my extracted folder and then ran it in a CMD.exe window and it worked.  I think the because the wallet ID is coded into the plot files, the Miner only needs to info from the miner.conf file saying which pool to use.

**Comment by RainbowMiner** [comment]
Thank you for the explanations. Sounds like an interesting project, indeed.
If I understand it right, it would be sufficient to add something like a "autoexec" to RainbowMiner, that contains commands to be executed at the startup.

**Comment by RainbowMiner** [comment]
Good, I added an autoexec feature:
- after the first start of Rainbowminer you will find a file ".\Config\autoexec.txt"
- put commands here, that shall be executed when RainbowMiner starts
- the path+command needs to be enclosed with double quotes (")
- arguments (if any) must follow after the closing double quote
- all commands will be exited automatically, if RainbowMiner is shut down

```
#
# RainbowMiner autoexec
# =====================
# 
# put commands to be executed at the startup of RainbowMiner here:
# - one line, one command
# - command and path must be enclosed with doublequotes (")
# - arguments (if any) must follow after the closing doublequote if the command
# - hashtag marks a comment
#

#"C:\Qbundle\BlagoMiner\Blagominer_avx.exe" --argument1 whatsoever1


```

**Comment by paulpoco** [comment]
Ok will try later tonight.

**Comment by paulpoco** [comment]
@RainbowMiner I updated to new version, there is no ".\Config\autoexec.txt" file.

**Comment by paulpoco** [comment]
@RainbowMiner manually added autoexec.txt it works fine.

Thanks.

**Comment by RainbowMiner** [comment]
Super :) I also fixed the issue, that the autoexec.txt is not being created upon restart.
