### ISSUE TITLE
MiningRigRental Rigs appear offline

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2612]
Good afternoon,

i have a rig with an nvidia gpu and a cpu. Mining on both. I have enabled miningrigrentals on it.
RBM created 94 rigs.The issue is that 22 out of 30 cpu rigs appears offline. And 46/64 gpu rigs are offline as well.
I have some algos (4 i think) in excluded algos but thats it. I cant find the issue anywhere.

Any help would be greatly appreciated.
Attached is the debug file.
[debug_2024-01-10.zip](https://github.com/RainbowMiner/RainbowMiner/files/13880773/debug_2024-01-10.zip)

**Comment by RainbowMiner** [comment]
Most probably you hit some minimum/maximum limit. For most of the cases it's the following variables in pools.config.txt:
```
  "MinHours":  "6",
  "MaxHours":  "168",
  "MaxMinHours":  "24",
```

Try to increase MaxMinHours and MaxHours
