### ISSUE TITLE
Mining with Rigel on Kryptex with email

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2616]
Kryptex has an autoexchange feature when mining with your email.
Srbminer works great for instance but Rigel has issues.
In Rigel.ps1 you have a replace function where @ is replaced with %40
This results in invalid logins in Kryptex as its replacing the @ from the mail.

**Comment by RainbowMiner** [comment]
> In Rigel.ps1 you have a replace function where @ is replaced with %40
> This results in invalid logins in Kryptex as its replacing the @ from the mail.

I see - i had that replace added for all relevant miners. Most (obviously not all) miners use an urldecode function on the user/wallet. Have you experienced trouble with Kryptix and other miners as well? Or is it Rigel, only.

**Comment by RainbowMiner** [comment]
These are the miners, that had that replace @ to %40 added:
![image](https://github.com/RainbowMiner/RainbowMiner/assets/39437538/29d0542b-5f68-404e-8e8b-6e419b50aaf6)

**Comment by papadrams** [comment]
I can confirm now that all those miners have this issue

**Comment by papadrams** [comment]
Since you are at it, pls also check why rbm receives 0 hashrate on all kawpow variants while benchmarking rigel. OI tried in multiple pools. Rigel runs normal but when the benchmark is done, it returns 0 hashrate. Shares has been found and i also went to localhost:32400 and it receives data normally.

This is from 127.0.0.1:32400
It still returns 0 to rbm

{"name":"Rigel","version":"1.12.2","os_name":"Windows","cuda_driver":"537.13","uptime":224,"algorithm":"neurai","watchdog":"off","pools":{"neurai":[{"id":0,"connection_details":{"protocol":"stratum","username":"*****************.w1","password":"x","worker":null,"hostname":"kawpow.auto.nicehash.com","port":9200,"ssl":false,"dns_mode":"system"},"state":{"issued_job":"1.07G"},"solution_stat":{"accepted":3,"rejected":0,"invalid":0},"average_latency_ms":47}]},"devices":[{"id":0,"selected":true,"name":"RTX 3060 Ti","total_mem":8589279232,"pci_address":"01:0","state":"mining","solution_stat":{"neurai":{"accepted":3,"rejected":0,"invalid":0}},"monitoring_info":{"core_temperature":68,"memory_temperature":96,"fan_speed":80,"power_usage":224.74525,"core_clock":1620,"core_clock_offset":0,"memory_clock":9251,"memory_clock_offset":0},"hashrate":{"neurai":33800591.78394849},"dual_ratio":null}],"solution_stat":{"neurai":{"accepted":3,"rejected":0,"invalid":0}},"hashrate":{"neurai":33800591.78394849},"power_usage":224.74525}

**Comment by RainbowMiner** [comment]
> Since you are at it, pls also check why rbm receives 0 hashrate on all kawpow variants while benchmarking rigel. OI tried in multiple pools. Rigel runs normal but when the benchmark is done, it returns 0 hashrate. Shares has been found and i also went to localhost:32400 and it receives data normally.
> 
> This is from 127.0.0.1:32400 It still returns 0 to rbm
> 
> {"name":"Rigel","version":"1.12.2","os_name":"Windows","cuda_driver":"537.13","uptime":224,"algorithm":"neurai","watchdog":"off","pools":{"neurai":[{"id":0,"connection_details":{"protocol":"stratum","username":"*****************.w1","password":"x","worker":null,"hostname":"kawpow.auto.nicehash.com","port":9200,"ssl":false,"dns_mode":"system"},"state":{"issued_job":"1.07G"},"solution_stat":{"accepted":3,"rejected":0,"invalid":0},"average_latency_ms":47}]},"devices":[{"id":0,"selected":true,"name":"RTX 3060 Ti","total_mem":8589279232,"pci_address":"01:0","state":"mining","solution_stat":{"neurai":{"accepted":3,"rejected":0,"invalid":0}},"monitoring_info":{"core_temperature":68,"memory_temperature":96,"fan_speed":80,"power_usage":224.74525,"core_clock":1620,"core_clock_offset":0,"memory_clock":9251,"memory_clock_offset":0},"hashrate":{"neurai":33800591.78394849},"dual_ratio":null}],"solution_stat":{"neurai":{"accepted":3,"rejected":0,"invalid":0}},"hashrate":{"neurai":33800591.78394849},"power_usage":224.74525}

Solved with new Rigel miner version 1.13.0

**Comment by sfalas01** [comment]
https://pool.kryptex.com/en/articles/account-mining-en
Only these pools support the email mining feature:
![image](https://github.com/RainbowMiner/RainbowMiner/assets/22576563/b2e173d5-83aa-4483-89f9-eef91d54aebc)

**Comment by Boulder08** [comment]
@RainbowMiner, at least MiniZ still seems to have this issue.
