### ISSUE TITLE
CpuminerRplant windows version 5.0.36 is broken

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2617]
Hallo, i was trying to find out why this miner was not connecting anywhere.
It seems like the windows version is broken. 
Its on their github as well:
https://github.com/rplant8/cpuminer-opt-rplant/releases/tag/5.0.36

We have to revert to 5.0.29

**Comment by RainbowMiner** [comment]
Yes, you are totally right. I'll roll back the Windows version.

**Comment by papadrams** [comment]
Do you remember why you had disabled minotaurx in miningrigrentals in this miner?

**Comment by UselessGuru** [comment]
I am quite happy with version v5.0.34

Problems with 5.0.36 are reported here:
https://github.com/rplant8/cpuminer-opt-rplant/issues/50
but developer does not seem to care :-(

**Comment by papadrams** [comment]
@UselessGuru If you have no object, i'll close this issue now
