### ISSUE TITLE
Pool Balance Glitch

### ISSUE THREAD

**Issue by LunarExplorer233** [RainbowMiner/RainbowMiner#2629]
I was mining in ZergPool, and it showed that I had a BTC balance of 0.76679374 in ZergPool, but then in the next day, my balance went down to 0.00084587. I want to understand where that balance went?

this is a small output for the balance update

RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   506.52
RainbowMiner_2024-01-07_17-05-56.txt:WARNING: Miner Gminer-GPU#00-GPU#01-GPU#02-GPU#03 mining EtcHash on pool ZergPool temporarily disabled.
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/00m 2 Times BzMiner EtcHash   ETC  RTX A4000 ZergPool 490W
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   506.52
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/00m 2 Times BzMiner EtcHash   ETC  RTX A4000 ZergPool 490W
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   506.52
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/01m 2 Times BzMiner EtcHash   ETC  RTX A4000 ZergPool 490W
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   505.66
RainbowMiner_2024-01-07_17-05-56.txt:WARNING: Miner BzMiner-GPU#00-GPU#01-GPU#02-GPU#03 mining EtcHash on pool ZergPool temporarily disabled.
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   505.66
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   505.66
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   505.66
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   505.87
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.01182468   505.87
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,804.34
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,793.71
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,793.71
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,793.71
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,793.71
RainbowMiner_2024-01-07_17-05-56.txt:314.94  H/s 00d/00h/00m 8 Times Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,764.44
RainbowMiner_2024-01-07_17-05-56.txt:319.00  H/s 00d/00h/00m 8 Times Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,764.44
RainbowMiner_2024-01-07_17-05-56.txt:306.00  H/s 00d/00h/01m 8 Times Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,764.44
RainbowMiner_2024-01-07_17-05-56.txt:302.62  H/s 00d/00h/02m 8 Times Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,764.44
RainbowMiner_2024-01-07_17-05-56.txt:310.06  H/s 00d/00h/03m 8 Times Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,773.61
RainbowMiner_2024-01-07_17-05-56.txt:312.85  H/s 00d/00h/04m 8 Times Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,773.61
RainbowMiner_2024-01-07_17-05-56.txt:312.11  H/s 00d/00h/06m 8 Times Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,773.61
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/00m 2 Times Gminer EtcHash   ETC  RTX A4000 ZergPool 509W  B
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,773.61
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/00m 2 Times Gminer EtcHash   ETC  RTX A4000 ZergPool 509W  B
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,752.93
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/01m 2 Times Gminer EtcHash   ETC  RTX A4000 ZergPool 509W  B
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76679374 32,752.93
RainbowMiner_2024-01-07_17-05-56.txt:WARNING: Miner Gminer-GPU#00-GPU#01-GPU#02-GPU#03 mining EtcHash on pool ZergPool temporarily disabled.
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,535.65
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,535.65
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,535.65
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,535.65
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,535.65
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,535.65
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,535.65
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,489.43
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,489.43
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,489.43
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,489.43
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,483.64
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,483.64
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,483.64
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,467.81
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/00m Once    Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,467.81
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/00m Once    Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,467.81
RainbowMiner_2024-01-07_17-05-56.txt:    0  H/s 00d/00h/00m 2 Times Gminer Equihash (144,5)      RTX A4000 ZergPool
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,467.81
RainbowMiner_2024-01-07_17-05-56.txt:WARNING: Miner Gminer-GPU#00-GPU#01-GPU#02-GPU#03 mining Equihash24x5 on pool ZergPool temporarily disabled.
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,466.94
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.76255413 32,466.94
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.00084587    36.01
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.00084587    36.01
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.00084587    36.03
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.00084587    36.03
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.00084587    36.03
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.00084587    36.03
RainbowMiner_2024-01-07_17-05-56.txt:ZergPool        0.00084587    36.02

**Comment by whitindllc** [comment]
wow wtf i have 3 a4000's and they run between 110 to 120 watts each tops....

**Comment by RainbowMiner** [comment]
Please do check with ZergPool for your real numbers. This looks like an API failure on Zergpool.
