### ISSUE TITLE
Neoscrypt profit issue?

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#263]
Ses picture, unrealistic profit. Pool or RBM issue. @RainbowMiner 
![screenshot_20181028-160143_teamviewer](https://user-images.githubusercontent.com/35561346/47617765-fa286380-daca-11e8-9765-b262bbe44351.jpg)

**Comment by RainbowMiner** [comment]
Pool issue. I will check!

**Comment by RainbowMiner** [comment]
Yes, these have been overexagerated pool prices (reflects also in the accuracy of 33%). The miningpoolhub modules, I programmed, are the only ones, that are not protected against overexageration.

**Comment by RainbowMiner** [comment]
To clear this, delete the miningpoolhub/neoscrypt stat files in .\Stats\Pools (e.g. MiningPoolHub_NeoScrypt_Profit.txt)

**Comment by RainbowMiner** [comment]
I will add a protection function to this pool, too.

**Comment by RainbowMiner** [comment]
Implemented. Now Rainbowminer should be immune against price exagerations at MiningPoolHub
