### ISSUE TITLE
Why is Attribute Utility (attrib.exe) asking to bypass firewall

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#264]
I just put RainbowMiner on a dedicated mining machine after my test system had been stable for some time.  Sometime while benchmarking, attrib.exe asked for a firewall exception.  Searching for this brings up some results that this could be a trojan miner.  I know most mining software is detected as malware but this is the first time I have seen this from any miner and didn't encounter this on my test machine.  Is this part of RainbowMiner or do you know what miner uses attrib.exe?  Since rbminer downloads other miner programs and hackers have been known to hijack a github account and post malware, this could be an issue at some point.

**Comment by RainbowMiner** [comment]
No, RainbowMiner does not use attrib.exe, nor do I know of a Miner using this. Is this a Nvidia or an AMD based rig? I have never had this Firewall question, neither.

**Comment by RainbowMiner** [comment]
Is this a clean setup mining rig, or has it been used to mine before? Eventually, the attrib.exe is an existing infection that is being triggered by using miners it detects.

**Comment by RainbowMiner** [comment]
Ok I found something in an old closed issue of Iceminer. It looks like this Miner uses attrib : 

https://github.com/jceminer/cn_cpu_miner/issues/7

.. it look.like it is intended behavior. You could try to disable Iceminer and see, if the exception disappears.

**Comment by RainbowMiner** [comment]
On the other hand, it could be an existing infection on that machine, that always starts background mining, when the CPU load drops, e.g. when miners are being switched or fail during benchmark (https://www.bleepingcomputer.com/news/security/cryptocurrency-miner-plays-hide-and-seek-with-popular-games-and-tools/).

That brings me back to the questions:
- which GPU are you using?
- has this system been in use before?
- what happens, if no Miner is running?

**Comment by jch9678** [comment]
These rig is 5 r9 390
Yes, it has been in use for a long time.  It has been using srbminer for quite a while most recently.
If no miner is running it just sits there.  
I don't have any scheduled task like that article describes nor do I see an IOstream.exe in programdata.

**Comment by RainbowMiner** [comment]
> If no miner is running it just sits there.

This is good :) In this case I would suspect Jceminer using obfuscation method to avoid being flagged as virus by antivir programs.

**Comment by RainbowMiner** [comment]
I can confirm that it is of no harm: it's Jceminer CPU that obfuscates itself as attrib.exe to avoid being flagged as virus:
![image](https://user-images.githubusercontent.com/39437538/47645694-103d2f00-db72-11e8-98b0-d33d409f057a.png)

Since Jceminer spawns attrib.exe as child process, it explains, why you get the UAC prompt.

**Comment by jch9678** [comment]
Thank you.
