### ISSUE TITLE
new start up issue

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2640]
this issue just popped up today.... this is using the latest code released yesterday

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/48439b49-6a04-49b2-bb2f-c2e01bfcf6bb)

**Comment by whitindllc** [comment]
maybe it has to do with this ?

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/3cade052-e0c9-4678-ac46-bcc56e770dff)

**Comment by RainbowMiner** [comment]
Thank you! It looks like RPlant has changed the number format of the fee field in their API. I will push a commit to fix it.

**Comment by RainbowMiner** [comment]
Ok, solved. They suddenly started to send a string containing the % symbol instead of a double for some coins. I have implemented a workaround, so that we can handle the string/double mix.

**Comment by whitindllc** [comment]
yes i dumped those two files on my machine and the error went away.... TABO is the only coin thats acting weird

RPlant          TABO    403,129,641,683.0 12,811,103,484.0 2,339,882.59 93,107,040,466.50

**Comment by whitindllc** [comment]
possibly... but the fix you put together made that error go away
