### ISSUE TITLE
Server-Client setup screws MRR

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2642]
Hallo!
I tried using server client so that i can manage all my rigs from 1 point.
I had i huge issue with mrr.
On documentation it says that mrr settings can only be configured per rig.
However the issues lies in pools.config.
This is a config that pretty much needs to be in the server client configuration.
However in this file there are many setting for mrr.
Personally i edit a lot of these per rig. Some examples are:
"AutoCreateMaxMinHours":  "",
"PriceFactor":  "",
"Title":  "%algorithmex% mining with RainbowMiner rig w1 %rigid%",
and especially
"User":  "****",
"API_Key":  "*****",
"API_Secret":  "*****"

On every rig these parameters can be different. Especially the api keys.
 I have 1 for each rig.

When the setup sends to clients the pools.config, it edits pool mrr as well.
So all hell breaks loose.
Any way to not copy the miningrigrentals details?

**Comment by whitindllc** [comment]
pull the pools part out of the config under "ServerConfigName": "algorithms,coins,config,POOLS,scheduler", and add it to the exclude maybe....

**Comment by papadrams** [comment]
I wouldnt even consider making the server client setup if the pools.config is not part of it.. 
What good would it be if i excluded it?

**Comment by whitindllc** [comment]
if every single one of your downchain clients has something different in the pools.config file what real choice do you have...

whats in this file?
Config\mrr.config.txt

If pool MiningRigRentals is in use, this file contains per worker name specific configuration parameters. Setting any parameter to a value other then empty string will override the same-name main parameter in pools.config.txt

**Comment by papadrams** [comment]
I cant set api keys per rig in mrr.comfig.txt
I said it in the first post as well. 
In the documantation it says to create api keys for each individual rig.
https://github.com/RainbowMiner/RainbowMiner?tab=readme-ov-file#how-can-i-rent-my-rig-to-someone-at-miningrigrentalscom
I will not pretend i know why, but i suppose i have to.
I dont know what other choice i have. Thats why i wrote here.

**Comment by whitindllc** [comment]
this part is what catches my attention

setting any parameter to a value other then empty string will override the same-name main parameter in pools.config.txt

the way it is written it is saying whatever you put in the mrr file will override whatever is in the pools.config

have you messed around and added these to the file with different values than whats in the pools.config and seen what happens?
"AutoCreateMaxMinHours": "",
"PriceFactor": "",
"Title": "%algorithmex% mining with RainbowMiner rig w1 %rigid%",
and especially
"User": "****",
"API_Key": "",
"API_Secret": ""

**Comment by crb247** [comment]
The answer you are looking for might be in this one [link](url)https://github.com/RainbowMiner/RainbowMiner/issues/679

I remembered finding it back when i was playing around with a server/client setup and the server kept overwriting my API Keys on the Clients

**Comment by papadrams** [comment]
> The answer you are looking for might be in this one [link](url)#679
> 
> I remembered finding it back when i was playing around with a server/client setup and the server kept overwriting my API Keys on the Clients

That has to be it!! I will try it when i've got the time.
Although i would recommend @RainbowMiner to be set from the get go. 

Propably  if i add just the "pools:MiningRigRentals" it will skip the whole miningrigrentals section of pools.config.txt

**Comment by whitindllc** [comment]
yes maybe that fix from 4 years ago might work... 

please advise

**Comment by RainbowMiner** [comment]
> Propably if i add just the "pools:MiningRigRentals" it will skip the whole miningrigrentals section of pools.config.txt

Yes, it does solve the problem. I really think, we could add this from the start, though I intended the mrr.config.txt to be the place to hold device specific configurations, when in Client/Server configuration. 

> I cant set api keys per rig in mrr.comfig.txt

You are right, that data is in the pools.config.txt, only. I think this is a bit unfortunate, but could be changed. 

So, basically, the following would be a possible way to go:
- put `pools:MiningRigRentals:API_Key,pools:MiningRigRentals:API_Secret` onto each client's ExcludeServerConfigVars
- edit the client's mrr.config.txt for individual Title, Description, limits and all other options
- for the latter you have two possibilities: edit the mrr.config.txt on each machine or in an subdirectory of the servers's Config folder. The subdirectory must match the client's name. I have chosen the second way currently. I simply mkdir a subdirectory and copy the server's mrr.config.txt into it, then I edit it to my needs.
