### ISSUE TITLE
Issue with RBM when restarts

### ISSUE THREAD

**Issue by Lagarinhos** [RainbowMiner/RainbowMiner#2644]
Hi, 

When I start normally RBM.. everything seems fine.
![image](https://github.com/RainbowMiner/RainbowMiner/assets/33929795/d27886b2-3853-4094-a484-838767d9962f)

But if I press R - Restart ... I get all those errors.
![image](https://github.com/RainbowMiner/RainbowMiner/assets/33929795/02c2af21-dc69-404e-bf8c-874504d288b5)

Also MiniZ started to detect my 3080ti 12gb as 3080 10gb since last rbm update.. it almost halved my hashrate on it

I already formatted the PC and reinstalled RBM... it started since last rbm update

cheers

**Comment by RainbowMiner** [comment]
That is somehow very weird, especially since I use [R] many times and never have experienced those errors. I will try to find out, what is going on.

**Comment by Lagarinhos** [comment]
Same. I use all the time. This error when pressing R is happening only in 1 of my rigs. I have formatted the PC and installed fresh RBM and the error persisted. Is there any kind of debug log that I can provide to help you?

**Comment by Lagarinhos** [comment]
and this is the other bug.... My 3080ti is being detected as 3080 on MiniZ. It was OK before the last update.
![image](https://github.com/RainbowMiner/RainbowMiner/assets/33929795/70529b7a-0bf9-417a-9168-bc53f2d8cc19)

**Comment by RainbowMiner** [comment]
Please create and upload a Debug file on that one machine. Use http://localhost:4000 and click "Debug file" on the left hand side.

Regarding the MiniZ: I have no influence on the seperate miners. You will have to open an issue on  https://miniz.cc/2018/07/28/supported-gpus/ for more information on that.

**Comment by Lagarinhos** [comment]
[debug_2024-01-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/14067943/debug_2024-01-26.zip)

**Comment by RainbowMiner** [comment]
You are currently using PowerShell Core v7.4.1 - maybe that is the culprit. Try to downgrade to PowerShell Core v7.2.18: https://github.com/PowerShell/PowerShell/releases/tag/v7.2.18

**Comment by Lagarinhos** [comment]
It seems to have resolved! Thanks a lot!
