### ISSUE TITLE
The data given by RPlant is too different from other pools

### ISSUE THREAD

**Issue by yoyofreeman** [RainbowMiner/RainbowMiner#2646]
and the way RBM handles them is incorrect.
![选区_070](https://github.com/RainbowMiner/RainbowMiner/assets/35377453/2f632db2-4902-48f1-ad80-1fc7cae86411)
![选区_071](https://github.com/RainbowMiner/RainbowMiner/assets/35377453/d768200f-33f7-4681-aba5-637654a24bb6)
![选区_072](https://github.com/RainbowMiner/RainbowMiner/assets/35377453/f6580f3e-961e-40e7-b6c3-9a2be35b4344)

**Comment by RainbowMiner** [comment]
Yes, that looks pretty much off. Obviously they have added another divisor. I will find out and fix it.

**Comment by yoyofreeman** [comment]
> 是的，这看起来很不对劲。显然他们又加了一个除数。我会找出并修复它。

Or, give us a few parameters in pools.conf and we can try to fix it ourselves.

**Comment by RainbowMiner** [comment]
Balance module is fixed. Now I go for the pool module.

**Comment by RainbowMiner** [comment]
Ok, it isn't a pool module problem. The BIT rate is that of the BitDAO token. I'll tweak the rates database accordingly. The correct rate should show up within the net 15 minutes on all rigs.
