### ISSUE TITLE
Ghostrider algo not appearing at all.

### ISSUE THREAD

**Issue by RoyCRoderickIII** [RainbowMiner/RainbowMiner#2647]
So i have a small phone farm of older 32bit Android. And I was attempting to use the "Best Pool" to have rbm tell me which might be the most profitable Ghostrider coin of the 24, and to my surprise, it does not appear at all, I cannot even select it by algorithm . now I thought okay maybe because of low profit, but then I see panthera on there for zergpool which only has 6 miners active as i am writing this, while ghostrider has 5328 which is the most above even verus.

**Comment by RoyCRoderickIII** [comment]
Was pointed out Take2 is the ghostrider algorithm, continue the amazing work :)

**Comment by whitindllc** [comment]
have you looked at verus with cell phones.... it pretty profitable

**Comment by RoyCRoderickIII** [comment]
verus only works for 64bit phones either natively in android or through termux/userland miners.

**Comment by whitindllc** [comment]
> verus only works for 64bit phones either natively in android or through termux/userland miners.

thats not true.... orange phi 5 and the apk for verusminer9k support 32 bit,...

**Comment by RoyCRoderickIII** [comment]
> > verus only works for 64bit phones either natively in android or through termux/userland miners.
> 
> thats not true.... orange phi 5 and the apk for verusminer9k support 32 bit,...

Orangi pi 5 is 64 bit processor, i have 2 64 bit processor phones running 32 bit android that says otherwise
