### ISSUE TITLE
abelhash

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2649]
saw a commit to add abelhash to rbm... what pool willl be handling it?

**Comment by whitindllc** [comment]
looks like it might have rigel support...

is this a userpools only setup??

looks like it only supports abelpool.io at this point

**Comment by RainbowMiner** [comment]
I am using it currently as one of my userpools. But I will add a pool module now.

**Comment by whitindllc** [comment]
okay ive got my whiskey in hand and im messing around with it... however the new code seems to have forced a rigel update and now its benchmarking stuff... so it might be awhile for a report...

**Comment by whitindllc** [comment]
Works
