### ISSUE TITLE
Balances on Monitoring Page

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#265]
I apologize ahead of time because I believe this was asked before. But I am wondering if there is a way to allow balances to be available in the monitoring page. Maybe as an opt in to sending the info?

Or if this is already in the works, Then just disregard.

**Comment by RainbowMiner** [comment]
This is not yet in the works. I will add this.

**Comment by jch9678** [comment]
I like this idea too.  Actually I wouldn't mind if you could add more functionality to it like localhost:4000.  Maybe you just want to keep it simple for reporting though, and we can forward ports to get more details.
