### ISSUE TITLE
MiningDutch API

### ISSUE THREAD

**Issue by RoyCRoderickIII** [RainbowMiner/RainbowMiner#2654]
MiningDutch pool updates in the best pool, shows up profit/earnings in the console window, but in the GUI show's 0.

![image](https://github.com/RainbowMiner/RainbowMiner/assets/19983866/1d068a85-1087-45ab-9fae-9c9205062723)

**Comment by papadrams** [comment]
I dont know if you did something but MiningDutch came up to my rigs. MiningDutchcoins did not.

**Comment by papadrams** [comment]
Nvm its not showing up again
