### ISSUE TITLE
USERPOOL config not being downloaded by clients

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2658]
I have tried adding custom user pools, they seem to be added correctly however only my server and 1 client have the userpools added to their configs.

For some reason the rest of the clients will not download the userpool, I dont know why. I tried restarting, ext.

I found this other issue and wondering if its related
https://github.com/RainbowMiner/RainbowMiner/issues/2362

It is possible that while I was creating the userpool I accidentally entered incorrect information initially so the majority of my clients are now locked and will not download new pool data.

The clients which dont see user pools still connect to the existing pools list and accept changes to those pools.config from the server. Just not changes to userpools

**Comment by realsetvin** [comment]
additional context, when adding even more additional userpools, the clients which dont see userpool still do not see the new userpools I added.

**Comment by whitindllc** [comment]
does it look anything like this??

{
        "Enable":  "1",
        "Name":  "AnonCommunityPool",
        "PoolFee":  "0",
        "Algorithm":  "Equihash24x7",
        "CoinName":  "ANONymous",
        "CoinSymbol":  "ANON",
        "Currency":  "ANON",
        "Protocol":  "stratum+tcp",
        "Host":  "47.242.230.93",
        "Port":  "3330",
        "User":  "$Wallet.$WorkerName",
        "Pass":  "x",
        "Region":  "HongKong",
        "SSL":  "0",
        "Worker":  "$WorkerName",
        "EthMode":  ""
    },

**Comment by realsetvin** [comment]
I was able to get the server and 1 client to accept userpools, however now the rest of my clients seem to be locked in a state where they no longer look for user pools at all.

**Comment by RainbowMiner** [comment]
Very strange. Could you please send me a Debug file of one of the clients, that stopped download the userpools.config.txt?

**Comment by whitindllc** [comment]
soooo let me see if understand.... you setup a few pools or a pool once... enabled it/them with 1... all the machines took them... then you added more to the userpools file and after that only one machine would take them?? 

the userpools.config on machine 4 is not the same as machine 1(the working one)?

**Comment by realsetvin** [comment]
I believe what happened the first time setting up the pool, I put in wrong information. At the time, I believe one client was turned off at that time. Later I fixed the userpool info and suddenly the server accepted the changes and mined to the userpool, then the client which I turned on later accepted the changes too.

All of the other clients must have become in a locked state as described in this other issue https://github.com/RainbowMiner/RainbowMiner/issues/2362

**Comment by whitindllc** [comment]
> I believe what happened the first time setting up the pool, I put in wrong information. At the time, I believe one client was turned off at that time. Later I fixed the userpool info and suddenly the server accepted the changes and mined to the userpool, then the client which I turned on later accepted the changes too.
> 
> All of the other clients must have become in a locked state as described in this other issue #2362

did you remove the 4 or 5 entries that are sitting there as examples and blank out the file

**Comment by whitindllc** [comment]
also if you look on the configs of your downstream clients do they have this in the config?

"ServerConfigName": "algorithms,coins,config,pools,userpools"

i have a ton of client pcs that i fucked up on when i was trying to change the device from cpu,gpu to cpu and it didnt have userpools in there so it didnt pull it down

**Comment by realsetvin** [comment]
> also if you look on the configs of your downstream clients do they have this in the config?
> 
> "ServerConfigName": "algorithms,coins,config,pools,userpools"
> 
> i have a ton of client pcs that i fucked up on when i was trying to change the device from cpu,gpu to cpu and it didnt have userpools in there so it didnt pull it down

I will try to follow up on this sometime this weekend - I guess otherwise completely reinstalling the client is the solution?

**Comment by realsetvin** [comment]
this is still an ongoing issue

**Comment by realsetvin** [comment]
> userpools

this helped me figure out the issue, 
![image](https://github.com/user-attachments/assets/c53e22c5-59d2-4245-969d-aff206958aaa)

this userpools was not enable by default

**Comment by realsetvin** [comment]
can be fixed by adding userpools as an option or just enable by default

**Comment by realsetvin** [comment]
issue solved, "EnableServerPools": "1", needs to be enabled on server, then clients will download enable server pools
