### ISSUE TITLE
VISH’s profits are abnormal

### ISSUE THREAD

**Issue by yoyofreeman** [RainbowMiner/RainbowMiner#2659]
![选区_116](https://github.com/RainbowMiner/RainbowMiner/assets/35377453/6388cfeb-fdf2-4e51-8ee7-be9548eb17bc)

**Comment by whitindllc** [comment]
im making bank bro... 

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/163ebc2c-18cd-4881-a6d2-505f46319d9c)

**Comment by RainbowMiner** [comment]
Oh! Yes, Zergpool's API gives is overblown numbers on VISH, currently. It should be resolved within some time. In the meantime, I would tend to block VISH for 12 hours.

**Comment by whitindllc** [comment]
on my side it looks like this garbage...if it i didn't need zerg/zpool to tell me the next big up and coming coin i would have turned them off 6 months ago

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/620b591d-24a0-4d66-9643-9bfe24fb459a)

**Comment by realsetvin** [comment]
> on my side it looks like this garbage...if it i didn't need zerg/zpool to tell me the next big up and coming coin i would have turned them off 6 months ago
> 
> ![image](https://private-user-images.githubusercontent.com/128111946/301482713-620b591d-24a0-4d66-9643-9bfe24fb459a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODc3NTUsIm5iZiI6MTcwNjc4NzQ1NSwicGF0aCI6Ii8xMjgxMTE5NDYvMzAxNDgyNzEzLTYyMGI1OTFkLTI0YTAtNGQ2Ni05NjQzLTliZmUyNGZiNDU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMTM3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzQyMzY4NmM1MzA1MjdmMzNjNzVmYjgwNDU0YzVkMmNiMTQ4Zjg4NDQyMWJiZThkNDllNDJkMWQ4YzliZTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WuGnE6sP39zm8zH-DjwywH3-XK5v8NsnoHJEurURauI)

Is this something which needs adjustment on zergpool side? We can communicate to the owner and I believe he would also be eager to fix the issues (after becoming aware of them)

**Comment by RainbowMiner** [comment]
Yes, it's a miscalculation of VISH's profit number in the ZergPool-API.

**Comment by pinpins** [comment]
Should be back to normal now
