### ISSUE TITLE
internal graphics and cpu mining performance

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2666]
this is more of a curiosity question...

if you have a PC with integrated graphics does it negatively affect the CPU miners ability turning on or allowing the integrated graphics card to mine.... I haven't tested it yet

**Comment by RoyCRoderickIII** [comment]
Yes,having tested it on both my nvidia graphics on my laptop and the internal on my desktop as well. While it does sometimes add new options ie algorithms, it was not worth it. I even had papadreams show me how to install older versions of some of the miners that showed they benchmarked successfully on my graphics cards. But in the end the loss was more then the gain.

**Comment by whitindllc** [comment]
so you tested cpu,gpu or cpu,nvidia in the config and then you tested just cpu in the config and it the cpu hash jumped?

**Comment by RoyCRoderickIII** [comment]
Once i got all the older miners i wanted i rebenched all the cpu by itself, then did the same for the GPUs, and just odd the top of my head randomx on my desktop hits 2kh no problem, ,but with gpu running would drop to like 1.2, and if i recall the only miners that ever worked for me atleast was randomx for the gpu and cryptonight upx , and neither atleast for me was worth it . My overall profit went up after i disabled the GPUs all together.

**Comment by whitindllc** [comment]
thats interesting... i suspected that.... i just didnt test it as i have 500 or so devices running... Thank you Greatly

We have talked before on discord... i am youritpro there...

**Comment by whitindllc** [comment]
yeah having the internal gpu try to mine halves the cpu performance greatly
