### ISSUE TITLE
CCMiner Verus CPU version

### ISSUE THREAD

**Issue by artplan1** [RainbowMiner/RainbowMiner#2677]
Hello!

CCMiner Verus supports CPU mining, it would be nice if RBM will support this as well

https://docs.verus.io/economy/start-mining.html#suitable-devices

https://github.com/monkins1010/ccminer/releases/tag/v3.8.3a

**Comment by RainbowMiner** [comment]
I think, I remember having this miner in our library. I'll check.

**Comment by artplan1** [comment]
yep, it's in library, but it has explicit Nvidia requirement at the moment

**Comment by RainbowMiner** [comment]
Ah, I see - the CPU version 3.8.3 is handled by the CpuminerVerus module.

**Comment by artplan1** [comment]
Got it, thank you! 😎
Probably better to rename the module for consistency  purposes
