### ISSUE TITLE
How to mine with a single coin?

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2679]
Hello. I want to mine with only one coin of my choice in the pool.
for example;
pool:zergpool
coin:BTCturquoise (BTCQ)

It is easy to prepare with .bat, but is it possible to do something like this with "rbm"?
.bat example : -o stratum+tcp://ghostrider.eu.mine.zergpool.com:5354 -u ltcwallet -p c=LTC,mc=BTCQ,ID=test

**Comment by RainbowMiner** [comment]
Of course :) Just use ZergPoolCoins, then add your LTC wallet address (to be sure, that the pool uses autoexchange to Litecoin, set AECurrency to LTC) in pools.config.txt, then set CoinSymbol to "BTCQ". Done!
```
  ...
  "ZergPoolCoins": {
    "LTC": "$LTC",
    "AECurrency": "LTC",
    "CoinSymbol": "BTCQ",
   ...
  },
  ...
```
