### ISSUE TITLE
Exosis not Added?

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#268]
I looked through the config files but could not find anything mentioning exosis. How to add it and on which pool is it mined? 

Cheers!

**Comment by RainbowMiner** [comment]
It is mined on bsod.pw pool. If you want to mine it, add it to your Algorithms in config.txt. You will need the current release v3.8.10.10 containing CryptoDredge for Nvidia or WildRig for AMD.
