### ISSUE TITLE
hashvault lthn

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2685]
the PWSH is reporting that my 5500 should make $1.50 a day and that was a4000's should make $3.28 a day...

The website reports the max a day i should expect to make it 20 cents

**Comment by whitindllc** [comment]
this pool is just off by a decimal at least... 
CryptoDredge      1.00% Argon2ChukwaV2                                    100.01 kH/s       -  349W 0.00002899   1.450            2.5 m         81% HashVault-LTHN

its thinking 20 cents a day and RBM for 4 different pc's is thinking 4 dollars a day

**Comment by RainbowMiner** [comment]
This should be solved within the next hour. The pool used a quote from Coingecko (which pulled the data from Tradeogre LTHN/BTC where there are no buyers and a much too high last trade value). I have switched this to rbminer.net's quote API.

**Comment by whitindllc** [comment]
is this why some or most of the coins on hashvault have disappeared? or give weird prices?

**Comment by whitindllc** [comment]
i got haven thinking its going to make 10 dollars on 1 3060ti
