### ISSUE TITLE
I have the problem in the picture on all my motherboards.

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2688]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/698746b2-4912-433e-a4e3-94b5994d7415)

I replaced all my bios batteries. I tested my date time both automatically and manually and it shows the same error. I don't think it's a big problem, but I wonder why it shows like this even though everything is fine.

**Comment by RoyCRoderickIII** [comment]
Its not a huge problem, but if you plan on using 2 factor authentication on that machine, the time will need to be correct.  i cannot tell from your picture if its a linux or windows machine, but just do a quick google search for time server syncing, and should fix your problem

**Comment by MTCHANNELL** [comment]
I am using windows 11. But there is no method I haven't tried. I don't use authentication. Frankly, it's not a big problem. But will such an error cause any problems?

**Comment by RoyCRoderickIII** [comment]
I had the same.problem.on my laptop for a month before my authenticator gave me the issue lol. But as far as rbm goes i see no reason why it  should besides being a annoying reminder.

**Comment by whitindllc** [comment]
w32tm /config /manualpeerlist:"time.nist.gov time.google.com" /syncfromflags:manual /update

**Comment by MTCHANNELL** [comment]
error code: The following error occurred: The service was not started. (0x80070426)

All services are as Windows was first installed. I am using unmodified windows. untouched.

**Comment by whitindllc** [comment]
what happens when you type net start w32time

**Comment by MTCHANNELL** [comment]
I opened cmd as administrator
01-) net start w32time
02-) w32tm /config /manualpeerlist:"time.nist.gov time.google.com" /syncfromflags:manual /update
I applied it sequentially and the commands worked successfully. I will run these commands on my hardware at night and see if that fixes the problem.

**Comment by whitindllc** [comment]
once you set this it shouldn't need to be played with again.. maybe at first if the time isn't right and once you hit sync it should stay synced forever and pick up the time hourly...
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/10c568c3-f2f4-498e-b373-cda2b106b615)

**Comment by MTCHANNELL** [comment]
01-) net başlangıç ​​w32time
02-) w32tm /config /manualpeerlist:"time.nist.gov time.google.com" /syncfromflags:manual /update

I put these codes in "start.bat". It works without any problems :) I added it to the top line of the .bat file just in case I don't get this error again in the future. It's working smoothly now. Frankly, I do not want to remotely intervene in all my PCs. Since I use a diskless system, the file I share from the server is automatically applied at system startup. It was more practical to do it this way.
