### ISSUE TITLE
The hashrate is wrong but whose fault is it?

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2689]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/ab406117-df97-4d71-b25f-dfedc5049049)

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/9d206690-fa87-4597-8a27-6a59ebf70884)

Hello. I get 52mh/s hashrate in the "autolykos2" algorithm with srbminer. However, when I look at the pool statistics, it shows between 29 mh/s.
1-) Does this problem affect earnings?
2-) Is it a problem caused by pool statistics?
3-) Is it srbminer error?
4-) Could it be related to rbm?

note: 
1-) I tried it with different miner and got the same result.
2-) I tried it manually with .bat and got the same result.
manuel : SRBMiner-MULTI.exe --disable-cpu --disable-worker-watchdog --algorithm autolykos2 --disable-cpu --pool stratum+ssl://autolykos-us.unmineable.com:4444 --wallet LTC:walletaddress.001RX570

windows : v11
srbminer : v2.4.7
pool : unmineable

**Comment by whitindllc** [comment]
how long are you waiting?

**Comment by MTCHANNELL** [comment]
on average 10 hours

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/eca11139-e4da-49ea-80a3-604de747ebb7)
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/229cc53f-2285-4250-8ada-2e4e896c5f6a)
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/60b4ac94-175c-4a31-8d5c-0d2715917d82)
![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/68cd2fe1-ad03-42d1-aa8c-ba2613f9fd63)

I received 108 acceptances in an average of 10 hours. is not it less?

**Comment by whitindllc** [comment]
it took 10 hours to find 100 shares of erg?

**Comment by MTCHANNELL** [comment]
Yes, that's right, there were 100 acceptances in 10 hours. So I changed the algorithm. I get continuous acceptance in the "ethashb3" algorithm without any problems. I'm happy right now. It works smoothly.

![image](https://github.com/RainbowMiner/RainbowMiner/assets/94814602/7ede1fd0-3c93-4e54-9cee-b161c13bfd54)
