### ISSUE TITLE
Ravenminer showing up when it probably shouldnt.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#269]
Miner          Fee Algorithm       Speed Power*   BTC/Day  USD/Day  Accuracy Pool                 PoolFee
-----          --- ---------       ----- ------   -------- -------- -------- ----                 -------
EnemyZealot  1.00% X16R       51.93 MH/s   373W 0.00004367   0.2754      96% Ravenminer-Ravencoin   0.50%
CryptoDredge 1.00% Skunk     127.51 MH/s   390W 0.00001818   0.1146      79% NiceHash               2.00%

I do not have Raven miner selected as a pool? Should that show up? Its in standby because its not profitable right now. Those were the only two that show up in my list right now.

**Comment by RainbowMiner** [comment]
Which pools do you have selected?

**Comment by Yamanipanuchi** [comment]
BlockMasters,Zpool,NLpool,BlazePool,NiceHash,BlockMastersCoins

**Comment by RetroShag** [comment]
I've seen that x16r mined for ravenminer pool, even though I do not have it selected as one of the pools.  I figured it was the RainbowMiner fee being mined.

**Comment by paulpoco** [comment]
Would be nice if on the https://rbminer.net/monitoring/?user= website that when donation run was running, it somehow would say "Donation run running".

**Comment by RainbowMiner** [comment]
@RetroShag Ah! That explains it :) Thank you. 
@paulpoco Good point. I will add a note.
