### ISSUE TITLE
Support for linux

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#271]
Is rainbowminer has linux version?

**Comment by RainbowMiner** [comment]
No, not yet. But I am constantly thinking about this. Might be worth a shot.

**Comment by RainbowMiner** [comment]
😄 oh dear! Ok, I will think more stronger about a solution. Guess, I will program this, using csh or maybe better cpp.

**Comment by RainbowMiner** [comment]
What tools are you using to overclock AMD gpu in a linux environement?

**Comment by rinkal26783** [comment]
I have nvidia. Is it supported in linux?

**Comment by RainbowMiner** [comment]
> I have nvidia. Is it supported in linux?

Yes, Nvidia is no problem.

**Comment by RainbowMiner** [comment]
This is already implemented, by now.
