### ISSUE TITLE
Converting to a coin not even possible

### ISSUE THREAD

**Issue by RoyCRoderickIII** [RainbowMiner/RainbowMiner#2717]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/19983866/32172c03-c331-4726-be16-bbdc70a51fd5)
So woke up to find my laptop mining a coin to zergpoolcoins, zergpool does not even support...... checked the wallet on zerg just to make sure, and its using my ADA address and zerg was just trying to pay it out in BTC, using the address

**Comment by RoyCRoderickIII** [comment]
Yes it does, however it does not support a payout to cardano.... I checked both the coins, payout list and even checked the wallet address its attempted to pay to and on zerg my ada wallet was acrewing btc.

**Comment by whitindllc** [comment]
oh you can put wtf you want in there and it will mine and then when it cant pay it, it will keep what you mined... Zpool is even funnier... they let you spend hours benchmarking coins that they dont actually auto exchange and then they keep them
