### ISSUE TITLE
Z-ENEMY VER 1.23 now released

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#272]
@everyone Z-ENEMY VER 1.23 From: Dk & Enemy (z-enemy)

IMPORTANT:
For maximum performance make sure you have latest drivers  (ver. 415+)
http://www.nvidia.com/Download/index.aspx

- First wave of performance optimizations for RTX 2080 and 2080Ti series up to 10-20% in various algos :(x16,x17,c11,hex,bitcore,xevan...)
- Minor performance optimizations for older cards (10x0)
- Fixed tribus out of memory bug (now it's possible to run it with higher intensities)
- Removed --tlimit and --plimit options
- Added --max-temp --resume-temp options @check #software or #z-enemy-123test

**Comment by RainbowMiner** [comment]
Thanks :) added.
