### ISSUE TITLE
Older Pi/Termux/userland/phone support(Enhancement)

### ISSUE THREAD

**Issue by RoyCRoderickIII** [RainbowMiner/RainbowMiner#2720]
purely as a Enhancement. Instead of attempting to run a full copy of RBM on a phone(which yes would be slow) I have been experimenting and trying various things all leads me back to the same answer. We need a RBM "lite" similar to client mode, only for older Pi's/phones. All it needs to be able to do is communicate with the server ability to change miners/algos, ability to save benchmark results could be on the server or client side doesn't really matter. There is no need for cpu/gpu detection because its honestly with the miners we already have for arm it will work or it wont,lol there is no inbetween. I have been toying with bendroids xxmrigCC, which is basically what solidified the answer for me. only problem with xmrigcc is it doesn't profit switch, and is limited to only xmrig algos.

Now i know, Pi's/phones do not have a high hashrate , have had this discussion over and over again ins discord, or even my Pi for instance utilizing that to mine.  but my same argument has before. i have 5-6 phones that can all do 300-500+h/s on randomx  that is  at minimum a extra 1.5  to 2k kh/s added to my mining effort for what? 4-5w a phone? that is  less then 1 kwh a week, Now admittedly if you power cost is higher then yes this does not make sense or even viable, however if you are in the below .15 cents kwh range it makes more sense. if you cant make .15 cents a week then your chasing the wrong coins. Now as a experiment i have a phone currently mining yada thanks to bendroid xmrigCC  i've let it go for the last 4 hours to stabilize, its going to average above 2 yada and change a day, with a earnings of .04 cents a day, cost me 12 cents a week to run it.... you show me a cpu/gpu that can achieve a profit margin that large. mind you that's pool mining 1 coin, throw the right hash rate in the right place at the right time (thanks to rbm) and that easily becomes more.

And here to solidify my argument to achieve according to xmrigs own benchmakrs 1.5kh your need a i5 3300
https://xmrig.com/benchmark?cpu=Intel%28R%29+Core%28TM%29+i5-3330+CPU+%40+3.00GHz
thats a 77w chip..... so in half the power same hashrate

**Comment by RainbowMiner** [comment]
Ok, I am thinking about this.

**Comment by RoyCRoderickIII** [comment]
So RetroMike has a youtube video on how to make this work as it is now, it does however have some errors/downsides. On install you need to run both RainbowMiner/install.sh AND sudo pwsh  ./Scripts/Install.ps1  after separately otherwise it wont work. Something about the way the powershell commands are called in the main install, just throws the command help prompt. Secondly on restart or dying of phones  you have to screen -wipe because the other screens are still present after restarting of userland. on the A03s he claimed in his video ScryptN2, RandomArq, and RandomX all crash the A03s, which i have verified. Which is very weird seeing both Randoms work fine simply running our Xmrig by itself. Even with the extended Swap space samsung has allowed turning the A03s up to 4GB. I currently have a A54g which allows for more benchmarking to see if maybe is just a ram limitation.
