### ISSUE TITLE
No longer reporting to dashboard 

### ISSUE THREAD

**Issue by bwstandard** [RainbowMiner/RainbowMiner#2724]
About an hour ago my miners stopped reporting to the miner monitoring central. Nothing has changed in forever so I'm unsure as to where to start looking.

**Comment by RainbowMiner** [comment]
We had our webserver moved. Everything should be back to normal, now.

**Comment by bwstandard** [comment]
Is there something I should be doing to make it appear? So far there has been no change since my original report.

**Comment by slappy6212** [comment]
Same for me all my windows 11 rigs marked as offline in pink and my Linux rig is ok running green.

**Comment by RainbowMiner** [comment]
That is strange - all of them should be green if running. I will check the server, just to be sure.

**Comment by bwstandard** [comment]
On winders 10. None of mine show on central

**Comment by RainbowMiner** [comment]
I have just fixed some binaries. After the move the attributes were wrong. So maybe that helps.
Could you send me your Miner Status Key by email to info@rbminer.net please?

**Comment by bwstandard** [comment]
Looks like it's working now. I will report back if it stops again.

**Comment by RainbowMiner** [comment]
Ah! Nice!

**Comment by slappy6212** [comment]
working now !
