### ISSUE TITLE
Suggestion to remove MiningPoolHub

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2725]
I strongly suggest that you remove MPH.

I have outstanding ETH balance (exceeding the pools payout threshold) for which I requested a payout a few weeks ago. 
But payment never happens and the balance is still visible in MPH balances. Re-triggering the payout does not work (message 'You already have one active manual payout request.')

I have contacted MPH support (Email: contact@miningpoolhub.com) several times, but the do not respond.

-> This is no longer a trustworthy pool.

**Comment by RainbowMiner** [comment]
Thank you for that report! That is too bad. I will try to contact the pool admins myself. If there is no response within 3 days I will remove the pool.

**Comment by jeromemorignot** [comment]
There is no longer any conversion available for MPH - I think the pool is completely dead
