### ISSUE TITLE
Rbminer.net not showing miner information (3.8.10.11)

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#273]
See picture, no miner info shown when expanding "pressing +"

![snip20181103_3](https://user-images.githubusercontent.com/35561346/47951548-75be6080-df62-11e8-8f04-5d25039e0804.png)

Link for testing: https://rbminer.net/monitoring/?user=fd5230d3-7d87-43d2-9c62-4b0ad24ed266

**Comment by ebojali** [comment]
Starter to work  now..

**Comment by RainbowMiner** [comment]
Strange, for me it does. Is this Chrome, you are using? Does the Chrome console report any Javascript errors?

**Comment by RainbowMiner** [comment]
Ok, I found and fixed it. Thank you for pointing at this.
