### ISSUE TITLE
newest bzminer 21.0.3 and warthog support

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2740]
Request for both...

**Comment by UselessGuru** [comment]
See https://github.com/RainbowMiner/RainbowMiner/issues/2744

**Comment by whitindllc** [comment]
so i tested this and couldnt get it to work... it might have something to do with bzminer... the algo is pobw but for some reason bzminer calls the algo wart

bzminer -a warthog -r test -w 0000 -p stratum+tcp://us.acc-pool.pw:12000 --nc 1 --nvidia 1 --amd 1 --warthog_cpu_threads 0 --warthog_max_ram_gb 0 --warthog_verus_hr_target 0
woolypooly uses 
stratum+tcp://pool.us.woolypooly.com:3140

**Comment by realsetvin** [comment]
> so i tested this and couldnt get it to work... it might have something to do with bzminer... the algo is pobw but for some reason bzminer calls the algo warthog
> 
> bzminer -a warthog -r test -w 0000 -p stratum+tcp://us.acc-pool.pw:12000 --nc 1 --nvidia 1 --amd 1 --warthog_cpu_threads 0 --warthog_max_ram_gb 0 --warthog_verus_hr_target 0 woolypooly uses stratum+tcp://pool.us.woolypooly.com:3140

To mine warthog you need to have a free CPU and a free GPU 

Using a 12 gpu rig with 1 intel cpu sweating is not going to work for warthog

It will require a special way for rainbowminer to handle this, as it will be considered a gpu miner and a cpu miner together.

it will require one of each hardware to operate.  

The cpu is based on verushash and the gpu is based on sha256 (so just pure core)

**Comment by whitindllc** [comment]
it works fine when you run Bzminer outside of RBM....  it doesnt work with RBM when setting either a focuswallet or pobw as only algo

**Comment by realsetvin** [comment]
> it works fine when you run Bzminer outside of RBM.... it doesnt work with RBM when setting either a focuswallet or pobw as only algo

probably due to the way rainbowminer works. I noticed even if you have only cpu or gpu selected, rainbowminer still pulls from both resources. He will need to make a fundamental change to the code to allow this work correctly.

**Comment by whitindllc** [comment]
the ship probably sailed on this coin.... the difficulty is through the roof on this one...
