### ISSUE TITLE
BZMiner 21.1.1 is available

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2744]
https://github.com/bzminer/bzminer/releases/tag/v21.1.1

**Comment by RainbowMiner** [comment]
So sorry, I am currently on crypto tour in South Korea, hence my time is a bit tight. Will add it now.

**Comment by realsetvin** [comment]
> So sorry, I am currently on crypto tour in South Korea, hence my time is a bit tight. Will add it now.

something to note concerning warthog, it will require special handling for rainbowminer as it requires 1 cpu and 1 gpu simultaneously to run. 

Hope you enjoyed the trip
