### ISSUE TITLE
Icemining stratum url changed

### ISSUE THREAD

**Issue by giannibonfanti** [RainbowMiner/RainbowMiner#275]
https://twitter.com/icemining/status/1058528177969094656

Please switch to http://stratum.icemining.ca  for all coins. Its an anycast dns which will pick a location near you

I actually have problem with old url

**Comment by RainbowMiner** [comment]
Yes, I know - I already changed the pool for the next release. In the meantime, download this zip and extract into your Pools folder:
[Icemining.zip](https://github.com/RainbowMiner/RainbowMiner/files/2546129/Icemining.zip)

**Comment by RainbowMiner** [comment]
Don't mind :) I just pushed a new release, containing this update.
