### ISSUE TITLE
odd fishhash error 

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2756]
driver error? Nanominer

2024-May-01 01:38:16: New job from us.ironfish.herominers.com:1145
2024-May-01 01:38:16: Could not make binaries for gfx1012
2024-May-01 01:38:16: Could not make binaries for gfx1012
2024-May-01 01:38:23: New job from us.ironfish.herominers.com:1145
2024-May-01 01:38:23: Could not make binaries for gfx1012
2024-May-01 01:38:23: Could not make binaries for gfx1012
2024-May-01 01:38:23: New job from us.ironfish.herominers.com:1145
2024-May-01 01:38:23: Could not make binaries for gfx1012
2024-May-01 01:38:23: Could not make binaries for gfx1012
2024-May-01 01:39:23: New job from us.ironfish.herominers.com:1145
2024-May-01 01:39:23: Could not make binaries for gfx1012
2024-May-01 01:39:23: Could not make binaries for gfx1012
2024-May-01 01:39:24: New job from us.ironfish.herominers.com:1145
2024-May-01 01:39:24: Could not make binaries for gfx1012
2024-May-01 01:39:24: Could not make binaries for gfx1012

**Comment by realsetvin** [comment]
https://github.com/nanopool/nanominer/issues/202

https://www.reddit.com/r/EtherMining/comments/rbfs15/could_not_make_binaries/

https://github.com/nanopool/nanominer/issues/355

try to reinstall. If that doesnt work you might not have enough memory to load the DAG

**Comment by RainbowMiner** [comment]
It looks like, nanominer doesn't support that GPU yet.

**Comment by whitindllc** [comment]
thats weird.... its a really old video card

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/ad465d3f-d9aa-4b52-aebf-cd7ea1345f40)

**Comment by whitindllc** [comment]
it appears there are others that work with fishhash so this can be closed
