### ISSUE TITLE
MinerRocks pools mining on wrong region

### ISSUE THREAD

**Issue by giannibonfanti** [RainbowMiner/RainbowMiner#276]
In my config file I have "eu" region, but Asia host url is always chosen instead of eu.

sg.stellite.miner.rocks is chosen on MinerRocks stellite instead of sg.stellite.miner.rocks

And in all pools page, the algo is listed twice but on both entries I find always asia region.

**Comment by RainbowMiner** [comment]
Ok, I will have a look.

**Comment by RainbowMiner** [comment]
Fixed. I also added multi port support, so that different ports CPU/GPU mining are used.
