### ISSUE TITLE
 API problem!

### ISSUE THREAD

**Issue by MTCHANNELL** [RainbowMiner/RainbowMiner#2761]
Hello. I cannot see the accumulated data in the ravenminer pool in "rbm". It doesn't show any errors. mining continues without any problems. I just can't see the gains. I have to check it on their website. I would be grateful if you could contact me at the appropriate time.

**Comment by realsetvin** [comment]
when you go to their website and put in your ravencoin address, do you see anything?

**Comment by MTCHANNELL** [comment]
I can see all the details on the site. But I guess ravenminer.com doesn't have API support. but there is no need for this anymore. I managed to get "balance" with python without api. Problem solved.
