### ISSUE TITLE
GLIBC_PRIVATE symbol not found error in TBMiner

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2773]
When running TBMiner with RainbowMiner, I encountered the following error:

```/home/user/RainbowMiner/Bin/GPU-Teamblack/TBMiner: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found```

My system uses glibc version 2.38. The issue appears to be related to an older version of the C library used by RainbowMiner or something. idk, please reach out if you'd like remote access

**Comment by RainbowMiner** [comment]
This is most likely a library the TTminer needs. I will contact the dev.

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
