### ISSUE TITLE
k1 pool setup

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2777]
messing around with the new release... noticed k1 was added.... where do put in your wallet.... K1 uses a wallet structure similar to gtpool

    Account_Id or wallet id.... since its got the ability to auto switch

**Comment by RainbowMiner** [comment]
Currently, our K1pool module does not support the pool's autoswitch feature. You have to decide which coins to mine: set the coin's to your "K1..." mining wallet.
e.g.
```
"XEL": "K1...",
...
```

**Comment by whitindllc** [comment]
so its not like zpool and zergpool? 

Also depending on the algo there is a bot on their dashboard that can be turned on
for instance if you setup KAS you can go into the dashboard and turn on the auto switching bot....

I will play with it more tonight

**Comment by whitindllc** [comment]
the K1 setup here will work with a focuswallet .... however you need to setup the front end coins that can autoswitch and then set the focus wallet to just that algo via that coin.... for instance... setup a wallet for KAS which is the same wallet as the other ones... 

focus it to kas and then go into the k1 autoswitch and let the bot choose
