### ISSUE TITLE
NVIDIA-YesCrypt Ccminer issues

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2780]
I've been spending some extra time looking at things lately, and I'm having a lot of issues that I've been overlooking for who knows how long. I'm sorry for the many recent issues/commits/PRs.

I'm focusing on running the latest drivers (525), the latest Ubuntu OS (24.04 LTS), and the latest RBM. I'm getting a lot of failures lately.

running manually:
```
user@RDRIG10:~/RainbowMiner/Bin/NVIDIA-YesCrypt$ ./start_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05_gpu06_zergpool_yescrypt.sh
/home/user/RainbowMiner/Bin/NVIDIA-YesCrypt/ccminer: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
```

Logs:
```
/home/user/RainbowMiner/Bin/NVIDIA-YesCrypt/ccminer: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
```

So, it seems it's the same error again and again I have the package `libldap-common` installed via apt but i think ccminer isnt looking for that, i think it's looking for a file in /opt/rainbowminer/lib that i don't have. 

I only have these files in that folder: 

```
$ ls /opt/rainbowminer/lib
libOpenCL.so           libcudart.so.12.2.140          libnvrtc-builtins.so.11.1      libnvrtc.so.11.1.105
libOpenCL.so.1         libcudart.so.8.0               libnvrtc-builtins.so.11.1.105  libnvrtc.so.11.2
libOpenCL.so.1.2       libcudart.so.8.0.61            libnvrtc-builtins.so.11.2      libnvrtc.so.11.2.152
libcrypto.so.1.1       libcudart.so.9.0               libnvrtc-builtins.so.11.2.152  libnvrtc.so.11.3
libcudart.so           libcudart.so.9.0.176           libnvrtc-builtins.so.11.3      libnvrtc.so.11.3.109
libcudart.so.10.0      libcudart.so.9.1               libnvrtc-builtins.so.11.3.109  libnvrtc.so.11.4
libcudart.so.10.0.130  libcudart.so.9.1.85            libnvrtc-builtins.so.11.4      libnvrtc.so.11.4.152
libcudart.so.10.1      libcudart.so.9.2               libnvrtc-builtins.so.11.4.152  libnvrtc.so.11.5
libcudart.so.10.1.243  libcudart.so.9.2.148           libnvrtc-builtins.so.11.5      libnvrtc.so.11.5.119
libcudart.so.10.2      libcurl-nss.so.3               libnvrtc-builtins.so.11.5.119  libnvrtc.so.11.6
libcudart.so.10.2.89   libcurl-nss.so.4               libnvrtc-builtins.so.11.6      libnvrtc.so.11.6.124
libcudart.so.11.0      libcurl-nss.so.4.5.0           libnvrtc-builtins.so.11.6.124  libnvrtc.so.11.7
libcudart.so.11.0.221  libcurl.so.3                   libnvrtc-builtins.so.11.7      libnvrtc.so.11.7.99
libcudart.so.11.1      libcurl.so.3.0.0               libnvrtc-builtins.so.11.7.99   libnvrtc.so.11.8
libcudart.so.11.1.74   libhwloc.so.5                  libnvrtc-builtins.so.11.8      libnvrtc.so.11.8.89
libcudart.so.11.2      libhwloc.so.5.6.8              libnvrtc-builtins.so.11.8.89   libnvrtc.so.12.0
libcudart.so.11.2.152  libjansson.so.4                libnvrtc-builtins.so.12.0      libnvrtc.so.12.0.140
libcudart.so.11.3      libjansson.so.4.11.0           libnvrtc-builtins.so.12.0.140  libnvrtc.so.12.1
libcudart.so.11.3.109  libmicrohttpd.so.10            libnvrtc-builtins.so.12.1      libnvrtc.so.12.1.105
libcudart.so.11.4      libmicrohttpd.so.10.34.0       libnvrtc-builtins.so.12.1.105  libnvrtc.so.12.2
libcudart.so.11.4.148  libncurses.so.5                libnvrtc-builtins.so.12.2      libnvrtc.so.12.2.140
libcudart.so.11.5      libncurses.so.5.9              libnvrtc-builtins.so.12.2.140  libnvrtc.so.9.0
libcudart.so.11.5.117  libnspr4.so                    libnvrtc-builtins.so.9.2       libnvrtc.so.9.0.176
libcudart.so.11.6      libnss3.so                     libnvrtc-builtins.so.9.2.148   libnvrtc.so.9.1
libcudart.so.11.6.55   libnssutil3.so                 libnvrtc.so                    libnvrtc.so.9.1.xxx
libcudart.so.11.7      libnvrtc-builtins.so           libnvrtc.so.10.0               libnvrtc.so.9.2
libcudart.so.11.7.99   libnvrtc-builtins.so.10.0      libnvrtc.so.10.0.130           libnvrtc.so.9.2.148
libcudart.so.11.8      libnvrtc-builtins.so.10.0.130  libnvrtc.so.10.1               libplc4.so
libcudart.so.11.8.89   libnvrtc-builtins.so.10.1      libnvrtc.so.10.1.243           libplds4.so
libcudart.so.12.0      libnvrtc-builtins.so.10.1.243  libnvrtc.so.10.2               libssl.so.1.1
libcudart.so.12.0.146  libnvrtc-builtins.so.10.2      libnvrtc.so.10.2.89            libssl3.so
libcudart.so.12.1      libnvrtc-builtins.so.10.2.89   libnvrtc.so.11.0
libcudart.so.12.1.105  libnvrtc-builtins.so.11.0      libnvrtc.so.11.0.221
libcudart.so.12.2      libnvrtc-builtins.so.11.0.221  libnvrtc.so.11.1
```

**Comment by RainbowMiner** [comment]
Since Ubunutu 20 the library has been updated to v2.5. I have added the old library v2.4 to our own lib repo.

**Comment by Nickfost** [comment]
> we continue with more missing libraries
> 
> ```
> /home/user/RainbowMiner/Bin/NVIDIA-YesCryptR8/ccminer: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> ```

same one two diff miners 

```
/home/user/RainbowMiner/Bin/NVIDIA-CcminerSha3d/ccminer: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

reason I'm running into this is I have to disable these miners. 

you don't seem to have logic for disabling the miner if the fastlane benchmark says we have a h/s 

normally without fastlane bench these just report 0h/s 

my 2 sats

**Comment by Nickfost** [comment]
/home/user/RainbowMiner/Bin/GPU-Teamblack/TBMiner: error while loading shared libraries: libnvrtc.so.12: cannot open shared object file: No such file or directory

**Comment by Nickfost** [comment]
/home/user/RainbowMiner/Bin/NVIDIA-YesCryptR8/ccminer: error while loading shared libraries: libgssapi.so.3: cannot open shared object file: No such file or directory

**Comment by Nickfost** [comment]
Unsure why this one is crashing, just turning it back off until next round up updates 

[CcminerKlausT-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-14000_2024-05-31_15-04-18.txt](https://github.com/user-attachments/files/15518799/CcminerKlausT-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-14000_2024-05-31_15-04-18.txt)
[CcminerKlausT-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-14000_2024-05-31_19-44-44.txt](https://github.com/user-attachments/files/15518800/CcminerKlausT-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-14000_2024-05-31_19-44-44.txt)
[CcminerKlausT-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-14000_2024-05-31_19-49-26.txt](https://github.com/user-attachments/files/15518801/CcminerKlausT-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-14000_2024-05-31_19-49-26.txt)
[CcminerKlausT-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-14000_2024-05-31_21-00-53.txt](https://github.com/user-attachments/files/15518802/CcminerKlausT-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-14000_2024-05-31_21-00-53.txt)

**Comment by Nickfost** [comment]
Miniz Seems to bug out too, unsure why either 
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_20-44-20.txt](https://github.com/user-attachments/files/15518811/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_20-44-20.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33020_2024-05-31_15-28-16.txt](https://github.com/user-attachments/files/15518812/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33020_2024-05-31_15-28-16.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33020_2024-05-31_19-46-41.txt](https://github.com/user-attachments/files/15518813/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33020_2024-05-31_19-46-41.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33020_2024-05-31_20-15-10.txt](https://github.com/user-attachments/files/15518814/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33020_2024-05-31_20-15-10.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33020_2024-05-31_20-16-50.txt](https://github.com/user-attachments/files/15518815/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33020_2024-05-31_20-16-50.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33020_2024-05-31_20-43-29.txt](https://github.com/user-attachments/files/15518816/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33020_2024-05-31_20-43-29.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33020_2024-05-31_20-45-09.txt](https://github.com/user-attachments/files/15518817/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33020_2024-05-31_20-45-09.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_15-18-44.txt](https://github.com/user-attachments/files/15518818/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_15-18-44.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_15-23-59.txt](https://github.com/user-attachments/files/15518819/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_15-23-59.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_15-37-53.txt](https://github.com/user-attachments/files/15518820/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_15-37-53.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_19-46-00.txt](https://github.com/user-attachments/files/15518821/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_19-46-00.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_19-47-27.txt](https://github.com/user-attachments/files/15518822/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_19-47-27.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_20-14-21.txt](https://github.com/user-attachments/files/15518823/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_20-14-21.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_20-16-01.txt](https://github.com/user-attachments/files/15518824/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_20-16-01.txt)
[MiniZ-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-33000_2024-05-31_20-42-43.txt](https://github.com/user-attachments/files/15518825/MiniZ-GPU.00-GPU.01-GPU.02-GPU.03-GPU.04-GPU.05-GPU.06-33000_2024-05-31_20-42-43.txt)

**Comment by RainbowMiner** [comment]
Thank you! 
The TTminer and Ccminer are missing some libraries. The CcminerKlausT and MiniZ fail with memory fault after some time. That indicates either too far stretched memory  over locking or hardware failure (heat?)

**Comment by sfalas01** [comment]
> Thank you! The TTminer and Ccminer are missing some libraries. The CcminerKlausT and MiniZ fail with memory fault after some time. That indicates either too far stretched memory over clocking or hardware failure (heat?)

What about CcminerYesCrypt (and variants) not working for ZergPool?

**Comment by Nickfost** [comment]
/home/user/RainbowMiner/Bin/NVIDIA-YesCryptR8/ccminer: error while loading shared libraries: libgssapi.so.3: cannot open shared object file: No such file or directory

**Comment by Nickfost** [comment]
> > Thank you! The TTminer and Ccminer are missing some libraries. The CcminerKlausT and MiniZ fail with memory fault after some time. That indicates either too far stretched memory over clocking or hardware failure (heat?)
> 
> What about CcminerYesCrypt (and variants) not working for ZergPool?

you might try turning off ssl i noticed some funkiness with zerg + ssl

**Comment by Nickfost** [comment]
/home/user/RainbowMiner/Bin/GPU-Teamblack/TBMiner: error while loading shared libraries: libnvrtc.so.12: cannot open shared object file: No such file or directory

**Comment by Nickfost** [comment]
/home/user/RainbowMiner/Bin/NVIDIA-CcminerSha3d/ccminer: /lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/user/RainbowMiner/Bin/NVIDIA-CcminerSha3d/ccminer)

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
