### ISSUE TITLE
hashcryptos randomx

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2787]
algo in pools.config doesnt seem to mine to it

**Comment by Nickfost** [comment]
Can you upload your debug file?

**Comment by whitindllc** [comment]
I dont understand what you are asking

im saying if you go into the pools config and tell it focus on that algorithm it just ignores it

**Comment by Nickfost** [comment]
On the web panel, there's a link on the sidebar that says debug file, click it, a zip file should download, upload it here.

**Comment by RoyCRoderickIII** [comment]
did you enable the wallet/algo on hashcryptos as well?  just adding it to RBM wont work, you need to setup say mine randomx to my randomx wallet, then both the algo and wallet are activated with hash. then you just need to say do the same for whatever other payouts/algos you want. and it can switch back and forth between them

**Comment by whitindllc** [comment]
wait I'm a bit confused.... its this an AE pool like Zpool,zergpool, unmineable and mining dutch?... you tell it your BTC address and it mines whatever and converts it? it mined yespower and yescryptr32 on its own.... however other algos i told it to mine it just ignored...

**Comment by RoyCRoderickIII** [comment]
Yes, you setup the wallet  for what you want to be paid in, but remember
RBM is about profit , LTC has been stable. Doge has been up and down
.03-.04 cents so BTC right now for payouts would be the most profitable.

**Comment by sfalas01** [comment]
> On the web panel, there's a link on the sidebar that says debug file, click it, a zip file should download, upload it here.

Not sure if this is a thing but it's probably automatically excluded as non-profitable because the pools has relatively low hashrate and may take a couple of days to find a block.

**Comment by whitindllc** [comment]
weird... seeing that the pool is reporting its profitable on their website

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/8a402449-7396-46d1-9f58-f8fd9089c48a)

**Comment by whitindllc** [comment]
actually now that i look at it this whole thing looks odd.... 

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/2085801e-ff8e-409e-b2b8-35268aad097a)

**Comment by sfalas01** [comment]
> actually now that i look at it this whole thing looks odd....
> 
> ![image](https://private-user-images.githubusercontent.com/128111946/334359412-2085801e-ff8e-409e-b2b8-35268aad097a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTY2MDYsIm5iZiI6MTcxNjg5NjMwNiwicGF0aCI6Ii8xMjgxMTE5NDYvMzM0MzU5NDEyLTIwODU4MDFlLWZmOGUtNDA5ZS1iMmI4LTM1MjY4YWFkMDk3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMTM4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjE4YWNmNDc0YjUwZmM0Y2Y0ZTllZDYyZTFiNjJiNDk0MTY2NzQyZWY5YTcwOTM2M2E5NzlmMWRiN2ZmYzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d1xOTQW1PrFYXHh1o9Vsz_q41dhFBIYxnsiQEav6aF0)

Yep, it's pretty different from what they are showing on their website. Maybe an API parsing issue?

**Comment by whitindllc** [comment]
RBM is only programmed for certain algos for this pool.... thats why the focus wallet for others dont work 

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/85c2c655-2914-4fd1-9211-044df19aa060)

**Comment by whitindllc** [comment]
hashcryptos is dead on RBM.... closing out...
