### ISSUE TITLE
Solopool dropped a new coin called xel on may 28th 2024

### ISSUE THREAD

**Issue by Faty100** [RainbowMiner/RainbowMiner#2791]
https://xel.solopool.org/

Please add to rainbowminer

Thank you : )

**Comment by RainbowMiner** [comment]
XEL should arrive automatically. The Solopool has full API integration with RainbowMiner. So just add your Xelis wallet into XEL and off you go. Either use the http://localhost:4000 pools/coins setup or edit coins.config.txt and pools.config.txt.

**Comment by Faty100** [comment]
I already tried it before I messaged you but I will try again.

Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Faty100** [comment]
I tried again just a few mins ago still not working.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by whitindllc** [comment]
> XEL should arrive automatically. The Solopool has full API integration with RainbowMiner. So just add your Xelis wallet into XEL and off you go. Either use the http://localhost:4000 pools/coins setup or edit coins.config.txt and pools.config.txt.

What other pool do?

**Comment by Faty100** [comment]
This is still not working

**Comment by RainbowMiner** [comment]
Huh. It should - I will try on one of my machines. We will get this fixed.

**Comment by Faty100** [comment]
Looks like I did not have autocoin selected it seems to be working now after i selected it.
