### ISSUE TITLE
Moneroocean suspended from mining

### ISSUE THREAD

**Issue by YastrebX** [RainbowMiner/RainbowMiner#2796]
Hello!
I have the issue with moneroocean pool.
From log:
 * POOL      stratum+ssl://gulf.moneroocean.stream:20032 algo flex
 * COMMANDS     hashrate, pause, resume, results, connection
 * HTTP API     127.0.0.1:30300 
 * OPENCL       disabled
 * CUDA         disabled
[2024-06-04 17:53:49.495]  net      stratum+ssl://gulf.moneroocean.stream:20032 error: "New connections from this IP address are temporarily suspended from mining (10 minutes max)", code: -1
[2024-06-04 17:53:49.495]  net      stratum+ssl://gulf.moneroocean.stream:20032 read error: "end of file"

I think the reason is using low difficulty port for old cpu/gpu. On moneroocean settings page:
Port descriptions:
    10032: Old CPU/GPU
    10128: Modern CPU/GPU
    18192: CPU/GPU farm
    20128: SSL/TLS
    10001: Very old CPU (1000 diff)

It would be better to change default port to 10128 and 20128 for ssl

**Comment by whitindllc** [comment]
is that why i went from mining there for 4 months straight to never mining there again?

**Comment by RainbowMiner** [comment]
> is that why i went from mining there for 4 months straight to never mining there again?

I don't think so. Others are just more profitable, currently.

**Comment by whitindllc** [comment]
> > is that why i went from mining there for 4 months straight to never mining there again?
> 
> I don't think so. Others are just more profitable, currently.

whatever fix was put in may have messed up a decibel point or two

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/d6efd4ab-c9b3-4cea-b423-dd7ab5064637)
