### ISSUE TITLE
epiccash when did we get access to 51pool

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2801]
saw this on the monitoring site today

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/22c5b5d0-96a1-4294-ba94-c6354cab21f1)

**Comment by RainbowMiner** [comment]
Not yet - that must be some rigs that have 51pool in their userpools.config.txt.

**Comment by whitindllc** [comment]
36% all of the miners using RBM are mining EPIC... thats a good chunk...
