### ISSUE TITLE
revert epic to 2.4.7 of srb

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2803]
chatting with some of the ppl in the interwebs world... it appears epic is way more stable on 2.4.7 of srb and i think we are using 2.5.6 and it crashes a TON ... note this is on the CPU side.... however the GPU side is buggy as well...

**Comment by RainbowMiner** [comment]
Thank you for the hint. I will try and compare.

**Comment by UselessGuru** [comment]
I cannot see any issues with CPU mining wirh the new 2.5.7 version.
Note that there is a updated version available:

https://discord.com/channels/629564842826792970/632442648434835456/1250893752872996884

**Comment by RainbowMiner** [comment]
> Note that there is a updated version of 2.5.7 available:
> 
> https://discord.com/channels/629564842826792970/632442648434835456/1250893752872996884
> 
> I cannot see any issues with CPU mining with that new version.

On older CPU it just start - and then stops. No mining, where the former version works fine. I prefer to wait for an update :)

**Comment by whitindllc** [comment]
So the mining operator says that only 48% can be mined on CPU... which seems odd because his own site reports how many blocks on the network are found with both the randomx derivative and the progpow one... and its not even close in the 24 hour period

![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/8d07dc41-12e3-4169-95b6-c3d352180056)

**Comment by whitindllc** [comment]
> > Note that there is a updated version of 2.5.7 available:
> > https://discord.com/channels/629564842826792970/632442648434835456/1250893752872996884
> > I cannot see any issues with CPU mining with that new version.
> 
> On older CPU it just start - and then stops. No mining, where the former version works fine. I prefer to wait for an update :)

might be this ? not sure if epic applies since it uses randomx


    To achieve better results on algorithms 'ghostrider' and 'mike', don't manually set number of threads or affinity.
    If your hashrate on algorithm 'flex' is lower than in previous version of SRBMiner, set '--cpu-threads' parameter manually to the number that was used in previous version
    All ghostrider based algorithms ('ghostrider', 'mike' and 'flex') now require minimum a CPU with SSE4.2 and HW AES support

**Comment by whitindllc** [comment]
closed
