### ISSUE TITLE
MeowPowMiner Missing libcudart.so.12

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2804]
/home/user/RainbowMiner/Bin/NVIDIA-MeowPow/meowpowminer: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory

**Comment by RainbowMiner** [comment]
Same like TTminer: https://github.com/RainbowMiner/RainbowMiner/issues/2805#issuecomment-2173286808
