### ISSUE TITLE
Teamblack missing libnvrtc.so.12

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2805]
/home/user/RainbowMiner/Bin/GPU-Teamblack/TBMiner: error while loading shared libraries: libnvrtc.so.12: cannot open shared object file: No such file or directory

**Comment by RainbowMiner** [comment]
Please let me know, if the last commit helps with the problem. If not, we may need the CUDA libs inside the folder of the executable.
After a restart of RainbowMiner, the `libnvrtc.so.12` should be in `/opt/rainbowminer/lib` - please have look there:
`ls -la /opt/rainbowminer/lib/*.12`

**Comment by Nickfost** [comment]
repulling and retesting

**Comment by Nickfost** [comment]
/home/user/RainbowMiner/Bin/GPU-Teamblack/TBMiner: error while loading shared libraries: libnvrtc.so.12: cannot open shared object file: No such file or directory

**Comment by Nickfost** [comment]
`user@RDRIG10:~$ ls -la /opt/rainbowminer/lib/*.12
-rw-r--r-- 1 root root  63888 Jun 17 15:19 /opt/rainbowminer/lib/liblber-2.4.so.2.10.12
-rw-r--r-- 1 root root 339472 Jun 17 15:19 /opt/rainbowminer/lib/libldap_r-2.4.so.2.10.12
user@RDRIG10:~$`

**Comment by Nickfost** [comment]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/1572453/f050debb-14d9-47d6-8baa-200d5c3f9246)

**Comment by Nickfost** [comment]
you can see there are 



lrwxrwxrwx 1 root root       43 Jun 17 15:20 /opt/rainbowminer/lib/libcudart.so.12.0 -> /opt/rainbowminer/lib/libcudart.so.12.0.146
-rw-r--r-- 1 root root   675168 Jun 17 15:19 /opt/rainbowminer/lib/libcudart.so.12.0.146
lrwxrwxrwx 1 root root       43 Jun 17 15:20 /opt/rainbowminer/lib/libcudart.so.12.1 -> /opt/rainbowminer/lib/libcudart.so.12.1.105
-rw-r--r-- 1 root root   679264 Jun 17 15:19 /opt/rainbowminer/lib/libcudart.so.12.1.105
lrwxrwxrwx 1 root root       43 Jun 17 15:20 /opt/rainbowminer/lib/libcudart.so.12.2 -> /opt/rainbowminer/lib/libcudart.so.12.2.140
-rw-r--r-- 1 root root   683360 Jun 17 15:19 /opt/rainbowminer/lib/libcudart.so.12.2.140
lrwxrwxrwx 1 root root       43 Jun 17 15:20 /opt/rainbowminer/lib/libcudart.so.12.3 -> /opt/rainbowminer/lib/libcudart.so.12.3.101
-rw-r--r-- 1 root root   703808 Jun 17 15:19 /opt/rainbowminer/lib/libcudart.so.12.3.101
lrwxrwxrwx 1 root root       43 Jun 17 15:20 /opt/rainbowminer/lib/libcudart.so.12.4 -> /opt/rainbowminer/lib/libcudart.so.12.4.127
-rw-r--r-- 1 root root   707904 Jun 17 15:19 /opt/rainbowminer/lib/libcudart.so.12.4.127
lrwxrwxrwx 1 root root       42 Jun 17 15:20 /opt/rainbowminer/lib/libcudart.so.12.5 -> /opt/rainbowminer/lib/libcudart.so.12.5.39
-rw-r--r-- 1 root root   712032 Jun 17 15:19 /opt/rainbowminer/lib/libcudart.so.12.5.39
-rw-r--r-- 1 root root    63888 Jun 17 15:19 /opt/rainbowminer/lib/liblber-2.4.so.2.10.12
-rw-r--r-- 1 root root   339472 Jun 17 15:19 /opt/rainbowminer/lib/libldap_r-2.4.so.2.10.12
-rw-r--r-- 1 root root  7026568 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc-builtins.so.11.6.124
lrwxrwxrwx 1 root root       51 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.0 -> /opt/rainbowminer/lib/libnvrtc-builtins.so.12.0.140
-rw-r--r-- 1 root root  6825864 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.0.140
lrwxrwxrwx 1 root root       51 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.1 -> /opt/rainbowminer/lib/libnvrtc-builtins.so.12.1.105
-rw-r--r-- 1 root root  6842248 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.1.105
lrwxrwxrwx 1 root root       51 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.2 -> /opt/rainbowminer/lib/libnvrtc-builtins.so.12.2.140
-rw-r--r-- 1 root root  2434952 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.2.140
lrwxrwxrwx 1 root root       51 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.3 -> /opt/rainbowminer/lib/libnvrtc-builtins.so.12.3.107
-rw-r--r-- 1 root root  6662024 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.3.107
lrwxrwxrwx 1 root root       51 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.4 -> /opt/rainbowminer/lib/libnvrtc-builtins.so.12.4.127
-rw-r--r-- 1 root root  5343112 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.4.127
lrwxrwxrwx 1 root root       50 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.5 -> /opt/rainbowminer/lib/libnvrtc-builtins.so.12.5.40
-rw-r--r-- 1 root root  5330824 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc-builtins.so.12.5.40
-rw-r--r-- 1 root root 45355984 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc.so.11.6.124
lrwxrwxrwx 1 root root       42 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc.so.12.0 -> /opt/rainbowminer/lib/libnvrtc.so.12.0.140
-rw-r--r-- 1 root root 55684176 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc.so.12.0.140
lrwxrwxrwx 1 root root       42 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc.so.12.1 -> /opt/rainbowminer/lib/libnvrtc.so.12.1.105
-rw-r--r-- 1 root root 56864848 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc.so.12.1.105
lrwxrwxrwx 1 root root       42 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc.so.12.2 -> /opt/rainbowminer/lib/libnvrtc.so.12.2.140
-rw-r--r-- 1 root root 58041000 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc.so.12.2.140
lrwxrwxrwx 1 root root       42 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc.so.12.3 -> /opt/rainbowminer/lib/libnvrtc.so.12.3.107
-rw-r--r-- 1 root root 60792048 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc.so.12.3.107
lrwxrwxrwx 1 root root       42 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc.so.12.4 -> /opt/rainbowminer/lib/libnvrtc.so.12.4.127
-rw-r--r-- 1 root root 60409520 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc.so.12.4.127
lrwxrwxrwx 1 root root       41 Jun 17 15:20 /opt/rainbowminer/lib/libnvrtc.so.12.5 -> /opt/rainbowminer/lib/libnvrtc.so.12.5.40
-rw-r--r-- 1 root root 61401616 Jun 17 15:19 /opt/rainbowminer/lib/libnvrtc.so.12.5.40

**Comment by Nickfost** [comment]
while there is not libnvrtc.so.12 present there is libnvrtc.so.12.0, libnvrtc.so.12.1 libnvrtc.so.12.2 libnvrtc.so.12.3 libnvrtc.so.12.4 and libnvrtc.so.12.5 present

**Comment by RainbowMiner** [comment]
Thank you very much for the file list. That's weird. It should have created main version links for each visa generation at startup. Could you please restart Rainbowminer on one of these machines and then create and upload a Debug file?

**Comment by Nickfost** [comment]
Sorry i was gone for a bit, pulling and retesting now

**Comment by Nickfost** [comment]
/home/user/RainbowMiner/Bin/GPU-Teamblack/TBMiner: error while loading shared libraries: libnvrtc.so.12: cannot open shared object file: No such file or directory

**Comment by Nickfost** [comment]
@RainbowMiner 
[debug_2024-07-07.zip](https://github.com/user-attachments/files/16121432/debug_2024-07-07.zip)

**Comment by Nickfost** [comment]
/home/user/RainbowMiner/Bin/NVIDIA-CcminerAllium/ccminer: /lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/user/RainbowMiner/Bin/NVIDIA-CcminerAllium/ccminer)

**Comment by Nickfost** [comment]
continuing on #2868
