### ISSUE TITLE
SgminerFancyIX Prerequisite and More Time to Benchmark

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#281]
I have been wondering why FancyIX was failing on benchmarking so I went to the github and found out that openssl needs to be installed for Windows.  The link is here https://github.com/fancyIX/sgminer-phi2-branch/releases  

It benchmarks now but it may need more time to get a more realistic speed.  x22i was still rising in speed when it switched to another algo.  It was not even half the speed of WildRig.

**Comment by RainbowMiner** [comment]
Ok, good to know. I will add the prerequisites plus an extended benchmark time.

**Comment by jch9678** [comment]
The developer also mentions 2 threads may be needed.  Maybe you want to add that in benchmarks??

**Comment by RainbowMiner** [comment]
I changed the default settings. These are fixed defaults (just look at the commandline in console window). If you want to override these, edit miners.config.txt, find the miner+device+algorithm and enter your own values in field Params. Use of the exact same commandline parameter writing overrides the fixed defaults.
This is common for all Sgminer.

**Comment by jch9678** [comment]
👍 yeah it's different than srbminer, which by the way made new configs when it recently updated.  The new ones caused my machine to crash upon switching algos.  I updated thew new configs and all is good.
