### ISSUE TITLE
TTminer - Takes big amount of disk space

### ISSUE THREAD

**Issue by sfalas01** [RainbowMiner/RainbowMiner#2810]
As you can see, TTminer saves a lot of DAG files on disks that do add up over time.
![image](https://github.com/RainbowMiner/RainbowMiner/assets/22576563/daa20b9c-29ad-41ce-a188-f2f319c090e8)
At some point the TTminers' folders were close to 130GB and I had to manually delete some of them.

**Comment by whitindllc** [comment]
its the dag file.... dev put a solution to this in another issue you need to edit one of the files and and ad ... somewhere.... it will stop it from creating the dag files.... i havent tried it yet though

**Comment by UselessGuru** [comment]
> dev put a solution to this in another issue you need to edit one of the files and and ad ... somewhere.... it will stop it from creating the dag files.... i havent tried it yet though

See https://github.com/RainbowMiner/RainbowMiner/issues/2755#issuecomment-2103192311
