### ISSUE TITLE
OpenCL error

### ISSUE THREAD

**Issue by rhadamants** [RainbowMiner/RainbowMiner#282]
In new versions of Windows 10 OpenCL.dll is only found in the SysWOW64 directory. RainbowMiner needs this DLL in the Win32 directory. This causes error when detecting VGA devices.

**Comment by RainbowMiner** [comment]
Thank you! Did you get any error message?

**Comment by rhadamants** [comment]
OpenCL device detection has failed: Exceção ao chamar "GetPlatformIDs" com "0" argumento(s): "Não é possível carregar a DLL 'OpenCL': Não foi possível encontrar o módulo
especificado. (Exceção de HRESULT: 0x8007007E)"

Copying an OpenCL.dll from the System32 directory of old versions of windows 10 back to detecting the VGA. This is not a problem with the VGA driver. It is just this OpenCL.dll in the System32 directory. The new versions of windows 10 this OpenCL.dll is only in the SysWOW64 directory.

**Comment by RainbowMiner** [comment]
Thanks again for this valuable hint. I consider including some fallback opencl.dll.
