### ISSUE TITLE
Balance View general question

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#2821]
![image](https://github.com/RainbowMiner/RainbowMiner/assets/4724631/dfefec55-842a-4564-bb4b-9ea0bb6cd7ae)

I really only need to see the balance information in blue. The information in red I dont need to see and as I look at it, its not even showing correct information. Is there a way to shut the wallet part off?

**Comment by RoyCRoderickIII** [comment]
Go into config in json editor, to show  walletbalances is able to be turned off.

**Comment by Yamanipanuchi** [comment]
Yup that worked... I had nothing in the variable.
