### ISSUE TITLE
can we dual zil mine

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2827]
without actually creating a userpool for it?

**Comment by RainbowMiner** [comment]
Yes - easy way is adding pool Crazypool to your config.txt and adding ZIL address to Crazypool in pools.config.txt. Finally check, if the miners are enabled in the Crazypool section in pools.config.txt:

```
    "EnableMiniZDual": "1",
    "EnableSrbminerMultiDual": "1",
    "EnableTTminerDual": "1",
    "EnableRigelDual": "1",
    "EnableGminerDual": "1",
    "EnableBzminerDual": "1",
    "EnableOneZeroMinerDual": "1"
```

**Comment by whitindllc** [comment]
can you add this to any pool with zil mining or just crazy pool?

**Comment by whitindllc** [comment]
i added a zil address to crazy pool and enabled it... nothing happened

**Comment by RainbowMiner** [comment]
> can you add this to any pool with zil mining or just crazy pool?

It is currently Crazypool, only.

**Comment by whitindllc** [comment]
[debug_2024-07-24.zip](https://github.com/user-attachments/files/16360168/debug_2024-07-24.zip)

**Comment by whitindllc** [comment]
so i rebenched ethash and all of the did the same thing until i got to bzminer

![image](https://github.com/user-attachments/assets/9281d348-a68e-4d25-920c-55e48e50aae1)

**Comment by RainbowMiner** [comment]
Actually, looks good: SrbminerMulti is also using crazypool, as far as I can see. I think, everything is fine.

```
Bin\ANY-SRBMinerMulti\SRBMiner-MULTI.exe --algorithm ethash --gpu-id 0,1 --pool ethash.mine.zergpool.com:19999 --wallet XXX --password c=BTC,ID=NSM1 --tls true --nicehash false --zil-enable --zil-pool us.crazypool.org:5005 --zil-wallet XXX.NSM1 --zil-esm 2 --retry-time 10 --disable-startup-monitor --disable-cpu --disable-gpu-nvidia --disable-gpu-intel --api-enable --api-port 34900 --api-rig-name NSM1
```

**Comment by whitindllc** [comment]
resolved
