### ISSUE TITLE
fee's disapperaed

### ISSUE THREAD

**Issue by truckinCowboy** [RainbowMiner/RainbowMiner#2829]
the miner fees disappeared is there a way to reset that?

**Comment by truckinCowboy** [comment]
also i have now caught rainbow mining to nicehash for the second time without me selecting it to i have no ideas who account.

**Comment by whitindllc** [comment]
> also i have now caught rainbow mining to nicehash for the second time without me selecting it to i have no ideas who account.

its the def mining... the fee... its a few mins a day.... you should watch what it mines... that might be where the money is at

**Comment by truckinCowboy** [comment]
> > also i have now caught rainbow mining to nicehash for the second time without me selecting it to i have no ideas who account.
> 
> its the developer mining...its the fee to use the program... all of them have it...... its a few mins a day.... you should watch what it mines... that might be where the money is at

ahh i see thanks for the answer 
now just need to figure out how to reset the miner fees so i can adjust miners i want to use accordingly. hopefully without reinstalling the whole thing as it takes so long to benchmark everything.

**Comment by whitindllc** [comment]
> > > also i have now caught rainbow mining to nicehash for the second time without me selecting it to i have no ideas who account.
> > 
> > 
> > its the developer mining...its the fee to use the program... all of them have it...... its a few mins a day.... you should watch what it mines... that might be where the money is at
> 
> ahh i see thanks for the answer now just need to figure out how to reset the miner fees so i can adjust miners i want to use accordingly. hopefully without reinstalling the whole thing as it takes so long to benchmark everything.


this might be to confusing for you... try this instead... go learn.. come back in 6 months or so...

https://www.awesomeminer.com/

**Comment by RainbowMiner** [comment]
Yes, the RainbowMiner mines for me once a day for some minutes. The rate can be adjusted with parameter `Donate` in config.txt - it contains the minutes per day that it is mining for me.

> the miner fees disappeared is there a way to reset that?

What do you mean by this exactly? Can you post a screenshot?

**Comment by whitindllc** [comment]
> Yes, the RainbowMiner mines for me once a day for some minutes. The rate can be adjusted with parameter `Donate` in config.txt - it contains the minutes per day that it is mining for me.
> 
> > the miner fees disappeared is there a way to reset that?
> 
> What do you mean by this exactly? Can you post a screenshot?

not worth the time...

**Comment by UselessGuru** [comment]
> hopefully without reinstalling the whole thing as it takes so long to benchmark everything.

Should you have to re-install then you can always copy over the benchmark results (files in folder 'Stats'). This will save you the time to re-benchmark.

**Comment by truckinCowboy** [comment]
> Yes, the RainbowMiner mines for me once a day for some minutes. The rate can be adjusted with parameter `Donate` in config.txt - it contains the minutes per day that it is mining for me.
> 
> > the miner fees disappeared is there a way to reset that?
> 
> What do you mean by this exactly? Can you post a screenshot?

![Screenshot 2024-07-16 164618](https://github.com/user-attachments/assets/368eb850-8af8-4ac5-bc9b-97e2550c26a3)
fees not showing so if i choose to use miners without fees it doesnt work and @whitindllc no need to be rude i mean wtf

**Comment by truckinCowboy** [comment]
I reinstalled RainbowMiner and moved the stats file over like suggested the fees are showing again and everytrhing working smoothly. thank you for your help I am really enjoy your program and don't mind the contribution for the dev it is worth it.
