### ISSUE TITLE
RainbowMiner filling up ssd, not logs.

### ISSUE THREAD

**Issue by IdiocracyFR** [RainbowMiner/RainbowMiner#2834]
Running RainbowMiner on Ubuntu-server 23.04 (not supported, i know, sorry) fills up my SSD in about two days, and its not the common too-many-logs problem.

What could be causing this? I don't have the same issue on windows machines, and didn't have this issue until after the last couple RainbowMiner updates.

Thanks for your time, and your work on RainbowMiner!

**Comment by RainbowMiner** [comment]
Is this a GPU mining rig? If yes - look into the `./Bin/NVIDIA-TTminer/DAGs` folder. It might be realted to this: #2755
This miner saves all the DAG files to disk. This is by default - if you need to get rid of the save-the-DAG feature, just add the following data block to miners.config.txt:

```
  "TTminer" : [
    {
      "MainAlgorithm": "*",
      "SecondaryAlgorithm": "",
      "Params": "-dag-2disk #",
      "MSIAprofile": "",
      "OCprofile": "",
      "Difficulty": "",
      "Penalty": "",
      "Disable": "0",
      "ShareCheck": "",
      "Tuning": "0",
      "HashAdjust": ""
    }	
  ],
```
 
If this is not the problem, you might want to have a look into the systems `/var/logs` folder - maybe there is some process throwing error messages.

**Comment by IdiocracyFR** [comment]
For some reason, adding that block to my miners.config.txt prevented rbminer from launching (json errors in main config).

However, deleting DAGs made enough space that I was able to run setup again. 
Once there I added "-dag-2disk #" param to TTminer for my gpus & problem solved!

Thank you :)
