### ISSUE TITLE
rbminer monitorining is gone

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2843]
site looks like it has some cloudfare like front... goes to ask for the key and then does one of two things... either craps out with this error
![image](https://github.com/user-attachments/assets/9c7ef300-90fc-4b5e-948f-71cf4ef607f9)

or all of the machines are offline...

also this is a new 

![image](https://github.com/user-attachments/assets/5cdd01bc-deca-44f7-84c7-58adf190177c)

**Comment by RainbowMiner** [comment]
Same with all of my machines. Seems like my provider has added some CloudFlare to the API. I will check that asap.

**Comment by RainbowMiner** [comment]
Ok, for some reason, my provider had flipped the CDN switch "I am under attack" to "ON" yesterday. I have switched it back to "OFF" now, all should be back to normal now. I will check with the provider for the reason of this.

**Comment by whitindllc** [comment]
everything is back.... thank you
