### ISSUE TITLE
gox.cx stratum address wrong?

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#285]
![image](https://user-images.githubusercontent.com/22162766/48104310-d97aaf00-e22a-11e8-9475-fcb87c339ae9.png)

Not sure if this is wrong, but the site asks for [area].gos.cx. Could this be why this isn't connecting?

**Comment by RainbowMiner** [comment]
Oh dear! You are totally right.
Please download this zip:
[GosCx.zip](https://github.com/RainbowMiner/RainbowMiner/files/2555707/GosCx.zip)
.. and extract the GosCx.ps1 into your Pools folder for a quick fix. It will be clear in the next release.

**Comment by talentoscope** [comment]
Whoops! I do things like it all the time, don't worry! :)
Thanks for the seriously quick fix. Wow!
