### ISSUE TITLE
Algo alias required for Zerg/Zpool for PEPEW

### ISSUE THREAD

**Issue by Ondalf** [RainbowMiner/RainbowMiner#2854]
Hello,
xelishashv2_pepew in SRB (and soon others) will be named as `xelisv2-pepew` in both zpool and zergpool.
Just to let you know :)

**Comment by RainbowMiner** [comment]
Thank you :)
Already taken care of:
```
    "xelisv2pepew": "XelisV2PepePow",
```

**Comment by whitindllc** [comment]
is this the CPU side of xelis pepe?

**Comment by RainbowMiner** [comment]
> is this the CPU side of xelis pepe?

Yes.

**Comment by Ondalf** [comment]
Are you sure its working, since there is dash in the algorithm name...?

**Comment by Ondalf** [comment]
Ah, SRBMiner minerfile has algorithm name invalid.
should be `xelishashv2_pepew` as opposed to what it now says `xelishashv2_pepepow`.
Causes crashed miner otherwise.

**Comment by Ondalf** [comment]
...and since its now using different name in the miner, shouldn't you also change algorithms.json
```diff
diff --git a/Data/algorithms.json b/Data/algorithms.json
index 815747d..8d80af2 100644
--- a/Data/algorithms.json
+++ b/Data/algorithms.json
@@ -865,9 +865,9 @@
     "xelis": "XelisHashV2",
     "xelishash": "XelisHash",
     "xelishashv2": "XelisHashV2",
-    "xelishashv2pepepow": "XelisV2PepePow",
-    "xelisv2pepepow": "XelisV2PepePow",
-    "xelisv2pepew": "XelisV2PepePow",
+    "xelishashv2pepepow": "XelisHashV2Pepew",
+    "xelisv2pepepow": "XelisHashV2Pepew",
+    "xelisv2pepew": "XelisHashV2Pepew",
     "xevan": "Xevan",
     "xevanmod": "Xevan",
     "xmg": "m7m",
```
Dince it may have hard time finding that algo otherwise, as no miner matches to ...PepePow
Sure do correct, if i'm wrong, but i couldn't get it to match data from pool with SRBMiner

**Comment by RainbowMiner** [comment]
Yes, probably for the best. A new coinsdb.json will follow.

**Comment by Ondalf** [comment]
We good. Should work. Thanks!
