### ISSUE TITLE
XmRig-MO: Benchmarking all algorithms before mining

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2856]
E.g seen with

`XmRig-v6.22.0.3\xmrig-mo.exe --algo gr --threads=5 --randomx-wrmsr=-1 --tls --url=ghostrider.mine.zergpool.com:15354 --user=########################## --pass=c=BTC,ID=################ --donate-level 0 --keepalive --http-enabled --http-host=127.0.0.1 --http-port=4000 --api-worker-id=#################### --api-id=XmRig-v6.22.0.3-1xCorei58600K3.60GHz-Ghostrider --retries=90 --retry-pause=1`

Is this intentional?

XmRig (non-MO) is running as expected.

**Comment by RainbowMiner** [comment]
No that is not intended. In fact, the xmrig-mo contains code to circle through a benchmark at the first start, but I thought I switched the code of before compile. I will recompile the xmrig-mo tomorrow and see if there is something wrong.

**Comment by UselessGuru** [comment]
> I will recompile the xmrig-mo tomorrow 

Done?

**Comment by RainbowMiner** [comment]
Sorry, had other things to do first. Now it's ok.

**Comment by UselessGuru** [comment]
Working fine now. Thank you!

**Comment by UselessGuru** [comment]
This is fixed in 6.24.0
