### ISSUE TITLE
Pool config issues

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#286]
Some issues with the Powershell config when trying to set them on the following:

Cryptoknight : No wallet or coin info, just asks for worker
MinerRocks: Selecting this just goes back to the main config screen
MiningPoolHubCoins: Same

Hope this helps somehow :)

**Comment by RainbowMiner** [comment]
Thank you for the report. I will check the config, since I changed a lot in this module, recently.

**Comment by RainbowMiner** [comment]
Problems fixed - I will publish a new release v3.8.11.2

**Comment by talentoscope** [comment]
Awesome!!! :+1:
