### ISSUE TITLE
Could not write to miners.config.txt

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#287]
it was the first time, closed the file, although others were open in notepad++ and I didn't get the warning. Close RBM try again, same message, closed notepad++ completely, close RBM tried again, same message

![image](https://user-images.githubusercontent.com/41829368/48131148-4e121580-e24c-11e8-8b86-fdaab042f85c.png)

**Comment by RainbowMiner** [comment]
So, when did this happen? After an update, or during a normal session? You might have a windows write lock on the file. Close all Explorer windows, too. Eventually you need to restart Windows.

**Comment by hernandn01** [comment]
after this last update on first start. I used updater.bat while out of RBM

**Comment by talentoscope** [comment]
Confirmed. I had nothing open and it happened here as well. Doesn't seem to have any ill effects though.

**Comment by RainbowMiner** [comment]
Thanks a lot! No, that should not affect anything, but it indicates a minor bug with the new code, I added. Unforunatly, I cannot reproduce this, here. 
Would any of you two be willing to catch the error? That would be wonderful :)

Like this:
Download this zip (containing a version, that will throw a more specific error) and extract Include.psm1 directly into the Rainbowminer root. Restart RainbowMiner and snapshot the red error(s).
[Include.zip](https://github.com/RainbowMiner/RainbowMiner/files/2557529/Include.zip)

.. after that: download this zip (containing the original backup) and extract Include.psm1 directly into the RBM root, restart.
[IncludeV3.8.11.2.zip](https://github.com/RainbowMiner/RainbowMiner/files/2557530/IncludeV3.8.11.2.zip)

**Comment by RainbowMiner** [comment]
Oh, remark: only use this with version v3.8.11.2!

**Comment by hernandn01** [comment]
PS>TerminatingError(Set-MinersConfigDefault): "Exception setting "SecondaryAlgorithm": "The property 'SecondaryAlgorithm' cannot be found on this object. Verify that the property exists and can be set.""
>> TerminatingError(Set-MinersConfigDefault): "Exception setting "SecondaryAlgorithm": "The property 'SecondaryAlgorithm' cannot be found on this object. Verify that the property exists and can be set.""
Write-Log : Exception setting "SecondaryAlgorithm": "The property 'SecondaryAlgorithm' cannot be found on this object. Verify that the property exists and can be set." Cannot run RainbowMiner. 
At C:\miner\RainbowMiner\Core.psm1:162 char:9
+         Write-Log -Level Error "$($_) Cannot run RainbowMiner. "
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
Write-Log : Exception setting "SecondaryAlgorithm": "The property 'SecondaryAlgorithm' cannot be found on this object. Verify that the property exists and can be set." Cannot run RainbowMiner.
At C:\miner\RainbowMiner\Core.psm1:162 char:9
+         Write-Log -Level Error "$($_) Cannot run RainbowMiner. "
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

**Comment by RainbowMiner** [comment]
Super! Thank you very much. Now I now 👍

**Comment by RainbowMiner** [comment]
... and fixed. Quick fix would be to download this zip and extract into Data folder:
[MinersConfigDefault.zip](https://github.com/RainbowMiner/RainbowMiner/files/2557594/MinersConfigDefault.zip)

**Comment by RainbowMiner** [comment]
.. or update to maintenance release v3.8.11.3
