### ISSUE TITLE
Centralized monitoring of all your installations in https://rbminer.net It doesn't work

### ISSUE THREAD

**Issue by biret733** [RainbowMiner/RainbowMiner#2874]
plus, the what to mine service does not work

**Comment by maiquecoutinho** [comment]
Monitor offline?

**Comment by RainbowMiner** [comment]
I am just in the middle of moving the monitor to a powerful VPS. Due to the DNS changes, there might be some short offline time. Should be resolved within some hours.

**Comment by RainbowMiner** [comment]
Done :)
