### ISSUE TITLE
BZMiner 21.5.0 has a bug

### ISSUE THREAD

**Issue by UselessGuru** [RainbowMiner/RainbowMiner#2875]
From https://github.com/bzminer/bzminer/releases/tag/v21.5.0:

BROKEN! this release has a breaking bug in the command line options. If experiencing bz hanging on start or showing "invalid wallet", please use last latest beta or wait for hotofx (coming shortly)

**Comment by RainbowMiner** [comment]
Yes, I have noticed it. I will wait for the hotfix.

**Comment by RainbowMiner** [comment]
Ok, the hotfix has arrived.
