### ISSUE TITLE
CryptoDredge PHI2

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#288]
Would it be possible to extend the bench on this please? It doesn't seem long enough and the hashrate was still climbing when the bench finished. Thank you!! :)

**Comment by talentoscope** [comment]
X17 too, sorry. Looks like this version likes to take a while to "bed in" those rates for some reason

**Comment by RainbowMiner** [comment]
Yes, looks like. The former versions have been faster.

**Comment by RainbowMiner** [comment]
I added extended intervals for those two:
[CryptoDredge.zip](https://github.com/RainbowMiner/RainbowMiner/files/2557565/CryptoDredge.zip)

**Comment by RainbowMiner** [comment]
I added extend intervals to those two algorithms:
