### ISSUE TITLE
xmrigCC

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2883]
Please add support for xmrigCC, as it includes some algorithms that the main xmrig repo does not include (such as mike)

xmrigCC is better than cpuminerrplant 

Thank you!

https://github.com/Bendr0id/xmrigCC

**Comment by realsetvin** [comment]
xmrigcc also has much better gpu support, making it the only open source ghostrider gpu miner. It would be a valuable addition and different from the main xmrig repo. Its the modern version of xmrstak

**Comment by RainbowMiner** [comment]
I see. I will try to integrate it.

**Comment by realsetvin** [comment]
> I see. I will try to integrate it.

looks like you added it, thanks for taking my suggestion.
