### ISSUE TITLE
API errors everywhere, even with fresh install

### ISSUE THREAD

**Issue by Lebob7** [RainbowMiner/RainbowMiner#2885]
![Screenshot 2024-10-28 182832](https://github.com/user-attachments/assets/ce55d161-489e-4a4d-9909-7dbe9672aed5)

Every API is failing and is unable to update data, including profitable and unprofitable coins, whattomine and pretty much everything. 
I have attached Errors API:
[errors_2024-10-28.api.txt](https://github.com/user-attachments/files/17539580/errors_2024-10-28.api.txt)

The below Runtime Log also output from same launch, this has now been happening for the past few months..

`Starting sysinfo ..
ok
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "0" argument(s): "Could not connect to MSI Afterburner 2.1 or later.""
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "0" argument(s): "Could not connect to MSI Afterburner 2.1 or later.""
PS>TerminatingError(): "Call to https://api.rbminer.net/data/unprofitable3.json timed out after 15 secs"
>> TerminatingError(): "Call to https://api.rbminer.net/data/unprofitable3.json timed out after 15 secs"
WARNING: Unprofitable algo API failed.
PS>TerminatingError(): "Call to https://api.coinbase.com/v2/exchange-rates?currency=BTC timed out after 15 secs"
>> TerminatingError(): "Call to https://api.coinbase.com/v2/exchange-rates?currency=BTC timed out after 15 secs"
>> TerminatingError(): "Call to https://api.coinbase.com/v2/exchange-rates?currency=BTC timed out after 15 secs"
PS>TerminatingError(): "Call to https://api.rbminer.net/data/coinbase.json timed out after 15 secs"
WARNING: Coinbase down.
WARNING: Powerprice currency  not found. Cost of electricity will be ignored.
Loading pool modules ..
.. loading MiningDutch
done (0.841s)
.. loading ProHashing
PS>TerminatingError(): "Call to https://prohashing.com/api/v1/status timed out after 15 secs"
>> TerminatingError(): "Call to https://prohashing.com/api/v1/status timed out after 15 secs"
>> TerminatingError(): "Call to https://prohashing.com/api/v1/status timed out after 15 secs"
WARNING: Pool API (ProHashing) has failed.
done (15.254s)
.. loading unMineable
PS>TerminatingError(): "Call to https://api.unmineable.com/v3/coins timed out after 15 secs"
>> TerminatingError(): "Call to https://api.unmineable.com/v3/coins timed out after 15 secs"
>> TerminatingError(): "Call to https://api.unmineable.com/v3/coins timed out after 15 secs"
WARNING: Pool API (unMineable) has failed.
done (15.23s)
.. loading ZergPool
PS>TerminatingError(): "Call to https://zergpool.com/api/status timed out after 15 secs"
>> TerminatingError(): "Call to https://zergpool.com/api/status timed out after 15 secs"
>> TerminatingError(): "Call to https://zergpool.com/api/status timed out after 15 secs"
WARNING: Pool API (ZergPool) has failed.
done (15.161s)
.. loading ZergPoolSolo
PS>TerminatingError(): "Call to https://zergpool.com/api/status timed out after 15 secs"
>> TerminatingError(): "Call to https://zergpool.com/api/status timed out after 15 secs"
>> TerminatingError(): "Call to https://zergpool.com/api/status timed out after 15 secs"
WARNING: Pool API (ZergPoolSolo) has failed.
done (15.16s)
.. loading Zpool
PS>TerminatingError(): "Call to https://www.zpool.ca/api/status timed out after 30 secs"
>> TerminatingError(): "Call to https://www.zpool.ca/api/status timed out after 30 secs"
>> TerminatingError(): "Call to https://www.zpool.ca/api/status timed out after 30 secs"
WARNING: Pool API (Zpool) has failed.
done (30.929s)
Loading balance modules ..
PS>TerminatingError(): "Call to https://prohashing.com/api/v1/wallet?apiKey=26f5833355a9c2a78a64c67d4b0f97c53d6159e0b9f96c1640b11b13c2be2661 timed out after 15 secs"
>> TerminatingError(): "Call to https://prohashing.com/api/v1/wallet?apiKey=26f5833355a9c2a78a64c67d4b0f97c53d6159e0b9f96c1640b11b13c2be2661 timed out after 15 secs"
>> TerminatingError(): "Call to https://prohashing.com/api/v1/wallet?apiKey=26f5833355a9c2a78a64c67d4b0f97c53d6159e0b9f96c1640b11b13c2be2661 timed out after 15 secs"
WARNING: Pool API (ProHashing) has failed for user Willhoy1.
PS>TerminatingError(): "Call to https://api.unmineable.com/v3/coins timed out after 15 secs"
>> TerminatingError(): "Call to https://api.unmineable.com/v3/coins timed out after 15 secs"
>> TerminatingError(): "Call to https://api.unmineable.com/v3/coins timed out after 15 secs"
WARNING: Pool API (unMineable) has failed.
PS>TerminatingError(): "Call to https://api.blockcypher.com/v1/dash/main/addrs/XtAscppCZPiDw3m7xs3GTA3B1QPy4ctFQJ timed out after 15 secs"
>> TerminatingError(): "Call to https://api.blockcypher.com/v1/dash/main/addrs/XtAscppCZPiDw3m7xs3GTA3B1QPy4ctFQJ timed out after 15 secs"
>> TerminatingError(): "Call to https://api.blockcypher.com/v1/dash/main/addrs/XtAscppCZPiDw3m7xs3GTA3B1QPy4ctFQJ timed out after 15 secs"
PS>TerminatingError(): "Call to https://api.blockcypher.com/v1/doge/main/addrs/DC2FRBhGH7m13NNRMu5Er6GMFecJkx7aLh timed out after 15 secs"
>> TerminatingError(): "Call to https://api.blockcypher.com/v1/doge/main/addrs/DC2FRBhGH7m13NNRMu5Er6GMFecJkx7aLh timed out after 15 secs"
>> TerminatingError(): "Call to https://api.blockcypher.com/v1/doge/main/addrs/DC2FRBhGH7m13NNRMu5Er6GMFecJkx7aLh timed out after 15 secs"
PS>TerminatingError(): "Call to https://api.blockcypher.com/v1/eth/main/addrs/0xCdfA4F3bD6883D8e312F392F69BBe581217E8455 timed out after 15 secs"
>> TerminatingError(): "Call to https://api.blockcypher.com/v1/eth/main/addrs/0xCdfA4F3bD6883D8e312F392F69BBe581217E8455 timed out after 15 secs"
>> TerminatingError(): "Call to https://api.blockcypher.com/v1/eth/main/addrs/0xCdfA4F3bD6883D8e312F392F69BBe581217E8455 timed out after 15 secs"
PS>TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No such host is known. (api.pyrin.network:443))" --> One or more errors occurred. (No such host is known. (api.pyrin.network:443))"
>> TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No such host is known. (api.pyrin.network:443))" --> One or more errors occurred. (No such host is known. (api.pyrin.network:443))"
>> TerminatingError(): "Exception calling "Wait" with "1" argument(s): "One or more errors occurred. (No such host is known. (api.pyrin.network:443))" --> One or more errors occurred. (No such host is known. (api.pyrin.network:443))"
PS>TerminatingError(): "Call to https://rvn.cryptoscope.io/api/getbalance/?address=RF2ube3qBzW4XP5ddjywRfGtK4ui73t9hz timed out after 15 secs"
>> TerminatingError(): "Call to https://rvn.cryptoscope.io/api/getbalance/?address=RF2ube3qBzW4XP5ddjywRfGtK4ui73t9hz timed out after 15 secs"
>> TerminatingError(): "Call to https://rvn.cryptoscope.io/api/getbalance/?address=RF2ube3qBzW4XP5ddjywRfGtK4ui73t9hz timed out after 15 secs"
PS>TerminatingError(): "Call to https://radiantexplorer.com/ext/getbalance/1PyPFJ5Ms8KyiVnXy3utx1cswsGJT1YaoV timed out after 15 secs"
>> TerminatingError(): "Call to https://radiantexplorer.com/ext/getbalance/1PyPFJ5Ms8KyiVnXy3utx1cswsGJT1YaoV timed out after 15 secs"
>> TerminatingError(): "Call to https://radiantexplorer.com/ext/getbalance/1PyPFJ5Ms8KyiVnXy3utx1cswsGJT1YaoV timed out after 15 secs"
PS>TerminatingError(): "Call to https://api.zcha.in/v2/mainnet/accounts/t1eTYVSRFZmqLyoGXhoU2aaCURXzuRQf62D timed out after 15 secs"
>> TerminatingError(): "Call to https://api.zcha.in/v2/mainnet/accounts/t1eTYVSRFZmqLyoGXhoU2aaCURXzuRQf62D timed out after 15 secs"
>> TerminatingError(): "Call to https://api.zcha.in/v2/mainnet/accounts/t1eTYVSRFZmqLyoGXhoU2aaCURXzuRQf62D timed out after 15 secs"
PS>TerminatingError(): "Call to https://zergpool.com/api/currencies timed out after 20 secs"
>> TerminatingError(): "Call to https://zergpool.com/api/currencies timed out after 20 secs"
>> TerminatingError(): "Call to https://zergpool.com/api/currencies timed out after 20 secs"
WARNING: Pool currencies API (ZergPool) has failed.`

I am at a complete loss and about to stop using RBM. I keep getting 'No Pools, check your config' and have to keep repairing the server install or rebooting it. I have started from scratch to achieve the exact same issue. 

Help, advice  or looking into the issue would be appreciated.

**Comment by RainbowMiner** [comment]
Since it hits all APIs, it looks like the internet access gets blocked somehow. Are there any Firewalls in place? Either on the machine, or on your router? If this happens short after an internet outage, you might try to clear the cache: go to folder "Cache" in your RainbowMiner home and delete all files inside the folder. Then start RainbowMiner again.

Also try the same on your server machine.

**Comment by RainbowMiner** [comment]
Second: please create a Debug file and upload it here if possible. That makes it easier for me to look into the problem.

**Comment by Lebob7** [comment]
Further to, I have also done a repair.bat operation on some systems due to invalid config files from the previous update.  I have reverted all config files on the server to assist resolving.

Thanks for your assistance. It's just odd.

**Comment by Lebob7** [comment]
To add to your previous comment, as i forgot to add - Windows firewall has been turned off,. No firewall active due to the firewall rule replicating from RBM until the firewall is using all available ram in Windows 10 Machines. This does not happen on Windows 11. All prerequisites installed.

**Comment by RainbowMiner** [comment]
Please try to downgrade the Powershell Core to v7.2.24 on all machines (https://github.com/PowerShell/PowerShell/releases/download/v7.2.24/PowerShell-7.2.24-win-x64.msi).

**Comment by Lebob7** [comment]
I actually updated from v7.2.23 to v7.2.24 yesterday on all machines as a last resort. So that has been done. Windows update is hard disabled in policies, when required i perform critical updates manually via SP downloads.
Trying to keep things tight on Windows 10 without Firewall running.

**Comment by Lebob7** [comment]
Hmmm, ok, will identify how that got onto machines and come back to you - I am only showing v7.2.24 as installed, but this is also my only Windows 11 system, does it come with 7.4.5 natively?

**Comment by RainbowMiner** [comment]
Ok, I will dig into the debug file.

**Comment by RainbowMiner** [comment]
You said, that there were no files in the Cache folder. How about now?
Could you please try the following:
- open cmd.exe
- cd to your RainbowMiner folder
- type `pwsh` and enter
- inside the pwsh prompt, type:
`using module .\Modules\Include.psm1`
`invoke-geturl "https://api.rbminer.net/data/hello.txt"`

.. it should now say "world". If it does try:
`invoke-geturl "https://api.rbminer.net/data/hello.txt" | Set-Content ".\Cache\test.txt"`

Did it create a file `test.txt` in the Cache folder? Any errors?

**Comment by Lebob7** [comment]
> You said, that there were no files in the Cache folder. How about now? Could you please try the following:
> 
>     * open cmd.exe
> 
>     * cd to your RainbowMiner folder
> 
>     * type `pwsh` and enter
> 
>     * inside the pwsh prompt, type:
>       `using module .\Modules\Include.psm1`
>       `invoke-geturl "https://api.rbminer.net/data/hello.txt"`
> 
> 
> .. it should now say "world". If it does try: `invoke-geturl "https://api.rbminer.net/data/hello.txt" | Set-Content ".\Cache\test.txt"`
> 
> Did it create a file `test.txt` in the Cache folder? Any errors?

#1 All systems are now fully corrected to powershell v7.2.24.
#2  The cache folder is still only showing console.txt in all cache folders on all machines.
#3 Machines are now not showing any existing currency figures and took them about 4 hours to pickup pool data from the server.
#4 Attached output from requested test, obviously unable to complete request, unable to access domain,
![Screenshot 2024-10-29 180424](https://github.com/user-attachments/assets/9d66e097-fa21-4a25-9058-40943b90433d)
#5 Pinged your api, failure, (attached) Pinged my rdomain in the UK, worked fine. I have zero restrictions set on network outgoing or incoming, it does set ports automatically through UPNP.
  
![Screenshot 2024-10-29 180717](https://github.com/user-attachments/assets/1ab69dc7-cf23-4e7d-9cc3-e2ff351127b1)

Ideas welcome.

**Comment by Lebob7** [comment]
Further to, I cannot even ping or tracert your website, let alone ping, but I can visit via any browser.

PS D:\RainbowMinerV4.9> ping rbminer.net

Pinging rbminer.net [2a02:4780:c:8f55::1] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 2a02:4780:c:8f55::1:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
PS D:\RainbowMinerV4.9>

**Comment by Lebob7** [comment]
Might explain why I cannot get any API functionality.

**Comment by Lebob7** [comment]
![Screenshot 2024-10-29 181506](https://github.com/user-attachments/assets/74377f48-5036-446b-a992-33bf442111c1)

And i can access this without issue, displaying content - WORLD, but ....  stumped.

**Comment by Lebob7** [comment]
Further on, delving into IPV protocols, I find IPV4 Forced ping (Ping -4 <site>) works for rbminer.net and the api subdomain. 

![Screenshot 2024-10-29 184012](https://github.com/user-attachments/assets/e128629d-265f-4c6c-9897-55f4314b2be9)

Can we force IPV4 protocol or fallback if timeout?

**Comment by RainbowMiner** [comment]
So it looks like it is a router or provider that blocks IPv6.
Can you access your router and check if IPv6 can be enabled? It also explains why so many different URL cannot be reached. The nameserver seems to resolve most of them to IPv6.

You could try: To configure Windows to prefer IPv4 over IPv6, you can adjust the prefix policy. This does not disable IPv6 but tells Windows to prefer IPv4 when both protocols are available. Here’s how to set it up:

Method 1: Using the Command Prompt

1. Open Command Prompt as Administrator.


2. Run the following command to modify the prefix policy:

netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 46 4

This command changes the IPv6-to-IPv4 precedence, instructing Windows to prefer IPv4 over IPv6.


3. You can verify the changes by running:

netsh interface ipv6 show prefixpolicies

The output should show ::ffff:0:0/96 with a higher precedence, indicating IPv4 preference.



Method 2: Using the Windows Registry

1. Press Win + R, type regedit, and press Enter to open the Registry Editor.


2. Navigate to the following key:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters


3. Right-click on the right pane, select New > DWORD (32-bit) Value, and name it:

DisabledComponents


4. Set the value of DisabledComponents to 20 (Hexadecimal) to prefer IPv4 over IPv6.


5. Restart your computer for the changes to take effect.



> Note: Setting DisabledComponents to 20 does not disable IPv6. It only adjusts the preference order to favor IPv4. To revert this change, delete the DisabledComponents entry or set its value to 0.



Method 3: Using Group Policy (for Network Environments)

If you’re managing a network with Group Policy, you can also set this preference across multiple machines by adjusting the Group Policy Object (GPO) to apply this registry setting.

After setting IPv4 as the preferred protocol, applications will generally attempt IPv4 connections first when both IPv4 and IPv6 addresses are available.

**Comment by RainbowMiner** [comment]
A second possibilty woud be to configure RainbowMiner to use curl instead of the build-in Invoke-WebRequest method. Curl in fact handles fallback from IPv6 to IPv4 more gracefully than the system tools. Try setting `"EnableCurl": "1",` in config.txt. Then restart.

**Comment by Lebob7** [comment]
Thankyou for your input here, IVP6 from the individual network configuration, as its not required on this system, but i do use IVP6 routing. It was working fine a few months back then suddenly started. I have even set IVP6 DNS to try and resolve but to no avail.Glad curl does graceful redundancy, good to note. I might go that way.

**Comment by RainbowMiner** [comment]
Good to hear that it is working out now! I think, I will add a smart check to the core module that operate like "if access to IPv4 works, but fails with IPv6 plus the systemtools fail, switch to curl automatically"
