### ISSUE TITLE
CCMiner Xevan

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#289]
![image](https://user-images.githubusercontent.com/22162766/48138338-0d41ed00-e29c-11e8-84b0-6fb61b7d8abb.png)

Me...again :rofl: 
Not sure why this is happening with xevan, probably the miner. I've disabled the algo my end for now, just thought I should give you a heads up on this one.

**Comment by RainbowMiner** [comment]
illegal memory access indicates an overclocking issue, in 99% of the cases. 
Are you overclocking with some tool other than RainbowMiner?

**Comment by RainbowMiner** [comment]
.. also it could be, that the intensity (-i) is too high. Eventually you could try with a lower -i param (miners.config.txt)

**Comment by RainbowMiner** [comment]
Question: how are you (if any) do the overclocking? Is it with afterburner?

**Comment by hernandn01** [comment]
this is what works for me for 1050 ti on ccminer xevan, edit your miners.config.txt and set to -i 21
![image](https://user-images.githubusercontent.com/41829368/48148914-1faa2f80-e278-11e8-85f9-db7f2438d920.png)

**Comment by talentoscope** [comment]
Oh nice one! Will try that, thanks mate!

**Comment by talentoscope** [comment]
Okay, I set the intensity to 18 and it works fine. Didn't want to cook it, so kept it lower than the suggested 20. Thanks guys, much appreciated :)
