### ISSUE TITLE
MiningRigRentals stopped working in the middle of rentals!

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2894]
Good afternoon, 5 of my rented rigs went offline about an hour ago. Tried restarting but it acts as if they arent rented.
Last night they had an upgrade going on.
Can you check if everything is ok?

**Comment by RainbowMiner** [comment]
Strange - try to clear the Cache folder and restart RainbowMiner. Normally it should pick up the rentals no matter what.

**Comment by papadrams** [comment]
Clearing the cache didnt work.
[debug_2024-11-14.zip](https://github.com/user-attachments/files/17750495/debug_2024-11-14.zip)

**Comment by papadrams** [comment]
Thats 1 of the rigs. If you need more let me know

**Comment by papadrams** [comment]
It corrected itself about an hour later. Maybe mrr issue? Thanks for the reply!
