### ISSUE TITLE
Power price by hour (peak hours)

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2897]
Requesting the ability to turn off miners during set hours (ig, turn off miners during peak of day noon to 4 pm ), and to also the ability to create an hourly power price schedule (eg 12 am 8 am 0.15 cent - 8 am to 8 pm 0.25 cent, ext.)

**Comment by RainbowMiner** [comment]
I think you can do this already by editing the scheduler.config.txt : https://github.com/RainbowMiner/RainbowMiner?tab=readme-ov-file#configschedulerconfigtxt
