### ISSUE TITLE
xmrigcc error along with a few others

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2898]
<img width="955" alt="{1470C823-4DBF-43F4-B085-DBAADC8565E5}" src="https://github.com/user-attachments/assets/e73603bf-2b24-4b6a-857e-74dbecd5a591">

**Comment by RainbowMiner** [comment]
Ah, sorry! Wrong filename in the repo. I have added the correct filename. It should download now.

**Comment by whitindllc** [comment]
doesnt download... maybe next update

**Comment by whitindllc** [comment]
it downloads now... but i will probably disable it... its buggy and often doesnt close when the schedule or stopp.bat tells it to
