### ISSUE TITLE
server broken?

### ISSUE THREAD

**Issue by realsetvin** [RainbowMiner/RainbowMiner#2903]
Server no longer shows remote devices, can see clients connected in the cli. Not sure what happened.

**Comment by RainbowMiner** [comment]
Can you still see all rigs on rbminer.net/monitoring ?

**Comment by realsetvin** [comment]
I can see some online, some of the are offline and not able to connect anymore. I think once they turn off and turn back on they no longer connect

**Comment by realsetvin** [comment]
this is what it says on startup

Starting v4.9.4.4! Please wait..

RainbowMiner recommends PowerShell Core Version 7.2.24 (vs. v7.2.18)
Everything will run fine with the current version, but consider updating your PowerShell

To update, run "sudo ./install.sh -pu" in folder /home/amd1/rainbow

Checking for VM ..
ok (not in a VM)
Checking for cURL ..
not found
Detecting devices ..
1 CPU found
Initialize configuration ..
PS>TerminatingError(): "Call to https://api.coinbase.com/v2/currencies timed out after 15 secs"
>> TerminatingError(): "Call to https://api.coinbase.com/v2/currencies timed out after 15 secs"
WARNING: Worldcurrencies API failed.
Checking last shutdown ..
crashed
Read configuration ..
WARNING: Could not read time from time.google.com
Starting sysinfo ..
ok
PS>TerminatingError(): "Call to https://api.github.com/repos/rainbowminer/RainbowMiner/releases/latest timed out after 15 secs"

**Comment by RainbowMiner** [comment]
That does mean you cannot connect to the internet currently. Maybe some IPv6 vs. IPv4 issue on the router?

**Comment by realsetvin** [comment]
> That does mean you cannot connect to the internet currently. Maybe some IPv6 vs. IPv4 issue on the router?

was working the night before, woke up and it had that error. 

I can still access the server from local machines and its mining right now, which means its connected to the internet

**Comment by realsetvin** [comment]
> Maybe a short outage. In these cases, you can try to https://api.coinbase.com/v2/currencies in your browser on that machine, just to see what is going on.

checked my internet account, had past due balance

no idea how some internet connection was active but others wasnt. Maybe rate limited. Sorry to bug you
