### ISSUE TITLE
is PYI a dead coin?

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2904]
Received a defect stratum message: conversion of data to type "bool" failed
Lost connection to stratum server pyi.2miners.com:2121 or server not reachable.
Trying to connect in 5 second(s)
Autolykos V2 (Ergo): Average speed (5s): 0.00 Mh/s
HeavyHash-Pyrin V2: Average speed (5s): 0.00 Mh/s
DNS over HTTPS resolve succeeded
Connected to pyi.2miners.com(162.19.139.120):2121  (TLS disabled)
New extra nonce received: efed
Received a defect stratum message: conversion of data to type "bool" failed
Lost connection to stratum server pyi.2miners.com:2121 or server not reachable.
Trying to connect in 5 second(s)

**Comment by realsetvin** [comment]
yes I believe they announced they were abandoning the project

**Comment by whitindllc** [comment]
okay i have removed all pyi wallets
