### ISSUE TITLE
bsod wallet balance

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#292]
I can't see why this isn't working. 

http://api.bsod.pw/api/walletEx?address=ScDWNsi4v7iUDjJ99gGSkQKHaCXXt3SZGN
populates with the correct info, and I can't see anything immediately obvious in the ps1 file (though I'm no expert).

Probably a bug if the site shows it fine :)

**Comment by RainbowMiner** [comment]
Does the line "Bsod (SUQA)"  show up? I just tried with your wallet address and for me, it is there. The column "Balance" will only show not paid values, so it reflects what you will be paid, only.

**Comment by talentoscope** [comment]
Nope. Nothing. I wonder if it's related to the colour code issue and is
getting mangled in there somewhere

**Comment by talentoscope** [comment]
I think I said this wrong. Yellow warnings do come up for BSOD.
Pool Balance API (bsod) for COIN returned nothing.
Same for all coins.

**Comment by talentoscope** [comment]
Okay, new update.

No yellow warnings, but bsod and gos.cx still don't show balances properly.
One thing I *have* noticed is that gos.cx shows the first alphabetically, in my case ALMN.
So I'm thinking this is probably API rate limiting on both sites.

Not sure what to suggest :)

**Comment by RainbowMiner** [comment]
Did the balances finally show up?

**Comment by RainbowMiner** [comment]
Solved with v3.9.7.0
