### ISSUE TITLE
NLPool Coins

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#293]
It looks as if NLpool has port for specific coins? Wondering if they could be added?

**Comment by talentoscope** [comment]
![image](https://user-images.githubusercontent.com/22162766/48167317-42bdf900-e2e3-11e8-9295-1a4045ab326c.png)

Mining on there right now. It looks like RBM *does* mine specific coins there with the password as the coin name, but doesn't show in the dashboard, or the shell.

**Comment by RainbowMiner** [comment]
> It looks as if NLpool has port for specific coins? Wondering if they could be added?

Interesting point. Yes, it can be added. I will create a NLpoolCoins pool file

**Comment by RainbowMiner** [comment]
Only some coins have other ports, you will have to take care on your own. I added Nlpoolcoins for test purposes.
