### ISSUE TITLE
PhiPhiPool Benchmarking SonoA

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#294]
For some reason neither T-rex or ccminerTPruvotx64 will connect to this stratum. Not sure why, there's miners on there.

**Comment by RainbowMiner** [comment]
I'll check. If there are miners, hashrate and sonoa enabled in config.txt, it should connect.

**Comment by RainbowMiner** [comment]
It looks like the phi-phi-pool stratum has problems with it's sonoa port. I cannot connect neither. 
I will get into contact with the pool owner to find out the reason.

**Comment by talentoscope** [comment]
Ahh. Gotcha. Thanks dude 👍
