### ISSUE TITLE
Gox.cx balances

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#295]
Doesn't seem to be pulling XDNA from gos.cx - maybe others.

https://www.gos.cx/?address=XUaiUWVz7p7poXvux8cCGdNz7j2xPS7RWJ

![image](https://user-images.githubusercontent.com/22162766/48172720-e2d24d00-e2f8-11e8-8638-741427d56586.png)

**Comment by RainbowMiner** [comment]
I will have a look.

**Comment by RainbowMiner** [comment]
Bug fixed. Thanks for pointing this out!

**Comment by talentoscope** [comment]
Awesome! :)
