### ISSUE TITLE
Coinbase is Down with Error

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#296]
After restarting RainbowMiner I got that warning that Coinbase was down.  It then went to this:

cmdlet ConvertTo-LocalCurrency at command pipeline position 1
Supply values for the following parameters:
BTCRate:

I just closed out of it and restarted the program.

**Comment by RainbowMiner** [comment]
Yes, RainbowMiner depends on Coinbase being there. I am thinking about adding a fallback, so that it is always running, no matter what Coinbase says.

**Comment by RainbowMiner** [comment]
I added a fallback for the case that Coinbase is down. Plus more error checks to avoid getting stuck at ConvertTo-Localcurrency.
