### ISSUE TITLE
Monitoring with Awesome Miner

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#297]
I like to monitor my rigs with Awesome Miner, do you think RainbowMiner be configured to do that?  I'm thinking that it's not possible because with awesome miner not only do you have to know the ports but you have to tell awesome miner the actual mining program in use.  Obviously RainbowMiner is your first priority but I'm wondering if you've had any thoughts on this...maybe you have more in store for remote monitoring at rbminer.net

**Comment by RainbowMiner** [comment]
I will have a look into Awesame miner monitoring. Basicly, every data can be delivered and shown to rbminer.net, too.

**Comment by jch9678** [comment]
That would probably be the easiest solution for monitoring.  If you could combine the info at MiningPoolHubStats.com with monitoring from Awesome Miner, I can't think of anything else that a miner would want to know.  The main thing I use miningpoolhubstats is to get a combined payout for the last 24 hours.
