### ISSUE TITLE
[Feature] Display current coin income

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#299]
Would it be possible to add a current expected coinrate for those of us that do coins rather than autoexchange please?

Something like 2.58 DOGE/day displayed somewhere. Underneath the BTC profit on the web dash maybe? :)

**Comment by RainbowMiner** [comment]
:) Nice. Yes, this would be possible.

**Comment by talentoscope** [comment]
Closing this as it appears you can select coins now in the currency display in the config.
