### ISSUE TITLE
Main Status Running/Idle can the Command line info be wrapped to next line so everything is shown?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#3]
Main Status Running/Idle can the Command line info be wrapped to next line so everything is shown?

I am new RainbowMiner so slightly different from MPM which is fine.

Sometimes you want to see the whole command line that is being passed so that you can check if correct address and c=xxx is being applied.

Also in the same section under Device, it cuts out all the "R"s in the Device name.
![image](https://user-images.githubusercontent.com/801414/43488392-6d9831bc-94ce-11e8-961f-1016c124bfc0.png)

**Comment by RainbowMiner** [comment]
The cut-offs are a PowerShell feature, but I will see, what I can do.
In the meantime, you could look into the main logfile in path Logs. There is one, for every day. Their filename are in the form RainbowMiner_YYYY-MM-DD.
Example:
Logs\RainbowMiner_2018-08-01.txt

RBM

**Comment by RainbowMiner** [comment]
I added a wrap command, so that the commandline will be wrapped over multiple lines, if needed.
See here: 31e7b5d0461d8e79c29de997e60f115afae00cf7
