### ISSUE TITLE
[Feature] Display all non zero balances on web

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#300]
As in the title, it would be great to be able to see all non zero balances for each pool where BTC and USD are currently in the main dashboard page with total too across all pools.
Especially useful for those of us who mine coins to wallet :)

**Comment by RainbowMiner** [comment]
Yes, that would be really nice. The data is there, just not on the display. I will show it.

**Comment by RainbowMiner** [comment]
Done :)

**Comment by talentoscope** [comment]
You're too good dude ;) Thanks!!
