### ISSUE TITLE
Autostart in case of computer restart or crash

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#301]
Today, While i was out. somehow my computer got restart and i lost 11 hours or mining. 
So, I think it would be nice if we can setup autostart for rainbowminers at windows startup. So, In case if our computer get crashed or restart by any other reason. We don't need to worry about loss.

**Comment by RainbowMiner** [comment]
This is already possible. We have a FAQ for this:
https://github.com/RainbowMiner/RainbowMiner#how-do-i-add-rainbowminers-startbat-to-the-windows-task-sheduler-for-autostart

**Comment by RainbowMiner** [comment]
Actually I can totally recommend doing this. It is for peace of mind - I hate missing out mining time ⏯

**Comment by paulpoco** [comment]
Ok I tried this and set it to start even if my user hasn't logged in yet.  For when the PC or Windows decides to reboot on it's own in the middle of the night.

How do I get it still show the Rainboxminer Window after I have logged in?

**Comment by RainbowMiner** [comment]
> Edit: for now I can run as admin Stopp.bat and then run as admin start.bat

Good finding. Yes, like that it should work. I do not have a solution for you, yet. All my mining rigs have one user, only. Without password, so that they smoothly reboot into windows.

**Comment by platonicjesus** [comment]
Couldn't you just have your main user auto-login and set Start.bat in the startup items? Thats what I do on my rigs.

**Comment by jch9678** [comment]
I can't get this to work with the instructions.  I get this error  "An error has occurred for task Start RainbowMiner. Error message: One or more of the specified arguments are not valid.

/c "C:\Users\Name\Desktop\RainbowMiner\Start.bat"
C:\Users\Name\Desktop\RainbowMiner

Even if I delete the "Arguments" and the "Start in" I still get the same error.

@platonicjesus The instructions allow for RainbowMiner to be started with Elevated Privileges.

**Comment by jch9678** [comment]
Got it to work by using Create Task instead of Create Basic Task

Not sure why there was a difference.  Maybe it has to do with not being able to create a task with highest privileges by using a Basic Task.

**Comment by platonicjesus** [comment]
For me, since its a mining rig it doesn't matter. I have had the most consistent results with just throwing the start.bat into the startup folder, having my main account (which has admin rights) auto login and let the mining fly.
