### ISSUE TITLE
RBM doesn't start up miners when 2 devices active

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#302]
![image](https://user-images.githubusercontent.com/22162766/48286882-f1d30f80-e45e-11e8-81f5-273be6f9c316.png)

Should start CryptoDredge up, but it hasn't for some reason. Only just added cpu to the available devices so hadn't noticed this behaviour before.

**Comment by RainbowMiner** [comment]
Your machine is waiting for profitability. No miners will be launched, until it will be profitable, again. Just edit the config.txt and set "CheckProfitability" to "0" and off you go.

**Comment by RainbowMiner** [comment]
Oh! I see, what you mean. You would have expected that the only profitable miner would launch. Actually, at the moment, the total profitability is used to check, only.

**Comment by talentoscope** [comment]
I'll close the issue I just opened as I realised what I was actually asking for

**Comment by RainbowMiner** [comment]
Ok, this should work now. If, for any reason, this issue happens again to you, please do look at http://localhost:4000 -> Active Miners, click the "+" for the miner not being started and report back the contents of the details.
