### ISSUE TITLE
Bminer error

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#304]
I updated to the version 416.81 and is currently benchmarking everything, so I caught this error on Bminer

![image](https://user-images.githubusercontent.com/41829368/48288580-dd285480-e429-11e8-9b98-a26b9978144c.png)

**Comment by RainbowMiner** [comment]
Duh! Good to know. Thank you for the feedback!

**Comment by RainbowMiner** [comment]
I just updated the bminer API (currently testing, so wait a little, before doing an upgrade)

**Comment by RainbowMiner** [comment]
Ok, works good. I'll pack it in the upcoming release.
