### ISSUE TITLE
Pool fees not displayed

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#305]
Not sure if this is just a display issue or if it's calculated/pulled wrong, but bsod and gos.cx don't appear to show any Pool Fee in the powershell. When bsod isn't in the top 3 (I view in lite mode), the PoolFee table column disappears.

When bsod is there it shows a dash and the others with "..."

![image](https://user-images.githubusercontent.com/22162766/48295109-b6493d00-e480-11e8-8e83-c5a2bef7e1fa.png)

**Comment by RainbowMiner** [comment]
I'll have a quick look.

**Comment by talentoscope** [comment]
Correction on that, Ravenminer was so long and I'm displaying 3 currencies, it was still there, just off o the right. Taken it down to 2 currencies and still the same issue.

Thanks btw :)

**Comment by RainbowMiner** [comment]
Pool fee is transported correctly. It could be the case, that the digits, right of the decimal separator, have been "wiped out" by your Windows console. Since both pools, bsod and gos.cx take fees below one (in fact 0.9%).

**Comment by RainbowMiner** [comment]
Ah :D Ok. That was "in-sync". Ok, then everything is fine.

**Comment by talentoscope** [comment]
Sorry, it's my terrible native English mate haha!  It's actually still an issue. I'm just being a bit stupid not explaining myself properly :man_facepalming: 

![image](https://user-images.githubusercontent.com/22162766/48295479-083f9200-e484-11e8-9359-3370d4ffb0a3.png)

**Comment by talentoscope** [comment]
Re-reading what you said, you mean there's no leading zero? Ok that makes sense about truncation. If I could fine a cheap upgrade to Win10 I might be okay lol! Thanks for looking at this
