### ISSUE TITLE
[Feature] Centralised wallet info

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#306]
It's a little annoying having to go into every pool and manually add in a new wallet address for each coin. I get why you'd want to mine certain coins on certain pools, but would it also be possible to centralise the whole wallet address thing like with BTC?

That way, both options are catered for, main wallets that can be used by any (updated) pool with new coins with better ROI, and/or ones where they're kept per pool.

Loving the new release by the way!!!!!!! :)

**Comment by RainbowMiner** [comment]
> Loving the new release by the way!!!!!!! :)

Thank you! ❤️ 

Of course, the central coin wallet setup is a superb idea. I will implement that.

**Comment by RainbowMiner** [comment]
Such a nice feature! Thank you for this idea. It is done :)

**Comment by RainbowMiner** [comment]
Add default wallets to coins.config.txt

e.g. enter in coins.config.txt


    "RVN":  {
                "Penalty":  0,
                "MinHashrate":  "0",
                "MinWorkers":  "0",
                "MaxTimeToFind":  "0",
                "Wallet":  "yourRVNwalletaddress"
            },

.. then enter in pools.config.txt, section of the pool to add this wallet:

    "RVN": "$RVN",

Done :)

Every occurence of $RVN will be automatically substituted with your coins.config.txt default.

**Comment by RainbowMiner** [comment]
Also, I added this feature to the build in configuration Co[i]ns and [P]ools

**Comment by talentoscope** [comment]
Already?! Wow. 
I'll add them all in as you say into those two files. Was hoping it would be a simple variable fix :)
Thanks again again 😇

**Comment by jch9678** [comment]
Can't wait to try this out, will you be releasing a new version with this implemented or do you have a zip to drop in?

**Comment by RainbowMiner** [comment]
Ok, I release this now.

**Comment by jch9678** [comment]
Great! could you please give me an example of what a pools.config.txt would look like for a pool with multiple coins.  For example cryptoknight.cc will need several wallets...

**Comment by RainbowMiner** [comment]
Sure, here you go:

    "Icemining": {
      "RVN": "$RVN",
      "SUQA": "$SUQA",
      "Worker": "$WorkerName",
      "DataWindow": "estimate_current",
      "Penalty": 0,
      "Algorithm": "",
      "ExcludeAlgorithm": "",
      "ExcludeCoin": "",
      "CoinName": "",
      "CoinSymbol": "",
      "ExcludeCoinSymbol": "",
      "FocusWallet": "",
      "AllowZero": "0"
    },

**Comment by RainbowMiner** [comment]
Rule-of-thumb: 
- pools.config.txt: add line  `"CURRENCY": "$CURRENCY",`

**Comment by jch9678** [comment]
Thank you very much.

**Comment by talentoscope** [comment]
This is great, but I'm thinking maybe it half-solves the problem since we can just put the wallet address in there anyway.
My train of thought was something like

if $wallet.coin != ""
  config.pool = $wallet.coin

or something like that. Auto updating the pools.config if there is a set wallet for that coin already in the coins config.

The problem this solves in particular is when a new coin is released on one pool like Zpool and is already on another, say phiphi, then zpool will be updated automatically, and the profit checked without the user having to do anything at all. 
Keeps profit going in cases where this happens - and it happens a lot :)

**Comment by RainbowMiner** [comment]
Ah! I understand. Yes, that would be smart. I will implement that 🍺

**Comment by talentoscope** [comment]
Woohoo! :+1:

**Comment by jch9678** [comment]
This would be better but in my case when I mine at zpool, I like to be paid in BTC, not in the currency being mined.  Hopefully you can include an option to be continued to be paid in BTC at certain pools (e.g. zpool) but auto-filled at others who don't offer auto-exchange (e.g. cryptoknight).

**Comment by talentoscope** [comment]
Maybe a simple switch in the config between coinlist and a single coin would suit both and include other single coins per pool as well :)

**Comment by talentoscope** [comment]
That's what I meant, the switch being in the pool config. Since there's less than 10 supported at the moment, I don't think a simple yes/no will take much effort :)

**Comment by RainbowMiner** [comment]
We will need two switches: one in coins.config.txt to enable the automatic distribution of a coin to possible pools and a second in pools.config.txt to enable pools to accept these coins. I will do it :)

**Comment by talentoscope** [comment]
Amazing, thanks RBM! I'll grab this commit now.
AwesomeMiner is so far behind right now :rofl:

**Comment by jch9678** [comment]
Yes, thank you for implementing this.  It's great, wish I knew how to compile RainbowMiner :)
But I'm perfectly happy waiting for the release.

**Comment by talentoscope** [comment]
@jch9678 Just grab the commit zip file from GitHub and overwrite the directory. No need to compile :)

**Comment by talentoscope** [comment]
Lol. It's been a long 30-something years for some of us mate, don't worry 😂

**Comment by RainbowMiner** [comment]
@jch9678 just create your own parameter. Use something like "Info": "my info here",

**Comment by jch9678** [comment]
I will use "Info" thank you.  I also had the question about paymentid's. Should we use 'address.paymentid' for "Wallet"?

I have another issue that popped up as a result of adding many wallets, I'm not sure if you want me to create another issue because this one is closed but I'll write it here first.

I added over 20 wallets, almost every coin from cryptoknight.cc pool.  After RainbowMiner restarted it only benchmarked Haven, Graft, and Loki.  One possible explanation I thought of was that a pool might expect the algo name instead of it's 'exchange' symbol.  For instance, RTO (which is what I used in coins.config) did not benchmark but maybe the pool was looking for Arto?  

By the way Graft mined with the wrong algo, maybe that's a clue??

**Comment by RainbowMiner** [comment]
> Should we use 'address.paymentid' for "Wallet"? 

Yes, exactly

> I added over 20 wallets, almost every coin from cryptoknight.cc pool. After RainbowMiner restarted it only benchmarked Haven, Graft, and Loki. One possible explanation I thought of was that a pool might expect the algo name instead of it's 'exchange' symbol. For instance, RTO (which is what I used in coins.config) did not benchmark but maybe the pool was looking for Arto?

Wow! This sounds like a lot work. Rainbowminer will not benchmark each coin. It will benchmark each algorithm, so normally it should benchmark the following algorithms, at maximum:

      7 CnLiteV7 
      1 CnAlloy   
      1 CnArto
      7 CnV7 
      2 CnSaber
      2 CnHaven
      6 CnHeavy
      1 CnFast
      1 CnXTL
      1 CnV8   

The "Cn=Cryptonight", the number tells the number of coins, using this algorithm. This is perfect, because, for example, CnHeavy is the same speed for every of the 6 coins.

**Comment by RainbowMiner** [comment]
> By the way Graft mined with the wrong algo, maybe that's a clue??

I will check the algorithm, which is currently assigend to Graft.

**Comment by RainbowMiner** [comment]
> I have a couple more issues that resulted from adding the coins but I think I will just create new issues. If I'm wrong about creating them just let me know and I will add them here.

All fine :) I will find your questions so or so.

**Comment by jch9678** [comment]
Ah ok, If I understand correctly, this is a change your are going to make?  And I should just wait for it or did I do something wrong.  Sorry for making a lot of work for you, I am mentioning RainbowMiner on twitter and bct so hopefully you will get more users.  It does seem to be picking up, more issues = more users, I think

btw you already found the other 'issues' and answered them.

**Comment by RainbowMiner** [comment]
> And I should just wait for it or did I do something wrong.

You did everything right. I am currently checking all the coins / algos. There are some new coins.

>  I am mentioning RainbowMiner on twitter and bct

😊 thank you.

**Comment by RainbowMiner** [comment]
Done. I just uploaded a new Cryptoknight.ps1 pool file with all coins checked. Now everything should be fine.

**Comment by RainbowMiner** [comment]
>  Sorry for making a lot of work for you

Thank you very much for pointing at things and adding valuable ideas.

**Comment by jch9678** [comment]
A few things happened when I loaded the ps1 file:
The cryptoknight.ps1 file is throwing some errors so that pool never loads.  
Graft is still trying to use cnv7.  
I added the coins to miner.rocks but that pool also didn't benchmark any of the newer algos, just v8, v7, and heavy.
Here's my debug file.
[debug-2018-11-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/2579367/debug-2018-11-13.zip)

**Comment by RainbowMiner** [comment]
Ok, I will doublecheck the Cryptoknight. Regarding the new algos, too.

**Comment by RainbowMiner** [comment]
> the cryptoknight.ps1 file is throwing some errors so that pool never loads.

It seems that your download is corrupt. Try this to extract into your Pools folder.
[CryptoKnight.zip](https://github.com/RainbowMiner/RainbowMiner/files/2580152/CryptoKnight.zip)

**Comment by RainbowMiner** [comment]
.. or update to the new release :)

**Comment by jch9678** [comment]
Thank you, and whoops, I guess I thought the config.txt would update with algos.  It makes sense it doesn't however.

I now have 24 miners benchmarking, ha

**Comment by jch9678** [comment]
If possible can we get rid of 1 thread for srbminer?  I don't think there's any configuration that's optimized for that.

**Comment by jch9678** [comment]
Graft is still using v7 for some reason, strange

**Comment by RainbowMiner** [comment]
> If possible can we get rid of 1 thread for srbminer? 

Yes, we can :) Is it really of any use?

> Graft is still using v7 for some reason, strange

?! Strange. I will check

**Comment by RainbowMiner** [comment]
Try this SrbMiner.ps1 (extract into your Miners folder) and there will be no more 1-threads:
[SrbMiner.zip](https://github.com/RainbowMiner/RainbowMiner/files/2582775/SrbMiner.zip)

**Comment by jch9678** [comment]
I really don't think 1 thread is of any use.
I have not put in the new ps1 file but I noticed a couple other issues
BBS was not using the right algo with jceminer
and srbminer did not produce configs with Heavy and HeavyXHV for 2 threads. It only produced HeavyTube.  However it did produce all 3 correctly with 1 thread.

I'm not sure what mechanism RainbowMiner uses to choose algos for a coin but if it only has one list then each miner may use a different list.  For example variation 2 for jceminer might be xtl but variation 2 for srbminer may be v8.  Could this be a reason the wrong algos are chosen?

**Comment by RainbowMiner** [comment]
> Graft mining cryptonightv7

I checked the full path, from pool to miner everything is ok. But I got an idea: please check your Srbminer config file for "CryptonightV8" - check field "cryptonight_type". Eventually there is "normalv7". For CryptonightV8, there must be "normalv8"

**Comment by RainbowMiner** [comment]
> I'm not sure what mechanism RainbowMiner uses to choose algos for a coin but if it only has one list then each miner may use a different list.

Each RainbowMiner miner module is programmed, so that it matches the indiviual miner requirement, so every miner has it's own list.

**Comment by RainbowMiner** [comment]
> and srbminer did not produce configs with Heavy and HeavyXHV for 2 threads. It only produced HeavyTube. However it did produce all 3 correctly with 1 thread.

This may be related to the minimum GPU memory requirements I have put in place:
- 1GB for all cn lite variants
- 2GB for all cn normal variants
- 4GB for all cn heavy variants

**Comment by jch9678** [comment]
This file,  config_SrbMiner-2-GPU#00-CryptoNightV8-R9290X-2  contains this:

`{
  "cryptonight_type": "normalv8",
  "intensity": 0,
  "double_threads": false,
  "timeout": 10,
  "retry_time": 10,
  "gpu_conf": [
    {
      "id": 0,
      "intensity": 0,
      "threads": 2,
      "platform": "OpenCL"
    }
  ]
}
`

**Comment by jch9678** [comment]
This is what I have in the srbminer directory.  I have an address for Arto (RTO) so I don't know why that algo didn't benchmark for either 1 or 2 threads

Algo List from Above              Filename                                                                                           Type               
------------------------         -----------------                                                                                    --------
7 CnLiteV7                          config_SrbMiner-2-GPU#00-CryptoNightLiteV7-R9290X-2                 litev7
1 CnAlloy                            config_SrbMiner-2-GPU#00-CryptoNightXao-R9290X-2                     alloy
1 CnArto
7 CnV7                                config_SrbMiner-2-GPU#00-CryptoNightV7-R9290X-2                      normalv7
2 CnSaber                           config_SrbMiner-2-GPU#00-CryptoNightHeavyTube-R9290X-2 (?)    bittubev2
2 CnHaven                          config_SrbMiner-2-GPU#00-CryptoNightHeavyXhv-R9290X-2          italo (?)
6 CnHeavy
1 CnFast                              config_SrbMiner-2-GPU#00-CryptoNightFast-R9290X-2                   fast
1 CnXTL                              config_SrbMiner-2-GPU#00-CryptoNightXtl-R9290X-2                     stellitev4
1 CnV8                                config_SrbMiner-2-GPU#00-CryptoNightV8-R9290X-2                     normalv8

And this is the list you had me put in my coins.config

cnfast,cnfest,cryptonotehaven,cnheavy,cryptonightitalo,cnheavytube,cnhaven,cnlite0,cndark,cryptonightipbc,cnlitered,cnlite1,cnlite2,cnb2n,cryptonightmox,cnarto,cn1,cn2,cnalloy,cnxtl

This gets confusing.

**Comment by jch9678** [comment]
oh no  I lost my formatting

**Comment by RainbowMiner** [comment]
> Also I'm assuming the other configs for other algos weren't produced because I don't have coins for them but I'm not so sure.

Yes: if there is no wallet assigned to an algo, no config file will be created.

> This gets confusing.

The Cryptonight world is confusing. There exist so many different variants, and each week a new variant or coin pops up.

> 2 CnSaber------------------config_SrbMiner-2-GPU#00-CryptoNightHeavyTube-R9290X-2 (?)---bittubev2

Saber = CryptoNightHeavyTube = Tubev2

> CnHaven-----------------config_SrbMiner-2-GPU#00-CryptoNightHeavyXhv-R9290X-2--------italo (?)

Haven and Italo share the same cryptonight heavy variant, that is correct.

**Comment by RainbowMiner** [comment]
> oh no I lost my formatting
> edit: sort of fixed it

If this happens to your Rainbowminer config files: there is a Backup subdirectory in Configs. It will contain automatic backup copies for up to seven days.

**Comment by jch9678** [comment]
> If this happens to your Rainbowminer config files: there is a Backup subdirectory in Configs. It will contain automatic backup copies for up to seven days.

Oh actually I meant I lost formatting in my github post.

> Yes: if there is no wallet assigned to an algo, no config file will be created.

A Heavy algo config was made overnight.  I'm not sure why those 2 Heavy variants took longer to benchmark and make.  I still don't have a CnArto config, I do have a wallet address for Arto in coins.config

**Comment by RainbowMiner** [comment]
Status update: I have been discussing with the cryptoknight.cc pool owner and now I am looking forward a suitable API for RainbowMiner, so that we can significantly reduce the API calls and speed up things a lot :)

Regarding alloy: has this problem resolved? Have this been 100% rejected shares, or just some?

**Comment by RainbowMiner** [comment]
> A Heavy algo config was made overnight. I'm not sure why those 2 Heavy variants took longer to benchmark and make. I still don't have a CnArto config for either srbminer or jceminer, I do have a wallet address for Arto in coins.config

Oh :) I just forgot the main clue: this is due to overload on the pool's API. Just too many calls, so it takes unusual long for RainbowMiner to collect all data needed to give clearance to some algorithm. This is why I tried the way with an extended API at the pool.

**Comment by jch9678** [comment]
> Status update: I have been discussing with the cryptoknight.cc pool owner and now I am looking forward a suitable API for RainbowMiner, so that we can significantly reduce the API calls and speed up things a lot :)

That's great!

> Regarding alloy: has this problem resolved? Have this been 100% rejected shares, or just some?

I'm not sure if it has, I excluded Alloy in the config to keep downtime to a minimum.  It was all 100% rejected.  What is the best way to 'trick' RainbowMiner into thinking Alloy is the most profitable?  I can make a .bat file in the directory but that wouldn't test all the whole process of RainbowMiner.

> Oh :) I just forgot the main clue: this is due to overload on the pool's API. Just too many calls, so it takes unusual long for RainbowMiner to collect all data needed to give clearance to some algorithm. This is why I tried the way with an extended API at the pool.

I will monitor to see if a cnarto config has been created.

**Comment by RainbowMiner** [comment]
> What is the best way to 'trick' RainbowMiner into thinking Alloy is the most profitable?

Make it the "FocusWallet" :)

**Comment by jch9678** [comment]
I'm going to make a new issue to discuss why cryptoknight.cc and certain coins are not working for me.
