### ISSUE TITLE
Rig Crashes Includes Logs

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#309]
Could you take a look at these logs please?  I'm trying to narrow down why it keeps crashing.  I excluded ethash and it still crashes.  To me, it looks like it crashes after it switches to Nicehash from MiningPoolHub and then right back.  Can you think of anything why this would happen, could a big discrepancy of diff's between the 2 pools cause some stress?

[debug-2018-11-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/2570050/debug-2018-11-11.zip)

**Comment by RainbowMiner** [comment]
Difficult to say. I will scan through the logs and see, what is going on.

**Comment by RainbowMiner** [comment]
I'ld try to tweak the settings for CryptonightV8 in the SrbMiner's config files. Maybe open the 2-threads config file (config_Srbminer_...-2-CrypronightV8-<portnumber>.txt and set Threads from 2 to 1. Just to try :)

**Comment by jch9678** [comment]
Wow thank you.  
In the meantime I think a better solution would be for me to just set RainbowMiner to autostart on reboot.  Not sure if that's another clue but the entire computer reboots.  I've never seen it crash with my own eyes though.
