### ISSUE TITLE
New algos on NLpool

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#310]
From discoord channel: @everyone .... i added Unitus / Globalboost-Y and Sonoa in the pool.

Is RBM updated for these algos on this pool?

**Comment by RainbowMiner** [comment]
Yes, all data will be picked automatically. New algorithm need support from some miners, first, to start.

**Comment by ebojali** [comment]
Ok no update un the config files needed to be done by me?

**Comment by RainbowMiner** [comment]
No update needed :)
