### ISSUE TITLE
Stat file corruption and update

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#311]
Two issues, may be related:

Since a couple of days ago, I've noticed every now and again the profit stat file gets mangled and gets reset. Not sure why.

For some reason - maybe it's the new miner software, the two miners for PHI - CryptoDredge and the other one I forget - have their hashrates dropped after benchmarking. Not sure why. From like 10 to 7 per second. Because this is outside the allowed deviation, they keep being disabled :(

**Comment by talentoscope** [comment]
[debug-2018-11-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/2571811/debug-2018-11-12.zip)

Debug attached

**Comment by RainbowMiner** [comment]
I found a potential issue, which is related to extra long cycle calculation times. Let me try to find out, what takes the cycle so long (I suspect the balance API calls due to these many coins). After that I will add a fix for that.

**Comment by talentoscope** [comment]
It appears to only be PHI but I haven't seen all algos. The ones I have seem fine. Maybe PHI as an algo is highly dependent on system use? (It's a home PC, not a rig)

I think maybe you're right about the number of site API calls for all these coins. I'm on a 100mb line though. Might be the timeout for detecting dead pools (nlpool, phiphi and bsod have gone down in the last 48h). Just another thought, might help :)

**Comment by RainbowMiner** [comment]
Also, please give it a shot and increase the Interval from 60 to 120 seconds. Since it takes a long time to load and calculate all pool informations on your PC, It might happen, that the Watchdog is triggered too early because of a timer overrun.
