### ISSUE TITLE
Web "Active Miners over the past 3 days" sorted by minute, largest time at the top really wrong.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#312]
![image](https://user-images.githubusercontent.com/801414/48381121-5a083800-e68f-11e8-98e5-6f54261dbf72.png)

[debug-2018-11-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/2574050/debug-2018-11-12.zip)

**Comment by RainbowMiner** [comment]
Oh wow! 🍭 Looks like you are Neoscrypt millionaire! Yea, this number is far off. I will check this.

**Comment by paulpoco** [comment]
It is gone now.
