### ISSUE TITLE
Added Lots of Coins, RainbowMiner takes a long time to initialize

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#315]
After adding many coins, the time to start mining has significantly increased.  Just wondering if this is normal, no bid deal if it is.

**Comment by RainbowMiner** [comment]
Yes, this is normal. Reading the balances from the pools will eat up a large chunk of time, since every wallet needs an own API call. I recommend increasing the mining interval (actually, I am currently working on a solution with dynamic adapt of this interval).

**Comment by jch9678** [comment]
Oh great.  I can just wait for your implementation as I'm not totally sure what increasing the mining interval does.
