### ISSUE TITLE
Bminer crash

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#316]
Please review new version of Bminer crashed, 

![image](https://user-images.githubusercontent.com/41829368/48487506-abbdd900-e7db-11e8-9cde-21ac26e7150a.png)

![image](https://user-images.githubusercontent.com/41829368/48487552-ce4ff200-e7db-11e8-8149-ff921d2675d6.png)

**Comment by RainbowMiner** [comment]
Too bad. Maybe it became more sensible to overclocking.

**Comment by RainbowMiner** [comment]
I positively checked function on GTX1070 and GTX1080Ti - which GPU are you using?

**Comment by hernandn01** [comment]
more specific on equihash algo
![image](https://user-images.githubusercontent.com/41829368/48490711-42da5f00-e7e3-11e8-880e-a3a8fc8a6c17.png)

**Comment by RainbowMiner** [comment]
Do you have the time to send me the current "Debug file" out of http://localhost:4000

**Comment by hernandn01** [comment]
sure, there you go
[debug-2018-11-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/2581284/debug-2018-11-14.zip)

**Comment by hernandn01** [comment]
fixed with 3.8.13.10 thanks

![image](https://user-images.githubusercontent.com/41829368/49047348-6fec2180-f194-11e8-82a5-86562b051708.png)
