### ISSUE TITLE
Z-ENEMY VER 1.24 From: Dk & Enemy (z-enemy) 

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#317]
Z-ENEMY VER 1.24 From: Dk & Enemy (z-enemy) 

IMPORTANT:
For maximum performance make sure you have latest drivers  (ver. 415+)
http://www.nvidia.com/Download/index.aspx

- Major optimizations for skunk, polytimos and phi
- Minor optimizations for hex and x16r/s, tribus.
- Massive performance boost for RTX 2080/2080ti/2070 in many algorithims.

Other: 
- Highlighted hardware stats reporting, colored GPU temperatures (green/yellow/red)
- Added Volta architecture support

Windows:

Cuda 10.0(For 10x0 & 20x0 cards, new drivers ver 411+): https://mega.nz/#!QT5zmagJ!6IN9NyOXbvAdA3PWgNNW5eRx6MpdgS4piuVqJy5jM3w
Cuda 9.2 (For 10x0 cards and drivers over ver 397+): https://mega.nz/#!VboVTQYT!ePGTG8ogyzcEJgauiFALC4Mdf_ucYYI0KnLlgBq9Xv0
Cuda 9.1 (For 10x0 cards and drivers over ver 388+): https://mega.nz/#!Ve4nmIDb!9HCuiEBzD-eJQRGYLv8T2icbaNBO6NVTYXcmf_gTcl8

Linux: (HiveOS, PiMP OS , EthOS & Ubuntu):
Cuda   9.0 : https://mega.nz/#!UWwykKjY!p-ulLSsVEdQI42_A06LMuG2efsvJKunzgHDHuRiN3zo
Cuda   9.1 : https://mega.nz/#!tXwSmCBa!70ngpM_GeWQ0WzW-B7WXoiIuMZKk9dlVOKUs_5KTtQc
Cuda   9.2 : https://mega.nz/#!oWpxGYDQ!oQDVxhYo-Zx9nfK0P8ucNlQWclUyf_ZQA3fCsvaoVco
Cuda  10.0 : https://mega.nz/#!xWxX3CQQ!FUnpUYm-g74e-xbA7wmqREtGAS45pjf2SD4kpIsiYpA  @everyone

**Comment by RainbowMiner** [comment]
Thank you! I will upload it.
