### ISSUE TITLE
Script stops abruptly

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#319]
When I start start.bat, It looks like it start the PS script, But right when it says "Detecting Devices" the window simply closes out.

Posting Log files, But looking at them I am sure you will need more. Let me know.

I've also just updated the video drivers thinking that might resolve the issue. It did not.

**Comment by Yamanipanuchi** [comment]
[RainbowMiner_2018-11-14.txt](https://github.com/RainbowMiner/RainbowMiner/files/2582450/RainbowMiner_2018-11-14.txt)
[RainbowMiner_2018-11-14_11-18-16.txt](https://github.com/RainbowMiner/RainbowMiner/files/2582451/RainbowMiner_2018-11-14_11-18-16.txt)

**Comment by RainbowMiner** [comment]
Oh dear! That sounds not good. Since when is this happening?

**Comment by RainbowMiner** [comment]
Please try GPUtest.bat. Does this crash, too?

**Comment by Yamanipanuchi** [comment]
It started today as my system Re-started due to the recent MS Update (Yay!)

I tried GPUTest.bat. After about 2-3 seconds it simply says "Press any Key to continue...."

**Comment by RainbowMiner** [comment]
> It started today as my system Re-started due to the recent MS Update

Ah, my bad!
Eventually you could try to completely deinstall the graphic drivers, using the 3dguru's DDU and then install the newest drivers.

**Comment by RainbowMiner** [comment]
I do not remember, did you use Nvidia or AMD devices? If these have been Nvidia, you might want to extract this opencl.zip into your Rainbowminer folder, just to give it a try:
[OpenCL.zip](https://github.com/RainbowMiner/RainbowMiner/files/2582688/OpenCL.zip)

If it changes nothing, please delete the opencl.dll after the test.

**Comment by RainbowMiner** [comment]
I prepared a small test script, basicly the Get-Device function, but with all error traps disabled. With that we might be able to see a red error and eventually finding out more about this issue.
Just extract the following zip into your Rainbowminer folder and start GetDeviceTest.bat

[GetDeviceTest.zip](https://github.com/RainbowMiner/RainbowMiner/files/2582735/GetDeviceTest.zip)

What is being written to the screen?

**Comment by Yamanipanuchi** [comment]
OpenCL.zip no change.
GetDeviceTest.zip No information displayed, Just "Press any key to Continue..."

This is an Nvidia environment. I have an AMD System that is working perfectly.

I've used the 3dguru application to completely remove the Nvidia driver, Reboot, Re-installed the newest driver, Reboot and unfortunately same result.

**Comment by Yamanipanuchi** [comment]
Just downloaded the new release as if it were a completely new install and same issue. I hope I am the only one and if I am, I can just simply Re-load the OS.. Its a pain. Wont be able to do it till tomorrow. So im open for trying anything else.

**Comment by hernandn01** [comment]
What does it says under Device Manager? Make sure you select Show Hidden Devices. You may have to remove them if they are hidden so that It will detect them again? Which version of drivers are you using? 416.94 is newest haven't try that one since the previous 416.81make RainbowMiner rebenchmark everything. So for sure try 416.34, no problems there.

![image](https://user-images.githubusercontent.com/41829368/48518452-daad6c80-e826-11e8-8710-38a7ec4276c2.png)

**Comment by Yamanipanuchi** [comment]
![capture](https://user-images.githubusercontent.com/4724631/48518722-586d7a00-e81f-11e8-9c88-4f9b827044a5.PNG)

I had 416.34 when issue first came up. I elected to upgrade to 416.94 to see if it resolved the issue.

The cards are there, and have not shown any issues.

I suspect it may have been something with the windows update not jiving right.

**Comment by hernandn01** [comment]
yes, there is a security update on scripting, you probably can get away with removing the patch

https://support.microsoft.com/en-ie/help/4048955/windows-10-update-kb4048955

**Comment by Yamanipanuchi** [comment]
Yup, That did it! Well.. I removed the two most recent updates from yesterday KB4462919 & KB4467702.

I did not have the updates listed above. But you did lead me to trying to just remove the update. Thank you!

**Comment by hernandn01** [comment]
you are welcome

**Comment by hernandn01** [comment]
if this is a dedicated pc for mining, apply these tweaks including disabling windows updates

https://1stminingrig.com/best-windows-setup-configuration-tweaks-for-mining/

**Comment by RainbowMiner** [comment]
Wow. Good finding. Whatever has been the cause of this problem. I will try to dig further into this, to avoid this problem to happen in the future.
