### ISSUE TITLE
Separate option for cpu algo in config.txt

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#32]
It would be nice if we can specify which algos to mine for CPU

**Comment by RainbowMiner** [comment]
This is already possible.
- Go to "C"onfiguration -> "D"evices
- type "list" and return to find out about your CPU model device name
- enter the CPU model device name (or mark + right-click + right-click)
- here you go :)

RBM

**Comment by rinkal26783** [comment]
thanks. it's working. another thing that we have to add "DeviceName": "nvidia,cpu",in config.txt

**Comment by rinkal26783** [comment]
also, after the benchmark of cpu. CPU profit screen is gone
![image](https://user-images.githubusercontent.com/30832110/44478998-eab91400-a65c-11e8-9f02-5fe841bda741.png)

**Comment by RainbowMiner** [comment]
Oh, could you please send Config\devices.config.txt ? I will have a look (actually I have an idea, already)

RBM

**Comment by RainbowMiner** [comment]
Ok, found it: the devices.config.txt has been reset during startup. I will push a new release in some minutes. From then, the problem should be gone.
Regarding the YesPower disappearing from the list after benchmark: most probably the profit has been too low. There is a minimum profitability build into the lists.

RBM

**Comment by RainbowMiner** [comment]
Problem solved with the new RainbowMiner v3.8.3.1 release. Please update and go to configuration/devices again. 

RBM
