### ISSUE TITLE
Nlpool port issue o  hex (xdna)

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#320]
See pic.. please update port all shared are rejected

**Comment by ebojali** [comment]
![screenshot_20181114-224546_discord](https://user-images.githubusercontent.com/35561346/48514690-35fb5100-e85f-11e8-8156-50956f53bc6e.jpg)

**Comment by ebojali** [comment]
Realize this wasn't your fault.. pool issue an now it is resolved.. shares are accepted when pretty ward changed on website.. please close this one.

**Comment by RainbowMiner** [comment]
Yes, the pool API delivers all data, including the port. If it delivers the wrong data, we will be lost.
