### ISSUE TITLE
Xdna (hex) Profit way over pool payouts on nlpool

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#322]
Rbm profit and pool profit/ pay out for XDNA (hex) on nlpool does not match. Not even close.. I've talked to the pool owner, see conversation below. Ticket opened towards you instead.
![screenshot_20181116-225117_chrome](https://user-images.githubusercontent.com/35561346/48649328-966ec780-e9f2-11e8-80bb-afb4181f8f22.jpg)
![screenshot_20181116-225105_chrome](https://user-images.githubusercontent.com/35561346/48649337-9c64a880-e9f2-11e8-9806-d87486177801.jpg)

**Comment by ebojali** [comment]
![screenshot_20181116-225511_discord](https://user-images.githubusercontent.com/35561346/48649370-b605f000-e9f2-11e8-833d-c34c34ef014b.jpg)

**Comment by ebojali** [comment]
And please consider starting a discoord server.. 👌

**Comment by RainbowMiner** [comment]
Thanks for checking! Which data window do you use for nlpool? Actually, the calculation is quiet straight forward: API result * hashrate. So the value requested by the data window must be off limits.

**Comment by RainbowMiner** [comment]
![screenshot_20181117-084520_brave](https://user-images.githubusercontent.com/39437538/48658634-600e6800-ea45-11e8-8cef-763b885bb718.jpg)

**Comment by RainbowMiner** [comment]
So the key figure is to look at the data window. Look into you running configuration to check out. I am using estimate_current and for the moment the profit display looks accurate. 
It is a common problem with all yiimp pools: if the hashrate jumps, the estimates get out of balance. For that RainbowMiner does average to reduce this effect.

Anyway - I will rethink the method the average is being calculated, using some kind of cut off strategy, so that sudden and maybe short lived price jumps in the APIs of the pools can be compensated.

**Comment by RainbowMiner** [comment]
> Without checking this parameter settings I know I haven't changed it so it is using default setting for this.

Ok, good :) I had similar figures with my rigs, yesterday, I strongly suspect price jumps on the API disturbing the average calculation of RainbowMiner. My plan is:
- I add pool API price logging, so that we can easily figure out all price jumps
- based on that to use margins and derivation on the pool api prices
With that we would possibly be able to calculate away big jumps.

**Comment by RainbowMiner** [comment]
It would be good, if you could anyway look into the http://localhost:4000 Running Config and pick the data_window for this pool. Not that we miss this :)

**Comment by ebojali** [comment]
The peofit is constantly high for this coin so somethings doesn't add up if we have spikes it would mean they would have to be quite buge in order to have the avarage on 0.0019...

**Comment by ebojali** [comment]
![screenshot_20181117-095226_teamviewer](https://user-images.githubusercontent.com/35561346/48659271-c350c800-ea4e-11e8-87e1-f14e72f825ce.jpg)

**Comment by cryptowhizzard** [comment]
Hi all, i am out for most of the day, so feel free to contact me for data by discord. Xdna rewards and profit change a lot because of bitgun. With having bigger block rewards the profit spikes x 10 or x 20.

**Comment by RainbowMiner** [comment]
Ok :) I started a discord server: https://discord.gg/ZBNVWYY

**Comment by RainbowMiner** [comment]
@ebojali are you using EnableFastSwitching=1 or the default?

**Comment by RainbowMiner** [comment]
Look at these numbers, directly pulled from the pool's API for HEX:

    estimate_current = 0.01091 mBTC/MH/day
    estimate_last24h = 0.01237 mBTC/MH/day
    actual_last24h     = 0.00340 mBTC/MH/day

I just set DataWindow in the pools.config.txt to either "minimum-3" which always uses the lowest of the three values, or "average-3", which uses the average of the three values. This should give much more accurate numbers.

This is what we could add: automatic price penalty for each pool currency indivdually, derived from actual_last24h/estimate_last24h

**Comment by ebojali** [comment]
@RainbowMiner I use default setting 

> @ebojali are you using EnableFastSwitching=1 or the default?

U use default setting

**Comment by RainbowMiner** [comment]
Status update: I contacted NLpool regarding this issue and I already have a very good idea of how to deal with spikey currencies, like XDNA is one. For the time being I recommend setting the DataWindow to "average-2h" for nlpool. It will create quiet realistic price assumptions.

**Comment by ebojali** [comment]
In what file. Data window parameter is not included in pools.config

**Comment by ebojali** [comment]
In what file? Data window parameter is not included in pools.config

**Comment by hernandn01** [comment]
add it yourself

 "NLpool": {
    "BTC": "$Wallet",
    "Worker": "$WorkerName",
    "Penalty": 0,
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "FocusWallet": "",
    "AllowZero": "0",
    **"DataWindow": "average-2h",**
    "EnableAutoCoin": "0"

**Comment by ebojali** [comment]
Thanks..

**Comment by RainbowMiner** [comment]
> In what file? Data window parameter is not included in pools.config

Yes, this parameter has not been added automatically. The next release will add an empty string for all pools.

**Comment by cryptowhizzard** [comment]
This issue is solved on my side , i wrote the correct patch to fix this bug and submitted it to Github.

So as for NLpool you don't need parameters now. 

https://github.com/tpruvot/yiimp/pull/330

**Comment by RainbowMiner** [comment]
Super! Thanks a lot!
