### ISSUE TITLE
Zero balances shown

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#323]
They probably shouldn't be. Think these are remaining there due to having "Paid" amounts, but no actual balance. Should probably zero and then be removed from display (shell and web) when the actual balance is zero (as in, paid out).

**Comment by RainbowMiner** [comment]
Yes, it's because of the paid ammounts. I will remove them. Good point.

**Comment by talentoscope** [comment]
Thank you :)

**Comment by RainbowMiner** [comment]
Done. In deed, it looks much better now, without all those 0.00 - I will publish a release within 24h, containing this.
