### ISSUE TITLE
Feature Request: Also show the Nicehash Balance that has been paid.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#324]
Right now for Nicehash it shows the Balance that is unpaid.
Could it also show the Balance that shows up once you have reached 0.001 and they pay you and then you wait till that Balance is large enough to withdraw?

Call the current one NicehashUnpaid
Then the new one NicehashPaid

Will you need the setting read-only API key?

**Comment by RainbowMiner** [comment]
Good idea! I will check with Nicehash, if this is possible.

**Comment by RainbowMiner** [comment]
It is possible, if you supply RainbowMiner with API_ID and API_Key. I will implement the call soon.

**Comment by RainbowMiner** [comment]
Yes :) It is the ReadOnly API Key. Commit d62c33bc4a8eaff5858d9b52f3109fa8d120bd6d

This commit adds nicehash wallet balance, if API_ID and API_Key are provided in pools.config.txt

Please do add "Readonly API Key", only.
- log into Nicehash
- go to "Settings"
- click "API" (find the API ID and API Keys on this page)
- click "Get a new key" for "Readonly API Key"
- now add
    "API_ID": "[your API ID]",
    "API_Key": "[your Readonly API Key]",

in the Nicehash section of pools.config.txt

I will include this into the next release

**Comment by RainbowMiner** [comment]
Plus this commit cbb9f621243b6c46f99227f682aee7d4c87b230c , if you want input fields for API ID and API Key into the build-in configuration.

**Comment by paulpoco** [comment]
@RainbowMiner 

Ok I cannot get it to work.  It only still shows the current unpaid balance.

Do I need to take out the "-" in the key?

What about the [ ] brackets?
[debug-2018-11-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/2593175/debug-2018-11-18.zip)

**Comment by paulpoco** [comment]
[click "Get a new key" for "Readonly API Key"]
I already had a key in the Readonly API Key spot.
Do I actually need a new one?

I will try with a new one.

**Comment by RainbowMiner** [comment]
No, you should not need a new one. The "-" must stay, they are part of the key.
Sorry for the brackets - this has been to illustrate, only.

**Comment by RainbowMiner** [comment]
If you changed the config at runtime, it might take some time until the balance shows up.

**Comment by paulpoco** [comment]
Will it both balances added together or 2 separate lines?

ok waiting to see if it changes

**Comment by RainbowMiner** [comment]
> Will it both balances added together or 2 separate lines?

No, it will be a total sum, only. All unpaid currencies plus pending payments plus paid

**Comment by paulpoco** [comment]
Is there no way to have it 2 separate things.

I.e. stats to found out if you are getting close or over 0.001 BTC so Nicehash does a transaction to your Nicehash wallet on the unpaid.

Then the amount in the wallet that if it was over the widthrawal limit one might do a widthraw or wait for the next 0.001 transaction.

**Comment by RainbowMiner** [comment]
Ah! You are right, that would be nice. I'll figure something out.

**Comment by RainbowMiner** [comment]
I found a way :)
![image](https://user-images.githubusercontent.com/39437538/48678993-d23c9500-eb8a-11e8-970f-308505854041.png)
.. will upload the commit (and another release, so that you do not need to work it into your code on your own)

**Comment by paulpoco** [comment]
Ok did update, still only shows  
![image](https://user-images.githubusercontent.com/801414/48679130-1f941480-eb41-11e8-837f-096e6494103f.png)

**Comment by paulpoco** [comment]
The Balance it is only showing is an old value for undpaid.
![image](https://user-images.githubusercontent.com/801414/48679186-db554400-eb41-11e8-8b39-99924c70b1fe.png)
![image](https://user-images.githubusercontent.com/801414/48679191-e4deac00-eb41-11e8-8dbd-ec3ed8a64b13.png)

**Comment by RainbowMiner** [comment]
You will have to wait - the update uses quick start feature and reads everything from the cache.
But :) you may exit RainbowMiner and then start it again. I am very interested if it works (since I do not have paid balance at Nicehash currently).

**Comment by paulpoco** [comment]
Ok e[x]ited out and restarted, and still only the unpaid.
![image](https://user-images.githubusercontent.com/801414/48679271-186e0600-eb43-11e8-96b9-f62461dc6889.png)
 
![image](https://user-images.githubusercontent.com/801414/48679269-11df8e80-eb43-11e8-9e8c-413c6ed64624.png)

I can look again in 29 minutes.

**Comment by RainbowMiner** [comment]
Oh my! You do not have to wait. I forgot the object root for the API values. Sorry!
With this commit: b87902d5e232fdf639bc2238b5b0efca146bf886 you should be fine.

**Comment by paulpoco** [comment]
So it was using the MiningPoolHub API

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/48679401-a8607f80-eb44-11e8-9e6e-92ad358a333e.png)

**Comment by RainbowMiner** [comment]
🍻 Perfect! Thank you for the feedback.

**Comment by paulpoco** [comment]
@RainbowMiner Can I close this issue now?

**Comment by RainbowMiner** [comment]
Sure :)
