### ISSUE TITLE
Problems with cryptoknight.cc pool and certain coins

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#329]
I'm at a loss as to why I keep getting 100% rejects at cryptoknight.cc for certain coins.  So far those are:
Graft
BBS
Alloy
Lines

I just made Lines the Focus Wallet and RainbowMiner logs in correctly to the pool with the right port, the right mode/variation (v7), however srbminer gives the following error:
Target Length Abnormal

Retesting:
Graft, working now but speed is slower than xmr v8
BBS, invalid share difficulty jceminer suggests changing variation but it says cryptolight is selected.
Alloy, invalid share difficulty jceminer suggests changing variation but it says cryptonight-alloy is selected.

**Comment by RainbowMiner** [comment]
Eventually you could try to change the startup difficulty for these algorithms.
You would need to put in the wallet address into pools.config.txt and add your individual difficulty with a dot "." after the wallet address.

**Comment by jch9678** [comment]
They seem to be starting off with the right port for a gpu...

**Comment by jch9678** [comment]
I let RainbowMiner run for the last 10 days to see if an arto config would be produced and it would benchmark but that one never did.

**Comment by RainbowMiner** [comment]
Thank you for reporting on that. I found a fix for that. Just download this zip and extract it into the Pools folder:
[CryptoKnight.zip](https://github.com/RainbowMiner/RainbowMiner/files/2638913/CryptoKnight.zip)

**Comment by RainbowMiner** [comment]
Could you drop the current debug file, so that I can have a look?

**Comment by jch9678** [comment]
[debug-2019-01-07.zip](https://github.com/RainbowMiner/RainbowMiner/files/2733219/debug-2019-01-07.zip)

**Comment by jch9678** [comment]
I noticed that some wallets are not XXX'ed out.

**Comment by RainbowMiner** [comment]
```I noticed that some wallets are not XXX'ed out``` Oh! Thanks for the notice. I will have a look. 

Regarding the initial problem: check "Algorithm" in config.txt. You will have to add all the cryptonight algorithm. Currently, there are only "CryptoNightHeavy",  "CryptoNightSuperFast",  "CryptoNightV8".

You might want to include this, into your list:
```
CryptoNightFast,CryptoNightFest,CryptoNightHeavy,CryptoNightHeavyTube,CryptoNightHeavyXhv,CryptoNightHycon,CryptoNightLite,CryptoNightLiteDark,CryptoNightLiteIpbc,CryptoNig
htLiteRed,CryptoNightLiteUpx,CryptoNightLiteV7,CryptoNightLiteV8,CryptoNightMkt,CryptoNightRed,CryptoNightRto,CryptoNightSuperFast,CryptoNightTurtle,CryptoNightV7,CryptoNightV8,CryptoN
ightWebchain,CryptoNightXao,CryptoNightXtl,CryptoNightXtlV8
```

**Comment by jch9678** [comment]
Ah thank you. I forgot that step.

**Comment by RainbowMiner** [comment]
I have created a shorter version for you:
```
cnfast,cnfest,cnheavy,cnheavytube,cnhaven,cnhycon,cnlite0,cndark,cryptonightipbc,cnlitered,cnliteupx,cnlite1,cnlite2,cnb2n,cryptonightmox,cnarto,cnfaven,cnliteturtle,cn1,cn,cnwebchain,cnalloy,cnxtl,cryptonightstellitev8
```

**Comment by RainbowMiner** [comment]
You are welcome :)

**Comment by jch9678** [comment]
For my future reference I'm going to put the steps in here to copy RM to a new machine.
1) Copy coins.config.txt with all wallets
2) List CryptoKnight in config.txt
3) List Wallets in pools.config.txt
4) Add algos to config.txt

Thanks for the list and the help again.

**Comment by jch9678** [comment]
I just peeked at the machine that is benchmarking and saw that BBS seems to be submitting invalid shares.  I had this problem in the past.  I don't think it's a difficulty issue because it didn't work on one machine with 1 gpu and now doesn't work on a machine with many.

**Comment by jch9678** [comment]
I have several balances that are wrong at MinerRocks, actually I think all of them are wrong.

**Comment by jch9678** [comment]
xmr-stak fails because it is expecting "platform_index".  

Sorry to report all these at once...

**Comment by jch9678** [comment]
srbminer benchmarked cnheavyxhv CryptoKnightXhv twice.  it's the same speed otherwise I would think it's 1 thread vs 2 threads

**Comment by RainbowMiner** [comment]
Would you send me the current debug file, again, please? Then I will have a look into these problems.

**Comment by RainbowMiner** [comment]
Also, would you be so kind and send me one wallet address for one currency, that gives you wrong balances on MinerRocks?

**Comment by RainbowMiner** [comment]
```xmr-stak fails because it is expecting "platform_index".```
that's weird. Could you send me a zip of all *.txt files, that you find in ".\Bin\Cryptonight-Fireice250" ?

**Comment by jch9678** [comment]
[debug-2019-01-07_.zip](https://github.com/RainbowMiner/RainbowMiner/files/2733979/debug-2019-01-07_.zip)
Here's a Tube address:
bi1b95WYJRES7oBrvRo2eQV53ExLzFAzjKVM4wp9H9B6irCR6UuQxHf183XsJwemdoQm5PUHhQVwS67Hf5yUE7qg4SwbWv9nTQd8arQjSret1
[FireIce250.zip](https://github.com/RainbowMiner/RainbowMiner/files/2733984/FireIce250.zip)

**Comment by RainbowMiner** [comment]
Super, thank you. 

Problem 1: Fireice = solved
Problem 2: Minerrocks balances = solved
Problem 3: Srbminer duplicate HeavyXhv = solved

.. with new release v3.9.2.1

**Comment by jch9678** [comment]
Awesome, thank you.  As always you're the best.

**Comment by jch9678** [comment]
Just opened up that machine and it's mining BCD at nlpool and making $4,700 usd / day.

I wish.

**Comment by RainbowMiner** [comment]
Yeah, BCD slips through, from time to time, even though there is a price protection build in. I will get to the bottom of this and sharpen the protection.

 Eventually you should reset the profit history by deleting the file Stats\Profit.txt

**Comment by jch9678** [comment]
Will do.  Thanks

**Comment by jch9678** [comment]
Any thoughts on the BBS problem?

**Comment by RainbowMiner** [comment]
```Any thoughts on the BBS problem?```
Not yet, I am on it.

**Comment by jch9678** [comment]
Don't break your back on it.  It's not like BBS is a money maker.
