### ISSUE TITLE
Feature Request: MiningRigRentals add an option set a Rig as only GPU or only CPU?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#330]
Feature Request: MiningRigRentals add an option set a Rig as only GPU or only CPU?

Right now if I setup a Rig for YescryptR32 and I want it to be CPU, I don't think Rainbowminer will know which device is to be used.  You set your hash rate to rent on the website, if I set for the hash for CPU I don't want Rainbowminer to start using the GPU with a much higher hash rate than the CPU, this would give the Renter tons of extra hash for the cost of a lower CPU hash.

So maybe on MRR Rig Description, where you have [rainbowminer] add the option to have [rainbowminer,CPU] or [rainbowminer,GPU]?

**Comment by paulpoco** [comment]
> YesCryptR32

I tried that.  You cannot have 2 different rigs at the same time.   When I make it active, within a few minutes it get disabled.

**Comment by RainbowMiner** [comment]
This is already implemented, by now.
