### ISSUE TITLE
Lastest release version v is available

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#331]
is 'v' meant to hold the actual version number?

![image](https://user-images.githubusercontent.com/41829368/48954958-dbba5a00-ef08-11e8-8c5b-ac0c76d21daf.png)

**Comment by hernandn01** [comment]
it seems intermittent it is showing a version now, but is back again to 'v' only 
![image](https://user-images.githubusercontent.com/41829368/48957844-900fac80-ef18-11e8-9b4b-bf7f021dc508.png)

**Comment by RainbowMiner** [comment]
Fixed with commit c3b9dab5b39d8b87b84219d0fc792ecf16dafd8a
