### ISSUE TITLE
Central Monitor shows wrong time left on MiningRigRentals 48hr rental

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#332]
A 48hr rental started, RBM Central Monitor shows the wrong time left in the pool name.  Started Rental at 9:42pm. 

![screenshot_20181123-231311_chrome](https://user-images.githubusercontent.com/801414/48965617-a26c0380-ef75-11e8-98c7-5116787b7a44.jpg)

**Comment by RainbowMiner** [comment]
Fixed with commit b5d71592db0e8629101d9a996f04c79a7f2b1610
