### ISSUE TITLE
Issue: CCminer failures

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#333]
![image](https://user-images.githubusercontent.com/42227809/49030815-3ea42f00-f15d-11e8-9e69-1d4e93ed2446.png)

**Comment by Byrd1083** [comment]
[RainbowMiner_2018-11-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/2616672/RainbowMiner_2018-11-26.txt)
[Activity_2018-11-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/2616673/Activity_2018-11-26.txt)
[RainbowMiner_2018-11-26_09-22-32.txt](https://github.com/RainbowMiner/RainbowMiner/files/2616674/RainbowMiner_2018-11-26_09-22-32.txt)

**Comment by RainbowMiner** [comment]
Weird 👻 
The key information is this warning:
![image](https://user-images.githubusercontent.com/39437538/49035215-77bbbe00-f1b4-11e8-8dc1-c52f26b41064.png)

Obviously windows has locked that file for some reason.
- the 1st possible cure would be to restart RainbowMiner. If this vaccine doesn't work, a background process has crashed, and continues to lock that file.
- the 2nd cure is a windows restart to release the lock. This should work in any case.

**Comment by Byrd1083** [comment]
Okay, it went away on it's own. I restarted the rig and noticed it was not using cryptodredge like the other rigs. I deleted it and the stats for it as well. Know the same error pops up.

![image](https://user-images.githubusercontent.com/42227809/49042912-5809a300-f17e-11e8-8199-501dea317352.png)

**Comment by Byrd1083** [comment]
Fixed it. I had some kind of weird issue with Microsoft run time 2016. Had to re-download and restart know working.
