### ISSUE TITLE
Trex 0.8.1 on RBM 3.8.13.6 does not report hashrate on x16r

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#334]
At least on NLPool, There is hashrate at pool level

![image](https://user-images.githubusercontent.com/41829368/49033305-035d2c80-f16c-11e8-8c93-83ec460ef0e6.png)

![image](https://user-images.githubusercontent.com/41829368/49033362-36072500-f16c-11e8-9650-ebe734211d1b.png)

**Comment by RainbowMiner** [comment]
Strange! Try to manually trigger a rebench for Trex/x16r at http://localhost:4000/minerstats.html

**Comment by hernandn01** [comment]
![image](https://user-images.githubusercontent.com/41829368/49034752-09550c80-f170-11e8-967d-5606f8972123.png)

it wasn't showing any failed benchmark until I filtered by x16r and Trex now it is showing and have triggered them manually.

I have been seeing a strange behavior when rebenching newly updated miners, I had to come back and keep looking for failed benchmark and trigger them manually one by one

**Comment by RainbowMiner** [comment]
Ok, please keep me updated on that issue. I think (am pretty sure), it must have something to do with the combo building.

**Comment by hernandn01** [comment]
it did not kicked off the benchmark for the combos, and now they are not showing either as ok, failed benchmarked or as need benchmark

![image](https://user-images.githubusercontent.com/41829368/49040665-6d7fcc80-f180-11e8-86fb-cb899d3f9064.png)

**Comment by RainbowMiner** [comment]
Good. I changed the following (for the next release)
- if combo stats contain 0 automatically recalculate
- benchmarks will now properly reset combos
- localhost will no longer show combos on benchmark page

**Comment by hernandn01** [comment]
thanks will wait for the next release

**Comment by RainbowMiner** [comment]
Since combos are artificially calculated, those should not need to benchmark.

**Comment by hernandn01** [comment]
oh, it makes sense now

**Comment by RainbowMiner** [comment]
Ok - the v3.8.13.9 should do the trick 🔢

**Comment by hernandn01** [comment]
I am running 3.8.13.9 now. Should I rebenchmark so that combos have the correct value, or have they recalculated already?

**Comment by RainbowMiner** [comment]
Oh, sorry. I forgot to change one detail. I will push another release.

**Comment by RainbowMiner** [comment]
> I am running 3.8.13.9 now. Should I rebenchmark so that combos have the correct value, or have they recalculated already?

That's the detail 😄

**Comment by hernandn01** [comment]
the miner rebooted it, waiting for it to come back

**Comment by RainbowMiner** [comment]
Ok, new release v3.8.13.10 is now ready to go:
- will delete all combo benchmarks when updating to this version
- automatically delete combo benchmarks when benchmark is triggered

Another thing:
Actually, I had some problems on a Nvidia Gtx1050Ti and miner EnemyZealot. Sometimes that would reboot this one particular rig. If you get reboots from time to time (and you are using a Gtx1050Ti), consider adding EnemyZealot to "ExcludeMinerNames" in "devices.config.txt", section "GTX1050TI" for some time, just to find out, if the reboots disappear.

**Comment by hernandn01** [comment]
combos are working fine again, closing the issue now
![image](https://user-images.githubusercontent.com/41829368/49046679-26023c00-f192-11e8-8344-1566358b790e.png)
