### ISSUE TITLE
Instruction page needs edit.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#336]
Just happen to be glancing through the instruction/information page and noticed this.

Notes for the pools BlockMasters, HashRefinery, YiiMP, ZergPool, ZergPoolCoins and Zpool
                                                                                         ^^^^^^^^^^^^^^^^

**Comment by Yamanipanuchi** [comment]
Meant to point at the Zergpool, ZergPoolCoins

**Comment by RainbowMiner** [comment]
Oh! Yes. Thank you, for pointing this out.

**Comment by RainbowMiner** [comment]
Changed.
