### ISSUE TITLE
RBM reads wrong rental amount on MiningRigRentals

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#338]
RBM reads wrong rental amount on MiningRigRentals.

Here is the Central Monitor webpage:
![screenshot_20181128-221340_chrome](https://user-images.githubusercontent.com/801414/49203079-c0fa4200-f35b-11e8-93c6-3f9a87dae1cd.jpg)

Here is the rental rate that happens to be 24hrs:
![20181128_221554](https://user-images.githubusercontent.com/801414/49203107-e12a0100-f35b-11e8-9aed-5ff00e8f356a.jpg)

Here is the price set for the rig.  You can set this price, then get a rental, then change the rental price for next time it get rented after the current rental is done.
![20181128_221524](https://user-images.githubusercontent.com/801414/49203245-5b5a8580-f35c-11e8-9ce4-748263bedcab.jpg)

**Comment by RainbowMiner** [comment]
Interesting find! I will check that.

**Comment by RainbowMiner** [comment]
Ah yes, of course, now I remember: the price in rbminer does not reflect the rental price, but the moving average of the current pricing of your rig. Eventually it would be more clear, if the current rental's price would be used. I will check, if the mrr API allows that.

**Comment by RainbowMiner** [comment]
Found a solution :) Now, always the paid price of the renter is used, if a rig is being rented.
