### ISSUE TITLE
Using RM with VEGA and his hashrate drops

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#339]
Hi!
I have a VEGA 56 and I have the common problem of hashrate drop. I'm currently using SRB miner only (and mine XMR only), because it has two nice features: --resetvega and "min_rig_speed". The first parameter in the command line disables and re-enable the VEGA PCIe card, and the second in the algo config file sets a minimum hashrate to monitor (actually an 5' average) that could fire a miner restart (and if you have --resetvega, also a card restart). This is the only way of maintaing a constant high hashrate for me while using the computer for other tasks as it mines (if the miner is working fine and I don't use the computer, it stays high forever; the hashrate drops only when doing certain things, or if I leave the PC alone without mining for a couple of minutes).
I've tried MPM and the problem is that when MPM switchs miner, sometimes the VEGA go crazy and lower it hashrate. Also I can't use --resetvega because MPM thinks (as it should!) badly of a miner that restarts.
There are also some scripts out there that can restart the card. One uses devcon.exe, the other does not (from TheJerichoJones). This script should be executed prior miner (GPU) start in case the miner doesn't have it (I know that there is at least one other miner that has a watchdog, Cast XMR, but I get 100H/s more with SRB so I didn't test it; also it's a watchdog so if the miner starts with low hashrate, it won't detect any drop at all).
Is there a way to implement something like this in RM?

**Comment by RainbowMiner** [comment]
Hi Djago,
of course, this would be possible. If I understand you right, you would like to have two problems to be solved:
- an individual script to be executed prior to a specific miner start
- no errorflag, if SrbMiner restarts itself

The first one should be no problem at all, the second is a bit more tricky: what happens exactly? I suspect, it restarts itself in a new instance with new process id. If this is the case, it will be killed by the garbage collection. For that, I could implement something, that would act just like the "min_rig_speed" parameter. E.g. if the measured hasrate drops below xx% of the average, it could lead to a miner restart.

**Comment by RainbowMiner** [comment]
Is this a VEGA problem, only? 
If yes, I could include automatic card and driver restart into RB, by default.

**Comment by Djago** [comment]
> Hi Djago,
> of course, this would be possible. If I understand you right, you would like to have two problems to be solved:
> 
> * an individual script to be executed prior to a specific miner start

As this seems to be a problem realted to VEGA, maybe it has to be think as a solution to be execute prior any GPU miner

> * no errorflag, if SrbMiner restarts itself

Yes, 

> 
> The first one should be no problem at all, the second is a bit more tricky: what happens exactly? 

If I'm mining OK I get 1850H/s with SRB. Then if I do any of the following things (not always but probably will) hashdrop CAN happen:
* stop the miner, wait for a couple of minutes, run it again, or run other miner, like Cast or XMR
* ~variation: running MPM sometimes starts ok and then it drop hashrate in the middle of, say, benchmarking, or even mining (not the actual process of mining, but maybe while changing miner)
* watch a video while mining (local file or streamed like youtube, even some video ads!)
I didn't test it, but I suspect that anything related to poweruse the VEGA (like games, rendering,...) or anything related to wait (maybe power saving feature?). When the VEGA enter in this mode, hashrate drops to 1100H/s. And there's no way to go back to 1850H/s without any of this methods:

- suspend/resume and start mining right away
- restart the computer and start mining right away
- use SRB with --resetvega
- disable/enable card in device manager and start mining right away (this is tricky if you only have one card!)
- use a script to disable/enable card and start mining right away.

> I suspect, it restarts itself in a new instance with new process id. If this is the case, it will be killed by the garbage collection. For that, I could implement something, that would act just like the "min_rig_speed" parameter. E.g. if the measured hasrate drops below xx% of the average, it could lead to a miner restart.

That would be nice!

> Is this a VEGA problem, only?
> If yes, I could include automatic card and driver restart into RB, by default.

I don't know for other GPUs, I only have a VEGA and I only read about XMR mining so I can't tell. I can tell for sure that CPU mining is not affected (Ryzen 1700 with XMR-Stak, solid as a rock). And looking around I see lots of people having this issue with VEGAs (I supposte that's why doktor has implemente this solution in SRB miner (designed for AMD GPUs), and also Cast has something similar (Cast was designed only for VEGAs)

**Comment by Djago** [comment]
> Ok, then I would suppose the following:
> 
> * activate --resetvega for SrbMiner, by default. (If you know the switches of other miners, too, please tell me)

In Cast XMR there's a switch:

> --ratewatchdog
Add the --ratewatchdog option to let Cast XMR monitor the hash rate of the GPU, if a sustained drop in hashrate is detected the effected GPU will be restarted.

It's the same concept, but I've nevert tried it because Cast gives me 1750H/s and SRB gives me 1850H/s on the same config. And, as I said earlier, this watchdog doesn't solve the problem if the miner started already "lowered".

> * I add parameter "MinRigSpeed" to miners.config.txt: it will be absolute or in percent. If you put in "95%" it will detect hashrate drops below 5% from the benchmark, if you put in a number, it will measure against this exact value.

That's ok, SRB do this, but it compare the value against a 5' average (in fact, it's a customizable amount of time).

> * change the funcionality of the RBM build-in watchdog, so that it will not disable a miner, but reset it for xx times

...and when resetting the miner, also resetting the VEGA? SRB has this wired with the --resetvega, but if RM is having trouble with, say, XMR-Stak, then resetting the miner alone won't solve the issue.

> .. a better solution:
> 
> * activate --resetvega for SrbMiner, by default. (If you know the switches of other miners, too, please tell me)
> * we simply reuse parameter "FaultTolerance" (in percent)
> * I add parameter "EnableMinerReset" to miners.config.txt
> * change the funcionality of the RBM build-in watchdog, so that it will not disable a miner, but reset it for xx times, if flag "EnableMinerReset" is set to "1"

Nice, as long as also the VEGA is restarted...

Here:
[JerichoJones](https://github.com/JerichoJones/VegaMining) has the .ps that he devised to restart VEGAs. I think it narrows to:

> START /W PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& {Get-PnpDevice| where {$_.friendlyname -like 'Radeon RX Vega'} | Disable-PnpDevice -ErrorAction Ignore -Confirm:$false | Out-Null}"
TIMEOUT /t 5
START /W PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& {Get-PnpDevice| where {$_.friendlyname -like 'Radeon RX Vega'} | Enable-PnpDevice -ErrorAction Ignore -Confirm:$false | Out-Null}"

(I think maybe we need permission about this...)

**Comment by RainbowMiner** [comment]
Ok, I get ahead with that :) You would help me a lot, if you did the following:
- if not yet done, download Rainbowminer latest release and extract to some folder
- start the batch GPUtest.bat (with admin rights) and drop the resulting gputestresult.txt file

**Comment by Djago** [comment]
Sorry for the delay!
I've done it, and I get:
PS D:\CryptoCurrencies\RainbowMiner\RainbowMinerV3.8.13.14> .\GPUtest.bat
Out-File : Could not find a part of the path 'D:\CryptoCurrencies\RainbowMiner\RainbowMinerV3.8.13.14\Logs\RainbowMiner_2018-12-03.txt'.
At D:\CryptoCurrencies\RainbowMiner\RainbowMinerV3.8.13.14\Include.psm1:300 char:132
+ ... lText $Message" | Out-File -FilePath $filename -Append -Encoding utf8
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

Out-File : Could not find a part of the path 'D:\CryptoCurrencies\RainbowMiner\RainbowMinerV3.8.13.14\Logs\RainbowMiner_2018-12-03.txt'.
At D:\CryptoCurrencies\RainbowMiner\RainbowMinerV3.8.13.14\Include.psm1:300 char:132
+ ... lText $Message" | Out-File -FilePath $filename -Append -Encoding utf8
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

Done! Now please drop the file

D:\CryptoCurrencies\RainbowMiner\RainbowMinerV3.8.13.14\gputestresult.txt

onto your issue at https://github.com/RainbowMiner/RainbowMiner/issues

I'm uploading the file also...
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2641922/gputestresult.txt)

**Comment by Djago** [comment]
Great, should you need anything else, don't hesitate to contact me!

**Comment by RainbowMiner** [comment]
I would greatly appreciate, if you would try out the current RainbowMiner [master.zip](https://github.com/RainbowMiner/RainbowMiner/archive/master.zip) (it's prerelease v3.9.0.1) and see, if the VEGA reset works. It should restart the display drivers of the selected vega before miner (re-)starts.

For the next step, I will now reprogram the watchdog, so that it monitors hashrate and restarts miners, if it drops below some percentage.

**Comment by Djago** [comment]
I'm on it. Right now it's benchmarking, and the results are bad. SRB is giving me 1.05KH/s but the correct value should be around 1.85. Maybe it's not resetting the VEGA while benchmarking?

**Comment by RainbowMiner** [comment]
If the EnableResetVega is setup, it should reset the Vega.
- Did you trim the SrbMiner config files to your needs, already? You find them in the Bin\AMD-Srbminer folder.
- Would you send me your Debug file? You get there, by opening http://localhost:4000 in your browser and click on "Debug file" on the left side.

**Comment by Djago** [comment]
I've been testing and I've discovered that in some occasions even disabling/reenabling VEGA doesn't cure the illness. Sometimes I have to suspend/reboot, and even so, on some rare ocassions I have to reboot system completely. I don't know why but sometimes TeamViewer seems to break the thing, but most of the time the autoreset of SRB is enough (sometimes not).
Regarding your suggestions, SRB doesn't need any tuning for me, I'm getting the maximum hashrate that I can get without consuming too much power.
I've started start.bat with admin priviletes.
I'll send you the debug file tomorrow!

**Comment by Djago** [comment]
Sorry for the delay. I'm sending you the config. I don't have SRB on the miners list so I don't know what's going on...
[debug-2018-12-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/2674094/debug-2018-12-12.zip)
PS: I have updated RM because it asked me to do it. Is it ok? Is SRB the only miner that has to reset the VEGA? I'm asking because no resetting has happened during benchmark...

**Comment by Djago** [comment]
Hi!
Good news! Adrenaline 2019 seems to be working VERY good respecting to the hashrate drop. Since I've installed it I've seen a lot fewer drops.
I'm sending you the debug file, just in case. I didn't test it thoroughly  but plan to do so on the next few days. Right now I can use RM just fine!

[debug-2018-12-16.zip](https://github.com/RainbowMiner/RainbowMiner/files/2683233/debug-2018-12-16.zip)

**Comment by Djago** [comment]
Hi
I'm back. I've been very busy with holidays and Adrenaline 2019 didn't give me a break at all. Still lots of hashdrops. I'll try now with the new Adrenaline 19.1.1 and report back. tomorrow.
But the card reset seems to be working less and less frequently. Last thing I've tried with a 50% chance of working is to turn on HBCC and then turn it off in order to avoid suspend/resume or even reset, but it's working less and less frequently and I'm forced to suspend/resume most of the time. Sometimes I even have to reset twice to get high hashrate again :'(

**Comment by Djago** [comment]
I've tried excluding the incompatible miners in the config for that card, but the messages still appear

**Comment by Djago** [comment]
Using a second card as primary and VEGA without cables is much better. Hashdrops rarely occurs (on VEGA) although they still happen.
I'll report more later if something happens.

**Comment by Djago** [comment]
This secondary VGA is a game changer. Mining is WAY stabler now. I can freely use anything (didn't try a game, thou). Looking at task manager, the only process using the VEGA card is RM and switching miner didn't brake the thing. I'm testing now with the switch regarding VEGA reset disabled but it seems that in this setup I can't test this problem anymore! Yay!

**Comment by Djago** [comment]
I'm again with 1 VEGA, no secondary VGA. So I'm suffering again this problem. RM does not reset the card (or at least not properly) so I have to quit RM and run a script to reset it and then start RM again. Can we re-open the issue?

**Comment by RainbowMiner** [comment]
Which script are you using currently to reset the VEGA? Unfortunately, there is problem with the windows registry in combination with AMD GPUs. It's super complicated to detect the Cuda Id's.

**Comment by Djago** [comment]
One of them is using the exe made by gandalph3000 (of Cast... Cast seems to be death and the old page doesn't show the util anymore... I can send the file to you but if you plan to use it I think you have to ask him?):
> switch-radeon-gpu.exe --hbcc on --admin fullrestart
TIMEOUT 1
switch-radeon-gpu.exe --hbcc off --admin fullrestart

The other one is:

> DevManView.exe /disable "PCI\VEN_1002&DEV_687F&*" /use_wildcard
TIMEOUT 5
DevManView.exe /enable "PCI\VEN_1002&DEV_687F&*" /use_wildcard

It uses DevManView. It's a free utility from the great Nirsoft:
[https://www.nirsoft.net/utils/device_manager_view.html](url)

**Comment by RainbowMiner** [comment]
That's super :) I'll integrate the cast solution.

**Comment by RainbowMiner** [comment]
Download the current master.zip and extract everything into your Rainbowminer folder - now try again. Since I do not have AMD cards, the vega reset feature is untested. So please report back :)

https://github.com/RainbowMiner/RainbowMiner/archive/master.zip

**Comment by Djago** [comment]
Nice! It's working now! Every time Vega changes miner it resets the Vega card!
Thanks!!!!

**Comment by RainbowMiner** [comment]
Super 💯 thanks to your help.

**Comment by jch9678** [comment]
Was this implemented in 4.0.0.0?  If so it may not be working as well as it was before..

**Comment by RainbowMiner** [comment]
Hi, sorry, I just saw your comment. Is there some bad behavior happening, now?
The reset of vega devices has changed - it's now hbcc memory on, then off and reset of the GPU.

**Comment by jch9678** [comment]
Yes, there is some unwanted behavior now.  I'm not sure how to describe it other than it takes forever to start mining/switch algos and I think that interferes with benchmarking.  I have 2 vega machines and it's present on the one that has been updated to 4.0.x.  I much preferred the old way, but maybe the old way just didn't work and I don't need the switching at all, I don't know.  From way back I understood that the hbcc on off trick was not needed.  The real fix was disabling the gpus and then re-enabling them.  I'm pretty sure that is the case, but maybe djago is trying to accomplish something else.  Here's a debug file.

[debug_2019-03-28.zip](https://github.com/RainbowMiner/RainbowMiner/files/3018393/debug_2019-03-28.zip)

**Comment by RainbowMiner** [comment]
Woa! That is way too much. It's very obvious that the switching eats up the time.
Please try to disable the Vega switching feature in config.txt:
```
"EnableResetVega": "0",
```

**Comment by RainbowMiner** [comment]
Did this "EnableResetVega" setting to "0" help? 
Also, it would be super helpful, if you sent a current Debug file of the not-updated Vega machine, too.

**Comment by jch9678** [comment]
Just updated, it started mining right away on all cards and the switch to benchmark appears to have worked.  I'll just keep that setting off then and monitor it, maybe the name needs to be changed to ResetHBCC or create that new switch?  

While I have you here.....I'll get that debug file right now.

**Comment by jch9678** [comment]
Here's the 3.9.9.7 machine.
[debug-2019-03-28.zip](https://github.com/RainbowMiner/RainbowMiner/files/3018545/debug-2019-03-28.zip)

While I have you here, I'm still on 18.6.1 drivers, do you think the newer drivers are better enough to change.  I noticed on the main rainbowminer website I think you always link to the newest.

Also wildrigPreview includes all the previous algos, it's not just for Rainforest.  More importantly for me, it includes the auto flag is enabled/optimized for Hawaii cards.

**Comment by RainbowMiner** [comment]
Ok, super. Thank you for that debug file. It looks like the Vega reset fails with the old logic on your rig - that's why there is no delay during switching. I recommend you set "EnableResetVega" to "0" on this machine, too. Especially before updating to the newest RainbowMiner version.

If you like, you may try out the WildRigPreview with all algorithm enabled. Download the following file and unzip the WildRigPreview.ps1 into your miners folder. I would be very interested, if the algorithm work hassle free compared to the old Wildrig.

[WildRigPreview.zip](https://github.com/RainbowMiner/RainbowMiner/files/3018642/WildRigPreview.zip)

**Comment by RainbowMiner** [comment]
Regarding your driver-question: yes, I think the newer drivers are better. But I is hear-saying, only, since I do not have AMD cards to try them out.

**Comment by jch9678** [comment]
Thank you for your answers and the zip.

By the way when I manually update RM, a cmd window pops up for a split second and all I can see is that it says access denied 2 times before it disappears. What is that?

**Comment by hernandn01** [comment]
I've seen this too, kind of catch it, it tries to delete two 7z files. Maybe put an exception to not delete these files while is trying to decompress the new release?

**Comment by jch9678** [comment]
The WildRigPreview.ps1 worked fine on my test machine.  Some algos were definitely faster others about the same.

**Comment by jch9678** [comment]
Thanks hernandn01.

**Comment by Djago** [comment]
>  [...] The real fix was disabling the gpus and then re-enabling them. I'm pretty sure that is the case, but maybe djago is trying to accomplish something else. [...]

The thread was started because when mining XMR there's a serious problem with VEGA 56 & 64 (I don't know on FE and VII). Under certain conditions when you try to mine the hashrate drops to something around (or lower than) half of the full speed. I know for sure that this happens when mining XMR, _but I don't know for other cryptos_. I've dug on every thread I found on the web and currently there are only two **working** solution (apart from resetting the computer or suspending and resuming). Both involve something like, as you said, disabling the VEGA card. One solution uses a custom-made exe from gandalph3000 (creator of Cast, a miner for XMR) solely creted to solve this annoying problem. The other is a program created by Nir software made as an alternative to the Device Manager  that allows you, via command line, to disable/enable a device.
BUT this problem (at least for me) wasn't showing it's ugly head when I had a secondary display card (not VEGA). One of the conditions of this slowness seems to be that the VEGA is connected to a monitor and used to display a desktop.
I can't tell you if this problem is happening to you (at least not for other coins), but  for XMR if you use your VEGA as a mean to display the desktop, watch for your hashrate and you'll see. A single VEGA 56 or 64 should be near 1900H/s-2100H/s (assuimg a standard configuration with wattman). If you are getting something near 1100H/s then you are having this issue.
I _suppose_ that you can check for this same problem on other cryptos in the same way. Try to run the miner as a stand alone program and watch the hashrate. Compare it to other hashrate from other people and look for big differences. You can also try to stop the miner, run the lines that I wrote on a previous post and immediately re run the miner and compare again.
Since RM has implemented this solution (I think he added the exe from gandalph3000), I don't have this issue anymore (with XMR) so I suppose that _if_ other cryptos can show this issue, RM has solved it for all miners

**Comment by jch9678** [comment]
Thanks for the explanation, I believe we had 2 different situations and the solution to yours fouled up my machine because I had ResetVega set to 1.  I just assumed I needed it because it's a Vega machine. When Vegas first came out the drivers wouldn't work properly in a multi card system.  The first solution was to manually turn off hbcc and then turn on hbcc, or vice versa.  This allowed all the cards to work at the same time.  It was soon discovered that this only reset the driver and the hbcc part was irrelevant. The disabling / enabling of each card could be automated by devcon or similar programs, then this was integrated into srbminer.  This is what I thought setting ResetVega to 1 enabled, the srbminer fix. I thought it was working properly in RM but it wasn't working at all and I'm sure the newer drivers fixed the problem so I never noticed.  
I do remember the problem you are/were having and I did encounter it but I moved my primary graphics to onboard and that took care of that. Glad to see it worked out for both of us.
I see that you mentioned you use Wattman, you should try overdriventool instead of opening up wattman.  You can just create a .bat to point to the profile to use for each card.  This is the one srbminer used to have on his website for Vega 56 and I still use it.
[Profile_7]
Name=SRBMiner
GPU_P0=852;800;0
GPU_P1=991;900;0
GPU_P2=1138;950;0
GPU_P3=1269;1000;0
GPU_P4=1312;1050;0
GPU_P5=1474;1100;0
GPU_P6=1538;1150;0
GPU_P7=1448;930
Mem_P0=167;800;0
Mem_P1=500;800;0
Mem_P2=700;900;0
Mem_P3=908;930
Fan_Min=4000
Fan_Max=4900
Fan_Target=75
Fan_Acoustic=2400
Power_Temp=85
Power_Target=0

Probably could use some tweaking but it's stable for me and I get around ~1900 h/s

**Comment by Djago** [comment]
Sorry for the delay @jch9678! I've tried ODnT but since wattman worked well for me, I didn't see any reason not to use it, so here I am, getting 1950 H/s with TRM ;)
Anyway right now I'm trying to configure RM to let it mine more coins than the default ones (GRIN, BEAM, SWAP, ...).
Still, for my VEGA, CNR is the most profitable coin to mine, but those three are also profitable and have, to my understanding, a brighter future than XMR (but I'm diversifying my portfolio).

**Comment by jch9678** [comment]
Yeah XMR is generally the most profitable for me with Vegas as well.  I guess for you it doesn't really matter if they are the most profitable at any given moment, just mine whatever you think will work out the best in the long run.

**Comment by Djago** [comment]
But RM will mine the most profitable at any given moment and the pools with auto convert feature will convert to whatever you say (for example, "what you think will work out the best in the long run"). So you have the best of both worlds, profitability in the mining (short term) and then store it in the coin you think will fluorish.
It could also happen that VEGAs are proficient with XMR but, say,  BTC is taking the lead, so it's best to mine XMR and convert BTC.

**Comment by jch9678** [comment]
Yep agreed. I have my auto conversions set to BTC in mph and zpool and zergpool because I need that crystal ball.  Sadly I don't have time to trade my earnings on a daily basis if I were to mine grin, swap, and the smaller cryptonight coins. ( but those really only apply to my old r9 290x cards ).
