### ISSUE TITLE
CPU mining

### ISSUE THREAD

**Issue by RetroShag** [RainbowMiner/RainbowMiner#34]
Is it possible to add a question how many thread to run for cpu mining during setup? 

Also, a suggestion for cpuminer-opt and derivatives add an argument --cpu-affinity AAAA.  This spread the load across all available cores to maximize the amount of L2/L3 cache used.  With Ryzen7, I usually run 12 threads across 16 "cores".

**Comment by RainbowMiner** [comment]
Very good idea - I will think about how to do it.

**Comment by Byrd1083** [comment]
I agree would be nice. For example you get higher hash rate on i7 and cryptonightv7 with no hyper threading. Would need to list only real cores for maximum hash rate.

**Comment by RetroShag** [comment]
I run 75% threads and affinity command will maximize the use of L2/L3 cache.
These are the argument I use with cpuminer-opt --randomize --cpu-priority 0 --cpu-affinity AAAA --quiet

**Comment by RainbowMiner** [comment]
#160
