### ISSUE TITLE
Question: MiningRigRentals

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#340]
What's the best way to troubleshoot setting up MiningRigRentals. I followed the instructions you have but I was unsuccessful.

**Comment by RainbowMiner** [comment]
- check, if you have added a description to your MRR rigs, containing your worker's name in [ ]
- check, if your pools.config.txt: API_Key, API_Secret and User are setup?
- check, if MiningRigRentals is on PoolName, but not on ExcludePoolName in config.txt

.. and, send me the current Debug file. I will have a look.
