### ISSUE TITLE
No displaying correctly?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#341]
GeForce GTX 1080 Ti (GPU#00,GPU#01)
===================================

Miner          Fee Algorithm       Speed Power    BTC/Day  USD/Day  Accuracy Pool     PoolFee
-----          --- ---------       ----- -----    -------- -------- -------- ----     -------
Trex         1.00% X16S       56.96 MH/s  363W -0.00001284  -0.0546      82% NLpool     0.10%
CryptoDredge 1.00% Skunk     136.45 MH/s  362W -0.00013745  -0.5848      90% NiceHash   2.00%
CryptoDredge 1.00% X16R       49.69 MH/s  361W -0.00009640  -0.4101      82% NLpool     0.10%

   Status: Running

 Last Speed Active                      Launched Miner           Device      Power Command
 ---------- ------                      -------- -----           ------      ----- -------
137.53 MH/s 00 Days 00 Hours 02 Minutes Once     CcminerAlexis78 GTX 1080 Ti 352W  Bin\NVIDIA-Alexis78\ccminer.exe -R 1 -b
                                                                                   10200 -d 0,1 -a lyra2v2 -q -o
                                                                                   stratum+tcp://mine.nlpool.nl:4533 -u

In the list at the top shows negative profits, although the system IS mining something that is profitable. Good that found the profit, Its just not displaying it correctly in the list.

**Comment by RainbowMiner** [comment]
Looks like a sort issue with negative values. I will have a look.

**Comment by Yamanipanuchi** [comment]
This has been resolved.
