### ISSUE TITLE
Tribus, Might be a bug?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#342]
I get this only on one machine... It has been happening over and over. I am going to simply disable to algo for now. Wanted to make sure it was not a bug though.

CcminerTpruvot | Tribus | BlockMasters-SCRIV | BTC | GTX1080 | 0.00710065 | 30.90 | 60.59 MH/s | 12.78 GH/s | 127 W | for you

Getting 60.59 MH, Bench says 12.78 GH

**Comment by RainbowMiner** [comment]
Oh! Thank you for reporting this. I will have a look.

**Comment by Yamanipanuchi** [comment]
CcminerTpruvot | Allium | NLpool-GRLC | BTC | GTX1080Ti | 0.29796133 | 1296.74 | 20.54 GH/s | 20.76 GH/s | 25 W | for you

 Just found a different machine doing this? Same mining software.

**Comment by Yamanipanuchi** [comment]
That lastone might just be odd numbers for the pool though.

**Comment by Yamanipanuchi** [comment]
GeForce GTX 1080 Ti (GPU#00,GPU#01)
===================================

Miner            Fee Algorithm      Speed Power    BTC/Day    USD/Day  Accuracy Pool             PoolFee
-----            --- ---------      ----- -----    --------   -------- -------- ----             -------
CcminerTpruvot     - Allium    20.73 GH/s   24W  0.37523843 1,479.5651      87% NLpool-Garlicoin   0.25%
EnemyZealot    1.00% PHI2       4.87 MH/s   60W -0.00002156    -0.0850      82% NLpool             0.10%
Trex           1.00% X16S      57.20 MH/s  363W -0.00002475    -0.0976      85% NLpool             0.10%

I keep getting these readings similar to what is seen on NLpool-Garlicoin. I've gotten this on several PC's and it typically it NLpool, BlazePool and BlockMasters. From what I can tell it is when using the CcminerTpruvot miner software. It is not always the same Algo though.

I know the issue has been marked, Just wanted to add more info to possibly hunt it down.

**Comment by RainbowMiner** [comment]
Thank you very much. This is very weird! It look like, the CcminerTpruvot has some problems in it's cuda10 version on GTX1080(ti). I will prepare a fallback module and upload it later, today. Eventually, that helps :)

**Comment by RainbowMiner** [comment]
Would you be so kind and try the following miner file with one of the rigs, these strange hashrates appeared?
[CcminerTpruvot.zip](https://github.com/RainbowMiner/RainbowMiner/files/2648581/CcminerTpruvot.zip)

Just extract CcminerTpruvot.ps1 into the Miners folder and do a rebenchmark.

**Comment by RainbowMiner** [comment]
I downgraded this in the new release already. Let me know, if the strange exagerated hashrates do appear again. If yes, I would recommend you put the CcminerTpruvot on the "ExcludeAlgorithm" list in config.txt

**Comment by Yamanipanuchi** [comment]
I have not seen this issue resurface in the last few updates. So I haven't been prompted to come back here and follow up. Sorry.
