### ISSUE TITLE
Feature request: show current Pool withdrawal fee with Balances

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#343]
Feature request: show current Pool withdrawal fee with Balances

This is mainly for MiningRigRentals as their withdrawal fee varies wildly.  Today it is an insane 0.000221 BTC and lower times are 0.000116 BTC.
Not sure if you can pull that from MiningRigRentals API?

![screenshot_20181201-104820_chrome](https://user-images.githubusercontent.com/801414/49331773-59104b00-f557-11e8-9890-e612ae7fdc1e.jpg)

**Comment by RainbowMiner** [comment]
I'll try :)

**Comment by paulpoco** [comment]
I will have to check if MiningRigRentals withdrawal fee is a flat % of amount to be withdrawn or just market conditions?  Now the rate is 0.000326 BTC.

**Comment by RainbowMiner** [comment]
It is market conditions. I will find out :)

**Comment by paulpoco** [comment]
Now it is 0.000576 BTC.  That is 3.14 CAD.  I guess I will wait for it to go back down.

**Comment by RainbowMiner** [comment]
Yes, I found a message from 2018/07/07
> merc07/07/2018
Our transaction fees scale automatically based on the average fees that we're paying at the time.. it lags behind the 'general bitcoin' transaction fee -- both on the way down and on the way up as it uses OUR transactions to average out the fee required.
