### ISSUE TITLE
Update deleted Files

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#344]
Is there a backup of files in the miner directories?  

One of the updates deleted all my optimization files and optimization notes in the srbminer and wildrig directories?  Everything went back to default, even 1 thread settings came back for srbminer when I think you got rid of those....

:(

**Comment by RainbowMiner** [comment]
Oh dear! I am so sorry for this. Normally, all updates should conserve all files named ["amd*.txt","cpu.txt","nvidia*.txt","config_*.txt"]. Those should have been backed up and then moved back into their folders, after a SrbMiner update.

Did the configuration files have names, that did not match the file list?

Eventually, you could try some undelete tool, look into the Bin folder and try to find "AMD-Srbminer.bak" and "AMD-Wildrig.bak"

For the future:
- are there file names, that you would like to have on that backup list?
- I will add a function, that will copy those protected files to a backup folder, just in case
- will double-tripple check the backup process, so that your files will be save.

**Comment by RainbowMiner** [comment]
For the single thead srbminer, please extract this zip into your Miners folder:
[SrbMiner.zip](https://github.com/RainbowMiner/RainbowMiner/files/2636388/SrbMiner.zip)

I will add a new setting to the pools.config.txt /SrbMiner section, where you may select 1,2 or both threads for this miner, with the next release.

**Comment by jch9678** [comment]
It was actually both scenarios. My optimized config_*.txt files were deleted from the srbminer directory.  And I did have miscellaneous files in the directories that were deleted.  For example WildRig_x22i.bat was deleted.  In order to test and optimize I just use the miners in the bin file so I don't have to download the miner again.  I keep notes, configs, and bats in there that aren't relevant to RainbowMiner.  That explains why the misc files were deleted but not why I lost all optimized configs for srbminer.  
If you want you can create another wildcard that I can name my personal files so they won't be marked for deletion. Maybe test_*.txt or another word you choose.

Regarding the number of threads per pool setting, that would be nice.  I think srbminer is the only miner where this problem occurs.

**Comment by RainbowMiner** [comment]
Ok. I feel very sorry about your SrbMiner config files and I will find out, what happened. Maybe there is some special structure in the miners's zip file. I will check this.
But you could try an undelete toll. That might recover the files. A .bak directory is being created with the update, that holds the old Miner files. This directory is being deleted afterwards.

Oh. Actually, this would be an idea: I will no longer delete these backup folders after the update. With that, you always have one backup, if anything fails.

Also, I will add custom wildcards to the config.

**Comment by jch9678** [comment]
It's ok, I think I have handwritten notes that I can recreate them with.

That's a good idea to have a backup, though maybe we need more than one set?  Only one set may not have helped me because I just updated a few times and assumed all the configs were ok so didn't check.  Not sure on which update they got deleted.

**Comment by RainbowMiner** [comment]
Ok, added :) 
- The next release will autocreate a new config file "Config\minerconfigfiles.txt". You may add as many user defined miner config files (including wildcards) as you like (one each row). Those config files will be protected during miner updates.
- Also, RainbowMiner will create upto three backups of the complete miner's Bin-folder, before updating.
