### ISSUE TITLE
Feature Request: have a setting AutoAddNewAlgo

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#345]
New Algos get added every now and then.   Would nice to have the new Algos just auto added to config.txt.

**Comment by RainbowMiner** [comment]
Yes, that would be nice. I will add this.

**Comment by RainbowMiner** [comment]
Added. 
- "EnableAutoAlgorithmAdd": if set to "1", all newly added algorithm will be added to the config.txt automatically, during (automatic) update. Be aware, that this is not a runtime feature, so if you manually update the algorithms.json file in the Data folder, nothing will happen. The update is being executed during update of RainbowMiner (you may emulate an update by downloading the current [Cleanup.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Cleanup.ps1) to your RainbowMiner folder and then restart RainbowMiner)
