### ISSUE TITLE
Nicehash added ZHash

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#346]
![image](https://user-images.githubusercontent.com/801414/49334843-a6f77400-f594-11e8-9457-e213d7e117d3.png)

**Comment by RainbowMiner** [comment]
Yes, I will have to adapt the params a bit.

**Comment by RainbowMiner** [comment]
Ok, that should work now with the updated Bminer.ps1 and Ewbf.ps1
