### ISSUE TITLE
Worker not authorized - MiningPoolHub

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#347]
I don't think is working adding something else to the worker name on MiningPoolHub. Maybe disable this feature for this pool only?

![image](https://user-images.githubusercontent.com/41829368/49348362-37e85100-f662-11e8-8d0f-b80e5d8b42f0.png)

m 18:44:31 main     ethminer 0.17.0-rc.0
 m 18:44:31 main     Build: windows/release
cu 18:44:31 main     Using grid size: 8,192, block size: 128
cu 18:44:31 main     Found suitable CUDA device [GeForce GTX 1050 Ti] with 4,294,967,296 bytes of GPU memory
cu 18:44:31 main     Found suitable CUDA device [GeForce GTX 1050 Ti] with 4,294,967,296 bytes of GPU memory
 i 18:44:31 main     Configured pool us-east.ethash-hub.miningpoolhub.com:17020
 i 18:44:31 main     Api server listening on port 30100.
 i 18:44:31 main     Selected pool us-east.ethash-hub.miningpoolhub.com:17020
 i 18:44:31 Api      New API session from 127.0.0.1:56193
 i 18:44:31 stratum  Stratum mode detected: STRATUM
 i 18:44:31 stratum  Subscribed!
 i 18:44:31 stratum  **Worker not authorized hernandn**
 i 18:44:31 main     Disconnected from  [18.204.40.75:17020]
 i 18:44:32 main     No more connections to try. Exiting...
 i 18:44:33 main     Terminated!

although I cann see the worker on the pool page, it is not working, would you pleease review?

![image](https://user-images.githubusercontent.com/41829368/49348843-10df4e80-f665-11e8-960c-f1881ee85fe9.png)

**Comment by RainbowMiner** [comment]
Ok, it seems to be a combination; no work found at miningpoolhub and the ethminer v0.17.0-rc0. I downgraded to the ethminer v0.17.0-alpha1, this seem to work fine.
