### ISSUE TITLE
Feature: Auto Benchmark new miners.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#349]
Have a setting to auto benchmark new miners. Mainly so it does not need to be done periodically.

**Comment by RainbowMiner** [comment]
Ok, I will add this to the next release.

**Comment by RainbowMiner** [comment]
Added (will be in the next release v3.9.0.0)
Set parameter "EnableAutoBenchmark" in config.txt to "1" to trigger automatic benchmarks of updated miners.

**Comment by RainbowMiner** [comment]
I must admit, that I love this feature ❤️ Thank you for this idea!
