### ISSUE TITLE
Feature request: add gminer 1.10

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#350]
https://bitcointalk.org/index.php?topic=5034735.0

**Comment by RainbowMiner** [comment]
I will check this miner.

**Comment by petrovsky34** [comment]
OK)) faster zhash

**Comment by RainbowMiner** [comment]
Ok, I tested your miner. If you solve the following issues, I will consider adding gminer:
- not compatible with RTX nvidia
- miner stops, if problem with dev fee pool
- heavy CPU load on weak machines

**Comment by RainbowMiner** [comment]
If these bugs are fixed, please reopen this issue.

**Comment by petrovsky34** [comment]
(((((((

**Comment by petrovsky34** [comment]
added gminer folder MinersOldVersions please???

**Comment by RainbowMiner** [comment]
Ok, I will add this miner to MinersOldVersions, but please be careful!

![image](https://user-images.githubusercontent.com/39437538/50220316-56548900-0392-11e9-8e30-a961b3e43511.png)

**Comment by petrovsky34** [comment]
ok

**Comment by RainbowMiner** [comment]
I reconsidered after testing and added it to the default Miners folder. If you want to use it adhoc,, update RainbowMiner to v3.9.0.9 and then download [master.zip](https://github.com/RainbowMiner/RainbowMiner/archive/master.zip) and copy 
```
APIs\Gminer.ps1
Miners\Gminer.ps1
Data\minersha256.json
```

to your RainbowMiner folder and restart.
