### ISSUE TITLE
3.9.0.1 not able to rebench new miners!

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#352]
Not possible to rebench miners in the latest release.. 0 stats files are removed everytime I try, see pic.
![image](https://user-images.githubusercontent.com/35561346/49579307-21851280-f94c-11e8-8d8b-7a3476acbc72.png)

I had to run TouchBenchmark bat file in order to get everything OK.

**Comment by RainbowMiner** [comment]
Oh dear! I will have a look at once.

**Comment by RainbowMiner** [comment]
Thank you! I fixed it.
