### ISSUE TITLE
Suggestion: All rgminer stats below personal miner stats.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#353]
Put all rgminer stats below personal miner stats for those of us that like to see stats. :)

AKA the stats you see when you do not put a miner string in. And possibly MORE stats?

**Comment by RainbowMiner** [comment]
Sorry for answering back that late. I have been out of house for some days.
Is this the goal: you want to see -all- miners, but mine on the selected, only?

**Comment by Yamanipanuchi** [comment]
The stats you see at the bottom of the page when you goto https://rbminer.net/monitoring. Ex "92 miners generating 77.31mBTC per day with 44.33kW"

Would be neat to see something like most mined algo and items like that... I know I am stretching what could be asked for though.

**Comment by RainbowMiner** [comment]
Nice idea! Thank you very much.

**Comment by paulpoco** [comment]
% of time each Miner ran in the last 24hrs.
