### ISSUE TITLE
Red errors showing

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#354]
![screenshot_20181208-100048_teamviewer](https://user-images.githubusercontent.com/801414/49689082-d8120000-fad0-11e8-8cbe-a5f517a14dc5.jpg)
[debug-2018-12-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/2659925/debug-2018-12-08.zip)
I did add the newest commit for MiningRigRentals the change to "1e6".

**Comment by RainbowMiner** [comment]
Thank you for pointing this out. I will check this.

**Comment by paulpoco** [comment]
I haven't noticed it lately.

**Comment by RainbowMiner** [comment]
Please reopen, if issue pops up again.
