### ISSUE TITLE
BTC Balances showing zero

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#356]
Weird error after several balance cycles (30 minutes) is still showing zero
![image](https://user-images.githubusercontent.com/41829368/49906480-5eab4200-fe2f-11e8-94c8-9e785703a59f.png)

**Comment by paulpoco** [comment]
The Fiat has too many digits too.

![screenshot_20181212-181937_teamviewer](https://user-images.githubusercontent.com/801414/49911261-94095d00-fe3a-11e8-8034-a6600516ddc0.jpg)

**Comment by RainbowMiner** [comment]
Thank you! Eventually coinbase has been down thus importing invalid values. I will check this.

**Comment by RainbowMiner** [comment]
Wow :) Not an easy one. Fixed with commit 29625d58fba50c77aa67833e4eca06944b8905b9
