### ISSUE TITLE
Algo list error

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#357]
Got the following when setting up a new workstation...

Enter the algorithm you want to mine (leave empty for all) [default=aergo,allium,balloon,bcd,bitcore,blake2s,c11,cryptonightfreehaven,cryptonighthaven,cryptonightheavy,cryptonightv8,equihash,equihash144,equihash192,ethash,hex,hmq1725,hodl,keccak,keccakc,lyra2z,m7m,myrgr,neoscrypt,pascal,phi,phi2,poly,renesis,skein,skunk,sonoa,timetravel,tribus,x16r,x16s,x17,x22i,xevan,yescrypt,yescryptr16,System.Object[],yespower]:

Between yescryptr16 and yespower

**Comment by RainbowMiner** [comment]
Found it. I had a double colon, which lead to an invisible object at first setup.

**Comment by RainbowMiner** [comment]
Good. Fixed with version v3.9.0.7 - sorry for that!
