### ISSUE TITLE
Add autobenchmark in config

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#359]
Please add the switch to allow auto benchmark when a miner is updated..

**Comment by RainbowMiner** [comment]
This is already there 🌻 
Use 
``` "EnableAutoBenchmark":  "1", ```

**Comment by ebojali** [comment]
so true, sorry about that! :)

**Comment by RainbowMiner** [comment]
There is even more automatic:
``` "EnableAutoAlgorithmAdd": "1", ```

.. this will automatically add new algorithms during update to new releases.
