### ISSUE TITLE
How to set P0 state for my GTX1070 and GTX1080?

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#36]
These cards, they are originally not 'intended' for compute work, so they start mining in P0 state and then, after a short period they switch back to P2 state and that messes up all overclock speeds and whatnot.
Therefor it is a good idea to disable this "Force P2 State" feature for mining.

- **first of all! Stop any miners**
- choose mem +0, core +0 overclocking in MSI Afterburner
- in your RainbowMiner directory, goto "**Includes\NvidiaProfileInspector**"
- start program "NvidiaProfileInspector.exe"
- when you are running that, go down to **section 5**: there is a setting "**CUDA - Force P2 State**". Set this to "**Off**" and click "**Apply Settings**" button on the top right.
- now your cards should be able to work and stay in P0 state
- **important:** the reference levels for overclocking are now shifted. You will have to redo all your overclocking profiles, so that you do not run the cards out of their limits.

**A last note: everytime you update the Nvidia drivers, the "Force P2 State" will be reset to "On", again. Do not forget to use NvidiaProfileInspector.exe to set it to "Off" again.**

RBM

**Comment by RainbowMiner** [comment]
Which GTX1080ti do you use, exactly? I could look up the numbers.

RBM

**Comment by ebojali** [comment]
I use the following devices.
6x MSI GeForce GTX 1080 Ti Gaming X 2xHDMI 2xDP 11GB
1x Colorful iGame GTX 1080 Ti Vulcan AD

**Comment by ebojali** [comment]
C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi.exe -q -d CLOCK

==============NVSMI LOG==============

Timestamp                           : Thu Aug 23 23:30:42 2018
Driver Version                      : 398.82

Attached GPUs                       : 6
GPU 00000000:01:00.0
    Clocks
        Graphics                    : 1835 MHz
        SM                          : 1835 MHz
        Memory                      : 5508 MHz
        Video                       : 1556 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1974 MHz
        SM                          : 1974 MHz
        Memory                      : 5505 MHz
        Video                       : 1620 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    SM Clock Samples
        Duration                    : 5.63 sec
        Number of Samples           : 100
        Max                         : 1923 MHz
        Min                         : 1695 MHz
        Avg                         : 1852 MHz
    Memory Clock Samples
        Duration                    : 5.73 sec
        Number of Samples           : 100
        Max                         : 5508 MHz
        Min                         : 5505 MHz
        Avg                         : 5507 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A

GPU 00000000:03:00.0
    Clocks
        Graphics                    : 1784 MHz
        SM                          : 1784 MHz
        Memory                      : 5508 MHz
        Video                       : 1506 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1974 MHz
        SM                          : 1974 MHz
        Memory                      : 5505 MHz
        Video                       : 1620 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    SM Clock Samples
        Duration                    : 13.07 sec
        Number of Samples           : 100
        Max                         : 1784 MHz
        Min                         : 1721 MHz
        Avg                         : 1778 MHz
    Memory Clock Samples
        Duration                    : 13.58 sec
        Number of Samples           : 100
        Max                         : 5508 MHz
        Min                         : 5505 MHz
        Avg                         : 5506 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A

GPU 00000000:04:00.0
    Clocks
        Graphics                    : 1771 MHz
        SM                          : 1771 MHz
        Memory                      : 5508 MHz
        Video                       : 1480 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1974 MHz
        SM                          : 1974 MHz
        Memory                      : 5505 MHz
        Video                       : 1620 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    SM Clock Samples
        Duration                    : 11.70 sec
        Number of Samples           : 100
        Max                         : 1771 MHz
        Min                         : 1733 MHz
        Avg                         : 1763 MHz
    Memory Clock Samples
        Duration                    : 11.45 sec
        Number of Samples           : 100
        Max                         : 5508 MHz
        Min                         : 5505 MHz
        Avg                         : 5507 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A

GPU 00000000:09:00.0
    Clocks
        Graphics                    : 1784 MHz
        SM                          : 1784 MHz
        Memory                      : 5508 MHz
        Video                       : 1506 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 2025 MHz
        SM                          : 2025 MHz
        Memory                      : 5505 MHz
        Video                       : 1620 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    SM Clock Samples
        Duration                    : 15.16 sec
        Number of Samples           : 100
        Max                         : 1809 MHz
        Min                         : 1708 MHz
        Avg                         : 1794 MHz
    Memory Clock Samples
        Duration                    : 15.95 sec
        Number of Samples           : 100
        Max                         : 5508 MHz
        Min                         : 5505 MHz
        Avg                         : 5507 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A

GPU 00000000:0B:00.0
    Clocks
        Graphics                    : 1759 MHz
        SM                          : 1759 MHz
        Memory                      : 5508 MHz
        Video                       : 1493 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1974 MHz
        SM                          : 1974 MHz
        Memory                      : 5505 MHz
        Video                       : 1620 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    SM Clock Samples
        Duration                    : 12.07 sec
        Number of Samples           : 100
        Max                         : 1771 MHz
        Min                         : 1721 MHz
        Avg                         : 1767 MHz
    Memory Clock Samples
        Duration                    : 12.07 sec
        Number of Samples           : 100
        Max                         : 5508 MHz
        Min                         : 5505 MHz
        Avg                         : 5506 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A

GPU 00000000:0E:00.0
    Clocks
        Graphics                    : 1797 MHz
        SM                          : 1797 MHz
        Memory                      : 5508 MHz
        Video                       : 1544 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1974 MHz
        SM                          : 1974 MHz
        Memory                      : 5505 MHz
        Video                       : 1620 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    SM Clock Samples
        Duration                    : 9.14 sec
        Number of Samples           : 100
        Max                         : 1835 MHz
        Min                         : 1784 MHz
        Avg                         : 1815 MHz
    Memory Clock Samples
        Duration                    : 8.86 sec
        Number of Samples           : 100
        Max                         : 5508 MHz
        Min                         : 5505 MHz
        Avg                         : 5507 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A

**Comment by RainbowMiner** [comment]
Super :) Yes, disabling then "Force P2 state" on these cards is IMHO mandatory for stable mining operation. I will look up the best values for your cards.

RBM

**Comment by paulpoco** [comment]
when you are running that, go down to section 5: there is a setting "CUDA - Force P2 State". Set this to "Off" and click "Apply Settings" button on the top right

Is not there anymore?
![image](https://user-images.githubusercontent.com/801414/47263507-b379ae80-d4b7-11e8-8bdc-d81a37c0e109.png)
![image](https://user-images.githubusercontent.com/801414/47263519-f0de3c00-d4b7-11e8-92c5-0bd3a622806d.png)

**Comment by acos0874** [comment]
HI, how do I set p0-state in linux?

**Comment by RainbowMiner** [comment]
I don't think, that there is a possibility to set p0 state (switch force p2 state off).

**Comment by acos0874** [comment]
Please can you give me the nvidia-smi path so I can get overclocking working in linux?

**Comment by acos0874** [comment]
I mean the one that goes in the config file?

**Comment by ShallowRelease** [comment]
If I force P2 state off for my 1080ti, will this effect hinder the performance of a 4090 that is separately dual mining? Having problems with karlsenhash hash rate can’t touch the benchmark of 3.4gh, I’m only getting 2.04 any other ideas or suggestions are appreciated. 🫡

**Comment by RainbowMiner** [comment]
No, the Force P2 state off should help every Nvidia card. Which miner are you using?

**Comment by ShallowRelease** [comment]
RBM has Rigel benching karlsenhash on my 4090 @ 3.4 G/Hs while dual mining and it’s the same with every combo. However it is now only getting 2.04 and this it throws out that Rigel dual mining that combo and tries another but fails the bench on that one because it doesn’t meet the bench requirements. 
I can’t think of anything else making this happen other than the 1080tis ethlargement pill enabled to revA. I’m just pulling at straws. I don’t know why it’s happening.
