### ISSUE TITLE
Question: Profitability is way off

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#360]
So I have 5 rigs running almost identical hardware. All configs are identical as well. Yet, they never mine the same algo. 
![screenshot_20181217-185727](https://user-images.githubusercontent.com/42227809/50129577-6bb0a280-022e-11e9-9d37-9a487b3fb0f9.jpg)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2688692/config.txt)

**Comment by RainbowMiner** [comment]
I think, this is due to a mixture of
- different dates of first start of the rigs
- production dependant variations in hardware components
- mainly algorithm mining speed variations

If it bothers you, eventuall resetting all pool stats at aprox. the same time should help.

**Comment by Byrd1083** [comment]
Just seems wierd that if I have 5 rigs running identical hardware, then you would think they would be mining the same algo. Yet, they are always mining somthing different. I mean if i have 10x 1070s in one rig and 5x 1070s in another rig, yes the hash rate and power consumption is different but if they are clocked the same they should have in theory the same profitability. However, no matter what settings I do, the rigs never mine the same also. I only use one pool and switch between 4 algos, so I'll go on blockmasters and all my rigs are always all over the place. I can't imagine blockmasters is reporting profit wrong to all rigs. I would imagine if say x17 is most profit then at least 3 or 4 of them should mine it but this never seems to happen. I've tried messing with profit switchingprevention from 0-10 with really the same results. Instead of profit switching to most profitable, my rigs just appear to mine at random. It can't be most profitable to mine 4 different algos on the same pool at the same time. I might as well just run one algo at that point and ditch switching all together.

**Comment by Byrd1083** [comment]
I'll keep an eye out. I just wanted to bring this to the board.
