### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#361]
Any chance the circled item can be expanded to add all current miners together? Or something of this effect from place on the dashboard?

![total profit](https://user-images.githubusercontent.com/4724631/50247389-97e23580-038c-11e9-804e-4b7984b8e923.PNG)

**Comment by RainbowMiner** [comment]
Yes, this should be possible :) Good point.

**Comment by RainbowMiner** [comment]
Done.
