### ISSUE TITLE
Question: MiningPoolHub Coins

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#362]
Question about MiningPoolHub, from time to time coin names change to full name and conversion to BTC is lost. After another cycle or so it gets back to normal. Is this because a change in API results from MiningPoolHub or is there something preventable?

![image](https://user-images.githubusercontent.com/41829368/50256213-8744b600-03b2-11e9-95ca-0e0f16eb657c.png)

**Comment by hernandn01** [comment]
and back, different coin names this time
![image](https://user-images.githubusercontent.com/41829368/50258377-b06a4400-03bc-11e9-9c5a-520b5a975d6d.png)

**Comment by RainbowMiner** [comment]
This happens, if the currency converting API fails. Rainbowminer falls back to names, then. I think, this can be prevented with more aggressive caching. I will have a look.
