### ISSUE TITLE
Latest Pheonix miner benchmark failure

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#363]
This error occurs:
Eth: Share actual difficulty: 14.7 GH (!)
Eth: Share accepted in 37 ms
Eth: New job #08ac15bd from europe.ethash-hub.miningpoolhub.com:17020; diff: 4300MH
GPU3: Starting up... (0)
GPU3: Generating ethash light cache for epoch #238
GPU4: Starting up... (0)
GPU2: Starting up... (0)
GPU6: Starting up... (0)
GPU1: Starting up... (0)
GPU7: Starting up... (0)
Light cache generated in 2.5 s (18.6 MB/s)
CUDA error in CudaProgram.cu:329 : unspecified launch failure (719)
GPU5 search error: unspecified launch failure
Eth speed: 0.000 MH/s, shares: 6/0/3, time: 0:02
GPUs: 1: 0.000 MH/s (0) 2: 0.000 MH/s (0) 3: 0.000 MH/s (3/2) 4: 0.000 MH/s (3) 5: 0.000 MH/s (0/1) 6: 0.000 MH/s (0) 7: 0.000 MH/s (0)
Thread(s) not responding. Restarting.

Screenshot of the miner call from RBM.
![snip20181221_9](https://user-images.githubusercontent.com/35561346/50355705-e2f87600-054f-11e9-8ba2-3ae1c099edea.png)

**Comment by RainbowMiner** [comment]
The call looks perfectly alright. An unspec. launch error is normally due to overclocking. It is well possible, that the Phoenix miner reacts sensitive to this. I'd prefer Ethminer for ethash mining.

**Comment by ebojali** [comment]
Ok, which of the MSI profiles do you set for that miner?

**Comment by RainbowMiner** [comment]
Yea :) Merry Christmas 🎄 
On my 1070 rigs, the default profile 2 works without problem. I would first give profile 5, then profile 3 a shot. Eventually that helps.

**Comment by ebojali** [comment]
Ok, I will try that and report back. Please keep the ticket open until then
