### ISSUE TITLE
ethminer 0.17.0 rc.2 ETHEREUMSTRATUM (NiceHash) for MiningPoolHub

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#364]
![image](https://user-images.githubusercontent.com/41829368/50359575-7616b900-051a-11e9-97ac-b6c7bc50e79f.png)

**Comment by RainbowMiner** [comment]
Oh, I will have a look.

**Comment by RainbowMiner** [comment]
Ok, found the problem. The ethminer has an automatic detection of the correct stratum protocol. Obviously it gets it wrong on MiningPoolHub. I will fix this.

**Comment by RainbowMiner** [comment]
Solved with release v3.9.1.2
