### ISSUE TITLE
FAIRPOOL added

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#365]
https://fairpool.pro/

**Comment by RainbowMiner** [comment]
Is this different from fairpool.xyz? If yes, I look into it.

**Comment by petrovsky34** [comment]
Yes


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: RainbowMiner <notifications@github.com> Дата: 23.12.18  22:03  (GMT+04:00) Кому: RainbowMiner/RainbowMiner <RainbowMiner@noreply.github.com> Копия: Petr <gtnz666@gmail.com>, Author <author@noreply.github.com> Тема: Re: [RainbowMiner/RainbowMiner] FAIRPOOL added (#365) 
Is this different from fairpool.xyz? If yes, I look into it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RainbowMiner/RainbowMiner","title":"RainbowMiner/RainbowMiner","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/RainbowMiner/RainbowMiner"}},"updates":{"snippets":[{"icon":"PERSON","message":"@RainbowMiner in #365: Is this different from fairpool.xyz? If yes, I look into it."}],"action":{"name":"View Issue","url":"https://github.com/RainbowMiner/RainbowMiner/issues/365#issuecomment-449653911"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RainbowMiner/RainbowMiner/issues/365#issuecomment-449653911",
"url": "https://github.com/RainbowMiner/RainbowMiner/issues/365#issuecomment-449653911",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RainbowMiner** [comment]
I think, this pool is too small. Only around 10-15 miners on x16r, nothing else. If you really, really want this pool, anyway, just reopen this issue and I will create a module.
