### ISSUE TITLE
YesScrypt ccminer crash

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#366]
Miner is constantly crashing. See pic attached
![screenshot_20181229-093853_teamviewer](https://user-images.githubusercontent.com/35561346/50535798-f017f500-0b4d-11e9-9c11-9982f67a97d9.jpg)

**Comment by RainbowMiner** [comment]
It says "Out of memory"
- eventually your windows swap file could be too small. For seven 1080ti's it should be at least 80GB

**Comment by RainbowMiner** [comment]
``` I upped the virtual memory to 77GB for my 7 1080TI cards and it seems to be working now.. ```

Try more, something like (11GB + 1GB) x 7 = 84GB , just to be sure. If the miner still fails, try to decrease overclocking. OC can cause of this error, too. Practically, try to set MSIAprofile 5, then 3.

**Comment by RainbowMiner** [comment]
If this is still an issue, just reopen the issue.
