### ISSUE TITLE
MiningRigRentals YescryptR32 GPU Miner getting lots of invalid shares and invalid ID only getting about 86%

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#367]
MiningRigRentals YescryptR32 GPU Miner getting lots of invalid shares and invalid ID only getting about 86%.

Not sure what is wrong, if it is on my end, or is it the Renter's pool?

Previous rental after 24hrs got 2.05khs for GPU/CPU.

New rental because of GPU invalid shares & ID only getting about 1.9khs.  I don't see any errors on the CPU Miner.  The new renter said he has difficulty set at static of 1.

[debug-2018-12-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/2716989/debug-2018-12-29.zip)

**Comment by RainbowMiner** [comment]
Unfortunatly, it is the ccminer that has problems with too low difficulty for YescryptR32. The root cause, YescryptR32 is designed to operate on CPU. One step to make it ASIC resistant. The ccminer tries to operate it on GPU, which works, if the difficulty is set a little higher than the minimum, because it reduces the data transfers from GPU to CPU.

**Comment by paulpoco** [comment]
So does the Renter need to lower the difficulty?  To reduce the rejected shares?

**Comment by RainbowMiner** [comment]
Yes, I would let the renter play around a bit. Changing the difficulty will reduce the stale share count. During a rental you have no influence on the diff, at your side.

**Comment by paulpoco** [comment]
"eventually your windows swap file (virtual disk) could be too small."

I lowered my swap file from 24G to 20G.  My C drive is an SSD and with my Burst mining, one of my BurstPlots is too big, so that leaves me with hardly any space.

I have 2 x 1070s.

**Comment by RainbowMiner** [comment]
20G should be enough for your two 1070. If the swap file is too small, it will cause an out of memory error at the start of some miners. It does not cause rejected shares (nor wrong ID shares).
