### ISSUE TITLE
miniZ no worker cuda 9.1 error

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#369]

**Comment by petrovsky34** [comment]
driver 391.35 minZ cuda 8.0 worker

driver 391.35 minZ cuda 9.0 error

**Comment by petrovsky34** [comment]
--intensity 100 (gpu 1050ti) error

**Comment by RainbowMiner** [comment]
Yes, it needs cuda 9.2. I increased the requirement and removed intensitiy
