### ISSUE TITLE
Feature Request: add ccminer Klaust 8.21 that also does YescryptR32

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#370]
Feature Request: add ccminer Klaust 8.21 that also does YescryptR32.  I looked at other rentals for YescryptR32 and they are using the ccminer Klaust 8.21, I assume that is GPU?

https://github.com/nemosminer/ccminerKlausTyescrypt/releases ????

![screenshot_20181230-213034_chrome](https://user-images.githubusercontent.com/801414/50555014-9bbe6380-0c7a-11e9-88d8-7d05bf119484.jpg)

**Comment by paulpoco** [comment]
@rainbowminer I looked into this and figured out it already was using Klaust.

**Comment by RainbowMiner** [comment]
In deed, it does.

**Comment by paulpoco** [comment]
@rainbowminer I told my renter to lower the difficulty, they didn't, so their loss on shares.
