### ISSUE TITLE
Red errors and CPU error on GPU Miner with new release

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#371]
Red errors and CPU error on GPU Miner with new release.
![screenshot_20190102-104359_teamviewer](https://user-images.githubusercontent.com/801414/50606893-2b7f3000-0e7c-11e9-9635-12e0ce273ec1.jpg)
![screenshot_20190102-104251_teamviewer](https://user-images.githubusercontent.com/801414/50606902-36d25b80-0e7c-11e9-9e99-5c333f762a6e.jpg)
[debug-2019-01-02.zip](https://github.com/RainbowMiner/RainbowMiner/files/2721605/debug-2019-01-02.zip)

**Comment by ebojali** [comment]
I get the same issue..

[RainbowMiner_2019-01-02_20-28-30.txt](https://github.com/RainbowMiner/RainbowMiner/files/2721859/RainbowMiner_2019-01-02_20-28-30.txt)

**********************
Transcript started, output file is .\Logs\RainbowMiner_2019-01-02_20-28-30.txt
Detecting devices ..
Initialize configuration ..
Read configuration ..
PS>TerminatingError(New-Object): "The value supplied is not valid, or the property is read-only. Change the value, and then try again."
New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again.
At C:\Users\DBminer\Desktop\RainbowMinerV3.9.1.4\Core.psm1:1236 char:38

**Comment by paulpoco** [comment]
Seems to be working fine otherwise, I think?

**Comment by ebojali** [comment]
Yes it does.

**Comment by RainbowMiner** [comment]
Thanks for reporting! I will fix this.

**Comment by RainbowMiner** [comment]
Wow. That was a hard one. Fixed :)
I will publish a release.
