### ISSUE TITLE
MMR Connection was closed by pool errors

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#372]
@RainbowMiner 

MMR Connection was closed by pool errors.

A new rental on X21S.

I was working for a bit and then it would say this the 1st time I rerun RBM.
https://photos.app.goo.gl/q3iChGQpvdPPiB2N6
And then it would stop the MRR miner and switch to something else.

[debug-2019-01-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/2730210/debug-2019-01-05.zip)

It also doesn't seem to be trying the other MRR urls.

**Comment by paulpoco** [comment]
I wonder if this was the renters fault?

**Comment by RainbowMiner** [comment]
Yes, this is a pool issue - if the pool is down for any reason (and some time), RainbowMiner mines something different for 15 minutes before it tries again.

**Comment by RainbowMiner** [comment]
The other URLs are used, if the origin URL is not reachable.
