### ISSUE TITLE
miner keeps stalling,

### ISSUE THREAD

**Issue by henry18341834** [RainbowMiner/RainbowMiner#374]
![img_5609](https://user-images.githubusercontent.com/10469825/50993114-da5be580-14e6-11e9-9b20-eafc98943b54.jpg)

having issues with the miner stalling, MSI afterburner shows that the GPU's are still running even though the miner says it is restarting. this can stay this way for hours if I leave it. the only way to stop this is to shut off the miner and then use afterburner to set a new profile numerous times until the GPU's reduce hashrate.
I have tried to even backtrack to the older version miners but still happens.

when the miner starts I get an error showing up. see attached.

any ideas??

**Comment by RainbowMiner** [comment]
Oh! Weird error!
First of all:
- Try to install dot.net framework 4.7.2, this should take care of the error: https://dotnet.microsoft.com/download/dotnet-framework-runtime

.. if the miner software still hangs after this, please send me your current debug file.
Which and how many GPUs are plugged into your rig?
Is there one specific miner, that hangs the machine?

**Comment by henry18341834** [comment]
ok, I had to run the repair program for the .net. looks like my .net file is either the same or higher???
the error is still there.
how do I find the debug file??
all five of my gfx1070 have the same issue.

**Comment by RainbowMiner** [comment]
Hi, there is a list in http://localhost:4000 "Activity" - this shows what and when has been mined for how long.
