### ISSUE TITLE
Where to Fine Tune WildRig

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#375]
It doesn't seem to work like srbminer or jcemineramd

**Comment by RainbowMiner** [comment]
WIldRig has common parameters, already preset. It's simple: add the parameters in miners.config.txt to overwrite the defaults.
The tuning parameters are ```--opencl-threads 2```and ```--opencl-launch 17x0``` (these values are only examples)

Many useful hints can be found at [bitcointalk](https://bitcointalk.org/index.php?topic=5023676.0)

**Comment by jch9678** [comment]
Where is miners.config.txt?

**Comment by RainbowMiner** [comment]
Ah, sorry. I missed your reply. All config files are located in directory "Config". But you may as well use the build-in configuration to add parameters. Press [C] for Configuration, then [M] for miners. Then enter "Wildrig" and the GPU and follow the prompts.

**Comment by jch9678** [comment]
Ah yeah.  I forgot about that.  Just used to srbminer and jceminer.

Thanks
