### ISSUE TITLE
Remote into RainbowMiner Dashboard

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#376]
I'm trying to view the dashboard remotely.  I've opened up the port but I get a Bad Request.

HTTP Error 400. The request hostname is invalid.

Any idea?

**Comment by Yamanipanuchi** [comment]
I do not believe it will work remotely. It will only work Locally. 

I've wanted it to work remotely also.

**Comment by jch9678** [comment]
RM, is this possible?
