### ISSUE TITLE
NanoXminer  added

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#378]
https://github.com/NanoXminer/NanoXminer/releases

**Comment by jch9678** [comment]
There are some reports this miner is a scam.  RainbowMiner needs to be careful what he adds because updates are automatically downloaded and benchmarked.

https://bitcointalk.org/index.php?topic=5081614.0

**Comment by jch9678** [comment]
This is a scam.  RM maybe there should be some protocol about how to suggest miners to add because this could be very dangerous if someone has auto update and auto benchmark set.

**Comment by RainbowMiner** [comment]
Thanks for looking into this.
Actually, before I add a miner to RBM, I do extensive research and testing. If a miner is open source, I dig deep into the source code and always do compile them on my developer machine, so that I can be sure the release is matching the code.
