### ISSUE TITLE
Wallet other than BTC

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#38]
Would you be able to add the option to have a wallet different than BTC. For example, on pool ZergPoolCoins, to mine sono to a sono address. I replaced "BTC": "**$Wallet**" for my sono address and that got translated to 

-p worker1,c=**BTC**,mc=SONO instead of -p worker1,c=**SONO**,mc=SONO

 "ZergPoolCoins": {
    "DataWindow": "minimum",
    "BTC": "$Wallet",
    "Worker": "$WorkerName",
    "Penalty": 0,
    "Algorithm": "sonoa",
    "ExcludeAlgorithm": "",
    "ExcludeCoin": "",
    "CoinName": "sono",
    "CoinSymbol": "sono",
    "ExcludeCoinSymbol": ""

**Comment by RainbowMiner** [comment]
Of course, this is already possibly. Use the build in configuration for the pools (press "C"onfiguration, then "P"ools)
- Type ZergPoolCoins
- now choose the currency, you want to mine directly and enter the corresponding Wallet
- save and exit the config

RBM

**Comment by RainbowMiner** [comment]
If you want to add this directly to the pools.config.txt, add this line after the BTC line:
"SONO": "putyourwalletaddresshere",

RBM

**Comment by hernandn01** [comment]
added the line on pools.config.txt and that worked. Thanks.
