### ISSUE TITLE
Power consumtion not showed for VEGA 56

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#380]
Hi!
The column regarding watts consumed by my VEGA 56 is 0W. But my Ryzen 1700 shows 65W. MSI's Afterburner shows 130W when working so there is a way to read power consumed. Can this be added?
Thanks!

**Comment by RainbowMiner** [comment]
Yes, it can be added. Would you please start the GPUtest.bat, which is located in your RainbowMiner directory? Even though there might popup warning messages, it will create a file gputestresults.txt - drop this here and I will have a look.

**Comment by Djago** [comment]
Something happened. For testing purposes I've gone from Adrenaline 18.2.x to 18.6.1 and now Afterburner doesn't show me power consumption. Could it be that this feature is enabled only on newer drivers?

**Comment by RainbowMiner** [comment]
It may be the case, that the driver's API has changed, yes.
So or so, it would be good, if you created a gputestresults.txt and dropped it here.

**Comment by Djago** [comment]
Ok, I'll do one with 18.6.1 and one with the newest

**Comment by Djago** [comment]
This is 18.6.1
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2755699/gputestresult.txt)

**Comment by Djago** [comment]
Strange... I've changed to 19.1.1 and power consumption isn't there anymore! 😢 
This is with 19.1.1
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2755784/gputestresult.txt)

**Comment by RainbowMiner** [comment]
Oh dear! I will bring back the power reading in RainbowMiner, for you :) 
Would you please drop the current debug file, too? Open http://localhost:4000 in your browser and click "Debug file" on the left hand side.

**Comment by Djago** [comment]
When I said "power consumption isn't there anymore!" I was referring to Afterburner!

**Comment by RainbowMiner** [comment]
Yeah, I got that. Anyway, you have "0W" in RainbowMiner, now. I changed the code, so that at least RainbowMiner will show some power consumption from v3.9.2.5 on (I hope ;-) )

**Comment by Djago** [comment]
[debug-2019-01-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/2755907/debug-2019-01-14.zip)

**Comment by Djago** [comment]
Now I'm getting:
WARNING: Could not read power data from CPU
WARNING: Could not read power data from AMD

**Comment by RainbowMiner** [comment]
Oh. This should not happen. Would you send me the new debug file, too, please?

**Comment by Djago** [comment]
Just updated to 3.9.2.6 and it's not happening here...

**Comment by RainbowMiner** [comment]
What is the name, RainbowMiner shows for your Vega? Is it Vega 56? Or different?

**Comment by Djago** [comment]
In the main window where appears a list of miners associated to the card I have: "Radeon RX Vega (GPU#00)"

**Comment by RainbowMiner** [comment]
Ok. Thank you :) I found and fixed the detection.

**Comment by Djago** [comment]
Now I have some miners showing power, some miners showing 0W. Will the list populate values as RM use the miners? Or some miners will stay at 0W?

**Comment by Djago** [comment]
Where are you reading the power consumption value for VEGA? RM says 256W for SRBMinerm but Afterburner used to say 130W (now, I don't know why, I can't read power values anymore). With this value of power consumption XMR is not profitable for a VEGA.

**Comment by RainbowMiner** [comment]
Which model and brand is your GPU, exactly? Eventually the GDP is setup a little high.

**Comment by RainbowMiner** [comment]
Ok, the GPU's TDP is 210W - have your setup a maximum power level? If there would be really 256W the power level would be sitting at around 120%.

Please try the following: while RainbowMiner is running, please note the current power consumption and start GPUtest.bat in parallel. Then please drop the new gputestresults.txt file here.

**Comment by Djago** [comment]
The problem is: how can I note the current power consumption? Afterburner doesn't show it anymore!

**Comment by Djago** [comment]
I have 50W of base power added in the config. RM says "net power consumption". Is it referring to net power of the card or net power of the system?

**Comment by Djago** [comment]
But a couple of days ago I used to look at power consumption on Afterburner! I read 130W when mining! I'm not sure WHEN it stop appearing in the program. Maybe when I put the second video card (nVidia 550Ti not used for mining)? 

I did what you need. I'm reading 253W (for the records, it's Teamred mining PHI2).
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2783253/gputestresult.txt)

**Comment by RainbowMiner** [comment]
> But a couple of days ago I used to look at power consumption on Afterburner! I read 130W when mining! I'm not sure WHEN it stop appearing in the program. Maybe when I put the second video card (nVidia 550Ti not used for mining)?

That is possible. Eventually your GPU drivers got an update. In the newer AMD drivers, there is no more power consumption calculation (in fact it did calculate the numbers, because there is no power-meter on-board the GPUs).

**Comment by Djago** [comment]
Is this fix available right now on the master.zip?

**Comment by RainbowMiner** [comment]
Yes, but I have relased v3.9.3.1 just now. This contains the fix.

**Comment by Djago** [comment]
Great, it's starting right now. Will it update the power consumption or do I need to re-benchmark all miners for the card?

**Comment by RainbowMiner** [comment]
It will update the power consumption over time. It's a one-week average. So, after 7 days, everything should work accordingly.

**Comment by Djago** [comment]
I will update benchmarks. Right now primarily because of the low value of the cryptos, and because of the high power noted by RM, almost every miner is having negative profitability.

**Comment by RainbowMiner** [comment]
Well, it's better. I will check the calculation, just to be sure.

**Comment by RainbowMiner** [comment]
Oh dear! I am so sorry, I left in some debug code. It's gone, now. Next release will work properly.

**Comment by Djago** [comment]
Great!
![image](https://user-images.githubusercontent.com/34612740/51779329-6e33d100-20e5-11e9-9b86-c01d41ce9ca5.png)

**Comment by rizkyaulya** [comment]
Hi, I am facing similar issue:

![image](https://user-images.githubusercontent.com/44210627/184541437-3cce0ef8-9be5-4266-b437-7f3b58df3d82.png)

but it only shows those warning and no temp info in monitoring central

[debug_2022-08-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/9333515/debug_2022-08-14.zip)
