### ISSUE TITLE
Profitability calculation is completely inaccurate

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#384]
I've reseted the profit.txt recently (as per suggested by you in another issue). It went ok and values went normal.
Today I'm getting:
RainbowMiner is between 0% and 349% more profitable than the fastest miner:

Miner                                    XMR                                 USD
-----                                    ---                                 ---
RainbowMiner                             1,24846 ±98 % (0,63113-2,46962)     57,06495 ±98 % (28,84782-112,88230)
{CpuminerYespower-Yespower, WildRig-Bcd} 0,45458 ±6.192 % (0,00723-28,60125) 20,77827 ±6.192 % (0,33025-1.307,31819)

(I have a lone VEGA 56 and a Ryzen 1700, so the calculated value is impossible). But the deviation is way off (98%?).
Right now my best bet accoridng to RM are: 
CpuminerYespower      - Yespower      990,29  H/s   65W   0,3062 0,006705     76 % Zpool                 1,25 %
Teamred           3 % PHI2                              8,88 MH/s    0W   0,5471 0,011983         85 % NLpool                                     0,1 %
So that would be around ~0.85 USD/Day

What is the cause of this deviation? How can I minimize it?

**Comment by Djago** [comment]
Oops... now it reads: 

RainbowMiner is between 874% and 2556% more profitable than the fastest miner:

Miner                                    XMR                                USD
-----                                    ---                                ---
RainbowMiner                             1,21010 ±98 % (0,61167-2,39403)    55,25628 ±98 % (27,93020-109,31735)
{CpuminerYespower-Yespower, WildRig-Hex} 0,06667 ±1.585 % (0,00396-1,12325) 3,04436 ±1.585 % (0,18070-51,29030)

**Comment by RainbowMiner** [comment]
The problem is the data, the pools deliver. Sometimes the values are way off and destroy the calculation. I think, best short-term solution to this is to delete the Profit.txt from time to time. I will try to figure out a long-term solution.

**Comment by Djago** [comment]
Right now I have:

RainbowMiner is between 3306% and 3422% more profitable than the fastest miner:

Miner                                                   XMR                             USD
-----                                                   ---                             ---
RainbowMiner                                            0,72900 ±98 % (0,36802-1,44407) 33,01510 ±98 % (16,66679-65,39932)
{CpuminerOptBF-Yespower, ClaymoreEthash-Ethash/Blake2s} 0,02104 ±18 % (0,01779-0,02489) 0,95302 ±18 % (0,80570-1,12727)

I will erase profit.txt!

**Comment by Djago** [comment]
In the meantime, can you add a way to erase profit.txt from inside the Configuration script? Or from the dashboard in the webfig?

**Comment by RainbowMiner** [comment]
Yes, I will add a button today.

**Comment by Byrd1083** [comment]
Just chiming in on this topic. I have 5 rigs running really stable. I have been only mining to blockmasters currently. Here is some helpful info to see how the profitability is working. If you do the math rainbow is reporting accurate profits when api is working correctly. Thanks.

Rack1:
![image](https://user-images.githubusercontent.com/42227809/52182630-df454980-27b3-11e9-9a27-4c566212de68.png)

Rack2:
![image](https://user-images.githubusercontent.com/42227809/52182634-e8361b00-27b3-11e9-89b9-18d4cfac3377.png)

Rig1:
![image](https://user-images.githubusercontent.com/42227809/52182644-fab05480-27b3-11e9-8e03-fa9328695cf9.png)

Rig2:
![image](https://user-images.githubusercontent.com/42227809/52182650-03a12600-27b4-11e9-9c09-2f47fe548bfe.png)

Rig3:
![image](https://user-images.githubusercontent.com/42227809/52182656-0b60ca80-27b4-11e9-9676-1e018a1c77e3.png)

Blockmasters actual payouts:
![image](https://user-images.githubusercontent.com/42227809/52182665-26cbd580-27b4-11e9-97bb-a73e31caac56.png)

**Comment by RainbowMiner** [comment]
Super! Thank you for reporting this!
