### ISSUE TITLE
Benchmark showed miners

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#387]
Right now RM has the option to benchmark:

- Updated Miners
- Failed Miners
- All Miners

It would be nice if I can re-benchmark all miners showed with filters. For example: all the CryptoNightV8 capable miners, or all the RXVega, or even better, all the CryptoNightV8 capable miners that works under RXVega!

**Comment by paulpoco** [comment]
Clickable list and then submit.

**Comment by itsdarklikehell** [comment]
such good ideas! woot.
