### ISSUE TITLE
How to config bsod pool mining?

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#39]
I have added Bsod to pool list in config.txt
  "PoolName": "Bsod,BlockMasters,Bsod,NiceHash,ZergPool",

Also, done following edits to my pools.config file.
"Bsod": {
    "DataWindow": "",
    "RVN": "",
    "PGN": "",
    "LUX": "LSdUXdjq1nsYprKno2nh2DEuz1JPn21WnT",
    "Worker": "$WorkerName",
    "Penalty": 0,
    "Algorithm": "phi2",
    "ExcludeAlgorithm": "",
    "ExcludeCoin": "",
    "CoinName": "lux",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": ""
  },

Still, I don't see phi2 bsod in my mining screen
![image](https://user-images.githubusercontent.com/30832110/44640822-8cd05780-a9e1-11e8-8648-89a54b31444f.png)

**Comment by RainbowMiner** [comment]
Could you send a zip of your Logs directory, please? I will have a look into it.

RBM

**Comment by rinkal26783** [comment]
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/2324754/Logs.zip)

**Comment by hernandn01** [comment]
![image](https://user-images.githubusercontent.com/41829368/44677148-754d9a80-a9f2-11e8-8874-337978fa44e4.png)
I think there is a multiplier issue on the BSOD pool, that is why is not getting chosen

**Comment by RainbowMiner** [comment]
Oh! You are right. It looks like, the divisor has changed. I will adjust it.

RBM

**Comment by rinkal26783** [comment]
pools.config.txt
  "Bsod": {
    "DataWindow": "",
    "RVN": "",
    "PGN": "",
    "Worker": "$WorkerName",
    "Penalty": 0.0,
    "User": "$UserName",
    "API_ID": "$API_ID",
    "API_Key": "$API_Key",
    "LUX": "LSdUXdjq1nsYprKno2nh2DEuz1JPn21WnT",
    "Algorithm": "phi2",
    "ExcludeAlgorithm": "",
    "CoinName": "lux",
    "ExcludeCoin": "",
    "CoinSymbol": "LUX",
    "ExcludeCoinSymbol": ""
  },
Still no sign of bsod
![image](https://user-images.githubusercontent.com/30832110/44702610-e4d68f00-aab1-11e8-8bc6-942be5f378f8.png)

**Comment by RainbowMiner** [comment]
Remove CoinName - Bsod has another name for LUX. The CoinSymbol is enough.

RBM

**Comment by RainbowMiner** [comment]
Hi, yes. That was expected, because there has been a wrong multiplier for this pool. 
Please delete all files beginning with "Bsod_" from your Stats directory:
Bsod_*_Profit.txt

RBM

**Comment by RainbowMiner** [comment]
.. I made it easier for you: simply update to v3.8.3.10 - it will cleanup all.

RBM

**Comment by rinkal26783** [comment]
Thanks
