### ISSUE TITLE
Getting Zergpool when its not a selected pool.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#390]
Might just be a visual glitch. I checked the pool and I am infact NOT mining there.

But in the web interface it says I am mining Zergpool.

**Comment by Yamanipanuchi** [comment]
![rainbowminer 7040](https://user-images.githubusercontent.com/4724631/51489750-118b8b80-1d5e-11e9-9682-b12f03c2272b.PNG)

**Comment by Yamanipanuchi** [comment]
Just had another machine show Nicehash, And in the PS screen it had Zergpool all over the place... Ya I do not have Zergpool selected.

**Comment by Yamanipanuchi** [comment]
![rainbow nicehash](https://user-images.githubusercontent.com/4724631/51626134-b9868d80-1ef3-11e9-9484-beeffe2c82e6.PNG)

**Comment by paulpoco** [comment]
What does the "Mines" column say?

When you are mining it will say "for you".

Other times it will say "for Dev".

**Comment by RainbowMiner** [comment]
Yes, eventually that has been a dev mining round. If you like, you may paste the current Debug file and I will check it.

**Comment by Yamanipanuchi** [comment]
That most likely is what I am seeing. I did not look closely at the wallet address. If I see it again ill check that. For now ill close out the issue.
