### ISSUE TITLE
Ccmindyn: Setting custom difficulty level

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#391]
I've noticed that my 14x 1070 gpu rack keeps crashing when running CcminerDYN. It will loaded but will continue to raise the diff level until miner finaly crashes. Anything over level 32 and my system bogs down and will run shares very slow and eventually crash the drivers requiring system reboot.

![image](https://user-images.githubusercontent.com/42227809/51494021-240cc180-1d6c-11e9-85cf-1d8b9669937c.png)
![image](https://user-images.githubusercontent.com/42227809/51494024-296a0c00-1d6c-11e9-8748-adeda22dcfff.png)

I think if I could just lock it to level 16 or 32 I will be stable.

**Comment by Byrd1083** [comment]
[RainbowMiner_2019-01-21_10-52-18.txt](https://github.com/RainbowMiner/RainbowMiner/files/2780193/RainbowMiner_2019-01-21_10-52-18.txt)
[Activity_2019-01-21.txt](https://github.com/RainbowMiner/RainbowMiner/files/2780194/Activity_2019-01-21.txt)
[RainbowMiner_2019-01-21.txt](https://github.com/RainbowMiner/RainbowMiner/files/2780196/RainbowMiner_2019-01-21.txt)

**Comment by Byrd1083** [comment]
Finally being rejected from to high of diff.

![image](https://user-images.githubusercontent.com/42227809/51494821-f6754780-1d6e-11e9-8cef-563d205256f1.png)

**Comment by Byrd1083** [comment]
I guess my goal is to understand how to set the custom diff for the algorithm specific.

**Comment by RainbowMiner** [comment]
Try the following:
- edit Config\miners.config.txt
- find 
```
  "CcminerDyn-GTX1070": [
    {
      "MainAlgorithm": "Argon2dDYN",
      "SecondaryAlgorithm": "",
      "Params": "",
      "MSIAprofile": "",
      "OCprofile": "",
      "Difficulty": "",
      "Penalty": ""
    }
  ],
```
- now enter the required difficulty into field Difficulty. E.g. for static diff of 10: `"Difficulty": "10",`
