### ISSUE TITLE
Common error

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#393]
I get this error on several machines here and there. Not completely sure where it is originating?

Read configuration ..
WARNING: Your miners.config.txt seems to be corrupt. Check for correct JSON format or delete it.
Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the
command again.

I've delete the config and let it RE-create it and the error creeps back in.

**Comment by RainbowMiner** [comment]
Hi, should not happen. Would you please send me a Debug file, of one of the machines?

**Comment by RainbowMiner** [comment]
Also, please send a Config\miners.config.txt , that would be very kind.

**Comment by Yamanipanuchi** [comment]
[Config.zip](https://github.com/RainbowMiner/RainbowMiner/files/2792508/Config.zip)

Removed the MiningPool API config.

**Comment by RainbowMiner** [comment]
Ok, I think I found and fixed a problem. Eventually this will work, now.
