### ISSUE TITLE
TT-Miner difficulty as seen on Zergpool

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#394]
TT-Miner/2.1.7 worker | GTX10603GB_GTX10606GB**%2cc%3dBTC%7bdiff%3a%2cd%3d%2** | mtp | **0.006984919309616088** |   | 845.9 kh/s | 0
-- | -- | -- | -- | -- | -- | --

**Comment by RainbowMiner** [comment]
Found and fixed.
