### ISSUE TITLE
Gminer Beam - Nicehash invalid nonce miner not compatible?

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#395]
![image](https://user-images.githubusercontent.com/41829368/51864276-83387c00-2300-11e9-9789-251aec2e579d.png)

**Comment by hernandn01** [comment]
it appears to be a glitch, mining fine now
![image](https://user-images.githubusercontent.com/41829368/51864809-fb537180-2301-11e9-9cb4-5c6ee0ebdcf2.png)

**Comment by hernandn01** [comment]
and back again, some are accept
![image](https://user-images.githubusercontent.com/41829368/51866287-da8d1b00-2305-11e9-87cd-466f417e98aa.png)

**Comment by RainbowMiner** [comment]
Yes, this is a real problem. Gminer has problems with the extranonce handling on Nicehash.

**Comment by RainbowMiner** [comment]
Gminer has solved the problem with the new version :)
