### ISSUE TITLE
GrinPro Miner

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#396]
Can you add GrinPro miner?
https://grinpro.io/
and GrinGold Miner?
https://github.com/mozkomor/GrinGoldMiner

**Comment by RainbowMiner** [comment]
Should be possible, yes. I'll try :)

**Comment by RainbowMiner** [comment]
Added with v3.9.3.8, enabled for AMD, only. For Nvidia bminer and gminer are a lot faster.

**Comment by Djago** [comment]
Thanks!
I'm on 3.9.3.9

**Comment by Djago** [comment]
I see grinprominer.ps1 on Miners folder but it's not listed in my Miners list on the webfig

**Comment by RainbowMiner** [comment]
Check config.txt:
- is Cuckaroo29 on the Algorithm list?
- is Grinmint pool on the PoolName list, but not on the ExcludedPoolName list?

Check pools.config.txt:
- did you add `"GRIN": "<your emailaddress>",` and `"Password": "<your grinmint password>"`,  to the "Grinmint" section?

If yes, please send me a Debug file and I will have a look.

**Comment by Djago** [comment]
> Check config.txt:
> * is Cuckaroo29 on the Algorithm list?

Yes

> * is Grinmint pool on the PoolName list, but not on the ExcludedPoolName list?

Grinmint pool is NOT on PoolName and is NOT on ExcludePoolName

> Check pools.config.txt:
> 
> * did you add `"GRIN": "<your emailaddress>",` and `"Password": "<your grinmint password>"`,  to the "Grinmint" section?

No, I didn't. I didn't know I have to add it manually!

> Your GPU:
> 
> * is there enough memory? This miner will need 6GB minimum

Yes, it's an 8Gb Vega 56. In fact, I've used successfully used grinpro miner alone

So I suppose I need to:

1. Add grinmint to the the PoolName list?
2. Complete data in the pools.config.txt as you said.
3. Restart RM

And my earnings will be accumulated at grinmint pool, ok?

**Comment by jch9678** [comment]
If there is not enough memory on the gpu will RM not download grinminer pro and not add grinmint to the pool list?

**Comment by RainbowMiner** [comment]
@Djago correct!

@jch9678 the pool should appear in the pools.config.txt, but the miner will not be downloaded, if the GPU have less than 6GB

**Comment by jch9678** [comment]
Is it possible to have the pool appear in the config file under exclude pools.  That way we can quickly check if a pool has been added with an update and move it to include pools and then configure pools.config

Maybe pools include and exclude are becoming redundant with pools.config.txt

**Comment by Djago** [comment]
@RainbowMiner Thanks! RM is mining full speed with GrinProMiner as the most profitable miner in my system now!
