### ISSUE TITLE
Update .8 broken

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#398]
Left it on auto update. It will still mine but keeps throwing this in main output window over and over.

Warning: could not request from 127.0.0.1:32400

[RainbowMiner_2019-01-31_07-22-59.txt](https://github.com/RainbowMiner/RainbowMiner/files/2817887/RainbowMiner_2019-01-31_07-22-59.txt)
[RainbowMiner_2019-01-31_07-21-17.txt](https://github.com/RainbowMiner/RainbowMiner/files/2817890/RainbowMiner_2019-01-31_07-21-17.txt)

.

**Comment by RainbowMiner** [comment]
Yes, I am sorry. I forgot some debug code in the source. Already removed with .9
