### ISSUE TITLE
Is ExcludeCoin for pool.config implemented?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#4]
Is ExcludeCoin for pool.config implemented?

"ExcludeCoin": ["MaxCoin", "BitcoinGold", "..."]

**Comment by RainbowMiner** [comment]
Good idea. I will implement this. Of course, this will only work on the both Coin-Pools MiningPoolHubCoins and ZergPoolCoins. 

RBM

**Comment by RainbowMiner** [comment]
Ok, done :)
See commits:
4ef652368926b95ca48573879c63900d31ace03b
a7d16632b73fef2b0eb8d536842e9cd123c14bcf
18bbdae84c9c08e97c26bdf85a8fac0f154168bd

.. to update download the new master.zip and extract.
