### ISSUE TITLE
Extended interval not calculated right from Interval value in config file

### ISSUE THREAD

**Issue by thebeerbaron2018** [RainbowMiner/RainbowMiner#400]
If I set "interval" in config.txt to 6000 and then benchmark X16R at nicehash - this should be a x3 as per the miner script.

but the code at 1686-1708 produces the message "Waiting 163s until next run"  so I assume it's still calculating 60s (the default) x 3 minus the time it took to do it's housekeeping....

Surely this should be 6000s x 3 ?  (I used a large interval to make sure it wasn't just an odd timing issue)

**Comment by thebeerbaron2018** [comment]
This causes me problems on things like Yesscript32 where it may not get the work straight away and also on algorithms that generate large DAG files or similar to upload to the cards....  they get only a few seconds benchmark or in some cases none at all!

**Comment by thebeerbaron2018** [comment]
Things like X16R which already have extended benchmark - but I would use an extendinterval of 3 on all the yescrypt algos in CCminerYescrypt.ps1 (and any other miners that use the yescrypt algo)

**Comment by thebeerbaron2018** [comment]
Maybe add a "BenchMarkInterval" to the config.txt?  That way you could leave normal running Interval low but raise the benchmarkinterval so that it spends longer on those - kinda like the quick/standard/precise options on Nicehash miner - so you can set it low (60-120) if you want a quick and dirty benchmark or raise it up (600+) if you want a more accurate one ?

**Comment by RainbowMiner** [comment]
Ok, thanks for the info. I already added the BenchmarkInterval parameter to be adjustable, right now.
It's a super idea to call them quick/standard/precise.

**Comment by thebeerbaron2018** [comment]
Tested.  Works perfectly!

**Comment by thebeerbaron2018** [comment]
Although I will need to change my interval as "Waiting 17978s  until next run" could be considered as excessive :)

**Comment by thebeerbaron2018** [comment]
The only thing you might want to do is do a calculation on the "approx times" in yellow - they are still based on 60 seconds....

**Comment by thebeerbaron2018** [comment]
Something else I have noticed when benchmarking (happened before the change above as well) but for arguments sake lets say the benchmark is set to 600.  I benchmark X16R which is a x3.  The miner starts and the main window states "Waiting 1789s until next run" - which is correct.  However when that interval ends - it does not ALWAYS end the current miner and move onto the next.  Frequently it will complete another cycle of 1800 seconds (600 x 3 for X16R).  This means you'll end up with 1800s+1800s worth of benchmarks for X16R which is overkill?  Is there any way to complete the benchmark ALWAYS after one full cycle?

**Comment by RainbowMiner** [comment]
The measured hashrates will be measured against a constant maximum variance. It would be a good idea to apply the algorithm's typical variance (which is already set at miner level) to this constant limit. This might solve the problem of multiple benchmark cycles in a quiet elegant manner. I will figure something out :)

**Comment by RainbowMiner** [comment]
I completely reworked the benchmarking feature, now. Also, I reworked the analytic part, so that the variance calculation is much more accurate and will no longer result in artificial increased benchmark times for X16r et al.
I will do some extensive testing, the comeing 24h before I push a release (anyway, the new code is already functional in the current master.zip)

**Comment by thebeerbaron2018** [comment]
I have been following your code changes.  I'll delete my stats folder and do a full re-test of benchmarking too.  I'll post the results in 3-4 hours when it completes or sooner if the code works :)

**Comment by thebeerbaron2018** [comment]
Benchmarking 20 miners at Nicehash and Zpool.  Notes so far : 

1.  All miners opening and closing correctly
2.  All benchmarks observing the intervals and applying the correct number of extended intervals where required

Side note:  I could not get EWBF to mine at Nicehash on Zhash (144_5) - I needed to add "--pers BgoldPoW" (case sensitive) or all the shares were getting rejected??

Command line created by RM:

Bin\Equihash-EWBF\miner.exe --api 127.0.0.1:31100 --cuda_devices 0 1 2 3 --server zhash.eu.nicehash.com --port 3369 --fee 0 --eexit 1 --user XXXXX.YYYYY --pass x --algo 144_5

Which doesn't work until --pers BgoldPoW is added to the end?  Is this a me issue or something you need to update?

**Comment by thebeerbaron2018** [comment]
Hmmmm, was working fine then it suddenly started rejecting - then accepting again - think I might just exclude this algo

`+-------------------------------------------------+
|         EWBF's Eqihash CUDA miner. v0.6         |
+-------------------------------------------------+
23:12:21 INFO: Configured pools: 1
23:12:21 INFO: Selected pool: zhash.eu.nicehash.com:3369
23:12:21 INFO: Algorithm: 144_5 "BgoldPoW"
23:12:21 INFO: Devices: User defined.
23:12:21 INFO: Temperature limit: 90
23:12:21 INFO: Api: Listen on 127.0.0.1:31100
---------------------------------------------------
23:12:21 INFO: Target: 001e1e1e1e000000...
23:12:21 INFO: Detected new work: 0000018b05e189e3
23:12:22 CUDA: Device: 0 GeForce GTX 1070, 8192 MB i:64
23:12:22 CUDA: Device: 1 GeForce GTX 1070, 8192 MB i:64
23:12:22 CUDA: Device: 2 GeForce GTX 1070, 8192 MB i:64
23:12:22 CUDA: Device: 3 GeForce GTX 1070, 8192 MB i:64
23:12:51 Temp: GPU0: 65C GPU1: 66C GPU2: 63C GPU3: 66C
23:12:51 GPU0: 40 Sol/s GPU1: 41 Sol/s GPU2: 42 Sol/s GPU3: 41 Sol/s
23:12:51 Total speed: 164 Sol/s
23:13:21 Temp: GPU0: 66C GPU1: 66C GPU2: 63C GPU3: 66C
23:13:21 GPU0: 41 Sol/s GPU1: 40 Sol/s GPU2: 40 Sol/s GPU3: 41 Sol/s
23:13:21 Total speed: 162 Sol/s
23:13:28 INFO: Target: 001e1e1e1e000000...
23:13:28 INFO: Detected new work: 0000018b05e199b0
23:13:50 INFO: Detected new work: 0000018b05e1a0a3
23:13:51 Temp: GPU0: 66C GPU1: 66C GPU2: 63C GPU3: 66C
23:13:51 GPU0: 40 Sol/s GPU1: 41 Sol/s GPU2: 41 Sol/s GPU3: 41 Sol/s
23:13:51 Total speed: 163 Sol/s
23:13:54 INFO: GPU2 Accepted share 47ms [A:1, R:0]
23:13:59 INFO: GPU3 Accepted share 41ms [A:1, R:0]
23:14:09 INFO: Target: 001e1e1e1e000000...
23:14:09 INFO: Detected new work: 0000018b05e1a746
23:14:10 INFO: GPU1 Accepted share 62ms [A:1, R:0]
23:14:22 Temp: GPU0: 66C GPU1: 66C GPU2: 64C GPU3: 66C
23:14:22 GPU0: 43 Sol/s GPU1: 43 Sol/s GPU2: 43 Sol/s GPU3: 42 Sol/s
23:14:22 Total speed: 171 Sol/s
23:14:41 INFO: Target: 001e1e1e1e000000...
23:14:41 INFO: Detected new work: 0000018b05e1b161
23:14:49 INFO: GPU0 Rejected share 51ms [A:0, R:1]
23:14:52 Temp: GPU0: 66C GPU1: 67C GPU2: 64C GPU3: 66C
23:14:52 GPU0: 39 Sol/s GPU1: 41 Sol/s GPU2: 42 Sol/s GPU3: 40 Sol/s
23:14:52 Total speed: 162 Sol/s
23:14:59 INFO: GPU0 Rejected share 43ms [A:0, R:2]
23:15:06 INFO: GPU0 Rejected share 46ms [A:0, R:3]
23:15:08 INFO: GPU2 Rejected share 39ms [A:1, R:1]
23:15:11 INFO: Detected new work: 0000018b05e1ba81
23:15:21 INFO: Target: 003c3c3c3c000000...
23:15:22 Temp: GPU0: 66C GPU1: 66C GPU2: 64C GPU3: 67C
23:15:22 GPU0: 42 Sol/s GPU1: 42 Sol/s GPU2: 42 Sol/s GPU3: 41 Sol/s
23:15:22 Total speed: 167 Sol/s
23:15:25 INFO: GPU2 Rejected share 69ms [A:1, R:2]
23:15:32 INFO: GPU1 Rejected share 63ms [A:1, R:1]
23:15:35 INFO: Target: 003c3c3c3c000000...
23:15:35 INFO: Detected new work: 0000018b05e1c23f
23:15:46 INFO: GPU0 Accepted share 63ms [A:1, R:3]
23:15:50 INFO: Detected new work: 0000018b05e1c73e
23:15:52 Temp: GPU0: 66C GPU1: 67C GPU2: 64C GPU3: 67C
23:15:52 GPU0: 39 Sol/s GPU1: 42 Sol/s GPU2: 42 Sol/s GPU3: 44 Sol/s
23:15:52 Total speed: 167 Sol/s
23:15:57 INFO: GPU1 Accepted share 43ms [A:2, R:1]
23:16:02 INFO: GPU3 Accepted share 39ms [A:2, R:0]
23:16:03 INFO: GPU3 Accepted share 45ms [A:3, R:0]
23:16:04 INFO: GPU1 Accepted share 49ms [A:3, R:1]
23:16:07 INFO: GPU0 Accepted share 51ms [A:2, R:3]
23:16:17 INFO: GPU3 Accepted share 43ms [A:4, R:0]
23:16:20 INFO: Detected new work: 0000018b05e1cd27
23:16:22 Temp: GPU0: 66C GPU1: 67C GPU2: 64C GPU3: 67C
23:16:22 GPU0: 40 Sol/s GPU1: 41 Sol/s GPU2: 42 Sol/s GPU3: 44 Sol/s
23:16:22 Total speed: 167 Sol/s
23:16:26 INFO: Target: 003c3c3c3c000000...
23:16:26 INFO: Detected new work: 0000018b05e1d521`

**Comment by thebeerbaron2018** [comment]
Eurrgghhhh sorry about the format

**Comment by thebeerbaron2018** [comment]
OK - so "--pers auto" should be used and looking at line 73 of the EWBF.ps1 - it should be added - but it's not!

`Arguments = "--api 127.0.0.1:$($Miner_Port) --cuda_devices $($DeviceIDsAll) --server $($Pools.$Algorithm_Norm.Host) --port $($Pool_Port) --fee 0 --eexit 1 --user $($Pools.$Algorithm_Norm.User)$(if ($Pools.$Algorithm_Norm.Pass) {" --pass $($Pools.$Algorithm_Norm.Pass)"})$(if ($MainAlgorithm_Norm -eq "Equihash24x5") {" --pers $(Get-EquihashCoinPers $Pools.$Algorithm_Norm.CoinSymbol -Default "auto")"}) $($_.Params)"
                `

**Comment by thebeerbaron2018** [comment]
I think it's the capital "E" of "Equihash24x5" since in data/algorithms.json it's "equishash24x5" - you should probably use all lower case throughout.  Unfortunately I don't have time right now to go through and see which other strings / conditions this might affect throughout the project.  I would push all strings (either calculated or hard coded) through a function that lowercases the entire string every time

**Comment by thebeerbaron2018** [comment]
OK so it appears that line 73 of EWBF.ps1 is the problem

I think : 
$MainAlgorithm_Norm -eq "Equihash24x5"

should be 
$Algorithm_Norm -eq "Equihash24x5"

**Comment by RainbowMiner** [comment]
Thank you so much for trying this out! I will correct the EWBF. Obviously it's a copy-n-paste bug :)

**Comment by thebeerbaron2018** [comment]
All algorithms benchmarked successfully.  I had one issue with excavator where it benchmarked one algorithm (skunk) which went over to a second interval, after the second interval expired it completed and it then switched to another excavator algorithm (ethash) but during the switch it closed excavator and then sat there without excavator open doing nothing.  This only happened where the excavator benchmark for the first algorithm runs into a second interval.  When excavator starts and completes the benchmark within one interval - excavator issues the message that "I/O stopped" and then the new algorithm for excavator starts up in the same session which is perfect.  Difficult to replicate and only happened once and all I did was stop and restart RM and it then benchmarked ethash and moved on and did the rest

**Comment by thebeerbaron2018** [comment]
Re-benchmarking everything after your recent changes.  Will post results in 3-4 hours

**Comment by thebeerbaron2018** [comment]
All benchmarking done and repeated 6 times - no left over miners, no unexpectedly closed miners, everything benchmarked correctly.  OK to close this once you've reviewed it :)

**Comment by RainbowMiner** [comment]
Super! Thank you so much!
