### ISSUE TITLE
Beam is available at Nicehash

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#401]
Could be profitable.

https://www.beam.mw/downloads
https://github.com/BeamMW/beam/releases

**Comment by RainbowMiner** [comment]
Yes. BEAM is based on Equihash150,5 (Equihash25x5). We already have miners for that. Unfortunately, Gminer is currently not compatible with Nicehash.

**Comment by jch9678** [comment]
AMD is able to use the opencl miner I linked to however. Also I'm assuming
the cuda miner there works as well...

**Comment by Djago** [comment]
+1 to add Beam crypto to RainbowMiner!
Can you look at lolMiner to see if you can integrate it to RM?

**Comment by RainbowMiner** [comment]
Ah, yes. I have Lol Miner, already. Last year I published a release, including it. But the miner tend to hang the machines, so I removed it.
Since half a year has passed, I will give it a new try :)

**Comment by RainbowMiner** [comment]
Ok, so AMD will get Beam support asap.
I will have a look into the beammw Miner, too. Thanks for bringing this up!

**Comment by jch9678** [comment]
You're welcome

Just want to point out, the beam.mw miner is the only one that works for
AMD as far as I know. Hopefully it works for nicehash.

While on the subject of adding miners, wildrig multi has a few algos that
aren't listed but were in an alpha build; pyrite, mtp, and notably veil.
He's since updated the beta miner on bct but there's no mention of those
algos. However they do still work with the default bats from the alpha
build.  Veil is one you might want to look into. I can copy the contents of
the bats here if you need them.

**Comment by Djago** [comment]
> You're welcome Just want to point out, the beam.mw miner is the only one that works for AMD as far as I know. 

Check lolminer alpha, it also mines Beam with AMD.

**Comment by jch9678** [comment]
Thanks djago
