### ISSUE TITLE
Symbols missing from cryptocompare

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#402]
I get this error when I start RM and it shows up while it's running.

**Comment by RainbowMiner** [comment]
What is the exact message? Is it colored red or yellow (error or warning)?

**Comment by jch9678** [comment]
[debug-2019-02-04.zip](https://github.com/RainbowMiner/RainbowMiner/files/2830681/debug-2019-02-04.zip)

**Comment by RainbowMiner** [comment]
I just tested this on my system, and it works perfect. Eventually, your IP has been blocked at cryptocompare. 
Please try to open
https://min-api.cryptocompare.com/data/pricemulti?fsyms=AEON,ARQ,BBS,BLOC,BSM,ETN,ETNX,GRFT,INTU,IRD,KRB,LNS,LOKI,LTHN,MSR,NBR,RTO,RYO,SOLACE,SUMO,TRTL,TUBE,WOW,WTIP,XAO,XHV,XMR,XMV,XRN,XTL&tsyms=BTC&extraParams=https://github.com/rainbowminer/RainbowMiner 

in your Browser and send me the result.

**Comment by RainbowMiner** [comment]
In the current release, I reduced the frequency of cryptocompare API calls significantly. This should help to keep your accesses below the API's limits.

**Comment by jch9678** [comment]
I get this warning now:

WARNING: Cryptocompare says tsyms param is invalid. (tsyms length is higher than maxlength: 100)

**Comment by RainbowMiner** [comment]
Ok, it looks like, the cryptocompare API has a new restricting, regarding the length of the query string. I will break it down to multiple queries in the next release.

**Comment by RainbowMiner** [comment]
Would you please drop me a current Debug file? I would like to see, which currencies will be converted..

**Comment by jch9678** [comment]
[debug-2019-02-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/2847045/debug-2019-02-08.zip)

**Comment by jch9678** [comment]
also just want to point out that lolminer now supports nicehash (i hate nicehash) and wildrig multi brought support back for hawaii.

**Comment by RainbowMiner** [comment]
Thank you! Ok, I'll update the two of them.

**Comment by RainbowMiner** [comment]
Fixed with v3.9.6.0
