### ISSUE TITLE
jcemineramd power is 0W

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#404]
Right now JceminerAMD is listed with 0W. Other miners have <>0 values so profitability is not accurately

**Comment by Djago** [comment]
No, other miners have values <>0. JceminerAMD is the only one at 0

**Comment by RainbowMiner** [comment]
Normally, that would indicated, that the benchmark has failed. Eventually, it did not manage to run jcemineramd successfully.

**Comment by Djago** [comment]
Now, I think related to Issue (https://github.com/RainbowMiner/RainbowMiner/issues/412) it's not listed so I can't tell you anything about it.
