### ISSUE TITLE
pwsh is using up all ram and locking systems now.

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#405]
So I never had this issue before with rainbow. However, since a few updates back I started to notice systems bogging down and not responding making it harder to manage remotely. It seems that after pwsh runs for a half a day it ends up maxing out all the ram available causing bad system lag. I am attaching screen shots. This is exactly why I stopped using multipool miner as they to had a ram problem they would not fix. I hope you can come up with a solution as it is destroying my usability of windows. I do have page files set to 100mb cache but still not helping the issue. Attaching screen shots for examples.

Rack1:
![image](https://user-images.githubusercontent.com/42227809/52166452-3ff45980-26c2-11e9-9c08-a8749543ce10.png)

**Comment by RainbowMiner** [comment]
Oh dear! Would you please send me the current Debug file?

**Comment by Byrd1083** [comment]
Sorry was out for a while. When I start rainbow it does not immediatly use all ram but after a day or so of running it reaches over 70% ram being used. before it would stay around 50% which was not enough to notice system lag. This seems to be the case for all 5 of my rigs now.
![image](https://user-images.githubusercontent.com/42227809/52179009-e0618100-2789-11e9-960b-8d6584d1
[RainbowMiner_2019-02-03.txt](https://github.com/RainbowMiner/RainbowMiner/files/2825682/RainbowMiner_2019-02-03.txt)
[Activity_2019-02-03.txt](https://github.com/RainbowMiner/RainbowMiner/files/2825683/Activity_2019-02-03.txt)
[errors_2019-02-02.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2825685/errors_2019-02-02.asyncloader.txt)
[RainbowMiner_2019-02-02.txt](https://github.com/RainbowMiner/RainbowMiner/files/2825686/RainbowMiner_2019-02-02.txt)
[Activity_2019-02-02.txt](https://github.com/RainbowMiner/RainbowMiner/files/2825687/Activity_2019-02-02.txt)




2f53.png)
[errors_2019-02-03.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2825680/errors_2019-02-03.asyncloader.txt)
[RainbowMiner_2019-02-03.txt](https://github.com/RainbowMiner/RainbowMiner/files/2825681/RainbowMiner_2019-02-03.txt)

**Comment by RainbowMiner** [comment]
What is your switching interval? Is it really that super-super long?
I will add a solution for this.

**Comment by RainbowMiner** [comment]
Yes, that is the reason for the memory fill-up. I would recommend the following solution:
- set the Interval to moderate 600 (10 minutes)
- set MinimumMiningIntervals to 24

With this setting, the mining cache is being cleared every 10 minutes. RainbowMiner will wait until 24 x 10min. (=4hours), until it starts switching evaluation with 10 minute intervals, until it switches to a new miner. After that, it will again wait for four hours.

**Comment by Byrd1083** [comment]
Thank you, I will adjust reset and see how it works out. Thanks for the solution ;-)
