### ISSUE TITLE
Bminer issue at nicehash, failing to connect

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#407]
See pics. Very unfortunate, the RBM is stuck on Bminer equihash since it is the most profitable right now :(

![snip20190203_4](https://user-images.githubusercontent.com/35561346/52180703-ef781b80-27e9-11e9-9055-8ac033db51af.png)

![snip20190203_3](https://user-images.githubusercontent.com/35561346/52180696-d66f6a80-27e9-11e9-9426-23eae8c80527.png)

**Comment by RainbowMiner** [comment]
Yes, it turns out, Bminer is incompatible with Nicehash. BUT :) the Gminer has updated to v1.28 and that one turns out to be Nicehash-compatible.

**Comment by ebojali** [comment]
alright, then we can expect an update soon?

**Comment by RainbowMiner** [comment]
v3.9.4.5 it is.

**Comment by ebojali** [comment]
Great, always fast with the updates as usual! 👍
