### ISSUE TITLE
Latest version 3.9.4.5. Getting symbol errors on lookup at Cryptocompare.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#408]
![screenshot_20190203-113942_teamviewer](https://user-images.githubusercontent.com/801414/52181647-00546d00-27a9-11e9-8ff6-b09364822af4.jpg)
[debug-2019-02-03.zip](https://github.com/RainbowMiner/RainbowMiner/files/2825916/debug-2019-02-03.zip)

**Comment by RainbowMiner** [comment]
I think, the MiningPoolHub api has been down. It should resolve after time. Anyway, I will include a conversion table for MiningPoolHub, so that these warnings will not return.

**Comment by RainbowMiner** [comment]
I added coin tables.
