### ISSUE TITLE
Add timetravel10  (bitcore), and HSR algorithm

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#41]
Hi,

As title says, would be great if we could add supportfor bitcore timetravel10  as well as HSR algorithm.

**Comment by RainbowMiner** [comment]
HSR and BitCore (aka Timetravel10) are both included with RainbowMiner, already. You should enable these algorithm with "C"onfiguration->"S"elections. At input field "Algorithms".
HSR miners: CcminerPolytimos, EnemyZealot and Trex
BitCore miners: CcminerSpModBitcore, EnemyZealot and Trex

Actually, Bitcore is being mined on BlazePool and ZergPool, but far from profitbility.

RBM

**Comment by ebojali** [comment]
Hmm HSR is not included in the complete list, perhaps it has been disabled on the pools?

Regarding bitcore I belive that the some timetravel miners are bitcore specific below if I look at the hashrates. Perhaps algo name could be changed to bitcore or am I wrong?
EnemyZealot            1 % Timetravel                     334,86 MH/s 1333W 0,00058055   3,4399   4,0087         74 % BlazePool                                             1 %
CcminerTpruvotx64        - Timetravel                     206,27 MH/s 1227W 0,00036122   2,1403   2,4942         74 % BlazePool                                             1 %

GeForce GTX 1080 Ti (GPU#00,GPU#01,GPU#02,GPU#03,GPU#04,GPU#05)
===============================================================

Miner                  Fee Algorithm                            Speed Power   BTC/Day  EUR/Day  USD/Day      Accuracy Pool                                              PoolFee
-----                  --- ---------                            ----- -----   -------- -------- --------     -------- ----                                              -------
EnemyZealot            1 % X17                            139,56 MH/s 1221W 0,00115019   6,8152   7,9421         92 % ZergPool                                            0,5 %
Ewbf                     - Equihash24x5                   404,56  H/s 1273W 0,00101616   6,0211   7,0166         94 % ZergPool                                            0,5 %
Ewbf                     - Equihash24x7                   205,41  H/s 1152W 0,00098604   5,8426   6,8086         95 % ZergPool-Zero                                       0,5 %
CryptoDredge           1 % Lyra2RE2                       462,56 MH/s 1334W 0,00099718   5,9086   6,8855         92 % BlazePool                                             1 %
Ewbf                     - Equihash24x5-BTG               404,56  H/s 1273W 0,00100950   5,9816   6,9706         90 % MiningPoolHub-bitcoin-gold                          1,1 %
CryptoDredge           1 % Allium                          62,40 MH/s 1313W 0,00096564   5,7217   6,6678         94 % ZergPool                                            0,5 %
CcminerAlexis78          - X17                            117,37 MH/s 1297W 0,00097708   5,7895   6,7467         92 % ZergPool                                            0,5 %
CcminerPolytimos         - Lyra2RE2                       431,48 MH/s 1308W 0,00093958   5,5673   6,4878         92 % BlazePool                                             1 %
ClaymoreEthash     1,5 %,- {Ethash, Blake2s} {290,45 MH/s, 7,75 GH/s} 1148W 0,00090743   5,3768   6,2658 {96 %, 90 %} {MiningPoolHub-ethereum, NiceHash}           {1,1 %, 2 %}
ClaymoreEthash     1,5 %,- {Ethash, Blake2s} {291,48 MH/s, 5,83 GH/s} 1153W 0,00090359   5,3540   6,2393 {96 %, 90 %} {MiningPoolHub-ethereum, NiceHash}           {1,1 %, 2 %}
Phoenix             0,65 % Ethash                         294,96 MH/s 1149W 0,00090064   5,3366   6,2189         96 % MiningPoolHub-ethereum                              1,1 %
ClaymoreEthash     1,5 %,- {Ethash, Pascal}  {291,18 MH/s, 3,20 GH/s} 1162W 0,00090141   5,3411   6,2242 {96 %, 87 %} {MiningPoolHub-ethereum, NiceHash}           {1,1 %, 2 %}
CryptoDredge           1 % Lyra2z                          31,62 MH/s 1333W 0,00093801   5,5580   6,4769         92 % ZergPool                                            0,5 %
ClaymoreEthash     1,5 %,- {Ethash, Pascal}  {291,30 MH/s, 2,91 GH/s} 1161W 0,00089999   5,3327   6,2144 {96 %, 87 %} {MiningPoolHub-ethereum, NiceHash}           {1,1 %, 2 %}
EnemyZealot            1 % C11                            201,48 MH/s 1216W 0,00092682   5,4917   6,3997         92 % ZergPool                                            0,5 %
ClaymoreEthash     1,5 %,- {Ethash, Pascal}  {291,51 MH/s, 2,62 GH/s} 1160W 0,00089880   5,3257   6,2062 {96 %, 87 %} {MiningPoolHub-ethereum, NiceHash}           {1,1 %, 2 %}
ClaymoreEthash     1,5 %,- {Ethash, Blake2s} {291,40 MH/s, 3,89 GH/s} 1153W 0,00089628   5,3107   6,1888 {96 %, 90 %} {MiningPoolHub-ethereum, NiceHash}           {1,1 %, 2 %}
ClaymoreEthash     1,5 %,- {Ethash, Keccak}  {273,98 MH/s, 1,83 GH/s} 1171W 0,00089809   5,3214   6,2013 {96 %, 87 %} {MiningPoolHub-ethereum, ZergPool-MaxCoin} {1,1 %, 0,5 %}
Ethminer                 - Ethash                         290,56 MH/s 1150W 0,00089299   5,2913   6,1661         96 % MiningPoolHub-ethereum                              1,1 %
Bminer              0,65 % Ethash                         291,48 MH/s 1156W 0,00089001   5,2736   6,1455         96 % MiningPoolHub-ethereum                              1,1 %
ClaymoreEthash     1,5 %,- {Ethash, Keccak}  {263,60 MH/s, 2,64 GH/s} 1174W 0,00089707   5,3154   6,1942 {96 %, 87 %} {MiningPoolHub-ethereum, ZergPool-MaxCoin} {1,1 %, 0,5 %}
Trex                   1 % X16R                           138,48 MH/s 1289W 0,00107678   6,3802   7,4351         76 % BlazePool                                             1 %
Trex                   1 % SonoA                           21,33 MH/s 1284W 0,00104827   6,2113   7,2383         78 % ZergPool-Sono                                       0,5 %
CryptoDredge           1 % PHI2                            54,15 MH/s 1306W 0,00095487   5,6579   6,5934         86 % ZergPool-Lux                                        0,5 %
CcminerSupr              - C11                            190,29 MH/s 1200W 0,00088416   5,2389   6,1051         92 % ZergPool                                            0,5 %
Trex                   1 % C11                            191,39 MH/s 1286W 0,00088041   5,2167   6,0792         92 % ZergPool                                            0,5 %
EnemyZealot            1 % SonoA                           20,73 MH/s 1244W 0,00101889   6,0372   7,0354         78 % ZergPool-Sono                                       0,5 %
CcminerSupr              - X16S                           118,75 MH/s 1166W 0,00088325   5,2335   6,0989         91 % ZergPool                                            0,5 %
ClaymoreEthash     1,5 %,- {Ethash, Keccak}  {238,45 MH/s, 3,18 GH/s} 1208W 0,00084137   4,9854   5,8097 {96 %, 87 %} {MiningPoolHub-ethereum, ZergPool-MaxCoin} {1,1 %, 0,5 %}
CcminerPigeoncoin        - X16S                           115,92 MH/s 1265W 0,00086224   5,1090   5,9538         91 % ZergPool                                            0,5 %
CcminerKlaust            - Yescrypt                       115,07 KH/s 1306W 0,00089075   5,2780   6,1506         88 % BlazePool                                             1 %
Trex                   1 % X16S                           116,62 MH/s 1169W 0,00085872   5,0882   5,9294         91 % ZergPool                                            0,5 %
Bminer                 2 % Equihash24x5                   340,00  H/s 1192W 0,00083693   4,9591   5,7790         94 % ZergPool                                            0,5 %
EnemyZealot            1 % X16R                           123,09 MH/s 1307W 0,00095709   5,6710   6,6087         76 % BlazePool                                             1 %
Trex                   1 % Lyra2z                          27,45 MH/s 1225W 0,00081419   4,8243   5,6220         92 % ZergPool                                            0,5 %
Excavator1.4.4           - NeoScrypt                       11,00 MH/s 1187W 0,00087958   5,2118   6,0735         83 % ZergPool                                            0,5 %
CcminerTpruvotx64        - HMQ1725                         42,45 MH/s 1210W 0,00152146   9,0151  10,5057         39 % BlazePool                                             1 %
CcminerSupr              - X16R                           117,34 MH/s 1150W 0,00092160   5,4607   6,3636         76 % BlazePool                                             1 %
Excavator                - Equihash-NHMP                    4,23 KH/s 1276W 0,00076373   4,5254   5,2736         92 % NiceHash                                              2 %
EnemyZealot            1 % Hex                             96,34 MH/s 1278W 0,00077564   4,5959   5,3558         89 % ZergPool-XDNA                                       0,5 %
CcminerXevan             - Xevan                           36,22 MH/s 1166W 0,00077627   4,5996   5,3601         89 % ZergPool                                            0,5 %
Trex                   1 % PHI                            253,00 MH/s 1337W 0,00076168   4,5132   5,2594         89 % ZergPool                                            0,5 %
CryptoDredge           1 % NeoScrypt                       10,26 MH/s 1260W 0,00081260   4,8149   5,6110         83 % ZergPool                                            0,5 %
CcminerAlexis78x64       - Skein                            5,73 GH/s 1330W 0,00079707   4,7229   5,5038         84 % BlazePool                                             1 %
EnemyZealot            1 % PHI2                            42,79 MH/s  920W 0,00075452   4,4708   5,2100         86 % ZergPool-Lux                                        0,5 %
CcminerTpruvotx64        - Allium                          44,13 MH/s  857W 0,00068984   4,0875   4,7633         94 % ZergPool                                            0,5 %
EnemyZealot            1 % PHI                            235,61 MH/s 1274W 0,00070935   4,2031   4,8981         89 % ZergPool                                            0,5 %
EnemyZealot            1 % Xevan                           32,81 MH/s 1228W 0,00069613   4,1248   4,8068         89 % ZergPool                                            0,5 %
EnemyZealot            1 % X16S                            91,23 MH/s 1121W 0,00067180   3,9806   4,6388         91 % ZergPool                                            0,5 %
CcminerSpModPhi          - PHI                            220,08 MH/s 1314W 0,00066927   3,9656   4,6213         89 % ZergPool                                            0,5 %
CryptoDredge           1 % PHI                            214,81 MH/s 1324W 0,00064672   3,8320   4,4656         89 % ZergPool                                            0,5 %
CcminerTpruvotx64        - Lyra2z                          20,59 MH/s  821W 0,00061697   3,6558   4,2602         92 % ZergPool                                            0,5 %
Excavator                - NeoScrypt-NHMP                  11,06 MH/s 1196W 0,00063454   3,7599   4,3815         87 % NiceHash                                              2 %
Bminer                 2 % Equihash                         4,36 KH/s 1266W 0,00061836   3,6640   4,2698         90 % MiningPoolHub-zcash                                 1,1 %
CryptoDredge           1 % Tribus                         892,04 MH/s 1336W 0,00064269   3,8081   4,4378         79 % BlazePool                                             1 %
Trex                   1 % Tribus                         888,96 MH/s 1334W 0,00064048   3,7950   4,4225         79 % BlazePool                                             1 %
Excavator                - Lyra2z-NHMP                     21,05 MH/s  854W 0,00053567   3,1740   3,6988         92 % NiceHash                                              2 %
CcminerTpruvotx64        - CryptoNightV7                    5,63 KH/s  778W 0,00051191   3,0332   3,5347         95 % MiningPoolHub-monero                                1,1 %
CcminerTpruvotx64        - CryptoNightV7                    5,63 KH/s  778W 0,00051191   3,0332   3,5347         95 % MiningPoolHub-monero                                1,1 %
EnemyZealot            1 % Tribus                         820,62 MH/s 1298W 0,00059124   3,5033   4,0825         79 % BlazePool                                             1 %
CcminerKlaust            - YescryptR16                     19,84 KH/s 1168W 0,00051679   3,0622   3,5685         89 % ZergPool                                            0,5 %
CcminerSkunk             - Skunk                          320,91 MH/s 1211W 0,00057722   3,4202   3,9857         77 % BlazePool                                             1 %
EnemyZealot            1 % Timetravel                     334,86 MH/s 1333W 0,00058055   3,4399   4,0087         74 % BlazePool                                             1 %
CcminerCryptonight       - CryptoNightV7                    5,04 KH/s  803W 0,00045781   2,7127   3,1612         95 % MiningPoolHub-monero                                1,1 %
CcminerCryptonight       - CryptoNightV7                    5,04 KH/s  803W 0,00045781   2,7127   3,1612         95 % MiningPoolHub-monero                                1,1 %
CcminerTpruvotx64        - SonoA                           10,14 MH/s 1254W 0,00050332   2,9823   3,4754         78 % ZergPool-Sono                                       0,5 %
CcminerAlexis78x64       - KeccakC                          7,84 GH/s 1333W 0,00054835   3,2492   3,7864         65 % ZergPool-CreativeCoin                               0,5 %
Excavator                - CryptoNightV7-...                4,50 KH/s  816W 0,00039654   2,3496   2,7381         93 % NiceHash                                              2 %
CcminerTpruvot           - Tribus                         588,54 MH/s 1318W 0,00042831   2,5379   2,9575         79 % BlazePool                                             1 %
CcminerTpruvotx64        - Timetravel                     206,27 MH/s 1227W 0,00036122   2,1403   2,4942         74 % BlazePool                                             1 %
CcminerPolytimos         - Keccak                           8,06 GH/s 1339W 0,00030303   1,7955   2,0924         87 % ZergPool-MaxCoin                                    0,5 %
EnemyZealot            1 % Polytimos                      266,66 MH/s 1244W 0,00093789   5,5573   6,4761          7 % ZergPool-Polytimus                                  0,5 %
CcminerAlexis78          - Polytimos                      230,97 MH/s 1312W 0,00082057   4,8621   5,6660          7 % ZergPool-Polytimus                                  0,5 %
CcminerAlexis78x64       - Polytimos                      225,16 MH/s 1265W 0,00079993   4,7399   5,5235          7 % ZergPool-Polytimus                                  0,5 %

**Comment by RainbowMiner** [comment]
> Hmm HSR is not included in the complete list, perhaps it has been disabled on the pools?
.. yes. That is the point.

Bitcore is TimeTravel10
TimeTravel alone is different

RBM

**Comment by ebojali** [comment]
Yeah, but I can't find the timetravel10 in the list of benched algos? @RainbowMiner

**Comment by RainbowMiner** [comment]
Yes, because it is BitCore. That should be found in the list.

RBM
