### ISSUE TITLE
Gminer Not Benchmarking Beam and Crashing on cuckaroo29

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#410]
I added equihash150 to the config file but no luck.  Did I miss a step? In algorithms beam is called beam and not equihash150.  This is all getting very confusing.

and cuckaroo29 crashes on benchmarking.  This is on a single 1060 6GB.

Nothing benchmarks using Bminer.

**Comment by RainbowMiner** [comment]
> and cuckaroo29 crashes on benchmarking. This is on a single 1060 6GB.

Yes, too bad, but it supports 8GB GPUs, only, at this point. I had hoped for the better, but unfortunatly it's not.

Equihash25x5 = Equihash150 = Beam

All of the beam will be translated to Equihash25x5, internally.
