### ISSUE TITLE
News: rbminer.net will be upgraded to a dedicated server

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#411]
I will upgrade the rbminer.net to a dedicated server now, so the monitoring service might be down for some (short) time. It's pretty well in use, so the current hosting plan turned out to be too weak.

So please do not be alarmed, if you get RainbowMiner warnings about rbminer.net. All will be back to normal after a short period of time.

**Comment by paulpoco** [comment]
Ok still not reachable

**Comment by RainbowMiner** [comment]
It is back online to normal operations, now. It took longer than expected for the SSL certificate to be reactivated.
