### ISSUE TITLE
CryptonightV8 not active

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#412]
Hi!

CNv8 miners are not listed as active (and not listed in the screen), but they're not banned in the config and I haven't changed anything (it was working right! I don't know when I've lost it).
[debug-2019-02-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/2834955/debug-2019-02-06.zip)

**Comment by RainbowMiner** [comment]
All looks normal. It should mine CnV8 on MiningPoolHub. Have a look at "Benchmarks" on http://localhost:4000 and search for "CryptonightV8" - eventually there are failed benchmarks.
Do you remember, which miner did the CnV8-job?

**Comment by Djago** [comment]
On benchmark I have several Ok, like SRB, Cast, and some failures.
It was handled by Teamred but last benchmark it went down a lot. I think that SRB is the best regarding hashrate. But I have an issue with JCE reporting 0W (issue 404 https://github.com/RainbowMiner/RainbowMiner/issues/404)

**Comment by Djago** [comment]
![image](https://user-images.githubusercontent.com/34612740/52361631-6ea16580-2a1d-11e9-8057-c9b400eed67e.png)
I'm trying to upload a screenshot of active miners. But it's not working ok. The list is empty! Sometimes I manage to get the list, then I filter by Algorithm CryptonightV8 and get only one result (the CPU miner, and no Vega56 miner) and suddenly the list become empty. Should I report this as another issue?

**Comment by Djago** [comment]
![image](https://user-images.githubusercontent.com/34612740/52362198-cdb3aa00-2a1e-11e9-8b16-161d8a9acbb4.png)
Seconds later without my intervention:
![image](https://user-images.githubusercontent.com/34612740/52362215-d86e3f00-2a1e-11e9-98db-b523d26b6caa.png)

**Comment by RainbowMiner** [comment]
Do you have profitability checks enabled? Eventually the CnV8 is below profitability. CPU needs far less power than the Vega56, so it may be that CnV8 simply isn't profitable anymore.

**Comment by Djago** [comment]
Shouldn't it be listed under a negative profitability like the other miners?
![image](https://user-images.githubusercontent.com/34612740/52383623-e8a31000-2a58-11e9-9337-fb5d46af89d8.png)
This is my Energycost configuration:
![image](https://user-images.githubusercontent.com/34612740/52383778-85fe4400-2a59-11e9-9524-43478cdc68b8.png)

**Comment by Djago** [comment]
With current market revaluation the list of most profitable has changed a bit, but CNv8 still is not listed. What can I do? What's the best way to reset RM without losing my config?

**Comment by RainbowMiner** [comment]
Sorry for not having checked back onto your issue. I have been busy with the last release of RainbowMiner.
So.. first, you should not need to reset RM at all.
If you want a whole new set of config files, do the following: copy Start.bat to something like Start2.bat and open it in an editor. Now find the line 
```
@set "command=& {.\rainbowminer.ps1 -configfile .\Config\config.txt; exit $lastexitcode}"
```
.. and change `.\Config\config.txt` to a new name, e.g. `.\Config\config2.txt`
If you now start Rainbowminer using the Start2.bat, a complete set of config files will be created:
config2.txt
devices.config2.txt
pools.config2.txt
..


But maybe, let me find out about the CNv8 issue, first :)

**Comment by RainbowMiner** [comment]
So is it still the case, that you see all CNv8 miners, when browsing the "Benchmarks" page?

**Comment by RainbowMiner** [comment]
I fixed mining with FireIce on single AMD rigs.

**Comment by Djago** [comment]
> So is it still the case, that you see all CNv8 miners, when browsing the "Benchmarks" page?

Yes

**Comment by Djago** [comment]
I updated Andrenaline drivers to latest, and RM did a full re-benchmark of all VEGA56 miners, including all CNv8 miners. But still, in the Active miners page, I don't see any VEGA56+CNv8 miner.

**Comment by RainbowMiner** [comment]
I have got an idea: please zip the whole ".\Stats\Miners" folder and drop it here. With this, I will find out about the CNv8 on your rig.

**Comment by Djago** [comment]
[Miners.zip](https://github.com/RainbowMiner/RainbowMiner/files/2849643/Miners.zip)

Have in mind that now I'm with the issue [https://github.com/RainbowMiner/RainbowMiner/issues/419](url)
So I don't know the state of the stats... (RM is still benchmarking...)

**Comment by RainbowMiner** [comment]
The issue #419 is solved. Sorry for that!

**Comment by Djago** [comment]
Back to "normality" (I mean, RM is not benchmarking), but still CNv8 is not listed in my Active miners (with Vega, I have active FireIce for CPU mining)

**Comment by Djago** [comment]
Do you want me to try to start with a new config to see if the CNv8 miners are still inactive?

**Comment by Djago** [comment]
Now Cuckaroo29 is also absent on the list of Active miners!

**Comment by RainbowMiner** [comment]
What the heck! Do you already run the newest release v3.9.7.2?
Would you please drop me the file `.\Data\minerinfo.json` ?

**Comment by Djago** [comment]
I was with a previos version, don't remember 3.9.7.2. Now 3.9.7.5 GRIN is back!

**Comment by Djago** [comment]
I've lost my Cuckaroo29 again... But I can't see it in the Miners page of the webfig!
[minerinfo.zip](https://github.com/RainbowMiner/RainbowMiner/files/2898272/minerinfo.zip)

**Comment by RainbowMiner** [comment]
Super strange! 
What do those url say:
http://localhost:4000/watchdogtimers
http://localhost:4000/stats

Actually, there is some more data, but those lines would contain your passwords and wallets. Eventually I could arrange looking onto your rig, personally. Do you have TeamViewer installed?

**Comment by Djago** [comment]
> Super strange!
> What do those url say:
> http://localhost:4000/watchdogtimers

[
  {
    "MinerName": "CpuminerJayddee-CPU#00",
    "DeviceModel": "CPU",
    "PoolName": "NLpool",
    "Algorithm": "YescryptR16",
    "Kicked": "2019-02-25T03:11:06.1605817Z"
  },
  {
    "MinerName": "Teamred-GPU#00",
    "DeviceModel": "Vega56",
    "PoolName": "Zpool",
    "Algorithm": "PHI2",
    "Kicked": "2019-02-25T03:11:06.1605817Z"
  }
]

> http://localhost:4000/stats

[stats.zip](https://github.com/RainbowMiner/RainbowMiner/files/2898869/stats.zip)

> 
> Actually, there is some more data, but those lines would contain your passwords and wallets. 

If you wish I can erase whatever you want in that data

> Eventually I could arrange looking onto your rig, personally. Do you have TeamViewer installed?

Yes, actually 99% of my jobs are done with TeamViewer

**Comment by Djago** [comment]
After CN went to v9 the new algo appeared in the list (with SRB miner)
