### ISSUE TITLE
Monitoring Central shows miner in status offline

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#413]
Seems like the rig is offiline state on the 
![image](https://user-images.githubusercontent.com/35561346/52328718-ddb49500-29f0-11e9-8b53-a65e1ce8527c.png)

Althought the miner is up and running. 

![image](https://user-images.githubusercontent.com/35561346/52327557-dab7a580-29ec-11e9-84ff-05046dfc1e84.png)

**Comment by RainbowMiner** [comment]
I upgraded the server, so it took some time to move everything #411

**Comment by ebojali** [comment]
Ok, thanks. All is fine now :)
