### ISSUE TITLE
Error while start up.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#414]
I have one PC without any GPU's and as the script starts up I get this error. Script still functions. Just more of a visual error. Not sure if it can be resolved?

WARNING: OpenCL device detection has failed: Exception calling "GetPlatformIDs" with "0" argument(s): "Unable to load DLL 'OpenCL': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)"

I have the config set to only CPU.

**Comment by RainbowMiner** [comment]
I see. Thank you for pointing at this. I will remove this message in the next release.
