### ISSUE TITLE
New OpenCL Warning

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#415]
I'm getting this:

Transcript started, output file is .\Logs\RainbowMiner_2019-02-08_17-04-55.txt
Detecting devices ..
WARNING: OpenCL device detection has failed: Exception calling "GetPlatformIDs" with "0" argument(s): "OpenCl error -1001: -1001."
Initialize configuration ..
Read configuration ..
WARNING: No devices available. Please check your configuration.

[debug-2019-02-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/2847217/debug-2019-02-08.zip)

**Comment by jch9678** [comment]
Something happened to my system, no miner detects an opencl gpu.  argh

**Comment by RainbowMiner** [comment]
Oh dear! Did you change anything (update from master.zip, update GPU drivers, etc), or did this just happen? If yes, I'ld try a reboot at first, if that does not help, check, if you can find the GPU in windows device manager, or if it is marked with error, or even isn't there anymore (both of these two may indicate, that the GPU is broken, alas!) 
If the GPU is still there, try to reinstall the GPU drivers. Eventually Windows has updated the drivers in the background.

**Comment by jch9678** [comment]
It was windows changing something.  It was stuck between restarts one one computer and I had to reinstall drivers on another.
