### ISSUE TITLE
New version v3.9.6.0 gets some red errors on startup and some balances don't work

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#416]
@RainbowMiner red errors and some balance symbols full word Livecoin vs LTC and these don't show balance.
[debug-2019-02-09.zip](https://github.com/RainbowMiner/RainbowMiner/files/2847888/debug-2019-02-09.zip)

![screenshot_20190209-061738_teamviewer](https://user-images.githubusercontent.com/801414/52521902-59058900-2c33-11e9-907f-5d17e282c685.jpg)

**Comment by RainbowMiner** [comment]
Weird enough! Only some are missing. I will find out, why.

**Comment by RainbowMiner** [comment]
Ah, ok. Found this one. The API failed after some calls. Actually, there were some calls in place, that are no longer needed. I fixed this.
