### ISSUE TITLE
Benchmark keeps going on 2 miners

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#419]
Hi!
 After installing the newest Adrenaline 19.2.1 RM started an all-out benchmark of my VEGA56 miners. It started and at some point, while I was absent, my Win10 decided "It's a good time to update", so today when I came back RM was nowhere to be found running. I fire it up again and it continued (remaining 30 miners). Then when there were 4 left, RM auto-updated to 3.9.6.3.
Now I'm at 2 miners left:

Currently:
ClaymoreEthash  1 %,- {Ethash, Blake2s} {35,17 MH/s, Benchmarking}
ClaymoreEthash  1 %,- {Ethash, Keccak}  {14,18 MH/s, Benchmarking}

In the Running I see:
{14,04 MH/s, 0  H/s} 00d/00h/25m 2 Times ClaymoreEthash {Ethash, Keccak} {ethereum-classic, $null} Vega 56

And after a cycle:
{29,03 MH/s, 0  H/s} 00d/00h/04m Once    ClaymoreEthash {Ethash, Blake2s} {ethereum, $null} Vega 56

(note the $null in the Coin column)

Sometimes I see some errors about "WARNING: Could not request from 127.0.0.1:20301" or "WARNING: Stat file (CpuminerOptBF-CPU#00_Yespower_HashRate) was not updated because the value (0) is outside fault tolerance (542 to 1733).", but benchmarking never ends, it only cycles between those two miners.
They were both working fine on previous runs. I don't know if the driver broke the deal or if later RM or miner version did. But the thing is that RM does not end the benchmark on its own.
I've tried going to config, devices, vega56 (I have CPU, GTX550Ti, Vega56) and excluding ClaymoreEthash, but it doesn't go away and RM still try to benchmark it.
I went to Running Config in the webfig and I see 4 devices instead of 3: "CPU", "GTX550Ti", "RXVega", "Vega56" (the GTX is not in use for RM). But I have RXVega and Vega56. Is this ok? The exclusion I put on the config is written on the Vega56 but not on the RXVega. Is this ok?
I manually added the same exclusion to RXVega in the devices.txt but it still tries to benchmark them.
I've tried disabling dual mining, to no avail.
I've tried excluding Keccak and Blake2s, to no avail.

**Comment by Djago** [comment]
Looking at Miners page in the webfig and restricting to ClaymoreEthash I have:
![image](https://user-images.githubusercontent.com/34612740/52538932-58661300-2d57-11e9-894f-8c8f46f81746.png)
Why 3

**Comment by Djago** [comment]
I've also tried mining only one algo (cuckaroo29) and still, RM tries to finish the benchmarks

**Comment by RainbowMiner** [comment]
Oh dear! Please delete Miners\claymoreethash.ps1 for now. I will check, what is going on.

**Comment by RainbowMiner** [comment]
Sorry for that! It's fixed, now. I will publish a new release.

**Comment by Djago** [comment]
Great! Sorry for the delay, my cat has broken my keyboard (an expensive one!). Right now I'm checking it.
It seems that my backspace key is dead  :P
