### ISSUE TITLE
Failed miners not showing up in the "benchmark" list webpage

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#42]
No falied miners are included in the benchmark list, only the ones that are benched OK and the ones that needs a benchmark. Could you please update so that failed miner are showed with the status "Failed". Some of my miners are failing a benchmark. 

The below miners fail, I really hope you can help me out here and get them benched..

   Status: Failed

Last Speed Active                      Launched Miner            Device      Power Command

           00 Days 00 Hours 21 Minutes 3 Times  XmrigNvidia      GTX 1080 Ti 458W  NVIDIA-Xmrig\xmrig-nvidia.exe -R 1 --cuda-devices=0,1,2,3,4,5 --api-port 30300 -a cryptonight-heavy -o stratum+tcp://cryptonightheavy.eu.nicehash.com:3364 -u
                                                                                   3PYGmPBzvzjzAnwzeYPXtKKd9FpBYgB9So.rig1 -p x --keepalive --nicehash --donate-level=1
           00 Days 00 Hours 15 Minutes 3 Times  Bminer           GTX 1080 Ti 0W    Equihash-BMiner\bminer.exe -devices 0,1,2,3,4,5 -api 127.0.0.1:30700 -uri ethstratum://DBminer.rig1:x@europe.ethash-hub.miningpoolhub.com:17020 -watchdog=false
                                                                                   -no-runtime-info -gpucheck=0
           00 Days 00 Hours 18 Minutes 3 Times  CcminerPolytimos GTX 1080 Ti 0W    NVIDIA-Polytimos\ccminer.exe -R 1 -b 10000 -d 0,1,2,3,4,5 -a polytimos -q -o stratum+tcp://polytimos.mine.zergpool.com:8463 -u 19CHzK8ATbN7mNiv48fGnCnbLuzyitvEcC -p
                                                                                   rig1,c=BTC -N 1
           00 Days 00 Hours 08 Minutes 3 Times  Fireice          GTX 1080 Ti 286W  yptoNight-FireIce\xmr-stak.exe -C NiceHash_CryptoNightHeavy_3PYGmPBzvzjzAnwzeYPXtKKd9FpBYgB9So.rig1_30800.txt --noUAC --noAMD --noCPU -i 30800

![snip20180828_16](https://user-images.githubusercontent.com/35561346/44746981-3e6ba780-ab0c-11e8-9536-4dad884e208f.png)

**Comment by RainbowMiner** [comment]
Sure. In the next bugfix release, I will include the list and fixes for CcminerPolytimos. The other three miner fails look like overclocking. Better you lower your maximum memory oc a little bit.

RBM

**Comment by ebojali** [comment]
The bugfix for poly works now and the failed benchmarks shows up in the list.  But you recommend reducing the memory overclock a bit, I am using the settings you recommended in ticket 33.

Profile 1: power 80%, core +0, mem +0
Profile 2: power 80%, core +100, mem +500
Profile 3: power 80%, core +100, mem +300
Profile 4: power 80%, core +100, mem +0
Profile 5: power 80%, core +100, mem +450

So which profile is set for the other three?

**Comment by RainbowMiner** [comment]
I would change the profile numbers for the Miner/algorithm combination. You can use "C"onfiguration - "M"iners for it. 
- enter miner's name
- enter device name
- enter algorithm name
- now you can enter all setup parameters for this exact combination.

For bminer/ethash try Profile 3 (if still.not working use Profile 4)
For the other two try Profile 5 (if not working Profile 3, if still not working Profile 4)

If no way for a Miner, you can also use Profile 1.
This is the order of Profile Numbers, from fastest to slowest:
2-5-3-4-1

RBM

**Comment by ebojali** [comment]
To be honest I run into problems when inputing the parameters, Entering miner, devicename and algo is fine but how do I configure the profiles for the miner in the parameter input? What is the exact syntax etc.

**Comment by ebojali** [comment]
Update: For Bminer profile 4 worked fine, managed to benchmark the ethash algo

**Comment by RainbowMiner** [comment]
Super :) I will keep this in mind for a future FAQ.

I just screen copied the miner's config:
![miners-config2](https://user-images.githubusercontent.com/39437538/44780404-29316000-ab82-11e8-9c19-e6c6df00776d.PNG)

For the configuration variables:
- just press return for variables, you want to keep
- enter the profile number at "MSI Afterburner Profile" (I entered 5, for example)
- at the end, enter "yes" to safe

RBM

**Comment by RainbowMiner** [comment]
I have an update for Profile 4: you should lower the memory oc to **-500** - this will give an extra boost to balloon, lyra2z, lyra2re2, x16r, x16s, at least for most of my rigs. If you do so, I would be very interested, if it increases hashrates for you, as well.

RBM

**Comment by ebojali** [comment]
I'll try it out and let you know in a new ticket.. 

Meanwhile I must say that XmRig-Nvidia doen't work at all.

**Comment by RainbowMiner** [comment]
> Meanwhile I must say that XmRig-Nvidia doesn't work at all for my rig.

Sometimes this is the case. At this time, this miner is not profitable, anyway.

RBM

**Comment by ebojali** [comment]
Yeah, perhaps it is time to remove it?
