### ISSUE TITLE
Getting stuck with no Pool

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#422]
I've had one of my miners several times get stuck in a loop telling me that there are no available pools. This machine happens to get disconnected once and a while and that is when it gets stuck in the loop. Requires me to manually restart the script. Any chance it can check, Or Restart the script after so much time?

**Comment by RainbowMiner** [comment]
I will try to figure out, what is happening. Normally it should simply reconnect after internet is back up.

**Comment by Yamanipanuchi** [comment]
This is what I am getting...

Finished waiting - starting next run
WARNING: Stat file (Phoenix-GPU#00_Ethash_HashRate) was not updated because the value (9165250) is outside fault tolerance (19729500 to 26306000).
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
...............................
WARNING: No pools available. Press [X] to exit.
.............

**Comment by thebeerbaron2018** [comment]
Could this be due to the watchdog kicking the pools due to internet outage?

**Comment by RainbowMiner** [comment]
Yes, most likely the watchdog - I will put something in place, that resets the watchdog.

**Comment by RainbowMiner** [comment]
I have added multiple functions to prevent this. If it happens ever again, please reopen this issue.
