### ISSUE TITLE
Idea for pool comparison

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#423]
An idea I've attempted with spreadsheets but it never was feasible due to manual entry. Use the average of the algorithm you have bench marked and apply the profit a crossed all pools for visual purposes. Like a one stop location to see if another pool could possibly be profitable but you do not have it added to your list of pools. If you have this opt enabled then it would update all pools say once a day with stats. This of course would not take care of the bursts you get though the day. But it would give a reasonable indication if a pool is consistently more profitable then the ones you have selected?

I only throw it out there because a lot of the information I would manually enter in the spreadsheet is already being collected by Rainbowminer.

**Comment by RainbowMiner** [comment]
I like this idea and will try to implement it.
