### ISSUE TITLE
Cryptodredge Allium issue

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#425]
![image](https://user-images.githubusercontent.com/35561346/52699018-10bcd280-2f75-11e9-899a-14ae372f7813.png)

[log_31300.txt](https://github.com/RainbowMiner/RainbowMiner/files/2859553/log_31300.txt)

**Comment by RainbowMiner** [comment]
Yes, this is an issue :) I will add a rejected shares ratio to the miner's calculation asap.

**Comment by ebojali** [comment]
Allium Stratum giving lots of rejects with Cryptodredge miner:
[20:25:35] INFO  - 11/1706 Rejected : diff=0.00551201, reason: Invalid extranonce2 size
Don´t know if it´s pool or miner issue

stop using cryptodredge
read above
or ask them to fix it


[12:45:26] INFO  - 0/1 Rejected : diff=0.0738062, reason: Invalid extranonce2 size   <<<   Dev needs to fix this bug in the miner.
WildRig had the same issue with extranonce2, the Dev fixed it.

Seems like a bug in Cryptodredge

**Comment by RainbowMiner** [comment]
From the comeing release on, RainbowMiner uses build-in checks for miners running into bad-shares problems on some algorithm/pools. As soon as the bad shares rate rises above 30% the running miner will be stopped and restarted three to four times, until the watchdog catches it and disables the miner/pool combination for some time.
