### ISSUE TITLE
Issue: Crash

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#427]
I keep having a rack crash. It appears to keep trying to benchmark from zergpool on algo "mtp". I have excluded it but it keeps doing this. My 1070's crash flat out when running mtp.

[RainbowMiner_2019-02-14_10-37-19.txt](https://github.com/RainbowMiner/RainbowMiner/files/2866662/RainbowMiner_2019-02-14_10-37-19.txt)
[Activity_2019-02-14.txt](https://github.com/RainbowMiner/RainbowMiner/files/2866663/Activity_2019-02-14.txt)
[RainbowMiner_2019-02-14.txt](https://github.com/RainbowMiner/RainbowMiner/files/2866665/RainbowMiner_2019-02-14.txt)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2866666/config.txt)

**Comment by RainbowMiner** [comment]
This should now be solved. MTP causes a bigger than usual current peak, at startup, so if your PSU doesn't like this, the rig might crash. The algo has been on my most wanted algorithms list during donation run. I have removed it, so no more crashes should happen.
