### ISSUE TITLE
Issue: Autoupdate not working

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#428]
I have auto update set on all 5 rigs. Non of them will auto update. I always have to manually push.
![image](https://user-images.githubusercontent.com/42227809/52828205-b1e28080-307c-11e9-801f-491c0228f725.png)
[RainbowMiner_2019-02-14.txt](https://github.com/RainbowMiner/RainbowMiner/files/2867403/RainbowMiner_2019-02-14.txt)
[Activity_2019-02-14.txt](https://github.com/RainbowMiner/RainbowMiner/files/2867404/Activity_2019-02-14.txt)
[errors_2019-02-14.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2867405/errors_2019-02-14.asyncloader.txt)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2867406/config.txt)

**Comment by RainbowMiner** [comment]
Weird! Would you be so kind and drop a Debug file of one of those rigs? http://localhost:4000/debug

**Comment by RainbowMiner** [comment]
Question: how long have you been waiting for the auto update? Longer than 2 hours? It may take up to 2 hours, until RainbowMiner detects the new version.

**Comment by Byrd1083** [comment]
Yes, longer then 2 hours. In config when I have autoconfig set to 0, it will alert me when updates are available. When I set to 1, it no longer alerts of update and it will not auto update ever. For example, yesterday I was running version 6.6. I just logged on and still had to manually press U to update to 6.8 just now. Here is logs from my single gpu 1080ti rig.
[RainbowMiner_2019-02-15.txt](https://github.com/RainbowMiner/RainbowMiner/files/2869846/RainbowMiner_2019-02-15.txt)
[RainbowMiner_2019-02-15_07-43-58.txt](https://github.com/RainbowMiner/RainbowMiner/files/2869847/RainbowMiner_2019-02-15_07-43-58.txt)
[RainbowMiner_2019-02-14_17-21-37.txt](https://github.com/RainbowMiner/RainbowMiner/files/2869848/RainbowMiner_2019-02-14_17-21-37.txt)
[Activity_2019-02-15.txt](https://github.com/RainbowMiner/RainbowMiner/files/2869849/Activity_2019-02-15.txt)
[errors_2019-02-15.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2869850/errors_2019-02-15.asyncloader.txt)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2869854/config.txt)

**Comment by Byrd1083** [comment]
[debug-2019-02-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/2869927/debug-2019-02-15.zip)

**Comment by RainbowMiner** [comment]
I just remembered I had added some blocker, that would avoid endless update loops (if the updates fails for three time, it would kick in).
Would you please drop the following file (of the 1080ti rig):
`\Logs\autoupdate.txt`

**Comment by Byrd1083** [comment]
I'm out for a few hours. Will post as soon as I get back to the terminal.

**Comment by RainbowMiner** [comment]
No need to hurry :) That's the thing with bugs. Normally, they do not run away.

**Comment by Byrd1083** [comment]
[
  {
    "6D92F9A9FA8DB00039A6F953C1D69F10": {
      "Url": "http://api.blazepool.com/wallet/3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:45.3588602Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "A8E8806D5F792AF4A3AC7F22C93D8171": {
      "Url": "https://phi-phi-pool.com/api/walletEx?address=3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:46.2955799Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "7CDA2661B415D60E8D91C740DF283C66": {
      "Url": "https://www.nlpool.nl/api/currencies",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:43:05.5162147Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "NLpool",
      "Timeout": 10
    },
    "28FF979BFEF0A498E0827A6ECCFFDE65": {
      "Url": "http://api.zergpool.com/api/walletEx?address=3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:47.6377346Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "globalticker": {
      "Url": "https://min-api.cryptocompare.com/data/pricemulti?fsyms=BCH,BTG,MAX,RVN,SUQA,XWP&tsyms=BTC&extraParams=https://github.com/rainbowminer/RainbowMiner",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 9,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:34:31.5192937Z",
      "CycleTime": 1800,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "58C730968CA9FBFD639F2B72C099998A": {
      "Url": "https://zpool.ca/api/walletEx?address=3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:47.9006671Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "2840F27C2638EF5B777645A59E8573FB": {
      "Url": "https://www.starpool.biz/api/walletEx?address=3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 15,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:48.6381176Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "882D4B94AD70991A5CD76C35DABD06C4": {
      "Url": "https://cryptoknight.cc/nginx.conf",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 1,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:34:35.9966746Z",
      "CycleTime": 14400,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "CryptoKnight",
      "Timeout": 10
    },
    "B311AB8BF590F057CD8E94D3F791881D": {
      "Url": "https://www.gos.cx/api/currencies",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 13,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:44:36.9734627Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "GosCx",
      "Timeout": 10
    },
    "129EEBD48499F44461AC39205F59C403": {
      "Url": "http://www.ahashpool.com/api/walletEx?address=3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:50.2323409Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "6FA6450021E13BDE522A2D7D5F1117BF": {
      "Url": "https://phi-phi-pool.com/api/currencies",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 13,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:44:42.5650493Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "PhiPhiPool",
      "Timeout": 10
    },
    "D5984F50896C6EC1277F605F541BF452": {
      "Url": "http://api.bsod.pw/api/currencies",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 5,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:43:06.6926478Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "Bsod",
      "Timeout": 10
    },
    "coinbase": {
      "Url": "https://api.coinbase.com/v2/exchange-rates?currency=BTC",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 25,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:50.3196175Z",
      "CycleTime": 600,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "B9B39235CE9E2A089CF5A51A83680FA4": {
      "Url": "https://cryptoknight.cc/rpc/swap/stats",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 5,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:43:08.025466Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "CryptoKnight",
      "Timeout": 15
    },
    "40E67D4227FB4B62CC332A440665FE9E": {
      "Url": "https://api.nicehash.com/api?method=simplemultialgo.info",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 1,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:34:36.1645003Z",
      "CycleTime": 600,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "NiceHash",
      "Timeout": 10
    },
    "0084F7EF939A632C802925757C67E34F": {
      "Url": "https://miningpoolhub.com/index.php?page=api&action=getuserallbalances&api_key=17fd69aa072aa202644f72c758573b1977f1e08f5c7f082768b6604565fba53d",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:50.4161913Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "1B3AC42F311725519AA8BCD9F5EB895B": {
      "Url": "http://api.bsod.pw/api/status",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 5,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:43:08.9424993Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "Bsod",
      "Timeout": 10
    },
    "600BD8297FC84921FE8FD6F6591BE03A": {
      "Url": "http://blockmasters.co/api/currencies",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 110,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:48:45.1964512Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "BlockMasters",
      "Timeout": 10
    },
    "926A7204A22C75B9D45E4DBE2B8D1034": {
      "Url": "http://pool.hashrefinery.com/api/walletEx?address=3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:50.555826Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "B7A3394FC0A540F3D0884D51891BBC01": {
      "Url": "https://nlpool.nl/api/walletEx?address=3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:50.848992Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "CF6B480CCADD0F94919E433BCFB39B6A": {
      "Url": "http://www.zpool.ca/api/status",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 5,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:43:09.1675698Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "Zpool",
      "Timeout": 10
    },
    "073E8495BECCB2AD61D7362A62C7884A": {
      "Url": "http://api.zergpool.com:8080/api/currencies",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 114,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:48:55.7463862Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "ZergPool",
      "Timeout": 10
    },
    "59774A27FE2C8F40D095BBF3C8D1CFDD": {
      "Url": "https://icemining.ca/api/currencies",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 13,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:44:41.5427023Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "Icemining",
      "Timeout": 10
    },
    "84C47803F9BBFA93AB452433B29941EB": {
      "Url": "https://api.github.com/repos/rainbowminer/RainbowMiner/releases/latest",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 5,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:44:36.0272143Z",
      "CycleTime": 3600,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "24D96806516095669AE3818188A978BB": {
      "Url": "http://blockmasters.co/api/status",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 110,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:48:45.2456856Z",
      "CycleTime": 120,
      "Retry": 3,
      "RetryWait": 1000,
      "Tag": "BlockMasters",
      "Timeout": 10
    },
    "D1A292F5C725D9900DB61DBDCFDA1C72": {
      "Url": "http://blockmasters.co/api/walletEx?address=3D4GSnKapLgUhxFfYowd81FojoBDNHMBR1",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:51.6498022Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "9B8D3F77FF714598BCE6AC505C91A328": {
      "Url": "http://www.zpool.ca/api/currencies",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 5,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:43:09.5921217Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "Zpool",
      "Timeout": 10
    },
    "8E1441C812D0F89E80632A78D1A4E15F": {
      "Url": "https://api.nicehash.com/api?method=stats.provider&addr=3NhaZNEFqHLB8dXXwPxnvaAGg71GPiz1xB",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 17,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:46:52.0139337Z",
      "CycleTime": 900,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "",
      "Timeout": 10
    },
    "9A60A4C43A44E9EBF6417154B302652D": {
      "Url": "https://www.nlpool.nl/api/status",
      "Error": null,
      "Running": false,
      "Paused": true,
      "Method": "REST",
      "Success": 5,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:43:10.0079261Z",
      "CycleTime": 120,
      "Retry": 0,
      "RetryWait": 250,
      "Tag": "NLpool",
      "Timeout": 10
    },
    "D68792A6DE6680A70A90147E98C0832C": {
      "Url": "http://api.zergpool.com:8080/api/status",
      "Error": null,
      "Running": false,
      "Paused": false,
      "Method": "REST",
      "Success": 114,
      "Fail": 0,
      "Prefail": 0,
      "LastRequest": "2019-02-15T19:48:56.2496437Z",
      "CycleTime": 120,
      "Retry": 3,
      "RetryWait": 1000,
      "Tag": "ZergPool",
      "Timeout": 10
    }
  }
]

**Comment by RainbowMiner** [comment]
> Would you please drop the following file (of the 1080ti rig): `.\Logs\autoupdate.txt`

**Comment by Byrd1083** [comment]
[autoupdate.txt](https://github.com/RainbowMiner/RainbowMiner/files/2873066/autoupdate.txt)
