### ISSUE TITLE
WARNING: GPU/CPU mining conflict: GPU-only will not be started for best profit

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#429]
Since last update (3968) I'm getting:
WARNING: GPU/CPU mining conflict: GPU-only will not be started for best profit
And RM won't use best profit miner:
![image](https://user-images.githubusercontent.com/34612740/52834956-0f99bb80-30c3-11e9-815e-e4b99e69ae3d.png)
and:
![image](https://user-images.githubusercontent.com/34612740/52834969-322bd480-30c3-11e9-9cbd-2b1ebc7aab85.png)

**Comment by paulpoco** [comment]
Same here.

What if I want to run both GPU and CPU?

**Comment by RainbowMiner** [comment]
I see that this new feature bings up some questions.
Some GPU mining algorithm like Cuckaroo29 put a heavy load on to the PC's CPU thus significantly reducing the CPU miner results, if used in parallel. So I put in some mechanic that decides what to do.
If such a GPU miner is to be started, it calculates what is more profitable:
- running this CPU hungry GPU miner and avoid CPU mining in parallel
- running the next best GPU combo that does not cause CPU load, but continue using the CPU

For very fast CPU, like the Ryzen, it would make only very insignificant difference, so I will add a switch to disable this feature at will.

**Comment by RainbowMiner** [comment]
I have added switch `EnableCheckMiningConflict` to config.txt - it defaults to `"1"`, if your CPU has 4 cores or lower, only. So, from the next release on, you may change this at will.

**Comment by Djago** [comment]
Great, I have a Ryzen 1700 so no difference for me!
