### ISSUE TITLE
ccminer-Polytimos unknown algo parameter error

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#43]
See picture, error during benchmarks.
![snip20180828_15](https://user-images.githubusercontent.com/35561346/44746073-af5d9000-ab09-11e8-9116-f6933fa1955b.png)

**Comment by RainbowMiner** [comment]
This is a false algo parameter. I will fix it with the next bugfix release (in an hour or so)

RBM
