### ISSUE TITLE
do not start new miner with exactly the same algo/card combo, keep mining the same

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#430]
I have seen this issue since MTP started. Example. I have TT-Miner mining MTP on GTX1060 6GB, other algo/miner on the other cards, 1060 3GB and 1050tis. After a few cycles other algo/miner might start on the other cards/combos but MTP is started back on 1060 GB same TT-Miner. MTP mining is losing all that time getting prime again when it should keep mining the same since it shouldn't stop mining to start back again the same. The miner is not crashing is just getting close along with the others at the end of the cycle.

**Comment by RainbowMiner** [comment]
Thank you for pointing at this. I will check, what is happening. Would you please be so kind and drop a current Debug file here (http://localhost:4000/debug)?

**Comment by RainbowMiner** [comment]
Is it possible, that the pool has changed for the miner? And, does this happen for MTP, only, or for any combination?

**Comment by hernandn01** [comment]
it is possible that the miner has change. I had showminer windows 0, put 1 and kept on eye until it did happen same pool, same miner
[debug-2019-02-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/2869180/debug-2019-02-15.zip)

**Comment by hernandn01** [comment]
it just happen again. either ttminer tried to mined with all combos? but it did not released the others? it appear that physically only the 6GB can mine MTP, so the others are fine.
![image](https://user-images.githubusercontent.com/41829368/52856834-b8a3de80-30e2-11e9-94c5-5fb670135a1e.png)

**Comment by RainbowMiner** [comment]
Oh, I see. There is a devices problem with the TTminer. I'll check the miner module.

**Comment by hernandn01** [comment]
you are welcome

**Comment by RainbowMiner** [comment]
Found a fix :) Will be part of the next release.

**Comment by RainbowMiner** [comment]
I just published a new release. The miner problem should be solved, now. If anything weird happens on your rig now, please report back.

**Comment by hernandn01** [comment]
updating now

**Comment by hernandn01** [comment]
fixed, waiting for the next change to see if the miner continues to mine or not
![image](https://user-images.githubusercontent.com/41829368/52867749-d3844c00-30fe-11e9-9330-e3e0ca53a8ca.png)

**Comment by RainbowMiner** [comment]
Now this looks amazing :) Thanks for reporting back.

**Comment by hernandn01** [comment]
it changes the others but mtp mining hold as expected, thanks
![image](https://user-images.githubusercontent.com/41829368/52870029-290f2780-3104-11e9-8919-3be10e7c5df9.png)

**Comment by hernandn01** [comment]
working perfect, TT-miner is constantly mining MTP now. Thanks

![image](https://user-images.githubusercontent.com/41829368/52879030-6af79800-311b-11e9-952b-6f655f419464.png)
