### ISSUE TITLE
Issue: System Crash

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#431]
Can you see any reason why my 14 gpu 1070 rig keeps crashing? I only have the clocks set to +200 on ram and +-0 clock rates with nvidiaprofileinspector with locked voltage 650000. Yet it will crash occasionally.

[RainbowMiner_2019-02-15_07-51-30.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871499/RainbowMiner_2019-02-15_07-51-30.txt)
[RainbowMiner_2019-02-15.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871500/RainbowMiner_2019-02-15.txt)
[Activity_2019-02-15.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871501/Activity_2019-02-15.txt)
[errors_2019-02-15.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871502/errors_2019-02-15.asyncloader.txt)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871503/config.txt)
[debug-2019-02-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/2871504/debug-2019-02-15.zip)

**Comment by Byrd1083** [comment]
This 6 gpu 1070 is crashing as well. Been stable for a long time. I hope we are not crashing during donation on an algo that my system will not run stable. Here is last logs from crash. Appears windows bsod and restart. Again only +200 mem and 0 clock.

[RainbowMiner_2019-02-15_07-51-46.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871597/RainbowMiner_2019-02-15_07-51-46.txt)
[RainbowMiner_2019-02-15.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871598/RainbowMiner_2019-02-15.txt)
[Activity_2019-02-15.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871599/Activity_2019-02-15.txt)
[errors_2019-02-15.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2871600/errors_2019-02-15.asyncloader.txt)
[debug-2019-02-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/2871601/debug-2019-02-15.zip)

**Comment by Byrd1083** [comment]
Just curious, can the donation run be set to only run the algos in the config list if not already that way?

**Comment by RainbowMiner** [comment]
They are both crashing on x16r with trex. Since this is a composition of multiple algorithms, changing frequently, I bet one of them overdrives the GTX 1070.
 Actually, I would not go faster than +150 for clock overdrive on GTX 1070. Also you might want to set a maximum powerlimit of not more than 85%. This makes sure the power spikes during x16r switching do not kill your system.

**Comment by RainbowMiner** [comment]
Btw, all of these OC can easily be done using RainbowMiner. For x16r, for example, you might want so set mem -500. It increases the efficiency for this kind of algorithms.

**Comment by RainbowMiner** [comment]
I just re-checked with my GTX1070 rigs: the maximum clock is set to +100, only.
Also make sure, that [**CUDA - Force P2 State**" is set to off](https://github.com/RainbowMiner/RainbowMiner/issues/36)

**Comment by RainbowMiner** [comment]
Also, I will prepare nice presets for Rainbowminer overclocking with OCprofiles

**Comment by Byrd1083** [comment]
Just to clarify, I have nvidiainspector set to as follows and have not had any issues with all 37x 1070's.

Mem + +200
clock = 0
power = 100
temp = 80
voltage locked = 650000

**Comment by RainbowMiner** [comment]
I would put my bets on some optimization in Trex/X16r that kills the rig at some algorithm combination. Eventually, you could try to disable X16R on Trex and see, if other miners do cause the same issue, or if it is a Trex-only thing. Just open "miners.config.txt", find the "Trex-GTX1070", and then the "MainAlgorithm": "X16r" subsection. In this section, set "Disable": "1"

```
  "Trex-GTX1070": [
    {
      "MainAlgorithm": "X16r",
      "SecondaryAlgorithm": "",
      "Params": "",
      "OCprofile": "Profile4",
      "MSIAprofile": "4",
      "Difficulty": "",
      "Penalty": "",
      "Disable": "1"
    },
```

**Comment by RainbowMiner** [comment]
Btw: how on earth did you manage to get such low power of 65W on a GTX1070. That's pretty awesome!

**Comment by Byrd1083** [comment]
Seems to be good to go for now. I think I was having issues with a bad gpu that is acting up. You can lock 1070 voltage to 650000 and achieve that wattage. Anything lower and it will crash bsod.

**Comment by Byrd1083** [comment]
Seems to be good to go for now. I think I was having issues with a bad gpu that is acting up. You can lock 1070 voltage to 650000 and achieve that wattage of 58~62watts by using the batch file outside of rainbow. Anything lower and it will crash bsod. Just load the batch file at system startup. I scraped msi af a year ago. I've also been able to lock 1080ti stable at 850000mV which runs about 180~200 watts depending on algo running.
