### ISSUE TITLE
Trex x21s fails to connect on MiningRigRentals & a little bit on CryptoDredge too

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#432]
Trex x21s fails to connect on MiningRigRentals & a little bit on CryptoDredge too.
[debug-2019-02-15 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/2871714/debug-2019-02-15.1.zip)
Appears to be cycling thru both miners.

20190215 23:31:03 ERROR: No connection, retry after 10 seconds
20190215 23:31:24 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20190215 23:31:24 WARN: failed to subscribe, JSON-RPC call failed: can't parse json:
* Line 1, Column 1
  Syntax error: value, object or array expected.

20190215 23:31:24 ERROR: No connection, retry after 10 seconds

Of course while writing this post, Trex appears to be working again.

**Comment by RainbowMiner** [comment]
This looks 99% like a problem on the renter's side. This is why both miners fail - and cycle.
