### ISSUE TITLE
Monitoring Central doesn't expand when selecting plus sign

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#433]
Monitoring Central doesn't expand when selecting plus sign.
![screenshot_20190216-100209_chrome](https://user-images.githubusercontent.com/801414/52903427-051a1780-31d2-11e9-84c4-3c5bea577c6c.jpg)

**Comment by jch9678** [comment]
I have this problem too with one of my accounts.

**Comment by hernandn01** [comment]
I've been having this problem too

**Comment by RainbowMiner** [comment]
Ha, this looks pretty much like an on-page javascript problem. I will fix this.

**Comment by jch9678** [comment]
Along the same lines, when a worker goes offline, it stays green, does not go red.

**Comment by ebojali** [comment]
Same issue here! :)

**Comment by paulpoco** [comment]
@RainbowMiner did you figure out how to fix this?

**Comment by RainbowMiner** [comment]
I will have a look, now. Sorry for the delay.

**Comment by RainbowMiner** [comment]
Solved :) Reload browser (eventually clear cache).

**Comment by paulpoco** [comment]
Working now, thanks
