### ISSUE TITLE
Worth looking at?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#434]
I get this Red text when the script starts up on one of my Systems.

------------------------
Initialize configuration ..
Get-ChildItem : Cannot find path 'C:\RainbowMiner\Config\gpugroups.config.txt' because it does not exist.
At C:\RainbowMiner\Include.psm1:3257 char:18
+                 (Get-ChildItem $PathToFile).LastWriteTime = Get-Date
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\RainbowMiner...oups.config.txt:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Get-ChildItem : Cannot find path 'C:\RainbowMiner\Config\gpugroups.config.txt' because it does not exist.
At C:\RainbowMiner\Include.psm1:3257 char:18
+                 (Get-ChildItem $PathToFile).LastWriteTime = Get-Date
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\RainbowMiner...oups.config.txt:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Get-ChildItem : Cannot find path 'C:\RainbowMiner\Config\gpugroups.config.txt' because it does not exist.
At C:\RainbowMiner\Include.psm1:3257 char:18
+                 (Get-ChildItem $PathToFile).LastWriteTime = Get-Date
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\RainbowMiner...oups.config.txt:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

WARNING: Unable to write to file C:\RainbowMiner\Config\gpugroups.config.txt
Resolve-Path : Cannot find path 'C:\RainbowMiner\Config\gpugroups.config.txt' because it does not exist.
At C:\RainbowMiner\Core.psm1:100 char:95
+ ... ath = $Session.ConfigFiles["GpuGroups"].Path | Resolve-Path -Relative
+                                                    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\RainbowMiner...oups.config.txt:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

------------------------------

**Comment by Yamanipanuchi** [comment]
This PC does not have a GPU...

**Comment by RainbowMiner** [comment]
Yes, thank you :) I will remove this warning.

**Comment by RainbowMiner** [comment]
Ok, fixed.
