### ISSUE TITLE
Invalid Xnonce2 size MTP on nicehash with TT-miner

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#438]
![image](https://user-images.githubusercontent.com/35561346/53095682-c4960300-351d-11e9-8bee-815832de3eed.png)

this might be a miner issue.. See your discoord channel

**Comment by RainbowMiner** [comment]
I updated to a special TTminer beta version that supports MTP mining

**Comment by jch9678** [comment]
This is probably why sgminerfancy wasn't working for me on an AMD card at
nicehash
