### ISSUE TITLE
Excavator 1.4.4

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#439]
I have two systems that seem to get stuck on bench marking this miner. I am going to simply add it to the exclusion list for now. It looks as if Rainbow Miner never gets a response from the miner itself.

**Comment by jch9678** [comment]
Nicehash deprecated it. Maybe rm should just remove it. I don't use it
though.

**Comment by Yamanipanuchi** [comment]
Keeps trying to use it on Blockmasters. I'm going to just leave it disabled.

**Comment by RainbowMiner** [comment]
This old thing! I just forgot about it. It will be removed.
