### ISSUE TITLE
the term 'dotnet' is not recognized

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#440]
![image](https://user-images.githubusercontent.com/41829368/53138888-0d14e700-3545-11e9-9b2f-fae9153d9a6f.png)

**Comment by hernandn01** [comment]
it continued, it doesn't appear to be affecting much

**Comment by paulpoco** [comment]
Same here.

I looked that dot net instructions awhile back from the SDK and didn't quite figure out how to install.  Will try again when I get a chance.

**Comment by RainbowMiner** [comment]
Ah, sorry for that error! It does not affect anything.

This is the dotnet download page: https://dotnet.microsoft.com/download
![image](https://user-images.githubusercontent.com/39437538/53159145-91a74a00-35c5-11e9-85ad-fdd970e5cfc0.png)

Click one of the two marked things, button or link.

**Comment by hernandn01** [comment]
fixed. Thanks
