### ISSUE TITLE
.net runtime vs sdk

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#441]
I think the runtime should be sufficient to run the grin miners unless I'm mistaken.

**Comment by RainbowMiner** [comment]
No, you really need this one:
![image](https://user-images.githubusercontent.com/39437538/53159216-b69bbd00-35c5-11e9-9975-958581d60707.png)

**Comment by giannibonfanti** [comment]
In my opinion, the prerequisite is .NET Core 2.2 Runtime.
Source: https://github.com/mozkomor/GrinGoldMiner/releases
and i'm using runtime only for grin/swap miners.

**Comment by RainbowMiner** [comment]
Ok, thanks for letting me know. I will try this out :) It would be much nicer, if we need the Runtime, only.

**Comment by RainbowMiner** [comment]
You are totally right. I rechecked on a non-developer rig and all works fine with Runtime.

**Comment by jch9678** [comment]
👍

Where is some more info about the swapminer

**Comment by RainbowMiner** [comment]
I am a huge fan of Swap, since the beginning: https://swap.fyi
The SwapMiner that comes with RainbowMiner is forked from here: https://github.com/swap-dev/SwapReferenceMiner/releases
