### ISSUE TITLE
General question: Grinpro miner

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#443]
How do I get Grinpro miner to Benchmark? I now have Net Core runtime 2.2.2, Latest driver 418.91 so that is Cuda 10. I saw that the binary was downloaded at one time. I have deleted the binary and is not downloading it again. I am not mining CPU. I see that the minimum requirement on GrinProMiner.ps1 to be 4 GB.

PS C:\Users\MINER1> (dir (Get-Command dotnet).Path.Replace('dotnet.exe', 'shared\Microsoft.NETCore.App')).Name
2.2.2

**Comment by RainbowMiner** [comment]
- Cuckaroo29 must be added to the Algorithm list in config.txt
- you will need a pool enabled that supports Cuckaroo29 (GrinPro is disabled for Nicehash)
- GrinPro and SwapMiner will both run in the background
- to find out, what they are currently up to (or if the have failed), look into .\Logs and find the latest "SwapMiner-GPU#00-..-GPU#xx-33700.. .txt" file.

**Comment by RainbowMiner** [comment]
Oh! Eventually the minimum memory requirement is wrong. It should be 8GB, not 4GB. GrinPro will not mine on 4GB.

**Comment by hernandn01** [comment]
I figured that much, I thought something change with the requirement of the net core runtime. Please fix the minimum on the grinprominer.ps1 file. Thanks
[PSCustomObject]@{MainAlgorithm = "cuckaroo29"; MinMemGb = 4;

**Comment by hernandn01** [comment]
answered
