### ISSUE TITLE
[Feature Request] Add "Personalized payment level" for Zergpool

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#444]
[Feature Request] Add "Personalized payment level" for Zergpool.
![screenshot_20190221-193624_chrome](https://user-images.githubusercontent.com/801414/53218292-6ac23580-3610-11e9-8260-bafd134c7655.jpg)

Using DASH for payout is too small in $ but if I used LTC it is too long to get paid.

You can only increase the minimum payment.

**Comment by RainbowMiner** [comment]
Woa, this enhancement needed a huge change! But it's done ;-)
Read about it here: https://github.com/RainbowMiner/RainbowMiner#add-additional-password-parameters-for-yiimp-based-pools
