### ISSUE TITLE
Issue: Donation Run

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#446]
I currently run x16r, x22i, and argon2dyn on blockmasters pool only. When donation run kicks in, it does this.
![image](https://user-images.githubusercontent.com/42227809/53289641-e4137280-374d-11e9-9e59-52d29a5b343f.png)

Would it not make sense to maximize your donation by continuing to run what is most profitable and stable for my miner? Could it not just simply switch to your wallet without changing any of the users config? I just does not make sense to mine less profitable algos on less profitable pools. Plus some systems are not stable on certain algos. You the dev will never really know what everyone's setup is. Remember last time I brought up donation, it was running algos that crashed my system. Yes it was excluded but still you are losing money my friend. Consider keeping donation run in line with my config file to minimize crashing and maximize your donation profits.

**Comment by Byrd1083** [comment]
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897052/config.txt)
[Activity_2019-02-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897054/Activity_2019-02-23.txt)
[RainbowMiner_2019-02-22_08-07-04.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897055/RainbowMiner_2019-02-22_08-07-04.txt)
[errors_2019-02-23.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897056/errors_2019-02-23.asyncloader.txt)
[autoupdate.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897057/autoupdate.txt)
[RainbowMiner_2019-02-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897058/RainbowMiner_2019-02-23.txt)

**Comment by RainbowMiner** [comment]
Thank you for bringing this up again. I will think about it.

**Comment by RainbowMiner** [comment]
The X16rt was last of it's kind. I forgot to delete it from the list. From now on, the algorithm preset is empty.

**Comment by Byrd1083** [comment]
What about the fact that bsod and zergpool are not the most profitable according to your program. How ever donation runs these pools. If it were my program, I would want donation to run most profitable pool regardless of user config. Again just my logic being shared. Thanks.
