### ISSUE TITLE
Issue: BSOD Pool API not working

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#447]
Tried using BSOD pool. No pool detected.
![image](https://user-images.githubusercontent.com/42227809/53293297-01643300-3786-11e9-969c-a14e81910667.png)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897424/config.txt)
[RainbowMiner_2019-02-23_16-12-21.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897425/RainbowMiner_2019-02-23_16-12-21.txt)
[RainbowMiner_2019-02-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2897426/RainbowMiner_2019-02-23.txt)

**Comment by Byrd1083** [comment]
Also pool balance does not show up under balances.

**Comment by RainbowMiner** [comment]
From time to time Bsod API is very slow (or down). If RainbowMiner manages to connect at least for one time, all will be good, because there will be some data in the cache.
