### ISSUE TITLE
Issue: Automatic update failed

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#449]
Automatic update failed!
[RainbowMiner_2019-02-25_09-48-19.txt](https://github.com/RainbowMiner/RainbowMiner/files/2901803/RainbowMiner_2019-02-25_09-48-19.txt)
[RainbowMiner_2019-02-24_14-28-23.txt](https://github.com/RainbowMiner/RainbowMiner/files/2901804/RainbowMiner_2019-02-24_14-28-23.txt)
[autoupdate.txt](https://github.com/RainbowMiner/RainbowMiner/files/2901805/autoupdate.txt)
[errors_2019-02-25.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/2901806/errors_2019-02-25.asyncloader.txt)
[Activity_2019-02-25.txt](https://github.com/RainbowMiner/RainbowMiner/files/2901808/Activity_2019-02-25.txt)
[RainbowMiner_2019-02-25.txt](https://github.com/RainbowMiner/RainbowMiner/files/2901809/RainbowMiner_2019-02-25.txt)

**Comment by RainbowMiner** [comment]
I remember, you mentioned that problem, before. Does the automatic update work, from time to time, or never? Only on this machine, or others, too?

**Comment by Byrd1083** [comment]
It only did the error on that one rig. Others seem to update fine. Could be permission issue but I have not had any changes. All rigs have identical systems and permissions. I'll post if it happens again. Just keeping you up to date ;-)
