### ISSUE TITLE
Ability to use NvidiaInspector to overclock the cards instead of MSI Afterburner

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#45]
Would if be possible for you to consider adding the feature of using NvidiaInspector instead of AfterBurner?
I have updated profile 4 to memory -500 and indeed there is an increase in Ballon hashrate but when a new miner starts and the profile is applied it affects all cards so Ethash hashrate decreases.
![image](https://user-images.githubusercontent.com/41829368/44814559-5984f880-ab9a-11e8-938a-fe2dd8dc2d4b.png)
An example of 3 cards command line is:
nvidiaInspector.exe -setBaseClockOffset:0,0,100 -setMemoryClockOffset:0,0,0 -setPowerTarget:0,60 -setBaseClockOffset:2,0,100 -setMemoryClockOffset:2,0,0 -setPowerTarget:2,60 -setBaseClockOffset:1,0,150 -setMemoryClockOffset:1,0,0 -setPowerTarget:1,60
Could this be constructed with the different cards combination that RainbowMiner already identifies tied with the profiles of Afterburner?

**Comment by RainbowMiner** [comment]
Oh, my! Yes, this is a bad constellation, since Ethash needs fast memory to perform well. Setting the GPU directly is possible, though it is a sophiticated task to program. I will try to figure out, how to do this.

What I did with mixed rigs: I did adjust the Afterburner overclocking values for the weakest GPU to the same values for all profiles (only for this weak cards), so that they got acceptable settings, no matter which profile is being set by RainbowMiner.

RBM

**Comment by hernandn01** [comment]
That is what I have been doing. Even lowering intensities per algo trying to unified all cards (1x1060-6gb, 1x1060-3gb and 2x1050ti). Since Ethash is not posible on the 3Gb card, I was splitting the miners manually. With RainbowMiner, I am able to do this and now that is has the power approximation feature for the 1050ti it is a much better implementation of other solutions that I have extensively used before like NemosMiner, Hashsynminer, Sniffdogminer, MultiPoolMiner, Megaminer, MindMiner. This implementation is much more elegant and easy to use. Having this kind of control over the cards will be just the cherry on top.

**Comment by RainbowMiner** [comment]
Thank you :) 
I will pick the cherry.
RBM

**Comment by Byrd1083** [comment]
You wouldn't happen to have any access to an ethpill for 1070's would you?

**Comment by RainbowMiner** [comment]
No :) the 1070 already has the better DRAM. This timing adjustment trick works on 1080 and Titan, only

RBM

**Comment by RainbowMiner** [comment]
I picked the cherry:
## CUSTOM OVERCLOCKING PROFILES

Recommended for mixed GPU mining rigs.

### Introduction

Each miner/device/algorithm combination can have it's own overclocking values set by RainbowMiner. To enable: set "**EnableOCProfiles**" to "**1**" in your config.txt or use the Configuration->Common.

### First setup overclocking profiles

Use the Configuration->OC-Profiles to edit and create different profiles. Values for PowerLimit, ThermalLimit, MemoryClockBoost and CoreClockBoost can be defined. You may name the profiles like you want. Of course you may also edit the ocprofiles.config.txt file directly.

### Second, assign profiles to miner-device-algorithms

The assignment is done, using either the Configuration->Miners or directly edited into the miners.config.txt file. Find your miner, the device it will use, plus the algorithm and put the profile's name into the field "**OCprofile**"
