### ISSUE TITLE
Test Machine Crashes includes debug file

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#451]
[debug-2019-02-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/2903096/debug-2019-02-25.zip)
Would you mind taking a look at this log and see if you can find a reason why this machine crashes all the time.

Thanks

**Comment by RainbowMiner** [comment]
It looks like the SrbMiner mining CryptonightHeavy crashes the rig. Eventually check if you can lower the intensity for this miner.

```
{"ActiveStart":"2019-02-25 11:52:41","ActiveLast":"2019-02-25 11:54:03","Name":"SrbMiner","Device":["R9390"],"Algorithm":["CryptoNightHeavy"],"Pool":["MinerRocks"],"Speed":[0.0],"Profit":7.9869774643052683E-05,"PowerDraw":275.0},
```

**Comment by jch9678** [comment]
I changed the intensity to a figure that used to work but it's still crashing.  It may have crashed on a different miner this time though, maybe when mtp switched to equihash25x5.  I attached a newer debug.

Could you add worksize and kernel to the config files that rainbowminer produces for srbminer:

So it would look something like this:

{
  "cryptonight_type": "heavy",
  "intensity": 0,
  "double_threads": false,
  "timeout": 10,
  "retry_time": 10,
  "gpu_conf": [
    {
      "id": 0,
      "intensity": 27,
      "worksize" : 8,
      "threads": 2,
      "kernel" : 1,
      "platform": "OpenCL"
    }
  ]
}

It will be much easier to troubleshoot and optimize.  Thanks
[debug-2019-02-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/2907225/debug-2019-02-26.zip)

**Comment by RainbowMiner** [comment]
Do you have experience with Worksize and Kernel for Srbminer? Are there any defaults, that I may add without killing some configuration?

**Comment by RainbowMiner** [comment]
Looking into your new debug file, every crash has been caused by the failing Srbminer/CryptonightHeavyXhv

**Comment by jch9678** [comment]
I believe I use kernel 1 but I have 290x and 390s so you can leave the defaults alone because the majority of the people are mining with rx cards.  It's just easier for me to go to the generated config and add kernel 1 and worksize 8 if those values are already there, default or otherwise.

I will have to do some testing with heavyxhv I guess.  27 intensity worked with 1.6.7 so maybe there have been some changes in the newer versions. (thought it didn't work with defaults either)  I will exclude that algorithm for now and hopefully the crashes stop.

Would you mind taking a look at this new debug file from a different machine.  I'm not sure why this one crashes but it crashes just as much as the other one.  Windows anti malware goes crazy on I think rainbowminer or the miner but it can barely draw to the cmd window.  Also the event viewer shows the driver crashing like every 4 seconds, doesn't really make sense.
[debug-2019-02-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/2911329/debug-2019-02-27.zip)

**Comment by jch9678** [comment]
By the way, are you sure it's cryptonightheavyxhv that is causing it to crash?  I know that is the last entry with 0 hashrate but usually rainbowminer tries to the more profitable coins first but those come up with 0 hashrate.

**Comment by RainbowMiner** [comment]
This is very well possible. It may be another type of crash besides the CnHeavyXhv. So, either it is the SgminerFancy that crashes the GPUs during runtime, or it's the lolminer at start. Eventually we need to differentiate between two phenomena: one that hangs the machine completely, and the other that crashes the GPUs, only.

**Comment by RainbowMiner** [comment]
Are these crashes since the update of the lolMiner to v0.7, eventually?

**Comment by jch9678** [comment]
I'll have to check. I'm not sure when these were updated to .7. The latest
alpha has been running for weeks without a problem on other machines.

**Comment by RainbowMiner** [comment]
Maybe that could be a cause - following the bitcointalk discussions and the issues for lolMiner it looks like the final version v0.7 has imported some bugs. I am considering to eventually fallback to the old combination v0.6 + v0.7alpha5
