### ISSUE TITLE
nlpool incorrectly shows the amount of the wallet

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#455]

**Comment by petrovsky34** [comment]
![1](https://user-images.githubusercontent.com/39003568/53668454-da1cd280-3c6b-11e9-906a-e256057508c9.PNG)
![default](https://user-images.githubusercontent.com/39003568/53668456-da1cd280-3c6b-11e9-867c-7e09347542e0.PNG)

**Comment by petrovsky34** [comment]
"BalanceUpdateMinutes":  "1",

**Comment by RainbowMiner** [comment]
Looks like double. I will check the balance calculation.

**Comment by petrovsky34** [comment]
ОК

**Comment by RainbowMiner** [comment]
Did this constantly happen with your VTC wallet? Also, could you send me your wallet address in plain text, so that is is easier for me to check?
