### ISSUE TITLE
Status: WAITING FOR PROFITABILITY

### ISSUE THREAD

**Issue by rhadamants** [RainbowMiner/RainbowMiner#456]
Miner   Fee Algorithm      Speed Power   BTC/Day  USD/Day  Accuracy Pool          PoolFee
-----   --- ---------      ----- -----   -------- -------- -------- ----          -------
Trex  1,00% X16rt     25,67 MH/s  232W 0,00020754   0,7885      82% GosCx-GINcoin       -

Status:
WAITING FOR PROFITABILITY
 (be patient or set CheckProfitability to 0 to resume)

No mining for hours after updating v3.9.8.3.
GosCx pool.

**Comment by RainbowMiner** [comment]
Please drop the current Debug file http://localhost:4000/debug here. I will check.

**Comment by RainbowMiner** [comment]
Have you enabled profitability check?
Is GosCx your only pool?

**Comment by RainbowMiner** [comment]
Ok, don't bother - I have found the problem. Fix is on the way. It happens, if only one miner is selected.

**Comment by RainbowMiner** [comment]
This is fixed with v3.9.8.4 - sorry for this bug!
