### ISSUE TITLE
Add sparkpool and f2pool

### ISSUE THREAD

**Issue by rhadamants** [RainbowMiner/RainbowMiner#458]
sparkpool and f2pool possible?

**Comment by RainbowMiner** [comment]
I will have a look into those two pools. In principle, every pool should be possible to add.

**Comment by RainbowMiner** [comment]
I have added SparkPool - that was easy. F2pool is a bit harder.

**Comment by rhadamants** [comment]
Thanks for SparkPool.
For Beam coin on Sparkpool need SSL or give this error:

> Connected to beam-us.sparkpool.com:2222
> Connection Error: End of file

**Comment by RainbowMiner** [comment]
Ok! I will enable ssl for beam. Also, there is an error with the price calculation in the actual release. I already posted a fix. Find the commit here: b0b13735fa47d2dc4e4da023d000727f069e0215

**Comment by RainbowMiner** [comment]
Currently working on f2pool. What a beast  🔨  to integrate!

**Comment by RainbowMiner** [comment]
F2pool hast been added. For some currencies you may use your F2pool username as wallet address (GRIN, ETH) for others a normal wallet address is needed. Happy mining!

**Comment by rhadamants** [comment]
Mining Grin on f2pool need username.

**Comment by RainbowMiner** [comment]
Yes, just enter your username as wallet address in the pool configuration, or directly in pools.config.txt, section "F2pool":
`  "GRIN": "yourusername",`

**Comment by RainbowMiner** [comment]
Regarding the download loop, it's normally related to some kind of writelock in Windows. I suspect TTminer locks some files and very seldom the download starts before the writelock is released. Luckily this happens very rarely. If you run into this problem, just press [R] for restart.

**Comment by rhadamants** [comment]
Restart, delete all TTminer not work.

**Comment by RainbowMiner** [comment]
Now that's weird! Is there any file explorer or some file opened inside the directory?

**Comment by RainbowMiner** [comment]
Try:
- [X] exit Rainbowminer
- delete all folders `.\Bin\NVIDIA-TTminer*`
- delete all files `.\Downloads\TTminer*.zip`
- make sure that `D:\adb\a` is excluded in your antivir
- now start RainbowMiner (with admin privileges)

**Comment by RainbowMiner** [comment]
Hmm.. that downloader thing happened to me with another miner, some time ago, too. Thinking about it, I eventually have an idea what could cause that.
Do you have a slow or fast CPU, slow or fast Internet?

**Comment by rhadamants** [comment]
Java runtime jre 1.8.0.201 lock this TTminer.

**Comment by RainbowMiner** [comment]
Oh! So TTminer uses jre. This is a hot trail. I'll try to figure something out. Eventually some wait time at the end of mining could help.

**Comment by rhadamants** [comment]
uninstall JRE solution.

**Comment by RainbowMiner** [comment]
Thank you. I will add a note to the readme.
