### ISSUE TITLE
TT-Miner 2.1.13 not working

### ISSUE THREAD

**Issue by giannibonfanti** [RainbowMiner/RainbowMiner#459]
It's a miner issue, but I wrote on bitcointalk and the reply is:

"please reload the miner. I made a mistake with the very first upload of the 2.1.13 - sorry. Please let me know if you still get the rejection."
https://bitcointalk.org/index.php?topic=5025783.msg50044822#msg50044822

But the miner keeps downloading from rbminer repo, so I think it should be reuploaded correctly.

**Comment by RainbowMiner** [comment]
No problem. I will push a release with the new TTminer 2.1.14
