### ISSUE TITLE
lolminer not working

### ISSUE THREAD

**Issue by RetroShag** [RainbowMiner/RainbowMiner#46]
![image](https://user-images.githubusercontent.com/39284708/44824674-ef3d7980-abd4-11e8-9910-6a9b6d68f53f.png)

**Comment by hernandn01** [comment]
this is the error I received when trying lolminer
![image](https://user-images.githubusercontent.com/41829368/44830688-3b41eb80-abe0-11e8-98d7-68a873feb57d.png)

**Comment by ebojali** [comment]
The lolminer is benchmarking for me but it's status is failed benchmark and it is not showing up in the complete miner list:
![image](https://user-images.githubusercontent.com/35561346/44837890-20e92b80-ac3b-11e8-9de0-3c6dfaaa90d5.png)

![image](https://user-images.githubusercontent.com/35561346/44837924-33fbfb80-ac3b-11e8-9df4-6174efcba0e8.png)

**Comment by RainbowMiner** [comment]
Too bad. This miner seems to be instable for non-GTX1070 rigs.
I will look into it.
RBM
