### ISSUE TITLE
Swapminer just benchmarked but don't have a Wallet Address

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#460]
I'm not sure how swap at cryptoknight pools benchmarked because I don't have that wallet set up there.  Also the window is not showing even though I have it set to 1.

**Comment by jch9678** [comment]
I'm guessing this was for the dev fee. As it seemed somewhat profitable and is not in my list for profitability, would it be possible to keep showing the benchmarks but label it as inactive or something.  It would be nice to see what the benchmarks are for coins that are hidden (dev fee) or excluded.  Eg I have excluded argond2dyn because it seems to be causing crashes but I would still like to see the profitability.

**Comment by RainbowMiner** [comment]
Yes, that was dev fee mining. The SwapMiner is special, since it will run in the background, only. The reason for that is, it doesn't have a build in API, so I have to parse the miner's output. But you will find SwapMiner files in the Logs folder.
I'll try to figure something out, so that the hidden benchmarks can be listed, too.

**Comment by jch9678** [comment]
So I think swapminer might be causing my system crashes when your dev fee mining kicks in. My systems are not crashing actually but the machines are restarting because of low resources.  I watched one of my machines reboot cleanly suddenly, i.e. it said you are being signed out in one minute.  I say reboot because my remote session was kicked off so it could have just logged me off and then logged me back in.  I wasn't sure what happened so I went to the event viewer and this is what I found:

`Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: OclSolver.exe (1936) consumed 7394033664 bytes, OclSolver.exe (4008) consumed 7393710080 bytes, and OclSolver.exe (7260) consumed 7393456128 bytes.`

The only reason oclsolver could be running would be if your dev fee mining kicked in.  There were 2 of those entries, I assume for each of the 6 gpu's

**Comment by jch9678** [comment]
Actually there were 3 of those entries.  I remember in the early days of grin mining, grin miners would not exit cleanly and oclsolver would remain behind.  I think this may be happening.

**Comment by RainbowMiner** [comment]
Yes, that looks pretty much like that. I will exclude SwapMiner for these runs. It's too picky.

**Comment by jch9678** [comment]
I noticed in the release notes for the new update:

"allow miners to be excluded from donation run"

Does this mean I have to add swapminer to my exclusion list or has swapminer been scrapped altogether from donation mining?  

Does dev fee mining show up in the Activity log?  When this crash happened I don't think I saw anything about dev fee mining in the Activity log, which could be a problem for troubleshooting.  I had been assuming it was one of my miners causing the problem.

**Comment by RainbowMiner** [comment]
You do not have to put it on your exclusion list. During donation run it will be excluded, automatically.
Yes, dev fee mining shows up in the activity log. So, maybe, at which point did your rig crash?

**Comment by jch9678** [comment]
At least that last crash was caused by oclsolver, I'm not sure about the other ones.  I'll keep an eye on it; I've kind of re-enabled everything.  Thanks

**Comment by jch9678** [comment]
I'm thinking srbminer might be causing the crashes.  In BCT doktor talks about bugs causing it to crash and I find this in the event viewer:

`Faulting application name: srbminer-cn.exe, version: 1.8.0.0, time stamp: 0x00000000
Faulting module name: srbminer-cn.exe, version: 1.8.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000000854c6
Faulting process id: 0x11d0
Faulting application start time: 0x01d4d50dcae2c8d7
Faulting application path: C:\Users\jhjhjh\Desktop\RainbowMiner\Bin\CryptoNight-SRBMiner\srbminer-cn.exe
Faulting module path: C:\Users\jhjhjhjh\Desktop\RainbowMiner\Bin\CryptoNight-SRBMiner\srbminer-cn.exe
Report Id: ce3d2da5-4fb1-40ab-a28f-7a2142d08632
Faulting package full name: 
Faulting package-relative application ID: `

That error is followed by the driver crashing.

**Comment by RainbowMiner** [comment]
Ok, thank you for reporting back.
