### ISSUE TITLE
Blazepool Balance not updating

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#465]
My Blazepool balance has not updated for several days. Localhost:4000 reporting .0021633. Blazepool website shows .0024346.

Have not checked the other pools yet.

**Comment by RainbowMiner** [comment]
Mine are updating. So eventually the blazepool api has some problem. Could you send me your btc wallet address by email or discord DM? And eventually drop the current Debug file here. Then I can have a closer look.

**Comment by Yamanipanuchi** [comment]
I actually closed the script out completely and Re-started it and it updated.. I had this one running for quite sometime.

**Comment by Yamanipanuchi** [comment]
Issue resolved with a Re-start of the script.
