### ISSUE TITLE
Mixed AMD Cards Problems

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#469]
In one of my rigs I have 3 290x and 2 290.  RM is opening several miners at once, I'm sure it was designed that way but it's causing a lot of problems.  Miners seem to hang more often and miners run 3 instances at once, one each for 3 gpus and one for all 6.  Just very unstable with for example wildrig and srbminer running at the same time.  Would gpu groupings help this?  I would like one miner to be run and just have different settings for each card.  Any insight?  Thanks
[debug-2019-03-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/2963334/debug-2019-03-13.zip)

**Comment by RainbowMiner** [comment]
There are two approaches: 
1) set MiningMode to "legacy" in config.txt - that would group all AMD together automatically
2) edit gpugroups.config.txt and group together, whatever GPUs you want. 

both methods will create new entries in miners.config.txt - there you can edit your settings.

**Comment by jch9678** [comment]
I will set it to Legacy, thank you.
