### ISSUE TITLE
Feedback of mem clock setting -500 for profile 4

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#47]
Benchmark results after change of mem clock -500 for profile 4 as you requested in #42 
[benchmark_profile4_mem_neg500.xlsx](https://github.com/RainbowMiner/RainbowMiner/files/2335031/benchmark_profile4_mem_neg500.xlsx)

**Comment by RainbowMiner** [comment]
Super! Thank you very much! This is very interesting. You use GTX1080Ti, don't you?
So maybe, it is better to keep your settings at 0 memory overclocking for profile 4.

RBM

**Comment by ebojali** [comment]
Yes, GTX 1080Ti is the once I use. I've changed back to 0 now. cheers! Keep up teh good work!

**Comment by RainbowMiner** [comment]
Ok, I will update my recommendations.

RBM
