### ISSUE TITLE
Is lolminer included

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#470]
I get better speeds on equihash25x5 with lolminer than I do with gminer.  I thought lolminer used be included but didn't see it in my stats or on the bin folder

**Comment by RainbowMiner** [comment]
It is included and should run on AMD cards with >= 4GB memory. Do you have any restrictions in place?

**Comment by jch9678** [comment]
None that I can think of. I added RM to a 390 machine and it didn't
download, and added it to 290x machines and it didn't download. The dev
does weird things on his GitHub, maybe that's why....?

**Comment by jch9678** [comment]
I just updated a 290 machine and lolminer did not download. I can see the ps1 in the miners folder...

**Comment by RainbowMiner** [comment]
The WildrigPreview is for Rainforest mining, only. I'll check, why the lolminer does not download. For which algorithm do you intend to use it?

**Comment by RainbowMiner** [comment]
Equihash25x5, I see.

**Comment by RainbowMiner** [comment]
I have just double checked on one of my rigs: lolminer is downloading into .\Bin\Equihash-lolMiner, up and running. I have lowered the memory requirements a bit (to 3.5GB), so please retry with https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Miners/lolminer.ps1 (right-click + save as.. into the Miners folder).
Also, just to be sure, have a look in the directory "MinersOldVersions" - if there is a file "lolminer.ps1", delete it. Any file in this folder will block new miners with the same name in folder Miners

**Comment by jch9678** [comment]
Will do.  I think I remember something that W10 reserves some video memory therefore I wouldn't be meeting the 4gb cutoff.  W7 does not do this.  Updating RM on a 390 looks like it confirms this, they have 8gb and lolminer is updating.

By the way when I manually update RM, a cmd window pops up for a split second and all I can see is that it says access denied 2 times before it disappears.  What is that?

**Comment by jch9678** [comment]
I still could not get it to benchmark on a hawaii machine, maybe I'm making a stupid mistake.  Here's my debug file
[debug-2019-03-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/2971733/debug-2019-03-15.zip)

**Comment by RainbowMiner** [comment]
Here you are:
https://rbminer.net/algorithms/
