### ISSUE TITLE
Error on none mining system.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#472]
I get this error on the machine I use to monitor with. 

        \/      \/        \/    \/                     \/        \/     \/

Starting up v3.9.9.8! Please wait..

Transcript started, output file is .\Logs\RainbowMiner_2019-03-15_07-48-25.txt
Detecting devices ..
Initialize configuration ..
Resolve-Path : Cannot find path 'C:\RainbowMiner\Config\gpugroups.config.txt' because it does not exist.
At C:\RainbowMiner\Core.psm1:100 char:95
+ ... ath = $Session.ConfigFiles["GpuGroups"].Path | Resolve-Path -Relative
+                                                    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\RainbowMiner...oups.config.txt:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

Read configuration ..

**Comment by RainbowMiner** [comment]
Ah! Yes, I forgot about that gpugroups file. Thank you!

**Comment by RainbowMiner** [comment]
Ok, I fixed this in v3.9.9.9
