### ISSUE TITLE
Rig set to Nvidia only but only on Miningrigrentals when using YescryptR32 also use CPU?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#473]
Rig set to Nvidia only but only on Miningrigrentals when using YescryptR32 also use CPU?

**Comment by RainbowMiner** [comment]
Two steps:
1) add "CpuminerOptBF" to all pool's "ExcludeMinerName" field in pools.config.txt - of course only for those pools that offer YescryptR32, except for MiningRigRentals
2) add "YescryptR32" as the only algorithm into field "Algorithm" of "CPU" section in file devices.config.txt - plus eventually give it an own worker name (I have put in xcpu as example, see note below). 
```
  "CPU": {
    "Algorithm": "YescryptR32",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "DefaultOCprofile": "",
    "PowerAdjust": "100",
    "Worker": "xcpu"
  },
```

Now you can decide at runtime, and case-by-case, if you want to the CPU be added to or removed from a MMR rental. Just add `[xcpu]` (your CPU's own worker name) to the rig's description to activate the CPU for the current rental (or in general). If you want to add the CPU in general for all YescryptR32 MRR rentals, just do not give your CPU an own worker name.

**Comment by paulpoco** [comment]
Maybe I don't understand.

I don't want any CPU unless it is on MMR and YescryptR32.

**Comment by RainbowMiner** [comment]
If it's constant, than you may make it a little easier:

Two steps:
1) add "CpuminerOptBF" to all pool's "ExcludeMinerName" fields in pools.config.txt - of course only for those pools that offer YescryptR32, except for MiningRigRentals
2) add "YescryptR32" as the only algorithm into field "Algorithm" of "CPU" section in file devices.config.txt
```
  "CPU": {
    "Algorithm": "YescryptR32",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "DefaultOCprofile": "",
    "PowerAdjust": "100",
    "Worker": ""
  },
```

That will do the thing. Now, CpuminerOpt will be activated, if MRR kicks in with YescryptR32

**Comment by paulpoco** [comment]
@RainbowMiner it was working with your instructions.  I updated to RainbowMiner v4.0.0.0 and now on NLpool it is mining on the CPU YescryptR32.

Ok while writing this, it went thru a loop and now not using CPU.

Weird? It was Benchmarking other stuff on GPUs and when Benchmarking done, it stopped using CPU.

  "NLpool": {
    "Worker": "$WorkerName",
    "Penalty": 0.0,
    "User": "$UserName",
    "API_ID": "$API_ID",
    "API_Key": "$API_Key",
    "DataWindow": "estimate_current",
    "LTC": "$LTC",
    "Algorithm": "",
	"ExcludeMinerName": "CpuminerOptBF",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "StatAverage": ""
  },
  "NLpoolCoins": {
    "LTC": "$LTC",
    "Worker": "$WorkerName",
    "Penalty": 0,
    "Algorithm": "",
	"ExcludeMinerName": "CpuminerOptBF",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "DataWindow": "",
    "StatAverage": ""
  },

Weird again my paste has the new line with "ExcludeMinerName": "CpuminerOptBF", with extra spaces I don't see in the file.  Ok I'll fix that

[debug-2019-03-19.zip](https://github.com/RainbowMiner/RainbowMiner/files/2985920/debug-2019-03-19.zip)

**Comment by RainbowMiner** [comment]
Interesting :) I'll have a look why it's CPU mining during benchmarks.

**Comment by paulpoco** [comment]
Working just fine now.   And yes I had tabs on all the "ExcludeMinerName": "CpuminerOptBF" line, took those out.

I found Mining on CPU isn't worth the power usage.  Rather lower my total Wattage.  I save 50 to 70 watts.

**Comment by paulpoco** [comment]
@RainbowMiner I just one time where the Crypto address showed up as CpuminerOptBF
![image](https://user-images.githubusercontent.com/801414/54649940-71a26380-4a69-11e9-95dc-ff6a060b4900.png)
[debug-2019-03-19 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/2985990/debug-2019-03-19.1.zip)

**Comment by RainbowMiner** [comment]
This indicates, that the ExcludeMinerName field in the configuration for Zergpool has been misspelled. Eventually there has been a space or tabspace.

**Comment by RainbowMiner** [comment]
Fixed.
