### ISSUE TITLE
Cuckaroo29 is not listed

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#474]
I was using Cuckaroo29 (for GRIN) but now I can't find it anywhere. In the Algorithm column on Miners list, is not available. Likewise I can't find grinprominer in the list, nor in the http://localhost:4000/miners.
[debug-2019-03-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/2979451/debug-2019-03-18.zip)

**Comment by RainbowMiner** [comment]
Did you have a look at the benchmarks? Maybe the benchmarks failed?

**Comment by Djago** [comment]
It's not listed anywhere. Not on Miners, not on Active Miners, not on Benchmarks.
But I have mined with RM several days with GrinProMine (exactly 0,46904247 GRIN mined).

**Comment by RainbowMiner** [comment]
Is Grinmint available on the allpools list?

**Comment by Djago** [comment]
![image](https://user-images.githubusercontent.com/34612740/54600400-72aca400-4a1b-11e9-92b5-09d392d80e90.png)

**Comment by RainbowMiner** [comment]
Good. What does http://localhost:4000/devices show?

**Comment by Djago** [comment]
[
  {
    "Index": 0,
    "PlatformId": 0,
    "PlatformId_Index": 0,
    "Type_PlatformId_Index": 0,
    "Vendor": "AMD",
    "Vendor_Name": "Advanced Micro Devices, Inc.",
    "Vendor_Index": 0,
    "Type_Vendor_Index": 0,
    "Type": "Gpu",
    "Type_Index": 0,
    "Type_Mineable_Index": 0,
    "OpenCL": {
      "AddressBits": 64,
      "Available": true,
      "CompilerAvailable": true,
      "DoubleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma",
      "EndianLittle": true,
      "ErrorCorrectionSupport": false,
      "ExecCapabilities": "ExecKernel",
      "Extensions": "cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash cl_amd_planar_yuv",
      "GlobalMemCacheSize": 16384,
      "GlobalMemCacheType": 2,
      "GlobalMemCachelineSize": 64,
      "GlobalMemSize": 8573157376,
      "ImageSupport": true,
      "LocalMemSize": 32768,
      "LocalMemType": 1,
      "MaxClockFrequency": 1590,
      "MaxComputeUnits": 56,
      "MaxConstantArgs": 8,
      "MaxConstantBufferSize": null,
      "MaxMemAllocSize": 4244635648,
      "MaxParameterSize": 1024,
      "MaxReadImageArgs": 128,
      "MaxSamplers": 16,
      "MaxWorkGroupSize": 1024,
      "MaxWorkItemDimensions": 3,
      "MaxWorkItemSizes": "1024 1024 1024",
      "MaxWriteImageArgs": 64,
      "MemBaseAddrAlign": 2048,
      "MinDataTypeAlignSize": 128,
      "Name": "gfx900",
      "ClVersion": "OpenCL C 2.0 ",
      "Platform": "@{Profile=FULL_PROFILE; Version=OpenCL 2.1 AMD-APP (2766.5); Name=AMD Accelerated Parallel Processing; Vendor=Advanced Micro Devices, Inc.; Extensions=cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices }",
      "PreferredVectorWidthChar": 4,
      "PreferredVectorWidthShort": 2,
      "PreferredVectorWidthInt": 1,
      "PreferredVectorWidthLong": 1,
      "PreferredVectorWidthFloat": 1,
      "PreferredVectorWidthDouble": 1,
      "Profile": "FULL_PROFILE",
      "QueueProperties": "ProfilingEnable",
      "SingleFpConfig": "FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "VendorId": 4098,
      "Version": "OpenCL 2.0 AMD-APP (2766.5)",
      "DriverVersion": "2766.5 (PAL,HSAIL)"
    },
    "Model": "Vega56",
    "Model_Name": "Radeon Vega 56",
    "InstanceId": "PCI_VEN_1002&DEV_687F&SUBSYS_0B361002&REV_C3_6&198E012F&0&0000001AA",
    "Name": "GPU#00",
    "Data": {
      "AdapterId": "0",
      "FanSpeed": 60,
      "Clock": 1272,
      "ClockMem": 950,
      "Utilization": 93,
      "Temperature": 67,
      "PowerLimitPercent": 78,
      "PowerDraw": 152.33400000000003,
      "Method": "tdp"
    }
  },
  {
    "Index": 1,
    "Vendor": "AUTHENTICAMD",
    "Vendor_Name": "AuthenticAMD",
    "Type_PlatformId_Index": 0,
    "Type_Vendor_Index": 0,
    "Type": "Cpu",
    "Type_Index": 0,
    "Type_Mineable_Index": 0,
    "CIM": {
      "CimClass": "@{CimSuperClassName=CIM_Processor; CimSuperClass=ROOT/cimv2:CIM_Processor; CimClassProperties=Caption Description InstallDate Name Status Availability ConfigManagerErrorCode ConfigManagerUserConfig CreationClassName DeviceID ErrorCleared ErrorDescription LastErrorCode PNPDeviceID PowerManagementCapabilities PowerManagementSupported StatusInfo SystemCreationClassName SystemName AddressWidth CurrentClockSpeed DataWidth Family LoadPercentage MaxClockSpeed OtherFamilyDescription Role Stepping UniqueId UpgradeMethod Architecture AssetTag Characteristics CpuStatus CurrentVoltage ExtClock L2CacheSize L2CacheSpeed L3CacheSize L3CacheSpeed Level Manufacturer NumberOfCores NumberOfEnabledCore NumberOfLogicalProcessors PartNumber ProcessorId ProcessorType Revision SecondLevelAddressTranslationExtensions SerialNumber SocketDesignation ThreadCount Version VirtualizationFirmwareEnabled VMMonitorModeExtensions VoltageCaps; CimClassQualifiers=Locale = 1033 UUID = \"{8502C4BB-5FBB-11D2-AAC1-006008C78BC7}\" dynamic = True provider = \"CIMWin32\"; CimClassMethods=SetPowerState Reset; CimSystemProperties=Microsoft.Management.Infrastructure.CimSystemProperties}",
      "CimInstanceProperties": "Caption = \"AMD64 Family 23 Model 1 Stepping 1\" Description = \"AMD64 Family 23 Model 1 Stepping 1\" InstallDate Name = \"AMD Ryzen 7 1700 Eight-Core Processor  ... Status = \"OK\" Availability = 3 ConfigManagerErrorCode ConfigManagerUserConfig CreationClassName = \"Win32_Processor\" DeviceID = \"CPU0\" ErrorCleared ErrorDescription LastErrorCode PNPDeviceID PowerManagementCapabilities PowerManagementSupported = False StatusInfo = 3 SystemCreationClassName = \"Win32_ComputerSystem\" SystemName = \"GO\" AddressWidth = 64 CurrentClockSpeed = 3200 DataWidth = 64 Family = 107 LoadPercentage = 32 MaxClockSpeed = 3200 OtherFamilyDescription Role = \"CPU\" Stepping = \"1\" UniqueId UpgradeMethod = 49 Architecture = 9 AssetTag = \"Unknown\" Characteristics = 252 CpuStatus = 1 CurrentVoltage = 12 ExtClock = 100 L2CacheSize = 4096 L2CacheSpeed L3CacheSize = 16384 L3CacheSpeed = 0 Level = 23 Manufacturer = \"AuthenticAMD\" NumberOfCores = 8 NumberOfEnabledCore = 8 NumberOfLogicalProcessors = 16 PartNumber = \"Unknown\" ProcessorId = \"178BFBFF00800F11\" ProcessorType = 3 Revision = 257 SecondLevelAddressTranslationExtensions = True SerialNumber = \"Unknown\" SocketDesignation = \"AM4\" ThreadCount = 16 Version = \"Modelo 1, nivel 1\" VirtualizationFirmwareEnabled = True VMMonitorModeExtensions = True VoltageCaps",
      "CimSystemProperties": "@{Namespace=root/cimv2; ServerName=GO; ClassName=Win32_Processor; Path=}",
      "Caption": "AMD64 Family 23 Model 1 Stepping 1",
      "Description": "AMD64 Family 23 Model 1 Stepping 1",
      "InstallDate": null,
      "Name": "AMD Ryzen 7 1700 Eight-Core Processor          ",
      "Status": "OK",
      "Availability": 3,
      "ConfigManagerErrorCode": null,
      "ConfigManagerUserConfig": null,
      "CreationClassName": "Win32_Processor",
      "DeviceID": "CPU0",
      "ErrorCleared": null,
      "ErrorDescription": null,
      "LastErrorCode": null,
      "PNPDeviceID": null,
      "PowerManagementCapabilities": null,
      "PowerManagementSupported": false,
      "StatusInfo": 3,
      "SystemCreationClassName": "Win32_ComputerSystem",
      "SystemName": "GO",
      "AddressWidth": 64,
      "CurrentClockSpeed": 3200,
      "DataWidth": 64,
      "Family": 107,
      "LoadPercentage": 32,
      "MaxClockSpeed": 3200,
      "OtherFamilyDescription": null,
      "Role": "CPU",
      "Stepping": "1",
      "UniqueId": null,
      "UpgradeMethod": 49,
      "Architecture": 9,
      "AssetTag": "Unknown",
      "Characteristics": 252,
      "CpuStatus": 1,
      "CurrentVoltage": 12,
      "ExtClock": 100,
      "L2CacheSize": 4096,
      "L2CacheSpeed": null,
      "L3CacheSize": 16384,
      "L3CacheSpeed": 0,
      "Level": 23,
      "Manufacturer": "AuthenticAMD",
      "NumberOfCores": 8,
      "NumberOfEnabledCore": 8,
      "NumberOfLogicalProcessors": 16,
      "PartNumber": "Unknown",
      "ProcessorId": "178BFBFF00800F11",
      "ProcessorType": 3,
      "Revision": 257,
      "SecondLevelAddressTranslationExtensions": true,
      "SerialNumber": "Unknown",
      "SocketDesignation": "AM4",
      "ThreadCount": 16,
      "Version": "Modelo 1, nivel 1",
      "VirtualizationFirmwareEnabled": true,
      "VMMonitorModeExtensions": true,
      "VoltageCaps": null,
      "PSComputerName": null
    },
    "Model": "CPU",
    "Model_Name": "AMD Ryzen 7 1700 Eight-Core Processor          ",
    "Name": "CPU#00",
    "Data": {
      "Cores": 8,
      "Threads": 16,
      "CacheL3": 16,
      "Clock": 3200,
      "Utilization": 100,
      "PowerDraw": 65,
      "Temperature": 0,
      "Method": "tdp"
    }
  }
]

**Comment by RainbowMiner** [comment]
Oh! Now I see - the memory requirements are the problem.
8GB are 8589934592 Bytes but the cards report 8573157376 Bytes which is slightly lower.
I will update the miner modules, so that you will be able to mine again.

**Comment by RainbowMiner** [comment]
Ok, done. If you want to try this out, download the current master.zip https://github.com/RainbowMiner/RainbowMiner/archive/master.zip

.. or wait for the next release.

**Comment by Djago** [comment]
Perfect! Not only GrinProMiner appeared, but also gminer! (never used it)
