### ISSUE TITLE
gpugroup corrupted

### ISSUE THREAD

**Issue by rhadamants** [RainbowMiner/RainbowMiner#477]
PC only 3 gpu but this miner detect 6 gpus. And edit gpugroup file not fix it.
z-enemy.exe -R 1 -b 30200 -d 0,1,2,3,4,5 -a x16r

**Comment by RainbowMiner** [comment]
Very weird! Would you please send me the current Debug file, if possible? 
If this is not possible, please send me a zip of .\Logs folder plus a zip of .\Configs folder.

**Comment by rhadamants** [comment]
[https://drive.google.com/open?id=1y-wCYIngoGS9S2L9xr47y3BGMu-MGyTM](url)

**Comment by RainbowMiner** [comment]
I have no access to your google drive. You should recieve a google email with a request.

**Comment by rhadamants** [comment]
[https://drive.google.com/file/d/1y-wCYIngoGS9S2L9xr47y3BGMu-MGyTM/view?usp=sharing](url)

**Comment by RainbowMiner** [comment]
Is this the Logs folder of the rig you have been addressing? It looks like it's mining on one GTX1080 GPU, only. If you resend, please add the Config folder, too.

**Comment by rhadamants** [comment]
[](http://www.mediafire.com/file/rw35q3j9d8j399w/Logs.7z/file)

**Comment by rhadamants** [comment]
[http://www.mediafire.com/file/rw35q3j9d8j399w/Logs.7z/file](url)

**Comment by rhadamants** [comment]
[http://www.mediafire.com/file/8t4yfbptbyg2c2y/Config.7z](url)

**Comment by rhadamants** [comment]
Name   Thread  Clock   CacheL3 Method Load Power Cores Threads PowerTotal Features                                            CPU Name                               
----   ------  -----   ------- ------ ---- ----- ----- ------- ---------- --------                                            --------                               
CPU#00   0    2.904GHz   2GB    tdp   17%   5W     2      2       20W     64bit,aes,mmx,sse,sse2,sse3,sse41,sse42,ssse3,vt,xd Intel(R) Celeron(R) CPU G3930 @ 2.90GHz
CPU#01   1    2.904GHz   2GB    tdp   52%   15W    2      2       20W     64bit,aes,mmx,sse,sse2,sse3,sse41,sse42,ssse3,vt,xd Intel(R) Celeron(R) CPU G3930 @ 2.90GHz



Name   Vendor Model   Driver  CL/CUDA Mem PS Gpu Clock Mem Clock Temp Fan% Gpu% Mem% PLim% Power
----   ------ -----   ------  ------- --- -- --------- --------- ---- ---- ---- ---- ----- -----
GPU#00 NVIDIA GTX1070 419.35 10.1.120 8GB P2  1.733GHz  3.802GHz 67øC  39%  99%  17%  100%  129W
GPU#01 NVIDIA GTX1070 419.35 10.1.120 8GB P2  1.771GHz  3.802GHz 72øC  58%  99%  18%  100%  136W
GPU#02 NVIDIA GTX1070 419.35 10.1.120 8GB P2   1.86GHz  3.802GHz 74øC  64% 100%  18%  100%  108W
GPU#03 NVIDIA GTX1070 419.35 10.1.120 8GB  -         -         -    -    -    -    -     -     -
GPU#04 NVIDIA GTX1070 419.35 10.1.120 8GB  -         -         -    -    -    -    -     -     -
GPU#05 NVIDIA GTX1070 419.35 10.1.120 8GB  -         -         -    -    -    -    -     -     -

See. Log from Listdevices.bat

**Comment by RainbowMiner** [comment]
I am currently at a conference until monday. After that, I will get back to this. Thank you for your patience!

**Comment by RainbowMiner** [comment]
Ok, that is *really* weird. 
Would please drop the full gpuresults.txt here?

- First - look into your "Config" folder. There seems to be a copy inside itself (a folder Config\Config). Delete the second layer Config folder. Even though I could not imagine that this would cause double devices, but one never know.
- Second - try to remove all Nvidia drivers using DDU (https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)
- Third - install the newest Nvidia drivers.
