### ISSUE TITLE
Issue: CpuminerOptBF placed as wallet address in CryptoDredge-NeoScrypt

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#478]
@RainbowMiner I just had one time where the Crypto address showed up as CpuminerOptBF
![image](https://user-images.githubusercontent.com/801414/54649940-71a26380-4a69-11e9-95dc-ff6a060b4900.png)
[debug-2019-03-19 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/2985990/debug-2019-03-19.1.zip)

And it mines on CpuminerOptBF as the wallet address for CryptoDredge-NeoScrypt but not every time.

**Comment by RainbowMiner** [comment]
This is fixed with the current master.zip
