### ISSUE TITLE
How to mine SWP?

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#480]
Hi

I want to benchmark and try SWP but it's not automatically used by RM. What is the correct procedure to do that? I've peeked at pools.config.txt and saw FairPool, Herominers, LuckyPool & CryptoKnight with the folowwing structure:

>    "XWP": "",
    "Worker": "$WorkerName",
    "Penalty": 0,
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "DataWindow": "",
    "StatAverage": ""

Should I add my email to XWP? What about the other fields?

**Comment by RainbowMiner** [comment]
Mining XWP/Swap (https://swap.fyi) with Cuckaroo29s
  - enter your XWP wallet address into "XWP" field
  - add the poolname(s) to field "PoolName" inside to your config.txt, also make sure these pool(s) are not on the "ExcludePoolName" list (to make things easy, you may just want to clear the ExcludePoolName field `"ExcludePoolName": "",`)
  - add Cuckaroo29s to the "Algorithm" field in config.txt (or clear the Algorithm field to have all algos avail `"Algorithm": "",`)

**Comment by Djago** [comment]
Nice! Now I can mine swap!
Also, I don't know why but both ExcludePoolName & Algorithm were filled. I've cleaned them and RM benchmarked 14 miners!

Thx!
