### ISSUE TITLE
luckypool not showed on balances

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#481]
Hi!
I started mining swap with RM yesterday. I've mined some XWP and I can see them on swap2.luckypool.io, but RM doesn't list them on the pool balances.
Do I have to wait for something? Or configure something?

**Comment by Djago** [comment]
This is my SWAP address:
fh44tMHfx7TfyM2fdQ4sZZjYKGDDrchWnYXqbJ6jWfDme3a421Wy1gJXNPyU5j1kHuYtsYPWSvw4wBEZ7NVsSCv21Ddxnw1kV

**Comment by RainbowMiner** [comment]
There hasn't been a LuckyPool balance module, yet. It's now implemented.
