### ISSUE TITLE
rainbow miner seems to stall and indicates that it is "finished waiting, starting next run". but checking the remote monitor i find that it is offline for 53 minutes. also looks like afterburner is still keeping the video cards at a high rate and not shutting down.

### ISSUE THREAD

**Issue by henry18341834** [RainbowMiner/RainbowMiner#483]

**Comment by RainbowMiner** [comment]
Would you please drop the current Debug file? I will have a look. Is this an AMD or a Nvidia rig?

**Comment by RainbowMiner** [comment]
Also, are you CPU mining, too? If yes, which CPU is it?

**Comment by henry18341834** [comment]
i hope this is the debug file you want. also as i was doing this i just double clicked the reset nividia driver file and the system restarted. tried this 2 times and both times rainbow miner started mining again. 
i am NOT running CPU but the CPU is mostly at 100%. this is also just a nividia rig.

![IMG_6110](https://user-images.githubusercontent.com/10469825/55275757-41589180-52c1-11e9-8f40-c5e34f5c00c1.jpg)
[testresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/3025417/testresult.txt)
[errors_2019-03-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/3025418/errors_2019-03-29.zip)

**Comment by RainbowMiner** [comment]
First: it looks like you have a problem with Windows 10, that is not related to RainbowMiner.
Try this fix: https://www.kapilarya.com/fix-service-host-diagnostic-policy-service-high-cpu-usage-in-windows-10

Then: the Debug file can be found at http://localhost:4000 (<- open this, using your mining rig's web-browser, just click it), then you will find "Debug file" on the left hand side. If you click this, RainbowMiner will create a debug zip file (all sensitive data will be x-ed out)

**Comment by henry18341834** [comment]
[debug_2019-03-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/3025662/debug_2019-03-30.zip)
I was watching rainbow miner start up and saw that the CPU% was low during start up but after the first run the CPU% went to 100% and then stayed there. the file running was the same as shown before. the diagnostic service policy. this is still after I checked and fixed the computer system. I do not show any files that are bad now. thanks for that.

**Comment by RainbowMiner** [comment]
I have checked the debug file - all looks normal, except the fact, that it takes a long time to download the pool data.
```
2019-03-29 05:34:21 [388.52 339.67] INFO: Loading pool information. 
2019-03-29 05:38:14 [388.60 339.57] INFO: Updating pool balances. 
```
.. it's around 4 minutes and far off. It should be around 5 to 15 seconds. Normally this happens, if the CPU hovers around it's maximum, so that there is not enough calculating power left over for RainbowMiner.

Please check the following things:
- did you start the Start.bat with admin privileges?
- did you set the Windows swapfile to a static value (minimum = maximum) with at least 44GB size?
- are any other processes running that could trigger that diagnostic policy service?

**Comment by RainbowMiner** [comment]
Also, you could try the following:
Download FixDPS.bat from here (right-click / save-as..) https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/FixDPS.bat

Now run this with admin privileges (right-click / run as admin)
This batch restarts the Diagnostic Policy Service and removes window's sru folder. It will not be created again, after that.
It's taken out of the answers (scroll down and click "Answers") on the following page: https://answers.microsoft.com/en-us/windows/forum/all/service-host-diagnostic-policy-service-high-cpu/37439fed-a9ef-4221-a9b3-3ab88053d512 (last answers)

**Comment by henry18341834** [comment]
did everything you said. i am running an ssd drive. the only other items running are awesome miner for my machines and afterburner. i turned each item off and only had rainbow running along with the diagnostic policy service and the CPU was running 99 to 100%. if i turn the policy off then CPU drops to 45 to 90%. then i turned all the other items back on and no change. only when rainbow miner is on the CPU goes to 100%. weird..............

**Comment by henry18341834** [comment]
forgot, looks like with the CPU down below 90% rainbow runs better at reloading.

**Comment by RainbowMiner** [comment]
I'll close the issue, for now. If you get into this trouble again, please reopen at will.
