### ISSUE TITLE
f2pool not showed on balances

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#485]
HI!

I configured f2pool to mine BEAM and mine some coins, but in the balance f2pool is not appearing.

Regards,
FSO

**Comment by RainbowMiner** [comment]
Please send me your BEAM address, so that I can check.

**Comment by Djago** [comment]
This is what RM shows
![image](https://user-images.githubusercontent.com/34612740/55366655-0b353080-54c0-11e9-9e7d-c8e84dd097e3.png)
This is my BEAM address:
242a8928a31b36c5642441a6c71899f0a5e41e186e59db34f69bf8a0d97da272ae2

**Comment by RainbowMiner** [comment]
Oh :blush: I just found out, that I haven't programmed the F2pool balances module, yet. It will be there asap.

**Comment by Djago** [comment]
Hi
Updated to 4.0.0.7. Filled username but still f2pool is not appearing. Do I need to put my username or my email?
