### ISSUE TITLE
Enhancement: Hard drive mining

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#486]
There is a new thing that we should jump on board with. Hard drive mining is now going to be easier. I'm already gearing up now for this wave. You may want to look into getting a jump on an auto switching hard drive mining software. I would be very interested.

**Comment by RainbowMiner** [comment]
Very nice :) So, are there already some currencies that you would recommend?

**Comment by Byrd1083** [comment]
Currently the bigger 3 is "burstcoin" "filecoin" and "storj" I'm just getting into this so I don't know much of the details yet.

**Comment by Byrd1083** [comment]
Also, I quit mining on blockmasters and switched to nlpool. Much better and stable profits now.

**Comment by Byrd1083** [comment]
Siacoin is another one for HDD mining.

**Comment by paulpoco** [comment]
Already doing Burstcoin using Rainbowminer with the execute command at start option.

**Comment by Byrd1083** [comment]
Oh really could you brief me in on how to Setup real quick? I would like to give it a shot.
