### ISSUE TITLE
Please review latest Miniz group usage

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#487]
at appears that one miner window of miniz is able to handle the 4 cards, 3 different groups, but is not detecting as such and it tries to open another window with one of the cards already been use and that is crashing

![image](https://user-images.githubusercontent.com/41829368/55632935-93455f80-5778-11e9-81c6-f8e2c0f7cc78.png)

![image](https://user-images.githubusercontent.com/41829368/55632968-a6582f80-5778-11e9-9bbf-e58ab5ba20cb.png)

**Comment by mo35** [comment]
same problem , i was wondering how 24x5 become so profitable suddenly

**Comment by RainbowMiner** [comment]
Woa, that would be bad - could you please send me a zip of the Logs folder? I would like to see what is going on with MiniZ and selecting devices.

**Comment by mo35** [comment]
unfortunately i cleaned up everything , and excluded miniz from mixed rigs , but what i can tell you is that on launch there was list of gpus with (1) or (0) after model name , my guess thats enabled or disabled flag.
Miniz even tho it was showing correct flags was trying to run all gpus in each miner session , ignoring flags for enabled/disabled gpus.

**Comment by hernandn01** [comment]
Here you go
[temp.zip](https://github.com/RainbowMiner/RainbowMiner/files/3050034/temp.zip)

**Comment by RainbowMiner** [comment]
Clearly, the parameters that we send to miniz are all fine, so miniz really has a problem. Better we disable it until the dev has cleaned this up.

**Comment by RainbowMiner** [comment]
I have updated the Miners\MiniZ.ps1 - until this problem is fixed, miniz will run in full combo mode, only (=only one instance for all GPU).

**Comment by RainbowMiner** [comment]
Only full combo mining enabled for MiniZ for now.
