### ISSUE TITLE
Grinpro Miner is not working for AMD

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#488]
I believe it has never downloaded for any of my machines with 8gb of memory.

**Comment by RainbowMiner** [comment]
It should have. Better you send me a current Debug file - I'll have a look.

**Comment by jch9678** [comment]
[debug_2019-04-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/3049097/debug_2019-04-05.zip)
Here is one of them.  Thanks.

**Comment by RainbowMiner** [comment]
Ok, it's due to the fact that GrinProMiner is not compatible with Nicehash - and as this is your only pool, capable of Cuckaroo29, it is not included in the list of miners.

**Comment by jch9678** [comment]
ahhhh.  Thank you very much.  I have an interesting issue with Rainforest, I'll try to get to it this weekend.
