### ISSUE TITLE
Question: what do you people use to track your crypto assets?

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#489]
Hi!

I originally mined manually choosing coins/algos, generating wallets, manually transferring, and so on. I had 4 or 6 wallets and life was _relatively_ easy,
When I began to use RM things started to get out of control: lots of coins, lots of pools, plus the ones I already had.
Currently, I have money on more than 7 pools in 9 different coins, more than 6 wallets (manually created with wallets like XMR or from FreeWallet or similar systems) so knowing how much money I have is quite hard. I tried some portfolio apps for Android and some have support for this pool or that pool, some wallets, but no others.
So the question is: how do you people manage your portfolio? Spreadsheet? A combo of apps? Do not manage it at all?

**Comment by paulpoco** [comment]
[Bitcoin.tax](url)
It is still is a manual process, I only record what a pool actually auto pays out.
