### ISSUE TITLE
Microsoft Visual C++ Repair Keeps opening on start

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#49]
Hey there, I'm a new user coming from Multipoolminer. I'm sick of them having a lack of support. I am going to give your software a shot. I currently run 4 rigs. 3 of them are 1070 and 1 test rig with one 1080 ti 11gb. I am setting up and benchmarking with latest version. Every time I start.bat, The Microsoft Visual C++ Repair/modify prompt keeps opening automatically. I have already repaird it and it was successful without errors. However, when closed and restarted, The same C++ repair window keeps opening.

**Comment by RainbowMiner** [comment]
Would you please show me a screenshot of the repair-error? Eventually you should try to completely deinstall/clean install of Microsoft Visual C++

RBM

**Comment by Byrd1083** [comment]
So, I've rebooted the system and it does not seem to be an issue anymore. May want to recommend a reboot scrypt for initial install since it runs install scrypts from shell automatically.
