### ISSUE TITLE
CryptoDredge starts GPU[1] first and then 30 seconds later starts GPU[0], is that normal?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#490]
CryptoDredge starts GPU[1] first and then 30 seconds later starts GPU[0], is that normal?
[debug_2019-04-07.zip](https://github.com/RainbowMiner/RainbowMiner/files/3052122/debug_2019-04-07.zip)
![Screenshot_3](https://user-images.githubusercontent.com/801414/55690986-5088b080-594d-11e9-96ce-d7871a580cdb.png)

**Comment by RainbowMiner** [comment]
Eventually, yes. Could you also drop the CryptoDredge logfile .\Bin\NVIDIA-CryptoDredge\log_31300.txt ? This is the miner's own logfile. Perhaps we get a clue when looking into this.

**Comment by petrovsky34** [comment]
I also had a current gpu 7 there was a problem
