### ISSUE TITLE
Could not set process priority/affinity: .....  Access is denied

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#491]
"Could not set process priority/affinity: .....  Access is denied"

I cleaned up my system removing drivers and reinstalling.  

Do I need the AMD CPU driver is that what it talking about?

![Screenshot_2](https://user-images.githubusercontent.com/801414/55690996-744bf680-594d-11e9-920a-153f5cc60a7c.png)

**Comment by paulpoco** [comment]
I thought it was the AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64 but didn't fix it.

**Comment by paulpoco** [comment]
Ok figured what it was.

I ran the Burstcoin Qbundle GUI to delete and plot and make the file smaller.

So somewhere this Qbundle updated the name of the miner from "C:\Qbundle\BlagoMiner\Blagominer_avx2.exe" to "C:\Qbundle\BlagoMiner\Blagominer_avx.exe".

@RainbowMiner so when RBM doesn't find the file to autoexec, then maybe a different message such as "Autoexec exe do not exist".

**Comment by RainbowMiner** [comment]
Yes, this message was really unclear. I will change it.

**Comment by RainbowMiner** [comment]
I have added more meaningful messages to RainbowMiner, regarding missing commands in autoexec.txt
