### ISSUE TITLE
During config allow blank

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#493]
Several times when I go to change settings in the config I want to select the default which pulls in what you already had, But unfortunately there happen to be something in the old existing config that was no longer acceptable or no available anymore. Like the allowed/excluded algo selection. If one gets removed but was previously selected it will bounce back at you saying it is not allowed. You then need to manually selects all algo's but that one. This also happens with Exclude miner, if you do not have one to exclude it wont let you past unless you pick one. Lucky I've found Excavator never works (It just gets stuck in a loop) so I always select this one.

A choice to enter something like "." for blank to accept the defaults would be great. Or some similar mechanic like that.

**Comment by RainbowMiner** [comment]
Oh! Ok, I'll check the setup step-by-step to allow empty strings, as well.

**Comment by RainbowMiner** [comment]
There are some handy commands available at the input prompts, that might do the job already:

`+sometext` = adds "sometext" to a list
`-sometext` = removes "sometext" from a list
`clear` = deletes the complete list
