### ISSUE TITLE
Windows 7 does not download miners

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#495]

**Comment by petrovsky34** [comment]
[RainbowMiner_2019-04-12.txt](https://github.com/RainbowMiner/RainbowMiner/files/3073124/RainbowMiner_2019-04-12.txt)

**Comment by RainbowMiner** [comment]
Have you found a solution for Windows 7 ? Was is that missing DLL?

**Comment by petrovsky34** [comment]
windows 8.1

**Comment by RainbowMiner** [comment]
Ah, cool :) Thank you for the reply!
