### ISSUE TITLE
CryptoDredge cuda cuda 9.1 error

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#497]

**Comment by petrovsky34** [comment]
![Сни1111мок](https://user-images.githubusercontent.com/39003568/56100053-ac42d300-5f25-11e9-9cb8-90af404f48fb.PNG)

**Comment by petrovsky34** [comment]
nvidia 391.35 best speed gtx 1000 series 10%-23%

**Comment by RainbowMiner** [comment]
Thank you very much! It's fixed.

**Comment by petrovsky34** [comment]
[PSCustomObject]@{MainAlgorithm = "cuckaroo29"; MinMemGb =(((((((4)))))); Params = ""; ExtendInterval = 2} #Cuckaroo29 / GRIN
Cuckaroo29 CryptoDredge min 4gb worker windows 7/8.1 add

**Comment by RainbowMiner** [comment]
Solved and Win10 detection added.
