### ISSUE TITLE
cuckaroo29 MinMemGb = 4gb aded (gminer cryptodrege) worker windows 8.1

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#498]

**Comment by petrovsky34** [comment]
Cuckaroo29 CryptoDredge min 4gb worker windows 7/8.1

**Comment by RainbowMiner** [comment]
Yes, thank you very much! I have added a win10 check, now.

**Comment by petrovsky34** [comment]
![2342342](https://user-images.githubusercontent.com/39003568/56136623-37fb4480-5fa4-11e9-97a5-678ad7315b8b.PNG)

**Comment by petrovsky34** [comment]
4gb add worker windows 7/8!!!!!!!!!!!!!!!!!

**Comment by RainbowMiner** [comment]
Added
