### ISSUE TITLE
Unknown algo parameter 'hmq1725'

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#5]
CpuminerTpruvotCorei7

** cpuminer-multi 1.3.1 by tpruvot@github **
BTC donation address: 1FhDPLPpw18X4srecguG3MxJYe4a1JsZnd (tpruvot)

[2018-07-31 15:55:48][31m Unknown algo parameter 'hmq1725'[0m
Try `cpuminer-multi --help' for more information.

**Comment by RainbowMiner** [comment]
Oh yes, this is a known one. There is no hmq1725 for the CPU miners. I will upload new miner-files in a minute.

RBM

**Comment by RainbowMiner** [comment]
Ok, CPUminerTpruvot does not allow hmq1725, so I removed this algo from these miners.
See here: 1fd4579b375b0fb6681fee688c8b095c86b43c7e
