### ISSUE TITLE
Powershell start scrypt error unkown

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#50]
Some kind of scrypt error on start. Attached screenshot.  I am running powershell 6.0.
![error-1](https://user-images.githubusercontent.com/42227809/44862491-a4048480-ac2f-11e8-9d14-81af21c6f14e.jpg)
4

**Comment by RainbowMiner** [comment]
Oh, that is weird!
Would you mind installing RainbowMiner into a subdirectory of your "Downloads" ? It might be an issue with access rights.

RBM

**Comment by Byrd1083** [comment]
I have it installed into c:/ root which works better in windows 10

**Comment by Byrd1083** [comment]
I've used all my miners in that directory such as Multipoolminer, and nemosminer without issues. I even have execution policy deactivated through gpedit and exceptions made.

**Comment by Byrd1083** [comment]
I would imagine it could be an issue that I am using powershell 6.04

**Comment by Byrd1083** [comment]
seems like some kind of command line issue. I've experienced similar issues in the past with upgrading powershell 5 to 6 with nemosminer.

**Comment by RainbowMiner** [comment]
Would you please send a zip of your Config and your Logs directory? I will have a look.

**Comment by Byrd1083** [comment]
Let me finish benchmark and I'll pack it up and send. 😎🍻

**Comment by RainbowMiner** [comment]
Ok :) I will test root C:\ setup with one of my rigs. Maybe I can reproduce and fix it.

RBM

**Comment by hernandn01** [comment]
It is not advise to install directly of the c:\ folder. You end up tangle into missing elevated permissions. Create a folder of the root folder. I use C:\miner and I install everything of that. Read link for some of the reasons why.
https://superuser.com/questions/628736/why-would-i-install-a-program-into-c-directly

**Comment by Byrd1083** [comment]
No it does not tangle up permissions. Everything is fine. I restarted the system and the error is gone. Does not seem to replicate. Was throwing the error same time I first installed with the c++ error I was experiencing. Everything is normal and closing issue thanks.

**Comment by RainbowMiner** [comment]
Super :) Thank you for the feedback on this issue. Anyway, I could identify a potential bug in the downloader, due to your problem. It will be fixed in the next release.
RBM
