### ISSUE TITLE
Getting the following error quite a lot since recent Push

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#500]
Where-Object : Parameter cannot be processed because the parameter name 'not' is ambiguous. Possible matches include: -NotLike -NotMatch -NotContains -NotIn.
At C:\RainbowMiner\Include.psm1:2741 char:130
+ ...  -or ($MiningProcess -and ($MiningProcess | Where-Object -not HasExit ...
+                                                              ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Where-Object], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.WhereObjectCommand

**Comment by Yamanipanuchi** [comment]
Where-Object : Parameter cannot be processed because the parameter name 'not' is ambiguous. Possible matches include: -NotLike -NotMatch -NotContains -NotIn.
At C:\RainbowMiner\Include.psm1:2741 char:130
+ ...  -or ($MiningProcess -and ($MiningProcess | Where-Object -not HasExit ...
+                                                              ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Where-Object], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.WhereObjectCommand

Where-Object : Parameter cannot be processed because the parameter name 'not' is ambiguous. Possible matches include: -NotLike -NotMatch -NotContains -NotIn.
At C:\RainbowMiner\Include.psm1:2741 char:130
+ ...  -or ($MiningProcess -and ($MiningProcess | Where-Object -not HasExit ...
+                                                              ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Where-Object], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.WhereObjectCommand

Where-Object : Parameter cannot be processed because the parameter name 'not' is ambiguous. Possible matches include: -NotLike -NotMatch -NotContains -NotIn.
At C:\RainbowMiner\Include.psm1:2741 char:130
+ ...  -or ($MiningProcess -and ($MiningProcess | Where-Object -not HasExit ...
+                                                              ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Where-Object], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.WhereObjectCommand

Where-Object : Parameter cannot be processed because the parameter name 'not' is ambiguous. Possible matches include: -NotLike -NotMatch -NotContains -NotIn.
At C:\RainbowMiner\Include.psm1:2741 char:130
+ ...  -or ($MiningProcess -and ($MiningProcess | Where-Object -not HasExit ...
+                                                              ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Where-Object], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.WhereObjectCommand

Where-Object : Parameter cannot be processed because the parameter name 'not' is ambiguous. Possible matches include: -NotLike -NotMatch -NotContains -NotIn.
At C:\RainbowMiner\Include.psm1:2741 char:130
+ ...  -or ($MiningProcess -and ($MiningProcess | Where-Object -not HasExit ...

**Comment by RainbowMiner** [comment]
Ok. that's weird. I suspect the powershell version has something to do.

**Comment by RainbowMiner** [comment]
I'll push a new release that fixed that.
