### ISSUE TITLE
criptoknight.cc SSL connection problem

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#501]
Hi!

I'm getting:
WARNING: [2019-04-15 14:59:13] Problem fetching https://cryptoknight.cc/rpc/swap/stats using REST: The SSL connection could not be established, see inner exception.

But I'm not mining and I don't have any coins there. I've tried login to criptoknight.cc and chrome says there's a certificate issue. Can this be the problem?

**Comment by RainbowMiner** [comment]
Yes, their ssl certificate expired. It will be back up soon :)

**Comment by RainbowMiner** [comment]
CryptoKnight.cc now has a new certificate installed.
