### ISSUE TITLE
Rig amd+nvidia

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#502]

**Comment by petrovsky34** [comment]
displays only red cards and does not see green

**Comment by RainbowMiner** [comment]
It sounds like the OpenCL configuration is broken.
Eventually you have to reinstall all display drivers (remove with DDU, first). Try to install AMD first, then Nvidia. If that doesn't work out, try it the other way around.

**Comment by petrovsky34** [comment]
ok
