### ISSUE TITLE
lolminer not returning Equihash25x5 benchmark values

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#503]
subj. tested on on 1060 6g , 1070 , 1070ti cards, its same for both mixed and same card rigs.
when looking at miner windows , it actually works fine, just benchmark data is either not collected or cant be collected.

**Comment by RainbowMiner** [comment]
Thank you for reporting this. Indeed, something has changed in the lolminer API. I have fixed it.
