### ISSUE TITLE
Q:force GRIN Cuckatoo31 mining?

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#504]
Now that lolminer mines Cuckatoo31, how can I force RM to mine GRIN but Cuckatoo31 flavor?

**Comment by RainbowMiner** [comment]
If your GPU really produce some graphs and Cuckatoo31 is more profitable than Cuckaroo29, you could eventually disable Cuckaroo29 globally (config.txt, field ExcludeAlgorithm).

**Comment by Djago** [comment]
![image](https://user-images.githubusercontent.com/34612740/56428368-81de7600-6295-11e9-98a9-b9473f31ca79.png)
Yes, it appeared after the last update. I don't know why RM listed Cuckaroo29s 2nd and Cuckatoo31 3dr because as you can see is (a bit) more profitable.
But suppose I want to force RM to mine Cuckatoo31 for a couple of days, or just to try to tune afterburner. How can I force RM to do that? Use my VEGA56 to only mine Cuckatoo31?

**Comment by RainbowMiner** [comment]
Wow :) It's not working on GTX1070 - 0G/s.
One of the most elegant ways to achieve this selectivity is to edit "devices.config.txt"
If you set 
```
"Algorithm": "Cuckatoo31",
```
.. for a device(group), then it will mine Cuckatoo31, only.

Also, you may make use of the "ExcludeAlgorithm" fields. E.g. set it to 
```
"ExcludeAlgorithm": "Cuckaroo29,Cuckaroo29s,CryptonightR",
```
.. and it will not mine on Cuckaroo29, Cuckaroo29s nor CryptoknightR.

**Comment by RainbowMiner** [comment]
`I don't know why RM listed Cuckaroo29s 2nd and Cuckatoo31 3dr `
.. this is most probably caused by the pool price accuracy. It should have moved up in the charts by now :)

**Comment by Djago** [comment]
![image](https://user-images.githubusercontent.com/34612740/56437758-04c3f880-62b7-11e9-9851-e7460265d2a8.png)
It moved... but also changed the numbers and now it's making less sense.
🤣 
Thanks for the tip. You are the best, as always.
