### ISSUE TITLE
Cuckatoo31 undefined benchmark value (lolminer, gminer)

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#508]
it throws out some bench params , but not specifies whats that , just undefined

**Comment by RainbowMiner** [comment]
Most probably, the lolminer does not have a solver for your GPU. Could you send a screenshot or more details?

**Comment by mo35** [comment]
1080ti should be fine with cuckatoo
![undefined](https://user-images.githubusercontent.com/16078512/56598081-745e1e80-65fc-11e9-92e1-af4610c9143e.JPG)

**Comment by RainbowMiner** [comment]
Ah!! Now I see. It is just the missing unit. Ok, this can be fixed easilz

**Comment by RainbowMiner** [comment]
fixed
