### ISSUE TITLE
Script stops

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#509]
This has happened several times now. the script stops when mining the following..

Trex | Veil | ZergPool | GTX10603GB | 0.00008945 | 11.08 MH/s | 11.14 MH/s | 92 W
-- | -- | -- | -- | -- | -- | -- | --
CcminerMtp | MTP | NiceHash | GTX1080-GTX1080Ti | 0.01223377 | 0 H/s | 238.79 MH/s | 0 W

I am not next to the machine right now, But will get you logs when I am there.

Seems to happen whenever it is doing MTP/NiceHash.

**Comment by Yamanipanuchi** [comment]
Several of the times the system was completely locked up. This time was one of them. It only happens when MTP/NH is being mined.

Attached are the log files.
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/3109345/Logs.zip)

**Comment by RainbowMiner** [comment]
I suspect a power issue. Since MTP causes huge.power swings it may eventually crash a machine, if the total power supply has too low overhead margins.

**Comment by Yamanipanuchi** [comment]
Could be how I have it hooked up. It is a 1000w power supply but I could have the 12v shared a little to much. I will look into it.

**Comment by Yamanipanuchi** [comment]
Turns out I didn't have the power lowered on one of my 1080's.. I be that was it.
