### ISSUE TITLE
MSI Afterburner issue

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#51]
So, I have been mining stable in my 1080 ti aorus xtreme 11gb now for 3 months with ethenlargementpill, and af setting power = 65% clock = +100 mem = +750 no crashes eth 54mh/s on multipoolminer all other algos fine too. I'm setting up your new miner and am having gpu crashes and artifacts. I followed the nvinspector instructions as provided for pstate including resetting AF to stock, then after modified pstate. However, now when I run it either crashes or pushed AF millivolts way over 1000. When I manually load my profile through af while running it will crash as well which it has never done before. I am running latest nvidia drivers as well. I am more interested in undervolting. What should be done to fix?

**Comment by Byrd1083** [comment]
FYI, I reset p2stat back to enabled and I'm back to no crashs at 750mv

**Comment by RainbowMiner** [comment]
As I understand you right, you have set "Force P2 state" to "Off". In this case you need to lower your overclocking values. Try clock=+100 and mem=+500
The reason is, that in P2 state more overclocking is needed to reach the same effective GPU speed, than in P0 state.

RBM

**Comment by Byrd1083** [comment]
Additional, while letting it benchmark seems to override AF settings upon each miner switch causing me to have to manually click my oc profile in AF each time. So I go from 750mv back to over 1000mv each switch. Why is a new miner opening triggering forced stock clock rates? It seems like it is forcing a reset each time. This is not ideal at all. I should be able to load ethenlargementpill, select AF profile and open miner. I realize you wanted to incorporate an automated built in profile switch function but AF is buggy enough on 8+gpu racks. Trying to force values is only causing instability and gpu crashs constantly. Need some work on this or eliminate the function all together and allow pure manual configuration outside of rainbow for stability. If 1 gpu setup can not be stable, there is no way it will work on my 20gpu and 12gpu racks. AF will barely work as it is on them with the program lag that is created with that many gpus.

**Comment by Byrd1083** [comment]
If AF is configured correctly, it does not need to be messed with. Finding the most stable profile without switching is what is practical for every hardware setup. Especially AMD. I wouldn't even attempt to have a miner modify AMD configurations automated. I also have ran rx 580s and vega56 with bios mods and would not be stable with anything other then advancedtools and custom wattman. I think in the end you will find the customer support to be to great to manage low level configurations for programs you have no control over. Even ethpill is launching for only certain algos late into benchmarks. It would be more stable to launch ethpill before rainbow even starts to hook the gpu and do not close or have a potential logical error trying to feed the gpu while it is running or fast closing from a previous running algo/miner.

Currently all I have to do to be stable is. 

1-load af with my settings for
Gigabyte gtx 1080 ti aorus xtreme 11gb water cooled. 
power/65%, clock/+150, mem/+750.

2-load ethpill

3-start Multipoolminer or Phoenixminer and get eth avg 53.5 mh/s stable at 750~800mv = avg 160watts. Multialgo switching runs stable same settings as well.

**Comment by RainbowMiner** [comment]
Hi, RainbowMiner has a build-in switching logic for MSI Afterburner profiles, so that you can optimize.
Either you disable it (set MSIAprofile to 0 in configuration or Config\config.txt) or you setup all five profiles.
I explain, how this works in the readme: https://github.com/RainbowMiner/RainbowMiner#msi-afterburner-configuration

And, please have a look into issue #33 

RBM

**Comment by RainbowMiner** [comment]
The third solution is to edit the Config\miners.config.txt and find-and-replace all "Profile" fields with your default profile number.

**Comment by Byrd1083** [comment]
Understood. So to be clear the profile section value in config.Txt will force whatever I have saved in af profile?

**Comment by RainbowMiner** [comment]
Yes, the "MSIAprofile" value (number 1 to 5) is the default profile, which is set at startup of RainbowMiner and which is used for any miner that does not have an own "Profile" setting in miners.config.txt.

I am just working on an advanced method of OC control, that will make RainbowMiner independant from the MSIA profiles.

RBM

**Comment by Byrd1083** [comment]
[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2338168/miners.config.txt)

**Comment by Byrd1083** [comment]
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2338207/config.txt)

Here is example of my config.txt 
I am stable running with ethpill out of Rainbow standalone before miner start. 

Possible enhancement would be that I prefer interval of 60 when benchmarking. If any higher, it would take days to bench all algos. I feel it would be more productive to bench at interval 60sec to get it over with. Then implement scrypt to update hashrates as they run in basic mining operation. Thevalue y could either be compared and accepted at the higher value or even more technical, somehow average out the recorded values and store a more average accurate hash rate.

**Comment by Byrd1083** [comment]
Update: I just driver crashed with black screen and had to reboot. I noticed it was fine until another miner loaded and then it bombed. Look through the miners.config.txt again and you have -i intensity settings for many miners. This is good for your rig but maybe not someone elses. I just deleted all -i parameters and rebenched. So far so good. I'll keep upto date.

[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2338261/miners.config.txt)

You can certainly add parameters but yours do not work ;-)

**Comment by RainbowMiner** [comment]
You are right. The RainbowMiner comes with some -i values as presets. I will remove them.

Please try also to set parameter "**Delay**" to a value greater than 0 (in config.txt). It will add "Delay" seconds before new miner starts to give the system some time to regenerate from the previous miner. It reduces the risk of BSOD. 

The driver crash is typical to the "Force P2 state". During high load, everything is fine, but when the load suddenly cuts off (when a miner is being stopped), the GeForce GPUs sometimes switch to P0 state for a very short time. If your overlocking values are too high, the memclock or coreclock may be out of the limits, during this time, thus crashing the drivers.

RBM
