### ISSUE TITLE
please add Finminer  nanominer 

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#510]
https://bitcointalk.org/index.php?topic=5062042.0

**Comment by petrovsky34** [comment]
please)))

**Comment by jch9678** [comment]
Finminer became this

https://bitcointalk.org/index.php?topic=5089248

**Comment by petrovsky34** [comment]
sometimes it happens that phoenix mines to another pool until you restart it

**Comment by petrovsky34** [comment]
![Снимок](https://user-images.githubusercontent.com/39003568/56676766-b0aa8100-66c7-11e9-91f2-0a415c040bbd.PNG)

**Comment by RainbowMiner** [comment]
This looks pretty much like the Phoenix Miner's dev fee mining.

**Comment by RainbowMiner** [comment]
Nanominer is already part of RainbowMiner - but currently restricted to Randomhash CPU mining (Pasc), only. I will give it a shot for the GPU algorithms, too.

**Comment by petrovsky34** [comment]
Initially, he normally minite then after a while constantly minite to this address
FinMiner ADD

**Comment by petrovsky34** [comment]
phoenix 150 mhs
finminer 148 mhs add please

**Comment by RainbowMiner** [comment]
Wow, that's bad news for Phoenix! I'll doublecheck with the developers, but disable Phoenix, for the meantime.

**Comment by RainbowMiner** [comment]
Have you tried Ethminer as substitute? It should work for AMD, too.

**Comment by petrovsky34** [comment]
yes ok

**Comment by petrovsky34** [comment]
nvidia

**Comment by jch9678** [comment]
I believe my phoenix miner was working ok although the worker name was not
showing up at nicehash. I'll double check.

**Comment by RainbowMiner** [comment]
I have added GPU mining for Nanominer (Ethash, Ubqhash, CnR, CnRwz, Cuckaroo29)
