### ISSUE TITLE
Problem with Saronite & Cryptoknight Pool

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#511]
This is what rbminer.net is showing

Name | Algorithm | Pool | Cur | Device | Profit | ETH | USD | Speed | Benched | Power | Mines
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SrbMiner | CryptoNightHeavyXhv | CryptoKnight-XRN | XRN | R9390 | 0.00145949 | 0.048 | 7.92 | 806 H/s | 806.58 H/s | 275 W | for you

I wish 1 gpu could mine $7.92 per day.  I think it has something to do with Saronite merging with Purk and changing the algo to cn-turtle

https://bitcointalk.org/index.php?topic=5133049

**Comment by RainbowMiner** [comment]
Very probably. I will have a look.

**Comment by RainbowMiner** [comment]
I have disabled Saronite on CryptoKnight.
