### ISSUE TITLE
Suggestion: edit configuration from webfig

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#512]
Hi!

It would be nice if the configuration could be made/edited from the webfig. One way could be editing the txt via the webfig, but I think that the best way would be a nicely done configuration editor where we can, via an UI, make the same configuration that now we have to make via console.

**Comment by RainbowMiner** [comment]
Yes, that would be wonderful :)
I have already started with that, but it is a lot of work.

**Comment by Djago** [comment]
Nice!
I'll be waiting!

**Comment by itsdarklikehell** [comment]
Shoot! I would love this!
