### ISSUE TITLE
Powershell Core 6 has Stopped Working

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#518]
Have you ever come across this error before?  I re-installed powershell but that didn't fix the problem.  I can't attach the debug file because RM closes too quickly but if you need me to manually get the files I can do that.

**Comment by jch9678** [comment]
[debug_2019-04-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/3122304/debug_2019-04-26.zip)

I grabbed one right before it quit.

**Comment by RainbowMiner** [comment]
I will look into it now. What ever happens, we will find out.

**Comment by RainbowMiner** [comment]
What is the exact error message?

**Comment by jch9678** [comment]
![Capture](https://user-images.githubusercontent.com/12422346/56832672-3d714e00-6832-11e9-9515-5b37a75a24df.JPG)

**Comment by RainbowMiner** [comment]
Wow, that is pretty bad. I have never seen this before. Since when is this happening?

**Comment by RainbowMiner** [comment]
Please try with the new Powershell Core 6.2.0 - eventually this solves the issue for now:

https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/PowerShell-6.2.0-win-x64.msi

**Comment by RainbowMiner** [comment]
Also, do you remember having done anything in this system, just before the problems started? Like using File Explorer or copying some things from a to b or similar?

**Comment by jch9678** [comment]
I don't remember doing anything like that but I do believe the computer restarted after some update.

**Comment by jch9678** [comment]
Powershell 6.2 didn't fix it.  I'll uninstall first then install.

**Comment by jch9678** [comment]
Uninstalled, restarted, Installed, restarted, checked to make sure it was in the Path.  Got this error.

![Capture](https://user-images.githubusercontent.com/12422346/56853109-e7131680-68e8-11e9-8ca8-177749a040d8.JPG)

**Comment by jch9678** [comment]
I couldn't really fix this and I needed to update windows anyway.  That got rid of it but I have no idea what went wrong.
