### ISSUE TITLE
Loop benchmaring and downloading

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#519]
Hi!

Since 4.1.0.8, RM has started a loop. It downloads WildRig and benchmark all its algos and then, when completed, it starts again with the same miner. I also have 1 download in progress that doesn't download at all. When 4.1.0.9 came out, RM correctly downloaded and benchmarked the corresponding miners, but then again, when it finished, it started again with WildRig.
The countdown of the benchmarks remaining sometimes jump for, say, 20 to 1. And then goes to 20 again.
In the downloads I have
[
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v0.15.5-wildrigmulti/wildrig-multi-windows-0.15.5.7z",
    "Path": "D:\\CryptoCurrencies\\RainbowMiner\\Bin\\AMD-WildRigPreview\\wildrig.exe",
    "Searchable": true,
    "IsMiner": true
  }
]
So I don't know if the download is the actual benchmark.
I just caught:
WARNING: Downloader-error: The process cannot access the file because it is being used by another process.
WARNING: Cannot download D:\CryptoCurrencies\RainbowMiner\Bin\AMD-WildRigPreview\wildrig.exe distributed at https://github.com/RainbowMiner/miner-binaries/releases/download/v0.15.6-wildrig/wildrig-multi-windows-0.15.6.7z.
WARNING: Searching for D:\CryptoCurrencies\RainbowMiner\Bin\AMD-WildRigPreview\wildrig.exe.

I know for sure that: it's benchmarking because in the "Status: Idle" I have lots of WildRig benchmark (by the way, they all have 0W, is that ok?).

![image](https://user-images.githubusercontent.com/34612740/56825088-95a65100-682e-11e9-9215-bb5adad88e20.png)

**Comment by RainbowMiner** [comment]
Oh! Yes, I see - I have found the problem and fixed it. As quick fix, please download the following file into your Miners folder (right-click, save as..). I will push a release, later.

https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Miners/WildRig.ps1
