### ISSUE TITLE
pwsh.exe opening and not closing

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#52]
Multipoolminer has this same problem. pwsh.exe will open for logging but will not close. It will continue to generate multiple instances in task manger. I've been benchmarking for about an hour and I already have open 28 pwsh.exe using almost 1gb of ram. MPM recognizes this issue and are developing a fix. The temp fix is to remove it from the start bat. Yes it is true you will not be able to see hash rate live, but hey at least it wont lag down ram and overall system performance. Would be nice to see it force close the pwsh.exe upon a miner switch. Ideally, It would need to also prevent a popup window. This should be done in the background without interrupting display aswell. Regardless I'm sure after letting it go for 24 hours, I'm sure it will reach my ram limit causing lockup like MPM does. I have had this same issue and resolved it by removing the miner display window. Fixing this would be an awesome enhancement to beat out the competition ;-) Keep up the great work.

**Comment by RainbowMiner** [comment]
What a strange issue! Since I do not have this problem:
- could you solve it by removing the reader? 
- what version of powershell are you using?
- are these pwsh instances clickable, so that you can find out, what command triggered these?

RBM

**Comment by RainbowMiner** [comment]
> could you solve it by removing the reader?

Sorry, I did miss this in your question. So you did solve it by removing the reade. So it must be something with powershell job handling. I will try to figure this out.

**Comment by Byrd1083** [comment]
I'm closing issue, for some reason at the first install, with my c++ error, it was happening. The issue has not seem to return. Must have been shell issue.
