### ISSUE TITLE
When Benchmarking Fails, rbminer.net still shows Benchmarking

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#520]
Hopefully it can be fixed, on more than one occasion I thought everything was fine but RM wasn't running at all.

**Comment by jch9678** [comment]
Along the same lines, rbminer.net seems to lose connection much more often now.  I am constantly getting notifications that my miners are offline and rbminer.net shows them as offline.  I remote into them and they are still running just fine.

**Comment by RainbowMiner** [comment]
The issue should be resolved, by now. I have fixed the time sync between remote machines.
