### ISSUE TITLE
why is NB miner using so much cpu time.

### ISSUE THREAD

**Issue by henry18341834** [RainbowMiner/RainbowMiner#522]
hi,
why is nbminer using so much cpu time?? i am at 100% all the time now. i forced an end task but the program came right back. during the short time it was off cpu time went down a lot.
![screenshot44](https://user-images.githubusercontent.com/10469825/56851186-369e1600-68da-11e9-8e84-540db6b72690.png)

**Comment by RainbowMiner** [comment]
It depends on which algorithm it has been mining. If it has been one of the Cuckaroo29, Cuckaroo29s or Cuckatoo31, then the CPU is used heavily.
You can decrease the load (even use an automation), by adding parameter "--cuckoo-intensity" in miners.config.txt for these algorithms:

> --cuckoo-intensity <intensity> Set intensity of cuckoo, cuckaroo, cuckatoo, [1, 12]. Smaller value means higher CPU usage to gain more hashrate. Set to 0 means automatically adapt.


RainbowMiner uses ```--cuckoo-intensity 1``` - which causes heavy CPU usage but optimizes the mining speed. You might want to try a value >1 (or 0 to let nbminer handle it).

Example miners.config.txt
```
  ...
    "NBminer-GTX1070":  [
                            {
                                "MainAlgorithm":  "Cuckaroo29",
                                "SecondaryAlgorithm":  "",
                                "Params":  "--cuckoo-intensity 3",
                                "MSIAprofile":  "",
                                "OCprofile":  "",
                                "Difficulty":  "",
                                "Penalty":  "",
                                "Disable":  "0"
                            },
                            {
                                "MainAlgorithm":  "Cuckaroo29s",
                                "SecondaryAlgorithm":  "",
                                "Params":  "--cuckoo-intensity 3",
                                "MSIAprofile":  "",
                                "OCprofile":  "",
                                "Difficulty":  "",
                                "Penalty":  "",
                                "Disable":  "0"
                            },
...
```

**Comment by RainbowMiner** [comment]
I have decreased the initial `--cuckoo-intensity` to 2 for good cpu and 4 for weak cpu. Anyway, you may change it to whatever value suits you later in miners.config.txt
