### ISSUE TITLE
Errors while waiting for profitability to come back

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#523]
Status:
WAITING FOR PROFITABILITY
 (be patient or set CheckProfitability to 0 to resume)

 Profit = 0.00000000/0.00000000 BTC/Day | 0.0000/0.0000 EUR/Day | 0.0000/0.0000 USD/Day | 1 BTC = EUR 4648.095 = USD 5173.445

Waiting 49s until next run: E[x]it, [R]estart, [S]kip switching prevention, [W]D reset, [C]onfiguration, [V]erbose, [P]ause
Finished waiting - starting next run

PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'ReferenceObject' because it is null."
PS>TerminatingError(Get-BestMinerDeviceCombos): "Cannot bind argument to parameter 'BestMiners' because it is null."
Get-BestMinerDeviceCombos : Cannot bind argument to parameter 'BestMiners' because it is null.
At C:\_MinerStuff\RainbowMiner\Core.psm1:1428 char:59
+ ...     $BestMiners_Combo = Get-BestMinerDeviceCombos $BestMiners -SortBy ...
+                                                       ~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Get-BestMinerDeviceCombos], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-BestMinerDeviceCombos
Get-BestMinerDeviceCombos : Cannot bind argument to parameter 'BestMiners' because it is null.
At C:\_MinerStuff\RainbowMiner\Core.psm1:1428 char:59
+ ...     $BestMiners_Combo = Get-BestMinerDeviceCombos $BestMiners -SortBy ...
+                                                       ~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Get-BestMinerDeviceCombos], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-BestMinerDeviceCombos

**Comment by RainbowMiner** [comment]
Thank you very much! I will check and fix that.

**Comment by RainbowMiner** [comment]
fixed
