### ISSUE TITLE
[Enhancement] some Web output while waiting on profitability

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#525]
at the moment its not possible to understand watching @web interface , either something stopped working or profitability is below treshold. Is it possible to indicate while profitability is below treshold with some visual feedback instead of "no matching records found" ?

**Comment by RainbowMiner** [comment]
Yes, this is very well possible. I'll add this.

**Comment by RainbowMiner** [comment]
Added new status "Waiting" (yellow) to v4.3.1.6.
