### ISSUE TITLE
Profitability how is this calculated?

### ISSUE THREAD

**Issue by higi** [RainbowMiner/RainbowMiner#526]
Miner                                             BTC                            USD
-----                                             ---                            ---
RainbowMiner                                      0,00033 ±7 % (0,00030-0,00035) 1,72944 ±7 % (1,61623-1,85057)
{ClaymoreEthash-Ethash/Blake2s, Nanominer-Ethash} 0,00058 ±4 % (0,00056-0,00060) 3,07207 ±4 % (2,96716-3,18069)

**Comment by RainbowMiner** [comment]
RainbowMiner tracks the average profitability achieved by started miners over time. The value in the Miner profitability status line is the average profitability measured against the profitability of the currently running miner(s) in percent.
