### ISSUE TITLE
Red Error during start up after enabling network.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#527]
Add-Member : Cannot validate argument on parameter 'NotePropertyMembers'. The argument is null or empty. Provide an argument that is not null or empty, and then try the
command again.
At C:\RainbowMiner\Core.psm1:455 char:60
+                     $Session.Config.GpuGroups | Add-Member $_ $AllGpu ...
+                                                            ~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.AddMemberCommand

**Comment by RainbowMiner** [comment]
Could you send me the .\Config\gpugroups.config.txt file, please?

**Comment by RainbowMiner** [comment]
Ah, found and fixed.
