### ISSUE TITLE
$235,000 per day for Minex at Zpool

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#532]
I think something is wrong.

**Comment by jch9678** [comment]
It might be the miner though, it's reporting 83 kh/s   with a k

**Comment by RainbowMiner** [comment]
It's Zpool - they opened up a new pool for Equihash16x5 (96,5) MMX.

**Comment by RainbowMiner** [comment]
Should be fixed, by now.

**Comment by RainbowMiner** [comment]
I have published a small pool update release. I have disabled Eq16x5 on Zpool temporarily, now.
