### ISSUE TITLE
Webservice issues

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#533]
since last couple updates , im unable to use webinterface even locally by using IP , localhost , etc , obviously remote not work either

before issues started i just set RemoteAPI = 1 and custom APIport , vpn to site and any remote server local user was able to authenticate and use webinterface.

after changes , no matter how i configure API settings , im unable to get to webinterface , not even localy , doesnt matter if RemoteAPI is enabled , so does APIUser, APIAuth , APIPassword not change anything , web not working even locally (APIport is custom) , cant figure out whats changed , suggestions ?

well netstat doesnt show any listener on custom APIport

**Comment by mo35** [comment]
So i was able to connect remotely to my custom APIport web only when i started rainbowminer RunMode as server  (with admin privs) ... id say overkill just for remote web. Im fine with my few boxes as standalone , but i would like to have possibility to see webinterfaces from remote box without running miner as server with admin.

**Comment by mo35** [comment]
update : after launching it once as server/admin and then changing in config back to standalone after restart RB web was working ... very weird tbh

**Comment by RainbowMiner** [comment]
Thank you for bringing this up. I think, it was a firewall issue. I will check what was going on.

**Comment by mo35** [comment]
most probably not FW , since i have its disabled on my rigs.

re-tested my discovery , so yeah launching miner as server/admin , then setting back to standalone works , also i noticed , previously to connect to web with RemoteAPI = 1 i had to authenticate with rigs local user (any) , now it doesnt ask auth whatsoever (probably have to set with thos new API variables , but since im vpning to isolated site to launch web , not tested this)

**Comment by RainbowMiner** [comment]
I have found the reason for this. It has it's origin in the client/server update and RemoteAPI handling. It has changed a lot thus affecting rigs that had RemoteAPI set to one. I'll add some extra checks to avoid this.
