### ISSUE TITLE
[question] lolminer and cuckatoo31 implementation for lesser cards

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#534]
is there any issue that particular feature in lolminer is disabled ?

was playing around and also noticed that for 8gb nvidia cards 4 gb solver is getting selected not 8gb code , thus using only half of potential

**Comment by RainbowMiner** [comment]
Yes, we had multiple users experiencing severe Rig crashes when running the Cuckatoo31 in lolminer. 
That's why I have it disabled, currently.

**Comment by jch9678** [comment]
It seemed to be working for me on 4gb AMD cards, it just wasn't profitable.

**Comment by mo35** [comment]
i dont do AMD ;) , but at some points cuckatoo31 , is more profitable than anything else , noticed particulary on 1060 6gb , they mostly suck for everything lately , but unless 1070 and Ti will load proper 8gb solver in RM , i wont turn it on
