### ISSUE TITLE
.bat for Updating Benchmarks

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#535]
Right now I manually update RainbowMiner to new versions and benchmarks are updated automatically.  I'm thinking about switching to auto updating RainbowMiner but manually updating benchmarks, this way I get the benefits of the updated changes to the Core and Pools.  

Does TouchBenchmarks.bat update benchmarks for new downloaded miners?

**Comment by RainbowMiner** [comment]
Yes. If this bat is started, all benchmarks are considered as current. No more benchmarking will happen.

**Comment by jch9678** [comment]
I'm kind of confused....if I run TouchBenchmarks.bat it will update newly downloaded/updated miners, correct?  And will not touch the stat file for miners that weren't updated.

**Comment by RainbowMiner** [comment]
Oh, sorry, I missed your question:
TouchBenchmarks.bat sets the timestamp of all miner stat files to "now". RainbowMiner compares the date of these statistic files (benchmark files) to the last write time of a stamp file in the corresponding miner's Bin folder. If it's older than this stamp file, RainbowMiner will run a benchmark.
