### ISSUE TITLE
Problems with PowerShell

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#536]
These errors are force closing RainbowMiner

Application: pwsh.exe
CoreCLR Version: 4.6.26725.6
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFF36D753DB (00007FFF36C30000) with exit code 80131506.

and

Faulting application name: pwsh.exe, version: 6.1.0.0, time stamp: 0x5b58a311
Faulting module name: coreclr.dll, version: 4.6.26725.6, time stamp: 0x5b587da7
Exception code: 0xc0000005
Fault offset: 0x00000000001453db
Faulting process id: 0x1140
Faulting application start time: 0x01d50308df3759ab
Faulting application path: C:\Program Files\PowerShell\6\pwsh.exe
Faulting module path: C:\Program Files\PowerShell\6\coreclr.dll
Report Id: ab920f15-a9c3-458c-ada9-e59382ac4030
Faulting package full name: 
Faulting package-relative application ID: 

This is the second machine that was giving me problems with powershell.  I re-installed windows to solve the other one.  On that one powershell wouldn't even start.

**Comment by RainbowMiner** [comment]
Please uninstall powershell core 6.1 and install the most current powershell core 6.2.0
