### ISSUE TITLE
add new pool

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#538]
https://ethashpool.com/
                                                       best pool
https://thegrinpool.com/

**Comment by RainbowMiner** [comment]
Nice. I'll have a look.

**Comment by petrovsky34** [comment]
thanks)))

**Comment by petrovsky34** [comment]
4gb eth etc
3gb etp

**Comment by RainbowMiner** [comment]
Added

**Comment by petrovsky34** [comment]
3gb etp

**Comment by RainbowMiner** [comment]
Ok.

**Comment by RainbowMiner** [comment]
Added ETP = 3GB min. memory for all Ethash miners

**Comment by paulpoco** [comment]
Where do I put the email address I used with EthashPool.com in pool.config.txt ?   For Autoexchange.
