### ISSUE TITLE
cryptodredge cucaroo29 benchmarks

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#539]
there is something funky about cryptodredges cucaroo29 benchmarks. i tought its issue with miner in previous release , but its same with latest too , it doesnt matter if its one 1080ti , or 3x 1060gb , or couple of 1070 , result of bench is always same 10h/s.

for 1080ti miner window shows ~5,5h/s , still in bench it writes 10h/s. 

after each update i have to go manually and disable cucaroo29 on each rig

**Comment by mo35** [comment]
sorry , i auto cleanup logs on each run , dont have any saved , but its easy to replicate on any nvidia card setup

**Comment by mo35** [comment]
sorry i auto clean logs on each launch , dont have any saved , but its easy to replicate on any nvidia setup , if you need help gather some , let me know

**Comment by mo35** [comment]
sorry i auto clean logs on each launch , dont have any saved , but its easy to replicate on any nvidia setup , if you need help gather some , let me know

**Comment by mo35** [comment]
sorry i auto clean logs on each launch , dont have any saved , but its easy to replicate on any nvidia setup , if you need help to gather some , let me know

**Comment by RetroShag** [comment]
I experienced similar issue with my 1080ti.  For 1070, it shows as a failed benchmark even though it passes.

**Comment by RainbowMiner** [comment]
I cannot replicate this CryptoDredge/Cuckaroo29 problem. Would you please try to replicate it and send me a Debug file plus the following Cryptdredge log: `.\Bin\NVIDIA-CryptoDredge\log_313xx.txt`
Thank you!

**Comment by RainbowMiner** [comment]
I have found the problem:  CryptoDredge rounds all hashrate values to kH with two decimal place, only. That's really bad, since all values 0..5G/s will be rounded down to 0.00kG/s (=0G/s) and all values 5G/s..10G/s will be rounded up to 0.01kG/s (=10G/s).
Now let's see how fast we get a new CryptoDredge version. Up to then, I will disable Cuckaroo29 mining with CryptoDredge.
