### ISSUE TITLE
Pool penalties

### ISSUE THREAD

**Issue by RetroShag** [RainbowMiner/RainbowMiner#541]
Do pool penalties refer to % fee? If so, I think some pool penalties are misconfigured, ie blockmaster pool penalty was set at 50 (0.25%) compared to nicehash(2%)

**Comment by RainbowMiner** [comment]
No, the pool fees are constant values, set in the pool modules.
Pool penalties are freely configurable and more a strategic value, that takes into account the real profits compared to the predicted profits (both on-pool values). Some pools pay pretty accurate (like Nicehash), some "loose" a lot of profit on the way from prediction to your wallet.
You may change these presets at any time in pools.config.txt
