### ISSUE TITLE
Cryptodredge SSL error

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#543]
Currently mining HMQ1725 at Zergpool, it appears it is mining fine, but there is this error. I didn't have anything under SSL in the config file, I changed it to SSL = "1" but still no difference
![image](https://user-images.githubusercontent.com/41829368/57583123-7e03d500-748a-11e9-8902-ee8bb8d9436c.png)

**Comment by RainbowMiner** [comment]
Very strange! I am mining with CryptoDredge on Zergpool, too, but do not get these errors. But since there is a connection and the miner is finding shares, I would not mind. Eventually it's the miner's dev fee run.

**Comment by hernandn01** [comment]
very well, thanks

**Comment by RainbowMiner** [comment]
It is confirmed, that it's a CryptoDredge bug - technobyl just published a Bugfix version. I will add a commit asap.
