### ISSUE TITLE
Initial install on Ubuntu 18

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#544]
Went to do a fresh install on a Ubuntu system. Ran the install.sh with no issues. Ran start.sh as and got the following error looped. Sorry to use a picture, But I do not have an easy way to copy and past from this machines.
![IMG_7066](https://user-images.githubusercontent.com/4724631/57631335-2893fa80-7554-11e9-9b19-5afc67ea4971.jpg)

**Comment by Yamanipanuchi** [comment]
Stupid Iphone and upsidedown pictures.. Sorry.

**Comment by RainbowMiner** [comment]
Oh! My bad! You stumbled over a bug in the pre-release. I just fixed it. Sorry for that. Please just clone again.

**Comment by Yamanipanuchi** [comment]
I dont think there is a way to clone stable is there? Or have I just not found it?

**Comment by RainbowMiner** [comment]
It has to be done by-hand :) So download the RainbowMinerV4.3.x.x.zip, using a browser and then unzip into a folder.
If you are interested, I will frickle together an one-liner for unix.
