### ISSUE TITLE
ServerConfigName missing - corrupt config.txt

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#545]
I am not using the Server configuration and have not assign any server name or work any part of this config, received this error/warning but it continued and it is mining

![image](https://user-images.githubusercontent.com/41829368/57638794-bc24f580-756b-11e9-8dda-6bac659940dc.png)

**Comment by RainbowMiner** [comment]
Oh dear! Im so sorry for this! Is the rig running, after you got that message?

**Comment by RainbowMiner** [comment]
Also, could you please send me a Debug file?

**Comment by hernandn01** [comment]
yes, it is running, only that initial message
[debug_2019-05-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/3174162/debug_2019-05-13.zip)

**Comment by RainbowMiner** [comment]
Duh! I thought it had stopped, right after the message, so I quickly removed the release.
Would you send me the Config\config.txt , too, please? I think, there should be the problem.

**Comment by RainbowMiner** [comment]
Thank you. I found it.
