### ISSUE TITLE
Config issue with new update

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#546]
![image](https://user-images.githubusercontent.com/42227809/57639194-35b8e580-7564-11e9-9d4f-f7d8a4b625a9.png)

**Comment by Byrd1083** [comment]
It is doing this on all 5 terminals

**Comment by RainbowMiner** [comment]
Oh dear! What happens! Could you please send me a zip of the Config and Logs folder?

**Comment by RainbowMiner** [comment]
Are your rigs up and running, after that message?

**Comment by RainbowMiner** [comment]
Found the bug.
