### ISSUE TITLE
Help with "SwitchingPrevention"

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#547]
If I increase "SwitchingPrevention": 2.0, to 3.0 or higher, will that reduce changing to an algo that is only say $0.05 more profitable?

I'm trying to prevent switches from happening when the profitability only increase by a small margin.

**Comment by RainbowMiner** [comment]
Hi, yes, that should help. It is a floating point number, so you may try smaller steps, too. Like 2.5, 3.0, 3.5 etc.
