### ISSUE TITLE
Prevent phoenix to use sample failover pools

### ISSUE THREAD

**Issue by giannibonfanti** [RainbowMiner/RainbowMiner#548]
Phoenix comes with two files where you can set failover pools: epools.txt and dpools.txt (for dual mining).
These pools are automatically added to the primary pool set via command line config, if the file is found.

The problem is that these two files are sample files, and they contain two pools already set and enabled (ethermine) with another wallet (developer wallet I suppose).

So every time the primary pool has some connection issues, phoenix switches over these failover pools, mining on another wallet, for 30 min (is the default setting).

My solution is that I manually delete those 2 files, but I need to remember and do it again after every miner update, on every rig.

Is there any other solution?

**Comment by RainbowMiner** [comment]
Thank you for bringing this up! Since I do not use Phoenix, I always wondered, why these strange switching things happened.

Sure, there is another solution. I will just add some check-and-delete logic.

**Comment by RainbowMiner** [comment]
Ok, I have added a start command to the Phoenix miner module. It will remove all "*pools.txt" files, before it launches the miner.

Good finding 👍
