### ISSUE TITLE
Stop remote api per miner

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#55]
Is there any way to stop each individual miner from porting a remote api?

**Comment by RainbowMiner** [comment]
For most ccminer, yes, this is already implemented. The newer one's like T-Rex and EnemyZealot do not have a switch for that, yet. As soon, as they have one, I will add the parameter asap.

RBM

**Comment by Byrd1083** [comment]
I had a feeling that was the issue thanks.
