### ISSUE TITLE
Win10 1903 build 18362.116 , RB just doesnt launch

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#550]
Had to upgrade Win to latest due some glichy MS crap , version in subj. RB just sits there , and cant get past initialization.

reinstalled PS to 6.2 stable , nvidia drivers ,  disabled for phun all AV/FW related stuff , set unrestricted PS , nothing helps , tried previous RB version too , tried clean package , same result

and logs not pointing to anything useful

--------------------
PowerShell transcript start
Start time: 20190521005457
Username: 
RunAs User: 
Configuration Name: 
Machine: TRASH (Microsoft Windows NT 10.0.18362.0)
Host Application: C:\Program Files\PowerShell\6\pwsh.dll -executionpolicy bypass -windowstyle maximized -command & {.\rainbowminer.ps1 -configfile .\Config\config.txt; exit $lastexitcode}
Process ID: 9876
PSVersion: 6.2.0
PSEdition: Core
GitCommitId: 6.2.0
OS: Microsoft Windows 10.0.18362 
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.2.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
---------------------------------

Starting up v4.3.1.4! Please wait..

Detecting devices ..
Initialize configuration ..

----------------------

and thats it , it just sits there

**Comment by RainbowMiner** [comment]
Ok, that's bad. Do you have Anydesk or TeamViewer, so that I could have a closer look? If yes, just send me the credentials by email at rbminer2018@gmail.com or by direct message using Discord.

**Comment by mo35** [comment]
im not fan of remoting since its my main box , but we can try to set it up something when im around.

btw. i tested Mind Miner , was using it before , its also PS based switcher , no issues whatsoever , so its defo RB only issue with latest Win10 build.

**Comment by RainbowMiner** [comment]
Ok, I found it. It's a broken Powershell system function.

**Comment by RainbowMiner** [comment]
Try to update to v4.3.1.5 (start run Updater.bat)

**Comment by mo35** [comment]
that fix did the job , working fine now

**Comment by RainbowMiner** [comment]
Super :+1: thank you for the feedback!
