### ISSUE TITLE
Feature Request: add column beside "Speed" to have the AVG difficulty for that algo?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#551]
Feature Request: add column beside "Speed" to have the AVG difficulty for that algo?
![image](https://user-images.githubusercontent.com/801414/58364354-14ab9b00-7e68-11e9-9898-4c9ad49ce854.png)

**Comment by RainbowMiner** [comment]
Since you are now the second that asks for difficulty, I will have a closer look into the different miner APIs and see, if we can gather that information.

**Comment by paulpoco** [comment]
Might come in handy for recommended difficulty on MRR rig listing.

**Comment by RainbowMiner** [comment]
Added for many miners. Some miners (those which use the EthMan API) will show "-" since they do not report back the current difficulty.
![image](https://user-images.githubusercontent.com/39437538/58382316-18a2fe80-7fc9-11e9-8b3f-f3e45a5e5394.png)

**Comment by paulpoco** [comment]
@RainbowMiner so is that Diff the average or that last difficulty?  This was requested more for MRR rig listings.

**Comment by RainbowMiner** [comment]
It is the one day moving average. If needed, I could also use 3 day MA or one week MA
