### ISSUE TITLE
No Benchmarked Miners in Dashboard

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#552]
For some reason there aren't any algos displayed on the dashboard.  Also ethash2gb and 3gb don't benchmark, I think they might be related.

![Capture](https://user-images.githubusercontent.com/12422346/58449132-d1ebfc00-80cf-11e9-8280-6d6231f95c83.JPG)
[debug_2019-05-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/3225564/debug_2019-05-27.zip)

**Comment by RainbowMiner** [comment]
Thank you, I will have a look

**Comment by RainbowMiner** [comment]
Could you please open http://localhost:3334/minerstats in your browser and send me the result (if there is any)?

**Comment by RainbowMiner** [comment]
I think, I have found & fixed the problem.

**Comment by jch9678** [comment]
The updates have fixed the problem of no algos in the dashboard however ethash2gb and ethash3gb are still not showing up.
