### ISSUE TITLE
Loading Pool Modules Question

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#553]
Just a thought, is there a reason these are loaded sequentially?  It seems like you could cut down on the startup time if they are loaded at the same time.

**Comment by RainbowMiner** [comment]
I have thought a lot about doing it in parallel, all the time. But came to the conclusion, that it does not benefit the runtime. So I created a solution, that optimizes the timing. Actually, it's only the start, that takes some more time (not a restart. For that, all data is pulled out of a cache). After that the asyncloader module takes control and does the time expensive API communications in the background. RainbowMiner just collects the data, round by round, then.

**Comment by jch9678** [comment]
Thanks. Your solution makes sense.
