### ISSUE TITLE
Suddenly I can't mine CriptoNight

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#554]
I was mining until 9:39 today. Then, without any warning, Cryptonight disappeared from my system.
[debug_2019-05-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/3233522/debug_2019-05-29.zip)
It's not listed on Miners page, but it's on Activity. What can I do?

**Comment by RainbowMiner** [comment]
Try to either restart RainbowMiner or the reset Watchdog option

**Comment by Djago** [comment]
I've already restarted the computer 2 times to no avail. I'm a little dizzy with so many options and I can't find the watchdog option. Where is it?

**Comment by RainbowMiner** [comment]
Don't mind. A restart of RainbowMiner resets it too. I'll look into your debug file.

**Comment by RainbowMiner** [comment]
It looks like MiningPoolHub is down:
```
Problem fetching https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics&{timestamp} using REST: Host desconocido
```

**Comment by RainbowMiner** [comment]
Perhaps was down. Do the following: stop RainbowMiner, delete the complete "Cache" folder in RainbowMiner folder, start RainbowMiner

**Comment by Djago** [comment]
I've tried. And... It didn't work.

**Comment by RainbowMiner** [comment]
Try to call
https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics
.. in your browser. What does it say?

**Comment by RainbowMiner** [comment]
If you click "All pools" - can you select CryptonightR as algorithm? If yes, what does the result look like?

**Comment by Djago** [comment]
> Try to call
> https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics
> .. in your browser. What does it say?

{"success":true,"return":[{"algo":"X16r","current_mining_coin":"ravencoin","host":"us-east.x16r-hub.miningpoolhub.com","all_host_list":"us-east.x16r-hub.miningpoolhub.com;europe.x16r-hub.miningpoolhub.com;asia.x16r-hub.miningpoolhub.com","port":12028,"algo_switch_port":17028,"multialgo_switch_port":12028,"profit":0.00444393,"normalized_profit_amd":0.02666356,"normalized_profit_nvidia":0.10221031},{"algo":"Lyra2RE3","current_mining_coin":"vertcoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12027,"algo_switch_port":17027,"multialgo_switch_port":12027,"profit":0.00108873,"normalized_profit_amd":0.03266187,"normalized_profit_nvidia":0.04681534},{"algo":"Equihash-BTG","current_mining_coin":"bitcoin-gold","host":"us-east.equihash-hub.miningpoolhub.com","all_host_list":"us-east.equihash-hub.miningpoolhub.com;europe.equihash-hub.miningpoolhub.com;asia.equihash-hub.miningpoolhub.com","port":12026,"algo_switch_port":17026,"multialgo_switch_port":12026,"profit":1294.65758629,"normalized_profit_amd":0.01424123,"normalized_profit_nvidia":0.07120617},{"algo":"Cryptonight-Monero","current_mining_coin":"monero","host":"us-east.cryptonight-hub.miningpoolhub.com","all_host_list":"us-east.cryptonight-hub.miningpoolhub.com;europe.cryptonight-hub.miningpoolhub.com;asia.cryptonight-hub.miningpoolhub.com","port":12024,"algo_switch_port":17024,"multialgo_switch_port":12024,"profit":63.89425971,"normalized_profit_amd":0.03737814,"normalized_profit_nvidia":0.04491766},{"algo":"Equihash","current_mining_coin":"zcash","host":"us-east.equihash-hub.miningpoolhub.com","all_host_list":"us-east.equihash-hub.miningpoolhub.com;europe.equihash-hub.miningpoolhub.com;asia.equihash-hub.miningpoolhub.com","port":12023,"algo_switch_port":17023,"multialgo_switch_port":12023,"profit":13.86146133,"normalized_profit_amd":0.00360398,"normalized_profit_nvidia":0.0094951},{"algo":"Sia","current_mining_coin":"siacoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12022,"algo_switch_port":17022,"multialgo_switch_port":12022,"profit":0,"normalized_profit_amd":0,"normalized_profit_nvidia":0},{"algo":"Yescrypt","current_mining_coin":"myriadcoin-yescrypt","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12021,"algo_switch_port":17021,"multialgo_switch_port":12021,"profit":2.47935612,"normalized_profit_amd":0.00079339,"normalized_profit_nvidia":0.00413309},{"algo":"Ethash","current_mining_coin":"ethereum-classic","host":"us-east.ethash-hub.miningpoolhub.com","all_host_list":"us-east.ethash-hub.miningpoolhub.com;europe.ethash-hub.miningpoolhub.com;asia.ethash-hub.miningpoolhub.com","port":12020,"algo_switch_port":17020,"multialgo_switch_port":12020,"profit":0.00282959,"normalized_profit_amd":0.07073978,"normalized_profit_nvidia":0.09903569},{"algo":"Lyra2RE2","current_mining_coin":"monacoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12018,"algo_switch_port":17018,"multialgo_switch_port":12018,"profit":9.313e-5,"normalized_profit_amd":0.00353883,"normalized_profit_nvidia":0.00450363},{"algo":"Skein","current_mining_coin":"digibyte-skein","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12016,"algo_switch_port":17016,"multialgo_switch_port":12016,"profit":9.15e-6,"normalized_profit_amd":0.00247049,"normalized_profit_nvidia":0.00547625},{"algo":"Qubit","current_mining_coin":"digibyte-qubit","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12014,"algo_switch_port":17014,"multialgo_switch_port":12014,"profit":2.193e-5,"normalized_profit_amd":0.00026974,"normalized_profit_nvidia":0.00066381},{"algo":"NeoScrypt","current_mining_coin":"feathercoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12012,"algo_switch_port":17012,"multialgo_switch_port":12012,"profit":0.01785306,"normalized_profit_amd":0.00873015,"normalized_profit_nvidia":0.0254049},{"algo":"X11","current_mining_coin":"dash","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12007,"algo_switch_port":17007,"multialgo_switch_port":12007,"profit":9.41e-6,"normalized_profit_amd":0.00011295,"normalized_profit_nvidia":0.00019681},{"algo":"Myriad-Groestl","current_mining_coin":"digibyte-groestl","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12005,"algo_switch_port":17005,"multialgo_switch_port":12005,"profit":1.683e-5,"normalized_profit_amd":0.00058794,"normalized_profit_nvidia":0.00189579},{"algo":"Groestl","current_mining_coin":"groestlcoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12004,"algo_switch_port":17004,"multialgo_switch_port":12004,"profit":1.238e-5,"normalized_profit_amd":0.00012081,"normalized_profit_nvidia":0.0007579},{"algo":"Keccak","current_mining_coin":"maxcoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12003,"algo_switch_port":17003,"multialgo_switch_port":12003,"profit":6.5e-6,"normalized_profit_amd":0.00227507,"normalized_profit_nvidia":0.00611956},{"algo":"Scrypt","current_mining_coin":"verge-scrypt","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12001,"algo_switch_port":17001,"multialgo_switch_port":12001,"profit":0.00045359,"normalized_profit_amd":0.00032658,"normalized_profit_nvidia":0.00040596}]}

> If you click "All pools" on http://localhost:4000 - can you select CryptonightR as algorithm? If yes, what does the result look like?

No...

**Comment by Djago** [comment]
The only place where I can filter with CryptoNightR is on the "Activity". There's no trace of CryptoNightR in Pools, Miners, Active Miners, nor Benchmarks

**Comment by Djago** [comment]
Just updated to 4.3.2.0. CryptoNightR still unavailable

**Comment by RainbowMiner** [comment]
That is really strange. Your config looks totally normal. And CryptonightR should be avail on Nicehash and MiningPoolHub. Eventually, the algorithms.json database has been damaged for whatever reason. 
I have just pushed an update - does CnR reappear after the Update?

**Comment by RainbowMiner** [comment]
Ok, so it just happened? You did not work at that PC?

**Comment by RainbowMiner** [comment]
Open http://localhost:4000/watchdogtimers in your browser. What does it say?

**Comment by Djago** [comment]
> Open http://localhost:4000/watchdogtimers in your browser. What does it say?

[
  {
    "MinerName": "CpuminerYespower-CPU#00",
    "DeviceModel": "CPU",
    "PoolName": "NLpool",
    "Algorithm": "Yespower",
    "Kicked": "2019-05-30T14:59:48.6330445Z"
  }
]

> Ok, so it just happened? You did not work at that PC?

At Activity it says that RM used SRB at 9.39.  Minutes later I configured RM to alert me via email and pushover but nothing less.
UPDATE: looking at Activity, I have two new etnries. One at 16:24 and one today at 4:25. So, this is more complex than it seems. I wasn't working at 4:25 for sure. I was using the computer at 16:24 but the usual thing (TeamViewer and web browsing, maybe an Excel open too).

**Comment by RainbowMiner** [comment]
Would you please send me your config.txt? Eventually there is something weird.

**Comment by Djago** [comment]
[config.zip](https://github.com/RainbowMiner/RainbowMiner/files/3237647/config.zip)

**Comment by RainbowMiner** [comment]
Please enable Nicehash for a test. It is on the pool exclude list. I would like to know, if CryptonightR shows up for Nicehash.

**Comment by Djago** [comment]
I've removed NiceHash from the ExcludePoolName and still, CN isn't showing anywhere...

**Comment by Djago** [comment]
4.3.2.1. same thing....

**Comment by Djago** [comment]
One thing to add: RM sometimes mines XMR on CPU and most of the time, on VEGA56. It disappeared from both, so it doesn't seem to be a problem with drivers whatsoever

**Comment by RainbowMiner** [comment]
Have you added Nicehash to the PoolName list, for the test?

**Comment by Djago** [comment]
No, I didn't! Now I did and RM started to mine XMR again, on NiceHash.
What can I do to regain MPH?

**Comment by RainbowMiner** [comment]
That's good news :) Please look into your pools.config.txt - section MiningPoolHub. It looks like there is no username. For mining on MPH you will need to fill in the `"User": "<mphusername>",`

**Comment by RainbowMiner** [comment]
A remark, regarding PoolName / ExcludePoolName:

"PoolName" is mandatory, that means that every pool you want RainbowMiner to use, needs to be on that list.

"ExcludePoolName" is optional. It can be left empty, since PoolName defines exactly which pools to use. It's main use is to quickly (temporarily) disable a pool, that is on the PoolName list. Some users like to keep all unused pools on that list, so that they have an easy copy-and-paste template.

**Comment by Djago** [comment]
Bingo!
But why did it happen?
