### ISSUE TITLE
Potential Claymore Issue.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#555]
I get this on ClaymoreEthash all the time on two separate miners...
ClaymoreEthash    Ethash    NiceHash    GTX1080Ti    NaN    0 H/s    0 H/s    0 W

**Comment by Yamanipanuchi** [comment]
[debug_2019-05-31.zip](https://github.com/RainbowMiner/RainbowMiner/files/3242162/debug_2019-05-31.zip)

**Comment by RainbowMiner** [comment]
Seems like your upload is broken. Please re-upload the Debug file. It's empty.

**Comment by Yamanipanuchi** [comment]
Ya all the Debug files have been empty lately.. I submitted an issue for that one also.. :|
