### ISSUE TITLE
[question] enforced fullscreen

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#556]
Since there is no param in config , is there some variable or code snippet to disable full screen launch? Annoys me quite alot on main box.

**Comment by RainbowMiner** [comment]
No, there is no parameter for this. I'll add a secondary Start.bat

**Comment by RainbowMiner** [comment]
Added. It's StartInWin.bat (release v4.3.2.2)

**Comment by mo35** [comment]
cheers
