### ISSUE TITLE
Client config download missing pool selection

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#558]
I've installed and setup several system recently using the Client/Server setup and downloading the config. I have the following in my server config file...

 "PoolName": "MiningRigRentals,NiceHash,ZergPool",

Once i've told the script to download the config it goes though all the choices and everything is there except of this one value. This one value will only have "ZergPool" selected. I end up needing to manually enter the other two pools in.

**Comment by RainbowMiner** [comment]
Oh. That should not happen. I will check asap.

**Comment by RainbowMiner** [comment]
Difficult to tell, what's happening there. Would you please try the following url in one of your clients web browsers?
`http://<your-servername-or-ip>:<your-server-port>/getconfig?version=4.3.2.4&config=config`
Is the "PoolName" field transmitted correctly?

**Comment by Yamanipanuchi** [comment]
Shows up correct there. I am just about to setup another machine.  I am fairly certain it is going to happen cause its been happening for a while. Not sure it its just something goofy in my config or not though.

**Comment by Yamanipanuchi** [comment]
"PoolName": "MiningRigRentals,NiceHash,ZergPool",

System I just setup only had ZergPool auto populated. Had to enter the other two manually.

**Comment by RainbowMiner** [comment]
Thank you for checking and reporting. So it's either a problem on the client side or:
Question: do you have subdirectories for individual client configurations inside your server's Config folder?

**Comment by RainbowMiner** [comment]
I just went to the whole process, step-by-step, no problems found. So it must be some different thing.
Please try the following url on that new client. Substitute your client's workername (the mining-name) and the client's machinename (that's the windows hostname):

`http://<your-servername-or-ip>:<your-server-port>/getconfig?config=config&workername=clientworkername&machinename=clientmachinename&version=4.3.2.4`

Do you still get the correct "PoolName" variable?

**Comment by RainbowMiner** [comment]
Could you tell me all steps, one by one, that you take to setup a new machine?

**Comment by Yamanipanuchi** [comment]
After initial OS install and driver install if system has a GPU I do the following...

git clone https://github.com/RainbowMiner/RainbowMiner.git

sudo chmod 777 install.sh

sudo ./install.sh

I select to start the script from there. and continue through all the choices.  I have dont most Linux installs recently but I had seen this issue on a Windows install which is actually a little more simple of an install.

I have user both root config on the server and now am using the separate folders for each rig.

I will most likely be doing another install today and will see if I can screen capture the SSH session.

**Comment by Yamanipanuchi** [comment]
Here is a screen capture of me setting up a new system.

I already had a folder 9020m-2 on my server copied off and existing system (9020m-1)

Preparing to unpack .../p7zip_16.02+dfsg-6_amd64.deb ...
Unpacking p7zip (16.02+dfsg-6) ...
Selecting previously unselected package p7zip-full.
Preparing to unpack .../p7zip-full_16.02+dfsg-6_amd64.deb ...
Unpacking p7zip-full (16.02+dfsg-6) ...
Setting up p7zip (16.02+dfsg-6) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up p7zip-full (16.02+dfsg-6) ...

Start RainbowMiner (run start.sh) now? (yes/no) [default=no]: yes
Transcript started, output file is .\Logs\RainbowMiner_2019-06-10_21-10-28.txt
__________        .__      ___.                   _____  .__
\______   \_____  |__| ____\_ |__   ______  _  __/     \ |__| ____   ___________
 |       _/\__  \ |  |/    \| __ \ /  _ \ \/ \/ /  \ /  \|  |/    \_/ __ \_  __ \
 |    |   \ / __ \|  |   |  \ \_\ (  <_> )     /    Y    \  |   |  \  ___/|  | \/
 |____|_  /(____  /__|___|  /___  /\____/ \/\_/\____|__  /__|___|  /\___  >__|
        \/      \/        \/    \/                     \/        \/     \/

Starting v4.3.2.6! Please wait..

Detecting devices ..
Initialize configuration ..
Read configuration ..


*** RainbowMiner Configuration ***


Hints (read them all! It will make entering data much easier):

- press Return to accept the defaults
- fields marked with * are mandatory
- use comma "," to separate list entries
- add new entries to a list, by adding a "+" in front of your input
- remove entries from a list, by adding a "-" in front of your input
- enter "list" or "help" to show a list of all valid entries
- enter "back" or "<" to repeat the last input
- enter "delete" to clear a non-mandatory entry
- enter "save" or "done" to end config and save changes
- enter "exit" or "cancel" to abort without any changes to the configuration


(1) Basic Setup


Every pool (except the MiningPoolHub) wants the miner to send a worker's name. You can change the name later. Please enter only letters and numbers.

Enter your worker's name [default=rainbowminer]*: 9020m-2
Select the operation mode of this rig (standalone,server,client) [default=standalone]: client

Let's start with the local setup of this machine's API.

RainbowMiner can be monitored using your webbrowser via API:
- on this machine: http://localhost:4000
- on most devices in the network: http://m9020:4000
- on any other device in the network: http://192.168.0.32:4000

If needed, choose a different API port [default=4000]*:
Enable username/password to protect access to the API? (yes/no) [default=no]:

Now let us continue with your server's credentials

Enter the server's IP-address (leave empty for standalone operation):
Enter the server's API port (clear for standalone operation) [default=4000]: back

Now let us continue with your server's credentials

Enter the server's IP-address (leave empty for standalone operation): yamen.poweredbyclear.com
Enter the server's API port (clear for standalone operation) [default=4000]:
If you have auth enabled on your server's API, enter the username (leave empty for no auth):
If you have auth enabled on your server's API, enter the password (leave empty for no auth):

Server connected successfully!


RainbowMiner can use centralized configuration files:
selected config files will be downloaded automatically, if changed on the server rig

HINT:
If specific config files for this client are needed, put them into subdirectory ".\Config\9020m2" on your server

Enable automatic download of selected server config files?  (yes/no) [default=no]: yes
Enter the config files to be copied to this machine [default=config,coins,pools,algorithms]:

Select all config parameters, that should not be overwritten with the server's config
- config.txt: use the parameter name
- pools.config.txt:
  "pools:<poolname>" to protect all parameters of a pool
  "pools:<poolname>:<parameter>" to protect a specific parameter of a pool
   e.g. "pools:MiningRigRentals:API_Key" will protect API_Key for MiningRigRentals

Enter all config parameters, that should not be overwritten (if unclear, use default values!) [default=WorkerName,DeviceName,Proxy,APIPort,APIUser,APIPassword,APIAuth,MSIApath,NVSMIpath,CPUMiningThreads,CPUMiningAffinity,GPUMiningAffinity,ServerName,ServerPort,ServerUser,ServerPassword,EnableServerConfig,ServerConfigName,ExcludeServerConfigVars,RunMode,StartPaused]:
Download server configuration now? This will end the setup. (yes/no) [default=yes]:

Configfiles downloaded successfully!


Please lookup your BTC wallet address. It is easy: copy it to your clipboard and then press the right mouse key in this window to paste

Enter your BTC wallet address [default=1Ffs7vFN5B2MV6X6q3KAEugGM4u7qxGY3C]*:

If you plan to mine using the Nicehash-pool, I recommend you register an account with them, to get a NiceHash wallet address (please read the Pools section of our readme!). I would not mine to your standard wallet (1Ffs7vFN5B2MV6X6q3KAEugGM4u7qxGY3C), since Nicehash has a minimum payout amount of 0.1BTC (compared to 0.001BTC, when using their wallet).
If you do not want to use Nicehash as a pool, leave this empty (or enter "clear" to make it empty) and press return

Enter your NiceHash-BTC wallet address [default=1Ffs7vFN5B2MV6X6q3KAEugGM4u7qxGY3C]:
You have entered your default wallet as Nicehash wallet. NiceHash will have a minimum payout of 0.1BTC. Do you want to disable NiceHash mining for now? (Or enter "<" to return to the wallet query) (yes/no) [default=yes]:

Now is your chance to add other currency wallets (e.g. enter XWP for Swap)

Do you want to add/edit wallet addresses of non-BTC currencies? (yes/no) [default=no]:

If you plan to use MiningPoolHub for mining, you will have to register an account with them and choose a username. Enter this username now, or leave empty to disable MiningPoolHub (can be activated, later)

Enter your Miningpoolhub user name:

If you plan to offer your rig for rent at MiningRigRentals, you will have to register an account with them and choose a username. Enter this username now, or leave empty to disable MiningRigRentals (can be activated, later)

Enter your MiningRigRentals user name:

Choose the region, you live in, from this list (remember: you can always simply accept the default by pressing return):
 us
 sea
 sg
 br
 usa
 europe
 na
 ru
 hk
 eu
 jp
 ca
 cn
 in
 asia

Enter your region [default=us]*:
Enter all currencies to be displayed (e.g. EUR,USD,BTC) [default=BTC,USD]*:

RainbowMiner includes a lot of different miner programs. Before the regular profit switching operation may start,
all programs need to be benchmarked on your system, once. The benchmarks will already mine into your wallet,
but it may take a long time to finish. Please be patient. It is a one time thing.

Please select the benchmark-accuracy. This value will determine the runtime interval used for benchmarks
(this value can be set to individual values by directly changing BenchmarkInterval in config.txt).
- Quick   = 60 seconds (should be enough, for most cases)
- Normal  = 90 seconds
- Precise = 180 seconds
Please select the benchmark accuracy (enter quick,normal or precise) [default=quick]*:

RainbowMiner can track this and all of your rig's status at https://rbminer.net (or another compatible service)
If you enable this feature, you may enter an existing miner status key or create a new one.
It is possible to enter an email address or a https://pushover.net user key to be notified in case your rig is offline.

Do you want to enable central monitoring? (yes/no) [default=yes]:
Enter the miner monitoring url [default=https://rbminer.net]:
Enter your miner monitoring status key (or enter "new" to create one) [default=f4ef0d2d-d3d5-43cc-aca3-b9888c7c79b4]:
Enter a offline notification eMail (leave empty to disable):
Enter your https://pushover.net user key (leave empty to disable):
Enable automatic update, as soon as a new release is published (yes/no) [default=yes]:
Automatically add new algorithms to config.txt during update (yes/no) [default=yes]:
Automatically start benchmarks of updated miners (yes/no) [default=yes]:

(2) Select your pools, miners and algorithm (be sure you read the notes in the README.md)


Choose your mining pools from this list or accept the default for a head start (read the Pools section of our readme for more details):
2Miners, 2MinersSolo, AHashPool, Aionmine, BlazePool, BlockMasters, BlockMastersCoins, Bsod, BsodParty, BsodSolo, CoinFoundry, CryptoKnight, EthashPool, Ethermine, F2pool, FairPool, GosCx, GosCxParty, GosCxSolo, Grinmint, Hashpool, Hashrefinery, HeroMiners, Icemining, LuckyPool, MinerMore, MinerRocks, Minexmr, MiningPoolHub, MiningPoolHubCoins, MiningRigRentals, Mintpond, Nanopool, NiceHash, NLpool, NLpoolCoins, PhiPhiPool, PocketWhale, PoolSexy, Ravenminer, SparkPool, YiiMP, ZergPool, ZergPoolCoins, ZergPoolCoinsParty, ZergPoolCoinsSolo, ZergPoolParty, ZergPoolSolo, Zpool

Hint: "+entryname" = add an entry to a list, "-entryname" = remove an entry from a list

Enter the pools you want to mine [default=ZergPool]*: MiningRigRentals,NiceHash,ZergPool

You are almost done :) Our defaults for miners and algorithms give you a good start. If you want, you can skip the settings for now

Do you want to skip the miner and algorithm setup? (yes/no) [default=yes]:

**Comment by RainbowMiner** [comment]
Ok, I think I found the potential problem. You wrote:
`I already had a folder 9020m-2 on my server copied off and existing system (9020m-1)`

Actually, RainbowMiner removes all non alphanumeric characters from the folder name. So, if you do not have a folder "9020m2" within your server's "Config" folder, it would copy the ".\Config\config.txt".

Could that be the problem?

I will do the following: with the next release, I will allow "-" and "_" in the folder names, too.

**Comment by RainbowMiner** [comment]
I must row back: some pools do not accept "-" nor "_" as characters in workername.

So, please do use alphanumeric characters for the workername, only.

**Comment by Yamanipanuchi** [comment]
This issue was present before i had the folders setup for the config. I just did a re install on a machine that does not have -‘s in it and still had this issue.

**Comment by RainbowMiner** [comment]
Ahh!! Now I see it! It is not a bug during runtime, but a bug in the setup script. I will fix it now.

**Comment by RainbowMiner** [comment]
Ok, I have fixed it. The clue was the missing "User" during setup. I had been blind, sorry for that!

**Comment by Yamanipanuchi** [comment]
Just confirmed both fixed on the most recent install.
