### ISSUE TITLE
Selected US but miners running EU

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#56]
![image](https://user-images.githubusercontent.com/42227809/44887651-303f9780-ac82-11e8-95aa-d042da0721f8.png)

[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2338460/config.txt)

I have not modified any of your .ps1 files.

**Comment by Byrd1083** [comment]
![image](https://user-images.githubusercontent.com/42227809/44887785-be1b8280-ac82-11e8-853d-ef58418d08c2.png)

**Comment by RainbowMiner** [comment]
Looks like a problem with miningpoolhub matching. I will check it.

RBM

**Comment by Byrd1083** [comment]
Did v3.8.4 fix this?

**Comment by Byrd1083** [comment]
I tested and yes that fixed the issue. I'm now running on us-east after date. Great job!

**Comment by Byrd1083** [comment]
I tested and yes that fixed the issue. I'm now running on us-east after date. Great job!
