### ISSUE TITLE
Windows 1903 and Powershell Problems

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#560]
I was having storage space issues and other general issues so I decided to do a clean windows install on one of my machines with Windows 1903.  RM and Powershell don't seem to like it. Powershell 6.2 and RM do not work at all on 1903, RM closes after a few seconds.  After installing 6.2.1 RM will start but eventually closes with this error in RM:

```
Read configuration ..
PS>TerminatingError(Get-Command): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
```
and
```
Waiting 20s until next run: E[x]it, [R]estart, [S]kip switching prevention, [W]D reset, [C]onfiguration, [V]erbose off, [P]ause
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:20300""
PS>TerminatingError(ConvertFrom-Json): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'InputObject' because it is null."
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:20300""
PS>TerminatingError(ConvertFrom-Json): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'InputObject' because it is null."
Finished waiting - starting next run
```
There is a Powershell 7.0 Preview but I have not tried it.

[debug_2019-06-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/3263076/debug_2019-06-06.zip)

**Comment by RainbowMiner** [comment]
Ouch. I will have a look.

**Comment by RainbowMiner** [comment]
But is this machine running? Or does it really just open and shut down without mining?
Also, please try to install the latest Dotnet Framework:
https://dotnet.microsoft.com/download/dotnet-framework/net472

**Comment by jch9678** [comment]
It wouldn't mine at all with powershell 6.2 installed. Rainbow miner would
quit some time during initialization. I updated to 6.2.1 and it mined for
some time. I started rainbow miner in order to get a debug file but
manually closed it as soon as it was downloaded for the last log entry.
I'm thinking it might be the .net framework. I thought I installed the
latest version when setting up windows. Do you know if installing an older
version will overwrite a newer version?

**Comment by RainbowMiner** [comment]
Honestly, I do not know. I would rather uninstall the older version, first.

**Comment by jch9678** [comment]
Will do. I have a feeling this is the problem.

**Comment by jch9678** [comment]
It appears that .net 4.8 comes with windows 1903

**Comment by thebeerbaron2018** [comment]
I've had the same on a new build.  The solution was a combination of installing the 32 and 64 bit visual C runtimes and then the dotnet SDK.

Download the x86 and x64 c++ redists from here:
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

and the dot net SDK from here:
https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.2.300-windows-x64-installer

Hope that helps

**Comment by jch9678** [comment]
Thanks @thebeerbaron2018 apologies for taking so long to get back to you. I installed the redists as you suggested and tried the dotnet -info and got the errors.  I haven't tried the SDK, I just can't bring myself to install an sdk when I think it should be ok.  Before I do, I need to see if I'm still having this problem, I haven't checked in a while.

**Comment by thebeerbaron2018** [comment]
@jch9678  No worries - you do need the SDK - it will solve your issue - you need both (and you can always uninstall it anyway).  More info :  the SDK installs "dotnet core" which is the part you're missing currently.

**Comment by jch9678** [comment]
Ahh I see. We came across this problem when grin miner came out. It was
thought we needed the SDK but we actually only needed the runtime. I'll
test that and see what happens.

**Comment by jch9678** [comment]
I installed .net core runtime, restarted, and I get this after DOTNET -INFO : 

Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

I didn't get the error so I'm going to stick with the runtime for now.  Thanks for the help.

**Comment by thebeerbaron2018** [comment]
I think you missed out the report from DOTNET -INFO  but I suspect you got the correct response which is instead for a red error message you get a page of text detailing your dotnet information as installed - which means everything is good to go!  Glad I could help
