### ISSUE TITLE
Debug download is not working

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#561]
Two of my Rigs dropped off while using MRR in the middle of a rental. Cannot figure out why. All other Algorithms go online but the one that is being rented. Tried to download the DeBug.zip file to submit it and the file has 0 files in it.

**Comment by Yamanipanuchi** [comment]
It looks as if I had a power fluctuation which re-started the two machines in question. When they came back up they did the version upgrade and then the benchmarks. I had a benchmark issue with CryptoNightR on one of them. Disabled it. Left the machines for a while and they finally started crunching on MRR again. Was a Very odd line of events there.

**Comment by RainbowMiner** [comment]
Wow! Yes, that sounds like an unfortunate chain reaction.
