### ISSUE TITLE
Mining not my pools and wallets

### ISSUE THREAD

**Issue by rhadamants** [RainbowMiner/RainbowMiner#562]
Some time mining my config pools and wallets. My pools Zergpool and Bsod. Never used Nicehash.
[Config.zip](https://github.com/RainbowMiner/RainbowMiner/files/3274385/Config.zip)
[notmy.txt](https://github.com/RainbowMiner/RainbowMiner/files/3274375/notmy.txt)
   
My pc is a zombie miner?
Only stop mining this strange wallet with restart Rainbown miner.

**Comment by RainbowMiner** [comment]
Hi, this is my developer fee wallet. It mines a couple of minutes a day for me.

**Comment by rhadamants** [comment]
I don't see this wallet before but is ok if wallet donation. 😃
