### ISSUE TITLE
Client/Server "User": "",

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#563]
In client/server setup when config is downloaded  "User": "", comes over blank when the system config file has something populated in it.

I dont know if this is intentional or not?

**Comment by RainbowMiner** [comment]
It's the "User" in pools.config.txt ?

**Comment by RainbowMiner** [comment]
It is potentially the same problem: please do not use "-" or "_" in your workername. Stay with alphanumeric, only.

**Comment by RainbowMiner** [comment]
A side note: API_ID and API_Key will always be empty for new rigs. This is intended. But User should be filled.

**Comment by Yamanipanuchi** [comment]
no - or _ in my username. just normal letters.

**Comment by RainbowMiner** [comment]
So, did it work, now?

**Comment by RainbowMiner** [comment]
Fixed.
