### ISSUE TITLE
System will not stay on MiningRigRentals

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#564]
I have the following in my device config. If I get a CPU and GPU rental at the same time GPU rental drops and will not start back up again. Double, triple and quadruple checked the API key. Do I need separate API keys for each device?

{
  "CPU": {
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "DefaultOCprofile": "",
    "PowerAdjust": "100",
    "Worker": "T5610-cpu"
  },
  "GTX1080Ti": {
    "DefaultOCprofile": "Profile2",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "DisableDualMining": "",
    "PowerAdjust": "80",
    "Worker": "T5610-gpu"
  }
}

**Comment by RainbowMiner** [comment]
Which algorithm is it? All or a specific?
Please send me your MRR rig Description. I will have a look.

**Comment by RainbowMiner** [comment]
Eventually it is a renter's pool problem or too many rejected shares. If that would happen, RBM would mine in normal operation and retry every 15 minutes.

**Comment by Yamanipanuchi** [comment]
If its a bad pool is their a way to confirm this? cause most of what i find in the log files it just looks like it stops with no cause.
