### ISSUE TITLE
Errors starting and mining, but working..

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#565]
Hi

Today, after last update, I started getting errors when mining, and after trying to restart RM, I get:

> ... Loading miner modules ..
> Cannot convert value "False" to type "System.Int32". Error: "Input string was not in a correct format."
>At D:\CryptoCurrencies\RainbowMiner\Include.psm1:86 char:13
>+         if ([int]$ver1[$i] -lt [int]$ver2[$i]) {if ($Warning -ne "")  ...
>+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>+ FullyQualifiedErrorId : InvalidCastFromStringToInteger
>
>Cannot convert value "False" to type "System.Int32". Error: "Input string was not in a correct format."
>At D:\CryptoCurrencies\RainbowMiner\Include.psm1:87 char:13
>+         if ([int]$ver1[$i] -gt [int]$ver2[$i]) {return $true}
>+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>+ FullyQualifiedErrorId : InvalidCastFromStringToInteger
>Selecting best miners ..

Then, while mining I get:

>Cannot convert value "False" to type "System.Int32". Error: "Input string was not in a correct format."
>At D:\CryptoCurrencies\RainbowMiner\Include.psm1:86 char:13
>+         if ([int]$ver1[$i] -lt [int]$ver2[$i]) {if ($Warning -ne "")  ...
>+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>+ FullyQualifiedErrorId : InvalidCastFromStringToInteger
>
>Cannot convert value "False" to type "System.Int32". Error: "Input string was not in a correct format."
>At D:\CryptoCurrencies\RainbowMiner\Include.psm1:87 char:13
>+         if ([int]$ver1[$i] -gt [int]$ver2[$i]) {return $true}
>+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>+ FullyQualifiedErrorId : InvalidCastFromStringToInteger

But it appears that **it is** mining

**Comment by RainbowMiner** [comment]
The error messages should be gone with this commit: 1e1542b53ff78909f8f8f7ceae5a50b52a205201

**Comment by Djago** [comment]
Gone!
