### ISSUE TITLE
Add Suprnova pool

### ISSUE THREAD

**Issue by rhadamants** [RainbowMiner/RainbowMiner#569]
It is possible add suprnova pool?
Is is possible a comment line with exchange name on coin config to remember exchange used this coin.

**Comment by RainbowMiner** [comment]
I am already working on it.

**Comment by RainbowMiner** [comment]
"comment" field added to coins.config.txt 80eb86aab870af99b242ef716d33c5214bc1581a

**Comment by RainbowMiner** [comment]
SuprNova has been added.
