### ISSUE TITLE
Enhancement : pre configured clocks for all cards

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#57]
Hey, I noticed the last update now has a oc config file. That's a step forward. Now what would be amazing is if you can pre test every miner with all the major cards to get the best AF configured when installed. Example, imagine rainbow asking the model of your card at install and automatically know what the fastest /stable clocks are and already force those for optimal undervolt mining. Just a tought to elaborate on further AF control. I find myself having to test each miner solo and find my best clock rate. Lots of work and research I know. But maybe request others to submit benchmarks to compile for your own list so you do not have to buy every card 😜
Just friendly thoughts.

**Comment by RainbowMiner** [comment]
Wondeful thoughts, in deed :) Thank you! I will start a list of well know presets.

RBM
