### ISSUE TITLE
Option for ExcludeServerConfigVars

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#571]
Add an option while setting up a new Rig to pull ExcludeServerConfigVar from server.

I setup a new machine today and it pulled over several settings that I did not want to come over. Namingly the MRR API information and EnableMinerStatus which I have disabled in ExcludeServerConfigVar. I ended up going with the defaults and it does not include these two variables. 

I have EnableMinerStatus in there because there are some machines I just dont want to show up on the monitor.

**Comment by RainbowMiner** [comment]
This is actually a super idea. I will add this.

**Comment by RainbowMiner** [comment]
Added fa27a0d1fe14eee28631895df83403b0f4e6422b
