### ISSUE TITLE
MTP Miner window shows "missing packet" for full Miner window.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#577]
MTP Miner window shows "missing packet" for full Miner window.

Nothing seen by Zergpool where the monitor said it was working.

[debug_2019-06-24.zip](https://github.com/RainbowMiner/RainbowMiner/files/3322370/debug_2019-06-24.zip)
![Screenshot_20190624-125829_TeamViewer](https://user-images.githubusercontent.com/801414/60048156-61a9a980-9680-11e9-932e-f6f69dac79bc.jpg)

**Comment by RainbowMiner** [comment]
This should be fixed with v1.1.22 of ccminermtp (in RainbowMiner release v4.3.4.4)
