### ISSUE TITLE
[Feature request] Equihash naming

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#587]
Can you add an option to change the way Equihash variants are shown on the console or the webfig? I know that Equihash24x7 is more logical than Equihash (192,7), but browsing on the web most pages uses Equihash (192,7).

**Comment by jch9678** [comment]
I have to agree with this.

**Comment by RainbowMiner** [comment]
:D Ok. I will add something.

**Comment by jch9678** [comment]
Where is EnableAlgorithmMapping?  It doesn't seem to be in the config.txt.

**Comment by RainbowMiner** [comment]
It's in release V4.3.4.9 - just restart, it should shine up.

**Comment by jch9678** [comment]
Hmmm.  I did an update and looked for it. I'll double check to see if it
updated correctly.

**Comment by RainbowMiner** [comment]
That's strange. It should have been added to the end of the config.txt.
It not: are you using client/server? If yes, the client might have pulled an older server config.
Anyway, if it really doesn't shine up, add it manually:
```
  "EnableAlgorithmMapping": "1",
```

**Comment by jch9678** [comment]
It's there now.  I just assumed it would've been added right after I updated.  I didn't realize I needed to start RM and then edit the config.  I thought I could just edit it after I manually update.

**Comment by RainbowMiner** [comment]
Good :) anyway, there is still some development ahead. The setting currently changes Equihash in the console, only.

**Comment by RainbowMiner** [comment]
I have added the new algorithm-mapping to localhost, now.
