### ISSUE TITLE
Cannot convert value, value too large for Decimal

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#588]
![image](https://user-images.githubusercontent.com/41829368/60522753-d2674c00-9ca6-11e9-8c5d-17c37924ed02.png)

**Comment by RainbowMiner** [comment]
This, in deed, is a large number! Did this error go away?

**Comment by hernandn01** [comment]
Yes it did after a few minutes, I haven't seen this error anymore

**Comment by RainbowMiner** [comment]
Ok, then it was a transmission error or wrong price from some pool API and RBM's auto-cleanup took care of it :)

**Comment by jamlazevedo** [comment]
Hi! I use zpool and i  have same error: 
![image 2019-12-10 at 12 35 04](https://user-images.githubusercontent.com/31184947/70529981-c0d57a80-1b49-11ea-9093-0e6c5a7342be.jpeg)
