### ISSUE TITLE
[Q] Use gminer for other algos

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#590]
How can I tell RainbowMiner to use gminer for other algos? I have a VEGA56 card. In the webfig for gminer I have Equihash24x5, Equihash25x5, Chuckaroo29, and Chuckaroo29s. But according to the developer, I can also mine
  - Cuckoo29 (Aeternity) (Nvidia/Amd)
  - Equihash 192,7 (Zero, Genesis) (Nvidia/Amd)
(I'm more interested in 192.7 or 24x7, as you call it). Right now RM mines 24x7 with lolminer and it's the best bet for my card. So I was wondering if gminer can do a better job.

**Comment by RainbowMiner** [comment]
I will change the Gminer module for this.
