### ISSUE TITLE
Time of Use

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#593]
Is it possible to add Time of Use to RBM?  Basically so the miner stops during high power costs. Obviously these would be times entered by the user.

**Comment by RainbowMiner** [comment]
Very good idea. Yes, I'll add it.

**Comment by RainbowMiner** [comment]
Added. It's called "scheduler", The config file is "scheduler.config.txt", but I have added it to the setup, too.
