### ISSUE TITLE
Error when going into pool selection

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#595]
Running this on Ubuntu Linux

*** RainbowMiner Configuration ***

Please choose, what to configure:

- Wallet: setup wallet addresses, worker- and username, API-keys
- Common: setup the most common RainbowMiner settings and flags
- Energycosts: setup energy consumtion values
- Selection: select which pools, miners, algorithm to use
- All: step through the full setup, configuring all
- Miners: finetune miners, add commandline arguments, penalty values and more (only for the technical savy user)
- Pools: finetune pools, add different coin wallets, penalty values and more
- Devices: finetune devices, select algorithms, coins and more
- Algorithms: finetune global settings for algorithms, penalty, minimum hasrate and more
- Coins: finetune global settings for dedicated coins, wallets, penalty, minimum hasrate and more
- OC-Profiles: create or edit overclocking profiles
- Network: API and client/server setup for multiple rigs within one network

[W]allets, [C]ommon, [E]nergycosts, [S]elections, [A]ll, [M]iners, [P]ools, [D]evices, A[l]gorithms, Co[i]ns, [O]C-Profiles, [N]etwork, E[x]it configuration and start mining [default=X]*: s

*** Selection Configuration ***

Hints (read them all! It will make entering data much easier):

- press Return to accept the defaults
- fields marked with * are mandatory
- use comma "," to separate list entries
- add new entries to a list, by adding a "+" in front of your input
- remove entries from a list, by adding a "-" in front of your input
- enter "list" or "help" to show a list of all valid entries
- enter "back" or "<" to repeat the last input
- enter "delete" to clear a non-mandatory entry
- enter "save" or "done" to end config and save changes
- enter "exit" or "cancel" to abort without any changes to the configuration

You have entered wallets for the following currencies. Consider adding some of the proposed pools:
Write-Log : Unknown goto command "Cannot bind argument to parameter 'ReferenceObject' because it is null.". You should never reach here. Please open an issue on github.com
At /home/user/RainbowMiner/Setup.psm1:1484 char:29
+ ...             Write-Log -Level Error "Unknown goto command `"$($NextSet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

You have entered wallets for the following currencies. Consider adding some of the proposed pools:
Write-Log : Unknown goto command "Cannot bind argument to parameter 'ReferenceObject' because it is null.". You should never reach here. Please open an issue on github.com
At /home/user/RainbowMiner/Setup.psm1:1484 char:29
+ ...             Write-Log -Level Error "Unknown goto command `"$($NextSet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

You have entered wallets for the following currencies. Consider adding some of the proposed pools:
Write-Log : Unknown goto command "Cannot bind argument to parameter 'ReferenceObject' because it is null.". You should never reach here. Please open an issue on github.com
At /home/user/RainbowMiner/Setup.psm1:1484 char:29
+ ...             Write-Log -Level Error "Unknown goto command `"$($NextSet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

You have entered wallets for the following currencies. Consider adding some of the proposed pools:
Write-Log : Unknown goto command "Cannot bind argument to parameter 'ReferenceObject' because it is null.". You should never reach here. Please open an issue on github.com
At /home/user/RainbowMiner/Setup.psm1:1484 char:29
+ ...             Write-Log -Level Error "Unknown goto command `"$($NextSet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

You have entered wallets for the following currencies. Consider adding some of the proposed pools:
Write-Log : Unknown goto command "Cannot bind argument to parameter 'ReferenceObject' because it is null.". You should never reach here. Please open an issue on github.com
At /home/user/RainbowMiner/Setup.psm1:1484 char:29
+ ...             Write-Log -Level Error "Unknown goto command `"$($NextSet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

You have entered wallets for the following currencies. Consider adding some of the proposed pools:
^Cuser@miningserver:~/RainbowMiner$

**Comment by RainbowMiner** [comment]
Yak! What's that. I will check it.
