### ISSUE TITLE
[Q] How to mine TRTL coin?

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#597]
How can I mine TurtleCoin in, say, MinerRocks?

**Comment by RainbowMiner** [comment]
- download the TRTL wallet, create an address (alt. use an exchange address plus evtl. payment id)
- add your TRTL wallet address to pools.config.txt, section MinerRocks
```
  "TRTL": "yourtrtladdress",
```
- add MinerRocks to PoolName in config.txt
- that should be it.

**Comment by RainbowMiner** [comment]
Additionally, you might want to pick the chance and do merged mining with LOKI:
- download the LOKI wallet, create an address (alt. use an exchange address plus evtl. payment id)
- add your LOKI wallet address to pools.config.txt in addition to the TRTL address, section MinerRocks
```
  "TRTL": "yourtrtladdress",
  "LOKI": "yourlokiaddress",
```
- now you should mine TRLT+LOKI together.

**Comment by RainbowMiner** [comment]
If you decide to use a deposit address of an exchange, you most probably will get a payment id. To use it, alongside the deposit address, add it with "." to your wallet address(es)
```
  "TRTL": "yourtrtladdress.paymentid",
  "LOKI": "yourlokiaddress.paymentid",
```

**Comment by RainbowMiner** [comment]
Coin aliases are allowed, of course. So you might want to add "TRTL" and "LOKI" to coins.config.txt and just use the "$" aliases in pools.config.txt
```
  "TRTL": "$TRTL",
  "LOKI": "$LOKI",
```
There is some nice thing about using coins.config.txt: you may use "Comment"

```
    "LOKI":  {
                   "Penalty":  0,
                   "MinHashrate":  "0",
                   "MinWorkers":  "0",
                   "MaxTimeToFind":  "0",
                   "Wallet":  "yourlokiaddress.paymentid",
                   "EnableAutoPool":  "0",
                   "PostBlockMining":  "0",
                   "Comment":  "exchange abc",
                   "MinProfitPercent":  "0"
               },
    "TRTL":  {
                   "Penalty":  0,
                   "MinHashrate":  "0",
                   "MinWorkers":  "0",
                   "MaxTimeToFind":  "0",
                   "Wallet":  "yourtrtladdress.paymentid",
                   "EnableAutoPool":  "0",
                   "PostBlockMining":  "0",
                   "Comment":  "exchange xyz",
                   "MinProfitPercent":  "0"
               },
```

**Comment by Djago** [comment]
Sas always, MANY THANKS!
