### ISSUE TITLE
Updated from RBM 4.3.4.7 to 4.3.4.8 and MiniZ Equihash24x7 then got lots of rejections on MRR.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#598]
Updated from RBM 4.3.4.7 to 4.3.4.8 and MiniZ Equihash24x7 then got lots of rejections on MRR.

My renter lost 1hr of hashing and i had to extend the rental.

Disabled MiniZ and Gminer hashes just fine.

[debug_2019-07-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/3370847/debug_2019-07-08.zip)

**Comment by RainbowMiner** [comment]
Yes, sometimes MiniZ fails to negotiate the "--pers auto" with MRR. It's eventually a renter's pool incompatibility.
