### ISSUE TITLE
NicehashV2 mining XmrigCpu CryptoNightR not seen by new platform

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#600]
NicehashV2 mining XmrigCpu CryptoNightR not seen by new platform.  It is showing up on old platform.  In the RBM console it has the 'new' in the stratum and the correct BTC address.

The stratum in the Miner window doesn't have 'new'.  And is there a way the miner window can have the BTC address at the beginning or is that the miner's issue?

[debug_2019-07-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/3388299/debug_2019-07-12.zip)

![image](https://user-images.githubusercontent.com/801414/61164873-581ca000-a4ce-11e9-9af4-d9d73247846d.png)

**Comment by RainbowMiner** [comment]
Interesting observation! Eventually Nicehash is still forwarding some hosts to the old Platform, under some condition. I will try to reproduce this.

Regarding the miner window: it is a miner issue. But Xmrig is special, since I always compile it myself before release, so I could very well change the output.

**Comment by paulpoco** [comment]
@RainbowMiner I tried manually running the Miner from a CMD line and it goes to correct V2 platform and shows the 'new' in the Miner window.  So I don't think Nicehash is forwarding some hosts to the old Platform?

![image](https://user-images.githubusercontent.com/801414/61175913-63260d80-a56c-11e9-93cc-db9262032bc2.png)

**Comment by paulpoco** [comment]
@RainbowMiner I deleted the \RainbowMinerV4.x.x.x\Bin\CPU-Xmrig folder and after it downloaded the Miner again, it is now Mining CryptoNightR to match the console window and at NicehashV2 correctly.

**Comment by RainbowMiner** [comment]
Oh, I see! You had old json config files. These are preserved during updates. In the new files, there is no longer the pool's information. I think, I should add some kind of cleanup for old json files.
