### ISSUE TITLE
Zergpool X16R gets rejected shares on both Trex and Z-enemy

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#601]
Zergpool X16R gets rejected shares on both Trex and Z-enemy.

![image](https://user-images.githubusercontent.com/801414/61176002-a6cd4700-a56d-11e9-8ce5-c86e07495187.png)

[debug_2019-07-13.zip](https://github.com/RainbowMiner/RainbowMiner/files/3389188/debug_2019-07-13.zip)

Invalid share ID on Neoscrypt too on Zergpool.

**Comment by RainbowMiner** [comment]
Oh dear, sounds like there are some shit-coins on Zergpool, currently. It's clearly a pool issue.

**Comment by paulpoco** [comment]
@rainbowminer is there a way for the Zergpool if an Algo is having lots of issues with Rejects/Invalids then don't try that Algo for a couple of hours again?

**Comment by RainbowMiner** [comment]
Actually, yes. Rainbowminer counts rejected/accepted shares, so that the watchdog should detect a rogue miner after some time.
