### ISSUE TITLE
No pools issue on some rigs

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#602]
after update , from time to time no pools issue apears

console flood with following:

Add-Member : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\_MinerStuff\RainbowMiner\Core.psm1:563 char:44
+ ... .Pools.$p | Add-Member $q @(($Session.Config.Pools.$p.$q | Select-Obj ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand

after flood stops , miner sits on:

WARNING: No pools available: check your configuration

and it doesnt go away till miner is restarted

**Comment by RainbowMiner** [comment]
That's very strange! Would you be so kind and send me a Debug file from one of those machines? (http://localhost:4000 -> click "Debug file")

**Comment by mo35** [comment]
well after upgrading to x.x.5.9 im not encountering this issue anymore

**Comment by mo35** [comment]
Unfortunately it randomly happening on totally diff rigs , i usually auto clean logs , but will try to catch some in action. 

if that helps im using only Nichehash, NicehashV2 and Zergpool.

**Comment by mo35** [comment]
meh , seems like issue was caused by unreliable zergpool apis , after excluding zergpool all seems ok
