### ISSUE TITLE
GRIN USD/Day way wrong

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#603]
After the fork profit for GRIN is way off, leading to mine it all day. But doing manual calculations shows me that the calculation is wrong.
I have a Vega56. Right now RBM says 3.781USD/Day. Entering in the pool (GrinMint) I have an estimate earning of 0.1544 GRIN/Day, or, taking the actual value from CoinGecko of 3.15USD/GRIN it's 0.48636 USD/Day. Using GrinMint calculator I get 0.2614 GRIN/Day, or 0.8261 USD/Day.
Can you correct the XXX/Day prediction?

**Comment by RainbowMiner** [comment]
You refer to the calculation of Rainbowminer when mining on GrinMint pool?

**Comment by RainbowMiner** [comment]
Oh! I found it. It has been accidentally using the price scheme for Cuckatoo31. Fixed.
