### ISSUE TITLE
Does EthashPool in RBM include https://thegrinpool.com/ ?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#604]
Does EthashPool include https://thegrinpool.com/ ?
![Screenshot_20190721-155135_Chrome](https://user-images.githubusercontent.com/801414/61598258-ad903580-abcf-11e9-965e-68a721b380cb.jpg)

**Comment by RainbowMiner** [comment]
I had this disabled, because there have been only one miner, in the beginning. It's enabled, now.

**Comment by RainbowMiner** [comment]
Use your email address as wallet
