### ISSUE TITLE
[question] Bminer

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#605]
i wanted to try latest bminer (since you updated it) , but i cant find way to enable it , it doesnt even gets downloaded (tried with clean setup with just my config file).

its not listed on my "ExcludeMinerName" list.

**Comment by mo35** [comment]
something is off in os selection part , i just did brute force variable defs and it works just fine 

#if (-not $IsWindows -and -not $IsLinux) {return}
#if (-not $IsLinux) {return}

#if ($IsLinux) {
#    $Path = ".\Bin\Equihash-BMiner\bminer"
#    $URI = "https://github.com/RainbowMiner/miner-binaries/releases/download/v15.7.3-bminer/bminer-v15.7.3-79a487c-amd64.tar.xz"
#} else {
    $Path = ".\Bin\Equihash-BMiner\bminer.exe"
    $URI = "https://github.com/RainbowMiner/miner-binaries/releases/download/v15.7.3-bminer/bminer-lite-v15.7.3-79a487c-amd64.zip"
#}

**Comment by mo35** [comment]
one more thing i also had to update ..\Data\minerinfo.json and change 

from "Bminer":[] to "Bminer":["AMD","NVIDIA"]

**Comment by mo35** [comment]
dont bother to test this version unless you after cucatoo31 (its faster than nbminer a bit , for high end cards)
cucaroo29d is borked on all nvidias with:
CUDA error DRIVER: '1' in func 'bminer::cuckoo::Cuckaroo29dSolverCudaBase::CollectEdges' line 493
Fatal cuda error in GPU 1. Terminate soon...
Miner died! It will be restarted soon...

**Comment by RainbowMiner** [comment]
Yes, that is why I have disabled Bminer for Windows, currently. It works fine on Linux.

**Comment by RainbowMiner** [comment]
Bminer newest version now works with Windows :) I have re-enabled it.
