### ISSUE TITLE
TeamRedMiner with Cuckatoo31 error

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#606]
I'm getting Failed Benchmark when trying to use it. The line that RM is using is:
teamredminer.exe -a cuckatoo31 -d 0 -o stratum+tcp://us-east-stratum.grinmint.com:3416 -u my@email/myrig -p mypass --api_listen=40900 --platform=0

What I get when I try to use it from command line is:
Unrecognized algorithm cuckatoo31 specified.

Looking at --help, it says that the algo should be:
cuckatoo31_grin

**Comment by RainbowMiner** [comment]
Oh!  Thank you. I'll fix this.

**Comment by RainbowMiner** [comment]
fixed

**Comment by Djago** [comment]
Now TRM doesn't list Cuckatoo31 as a possible algo!

**Comment by RainbowMiner** [comment]
Oh! I see. My last algorithms.json update failed. I'll fix.it

**Comment by RainbowMiner** [comment]
I have pushed the correct .\Data\algorithms.json - just update that file and you are good :)

Right-click -> Save as.. https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Data/algorithms.json

.. into folder "Data"

**Comment by Djago** [comment]
Thanks! I've used the file, but now it's not needed anymore thanks to your latest update.
