### ISSUE TITLE
loki.miner.rocks connection closed

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#607]
I'm trying to mine TRTL+LOKI in MinerRocks but I get
Pool loki.miner.rocks connection was closed by the pool.
Other coins are mined OK at MinerRocks. I know that there's a fork going on. Could this be the cause?

**Comment by RainbowMiner** [comment]
Could be, yes. I'll check.

**Comment by RainbowMiner** [comment]
Loki forked to new algorithm "RandomXL". I have added that to RainbowMiner pools - plus updated XmrigCpu to v2.99.0 beta (which allows mining RandomXL
