### ISSUE TITLE
GrinProMiner is not listed

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#608]
Hi!
I've mined in the past with GrinProMiner. I have several folders with it. But now GrinProMiner is not listed in the Miners part in the webfig. Currently I am mining with other miners with Cuckatoo31 (TRM), Chuckaroo29s (Gminer) and Cuckarood29 (lolminer) so it's not a GRIN or SWAP configuration related issue.
![image](https://user-images.githubusercontent.com/34612740/61988726-b6cc3880-affb-11e9-9bd6-ae0796be7228.png)
I'm sending the debug file just in case...
[debug_2019-07-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/3437769/debug_2019-07-26.zip)

**Comment by RainbowMiner** [comment]
In fact, I have replaced the GrinPro miner with GrinGoldMiner, since the GrinPro did not follow through the GRIN fork to Cuckarood29. The only thing: the GrinGoldMiner cannot mine SWAP (Cuckaroo29s). So, if you do want the GrinPro miner back for SWAP mining, please let me know.

**Comment by RainbowMiner** [comment]
Ok, I just re-added the GrinProMiner for SWAP mining, only.

**Comment by Djago** [comment]
I see... Last version is very old. Thanks! I'll see if at least it's good for SWAP.
