### ISSUE TITLE
[Q] bminer on AMD

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#609]
Hi!

I know bminer can mine on AMD on Windows, at least on some cards/algos. Currently it's listed on Equihash 25x5 only. Is there any way of using it on other algos?
I'm interested on Equihash 125x4 because right now lolminer is the only one I can use.

**Comment by RainbowMiner** [comment]
Bminer will not mine Equihash25x4 (125,4), neither on Nvidia nor on AMD.

**Comment by RainbowMiner** [comment]
Also, the bitter truth is, that there is in only lolminer, that mines Equihash25x4 (125,4) on AMD, currently.

**Comment by Djago** [comment]
What about ZelCash? I'm a bit confused here. On RM I have the following line:
![image](https://user-images.githubusercontent.com/34612740/62012044-6cf86500-b157-11e9-973e-3f1d5b5fa834.png)
On the Documentation page:
![image](https://user-images.githubusercontent.com/34612740/62012169-05dbb000-b159-11e9-8e07-c1f5d929bd08.png)

And on Zel page it says:
![image](https://user-images.githubusercontent.com/34612740/62012135-98c81a80-b158-11e9-84d1-d753ff25c72d.png)

Also on bminer's page:
![image](https://user-images.githubusercontent.com/34612740/62012081-ebed9d80-b157-11e9-978d-595ab76140ce.png)

From bminer's page seems that it is capable of mining ZEL, but with "Equihash 144,5". On ZEL page the text says one thing in the subtitle (125_4) and other value on the text (144,5)...
😵

**Comment by Djago** [comment]
It also seems capable of other feats;
![image](https://user-images.githubusercontent.com/34612740/62012271-86e77700-b15a-11e9-86ee-ae428106bed7.png)

**Comment by RainbowMiner** [comment]
No, bminer cannot ZEL, anymore. It's a relict on their homepage - they refer to Equihash 144,5, but this is no more valid for ZEL. ZEL needs Equihash 125,4.

Since bminer comes from Nvidia, originally, they have added only little AMD support. Even BEAM (which is Equihash 150,5) is considered experimental.
Anyway, if you want to try, I could provide you with an experimental Bminer module, with all algorithms activated for AMD. Just let me know :)

**Comment by Djago** [comment]
I have:
![image](https://user-images.githubusercontent.com/34612740/62014201-7643fa80-b174-11e9-80df-748c71558948.png)
So, it only matters (to me) if it can mine something worth it, i.e. CNr, Equihash 125,4 or 192,7, Cuckatoo31, HMQ1725... Equihash 144,5 is far down on the list, so if bminer can't mine something valuable, for me is not important. I can do it if you want to try so other miners can benefit from it.
