### ISSUE TITLE
Balloon default msi profile 2?!

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#61]
The MSI profiles are configured as below, but default MSI profile for balloon is 2.Is that really correct?
My profiles as below:
Profile 1: power 80%, core +0, mem +0
Profile 2: power 80%, core +100, mem +500
Profile 3: power 80%, core +100, mem +300
Profile 4: power 80%, core +100, mem +0
Profile 5: power 80%, core +100, mem +450

**Comment by ebojali** [comment]
Doesn't work. Added it to Trex-GTX1080Ti profile now but still profile 2 is applied. adding screenshots later.

**Comment by RainbowMiner** [comment]
If the problem still persists with the new release, please add a zip of your Config and Logs folders, so that I can analyse the problem. What you could try: setup your own custom profiles. These work much faster and safer. See documentation issue #77
