### ISSUE TITLE
Night Theme, Benchmark page has problems

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#611]
This is what happens when I try the Night theme:
![image](https://user-images.githubusercontent.com/34612740/62096833-681cd980-b25b-11e9-8676-1cd78cf7b43f.png)
Also Running Config has low contrast (text vs. background).
All other pages seems OK

**Comment by RainbowMiner** [comment]
Yes, I see. It is fixed, now.
