### ISSUE TITLE
NiceHashV2 pool using wrong wallet in config

### ISSUE THREAD

**Issue by thebeerbaron2018** [RainbowMiner/RainbowMiner#614]
Can you check the way pools.config.txt is generated for NiceHashV2 pool during the setup installation because it puts the BTC address as "$WALLET" - which I believe is the BTC address you enter first and NOT the Nicehash wallet!

**Comment by thebeerbaron2018** [comment]
Since V1 is one address and V2 is another address - you may need to temporarily add another question for "enter address" up front where you ask : BTC address, Nicehash Address (this needs to ask for V1 address and V2 address) - only until they transition over to only using the new platform.  Then the current setup of asking just the "Nicehash" address will work again provided that the $WALLET is changed in the pools.config.txt   (as a temporary fix I removed the $WALLET from the NicehashV2 pool section and replaced directly with my actual address from the new Nicehash platform)

**Comment by RainbowMiner** [comment]
Thank you! Yes, that would be very good. I will add an input.

**Comment by mo35** [comment]
also please do not enforce to use diff address for nicehash v2 , im using my old btc address just fine , and i dont plan to use nicehash btc address , nor create any logins , im just selling hashpower and they paying to old addresses w/o issues

**Comment by mo35** [comment]
also there is syntax error in nicehashv2.ps1 line 11

    [String]$StatAverage = "Minute_5"

missing "," at the end

**Comment by thebeerbaron2018** [comment]
Mo35, I didn't mean enforce a different address - just ASK for the address... so if you are withdrawing to your normal BTC address for all miners and V1 and V2 for Nicehash then you would put the same address in 3 times during the setup if that makes sense.  It's only until they end the transition period and remove V1 completely anyway.

**Comment by mo35** [comment]
Well right now there is annoying nag , that nicehash v2 needs separate btc address .. no it doesnt, if you dont want to use it , global works just fine. I can easely remove that warning from code after update , no big deal , but missing balance from v2 if using global btc address is bad choice , it should show balance no matter what btc address is used , as long as pool is selected.

**Comment by thebeerbaron2018** [comment]
mo35 - for me it didn't work but I use NH internal addresses - so during the setup it asked for my BTC address, I gave it 12345 (which is loaded into $wallet), then it asked for my Nicehash address so I gave it 56789.... then on pools I gave it Zergpool,Zpool,Nicehashv1,Nicehashv2... then BTC field in the pools.config.txt :   Zergpool > $wallet, Zpool > $wallet, Nicehashv1 > 56789, Nicehashv2 > $wallet  (which is wrong)

**Comment by RainbowMiner** [comment]
@mo35 @thebeerbaron2018 I will change the code, understood.

**Comment by RainbowMiner** [comment]
I changed the setup for Nicehash pool address from "mandatory different from global wallet" to "warn, if it is same as global wallet". Also, I fixed that syntax error, I had imported in v4.3.7.3. Balance is back again, too.
