### ISSUE TITLE
CCX balance not showing up.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#615]
CCX balance not showing up on HeroMiners.

**Comment by RainbowMiner** [comment]
Yes. It's the payment id handling with "+" which causes the trouble. I'll adapt.

**Comment by RainbowMiner** [comment]
This commit 9e380815530c9c8a175dd49bc361e5787b9ae808 should fix this.

**Comment by Yamanipanuchi** [comment]
[2019-08-13 08:38:22] Problem fetching https://turtlecoin.herominers.com/api/stats using REST: The remote name could not be resolved: 'turtlecoin.herominers.com'
[2019-08-13 10:08:30] Problem fetching https://conceal.herominers.com/api/stats using REST: The remote name could not be resolved: 'conceal.herominers.com'

These im sure are why ccx and trtl do not show up jn the balances. If i copy and paste the URLs into my browser the information comes up.

**Comment by Yamanipanuchi** [comment]
So I keep digging into this issue more and more as I have time. It looks like RBM is in fact getting the information via the API. So somewhere from there and to it actually displaying the information it gets lost. Both these wallets do have the + or . in the mining wallet. I dont know if that may be the culprit?

**Comment by RainbowMiner** [comment]
Thank you for digging. I will have a closer look on the + handling

**Comment by Yamanipanuchi** [comment]
So, I keep playing with this when I have some time. It looks like the earnings calculator that was added pick up CCX and TRTL earning. Just still no balance.
