### ISSUE TITLE
mBTC instead of BTC

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#616]
Hi!

Due to the vast differences between the values of BTC and most altcoins, using BTC in the console puts lots of 0000 on screen. Is there a way of using mBTC, μBTC or satoshis instead of BTC?

**Comment by RainbowMiner** [comment]
A very good point. Thank you! I will add a config parameter for that.

**Comment by Nickfost** [comment]
Why not MBTC? you guys must be doing it wrong :wink:

**Comment by Djago** [comment]
Actually, for Turtle coin is the other way around.
But if one day I have a profit in the order of MBTC, then PROBABLY I won't read this anymore 🤣
