### ISSUE TITLE
Scheduler not accepted during setup.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#618]
RainbowMiner can use centralized configuration files:
selected config files will be downloaded automatically, if changed on the server rig

HINT:
If specific config files for this client are needed, put them into subdirectory ".\Config\rig1" on your server

Enable automatic download of selected server config files?  (yes/no) [default=no]: yes
Enter the config files to be copied to this machine [default=config,coins,pools,algorithms,scheduler]:
The following entries are invalid (type "list" to show all valid):
scheduler

Enter the config files to be copied to this machine [default=config,coins,pools,algorithms,scheduler]:

**Comment by RainbowMiner** [comment]
Solved with commit d2f489bf878f27290c879004d9b08f98f51c3ab3
