### ISSUE TITLE
Old CPU

### ISSUE THREAD

**Issue by Horseman-usr** [RainbowMiner/RainbowMiner#619]
Hi,
please can fix:
"CPU: Intel(R) Core(TM) i3-2100 CPU @ 3.10 GHz.
The SW build requires a CPU with AES!":
CPU-CpuPower, CPU-JayDDee, CPU-OptBF, CPU-Rplant...

But CPU with AVX without AES, and I manually correct after update, the scripts in bulk (CpuPower.ps1, CpuminerJayddee.ps1, CpuminerOptBF.ps1, CpuminerOptBF.ps1) in all my worker...

**Comment by RainbowMiner** [comment]
Yes, I will have a look and fix this.

**Comment by RainbowMiner** [comment]
Could you please download [CPUtest.bat](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/CPUtest.bat) (Right-click .. save as..) into your RainbowMiner folder, start it and send me the result?

**Comment by Horseman-usr** [comment]
[CPUtest1.txt](https://github.com/RainbowMiner/RainbowMiner/files/3488595/CPUtest1.txt)
[CPUtest2.txt](https://github.com/RainbowMiner/RainbowMiner/files/3488596/CPUtest2.txt)
Done.

**Comment by RainbowMiner** [comment]
Ok, thank you. How did you correct the Cpu*.ps1 files, exactly?

**Comment by RainbowMiner** [comment]
Oh! I think I understand, what is going on. I'll fix it.

**Comment by Horseman-usr** [comment]
Yes, You understood right. THNX!
