### ISSUE TITLE
Error on start no pools available

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#62]
Would you please look into this?

![image](https://user-images.githubusercontent.com/41829368/44916120-19d12480-acf2-11e8-9a90-b706963845f3.png)

**Comment by hernandn01** [comment]
deleted pools.config.txt and let it create a new one, working fine now, not sure why it did not detect the previous file like other times, still worth looking into this, it could be a possible problem introduce at include.psm1

**Comment by RainbowMiner** [comment]
Thank you. I will have a look.

RBM
