### ISSUE TITLE
[Q] What is W shortcut for?

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#621]
I see a [W]D reset shortcut but on https://rbminer.net/documentation/ it's not explained. What does it do? It only says "resetting watchdog", but can you give more details?

**Comment by RainbowMiner** [comment]
RainbowMiner uses a watchdog feature to track all miners and pools. If a miner/pool fails for too long, the watchdog will disable for a timespan. Sometimes, especially during a trial-and-error process of setting overclocking values, it is useful to clear the watchdog. All disabled miners/pools will then be re-enabled in the next round.

**Comment by Djago** [comment]
Thanks!
