### ISSUE TITLE
NLPool problem with VerusCoin

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#623]
Hi!

I've added VRSC address to NLPool and since then I'm getting "WARNING: Pool API (NLpool) returned nothing.". I've also added the same address to ZERGPool and it seems ok. Is this a problem from NLPool? Should I disable it?

**Comment by RainbowMiner** [comment]
How did you add VRSC to NLPool, exactly?

**Comment by Djago** [comment]
I've added
"VRSC": "_myaddress_",
to the NLPool section in the pools.config.txt (and ZERG pool)

**Comment by Djago** [comment]
It's not warning me anymore!
