### ISSUE TITLE
[Req] A Wizard for adding coins?

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#624]
Hi!

Suppose I want to add XXX coin to RBM. How can I do that? Asking here, googling it, asking on discord,..., then following instructions (generate a wallet, searching what pool can I use, editing config files,...).
It would be nice to have a Wizard in RBM that you would simply say: I want to add a coin. Then RBM list the coins you can mine that are not being mined, or add the pools that you can add to the already mining coins. Select XXX coin and let RBM do 'almost' all the work of editing cofigs provided we add the wallet address (I know WE have to generate the wallet, but you could add the info needed to do that, like, go to www.xxx.io, download wallet, etc.).

**Comment by RainbowMiner** [comment]
Oh, that would be neat! I'll try to add some config page to localhost.

**Comment by RainbowMiner** [comment]
I have added some extra to the coins setup (Setup.bat -> button "I"). It will now detect coins/pools and give you the possibility to add coins quickly to pools.

**Comment by Djago** [comment]
Great! I've checked with my current VRSC config and at some point, it says: "Enter global wallet address" to what I suppose I have to enter my address. But it puzzles me that it says "optional". What happens if I don't enter any address?

**Comment by RainbowMiner** [comment]
It is possible to create "empty" wallets in coins.config.txt. Useful, if you do want to use the coin-controls on autoexchange pools, even though you do not have a wallet.

**Comment by Djago** [comment]
Thanks!
