### ISSUE TITLE
[Q] What is the difference between Currencies and Coins in RBMiner.net

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#625]
I'm looking at the charts at rbminer.net/monitoring and there's TOP 10 Currencies and TOP 10 Coins. What's the meaning of both?

**Comment by RainbowMiner** [comment]
Very well spotted :)

Currencies = payout currencies of the pools
Coins = coins, that are being mined at a pool

e.g. you might be mining "Coin" VEIL at ZergPool, but being paid with "Currency" BTC.

**Comment by Djago** [comment]
Thanks!
