### ISSUE TITLE
ethminer not working on AMD Vega56

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#626]
Hi!

ethminer is failing on benchmark phase for me. If I run the RBM command:
Bin\Ethash-Ethminer\ethminer.exe --api-port 30100 --opencl --opencl-platform 0 --opencl-devices 0 -P stratum2+tcp://**xxxxxx**%2e**yyyyyy**:**zzzzzz**@asia.ethash-hub.miningpoolhub.com:17020
I get:
 m 17:43:00 main     ethminer 0.17.1
 m 17:43:00 main     Build: windows/release
 X 17:43:00 main     No OpenCL platforms found

**Comment by RainbowMiner** [comment]
You most probably have a newer driver 19+ installed. Ethminer has a problem with that.
If you really, really want to use this miner:
https://github.com/ethereum-mining/ethminer/issues/1845#issuecomment-469861696

.. but I would stick with Claymore or Phoenix, for now.

**Comment by Djago** [comment]
> You most probably have a newer driver 19+ installed. Ethminer has a problem with that.

Yes, 19.4.2

> If you really, really want to use this miner:
> [ethereum-mining/ethminer#1845 (comment)](https://github.com/ethereum-mining/ethminer/issues/1845#issuecomment-469861696)

Not really, I was just looking at failed benchmarks and researching what was wrong with those miners

> .. but I would stick with Claymore or Phoenix, for now.

Got it. I'm on Phoenix now. Let's wait for them to fix that.
