### ISSUE TITLE
[bug] in mining mode "legacy"

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#628]
as subj says , i have couple rigs with assorted nvidias , and since they run celerons , in normal "combo" mode they had issues with cpu , so i set them on "legacy" , no parallelism with multiple miners , one per different card model.

issue: 
i noticed that when RNB is updated , rigs in "combo" mode does auto benchmark updated miners. boxes in "legacy" does not , until i manually from webui hit benchmark updated miners.

**Comment by RainbowMiner** [comment]
This should be solved, by now. Let me know, if it still happens to your legacy rigs.

**Comment by mo35** [comment]
not noticed anymore , thx
