### ISSUE TITLE
Over/underclocking doesn’t work in Ubuntu 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#630]

**Comment by RainbowMiner** [comment]
It works - but it depends on the linux version and Nvidia drivers. Not all linux/drivers support overclocking.

**Comment by Yamanipanuchi** [comment]
Running Ubuntu Server and using the Nvidia PPA repository and mine work. I did notice that some cards do not have pre set overclock's (1660 TI).

**Comment by qinapps** [comment]
I have the same problem that on linux its not working. I'm running linux headless so the first problem i have that the ocdemon is failling with: not run on tty > this mean it need to run with nohup

**Comment by RainbowMiner** [comment]
Can you help with the ocdaemon on linux headless? What would help, to make it run?

**Comment by qinapps** [comment]
I think just change by calling ocdaemo to nnohup ocdaemon

**Comment by qinapps** [comment]
I analyze a little include.psm1 
On line 4328 and folowing you set nvidia-settings
but i cant see export DISPLAY=0
for example the command should be like:
export DISPLAY=:0;nvidia-settings -a [gpu:0]/GPUMemoryTransferRateOffset[4]=800 | grep -v "^$"
next problem I see, when the GPU is under load (~100%) nvidia-settings will set MemoryTransferRate and Clock only 50%, for example: GPUMemoryTransferRateOffset[4]=800 will set the Memory Clock to +400MHz when is under 100% Gpu load (when GPU have no load > Memory clock will be set to 800MHz

This is a well known bug in nvidia-settings, but never fixed and I think never will
So when I log in remotely with the same user at the RMB is running I dont need the ocdaemon

**Comment by RainbowMiner** [comment]
It should be solved, by now :)
