### ISSUE TITLE
Docs for amd Ubuntu 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#632]

**Comment by RainbowMiner** [comment]
I will need help on that, since I do not have any AMD gpus.

**Comment by Yamanipanuchi** [comment]
I used these instructions when I did it. It worked, And it was much more simple then I thought. I spent more time thinking it was REALLY complicated.

https://www.amd.com/en/support/kb/faq/gpu-635

Quick search and I was able to find a PPA setup for Ubuntu also, But I never actually used it.

**Comment by Nickfost** [comment]
re : Quick search and I was able to find a PPA setup for Ubuntu also, But I never actually used it.

Would like to see this

**Comment by Nickfost** [comment]
I worked on this some more.

**Comment by RainbowMiner** [comment]
Thank you! Merged.

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
