### ISSUE TITLE
MiniZ 1.5p - Beam not working on New Nicehash and 1060 3GB

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#633]
![image](https://user-images.githubusercontent.com/41829368/62989918-3c772300-be07-11e9-915e-fc9811fe5b1b.png)

**Comment by RainbowMiner** [comment]
Do you eventually remember, if the prior version mined Beam on that Gpu?

**Comment by RainbowMiner** [comment]
I have updated the MiniZ miner module, so that it now no longer starts BEAM on <4GB GPU on Windows10.

**Comment by hernandn01** [comment]
I don't think it ever mined Beam on 3GB, thanks
