### ISSUE TITLE
MiniZ is not reporting hashrate Beam2 New Nicehash

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#636]
![image](https://user-images.githubusercontent.com/41829368/63128954-8a109e80-bf73-11e9-9739-8c77e348f78d.png)

**Comment by hernandn01** [comment]
![image](https://user-images.githubusercontent.com/41829368/63129057-ce9c3a00-bf73-11e9-8e7e-6550ed11a4e9.png)

**Comment by RainbowMiner** [comment]
Too bad. Thank you for reporting. I will check with the devs.

**Comment by RainbowMiner** [comment]
Fixed. It didn't like pers auto on Nicehash.

**Comment by hernandn01** [comment]
yes it did, thanks
