### ISSUE TITLE
Only CPU available. Ubuntu 18.04 AMD Cards 

### ISSUE THREAD

**Issue by RickyJia2018** [RainbowMiner/RainbowMiner#637]
At this step:
the devices, you want to use for mining. Valid descriptors are: gpu, cpu, nvidia, amd (RainbowMiner will show you, which devices are available on your machine) or use your device names (without spaces, without leading geforce): gtx1070, gtx1080ti ..

I can only chose cpu. WHY??     using AMD RX580 and Ubuntu
And gputest.sh shows: Coud not execute nvidia-smi.      I don't have nvidia card why use nvidia-smi

**Comment by RainbowMiner** [comment]
Please try to follow this documentation to install AMD pro driver plus the ROCm component. RainbowMiner needs OpenCl to access the Gpu data.
https://www.amd.com/en/support/kb/faq/gpu-635
