### ISSUE TITLE
Profitability is Ignored

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#639]
Every once in a while I will catch this machine ignoring profitability and it mines by alphabetical order of algorithm.  The powershell window sorts the algorithms alphabetically like it's benchmarking but it's not benchmarking.  

Could this be because I have minimum mining time around 3 hours (I think) and autobenchmark set up.  So when it finishes benchmarking the updated algo or miner, rm sticks with that algo for 3 hours until it switches?
[debug_2019-08-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/3522393/debug_2019-08-20.zip)

**Comment by RainbowMiner** [comment]
That could actually happen, yes. I will fix this in release v4.4.0.1

**Comment by jch9678** [comment]
I don't believe this is fixed.  My machine is stuck mining Argon2Chukwa on 4.4.1.7 while 4.4.1.9 has been released.  It is set to auto update and autobenchmark.
[debug_2019-09-10.zip](https://github.com/RainbowMiner/RainbowMiner/files/3596421/debug_2019-09-10.zip)
