### ISSUE TITLE
Merged Mining not working ARQ+TRTL (Or any other's)

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#640]
[debug_2019-08-23.zip](https://github.com/RainbowMiner/RainbowMiner/files/3535024/debug_2019-08-23.zip)

I've checked the config countless times over the past few days. Cant seem to see why Merged Mining is not working. Its not just ARQ+TRTL, But that is the one I am focusing on.

**Comment by RainbowMiner** [comment]
Thank you for checking. I will recheck this.

**Comment by RainbowMiner** [comment]
Ok, I have found the reason for that. It should be fixed with release v4.4.0.2
