### ISSUE TITLE
Bring back unpaid balance on NicehashV2

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#648]
Paid Balance is showing on NicehashV2, thanks. Unpaid balance is not showing anymore. I had to create a new API key with more rights for the Paid Balance to show. Am I missing something? Can you bring the two values like it was on old Nicehash?

**Comment by RainbowMiner** [comment]
Currently, it's a combined value (paid + unpaid). But yes, I can bring this back, if you like. Just let me know.
