### ISSUE TITLE
Issue: Excavator is not connecting or mining cryptonightV7

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#65]
Not sure if it matters since excavator is not really ever worth mining cryptonightv7 but after your latest update it decided to bench. Here is the error. I don't really use excavator but should look into excluding algos that are not worth mining on it.

I currently just excluded excavator for now in config.

![image](https://user-images.githubusercontent.com/42227809/44922975-bb10a880-acfb-11e8-8e53-9a1a6d3b5bfc.png)

**Comment by RainbowMiner** [comment]
Maybe there has been an issue with NiceHash. I will find out.

RBM

**Comment by RainbowMiner** [comment]
It was a nicehash problem, I think. Excavator is connecting now. At least for me.

RBM
