### ISSUE TITLE
incorrect nanominer(gpu) log

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [RainbowMiner/RainbowMiner#651]
Nanominer ordinary log going into file named with 'err.txt'

rbm 4.4.0.5, ubuntu, amd gpu
[Nanominer-GPU#00-53400_2019-08-28_10-05-28-err.txt](https://github.com/RainbowMiner/RainbowMiner/files/3552390/Nanominer-GPU.00-53400_2019-08-28_10-05-28-err.txt)

Edit: added attachments, but 0-byte file won't attach.

**Comment by RainbowMiner** [comment]
Thank you for reporting this!

**Comment by RainbowMiner** [comment]
I have moved the miner calls to ocdaemon (they all run as root now, no matter how you start RainbowMiner) - both output streams will now be redirected into one txt file, only.
