### ISSUE TITLE
No miners under Active Miners page

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#655]
A few releases ago I noticed that there are no local miners showing in dashboard page only the remote miners are shown. There are no miners showing on the Active Miners page too. Currently running 4.4.0.6

![image](https://user-images.githubusercontent.com/41829368/63986537-8dd31380-ca91-11e9-89ba-6f9b43d5c534.png)

![image](https://user-images.githubusercontent.com/41829368/63986661-32555580-ca92-11e9-8014-54b72f74c62a.png)

![image](https://user-images.githubusercontent.com/41829368/63986737-83fde000-ca92-11e9-924d-c415082a6cb7.png)

**Comment by RainbowMiner** [comment]
That's probably a javascript issue. Could you please click http://localhost:4000/activeminers and send me the result?

**Comment by hernandn01** [comment]
[activeminers.txt](https://github.com/RainbowMiner/RainbowMiner/files/3559707/activeminers.txt)
here you go

**Comment by RainbowMiner** [comment]
Super, thank you. Which browser do you use? Chrome, FireFox, Edge or different?

**Comment by hernandn01** [comment]
I use chrome, just now testing on IE and it is just loading but not finishing
![image](https://user-images.githubusercontent.com/41829368/64018370-7f184b00-cae9-11e9-9671-c0054e6a76b6.png)

**Comment by RainbowMiner** [comment]
I have thrown that file into RainbowMiner and my Google Chrome just displays all correctly. Weird.

![image](https://user-images.githubusercontent.com/39437538/64018344-7dbc4200-cb2c-11e9-961b-0b51da7bfe02.png)

**Comment by hernandn01** [comment]
IE just finished, the same
![image](https://user-images.githubusercontent.com/41829368/64018488-cd2d4e80-cae9-11e9-85df-136ea4b8f7ca.png)

**Comment by RainbowMiner** [comment]
Ok, let's try the following:
- use Chrome, press Ctrl-Shift-I (or right-click "Inspect..").
- Click on "Console"
- Now (re)load the Active Miners page
- are there any Javascript errors? If yes, please send me.

**Comment by hernandn01** [comment]
Edge returned much faster but the same
![image](https://user-images.githubusercontent.com/41829368/64018592-12ea1700-caea-11e9-9180-05d1674ebb45.png)

**Comment by RainbowMiner** [comment]
This is the expected Console result on Chrome:
![image](https://user-images.githubusercontent.com/39437538/64018629-3d10f880-cb2d-11e9-8bd3-f64c30321c0b.png)

**Comment by hernandn01** [comment]
one error, this happens too from time to time
![image](https://user-images.githubusercontent.com/41829368/64018759-8e4bc880-caea-11e9-9a57-87af7aab3998.png)

![image](https://user-images.githubusercontent.com/41829368/64018785-999ef400-caea-11e9-8b13-42431782bf23.png)

**Comment by hernandn01** [comment]
reload by itself, no further errors
![image](https://user-images.githubusercontent.com/41829368/64018968-23e75800-caeb-11e9-804b-18b0f7c95c1a.png)

**Comment by hernandn01** [comment]
there is one message
![image](https://user-images.githubusercontent.com/41829368/64019295-036bcd80-caec-11e9-9305-b70ebe4e92b1.png)

**Comment by hernandn01** [comment]
Clicked on Dashboard and there are these errors
![image](https://user-images.githubusercontent.com/41829368/64019446-6b221880-caec-11e9-9df8-4c60d1c51271.png)
![image](https://user-images.githubusercontent.com/41829368/64019470-7aa16180-caec-11e9-9fb1-2c94fa426636.png)
![image](https://user-images.githubusercontent.com/41829368/64019492-8b51d780-caec-11e9-82e3-bca70dab93c1.png)

**Comment by hernandn01** [comment]
clicked back on Active Miners, same errors
![image](https://user-images.githubusercontent.com/41829368/64019713-2185fd80-caed-11e9-9338-c8727773958e.png)
![image](https://user-images.githubusercontent.com/41829368/64019728-2a76cf00-caed-11e9-944b-c051bd11feef.png)
![image](https://user-images.githubusercontent.com/41829368/64019742-3367a080-caed-11e9-94a1-7e2e78024852.png)
![image](https://user-images.githubusercontent.com/41829368/64019755-3e223580-caed-11e9-8017-37c624f419c3.png)

**Comment by RainbowMiner** [comment]
Thank you for looking this up. I think, it all comes down to a timing issue. I'll check the API modules, if I can squeeze out some more speed.

**Comment by hernandn01** [comment]
thanks, it does appear to be a timing issue, this was collected after a while
![image](https://user-images.githubusercontent.com/41829368/64022603-d1f70000-caf3-11e9-8620-444e71a79efd.png)

**Comment by hernandn01** [comment]
apply commit for API.psm1, it is working now for Active Miners, very fast response. I cannot see current mining on Dashboard still
![image](https://user-images.githubusercontent.com/41829368/64031913-a598af00-cb06-11e9-8010-58e4845f364e.png)
![image](https://user-images.githubusercontent.com/41829368/64031948-b812e880-cb06-11e9-83f0-474c56c058f3.png)

**Comment by RainbowMiner** [comment]
Super :) Could you please now do the same Ctrl+Shift+I "Inspect" thing on the Dashboard page? Let's see, where the problem is, there.

**Comment by hernandn01** [comment]
![image](https://user-images.githubusercontent.com/41829368/64050688-11464080-cb36-11e9-81ee-c84ed5ec614a.png)

**Comment by RainbowMiner** [comment]
All calls should be pretty fast. Could you try the following pages and see, if they come up quick or slow?

http://localhost:4000/runningminers?sort=Profit&order=desc&_=1567198844627
http://localhost:4000/remoteminers?sort=Profit&order=desc&_=1567199067413
http://localhost:4000/balances?add_total=1&add_btc=1
http://localhost:4000/currentprofit

**Comment by hernandn01** [comment]
all 4 calls are superfast

**Comment by RainbowMiner** [comment]
So, could you please send me the result of http://localhost:4000/runningminers?sort=Profit&order=desc&_=1567198844627 ?

**Comment by RainbowMiner** [comment]
Oh!! I have an idea. Please click on the "Running Miners on Worker1", once.

**Comment by hernandn01** [comment]
there they are, it doesn't appear that that text was clickable
![image](https://user-images.githubusercontent.com/41829368/64052132-a4817500-cb3a-11e9-947f-cfb7fd79e7b6.png)

**Comment by RainbowMiner** [comment]
👍 sorry. Yes, I have made all headlines on the Dashboard page clickable. The state will be stored in a cookie

**Comment by hernandn01** [comment]
I can see that now, sorry for the inconvenience
