### ISSUE TITLE
Config menu errors (fresh install; bare config)

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [RainbowMiner/RainbowMiner#656]
I started working on documenting the RBM menu system (see #652.) And have encountered error messages. So far, it's just this M[r]r error, but maybe there are more and they will be added to this issue if/as they come up.

MRR had its basic config done in the install+start script. mrr.config.txt could have been created at that time, even if left an undefined skeleton. 

```
[R]igs, [C]reate missing, [U]pdate prices, E[x]it MRR config [default=X]*: r
 
Get-Content : Cannot find path '/home/larry/RainbowMiner/Config/mrr.config.txt' because it does not exist.
At /home/larry/RainbowMiner/Setup.psm1:2991 char:42
+ ...             $MRRActual = Get-Content $ConfigFiles["MRR"].Path | Conve ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (/home/larry/Rainbow\u2026nfig/mrr.config.txt:String) [Get-Content], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
Which algorithm do you want to configure? (leave empty to end algorithm config):
```

![RBM-Mrr-Rigs error](https://user-images.githubusercontent.com/7605896/64052426-de4a7f80-cb2a-11e9-9ca7-32883109ae9a.png)

Probably the easiest thing to do is to add an `if not "pathto/mr.config.txt" then touch "pathto/mrr.config.txt"` (however pwsh handles this) before attempting to get the content or edit it. That reduces the creation of empty config files during the first-run script. But, for many users, it might be nice to have a skeleton file created for entering the values by hand.

Also, mrr.config.txt is completely undocumented in the README.

MRR *does* have an entry in pools.config.txt, though. Should this script be looking to edit MRR there?

**Comment by RainbowMiner** [comment]
Oh! I see. Please ignore this MRR section, for now. It is work in progress (and I have unintentionally added the selection to the main menu).

**Comment by ParaplegicRacehorse** [comment]
Okay. Should I then file separate issues for non-MRR errors, *if* any come up?

**Comment by RainbowMiner** [comment]
Yes, that would be great.

**Comment by RainbowMiner** [comment]
The MRR module will be ready, soon. I think, we will need to write an own documentation for that.

**Comment by ParaplegicRacehorse** [comment]
Okay. Closing issue, for now, then. Any further errors I encounter, if any, will get new issues.
