### ISSUE TITLE
Pools menu, edit username

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [RainbowMiner/RainbowMiner#657]
While trying to edit username for miningpoolhub, I achieved the following error:

```
Write-Log : Unknown goto command "The regular expression pattern [^A-Z0-9\-\_]+ is not valid.". You should never reach here. Please open an issue on github.com
At /home/larry/RainbowMiner/Setup.psm1:2159 char:41
+ ...             Write-Log -Level Error "Unknown goto command `"$($NextSet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
```

Current username, after initial system config, is 'parplegicracehorsegmailcom' and I tried to fully punctuate with all the dots and @s of an email address. Then tried accepting default again, then tried rewriting existing default without dots and @s and error remained.

Now pwsh and/or the RBM script(s) are stuck in a loop and I don't know how to kill it. The usual linux C-c and C-x don't seems to work for powershell.

**Comment by RainbowMiner** [comment]
Thank you! I fixed this.
