### ISSUE TITLE
Enhancement: Add miner support for EWBF V5

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#66]
Please add support for latest miners ;-)

https://mega.nz/#F!fsAlmZQS!CwVgFfBDduQI-CbwVkUEpQ

**Comment by RainbowMiner** [comment]
Hi, Ewbf v0.5 is already part of the game. Enable it by adding algorithm equihash1445 (=equihash24x5), equihash1927 (=equihash24x7) and equihash965 (=equihash16x5). It also supports --pers=auto for ZergPool, AION, BTG, BTCZ, SAFE, XSG, ZEL and ZER.

RBM
