### ISSUE TITLE
stuck in weird state

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#662]
ive found this system stuck in this state quite a few times lately.

gfx804 (GPU#00)
===============
Status: LOCKED to HashVault-CryptoNightConceal, HashVault-RandomXL (press L to unlock)

   Status: Running

Last Speed Active      Started Miner  Algorithm     Coin    Device Power Command
---------- ------      ------- -----  ---------     ----    ------ ----- -------
    0  H/s 00d/00h/01m 4 Times Gminer EquihashR25x4 Zelcash gfx804 0W    Bin\GPU-Gminer\miner.exe --api 32900 --devices 0 --server zel.2miners.com --port 9090 --user
                                                                         t1LYQndTRXbWh6WzBJXRduUMax2eFtZgeoA.7010 --pass x --pers ZelProof --cuda 0 --opencl 1
                                                                         --watchdog 0 --pec 0 --nvml 0 --algo 125_4

I have the system locked, but its nit locked on what it was locked on.
[debug_2019-09-01.zip](https://github.com/RainbowMiner/RainbowMiner/files/3563965/debug_2019-09-01.zip)

**Comment by RainbowMiner** [comment]
Intersting! I'll check this. Eventually it's a postblockmining thing.

**Comment by Yamanipanuchi** [comment]
hmmm i have all post block mining set to zero. ill guess i should shut it off all together.

**Comment by Yamanipanuchi** [comment]
Re-installed from scratch and it seems to be working. I might have had a typo in the config.
