### ISSUE TITLE
Runaway memory?

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [RainbowMiner/RainbowMiner#664]
RainbowMiner 4.4.1.5
Ubuntu 18.04 (linux kernel 5.20)
Intel i7-6700K
AMD Radeon R9 390X (amdgpu-pro-19.30-855429-ubuntu-18.04)
16GB hardware RAM; 16GB swap_file_ instead of partition

I came back to the rig after two days away, while it had been running unattended, and found it unresponsive (using it also as a desktop [display is onboard video while GPU is --headless]). I pulled up the ever-useful `htop` and found RainbowMiner using up ~~all~~ most of my RAM.

This screenshot of htop is telling: 
![Screenshot_2019-09-08_07-42-16](https://user-images.githubusercontent.com/7605896/64490921-9dc7c180-d20e-11e9-9a27-d82431136d2a.png)

This is RBM 4.4.1.5 hashing GPU-Equihash(192,7) and CPU-YespowerR16 on Ubuntu 18.04; latest kernel, latest amdgpu-pro. I initially noticed it and began troubleshooting while RBM was driving the GPU with Ethash. I would have to check the logs to determine which miners running, though. The offending process is

```
pwsh -ExecutionPolicy bypass -Command & {./RainbowMiner.ps1 -configfile ./Config/config.txt; exit $lastexitcode}
```

Logs attached.
[RBM-Logs_20190908-0800.tar.gz](https://github.com/RainbowMiner/RainbowMiner/files/3587767/RBM-Logs_20190908-0800.tar.gz)

Hmm. As an afterthough.... I had left Firefox running with an RBM localhost tab open. Firefox said a script had stalled the page and would I like to kill it. Well, one of the first parts of troublehsooting responsiveness is to kill all processes known to be RAM-hungry, like Firefox. However, the screenshot is from several minutes after killing FF but before restarting RBM (with `X` at running menu; `./start.sh` back in system shell). After restart, RBM processes are back to where I have seen them in the past.

This was my first time attempting to run RBM for more than a few hours between restarts. I'm still trying to find out if I can ever get the rig to run stable. Several miners crash reliably, routinely, every time they try to run (No, I have not yet tried running them outside the RBM shell. Yes, that's coming, but it's low priority.)

**Comment by RainbowMiner** [comment]
Thank you for reporting!
I will scramble through the logs and try to find out, what has happened.
Regarding crashing miners: eventually update to 4.4.1.6 and re-run install.sh, that could solve some of the miner's non-starting issue.

**Comment by ParaplegicRacehorse** [comment]
##### Update:
RBM is back to running as reliably as it had previously done. The 4.4.1.6 upgrade didn't seem to have anything in it that would affect this issue (though maybe the stability of one or two miners. YTBD)

##### Correction:
Linux kernel version is 5.0.0-27

##### Suspicions (re: crashing GPU miners)
Having poked through various internet forums and looked at what's on offer from the likes of HiveOS, MinerstatOS and PIMP....

The 'Hawaii' line of GPUs from AMD (R9- series) is not supported since driver version 18.40, linux kernel 4.15. This, in spite of claims of AMD in the driver documentation; and the fact that several older, pre-R9 series, cards ARE supported in the latest driver+kernel combinations (including ROCm, see next); or claim to be.

Radeon OpenCompute (ROCm), the separate open source project, was removed from the main amdgpu driver set some time between v18.40 and v19.30. It is reported to be get-working-able on Hawaii cards with driver v19.30 by:
- manually patching some kernel modules,
- praying to Ra, on a *night* when
--- a supertide, local to you, coincides with a blue-moon,
--- the date + time (YYYY - DD - ((mm / hh) * ss) + MM) is prime and a factor of 37,
- and sacrificing two young ducklings while singing Weird Al Yankovic's "Theme from Rocky XIII" in a macho falsetto and hopping up and down on one arm,

Don't ask how these details were discovered. It's a whole series of harrowing tales of daring-do. :stuck_out_tongue_winking_eye: 

That is to say... ROCm basically doesn't work on these cards with recent kernels and drivers. :)

**Comment by RainbowMiner** [comment]
Do you have OCprofiles enabled?

**Comment by ParaplegicRacehorse** [comment]
No OCProfiles and no MSI Afterburner.
However, I recall RBM complaining that OCDaemon isn't running (4.4.1.5. I don't know about current 4.4.1.7 since RBM updated overnight and I haven't restarted it).
config.txt has these settings, regarding overclocking:
```
"MSIAprofile": 0,
"EnableOCProfiles": "0",
"EnableOCVoltage": "0",
```

**Comment by RainbowMiner** [comment]
This issue should be solved, by now.
