### ISSUE TITLE
[Headsup-Warning] Nvidia higher than 431.60 + Trex + lowend CPU

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#665]
If you using lowend CPU, you will have issues , RB will get stuck on "starting next run" so on, basicaly trex will become unusable if you get past 431.60 on weak CPU. Spent quite some time trying to figure out whats happening , using DDU/rolling drivers back solves issue.

**Comment by RainbowMiner** [comment]
Trex has published a fixed version (v0.14.6) - it is part of RainbowMiner v4.4.4.3
