### ISSUE TITLE
Issue: Mining on pools that are not in config file.

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#666]
I just looked at the monitor and noticed that my rigs occasionally mine on pools that are not in the config file. Any ideas why this is happening?
![image](https://user-images.githubusercontent.com/42227809/64495114-7bec3000-d24a-11e9-8d63-74949ea61958.png)

**Comment by Byrd1083** [comment]
I just hit restart and now the problem is gone. However, it was an issue before.

**Comment by Byrd1083** [comment]
[RainbowMiner_2019-09-08.txt](https://github.com/RainbowMiner/RainbowMiner/files/3588112/RainbowMiner_2019-09-08.txt)
[Activity_2019-09-08.txt](https://github.com/RainbowMiner/RainbowMiner/files/3588113/Activity_2019-09-08.txt)
[errors_2019-09-08.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/3588114/errors_2019-09-08.asyncloader.txt)

**Comment by RainbowMiner** [comment]
That was my donation fee mining round. I have setup Nicehash for that.
