### ISSUE TITLE
\RainbowMinerV4.4.2.1_win\IncludesLinux\lib' because it does not exist.  (Windows 10)

### ISSUE THREAD

**Issue by yellow-dragon** [RainbowMiner/RainbowMiner#669]
I run on win 10, but see error Linux: "\RainbowMinerV4.4.2.1_win\IncludesLinux\lib' because it does not exist."

Loading miner modules ..
Selecting best miners ..
Starting mining operation ..
Resolve-Path : Cannot find path 'D:\0\RainbowMinerV4.4.2.1_win\IncludesLinux\lib' because it does not exist.
At D:\0\RainbowMinerV4.4.2.1_win\Include.psm1:1745 char:86
+ ... {"/opt/rainbowminer/lib"} else {(Resolve-Path ".\IncludesLinux\lib")}
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\0\RainbowMin...cludesLinux\lib:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

**Comment by RainbowMiner** [comment]
Oh, I see! Thank you for reporting this. It should be fixed with v4.4.2.2
