### ISSUE TITLE
Enhancement: Remove individual miner donation

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#67]
Is there a way to remove all miners donations or set them to 0? I would rather you get the donation ;-)

I realize there are a few miners that are locked and can not be changed.

**Comment by Byrd1083** [comment]
I realize there are a few miners that are locked and can not be changed.

**Comment by RainbowMiner** [comment]
Thanks a lot :D - I will scan through the relevant miners and look, what I can do.

RBM

**Comment by RainbowMiner** [comment]
I re-compiled FireIce / XMR-Stak with 0% developer fee in it. Included in release v3.8.6.5 and up.
For mining without RainbowMiner, it can be downloaded from here: https://github.com/RainbowMiner/xmr-stak/releases
