### ISSUE TITLE
Error during balances.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#670]
Getting this error when retrieving balances.

Finished waiting - starting next run
Cannot convert value "2019-09-15T01:09:48Z" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\RainbowMiner\Pools\HashVault.ps1:87 char:34
+ ... int]$($(if ($blocks_measure.Count -gt 1 -and ($blocks_measure.Maximum ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger

**Comment by RainbowMiner** [comment]
Wow, that value should be of type int32, actually. Which currency are you mining on this pool?

**Comment by Yamanipanuchi** [comment]
I have since switched back to HeroMiners, But below is that I have set to mine on HashVault when I was mining there.

    "LOKI": "$LOKI",
    "LOKI-Params": "",
    "WOW": "$WOW",
    "WOW-Params": "",
    "TRTL": "$TRTL",
    "TRTL-Params": "",
