### ISSUE TITLE
Low profit on 1080ti

### ISSUE THREAD

**Issue by gorilza** [RainbowMiner/RainbowMiner#672]
For 15 days profit from the card at 0.44 usd. While all this time were given 3 1080 ti given the electricity profit is not less than 2 usd.

**Comment by RainbowMiner** [comment]
Which pool(s) have you been mining?

**Comment by gorilza** [comment]
NLPool 99% time

**Comment by Byrd1083** [comment]
I average $0.50 a day with one 1080ti 11gb right now so you sound pretty close.

**Comment by gorilza** [comment]
Now Yes, but all these 15 days profit in web and in RBM console was not lower than 2$, and even 3 $. Which is somewhat more than$0.5. Perhaps this is already solved in 4.4.2.4 "update pool NLpool: calculate down equihash bc. wrong estimates"

**Comment by RainbowMiner** [comment]
It turned out, that the NLpool reports very much different profit numbers for the Equihash algorithm family, on their API, compared to the other pools. I have now tuned it down to levels, that should match the actual profit.

**Comment by Byrd1083** [comment]
Seems that before you did the update, NLPool was always being calculated as most profitable almost on all algos. Now after update, NLpool does not even show up on the list as if Zergpool, Nicehashv2, and miningpoolhub is most profitable. Just to verify is this true now?

**Comment by RainbowMiner** [comment]
That is very possible. I have included a new feature, that keeps track on the actual profit vs. estimated profit, for each algorithm/pool and applies penalties, automatically.

I'll look up the diff level question.
