### ISSUE TITLE
Error log growing to unmanageable sizes.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#673]
I keep running out of disk space on my Server system, I have no confirmed this happening on others. When I look in the log folder I find muti 100MB or even GB log files. 

user@miningserver:~/RainbowMiner/Logs$ ls -lh
total 5.6G
-rwxrwxrwx 1 root root  537 Sep 18 11:59 7z-console.log
-rwxrwxrwx 1 root root    0 Sep 18 11:59 7z-error.log
-rwxrwxrwx 1 root root  112 Sep 18 11:59 autoupdate.txt
-rw-r--r-- 1 root root 142M Sep 17 23:29 errors_2019-09-17.api.txt
-rw-r--r-- 1 root root 5.3K Sep 17 23:49 errors_2019-09-17.asyncloader.txt
-rw-r--r-- 1 root root 3.9M Sep 18 23:59 errors_2019-09-18.api.txt
-rw-r--r-- 1 root root 3.4K Sep 18 23:33 errors_2019-09-18.asyncloader.txt
-rw-r--r-- 1 root root 356M Sep 19 23:59 errors_2019-09-19.api.txt
-rw-r--r-- 1 root root 5.3K Sep 19 23:46 errors_2019-09-19.asyncloader.txt
-rw-r--r-- 1 root root 133M Sep 20 23:59 errors_2019-09-20.api.txt
-rw-r--r-- 1 root root 5.2K Sep 20 23:46 errors_2019-09-20.asyncloader.txt
-rw-r--r-- 1 root root 986M Sep 21 23:59 errors_2019-09-21.api.txt
-rw-r--r-- 1 root root 3.6K Sep 21 23:20 errors_2019-09-21.asyncloader.txt
-rw-r--r-- 1 root root 314M Sep 17 22:57 RainbowMiner_2019-09-16_23-46-44.txt
-rw-r--r-- 1 root root  68M Sep 18 11:59 RainbowMiner_2019-09-17_22-57-30.txt
-rw-r--r-- 1 root root 118M Sep 17 23:59 RainbowMiner_2019-09-17.txt
-rw-r--r-- 1 root root 728M Sep 19 18:59 RainbowMiner_2019-09-18_11-59-33.txt
-rw-r--r-- 1 root root  50M Sep 18 23:59 RainbowMiner_2019-09-18.txt
-rw-r--r-- 1 root root  37M Sep 20 02:48 RainbowMiner_2019-09-19_19-10-27.txt
-rw-r--r-- 1 root root 1.8K Sep 19 21:14 RainbowMiner_2019-09-19_21-14-26.txt
-rw-r--r-- 1 root root 216M Sep 19 23:59 RainbowMiner_2019-09-19.txt
-rw-r--r-- 1 root root 2.0G Sep 21 23:59 RainbowMiner_2019-09-20_02-49-27.txt
-rw-r--r-- 1 root root 115M Sep 20 23:59 RainbowMiner_2019-09-20.txt
-rw-r--r-- 1 root root 505M Sep 21 23:59 RainbowMiner_2019-09-21.txt
-rw-r--r-- 1 root root 306K Sep 22 00:14 RainbowMiner_2019-09-22_00-09-55.txt
-rw-r--r-- 1 root root 9.7K Sep 22 00:14 RainbowMiner_2019-09-22.txt
-rw-rw-r-- 1 user user 6.9K Aug  1 03:06 Setup_2019-08-01_03-06-01.txt
-rw-r--r-- 1 root root 8.7K Sep 19 21:20 Setup_2019-09-19_21-16-01.txt
-rw-r--r-- 1 root root 2.5K Sep 19 21:21 Setup_2019-09-19_21-21-04.txt
-rw-r--r-- 1 root root 8.7K Sep 20 03:15 Setup_2019-09-20_03-14-49.txt
-rwxrwxrwx 1 root root  120 Sep 22 00:13 timerpools.json
user@miningserver:~/RainbowMiner/Logs$

This is what it looks like in errors_2019-09-17.api.txt

OKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDX                                                                                                              HVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOW                                                                                                              WOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWBEAMXZCZ                                                                                                              ELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOW&tsyms=BTC&extraParams=ht                                                                                                              tps://rbminer.net" to type "System.Uri". Error: "Invalid URI: The Uri string is too long."
At /home/user/RainbowMiner/Include.psm1:5916 char:27
+         Invoke-RestMethod $RequestUrl -UseBasicParsing -UserAgent $ua ...
+                           ~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Invoke-RestMethod], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : Cannot bind parameter 'Uri'. Cannot convert value "https://min-api.cryptocompare.com/data/pricemulti?fsyms=WOWBEAMXZCZELXWPWOWLOKITRTLARQCCXI                                                                                                              RDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOW                                                                                                              WOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWO                                                                                                              WBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAM                                                                                                              XZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXW                                                                                                              PWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWL                                                                                                              OKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLA                                                                                                              RQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRD                                                                                                              XHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSI                                                                                                              NRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWW                                                                                                              OWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOW                                                                                                              WOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBE                                                                                                              AMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZC                                                                                                              ZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLO                                                                                                              KITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLAR                                                                                                              QCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXI                                                                                                              RDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSIN                                                                                                              RVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWO                                                                                                              WWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWW                                                                                                              OWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOW                                                                                                              WOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELX                                                                                                              WPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOW                                                                                                              LOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCX                                                                                                              IRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRV                                                                                                              NWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWW                                                                                                              OWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZE                                                                                                              LXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKI                                                                                                              TRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVX                                                                                                              LAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOW                                                                                                              WOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWO                                                                                                              WWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOW                                                                                                              LOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCX                                                                                                              IRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRV                                                                                                              NWOWWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWW                                                                                                              OWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXW                                                                                                              PWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIR                                                                                                              DXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWW                                                                                                              OWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWBEAMXZ                                                                                                              CZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLAR                                                                                                              QCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINR                                                                                                              VNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOW                                                                                                              WOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPW                                                                                                              OWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVX                                                                                                              LAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOW                                                                                                              WOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMX                                                                                                              ZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITRTLARQCCXIRDXHVXLAXMRSINRVNWOWWOWWOWWOWWOWWOWWOWWOWBEAMXZCZELXWPWOWLOKITR

**Comment by RainbowMiner** [comment]
Wow, that's a weird one! Which version of RainbowMiner are you running?

**Comment by Yamanipanuchi** [comment]
Current, i run everything with auto update. 4.4.2.5

**Comment by RainbowMiner** [comment]
Are the Clients running linux or Windows?

**Comment by RainbowMiner** [comment]
Did this actually disappear, after the last release?

**Comment by Yamanipanuchi** [comment]
Just looked in the Error API log for today and it looks as if it is still there.

Log file looks smaller so far though.

user@miningserver:~/RainbowMiner$ ls -lh Logs/
total 918M
-rwxrwxrwx 1 root root  537 Sep 23 00:26 7z-console.log
-rwxrwxrwx 1 root root    0 Sep 23 00:26 7z-error.log
-rwxrwxrwx 1 root root  112 Sep 23 00:25 autoupdate.txt
-rw-r--r-- 1 root root 232M Sep 22 23:59 errors_2019-09-22.api.txt
-rw-r--r-- 1 root root 2.0K Sep 22 12:23 errors_2019-09-22.asyncloader.txt
-rw-r--r-- 1 root root  15M Sep 23 09:32 errors_2019-09-23.api.txt
-rw-r--r-- 1 root root 4.3K Sep 23 14:22 errors_2019-09-23.asyncloader.txt
-rw-r--r-- 1 root root    0 Sep 22 00:17 RainbowMiner_2019-09-22_00-09-55.txt
-rw-r--r-- 1 root root 445M Sep 23 00:24 RainbowMiner_2019-09-22_00-18-01.txt
-rw-r--r-- 1 root root 155M Sep 22 23:59 RainbowMiner_2019-09-22.txt
-rw-r--r-- 1 root root 4.5K Sep 23 00:26 RainbowMiner_2019-09-23_00-25-26.txt
-rw-r--r-- 1 root root  65M Sep 23 14:54 RainbowMiner_2019-09-23_00-26-20.txt
-rw-r--r-- 1 root root 8.6M Sep 23 14:54 RainbowMiner_2019-09-23.txt
-rw-rw-r-- 1 user user 6.9K Aug  1 03:06 Setup_2019-08-01_03-06-01.txt
-rw-r--r-- 1 root root 8.7K Sep 19 21:20 Setup_2019-09-19_21-16-01.txt
-rw-r--r-- 1 root root 2.5K Sep 19 21:21 Setup_2019-09-19_21-21-04.txt
-rw-r--r-- 1 root root 8.7K Sep 20 03:15 Setup_2019-09-20_03-14-49.txt
-rwxrwxrwx 1 root root  120 Sep 23 14:54 timerpools.json
user@miningserver:~/RainbowMiner$

**Comment by RainbowMiner** [comment]
Could you eventually send me a zip of RainbowMiner_2019-09-23_00-26-20.txt ?

**Comment by RainbowMiner** [comment]
Also, if you open http://localhost:4000/asyncloaderjobs on that server (and probably on one of the clients) - what does it say?

**Comment by Yamanipanuchi** [comment]
Requested Information.

[asyncloaderjobs - client.txt](https://github.com/RainbowMiner/RainbowMiner/files/3643126/asyncloaderjobs.-.client.txt)
[asyncloaderjobs - server.txt](https://github.com/RainbowMiner/RainbowMiner/files/3643127/asyncloaderjobs.-.server.txt)
[Logs (2).zip](https://github.com/RainbowMiner/RainbowMiner/files/3643128/Logs.2.zip)

**Comment by RainbowMiner** [comment]
Super, thank you. So the one issue seems to be resolved. But I discovered another one, regarding RainbowMiner running in the background. It is fixed in v4.4.2.7 (I'll upload it soon)
