### ISSUE TITLE
icemining pool issue

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#674]
Getting this error

Cannot compare "@{IsPowerOfTwo=False; IsZero=False; IsOne=False; IsEven=True; Sign=1}" to "0" because the objects are not the same type or the object "@{IsPowerOfTwo=False; IsZero=False; IsOne=False; IsEven=True; Sign=1}" does not implement "IComparable".
At C:\Users\Turbo\Desktop\RainbowMiner\Pools\Icemining.ps1:42 char:324
+ ... ol_Currency;($PoolCoins_Request.$_.hashrate -gt 0 -or $AllowZero) -an ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
+ FullyQualifiedErrorId : PSObjectCompareTo

**Comment by RainbowMiner** [comment]
Is this still happening (for which currency)? I just checked, and all looks good.

**Comment by jch9678** [comment]
Sorry didn't see this.  Yes it's still happening.  I'm not sure which currency....I would get that warning or similar upon startup and again as new runs occur.  I just removed the pool as I don't seem to be using it that much.  I may add it back if I start mining Arrow, not sure how profitable it is though.

**Comment by RainbowMiner** [comment]
Ok, found it. It is EPIC - Icemining sends a very much too big number, as hashrate. The digits are far out-of-range of JSON definitions.
