### ISSUE TITLE
region

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#675]
Hi!
I'm in Argentina. I'm choosing the region in the config and I have:
![image](https://user-images.githubusercontent.com/34612740/65426152-081f5b00-dde6-11e9-9255-efb07f54f440.png)
What is "sa"? In the Country Code listing, SA is Saudi Arabia but region code is for South America...

**Comment by RainbowMiner** [comment]
Oh, sorry for the confusion. Those region shortcuts are kind of a mixup. Some are shortcuts (like "sa"= SouthAmerica, "na" = NorthAmerica) and others are web country codes. If you are unclear, you may simply enter the full "SouthAmerica" as region. That works out.

**Comment by Djago** [comment]
As always, a BIG thanks!
