### ISSUE TITLE
ARS to BTC 

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#676]
Hi!

Where do you get the exchange conversion for BTC<->ARS? In RBM I get 1 BTC = ARS 554451.905 but on CryptoMarket I get ARS655560/659900 (Sell/Buy)

**Comment by RainbowMiner** [comment]
RainbowMiner gets the rates from Coinbase, Coinmarketcap and Whattomine. But since ARS is not listed on one of them, I'ld suspect it's a number, we get from a pool. What brings me to the question: on which pool do you mine ARS?

**Comment by Djago** [comment]
No, I'm not mining ARS, it's my local currency (Argentinian Pesos). Since we have lots of fluctuations in ARS-USD I'm trying to use ARS as a primary currency in order to put the KWh value in what I use to pay.

**Comment by RainbowMiner** [comment]
Ah! Sorry, I keep on thinking in means of "Coins"..
So it's Coinbase that delivers the value: `"ARS":"549940.158915"`
