### ISSUE TITLE
Sometimes Lock dissapears

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#677]
I use Lock function. Sometimes (I couldn't pinpoint when), the function just disappears from the options:
![image](https://user-images.githubusercontent.com/34612740/65648438-aa9f3000-dfd8-11e9-99ee-1eed224a4e98.png)
I'm not sure if it's related but right now the list of miners is short in comparison with the normal list I see daily.
Today I have activated the Lock. But at a given moment, my Vega reseted (I have configured RBM to do it!) and went to the short miner list, and the Lock function disappeared. Then (while writing this Issue), the Vega reseted again and the long list reappeared, so did the Lock function (and it also appeared activated!).

**Comment by RainbowMiner** [comment]
This might very well have been a donation round.
