### ISSUE TITLE
Stats not matching across Rigs.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#678]
How are these two different. One in XmrigCpu fee, One has the fee the other does not. And ZergPoolCoins m7m accuracy is wildly different on each PC. They should be the same, Or VERY close right?

`Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz (CPU#00)
=================================================

Miner             Fee Algorithm       Speed   Diff Power   BTC/Day  USD/Day  Accuracy Pool               PoolFee
-----             --- ---------       -----   ---- -----   -------- -------- -------- ----               -------
CpuminerJayddee     - m7m        60.44 kH/s   3.64   62W 0.00002246   0.1800      77% ZergPoolCoins-Magi   0.50%
XmrigCpu        1.00% RandomWow   1.37 kH/s 42.69k   65W 0.00001118   0.0896      94% HeroMiners-Wownero   0.90%
XmrigCpu        1.00% RandomXL  916.80  H/s 34.01k   54W 0.00001014   0.0812      85% HeroMiners-Loki      0.90%

Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (CPU#00)
================================================

Miner           Fee Algorithm      Speed   Diff Power   BTC/Day  USD/Day  Accuracy Pool               PoolFee
-----           --- ---------      -----   ---- -----   -------- -------- -------- ----               -------
XmrigCpu          - RandomWow  2.41 kH/s 67.38k   65W 0.00001973   0.1588      98% HeroMiners-Wownero   0.90%
XmrigCpu          - RandomXL   1.54 kH/s 46.62k   65W 0.00001706   0.1373      93% HeroMiners-Loki      0.90%
CpuminerJayddee   - m7m       79.21 kH/s   4.79   63W 0.00003050   0.2454      35% ZergPoolCoins-Magi   0.50%
`

**Comment by RainbowMiner** [comment]
It's difficult to say. Most probably it is related to the different sampling times and rates and eventually to different age of the samples. I would try to remove the pool stats for m7m on both rigs (at the same time, preferably) and see, if the accuracy still differs that much

**Comment by RainbowMiner** [comment]
Another information: the stats are *not* synced. Every machine collects it's own information.
