### ISSUE TITLE
MRR API Key keeps syncing across systems

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#679]
I have the following in the ExcludeServerConfigVars

pools:MiningRigRentals:API_Key,pools:MiningRigRentals:API_Secre

I keep finding that my system still sync the keys. I have all my rigs as separate rig rentals. I've found that I end up getting the same physical rig rented for different algorithms at the same time unless I have different API Keys.

Either something is Bugged, Or I am no excluding MRR API Keys correctly.

**Comment by Yamanipanuchi** [comment]
I just found   "EnableServerExcludeList": "0", I dont ever remember setting it to 0. I just set it to 1. Im going to guess maybe this it is?

**Comment by Yamanipanuchi** [comment]
Also getting the following in the server log files quite a lot.

2019-09-28 05:46:26 [328.96 0.00] INFO: MiningRigRental call: Cannot process argument transformation on parameter 'body'. Cannot convert the "{
  "status": "disabled"
}" value of type "System.String" to type "System.Collections.Hashtable".

**Comment by Yamanipanuchi** [comment]
Getting the following from one system that keeps showing this issue.
2019-09-28 05:57:29 [354.44 0.00] INFO: Could not request from us-west01.miningrigrentals.com:3333

**Comment by RainbowMiner** [comment]
Oh, that's interesting! Most probably the Mrr server has some problems. I already wondered, if it might be an API change, but this really looks like a Mrr stratum problem. I will investigate

**Comment by RainbowMiner** [comment]
> I keep finding that my system still sync the keys

If you had added the `"pools:MiningRigRentals:API_Key,pools.MiningRigRentals:API_Secret"` to the server's exclude-list, only, then setting `"EnableServerExcludeList": "1",` should have solved that for you. Otherwise you would have had to set the above two to every client's config.txt exclude-list.
