### ISSUE TITLE
Enhancement: Set CPU cores in config for global or Remove hyperthreading

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#68]
Would like to be able to set CPU cores in config for globally or Remove hyperthreading feature. Intel cpu's do not benefit from hyperthreading. For almost all algos including monero, you will see a hash drop. This is not true for AMD as a threadripper would double it's hash rate with hyperthreading. Plus I like to keep a core free so the system will still respond quickly.

**Comment by RainbowMiner** [comment]
Would it be sufficient, to select the number of free cores in the config? So, setting this new parameter to 1 one always leave one core unused to mining.

RBM

**Comment by RainbowMiner** [comment]
Also, see issue #34 CPU mining

**Comment by RainbowMiner** [comment]
With the new release v3.8.5.5 all miners/devices/algorithm combinations will be in the miners.config.txt.
