### ISSUE TITLE
Rainforest2 fails

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#681]
[debug_2019-10-02.zip](https://github.com/RainbowMiner/RainbowMiner/files/3682076/debug_2019-10-02.zip)

Rainforest2 rfv2 fails

**Comment by RainbowMiner** [comment]
Oh dear, I just see it. It seems to have a problem.

**Comment by RainbowMiner** [comment]
Ok, I have added a new RainforestV2 ccminer (thanks to spmod). Eventually that one will run more stable and faster.

**Comment by RainbowMiner** [comment]
RainforestV2 is no longer applicable. MBC is mined with Yespower2b, now.
