### ISSUE TITLE
MRR API Keys keep Syncing even with Exception in place.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#682]
The MRR API key keeps syncing across my rigs even with the exception in place. I have each physical rig setup with separate MRR rigs. When the API Key gets sync'd I end up with all odd different out comes on one of the three systems I have.

Currently I have the Client machines setup as "standalone" so the key doesn't get synced.

[Server Config.zip](https://github.com/RainbowMiner/RainbowMiner/files/3688328/Server.Config.zip)
[Client Debug.zip](https://github.com/RainbowMiner/RainbowMiner/files/3688329/Client.Debug.zip)

**Comment by RainbowMiner** [comment]
I will check this asap.

**Comment by RainbowMiner** [comment]
There is a missing a "t" at the end of `pools:MiningRigRentals:API_Secre` in the server's config.txt:
```
pools:MiningRigRentals:API_Key,pools:MiningRigRentals:API_Secre,
```
.. also, there is a bug in the core. I will fix it now.
