### ISSUE TITLE
Zergpoolcoins not picking up all coins

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#684]
Notable some equihash coins don't get picked, in particular, ZEL and BTCZ which I'm trying to enable for PBM

**Comment by RainbowMiner** [comment]
Thank you for reporting that. I will check ZergPoolCoins.

**Comment by RainbowMiner** [comment]
It should, with the next release.

**Comment by acos0874** [comment]
Thanks. It looks like it's working again, even though I'm 4.4.3.8

**Comment by RainbowMiner** [comment]
Yes, most probably - there is a unprofitable list, which is aquired online every six hours. I have adapted this list. The new release contains this list as default.
