### ISSUE TITLE
Equihash R 150,5,3 Accuracy Issues

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#686]
There appears to be an issue with the accuracy calculation on this algorithm for Nicehash. The value seems to fluctuate wildly. Sometimes it shows 34% and then the next moment it's 100% and then sometimes I've even seen -1000%.

**Comment by RainbowMiner** [comment]
Wow -1000% is quiet a lot :) Thanks for reporting. Normally, this indicates, that Nicehash is running low on orders on that algorithm. I'll have a look into their orderbook.

**Comment by RainbowMiner** [comment]
For explanation: there is a build-in error check on accuracy calculations. If it's out-of-range (like when the price drops down to 0), the accuracy will be reset. This is when it's back to 100%.
