### ISSUE TITLE
Lots of errors appearing

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#687]
Since last update I am receiving lots of red lines with:

> Add-Member : Cannot add a member with the name "MaxRejectedShareRatio" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.
At D:\CryptoCurrencies\RainbowMiner\Core.psm1:1467 char:63
> + ... ) {$Miner | Add-Member MaxRejectedShareRatio $Session.Config.MaxRejec ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : InvalidOperation: (@{Path=D:\CryptoCur\u2026 NoCPUMining=False}:PSObject) [Add-Member], InvalidOperationException
> + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

[...] several times repeated

I'm uploading the debug file
[debug_2019-10-10.zip](https://github.com/RainbowMiner/RainbowMiner/files/3714918/debug_2019-10-10.zip)

**Comment by RainbowMiner** [comment]
Yes, found it. I have used that MaxRejectedShareRatio for the Power2b miner.
