### ISSUE TITLE
Benchmark doesn't close miner and doesn't switch to next miner

### ISSUE THREAD

**Issue by theappym** [RainbowMiner/RainbowMiner#688]
I have windows 10 Ent 1903.
12 Nvidia GPUs - 1070 and 1070Ti.
I am struggling with benchmarking.
It will start with a specific algo, start benchmarking it, then after the benchmark time is up, rbm will say "finish..." and is suppose to close the miner and start with the next miner.
This does not happen.
It does not close the miner and does not record the mining stats.
So, when I End-Task rbm, it starts again.
I have excluded all miners for specific algos, hoping it was a specific miner causing this issue, and have also limited to about 3 or 5 algos with 2 miners, and still does the same.

If I choose one algo and one miner only, it will finish.
I am now upgrading Windows to next Edition, so busy with reboots etc.

If I try to close rbm using "x" it will sometimes freeze, or even the miner will freeze and then windows will freeze.
When I End-task it, it will actually close.

Let me know what info you might need and from where I can get it for you.
The localhost:4000 portal will also become sluggish or unresponsive / times-out.
I have clean-installed Windows several times to try and by-pass this, downloaded every .net etc as per your guide and allowed rbm to install whatever it might need.

I have run it in ps as admin or cmd as admin, and have run ps scripts to allow execution of bat and exe files using:

Get-ChildItem -Path 'C:\Users\theap\Downloads\00_RainbowMiner\' -Recurse | Unblock-File

**Comment by RainbowMiner** [comment]
Which Nvidia driver version are you using? 
And, are you mining your cpu, too?
Please zip the "Logs" folder and upload it. I will have a look.

**Comment by RainbowMiner** [comment]
Also, which Cpu is plugged into the system?

**Comment by theappym** [comment]
I do not mine on CPU, but it is: i3-7100 3.90 GHz
Nvidia 436.3, haven't downloaded the latest yet.
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/3717225/Logs.zip)

**Comment by theappym** [comment]
Thank you very much :)

**Comment by RainbowMiner** [comment]
Eventually try to downgrade your Nvidia drivers. It could be very much the case the new drivers mess up most miners.
I have linked to a debloated package of 431.68 in my readme: https://github.com/alanfox2000/repack_NVIDIAGeforceGraphicsDriver/releases/download/431.68/nvidia-geforce-graphics-driver-lite-431.68-win10-64bit-standard-03-08-2019.exe

**Comment by theappym** [comment]
I did that just before you send your suggestion.
Still, even with a windows.iso upgrade, reinstall of the above nvidia drivers, rbm would start benching and then just stop at "20s remaining..." whilst cryptodredge mines in the background for 45min.
I cannot get rbm to respond and just is stuck on "20s remaining".
Even if I click "enter" on rbm screen, or "x" or "r", nothing happens. I have to end-task it.

Could it be Win10 Enterprise functionality that is the problem?
I am going to try Linux and see if that is better...any other suggestions you might have?

**Comment by RainbowMiner** [comment]
Ok, it looks like you have stability problems with this rig (eventually powersupply). Miners tend to crash and cause lagging. The worst seems to be the EnemyZealot miner. RainbowMiner needs to kill it, because of frequent crashes on your rig.

How about overclocking. Do you overclock your GPUs, potentially with Afterburner? I ask, because Afterburner is known to cause lags and high CPU load on machines with more than 6 GPUs.

Try the following:
- first of all, install [Powershell Core v6.2.3](https://github.com/PowerShell/PowerShell/releases/download/v6.2.3/PowerShell-6.2.3-win-x64.msi)
- uninstall MSI Afterburner, if you have it running.
- set the following in your RainbowMiner config.txt:
```
"EnableOCProfiles": "1",
```

**Comment by theappym** [comment]
Thank you for checking the logs and all your suggestions. I have 3 PSUs :).
I have Installed Linux last night - manjaro-kde (my fav OS), updated the nvidia drivers, applied the suggestions as on your download site and it has gone through "ALL" the benches without problems.
I would tend to agree that it could have been MSI Afterburner, as that is not applicable anymore.
Linux is just so much more stable!
You may close this as resolved, as I believe the test implies that it is not RBM which is the problem but rather a combo of OS and Afterburner mostly.
If you want steps to follow to test on Manjaro-KDE, please let me know, but it is running on the latest v.19 of Manjaro with kernel 5.2.20-1 and NVidia 430.
Mining against Zergpool and Nicehash.
Thank you for everything and have an awesome day!
