### ISSUE TITLE
Alternative profit switch priority - minimise cost per watt

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#689]
The cold winter months are approaching us, and some of us use our mining rigs to heat our homes. It's one of the ways mining still makes economic sense as it offsets our heating bills. Unfortunately, RBM will always prioritise the most profitable algorithm even if it's way lower power consumption than a slightly less profitable algorithm. Please can a toggle be added to instead of trying to maximising profitability, minimise cost per watt instead? This will allow people to heat their homes cheaply this winter.

**Comment by RainbowMiner** [comment]
Done :) I have added a new parameter "EnableHeatMyFlat". To enable, set
```
  "EnableHeatMyFlat": "1",
```
.. in config.txt

**Comment by samdave123** [comment]
Thanks for this, but I think it needs a bit more work to make it economical. The difference between profitability of X16s and ethash for me is about £0.70 but the difference in wattage is 144, which equates to about a £0.30 increased power cost. If the difference in profit is greater than the difference in power cost, then it's uneconomical to switch algorithm for heat rather than just turning on an electric space heater. Could you tweak it to only switch to a higher power algorithm if it's economical to do so?

**Comment by RainbowMiner** [comment]
I'll try to wrap a better function around this. Oddly enough, this heating task seems surprisingly difficult. Which are the parameters you are using to crunch the numbers exactly?

**Comment by samdave123** [comment]
I think a calculation needs to be made for every miner/algo combination so that RBM can switch to maximise the 'heating value'. I suggest in order to minimise the amount of calculations RBM needs to do, it exclusively calculates profit value when HeatMyFlat=0 and exclusively calculates heating value when HeatMyFlat=1

Heating value=watts*(revenue-miner fee) 
Profit value=revenue-miner fee-powercost

**Comment by RainbowMiner** [comment]
Yes. This exactly is in place, currently. 
Miners are then being compared by their Heating value, if HeatMyFlat=1

Actually, I am not using the absolute watts, but a relative value (like in %). Something like watts(rel) = watts/watts(max).

**Comment by RainbowMiner** [comment]
> If the difference in profit is greater than the difference in power cost, then it's uneconomical

Maybe we can use this as basis for a better calculation.

**Comment by samdave123** [comment]
> Yes. This exactly is in place, currently.

Sorry, I must have misunderstood how you implemented it. Perhaps you've actually perfected it already. I'm actually really confusing myself trying to figure out the maths.

**Comment by RainbowMiner** [comment]
I think, I have an idea for another formula:
We could use the HeatMyFlat as number. 0=off, 1..10 is intensity of heat.

With a heat value of:

`Heat value=revenue-miner fee-powercost*(0.5 - HeatMyFlat/10)`

**Comment by samdave123** [comment]
Okay, I think I've finally figured out this simple problem. The economic heating calculation should obviously be (killowatts*powercost*24)+(revenue-costs).

The heating value is (killowatts*powercost*24) because that is what an space heater would cost to produce that amount of heating during the day, and profit then adjusts that value.

**Comment by samdave123** [comment]
Okay I've figured it out. Instead of calculating 'Profit' it should calculate 'Cost per watt'. 

Cost per watt =(Wattage / daily power cost) + profit

((killowatts/((killowatts * 24) * power cost)) + profit

**Comment by samdave123** [comment]
I think "UsePowerPrice" is the setting to use for optimal heating. Sorry for making this so much more complicated than it should be. The whole "HeatMyFlat" setting is not necessary.

**Comment by samdave123** [comment]
Please could the heat mode be changed to ignore power price and thus profit-switching to maximise revenue generated ignoring power cost? The heat mode would still be useful to have to display and track profitability. Alternatively, having "UsePowerPrice" set to 1 and then having another option to factor power price into profit-tracking?

**Comment by RainbowMiner** [comment]
Of course :D basically, we are right now at the formula:
`Heat value=revenue-miner fee-powercost*(0.5 - HeatMyFlat/10)`
.. If HeatMyFlat = 5, you have exactly the effect as if you were using "UsePowerPrice"=0.

**Comment by samdave123** [comment]
Okay that sounds great then. Let's go with that and then I'll be all set for the colder weather that'll start next month.

**Comment by RainbowMiner** [comment]
Hope, your flat is warm and cosy now :) mine is.
