### ISSUE TITLE
% of accepted shares in Activity page on dashboard

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#690]
Currently the Activity page says when there's a crash which is really helpful to identify issues with the mining rig. It would also be helpful to have another column with the % of accepted shares. This could then highlight any activity with less than 90% accepted rate which would show problems.

This would also be very helpful on the Benchmark page as sometimes the benchmark passes but with lots of rejected shares.

**Comment by RainbowMiner** [comment]
Added. This is very useful.

**Comment by samdave123** [comment]
This is great, thanks for adding so quickly!

**Comment by samdave123** [comment]
Could it be rounded to 2 decimal places?

![Screenshot_2019-10-16 RainbowMiner Local Dashboard](https://user-images.githubusercontent.com/56473344/66906492-b8f0d280-efff-11e9-93a6-44db3709c014.png)

**Comment by RainbowMiner** [comment]
Oh. Damn the Powershell "double". It's fast but pretty imprecise.
I'll round along.

**Comment by RainbowMiner** [comment]
Actually, which browser are you using?

**Comment by samdave123** [comment]
I'm using Firefox, but it appears the same in Chrome. I just double-checked and I think it's only an issue in the Benchmarks page.

**Comment by RainbowMiner** [comment]
Solved in v4.4.4.8
