### ISSUE TITLE
Issue with three machines.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#691]
Getting the following on three separate machines after recent updates.

user@solar1:~/RainbowMiner$ sudo ./start.sh
[sudo] password for user:
Transcript started, output file is .\Logs\RainbowMiner_2019-10-14_15-49-47.txt
__________        .__      ___.                   _____  .__
\______   \_____  |__| ____\_ |__   ______  _  __/     \ |__| ____   ___________
 |       _/\__  \ |  |/    \| __ \ /  _ \ \/ \/ /  \ /  \|  |/    \_/ __ \_  __ \
 |    |   \ / __ \|  |   |  \ \_\ (  <_> )     /    Y    \  |   |  \  ___/|  | \/
 |____|_  /(____  /__|___|  /___  /\____/ \/\_/\____|__  /__|___|  /\___  >__|
        \/      \/        \/    \/                     \/        \/     \/

Starting v4.4.4.5! Please wait..

Detecting devices ..
Initialize configuration ..
Write-Log : Cannot bind argument to parameter 'ReferenceObject' because it is null. Cannot run RainbowMiner.
At /home/user/RainbowMiner/Core.psm1:244 char:9
+         Write-Log -Level Error "$($_) Cannot run RainbowMiner. "
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

Write-Log :  is invalid. Cannot continue.
At /home/user/RainbowMiner/Core.psm1:371 char:9
+         Write-Log -Level Error "$($Session.ConfigFiles["Config"].Path ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

The property 'Stop' cannot be found on this object. Verify that the property exists and can be set.
At /home/user/RainbowMiner/API.psm1:1021 char:198
+ ... null} catch {if ($Error.Count){$Error.RemoveAt(0)};$API.Stop = $true}
+                                                        ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : PropertyNotFound

The property 'Server' cannot be found on this object. Verify that the property exists and can be set.
At /home/user/RainbowMiner/API.psm1:1023 char:5
+     $Global:API.Server = $null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : PropertyNotFound

The property 'Handle' cannot be found on this object. Verify that the property exists and can be set.
At /home/user/RainbowMiner/API.psm1:1024 char:5
+     $Global:API.Handle = $null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : PropertyNotFound

Remove-Variable : Cannot find a variable with the name 'API'.
At /home/user/RainbowMiner/API.psm1:1025 char:5
+     Remove-Variable "API" -Scope Global -Force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (API:String) [Remove-Variable], ItemNotFoundException
+ FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand

Transcript stopped, output file is /home/user/RainbowMiner/Logs/RainbowMiner_2019-10-14_15-49-47.txt
user@solar1:~/RainbowMiner$

Will dig into it further when I get to my desk and can look into it further.

**Comment by RainbowMiner** [comment]
Oh! This is not good! Please keep me updated, also a zip of the Logs folder would be super.

**Comment by RainbowMiner** [comment]
I hide the v4.4.4.5 until this is clarified.

**Comment by Yamanipanuchi** [comment]
Working on the config files.. But it looks as if all the files that sync with the server are now 0 bytes.

user@solar1:~/RainbowMiner$ ls -l Config/
total 136
-rw-r--r-- 1 root root     0 Oct 14 15:29 algorithms.config.txt
-rw-r--r-- 1 root root   415 Sep 13 14:08 autoexec.txt
drwxr-xr-x 2 root root 69632 Oct 14 15:03 Backup
-rw-r--r-- 1 root root     0 Oct 14 15:29 coins.config.txt
-rw-r--r-- 1 root root   414 Oct 14 15:03 colors.config.txt
-rw-r--r-- 1 root root    32 Oct 14 15:03 combos.config.txt
-rw-r--r-- 1 root root     0 Oct 14 15:29 config.txt
-rw-r--r-- 1 root root   217 Oct 14 15:03 devices.config.txt
-rw-r--r-- 1 root root     3 Oct 14 15:03 gpugroups.config.txt
-rw-r--r-- 1 root root   760 Aug 15 16:16 minerconfigfiles.txt
-rw-r--r-- 1 root root     3 Oct 14 15:03 miners.config.txt
-rw-r--r-- 1 root root 27634 Oct 14 15:03 mrr.config.txt
-rw-r--r-- 1 root root   748 Oct 14 15:03 ocprofiles.config.txt
-rw-r--r-- 1 root root     0 Oct 14 15:29 pools.config.txt
-rw-r--r-- 1 root root  1035 Oct 14 15:03 scheduler.config.txt
user@solar1:~/RainbowMiner$


Odd that it happened on three system. Ill restore the backup and I am sure it will be fine. But not sure  what caused it.

**Comment by Yamanipanuchi** [comment]
These machines are difficult to get the logs off of. I restored the config and they are working now. I suspect they possibly lost power while they were in the update process, effectively leaving the config files blank.

**Comment by RainbowMiner** [comment]
Are other machines running fine one v4.4.4.5 ? Meaning, can I dare to reactivate the release?

**Comment by RainbowMiner** [comment]
Just if you find the time, I am mostly interested on the RainbowMiner_2019-10-hh_mm-dd-ss.txt, that tracked the crash and the RainbowMiner_2019-10-14.txt

**Comment by Yamanipanuchi** [comment]
Ya, I have several other machines working fine. I will get the logs off one of them at least.

**Comment by Yamanipanuchi** [comment]
[Logs (2).zip](https://github.com/RainbowMiner/RainbowMiner/files/3725822/Logs.2.zip)

Logs from one of the machines.

**Comment by RainbowMiner** [comment]
There must have been some major disturbance on that machine. The logs contains a hand full of "file is corrupt" messages. It indicated, that something went wrong during write to disk. Is the SSD full?

**Comment by Yamanipanuchi** [comment]
Nope, Currently at 1.7g free. They are relatively small drives on these machines. Honestly given the nature of how these are setup, I wouldn't put much more time into it. Thank you for looking. Mostly I saw several down and Wanted to make sure there was not something more major going on.
