### ISSUE TITLE
Custom Configs for a group of Rigs

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#693]
Currently if you add /Rig-Name to the config folder you can customize that one rig. Is there the possibility to add something like a rig group?

Example.

/Office
/Home
/Solar

And you can point multiple rigs to that folder for config info.

Not sure if this makes sense... Trying to avoid having to updates multiple config files for a set of rigs that all use the same configs but still need to keep them segregated from the larger group.

**Comment by RainbowMiner** [comment]
That is a super smart idea. Of course it makes of sense. I'll try to figure something out. Thank you for the inspiration :)

**Comment by RainbowMiner** [comment]
Should work, by now :)

**Comment by Yamanipanuchi** [comment]
Ohh ya works great!
