### ISSUE TITLE
Longer/customisable retention for logs of crashed miners

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#695]
I am currently checking on my rig once a week for any instability so I can fine-tune my overclocks if something is unstable. The problem I have is that I can't see crashed miners that weren't in the past three days, and I don't have time to check my rig every 3 days. Please could log retention for crashed miners be either extended or customisable?

Perhaps we can specify a value to determine number of days retention, or a value to specify the number of crashes to log so the last X are all retained? This would really help me to manage regular checks on my rig.

**Comment by Nickfost** [comment]
Maybe a log server rather? or emailer?

**Comment by samdave123** [comment]
I'm not sure what the best way to implement it is, but the last 50 lines of the Miner console output must be saved as its so helpful for determining what the issue is.Is disk space a big issue for storing these log files? On 22 Oct 2019 3:16 am, Nick Foster <notifications@github.com> wrote:Maybe a log server rather? or emailer?

**Comment by RainbowMiner** [comment]
The miner console window can be saved, but you have to switch "ShowMinerWindow" to "0". There is no easy way to pipe the console window's output. Regarding the activity: yes, there is a way. I'll figure something out.

**Comment by RainbowMiner** [comment]
- added "MaxActivityDays" to config.txt
  - default = 2
  - set to maximum days for activity-list history on localhost
