### ISSUE TITLE
Scheduler may not be working.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#697]
I have the current in my config.txt

  "PowerPrice": 0.00,
  "PowerOffset": 0.0,
  "PowerPriceCurrency": "USD",
  "UsePowerPrice": "1",
  "CheckProfitability": "1",

And the current in my scheduler.config.txt

[
  {
    "DayOfWeek": "*",
    "From": "14:00",
    "To": "23:00",
    "PowerPrice": "0.25",
    "Pause": "1",
    "Enable": "1"
  },
  {
    "DayOfWeek": "0",
    "From": "14:00",
    "To": "23:00",
    "PowerPrice": "0.00",
    "Pause": "0",
    "Enable": "0"
  },
  {
    "DayOfWeek": "1",
    "From": "14:00",
    "To": "23:00",
    "PowerPrice": "0.25",
    "Pause": "1",
    "Enable": "1"
  },
  {
    "DayOfWeek": "2",
    "From": "14:00",
    "To": "23:00",
    "PowerPrice": "0.25",
    "Pause": "0",
    "Enable": "1"
  },
  {
    "DayOfWeek": "3",
    "From": "14:00",
    "To": "23:00",
    "PowerPrice": "0.25",
    "Pause": "0",
    "Enable": "1"
  },
  {
    "DayOfWeek": "4",
    "From": "14:00",
    "To": "23:00",
    "PowerPrice": "0.25",
    "Pause": "0",
    "Enable": "1"
  },
  {
    "DayOfWeek": "5",
    "From": "14:00",
    "To": "23:00",
    "PowerPrice": "0.25",
    "Pause": "0",
    "Enable": "1"
  },
  {
    "DayOfWeek": "6",
    "From": "00:00",
    "To": "23:59",
    "PowerPrice": "0.25",
    "Pause": "0",
    "Enable": "0"
  }
]

I am looking to have my miners stop during a specific time of day through the week but not stop on the weekends or have a higher power price to effectively only mine when it is super profitable. Either I am missing something in the config, Or the script is not picking up what I am asking. If I manually go into the config.txt and change the powerprice to .25 it acts appropriately.

**Comment by Yamanipanuchi** [comment]
Sidenote, I only have one rig with an active rental. once I set .25 in config.txt the two systems NOT rented stopped mining. But the one that is rented keeps turning on and off continually.

I just changed

"DayOfWeek": "*",
"From": "14:00",
"To": "23:00",
"PowerPrice": "0.25",
"Pause": "1",
"Enable": "1"

to

"DayOfWeek": "*",
"From": "14:00",
"To": "23:00",
"PowerPrice": "0.25",
"Pause": "0",
"Enable": "1"

and it looks like it started mining. I am going to keep an eye on it.

**Comment by Yamanipanuchi** [comment]
Correction, I still see the same behavior with the above setting. I just changed it to...

  {
    "DayOfWeek": "*",
    "From": "14:00",
    "To": "23:00",
    "PowerPrice": "0.25",
    "Pause": "0",
    "Enable": "0"

Ill continue to monitor it.

**Comment by Yamanipanuchi** [comment]
It almost looks as if PowerPrice is also shutting Rentals off.

**Comment by RainbowMiner** [comment]
It's an "almost" - it should display a message, but continue mining, anyway. But I think, I might have found a reason for the alternating on-off (and fixed with b62b85a eventually).

Some inside explanation on the scheduler.txt:
`"Enable": "1",` means "use this configuration record"
`"Pause": "1",` means "if day and time matches for this record, stop mining except in a rental"

An enabled record with an exact day (like `"DayOfWeek": "1",`) is being used over the record for every day `"DayOfWeek": "*",` (if it is enabled)
