### ISSUE TITLE
Nicehack earnings tracking is broken

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#699]
Nicehash reported earnings are heavily inflated at the moment. I'm definitely not earning as much as RBM says I am.

![image](https://user-images.githubusercontent.com/56473344/67517322-47b5bd00-f69a-11e9-8c53-0420b160dbee.png)

**Comment by RainbowMiner** [comment]
Yes, the average is miscalculated for Nicehash. I am still investigating this.
