### ISSUE TITLE
RainbowMiner/Miners/CcminerSpModTribus.ps1 that Ccminer doesn't support Tribus

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#7]
RainbowMiner/Miners/CcminerSpModTribus.ps1 that Ccminer doesn't support Tribus
CcminerSpModTribus

*** ccminer TribusSPmod2 for nVidia GPUs from alexis78@github ***
*** Based on tpruvot@github ccminer
*** Originally based on Christian Buchner and Christian H. project
*** Include some of the work of djm34, sp, tsiv and klausT.

*** Optimized by (c) SP

[2018-07-31 21:30:36][31m Non-existant CUDA device '-a' specified in -d option[0m

**Comment by RainbowMiner** [comment]
Oh, I see. Yes, the devices-string is missing in this miner. Thank you!
See commit ad28622eba2590289a84f7b8f75ac051d531b694
