### ISSUE TITLE
Enhancement: Separate Stats folder into 2 for profits and miners

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#70]
Instead of having 1 folder that is storing the stats for profits from pools and miners benchmark. Could we have 2 separate folder for stats. 1 only for the pools profits and another only for the miners benchmarks? It would make it much easier when wanting to delete only one benchmark.

**Comment by RainbowMiner** [comment]
Done :) Will be part of the next release.
RBM
