### ISSUE TITLE
Group and Specific Machine Config Question

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#700]
Just a question. If I have a folder setup for a group or a specific machine and I leave a file out, For example coins.config.txt. Will it reference the one from the root folder?

Why I ask, Is that coins.config.txt and pools.config.txt are the same for every machine. If I only needed up update the root on and leave the file out in the group it would take less updating.

Was not sure if this is how it is setup. Guess I could just try it and see what happens. ;)

**Comment by RainbowMiner** [comment]
Yes, it will fallback to the root config for missing files.

**Comment by RainbowMiner** [comment]
More explanation, the files will be looked up with the following fallback-strategy:
```
if (config file exists in WorkerName-Folder) use WorkName-Folder's config file
else if (config file exists in GroupName-Folder) use GroupName-Folder's config file
else use root Config-Folder's config file
```

**Comment by Yamanipanuchi** [comment]
That is awesome!
