### ISSUE TITLE
Mine till block found

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#701]
I think this has been asking for.

Wondering if there would be a way to add the ability to lock your miner to an algo until a block is found per pool or algo. For example 2miners, If your miner switches off this pool and it takes long enough you will basically wait your time there. Maybe one a threshold. Like if you spend more then said time on this pool/algo stay there until block found. There's still a chance for Orphaned block.. But...

Or is this function already there in some way?

**Comment by RainbowMiner** [comment]
We could solve it like this:
- add new key "LockUntilBlock": "0" / "1" to pools.config.txt and/or algorithms.config.txt
- add new key "MaxLockTime": "0%".."100%" / "0..x" to pools.config.txt and/or algorithms.config.txt

So, if "LockUntilBlock" is enabled and mining is going on for this pool / algorithm, go on mining until block has been found or longer mining than "MaxLockTime". Where "MaxLockTime" is either in percent of average time to find or absolute in seconds.

What do you say? Would that solve this?

**Comment by Yamanipanuchi** [comment]
Yes. Exactly.

**Comment by RainbowMiner** [comment]
Regarding this application, would it be wise to have these options at multiple locations (e.g. pools.config.txt, coins.config.txt, algorithms.config.txt), or would it be sufficient to have them in one of the upper three configurations?

**Comment by Yamanipanuchi** [comment]
I was thinking about that. Some pools use pplns on all algo/coins, but then some pools do not. I think it may need to be under all of them to cover all possible scenarios.
