### ISSUE TITLE
Updated and now all miners crash

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#702]
Noticed a day ago that this system would crash instantly. I have had this rig mining fine for over a year. All windows and drivers upto date. Exclusions have been the same through AVG for the same time period. Yet, a few days ago now the miner will instantly crash when loading. None of them work could you help diagnose?
[RainbowMiner_2019-10-27_14-47-33.txt](https://github.com/RainbowMiner/RainbowMiner/files/3776474/RainbowMiner_2019-10-27_14-47-33.txt)
[Activity_2019-10-27.txt](https://github.com/RainbowMiner/RainbowMiner/files/3776475/Activity_2019-10-27.txt)
[RainbowMiner_2019-10-27.txt](https://github.com/RainbowMiner/RainbowMiner/files/3776476/RainbowMiner_2019-10-27.txt)
[errors_2019-10-27.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/3776478/errors_2019-10-27.asyncloader.txt)
[errors_2019-10-26.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/3776480/errors_2019-10-26.asyncloader.txt)
[Activity_2019-10-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/3776481/Activity_2019-10-26.txt)
[RainbowMiner_2019-10-26_13-54-39.txt](https://github.com/RainbowMiner/RainbowMiner/files/3776482/RainbowMiner_2019-10-26_13-54-39.txt)
[RainbowMiner_2019-10-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/3776483/RainbowMiner_2019-10-26.txt)

**Comment by RainbowMiner** [comment]
Something very weird is going on - it looks like the crashing started sometime during runtime. It has not started with an updated.

Could you try the following?

1. Stop RainbowMiner, open an Administrator cmd console and enter this:
```
cd C:\Mining\RainbowMiner\Bin\GPU-NBMiner
.\nbminer.exe --api 127.0.0.1:34000 -d 0 -o nicehash+tcp://us-east.ethash-hub.miningpoolhub.com:17020 -u byrd1083.rig1:x --no-watchdog --no-nvml -a ethash
```

Just to see, if the miner crashes?

2. Do you have overclocking in place?
3. check, if the `Force P2 State = Off` has flipped to `On` (happens after a major windows update), start C:\Mining\RainbowMiner\Includes\NvidiaProfileInspector\nvidiaprofileinspector.exe and check section 5


4. check, which Nvidia driver version is running

**Comment by RainbowMiner** [comment]
What exactly have you been doing in between these times:
2019-10-26 11:13:51 [522.80 371.83] INFO: Miner Status https://rbminer.net/api/report.php has failed. 
2019-10-26 13:54:39 [171.67 135.27] INFO: Starting RainbowMiner v4.4.5.0

.. it looks like the crashes started after this break.

**Comment by Byrd1083** [comment]
I updated the nvidia driver to 440.97
I noticed all miners crashing after that. Also Nvidia inspector will no longer show power. fan, and speed are grayed out. Should I just switch back to older driver to see if that fixes? Running a 1080ti on this system. That is the only change that was made to the system.

**Comment by Byrd1083** [comment]
I did go through and update the nvidiaprofileinspector after this and yes pstate2 is OFF. Seems bizarre how all miners will crash now.

**Comment by Byrd1083** [comment]
Here's a copy of my profile.
[Base Profile.zip](https://github.com/RainbowMiner/RainbowMiner/files/3776856/Base.Profile.zip)

**Comment by RainbowMiner** [comment]
I would strongly recommend to downgrade your drivers to v431.68 - most probably the newer drivers did import some incompatibility

**Comment by Byrd1083** [comment]
Ok I'll give it a shot today. Also, I keep having an issue with another rig not reporting to the monitor properly. When I check it, it says it is offline. Yet, when I go to that terminal, it is on and working as expected. Any ideas?
![Screenshot_20191028-073341](https://user-images.githubusercontent.com/42227809/67688158-a27b3d00-f956-11e9-81a3-cf24557d768a.jpg)
[Screenshot_20191028-073623](https://user-images.githubusercontent.com/42227809/67688141-9d1df280-f956-11e9-8cee-cc78e9ff3436.jpg)

**Comment by Byrd1083** [comment]
![Screenshot_20191028-073341](https://user-images.githubusercontent.com/42227809/67688234-bcb51b00-f956-11e9-9539-22a65a02eee9.jpg)

**Comment by Byrd1083** [comment]
![Screenshot_20191028-073623](https://user-images.githubusercontent.com/42227809/67688265-c9d20a00-f956-11e9-9881-cfc5602e1c17.jpg)

**Comment by RainbowMiner** [comment]
Yes, eventually check the system time of the rig. Is it off?

**Comment by Byrd1083** [comment]
yes, and it also threw a google time clock issue

**Comment by Byrd1083** [comment]
I am switching vpn locations. I think that may have somthing to do with it. Running to many requests through one server I think. all internet traffic was lagging bad. Switched vpn location and now it seems stable and reporting again.

**Comment by Byrd1083** [comment]
DDU and reinstalled your recommended driver package. All is well again. Sucks the update crashes all miners though.
