### ISSUE TITLE
MRR on Rigs with mixed cards and separate workers

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#703]
This used to work fine but now something seems to have changed in the core which means my 1660TIs are not being picked up as a rental at all. When I manually change the workername in pool.config to 6xGTX1660TIs as per the mrr description then all cards are picked up, which shows the API is working fine.

**Comment by acos0874** [comment]
I reverted to 4.4.5.0 and the problem went away so I think the problem is with 4.4.5.1

**Comment by RainbowMiner** [comment]
Thank you for reporting this. Could you please send me a current Debug file? I'ld like to understand, what is going on.

**Comment by RainbowMiner** [comment]
Ok, I might have found and fixed the root cause in v4.4.5.2. Could you please check and verify, if it really did solve this issue?

**Comment by RainbowMiner** [comment]
The bug still seems not to be solved #705
