### ISSUE TITLE
Feature: Leave MRR's disabled in scheduled.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#707]
I have a situation that if a rental ends within a certain time I would prefer the rig to not set all the Rigs to available until later in the day.

Example, If the rig is not rented at 06:00 set MRR to disabled. If rig is rented and the rental ends after 06:00, dont set it to available until 16:00.

Not sure if this is something that would be easy to implement.

**Comment by RainbowMiner** [comment]
A very interesting feature :) It would basically add scheduling to pools. Let me think about it.

**Comment by Yamanipanuchi** [comment]
Could even be something where after a certain time it will not Re-activate your MRR rigs. Only the scheduled time is over it will Re-enabled them.
