### ISSUE TITLE
Suggestion: WTM Button

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#709]
I occasionally want to check the average profitability of some algorithms and so copy my hashrates and power consumptions across to WTM for checking. It would be cool if this could be automated with a button on localhost which would launch WTM wiht all the hashrates already populated. #

**Comment by Yamanipanuchi** [comment]
Oh this would be nice.. But not way to copy over hash rates you dont have. But at least it will tell you the ones you have.

**Comment by RainbowMiner** [comment]
Ok, I have put those buttons onto the Active Miners page. One button per device combo.

**Comment by acos0874** [comment]
Amazing!

**Comment by acos0874** [comment]
Thanks for this, but it doesn't seem to be working correctly right now. This is the url that is generated...

https://whattomine.com/coins?eth=false&factor[eth_hr]=0&factor[eth_p]=0&zh=true&factor[zh_hr]=383.446&factor[zh_p]=727&cnh=false&factor[cnh_hr]=0&factor[cnh_p]=0&cng=false&factor[cng_hr]=0&factor[cng_p]=0&cnr=false&factor[cnr_hr]=0&factor[cnr_p]=0&cnf=false&factor[cnf_hr]=0&factor[cnf_p]=0&eqa=false&factor[eqa_hr]=0&factor[eqa_p]=0&cc=false&factor[cc_hr]=0&factor[cc_p]=0&cr29=true&factor[cr29_hr]=42.11&factor[cr29_p]=803&ct31=false&factor[ct31_hr]=0&factor[ct31_p]=0&eqb=true&factor[eqb_hr]=254.894&factor[eqb_p]=717&ns=false&factor[ns_hr]=0&factor[ns_p]=0&bcd=false&factor[bcd_hr]=0&factor[bcd_p]=0&tt10=false&factor[tt10_hr]=0&factor[tt10_p]=0&x16r=true&factor[x16r_hr]=141.266&factor[x16r_p]=809&phi2=false&factor[phi2_hr]=0&factor[phi2_p]=0&xn=false&factor[xn_hr]=0&factor[xn_p]=0&hx=false&factor[hx_hr]=0&factor[hx_p]=0&zlh=false&factor[zlh_hr]=0&factor[zlh_p]=0&ppw=false&factor[ppw_hr]=0&factor[ppw_p]=0&x25x=false&factor[x25x_hr]=0&factor[x25x_p]=0&mtp=true&factor[mtp_hr]=17.435&factor[mtp_p]=823&lrev3=false&factor[lrev3_hr]=0&factor[lrev3_p]=0&factor[cost]=0.104&sort=Profitability24&volume=0&revenue=24h&dataset=1070TIs&commit=Calculate

I get the error eth_hr must be greater than 0

**Comment by acos0874** [comment]
Sorry I realised I don't have eth enabled and this caused all algos to go haywire. Renabling eth means it works fine.

**Comment by RainbowMiner** [comment]
I will add some virtual hashrate for eth, in the next version.

**Comment by acos0874** [comment]
Also there is a slight bug in the electricity price, it copies across the £ value into the $ value. Thanks again.

**Comment by RainbowMiner** [comment]
Oh! Yes, you are right, of course. I will add some rate calculation.

**Comment by RainbowMiner** [comment]
> I will add some virtual hashrate for eth, in the next version.

.. and ..

> Oh! Yes, you are right, of course. I will add some rate calculation.

done!
