### ISSUE TITLE
Add Luxor Pool

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#710]
Hi. 

http://mining.luxor.tech/en#coins

**Comment by Nickfost** [comment]
Does this include support for their "Catalyst" product?

**Comment by RainbowMiner** [comment]
That should work out, yes. Just sign up with then, get a username and enable diverse coins, that you want to be autoexchanged to BTC. Then use your Luxor username as wallet address.
Only backdraw: the pool fee will not be correct, currently. If using the autoexchange feature it's at a 3% for every coin and not the fee shown by RainbowMiner. I'll eventually add a config field for that pool, where you can declare, which coins are switched to autoexchange.

**Comment by Nickfost** [comment]
Can you add full support for Catalyst?

**Comment by RainbowMiner** [comment]
I'll have a closer look, now.

**Comment by Nickfost** [comment]
![image](https://user-images.githubusercontent.com/1572453/77804791-5f7cdd00-704e-11ea-8fde-4cd82cbce51a.png)
whats this mean "NaN seconds ago"

**Comment by RainbowMiner** [comment]
Interesting - I think, your PC clock might be off. I will check this, tbs

**Comment by Nickfost** [comment]
> 
> 
> Interesting - I think, your PC clock might be off. I will check this, tbs

Findings?
