### ISSUE TITLE
Enhancement to Miners page

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#712]
I find I am often using the Miners page to see what algorithms work best on my GPUs. I am sorting by profit and then setting custom OC profiles for particular algorithms which stand out.

With the cold weather approaching and the heating mode ready for use, it would be helpful to have an additional column for revenue so that I can sort algorithms by revenue.

It would also be useful to have an additional column for efficiency as a calculation of profit/power. This would be a useful insight during either times of very low profitability, or during heatwaves.

**Comment by RainbowMiner** [comment]
"by revenue", isn't that the profit? I think, I do not understand.

**Comment by samdave123** [comment]
Profit is revenue-costs. "Revenue" would be the same thing as "reward" or "btc earned". It would be a calculation of BTC earned minus fees but not subtracting electricity. It would be the amount of BTC that ends up in my wallet.

If sorted, it should show the order of priority of miners chosen by the profit-switcher when Heat my Flat setting 5 is used.

It's getting pretty chilly in the UK so I'm going to be converting my mining rig into a space heater this weekend.

**Comment by RainbowMiner** [comment]
Ah, now I understand :) You'll get that column.

**Comment by samdave123** [comment]
Thank you so much!

**Comment by RainbowMiner** [comment]
Isn't the efficiency of a miner Revenue/Power and not profit/power?

**Comment by samdave123** [comment]
Yes it is, sorry that was my mistake.
