### ISSUE TITLE
Error when script cycles

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#716]
Invoke-RestMethod : The operation has timed out.
At C:\RainbowMiner\Include.psm1:5910 char:9
+         Invoke-RestMethod $RequestUrl -UseBasicParsing -UserAgent $us ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

WARNING: Unknown download error

**Comment by RainbowMiner** [comment]
Looks like some miner download fails. Have you tried restart RainbowMiner?
What does http://localhost:4000/downloadlist say?

**Comment by RainbowMiner** [comment]
Update: the "Unkown download error" is thrown, in case a server-call fails. So eventually, try to restart the server.

**Comment by Yamanipanuchi** [comment]
Will do.
