### ISSUE TITLE
Localhost heating mode toggle

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#718]
I need a toggle to turn heating mode on/off. Just a simple button on the localhost to set heating mode to 5 or to 0 would be fine.

Depending on the day, I might need the heat or not need the heat, or in the afternoon I might decide to turn it off because my flat is already warm enough.

I am currently doing this by pausing my rig before remoting into it so it won't crash, remoting into it, opening the config file, changing the config, saving it, closing the remote session, opening up the localhost again and unpausing the rig.

**Comment by RainbowMiner** [comment]
Ok :) I'll add a control.

**Comment by samdave123** [comment]
Thank you! I think eventually I'll be looking to automate this with a ambient temperature thermometer, which will be the coolest flat heating system ever.

**Comment by RainbowMiner** [comment]
I have added the first draft of a "Setup" page to localhost. One of the values is HeatMyFlat :)
![image](https://user-images.githubusercontent.com/39437538/68603537-c2f3dd00-04a8-11ea-8c02-80ceea8abc98.png)

**Comment by samdave123** [comment]
Sweet, the less I have to remote into my rig the better! Being able to toggle the heating mode with a single button will be incredibly convenient.

**Comment by samdave123** [comment]
I just tested it, and it's a bit confusing at the moment. It's not clear which is the disabled point and which is the number 5 point.

**Comment by RainbowMiner** [comment]
Good guess :) I have already added a text output to the slider, so now you can see the value.

**Comment by samdave123** [comment]
If it says "max profit" under "0" and "max revenue" under "5" then that would also be helpful.

**Comment by RainbowMiner** [comment]
Ok, it will do that :)
