### ISSUE TITLE
Icemining Issues

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#719]
I was hoping we could get icemining working again because of Beam's new algos and it's CKB pool.
I had icemining disabled because it was reporting AEON as being the most profitable by a couple magnitudes. I re-enabled icemining and still have the AEON problem so I disabled that coin.  However I get this issue below.

Cannot compare "@{IsPowerOfTwo=False; IsZero=False; IsOne=False; IsEven=True; Sign=1}" to "0" because the objects are not the same type or the object "@{IsPowerOfTwo=False; IsZero=False; IsOne=False; IsEven=True; Sign=1}" does not implement "IComparable".
At C:\Users\Name\Desktop\RainbowMiner\Pools\Icemining.ps1:42 char:324
+ ... ol_Currency;($PoolCoins_Request.$_.hashrate -gt 0 -or $AllowZero) -an ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
+ FullyQualifiedErrorId : PSObjectCompareTo

**Comment by jch9678** [comment]
[debug_2019-11-10.zip](https://github.com/RainbowMiner/RainbowMiner/files/3829641/debug_2019-11-10.zip)

**Comment by RainbowMiner** [comment]
It is EPIC, which messes Icemining up. I'll try to figure out, how to overcome this.

**Comment by jch9678** [comment]
The owner of icemining seems to be pretty engaging, would it help if I ask
him to work with you? Is the problem more than just aeon? If not let's not
worry about it, I think I'm only concerned with the beam and CKB pool.

**Comment by RainbowMiner** [comment]
If you find the time, yes, please ask him, if it would be possible to add three entries for EPIC to the API. One for each algorithm (RandomX, Progpow, Cuckoocyle), so that we can read the current pool hashrate for each.

**Comment by jch9678** [comment]
You know, when you were saying it is EPIC, I always thought you meant the problem was EPIC to overcome.  Epic as in Huge.  Hahaha.  I'll ask him, are those the only algo's you need help with?

**Comment by jch9678** [comment]
He said he will possible have time to fix it but it won't be for a couple weeks because he is swamped.  I'll contact him then to see if he has time.

**Comment by RainbowMiner** [comment]
:rofl: nah, EPIC is a coin. And the only one, which creates this problem. Thank you for contacting him.
