### ISSUE TITLE
Still getting this Download error

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#721]
Starting v4.4.6.0! Please wait..

Detecting devices ..
Initialize configuration ..
Invoke-RestMethod : The operation has timed out.
At C:\RainbowMiner\Include.psm1:5910 char:9
+         Invoke-RestMethod $RequestUrl -UseBasicParsing -UserAgent $us ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

WARNING: Unknown download error
Read configuration ..

**Comment by RainbowMiner** [comment]
Ok, I have increased the timeout for the server calls. Eventually, that should solve the issue.

**Comment by RainbowMiner** [comment]
#723 this is related
