### ISSUE TITLE
Enable/Disable devices in schedual

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#722]
May be related to previous feature request. But the ability to disable/enable devices in the schedule would be nice. Ex. Certain time of the say stop GPU, But leave CPU going or the other way around.

**Comment by RainbowMiner** [comment]
Very good idea!

**Comment by samdave123** [comment]
Why would anyone want to do this?

**Comment by Yamanipanuchi** [comment]
Heat. If one could cut devices off to reduce heat during the day. Also looking into switching out my configs a specific times of the day to mine algo's that produce less heat (Lower wattage).

**Comment by samdave123** [comment]
Ah this is something I was going to ask for before next summer. At the moment there's a mode that profit-switches to max revenue. It would be useful to have another mode to profit-switch to max sats/W. That way, you'll only use more power if the reward is significantly greater.

**Comment by samdave123** [comment]
If my suggestion in the latest comment of issue 735 is implemented, and the value can be scheduled during times of the day, then this can help reduce heat during the day for Yamani.

**Comment by RainbowMiner** [comment]
I have added two new configuration values to config.txt and scheduler.config.txt:
config.txt : 58e60823713b4fd55b8b92ecb4edbe036cd061c4
scheduler.config.txt : e747c3c5580e56a716f357a8e46342b10e208cdb
.. now the heat can be controlled.

**Comment by samdave123** [comment]
@Yamanipanuchi This isn't quite what you have requested, but I think it will have the practical effect you are after to reduce power consumption at certain times of the day.
