### ISSUE TITLE
Get Server Config error

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#723]
Getting a WARNING: Get-ServerConfig failed.

And configs are not being synced.

**Comment by RainbowMiner** [comment]
Ok, is there the timeout problem still persisting?

**Comment by RainbowMiner** [comment]
Could you eventually create and upload a Debug file?

**Comment by Yamanipanuchi** [comment]
Ill get the debug file over in a minute.. This looks like a separate issue with the config. Previous error looked like it was trying to down a piece of mining software.

I could be wrong though.

**Comment by Yamanipanuchi** [comment]
[debug_2019-11-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/3833156/debug_2019-11-11.zip)

**Comment by RainbowMiner** [comment]
Yes, it's a seperate issue. I unintentionally added a duplicate endpoint to the API.
