### ISSUE TITLE
GRIN estimates too high

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#724]
![Capture](https://user-images.githubusercontent.com/42582444/68627610-14669100-04d6-11ea-99cf-90a580599f1f.JPG)
Hi, please can you check the grin estimates on f2pool? I don't know where the estimates are drawn in from but they seem too high.

**Comment by RainbowMiner** [comment]
Oh yes, those look far too high. I will have a look.

**Comment by acos0874** [comment]
Hi, did it get fixed?

**Comment by acos0874** [comment]
Ok yes sorry I see it in the commits

**Comment by RainbowMiner** [comment]
There will be an update release within the next 20 minutes
