### ISSUE TITLE
F2Pool Aion

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#725]
I get a truncated stream error message when trying to mine AION at f2pool. Is the personalisation set correctly?

**Comment by RainbowMiner** [comment]
Could you eventually upload a Debug file? I will have to check this.

**Comment by acos0874** [comment]
[debug_2019-11-12 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/3835076/debug_2019-11-12.1.zip)

**Comment by acos0874** [comment]
Thank you for the fix. It's benchmarking fine now. It shows under the AllPools tab on local host, however, it doesn't seems to be appearing in the list of active miners for some reason.

**Comment by acos0874** [comment]
Nevermind it's there now
