### ISSUE TITLE
LOKI and WOW - Linux

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#726]
Looks as if there is no longer a miner available for LOKI and WOW for Linux. Might be some other's but these ones I use frequently.

Will stick with XMR if this is not resolvable?

**Comment by RainbowMiner** [comment]
Oh! Ok, which miners did the job? I can easily re-add missing ones.

**Comment by RainbowMiner** [comment]
If it's Nvidia, I can compile the cuda plugin library, then Xmrig 4.6.x should do the job.

**Comment by Yamanipanuchi** [comment]
They were CPU miners... Dont remember which ones they were now.

**Comment by RainbowMiner** [comment]
The new Xmrig 4.6.x should do the job. I just checked, if it runs on linux. On my Ubuntu 18 distro, it works.

**Comment by Yamanipanuchi** [comment]
Yup. Working now! Thanks!
