### ISSUE TITLE
Active Miners WTM Not working

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#727]
I am getting the following when I click the WTM buttons on Active Miners.

![image](https://user-images.githubusercontent.com/4724631/68719499-1590d000-0561-11ea-8016-2073eb226462.png)

[debug_2019-11-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/3838657/debug_2019-11-12.zip)

**Comment by RainbowMiner** [comment]
Could you please tell me, what http://localhost:4000/getwtmurls is showing?

**Comment by Yamanipanuchi** [comment]
![image](https://user-images.githubusercontent.com/4724631/68722928-e338a000-056b-11ea-9c31-683cfa3d3bcf.png)

I will also add, When I click "Active Miners", The web interface stops responding for a short while. I presume that it is collecting information?

**Comment by RainbowMiner** [comment]
Ah! Now, I get it. There is a slight backdraw, with these WTM buttons: since it fills in the WTM start page form, onyl, you will need to have at least one of the WTM algorithms from this form, among your Active Miners. Otherwise you will get "unknown"

These are
```
Bcd, Bitcore, CryptoNightFast, CryptoNightGPU, CryptoNightHeavy, CryptoNightR, Cuckarood29, Cuckatoo31, CuckooCycle, Equihash21x9, Equihash24x5, EquihashR25x
4, EquihashR25x5x3, Ethash, Hex, Lyra2RE3, MTP, NeoScrypt, PHI2, ProgPoW, X16rv2, X25x, Xevan
```

**Comment by Yamanipanuchi** [comment]
Got it. Makes sense. I just happen to be mining a specific coon right now. ill try it when i have an ae pool enabled.
