### ISSUE TITLE
Profit Selection on F2Pool vs Nicehash

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#728]
Hi, thanks for the work you did on getting f2pool estimates working. It's been working great the last couple of days but then I noticed today that RBM was selecting nicehash over f2pool even though the estimates for f2pool were higher (see picture below). I thought maybe it was to do with accuracy or pool fees but this doesn't seem to be a big enough difference. I also disabled nicehash, to force RBM to select f2pool but when I enabled it again RBM switched straight back to nicehash.

![image](https://user-images.githubusercontent.com/42582444/68770728-9a8def00-061e-11ea-85e5-f797fe14f61a.png)

Is there something else going on in the background, such as, selecting nicehash cos it's flagged as PPS, or something to do with the hashrate weights? Here is the information from the 'all pools' page.

![Annotation 2019-11-13 140855](https://user-images.githubusercontent.com/42582444/68771050-2b64ca80-061f-11ea-8898-72cc1b63f449.png)

![Annotation 2019-11-13 141019](https://user-images.githubusercontent.com/42582444/68771159-5b13d280-061f-11ea-8b0b-25507a0471d9.png)

**Comment by RainbowMiner** [comment]
Yes, there is something else:
- RainbowMiner compares "StablePrice" against each other
- since Nicehash is a PPS pool, it's live price "Price" (without any deduction from "MarginOfError") is being used to compare against other pool's prices

now you get your result:
Nicehash("Price") = 0.0000100322  >  F2pool("StablePrice") = 0.0000098643

**Comment by acos0874** [comment]
Got it, but F2pool is also PPS so can this be detected by RBM please?

**Comment by acos0874** [comment]
Actually I just realised something. If Nicehash ignores the margin of error does this mean it is not affect by the switch prevention algorithm, which has an exponential decay of the margin of error normally?

In an ideal world I would like to keep this on for both f2pool and nicehash. Would it be possible for the user to select whether to ignore margin for error on a pool by pool basis?

**Comment by acos0874** [comment]
Or I suppose I could just reduce the "switchprevention" or enable "Fastswitching"

**Comment by RainbowMiner** [comment]
> Actually I just realised something. If Nicehash ignores the margin of error does this mean it is not affect by the switch prevention algorithm, which has an exponential decay of the margin of error normally?

Yes. That's correct. My idea behind this was, that RainbowMiner very quickly detects price jumps on Nicehash. With that, you will grab a bigger share (which will be paid 1:1).

Maybe I should change the name of the pool's PPS attribute. It's used a bit out of the meaning, currently. At the moment, it implies "pool uses live payment in BTC, so always use live prices in comparison and ignore margin errors".  All other pools use a calculation, "coin price to BTC", so that the usage of "StablePrice" is the better option, in my opinion.

Actually, I like your idea with the selective MarginError deduction on/off on a pool basis.

**Comment by RainbowMiner** [comment]
> Or I suppose I could just reduce the "switchprevention" or enable "Fastswitching"

If you use "EnableFastSwitching", only live prices will be compared ("Price"). But Nicehash will still be clear of "MarginOfError".

**Comment by acos0874** [comment]
The only issue with ignoring the margin for error as far as I can see if there is then no threshold in calculation that will prevent too frequent switching. I noticed this as a problem and decided to enable 'minute_5' as the pool stat average. 

My preferred method would use the errormargin on both nicehash and f2pool, but switch back to using 'live' as the pool stat average as this will allow the miners to catch price increases early but also prevent a switch unless its more than xx% profitable, as per the switch prevention formula, but the ability to choose may be beneficial to other users.

**Comment by RainbowMiner** [comment]
> Am I right in understanding that errormargin is calculated from the amount of fluctuation? 

Correct.

**Comment by acos0874** [comment]
And the error margin is the figure that is passed into the switch prevention formula to prevent switching?

**Comment by RainbowMiner** [comment]
> And the error margin is the figure that is passed into the switch prevention formula to prevent switching?

Yes :)

**Comment by acos0874** [comment]
Ok then I think it would be preferable to keep the marginoferror enabled in the nicehash calculation please, as this can then be used with 'live' prices but keep switching from becoming to frequent.

**Comment by RainbowMiner** [comment]
I would propose the following solution for the MarginOfError per pool:
- add parameter "MaximumMarginOfError" to pools.config.txt (in percent 0..100%)
- Nicehash will be prepopulated with "0" - changing it to e.g. "5" would allow a maximum error margin of 95%. With that, we can avoid, that a very high fluctuation unintentionally supresses a good bid on Nicehash.

**Comment by acos0874** [comment]
Sounds great. Thanks again!

**Comment by acos0874** [comment]
One other quick question, I've set a pool stataverage both globally in the config file and in the pools file, but I've noticed there is also a static value in the .ps1 file for nicehash. Which value would take priority?

**Comment by acos0874** [comment]
Hmm things aren't working quite as expected. I turned switch prevention down to 0 and accuracy weight to 0. Yet when looking at beamii it selects nicehash even though f2pool pays more. Enabling fast switching seems to make it prefer f2pool. It's all getting a bit complicated for me. Can you point me in the direction of where the profit calculations are made and I'll see if I can try to understand it better?

**Comment by RainbowMiner** [comment]
> One other quick question, I've set a pool stataverage both globally in the config file and in the pools file, but I've noticed there is also a static value in the .ps1 file for nicehash. Which value would take priority?

It's pools.config.txt > config.txt > pool default
