### ISSUE TITLE
Beam F2Pool Connection Error

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#729]
Arguments: "--api $mport --devices 0 1 2 3 4 5 6 --server beam.f2pool.com --port 5000 --user XXX.1070TIs --pass x --pers Beam-PoW --cuda 1 --opencl 0 --watchdog 0 --pec 0 --nvml 0 --algo BeamHashII"

Same problem as was occurring with AION I think.

**Comment by RainbowMiner** [comment]
I would rather think it's a pool issue, this time. The command string looks perfectly allright. Anyway, I'll test with one of my rigs to be sure.

**Comment by RainbowMiner** [comment]
Oh! F2pool want's ssl for BEAM. So it's a module issue. I'll post an update asap.
