### ISSUE TITLE
Percentage threshold for algos with multiple pools and miners

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#731]
Hello,

I'm referring to the issue when one particular algorithm is enabled for multiple pools or miners, that the switch prevention and minimum intervals are ignored causing sometimes a lot of switching between the different miners and pools.

Would it please be possible to implement a basic percentage threshold to mitigate this switching whilst still keeping all pools and miners active?

So for example if mining Beam, and having nbminer, gminer, nicehash and f2pool enabled, it will only switch to a different miner or pool if it passes a 10% threshold?

Thanks

Ash

**Comment by RainbowMiner** [comment]
Yes, that would be neat. I will try to figure something out. It is quiet complex, but I am sure I will find a way.

**Comment by acos0874** [comment]
"rework switching prevention"

Is this part of the latest release?

**Comment by RainbowMiner** [comment]
Yes :) we now have a threshold between the current miner's pools and the others. This threshold is decreasing over time with the same SwitchingPrevention function.

**Comment by RainbowMiner** [comment]
Also, the threshold is derived from the ErrorRatio.

**Comment by acos0874** [comment]
Hi, thanks for this. It seems to be working well once the miners have hugged a pool for a while but I seem to be getting frequent switching

![image](https://user-images.githubusercontent.com/42582444/69044873-a3e7d480-09ed-11ea-9d16-2fc182756a53.png)

I suspect this may be due to it ignoring the minimum intervals (mine is set to 5 but I was switching every minute).

Second thing, you said about the threshold is deriver from the errorRatio but I have this turned off because I only really use NIcehash and F2pool and neither of these have an error ratio anyway. Please can you explain how this would work otherwise?

**Comment by RainbowMiner** [comment]
Also, there is another important setting, that has an influence on the pool evaluation: "PoolAccuracyWeight", it's a percentage value 0..100
The higher, the longer it will take for a pool to be replaced, by another. It's basically the following function, that creates the comparison values:

`Pool_Price * ( 1 - MarginOfError * SwitchingPreventionDecayFactor * (PoolAccuracyWeight/100) ) * OutOfSyncPenaltyFactor`

SwitchingPreventionDecayFactor = decreases from 1 down to 0 over time, starting with the last miner switch
OutOfSyncPenaltyFactor = if a pool price/hashrate hasn't changed for ten minutes, this factor will slowly decrease from 1 down to 0 (after one hour)

**Comment by acos0874** [comment]
Excellent. Thank you for the explanation. Sent from Mail for Windows 10 From: RainbowMinerSent: 18 November 2019 11:10To: RainbowMiner/RainbowMinerCc: acos0874; AuthorSubject: Re: [RainbowMiner/RainbowMiner] Percentage threshold for algos with multiple pools and miners (#731) Also, there is another important setting, that has an influence on the pool evaluation: "PoolAccuracyWeight", it's a percentage value 0..100The higher, the longer it will take for a pool to be replaced, by another. It's basically the following function, that creates the comparison values:Pool_Price * ( 1 - MarginOfError * SwitchingPreventionDecayFactor * (PoolAccuracyWeight/100) ) * OutOfSyncPenaltyFactorSwitchingPreventionDecayFactor = decreases from 1 down to 0 over time, starting with the last miner switchOutOfSyncPenaltyFactor = if a pool price/hashrate hasn't changed for ten minutes, this factor will slowly decrease from 1 down to 0 (after one hour)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by RainbowMiner** [comment]
Added: commit be0aaaf64b820f59e868e2bb3368dc1be89425c8 and commit ac334e644ca2df982e38974c9c1b9c190a0c3632
