### ISSUE TITLE
Dual mining eaglesong and ethash

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#732]
Hello, is this enabled for gminer? I'm having a hard time getting it working as per the instructions in the readme.

**Comment by RainbowMiner** [comment]
Please use NBminer for dual mining ETH with Eaglesong.
It's pretty straight forward, except that you will have to supply a username for Eaglesong CKB (from SparkPool, that is the pool I am using, currently) instead of a real mining address, since it is testnet.

**Comment by acos0874** [comment]
What is the correct way to specify I want it to dual mine if I'm using the 'focus wallet' section of the pools config please?

**Comment by RainbowMiner** [comment]
For dual mining, just add "ETH" and "CKB" wallet addresses (username for CKB) in pools.config.txt to some pools. Regarding the focus wallet, I am not quiet sure if this works out for dual mining - I'ld try to put "ETH" as focus wallet in your eth pool and "CKB" in your eaglesong pool section in pools.config.txt to try.
