### ISSUE TITLE
Stable price higher than price

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#734]
If I've understood this correctly, it shouldn't be happening. Please can you confirm?

Currency: "XZC"
Price: 2.22606075613045e-11
StablePrice: 2.7124097320026643e-11
MarginOfError: 0.06829596959072237
Protocol: "stratum+tcp"
Host: "zcoin-eu.mintpond.com"

**Comment by RainbowMiner** [comment]
That's totally ok. The stable price is a moving average, based on 7 days.

What never should happen, that Price_Bias is greater than Price
