### ISSUE TITLE
Heatmyflat level 0.5

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#735]
I love the Heatmyflat setting, it's so incredibly useful for me! What I'm finding is that the best values are 0, 1 and 5. 

5 will give the most economic heating
0 will give the most profitability
1 gives a slight bias to heating over profit. 

I think values 2-4 and especially 6-9 have much less relevance and I'll probably never use them. It would however be really useful to have a value 0.5 as I might want to give slightly less bias towards heating than 1 is currently giving. Please can you add a value between 0 and 1 and add to the localhost? I am finding that this setting makes more sense to have as a lotharithmic scale than a linear scale.

**Comment by RainbowMiner** [comment]
I am happy, that you like that setting :) 
Ok, I'll think about a change to a logarithmic scale.

**Comment by samdave123** [comment]
Either a lotharithmic scale but keeping values 0 5 and 10, or if the values could be 0-100 that might be even better.

The "max revenue" needs to stay as a focal point because that will be crucial when the weather gets really cold.

1 seems to be the best for me at the moment because I gain heating more than proportionately to the loss of profit.

**Comment by samdave123** [comment]
Setting the value to 0.5 in localhost doesn't seem to stick.

**Comment by RainbowMiner** [comment]
Oh. It should. I'll check this.

**Comment by RainbowMiner** [comment]
Found it - I underestimated the automatic typecast of Powershell. It's already fixed in Core.psm1, next release will follow.

**Comment by samdave123** [comment]
It seemss even 0.5 is massively favouring MTP and other high-power algorithms over much more profitable lower-power algorithms. Could the interval change to 0.1 or 0.25 to give slightly less bias towards heating?

**Comment by RainbowMiner** [comment]
Wow, I'll further investigate this :) Eventually, a logarithmic scale would make sense, after all.

**Comment by samdave123** [comment]
I think because revenue can vary so much even when profit is very similar, the value input into the current formulae needs to be very small if you only want a slight bias towards heating than profit.

I've got algorithms which are much less profitable despite having twice the revenue just because they consume three times as much power.

When it gets colder I'll probably just go straight to 5, but right now we're in a weird spot where the extra heat is useful but I'm not willing to sacrifice much profit to get it.

**Comment by samdave123** [comment]
Hmmmm even 0.1 seems to massively favour more heat-intensive algos rather than the most profitable algorithm. 
![image](https://user-images.githubusercontent.com/56473344/69196574-caf5f180-0b26-11ea-9331-17564c6f689e.png)

Out of all those algos, RBM chooses Ethash with a heatmyflat value of 0.1. Either the intervals need to change to 0.01 or perhaps the formulae needs to be changed to give a bit more fine-control.

I'm still going to use 0.1 for now because I need a bit of extra heat, but the bias towards revenue over profit is still a little bit too strong even at 0.1.

**Comment by samdave123** [comment]
I've been thinking of how to rework this to make it simpler and also allow the inverse (more efficient and less power per sat).

Okay so the current calculation is Heat value=revenue-miner fee-powercost*(0.5 - HeatMyFlat/10)

Why not just simplify it as Heat value=revenue-miner fee-(powercost*X) where X is a value between -5 and +5? A slider to change the values in intervals of 0.1 would then allow full control between profit-maximising at 0, max heat at -5 and max efficiency at +5.

**Comment by RainbowMiner** [comment]
Yeah, sounds good to me. I'll implement this - and await your test results, eagerly.

**Comment by samdave123** [comment]
It might be better to have it between -2 and +3 and then just skip straight to -99999 and +99999. The optimal values will be between 0 and 1 for anyone trying to get a bit more heating and 1 and 3 for anyone trying to reduce the heating. -99999 and +99999 would ensure that the abosolute most heat / absolute best efficiency is used.

The values between 0.5 and 1 are where more intervals will be most beneficial as I can then choose to only sacrifice a very tiny amount of profit if another algorithm has significantly more revenue.

**Comment by RainbowMiner** [comment]
Ok, here you go: 58e60823713b4fd55b8b92ecb4edbe036cd061c4

I have implemented another scale, so that a negative value can be avoided.

- add "EnableMiningHeatControl": set to "1" to enable heat control
- add "MiningHeatControl": set to a value from 0 to 5 in steps of 0.1

If enabled, the following formula is being used to calculate:
`Heat value=revenue-miner fee-powercost*(3 - MiningHeatControl)`

- "0" = min. heat
- "2" = max. profit
- "3" = max. revenue, best heat efficiency
- "5" = max.heat

A good start is to try values in the range of 2 to 3

**Comment by samdave123** [comment]
Looks great, can't wait to test it! I'm going to try 0.9 first to try to give a slight edge to heat over profit, but it looks like the night time temperature is going to drop to -0/-1 so I might give 0 a try to warm up my flat on a cold morning.

**Comment by samdave123** [comment]
You say the best values to try are 2-3 but that's just if someone wants to get a bit more heat. 

Other people like Yamani want to reduce heat at times, or when it gets to summer time, values between 1-2 will be better to reduce heat. This new mode is now a cooling mode as well as a heating mode, and the readme should be updated to reflect that.

**Comment by RainbowMiner** [comment]
I have added the two values "EnableMiningHeatControl" and "MiningHeatControl" to the scheduler.config.txt, too.
Leaving them empty will use the global defaults, out of config.txt

**Comment by samdave123** [comment]
I'm finding the miner keeps trying to use these miners which have 0W but are obviously broken. It should be ignoring benchmarks with 0W. See below screenshot.
![image](https://user-images.githubusercontent.com/56473344/69903174-2a0cff00-138e-11ea-9fff-f71a548144bd.png)

I think the problem with the calculation is that the profit-switcher is looking to minimalise cost rather than maximise efficiency. I think it needs to prioritise miners/algos with the highest sat/W rather than the lowest cost.

I also think it would be useful to have an option "do not select unprofitable miners" to enable when heating mode is enabled to prevent extreme cases where power consumption is way too high.
