### ISSUE TITLE
2Miner profit calculations

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#737]
Hello, 

I'm currently using f2pool since it's PPS and it's profit calculations seem fairly accurate. The big problem with f2pool is rejected shares, I'm guessing due to high latency.

Ideally I would like to switch to using 2miners as it has most of the coins I'm trying to mine, however, some of the profit calculations don't seem accurate (e.g. zcoin) or non-existent (e.g. ethereum).

Please can you look into the pricing on their API? Ideally I would not like to pull data from WTM since it lags by up to 10 minutes behind true market data,

Also, CKB needs enabling on 2miners.

**Comment by acos0874** [comment]
Thank you for implementing this so quickly. The calculations seem accurate but unfortunately ckb was missing when I checked.

**Comment by acos0874** [comment]
Sorry CKB is there but the payrate is 0. However, Grin does not appear in the list of pools.

**Comment by RainbowMiner** [comment]
GRIN is fixed, now. For CKB, we will have to wait, until we have got a price at one of the conversion APIs. It's only a matter of time.

**Comment by acos0874** [comment]
Do the prices for 2miners come directly from their own API or does it come from elsewhere?

**Comment by RainbowMiner** [comment]
They do not support earning eastimates, so I calculate them, out of average time to find, hashrate and block reward. For Grin, it is a bit different, since it's a combination of Cuckrood29 and Cuckatoo31, plus, these algorithms.base on cycles.

**Comment by acos0874** [comment]
Is the same true for f2pool?Sent from my Samsung Galaxy S9 - Powered by Three
-------- Original message --------From: RainbowMiner <notifications@github.com> Date: 20/11/2019  00:11  (GMT+00:00) To: RainbowMiner/RainbowMiner <RainbowMiner@noreply.github.com> Cc: acos0874 <acostello0874@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RainbowMiner/RainbowMiner] 2Miner profit calculations (#737) They do not support earning eastimates, so I calculate them, out of average time to find, hashrate and block reward. For Grin, it is a bit different, since it's a combination of Cuckrood29 and Cuckatoo31, plus, these algorithms.base on cycles.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RainbowMiner/RainbowMiner/issues/737?email_source=notifications\u0026email_token=AKE4DLCKPB5A64AOBJZEB5DQUR6BLA5CNFSM4JPDZRI2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEQHEYI#issuecomment-555774561",
"url": "https://github.com/RainbowMiner/RainbowMiner/issues/737?email_source=notifications\u0026email_token=AKE4DLCKPB5A64AOBJZEB5DQUR6BLA5CNFSM4JPDZRI2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEQHEYI#issuecomment-555774561",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RainbowMiner** [comment]
No, f2pool supplies ready made earning estimates. Actually, I think those are a bit exaggerated.

**Comment by acos0874** [comment]
I actually find the f2pool estimates are more accurate. My hashrate is 7.2gh/s on CKB
![image](https://user-images.githubusercontent.com/42582444/69228922-5fd70a00-0b7c-11ea-8ded-de2e591b9b54.png)

Hashrate for 24 hours
![image](https://user-images.githubusercontent.com/42582444/69229247-01f6f200-0b7d-11ea-9311-e8400b50a351.png)

Earnings in last 24 hrs
![image](https://user-images.githubusercontent.com/42582444/69229273-0ae7c380-0b7d-11ea-8a3a-2ba886915508.png)

Calculator
![image](https://user-images.githubusercontent.com/42582444/69229405-43879d00-0b7d-11ea-9098-fee59f783c8a.png)

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/69229541-821d5780-0b7d-11ea-8689-11ae74c614d2.png)
