### ISSUE TITLE
New Rig setup getting error and stuck in loop.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#739]
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/3865351/Logs.zip)
Getting the following when setting up  a new rig.

Use the server's exclusion list? (yes/no) [default=no]: yes
Download server configuration now? This will end the setup. (yes/no) [default=yes]:

WARNING: Get-ServerConfig failed
Error downloading configfiles!

Download server configuration now? This will end the setup. (yes/no) [default=yes]:

WARNING: Get-ServerConfig failed
Error downloading configfiles!

Download server configuration now? This will end the setup. (yes/no) [default=yes]:

**Comment by RainbowMiner** [comment]
Ok, I will check this.

**Comment by acos0874** [comment]
Having the same problem on existing rigs. Get-ServerConfig Failed.

**Comment by RainbowMiner** [comment]
Yes, I changed the API stream technique (it's roughly 10 times faster, now), but caught us a bug. The new StreamWriter sent a byte-order-data block to the beginning, thus breaking the json decoding of Powershell. It's fixed in v4.4.7.1

**Comment by Yamanipanuchi** [comment]
Yup, Confirmed working now. Thanks!
