### ISSUE TITLE
Equihash192 on MPH

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#740]
Sorry for all the requests. Please can you add this?

**Comment by RainbowMiner** [comment]
You are most welcome. I will add this.

**Comment by RainbowMiner** [comment]
It looks like, Equihash192 is not on their API.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/69228217-1934e000-0b7b-11ea-88a5-4bc2e1fcf839.png)
It shows up in Awesome Miner

**Comment by RainbowMiner** [comment]
Looks like Awesome Miner has some pretty old data. It's def. not on MiningPoolHub:
![image](https://user-images.githubusercontent.com/39437538/69238974-7c356f80-0b99-11ea-8043-3a24395ea913.png)

**Comment by RainbowMiner** [comment]
miningpoolstats.stream doen't list it, neither:
https://miningpoolstats.stream/zero

**Comment by acos0874** [comment]
Equihash-ZCL is equihash192 as far as I know.

**Comment by RainbowMiner** [comment]
Oh! So, Zclassic is now on Equihash192? If that's the case, then, yes. I'll check this.

**Comment by RainbowMiner** [comment]
Looks like I have missed that fork :) Yes, it's Equihash 192,7 now. I'll adapt the database accordingly.

**Comment by RainbowMiner** [comment]
Thank you for bringing this up. I am always happy, if someone points out to a fork, I might have missed.
