### ISSUE TITLE
Question about Linux Voltage Control

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#741]
Do locked voltages work when running RBM in Linux? I'm considering trying linux so I can hopefully mine c31 on 8gb cards.

**Comment by acos0874** [comment]
I'm having a really hard time getting any kind of overclocking profile to work in linux. Any help would be appreciated please? RBM doesn't seem to be passing the OCProfile to nvidia-smi

**Comment by RainbowMiner** [comment]
Overclocking in Linux is kind of different. It uses a different set of tools. Did you follow https://github.com/RainbowMiner/RainbowMiner/blob/master/README.md#ubuntu-18x-pre-requesites ? I think, a clue is to use Ubuntu Server version and the Nvidia ppa drivers.
> Running Ubuntu Server and using the Nvidia PPA repository and mine work. I did notice that some cards do not have pre set overclock's (1660 TI).

**Comment by acos0874** [comment]
I did the ppa bit

I then did this...

sudo nvidia-xconfig -a --cool-bits=31 --allow-empty-initial-configuration

But it didn't really seem to do a lot.

I didn't use the server version, is there a way to upgrade without a fresh install?

**Comment by RainbowMiner** [comment]
> I didn't use the server version, is there a way to upgrade without a fresh install?

I fear not, sorry.

**Comment by acos0874** [comment]
Would you mind please giving me the command that linux uses to execute the overclock settings so that I may look into getting the system working without switching to ubuntu server in the first instance?

**Comment by acos0874** [comment]
if ($IsLinux -and $Session.DevicesByTypes.NVIDIA -and $Session.Config.EnableOCProfiles) {
            Invoke-NvidiaSmi -Arguments "-pm 1" -Runas > $null
            Invoke-NvidiaSmi -Arguments "--gom=COMPUTE" -Runas > $null
            if (Test-OCDaemon) {Set-OCDaemon "sleep 1"} else {Start-Sleep 1}
            Invoke-NvidiaSettings -SetPowerMizer
            Invoke-OCDaemon -Quiet
        }

Cool I found this. Now just need to figure out what it's referencing :D

**Comment by acos0874** [comment]
Couldn't figure it out so switching to ubuntu server instead.

**Comment by acos0874** [comment]
I'm now up and running in ubuntu server. Cards are hashing but the OCProfiles still aren't being applied. I got this error when I try to apply the coolbits instruction

![image](https://user-images.githubusercontent.com/42582444/69339206-be73b500-0c5c-11ea-9365-a7bcfe7ac1ec.png)

**Comment by RainbowMiner** [comment]
The tool for setting the oc is nvidia-smi for setting the powerlimit and nvidia-settings for setting core and memory boost.

```
nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffset[2]=100'
nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffset[2]=400'
```
The number behind "gpu:" is the device id, the number behind the command (in square brackets) is the highest PState (depends on the GPU)

**Comment by acos0874** [comment]
Thanks. I'm pretty sure this is in the usr/bin folder, any idea why my OC profiles are firing up correctly?

**Comment by RainbowMiner** [comment]
Did you run `./install.sh` before first start of RainbowMiner?

**Comment by acos0874** [comment]
Yes I followed the instructions to the letter on the github page.

**Comment by acos0874** [comment]
Hi I saw the headless option in the new release. I just tested it and OC seems to be still not working I'm afraid.

**Comment by acos0874** [comment]
Is it possible that having a monitor plugged into one of the GPUs may be causing an issue?

**Comment by acos0874** [comment]
No change.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/69382811-e93b2900-0caf-11ea-8665-e2e7e6837ffd.png)

**Comment by acos0874** [comment]
I was wondering if it is also to do with permissions. I normally run sudo ./start,sh but I tried running ./start.sh (since this is what is said in githubt) and got a lot of permission denied errors. I think ran chmod +x *.sh and tried again but was still getting errors.

**Comment by acos0874** [comment]
I tried running one of the commands you mentioned above whilst navigated to the /usr/bin folder where nvidia-settings is located and I got this error message...

![image](https://user-images.githubusercontent.com/42582444/69383496-af6b2200-0cb1-11ea-8c4d-bd603de63c64.png)

**Comment by RainbowMiner** [comment]
Ok, eventually your permissions are messed up, now. Try to reinstall RainbowMiner into a different path and run ./install.sh and ./start.sh without sudo. 
Eventually, try to enter 
```
export DISPLAY=:0
```
.. before testing the nvidia-settings on the command line

**Comment by gurkburk76** [comment]
I have a rig with amd cards (570 4mb) and i'm getting the impression that i can't oc/powerlimit the cards in rbm, do i have to resort to modding my bios to do that? (running linux)
