### ISSUE TITLE
Rainbowminer found not running this morning, is there a way to have Windows restart it if it isn't running?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#742]
Rainbowminer found not running this morning, is there a way to have Windows restart it if it isn't running?  I checked the online Monitor and it said last seen 1 hr ago so that isn't so bad.

I already use the autostart at boot part of Windows.

Here is my diag file just incase there was a case for Rainbowminer to stop running.
[debug_2019-11-21.zip](https://github.com/RainbowMiner/RainbowMiner/files/3874966/debug_2019-11-21.zip)

**Comment by RainbowMiner** [comment]
It looks like it has just - stopped. There is no error massage. Very weird. I will try to find a way for an external Watchdog to monitor RainbowMiner.

**Comment by Yamanipanuchi** [comment]
I have had this happen before also, and I thought about asking for this feature. But it scared me thinking it might put my system into a perpetual loop. Might be solved with say a 5 minute timer before it re-starts the system?

**Comment by samdave123** [comment]
I had this happen a few days ago. RBM seems to go very sluggish before stopping entirely. It didn't seem to be an issue with the miners but RBM itself.

**Comment by RainbowMiner** [comment]
You don't happen to have a Debug file, that would cover this crash?

**Comment by samdave123** [comment]
I'm at work now, but can check tonight. Can you tell me exactly what to look for? On 27 Nov 2019 2:12 pm, RainbowMiner <notifications@github.com> wrote:You don't happen to have a Debug file, that would cover this crash?

**Comment by samdave123** [comment]
Just noticed this and my mining rig was acting VERY sluggish. Memory leak? https://cdn.discordapp.com/attachments/513280353239171095/649301026377302066/unknown.png

**Comment by RainbowMiner** [comment]
Yes, that looks like a memory leak. I just discovered one memory leak inside the localhost API. Have you had a browser window opened?

**Comment by samdave123** [comment]
I got home and opened a browser window, but I haven't had one open all day.

**Comment by RainbowMiner** [comment]
@samdave123 Could you create a Debug file and send it to me?

**Comment by samdave123** [comment]
> 
> 
> @samdave123 Could you create a Debug file and send it to me?

Nope sorry I don't know how to do that.

**Comment by RainbowMiner** [comment]
It's simple: either open http://localhost:4000 in your browser and click "Debug file" or directly click here (if you are on that miner machine): http://localhost:4000/debug

![image](https://user-images.githubusercontent.com/39437538/69765855-de800880-1175-11ea-9bd4-0b464c6a0d77.png)

**Comment by samdave123** [comment]
[debug_2019-11-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/3899133/debug_2019-11-27.zip)

**Comment by RainbowMiner** [comment]
Thank you very much for bringing this up! I have discovered an ancient memory leak inside the API handling. It should be fixed with the new version v4.4.7.7, so I recommend an update.
