### ISSUE TITLE
Zergpool(coins) is there a way to have auto penalty for certain Algos that overestimate the Profit?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#744]
Has anyone figured out what Penalty to use on Zergpool and Zergpoolcoins?  I am only using those pools and Nicehash and MRR.  So Nicehash should be accurate and MRR will be whatever it gets rented for.  I tried 45 and Zergpool(coins) still runs most of the time.

An Auto Penalty per Algo and changes as the profits get more accurate or less accurate?

**Comment by RainbowMiner** [comment]
There is already an autocorrect in place, that should keep track and adjust the estimates. There is only one thing for it to function: estimate_current needs to be used (in fact, that is the default)

In my experience, a 12 or 15% static penalty for Zergpool, together with the autoadjusting estimates do a pretty decent job. Of course there are always really really spammy coins, that manage to mess up. 
So another good idea is, to limit ZergPoolCoins to the good paying coins.

**Comment by samdave123** [comment]
Are you saying error ratio only works with estimate_current? I'm using it with minimum-3 at the moment. It might not be the most accurate, but I'm trying to eliminate the highly volatile and low-paying coins.

I really hate using static penalties for entire multipools because I don't see how that's a good way of doing it.

**Comment by RainbowMiner** [comment]
> Are you saying error ratio only works with estimate_current? I'm using it with minimum-3 at the moment.

Actually, yes. These are the three settings, that turn auto-correct off: "actual_last24h","minimum-3","minimum-2h".

> I really hate using static penalties for entire multipools because I don't see how that's a good way of doing it.

In my experience, an additional static penalty for multipools is quiet useful to cover the risk of friction losses during the auto-exchange process.

**Comment by samdave123** [comment]
> In my experience, an additional static penalty for multipools is quiet useful to cover the risk of friction losses during the auto-exchange process.

I'd rather see friction losses auto-measured and penalty dynamically adjusted than setting a static penalty. Surely the correct penalty will vary depending on coin and even vary over time?

**Comment by acos0874** [comment]
Error ratio (which accounts for actual luck/orphans)
+ 12% penalty (which accounts for exchange fees and inflated estimates)
 + switch penalty 2 (which avoids too much switching)
 + minute_5 (which avoids profit spikes of spammy coins)
= winning combo for me at the moment
