### ISSUE TITLE
Getting this error on two Systems

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#745]
Been getting this on two system consistently. Deleted the Config and Re-built it with the same issue.

Finished waiting - starting next run
The operation was canceled.
At /home/user/RainbowMiner/Include.psm1:6199 char:36
+         if ($ErrorMessage -ne '') {throw $ErrorMessage}
+                                    ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (The operation was canceled.:String) [], RuntimeException
+ FullyQualifiedErrorId : The operation was canceled.

user@t5610:~/RainbowMiner$

**Comment by Yamanipanuchi** [comment]
[debug_2019-11-21.zip](https://github.com/RainbowMiner/RainbowMiner/files/3878201/debug_2019-11-21.zip)

What is odd, Is that the mining binary keeps running in the background. Just the script error's out.

**Comment by RainbowMiner** [comment]
Very weird, in deed! I will have a look into it asap.

**Comment by RainbowMiner** [comment]
Since when is this error happening?

**Comment by RainbowMiner** [comment]
Ok, I think, I have found the free running geturl. It will be fixed within the next couple hours. Until then, you might want to switch those two systems to "standalone".
