### ISSUE TITLE
Possible 2Miners API change for RVN?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#746]
Lastnight all my systems stopped showing RVN as a minable option 2miners, Balances show up. No changes by me, Multiple systems.

Tried loading a backup config to make sure. This did not make a difference.

**Comment by RainbowMiner** [comment]
Ok, I'll have a quick look.

**Comment by RainbowMiner** [comment]
Very weird! RVN on 2miners appears and works on my machines. Btw, I found a small bug in the 2miners pool modules, that would mix up the regions, but should not cause any trouble.
Is 2miners+RVN on the localhost:4000 All Pools page?

**Comment by Yamanipanuchi** [comment]
It is in the All Pools on localhost. But in the screenshot. Even if there was a large drop in value it would usually show up somewhere in this list.

![image](https://user-images.githubusercontent.com/4724631/69682150-56124280-1065-11ea-8098-56ce9c6d92b5.png)

**Comment by Yamanipanuchi** [comment]
Different Machine... Show in Active Miners X16R2 as most profitable... 

![image](https://user-images.githubusercontent.com/4724631/69688916-49e5af80-107c-11ea-9424-90509b871f89.png)


Script screen show NiceHash as most profitable for X16R2, But no 2Miners...

![image](https://user-images.githubusercontent.com/4724631/69688982-7994b780-107c-11ea-8729-c4199eabe02c.png)

[debug_2019-11-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/3894862/debug_2019-11-20.zip)

Am I just missing a comma (,)someplace, Or a quote (")?

**Comment by Yamanipanuchi** [comment]
I shut nicehash off, And it still doesnt show up.

**Comment by RainbowMiner** [comment]
Looking into your config, I did not found 2Miners setup:
in config.txt it is missing `"2Miners"`
```
  "PoolName": "MiningRigRentals,NiceHash,ZergPool,ZergPoolCoins",
```

in pools.config.txt
```
    "2Miners": {
      "BTC": "XXX",
      "Worker": "rainbowminer",
      "Algorithm": "",
      "ExcludeAlgorithm": "",
      "CoinName": "",
      "ExcludeCoin": "",
      "CoinSymbol": "",
      "CoinSymbolPBM": "",
      "ExcludeCoinSymbol": "",
      "MinerName": "",
      "ExcludeMinerName": "",
      "FocusWallet": "",
      "AllowZero": false,
      "EnableAutoCoin": false,
      "EnablePostBlockMining": false,
      "DataWindow": "estimate_current",
      "Penalty": "0.0",
      "MaxMarginOfError": "100.0",
      "StatAverage": "Minute_10"
    },
```
.. it is missing the `"RVN": "yourravenaddress",`

**Comment by RainbowMiner** [comment]
Oh. It might be the case, that you have uploaded an old debug file `debug_2019-11-20.zip`

**Comment by Yamanipanuchi** [comment]
I have been using the "EnableAutoCoin" feature recently due to me shifting around on pools testing things. I am fairly nailed down on my pools now. So Ill try added those lines back in. Below is the correct config...

[debug_2019-11-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/3897366/debug_2019-11-27.zip)

**Comment by Yamanipanuchi** [comment]
Also using  "EnableAutoPool": "0", in coins.config.txt makes one easy place to turn on and off coins.

**Comment by Yamanipanuchi** [comment]
I added the "RVN": "$RVN", line to pools.config.txt. It showed up for a short moment and now is gone again.

**Comment by Yamanipanuchi** [comment]
I enabled XWP on HeroMiners and it doesn't show up either.  Yet WOW and LOKI show up in the list.

**Comment by Yamanipanuchi** [comment]
So now I disabled NiceHash and still have the "RVN": "$RVN" in pools.config.txt. RVN shows up and it is trying to mine it, but I am getting 0h/s on speed and its been going to over 10 minutes.

![image](https://user-images.githubusercontent.com/4724631/69739496-ad0f2a80-10ec-11ea-843d-f14f24b7e265.png)

**Comment by Yamanipanuchi** [comment]
I've been watching it, I have it all back to how I originally had it and I see RVN-2Miners show up in the list every once and while and then it disappears.

**Comment by Yamanipanuchi** [comment]
Removed 2Miners and added RevenMiner in and works perfectly. I can just move to this pool for now.. I have a small balance on 2Miners.. But..

**Comment by RainbowMiner** [comment]
There is one clue: 
> RVN shows up and it is trying to mine it, but I am getting 0h/s on speed and its been going to over 10 minutes

The watchdog will most likely disable RVN on 2Miners, if that happens. Could you please send me a Debug file? Or extract the command line RainbowMiner has been using to mine RVN on 2miners.

**Comment by Yamanipanuchi** [comment]
[debug_2019-11-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/3898806/debug_2019-11-27.zip)

**Comment by Yamanipanuchi** [comment]
I enabled XWP also, And it does not show up in the list at all.. And according to the stats I should be mining it...

**Comment by RainbowMiner** [comment]
It looks like, some of the 2miners stratum servers are down, even though their port addresses are marked as online. I'll post a fix for that, but first I have to write a script, that pings all stratums, so that I can see, which ones are dead.

**Comment by Yamanipanuchi** [comment]
This makes sense... I think the XWP on Herominers is a separate issue..

**Comment by Yamanipanuchi** [comment]
It seems when NiceHash is enabled RVN completely disappears. I have it set to RavenMiner right now... And I have XWP on HeroMiners enabled.

![image](https://user-images.githubusercontent.com/4724631/69762188-56224900-111e-11ea-9510-8d6de60024ef.png)

**Comment by Yamanipanuchi** [comment]
With NiceHash Removed...

![image](https://user-images.githubusercontent.com/4724631/69762448-10b24b80-111f-11ea-8084-987b1c51413c.png)

Still no XWP. But RVN is there...

**Comment by RainbowMiner** [comment]
Now, the 2miners problem should be solved, with the two commits, above.

**Comment by RainbowMiner** [comment]
> It seems when NiceHash is enabled RVN completely disappears. I have it set to RavenMiner right now... And I have XWP on HeroMiners enabled.

Nicehash/RVN is on the list of your screenshot: line number three "x16rv2"

**Comment by RainbowMiner** [comment]
If you want a quick fix for 2miners: directly download the 2Miners.ps1 into your Pools folder

[2Miners.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/2Miners.ps1) - use "right-click" and "Save as.."

**Comment by Yamanipanuchi** [comment]
Yes, For Nicehash. But 2Miners (We know why) OR RavenMiner are not there along with XWP-HeroMiners. If I remove Nicehash RavenMiner shows up, But XWP never shows up no matter how I change the settings.

**Comment by Yamanipanuchi** [comment]
In this screen shot I have both RVN-RavenMiner and XWP-HeroMiners enabled. But they are no where on the list. If I disable NiceHash then RVN will show up.. XWP never shows up.

![image](https://user-images.githubusercontent.com/4724631/69766402-9a1c4a80-112c-11ea-934b-f57b2e0f02a9.png)

**Comment by Yamanipanuchi** [comment]
With NiceHash Removed.

![image](https://user-images.githubusercontent.com/4724631/69766438-d3ed5100-112c-11ea-8751-d2e4dde7bef4.png)

**Comment by RainbowMiner** [comment]
> In this screen shot I have both RVN-RavenMiner and XWP-HeroMiners enabled. But they are no where on the list. If I disable NiceHash then RVN will show up.. XWP never shows up.

.. that's normal behavior: the list shows the best paying pool for each algorithm, only. So if Nicehash pays better than Ravenminer, Nicehash x16rv2 will be on the list. If Ravenminer pays better than Nicehash, Ravenminer x16rv2 will be on the list.

**Comment by Yamanipanuchi** [comment]
Ohhh... Well.. Then... Let me remove my shoe from my mouth then....

**Comment by Yamanipanuchi** [comment]
So, Then XWP.. Its just missing all together...

**Comment by RainbowMiner** [comment]
Leaves us with the question, why your Herominers XWP is missing. So it's either a watchdog problem, or the pool's data is out of sync. This can be checked. 
What do
 http://localhost:4000/watchdogtimers
and
 http://localhost:4000/allpools
say?

**Comment by Yamanipanuchi** [comment]
![image](https://user-images.githubusercontent.com/4724631/69766663-d308ef00-112d-11ea-8464-b9f43a21e382.png)
[allpools.txt](https://github.com/RainbowMiner/RainbowMiner/files/3899176/allpools.txt)

**Comment by Yamanipanuchi** [comment]
Interesting, When one of my systems went into DEV mode HeroMiners-Swap shows up....

![image](https://user-images.githubusercontent.com/4724631/69828395-97733100-11d0-11ea-9717-a242b0412cfb.png)

**Comment by Yamanipanuchi** [comment]
And now SWAP is showing up...
