### ISSUE TITLE
Linux AMD card room-smi read out don't work

### ISSUE THREAD

**Issue by qinapps** [RainbowMiner/RainbowMiner#749]
on Linux with AMD cards I have: WARNING: Could not read power data from AMD

I see the rocm-smi gives following values:
========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr  SCLK     MCLK     Fan     Perf  PwrCap  VRAM%  GPU%  
0    38.0c  155.0W  1802Mhz  1001Mhz  21.96%  auto  250.0W   48%   100%  
================================================================================
==============================End of ROCm SMI Log ==============================

But in Include.psm1 looks for the values: Temperature, Power, Fan.

**Comment by qinapps** [comment]
the json report is:
{"card0": {"Fan Speed (%)": "45", "Average Graphics Package Power (W)": "222.0", "Temperature (Sensor mem) (c)": "79.0", "Fan Speed (level)": "117", "Temperature (Sensor junction) (c)": "103.0", "Temperature (Sensor edge) (c)": "77.0"}}

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I will check.

**Comment by RainbowMiner** [comment]
Could you double-check, that you have been using the following command-line?
```
rocm-smi -f -t -P --json
```
.. if not, please send me the output, if yes, please let me know.

**Comment by qinapps** [comment]
Creat Thx a lot working now

**Comment by qinapps** [comment]
ooh I realise on AMD is $_.DataMax.Clock, _.DataMax.ClockMem ,$_.Data.PowerLimitPercent not set, can you add this info pls?

rocm-smi -a --json is;
{"card1": {"dcefclk clock level": "0", "fclk clock speed": "1226Mhz", "fclk clock level": "7", "mclk clock speed": "1001Mhz", "Temperature (Sensor edge) (c)": "55.0", "Unique ID": "3d02606173c71c2c", "mclk clock level": "2", "Temperature (Sensor mem) (c)": "62.0", "Serial Number": "N/A", "pcie clock level": "1", "Fan Speed (level)": "188", "dcefclk clock speed": "358Mhz", "pcie clock speed": "5.0GT/s, x1 308Mhz", "sclk clock speed": "1774Mhz", "Voltage (mV)": "1043", "socclk clock level": "7", "GPU memory use (%)": "27", "GPU ID": "0x66af", "GPU OverDrive value (%)": "0", "Temperature (Sensor junction) (c)": "74.0", "sclk clock level": "7", "socclk clock speed": "972Mhz", "Performance Level": "manual", "GPU Memory OverDrive value (%)": "0", "Max Graphics Package Power (W)": "250.0", "Average Graphics Package Power (W)": "154.0", "PCIe Replay Count": "0", "Fan Speed (%)": "73", "GPU use (%)": "100"}}

**Comment by qinapps** [comment]
I now this is a harden, can you add for and memory tweak? https://github.com/Eliovp/AMDMemoryTweakXL
