### ISSUE TITLE
Download in progress never stop

### ISSUE THREAD

**Issue by qinapps** [RainbowMiner/RainbowMiner#752]
On Linux i have the message that is 5 miners left to download. I think they are some typos in the download address. I highly recommend to remove the download address to a separate file, for example in Bminer.ps1 is the uri defined as "$URI = "https://github.com/RainbowMiner/miner-binaries/releases/download/v15.8.7-bminer/bminer-v15.8.7-6831c33-amd64.tar.xz". With a separate include file would make the debugging much easier.

**Comment by RainbowMiner** [comment]
Could you please open http://localhost:4000/downloadlist (or http://<youripaddress>:4000/downloadlist and upload what you see?

**Comment by qinapps** [comment]
Here is the list:

  |  
-- | --
0 |  
URI | "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.3.1-ccminermtp/ccminermtp-v1.3.1-linux-cuda101.7z"
Path | "/root/RainbowMiner/Bin/NVIDIA-CcminerMTP/ccminer"
Searchable | true
IsMiner | true
1 |  
URI | "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.83-gminer/gminer_1_83_linux64.tar.xz"
Path | "/root/RainbowMiner/Bin/GPU-Gminer/miner"
Searchable | true
IsMiner | true
2 |  
URI | "https://github.com/RainbowMiner/miner-binaries/releases/download/0.9.2-lolminer/lolMiner_v092_Lin64.tar.gz"
Path | "/root/RainbowMiner/Bin/Equihash-lolMiner/lolMiner"
Searchable | true
IsMiner | true
3 |  
URI | "https://github.com/RainbowMiner/miner-binaries/releases/download/v8.21r17kotov2-ccminerklaust/ccminer-KlausT-8.21-mod-r17-koto-sapling-2.tar.7z"
Path | "/root/RainbowMiner/Bin/NVIDIA-YesCryptR8/ccminer"
Searchable | true
IsMiner | true
4 |  
URI | "https://github.com/RainbowMiner/miner-binaries/releases/download/v2.10.8-fireice/xmr-stak-linux-2.10.8-cpu_opencl-amd.tar.xz"
Path | "/root/RainbowMiner/Bin/AMD-FireIce/xmr-stak"
Searchable | true
IsMiner | true
5 |  
URI | "https://github.com/RainbowMiner/miner-binaries/releases/download/v2.10.8-fireice/xmr-stak-linux-2.10.8-cpu_cuda-nvidia.tar.xz"
Path | "/root/RainbowMiner/Bin/NVIDIA-FireIce/xmr-stak"
Searchable | true
IsMiner | true

**Comment by RainbowMiner** [comment]
Ok, thank you. I'll double-check the packages. Did you try to restart RainbowMiner? Rarely the Downloader crashes and blocks all progress.

**Comment by RainbowMiner** [comment]
Found it. I forgot to adapt the CcminerMTP 1.3.1 binary paths, it is fixed, now. I will push a new release today. In the meantime you could download [CcminerMTP.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Miners/CcminerMtp.ps1) directly into your Miners folder (use right-click, save as)

**Comment by qinapps** [comment]
thx. its looks that also with cpuminer is a problem. /v3.10.0-jayddee/cpuminer-opt-3.10.0-linux.7z

**Comment by RainbowMiner** [comment]
That one should not have a problem. Is it blocking the download, too? If yes, what does the  http://localhost:4000/downloadlist say? Or is it causing different problems?

**Comment by qinapps** [comment]
[
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v8.21r17kotov2-ccminerklaust/ccminer-KlausT-8.21-mod-r17-koto-sapling-2.tar.7z",
    "Path": "/root/RainbowMiner/Bin/NVIDIA-YesCryptR8/ccminer",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.83-gminer/gminer_1_83_linux64.tar.xz",
    "Path": "/root/RainbowMiner/Bin/GPU-Gminer/miner",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/0.9.2-lolminer/lolMiner_v092_Lin64.tar.gz",
    "Path": "/root/RainbowMiner/Bin/Equihash-lolMiner/lolMiner",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v2.10.8-fireice/xmr-stak-linux-2.10.8-cpu_opencl-amd.tar.xz",
    "Path": "/root/RainbowMiner/Bin/AMD-FireIce/xmr-stak",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v2.10.8-fireice/xmr-stak-linux-2.10.8-cpu_cuda-nvidia.tar.xz",
    "Path": "/root/RainbowMiner/Bin/NVIDIA-FireIce/xmr-stak",
    "Searchable": true,
    "IsMiner": true
  }
]
[
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v3.10.0-jayddee/cpuminer-opt-3.10.0-linux.7z",
    "Path": "/home/prospector/RainbowMiner/Bin/CPU-JayDDee/cpuminer-avx2",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v8.21r17kotov2-ccminerklaust/ccminer-KlausT-8.21-mod-r17-koto-sapling-2.tar.7z",
    "Path": "/home/prospector/RainbowMiner/Bin/NVIDIA-YesCryptR8/ccminer",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.83-gminer/gminer_1_83_linux64.tar.xz",
    "Path": "/home/prospector/RainbowMiner/Bin/GPU-Gminer/miner",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v2.10.8-fireice/xmr-stak-linux-2.10.8-cpu_cuda-nvidia.tar.xz",
    "Path": "/home/prospector/RainbowMiner/Bin/NVIDIA-FireIce/xmr-stak",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v2.10.8-fireice/xmr-stak-linux-2.10.8-cpu.tar.xz",
    "Path": "/home/prospector/RainbowMiner/Bin/CPU-FireIce/xmr-stak",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v3.8.8.1m4-nosuch/cpu-nosuch-m4-ubuntu18.7z",
    "Path": "/home/prospector/RainbowMiner/Bin/CPU-Nosuch/cpuminer-avx2",
    "Searchable": true,
    "IsMiner": true
  }
]

**Comment by RainbowMiner** [comment]
In this list, it's always the first entry, that blocks the download. I turns out, that the file is not a tar file, but a 7z packed file. It should be fixed by now.
