### ISSUE TITLE
ADD please Hashcity pool

### ISSUE THREAD

**Issue by petrovsky34** [RainbowMiner/RainbowMiner#753]
hashcity.org

**Comment by RainbowMiner** [comment]
Ok, I'll have a look

**Comment by petrovsky34** [comment]
Thanks)))))))))))

пт, 6 дек. 2019 г., 13:07 RainbowMiner <notifications@github.com>:

**Comment by petrovsky34** [comment]
I'll be looking forward to it)))

**Comment by petrovsky34** [comment]
))))))))))))))))))))))))))))))))))))
