### ISSUE TITLE
Issue with CPU Mining Threads

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#754]
Trying cpu mining for the first time and rainbowminer doesn't seem to be recognizing 

"CPUMiningThreads": 24,

It only Benchmarks with 12
[debug_2019-12-07.zip](https://github.com/RainbowMiner/RainbowMiner/files/3934871/debug_2019-12-07.zip)

**Comment by RainbowMiner** [comment]
For CPU mining, you have these two options:
```
  "CPUMiningThreads": 24,
  "CPUMiningAffinity": "0x00555555",
```

The CPUMiningAffinity describes on which Cores/Virtual Cores the miner will be started. It's a binary number:
0x00555555 = 010101010101010101010101 = Core 0,2,4,6,8,10,12 .. 22

I do not recommend blocking all cores with mining. Leave at least on (virtual) core open. Try:

0x00FFFFFE = 111111111111111111111101 = Core 0,2,3,4,5,6 .. 23

**Comment by jch9678** [comment]
I had tried messing with Affinity but still didn't seem to work, I probably used a bad hex number.  I tried your suggestion 0x00FFFFD and randomx worked with Srbminer-multi right away but I had to manually delete the config files for xmrig to work.  It looks like rainbow miner created a backup of ANY-Xmrig and started all over.

Incidentally srb-miner says it's using 24 threads but only 23 are actually used, also it doesn't look like it's compatible with nicehash or maybe a setting is wrong.

Seems to be working now, thank you, cpu mining is going to take time to get  used to.

**Comment by RainbowMiner** [comment]
I have updated the Xmrig API, so that the CPU config file names now contain the affinity string, as well. With that, you will not need to delete the config files, in case you change the affinity in the future.

**Comment by jch9678** [comment]
Thank you for the update. Is it possible this could've broken
srbminer-multi. Benchmarking did not work with affinity ffffff

**Comment by RainbowMiner** [comment]
The update should have no impact on Srbminer. Could you upload a Debug file? I will have a look.

**Comment by jch9678** [comment]
[debug_2019-12-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/3937696/debug_2019-12-08.zip)
Here it is.

**Comment by RainbowMiner** [comment]
Use `"0xFFFFFF"` in config.txt - note the "0x" in front of the hexadecimal number. I will add some extra syntax check in the next version, so that it will work with and without that 0x, in the future.

**Comment by jch9678** [comment]
Thanks for the suggestion.
