### ISSUE TITLE
Error message "System.Decimal"

### ISSUE THREAD

**Issue by exilebg** [RainbowMiner/RainbowMiner#756]
I've been getting the following error lately:

```
Cannot convert value "8.04569302377751E+28" to type "System.Decimal". Error: "Value was either too large or too small for a Decimal."
At C:\RainbowMiner\Include.psm1:1315 char:17
+                 [PSCustomObject]@{
+                 ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastIConvertible
```

**Comment by RainbowMiner** [comment]
I see, I had this for some rounds, too. I think, it is a problem with one miner's API (as far as I remember, it was a MiniZ issue). Could you zip the Stats\Miners folder and upload it here?

**Comment by exilebg** [comment]
Here it is, if you still need it...
[Miners.zip](https://github.com/RainbowMiner/RainbowMiner/files/3936686/Miners.zip)

**Comment by RainbowMiner** [comment]
Thank you very much, it looks like, it's a floating point overflow happening to "Ratio_Average" in the stat file. Since this value is of pure statistical nature and does not have a real purpose, I decided to remove it (see the above commit). This should get rid of the error.

**Comment by exilebg** [comment]
Thank you.
