### ISSUE TITLE
Isuue: problem with AMD GPUs

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#76]
I loaded rainbow onto my mixed rig with 4 1070 and one vega56 modded. I started the app, it started to download a miner and bsod with stop code thread stuck in device driver. Im going to restart and see if it happens again.

**Comment by Byrd1083** [comment]
I'm back up and running now but it through this upon launching Rainbow.

![image](https://user-images.githubusercontent.com/42227809/44947484-6edc6b80-adc2-11e8-82bb-6579e660ddd0.png)

**Comment by Byrd1083** [comment]
I have no idea why this rig is has errors at startup. The other 2 do not do this.

![image](https://user-images.githubusercontent.com/42227809/44947609-3e95cc80-adc4-11e8-8958-f4762b57645a.png)

**Comment by Byrd1083** [comment]
So, I deleted the entire app and reinstalled from scratch with your master file. More errors.

![image](https://user-images.githubusercontent.com/42227809/44947665-a00a6b00-adc5-11e8-888c-e02ed746979d.png)

**Comment by Byrd1083** [comment]
Wierd thing is rainbow does skip over it and continue to download miners and try to benchmark.

**Comment by Byrd1083** [comment]
![image](https://user-images.githubusercontent.com/42227809/44947737-a5b48080-adc6-11e8-8e37-fdd8836e2838.png)

**Comment by Byrd1083** [comment]
Just to do it, I reinstalled powershell 6.04. Still get errors.

![image](https://user-images.githubusercontent.com/42227809/44947905-1fe60480-adc9-11e8-8fec-171a41da6466.png)

**Comment by RainbowMiner** [comment]
Oh no! Did you load the master.zip? This is under development, at the moment.
Please use the last release.

RBM

**Comment by Byrd1083** [comment]
Okay I'll retry. However, the first time I loaded rainbow from my 1080 ti test rig to this 5x rig it still through errors. The first 2 screen shots were as such. It was not master file with those screen shots. It also bsod on me the 1st run upon initialization of configs. I could not retrieve log since bsod.

**Comment by RainbowMiner** [comment]
Ya, I found a problem with the AMD functions. It will be fixed asap. The next release will be there in an hour.

RBM

**Comment by RainbowMiner** [comment]
The new release is published. I fixed a bit of code within the AMD watt reader. Let's hope it is running now. Please let me know, if not. I would be greatful, if you send a zip of the Logs directory, in case of error.

RBM

**Comment by Byrd1083** [comment]
I will test with my vega56 as soon as we can get a stable release for my nvidia rigs ;-)

**Comment by RainbowMiner** [comment]
The current release should run stable on the Nvidia rigs. I hope. Desperatly :-)

RBM

**Comment by r0dn0r** [comment]
I get this error for my AMD GPU:

```
Cannot convert value "GPU1 " to type "System.Int32". Error: "Input string was not in a correct format."
At C:\Users\r0dn0r\Programs\RainbowMiner\Include.psm1:1147 char:95
+ ...          = [int]$($null = $_.GpuId -match "&BUS_(\d+)&"; $matches[1])
+                                                              ~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastFromStringToInteger
```

**Comment by Byrd1083** [comment]
Testing latest version now with vega56 mixed rig. It is working without errors. However, I like to view the benchmarking hash rate with the miner windows open to ensure cards are hooked right. The window for nvidia and cpu opened but there is no miner window open for amd.
