### ISSUE TITLE
MRR rental since 8:15am pst is not being picked up by RBM?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#760]
MRR rental since 8:15am pst is not being picked up by RBM?
[debug_2019-12-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/3952838/debug_2019-12-11.zip)

**Comment by paulpoco** [comment]
Ok I see my MRR rental shows "Rentor Pool Offline" so this probably not RBM.

I have seen this a few rentals ago, Shark123 had 48hrs of this and I still got paid.

**Comment by paulpoco** [comment]
@RainbowMiner   Ok it still isn't picking up the rental.  The Rental pool is online.
[debug_2019-12-11 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/3953481/debug_2019-12-11.1.zip)

**Comment by RainbowMiner** [comment]
Weird thing! Normally that is related to a renters pool issue. Which algorithm did the renter buy?

**Comment by paulpoco** [comment]
@RainbowMiner Neoscrypt.

**Comment by paulpoco** [comment]
@RainbowMiner the same Renter rented again, he got no hash for 48hrs the previous rental.  Must be some automated script as I got no communication from Renter yet.  Left several messages but no response from Renter.
![Screenshot_20191213-175824_Chrome](https://user-images.githubusercontent.com/801414/70841866-ae21a680-1dd2-11ea-83fb-dd79aa05af8a.jpg)

**Comment by paulpoco** [comment]
I noticed a pattern, every 15 min.  How does RBM retry the rental on MRR?  How often?
![Screenshot_20191213-183213_Chrome](https://user-images.githubusercontent.com/801414/70842337-3144fb80-1dd7-11ea-8ae8-c77a9a8e451f.jpg)

**Comment by RainbowMiner** [comment]
It is exactly every 15 minutes.
If the miner fails to connect or gets rejected shares, only for some time, it falls back to normal mining for 15 minutes. Then it tries again. With that, you do not loose any mining time, if a renter messes up the pool setup (automated scripts do this, from time to time)

**Comment by paulpoco** [comment]
@RainbowMiner this Shark123 sure going to be pissed when they figures it out.

I just send a communication every now and then that their rental pool is off line.

**Comment by RainbowMiner** [comment]
Ah! Actually, Shark123 is a pretty well known figure at MRR. I had the pleasure for some rentals myself. It's a renter who uses a bot script to rent and very often connects to spammy pools and coins, that then causes a lot of failures at our rigs. So, as long as you get paid, I would not mind. Anyway, RainbowMiners tries to make the best out of it by mining for you, during the waiting times.

**Comment by paulpoco** [comment]
@RainbowMiner yes I got paid for MRR and other pools at the same time for more than 96 hours.

Closing as this is Renter Pool issue.
