### ISSUE TITLE
Miner Switch Fidelity is not working

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#761]
I currently have the value set at 10. Doesn't seem to working correctly.

![image](https://user-images.githubusercontent.com/42582444/70749948-59742200-1d25-11ea-8a2c-d3a4fda7ba57.png)

**Comment by RainbowMiner** [comment]
Which config parameter did you set exactly?

**Comment by acos0874** [comment]
"SwitchingPrevention": 2,
  "PoolSwitchingHysteresis": 10,
  "MinerSwitchingHysteresis": 10,

**Comment by acos0874** [comment]
From the pools file...

"SwitchingHysteresis":  ""

**Comment by acos0874** [comment]
OH I think I might have misunderstood the principal of hysteresis? Is the lower the number the less it will switch?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/70887990-235dc900-1fd7-11ea-9d69-9f6e62b55176.png)
I tried it with a lower number and still doesn't appear to be working.

**Comment by acos0874** [comment]
Please can you clarify how this is intended to work because I still get a lot of switching when more than one miner is enabled for an algo and there is not a clear leader in terms of profitability?
