### ISSUE TITLE
Error every once and while, Does not stop script

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#762]
I get the following error on all my Windows Miners, It shows up what seems to be ever 5 ish minutes.

Finished waiting - starting next run
Get-Date : Cannot bind parameter 'Date'. Cannot convert value "" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
At C:\RainbowMiner\Include.psm1:1536 char:158
+ ... [TimeSpan]::FromSeconds($DateTime)} else {(Get-Date $DateTime).ToUniv ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetDateCommand

**Comment by RainbowMiner** [comment]
Thank you, I will have a look.

**Comment by RainbowMiner** [comment]
Ok, I know now. Which pools are enabled?

**Comment by Yamanipanuchi** [comment]
Sorry so late on the reply.. If you still need it..

  "PoolName": "HeroMiners,2Miners,F2pool,RavenMiner,NiceHash",

**Comment by Yamanipanuchi** [comment]
I am fairly certain this showed up before F2Pool was added.

**Comment by RainbowMiner** [comment]
Thank you! I'll check now.

**Comment by RainbowMiner** [comment]
F2pool uses a different function to calculate the payments array, so it's not the cause. I have checked Herominers, 2Miners, Ravenminer, all look ok. Leaves us with Nicehash. Do you use the Nicehash's internal mining address or an external address?
