### ISSUE TITLE
Error on Ubuntu 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#763]
![image](https://user-images.githubusercontent.com/1572453/70823731-3fc6ef00-1da6-11ea-9d49-9721939401c2.jpg)
I do not understand. All was well. Then for no reason it just died. Even tried reinstalling everything but the OS

**Comment by RainbowMiner** [comment]
Do other machines, that are connected to the same server, run fine?

**Comment by RainbowMiner** [comment]
Eventually, if your server is not password protected, you might want to try:
http://104.254.25.111:4000/getconfig?config=configZZZ0,coinsZZZ0,poolsZZZ0,algorithmsZZZ0,schedulerZZZ0&workername=TESTER&groupname=&machinename=TESTER&myip=0.0.0.0&version=4.4.8.6

.. what does it say?

**Comment by RainbowMiner** [comment]
If you try the above link, please remove all secret keys from the result before posting it here.

**Comment by Nickfost** [comment]
Resolved
