### ISSUE TITLE
Luxor Catalyst

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#765]
Please add full support for Luxors auto exchange 

<3

**Comment by RainbowMiner** [comment]
Ok :)

**Comment by RainbowMiner** [comment]
- add full Catalyst support (issue #765)
- just enter your Luxor username into property "User" of luxor in pools.config.txt
- if you want to mine a specific coin to another address (not catalyst), enter that coin as usual (like "VEIL": "yourveiladdress",) in pools.config.txt
