### ISSUE TITLE
PBM is based on revenue, not profit

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#768]
Please can this be adjusted so that the PBM minprofitpercent is based on profit as it is intended?
Thanks

**Comment by RainbowMiner** [comment]
Oh! I didn't notice that. Will check it, of course.

**Comment by acos0874** [comment]
Did this get updated? If so, thanks!

**Comment by acos0874** [comment]
What was the outcome please?

**Comment by RainbowMiner** [comment]
The calculation was based on Revenue **+** Profit_Cost, which is pretty much wrong. 
Now it's correct: Revenue **-** Profit_Cost

**Comment by acos0874** [comment]
Thanks
