### ISSUE TITLE
Server Config Error

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#770]
Hi, something broke in the latest update. All my benchmarks reset and I'm getting this error on my client machines...

![image](https://user-images.githubusercontent.com/42582444/70936690-bda32880-203a-11ea-9aae-0ca385c5ae1d.png)

**Comment by acos0874** [comment]
Both rigs are on the same version.

**Comment by RainbowMiner** [comment]
Sorry!!

**Comment by acos0874** [comment]
Lots of good updates. Thanks!
