### ISSUE TITLE
[Feature request] - Option to delete not needed files for users with limited drive space. 

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#772]
[Feature request] - Option to delete not needed files for users with limited drive space. 

Delete Logs every 2 days.
Delete Miners in Download Folder after finished extraction to Bin folder.
Don't keep old Miners.  I.e the ones with miner name and date at end of file name.

**Comment by RainbowMiner** [comment]
I see :) Ok, I'll add some options for that.

**Comment by RainbowMiner** [comment]
Here you are: a6309db6743190093dca4248a51f8c46626e65f4

add some maintenance parameters to config.txt:
- MaxLogfileDays = maximum days for the logfiles to keep [default=5]
- MaxDownloadfileDays = maximum days for the downloads to keep [default=14]
- MaxCachefileDays = maximum days for the cachefiles to keep [default=14]
- EnableMinerBackups = keep backups of miner binaries, when miner gets updated [default=1]
- EnableKeepDownloads = keep downloads of miner in folder Downloads [default=1]
