### ISSUE TITLE
Disabling an algo on a miner

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#774]
At the moment, if I want to disable an algo on a particular miner, I need to go into the miner config file on each rig. 

Is there a way to do this just on the server rig or could it be implemented in a separate file?

Specifically, I would like to enable cryptodredge only for argon2d4096.

**Comment by RainbowMiner** [comment]
Hm, normally, you would do it with a miners.config.txt on your server. But that would, of course, overwrite all specific client miner's settings. So eventually, a separate way needs to be found. I'll think about it.
