### ISSUE TITLE
Suggestion: Add Miner Program and Version to Monitoring Central

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#775]
so we can compare miner programs and versions to how others are doing.

**Comment by RainbowMiner** [comment]
Adding it to you own rig's list?

**Comment by jch9678** [comment]
Yes. That way I can see which miner and version my rig is using and compare
it to what others are using. I don't have auto update enabled so maybe a
newer version of the miner provides better hashrate.
