### ISSUE TITLE
Error in the console, but working

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#777]
Hi!

I'm getting:

>At D:\CryptoCurrencies\RainbowMiner\Pools\MiningPoolHub.ps1:105 char:17
>+                 Algorithm0    = $Pool_Algorithm_Norm
>+                 ~~~~~~~~~~
>Duplicate keys 'Algorithm0' are not allowed in hash literals.
>+ CategoryInfo          : ParserError: (:) [], ParseException
>+ FullyQualifiedErrorId : DuplicateKeyInHashLiteral

[debug_2019-12-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/3990741/debug_2019-12-20.zip)

What can I do?

**Comment by RainbowMiner** [comment]
It's already fixed, will be in the upcoming release.

**Comment by SuperBartimus** [comment]
I had been receiving the same error the the OP posted at startup followed by this:
----
At B:\NHML\RM\Pools\MiningPoolHub.ps1:105 char:17
+                 Algorithm0    = $Pool_Algorithm_Norm
+                 ~~~~~~~~~~
Duplicate keys 'Algorithm0' are not allowed in hash literals.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : DuplicateKeyInHashLiteral
----

I also then see this error on each stat refresh.  Is this addressed in the fix you indicated?  I don't think it negatively impacts anything.

**Comment by RainbowMiner** [comment]
Yes, it does not have an impact. It's solved for the next release.
