### ISSUE TITLE
Fresh install error's

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#778]
These errors may be due to it not being a official release yet.. But I just did full Re-install on one of my rigs (Unrelated reason) and I am getting these error's.

 Profit = 0.00000000 BTC/Day | 0.0000 USD/Day | 1 BTC = USD 7390.995

[Client-Mode] Connected to 192.168.1.80:4000

Waiting 38s until next run: E[x]it, [R]estart, [B]alance update, [S]kip SP, [W]D reset, [C]onfiguration, [V]erbose, [P]ause, [L]ock
WARNING: 1 miner crashed. Restarting loop asap.
Finished waiting - starting next run
Index was outside the bounds of the array.
At /home/user/RainbowMiner/Include.psm1:4257 char:9
+         $this.Variance[$this.Algorithm.IndexOf($Algorithm)] = $HashRa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], IndexOutOfRangeException
+ FullyQualifiedErrorId : System.IndexOutOfRangeException

Index was outside the bounds of the array.
At /home/user/RainbowMiner/Include.psm1:4257 char:9
+         $this.Variance[$this.Algorithm.IndexOf($Algorithm)] = $HashRa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], IndexOutOfRangeException
+ FullyQualifiedErrorId : System.IndexOutOfRangeException

WARNING: You are running RainbowMiner prerelease v4.4.9.6. Use at your own risk.
WARNING: Could not write to miners.config.txt. Is the file openend by an editor?

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I am currently reworking the core pretty heavily.
