### ISSUE TITLE
Monero Ocean pool support?

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#779]
Hi, I found out from miningpoolstats.stream that moneroocean.stream
become top 2 pool for some cryptonote coins; such as
Wownero, Masari, ArQmA, Iridium, Loki

can you add monerocoean as well?

**Comment by RainbowMiner** [comment]
I did give this a shot, some time ago, but never found a probate way to integrate Monero Ocean. Since it looks like to be a pretty big pool, now, I'll retry.

**Comment by RainbowMiner** [comment]
Implemented.

**Comment by RainbowMiner** [comment]
Insert your XMR wallet address into pools.config.txt (alt. coins.config.txt and set `"XMR": "$XMR",` in pools.config.txt) plus your moneroocean password (this might as well be your email-address) and off you go.

**Comment by rizkyaulya** [comment]
Amazing, Thank you!
I've been add monero ocean to my pool list since it implemented.
Please add DERO | astrobwt too.
They just added it yesterday.. :)

**Comment by RainbowMiner** [comment]
Sure. I will add this today.

**Comment by RainbowMiner** [comment]
Added with commit 051bf3f1948e6c6de0ae0bf3e1f874352e752936 
Actually, I reworked the pool module and attached it to rbminer.net proxy service, so that we now get all coins, as soon as they are launched at moneroocean.stream .
