### ISSUE TITLE
Issue: Scrypt Errors

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#78]
My 14 gpu rack was running stable on your last version. I just updated to 3.8.5 and restarted.

![image](https://user-images.githubusercontent.com/42227809/44950130-c3004380-adf4-11e8-9b2c-e467fc0f2a91.png)

**Comment by Byrd1083** [comment]
I also , just redownloaded your latest release 3.8.5 and installed on 5 gpu rig fresh and new. Still broken and will not work on 14 or the 5 gpu rigs.

**Comment by Byrd1083** [comment]
This is what flashes before basic setup screen on new install.

![image](https://user-images.githubusercontent.com/42227809/44950186-6a31aa80-adf6-11e8-94d0-205bd9735ef9.png)

**Comment by hernandn01** [comment]
it does let me to continue, it appears there is a missing -Force
![image](https://user-images.githubusercontent.com/41829368/44950219-5cccee00-adff-11e8-8f10-551bf381e5d7.png)

**Comment by Byrd1083** [comment]
A lot of bugs coming out of the wood work.

My single test 1080 ti is still stable on v3.8.4.4

Anything after that is throwing scrypt errors.

**Comment by RainbowMiner** [comment]
Ok. Found it. It is only one "s" too much!
I will push a new release ASAP.

**Comment by RainbowMiner** [comment]
The new release has been published. 

** Before starting the new release: please replace your current miners.config.txt with the last miners.config.txt out of Config\Backup. **

Again, I am so sorry for the inconvenience.

RBM

**Comment by Byrd1083** [comment]
I'll test tomorrow. Going to be away for a min.

**Comment by RainbowMiner** [comment]
Ok. Thanks!

**Comment by Byrd1083** [comment]
Okay just compiled new on 14 gpu rack. I get more scrypt error before basic config setup.

![image](https://user-images.githubusercontent.com/42227809/44952673-206ab380-ae3a-11e8-9490-f828cf78a341.png)

**Comment by Byrd1083** [comment]
There is no config file because this is a new install. I still need to go through the basic setup. It looks like an issue with paths for write logs.

**Comment by RainbowMiner** [comment]
Oh, that is weird. It should create a new config.txt. Could you have a look into your Rainbow-master directory? Is there a Config directory? And if yes, is there a Backup directory inside?
