### ISSUE TITLE
MINER STUCK

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#780]
The miner has been stuck like this for more than 20 mins and i am at a loss 
this is happening post the new updates
![Annotation 2019-12-23 230054](https://user-images.githubusercontent.com/32984054/71371754-3b85a780-25d8-11ea-88b6-6a5bdd56ac70.png)

**Comment by RainbowMiner** [comment]
Did this problem resolve after restart? If not, please upload a debug file, then I will have a look.

**Comment by saroshpatel09** [comment]
Nope it didn't had to reboot the entire system thrice over and I have 4
GPUs but the miner detects only 3 of them

**Comment by saroshpatel09** [comment]
I am not using the miner at the moment as things keep on crashing

This is the best I can do for you will also attach the screenshot of the number of GPU's
![Screenshot_180](https://user-images.githubusercontent.com/32984054/71428983-3b75cc80-26ea-11ea-96b1-4c022285ba1b.png)



[RainbowMiner_2019-12-20.txt](https://github.com/RainbowMiner/RainbowMiner/files/3999368/RainbowMiner_2019-12-20.txt)

**Comment by RainbowMiner** [comment]
It looks like, that one of the GTX1070 Ti is failing - that might cause the trouble. I'ld try to remove and replug the card. If it still fails - eventually try to reinstall the nvidia drivers.
