### ISSUE TITLE
RBM closing on its own.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#782]
RBM closing on its own.
[debug_2019-12-24.zip](https://github.com/RainbowMiner/RainbowMiner/files/3999669/debug_2019-12-24.zip)

Done this 2 times today.

Ok a couple of more times RBM just goes from running to not running when I check it.

**Comment by paulpoco** [comment]
i saw a pop up saying "a new guard stack cannot be created".

**Comment by RainbowMiner** [comment]
Very, very weird! I will have a look today.

**Comment by RainbowMiner** [comment]
Actually, this message could be related to a damaged .net installation. Eventually, you could try to re-install .net
https://www.ibm.com/support/pages/how-can-i-resolve-error-new-guard-page-stack-cannot-be-created-when-using-icm

**Comment by paulpoco** [comment]
I excluded miner CcminerMTP and so far no new closing of RBM but I will look at the . Net

**Comment by AnthonyBe** [comment]
I just updated from  v4.4.9.4 to v4.4.9.8 and started seeing same.

This seems to be the culprit from the log:

[2019-12-26 17:56:58] [162.08 146.44] INFO: Starting RainbowMiner v4.4.9.8
[2019-12-26 17:56:59] [168.77 151.67] INFO: Run as administrator
[2019-12-26 17:57:01] [196.19 175.66] ERROR: Index operation failed; the array index evaluated to null. Cannot run RainbowMiner. 
[2019-12-26 17:57:14] [157.70 145.16] INFO: Starting RainbowMiner v4.4.9.8
[2019-12-26 17:57:14] [164.85 151.04] INFO: Run as administrator
[2019-12-26 17:57:17] [192.14 174.80] ERROR: Index operation failed; the array index evaluated to null. Cannot run RainbowMiner.

**Comment by rhadamants** [comment]
RBM is closing for me too using CcminerMTP but always with this message:
PS> TerminatingError (Get-Process): "Not enough memory resources available to process this command"

**Comment by RainbowMiner** [comment]
> I excluded miner CcminerMTP and so far no new closing of RBM but I will look at the . Net

I think, I will have to doublecheck the CcminerMTP - actually, there could be some memory leak in the ccminer.exe .

**Comment by rhadamants** [comment]
PS> TerminatingError (Get-Process): "Not enough memory resources available to process this command"
>> TerminatingError (Get-Process): "Not enough memory resources available to process this command"
>> TerminatingError (Update-ActiveMiners): "Exception of type 'System.OutOfMemoryException' was thrown."

Any miner MTP cause this and close RBM.
