### ISSUE TITLE
4.4.9.8 - "ERROR: Index operation failed; the array index evaluated to null. Cannot run RainbowMiner."

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#783]
Just updated from 4.4.9.4 to 4.4.9.8

I now get following error on startup and RM exits

```
[2019-12-26 17:56:58] [162.08 146.44] INFO: Starting RainbowMiner v4.4.9.8
[2019-12-26 17:56:59] [168.77 151.67] INFO: Run as administrator
[2019-12-26 17:57:01] [196.19 175.66] ERROR: Index operation failed; the array index evaluated to null. Cannot run RainbowMiner. 
```

I'm running Win 10 1909 with following .Net Framework versions

.NET FW 4.8 Windows 10 May 2019 Update (CLR:4.0)

<32Bit>
2.0.50727.9148
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.8.4075.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.9148
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.8.4075.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

**Comment by AnthonyBe** [comment]
Oddly, I just rolled back to 4.4.9.4 (just copied extracted archive over the 4.4.9.8) and still getting same error..hmmm...

**Comment by RainbowMiner** [comment]
Did you use Autoupdate, or did you just copy over the new archive? Could you please upload the transcript log file, so that I can quickly fix this?
It is the most recent RainbowMiner log txt, with date and time in its name.

**Comment by AnthonyBe** [comment]
From 4.4.9.4 -> 4.4.9.8 was via Autoupdate

[RainbowMiner_2019-12-26.txt](https://github.com/RainbowMiner/RainbowMiner/files/4002297/RainbowMiner_2019-12-26.txt)

**Comment by RainbowMiner** [comment]
There is another log file: RainbowMiner_2019-12-26_hh-mm-ss.txt - that's what I need

**Comment by RainbowMiner** [comment]
The most actual two logfiles would do the job. It looks like the device detection fails for some reason. Which GPU are plugged into this rig?

**Comment by AnthonyBe** [comment]
Apologies!

I thought the problem might be that I hadn't actually installed PowerShell 6 (I've been running RM with PS 5.1 for many months) but even after doing so, same issue. I've attached before and after PS6 install logs just in case it is useful or relevant.
[RainbowMiner_2019-12-26_20-31-01.txt](https://github.com/RainbowMiner/RainbowMiner/files/4002336/RainbowMiner_2019-12-26_20-31-01.txt)


[RainbowMiner_2019-12-26_22-07-55.txt](https://github.com/RainbowMiner/RainbowMiner/files/4002334/RainbowMiner_2019-12-26_22-07-55.txt)

**Comment by RainbowMiner** [comment]
Try to delete Config\miners.config.txt

**Comment by RainbowMiner** [comment]
Oh, maybe, please upload it here before you delete it

**Comment by AnthonyBe** [comment]
> The most actual two logfiles would do the job. It looks like the device detection fails for some reason. Which GPU are plugged into this rig?

It's just an old nVidia GTX 660Ti

**Comment by AnthonyBe** [comment]
> Oh, maybe, please upload it here before you delete it

[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4002346/miners.config.txt)

**Comment by AnthonyBe** [comment]
Yep - renamed **miners.config.txt** and RM is running fine now.

**Comment by RainbowMiner** [comment]
Could you please upload that defective miners.config.txt? Also, which GPU are you using?

**Comment by AnthonyBe** [comment]
> Could you please upload that defective miners.config.txt? Also, which GPU are you using?

Attached the defective miners.config.txt about 3 posts up.

GPU = nVidia GTX660Ti

**Comment by RainbowMiner** [comment]
Ah sorry you did. Thank you! What's left is the question about which GPU you are using.

**Comment by AnthonyBe** [comment]
LOL. Answered that one twice already :)
Third time's the charm!

GPU = nVidia GTX660Ti

It's just one of my test boxes.

**Comment by RainbowMiner** [comment]
Wow, it is pretty much messed up. I will investigate this further - I do suspect a Powershell 5 problem with generic lists, though. Until I find the source, I will revoke the 4.4.9.8 version, just to be sure. Thank you for reporting this!

**Comment by AnthonyBe** [comment]
Well, partly my fault for not having PS6 which is listed as a pre-req. Although I am curious if that was added in recent times as I don't remember seeing it when I originally setup RM a few months ago?

Either way, maybe a check for PS version and exit with notification if not PS6?

**Comment by RainbowMiner** [comment]
You could give the new release 4.4.9.9 a shot. I have added an auto correct for the miners.config.txt, plus, I reworked the relevant function. I am curious, if your test machine likes this update.
Actually, I always try to have RainbowMiner backwards compatible with PS5.

**Comment by AnthonyBe** [comment]
4.4.9.9 working perfectly!

**Comment by RainbowMiner** [comment]
Duh! That's a relief! Thank you for reporting back.
