### ISSUE TITLE
Wownero Profit Calculation is off by a huge factor

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#784]
[debug_2019-12-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/4005382/debug_2019-12-27.zip)

The pool, herominers, reports a much lower payout.

**Comment by Yamanipanuchi** [comment]
Yes, I've been noticing this also. Disabled WOW for now. Each time I enable it, It puts me at several $$ an day.

**Comment by RainbowMiner** [comment]
Thank you for reporting that. I have stopped mining WOW for some time, so I didn't notice. I will have a look.
