### ISSUE TITLE
Unable to Complete Benchmarking with 4.4.9.9

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#785]
A few of my machines are not able to complete benchmarking.  Also monitoring central loses connection with them.  They show as offline however they are still mining, just not switching miner programs.
[debug_2019-12-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/4005839/debug_2019-12-27.zip)

**Comment by RainbowMiner** [comment]
Oh dear!! Eventually it's a problem with Powershell 5 - try to update your machine to Pwsh 6.2.3
Are there any error messages printed to the console?

**Comment by jch9678** [comment]
There aren't any messages in the console. It just shows that it's still
benchmarking.

I'll update powershell right now. Thanks.

**Comment by RainbowMiner** [comment]
Could you please upload your current config.txt (please delete all sensitve information, like API secrets, before uploading).

**Comment by jch9678** [comment]
Updating powershell to v6 apparently fixed all the benchmarking issues with the exception of one rig.  It's config.txt is attached.
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4006555/config.txt)

Also updating powershell did not have an effect on the monitoring central problem.  The rigs still intermittently show up as offline then online etc.

**Comment by RainbowMiner** [comment]
I think, this will solve the issue:

https://github.com/RainbowMiner/RainbowMiner/issues/787#issuecomment-569370864
