### ISSUE TITLE
crashes on startup all instances offline since update

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#786]
Hi 

my server crashes shortly after printing "detecting devices" 

this was after an auto update. 

all of my clients have went offline too, im unable to access them 

Please reach out to me to get details to connect to my server. 

Thanks

**Comment by RainbowMiner** [comment]
Oh dear! Sure, I will get into contact.

**Comment by Nickfost** [comment]
seems a remedy is in place
