### ISSUE TITLE
Verushash and Paid in Random coins.

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#787]
Somehow a "c=RandomCoin" is added to my password when using nheqminer.  If I'm not mistaken that means I've chosen to get paid in that coin.  However no where did I choose to get paid in these coins....  Here are just a few examples

nheqminer.exe -a 53601 -v -l mine.nlpool.nl:3300 -u 4Cd7rzeiqwQJe8dCZbQeQxeNHUV4P4w7hAJ2g8U2ciiEao2AmqN9tXEfngQaPGV6T2Sx9mEtCaEMzaCR53iQRJqEgfdPczi5Wjy5xcLyFN -p GCPU,c=XMV -t 24 --cpu-affinity 0xFFFFFF

nheqminer.exe -a 53601 -v -l mine.nlpool.nl:3300 -u
PiyAfA1u1bNH9XjsPjXc5M64sip7LCj6ziBKEneKPmbVWM6kPMMAQs17h26tnCogW5Q72c5pVGJ4QW3kSKso4MW4h6hQRvmXG5385j57HGJjj -p GCPU,c=XRN -t 24 --cpu-affinity 0xFFFFFF

nheqminer.exe -a 53601 -v -l verushash.mine.zergpool.com:3300 -u
SEiStP7SMy1bvjkWc9dd1t2v1Et5q2DrmaqLqFTQQ9H7JKdZuATcPHUbUL3bRjxzxTDYitHsAPqF8EeCLw3bW8ARe8rYJfjcuHD6aUbZUmysE -p SCPU,c=XTL -t 24 --cpu-affinity 0xFFFFFF

nheqminer.exe -a 53601 -v -l mine.nlpool.nl:3300 -u
WzWP347dSczJVmPpw65AsAGi5WhT85z5n66D8vcT3RcxRBBj4tFiDcd2CVFcQ1bBpjNQD5Z5kbXrLjVidvoKFaFK6uj7xTraXmN2w6smkdA8 -p GCPU,c=AEON -t 24 --cpu-affinity 0xFFFFFF

nheqminer.exe -a 53601 -v -l verushash.mine.zergpool.com:3300 -u
WtiptjGr6oRdZVFqumdfLbVd1XMtCYWKBT6dXppmCWA3TAk4tvesMCsbFLewv4rnmQHKimvwvcsbzC5FgWRrkGmc1DXreHk7sS.bbddc5797cdc7a164156771a24429b616423696e4e782bf006f2f6773673117d  -p ACPU,c=WTIP -t 24 --cpu-affinity 0xFFFFFF

**Comment by RainbowMiner** [comment]
! That's strange, actually. Are those your wallet addresses?

**Comment by RainbowMiner** [comment]
I think these issues are strongly related: #785

**Comment by RainbowMiner** [comment]
Could you please upload your current coins.config.txt and pools.config.txt ?

**Comment by jch9678** [comment]
I looked up one of the addresses and it was mine so I assume the others are mine as well.  I just noticed this behavior with srbminer-multi on another machine so maybe the issue is with how RM handles zergpool and nlpool.  I'll grab the files for you now

**Comment by jch9678** [comment]
[coins.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4006546/coins.config.txt)
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4006549/pools.config.txt)

**Comment by RainbowMiner** [comment]
Ok, that's a pretty good hint.

Please do disable EnableAutoCoin for all pools in pools.config.txt, that do autoexchange. It will fully mess up everything, since all EnableAutoPool enabled coins will be used as wallet addresses for autoexchange currencies.

```
  "EnableAutoCoin":  "0",
```

**Comment by jch9678** [comment]
ok disabled it in zergpool (and related), zpool, nlpool, blazepool, and AHashPool

Did I miss any?  Should I disable it in WhatToMine and MiningPoolHub and NiceHash?

**Comment by RainbowMiner** [comment]
Yes.

**Comment by RainbowMiner** [comment]
I should add an extra logic to avoid this problem.

**Comment by jch9678** [comment]
"EnableAutoCoin":  "0"  is there a scenario where someone would want it "True" for an autoexchange pool?

I was thinking that I should keep it enabled for MiningPoolHub since autoexchange is done with a setting at the pool....

**Comment by RainbowMiner** [comment]
Actually, I don't think there is a scenario, that would work out for those autoexchange pools. I have just added an extra check to the core that will automatically disable EnableAutoCoin for all autoexchange pools. Just to be sure :)

**Comment by RainbowMiner** [comment]
Did this solve the issue?

**Comment by jch9678** [comment]
Yes I believe it did solve the issue. Thank you very much

**Comment by RainbowMiner** [comment]
Duh! That is good to hear! Thank you for reporting this.
