### ISSUE TITLE
Bminer failing to benchmark

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#789]
[INFO] [2019-12-28T12:11:34Z] Bminer: When Crypto-mining Made Fast (v15.8.7-6831c33) 
[INFO] [2019-12-28T12:11:34Z] Watchdog has started.                        
[INFO] [2019-12-28T12:11:34Z] Detecting platform                           
[FATA] [2019-12-28T12:11:43Z] CudaError: Unknown error: c:\users\mining\downloads\rainbowminerv4.3.4.8\bin\gpu-bminer\vcruntime140.dll

**Comment by RainbowMiner** [comment]
The bminer is know to cause trouble for some Nvidia drivers. Which version is in use on your rig?

**Comment by samdave123** [comment]
GeForce 440.97 WHQL

**Comment by RainbowMiner** [comment]
Yes, that's the point. Bminer is _very_ picky with the driver versions. 
If you want Bminer to run (also, I would rather recommend putting it on the "ExcludeMinerName" list in config.txt), you will have to install driver "431.68 hotfix"

DCH version: https://international.download.nvidia.com/Windows/431.68hf/431.68-desktop-notebook-win10-64bit-international-dch.hf.exe
Standard version: https://international.download.nvidia.com/Windows/431.68hf/431.68-desktop-notebook-win10-64bit-international.hf.exe

during install choose custom install and select clean install
