### ISSUE TITLE
Unnecessary miner combinations on mixed rigs

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#79]
I have 2x1050ti, 1x1060 6gb and 1x1060 3GB. From there 3 miner groups were identified, 1050ti (both cards in there together gpu 0 and 2), and the other 2 cards in their respective group. From those combinations of miner groups were created. With new version 3.8.5.0 a lot more unnecessary combinations are created. Possible the source of the main error on script start. See the following example:

Bminer-GTX1050Ti GTX10606GB GTX10603GB GTX1050Ti-GTX10606GB GTX1050Ti-GTX10603GB GTX10603GB-GTX10606GB GTX1050Ti-GTX10603GB-GTX10606GB"": [

**Comment by RainbowMiner** [comment]
Yes, I see. It is a bug. I am very sorry for that!
The old miners.config.txt is backed up in Config\Backup 
I will fix it at once.

**Comment by RainbowMiner** [comment]
Would you please zip your Config folder and add it here?

**Comment by hernandn01** [comment]
[Config.zip](https://github.com/RainbowMiner/RainbowMiner/files/2342825/Config.zip)
there you go

**Comment by hernandn01** [comment]
I had already replace the miners.config,txt with the backup, would you like me to restart to create another miner.config.txt ?

**Comment by RainbowMiner** [comment]
Ok, found it. Please wait. I will push a new release.
RBM

**Comment by RainbowMiner** [comment]
The new release has been published. 

**Before starting the new release: please replace your current miners.config.txt with the last miners.config.txt out of Config\Backup.**

Again, I am so sorry for the inconvenience.

RBM

**Comment by hernandn01** [comment]
working fine
