### ISSUE TITLE
Question about accuracy

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#790]
If I'm using minute_10 as the global average for all pools, is the accuracy calculated on the live prices or the minute_10 prices?

**Comment by RainbowMiner** [comment]
We are using three values:
Price = moving average price, based on the global/specific average timescale, which is setup in the config files
StablePrice = moving average price, based on one week timescale
Accuracy = moving average fluctuation, based on the StablePrice (so it's one week timescale)
