### ISSUE TITLE
Error while script running (Linux)

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#791]
Got the following error while running this script in Linux. Will upload logs shortly after this post.

Waiting 46s until next run: E[x]it, [R]estart, [B]alance update, [S]kip SP, [W]D reset, [C]onfiguration, [V]erbose, [P]ause, [L]ock
Finished waiting - starting next run
./start.sh: line 23:  3382 Segmentation fault      (core dumped) pwsh -ExecutionPolicy bypass -Command ${command}
user@solar:~/RainbowMiner$

**Comment by Yamanipanuchi** [comment]
Getting the Debug file was much easier this time...

[debug_2019-12-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/4008597/debug_2019-12-29.zip)

**Comment by RainbowMiner** [comment]
Did this happen only once, or is this happening like always? Only on that specific machine? 
A segmentation fault is a linux error.

**Comment by Yamanipanuchi** [comment]
It happened a couple times on this machine. But has stopped now. Ill close the issue.
