### ISSUE TITLE
Seeing Multiple instances of OhGodAnETHlargementPill

### ISSUE THREAD

**Issue by SuperBartimus** [RainbowMiner/RainbowMiner#792]
While mining...
Noticing multiple instances of OhGodAnETHlargementPill are running on several of my rigs.  
Perhaps due to that, the script doesn't detect an existing instance is already running and so starts a new instance for Equihash.
If left unchecked for long periods of time, I've found about 50 instances running.

**Comment by RainbowMiner** [comment]
Thank you for reporting this. Are these Windows or Linux machines?

**Comment by SuperBartimus** [comment]
Windows

**Comment by RainbowMiner** [comment]
- eventually fix issue #792
- to be sure: kill maroding EthPills
