### ISSUE TITLE
Bypass Auto Adjust Affinity

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#793]
Could you give me more info about why I should not use all cores please?  This is strictly a mining computer.  Does it have to do with RM not being able to report to Monitoring Central in a timely fashion?

**Comment by RainbowMiner** [comment]
It's just to give RainbowMiner script a little room to calculate the next round. There were users complaining about overly slow machines, especially after they have copied over their configs to new boxes with different (mostly slower CPUs) - it happened a lot, that those machines then were confronted with too many CPUMiningThreads to handle. so I thought an automation would be of help. I will quickly change two things:
1. add a switch to enable this automation. Then your machine will be back to normal and users may switch the automation to on.
2. reduce the check to look for CPUMiningThreads greater than avail threads, only.

**Comment by RainbowMiner** [comment]
Added

**Comment by RainbowMiner** [comment]
Ok, I pushed a new release version v4.5.0.2 containing this update. Sorry for the inconvenience! You were certainly right to complain.

**Comment by jch9678** [comment]
Sorry if I came across harsh. That was definitely not my intention. No
apology necessary. I actually don't lose as much hashrate as one would
think with a full core disabled. It's more like half a core.
