### ISSUE TITLE
Feature Request:  Immediately Pause when not Idle ( w/ Auto-resume)

### ISSUE THREAD

**Issue by SuperBartimus** [RainbowMiner/RainbowMiner#795]
Any way to have RM to immediately pause mining when the system becomes active by keyboard or mouse activity?
I'd like to be able to use my desktop PC when I need to, but having to wait for RM to respond to the PAUSE command sometimes takes a bit.
Along with this feature would be an auto-resume option that could be a set configurable amount of seconds.

**Comment by RainbowMiner** [comment]
Thank you for this idea. I will try to find a way.

**Comment by RainbowMiner** [comment]
- add new parameters to config.txt:
  - "EnablePauseOnActivity" = Send RainbowMiner into pause mode, if user input is detected
  - ResumeOnInactivitySeconds = Seconds of no user input, until RainbowMiner leaves pause mode (0 = never, default = 300)
