### ISSUE TITLE
CORTEXMINT

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#796]
why cant the miners bench cortex (CTXC)

just doesnt catch it

and is this even real for XTNCX..?

see pic 
![Screenshot_188](https://user-images.githubusercontent.com/32984054/71675545-fade1900-2da3-11ea-866f-e3c0bc9c1463.png)

**Comment by RainbowMiner** [comment]
Cortex is a pretty memory hungry algorithm (currently only Gminer supports it). You will need at least 10GB of GPU memory (like GTX1080Ti) on Windows 10.

**Comment by RainbowMiner** [comment]
The calculation for XTNC is correct for this hour - BUT - there is nearly no trading volume and a large price spread on TradeOgre, so you will have hard times to sell them for that price. I would rather disable XTNC mining.
