### ISSUE TITLE
RandomX FailBenchmark

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#797]
Two of my Linux machines Fail Benchmark on RandomX. Looking at the logs NanoMiner looks as if its working, But RBM still says it fails. Xmrig cant really tell what is going on. Need to have the color codes striped out.
[debug_2020-01-02.zip](https://github.com/RainbowMiner/RainbowMiner/files/4017345/debug_2020-01-02.zip)

**Comment by RainbowMiner** [comment]
Difficult to say, the system CPU load could eventually be too high. Try to free up one or two threads of the CPU.

**Comment by Yamanipanuchi** [comment]
Actually NanoMiner finally started working after several time Re-Benching... XmRig no worky at all. Cant figure out why. It is working only another Linux Desktop PC, So it might just be a package missing.

**Comment by RainbowMiner** [comment]
Which Linux is running on the failing machines? Is it a different version to that one running the non-failing one?

**Comment by RainbowMiner** [comment]
Looking through your debug file, it looks like you are not running the OCDaemon on those machines. Eventually try to run Xmrig using the OCDaemon. Also, you might want to update to v4.5.0.4 (it's pre-release master.zip), as I have added a new build of the CUDA plugin lib. Xmrig had it updated some days ago.
