### ISSUE TITLE
Lock isn't working as expected

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#798]
Hi!
Lock function isn't working, or to say it right, it's not working as expected. You see, the problem I have and why I suggested Lock was because when miming some coins with Vega56 sometimes the card enters in a mode that makes it mine a lot less than it's supposed. That's why you added the reset function for the card that solves the issue. But when the card is resetted, the display turns off for a second or two, and Windows restart some things (BTW, Windows has a bug that sometimes Explorer.exe hangs some aspects of it, like the Start menu!)
When Lock was implemented it was working ok and it did what was expected to do: lock the miner and don't restart the card. But now even when locked the card resets.

**Comment by RainbowMiner** [comment]
Ok, thank you for reporting it. I will double-check the lock. So you say, the miner is not changing, but the reset happens, anyway? 
Could you eventually create and upload a Debug file?

**Comment by Djago** [comment]
>  So you say, the miner is not changing, but the reset happens, anyway?
Not really. Something like that.
The line saying:
Status: LOCKED to ZergPool-RandomSFX-SFX, ZergPool-CryptoNightHeavy-NBR (press L to unlock)
always says the same, but the actual miners that are working (displayed in the "Status: Running" part of the window) keep changing.

> Could you eventually create and upload a Debug file?
Sure!
[debug_2020-01-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/4023540/debug_2020-01-05.zip)

**Comment by Djago** [comment]
Now miners aren´t changing when locked, but still VEGA is resetting. Can you please make that the resetting of VEGA card is not performed while RainbowMiner is locked?

**Comment by RainbowMiner** [comment]
Ok, I'll check and fix this.

**Comment by RainbowMiner** [comment]
Could you eventually upload another Debug file, now that the lock is working? I have hard times locating the problem, why the VEGA are resetting.
Actually, do they reset every round or every other hour?
