### ISSUE TITLE
Windows = 5 GPU & RBM = 4

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#799]
Hey 
below is the screenshot of windows that shopws 5 GPU's but RBM takes only 4 

Whats going on

![Annotation 2020-01-05 192418](https://user-images.githubusercontent.com/32984054/71781146-69fc7d00-2ff1-11ea-96a4-906c97b324d5.png)

**Comment by RainbowMiner** [comment]
Eventually, the Nvidia drivers are crashed for one GPU.

Try
- stop RainbowMiner
- run "RestartDisplayDriversNvidia.bat"
- start RainbowMiner

.. if the GPU still does not show up, try a reboot of the machine.
