### ISSUE TITLE
Does RainbowMiner do anything to the Windows Firewall?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#8]
I went to go back and run my MPM and I cannot access the web part anymore.
http://localhost:3999/
Going to check my Firewall settings.

**Comment by RainbowMiner** [comment]
RainbowMiner uses the same localhost port 3999, that could cause a problem. I will change the localhost port.

**Comment by RainbowMiner** [comment]
Done. Find the web interface at URL http://localhost:4000
See commit a49c4045c4c4b2f583d67719015fa3dc686bc777

**Comment by paulpoco** [comment]
For some unknown reason I cannot get the MPM http://localhost:3999 to work anymore.  The only thing different is I used RainbowMiner then shut that down and started MPM up again and no web for dashboard etc.

**Comment by RainbowMiner** [comment]
It looks like a port problem. Just update RainbowMiner to the current release version and reboot the PC. That should solve the problem.

**Comment by paulpoco** [comment]
What did RainbowMiner do to the Windows Firewall to stop MPM http://localhost:3999/ from working when running MPM?

**Comment by paulpoco** [comment]
I reset the Firewall to default.
Moved my working MPM setup to a different folder.
Replaced API.psm1 with the Rainbowminer one.
MPM web function works now.  Will stop MPM and try MPM's API.psm1 and see if the localhost function still works.

**Comment by paulpoco** [comment]
Ok it was the new folder and resetting Window Firewall.

**Comment by RainbowMiner** [comment]
Super :) Please note, that you will have to update the https://github.com/RainbowMiner/RainbowMiner/blob/master/Downloader.ps1 , too, since there is a call to the API inside.
