### ISSUE TITLE
error on CrytoBridge 9.0 on cryptonight v7

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#80]
[17:01:21] INFO  - 0/1 Rejected : diff=455.844, reason: Invalid nonce; is miner not compatible with NiceHash?

**Comment by RainbowMiner** [comment]
Yes. This is a bug in CryptoDredge. A beta version is being promised.

**Comment by hernandn01** [comment]
https://github.com/technobyl/CryptoDredge/releases/download/v0.9.1/CryptoDredge_0.9.1_cuda_9.2_windows.zip

New CryptoNightHaven algorithm
Fix issue related to many rejected shares on NiceHash pool when used CryptoNight-like algorithms

**Comment by RainbowMiner** [comment]
New RainbowMiner v3.8.5.10 contains bugfixed CryptoDredge
