### ISSUE TITLE
Feature: Allow or Disallow Coin symbol in schedule.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#801]
Would it be possibly to Allow or Disallow specific coins in the scheduler?

**Comment by RainbowMiner** [comment]
Actually, that would be nice! 
That's the cool thing about hacking. Everything is possible. I'll add this.

**Comment by RainbowMiner** [comment]
Ok, implemented.
- added "Algorithm", "ExcludeAlgorithm", "CoinSymbol" and "ExcludeCoinSymbol" to scheduler.config.txt to specify mining operations during schedules
