### ISSUE TITLE
XTNC Profitability

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#802]
Hey ..
My Miner is stuck on XTNC Showing about $ 100 per day ???
Is the profitability even real.???
and if the miner uses whattomine to determine the profitability and mine 
then please tell me why is it that XTNC doesnt even show up on whattomine

so do i enable XTNC or should i disable it.?

**Comment by RainbowMiner** [comment]
I would rather disable XTNC mining. It's not worth it.

**Comment by saroshpatel09** [comment]
k done thanks
