### ISSUE TITLE
Eaglesong

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#803]
Nicehash have told me they would be adding eaglesong soon. Please can you set this up in rbm so we're good to go from the off?

**Comment by RainbowMiner** [comment]
Actually, everything is already up-n-running with eaglesong. We have dual and single mining. So, as soon as Nicehash opens the CKB market, we will be mining it.

**Comment by acos0874** [comment]
Thanks. It seems it's live but is giving errors. Please can you check? Maybe a protocol issue.

**Comment by acos0874** [comment]
Nevermind it seems to be ok now.

**Comment by RainbowMiner** [comment]
It was a cache problem. The Nicehash ports are cached for 1 hour in file .\Cache\E33EED05F8D38DA3A8ABA6B8F42CC34E.asy - so, basically, if it fails, delete this file.
