### ISSUE TITLE
NBMiner Intensity Testing

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#805]
Hi, please can you add the same feature for testing multiple intensities for nbminer (I was getting too many rejected shares with gminer)? The intensities range between 1 and 10.

**Comment by RainbowMiner** [comment]
Sure. The rejected shares may be related to Nicehash bots - there are multiple bots currently active, that cause those rejected shares. Most of the time it happens in waves.

**Comment by acos0874** [comment]
Ok thanks!

**Comment by acos0874** [comment]
The gminer was also giving this error so I gave up 
![image](https://user-images.githubusercontent.com/42582444/71990997-50934500-322c-11ea-972f-a937a588f20d.png)

**Comment by RainbowMiner** [comment]
> The intensities range between 1 and 10.

Actually, their documentation says:
> * -di, --secondary-intensity \<intensity>    The relative intensity for ETH when dual mining. recommend: 8 - 24, default to 16.

.. have you already tried out some intensities?

**Comment by acos0874** [comment]
Yes. Khayto kindly pointed out the values are different in the patch notes. I tested them and it seems 10 is max.

**Comment by RainbowMiner** [comment]
Ok, thank you! Anyway, I have a full sweep test running, 1-24. So maybe it's an 1/x function.

**Comment by RainbowMiner** [comment]
Good. Done. It's definitely cut-off at max. 10, so no 1/x

**Comment by acos0874** [comment]
If it's easier I managed to figure out the best intensity by trial and error. Happy either way.

**Comment by RainbowMiner** [comment]
All done, don't worry :) The new release v4.5.0.4 contains an updated NBminer module, which will do the magic. Actually, during my tests, it turned out, that the NBminer is very much better, regarding the efficiency (very low power consumption, compared to Gminer)

**Comment by acos0874** [comment]
Hello. Sorry for all the issues. With the new multiple intensities I'm having issues with the miner switching between intensities every couple of minutes. I know the miner hysterisis was supposed to prevent this but doesn't appear to be working. Please can you offer some advice?

**Comment by RainbowMiner** [comment]
Ha, good question. Actually, it should work - eventually, it's because it is always the same miner, though. I'll have a look.

**Comment by acos0874** [comment]
I increased the hysteresis to 15. I figured 3 maybe isn't enough whilst profits are so low

**Comment by RainbowMiner** [comment]
And did the 15% hysteresis solve the problem? If yes, I'ld probably increase the defaults.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/72023907-fca85080-326b-11ea-927a-ab170d643d8e.png)
Sorry doesn't look like it.

**Comment by acos0874** [comment]
Oh thats strange I just checked and it's defaulted back to 3. Maybe I changed it on the wrong rig.

**Comment by acos0874** [comment]
Still happens at 15%
![Screenshot_20200109-073509_Chrome](https://user-images.githubusercontent.com/42582444/72047569-b9bd9b80-32b2-11ea-9d44-c1a640e9fadf.jpg)

**Comment by RainbowMiner** [comment]
Is it eventually possibly, that you have set "EnableFastSwitching": "1" in config.txt ?
That's the only other parameter, that would disable the miner hysteresis.

**Comment by acos0874** [comment]
Nope. See below. Miner hysteresis has never worked for me, which is why I only have a couple of miners activated and was asking about disabling certain miner/algo combinations.

"MinimumMiningIntervals": 3,
  "DisableExtendInterval": "0",
  "SwitchingPrevention": 2,
  "PoolSwitchingHysteresis": 2,
  "MinerSwitchingHysteresis": 15,
  "MaxRejectedShareRatio": 0.3,
  "EnableFastSwitching": "0",
  "Donate": 10,
  "Watchdog": "1",
  "IgnoreFees": "0",
  "DisableDualMining": "0",
  "EnableCheckMiningConflict": "1",

**Comment by RainbowMiner** [comment]
Now you got me thinking. Strange thing - it should work, though. I'll double check the algo.

**Comment by RainbowMiner** [comment]
Could you eventually create a debug file and upload it here?

**Comment by acos0874** [comment]
I hashed out the different intensities in the nbminer.ps1 file as a temporary fix. Do you need me to re-enable them before sending you the debug file?

**Comment by RainbowMiner** [comment]
No, I hope that the logs still contain the actions before that.

**Comment by acos0874** [comment]
[debug_2020-01-09.zip](https://github.com/RainbowMiner/RainbowMiner/files/4040949/debug_2020-01-09.zip)

**Comment by RainbowMiner** [comment]
It looks ok - but it seems, there were heavy swings in Nicehash Ethash+Eaglesong prices, with a much higher altitude than 15%. And since we use the live prices for Nicehash, these quickly strike through. So eventually, that's causing the trouble. 
I am thinking about adding something like `"Intensity": "0,5,10",` setting in miners.config.txt, so that one can specify exactly, which intensities should be used.

**Comment by acos0874** [comment]
OK I will try increasing to 40% and see if that improves things.

**Comment by RainbowMiner** [comment]
I have added "Intensity" to miners.config.txt for Gminer and NBminer. Will be in the next release, see commit 2b86f997ac4594baf76bb1ef4b0479b730c1fee8

**Comment by acos0874** [comment]
I increased the hysteresis to 30% and it seemed to do a good job on my 2 rigs, but on my gaming machine the switching was still there. I set it to 40 and left it overnight.

![image](https://user-images.githubusercontent.com/42582444/72136462-c1e40c80-3380-11ea-81ee-3633623fb8c0.png)

It's still switching too often whereas my rigs don't switch enough.

I'll try 60 next. Here is the debug file.

[debug_2020-01-10 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/4044548/debug_2020-01-10.1.zip)

**Comment by acos0874** [comment]
I thought increasing the intensity to 60 would fix the problem but it's still switching every few minutes 
![image](https://user-images.githubusercontent.com/42582444/72149524-4479c580-339b-11ea-936b-ea77f72110f3.png)

**Comment by acos0874** [comment]
Nevermind, it had reverted to 20. I don't know why that keeps happening. I have it set in standalone mode :S

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/72152437-e94bd100-33a2-11ea-843b-551643266970.png)
Still switching like a mofo! 😢

**Comment by RainbowMiner** [comment]
So it's working perfectly on two mining rigs, but not on that one gaming rig?
We need to find out the difference. Does the gaming rig have different kind of GPUs?

**Comment by RainbowMiner** [comment]
Is it eventually possible, that NBminer is crashing on the gaming rig?

**Comment by acos0874** [comment]
My set up is 6x1660ti (working fine)
6x1070ti (working fine)
1x2070 super

I'm currently trying mining without power costs to see if that helps.

**Comment by acos0874** [comment]
I'll monitor it for a while for crashing.

**Comment by acos0874** [comment]
Ok a slight observation. I keep getting the message 'Socket error: Remote host closed the connection'. I'm guessing cos of the high starting difficulty means shares aren't being submitted frequently enough. However, this isn't showing as a crash. In fact since I switched to revenue only, it has stayed on one miner for 18 minutes. I suspect this isn't the cause of the problem.

**Comment by acos0874** [comment]
So switching to revenue only it hasn't changed in 26 minutes and this is with the hysteresis set at 10%!! But now my 1660ti has reverted to switching ever 2 minutes.

**Comment by acos0874** [comment]
OK so all rigs seems to have settled down now, which seems to suggest it has something to do with the first 1-5 minutes of the rig selecting an algo. Could it possibly be something to do with the way the switch prevention algo applies it's accuracy calculations?

For example, if the penalised value were being compared to the non-penalised values.

**Comment by acos0874** [comment]
The other unusual thing is it ignores the minimum intervals which I've set to 3.

**Comment by RainbowMiner** [comment]
> I keep getting the message 'Socket error: Remote host closed the connection'.

> The other unusual thing is it ignores the minimum intervals which I've set to 3.

That would normally indicate crashing miners. I will dig a bit deeper, just to be sure.

**Comment by acos0874** [comment]
Wouldn't they show as crashes in the activity log?

**Comment by RainbowMiner** [comment]
That depends - normally, yes, but there exists a condition, where it might be ignored.
So, the rig contains exactly one GPU?

**Comment by acos0874** [comment]
Yes, but I'm still getting the occasional bout of frequent switching on the multi card rigs still. It seems that once the rig has 'bit' onto an algo for over 5 minutes it tends to stay put, but it can get stuck switching in a loop in the opening couple of minutes. I don't think it's due to crashing because I've used the same OC settings as I've used for months with no problems. Thanks for looking into this.

**Comment by RainbowMiner** [comment]
Yes, I doubt the crashes, too.  Could you eventually create a Debug file on the one-GTX2070 rig, too?

**Comment by acos0874** [comment]
[debug_2020-01-10 (2).zip](https://github.com/RainbowMiner/RainbowMiner/files/4046201/debug_2020-01-10.2.zip)

The current settings are 'revenue only' and hysteresis 10%.

**Comment by acos0874** [comment]
I've restarted both instances of rbm twice and the switching seems to have stopped on both. Could possibly be due to benchmark fluctuations?

**Comment by RainbowMiner** [comment]
Sure, that is very well possible. It would then take some time, until all miners have stabilized.
- but -
I have discovered a problem in the code: eventually try to set `"FastestMinerOnly": "0",` - this function is pretty old and it I think, it doesn't deal with different intensities on miners. But I will dig more.

**Comment by acos0874** [comment]
I think the fastestmineronly option may be the problem. It's the only one that makes sense if the current miner gets replaced with the next fastest miner. I thought it was just for display purposes but maybe not.

**Comment by RainbowMiner** [comment]
Thank you so much for bringing this problem up 👍 
It lead to the discovery of two design flaws in the core:
- the "FastestMinerOnly" function now respects multiple intensities, when dual mining
- the miner's hysteresis did work in the wrong direction on negativ profit miners:
  use `profit x (1 + hyst/100) - cost` instead of `(profit - cost) x (1 + hyst/100)` for comparision

**Comment by acos0874** [comment]
That's great. Thank you for your efforts. Glad we got to the bottom of it

**Comment by khayto** [comment]
"I have added "Intensity" to miners.config.txt for Gminer and NBminer. Will be in the next release, see commit 2b86f99"

does this actually work? tried it and it didnt seem to do anything (changed both eaglesongethash and ethasheaglesong). if it does work, does it support multiple intensities (-di 4,4,4,8,8,8 for exemple) and how does it interact with rbm benching all 10 intensities?

the bat file i use looks something like this ''-di 7,7,10,6,9,9'' this is what i have to use to get close to optimum ethash hashrate while getting as much eaglesong hashrate as possible, cant get anywhere close using all the same.

**Comment by RainbowMiner** [comment]
Yes, it does work, but it works different, like one might expect: the "Intensity" in miners.config.txt just defines which intensities are allowed for Benchmarking. Rainbowminer, by default, uses all intensities 0..10 for benchmark. With this setting, you can simply tell Rainbowminer to use 8..10, only, for example.

To be able to define multiple intensities, you will need to add "-di 7,7,10,6,9,9" directly to the "Params" in miners.config.txt (you will need to find the right "NBminer-devicegroup1-devicegroup2.." or "Gminer-devicegroup1-devicegroup2-.." section).

**Comment by acos0874** [comment]
Also isnt it possible to run custom device groups and switch to device or combo mode?

**Comment by khayto** [comment]
@acos0874 not for this particular rig, has a g3930 cpu that takes ages to complete the runs when in combo mode.
@RainbowMiner thanks, seems to work but also looks like it applies to all the variants so also have to add a value in the intensity field so theres only 1 bench. now just gotta get ethpill stable cause it doesnt always apply.

using both ethasheaglesong and eaglesong ethash in the configs, ive tried first at intensity 10 with the configs i use, and a 2nd at 9 with bit less intensity to have higher eaglesong hashrate in case its ever that profitable but it doesnt seem like they both show in the miner, it did however bench both.

{
      "MainAlgorithm": "Eaglesong",
      "SecondaryAlgorithm": "Ethash",
      "Params": "-di 7,7,9,5,8,8",
      "MSIAprofile": "",
      "OCprofile": "",
      "Difficulty": "",
      "Penalty": "",
      "Disable": "0",
      "Intensity": "10"
    },
    {
      "MainAlgorithm": "Ethash",
      "SecondaryAlgorithm": "Eaglesong",
      "Params": "-di 7,7,10,6,9,9",
      "MSIAprofile": "",
      "OCprofile": "",
      "Difficulty": "",
      "Penalty": "",
      "Disable": "0",
      "Intensity": "9"
    },

**Comment by acos0874** [comment]
Have you tried device mode? It seems to me this won't use much more CPU and will allow rbm to automatically select intensities per device type. CPU load shouldn't be too bad if you're only using nicehash

**Comment by khayto** [comment]
@acos0874 yea, teamviewer + msia doesnt help to be fair. legacy just runs smoother.
