### ISSUE TITLE
Daggerhashimoto & CKB on Nicehash

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#806]
Keeps on crashing continously

![Annotation 2020-01-09 075043](https://user-images.githubusercontent.com/32984054/72032405-479a8600-32b5-11ea-9204-ce19a49ed950.png)

![Annotation 2020-01-09 075014](https://user-images.githubusercontent.com/32984054/72032351-1c179b80-32b5-11ea-984c-a8d65fd4773b.png)

**Comment by RainbowMiner** [comment]
That looks like, Gminer and NBminer's Eaglesong implementation is not compatible with Nicehash. Actually, very strange, I tried it out, yesterday and everything worked fine. 
So there are a few other possibility (I will investigate further): the Hongkong proxy's Eaglesong implementation of Nicehash is false, or the Nicehash Eaglesong market is drying up, in between.

**Comment by RainbowMiner** [comment]
Ok, so NBminer and Gminer both work on Eaglesong/Nicehash:
![image](https://user-images.githubusercontent.com/39437538/72057359-91439a80-32ce-11ea-83af-7dcf5712d270.png)
.. now I will try the different Nicehash stratums.

**Comment by RainbowMiner** [comment]
Good, the hk proxies seem to be ok, too:
![image](https://user-images.githubusercontent.com/39437538/72057787-41b19e80-32cf-11ea-8f68-c39a2b92e7a9.png)

**Comment by RainbowMiner** [comment]
So the most probably answer to this issue is, that there has been a temporary technical problem with the Nicehash proxies. Eventually, Nicehash has already solved it.
