### ISSUE TITLE
F2Pool Fees

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#807]
I think f2pool API already accounts for fees deducted, so there may be no need for rbm to calculate an additional 3% fee.

**Comment by RainbowMiner** [comment]
The values are parsed from their index page:
![image](https://user-images.githubusercontent.com/39437538/72062690-94438880-32d8-11ea-9b9a-c7e399b5b2ab.png)

I had assumed, that the estimated daily revenue is excluding the 3% fee. Are you 100% sure, that the estimated daily revenue is already deducted? If yes, I will need to change this.

**Comment by acos0874** [comment]
I was comparing it to zergpoolcoins, wtm and minerstat. 

Minerstat says $156. 
WTM says $151
Zergpoolcoins says $151
f2pool says $148 (compared to minerstat it's about -3% which is why I thought fee was already deducted.

I dunno which is right. It's not at the top of profitability for me anyway so it doesn't really matter too much. I suppose it depends where they draw their price data from.

**Comment by RainbowMiner** [comment]
Ok, I will ask their support to be sure.

**Comment by RainbowMiner** [comment]
I've got clarification from the f2pool support:
> The  "Estimated Daily Revenue" has reduced by the pool fee.
The rbminer.net API scanner has been adapted, accordingly.

**Comment by acos0874** [comment]
Ace. Thanks!
