### ISSUE TITLE
multiple algo entries per miner

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#81]
miner.config.txt file grew very big with repeated algo entries per miner. attached zip
[miners.config.txt.zip](https://github.com/RainbowMiner/RainbowMiner/files/2342842/miners.config.txt.zip)

**Comment by RainbowMiner** [comment]
Ok, I will check it. It should not happen.
RBM

**Comment by RainbowMiner** [comment]
Sorry for that! I included a cleanup function that will remove all duplicates automatically.
