### ISSUE TITLE
Some kind of ERROR..!!

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#810]
please see the screenshot
![Screenshot_197](https://user-images.githubusercontent.com/32984054/72220381-18666c00-3576-11ea-9a9f-d19da58dd8f6.png)

**Comment by RainbowMiner** [comment]
Looks like Aionmine no longer sends the network difficulty. I'll check with them and post an intermediate fix for that.
This is the same issue: #811

**Comment by RainbowMiner** [comment]
Yeah, that's the problem.
![image](https://user-images.githubusercontent.com/39437538/72221468-5a35e900-355b-11ea-90b2-2cc5f089b934.png)

**Comment by RainbowMiner** [comment]
I have posted a fix. Will be in the next release.
