### ISSUE TITLE
Pausing Autoupdate

### ISSUE THREAD

**Issue by SuperBartimus** [RainbowMiner/RainbowMiner#814]
Referencing https://github.com/RainbowMiner/RainbowMiner/issues/795

Thanks for adding it.
Additional suggestion:  Apply the pause settings to the autoupdate feature.
Notice that while I'm working, the script updates causing the newly generated window to interrupt my work.  Also, the script will go through one cycle of mining before re-pausing.

**Comment by RainbowMiner** [comment]
Of course, I will change this.

**Comment by Nickfost** [comment]
smart
