### ISSUE TITLE
Suggestion: Disable/Enable Miners in the benchmark page

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#816]
Rather than navigating to the miner config files, could there be a button or text box on the benchmark page of local host? It could possibly also include a place to enter miner parameters?

**Comment by RainbowMiner** [comment]
I have already added something similar to http://localhost:4000/miners.html
![image](https://user-images.githubusercontent.com/39437538/72428068-3e198e00-378d-11ea-9de2-d240085672c4.png)
.. it's switch on/off, only, currently. But we could eventually add parameters there, too.

**Comment by acos0874** [comment]
Oh yea great I never noticed!
