### ISSUE TITLE
Pool addition

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#817]
Thanks M8,

Can we also have Leafpool please

**Comment by RainbowMiner** [comment]
You are welcome :) Yes, we can add leafpool, too. But first I'll take my efforts to OceanMining pool.

**Comment by RainbowMiner** [comment]
LeafPool added.

**Comment by saroshpatel09** [comment]
thanks m8.

**Comment by saroshpatel09** [comment]
i do not see it in the pools.config.txt even after updation
