### ISSUE TITLE
Added specific coin to schedualer get still mines something else.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#818]
I have XMR set as a filter during certain times in the scheduler for testing purpose.

Under Benchmarks only RandomX shows up. Yet the system is still mining on Nicehash during this time.
[debug_2020-01-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/4060948/debug_2020-01-14.zip)

**Comment by RainbowMiner** [comment]
Ok, I'll test this.

**Comment by RainbowMiner** [comment]
The detection, using Algorithm/ExcludeAlgorithm in scheduler.config.txt was broken. I have fixed this: 92f1f16a9829307e692c2e729032b86e6995f7fd

Hint: excluding a coin, using ExcludeCoinSymbol will _not affect Nicehash_, since Nicehash does not use coins, but algorithms, only.

**Comment by RainbowMiner** [comment]
> Hint: excluding a coin, using ExcludeCoinSymbol will not affect Nicehash, since Nicehash does not use coins, but algorithms, only.

.. I have updated Nicehash pool, so that there will be CoinSymbols for distinct Algorithms.
