### ISSUE TITLE
Miners stuck in benchmarking state 

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#82]
All benched are done but the state on the webpage is benchmarking.. running touchBenchmark did not help.

![screenshot_20180902-100714_teamviewer](https://user-images.githubusercontent.com/35561346/44953778-72422680-ae98-11e8-8062-9b73de4dd422.jpg)
![screenshot_20180902-100732_teamviewer](https://user-images.githubusercontent.com/35561346/44953779-72422680-ae98-11e8-9b6d-66dfd605d404.jpg)

**Comment by RainbowMiner** [comment]
Yes, I see. This is related to the new file organization in the Stats directory. I will correct the API.

RBM
