### ISSUE TITLE
RM Crashes within a Few Minutes of Starting

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#821]
I was hoping you can analyze this debug file.
[debug_2020-01-16.zip](https://github.com/RainbowMiner/RainbowMiner/files/4072296/debug_2020-01-16.zip)

**Comment by jch9678** [comment]
bumping this to see if you could take a quick look.  I haven't been able to run RM for a few days.

**Comment by RainbowMiner** [comment]
Very, very strange! Did this start to happen pretty suddenly, or has there been some event? E.g. Windows Update, a new RainbowMiner release?
I cannot find a clue in the logs, it pretty much looks like the powershell process is being killed at a random point. 
Do you have any anti-malware, anti-virus or process control running, that could eventually kill the process?

**Comment by RainbowMiner** [comment]
Also, could you please try to run Updater.bat ? Eventually, there is a corrupted source file somewhere.

**Comment by RainbowMiner** [comment]
A third question: do you see any red errors, in case RainbowMiner crashes? Or is it just gone?

**Comment by RainbowMiner** [comment]
Eventually try to re-install powershell 6.2.3 - maybe it's broken.

**Comment by jch9678** [comment]
Yes, it just started happening suddenly.  I have windows update turned off.  I doubt it was a new RainbowMiner release as I have identical rigs and those updated just fine.  All antivirus software is turned off via group policy.  I never see any red errors, RM just disappears.  I'll update RM and re-install powershell.

**Comment by jch9678** [comment]
After Updating and Re-installing Powershell, the system just crashed.
[debug_2020-01-21.zip](https://github.com/RainbowMiner/RainbowMiner/files/4091704/debug_2020-01-21.zip)
Maybe it's my Ryzen settings or memory settings, it's just strange it started happening after months of no problems.

**Comment by jch9678** [comment]
I copied some Ryzen timings over from another rig and it has been stable for a few hours.  Somehow it prefers a 3733 memory clock.

**Comment by RainbowMiner** [comment]
That sounds good :) So let's hope the issue is resolved.

**Comment by jch9678** [comment]
I think the issue is resolved.  Thanks.
