### ISSUE TITLE
Nanominer the config file  is  wrong its starts with device 1 instead  of  0

### ISSUE THREAD

**Issue by qinapps** [RainbowMiner/RainbowMiner#823]
In nanominer is the generated config file  wrong. its starts with device 1 instead  of  0
so its not using one gpu

**Comment by RainbowMiner** [comment]
Do you have an onboard GPU, as well? The Nanominer is special, since it's not accounting for different GPU platforms, but uses a counter for the total amount of GPUs. Anyway, I'll doublecheck the Type_Index counts for Linux.

**Comment by qinapps** [comment]
Dear RainbowMiner,
I don't use the onboard GPU. Im running this machine on windows with AMD Radeon VII. because on linux I have the fault that it can't mine on it

**Comment by RainbowMiner** [comment]
Ok, understood. But there is an onboard GPU, I suppose. That's maybe, where the bug has it's root. I'll dig into it.

**Comment by RainbowMiner** [comment]
Could you eventually run `.\GPUtest.bat` and post the gputestresults.txt ?
