### ISSUE TITLE
Gminer & MiniZ

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#825]
Hi,
when ever my rig starts to Hash BTG/Zero/ZCL it starts with Gminer & then crashes.
MiniZ too doesnt take over after that and that is making a loss on MRR everytime

Then the miner shifts to any other profitable miner but leaves MRR

Also on my rig of 1660ti + P104-100 cards the list function shows 5 gpu's but the miner picks up only 4

**Comment by RainbowMiner** [comment]
> when ever my rig starts to Hash BTG/Zero/ZCL it starts with Gminer & then crashes.

try the new release - it contains the new Gminer v1.94. Eventually it fixes a problematic bug.

> Also on my rig of 1660ti + P104-100 cards the list function shows 5 gpu's but the miner picks up only 4

Could you eventually run "GPUtest.bat" and post the gputestresults.txt here?

**Comment by saroshpatel09** [comment]
reinstalled all drivers including nvidia & redid the entire miner config
got it working for the moment
