### ISSUE TITLE
Verushash keeps disappearing from the list of CPU Miners

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#826]
Verushash keeps disappearing from the list of CPU 
[debug_2020-01-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/4078476/debug_2020-01-17.zip)
Miners

**Comment by paulpoco** [comment]
I had to manually add Verushash to the config file, it didn't get auto added even though I have that setting set.

**Comment by paulpoco** [comment]
@RainbowMiner  I notice Verushash that has been Benchmarked, somehow later the rates in the file go to zero.  And that is when it disappears.

**Comment by RainbowMiner** [comment]
Maybe the CpuminerVerus has a problem with longer runtimes. I have recompiled the miner, it looks like, there is a new Rev.D for the CPU version of the miner. Eventually that solves the problem. But - your CPU needs to support AVX, otherwise you will have to use Nheqminer for VerusHash on CPU

**Comment by paulpoco** [comment]
Ryzen 7 1700 supports AVX.
