### ISSUE TITLE
poolin.com

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#828]
Hey man,
thanks for the pool but can you please let me know what do I put in the wallet..?
do I put my login and password for poolin.com.

**Comment by RainbowMiner** [comment]
Set Poolin subaccount-worker plus minerid (e.g. "miner.001") as wallet address in pools configuration or edit pools.config.txt
.. that's all :)

**Comment by saroshpatel09** [comment]
I have put in the worker name rvn009.001 but doesn't pick up
