### ISSUE TITLE
GPU 0 LOST

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#829]
The GPUTEST showed 5 GPU 
but miner says 1 gpu lost
the screen shot shows 13 MH/s it is a P104-100 8 GB Card
![Annotation 2020-01-18 155230](https://user-images.githubusercontent.com/32984054/72662220-9e693380-3a0a-11ea-8997-9d826b353d5a.png)

[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/4080333/gputestresult.txt)

**Comment by saroshpatel09** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/4080767/gputestresult.txt)

IT shows 5 cards but the miner has picked up 4 cards only 

have rebooted twice - thrice over but no juice.,

**Comment by qinapps** [comment]
see ticket #822 https://github.com/RainbowMiner/RainbowMiner/issues/822

I think its the same problem
