### ISSUE TITLE
Crashes in past 24 hours

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#831]
Please can you add a column to the local host that allows the user to see at a glance if there have been any crashes in the past 24 hours on all linked rigs without having to click on any expansion buttons?

![image](https://user-images.githubusercontent.com/42582444/72742077-e752f080-3ba0-11ea-8f65-114a3734960f.png)

**Comment by RainbowMiner** [comment]
Yes, that's possible, but requires some more changes. The info needs to be passed through rbminer.net. I'll add this.
