### ISSUE TITLE
PBM without the penalty

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#832]
Is there a way of preventing a coin being mined except for when it is considered for post block mining?

**Comment by RainbowMiner** [comment]
Good question. I'll check :)

**Comment by acos0874** [comment]
I realised I responded in the wrong thread. Thanks again!

**Comment by RainbowMiner** [comment]
Oh, me too 🍭

**Comment by acos0874** [comment]
Final request though. Is there some way of introducing a PBM hysteresis in the same way you did with the miners and the pools? I think this would be the cherry on top of the PBM setup.

**Comment by RainbowMiner** [comment]
With the next release, the parameter "CoinSymbolPBM" in pools.config.txt will work as expected, even if there is only one pool for the coin's algorithm selected:

If you put a coin symbol onto the "CoinSymbolPBM" list, this coin will idle on the corresponding pool, until the post block mining condition is met.

**Comment by acos0874** [comment]
Final request though. Is there some way of introducing a PBM hysteresis in the same way you did with the miners and the pools? I think this would be the cherry on top of the PBM setup.

**Comment by RainbowMiner** [comment]
I think, that cherry already exists in coins.config.txt, parameter `"MinProfitPercent"`:
switching to postblock mining only, if the post block miner's profit is at least MinProfitPercent % of the best miner's profit.

**Comment by acos0874** [comment]
Yes I do use that however what actually ends up happening is that as that PBM ignores the switch prevention I get a lot of chopping between nicehash and PBM as soon as one becomes slightly more profitable than the other.  

As an alternative to using an hysteresis it might be effective to have the miner lock to a coin when PBM is detected. Although of the two options I think this would be less desirable

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/72983736-efe23b80-3dd9-11ea-88ef-88671f89db9e.png)
Here's how it looks when it's switching too much. It seems to ignore both the switch prevention and minimum mining intervals. I would be happy if it would obey the minimum mining intervals which I could set to a higher number.

**Comment by acos0874** [comment]
It also seems that pbm is still based on revenue not profit, although I'm not entirely sure.
