### ISSUE TITLE
Add current active Schedule from scheduler.config to Logs

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#833]
Would it be possible to add the current active schedule as defined in scheduler.config.txt to the Logs to assist in validating/troubleshooting when configuring scheduler.config.txt?

**Comment by RainbowMiner** [comment]
Sure, that's a good idea.

**Comment by AnthonyBe** [comment]
Thank you!

**Comment by AnthonyBe** [comment]
`[2020-01-22 21:23:40] INFO: Scheduler profile Wednesday currently active: DayOfWeek=3, From=20:00, To=21:59`

:)
