### ISSUE TITLE
Supported PowerPriceCurrency currencies & mixing currencies

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#834]
The documentation currently states:
`PowerPriceCurrency = currency of your PowerPrice [default=USD]`
can it accept any currency names/formats (i.e. is it just a decorative label) or are there only certain currencies accepted?

If I can use any currency, in my case AUD, if I configure PowerPriceCurrency in AUD can RainbowMiner perform currency conversations when determining profitability? Or does it not need to have uniform currencies to perform these calculations?

Thanks!

**Comment by RainbowMiner** [comment]
All currencies are being converted with the current exchange values. So, as long as you use the international currency names, you are good. AUD will do the job.

**Comment by RainbowMiner** [comment]
This is the list of possible world currencies:

AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL, BSD, BTN, BWP, BYR, BZD, CAD, CDF, CHF, CLP, CNY, COP, CRC, CUP, CZK, DKK, DOP, DZD, EGP, ERN, ETB, EUR, FJD, FKP, GBP, GEL, GHC, GMD, GNF, GTQ, GYD, HKD, HNL, HRK, HTG, HUF, IDR, ILS, INR, IQD, IRR, ISK, JMD, JOD, JPY, KES, KHR, KMF, KPW, KRW, KWD, KYD, LAK, LBP, LKR, LRD, LSL, LTL, LVL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MUR, MVR, MWK, MXN, MYR, MZM, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, RON, RSD, RUB, RWF, SAR, SAT, SBD, SDG, SEK, SGD, SHP, SLL, SRD, STD, SYP, SZL, THB, TMM, TND, TOP, TRY, TTD, TWD, TZS, UAH, UGX, USD, UYU, UZS, VEF, VND, VUV, XAF, XCD, XOF, XPF, YER, ZAR, ZMK, ZWD

**Comment by AnthonyBe** [comment]
Thanks! It would be good to have that in the Wiki.

So in the config.txt I changed PowerPriceCurrency from USD to AUD
`  "PowerPriceCurrency": "AUD",`
and I'm getting the following error on startup and when it starts a miner each subsequent run:
`WARNING: Powerprice currency  not found. Cost of electricity will be ignored.`

[RainbowMiner_2020-01-22.txt](https://github.com/RainbowMiner/RainbowMiner/files/4093854/RainbowMiner_2020-01-22.txt)
[RainbowMiner_2020-01-22_08-37-25.txt](https://github.com/RainbowMiner/RainbowMiner/files/4093855/RainbowMiner_2020-01-22_08-37-25.txt)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4093856/config.txt)
[scheduler.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4093873/scheduler.config.txt)

**Comment by RainbowMiner** [comment]
Yes, add AUD to "Currency", as well.
For example like that:
```
"Currency": "BTC,USD,AUD",
```

**Comment by AnthonyBe** [comment]
Ahhhh.. Perfect! Thank you!
