### ISSUE TITLE
RBM not picking up MRR rental. 

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#837]
RBM not picking up MRR rental. 
I got an email from MRR that I had an MTP rental.

Looked at RBM, it hadn't picked up the rental.  MRR site showed 2.6hrs left of a 3hr rental.  I had to close RBM manually because it seemed to be taking forever for the screen with the key commands to come up.  Then it picked up the rental when I re-run RBM. 
[debug_2020-01-21.zip](https://github.com/RainbowMiner/RainbowMiner/files/4093276/debug_2020-01-21.zip)

**Comment by paulpoco** [comment]
What causes the rental to do this?
![Screenshot_20200121-125217_Chrome](https://user-images.githubusercontent.com/801414/72843222-eed0d300-3c4e-11ea-97d5-af2307f1be25.jpg)

**Comment by RainbowMiner** [comment]
The renter has set the difficulty far too high. Miningrigrentals counts successful shares, only. And if the difficulty is too high, it will take a long time, until your miner creates a valid share. If it is then transmitted, the total hashrate will be a product of shares and difficulty. Thus, the higher the diff, the more your share counts.

**Comment by paulpoco** [comment]
@RainbowMiner why did RBM not pick up the rental right away?  I had to restart RBM so it then picked up the rental right away.

Here is newer debug file that you could also look at.  Also running Verushash the whole 3hrs.
[debug_2020-01-21 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/4093912/debug_2020-01-21.1.zip)

**Comment by RainbowMiner** [comment]
That should not happen, actually. The only explanation could be related to
> because it seemed to be taking forever for the screen with the key commands to come up
.. eventually your CPU has been under heavy load. That can have multiple causes. One could be a Cuckaroo family miner running in parallel to CPU mining.

Looking into your config.txt, eventually change your mining affinity and threads. It will cost you near no hashpower, but allow RainbowMiner to allocate more CPU time.

I strongly recommend you change the two following settings to these values:
```
  "CPUMiningThreads": 14,
  "CPUMiningAffinity": "0xfff5",
```

**Comment by paulpoco** [comment]
@RainbowMiner I was thinking the same thing.  

Verushash right now is making the PC less responsive.  It uses every CPU core 100%.   Which also makes the Monitor update not alway update soon enough, get lots of email saying RBM has gone offline.

**Comment by RainbowMiner** [comment]
> After the change I see 2 Cores that sometimes go below 100%, seems a little moresponsive.

It is an eight core CPU, that uses hyper threading to allow one extra thread per real core.
A hyper thread shares many resources with the underlying core (like L1/L2 cache). That explains, why using the extra threads for mining, together with the real cores, do not increase the hashrate linearly. This percentage of increase can vary, it can even cause a negative impact (for example on many Intel processors).

But what you should always do is to spare some threads for the operating system.

The affinity control works bitwise. The proposed value of 0xFFF5 looks like that:

| hexa decimal | F | F | F | 5 |
| ------------- |:----:|:----:|:----:|:----:|
| binary | 1111 | 1111 | 1111 | 0101 |
| core/thread | 15,14,13,12 | 11,10,9,8 | 7,6,5,4 | ~~3~~,2,~~1~~,0 |

Windows/AMD real cores are on number 0,2,4,6,8,10,12,14, the hyper threads are on number 1,3,5,7,9,11,13,15

As you can see, the value 0xFFF5 uses a total of 14 threads and spares out the hyper-threads number 1 and 3. The decrease in hashrate should be not too harsh.

If the system is still very slow, you might want to free up even more hyper-threads.

| threads | affinity |
|:----:|:------:|
| 13 | 0xFFD5 |
| 12 | 0xFF55 |
| 11 | 0xFD55 |
| 10 | 0xF555 |
| 9 | 0xD555 |
| 8 | 0x5555 |

**Comment by paulpoco** [comment]
I think not picking up the MRR rental was caused my 100% CPU, the changes fixed it.
