### ISSUE TITLE
Issue: Pool entries are invalid

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#84]
Not a major issue but is confusing with basic setup asks for pool names. Just for testing I put all of them in the field. 2 were rejected.

![image](https://user-images.githubusercontent.com/42227809/44957817-6ac85080-ae8b-11e8-8457-5b907e9dc3f2.png)

**Comment by Byrd1083** [comment]
My bad, I see.

**Comment by RainbowMiner** [comment]
I implemented a better duplicate checking method.
RBM
