### ISSUE TITLE
TTminer doesn't launch just no GPU mining during Benchmarking

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#843]
TTminer doesn't launch just no GPU mining during Benchmarking.

I hit the button to re bench the failed miners, it was a long list.

Now it is Benchmarking fine with CPU SrbMinerMulti but it says it launched the GPU miner TTminer MTP, I saw an icon for a blip on the tray but went away right away.

[debug_2020-01-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/4111847/debug_2020-01-25.zip)

Edit: Exclude TTminer, GPU works fine now.

**Comment by RainbowMiner** [comment]
Interesting! It looks like SrbMinerMulti and TTminer interfere with each other. I will tryout on my test rig. So, excluding ttminer is pretty much the best thing, in the meantime.
