### ISSUE TITLE
Balances stopped showing the actual currency auto exchanging to

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#845]
Balances stopped showing the actual currency auto exchanging to, example DASH, just shows BTC balance.

![image](https://user-images.githubusercontent.com/801414/73119348-5750d600-3f15-11ea-840f-5b2948759b09.png)

![image](https://user-images.githubusercontent.com/801414/73119332-253f7400-3f15-11ea-959d-4d53913670ea.png)

[debug_2020-01-25 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/4111885/debug_2020-01-25.1.zip)

**Comment by RainbowMiner** [comment]
Did this happen "Just like that", or did you change anything inside the config files?

**Comment by RainbowMiner** [comment]
Is it eventually possible, that ZergPool paid your DASH and the current balance was zero, at that time?

**Comment by paulpoco** [comment]
> Did this happen "Just like that", or did you change anything inside the config files?

It happened about the time I hit re-benchmark fail miner but that probably has nothing to do with it.

**Comment by paulpoco** [comment]
> Is it eventually possible, that ZergPool paid your DASH and the current balance was zero, at that time?

No I didn't get a a DASH payment.  I did switch from mining to DOGE from DASH and did get a DOGE Payout.

**Comment by paulpoco** [comment]
I had these settings:
![image](https://user-images.githubusercontent.com/801414/73126999-dcb4a480-3f6e-11ea-9637-8bdfc700a834.png)

Then changed back to show excluded pools back to a value of 1 and the Zergpool DASH came back.
![image](https://user-images.githubusercontent.com/801414/73127023-21d8d680-3f6f-11ea-86a1-4436ac95c811.png)

**Comment by RainbowMiner** [comment]
Your settings should work just fine. I will double check.

**Comment by khayto** [comment]
if i uncheck showpoolbalancesdetails, it doesnt show balance for sparkpool at all. i believe its related.
