### ISSUE TITLE
Gminer keeps on crashing

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#847]
Hey i am attaching the debug.zip for your check 

please see what is making gminer keep on crashing

[debug_2020-01-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/4112134/debug_2020-01-25.zip)

**Comment by saroshpatel09** [comment]
have disabled claymore & gminer

**Comment by paulpoco** [comment]
My rig has been using Gminer(Equihash 144,5) all morning just fine.

**Comment by saroshpatel09** [comment]
mine keeps on picking up eth

**Comment by RainbowMiner** [comment]
I think, it's related to #846 - did you eventually update the Nvidia drivers, or did Windows 10 run an update?

In my experience, that has one of the following causes:
- "Lock P2 State" is not set to off
- Overclocking is too harsh
- Hardware failure, most likely one channel of your power supply units. In worst case, it may also be a GPU starting to fail.

This is what I would do:
- please verify, that the Nvidia "Lock P2 State" is set to off, use `.\Includes\NvidiaProfileInspector\nvidiaProfileInspector.exe` to check and set it to off, if needed.
- change the PSU

**Comment by khayto** [comment]
@saroshpatel09 do a fresh install of the latest drivers, download a clean install of rbm in a 2nd folder (dont overwrite yours), reset your overclocks, select gminer as the only miner and nicehash as the only pool, see if it benches. if it doesnt, than i would consider hardware failure as rbm said.

@RainbowMiner isnt p2 state ONLY relevant on GTX 9xx series?

**Comment by paulpoco** [comment]
@RainbowMiner Gminer 96,5 crashing too.
[debug_2020-01-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/4114305/debug_2020-01-26.zip)

**Comment by RainbowMiner** [comment]
@khayto the Force P2 State setting affects all GTX Nvidia.

**Comment by paulpoco** [comment]
P2 set to off causes this:
![image](https://user-images.githubusercontent.com/801414/73142784-91ba9000-4047-11ea-9aa7-cad7f56d944f.png)

Put back to P2 as on for now and the artifact never came back.

**Comment by saroshpatel09** [comment]
Yes i have updated windows

also have uninstalled Nvidia Drivers Via DDU & Reinstalled them

**Comment by khayto** [comment]
there used to be a setting in nvidiaprofileinspector under common that was named ''cuda : force p2 state" that could be turned to OFF. that setting is no longer there, idk since when but it was there before going to geforce 400 drivers. the state of all my gpus when opening nvidiainspector is on p0 by default even tho ive never changed p2 to p0 myself. curious to know why it would be on p2 for you guys?

**Comment by RainbowMiner** [comment]
@paulpoco did you reset all overclocking, before trying? I have written a description on what happens with this setting: https://github.com/RainbowMiner/RainbowMiner/issues/846#issuecomment-578549257

**Comment by saroshpatel09** [comment]
@RainbowMiner gminer keeps on crashing on my single card machine 
it was running smoothly but then poof suddenly stopped
