### ISSUE TITLE
Wrong port on 2miners xzc

### ISSUE THREAD

**Issue by Jimxp** [RainbowMiner/RainbowMiner#848]
There is wrong port on xzc.2miners.com on t-rex. The port is 8008 with too difficult shares, the right port is 8080

**Comment by RainbowMiner** [comment]
Thank you for reporting this! I'll fix it.

**Comment by Jimxp** [comment]
👍

**Comment by Jimxp** [comment]
the port changes to 8008 or 8080 without any pattern on 4.5.2.0 version. It was 8080 one time, and 8008 now
![Screenshot_2020-01-29-00-52-46-226_com android chrome](https://user-images.githubusercontent.com/60325574/73308659-d6098400-4231-11ea-8f60-512079c055c5.jpg)

**Comment by Jimxp** [comment]
And now
![Screenshot_2020-01-29-00-55-48-857_com android chrome](https://user-images.githubusercontent.com/60325574/73308817-2254c400-4232-11ea-95ab-12b8530c32ef.jpg)

**Comment by RainbowMiner** [comment]
Oh dear! I'll look into it asap.
