### ISSUE TITLE
Enhancement: Startup potential for logical error

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#85]
This is just me being a simple man but at basic startup it asks for miner to include and miner to exclude. Same with pools and algos. I have not tried to break it but what would to happen if I selected to exclude and include the same miner or pool on accident. Would it create a logical error? I would think it would be safer for the amateur user to just leave all miners, algos, and pools selected as default and just simply remove the include option and only allow excludes. This way the user doesn't break the logic. Make sense?

**Comment by Byrd1083** [comment]
Another one I'm just not sure about is allowing the seperation of coins from algos. I would think as a multi miner using this type of software, I would not really care what coin I'm mining honestly. I multi mining to maximize profits. If someone wants to be so picky and choosy about a specific coin then I would not even cater to that type of miner. I feel that they would be better served using a solo miner without switching. After all why would I care about a specific coin in an algo that may have 5. Just doesn't seem logical to even need this type of functionality unless you just have a vendetta against a specific coin. Just my thoughts between the 2 different types of miners out there. Just excluding an algo is good enough for me but I'm not the only one on this rock ;-)

**Comment by hernandn01** [comment]
I think the separation of coins is need it when requested. I would like to have the option to mine to a specific wallet for certain coins regardless of pools. In other words, when coin1,coin2,coin3,coin4 mine to wallet1,wallet2,wallet3,wallet4 and do not autoexchange.  And that feature could be activated when that coin is the most profitable only.

**Comment by Byrd1083** [comment]
I could see that makes sense. Still would like to know if including and excluding the same coin, algo, pool, or miner would create a logical error.

**Comment by RainbowMiner** [comment]
Thank you for thinking about this.

**Comment by RainbowMiner** [comment]
> Makes sense?

Absolutely. I will rethink the initial setup. You are right, it is a bit over-the-top.

The logic RainbowMiner follows for algorithm, miners, pools, coins include and exclude is the following:
- If include-list contains elements then accept only elements out of the list
- if exclude-list contains elements then do not accept elements out of the list

RBM
