### ISSUE TITLE
Nicehash C29D

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#851]
It looks like there are still a large number of orders for this on Nicehash. Would it be possible to please re-enable it in RBM?

**Comment by acos0874** [comment]
Used by mimblewimble coin

**Comment by RainbowMiner** [comment]
Sure, I'll give it a try.

**Comment by RainbowMiner** [comment]
Done: 491cce089b55a380b85330f9f50c2cbd8de2c0a8

**Comment by acos0874** [comment]
Thanks!
