### ISSUE TITLE
''No Miners check config'' loop

### ISSUE THREAD

**Issue by khayto** [RainbowMiner/RainbowMiner#853]
seems to be an issue with using groups and i cant figure it out.

for instance if i use 1-6 like bellow in group config :
{
  "GPU#00": "1",
  "GPU#01": "2",
  "GPU#02": "3",
  "GPU#03": "4",
  "GPU#04": "5",
  "GPU#05": "6"
}

upon starting RBM it wont add em to OCprofile.config, i have to close RBM, delete OCprofile.config, delete devices.config restart RBM, than it recreates them. at this point, it works.
but than if i close RBM to go change the OC values, when i restart it, it rewrites the OCprofile.config and devices.config with the default settings (it also keeps the 1-6 like i wanted in the first place) but than the miner just goes into a loop of ''no miners check config'' loop over and over again, until i delete the devices.config and the ocprofile again. i have no idea what to do, it does it on all my rigs with no exception. sometimes if i press R to restart it it goes just fine, but thats like 1/10 and it fails 100% of the time when starting it from the batch file.

Smash let me know i could use GPU# in the ocprofile config and thats all i really needed it for, but i would think it still affects people using combo mode.

**Comment by khayto** [comment]
After i delete the first time it recreates ocprofiles.config like this. after i restart, it readds the normal profiles too and runs nothing.

{
  "Profile1-GTX10703": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile1-GTX10705": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile1-GTX10706": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile1-GTX1070Ti4": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile1-GTX10801": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile1-GTX10802": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile2-GTX10703": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile2-GTX10705": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile2-GTX10706": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile2-GTX1070Ti4": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile2-GTX10801": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile2-GTX10802": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile3-GTX10703": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile3-GTX10705": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile3-GTX10706": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile3-GTX1070Ti4": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile3-GTX10801": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile3-GTX10802": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile4-GTX10703": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile4-GTX10705": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile4-GTX10706": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile4-GTX1070Ti4": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile4-GTX10801": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile4-GTX10802": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile5-GTX10703": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile5-GTX10705": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile5-GTX10706": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile5-GTX1070Ti4": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile5-GTX10801": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  },
  "Profile5-GTX10802": {
    "PowerLimit": 0,
    "ThermalLimit": 0,
    "MemoryClockBoost": "*",
    "CoreClockBoost": "*",
    "LockVoltagePoint": "*"
  }
}

**Comment by khayto** [comment]
after i mod it. (sorry for the wall of text) 
{
  "Profile1-GTX1070-3": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile1-GTX1070-5": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile1-GTX1070-6": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile1-GTX1070Ti-4": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile1-GTX1080-1": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile1-GTX1080-2": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile2-GTX1070-3": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "300",
    "CoreClockBoost": "100",
    "LockVoltagePoint": "850000"
  },
  "Profile2-GTX1070-5": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "300",
    "CoreClockBoost": "100",
    "LockVoltagePoint": "850000"
  },
  "Profile2-GTX1070-6": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "300",
    "CoreClockBoost": "100",
    "LockVoltagePoint": "850000"
  },
  "Profile2-GTX1070Ti-4": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "500",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "850000"
  },
  "Profile2-GTX1080-1": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "400",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "850000"
  },
  "Profile2-GTX1080-2": {
    "PowerLimit": 100,
    "ThermalLimit": 0,
    "MemoryClockBoost": "400",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "850000"
  },
  "Profile3-GTX1070-3": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile3-GTX1070-5": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile3-GTX1070-6": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile3-GTX1070Ti-4": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile3-GTX1080-1": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile3-GTX1080-2": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile4-GTX1070-3": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile4-GTX1070-5": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile4-GTX1070-6": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile4-GTX1070Ti-4": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile4-GTX1080-1": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile4-GTX1080-2": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile5-GTX1070-3": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile5-GTX1070-5": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile5-GTX1070-6": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile5-GTX1070Ti-4": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile5-GTX1080-1": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  },
  "Profile5-GTX1080-2": {
    "PowerLimit": 60,
    "ThermalLimit": 0,
    "MemoryClockBoost": "0",
    "CoreClockBoost": "0",
    "LockVoltagePoint": "0"
  }
}

**Comment by khayto** [comment]
neway im giving up on it, going to mine on phoenix directly in the meantime.

**Comment by khayto** [comment]
idk what exactly the issue is but i am almost 100% sure it is related to gpugroups. since all work just fine when i am not using them.

**Comment by khayto** [comment]
all of this brings me back to an old issue ive always had with using all gpus bundled together by device name rather than having rbm (or mpm) properly split devices apart. since not all gpus are made equal, and some gpus have hynix memory, for instance combo mode cant identify 2 different 1060s, so it bundles em togheter regardless if one has 18mh and the other one has 23mh. this is why ive always used MSIA for overclocking when using RBM or MPM back in the days since i can do per gpu overclock directly in the profile and apply 2 different clock on 2 cards with the same device name.

it would probably be a massive change, but i really believe it would make everything much smoother if rbm was to not group device names by default. as far as im aware, this seems to be so that rbm (mpm) isnt opening 6 different miner per gpu, but now that we have gpugroup and the mining modes, it feels like it would be much simpler to have the ocprofiles.config sorted out per card, the devices.config sorted out per card, make combo use all individual cards seperately and people can just use the gpugroup / combo .configs (which could probably be merged at this point) to set themself up in the same exact way.

anyways! lol, ill let you look into this, see whats up.

**Comment by RainbowMiner** [comment]
Try this: 
- do not use groups, since every gpu can be selected on it's own
- copy your default modelname profile in ocprofiles.config.txt and use one of the three following values as device, instead of your GPU's modelname:
  - name GPU#00, GPU#01, .. descriptor
  - alternatively use the "PCIBusId"
  - alternatively use the "Index"

This is how you find those three values on http://localhost:4000/devices.html
![image](https://user-images.githubusercontent.com/39437538/73300905-1a852780-4212-11ea-88f1-d9d2f6f6cd0d.png)

```
    "Profile1-GPU#03":  {
                           "PowerLimit":  88,
                           "ThermalLimit":  0,
                           "MemoryClockBoost":  "0",
                           "CoreClockBoost":  "110",
                           "LockVoltagePoint":  "*"
                       },
```

```
    "Profile1-3":  {
                           "PowerLimit":  88,
                           "ThermalLimit":  0,
                           "MemoryClockBoost":  "0",
                           "CoreClockBoost":  "110",
                           "LockVoltagePoint":  "*"
                       },
```

```
    "Profile1-05:00":  {
                             "PowerLimit":  80,
                             "ThermalLimit":  0,
                             "MemoryClockBoost":  "0",
                             "CoreClockBoost":  "110",
                             "LockVoltagePoint":  "*"
                         },
```

If you use Profile1, your GPU#03/Index 3/05:00 would always be set to the above values. A directly addressed GPU has prio over a modelname addressed GPU group.

**Comment by RainbowMiner** [comment]
Anyway, I'll check what is going on with the gpugroups.

**Comment by khayto** [comment]
thanks, yeah smash pointed me towards this method and it indeed works and does what i tried to do with the gpugroups.
