### ISSUE TITLE
What is valid setup for Ethashpool?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#854]
From my exchange, my ETH and ETC wallets are the same address?

1) I don't think they use email as the connect, I think it is username.
2) There is also a GRIN31 listed on their webpage.
3) So far only GRIN29 and ETC mines, ETH/ETP/GRIN31 do not show up on RBM main screen.
![image](https://user-images.githubusercontent.com/801414/73293669-2a245200-41b9-11ea-9ef6-2d6653b5e5af.png)

Here are my algos:
  "Algorithm": "Argon2d4096,CpuPower,CryptoNightGPU,CryptoNightHeavy,CryptoNightHeavySaber,CryptoNightHeavyX,CryptoNightLiteUpx2,Cuckaroo29s,Cuckaroo29,Cuckarood29,Cuckaroom29,CuckooCycle,Cuckatoo31,Cuckarood29v,Cuckatoo32,CuckooBFC,DaggerHashimoto,Equihash,Equihash16x5,Eaglesong,Equihash21x9,Equihash24x5,Equihash24x7,EquihashR25x4,EquihashR25x5,EquihashR25x5x3,Ethash,Hex,Lyra2RE3,Lyra2z330,m7m,MTP,NeoScrypt,ProgPoW,RandomHash,RandomX,VerusHash,X16r,X16rt,X16rv2,X16s,X17,X22i,X21s,X25x,Xevan,YescryptR32,Yespower,Yespower2b,Yespoweriots",

My ethash config from pools.config.txt:
![image](https://user-images.githubusercontent.com/801414/73292960-dc5b1a00-41b7-11ea-91bc-41a286a63dca.png)

I only see these possible from RBM main screen:
![image](https://user-images.githubusercontent.com/801414/73293037-fe549c80-41b7-11ea-91d9-d4fe33ccf014.png)

[debug_2020-01-28.zip](https://github.com/RainbowMiner/RainbowMiner/files/4123959/debug_2020-01-28.zip)

Here an example for Phoenix miner for ETH:
./PhoenixMiner -pool stratum+tcp://eth.ethashpool.com:3939 -wal paulpoco -worker RIG_ID -pass x -proto 2 -coin eth

Here an example for Phoenix miner for ETP:
./PhoenixMiner -pool stratum+tcp://etp.ethashpool.com:3737 -wal paulpoco -worker RIG_ID -pass x -proto 2 -coin etp

Here an example for Bminer for GRIN31:
`#!/bin/sh
# Change the following USERNAME to your registered username.
ADDRESS=paulpoco
USERNAME=$ADDRESS.RIG_NAME
POOL=mine.thegrinpool.com:4949
SCHEME=cuckatoo31
PWD=x
./bminer -uri $SCHEME://$USERNAME:$PWD@$POOL -api 127.0.0.1:1880`

**Comment by RainbowMiner** [comment]
Should be working now.
