### ISSUE TITLE
RBM Dev mining is missing Verushash as an Algo for CPU Mining

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#855]
@RainbowMiner RBM Dev mining is missing Verushash as an Algo for CPU Mining.
![image](https://user-images.githubusercontent.com/801414/73295797-37434000-41bd-11ea-8335-911d59e4861e.png)

**Comment by RainbowMiner** [comment]
Oh! Thank you so much. I had forgotten to add it. It's done and will shine up.
