### ISSUE TITLE
YEC Flypool 

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#856]
Hi 

The miners mine very well but suddenly it says 

"MISALIGNED ADDRESS"

and mining stops post that it says
"All miners crashed"

**Comment by RainbowMiner** [comment]
Which miner is crashing?

**Comment by saroshpatel09** [comment]
as usual Gminer

**Comment by saroshpatel09** [comment]
my 1660Ti keeps on crashing says " Misaligned Address"
please tell me what it means
