### ISSUE TITLE
Flypool API

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#857]
The Earnings on Flypool for YEC gives extra ordinary results

is it corrrect.?
I have my doubts but the miner catches it as it shows most profitable like $20 a day.??

**Comment by RainbowMiner** [comment]
"If something seems too good to be true, it probably is too good to be true."

.. I'll better have a look.

**Comment by saroshpatel09** [comment]
please do thank you

**Comment by saroshpatel09** [comment]
so should i disable it for the moment.?

**Comment by RainbowMiner** [comment]
Yes, better disable it, until I find out.

**Comment by RainbowMiner** [comment]
Thank you very much, for bringing this up. I discovered and fix a bug in the price calculation for some rare coins, that are not covered by WhatToMine.
It's fixed in release version 4.5.2.2
