### ISSUE TITLE
claymore and other issues

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#859]
attached is the debug file 

please tell me why are my miners crashing while ewbf runs smooth
even claymore has crashed
the rig is comprised of
2*P104-100 (8GB) + 1*1070Ti + 2*1660Ti

as usual your help would be appreciated

[debug_2020-01-29.zip](https://github.com/RainbowMiner/RainbowMiner/files/4129543/debug_2020-01-29.zip)

**Comment by RainbowMiner** [comment]
That one relates to #861
