### ISSUE TITLE
Issue: V3.8.5.6 still broken when mining on CPU

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#86]
Just did clean install. Did not have any errors going through the basic setup. However, as soon as I completed the setup and chose exit to start, I got this again.

![image](https://user-images.githubusercontent.com/42227809/44957936-9b10ee80-ae8d-11e8-9438-049c6bd67b5e.png)

**Comment by RainbowMiner** [comment]
Could you please send me the miners.config.txt file?

**Comment by Byrd1083** [comment]
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2343556/config.txt)
[devices.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2343557/devices.config.txt)
[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2343558/miners.config.txt)
[ocprofiles.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2343559/ocprofiles.config.txt)
[pools.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2343560/pools.config.txt)

**Comment by RainbowMiner** [comment]
Thank you! This will make it easier to figure out, what is going on.

**Comment by Byrd1083** [comment]
Here is the whole zip

[RainbowMiner-master-testing.zip](https://github.com/RainbowMiner/RainbowMiner/files/2343563/RainbowMiner-master-testing.zip)

**Comment by RainbowMiner** [comment]
Super!! I found the bug. New release is on the way. Thank you for your patience!

**Comment by RainbowMiner** [comment]
The new release is ready to be installed. The problem should now be solved.

RBM

**Comment by Byrd1083** [comment]
Yay, you are awesome. errors are gone and I'm benching stable on my 14x nvidia 1070 with Asus h370 mining master. 👍 🥇
