### ISSUE TITLE
mBTC in localhost & Bech32 support

### ISSUE THREAD

**Issue by khayto** [RainbowMiner/RainbowMiner#860]
anyway to change mbtc to btc or sat all across localhost?

bech32 btc addresses dont work when setting up config.

**Comment by RainbowMiner** [comment]
It's a bit complicated, but I will have a look. Regarding the bech32 btc address: there are currently not many autoexchange pools, that allow bech32 addresses. That's why we still stick with the old BTC format.

**Comment by khayto** [comment]
oh i didnt know, that makes sens, scratch that than.

if its to much work dw about it, its really just personal preference, mbtc just doesnt feel intuitive to me but ik its pretty much industry standard at this point. that being said, i think it would be kinda cool if the currency selection at the top of the localhost page changed the values across all the localhost UI.

**Comment by RainbowMiner** [comment]
>  i think it would be kinda cool if the currency selection at the top of the localhost page changed the values across all the localhost UI

Cool it is :) I changed the js lib accordingly: 2d3a7b8a6674aa53eb84bc36695bc870e707b466
