### ISSUE TITLE
[Nicehash] how set a larger amount for when it goes from Unpaid to Nicehash wallet?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#862]
[Nicehash] how set a larger amount for when it goes from Unpaid to Nicehash wallet?

To have less transactions.

**Comment by khayto** [comment]
you cant, nicehash pays every 4h if +1000 satoshis. what you can do however is go into the mining tab on nicehash, than go to the stats page, and at the bottom check daily. it doesnt change the way nicehash does payouts, but it shows you daily earnings rather than 4h.
