### ISSUE TITLE
Leafpool Connection Issue

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#863]
Hi
am trying to bench BEAM to hash on Leafpool but it keeps on telling me cannot connect

please see if things are correct
![Annotation 2020-02-01 184201](https://user-images.githubusercontent.com/32984054/73592682-c8e6e080-4522-11ea-8ef3-53ce9df29d87.png)

**Comment by RainbowMiner** [comment]
I'll check asap. Eventually leafpool want ssl for BEAM. If yes, I'll change the pool module.

**Comment by RainbowMiner** [comment]
Solved. It needs ssl, I have updated the pool module, will be in the next release.
