### ISSUE TITLE
beepool addition

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#866]
hi,
sorry for being over bearing in adding pools but can you please add beepool also

**Comment by RainbowMiner** [comment]
Buy me a coffee :) Done.

**Comment by saroshpatel09** [comment]
says login failed invalid pool response

**Comment by RainbowMiner** [comment]
For which coin and algorithm did you try?

**Comment by saroshpatel09** [comment]
Happened on cuckoocycle ae on beepool

**Comment by RainbowMiner** [comment]
Could you eventually either create a Debug file or just upload your current .\Logs\RainbowMiner_YYYY-MM-DD.txt file? The AE mining works like a charm, for me. What does cause trouble, is GRIN mining on BeePool.

**Comment by RainbowMiner** [comment]
Regarding GRIN mining on beepool, I found out, that their parser doesn't accept hyphen ("-") in the mining email address. So if mining for some GRIN, make sure, your email address is hyphen free.

**Comment by saroshpatel09** [comment]
also SuperZero.. now not benching on beepool

have uploaded the last 4 txt files


[RainbowMiner_2020-02-03_06-24-04.txt](https://github.com/RainbowMiner/RainbowMiner/files/4147748/RainbowMiner_2020-02-03_06-24-04.txt)
[RainbowMiner_2020-02-03_06-28-45.txt](https://github.com/RainbowMiner/RainbowMiner/files/4147749/RainbowMiner_2020-02-03_06-28-45.txt)
[RainbowMiner_2020-02-03_06-50-56.txt](https://github.com/RainbowMiner/RainbowMiner/files/4147750/RainbowMiner_2020-02-03_06-50-56.txt)
[RainbowMiner_2020-02-03_07-30-57.txt](https://github.com/RainbowMiner/RainbowMiner/files/4147751/RainbowMiner_2020-02-03_07-30-57.txt)
[RainbowMiner_2020-02-03_08-03-00.txt](https://github.com/RainbowMiner/RainbowMiner/files/4147752/RainbowMiner_2020-02-03_08-03-00.txt)

**Comment by RainbowMiner** [comment]
Oh, no ae mining in those. I'ld need the logfile `.\Logs\RainbowMiner_2020-02-03.txt` (the one without hours/min/secs)

**Comment by saroshpatel09** [comment]
[RainbowMiner_2020-02-03.txt](https://github.com/RainbowMiner/RainbowMiner/files/4147880/RainbowMiner_2020-02-03.txt)

**Comment by RainbowMiner** [comment]
Sorry, to bother you again, could you please upload yesterday's log file `".\Logs\RainbowMiner_2020-02-02.txt"`, as well? Still no ae in the today's one.

**Comment by saroshpatel09** [comment]
[RainbowMiner_2020-02-02.txt](https://github.com/RainbowMiner/RainbowMiner/files/4148079/RainbowMiner_2020-02-02.txt)
no bother bud u r doing it to help me out

**Comment by saroshpatel09** [comment]
thanks for all your support

**Comment by RainbowMiner** [comment]
Ok, got it. You might want to try the new release v4.5.2.7
