### ISSUE TITLE
Zergpool unconfirmed earnings

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#867]
I think that at the moment the earnings tracking seems to track the confirmed earnings.  Is it possible for the unconfirmed earnings to be tracked please? This would mean it's easier to see how effective the last 24 hours were. However, it might mess up the error ratio calculations.

**Comment by RainbowMiner** [comment]
True, it's the confirmed earnings, only, currently. I'll see what I can do.

**Comment by acos0874** [comment]
Just so you know, on the zergpool page its already calculated. Would just be nice not to have to manually add it to my nicehash earnings. Perhaps it's included in the API?
