### ISSUE TITLE
How to apply WhatToMine

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#868]
Hey when i run the miner with the Hashrates & then open the WTM website 
both show a different story altogether

please see the screen shots
![Annotation 2020-02-04 082901](https://user-images.githubusercontent.com/32984054/73709900-6f500300-4728-11ea-8b2a-9a3eb18522b2.png)
![Uploading Annotation 2020-02-04 082647.png…]()

**Comment by RainbowMiner** [comment]
Yes, that's perfectly normal. RainbowMiner uses a pretty much more evolved comparison method. If we would simply mine away what WTM dictates, we would end up with lower profits.
