### ISSUE TITLE
MRR

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#869]
Hi 
My rigs used to be picked up in MRR and the miner used to shift automatically to that

But now the miner just doesn't shift to  MRR automatically once the rigs are picked up in MRR

**Comment by saroshpatel09** [comment]
Bro miners not hashing XWP at all just bloody ignoring it

**Comment by saroshpatel09** [comment]
this is what happens when I select only herominers pool for xwp


![Annotation 2020-02-05 210755](https://user-images.githubusercontent.com/32984054/73856535-99561200-485b-11ea-9088-a459f7fa7b52.png)

**Comment by saroshpatel09** [comment]
same thing happens on lucky pool 
Bro my earning on MRR was 0.00175 for 65 hours on XWP

**Comment by RainbowMiner** [comment]
Never had this. My rigs always move to MRR happily. Eventually upload a Debug file, so that I can check. It might be a problem with the renter's pool - if that happens, RainbowMiner retries every 15 minutes, if the renter's pool is working.
Also, please hit http://xsteam:4000/watchdogtimers and see, if all XWP miners are blocked.

**Comment by saroshpatel09** [comment]
The renters pool if is in error will show on my system but here the minera
have not shifted at all
Will upload the debuf file too for you to check

**Comment by saroshpatel09** [comment]
oh and now even the debug file is not downloading and  http://xsteam:4000/watchdogtimers not opening

**Comment by saroshpatel09** [comment]
[debug_2020-02-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/4160917/debug_2020-02-05.zip)

**Comment by saroshpatel09** [comment]
![Annotation 2020-02-05 222922](https://user-images.githubusercontent.com/32984054/73864054-015e2580-4867-11ea-954f-9efa54dc45f6.png)

**Comment by RainbowMiner** [comment]
Ah, sorry, wrong url: http://localhost:4000/watchdogtimers

**Comment by RainbowMiner** [comment]
Ok, regarding MRR: please look into your pools.config.txt, MiningRigRentals section. You have fixed miner names:
```
      "MinerName": [
        "ClaymoreDual",
        "CryptoDredge",
        "Gminer155",
        "MiniZ",
        "Phoenix",
        "Trex",
        "XmrigNvidia"
      ],
```

.. no wonder, XWP is not being used, it's a Gminer or NBminer thing.

**Comment by saroshpatel09** [comment]
[
  {
    "MinerName": "Gminer-GPU#01-GPU#02-GPU#04",
    "DeviceModel": "GTX1660Ti",
    "PoolName": "NiceHash",
    "Algorithm": "Cuckaroom29",
    "Kicked": "2020-02-05T16:26:39.9243352Z"
  },
  {
    "MinerName": "Gminer-Ethash-Eaglesong-0-GPU#01-GPU#02-GPU#04",
    "DeviceModel": "GTX1660Ti",
    "PoolName": "EthashPool",
    "Algorithm": "Ethash",
    "Kicked": "2020-02-06T00:17:49.2170801Z"
  },
  {
    "MinerName": "Gminer-Ethash-Eaglesong-0-GPU#01-GPU#02-GPU#04",
    "DeviceModel": "GTX1660Ti",
    "PoolName": "NiceHash",
    "Algorithm": "Eaglesong",
    "Kicked": "2020-02-06T00:17:49.2729461Z"
  },
  {
    "MinerName": "Gminer-Ethash-Eaglesong-1-GPU#01-GPU#02-GPU#04",
    "DeviceModel": "GTX1660Ti",
    "PoolName": "NiceHash",
    "Algorithm": "Ethash",
    "Kicked": "2020-02-05T23:35:17.4060629Z"
  },
  {
    "MinerName": "Trex-GPU#00-GPU#03",
    "DeviceModel": "GTX1070Ti",
    "PoolName": "2Miners",
    "Algorithm": "MTP",
    "Kicked": "2020-02-06T00:17:49.1269803Z"
  }
]
