### ISSUE TITLE
Issue with latest release when benchmarking eminer.

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#87]
Please see error printout in the picture below. After the error is printed everything crashes. I've added Eminer to the ExludeMinerName parameter and everything works fine again. I hope this is an easy fix for you.

![image](https://user-images.githubusercontent.com/35561346/44958306-c2dc7280-aede-11e8-94fe-2de5e47bc4b7.png)

**Comment by RainbowMiner** [comment]
Look like Eminer has crashed the GPU's at some point. You should reduce the overclocking for this miner.
I will include some extra error checks to get rid of the red messages.
RBM

**Comment by ebojali** [comment]
Hmm don't you choose a relevant msi profiler for this miner?

**Comment by RainbowMiner** [comment]
It worked perfect for my setup. If you setup with my recommendations, I would try to set Profile 5, then Profile 3. And if nothing helps: Profile4.
RBM

**Comment by ebojali** [comment]
Unfortunatley it seems like the GPU temperature shoots into the sky with this miner over 92 degrees celcius. Additionally I think it broke one of my GPUs since the one of my fan has now stopped working. 
![rig_fanstop](https://user-images.githubusercontent.com/35561346/44971227-0e316800-af55-11e8-9ca1-e9a50e345cbe.jpg)
 
I advise carefulness when adding miners and if they are added they need to be tested and disabled by default so no banchmarks are done before configuring profiles etc in config files.
 
![image](https://user-images.githubusercontent.com/35561346/44970973-32407980-af54-11e8-9f02-02979b19ce25.png)

**Comment by ebojali** [comment]
I've tried to start eminer standalone and it seems like it initiates two instances towards GPU0 as the picture below...

![image](https://user-images.githubusercontent.com/35561346/44973524-1e4d4580-af5d-11e8-9ae7-e2c0648736c2.png)

**Comment by RainbowMiner** [comment]
Thank you for the reports. Following it, it seems, like this miner def. runs instable under some circumstances. I will disable it.
RBM

**Comment by ebojali** [comment]
Sounds Good. I can try that. What tool are you thunking about?

**Comment by RainbowMiner** [comment]
I uploaded [RestartDisplayDriversNvidia.bat](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/RestartDisplayDriversNvidia.bat) (right mouse click ans save as..)

It uses nvidiaInspector to restart the drivers.

First rule: reboot your rig at first and check if everything is back to normal

You could also use this tool to reset the P-States to their GPU Bios defaults:
- open windows cmd
- cd to Includes\NvidiaInspector (in RainbowMiner directory)
- now start nvidiainspector by command line input for each GPU (numbers 0 to x):
  - nvidiainspector -restoreAllPstates:0
  - nvidiainspector -restoreAllPstates:1
  - nvidiainspector -restoreAllPstates:2
  - ..

**Comment by ebojali** [comment]
Seems like the fan has loosen up a bit, I pressed it a bit and it fell into place and resumed to spin again.. :) That was very strange..

**Comment by RainbowMiner** [comment]
So it's a mechanical problem with the bearing or simply the axis loosing friction to the fan. This is good news, since the GPU is not damaged :)
Nb: I disabled the Eminer in the new release v3.8.5.10, until further notice.
