### ISSUE TITLE
Reboot.bat

### ISSUE THREAD

**Issue by khayto** [RainbowMiner/RainbowMiner#871]
any chance a function to reboot the rig every x hours could be added? just want my rigs to reboot every couple days but i figured there might eventually be some sort of conditions you could add to watchdog when you got time to also trigger a reboot like miner not updated for extended period of time, repeated miner crashing on launch, monitoring indicates lower or higher wattage than benchmark for extended period of time, just to name a few examples.

**Comment by RainbowMiner** [comment]
Sure, that's possible. If you run RainbowMiner as Admin, I could even integrate a reboot function into the core script.

**Comment by khayto** [comment]
awesome thank you!
