### ISSUE TITLE
RBM in linux

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#872]
I tried this before but can't for the life of me get it working. I have tried ubuntu server and desktop but continually get the following issues...

1. once I install headless drivers/coolbits, then the monitor will not display anything and I have to log in via SSH. (my monitor is plugged into the hdmi socket on the mobo)
2. I cannot get linux to apply any OCs
3. miners like trex crash instantly on start up

Please can you look into why this is not working for me as I have followed the installation instructions to the letter but am not having any success?

**Comment by RainbowMiner** [comment]
Which Ubuntu version did you use?

**Comment by acos0874** [comment]
I have tested Ubuntu 18 lts. Both the desktop and server versions. Currently running desktop

**Comment by acos0874** [comment]
I've noticed that running the nvidia-settings command gives the following error...
![image](https://user-images.githubusercontent.com/42582444/74107749-29050480-4b6b-11ea-812c-e75be0d4e18e.png)

I'm going to try running my monitor through one of the GPUs and try again

**Comment by acos0874** [comment]
Doing this seemed to fix the crashing issue I was having with trex. I also checked the xorg.conf file and the correct coolbits settings are there now where they weren't previously. The only issue now is overclocking is now working. Not even a simple power limit setting.

**Comment by acos0874** [comment]
Do you think you'd ever compile a full linux+rbm package similar to hiveOS or hashr8?

**Comment by acos0874** [comment]
I'm trying ubuntu 16.04 server but am unable to get the nvidia drivers to install. Always says package not found for any version I try.

**Comment by acos0874** [comment]
I officially throw in the towel.

**Comment by acos0874** [comment]
Ok perhaps I didn't give up afterall. So at the moment I have switched back to desktop 18.04 LTS. Drivers etc... all ok. I've created a script using nvidia-smi to set the power limit then nvidia-settings to set the core and mem offset. FInally the script launches the miner and everything is fine and dandy! So I just don't know why RBM refused to run the overclocks since I thought it's all controlled via nvidia-settings.

**Comment by acos0874** [comment]
When I try to launch nvidia-settings through ssh I get this error

> Unable to init server: Could not connect: Connection refused

ERROR: The control display is undefined; please run `nvidia-settings --help` for usage information.

Perhaps this is the same issue rbm is facing?

**Comment by acos0874** [comment]
I discovered this post discussing the issue...

> DISPLAY=:0 XAUTHORITY=/run/user/111/gdm/Xauthority nvidia-settings [youroptions]

Seems to get rid of the error but unfortunately it seems to have no bearing on the actual clock speeds of cards (similarly to RBM!!). I'll keep digging.

**Comment by RainbowMiner** [comment]
Thank you for not giving up :) Would you mind sharing your startup script? I'ld love to find out, why it's not working for you in RainbowMiner.

**Comment by acos0874** [comment]
I got nvidia-settings working on my 1070ti rig using the following script...

`nvidia-smi -pl 130
mem=-1599
DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority nvidia-settings -a "[gpu:0]/GPUGraphicsClockOffset[3]=150" -a "[gpu:0]/GPUMemoryTransferRateOffset[3]=$mem"
DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority nvidia-settings -a "[gpu:1]/GPUGraphicsClockOffset[3]=150" -a "[gpu:1]/GPUMemoryTransferRateOffset[3]=$mem"
DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority nvidia-settings -a "[gpu:2]/GPUGraphicsClockOffset[3]=150" -a "[gpu:2]/GPUMemoryTransferRateOffset[3]=$mem"
DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority nvidia-settings -a "[gpu:3]/GPUGraphicsClockOffset[3]=150" -a "[gpu:3]/GPUMemoryTransferRateOffset[3]=$mem"
DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority nvidia-settings -a "[gpu:4]/GPUGraphicsClockOffset[3]=150" -a "[gpu:4]/GPUMemoryTransferRateOffset[3]=$mem"
DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority nvidia-settings -a "[gpu:5]/GPUGraphicsClockOffset[3]=150" -a "[gpu:5]/GPUMemoryTransferRateOffset[3]=$mem"
`
Is this how RBM does overclocking?

Using the same script I can't get it working on the 1660ti rig. I noticed that xorg was only running on the main GPU and was getting an error message. So I did a fresh install of ubuntu + drivers ensuring the integrated graphics were disabled and pcie gen 1 was enabled. Now xorg is running on all cards, there's a coolbits entry for every card, but the commands above seem to have no effect on the clock speeds.

**Comment by acos0874** [comment]
Hurray I think I sussed it!

I used the attribute GPUMemoryTransferRateOffsetAllPerformanceLevels and it worked.

https://devtalk.nvidia.com/default/topic/1031142/linux/-390-x-unable-to-modify-gpumemorytransferrateoffset-and-gpugraphicsclockoffset-via-nvidia-settings-/post/5248352/#5248352

**Comment by RainbowMiner** [comment]
Nice!! I will add this to RainbowMiner asap. Thank you very much for doing the research!

**Comment by RainbowMiner** [comment]
>XAUTHORITY=/run/user/1000/gdm/Xauthority

.. do you still use this setting in your overclocking script? What happens, if you leave it out?

**Comment by RainbowMiner** [comment]
If you like, you may eventually tryout the change by downloading the [MinerAPIs.psm1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/MinerAPIs.psm1) file into your RainbowMiner folder. Use righ-click save-as. 

And do not forget to set "EnableLinuxHeadless": "1", in config.txt - this adds "export DISPLAY:=0" - and Restart RainbowMiner, of course.

**Comment by RainbowMiner** [comment]
Oh!! I just found a bug in the OCDaemon handler that blocks almost all overclocking commands. I will fix it asap.

**Comment by acos0874** [comment]
> > XAUTHORITY=/run/user/1000/gdm/Xauthority
> 
> .. do you still use this setting in your overclocking script? What happens, if you leave it out?

The display part is essential if remoting in with ssh or otherwise.

**Comment by acos0874** [comment]
I'll wait for the next release and then fire rbm up again to see how it's working.

**Comment by RainbowMiner** [comment]
Please watch the new release carefully - if any error messages appear, please do report them.

**Comment by RainbowMiner** [comment]
Just an annotation:
> Using the same script I can't get it working on the 1660ti rig

Reviewing your script, did you change all `[3]` to `[4]` for the 1660ti? This GPU has one extra power-state (the P4)

**Comment by acos0874** [comment]
I had tested 0, 1, 2 and 3 but I didn't realise 4 was an option.

What actually worked is changing.

`DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority nvidia-settings -a "[gpu:0]/GPUGraphicsClockOffset[3]=150" -a "[gpu:0]/GPUMemoryTransferRateOffset[3]=500"`

To 

`DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority nvidia-settings -a "[gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels=150" -a "[gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels=500"`

So effectively there are no performance levels specified in the command. I haven't tested if this command works on the 1070tis.

**Comment by acos0874** [comment]
I've just fired RBM up again in a remote console and sorry but neither the memory/core offset or power limits seem to working.

**Comment by RainbowMiner** [comment]
Would you eventually upload the current Debug file? I would like to investigate a bit. Also, if you look into the last miner's Bin folder, e.g. if it has been the gminer it's "./Bin/GPU-Gminer" - RainbowMiner should have created some shell scripts. These scripts should all start with your WorkerName.
Could you upload these, too, please?

**Comment by RainbowMiner** [comment]
Do you have "screen" installed on that machine?
Also, it would be very interesting, what happens, if you start:
```
ocdaemon status
```
.. in the command line.

**Comment by acos0874** [comment]
> Do you have "screen" installed on that machine?
> Also, it would be very interesting, what happens, if you start:
> 
> ```
> ocdaemon status
> ```
> 
> .. in the command line.

Daemon says running

[debug_2020-02-16 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/4209924/debug_2020-02-16.1.zip)

I'm not too familiar with file transfers in linux so here is a quick screen shot of the file in the 6miner folder...

![image](https://user-images.githubusercontent.com/42582444/74607047-4129d600-50cd-11ea-9da7-be825c7df9b0.png)

**Comment by acos0874** [comment]
and here is the one for trex. Trex always crashes on launch

![image](https://user-images.githubusercontent.com/42582444/74607089-82ba8100-50cd-11ea-9f15-ab9b13a003a5.png)

**Comment by RainbowMiner** [comment]
Ok, it looks like you haven't setup and ocprofiles for the GTX1660Ti, yet:
```
  "OCProfiles": {
    "Profile1-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    },
    "Profile2-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "",
      "CoreClockBoost": "",
      "LockVoltagePoint": ""
    },
    "Profile3-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    },
    "Profile4-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    },
    "Profile5-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    }
  },
```

**Comment by acos0874** [comment]
Oh that's odd I thought there were some defaults. I'll try nowSent from my Samsung Galaxy S9 - Powered by Three
-------- Original message --------From: RainbowMiner <notifications@github.com> Date: 16/02/2020  15:08  (GMT+00:00) To: RainbowMiner/RainbowMiner <RainbowMiner@noreply.github.com> Cc: acos0874 <acostello0874@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RainbowMiner/RainbowMiner] RBM in linux (#872) Ok, it looks like you haven't setup and ocprofiles for the GTX1660Ti, yet:
  "OCProfiles": {
    "Profile1-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    },
    "Profile2-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "",
      "CoreClockBoost": "",
      "LockVoltagePoint": ""
    },
    "Profile3-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    },
    "Profile4-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    },
    "Profile5-GTX1660Ti": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    }
  },


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RainbowMiner/RainbowMiner/issues/872?email_source=notifications\u0026email_token=AKE4DLHLKIECYN7X2AGIM5LRDFJIHA5CNFSM4KRPX4PKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4JSOY#issuecomment-586717499",
"url": "https://github.com/RainbowMiner/RainbowMiner/issues/872?email_source=notifications\u0026email_token=AKE4DLHLKIECYN7X2AGIM5LRDFJIHA5CNFSM4KRPX4PKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4JSOY#issuecomment-586717499",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RainbowMiner** [comment]
Regarding trex, I am pretty  sure there is a library missing. Could you simply run that test script for it and report back, which lib it is?
These are the commands:
```
cd /home/ash/RainbowMiner/Bin/NVIDIA-Trex
chmod +x *sh
./start_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05_nicehash_x16r.sh
```

**Comment by acos0874** [comment]
Power limit is working now where it wasn't previously, so some progress! but the memory offset still isn't unfortunately.

trex runs fine on it's own...

![image](https://user-images.githubusercontent.com/42582444/74607338-14c38900-50d0-11ea-9fad-9a1ada6d9ed6.png)

**Comment by acos0874** [comment]
Sorry hold on linux headless disabled itself

**Comment by acos0874** [comment]
Sorry mem clocking is still not working. I have to go out now so I'll have another look later.

**Comment by RainbowMiner** [comment]
> Sorry mem clocking is still not working. I have to go out now so I'll have another look later.

Thank you very much! I am happy, that the power limits are working, now. We will get the rest working, too, then :)

**Comment by acos0874** [comment]
It looks like by default the startoc file isn't executable.

**Comment by acos0874** [comment]
I made the file executable and it doesn't seem to have made a difference. OC still not being applied. Although when I run the file independently it works fine.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74609188-a25aa500-50df-11ea-8eff-f7a750d98e0b.png)

**Comment by acos0874** [comment]
Hmm I changed to executable and ran. It required root so did, but then I get an error...

![image](https://user-images.githubusercontent.com/42582444/74609223-f82f4d00-50df-11ea-8ba5-f65a82f6ef41.png)

**Comment by RainbowMiner** [comment]
Now that's interesting. This script is being executed by RainbowMiner (using the ocdaemon, so it behaves like root). It explains, why the power limit is set correctly, but the nvidia-settings is not applied.
So, all we need to do, is to get this script working.
Actually, I still do not have the XAUTHORITY setting in it. Would you mind edit the file and add the line
```
export XAUTHORITY=/run/user/1000/gdm/Xauthority
```
right in the next line, after the current `export DISPLAY=:0;export CUDA_DEVICE_ORDER=PCI_BUS_ID` and re-run the script?

**Comment by acos0874** [comment]
I will try, but it seems that running the script as root causes nvidia-settings to play up. This is how the original script seemed to handle it.

![image](https://user-images.githubusercontent.com/42582444/74609888-68d96800-50e6-11ea-872f-4fc3901b8e32.png)

**Comment by acos0874** [comment]
Adding 
`export XAUTHORITY=/run/user/1000/gdm/Xauthority`
Caused it to work fine when run as root. So I suspect this may be the final step in getting it working live in RBM

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74610000-2ebc9600-50e7-11ea-9a3e-e3de7fe8f075.png)

**Comment by RainbowMiner** [comment]
Wow :D Now that's nice. So I'll add these settings asap. Thank you for trying!

**Comment by RainbowMiner** [comment]
Oh, actually, there is another one. 
Could you eventually download one of my new detection scripts an try them out? 
This is what you would have to copy-n-paste to the command line:
```
wget https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/IncludesLinux/bash/getxauth.sh
chmod +x *.sh
./getxauth.sh
```

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74610226-249b9700-50e9-11ea-8ace-ca02fafc8de8.png)

**Comment by RainbowMiner** [comment]
Hah! Perfect :) Thank you!

**Comment by RainbowMiner** [comment]
Ok, I have added the XAUTHORITY to release v4.5.3.4 - if you feel like it, give it a try. There will be two new parameters in Config/config.txt:
```
  "LinuxDisplay": "$LinuxDisplay",
  "LinuxXAuthority": "$LinuxXAuthority",
```
Normally, you should not need to change them. So leave them "on default" with the $-values. The variables will be passed to DISPLAY=$LinuxDisplay and XAUTHORITY=$LinuxXAuthority, respectively.

Defaults:
"LinuxDisplay" = ":0"
"LinuxXAuthority" = result of bash script ./IncludesLinux/bash/getxauth.sh

**Comment by RainbowMiner** [comment]
If it still fails, please have a look into the above startoc.. .sh scripts and look, if both values have arrived there.

**Comment by acos0874** [comment]
Woohoo it works! Well done and thanks. Quick question, locking voltages isn't possible in linux right?

**Comment by acos0874** [comment]
A couple more bugs I'm afraid though. HNS fails to benchmark even though it seems to be hashing fine. So must be an issue with the API. Also I've tested enemyzealot and trex and both crashe on start up with algos like x16r and x16rv2, but run independently there are no problems so must be an issue with how it interfaces with rbm.

**Comment by acos0874** [comment]
[debug_2020-02-16 (4).zip](https://github.com/RainbowMiner/RainbowMiner/files/4211233/debug_2020-02-16.4.zip)

I've tried creating a log file for trex, which I thought it should do automatically anyway but no matter what I try nothing gets generated, which suggests there is a problem with the launch command and trex isn't even firing up.

**Comment by RainbowMiner** [comment]
> Woohoo it works! Well done and thanks. Quick question, locking voltages isn't possible in linux right?

That's great :) And yes, locking voltages is not possible, when running linux.

> Also I've tested enemyzealot and trex and both crashe on start up with algos like x16r and x16rv2, but run independently there are no problems so must be an issue with how it interfaces with rbm.

Oh, that's bad. They should run without problem. Actually, they are called a bit different (RainbowMiner uses the start-stop-daemon to fire up miners, if it finds it). So maybe that could be the culprit.

What you could try is to set `"EnableMinersAsRoot": "0",` in config.txt - that doen't avoid using the start-stop-daemon, but starts the screen process for the miner as user. Does this start the miners?

**Comment by RainbowMiner** [comment]
Could you eventually try the following, too?
```
cd /home/ash/RainbowMiner
wget https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Include.psm1
```
.. and then restart RainbowMiner until trex or enemyzealot fails again?

It should now generate a debug startup script, containing the behind-the-curtain miner launch code in the respective miner folders.

```
cd /home/ash/RainbowMiner/Bin/NVIDIA-Trex
ls debug_*sh
```

What happens if you start that script with and without sudo?
So if it's trex on x16r on nicehash it would be like that
```
sudo ./debug_start_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05_nicehash_x16r.sh
```

```
./debug_start_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05_nicehash_x16r.sh
```

**Comment by acos0874** [comment]
Just to check, am I running start.sh without sudo?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74647316-5bb68a80-5173-11ea-815f-7407d7ba48b1.png)
No file is created unfortunately.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74647465-94eefa80-5173-11ea-8dbd-4cc2731c60f7.png)

![image](https://user-images.githubusercontent.com/42582444/74647486-a33d1680-5173-11ea-837f-f1f169763760.png)

Trex runs fine on it's own. With or without sudo.

**Comment by RainbowMiner** [comment]
We will need the debug_*sh file, first. Have you downloaded the new Include.psm1 into the RainbowMiner folder?

```
cd /home/ash/RainbowMiner
wget https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Include.psm1
```
.. and then restart RainbowMiner until trex or enemyzealot fails again?

**Comment by acos0874** [comment]
Yes I did this but no debug file was created. I'm testing if it works with gminer now then I'll run it again with trex.

**Comment by RainbowMiner** [comment]
Ah! Sorry, wget did not overwrite your current Include.psm1.
Please do the following:
```
cd /home/ash/RainbowMiner
wget https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Include.psm1 -O /home/ash/RainbowMiner/Include.psm1
```

**Comment by RainbowMiner** [comment]
So, here is the full "plan", again :) (btw thank you for your help!)

#### First, try with sudo.

So if it's trex on x16r on nicehash it would be like that
```
sudo ./debug_start_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05_nicehash_x16r.sh
```

If there are no errors, respectively, type the following:
```
screen -ls
```

You should see one screen with the name agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 on the list. If yes, type the following:
```
screen -R agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05
```
.. now you look directly into the eyes of the miner. What does it say?

To get rid of the screen and get back into your command line:
- if the miner runs, press Strg+C to stop it.
- type "exit" + Return

Now check, if the screen is gone:
```
screen -ls
```

.. if it's not gone, type
```
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X quit
```


#### Second, try without sudo.

So if it's trex on x16r on nicehash it would be like that
```
./debug_start_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05_nicehash_x16r.sh
```

If there are no errors, respectively, type the following:
```
screen -ls
```

You should see one screen with the name agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 on the list. If yes, type the following:
```
screen -R agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05
```
.. now you look directly into the eyes of the miner. What does it say?

To get rid of the screen and get back into your command line:
- if the miner runs, press Strg+C to stop it.
- type "exit" + Return

Now check, if the screen is gone:
```
screen -ls
```

.. if it's not gone, type
```
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X quit
```

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74648211-227f1a00-5175-11ea-89fa-2abb7e93cc42.png)

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74648255-30cd3600-5175-11ea-8f3b-493e0bab4a3d.png)

**Comment by acos0874** [comment]
Result of running screen -R agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05


![image](https://user-images.githubusercontent.com/42582444/74648276-3d518e80-5175-11ea-856e-cbb3288f2d35.png)

**Comment by RainbowMiner** [comment]
Oh! That's not much.
What is the contents of the debug shell script?

**Comment by acos0874** [comment]
`#!/usr/bin/env bash
screen -ls "agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05" | (
  IFS=$(printf '\t');
  sed "s/^$IFS//" |
  while read -r name stuff; do
    screen -S "$name" -X stuff ^C >/dev/null 2>&1
    sleep .1 >/dev/null 2>&1
    screen -S "$name" -X stuff ^C >/dev/null 2>&1
    sleep .1 >/dev/null 2>&1
    screen -S "$name" -X quit  >/dev/null 2>&1
    screen -S "$name" -X quit  >/dev/null 2>&1
  done
)
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -d -m
sleep .1
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X stuff $"export DISPLAY=:0\n"
sleep .1
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X stuff $"cd /\n"
sleep .1
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X stuff $"cd '/home/ash/RainbowMiner/Bin/NVIDIA-Trex'\n"
sleep .1
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X stuff $"export CUDA_DEVICE_ORDER=PCI_BUS_ID\n"
sleep .1
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X stuff $"export LD_LIBRARY_PATH=./:/opt/rainbowminer/lib\n"
sleep .1
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X stuff $"start-stop-daemon --start --make-pidfile --chdir '/home/ash/RainbowMiner/Bin/NVIDIA-Trex' --pidfile '/home/ash/RainbowMiner/Data/pid/agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05_pid.txt' --exec '/home/ash/RainbowMiner/Bin/NVIDIA-Trex$sleep .1`

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74648577-df717680-5175-11ea-98fb-9f285f0322b2.png)
I got to here. Check the power draw at the wall and miner isn't running.

**Comment by acos0874** [comment]
So I run

screen -R agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05

But just get this...

![image](https://user-images.githubusercontent.com/42582444/74648660-06c84380-5176-11ea-8264-93310b31198c.png)

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74648923-7b02e700-5176-11ea-94b2-0f3d6c7e8349.png)
This is what I get if I repeat the process with gminer.

**Comment by RainbowMiner** [comment]
So, it looks like gminer would run in RainbowMiner.
But what happens to the trex?
Could you eventually re-upload the contents of the trex's debug shell script? Is the above cat really complete?

```
cat debug_start_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05_nicehash_x16rv2.sh
```

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74649328-3297f900-5177-11ea-80a5-899e4e238556.png)

**Comment by RainbowMiner** [comment]
That's pretty much perfect and should do the job. I've got the impression, screen's stuff command has an upper limit for string size.
Try the following:
```
Ah! Sorry, wget did not overwrite your current Include.psm1.
Please do the following:
```
cd /home/ash/RainbowMiner
wget https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Include-test.psm1 -O /home/ash/RainbowMiner/Include.psm1
```

And retry RainbowMiner. I have disabled the start-stop-daemon, since this will shorten the command string a lot.

**Comment by RainbowMiner** [comment]
Ok - it's really the stuff command, which messes up. It's restricted to the screen buf size. I'll fix this asap.

**Comment by acos0874** [comment]
Sorry didn't hit submit..


Still the same result I'm afraid

![image](https://user-images.githubusercontent.com/42582444/74650260-375dac80-5179-11ea-8e7d-dbf828f2217e.png)

**Comment by RainbowMiner** [comment]
So still too long, then. Would it be possible for you to open the debug shell script with any editor and copy-n-paste the whole (long) last line as text, so that I can count the characters?

**Comment by acos0874** [comment]
screen -S agnus_gpu00_gpu01_gpu02_gpu03_gpu04_gpu05 -X stuff $"/home/ash/RainbowMiner/Bin/NVIDIA-Trex/t-rex -N 10 -r 5 -b 127.0.0.1:31600 -d 0,1,2,3,4,5 -a x16rv2 -o stratum+tcp://x16rv2.$";

243 characters I think

**Comment by acos0874** [comment]
OH wait hmm... when I open the debug script there's a chunk missing. Can you guide me through how to get the command you're looking for?

**Comment by RainbowMiner** [comment]
Ok, that _is_ too much. I think, the maximum is somewhere around 750 characters. So we found the culprit! I will fix this now.

**Comment by RainbowMiner** [comment]
It should work now. Try the following:
```
cd /home/ash/RainbowMiner
wget https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Include.psm1 -O /home/ash/RainbowMiner/Include.psm1
```

.. and restart RainbowMiner

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/74653346-e56c5500-517f-11ea-9863-b751652c8aed.png)
Superb well done!

**Comment by RainbowMiner** [comment]
Yippie :) Thank you so much for helping me with the debugging.

**Comment by RainbowMiner** [comment]
Finally, I have fixed the linux wrapper, which is needed for some miners (e.g. 6Miner).

**Comment by acos0874** [comment]
Thank you for your hard work

**Comment by acos0874** [comment]
Still a slight glitch.

![image](https://user-images.githubusercontent.com/42582444/74686300-0016ec00-51c9-11ea-9eea-5b0d182f4c70.png)

I have tried changing it manually but it keeps changing back.

**Comment by RainbowMiner** [comment]
Oh yes, I see. I will fix the setup. In the meantime just edit config.txt directly and make it look like that:
```
  "LinuxXAuthority": "$LinuxXAuthority",
```

**Comment by RainbowMiner** [comment]
The both parameters should now always be excluded from server/client config downloads.
- linux: fix LinuxDisplay/LinuxXAuthority, also add automatic fallback to '$' values (issue #872)
