### ISSUE TITLE
Misaligned address

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#874]
Hi

While mining daggerhashimoto on NH the miner keeps on giving misaligned address

please tell me what could be causing it

this happened on Gminer

**Comment by RainbowMiner** [comment]
This normally indicates
- an underpowered GPU (can happen, if connected via riser and USB cables). So check your wiring, just to be sure
- a bad GPU card. Do you happen to know for which GPU model this message happens?

It would be very interesting, if it's happening for other miners, as well. Is it an Ethash exclusive problem, only?

**Comment by saroshpatel09** [comment]
it keeps on happening to my 1660Ti's
and only on ethash
alll other algo's run smoothly

**Comment by saroshpatel09** [comment]
the moment it runs on NH ethash & eaglesong combo it goes down with this error

was nopt happening till 08.302.2020 now started suddenly

**Comment by saroshpatel09** [comment]
![Annotation 2020-02-09 194609](https://user-images.githubusercontent.com/32984054/74103750-d892a480-4b74-11ea-8289-5a98eb8865d6.png)

**Comment by saroshpatel09** [comment]
happening on ethash algo only

**Comment by saroshpatel09** [comment]
but this setup it runs when I increase the core clock
![Annotation 2020-02-09 195035](https://user-images.githubusercontent.com/32984054/74103850-856d2180-4b75-11ea-8ec4-e3e4dfc3b5e3.png)

**Comment by RainbowMiner** [comment]
So it looks to me, that the GPU memory overclocking could be the culprit. In your first screnario, I spotted "+1000", in your second it is at "+800"

**Comment by saroshpatel09** [comment]
correct
and was running smoothly at +1000
also the core memory is increased and thus the power output

**Comment by RainbowMiner** [comment]
How about the cooling of the GPUs? Are the 1660ti pretty dusty? Maybe they run too hot. Blow the dust out.

**Comment by saroshpatel09** [comment]
They are not dusty bro running pretty cool at 60 degrees

**Comment by saroshpatel09** [comment]
also my 1070Ti's running @ 143W am trying to lower the wattage but just not able to
