### ISSUE TITLE
CUDA FAILED..????????????

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#875]
my 1660ti are giving this error

**Comment by RainbowMiner** [comment]
CUDA failed is like 99% related to memory overclocking. Most probably, you will have to lower memory oc for the current algorithm/miner, plus eventually restart the Nvidia drivers (try to run "RestartDisplayDriversNvidia.bat" in your RainbowMiner folder).

**Comment by saroshpatel09** [comment]
![Annotation 2020-02-10 065900](https://user-images.githubusercontent.com/32984054/74114960-db23e700-4bd2-11ea-91af-1a470378f52f.png)

**Comment by saroshpatel09** [comment]
now it automatically kills 2 gpu's 
same config it runs the rest
