### ISSUE TITLE
reboot not working.

### ISSUE THREAD

**Issue by khayto** [RainbowMiner/RainbowMiner#876]
https://imgur.com/a/evFtth4

**Comment by RainbowMiner** [comment]
I see - it looks like WinRM is not configured on your machine. The powershell Restart-Computer command always sends it's request through WMI + WinRM, even on a local-only machine. 

You could follow the following instructions to enable WinRM: https://www.cnblogs.com/chucklu/p/7491868.html

Eventually I could change the command to a "shutdown /r", which is a Windows 10 native command.
I'll try, if this works out, as well.

**Comment by RainbowMiner** [comment]
Ok, commit 0766168cdf2b85b3a5694aad7cfcbd3f293b10d6 should fix this. I have added a fallback to Window's shutdown command.

**Comment by khayto** [comment]
just confirming that the fallback is working as intended, tyvm!
