### ISSUE TITLE
Process garbage collection

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [RainbowMiner/RainbowMiner#877]
Symptom: on Linux (AMD GPU with proprietary drivers installed), RBM stops mining after some hours/days and hardware requires a hard-reboot (use hardware power button to shutdown) due to un-killable processes in forever-waiting loop for IO response.

Investigation reveals:

* all cooling fans are still running
* CPU usage drops to near-zero
* process tree full of PIDs with status "S" and "D", all of which are miner programs
** these processes are un-killable: `kill --signal-KILL {PID}` fails, even when issued as root user
* `pstree` command shows parent process to be init (PID 1)
* `kill --signal-CHLD 1` fail, even when issued as root
* RBM-logs show no errors
* individual miner-logs show no errors

Internet searches reveal process status "D" is an un`KILL`able wait-for-IO-response loop, locking IO device access until originating process releases it on receipt of the awaited response. This is a kernel-level process/IO lock. I do not have a means to determine if the error is in the RBM script or PowerShell (which has a whole raft of problems on non-Windows systems) or gnu-screen or the individual miners.

Question:

Is RBM script properly watching for stop of existing miner processes before it starts a new one?

Most common failing miners - xmrig, nanominer, lolminer

**Comment by ParaplegicRacehorse** [comment]
Just a side-comment, and minor-complaint since I started using RBM:

There is no excuse or justification for running miners as the root user!

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll check the Linux process handling (currently all processes are being killed with kill -9).

**Comment by RainbowMiner** [comment]
It looks like, some miners happen to be unkillable - but what works, most of the times, is to send a ^C to them. So I have changed the kill-function to do that, first.
af8573ccb84ccb089f52ed28e3b7bcd6c03b40b5
60dfaae9154e3e208cb783f1b5348fe9fd64857c
ea82ea9ea2046c68d04e52b9c83a2314e3b44efc

**Comment by ParaplegicRacehorse** [comment]
Great! Waiting for the update to see if that helps. I have, in the past, had to issue CTRL-C multiple times in order to kill miners (wolf-verium miner. grr.) so it will be interesting to watch the results.

When the system crashed like this, software-directed reboot (`sudo shutdown -r now` or `sudo reboot`) have failed with a stuck process waiting for resources. I had to use the hardware power button. Just FYI. It's a reasonable idea, but I doubt it's a solution.

Other update:
I was just looking at an `htop` and noticed that process `pwsh` is running when RBM is running. It is not running (isn't in `pstree` output and cannot be found in a search in `htop`) when a hard crash occurs. So I am fairly certain PowerShell is crashing. Whether this is a related issue or a symptom is unknown and I can't think of a reliable way to test.

**Comment by RainbowMiner** [comment]
> There is no excuse or justification for running miners as the root user!

Some miners apply hardware tweaks, if started as root. Anyway, your complaint is heard: I just added "EnableMinersAsRoot" to config.txt. If set to "0" miners will no longer be started as root, using the OCDaemon (if running). The current default is "1" (=enabled)

**Comment by RainbowMiner** [comment]
Eventually it would make sense to do a `reboot -f` in the case of a stuck miner. Let me know, if the new process kill works out better for you.

**Comment by ParaplegicRacehorse** [comment]
So far, so good. Computer's only locked up on me once since update and it locked so hard, couldn't even switch to a text-only TTY, so I don't know if it was RBM or something else. Lockup happened on trying to launch local instance of Firefox to access the monitor/control panel.

**Comment by ParaplegicRacehorse** [comment]
Still crashing and hard-locking as of 4.5.3.1; just updated to 4.5.3.3 but I don't see anything in the changelog which I think might affect anything.

I _did_ review my logs again. It seems some miners are not able to find my R9390x GPU and are, perhaps, trying to use the Intel integrated graphics of the CPU. I disabled all devices INTEL in my config. GPU miners are still crashing right-n-left, and the RBM script is still not responding to the Q key-press (has done this since .... always? ... in my experience, when a miner is crashing repeatedly or has recently crashed and waiting for a new round for restart.)

My config is old. "VersionCompatibility": "4.4.0.4" kind of old and not updated since that release, until today. Do you think it would help any to delete and start over?

**Comment by RainbowMiner** [comment]
> My config is old. "VersionCompatibility": "4.4.0.4" kind of old and not updated since that release, until today. Do you think it would help any to delete and start over?

That should not change anything. I always keep RainbowMiner backwards compatible.

> I did review my logs again. It seems some miners are not able to find my R9390x GPU and are, perhaps, trying to use the Intel integrated graphics of the CPU.

Ok, that could be a problem. Could you eventually send me your logs? Or even better a Debug file?
I am really interested, which miners cause the troubles, so that I can disable them in case a R9390x is found.

**Comment by ParaplegicRacehorse** [comment]
Oh, would if I could! I decided to try an update to my amdgpu drivers, which failed and borked everything. So I downgraded my kernel to the officially supported kernel and tried the driver install again -- fail! So I backed up my config and stat directories and did a fresh OS reinstall + driver install -- fail! I have a support request out to AMD because the driver really should be able to install on a clean install of an 'officially supported' Linux distro with the officially supported kernel version.

If memory serves, the following miners consistently crashed, regardless of algo:
* WildRig
* TeamRed
* SgminerFancyIX
* ClaymoreDual

The following miners crashed under one or more algos, noted where I remember them:
* lolminer (all mining at Zergpool, none at Nicehash. Go figure...)
* Gminer
* Xmrig-GPU

Interestingly, I have some CPU miners also crashing consistently:
* CpuminerJayddee (Hex, Phi2, X16rv2, ScryptN2)
* XmrigUpx (CryptoNightLiteUpx2)
* CpuminerVerus
* SrbMinerMulti ... seems to have fixed itself after OS reinstall. Was crashing m7m.
