### ISSUE TITLE
Question - Switching weights?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#878]
Is there a way to make RBM reluctant to switch to Nicehash? I want Nicehash to always be there, but I prefer RBM to stick to direct coin mining.

Or put a different way, Make switching to direct mining a normal process but when Nicehash becomes more profitable dont switch RIGHT AWAY, AKA make it harder to switch back to Nicehash then it is to switch to direct coin.

Ok, Either that all made complete sense, or no sense at all! Ha!

**Comment by RainbowMiner** [comment]
> Ok, Either that all made complete sense, or no sense at all! Ha!

Makes perfect sense :)

**Comment by RainbowMiner** [comment]
- add parameter "ForceStablePrice" to config.txt:
  - if set to "1", all pools, including Nicehash, will use their stable price (slow moving average) to compare. All pools will behave equally, then.

**Comment by saroshpatel09** [comment]
where do i set it to "1"
as my config shows "ForceStablePrice": "$ForceStablePrice"

so do i change this.?

**Comment by RainbowMiner** [comment]
@saroshpatel09 yes, make it look like:
```
"ForceStablePrice": "1",
```
