### ISSUE TITLE
grin31 on Nicehash?

### ISSUE THREAD

**Issue by exilebg** [RainbowMiner/RainbowMiner#879]
It seems to me that green31 is not enabled in RBM (Linux) for Nicehash, or I couldn't find it where to enable it. While manually started, Gminer is working fine. Haven't tested other miners.

![gr31-nh](https://user-images.githubusercontent.com/48388831/74585282-b6b97780-4fe3-11ea-9eb2-b65e398545b3.png)
![gr31-nh-2](https://user-images.githubusercontent.com/48388831/74585288-bde08580-4fe3-11ea-89b5-13f59002f2ce.png)

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I will check it asap.

**Comment by RainbowMiner** [comment]
Could you eventually open http://localhost:4000/alldevices on that machine and report back the result?
Also, uploading a Debug file would help my investigation a lot.

**Comment by exilebg** [comment]
Here they are

![alld](https://user-images.githubusercontent.com/48388831/74585877-5c6fe500-4fea-11ea-8802-3b4c22637c7f.png)
[debug_2020-02-15.zip](https://github.com/RainbowMiner/RainbowMiner/files/4208311/debug_2020-02-15.zip)

**Comment by RainbowMiner** [comment]
Ok, super, I think, I have already spotted the problem. To get it more clear, please open http://192.168.1.10/alldevices - without .html - and upload the result as text?

**Comment by exilebg** [comment]
[alldevices.txt](https://github.com/RainbowMiner/RainbowMiner/files/4208327/alldevices.txt)

**Comment by RainbowMiner** [comment]
Ok, fixed. Just download [Include.psm1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Include.psm1) (right-click save-as..) into your RainbowMiner folder - and restart RainbowMiner.

**Comment by exilebg** [comment]
Thank you!
