### ISSUE TITLE
Dual Mining ETH + CKB

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#880]
Hi,
Just a question ..
I am mining ETH on NH & CKB on F2Pool dually.

With the profitability of CKB Down dont you think This dual mining kills even some profitability of ETH.?

**Comment by RainbowMiner** [comment]
That's a question of how much trust you put into Nervos Network. Personally, I think Nervos Network is a good project, so I do not regret mining away a small percentage of my Ethash into their network and collecting some CKB.
