### ISSUE TITLE
WTM

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#881]
Hi,
WTM shows ethereum is most profitable on my 2*1660ti + 2*1070ti rig

but the miner keeps on going to etc on ethash pool with dual mining on CKB

Can you please explain this

**Comment by RainbowMiner** [comment]
> etc on ethash pool

I believe it's mining ETH not ETC? I just compared the prices and ETC comes in at a lower price than ETH, currently.

The dual-mining ETH+CKB is still slightly more profitable, compared to ETH mining (it's about 1% better). The automatic intensity selection of RainbowMiner makes this possible. But this comes at a price, of course, you will have to sell your CKB regularly to cash in the extra profit. Of course you may as well hodl your CKB and hope for a bright future of Nervos network.
