### ISSUE TITLE
What do I put as wallet address for mining GRIN on F2Pool?

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#882]
Hi

Can you tell me what is the wallet addy to be put in pools.config.txt for F2pool

Have put in my account name of f2pool & miners are mining Grin29 + CKB here but the pool shows just CKB not Grin29 anytime

**Comment by RainbowMiner** [comment]
> Have put in my account name of f2pool

That is totally correct, you use your f2pool username as the GRIN wallet.
```
  "GRIN": "yourusername",
```

I just tested and the miner does it's job. For statistics to show up at f2pool, you will have to wait at least 30 minutes.
