### ISSUE TITLE
4.5.3.6 downloader complains about not finding ANY-SRB........

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#885]
4.5.3.6 downloader complains about not finding ANY-SRB........

[debug_2020-02-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/4215401/debug_2020-02-17.zip)

**Comment by RainbowMiner** [comment]
Eventually, the downloader crashed. Please restart RainbowMiner to resolve the issue.
