### ISSUE TITLE
Power difference

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#887]
Hi attached is the screenshot for your reference.
there is a large difference in the power readings shown
please see
![Capture](https://user-images.githubusercontent.com/32984054/74796494-bde7ca80-52ee-11ea-9426-99bd7cb5e6cf.PNG)

**Comment by RainbowMiner** [comment]
That is totally normal:
- the **Device Status** shows live numbers (a snapshot). Those numbers can jump up and down a lot.
- the **Power** column in the Miners sections shows the moving average, thus does reflect the real value.
