### ISSUE TITLE
Force P0 state in Linux

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#888]
Hello again, I've observed more crashing in linux with the same overclocks I'm used to in windows. It appears it is because when the miner first starts it drops into p0 state and the mem clock surges, causing a crash. Is it possible to control the power states in linux?

Alternatively, this may be an adverse consequence of using the 'allpowermodes' overclocking, so perhaps it may be better to use power mode 3 for 10 series and power mode 4 for 16 series cards?

**Comment by RainbowMiner** [comment]
Unfortunately there doesn't seem to be a way to control the power states in linux, as far as I know. But yes, we could of course only set memory and core clock offsets for the topmost power state. I'll add a quick option for that asap.

**Comment by RainbowMiner** [comment]
Ok, added. I'll push a new release.

**Comment by RainbowMiner** [comment]
- linux: add option "EnableOCLinuxSetAllPStates" (issue #888)
  - set to "1", to set mem/core clock offsets to all PStates, instead to the highest, only [default=0]

**Comment by RainbowMiner** [comment]
Now try again, with the new v4.5.3.8 release

**Comment by acos0874** [comment]
It looks like it's still doing it. I've left it as default.

**Comment by RainbowMiner** [comment]
Just to be sure: have a look at http://localhost:4000/runningconfig.html and search for 
![image](https://user-images.githubusercontent.com/39437538/74884069-9f2b1780-5372-11ea-9d4d-8cfe3514ace9.png)
.. it should say "false". If yes, then the default is being locked in correctly.

**Comment by RainbowMiner** [comment]
Just to be sure: do the overclocking offsets still arrive at the GPUs?

**Comment by RainbowMiner** [comment]
> It looks like it's still doing it. I've left it as default. Well I saw the clock speed jump but the miner didn't actually crash.

.. oh, maybe you will have to reset all PState's overclocking offsets to their defaults. Since we now set the highest P-level, only, all others remain untouched (and could in fact hold the values of the former sessions).

**Comment by acos0874** [comment]
I hard reboot after every crash cos it causes the system to lock up.

**Comment by acos0874** [comment]
Unless it's something to do with persistance mode?

**Comment by RainbowMiner** [comment]
> Unless it's something to do with persistance mode?

I don't think so. I'ld try to approach the overclocking values from a more conservative side. That could help. Just to be sure, if you find the time, upload a current Debug file.

**Comment by acos0874** [comment]
I'll give it a go, but ideally I would like to be able to use the same OC settings I used in windows. So for example I would use +600 mem in windows when mining ethereum on 1070ti cards. The problem if I use this in linux when the card goes into p0 state the mem goes to +800 and crashes. In order to avoid this I would need to use +400 mem, which means I'm losing a significant amount of hashrate.

**Comment by acos0874** [comment]
As expected everything is stable when I chop my mem clocks down. Apart from c29d keeps crashing on nbminer but I don't think that's OC related.

**Comment by acos0874** [comment]
[debug_2020-02-20.zip](https://github.com/RainbowMiner/RainbowMiner/files/4232031/debug_2020-02-20.zip)

**Comment by RainbowMiner** [comment]
> I'll give it a go, but ideally I would like to be able to use the same OC settings I used in windows. So for example I would use +600 mem in windows when mining ethereum on 1070ti cards. The problem if I use this in linux when the card goes into p0 state the mem goes to +800 and crashes. In order to avoid this I would need to use +400 mem, which means I'm losing a significant amount of hashrate.

Just to make sure:
you did set "CUDA - Force P2 State" to "Off" with the nvidiaprofileinspector on your Windows machines? If not, it would explain, why +600 kills you Linux, but not your Windows machine, since the Nvidia cards would be forced to P2 State (means, they almost never switch into P0 state and your memory overclocking offset applies to P2 state).

![image](https://user-images.githubusercontent.com/39437538/75093248-4fba3680-5580-11ea-89e6-21f059a95f55.png)

Just in case: if you now want to switch this setting to "Off", make sure to reduce all your memory overclockings by 200 _before_ you restart RainbowMiner.

**Comment by acos0874** [comment]
Yes I use p0state in windows. 

So for example on a 1070ti p0state is 4000mhz sp I would use +400 to get to 4400mhz but on linux it miners in p2state so I need to use +600 to get the same 4400mhz

The problem comes where I use +600 in linux to get to 4400mhz in p2state but it jumps to +800 or 4600mhz when it briefly goes to p0state before miner initiates.

I just thought of a work around, if the overclocks could be reset to 0 when a miner closes, then the this would mean the p0state goes to 4400mhz after OC, then the new OC profile could be applied preventing the crash.

Otherwise if the OC could be applied only to the correct power state then this would be a more permanent solution, but it appears the OC is being applied to all power states causing crashes. I'm currently using Awesome Miner Professional as an interim, which seems to handle OCing in linux without the same jumps to p0state, which suggests it is possible. However, I'm eager to switch back to rbm as soon as possible.

**Comment by acos0874** [comment]
Please can you also give me some guidance on how to get RBM to run automatically at start up? I have tried writing in the crontab file

`@reboot /home/ash/RainbowMiner/start-screen.sh
`

And 

'@reboot root /home/ash/RainbowMiner/start-screen.sh'

But it seems to do nothing and generates errors in the log file.

**Comment by RainbowMiner** [comment]
> I just thought of a work around, if the overclocks could be reset to 0 when a miner closes, then the this would mean the p0state goes to 4400mhz after OC, then the new OC profile could be applied preventing the crash.

This workaround could do the job. I'll implement it.

**Comment by exilebg** [comment]
> 
> 
> Please can you also give me some guidance on how to get RBM to run automatically at start up? I have tried writing in the crontab file
> 
> `@reboot /home/ash/RainbowMiner/start-screen.sh `
> 
> And
> 
> `@reboot root /home/ash/RainbowMiner/start-screen.sh`
> But it seems to do nothing and generates errors in the log file.

Hi, I use rc.local, check first if rc-local.service exist in /etc/systemd/system and activate it. Then write in /etc/rc.local 
sudo /path to RBM/start-screen.sh || exit 0

google it, rc local ubuntu
[How to Enable /etc/rc.local](https://www.linuxbabe.com/linux-server/how-to-enable-etcrc-local-with-systemd)

**Comment by acos0874** [comment]
Thanks for the work around.

To keep you updated, I did a complete fresh install of linux, drivers and rbm on the 1660ti rig. I've set it in standalone mode so it doesn't draw in settings from other rigs. 

  "EnableOCLinuxSetAllPStates": false,

This is shown on the 'running config'

I observed the memory clocks from the localhost and they still continue to spike an additional +250mhz when the cards briefly go to p0state. This suggests that whatever rbm is doing in the background is still causing all Pstates to receive the offset.

**Comment by acos0874** [comment]
> > Please can you also give me some guidance on how to get RBM to run automatically at start up? I have tried writing in the crontab file
> > `@reboot /home/ash/RainbowMiner/start-screen.sh `
> > And
> > `@reboot root /home/ash/RainbowMiner/start-screen.sh`
> > But it seems to do nothing and generates errors in the log file.
> 
> Hi, I use rc.local, check first if rc-local.service exist in /etc/systemd/system and activate it. Then write in /etc/rc.local
> sudo /path to RBM/start-screen.sh || exit 0
> 
> google it, rc local ubuntu
> [How to Enable /etc/rc.local](https://www.linuxbabe.com/linux-server/how-to-enable-etcrc-local-with-systemd)

Thanks for this. It seems to have worked a treat. However, how to do get into viewing the rbm terminal? Since screen -ls returns nothing. Thanks in advance. @exilebg

**Comment by RainbowMiner** [comment]
I have added a reset overclocking function, that kicks in just before exiting a miner:
- add reset overclocking to 0/0, just before shutting down a miner

**Comment by RainbowMiner** [comment]
> Thanks for this. It seems to have worked a treat. However, how to do get into viewing the rbm terminal? Since screen -ls returns nothing. Thanks in advance.

Did you try `sudo screen -R RainbowMiner`, already?

**Comment by acos0874** [comment]
> > Thanks for this. It seems to have worked a treat. However, how to do get into viewing the rbm terminal? Since screen -ls returns nothing. Thanks in advance.
> 
> Did you try `sudo screen -R RainbowMiner`, already?

Of course because it's running as root :)

**Comment by RainbowMiner** [comment]
Also, I will add a mini-program, that will keep all GPUs busy -> thus forcing them to that one busy power state.

**Comment by exilebg** [comment]
@acos0874 
Check your script, if you have used "start-screen.sh" there is no way that "screen -ls" will not work.
It works for me.
![screen](https://user-images.githubusercontent.com/48388831/75165659-651f9400-572b-11ea-848e-9720d6ff1319.jpg)

**Comment by RainbowMiner** [comment]
@acos0874 if you have the time, I would need a beta tester for my new forcePstate script:

```
wget https://github.com/RainbowMiner/RainbowMiner/raw/master/IncludesLinux/bin/forcePstate -O forcePstate
chmod +x forcePstate
./forcePstate &
```

That should launch forcePstate in the background and softly tickle all GPUs. It should have no impact on the total compute power, but keep the GPUs in their fastest P-state.

I currently do not have any linux box with Nvidia in it, so I wrote it "blind". What does it say?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/75168931-94300880-571f-11ea-8eb3-204e4b0cc090.png)
Should I run is as a screen? Can I close the ssh windows?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/75169021-bf1a5c80-571f-11ea-977a-fed3bb6eddae.png)

**Comment by acos0874** [comment]
I used ctrl-C and it still runs in the background

**Comment by RainbowMiner** [comment]
Yes, it's a background job :) To kill it use `kill -9 29990` 
29990 is the process id of forcePstate

**Comment by RainbowMiner** [comment]
The deviceid number seems wrong. It always says "0" - anyway, if this script runs in the background, which powerstate is active for your GPUs?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/75169706-eaea1200-5720-11ea-8545-5da9b176f555.png)
It seems that there has been an adverse side effect of preventing any overclock settings from being applied.

**Comment by RainbowMiner** [comment]
Depends on what NBminer is currently crunching. So, what does nvidia-smi say, if you stop all mining, but leave forcePstate running?

**Comment by RainbowMiner** [comment]
Did the RainbowMiner version already include the reset-patch from above? Or was this a code version pre-commit?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/75170285-c7739700-5721-11ea-8774-4b4aba148232.png)

Process seems to be holding p2 state as intended. I am wondering whether the OC issue I'm facing now is due to some parts of rbm running as root and some not. The reason I suspect this is because when I try to rebench and algo from local host it has stopped deleting those files.

**Comment by RainbowMiner** [comment]
> Process seems to be holding p2 state as intended.

Wow :) I hit the 12. Blindfolded.

> I am wondering whether the OC issue I'm facing now is due to some parts of rbm running as root and some not. The reason I suspect this is because when I try to rebench and algo from local host it has stopped deleting those files.

Yes, that could be very well possible.

**Comment by acos0874** [comment]
I have to go out now. It was mining fine when I left it but oc was not changing correctly. I'll review it more carefully when I get back

**Comment by acos0874** [comment]
Back now. I reset the rig (this is the 1070ti one) and re-ran with sudo and it's mining fine but the OC profiles aren't being applied, cards are running at 3800mhz. Except the power limit seems to be running fine. So I guess I broke something.

**Comment by acos0874** [comment]
OC not working on my 1660ti rig now I ran rbm with sudo after adding stuff to rc.local

**Comment by acos0874** [comment]
Good news. I did a fresh install of rbm to get rid of all the user rights issues. The pstate background service seems to have done the trick. 

Now I just have to figure out how to get rbm to run at start up without sudo so it doesn't destroy my config files.

**Comment by acos0874** [comment]
Holy crap. 1660tis and 2070 supers work perfectly with the new higher overclocks. 

Problem is now my 1070ti rig won't apply OCs 🗡 

I'm using 

  "EnableOCProfiles": "1",
  "EnableOCVoltage": "0",
  "EnableOCLinuxSetAllPStates": "1",                                                                                            
   "EnableLinuxHeadless": "1",

**Comment by acos0874** [comment]
I made some progress... I reset the values in the config file for LinuxDisplay and LinuxXAuthority to $blahblah as suggested in the other thread.

I then ran the set up again but unfortunately it seems the xauthority section has come out blank...

![image](https://user-images.githubusercontent.com/42582444/75186258-7d99a980-573f-11ea-898b-2ab0a71ee693.png)

**Comment by acos0874** [comment]
Phew I fixed it. It seems the xauthority hadn't been collected correctly.

On my server (1660ti) rig it's 

/run/user/1000/gdm/Xauthority

On my client rig (1070tis which wasn't working) it's 

/run/user/121/gdm/Xauthority

So I changed it manually and it's fine. Does your script automatically look up this path? If it does it seems it may have be inadvertently overwritten by the server config.

**Comment by RainbowMiner** [comment]
> If it does it seems it may have be inadvertently overwritten by the server config.

Exactly! I will have to add the parameters to the Exclude list for client/server

The forcePstate script start is now part of RainbowMiner v4.5.4.0:
- linux: add parameter "EnableOCLinuxForcePState"
  - set to "1" to let RainbowMiner start forcePstate tool to force all GPUs into their workload powerstate (issue #888)

**Comment by acos0874** [comment]
Yes I did that manually now. Thanks for the pstate stuff. I think we're up to full speed ahead 💃
