### ISSUE TITLE
nicehashpaid

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#889]
pls bring back nicehash paid so i know when to withdraw

**Comment by acos0874** [comment]
Nicehash paid balance works fine for me. You might just need to check your API settings.

**Comment by Nickfost** [comment]
Bump

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
