### ISSUE TITLE
issue with fetching balances if only Zpool is selected

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#89]
as subj. says. if only Zpool is selected then there is issue fetching balances , i peeked at code not seeing anything weird tbh.

if i add zergpool and nicehash , all balances is fetched correctly , including from Zpool.

testing directly via browser , all apis returned correctly , nothing is blocked.

**Comment by RainbowMiner** [comment]
I will check it. Thank you.
RBM
