### ISSUE TITLE
6 miner

### ISSUE THREAD

**Issue by Adiuk** [RainbowMiner/RainbowMiner#890]
Have latest release and 6block added but 6 miner not showing up or benchmarking, checked miner folder etc and 6miner is there?

**Comment by RainbowMiner** [comment]
Please check, that:
- 6Block is on the PoolName list in config.txt
- your Handshake username is set in pools.config.txt, parameter "HNS" in 6Block section

**Comment by RainbowMiner** [comment]
e.g. config.txt:
```
...
  "PoolName": "6Block,Nicehash,ZergpoolCoins",
...
```

e.g. pools.config.txt:
```
"6Block": {
  "HNS": "yourhnsusername",
...
},
```

**Comment by Adiuk** [comment]
Have checked above and both are there, pool shows in best pools all pools etc, the problem seems to be 6miner is not showing in miners section therefore it is not loading it or benchmarking.

**Comment by RainbowMiner** [comment]
> still no sign of 6miner

This is by intention. I have disabled 6miner, since it's very much too slow, compared to SrbminerMulti (for AMD) and NBminer (Nvidia) or Gminer (Nvidia). The HNS algorithm is Blake2bSHA3 - so everything looks good for you, now.

**Comment by Adiuk** [comment]
Ok that’s good enough for me, mining now at 540 M, thanks for your time
