### ISSUE TITLE
Ethash not mining anymore on 4GB 1050ti

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#891]
it appears that Ethash is not mining on NBminer with Eaglesong or Claymore or Ethminer in 1050ti (4GB)
![image](https://user-images.githubusercontent.com/41829368/75065148-7f484080-54a5-11ea-82eb-f3dfd1b894b5.png)

**Comment by RainbowMiner** [comment]
Oh dear! Yes, it pretty much looks like the Eth DAG size is now too big for 4GB on Win10.

**Comment by RainbowMiner** [comment]
- I will check the current VRAM calculations, so that the overflow will be detected.
- @hernandn01 your only chance will be to use Win7 or Linux, since Win10 always reserves a part of every GPU.

**Comment by RainbowMiner** [comment]
> I will check the current VRAM calculations, so that the overflow will be detected.

Actually, RainbowMiner should already detect, that the DAG size is too big for the 4GB cards. I will recheck.

**Comment by RainbowMiner** [comment]
Solved. We had the wrong DAG size in place on Nicehash and Zergpool. From now on, your 4GB-GPUs should not catch Ethash on those pools, again.

**Comment by hernandn01** [comment]
got the new version now, thanks
