### ISSUE TITLE
CryptoDredge100% cpu utilization

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#892]
I had to completely disable CryptoDredge, can't tell exactly when this started but one or more instances of CryptoDredge take up the whole cpu and Rainbowminer becomes unresponsive, does not switch or complete a cycle. The miner does mine. I used to have 3 instances going fine. Has something change?

![image](https://user-images.githubusercontent.com/41829368/75095691-cd684d00-5554-11ea-8aea-a83b7e74193d.png)

**Comment by RainbowMiner** [comment]
Wow, that's bad! Thank you for reporting this. CryptoDredge has been updated to a new version (v0.23.0) with this commit: b0518b19dfc09b201eb49d0747201155ca5bcf0d - part of RainbowMiner release version v4.5.3.2

Could you eventually upload a current Debug file? I'ld really like to see, which CryptoDredge algorithm kills your machine.

**Comment by RainbowMiner** [comment]
One other thing: it could be related to the Nvidia driver version. Which version have you installed, currently? Eventually, we need to block CryptoDredge on running, when specific driver versions are in use. I remember that this miner had CPU load problems that were related to newer Nvidia drivers, in the past.

**Comment by hernandn01** [comment]
Yes I recently updated drivers. Running 442.19. I will upload a debug file later

**Comment by RainbowMiner** [comment]
> Yes I recently updated drivers. Running 442.19. I will upload a debug file later

Ah, ok. So maybe try the alanfox2000 version v441.41 (look at his repository and follow the installation hints).

**Comment by hernandn01** [comment]
thanks, I will give it a try

**Comment by Minerx117** [comment]
no more alanfox2000
