### ISSUE TITLE
Memory Detection of Newer Cards

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#893]
I previously raised an issue about the 1660tis not passing the check for required memory to mine MTP. There was an update but it didn't fix the problem and I still have to remove the memory check manually. 

A similar issue is occuring with my 2070 Supers in that all c31* algos are not available in linux even though they have 8gb of memory. I also have 1070tis which run 31 algos fine.

I suspect there is some issue with an incorrect memory detection on the newer cards.

**Comment by acos0874** [comment]
Removing the minmem = 8gb from the Gminer.ps1 and NBMiner.ps1 files meant the algos showed up in the profit switching list correctly for the 2070 supers.

**Comment by acos0874** [comment]
Hmm the algos are actually crashing on benchmark. I get some strange memory read outs for the 2070supers vs the 1070tis.

![image](https://user-images.githubusercontent.com/42582444/75197025-2272b180-5755-11ea-8ade-b9d62ad81b04.png)
![image](https://user-images.githubusercontent.com/42582444/75197032-26063880-5755-11ea-8405-ecfa7710f14d.png)

![image](https://user-images.githubusercontent.com/42582444/75197075-47672480-5755-11ea-8aa8-2743bebc38e4.png)

![image](https://user-images.githubusercontent.com/42582444/75197100-5b128b00-5755-11ea-9a48-e8547fa628ce.png)

**Comment by acos0874** [comment]
I got c31 working but c32 says error end of file. Might be a nicehash issue. I don't think it's very profitable right now anyway.

**Comment by RainbowMiner** [comment]
The memory numbers are really weird - but match the nvidia-smi numbers. I will increase the tolerance.

**Comment by RainbowMiner** [comment]
1-7.79GB/8GB = 0.025 - so we need a tolerance of 3% to cover this up. At the moment I have set 2%

**Comment by RainbowMiner** [comment]
Done :)

**Comment by acos0874** [comment]
Thank you. Can you please also adapt the mtp restrictions on 6gb 1660ti. It wasn't working last time I checked but it was in Windows

**Comment by RainbowMiner** [comment]
Ok, do you remember, which miner didn't work for MTP 6Gb?

**Comment by acos0874** [comment]
Trex. Ill have to check it tomorrowSent from my Samsung Galaxy S9 - Powered by Three
null

**Comment by RainbowMiner** [comment]
Ok - normally, that should work, even on Win10. The limit is set to 5GB - but maybe the 1660ti has some lower memory numbers, as well. If you find the time - most important number will be the "Mem"ory column of the device-table.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/75209446-219e4780-5776-11ea-8e5c-b047c15dd41f.png)
