### ISSUE TITLE
After update Nvidia SMI warning and miner crash

### ISSUE THREAD

**Issue by Paul-Trasca** [RainbowMiner/RainbowMiner#894]
WARNING: Could not execute C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe --query-gpu=index,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,pstate,clocks.current.graphics,clocks.current.memory,power.max_limit,power.default_limit --format=csv,noheader,nounits: Index was outside the bounds of the array.

**Comment by RainbowMiner** [comment]
Thank you for reporting this! I'll check asap.

**Comment by RainbowMiner** [comment]
Could you eventually create a Debug file? Just click http://localhost:4000/debug

.. also, how many and which gpus are you using?

**Comment by RainbowMiner** [comment]
It is a very strange error, actually. I think, I will need your help.
Please do the following:
- open a "cmd" (press Windows-Key, then type cmd, then start cmd.exe)
- copy-paste the following into that cmd window and press Return:
  `C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe --query-gpu=index,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,pstate,clocks.current.graphics,clocks.current.memory,power.max_limit,power.default_limit --format=csv,noheader,nounits`

Now please send me the result. Either a screenshot, or mark, copy and paste it here.

**Comment by RainbowMiner** [comment]
> .. and miner crash

Which miners do crash?

**Comment by Paul-Trasca** [comment]
I dont know... how to see this?




PAUL TRAŞCĂ 
office@wpmedia.ro / 0722.527.582

WISE PEOPLE MEDIA SOLUTIONS 
Strada Justitiei 36, sector 4, Bucuresti 
http://www.wpmedia.ro

**Comment by RainbowMiner** [comment]
Best would be, you could upload the following debug informations:
- 1st: could you eventually create and upload a Debug file? Just click http://localhost:4000/debug
- 2nd: how many and which gpus are you using?
- 3rd: get the output of nvidia-smi:
  - open a "cmd" (press Windows-Key, then type cmd, then start cmd.exe)
  - copy-paste the following into that cmd window and press Return:
    `C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe --query-gpu=index,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,pstate,clocks.current.graphics,clocks.current.memory,power.max_limit,power.default_limit --format=csv,noheader,nounits`

**Comment by Paul-Trasca** [comment]
On this new version 0 crashes

**Comment by RainbowMiner** [comment]
If you find the time, I would very much appreciate, if you could upload those debug informations, anyway. It would help me a lot to avoid this problem, in the future.
