### ISSUE TITLE
RBM Running at start-up in Linux

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#895]
I thought I'd set up a new issue so others can refer to it in future. I have been successful in getting rbm to run at boot using this article as referred in the post. 

https://www.linuxbabe.com/linux-server/how-to-enable-etcrc-local-with-systemd

However, I'm not sure if I'm doing something wrong because if I use

`sudo /home/ash/RainbowMiner/start-screen.sh
`or
`/home/ash/RainbowMiner/start-screen.sh`

Then rbm seems to run as root in either case causing the read permissions of the files in the RBM to get screwed up causing OC profiles amongst other things to not work correctly.

So ideally I think the best way to get it working is to change the run level, but I'm not sure of the best way to do this. I've looking into using systemd run levels and also crontab.

**Comment by acos0874** [comment]
I think I got it working with

`sudo -u ash bash -c '/home/ash/RainbowMiner/start-screen.sh' `
I'll have to monitor it for a bit longer to check I don't get the same write permission errors as before.

**Comment by RainbowMiner** [comment]
Nice! So or so, I think I'll add a "chmod" for full r/w permissions on all files to RainbowMiner, in case it is started as root.

**Comment by acos0874** [comment]
Well I hope that doesn't break it! 😕

**Comment by RainbowMiner** [comment]
> Well I hope that doesn't break it! 😕

Don't worry. It will be a simple chmod 0666 to all Cache/Config/Data/Log/Stat files.
