### ISSUE TITLE
1 miner crashed. Restarting loop asap

### ISSUE THREAD

**Issue by jamlazevedo** [RainbowMiner/RainbowMiner#896]
Hi!
Lately I've been getting the message "WARNING: 1 miner crashed. Restarting loop asap.". When I ran the client, for example, "sudo Bin/CPU-Rplant/cpuminer-avx2 -b 53201 -a yescryptr32 -o ..." I get the error: "API bind to port 53201 failed - trying again in 20sec". Can you help me to solve the problem?
System: 
Ubuntu 10.04 (X64)
RainbowMiner v4.5.4.1

Thxs

**Comment by RainbowMiner** [comment]
Eventually the port 53201 is in use by another service on your machine. Try to enable automatic ports in config.txt:

```
  "EnableAutoMinerPorts": "1",
```

**Comment by jamlazevedo** [comment]
Thxs, it fix the problem.
