### ISSUE TITLE
Problem with downloading miners

### ISSUE THREAD

**Issue by SuperBartimus** [RainbowMiner/RainbowMiner#897]
Have one rig that continually flashes the attached screenshot error and won't mine.
the error flashes very quickly and disappears.  Attaching clean log file too.
[log.txt](https://github.com/RainbowMiner/RainbowMiner/files/4263422/log.txt)
![AnyDesk_b7DvAla6IC](https://user-images.githubusercontent.com/22985127/75475920-4dc8ec80-595f-11ea-871d-2c3ede0a9d79.png)

**Comment by RainbowMiner** [comment]
It's a path problem. You have been using a single quote in your directory name. This is something, RainbowMiner doesn't like. For the quick fix, I recommend you rename the directory from "Bart's Utilities" to "Barts Utilities"

**Comment by RainbowMiner** [comment]
I have fixed this in the core. From the next version on, single quotes will be allowed as character in the path to RainbowMiner.
