### ISSUE TITLE
Error on startup - "WARNING: EthDAGsize API failed"

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#898]
Starting a few versions ago I started to notice an error during startup:

`WARNING: EthDAGsize API failed`

I don't think I'm seeing any ill-effects, but figured I should report it.
[RainbowMiner_2020-02-29_18-54-13.txt](https://github.com/RainbowMiner/RainbowMiner/files/4270048/RainbowMiner_2020-02-29_18-54-13.txt)

**Comment by RainbowMiner** [comment]
Thank you for reporting this. It doesn't harm, but it's a flaw, nonetheless. I have fixed it.
