### ISSUE TITLE
Rebooting

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#899]
Hi,

This has started happening recently and very frequently.
" If I run a standalone miner the machine runs smoothly without any issues for days.
  but the moment I start RBM it benches ( Everytime ) and then reboots itself.
  Also Gminer, CD don't bench at all"

Do I need to remove RBM and reset everything again in RBM.?

**Comment by RainbowMiner** [comment]
It would be interesting, which miner causes this. Try to generate a Debug file and upload it here, and I will have a look.
Q: Did you update your graphics drivers, recently?

**Comment by saroshpatel09** [comment]
yes nvidia drivers have just been updated
and if I run rbm the PC reboots so how do I generate the debug file.?

**Comment by saroshpatel09** [comment]
and no particular miner just loads starts mining and boom its reboots the system

**Comment by RainbowMiner** [comment]
> yes nvidia drivers have just been updated

Ok, then it is most probably an overclocking issue.

Q1: Did you set "CUDA Force P2-State" to "Off", using `.\Includes\NvidiaProfileInspector\nvidiaProfileInspector.exe` ?
![image](https://user-images.githubusercontent.com/39437538/75628851-1b2c2780-5bdd-11ea-9578-18c9c7658001.png)

If not, do so. It will most probably cure it.

Q2: If you did install the newest Nvidia drivers available, you will most probably loose some miners (they won't bench or will crash). I recommend, you install the alanfox2000 de-bloated drivers v441.41. See the readme for direct download links: https://github.com/RainbowMiner/RainbowMiner#windows-78110-pre-requesites

**Comment by RainbowMiner** [comment]
> and if I run rbm the PC reboots so how do I generate the debug file.?

Just zip the whole `.\Logs` folder and upload the zip.

**Comment by saroshpatel09** [comment]
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/4272072/Logs.zip)

**Comment by RainbowMiner** [comment]
Your log files indicate a reboot, when RainbowMiner tries to benchmark very power hungry algorithm (like Neoscrypt, Lyra2RE3 or CryptonightGPU) - so it def. looks like an overclocking issue (see above note, regarding the "CUDA Force P2-State"), that seems to drive your GPUs and then your total power over the limits.

**Comment by saroshpatel09** [comment]
am running 3 1660ti + 1 1070ti and a 1000w corsair is running them bro

even when I remove NH it gets into the rebooting mode

**Comment by saroshpatel09** [comment]
[Logs (2).zip](https://github.com/RainbowMiner/RainbowMiner/files/4272271/Logs.2.zip)
![GPU2](https://user-images.githubusercontent.com/32984054/75631975-91507e80-5c1d-11ea-8694-3ba00bee3eb5.png)
![GPU1](https://user-images.githubusercontent.com/32984054/75631977-9281ab80-5c1d-11ea-9699-7fa996f7116c.png)
