### ISSUE TITLE
MWC 

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#900]
Hi,

Am trying to Mine MWC on Icemining but it takes Cuckarood31 instead Cuckarood29

How can I get this coin to mine

**Comment by saroshpatel09** [comment]
and what do I sue as a wallet on this coin 

as tradeogre says I need a file to transfer it to the exchange

**Comment by RainbowMiner** [comment]
I have not been mining MWC, yet. So I recommend you follow this documentation (written by Icemining.ca): https://medium.com/icemining-guides/how-to-mine-mwc-and-withdraw-to-a-cli-wallet-any-http-listener-c623419e0910

> Am trying to Mine MWC on Icemining but it takes Cuckarood31 instead Cuckarood29

This is totally ok - MWC can be mined by Cuckarood29 and Cuckatoo31, RainbowMiner will choose, which is more profitable.
