### ISSUE TITLE
MRR set up

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#901]
I've setup my rig on MRR. From the documentation, it says

> All rigs will be automatically set to status "online", at MiningRigRentals and rest idle within RainbowMiner.

But, I see the rig is shown as offline.

Should I use MRR username or worker name in pool config?

Anyone can help me with the set up?

**Comment by RainbowMiner** [comment]
I can help :)
For MiningRigRentals, there are three values to set in pools.config.txt:
```
    "API_Key": "<your MRR API key>",
    "API_Secret": "<your MRR API secret>",
    "User": "<your MRR username>",
```

Then, if you have setup a rig on the miningrigrentals.com website, do not forget to edit the description and add `[<your RainbowMiner workername>]` 

E.g. if your worker is named 'Rainbowminer1', make it look like `[Rainbowminer1]`

**Comment by astronyu** [comment]
Thanks, one last thing...what do you meant by <your RainbowMiner workername>?

**Comment by astronyu** [comment]
Thank you. Have edited the description on MRR, waiting for the status to change to Online.

**Comment by RainbowMiner** [comment]
> While the rig isn't rented, does the MRR page shows current hashrate of the rig?

No, it just shows zero hashrate, but "Online".

**Comment by astronyu** [comment]
> 
> 
> > While the rig isn't rented, does the MRR page shows current hashrate of the rig?
> 
> No, it just shows zero hashrate, but "Online".

@RainbowMiner , I took off my rig for a few hours while it is still being rented on MRR. Had to replace one of the card's riser. The rig is now on but MRR status still showing offline. Is there something else that need to be done to get it shown as online again so that it can continue mining for the renter?

**Comment by RainbowMiner** [comment]
> Is there something else that need to be done to get it shown as online again so that it can continue mining for the renter?

Normally, not. It should come back online. If it doesn't maybe verify, that your windows system clock isn't off.

**Comment by astronyu** [comment]
That is weird. The clock is fine though.
On MRR, both rig status and renter's pool were shown as offline.
Usually, if the renter's pool shown as offline, my rig status still showing online.

**Comment by astronyu** [comment]
@RainbowMiner is there a way to see the pool's difficulty?
