### ISSUE TITLE
Had a lot of crashes

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#902]
The mining continues but when I checked activity tab, seems there are a lot of crashes going on.
I'm not sure what is going on.

[debug_2020-03-04.zip](https://github.com/RainbowMiner/RainbowMiner/files/4285742/debug_2020-03-04.zip)

![rbminer crashes](https://user-images.githubusercontent.com/3217740/75855161-99cad400-5e2c-11ea-9d75-d1e956400fbf.PNG)

**Comment by RainbowMiner** [comment]
It's the dual mining of Ethash and Eaglesong with NBminer, that causes the trouble.
I would reduce memory overclocking for this miner a bit.
Actually, are you overclocking this rig? If yes, you might want to use the RainbowMiner build-in OCprofiles to optimize your results.

**Comment by astronyu** [comment]
Yes, I overclocking the rig. I'm planning to use the build-in OC profile but not sure where to start.
Although, looking at the stats, seems like RBMiner automatically adjusts the base and memory clock depends on what are being mining.

**Comment by astronyu** [comment]
[debug_2020-03-04.zip](https://github.com/RainbowMiner/RainbowMiner/files/4286297/debug_2020-03-04.zip)

This is the latest crash while mining ethash using phoenix miner.

**Comment by RainbowMiner** [comment]
It's easy to start:
1. make 100% sure you have set "CUDA Force P2-State" to "Off", using `.\Includes\NvidiaProfileInspector\nvidiaProfileInspector.exe`
2. edit config.txt and set `"EnableOCProfiles": "1",`
3. now check your overclocking settings in ocprofiles.config.txt. Although you may add as many profiles, as you like, RainbowMiner already comes with a default set of "Profile1" .. "Profile5" - many algorithms are already tied to those, so I recommend you use them.
If you feel a bit unsafe, when editing json files directly, I recommend you use "Setup.bat" and go to OCProfiles.

These will be the presets, RainbowMiner is using for your rig (there may be more entries in your ocprofiles.config.txt, but these are the essential ones). Make sure, to check if these values are ok for your GPUs, before activating "EnableOCProfiles"
```
{
    "Profile1-GTX10606GB": {
      "PowerLimit": 0,
      "ThermalLimit": 0,
      "MemoryClockBoost": "*",
      "CoreClockBoost": "*",
      "LockVoltagePoint": "*"
    },
    "Profile2-GTX10606GB": {
      "PowerLimit": 80,
      "ThermalLimit": 0,
      "MemoryClockBoost": "300",
      "CoreClockBoost": "100",
      "LockVoltagePoint": "*"
    },
    "Profile3-GTX10606GB": {
      "PowerLimit": 80,
      "ThermalLimit": 0,
      "MemoryClockBoost": "150",
      "CoreClockBoost": "100",
      "LockVoltagePoint": "*"
    },
    "Profile4-GTX10606GB": {
      "PowerLimit": 80,
      "ThermalLimit": 0,
      "MemoryClockBoost": "-500",
      "CoreClockBoost": "100",
      "LockVoltagePoint": "*"
    },
    "Profile5-GTX10606GB": {
      "PowerLimit": 80,
      "ThermalLimit": 0,
      "MemoryClockBoost": "250",
      "CoreClockBoost": "100",
      "LockVoltagePoint": "*"
    }
}
```

See, how the entries are structured?
Look into algorithms.config.txt to find out, which algorithms are bound to which profile.

- Profile 1: no oc (e.g. +0/+0)
- Profile 2: max. core / max. memory oc - used for most algorithm/miners
- Profile 3: max. core / half memory oc - used for some sensible algorithms/miners
- Profile 4: max. core / low memory oc - used for x16 and algorithms, that do not need memory oc
- Profile 5: max. core / reduced memory oc - used for some dual mining algorithms

In you case, I would bind "Profile5" to the NBminer's Ethash-Eaglesong in miners.config.txt

In miners.config.txt, find "NBminer-GTX10606GB" section and add "Profile5" to the matching algorithm section:
```
    {
      "MainAlgorithm": "Ethash",
      "SecondaryAlgorithm": "Eaglesong",
      "Params": "",
      "MSIAprofile": "",
      "OCprofile": "Profile5",
      "Difficulty": "",
      "Penalty": "",
      "Disable": "0",
      "Intensity": ""
    },
```

**Comment by astronyu** [comment]
Should I re-benchmark all miners again after changing overclock?

**Comment by astronyu** [comment]
> In miners.config.txt, find "NBminer-GTX10606GB" section and add "Profile5" to the matching algorithm section:

Did that but still showing using profile 2 though.

MiniZ is using profile 5

**Comment by astronyu** [comment]
@RainbowMiner , I have miner for MMR crashing a lot. Is it possible to know what is the problem whether it is my rig or the miner?
[debug_2020-03-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/4290792/debug_2020-03-05.zip)

**Comment by RainbowMiner** [comment]
> RBMiner shows sometimes the miner stopped mining MMR and started mining others. I'm not sure if this is caused by my rig or caused by renter's pool.

In 99% of all cases, it's a renter's pool issue. In that case, RainbowMiner uses failover to standard operation for 15 minutes before it retries to connect to MRR. That way, you do not loose mining time.

Anyway, I will check your debug file, just to be sure there isn't a miner crashing.

**Comment by RainbowMiner** [comment]
```
CUDA error in CudaProgram.cu:456 : unspecified launch failure (719)
GPU3 search error: unspecified launch failure
CUDA error in CudaProgram.cu:456 : unspecified launch failure (719)
GPU5 search error: unspecified launch failure
CUDA error in CudaProgram.cu:456 : unspecified launch failure (719)
GPU6 search error: unspecified launch failure
CUDA error in CudaProgram.cu:456 : unspecified launch failure (719)
GPU4 search error: unspecified launch failure
CUDA error in CudaProgram.cu:456 : unspecified launch failure (719)
GPU1 search error: unspecified launch failure
```

.. this looks pretty much like the GPUs run into trouble while running Phoenix miner. This happens, if you are overclocking too much for Ethash mining. Try a reduced profile, like Profile 5, and double-check, that you have "CUDA Force P2-State" set to "Off".

**Comment by astronyu** [comment]
Hi, in RBminer dashboard, why is it sometimes it is showing 

null % | NaN W for the fan and power?

**Comment by astronyu** [comment]
@RainbowMiner can you help me debug? Been seeing a lot of crashes involving NBMiner on Ethash,Blake2bSHA3.
[debug_2020-03-22.zip](https://github.com/RainbowMiner/RainbowMiner/files/4364398/debug_2020-03-22.zip)

**Comment by RainbowMiner** [comment]
Yes, I had these, too. There are two factors, that often crash the miner:
- first, it turned out, that the NBminer dual mining reacts very sensitive to memory overclocking. I am currently only 50% of max. memory overclocking (it's Profile3, in my ocprofiles)
- second, there are times, where the 6Block pool fails to respond. You could eventually switch to F2pool. I am currently staying with 6Block and hope, that the episodes will be short lived.

**Comment by astronyu** [comment]
I see, in that case I'll set it to profile3 as well and see if that would take care of it.
I also have F2Pool set up in the config but never once I saw the script went to mine on it though.

**Comment by astronyu** [comment]
One thing that I noticed is that the crashed miner always when it dual mining MPH and 6Block while dual mining Nicehash, 6Block ran just fine.

**Comment by RainbowMiner** [comment]
Oh, that might hint us into the right direction. I will check the MPH ethash mining with NBminer

**Comment by RainbowMiner** [comment]
It is a regex bug in NBminer. I have started an issue at their  github repo: https://github.com/NebuTech/NBMiner/issues/137
The dual mining will be temp. disabled for MPH.

**Comment by astronyu** [comment]
@RainbowMiner , sorry for troubling you again. Could you decipher this debug and tell me what is wrong with it? NBMiner and Ethminer crashing almost every time. 
[debug_2020-03-24.zip](https://github.com/RainbowMiner/RainbowMiner/files/4371977/debug_2020-03-24.zip)

**Comment by RainbowMiner** [comment]
No trouble, at all. Thank you for reporting. I'll see, what I can find in the debug files.

**Comment by astronyu** [comment]
One more thing, is this string correct in Ethminer?
`stratum2+tcp://astronyu%2eBLACKBLIZZARD1:x@asia.ethash-hub.miningpoolhub.com:17020`

That "astronyu%2eBLACKBLIZZARD1" instead of astronyu.BLACKBLIZZARD1

**Comment by RainbowMiner** [comment]
This string is totally ok.
