### ISSUE TITLE
Could not execute \NVSMI\nvidia-smi.exe

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#905]
WARNING: Could not execute C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe --query-gpu=index,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,pstate,clocks.current.graphics,clocks.current.memory,power.max_limit,power.default_limit --format=csv,noheader,nounits: Exception calling "Start" with "0" argument(s): "The file or directory is corrupted and unreadable"

>> THIS was fixed by reinstalling the driver. (using lite version as recommended)

WARNING: Invalid MSIAprofile for NBminer-GTX10606GB-Ethash-Eaglesong in miners.config.txt: "Profile5" (empty or 1-5 allowed, only)

>> THIS wasn't fixed. Tried "Profile5", "5" but still showing the error. Reverted default and error gone.

**Comment by RainbowMiner** [comment]
> WARNING: Invalid MSIAprofile for NBminer-GTX10606GB-Ethash-Eaglesong in miners.config.txt: "Profile5" (empty or 1-5 allowed, only)

There are two separate parameters. "MSIAprofile" is the profile number 1 to 5, in case you are using MSI Afterburner for overclocking, the other is for the build-in OCprofiles.

Use the "OCprofile", in your case.

```
      "MSIAprofile": "",
      "OCprofile": "Profile5",
```

**Comment by RainbowMiner** [comment]
> Exception calling "Start" with "0" argument(s): "The file or directory is corrupted and unreadable"

If this happens, the nvidia-smi.exe, that comes with the Nvidia drivers, is damaged. There is a quick fix: I have packed a nvidia-smi.exe, together with RainbowMiner. To force RainbowMiner to use this, just delete the damaged Nvidia `C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe`

RainbowMiner will automatically use our version.
