### ISSUE TITLE
Power price in setup page

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#907]
Please could the power price be added to the setup page so that it can be changed using the localhost? UK energy prices are currently trending down and I'm switching tariff every month, so it would be nice to have it in the setup page.

**Comment by RainbowMiner** [comment]
Good idea. Done :)

**Comment by samdave123** [comment]
Please can you enable up to 8 decimal places? Currently I cannot enter in the full power price without opening the config file.

**Comment by RainbowMiner** [comment]
Yes. Done.
