### ISSUE TITLE
Percentage offset added directly to miner power consumption

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#908]
Please could you add the % offset directly to the miner power benchmark so that it's factored into the profit-switcher?

For example, if NBMiner Ethash benches at 500W, then a 10% offset will apply to set this to 600W and then the profit-switcher will calculate the profitability based on the total power consumption. If another algorithm is then 300W, a 10% offset will set this to 330W.

Having this apply directly to algorithms will enable my mining rig to more accurately calculate the most profitable miner to switch to. I believe currently the % offset is just visual and has no statistical function on the profit-switching?

**Comment by samdave123** [comment]
With the recent drop in crypto prices, I'm having to manually disable high power algos so my rig will switch to more profitable lower power algos. This is because the % offset isn't being included in the miner power value. I really want to keep this all automated, so please could this be implemented soon?

**Comment by RainbowMiner** [comment]
Ok, I'll find a way.

**Comment by samdave123** [comment]
Just take the offset (in my case I find 16% to be a pretty accurate multiplier when checking against my smartplug) and add multiply the benchmarked stats by it.

**Comment by samdave123** [comment]
The other advantage of this enhancement is it will discourage RBM from using high-power algos, which will become increasingly important as we get towards summer.

**Comment by Nickfost** [comment]
bump

**Comment by RainbowMiner** [comment]
> bump

Thank you! I have implemented this, now.

**Comment by samdave123** [comment]
Super excited for this one, thank you! My only concern is whether the implementation is going to make benchmarks incomparable between rigs? It's useful to see others' benchmarks to see what other models of GPUs can get and what people are able to get out of the same GPUs. I'm not sure how you've implemented this, but will it be a problem?

**Comment by samdave123** [comment]
I just read the code, and I think this is implemented at the profit-switching level without editing the benchmarks themselves, is that right?

**Comment by RainbowMiner** [comment]
Yes, it's "non-invasive", so all benchmarks remain intact.
