### ISSUE TITLE
Idle Detection

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#909]
Specifically in Linux, I was wondering if you could please tell me how idle detection is implemented to only mine when idle?

I have a very specific use case where I would like to keep my GPUs available for machine learning tasks that may arrive at any random time. Ideally I would like rainbow miner to detect when work is received and pause mining until the job is finished.

Does rainbow miner detect activity on a process level or is it base on say, mouse movement? If the latter, please could a system of detecting load on the GPU be implemented?

**Comment by RainbowMiner** [comment]
It is detecting mouse and keyboard events. I will thinking about some alternative method.

**Comment by Nickfost** [comment]
Hey @acos0874 use the local web API to pause when you need to use the GPUs
