### ISSUE TITLE
[Zergpool] when mining Verushash and using BCH for Autoexchange, the miner doesn't show up on Zergpool website

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#910]
[Zergpool] when mining Verushash and using BCH for Autoexchange, the miner doesn't show up on Zergpool website.  It also seems to eventually stop mining Verushash for good.
[debug_2020-03-06 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/4300577/debug_2020-03-06.1.zip)

**Comment by RainbowMiner** [comment]
That's weird - I will check this.
