### ISSUE TITLE
NVIDIA driver

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#911]
@RainbowMiner , is the 441 version the recommended driver we could use or is it safe to upgrade the driver to the latest (debloated version)?

**Comment by RainbowMiner** [comment]
The newest versions have problems with some of the major miners. So, yes, the 441 (debloated) is the strongly recommended version, currently.

**Comment by astronyu** [comment]
I changed my cpu to Ryzen 3 2200G recently and that causes me to reinstall drivers as it comes with Vega 8. Apparently, installing the vega driver is fine but when I reinstall the nvidia 441 driver it makes windows setting crashes. I mean, I can't open settings page, or any windows pref panes.

**Comment by RainbowMiner** [comment]
Combining AMD and Nvidia drivers, side by side, can be very tricky. I think, the debloated drivers might eventually be incompatible in a combi rig. Try to install the older, but original Nvidia drivers.

**Comment by RainbowMiner** [comment]
Eventually you have to reinstall all display drivers (remove with DDU, first). Try to install AMD first, then Nvidia. If that doesn't work out, try it the other way around.

**Comment by astronyu** [comment]
That's how I did it.

DDU Nvidia and AMD.
Install AMD drivers
Restart - all works fine
Install NVIDIA 441.41 drivers
Restart - issues with windows pref panes.

Tried repeated the step above but with NVIDIA 441.66 just to test, issue were gone BUT miners crashed. Probably will try older driver too, after this mining rental is done.

**Comment by astronyu** [comment]
@RainbowMiner does this error related to unsuitable driver?

`WARNING: Stat file (Phoenix-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05_Ethash_HashRate) was not updated because the value 0  H is outside fault tolerance 13.11 MH to 249.09 MH.`

**Comment by RainbowMiner** [comment]
No, that message is normally related to a slow startup of the miner. If it repeats round by round, it might be too many rejected shares or a failing pool.

**Comment by astronyu** [comment]
Understood thanks.
I'm experimenting with different driver now as the 441.41 still gave me issues with Windows pref pane. Can't stand it as I can't remote desktop into it.

Currently running 442.01 and it seems stable.

**Comment by RainbowMiner** [comment]
Thank you very much for doing those tests!
Did you test the debloated 442.19 as well?

**Comment by astronyu** [comment]
No I didn't. I was trying to get a driver that gave me less issue ;p.
The 442.01 seems ok at the moment so I stopped there.
