### ISSUE TITLE
Tecracoin..???? super profitable.??

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#914]
Now that it is on MTP..
suddenly RBM says it is super profitable 
but there are no exchanges for it

please look into the issue

**Comment by RainbowMiner** [comment]
Sure, I will look into it asap

**Comment by RainbowMiner** [comment]
Here are the facts, regarding TCR (TecraCoin):
- it is an ICO and not yet publicly listed https://icobench.com/ico/tecracoin
- the current price is fixed at the pre-ICO price of USD 0.75
- at current BTC/USD ratio, that results in aprox. 0,14mBTC per TCR

**Conclusion:** if you believe in the TecraCoin project, you might consider mining some TCR. Anyway, be aware, that the price/profitability is only virtual, currently. It might be a hit and TCR could be traded on many exchanges with prices, higher than the pre-ICO. But if the project fails completely, TCR might never hit any exchange, or if it fails partly, the future prices might as well be lower than the pre-ICO price of USD 0.75

**Comment by saroshpatel09** [comment]
Wow
So I can continue to mine it ?

**Comment by RainbowMiner** [comment]
Sure, but I do recommend extensive research on the project, first. Put everything on trail, team, idea, financing, etc.

**Comment by saroshpatel09** [comment]
Seems good enuff bud what's your take on it
