### ISSUE TITLE
Connected but 0 Hash rate.

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#916]
One on my rental mining Eth using TTminer. In ttminer notepad, I see that mining starts and received jobs but 0 H/s. It's been like that until rainbow miner switched to my own pool before retrying.

What might causing this?

**Comment by astronyu** [comment]
[debug_2020-03-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/4343685/debug_2020-03-17.zip)

Debug file attached.

**Comment by RainbowMiner** [comment]
That looks pretty much like a renter's pool issue. I have experienced this before, too. In my case, I could solve this by temporarily forcing "Ethminer" (I simply added a very high penalty, like 25, on all better Ethash miners in miners.config.txt for the time of the rental).

Give it a try - if this doesn't help, contact the renter and complain about the pool not working.

**Comment by astronyu** [comment]
Yeah, I did told the renter about this, maybe he changed pool but afterwards I just rebooted pc and rbminer uses Phoenix to mine without problem. Although not sure why rbminer shows it mining constantly at 136MH/s but on MRR it goes up and down and sometimes 0 hashes. Maybe still pool issue.

**Comment by RainbowMiner** [comment]
> It would be cool if rbminer has a public link that can show status of mining and perhaps history of mining when rented. :p

Ahh! Now I understand the necessity of that! Thank you for clarification. I'll add a link asap.

**Comment by RainbowMiner** [comment]
>  but on MRR it goes up and down and sometimes 0 hashes

That is because of the accepted shares count. MRR simply counts the accepted/rejected shares and calculates an aprox. hashrate out of it. If difficulty is high, it might take a lot of time to find a share - if found, MRR jumps up. During the time-to-find, it moves down.

**Comment by astronyu** [comment]
I see, thanks for pointing that out. I guess that's the reason it is recommended to advertised hashrates about 5% lower than being shown on rbminer.

**Comment by RainbowMiner** [comment]
That's especially true, if you get a short rental period. If it is long enough (say 6+ hours), it will average out.

**Comment by astronyu** [comment]
It happened today and when it happened it will also says something in the line on GPU#00#01#02#03#04#05 disabled before retrying. 

Checked task manager and it shows 100% cpu usage under Windows Command Processor where there are a couple of nvidia inspector running together with nvidia smi and a few others.

Had to restart the rig and only then it could mine correctly giving me hash rate. I believe still with the same pool as renter did not made any changes.

**Comment by RainbowMiner** [comment]
Wow, that really sound like some miner has major trouble with the current Nvidia drivers! Do you remember, which miner has been running, during the crash? Eventually disable TTminer in config.txt ("ExcludeMinerName")

**Comment by astronyu** [comment]
From the log, I think all miners and not just these two below giving out issue before I rebooted the rig.

`WARNING: Stat file (Ethminer-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05_Ethash_HashRate) was not updated because the value 0  H is outside fault tolerance 13.45 MH to 255.53 MH.
WARNING: Miner Ethminer-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05 mining Ethash on pool MiningRigRentals temporarily disabled.`

`Waiting 52s until next run: E[x]it, [R]estart, [B]alance update, [S]kip SP, [W]D reset, [C]onfiguration, [V]erbose, [P]ause
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:20500""
PS>TerminatingError(ConvertFrom-Json): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'InputObject' because it is null."
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:20500""
PS>TerminatingError(ConvertFrom-Json): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'InputObject' because it is null."
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:20500""
PS>TerminatingError(ConvertFrom-Json): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'InputObject' because it is null."
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:20500""
PS>TerminatingError(ConvertFrom-Json): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'InputObject' because it is null."
Finished waiting - starting next run

WARNING: Stat file (ClaymoreDual-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05_Ethash_HashRate) was not updated because the value 0  H is outside fault tolerance 13.54 MH to 257.29 MH.
WARNING: Miner ClaymoreDual-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05 mining Ethash on pool MiningRigRentals temporarily disabled.`

**Comment by RainbowMiner** [comment]
> WARNING: Stat file (Ethminer-GPU#00-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05_Ethash_HashRate) was not updated because the value 0 H is outside fault tolerance

.. this message appears, if a miner has crashed so badly, that it is running, but cannot be contacted, anymore. I think, your problem might be due to one miner, that crashed so badly, that it could not be killed nor contained, thus starting a cascade of crashes of all subsequent miner/programs. 

Are you using "-strap" on ClaymoreDual, eventually? This strapping is known to cause really, really bad lockups (that's why I do not enable it by default in RainbowMiner).

If you find the time and create a new Debug file, I can have a deeper look on what has happened exactly.

**Comment by astronyu** [comment]
I didn't use "-strap" nor I knew about it. Everything was ran default apart from turning on OCProfiles.
Here is new debug file.
[debug_2020-03-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/4349814/debug_2020-03-18.zip)
