### ISSUE TITLE
claymore strap option

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#917]
Hi,

Where do I enable the strap option in claymore
attached is the file please tell me if it is done correctly.

and if it is done correctly then why is it not accepting the strap option
[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4344444/miners.config.txt)

**Comment by RainbowMiner** [comment]
Actually, your "-strap 4" is totally correct. It should apply. If you are unsure, please upload a Debug file and I will have a closer look.

**Comment by saroshpatel09** [comment]
It is not loading bro that's y I sent u the file
