### ISSUE TITLE
XTNC on monero Ocean

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#918]
I am unable to get the pool to mine XTNC as it says use 95 character wallet.
then it says invalid login

**Comment by saroshpatel09** [comment]
![Annotation 2020-03-18 083354](https://user-images.githubusercontent.com/32984054/76921138-427c3780-68f3-11ea-81aa-dd32b34829e2.png)

**Comment by RainbowMiner** [comment]
This pool needs a valid XMR wallet and an email address as "Password" - it is an Autoexchange pool

**Comment by saroshpatel09** [comment]
buddy
the miner just dropped the 1660ti from the mining setup

it benches but just doesnt run at all

miner keeps on crashing
