### ISSUE TITLE
MiniZ Equihash (192,7) crash

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#919]
Miner won't run, error:
"Cannot read health status! (is libnvidia-ml.so installed?): No such file or directory"

Nvidia Driver Version v431.68

**Comment by RainbowMiner** [comment]
Is this on Windows? If yes, is it sure, that it doesn't start at all?

**Comment by samdave123** [comment]
> 
> 
> Is this on Windows? If yes, is it sure, that it doesn't start at all?

Yes that's exactly right. If the miner doesn't work on Windows, why does it have a Windows version and why is it included in RBM?

**Comment by RainbowMiner** [comment]
Actually, it works pretty good in Windows. So that's why I am wondering. Could you create a Debug file, so that I can have a closer look?

**Comment by RainbowMiner** [comment]
> "Cannot read health status! (is libnvidia-ml.so installed?): No such file or directory"

I have this warning, too. But the miner runs fine.

**Comment by samdave123** [comment]
I think it might be an issue with my rig. I'm also getting this error in T-rex X25x:

"03:24:47 ERROR: Can't start miner, GPU index 6 is not allowed, total devs: 6
20200318 03:24:47 T-Rex finished"

**Comment by RainbowMiner** [comment]
Yes, that sounds like a GPU failure. Try the following steps:
First - reset the Nvidia drivers: just run `RestartDisplayDriversNvidia.bat`
Second - power down the rig completely, then restart
Third - check if "Force P2-Cuda State" is set to Off

**Comment by RainbowMiner** [comment]
Eventually check or connections and consider replacing the riser card of that GPU.

**Comment by samdave123** [comment]
I'll close this one, as it's probably an issue with my rig and not RBM. Thanks for your help.
