### ISSUE TITLE
Issue: Mining Eu when US is selected still

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#92]
I have selected US again yet it is benching all EU.

![image](https://user-images.githubusercontent.com/42227809/44970063-c08d0f00-af04-11e8-91dd-aca766ea03bc.png)
[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2344352/config.txt)

**Comment by RainbowMiner** [comment]
Is this happening at all pools, or only at MiningPoolHub?

**Comment by RainbowMiner** [comment]
I fixed it. We now have much better region checking.
RBM
