### ISSUE TITLE
f2pool connection error

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#922]
getting a continuous stratum connection failed message in f2pool raven coin

**Comment by saroshpatel09** [comment]
sorry its stratum authentication failed

**Comment by RainbowMiner** [comment]
I'll check asap. Thank you for reporting this.

**Comment by RainbowMiner** [comment]
I have checked the RVN/X16rv2 mining on F2pool and it works. 
Did you use a valid RVN wallet address? Do not use your F2pool username for ravencoin.
