### ISSUE TITLE
miner not benching

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#924]
My TT miner is benching zano and now not stopping so that other miners can bench too

It is hanging and crashing all other miners

If one miner is benching it just doesn't stop

**Comment by RainbowMiner** [comment]
> My TT miner is benching zano and now not stopping so that other miners can bench too

This is considered very bad behavior of a miner. Eventually consider to completely disable TTminer on that rig (put it on "ExcludeMinerName" list in config.txt)

**Comment by saroshpatel09** [comment]
Removed 1 1660ti and now running nicely

**Comment by saroshpatel09** [comment]
this has me perplexed totally
as the total wattage i have is 2600W and just 6 cards
the moment i add the 7th it goes for a toss
