### ISSUE TITLE
ETHASHPOOL

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#925]
Hi,

When mining to Ethashpool it is mining to my ETC wallet and not the useraddress which has been specified in the pools.config.txt file

    "EthashPool":  {
                       "ETH":  "Saroshp09",
                       "ETH-Params":  "",
                       "ETC":  "Saroshp09",
                       "ETC-Params":  "",
                       "ETP":  "Saroshp09",
                       "ETP-Params":  "",
                       "GRIN":  "Saroshp09",
                       "GRIN-Params":  "",
                       "Worker":  "$WorkerName",
                       "Penalty":  0,
                       "Algorithm":  "",
                       "ExcludeAlgorithm":  "",
                       "CoinName":  "",
                       "ExcludeCoin":  "",
                       "CoinSymbol":  "",
                       "ExcludeCoinSymbol":  "",
                       "MinerName":  "",
                       "ExcludeMinerName":  "",
                       "FocusWallet":  "",
                       "AllowZero":  "0",
                       "EnableAutoCoin":  "0",
                       "EnablePostBlockMining":  "0",
                       "CoinSymbolPBM":  "",
                       "DataWindow":  "",
                       "StatAverage":  "",
                       "MaxMarginOfError":  "100",
                       "SwitchingHysteresis":  ""
                   },

Please have this checked out

**Comment by saroshpatel09** [comment]
AND STAY SAFE AND SECURE

**Comment by RainbowMiner** [comment]
> AND STAY SAFE AND SECURE

You too! Stay home!
