### ISSUE TITLE
MoneroOcean miner

### ISSUE THREAD

**Issue by Adiuk** [RainbowMiner/RainbowMiner#926]
Will you be adding a miner for auto switch at MoneroOcean? I can connect fine but only using gminer on XWP at the moment or is there something I need to set up?

**Comment by RainbowMiner** [comment]
RainbowMiner is automatically doing profit switching with all available algorithm, already. For Nvidia setup, XTNC mining with Cuckaroo29s is currently the most profitable. You can lookup the pools data and profitability for all the MoneroOcean algorithms here: http://localhost:4000/allpools.html

**Comment by Adiuk** [comment]
Thanks for the reply. I will assume then XWP was most profitable yesterday every time it connected, I don’t appear to have anything related to XTNC, also noticed I am connecting to the US ports is there a way to change it to connect to EU. Thanks

**Comment by RainbowMiner** [comment]
> also noticed I am connecting to the US ports is there a way to change it to connect to EU.

Here is what is written in their FAQ:

> We recommend using "gulf.moneroocean.stream" as primary mining address because 1) it will direct you to the closest server with the lowest latency (and this is the most important thing to consider) and 2) it will automatically redirect your miner to another server if the nearest one goes down for some reason. Region specific pool nodes like "de.moneroocean.stream", "us.moneroocean.stream" and "jp.moneroocean.stream" make sense to use as backup pool addresses.

I think, they automatically redirect the miners to the best-latency address.

**Comment by Adiuk** [comment]
Ok thanks for the help, will close and approach again if necessary.
