### ISSUE TITLE
Unable to upgrade to 4.5.4.7

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#927]
The script failed when trying to upgrade. Tried upgrading using Updater.bat (with both normal and admin rights) but it just failed the same.

It stuck at 1/3 downloading @ number of bytes processed: 96592, 1548864 etc.

**Comment by RainbowMiner** [comment]
Oh dear! Still? It might have been a short internet or github downtime.

**Comment by astronyu** [comment]
Yeah, I instead download the zip manually and replaced all the files.

**Comment by RainbowMiner** [comment]
Perfect. Yes, that is always the way to go, if the manual update fails.

**Comment by astronyu** [comment]
@RainbowMiner got this on latest release.

Cannot find path 'D:\Miner Selection\RainbowMinerV4.5.3.9\Bin\ANY-Xmrig' because it does not exist.
+ CategoryInfo          : ObjectNotFound: (D:\Miner Selection\\u20265.3.9\Bin\ANY-Xmrig:String) [Copy-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
+ PSComputerName        : localhost

Waiting 50s until next run: E[x]it, [R]estart, [B]alance update, [S]kip SP, [W]D reset, [C]onfiguration, [V]erbose, [P]ause, [L]ock

**Comment by RainbowMiner** [comment]
Just [R]estart.
If this doesn't help, exit Rainbowminer, delete all xmrig-5.10.0-msvc*.7z downloads in folder Downloads, the start again.
 It could be, that those are corrupted, due to the same download problems, that happend during the update.

**Comment by RainbowMiner** [comment]
Just to be sure - which CUDA version are you using, currently?

**Comment by astronyu** [comment]
You mean driver version? I'm using 442.01 debloated.

Also, it gave me a waning saying download in progress, 2 miners left but at the same time multiple crashes happening.
