### ISSUE TITLE
RVN shifting To Kaapow

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#928]
Hi,

Just read up that RVN might be shifting to Kapow which is like ProgPow 
and even the test net is up can we mine test net?

**Comment by RainbowMiner** [comment]
I'll check.

**Comment by RainbowMiner** [comment]
Checked:
- added KawPOW algorithm
- connected coinsymbol RVNT to RavenCoin KawPOW testnet mining on MinerMore
- added miners KawPOWAmd & KawPOWNvidia
- updated miner Gminer to v2.04, now supporting KawPOW

**Comment by saroshpatel09** [comment]
how do we get the wallet.? and which is the testnet pool 
please do let me know

**Comment by saroshpatel09** [comment]
tried mining on minermore but the software said after updation " No Miners Available"
![Annotation 2020-04-01 005210](https://user-images.githubusercontent.com/32984054/78066701-0e088100-73b3-11ea-999d-ba3393543ee1.png)

**Comment by saroshpatel09** [comment]
bro got all up and running

but just to let you know it hashes on the testnet but wallet is the original RVN wallet.

i do have a RVNt wallet also but the miner does not recognise RVNt it catches RVN only
