### ISSUE TITLE
Miner Crash CPU-JayDDee

### ISSUE THREAD

**Issue by Miner2212** [RainbowMiner/RainbowMiner#930]
CPU-JayDDee is crashing.. In Logfile i see:
RainbowMiner/Bin/CPU-JayDDee/cpuminer-avx2: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
libcrypto in general is installed. 
Path:
./RainbowMiner/IncludesLinux/lib/libcrypto.so.1.1
System: ubunutu 16
Any hint?

**Comment by RainbowMiner** [comment]
Which Linux distro are you using? It's most likely related to Openssl

**Comment by RainbowMiner** [comment]
Eventually, there is dependancy problem with the OpenSsl libraries in Ubuntu 16. What we could try, is to recompile the cpuminer on an Ubuntu 16 machine. This could possibly fix the dependancies. 
I will try to compile one version for you to try, today. If it works out positive, I could add that version, by default.
