### ISSUE TITLE
Unable to pickup ProgPow BCI rental

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#933]
Unable to pickup ProgPow BCI MRR rental.

[debug_2020-03-31.zip](https://github.com/RainbowMiner/RainbowMiner/files/4409256/debug_2020-03-31.zip)

![image](https://user-images.githubusercontent.com/801414/78031329-46a74c80-7318-11ea-8793-2c6752e349de.png)

**Comment by paulpoco** [comment]
Added missing progpow variants.
![image](https://user-images.githubusercontent.com/801414/78031838-f41a6000-7318-11ea-9b70-b6422844981d.png)

I don't even know what ProgPow BCI is?  BCI?

**Comment by paulpoco** [comment]
[debug_2020-03-31 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/4409365/debug_2020-03-31.1.zip)
 @RainbowMiner ok it was working but it is getting messages about invalid JSON and crashed miner and failed to connect to miner.

**Comment by RainbowMiner** [comment]
Could you send me a link to your rental? Actually, ProgPOW BCI _is_ ProgPOW - I will have a closer look. Actually, what I do have experienced at MRR is, that many renters do not know the difference between the different ProgPow algorithm. The MRR ProgPow proxy is capable of BCI's ProgPow, only. This then results in permanent connection issues, of course.

> Is there a way for MRR to pickup rentals even it they are not in your list of Algos in config.txt?

Consider clearing the Algorithm parameter and make use ExcludeAlgorithm, instead.
e.g.
```
"Algorithm": "",
```
.. now all algorithm are allowed.

**Comment by RainbowMiner** [comment]
> Edit: It was missing ProgPowEthercore, picked up rental now.

Now that is weird. I got the feeling, I might have included some debug code in the current release. Let me check.

**Comment by RainbowMiner** [comment]
Oh dear, some debug code had unintentionally slipped into the current release. I had tried to connect with ProgpowEthcore over the MRR proxy.

**Comment by paulpoco** [comment]
> Could you send me a link to your rental? Actually, ProgPOW BCI _is_ ProgPOW - I will have a closer look. Actually, what I do have experienced at MRR is, that many renters do not know the difference between the different ProgPow algorithm. The MRR ProgPow proxy is capable of BCI's ProgPow, only. Using ProgPow for other coins than BCI then results in permanent connection issues, of course.
> 
> > Is there a way for MRR to pickup rentals even it they are not in your list of Algos in config.txt?
> 
> Consider clearing the Algorithm parameter and make use of ExcludeAlgorithm, instead.
> e.g.
> 
> ```
> "Algorithm": "",
> ```
> 
> .. now all algorithm are allowed.

https://www.miningrigrentals.com/rigs/145027

**Comment by paulpoco** [comment]
The MRR rental eventually caught up to 100%.
