### ISSUE TITLE
EthashPool(=TheGrinPool) C31 Error "--port"

### ISSUE THREAD

**Issue by ArSd-g** [RainbowMiner/RainbowMiner#934]
Hi,
Please correct "--port 4949" instead of "4747" for Grin-C31 mining on EthashPool
Resulting in mining but shares rejected "cant validate result"
Takes me some times to find this very simple issue :smile:

#FIX#: pass "--port 4949" parameter for C-31-EthashPool (=thegrinpool)-lolminer or whatever miner you use!

**Comment by RainbowMiner** [comment]
Oh!! Thank you for reporting this. I'll change the port asap.

**Comment by RainbowMiner** [comment]
Luckily, EthashPool request runs through the my rbminer.net proxy. I have changed the port. Your rigs should pick it up in a minute or two.
Thanks again, for telling me!
