### ISSUE TITLE
https://solopool.org/

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#936]
CAN WE HAVE THIS POOL FOR SOLO MINING CERTAIN LOW DIFFICULTY COINS

**Comment by saroshpatel09** [comment]
Saw it but how do i implement it.?

**Comment by RainbowMiner** [comment]
Either you wait for next release, or you download [SoloPool.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/SoloPool.ps1) into the `Pools` folder.

**Comment by saroshpatel09** [comment]
I do not see the pool brother.?

**Comment by saroshpatel09** [comment]
do i download the master and update ?

**Comment by RainbowMiner** [comment]
> do i download the master and update ?

Sure, that's the easy way. Download - unzip - restart. Then, after that, set the wallets in pools.config.txt

**Comment by saroshpatel09** [comment]
did that bro but it is not showing the pool in pools.config.txt so am scratching my bald head..!!!

**Comment by RainbowMiner** [comment]
Did you restart RainbowMiner? It should have created the following section in pools.config.txt.
```
  "SoloPool": {
    "ETC": "",
    "ETC-Params": "",
    "ETH": "",
    "ETH-Params": "",
    "SAFE": "",
    "SAFE-Params": "",
    "SEL": "",
    "SEL-Params": "",
    "XMR": "",
    "XMR-Params": "",
    "XWP": "",
    "XWP-Params": "",
    "ZERO": "",
    "ZERO-Params": "",
    "Worker": "$WorkerName",
    "Penalty": "0",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "EnablePostBlockMining": "0",
    "CoinSymbolPBM": "",
    "DataWindow": "",
    "StatAverage": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": ""
  },
```
