### ISSUE TITLE
Enhancement: Separate stats folder CPU from Nvidia and AMD

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#94]
Hey, awesome job with breaking up the stats folder. I would like to be able to just delete nvidia benches vs cpu or amd faster. Is there any way to take it one more step and have it separate cpu, nvidia, and amd? This is great for example, wanting to only delete the nvidia benches which I am having trouble getting to keep AF settings while benching. I would love to be able to just open the nvidia folder and delete them all without having to track down each miner or worry about deleting benches for cpu or amd on accident. Time saver enhancement  ;-)

**Comment by Byrd1083** [comment]
Additionally, you could create a bench reset .bat separate for cpu bench reset, nvidia, and amd.

**Comment by RainbowMiner** [comment]
Very well possible :) I will include this.
RBM

**Comment by RainbowMiner** [comment]
Ok, done with the next release. I did change the stat file names to
AMD-..._Hashrate.txt
CPU-..._Hashrate.txt
NVIDIA-..._Hashrate.txt

and added new tools:
ResetBenchmarkAMD.bat -- clears all AMD benchmarks
ResetBenchmarkCPU.bat -- clears all CPU benchmarks
ResetBenchmarkNVIDIA.bat -- clears all NVIDIA benchmarks
