### ISSUE TITLE
maxhash.org

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#940]
I want to hash UBIQ but isnt there a miner for it.? would like this pool too

**Comment by RainbowMiner** [comment]
UBQ is mined, using Ethash with coin UBQ - Phoenix does the job, for example.

**Comment by saroshpatel09** [comment]
Have set it but pffff nothing broStay safeSent from my Samsung Galaxy smartphone.
-------- Original message --------From: RainbowMiner <notifications@github.com> Date: 03/04/2020  18:18  (GMT+05:30) To: RainbowMiner/RainbowMiner <RainbowMiner@noreply.github.com> Cc: saroshpatel09 <saroshpatel09@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RainbowMiner/RainbowMiner] maxhash.org (#940) 
UBQ is mined, using Ethash with coin UBQ - Phoenix does the job, for example.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RainbowMiner/RainbowMiner/issues/940#issuecomment-608414507",
"url": "https://github.com/RainbowMiner/RainbowMiner/issues/940#issuecomment-608414507",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
