### ISSUE TITLE
solopool Profit Figures

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#941]
Bro the miner takes solopool no issues at all

But the profit figures given are phenomenal

**Comment by RainbowMiner** [comment]
For all, or only for some of the coins?

**Comment by saroshpatel09** [comment]
Am mining only safecoin
And the profits are showing more than 4 usd a day which is phenomenal in
today's market brother

**Comment by talentoscope** [comment]
Can confirm this is still an issue with Safecoin on Solopool.
The coin isn't listed on whattomine, so I'm not entirely sure where the calculation data is coming from.
Looking at the json-returned stats on the Solopool site, it shows correctly (I think).

Let me know what you need to fix this, happy to help out if I can.
Keep up the great work!!!!

**Comment by RainbowMiner** [comment]
I'll doublecheck. Thanks for pointing this out!

**Comment by RainbowMiner** [comment]
The SAFE rate is from here:
https://coinpaprika.com/coin/safe-safe/#!exchanges

It's about 6 times higher than the rate in the Solopool API.

**Comment by talentoscope** [comment]
Oh wow. And it seems there's three exchanges with markets around that value.
Fair enough, I guess it's down to which to trust which is entire subjective.
Thanks for looking into it :)

**Comment by talentoscope** [comment]
Okay, managed to do a little more digging.

https://coinpaprika.com/coin/safe-safe/ 

is some Chinese crypto, not the official SAFECoin which is here

https://coinpaprika.com/coin/safe-safecoin/

Not sure if you're able to fix that? I can't see any references to CoinPaprika in the code.

**Comment by RainbowMiner** [comment]
Ah! That it explains it. Super! Thank you very much. Of course, I can resolve this 👍 
Expect the new numbers arrive in the next hour.

**Comment by talentoscope** [comment]
You star!
Thanks dude :)
Guess this can be closed
