### ISSUE TITLE
Pool Balance not showing all pools

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#944]
I'm trying to get all of the pools that I have a balance at to display in Pool Balances, however there are some that I can't get to show up and I'm not sure what I'm doing wrong.

My Pool Balances always shows the following: MiningPoolHub, NLpool, ZergPool, Zpool.
However, I also have balances at 6Block and Nicehash but I've never seen these pools displayed?

In my config.txt I have the following:
```
  "ShowPoolBalances": "1",
  "ShowPoolBalancesDetails": "1",
  "ShowPoolBalancesExcludedPools": "1",
```

Any thoughts on what I'm doing wrong?
[RainbowMiner_2020-04-04_16-48-30.txt](https://github.com/RainbowMiner/RainbowMiner/files/4430825/RainbowMiner_2020-04-04_16-48-30.txt)

**Comment by RainbowMiner** [comment]
Some pools give us no access via an API. 6Block is one of them. For Nicehash to show up, you will need to supply three components (you get them via the Nicehash account): API_Key, API_Secret and OrganizationID. Hint: don't forget the "-" between the numbers for the three values. These are mandatory.

**Comment by AnthonyBe** [comment]
Copy that.

Got Nicehash up and running.

Thanks again!

**Comment by rizkyaulya** [comment]
How about herominers, minerrocks and hashvault?
it was showing all balance.
but not all balance showing up

**Comment by RainbowMiner** [comment]
I will check, if their API has been changed.
