### ISSUE TITLE
Tellor

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#945]
Hi

Can we mine Tellor..?

**Comment by RainbowMiner** [comment]
Currently, not. But I have an eye on it.

**Comment by saroshpatel09** [comment]
it is doing bro with eth

Hashpool doesnt work but uupool works automatically

**Comment by saroshpatel09** [comment]
check if u can get hashpool on

**Comment by jch9678** [comment]
Isn't this sha256?

**Comment by RainbowMiner** [comment]
Tellor.io / Tributes TRB is a token based on Ethereum blockchain. We have NBminer to mine TRB on uupool and hashpool.

**Comment by jch9678** [comment]
https://miningpoolstats.stream/tellor  says it's sha256 and the high hashrate seems like it corroborates that.

**Comment by RainbowMiner** [comment]
It's something similar - they use their own "Tellor" algorithm. It's mainly of use, if you are dual-mining, together with Ethash.

**Comment by jch9678** [comment]
Gotcha, is there an AMD miner?

**Comment by RainbowMiner** [comment]
Unfortunatly, not. It's currently either ASIC or NBminer. Eventually, Gminer will come up with a solver.

**Comment by RainbowMiner** [comment]
> check if u can get hashpool on

I just noticed, our hashpool module is for hashpool.eu, not hashpool.com. Since hashpool.eu is of no big use, currently, I will swap the module for hashpool.com

**Comment by saroshpatel09** [comment]
Hashpool says invalid wallet ID but uupool takes it up smoothlySent from my Samsung Galaxy smartphone.
-------- Original message --------From: RainbowMiner <notifications@github.com> Date: 07/04/2020  21:31  (GMT+05:30) To: RainbowMiner/RainbowMiner <RainbowMiner@noreply.github.com> Cc: saroshpatel09 <saroshpatel09@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RainbowMiner/RainbowMiner] Tellor (#945) 
Tellor.io / Tributes TRB is a token based on Ethereum blockchain. We have NBminer to mine TRB on uupool and hashpool.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RainbowMiner/RainbowMiner/issues/945#issuecomment-610473155",
"url": "https://github.com/RainbowMiner/RainbowMiner/issues/945#issuecomment-610473155",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RainbowMiner** [comment]
Ok, I have replaced hashpool.eu with hashpool.com (module "Hashpool")
