### ISSUE TITLE
ETC Message on Ethashpool

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#946]
please see what to do in this

![Annotation 2020-04-08 172647](https://user-images.githubusercontent.com/32984054/78781605-32b9b580-79be-11ea-9af7-8770413bbb8b.png)

**Comment by RainbowMiner** [comment]
Good find! I will add that coin parameter to NBminer.

**Comment by saroshpatel09** [comment]
Thanks m8 stay safe hope all wellSent from my Samsung Galaxy smartphone.
-------- Original message --------From: RainbowMiner <notifications@github.com> Date: 08/04/2020  19:09  (GMT+05:30) To: RainbowMiner/RainbowMiner <RainbowMiner@noreply.github.com> Cc: saroshpatel09 <saroshpatel09@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RainbowMiner/RainbowMiner] ETC Message on Ethashpool (#946) 
Good find! I will add that coin parameter to NBminer.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RainbowMiner/RainbowMiner/issues/946#issuecomment-610965526",
"url": "https://github.com/RainbowMiner/RainbowMiner/issues/946#issuecomment-610965526",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
