### ISSUE TITLE
MoneroOcean Error

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#949]
Hey Bud,

Please see screen shot

**Comment by saroshpatel09** [comment]
![Annotation 2020-04-10 184338](https://user-images.githubusercontent.com/32984054/78993439-4ea68e00-7b5b-11ea-855b-5f1007b410ec.png)

**Comment by RainbowMiner** [comment]
This looks like a temporary pool failure.  If it doesn't resolve after some time, please report again.
