### ISSUE TITLE
Testing: AMD vega56 tests

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#95]
I'm trying to bench this AMD mixed rig and I keep getting problems with miners.

![image](https://user-images.githubusercontent.com/42227809/44995443-e394de80-af57-11e8-9322-fd556ecb7854.png)

**Comment by Byrd1083** [comment]
![image](https://user-images.githubusercontent.com/42227809/44995569-70d83300-af58-11e8-97d6-b64160d45d2b.png)

**Comment by Byrd1083** [comment]
When it runs, the mouse almost wont een move on the screen lags bad then crashs with reboot.

![image](https://user-images.githubusercontent.com/42227809/44995909-10e28c00-af5a-11e8-806f-5dc79ea0f7a2.png)

**Comment by Byrd1083** [comment]
I'm going to now just test the vega56 bench only and exclude the cpu, nvidia to see what happens.

**Comment by Byrd1083** [comment]
![image](https://user-images.githubusercontent.com/42227809/44996359-69b32400-af5c-11e8-87e2-1c96253830b2.png)

**Comment by Byrd1083** [comment]
Eminer failed

![image](https://user-images.githubusercontent.com/42227809/44996456-e34b1200-af5c-11e8-9db2-8e49fc17ba80.png)

**Comment by Byrd1083** [comment]
2 miners opened at the same time.

![image](https://user-images.githubusercontent.com/42227809/44996493-1097c000-af5d-11e8-8d1c-4b6236c60111.png)

**Comment by Byrd1083** [comment]
3rd miner opened before the last closed. I had to manually close eminer to prevent crash.

![image](https://user-images.githubusercontent.com/42227809/44996532-4341b880-af5d-11e8-9090-885119af05e8.png)

**Comment by Byrd1083** [comment]
Now benching sgminer. Posting AF just for FYI.

![image](https://user-images.githubusercontent.com/42227809/44996599-96b40680-af5d-11e8-8e68-eb562e516c33.png)

**Comment by Byrd1083** [comment]
The extra miner windows wont close manually either.

**Comment by Byrd1083** [comment]
Ya this will have to be fixed before further testing. It will just lockup. I'll stick this out with you ;-)

**Comment by Byrd1083** [comment]
![image](https://user-images.githubusercontent.com/42227809/44996772-9ff1a300-af5e-11e8-85af-f277c27d6b45.png)

**Comment by RainbowMiner** [comment]
Ok, first: disable eminer (put it into the ExcludeMiner list). This miner is not stable. I will disable it in the next release.

**Comment by Byrd1083** [comment]
Let me exclude both and rerun. I'll post results shortly.

**Comment by Byrd1083** [comment]
Sgminerk1 working out side of rainbow. Hard hang in rainbow
