### ISSUE TITLE
benching & profit ISSUES

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#951]
Hi

My 4*1070Ti shows a profit of INR 5.63 on ethash + trb
while my 1*1660Ti shows 15.93 

Isnt that incorrect.??
![1660ti](https://user-images.githubusercontent.com/32984054/79052706-05873480-7c56-11ea-900f-356f1250e475.png)
![1070ti](https://user-images.githubusercontent.com/32984054/79052709-06b86180-7c56-11ea-9160-cd05c7c176c7.png)

**Comment by RainbowMiner** [comment]
That's actually really looking weird, at first. What makes the difference, is the power cost. 
679W for the 1070tis vs. 79W for the one 1660 ti
That's factor 8.6 compared to only factor 4 better combined speed.

**Comment by saroshpatel09** [comment]
that power is for 4*1070ti bro please have a re look

**Comment by RainbowMiner** [comment]
Which power price have you set per kWh?

**Comment by saroshpatel09** [comment]
0.1153 USD per KWH ie : INR 7.95

**Comment by RainbowMiner** [comment]
Ok, let me do the math:

Cost 1660ti = 0.079 kW x 7.95 INR/kWh = 0.62 INR/h = 14.88 INR/day
Cost 4 x 1070ti = 0.679 kW x 7.95 INR/kWh = 5.4 INR/h = 129.60 INR/day

Rev per 1660ti (14.88 + 15.93)/1 = 30.81 INR/day
Rev per 1070ti (129.60 + 5.63)/4 = 33.80 INR/day

That looks perfectly normal to me.

**Comment by saroshpatel09** [comment]
But that's not what the screenshot showsSent from my Samsung Galaxy smartphone.
-------- Original message --------From: RainbowMiner <notifications@github.com> Date: 13/04/2020  11:34  (GMT+05:30) To: RainbowMiner/RainbowMiner <RainbowMiner@noreply.github.com> Cc: saroshpatel09 <saroshpatel09@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RainbowMiner/RainbowMiner] benching & profit ISSUES (#951) 
Ok, let me do the math:
Cost 1660ti = 0.079 kW x 7.95 INR/kWh = 0.62 INR/h = 14.88 INR/day
Cost 4 x 1070ti = 0.679 kW x 7.95 INR/kWh = 5.4 INR/h = 129.60 INR/day
Rev per 1660ti (14.88 + 15.93)/1 = 30.81 INR/day
Rev per 1070ti (129.60 + 5.63)/4 = 33.80 INR/day
That looks perfectly normal to me.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RainbowMiner/RainbowMiner/issues/951#issuecomment-612765790",
"url": "https://github.com/RainbowMiner/RainbowMiner/issues/951#issuecomment-612765790",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
