### ISSUE TITLE
NBMiner Issues on Eth + TRB

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#952]
Hi

Please see the attachment
thi is a constant message that the miner is outside default range

**Comment by saroshpatel09** [comment]
![NBMiner](https://user-images.githubusercontent.com/32984054/79059013-9d0a7880-7c92-11ea-9cc4-c9f320695ecf.png)

**Comment by saroshpatel09** [comment]
also please see why are there so many instances of NBMiner while the rest of the moners are running only 1 instance
![Annotation 2020-04-12 080214](https://user-images.githubusercontent.com/32984054/79059113-0939ac00-7c94-11ea-9875-0a3123e6ffd6.png)

**Comment by RainbowMiner** [comment]
The multiple NBminers are because there is one for each intensity in dual mining.

**Comment by RainbowMiner** [comment]
The constant message, on the other hand, indicates, that the current NBminer either produces too much rejected shares, or has crashed.
