### ISSUE TITLE
New Powershell Error

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#957]
I got 3 errors that I haven't seen before and wanted to see if you've encountered them.

1) Application: pwsh.exe
CoreCLR Version: 4.6.28008.1
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE67075AF3 (00007FFE66ED0000) with exit code c000001d.
----------------------------------------
2) Faulting application name: pwsh.exe, version: 6.2.3.0, time stamp: 0x5d4c83a4
Faulting module name: coreclr.dll, version: 4.6.28008.1, time stamp: 0x5d4c68b3
Exception code: 0xc000001d
Fault offset: 0x00000000001a5af3
Faulting process id: 0x1e44
Faulting application start time: 0x01d611e5eceeadb0
Faulting application path: C:\Program Files\PowerShell\6\pwsh.exe
Faulting module path: C:\Program Files\PowerShell\6\coreclr.dll
Report Id: cd39376d-b8c5-4247-a8bc-a1f09bf495b1
Faulting package full name: 
Faulting package-relative application ID: 
-----------------------------------------------------
3) Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program PowerShell Core 6 because of this error.

Program: PowerShell Core 6
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

**Comment by RainbowMiner** [comment]
This looks like a hard drive failure. Eventually try running chkcsk /f and reinstall Powershell Core 6, afterwards.
