### ISSUE TITLE
Issue: Ccminer failures

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#96]
So far ccminerpolytimus failed and ccminerspmodbitcore also. Says something about gpu 11 and a -d command issues.

2018-09-03 10:56:31 INFO:  miner CcminerPolytimos-GPU#01-GPU#02-GPU#03-GPU#04-GPU#05-GPU#06-GPU#07-GPU#08-GPU#09-GPU#10-GPU#11-GPU#12-GPU#13 closed gracefully

![image](https://user-images.githubusercontent.com/42227809/44998266-fc59c000-af68-11e8-94f2-16cb3cb871a3.png)

**Comment by Byrd1083** [comment]
CPU miner failing as well.

![image](https://user-images.githubusercontent.com/42227809/44998295-34610300-af69-11e8-962a-f2cc2015f807.png)

**Comment by RainbowMiner** [comment]
This is normal, because:
- some miner will not be able to handle more than 10 GPU.
- not all CPU miner are fitting the CPU capabilities
All of those will simply fail and be deactivated after benchmark, so no need to worry.

RBM

**Comment by Byrd1083** [comment]
![image](https://user-images.githubusercontent.com/42227809/44998380-07f9b680-af6a-11e8-9ecc-04a5c2817089.png)

**Comment by Byrd1083** [comment]
xmr-stak should work but it is failing

**Comment by RainbowMiner** [comment]
Did you run the Start.bat as Administrator?

**Comment by Byrd1083** [comment]
I have 7x.exe settings as admin rights. However, I have not been running start.bat as admin. I'll reset and rerun to see if that changes things.

**Comment by RainbowMiner** [comment]
Maybe it is related to this problem with UAC:
https://github.com/fireice-uk/xmr-stak/issues/150
