### ISSUE TITLE
4.5.5.0 Update, mining on ZCL continously and not changing to other algo

### ISSUE THREAD

**Issue by astronyu** [RainbowMiner/RainbowMiner#960]
@RainbowMiner not sure if ZCL Equihash (192,7) is the most profitable coins to mine atm or something wrong with the script. Usually the miner mines Eth on MPH or Nicehash/6Block dual but after the update it seems the miner continously mining ZCL on mph. 

On mph, ZCL is on the very bottom of the profitably list. 
[debug_2020-04-16.zip](https://github.com/RainbowMiner/RainbowMiner/files/4485694/debug_2020-04-16.zip)

**Comment by RainbowMiner** [comment]
Very strange! Eventually the MPH API's profitability numbers are off. I'll better check.

**Comment by RainbowMiner** [comment]
Ok, checked. It's bad - MPH over-estimates the ZCL profitability a lot, when mining with MiningPoolHubCoins, thus directly a coin. For short term: I will temporarily disable ZCL on MiningPoolHubCoins via rbminer.net proxy, now.

**Comment by astronyu** [comment]
Thank you. Do I need to do anything on my end or this will be kind of OTA fixed or another small updates?

**Comment by RainbowMiner** [comment]
This will be propagated to your miner, automatically within an hour or two. 
Here is the reason for that behavior. It seems, that MPH did not manage to update the blockreward value, in time: https://medium.com/@prof_crypto/zclassic-development-in-review-63f988cc1d3f .. search for "tripple halving"

**Comment by RainbowMiner** [comment]
ZCL should now be disabled on all MiningPoolHub/MiningPoolHubCoins.
Also, for the next release, I have added a temporary fix to the MPH pool modules. This will stay in place until MPH fixes their API.

**Comment by astronyu** [comment]
Thank you for your hard work.
