### ISSUE TITLE
T-Rex x16r

### ISSUE THREAD

**Issue by Adiuk** [RainbowMiner/RainbowMiner#964]
For some reason t-rex is exclusively mining exosis when x16r is most profitable, how do i change this so it just mines x16r without the mc=EXO? H ave checked miner config, params and pool settings and cant see why it is doing it.

**Comment by RainbowMiner** [comment]
It is most probably mining on ZergPool(Coins) or Zpool for some EXO coins for autoexchange. It is eventually the most profitable x16r coin, currently.
You cannot mine RVN with x16r, anymore. It is on x16rv2 and will fork to KAWPOW in may.

**Comment by RainbowMiner** [comment]
.. so if you want to mine some RVN, exclusively, enable one of the top Ravencoin pools: https://miningpoolstats.stream/ravencoin

**Comment by Adiuk** [comment]
Ok thx will just leave as is then, not bothered with RVN at the moment will see what it’s like when forked. Thanks
