### ISSUE TITLE
RBM is losing connection with the Monitor website but miners are still running

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#965]
RBM is losing connection with the Monitor website but miners are still running.

Has been like this for a day now.

[debug_2020-04-23.zip](https://github.com/RainbowMiner/RainbowMiner/files/4523013/debug_2020-04-23.zip)

Error at startup:
![Screenshot_20200423-061230_TeamViewer](https://user-images.githubusercontent.com/801414/80109169-08293a00-8532-11ea-814a-6b1560da4afa.jpg)

Edit: just checked the Monitor website and it says offline but miners are still working:
![Screenshot_20200423-071737_Chrome](https://user-images.githubusercontent.com/801414/80109741-b6cd7a80-8532-11ea-8ef4-5d0c7209fff5.jpg)

**Comment by RainbowMiner** [comment]
I have questions:
- is it normally working, and from time to time, suddenly loosing connection?
- will it be back, after some time?
- are you mining CPU, as well?

**Comment by RainbowMiner** [comment]
Could you eventually check your machine's system clock? It could be out of sync.

**Comment by paulpoco** [comment]
> I have questions:
> 
> * is it normally working, and from time to time, suddenly loosing connection?
> * will it be back, after some time?
> * are you mining CPU, as well?

It normally works just fine. 
It does come back after awhile.
I am mining CPU, doing Verushash.

**Comment by paulpoco** [comment]
> Could you eventually check your machine's system clock? It could be out of sync.

Your mean the time?  The time seems to be in sync with my cellphone time that it set by Cell network.

**Comment by paulpoco** [comment]
@RainbowMiner The main Powershell window stops updating after awhile and loses contact with  the Monitor.  The last message about updating Balance says last balance was updated 11:18 but it is now 12:52.

The miners are still running but because the main Powershell window is not updating it is not autoswitching.

Tried lower affinity but will have to try going lower.

[debug_2020-05-03.zip](https://github.com/RainbowMiner/RainbowMiner/files/4571478/debug_2020-05-03.zip)
