### ISSUE TITLE
Ethminer--Remove Buggy argument!!!

### ISSUE THREAD

**Issue by ArSd-g** [RainbowMiner/RainbowMiner#967]
Please remove opencl-plateform automatically generated, argument cant load miner idkw ......!
Suggestion: Add an option to remove RB default arguments
![Capture d'écran Deepin_zone de sélection _20200426191723](https://user-images.githubusercontent.com/42816950/80314600-c549b980-87f2-11ea-82c7-8ba287fb100d.png)
PS: before you ask: i test with several opencl-plateform number 1-4 ! :) the argument is the problem!

**Comment by RainbowMiner** [comment]
Thank you for bringing this up. I'll check asap.

**Comment by RainbowMiner** [comment]
Did you check it with number 0, too?
