### ISSUE TITLE
Issue: Mining EU when US selected

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#97]
Alright, ya are awesome. Everything is going so well now. Only thing left for me to be 100% is the mining to EU when selected US.

[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2346515/config.txt)

![image](https://user-images.githubusercontent.com/42227809/45000689-f5887880-af7b-11e8-8260-b4bdc1ba5f2a.png)

**Comment by RainbowMiner** [comment]
Wonderful :) :100:  It is already fixed in the upcoming release. I will push it soon, after some testing.
RBM

**Comment by Byrd1083** [comment]
I can wait for release. Hopefully more amd work will be done and I can do more testing for you.
