### ISSUE TITLE
K12 on Zergpool

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#970]
It looks like this is pretty popular. Please can it be added?

**Comment by naminator666** [comment]
Yes, this!

**Comment by RainbowMiner** [comment]
Isn't it already? I'll check.

**Comment by RainbowMiner** [comment]
We don't have any Nvidia miners, yet. Only CPU and AMD. Since it's already FPGA territory, I am not sure about the profitability. But nonetheless, I will search for a Nvidia miner.

**Comment by acos0874** [comment]
http://zergpool.com/site/miners?algo=k12

It looks like cryptodredge supports it.

**Comment by Cryptominer937** [comment]
Cryptodredge is being reported by blackminer FPGA's as they use random miner names.
