### ISSUE TITLE
Amd CPU 

### ISSUE THREAD

**Issue by Adiuk** [RainbowMiner/RainbowMiner#972]
Just installed new Amd 3900 X CPU. Is there anything i need to add or can do to show CPU temp, power etc on running miners and device status as it is only showing clock speed and power at 65W  which is what it used to be for my old i7 8700K therefore benchmarks are going to be wrong with wrong power consumption.

**Comment by RainbowMiner** [comment]
Eventually this CPU isn't in my database. I will push an update asap.

**Comment by Adiuk** [comment]
Ok thanks no rush.

**Comment by RainbowMiner** [comment]
Ok, I have updated the `Data\cpu-tdp.json` file, so that it should now recognize the AMD 3900 X, as well as many others.
