### ISSUE TITLE
Feature Request: Change Pool's "c="

### ISSUE THREAD

**Issue by sinnx3** [RainbowMiner/RainbowMiner#975]
Like for instance zergpool -p c=BTC be allowed to change for a specific coin OTHER than BTC.
Like I for instance want to get paid out in ETC, but the config inputs c=BTC instead of c=ETC which messes up the payout coin since zerg will convert it to BTC and pay out to ETC address due to the issue.

**Comment by ArSd-g** [comment]
not sure to understand but...did you, at least, try to add "-p c=ETC" parameter from config in miner/device/algo/ additionnal parameters?

**Comment by RainbowMiner** [comment]
This already works:
in pools.config.txt, just replace the `"BTC": "$Wallet",` with `"ETH": "$ETH",` or empty the "BTC" and add an "ETH" wallet. This works with every coin, btw.

e.g. if you have defined your ETH wallet in coins.config.txt
```
"ZergPool": {
  "BTC": "",
  "ETH": "$ETH",
...
},
```

or if you want to put your ETH wallet address directly into pools.config.txt

```
"ZergPool": {
  "BTC": "",
  "ETH": "0xyourethwalletaddress",
...
},
```

**Comment by sinnx3** [comment]
Nope, this did not fix the issue. In fact that added a whole new issue as latest RBminer says it's in an incorrect json format despite being triple checked and there's no issues in the syntax/formatting.

> This already works:
> in pools.config.txt, just replace the `"BTC": "$Wallet",` with `"ETH": "$ETH",` or empty the "BTC" and add an "ETH" wallet. This works with every coin, btw.
> 
> e.g. if you have defined your ETH wallet in coins.config.txt
> 
> ```
> "ZergPool": {
>   "BTC": "",
>   "ETH": "$ETH",
> ...
> },
> ```
> 
> or if you want to put your ETH wallet address directly into pools.config.txt
> 
> ```
> "ZergPool": {
>   "BTC": "",
>   "ETH": "0xyourethwalletaddress",
> ...
> },
> ```
