### ISSUE TITLE
Thousands in dashboard

### ISSUE THREAD

**Issue by Antoninich** [RainbowMiner/RainbowMiner#980]
Thousands are displayed incorrectly in web dashboard.
![1](https://user-images.githubusercontent.com/57628432/81254837-e43b1d80-9034-11ea-82cc-d528591a8bfb.PNG)
![2](https://user-images.githubusercontent.com/57628432/81254839-e4d3b400-9034-11ea-95b9-c7e6053c0a3e.PNG)

**Comment by RainbowMiner** [comment]
Thank you for pointing this out. I'll check it asap.

**Comment by Antoninich** [comment]
To solve the issue add to RainbowMiner.ps1:
`$culture = [System.Globalization.CultureInfo]::CreateSpecificCulture("en-US")
$culture.NumberFormat.NumberDecimalSeparator = "."
$culture.NumberFormat.NumberGroupSeparator = ""`
![12](https://user-images.githubusercontent.com/57628432/82214021-c9628600-991d-11ea-8128-b8d33d873dab.PNG)

**Comment by RainbowMiner** [comment]
Thank you :) I'll use this.
