### ISSUE TITLE
alanfox2000 repo

### ISSUE THREAD

**Issue by Antoninich** [RainbowMiner/RainbowMiner#982]
This block is not relevant. The alanfox2000 repo on Github has been removed.
![3](https://user-images.githubusercontent.com/57628432/81395534-7d009480-912c-11ea-81c4-b7f33e478d59.PNG)

**Comment by RainbowMiner** [comment]
Thank you for reporting. I'll update the readme accordingly.

**Comment by RainbowMiner** [comment]
Done. Thanks again!
