### ISSUE TITLE
RVN Estimates on 2miners

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#984]
NEvermind they seem to be accurate.

**Comment by acos0874** [comment]
Actually I just came across this pool...

https://hellominer.com/Default.aspx

0 fee PPS for a while. Can it be added if possible?

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/81401048-5dff0400-9126-11ea-96da-99df813f70ab.png)
ravenminer estimates are defo broken

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/81401262-dc5ba600-9126-11ea-8abb-2f86426cb712.png)

vs

![image](https://user-images.githubusercontent.com/42582444/81401271-e1b8f080-9126-11ea-8554-a12ccf5a0fe3.png)

**Comment by RainbowMiner** [comment]
Yea, those numbers look pretty off. I'll check asap.
