### ISSUE TITLE
Hellominer.com

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#986]
Figure I'd create a separate issue. This pool looks promising. PPS with 0% fee currently. Please can it be added?

There's also elitehash.net

**Comment by RainbowMiner** [comment]
I'll see into this.

**Comment by acos0874** [comment]
Thanks for putting this in. It looks like it's not picking up any profitability figures though.

**Comment by RainbowMiner** [comment]
Is this still an issue?

**Comment by acos0874** [comment]
No it's fixed now.

**Comment by RainbowMiner** [comment]
Perfekt :) I'll close the issue.
