### ISSUE TITLE
BTC wallet balance

### ISSUE THREAD

**Issue by Antoninich** [RainbowMiner/RainbowMiner#989]
Please add BTC wallet balance.
Example from https://btc.com/api-doc: https://chain.api.btc.com/v3/address/15urYnyeJe3gwbGJ74wcX89Tz7ZtsFDVew

**Comment by RainbowMiner** [comment]
Good idea. I'll add this.

**Comment by RainbowMiner** [comment]
Your BTC wallet(s) will be listed together with the pool balances, now.

**Comment by Antoninich** [comment]
Cool! Thanks

**Comment by AnthonyBe** [comment]
Hmm.. I really like that my BTC wallet is now displayed in Pool Balances.
I have other wallets for other currencies.

Is there a way of including these as well?

If so, would it then makes sense to separate Pool Balances and Wallet Balances in the display output, calculating those balances, and also calculating a total combined balance?

I'm thinking about pool balances as 'what you have access to' versus wallet balances as 'what you have'

**Comment by RainbowMiner** [comment]
Yes, that would be possible for most non-privacy coins. Which wallet currencies do you have in mind?

**Comment by AnthonyBe** [comment]
Thanks!  Any of the following would be great. 
ZEC, XLM, BAT, DAI, EOS, SAFE, RVN

**Comment by RainbowMiner** [comment]
I have added multiple wallets and resorted all outputs.
ZEC, XLM, SAFE, RVN, LTC, ETH
.. will add more and more over time.
