### ISSUE TITLE
issue on NH kawpow with Z-enemy 

### ISSUE THREAD

**Issue by mo35** [RainbowMiner/RainbowMiner#990]
Sometimes when on Nicehash, miner fails to create dag and just sits there with error:
"Epoch calculation failed".

This is NH issue , but other miners (trex, gminer, nbminer) just jumps over that error and continue,
z-enemy unfortunately not handling this issue very well and when it hits, mining stops completely.

posted for devs also, prolly need to disable on NH for now

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll push an update asap.

**Comment by mo35** [comment]
https://github.com/zealot-rvn/z-enemy/releases

fixed in new released version

**Comment by RainbowMiner** [comment]
Cool. I'll post an update asap.
