### ISSUE TITLE
Linux Headless

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#991]
Is it possible to run RBM on linux headless with full overclocking options? When I tried this previously it was a requirement that GNOME was running in order to get xorg and hence the coolbits overclocking option. I'd like to give it another try, but if you think it is not possible then I will not bother :D

Thanks.

**Comment by acos0874** [comment]
In other words, what is the recommended set up in linux?

**Comment by acos0874** [comment]
I had some hardware issues so needed to install Awesome Miner. The dev suggested installing hiveOS with the AM client and it did the trick. All OC capabilities working out of the box. I intend to try getting RBM up and running from the HiveOS USB stick, but before I try, can you foresee there being any problems?

**Comment by RainbowMiner** [comment]
That should work - just make sure to set `"EnableLinuxHeadless": "1",` in config.txt

**Comment by acos0874** [comment]
The setup has been working perfectly for my 1070ti rig. The steps I took were installing hiveOS, the awesome miner remote agent, then cuda toolkit.

However, when I repeat the steps on my 2070 super rig I just can't get the OCs to work. 

I've checked the config file...

1070ti rig (note how xauthority is blank but it still works"
    "EnableOCLinuxSetAllPStates": false,
    "EnableOCLinuxForcePState": true,
    "EnableLinuxHeadless": true,
    "LinuxDisplay": ":0",
    "LinuxXAuthority": "",

2070super rig:
    "EnableOCLinuxSetAllPStates": false,
    "EnableOCLinuxForcePState": true,
    "EnableLinuxHeadless": true,
    "LinuxDisplay": ":0",
    "LinuxXAuthority": "",

So they have identical settings. Here is my debug file. Please help.
[debug_2020-05-22 (1).zip](https://github.com/RainbowMiner/RainbowMiner/files/4669717/debug_2020-05-22.1.zip)

**Comment by acos0874** [comment]
Also I have tried to manually enter the xauthority path as

/run/user/1000/gdm etc...
but the gdm folder doesn't exist on either the 1070ti rig or the 2070 super rig, so I suspect this isn't the problem.

**Comment by acos0874** [comment]
Additional info: Overclocking the RTS2070 supers seems to work fine through awesome miner.

**Comment by RainbowMiner** [comment]
Thank you for the report. I'll try to find out asap

**Comment by acos0874** [comment]
Actually, you don't need to worry about it. I was just booting into linux again to see if c32 was more more profitable on the rtx2070supers, but it's not so I'll probably eventually go back to windows. Wouldn't want you doing lots of unnecessary work.
