### ISSUE TITLE
Output MiningPoolHub coins bug

### ISSUE THREAD

**Issue by Antoninich** [RainbowMiner/RainbowMiner#992]
I added pool Miningpoolhub.

In RainbowMiner_2020-05-15.txt:
```
[2020-05-15 03:46:38] WARNING: Cannot determine currency for coin () - cannot convert some balances to BTC or other currencies. 
[2020-05-15 03:46:38] WARNING: Cannot determine currency for coin (musicoin) - cannot convert some balances to BTC or other currencies. 
[2020-05-15 03:46:38] WARNING: Cannot determine currency for coin (zencash) - cannot convert some balances to BTC or other currencies. 
```

Output "https://miningpoolhub.com/index.php?page=api&action=getuserallbalances&api_key=" for my api (Note: balance zclassic and empty coin is equal, but this is bug MPH):

`{"getuserallbalances":{"version":"1.0.0","runtime":47.134876251221,"data":[{"coin":"zclassic","confirmed":0.22293497,"unconfirmed":0,"ae_confirmed":0,"ae_unconfirmed":0,"exchange":0},{"coin":"","confirmed":0.22293497,"unconfirmed":0,"ae_confirmed":0,"ae_unconfirmed":0,"exchange":0},{"coin":"musicoin","confirmed":3.08392604,"unconfirmed":0,"ae_confirmed":0,"ae_unconfirmed":0,"exchange":0},{"coin":"zencash","confirmed":0.03458358,"unconfirmed":0,"ae_confirmed":0,"ae_unconfirmed":0,"exchange":0}]}}`

In console RainbowMiner:
![10](https://user-images.githubusercontent.com/57628432/82001695-714d2a80-9664-11ea-9722-21ae577bcea7.PNG)
![7](https://user-images.githubusercontent.com/57628432/82001319-968d6900-9663-11ea-88ae-2791dab64dab.PNG)
![8](https://user-images.githubusercontent.com/57628432/82001322-9a20f000-9663-11ea-9a62-47ce5bb96527.PNG)
![9](https://user-images.githubusercontent.com/57628432/82001325-9c834a00-9663-11ea-96e2-08cb25b0cba9.PNG)

**Comment by RainbowMiner** [comment]
Thank you for reporting this. I'll post a fix for that.

**Comment by RainbowMiner** [comment]
Fixed. I'll post a new release soon.

**Comment by Antoninich** [comment]
The balance is displayed incorrectly.
![13](https://user-images.githubusercontent.com/57628432/82217285-e483c480-9922-11ea-8f3f-8ddb309a9042.PNG)
![14](https://user-images.githubusercontent.com/57628432/82217465-201e8e80-9923-11ea-99cd-2d3ff0d915f2.PNG)

How to remove the balance display for coins MAX, MUSIC, etc.?

**Comment by RainbowMiner** [comment]
The display is correct - it just shows a different value. BTC and all fiat currencies display the added value of all coins.

**Comment by RainbowMiner** [comment]
> How to remove the balance display for coins MAX, MUSIC, etc.?

This is not possible, currently. Since MPH is an autoexchange pool, all collected coins will be listed. I'll add some extra parameter, so that you can (de-)select them.

**Comment by RainbowMiner** [comment]
Now the display should be much clearer. I have separated the "Value in xxx" values from the real coin values on the Dashboard

**Comment by Antoninich** [comment]
> > How to remove the balance display for coins MAX, MUSIC, etc.?
> 
> This is not possible, currently. Since MPH is an autoexchange pool, all collected coins will be listed. I'll add some extra parameter, so that you can (de-)select them.

Coins MAX, MUSIC is trash. Please add the option to remove them from the dashboard. Thanks.

**Comment by RainbowMiner** [comment]
Ok, I'll add an option for that.

**Comment by RainbowMiner** [comment]
Done.
