### ISSUE TITLE
Option to make run as a service or in cron on ubuntu startup 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#993]
Option to make run as a service or in cron on ubuntu startup 

pls automate this for me , thankies

**Comment by itsdarklikehell** [comment]
I could/would look into this. P.m me in a few days if I've found any solutions.
One I use is making a shell script like:
`~/bin/RainbowMiner-Screen.sh`
Containing:
`#!/bin/bash
cd _PATH TO RAINBOWMINER FOLDER_
chmod +x *.sh
./install.sh -pu
./install.sh
./start-screen.sh`
This should start rainbowminer in a screen session, with Wich one can connect with `screen -r`
Then I set this script to start when x starts.

**Comment by itsdarklikehell** [comment]
after creating the `~/bin/RainbowMiner-Screen.sh` file.

creating an .desktop file in `~/.config/autostart/rainbowminer.deskop`
Containing the following:
```
[Desktop Entry]
Name=RainbowMiner
Comment=RainbowMiner
Exec=RainbowMiner-Screen.sh
Type=Application
Terminal=false
Hidden=false
```
should yield the same effect.

**Comment by RainbowMiner** [comment]
Nice! Thank you very much for the research and input!

**Comment by itsdarklikehell** [comment]
> Nice! Thank you very much for the research and input!

No problem man, I love looking into this kind of Linux things.
As long as it's open source and stuff.

**Comment by Nickfost** [comment]
I’m closing old issues to help reduce the number of open issues. Here’s a link to all of the issues I’ve opened:

[Nickfost's Issues · RainbowMiner (github.com)](https://github.com/RainbowMiner/RainbowMiner/issues?q=author%3ANickfost+is%3Aissue)
