### ISSUE TITLE
Autoexec function doesn't kill the task that it started when RBM restarts or upgrades.

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#994]
![image](https://user-images.githubusercontent.com/801414/82128202-346d5a80-976e-11ea-91cb-5e5400f5b0b1.png)

I was hoping this could be fixed so I don't get multiple running tasks that where autostarted.

I will be adding BRS 2.5.0 Burst Node and don't want that starting multiple times.

Thanks.

**Comment by RainbowMiner** [comment]
Ok, I'll have a look.

**Comment by paulpoco** [comment]
@RainbowMiner is there a way to check if the Process is already running?  And if it is then don't exec.

**Comment by RainbowMiner** [comment]
Sure, that's the direction I am looking to.

**Comment by paulpoco** [comment]
I have 3 different thing starting with the autoexec now.  Burst Miner, BitcoinHD miner, and a BRS node.
>#


"C:\Qbundle\BlagoMiner\BlagoMiner_AVX2.exe"
"C:\Users\pjb\Downloads\hdminer-20200320\hdminer\hdminer.exe"
"C:\Users\pjb\Downloads\burstcoin-2.5.0\burst.exe"

**Comment by RainbowMiner** [comment]
Implemented with commit 91d689bc51064d08f2e2bfc4e2e1296b43043247

**Comment by RainbowMiner** [comment]
I'll check this. Thank you for reporting back on this.
