### ISSUE TITLE
Kawpow is a bit funky

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#995]
![image](https://user-images.githubusercontent.com/42582444/82156940-4c300600-9876-11ea-8b32-60283fc2602e.png)

I don't know if this is just a linux thing, but I can't get nbminer or trex to work at all with kawpow on nicehash.

**Comment by acos0874** [comment]
There error in trex, is cannot get nonce for GPU.

**Comment by RainbowMiner** [comment]
Thank you for reporting - I'll check these two.
