### ISSUE TITLE
4.5.6.9 - EWBF's Eqihash CUDA miner v0.6 - ERROR: Cannot load nvml

### ISSUE THREAD

**Issue by AnthonyBe** [RainbowMiner/RainbowMiner#996]
I've just noticed the following error today with RM v4.5.6.9:

```
+-------------------------------------------------+
|         EWBF's Eqihash CUDA miner. v0.6         |
+-------------------------------------------------+
12:40:06 ERROR: Cannot load nvml.
```
The miner is crashing every single time with above error.

Logs attached.

[RainbowMiner_2020-05-18_12-39-05.txt](https://github.com/RainbowMiner/RainbowMiner/files/4641744/RainbowMiner_2020-05-18_12-39-05.txt)
[Ewbf-GPU#00-31100_2020-05-18_12-46-04.txt](https://github.com/RainbowMiner/RainbowMiner/files/4641745/Ewbf-GPU.00-31100_2020-05-18_12-46-04.txt)
[Activity_2020-05-18.txt](https://github.com/RainbowMiner/RainbowMiner/files/4641746/Activity_2020-05-18.txt)

**Comment by RainbowMiner** [comment]
This indicates either a problem with the Nvidia drivers or the `nvml.dll` is no longer in the required NVIDA path `C:\Program Files\NVIDIA Corporation\NVSMI`

**Comment by RainbowMiner** [comment]
Ok, I have added checks to RainbowMiner core, which will check for NVSMI during startup and try to install it, if it's not found.

**Comment by RainbowMiner** [comment]
If you happen to have the file `C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll` on your system, there is a good chance, that it is damaged. Look for `nvml.dll` in RainbowMiner's .\Includes folder and copy it into the `C:\Program Files\NVIDIA Corporation\NVSMI\` folder (as administrator).

**Comment by AnthonyBe** [comment]
Thanks!

The `C:\Program Files\NVIDIA Corporation\NVSMI` folder was completely empty on my PC.

I copied the `nvml.dll` from the RM `.\includes` folder and everything working smoothly again.

Odd that that folder is empty on my PC. I wonder if nVidia forgot to include it in the 445.87 installer or something..

**Comment by RainbowMiner** [comment]
> Odd that that folder is empty on my PC. I wonder if nVidia forgot to include it in the 445.87 installer or something..

In fact, newer Nvidia driver packages seem to no longer contain the nvml.dll - if you start the newest RainbowMiner release as Administrator, it will automatically check if nvml.dll exists and install it, if missing.
