### ISSUE TITLE
Daily report

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#997]
One of the features I miss from other miner management software is the ability to receive notifications when there is a crash or a problem with a miner. This means I can have the peace of mind that everything is ticking over without having to check the miner page for any issues. I was wondering if something could be implemented on RBM please? It doesn't have to be a notification as such, but something on the main page that saves me having to go to the activity view, such as "number of crashes in the past 24 hours" or even a daily email that can be set on a schedule, so for example I could get an email at 9am saying "there were 2 issues that need your attention"?

**Comment by RainbowMiner** [comment]
Very good enhancement! I'll add some report emails. Eventually we could also add something like a maximum number of crashes per hour to trigger a push message.

**Comment by RainbowMiner** [comment]
First step: I have added an additional parameter to config.txt:
- **MinerStatusMaxCrashesPerHour** = maximum allowed crashes per hour, triggers push message, if above [default=5]

**Comment by acos0874** [comment]
That's awesome!Sent from my Samsung Galaxy S9 - Powered by Three
null
